#+STARTUP: showeverything logdone
#+options: num:nil

* Interesting event

I had the opportunity to tour the St. Anthony Falls Laboratory
today.  It is a big hydrology and geophysics lab built on the
Mississippi river, at the Falls of St. Anthony (the site of the
first lock and dam on the river).  A controlled channel flows
right through the lab and is used for experiments.  I was kind
of reminded of the art from the "Les Cites Obscures" comics.  The
lab is old: it is where the lock and dam system was originally designed.
But still full of experiments.  The experiment that interested me the most
was a mock-up of a river that was made with sand, water, and
alfalfa sprouts.  Looking at it was like looking at the Mississippi
or St. Clair from a bridge... or maybe video of flying over the Amazon.
It reminded me of my interest in physical computation -- and of the
fact that sometimes the best "simulations" are done, not on computers,
but with large-scale physical objects.  My "computer" used to be
a large-screen display (blackboard), printing device (typewriter),
large disk (library books), together with wetware CPU and memory.  I
still like books, paper, and ink... but these days I spend most of my time 
working on a "real" computer.  (It really isn't so different.)
The lab visit gave me an interesting sense of perspective... science
can be like that.  --[[file:jcorneli.org][jcorneli]]
