#+STARTUP: showeverything logdone
#+options: num:nil

* from the land of many waters

So.. no internet connection in my apartment today, that was too bad, but I hope
that it is just a temporary glitch, and not a permanant "security fix".  I'm currently
writing to you from the library (using this crazy layout called "QWERTY", you might have
heard of it?).

I'll try to find some connection whereby I can do a CVS update for HDM soon, I would
like it if interested parties would check out the parser, code, documentation, etc. --
happily, by the time I upload, it may be further improved.

If we all had offices located in the same area, I would definitely stop in to blather
at you about the parser -- and I'm sure it would help the code come along.  Anyway,
it is improving (slowly)... but I do think some chit chat would help.

I feel "tongue tied" here with this computer, so I'm going to make the rest brief. 
I had the kind of funny thought recently about designing a /physical/ digital library.
This would be something somewhat different from a "computer lab", surely, but what
would it look like?  Architecture has been one of my favorite artforms for a while,
but the best I can offer are a few vague concepts about this idea.  Nice space, correct
lighting, side rooms with projectors for discussion.  No paper anywhere - but maybe
some trees growing in an indoor garden.  Of course, when the technology changed, this
building might become outdated... but it could probably still be used for some other thing.
Dig it?  It is fun to think about merging online & in-person communities (a somewhat
popular topic for discussion)... what d'ya'll think?
--[[file:jcorneli.org][jcorneli]]

: I like the digital library that appears in "Attack of the Clones", when Ben-Kenobi is looking for the Camino system. Nice space, correct lighting, and a beautiful old building. -[[file:alozano.org][alozano]]
