#+STARTUP: showeverything logdone
#+options: num:nil

I think this turned out tremendously well. Seems like we will be
"unpacking" all the ideas and connections for a while. Having the
board meeting in a week is probably really good timing. Thank you for going and being so thorough! --[[file:akrowne.org][akrowne]] 

I agree, its turned out well, or maybe we should say, has begun well,
since this unpacking process will definitely take a while.  We should
talk some about overall strategy for that.  Of course, I think I
should probably send something to everyone I said I would email... but
before I do that, let's talk some about the cast of characters and so
forth.

I'm back in MN, and nominally don't have any work until Thursday,
but a preliminary step is figuring out whether I still have that
job, and if I do have it, whether I still want it at all.  P'raps
we can talk some about that too.  Next thing for me is probably a
bath and a nap, maybe eventually some physical unpacking. --[[file:jcorneli.org][jcorneli]]

* Themes to keep thinking about

OK... Aaron and I talked last night about this stuff, and I was hoping
he would provide a triple-filtered summary of the important points.
But I suppose double filtered will do OK; and this can be revised later.

 * /Two promises: PM for research and PM for teaching./  These are
good things to talk about with math folks, because typically math
folks are interested in at least one of these things, and PM
already provides some support for these (encyclopedia, forums,
collaborations; encyclopedia, rmilson experiment) and PM can
obviously be improved in these areas.  We should continue to push in
these directions (e.g.  try to get a series of classes that do
something similar to what rmilsonn did). 

 * /Understanding the "free" model./  This seemed to me to be a very
key point.  We need to understand this backwards and forwards, because
this isse is meta to the "two promises" above;  in a way it constitutes
the biggest promise of PM (both site and project etc.).

 * /Partnerships with various organizations./  There are a variety
of "small" organizations (Project Next, math REUs as a collection,
MSRI, !PascGalois, youngmath.net, !EduWorks, New College) that we should talk to about
possible connections.

 * /Getting involved with the Math Gateway and Math DL/ -- as a partner
organization and (later) as a participant in the process.

 * /Sending a white paper to Lee Zia and NSDL about PM./ Hopefully
he can either give us money (!) or give us advice about how to
go about getting money.  

 * /Mathematical individuals./  One
thing to note is that mathematicians can always contribute content;
and if any of them are interested in talking with us about
how to make contributing content easier, then perhaps we can
work with them.  (Identifying demand is an important step, even
if money doesn't come directly.)  Some individuals may be interested
in more "technical" or "meta" contributions (e.g. graphics software).
Some individuals may have a lot of content all ready to go, but
won't want to go through the trouble of uploading it.  That works
too (but if there is a lot of material to ingest, we'll need some
machinery to help with this).  Examples of people here are
Jean Taylor, Bob Palais, and Edward "Ted" Odell.  (There are
a number of individuals I will similarly want to ping re. HDM.)

 * /Organizationally important individuals./ Of course,
I'll want to follow up with the presidents of AMS and MAA --
in part because I can, and in part because these people
could be very helpful.  But we'll have to think more about
what we want to say to them (see especially first two points
above).  

 *  /Combinations./ Things like PM, MSRI, and NDSL seem like
possible/attractive combos.  There are others.

Aaron's list (better late than never.  Note that this is only to /augment/
Joe's list, it is not an alternative for it) :

 * /Cornering the REU Market./  I think of REU as more of a market/audience
than an "organization".  From this perspective, one can recognize that there
is a deficit of "service" for this market out there.  There are plenty of 
destinations that cater to research-level practitioners, and even those that
cater just to grad students (and those who interact with them)--e.g., NDLTD.  
But what about undergrads doing research?  The outcomes of most of this work
seems to go to /dev/null.  What if instead it went to the !PlanetMath DL? 
I think there is a real opportunity here to fill a vacuum and "corner the 
market" on serving the REU community.

 * /Contributions from Individuals./  This relates to Joe's "mathematical
individuals" above.  Rather than just discussing with them where we can take 
!PlanetMath in the future, we should also make sure to try to get them involved
/now/, with the kinds of things that can be done now.  For example, having them 
contribute their teaching materials (course notes, lectures, unpublished papers)
that otherwise have no real high-audience "home".  While the utility of doing
all this might be relatively small (thought doing it a lot will certainly have
an impact), the important thing is drawing "power users" into the site.

 * /NSDL, etc. Organizational Partnerships./  I do think we should put forth a white 
paper and circulate it.  Adding up all of the above, I think we should push to
get PlanetMath supported as a virtual community for /developing mathematical
scholars/.  This capitalizes on our current strengths, plus seems to take us in 
the right direction (that which lets us evolve the site in a natural way, and takes
us where the field is most open).   Honestly, simply framing much of what we 
talked about in the NSF ALT grant proposal and in other conversations with this kind of
language may get us seen in a whole new, positive light. (See my notes from the field at [[file:2006_JMM.org][2006_JMM]] for more potential contacts/organizations.)

 * /probably more to come as soon as I'm back with my notes/.

** Discussion
Thanks, Aaron, for these comments, yes I think they do augment my points
above nicely!  Let's start work on that [[file:PlanetMath whitepaper for potential partners.org][PlanetMath whitepaper for potential partners]].  Hopefully
some draft of this can be a "supporting document" (recommended pre-reading)
for the board meeting. --[[file:jcorneli.org][jcorneli]]

* Immediate action items

We can probably email the Math Gateway people about becoming a
participating member, right away.  I don't suppose it matters who
sends this email, although maybe it would be a good idea if I did it
(for sake of continuity).  However, I'd be happy to get suggestions
about what I should say if I do send the email.

I'm also planning to emailing a few of the individuals I talked to
or heard interesting things about each day.

--[[file:jcorneli.org][jcorneli]]

I continue to think we should do this -- figure out what involvement
requires.  I guess I'll plan send the email tomorrow & will CC Aaron.

--[[file:jcorneli.org][jcorneli]]

----
[[file:2006 JMM.org][2006 JMM]]
