#+STARTUP: showeverything logdone
#+options: num:nil

I guess its Saturday.  Tired, yes.  Made a bunch of contacts.

Lee Zia.  Lead program director of NSDL!  Had a great conversation with
him.  He mentioned a big NSDL thing in April, and suggested to check
them out; said to consider networking with "eduwork".

Ion.  Math reviews.  Fun stuff; seems very much on our side.  One
of the things he mentioned was a set of conversations he had with
people some time ago, who were talking about an online math space
(something like PM), with different halls and rooms etc. -- "you want
a math MUD!" -- yes, definitely.  What PM lacks in being MUDlike,
I'd hope to see produced as part of the HDM project.

Kyle T. Siegrist, Editor of Journal of Online Mathematics and its Applications (MAA).
I think he must have been the person I talked to about the [http://www.maa.org/news/101404gateway.html Math Gateway]
and [http://www.mathdl.org MathDL].
Thinking about this site (and other similar/related stuff) makes
me interested to think about the role PM can/should play.  My thought 
(at the time) was that anything we want people to use on the
site that exists elsewhere we need to simulate.  It was interesting
to see how much the !MathDL seems to have in common with PM.
And plenty of things not in common too.  I said we'd follow up and
enquire about becoming a parter organization.  I think there
are some meetings associated.

Kathleen M. Shannon, who is working with Eirini (see yesterday) on
http://www.PascGalois.org (interesting pictures).

Michael B. Saclolo, St. Edward's University.  Literature and mathematics.

Kevin Iga (Pepperdine), who was the guy who told me about modal theory
yesterday.

I chatted a little with Paul Hildebrant, president of Zome tools.

Paul Humphries, gave an interesting talk on the philosophy of
(computer) mathematics.  I talked with him for a bit before the talk.
Interesting philosophical idea of an analogy between telescopes and
computer systems.  I mentioned my [[file:visions talk|theory.org][visions talk|theory]] of relatively homogeneous
mathematical media after the talk.  That went over well.

He cited  an unpublished MS onbuilding meaning with google that sounded
interesting. Cilibras and Vitanyi, I think.

Eric Schechter, fan of transhumanism.  This rather nicely tied
everything together.

I got a few more references that I jotted down on paper.  Will get to
that later I guess.

--[[file:jcorneli.org][jcorneli]]

----
[[file:2006 JMM.org][2006 JMM]]
