#+STARTUP: showeverything logdone
#+options: num:nil

: An object is exposed to the cognising subject from various "angles", in various aspects.
:: -- http://www.marxists.org/subject/psychology/works/lektorsky/essay_77.htm

: We can deal with rockets and dreams, but reality, what does it mean?
::  -- Curtis Mayfield, "Freddies Dead"

If you don't know about parallax you should check it out.  It means
/to wander/.  It also means, the multiple views on a single
object revealing the "imperfect" nature of perception, this according
to Plato, barker for the "world of forms."

The term is important even when we look at hyperreality as a created
thing and go so far as to view theories of reality as tools for
bending reality to suit our needs.  We define intersubjectivity to be
multiple subjectivity.  Scientific epistemology reduces to parallax.

What a change of heart that was!  And it sure took a long time, but,
then again, so does the reversal of the magnetic poles.  But all this
is preface.

/(I too have at times taken objection to the way things are
expressed.  I don't have a problem with the way things are expressed in reality, as by
occasion I may chance to learn something about it; but human understanding, and accordingly,
human expressions, are often painfully limited.
And indeed, with the fanaticism for "classic texts" -- "religious
texts" some might even say -- among mathematicans, it might
appear that mathematicians are stuck in Plato's cave hunting around in the dark for
ideal forms, and maybe even fancying that they have come
"pretty damn close."  Well, I say, that isn't very scientific.)/

Consider the mind, in its own most humble aspect, as the recipient of
data coming in through the sense organs, which it then captures,
recycles, and projects through various mirrors, evoking a picture of
reality.  An involuntary simulation, what we might call a "simulasm";
an agentless simulation, to correspond roughly to the notion of
"simulacrum", a simulation without original.

Agentless?  Really?  Perhaps not entirely so (what is an "agent"?);
the mind is in actuality somewhat more sophisticated, and having learned what
sorts of things it likes and what sorts of things it detests, here and
there the putative simulasm may show some rosy-colored tinges of
self-deception or even self-creation.

Somehow it seems important to know; does the individual have choice?
Presumably some of the most well-trodden philosophical ground out
there.  The sense that we either do or do not have choice is assumed
to be so ingrained as to be inescapable, regardless of the analytical
conclusions one comes up with.  But without even a proper definition
for this term, "choice", I don't really know how to describe my
sensations of it.  Perhaps it is a matter of degrees; a person with
$1000 of spending money could buy up to 1000 different $1 items,
whereas a person with $1 of spending money could only buy one $1 item.
Freedom, or for that matter, agency, not as an abstract state of mind,
but as a physical quality (or vector of such quantities).

For one thing, a choice is usually defined with regard to some set of
outcomes.  For example, we have been considering choices having to do
with how one understands the world.  Perhaps an instance of this sort
of choice is found when one goes to the library and selects a book to
read.  But one's agency here should hopefully have been called in
question by the foregoing: what are the preconditions under which the
selection of reading material is made?  Often there are some "prior
causes"; other books one has been reading, things one has been
thinking about, recommendations one has received.  On the other hand,
to ignore such things and choose a book "at random" from the shelf
would seem to dash all hopes of "agency" obtaining.  We seem
to be arriving at a contradiction; one can not make an /informed/ choice
with "agency" (because any informed choice is a mechanical one, i.e., based
on prior causes); and, one can not make an uninformed choice with
"agency", because (whatever agency is!) it is informed.  Or maybe
our conclusion should be that agency, like justice, must be blind.

/To be continued...maybe.../

----

* Systems

Here is one footnote on "systems".  Physical systems, or computational
systems, or cultural systems would all do as examples.  Or the formal
mathematical systems from Ray's [[file:Monadology of systems.org][Monadology of systems]], which maybe
could be used to model these other sorts of systems in a formal way.

I don't mean to lead anyone far out on a limb here, but I was
interested by the connection between simulation, systems, and
metasystems.  Consider that /a mind understands the world/ and that
/a mind is a part of the world/.  Well, it doesn't understand the
world completely, but it understands the world somewhat.
"Understanding" and "simulating" are used essentially as synonyms here.

The curious thing here, I think, are the containment relationships.
The world contains the mind (as embodied in some physical computation
system, e.g., a brain), and the mind contains /a representation/ of
the world, specifically, a "grainy" representation.  You could also
look at this grainy representation as a "subset" of the world
(actually a projected subset).  Really, this is just saying that the
world contains "grainy self-similar representations of itself."  

Now, the question is whether these representations are "meta" to the
world or not.  On a day-to-day basis, we act as though they are; we
speak of these representations as "understanding", and we can /use/
our understandings of the world to make predictions about outcomes of
other events that are taking place in the world.  I.e., we model
/these/ systems.  But I think it is overstepping to say that the
mind is "meta" to /the world/ in any fashion, since (as Baudrillard
put it) the world can't be exchanged for anything.  Translation: the
world can't be modeled.  Translation: the world is the top of the
lattice of models.  So, our minds are only "meta" to some subsets
of the world.

That matter settled, let me now note the connection to a somewhat
/different/ kind of "meta" relationship, namely the one I have been
talking about on the [[file:tragical comedy intermission.org][tragical comedy intermission]] page and
surrounding environs.  This is the relationship of /media/ to
/content/, or similarly, /systems for exchange/ to the /things
that are exchanged/, or similarly, /CBPP projects/ to /CBPP
products/.  You get the idea.

When I say there that I think it would be good for more CBPP
participants to take a hand in the "leadership" of the project, and
that the fundamental gap in participant knowledeg is the one of
understanding the "meta" aspects of the project, and that the
potential tragedy of the information commons lies in the scarce,
singular, nature of the leadership group/...*, I think I'm
talking about something that relates closely to the more formal ideas
about metasystems.

I won't go into that relationship right now, but will state a
conclusion I came to earlier, which is that /DIY is very
"monadological" in nature/.  If you are your own doctor, your own
lawyer, your own baker, butcher, and candlestick maker, then you can
call yourself /DIY/ and you will be (in an economic sense)
sufficient unto yourself.  You will still depend on /the world/, and
it should be clear that the DIY "ideal" can't realistically be
obtained, and may not even be very desirable.  Well, that isn't
completely clear.  Humans could, in theory, depend on each other for
"non-economic" goods, even if each was fully DIY in other areas.

I assume that this speech is either motivating or incomprehensible.

I consign myself, a lasso between the animal and the superman, --[[file:jcorneli.org][jcorneli]]
