#+STARTUP: showeverything logdone
#+options: num:nil

A few things are making me rethink this issue.  First, the fact that we have
apparently not been chosen to receive funding through the 
[[file:Google Summer of Code.org][Google Summer of Code]].  Second, the fact that I'm not really sure what we
need money for (see [[file:social, political, and economic scholium systems.org][social, political, and economic scholium systems]] and
[[file:the way of the asteroid.org][the way of the asteroid]]).  While it would be great to get funding for our
work, there is also this idea of "individual responsibility" for coming up
with money to do what you want (see also [[file:free culture as a labor issue.org][free culture as a labor issue]]).

If !PlanetMath and the other AM projects can be run on volunteer effort, do we
need to worry about fundraising?

One nice offshoot of being involved with SOC was networking: we got the HDM
project "out there" in the public eye more than ever before.  This is good:
we've found some people who would like to contribute to the project, and we've
gotten some leads to other interesting related work that is going on out there
in the wide world.

If the "social welfare" gains to be had from funding HDM (for example) aren't
obvious to other people, we don't have many options other than working on things
on a volunteer basis and finding more-or-less unrelated sources of funding to
keep us fed and watered.

Looking towards the future, the idea of /salable products and services/ still
seems attractive.  It is probably less challenging to find people who recognize
the value of a given product or service to themselves than it is to convince
people in positions of social power that a given product or service is of value
to society as a whole.

--[[file:jcorneli.org][jcorneli]] Sat Jun 25 18:47:25 2005 UTC

----
Back to [[file:sources of funding for PM.org][sources of funding for PM]]
