#+STARTUP: showeverything logdone
#+options: num:nil

I had a frustrating experience, recounted in the following
section:

* A Missed Connection!

On October 12 of 2006, I went to visit Hoon Song in the Anthropology
department of the University of Minnesota.  He gave me a list of a few names to check out.
I have this list, it is a yellow piece of paper with lines on it; I haven't
looked at it, since then, until today.

The names it has on it are: Alex Golub, Alain Badiou, Gregory Bateson.

All three look like weird folks, but Golub is young enough to go any
direction. :)

The unfortunate and interesting thing is that after I talked with Hoon,
I was in the library futzing around -- maybe he had another name
for me that I had stored in my brain, or maybe I had come up with
some collection of google (or other) search terms that just worked.

The criteria are extremely vague.  But the point is, I found someone who had written
a series of books on math and philosophy.  They seemed to have
undergone a slow and respectable development.  At this point
in the person's career, it wasn't clear just where the trend was
leading, but the person seemed worth staying aware of.  Also, what
particularly caught my attention, was that this person had a
collection of short writings called "screens" that were written
on a separate computer from the work computer.  That really
jumped out to me as similar to a creative writing experiment
I was doing at the time.

However, as you might have noticed, aside from the emotional content of
my impression of this person, all of the search terms that seem
to be associated with their work seem very vague.  I can't just
search for "screen", for example, and expect to get anything
useful back.  I've tried now for about three hours to hunt up anything
interesting about the person.  I had thought that maybe
they were located in Hawaii, but that's where Alex Golub is
located, and so that might be a false memory.  It's frustrating --
I must have thought I would easily remember how to make
the connection, but at this point I don't see any of the evidence
that led me to that conclusion.

It's odd, how assumptions like this can occur.

* A Tentative Solution!
The internet would be better if there was some service out
there that you can log into that would
record every web page you visit on your behalf.  (A genuine
"web log" unlike these controversial "blogs".)  This would
be a web service you would want to log into habitually, every time
you used the internet -- a "web home".

If this solution seems "Orwellian", remember, I just want to snoop
/on myself/, not on other people.  Also, I don't particularly
care who snoops on me (I already know that Google does!).  Indeed,
you might think that Google's information about ones searches would
typically be enough to track down most pages viewed, but when I checked
there I couldn't access anything in the history.  Too bad.  Besides,
search history alone (even if it was available) isn't quite as detailed as I what I would
like...

Anyway, this is the sort of thing I think web users should be demanding!

An interesting and starkly ironic point is that if someone coded a web browser as
a web service available through other browsers, "plugins" to that embedded
browser could provide nice features -- like the full-on logging I've
described above :).
--[[file:jcorneli.org][jcorneli]]

Mozilla alreasy does that --- it has a history list which keeps track of
all pages visited.  I, in fact, use this feature from time to time to find
pages which I have visited before but did not bookmark and want to revisit
later nevertheless.
--[[file:rspuzio.org][rspuzio]]

The point is that I want a history list that is stable across different sessions,
possibly with different browsers, most importantly, on different computers.  The 
reason the situation I described was so frustrating was that I was using a 
/library computer/ and so I have no way of retrieving its history list now, 
several months after the fact.

--[[file:jcorneli.org][jcorneli]]

For what it is worth, the Mozilla history list is stable over sessions ---
for instance, I just now used it to call up a page on non-commutative geormetry
I had been perusing yeasterday, even though that was a  completely diferrent
session and I had turned uff the computer for the night and only restarted is
this morning.  Since I use only a single browser on a single computer, the 
complications you mention do not arise for me.

As for what you say about differrent browsers and differrent computers,
that is a differrent matter.  I suspect it already has been done by the
likes of the FBI in their carnivore program.  Of course, that would not
necessarrily be of much use to you.  Maybe a better solution for your 
situation would be to speak to the librarian and try to make some 
arrangement whereby you could make a personal copy of the history
list for your sessions which you could take with yourself for later reference.
--[[file:rspuzio.org][rspuzio]]

I prefer the "ironic" solution mentioned above.  The [[file:MUSN.org][MUSN]] is where
the web heart is.  The rest of the web is boring.  So log into the MUSN,
fire up [[file:Nero.org][Nero]] or something like that, and go from there :).  Rage against
the web!

--[[file:jcorneli.org][jcorneli]]

* A Harder Solution!

The internet, as it is, is just too "big" for a search for a simple
semantic query "person writes about mathematics,
writes on so-called screens on a special computer".
However, if the computer was even a little intelligent, you might think
that sort of search would turn up my target human directly!!
