#+STARTUP: showeverything logdone
#+options: num:nil

AKA: Angus Errington

I am an electrical engineering grad student in
Saskatoon, Canada. 

I have corresponded with Joe for a bit and am
quite interested in free math, free learning, etc.

Not sure how to do all this wiki editing stuff yet, but
hopefully I will figure it out by trying.

----

Yay! Welcome to the wiki Angus.  Angus is the brains behind the [[file:WOA.org][WOA]],
that life calculus that everyone but me felt somewhat dubious about at
first, but that has informed many of the things I've written since,
including the latest version of the Strategic Plan for !PlanetMath.org, which will appear
here on the wiki shortly; Angus I bet you'll be interested in that.
For you I might suggest a few notes on [[file:PlanetEngineering.org][PlanetEngineering]] (a new
project we can create just by thinking about it).  I look forward
to catching up & seeing what the wiki has in store for you and vice versa.
--[[file:jcorneli.org][jcorneli]]

Thanks Joe! I will try to keep my eye open for the Stragetic Plan
and maybe start a discussion regarding [[file:PlanetEngineering.org][PlanetEngineering]].
--[[file:aerringt.org][aerringt]]
