#+STARTUP: showeverything logdone
#+options: num:nil

http://www.newmediaexplorer.org/sepp/2006/03/22/homocysteine_and_heart_disease_patenting_a_thought.htm

thoughts can be patented.  yikes.

i wonder what the supreme court will say...

--[[file:jcorneli.org][jcorneli]] March 30, 06
 
The idea of patenting an idea is counter to the basic principles of law
which have been upheld by U.S. courts from the beginning.  If something 
like this goes through, then patent law becomes a farce.  --[[file:rspuzio.org][rspuzio]]

The news articles say that if this patent is shot down, "many patents will
be affected".  It isn't just a matter of the courts, but of the patent
office.  How are these things being granted in the first place? --[[file:jcorneli.org][jcorneli]]

And while we're at it, let's not forget Congress since they are ultimately
responsible for this mess.  After all,they wrote the patent law, voted in the
judges and the commissioners and can impeach them.  It sounds like maybe a
congressional hearing is in order if this nonsense doesn't straighten itself
out soon.  --[[file:rspuzio.org][rspuzio]]

I imagine what will finally throw a wrench in this dysfunctional momentum is that
the US will become obviously mired down by intellectual property.  Foreign companies
will become more dominant, jobs will move offshore, and the rate of progress (as 
measured by the usual econometrics) will slow.  Recognition that there are already
problems in producing qualified people in the sciences is burgeoning.  --[[file:akrowne.org][akrowne]] Sat Apr 1 05:01:59 UTC 2006

I think we should fight fire with fire and apply for a patent on the process
of patenting a thought.  To be used only for good, of course. ;) --[[file:jcorneli.org][jcorneli]]
