#+STARTUP: showeverything logdone
#+options: num:nil

** Alvaro Lozano-Robledo

H. C. Wang Assistant Professor in Mathematics at Cornell University, NY.

You may find more info about myself at:

http://www.math.cornell.edu/People/Faculty/lozanorobledo.html

or at PlanetMath.org (login alozano).

** Research Interests
Number Theory, in particular Algebraic Number Theory, in particular elliptic curves and class number related questions. Also, I study Galois representations attached to elliptic curves; elliptic units and their connections with Galois representations and class number divisibility; elliptic surfaces and elliptic curves of high algebraic rank.

** PlanetMath Interests and Long-term Goals
I want PlanetMath to be the standard online reference in Algebra and Number Theory. At least, it will be *my* standard reference. As I do research, I take mental notes of results that I think particularly useful and then include them in PM. That way, I can always go back from any computer and check the result, in case I don't have the article/book with me. It is working! 

** Some Projects

 * [[file:Article for FOCUS.org][Article for FOCUS]], see also [[file:Discussion of Article for FOCUS.org][Discussion of Article for FOCUS]] and [[file:Further discussion of Article for FOCUS.org][Further discussion of Article for FOCUS]].

----

Welcome to the wiki Alvaro - and thanks for your contributions so far!  --[[file:jcorneli.org][jcorneli]]

I like your approach to making PM your own personal reference.  I feel similarly about my computer/math endeavors!  I think many people working together like this creates a great resource for everyone... this should be tied in, somehow, to the page describing [[file:CBPP Benefits.org][CBPP Benefits]]. --[[file:jcorneli.org][jcorneli]]

I hope you're still going to finish the article for FOCUS -- and I continue
to think that emphasizing the view you express in the "!PlanetMath Interests and Long-term Goals" section
would be a great way to do that.  When I think about getting new people involved with PM,
I often want to refer them to your page here, so they can read that statement.  --[[file:jcorneli.org][jcorneli]]
