#+STARTUP: showeverything logdone
#+options: num:nil

This page is a place to create or link to summary overviews of the PM/AM
project(s).  They are relevant to our [[file:Letter writing campaign.org][Letter writing campaign]] and 
[[file:Grant planning.org][Grant planning]] (potentially among other things).

We will probably want to come at this task from several different perspectives,
because we may have different goals with these documents.

Here are three samples to begin with.  

 * [[file:PlanetMath infopack.org][PlanetMath infopack]]
 * [[file:Noosphere as an educational tool infopack.org][Noosphere as an educational tool infopack]]
 * [[file:AM projects infopack.org][AM projects infopack]]
 * [[file:FEM infopack.org][FEM infopack]]

* Discussion

The theme that I'm coming up with here is to use NPOV as much as possible,
and to separate out POV sections and explicitly label them as such.  The
reason for this is that we may want to "sell" the ideas here to people who
have different points of view.  It would be best, I think, to start with
an NPOV base, and then add some snippets of POV.  Besides, I think that
the intellectual challenge of describing our projects with NPOV could be
fun.
--[[file:jcorneli.org][jcorneli]] Thu Apr 21 04:38:47 2005 UTC

----
[[file:AsteroidMeta.org][AsteroidMeta]]
