#+STARTUP: showeverything logdone
#+options: num:nil

* Letter from the editor

Hi folks, 

its been a busy week on the Asteroid, but no one has taken the time to write
anything in the bulletin, so you just get a letter from me, and that a few days
late.

I wrote a few essays about Free Culture, and these have been the basis for
some interesting conversations.

http://planetx.cc.vt.edu/AsteroidMeta/free_culture_as_a_labor_issue

http://planetx.cc.vt.edu/AsteroidMeta/social%2c_political%2c_and_economic_scholium_systems

The second of these is related to the "scholium system" I'm writing a paper
about; you can find an introduction to that topic here:

http://planetx.cc.vt.edu/AsteroidMeta/first_introduction_to_scholium_systems

In the mean time, we've been continuing to discuss and debate about what the
term "Free Culture" means:

http://planetx.cc.vt.edu/AsteroidMeta/What_is_Free_Culture

These things are plenty philosophical (and even politically charged in places!)
and there's lots there to read; you may enjoy these things.

If you're interested in something more mathematical (but still pretty
philosophical), you might check out the mathematical-metamathematics stuff Ray
has been working on:

http://planetx.cc.vt.edu/AsteroidMeta/What_is_a_Mathematical_Entity

And last but not least, Aaron has been using the wiki as a place to broadcast
draft proposals for the NSF Advanced Learning Technologies grant he has been
working on. See

http://planetx.cc.vt.edu/AsteroidMeta/NSF_ALT_2005_Grant_Proposal_Draft

If you wish to make comments on these grant planning pages, please do it on
separate pages -- the people who need to see your comments will see them and the
people who don't probably won't :).  But since this application is due in only a
couple days; don't expect to be able to make massive changes at the last minute!
(Also parts of the application are not available on the wiki as of this
writing.)  Mostly you should just be aware of what's going on in the grant -
when its actually submitted, we'll have more updates.

Thanks for reading, --[[file:jcorneli.org][jcorneli]] Tue May 24 17:37:04 2005 UTC



* Discussion of this week's bulletin

You know the drill.  (And I'll try to add my input earlier next time!)  --[[file:jcorneli.org][jcorneli]]

Posted.  --[[file:jcorneli.org][jcorneli]] Tue May 24 21:12:27 2005 UTC

----
[[file:Bulletins.org][Bulletins]]
