#+STARTUP: showeverything logdone
#+options: num:nil

* Thanks to guest editor, and welcome to new users

I was absent last week - a visiting sister and a high-velocity cross-country
drive to the West Coast eclipsed the Asteroid Bulletin for me.  Thanks Ray for
keeping the Asteroid in view on PlanetMath.

I also want to say thanks and welcome to two new AM users, who met up with us
through the Google Summer of Code.  Both of them hail from Scandinavia -- a
place not too unlike Minnesota, but a bit further to the east - maybe you've
heard of it :).

Its great to have you guys on board!  I hope we'll be working together
at least through the summer...

http://planetx.cc.vt.edu/AsteroidMeta/pekuja

http://planetx.cc.vt.edu/AsteroidMeta/shargestam

Which brings me to the next topic.

* HDM grant idea

For about $25,000, HDM could be funding a team of five student interns for the
summer.  This would be good.  It isn't a whole lot of money when you think of
the size of some grants.  Maybe someone would be interested in putting together
an NSF REU (or a similar program) focused on the HDM?  That would be cool!  Or
if you have any other ideas about how to come up with that kind of money
(possibly on a quarterly basis, so we can keep people in work all year round)
get in touch!  Finally, if you have any interest in matching google's $4500
contribution and helping us fund another student this summer, I'm pretty sure we
can make arrangements with PlanetMath to make your deduction into a nice tax
writeoff...

http://planetx.cc.vt.edu/AsteroidMeta/HDM_SOC_II

* Summer of Hcode

Some new discussion has been taking place about what the HDM project is going to
work on this summer.  The general agreement is that improving the definition of
h-code -- our "formal" computer language for representing mathematics -- is one
of the top priorities for the research team.  We'll be coming at this problem
from a couple of different points of view - from the natural language and human
understanding point of view, and from the formal math point of view.  Two pages
to check out for a preview are here.

http://planetx.cc.vt.edu/AsteroidMeta/a_dozen_proofs

http://planetx.cc.vt.edu/AsteroidMeta/structured_proofs

(The second page here may be of interest to anyone wanting to learn how to write
better proofs.)



* Discussion

Per usual, feel free to edit and add content to the bulletin.  New users: in
general we use these to keep track of the highlights of our Asteroid
experiences, and keep everyone here and in the background PlanetMath community
(and anyone else who is interested) up to date.  --[[file:jcorneli.org][jcorneli]] Sun Jun 19 02:22:49 2005 UTC

----
[[file:Bulletins.org][Bulletins]]
