#+STARTUP: showeverything logdone
#+options: num:nil

* Emory Conference Deadline!

The deadline for submitting papers for the Emory Conference on the Free Culture and the Digital Library is this Friday.  Among the list of contributors who are hard at work writing and polishing submissions one can find a few names which will be familiar to readers of this bulletin:

 * Robert Milson "Adapting CBPP platforms for instructional delivery"
 * Daniel Mayer "Trusting the user, Wikipedia as an example"
 * Aaron Krowne "How Free Culture Will Save Digital Libraries"
 * Joseph Corneli "A scholia-based document model for commons-based peer production"
 * Raymond Puzio "Free Math and Potential Bottlenecks"

This conference will offer people who are concerned about free access to information a chance to meet and exchange ideas.  In particular, it will give those of us involved in projects like Planet Math, the Hyperreal Dictionary of Mathematics, and Asteroid Meta a chance to publicize these projects to a wider audience and benefit from interaction with like-mided individuals in other fields.

If you have a chance, please have a look at the essays and perhaps post comments and suggestions to their authors.  

http://planetx.cc.vt.edu/AsteroidMeta/Emory_Free_Culture_and_the_DL_Symposium

* Getting involved with HDM

If you're curious about how to help out with the HDM project, we've got a short
list of relatively "small" projects going here.  "Small" doesn't necessarily
mean easy or short term; some of these things could be tasks for a weekend,
others could be tasks for a thesis project.

http://planetx.cc.vt.edu/AsteroidMeta/Focused_HDM_subprojects

One of the weekend-sized tasks is sifting through the "related work" page that
we've put together with some preliminary content.

http://planetx.cc.vt.edu/AsteroidMeta/HDM-related_things_to_check_out

* When is a theorem important?

That is the subject under discussion on this page:

http://planetx.cc.vt.edu/AsteroidMeta/Mechanically_structuring_readable_proofs

It would be interesting to get some additional views on the subject!
(Probably every mathematician "knows" why their own work is important!)

* HDM Summer of Code not funded

Google has declined to fund our great applicants, and the HDM project continues
to be a fly-by-night volunteer operation.  Getting heavily involved with the
project may not be an option for you, and helping us with funding may not be an
option either.  But please take the time to get acquainted with the project if
you haven't done so already.  More people should be aware of what we're trying
to do here (even if they don't particularly care for it).  We like friendly
debate and constructive criticism.

http://planetx.cc.vt.edu/AsteroidMeta/HDM

* Discussion
Note to all users (esp. new ones): check the [[file:Policy.org][Policy]] and so forth about
bulletins.  To sum up: sum up your activities for the historical
and public record.  Especially important since I'll be gone most of
the week.  --[[file:jcorneli.org][jcorneli]]

I was considering posting something about free

----
[[file:Bulletins.org][Bulletins]]
