#+STARTUP: showeverything logdone
#+options: num:nil

As the title indicates I spent most of my travel time on a train.
(Or "tomo tawa linja" if I remember my tiny bit of toki pona properly -- a
line-like moving building.)  I stopped off in Charlottesville,
and walked around. I found it to be scenic, but my sense was that the
denizens were very conservative.  I appreciated the quotes on the
pair of gates whereby one enters the university there: "Through wisdom
a house is builded, and through understanding it is established, and by knowledge filled with precious and pleasant things"
on one, and "Let me pass through this gate in willingness to be of
service to mankind" on the other.  I'm sure I have the quotes wrong,
but this conveys their general sentiment; the first one was a version
of Proverbs 24:3, which is quoted in various forms on the internet.
Any other interpretation of the first quote aside, I appreciated it very
much because I was studying Go most of the time on the trip, including the basics of "life and death" -- so serious sounding!
The idea of building good structures is quite relevant to Go -- there is even a Korean
proverb related to the game that says, build your house and your enemy will die!
As for the other gate, it reminded me of a film I have ambiguous feelings
about ("Institute Benjiamenta") and my historical interest in gates.
(I have a framed print of a painting of a gate above my door, and the
maintenancewoman who runs my building once remarked that she thought it
was too symbolic for me; I said, mathematics is very much concerned with
symbols.)  There is a soup kitchen up the road from the train station towards
downtown (actually about a half a block to the left of this street) that
I didn't eat at, although probably I should of (as I had had to cancel my credit card and was out of cash).  At Charlottesville, I slept
through connection to Chicago and had to get rerouted through DC, where I
spent the night in the station.  The most interesting thing about this station
is that it is run by cops on those new-fangled Segway conveyances.  It
reminded me of "THX 1138".  DC seems to be the only station where they
actually check IDs of outgoing passengers, but they seemed to do so in a very
half-hearted way, just checking that the ID existed, and seeming even to
be somewhat annoyed by its presence.  From there on, travel was easy.
I stopped off in Chicago at my relatives' again, and they fed me, then
I got back later that night.  On the train I thought about all sorts of
different things which presumably you'll be getting wind of soon enough.
I also finished my book of Borges short stories, which I enjoyed,
particularly "Ibn Hakkan al-Bokhari, Dead in his Labyrinth".
