#+STARTUP: showeverything logdone
#+options: num:nil

On the wikipage "[[file:Competitors vs collaborators.org][Competitors vs collaborators]]" I suggested that it
would be a good idea to coordinate work with various other CBPP groups.
Here I'd like to kick the idea up a notch, and say that I think it would
be good if we could get other CBPP theorists and "meta-heads" involved
in working together on various CBPP issues.  AsteroidMeta was supposed
to be a central place for coordinating work on CBPP -- but so far we
haven't seen much involvement from anyone other than the founding members
of this project here.  Perhaps this is because /work on CBPP/ must inherently
be as "segmented" and "polycentric" as the field it describes.  Nevertheless,
I'd like to think we could take some steps to be more grounded in society and better integrated 
with the work of others.

/For fun: one may investigate the notions of 'Instrumentality' at
[http://en.wikipedia.org/wiki/Human_Instrumentality_Project these]
[http://en.wikipedia.org/wiki/Instrumentality_of_Mankind two] science fiction related pages
on Wikipedia./

BTW, [[file:akrowne.org][akrowne]] is apparently one of the world's top experts
on CBPP at present (according to Google), e.g. the search for "cbpp commons"
turns up several references to his work, including
the relatively recent review at
http://fis1311smiddleton.blogspot.com/2006/03/review-building-digital-library.html.

Other experts and/or pundits include [http://www.benkler.org/ Yochai Benkler],
[http://www.catb.org/~esr/ Eric S. Raymond (esr)], and [http://en.wikipedia.org/wiki/User:Jimbo_Wales Jimbo Wales].
However, given the nature
of the field there are bound to be lots and lots of people working on 'related topics'.
(E.g. "the commons" itself has been very interestingly tackled in a book I recommend
all the time, called
[http://www.uapress.arizona.edu/BOOKS/bid299.htm The Question of the Commons], edited by
anthropologists [http://aesop.rutgers.edu/~humeco/cvs/mccay.htm McCay] and
[http://www.marine.maine.edu/faculty/faculty_indiv.php?faculty_id=18 Acheson].)

Oughtn't some of these folks be working together more?

--[[file:jcorneli.org][jcorneli]]
