#+STARTUP: showeverything logdone
#+options: num:nil

* how to
I am trying to post that my book is available for downloading in the physics board.
The book is about compressible flow. I also would like to find a volunteer(s) to help with the 
editing www.potto.org. 
genick bar-meir

* Personnel

We are currently seeking qualified volunteer Associate Editors for the [[file:FEM.org][FEM]]
project.  Please get in touch via the [[file:FEM Editors.org][FEM Editors]] page.

* Personal

If you are in or visiting Minneapolis, ping [[file:jcorneli.org][jcorneli]].

For Atlanta, GA, [[file:akrowne.org][akrowne]].

In New York City, [[file:rspuzio.org][rspuzio]]

Around Colorado Springs, [[file:bloftin.org][bloftin]]

* Material

We are always soliciting new free math at PlanetMath, for addition to the
Papers, Books, and Exposition sections as well as the Encyclopedia.

* Material

Wanted: printer paper and access to your printer. --[[file:jcorneli.org][jcorneli]]

Wanted: workstation with flatscreen monitor. --[[file:jcorneli.org][jcorneli]]
