#+STARTUP: showeverything logdone
#+options: num:nil

This page refers to the discussion of [[file:Asteroid Bulletin for the week of May 1 2005.org][Asteroid Bulletin for the week of May 1 2005]].
I am impressed by [[file:rspuzio.org][rspuzio]]'s use of wikitime, when he commented
in what is known to this wiki as 
[http://planetx.cc.vt.edu/AsteroidMeta/?action=browse;id=Asteroid_Bulletin_for_the_week_of_May_1_2005;revision=2 revision 2]
of that page:

: It is interesting to compare [Aaron's remark, /On "the way of
the Asteroid" - I don't want a "code of behavior to govern" me,
especially not one authored by someone else on a Wiki (the key onerous
word being "govern"). Joe, I believe we need to be more clear about
drawing the line between this wiki as your personal organizer and
diary, and it as a public, shared space. For one, if no one
contributes to policy discussions you start, then I don't think its
right for you to just propagate them as the final word of "the
community."/, made] a year ago (especially the last sentence) with 
the current bru-ha-ha about the the relation of AM and PM.

I don't know if it is fully appropriate for me to pull that comment
out of its context and put it on a new page, however, I have a number
comments to make about it, and I feel I can express myself more freely
here; if it is decided that these comments should be put back into
that context, I would be happy to accommodate.

Indeed, Ray's comment highlights one elocution in a long discussion,
which itself was part of a broad system of occurances, so by way of
response, let me first highlight a number of important contextual
details.

First, there were only 4 bulletins prepared and published after the
May 1 bulletin.  The reason for this is no doubt complicated, but as
the main reason I would cite the overwhelming lack of interest of PM
people in the content of previous bulletins; I don't know if we heard
back to any of them, if we did, I don't remember it.  This, and the
general lack of involvement by PM people in the wiki, I considered to
be a major failing of community spirit on the part of the mathlings.

In the case of the [[file:WOA.org][WOA]], I felt this community spirit failure to be
present in my close colleagues on !AsteroidMeta.  I did not start that
policy discussion solely for my own amusement, and I saw the fact that
these others did not participate as deeply as myself as both their
loss, and also a loss to both AM and PM.  As I remarked to Aaron in my
reply to his comment highlighted above, /It is really more of a
meta-code for than a code. The only demands it places on people is
that they should participate in some self-reflection, writing, and
discussion./  I continue to think that we need to cultivate a culture
of reflection, expressiveness, and thoughtful critique; indeed, this
sentiment underlies many of my current activities on or related to AM,
for example, drafting the [[file:whitepaper|strategic plan.org][whitepaper|strategic plan]] for PM, 
working on [[file:Arxana.org][Arxana]], posting little-discussed philosophical essays such as my
proposed [[file:calculus of self-referentiality.org][calculus of self-referentiality]].  Codes governing
behavior, tools for understanding and generating codes governing
behavior, musing on the nature of codes of behavior!  Whether or not
others have participated in these discussions (sometimes they have
participated significantly, and sometimes they haven't), I think it is
vital that we have these discussions, and this is why I write about
these things.

I would never say that something written by one or a handful of people
was "the final word of 'the community'", and I think that Aaron's
rhetorical claim that I was about to propagate the WOA as just such
a "final word" is pretty ridiculous.  However, it may well be that there
was the possibility of mistaking what I said in the bulletin for
masquerading as such a final word; and if so, no doubt it could have
been corrected with a minor change of wording, for example, we could have
revised my feature to begin with "Joe Corneli proposed..." or something like that. 
As they report on the goings on at the wiki, the Bulletins appropriately
would document the "personal" projects of wiki users.

Our recent discussion of "moving consensus" at [[file:Sketch of a Possible Organizational Structure.org][Sketch of a Possible Organizational Structure]]
develops the idea of a conglomerate of personal points of view as a "consensus
reality".  As was remarked there, this sort of consensus does not mean
that everyone agrees with everything; it is not /the/ voice of the
community, but the /voices/ of the community, whether aligned in
harmony, or dischord, or, more likely, some sort of jazz jam session
with both.  This view of consensus is important to me, and it informs
my overall strategy for understanding PM's upcoming strategic plan, a
document which will eventually "speak for" PlanetMath, although I wouldn't
ever say that it offers the last word.

In such a metaphorical jazz session, if someone doesn't want to listen to e.g. the clarinet, or to hear any
note below middle C, it would certainly be hard for them to do that with
the wiki.  Personally, I would rather focus on getting [[file:Arxana|AM2.org][Arxana|AM2]]
up and running than devote much time figuring out how to use what I see
as a less-flexible medium; however, [[file:A note from some members of PlanetMath who dislike this media|as I've also said.org][A note from some members of PlanetMath who dislike this media|as I've also said]],
I wouldn't have a problem with people creating some sort of PM-only wiki.
I wouldn't know how to do that sort, but my view of PM is not completely
typical.

As above, I think it is a problem if people don't participate in the
more philosophical and reflective sorts of thinking.  Nevertheless,
if people aren't participating in these things, as [[file:drini.org][drini]] and [[file:alozano.org][alozano]]
have (indirectly) pointed out, we should be asking why.  We can debate
the
[[file:the relative merits of wiki and other workflow management media|merits of the wiki medium.org][the relative merits of wiki and other workflow management media|merits of the wiki medium]]
for a long time.  However, I think the question goes beyond the particular
choice of medium, and on to the question of motivation of individual participants.
Whether to participate in a given forum or discussion is always a personal
choice; and no doubt these choices are made for "good" personal reasons.
In cases where more participation is hoped for but not forthcoming,
there is bound to be a reason for that too.  I think we should be having
these contentful discussions.

--[[file:jcorneli.org][jcorneli]]
