#+STARTUP: showeverything logdone
#+options: num:nil

Non-[[file:Projects|project.org][Projects|project]]-specific collaborative efforts and
jointly-written papers.

* PlanetMath Documents

 * [[file:Second Draft of Pact.org][Second Draft of Pact]] (The contributor copyright "pact")

* Grant Proposals

 * [[file:NSF ALT 2005 Grant Proposal Draft.org][NSF ALT 2005 Grant Proposal Draft]]

* Conference/Journal Papers

** First Monday Papers 2006

 * [[file:First_Monday_Paper--The_Fog_of_Copyleft.org][First_Monday_Paper--The_Fog_of_Copyleft]]
 * [[file:First_Monday_Paper--The_HDM_Manifesto.org][First_Monday_Paper--The_HDM_Manifesto]]

** Emory FCDL Conference 2005

 * [[file:Adapting_CBPP_platforms_for_instructional_use.org][Adapting_CBPP_platforms_for_instructional_use]]
 * [[file:How_Free_Culture_Will_Save_Digital_Libraries.org][How_Free_Culture_Will_Save_Digital_Libraries]]
 * [[file:A_scholia-based_document_model_for_commons-based_peer_production.org][A_scholia-based_document_model_for_commons-based_peer_production]]
 * [[file:Free_Math_and_Potential_Bottlenecks.org][Free_Math_and_Potential_Bottlenecks]]

* Presentations

** JMM 2006 Presentations

 * [[file:Metamathematical_Visions_-_metadata,_learning,_and_knowledge_communities.org][Metamathematical_Visions_-_metadata,_learning,_and_knowledge_communities]]
 * [[file:PlanetMath_and_Free_Mathematics.org][PlanetMath_and_Free_Mathematics]]

----

Some of these I actually do think are "project specific" but we can
rearrange them later. --[[file:jcorneli.org][jcorneli]]

Yeah, I just felt we needed a direct index to them.  I find myself getting
lost in the Wiki looking for them exacerbated by the mediocre-ness of the search engine.
--[[file:akrowne.org][akrowne]] Sat Jan 7 23:30:09 UTC 2006

A number of other people have mentioned the getting-lost effect,
so if this index helps counter-act that effect, good!  I re-worded the text on
the homepage that describes this page, so that project-specific
jointly-written papers are part of its mandate.  One potential
concern for a later date is that these seem to be mostly (or all?)
your ([[file:akrowne.org][akrowne]]'s) collaborations, but that only stands to reason at
present, since you've participated in a lot of the collaborative
writing of large-scale fixed documents on this site.  At some point it
could be helpful to re-index onto specific pages for each user's
collaborations.  By the time this comment is actually relevant,
it might also be very easy to accomplish the desired multi-factoring
with the appropriate scholium system tools.  For now, the page
seems to capture the relevant info -- as long as it is understood
correctly (I think I do, now). --[[file:jcorneli.org][jcorneli]] 
