#+STARTUP: showeverything logdone
#+options: num:nil


Below is a short piece I wrote to describe what I think is the
(candidate) "tragedy of the free/cbpp information commons".  Not to be
entirely gloomy, I also give some suggestions for how this tragedy
may be staved off.

This source text is taken in another direction in the accompanying
piece [[file:user lib.org][user lib]]. --[[file:jcorneli.org][jcorneli]]

----

Quel disastre!  (I love to say that these days!)

The tragedy of the commons?  That some greedy users would destroy
the resource for everyone.  The antidote?  Game theory (on the theoretical
level), morals (on the moralistic level), social norms (on the societal
level), and common sense (exercised on the common grounds of the commons
itself).  Presto.  What "tragedy of the commons"?

Funny you should ask.  I'll tell you what I think.  For information
commonses, the greatest tragedy I can think of is not that the users
are "too greedy" but that they are "too ignorant".  There is, indeed,
an interesting duality between ignorance and greed as we move between
the "mental" and "physical" worlds.

And when I say "ignorant" or "greedy" please do not think that I
am judging my bretheren.  Or that I pity them.  This is the
nature of tragedy: a tragic flaw in inherent and has no cure.
Therein obtains its fatal beauty.

But did we not speak of an antidote just before?  Aye, but to
a mal-predicated ill.  Evolutionarily speaking, I mean.  For,
people /can/ learn from their mistakes, or at least appear to
do so, as the ones who don't learn die out.  The solution to the
tragedy of the material commons is learning; it is, in a sense,
to impose an "information commons" of sorts - in the form of "common law" -
on the material commons.  A sense of indecency becomes associated with
destructive overuse, perhaps further associated with punitive measures.

But the information commons does not suffer from overuse.  It suffers
(relative to what it could be), as I have said, from the widely
prevailing ignorance of its users.  How so?

They are, as a whole, ignorant of the inner workings of the
information commons.  This is the case whether we speak of
governmental systems or systems based on other more mundane sorts of
codes.  This ignorance chrystalizes in the inability of all but a few
users (the /superusers/) to make changes in the system.  Even when
technically free to /learn/ and to /adapt/ the system to their
needs, the user instead adapts emself to the system and the system's
power dynamic, preying, as it were, upon the mercy of the superuser.

But the superuser is often just as straightjacketed as the user,
precisely because the superuser's time, knowledege, and interest are
scarce goods!  Overuse of the system essentially doesn't exist, but
overburdening of the superuser most certainly does.

Disaster, indeed.  You may now wonder, is there hope for an antidote?

Thunder crashes.  Stay tuned for Act II.

----
[[file:tragical comedy intermission.org][tragical comedy intermission]]

Is the situation really as dire as it might seem?  Perhaps we haven't
given the superuser enough credit.  Working "outside" the system or
behind the scenes; thinking outside the box -- these are powerful
things.  Perhaps it is OK if the user base remains ignorant of the
system's workings and depends on the superuser working a bit of magic.

We've come to depend on precisely the one scare resource that could be
part of the equation, but perhaps that was to be expected.  Although
scarce, it may be valuable enough to solve our problems, just like
that...?

It isn't likely to be that easy.  Put all your chips on the superuser
and risk trouble.  ("Who watches the watchman?")

I think the antidote here is similar to the one for the standard
tragedy.  The system needs to be digested in its parts to the point
where it is feasible for anyone who might want to do so to make
systemic changes.  While not every user would care about making
changes to the system, some will care; but the technical ramp-up needs
to be fairly gradual for "caring" to translate into solid work.

Tragedy of the commons always pertains to the scarce resource.  In the
standard case, scarcity is /managed/ by limiting consumption.  I'd
argue that in the info commons case, scarcity must be staved off by
increasing production. 

----
