#+STARTUP: showeverything logdone
#+options: num:nil

On a recent [[file:stallman adventure|page.org][stallman adventure|page]] describing a Q&A session with Richard Stallman (which
concerned the QA section of the library of congress; I mention this so as to be completely clear
on terminology), I asked, more clearly than I think I have asked before (for this has been
a question of ongoing concern), whether we can legally haxor GNU in the same fashion in which
we propose to rip, garrote, and burn (whether at the stake, or perhaps, more appropriately,
in effigy) traditional mathematics, with our [[file:HDM.org][HDM]] project.

Let's consider the facts; then there can be no argument.  Which is not to say that I
am utterly convicted in my views, indeed, on the contrary, I hope to see this
question discussed with the enlightened detachment required for the formation of
a plan of action, and then (and only then) do I hope for the plan to be executed.

Ladies and gentlemen of the jury, I appeal herein mainly to your sense of
humor, but also to your senses of decency, justice, honor, and humility.
For, as it has come into the view of this court, certain documents
([[file:GPL|Exhibit A.org][GPL|Exhibit A]], [[file:FDL|Exhibit B.org][FDL|Exhibit B]]) which show the GNU project to be
thoroughly anti-hoarding in its policies, which, taken together with other documents too
plentiful to exhibit but in abstract form ([http://souceforge.org Exhibit C],
[http://savannah.gnu.org Exhibit D]) that underscore the spirit of sharing
and community exercised by the GNU project and its followers, show that
my client, who has /understood/ the contents of the various documents
shown in Exhibit C and Exhibit D, and /based only on her own understanding/
translated the ideas expressed therein not simply from one language to another, but
into a new and utterly distinct form, has /acted within her rights as a reader and
author/, namely, to create
a parody of the original work.  That my client has released the result of this
labor into the public domain shows that her concern is not for personal gain
but for the entertainment, enjoyment, and edification of our society at
large.  The GNU project's spirit of sharing is revivified in this admirable
work. 

The case for the plaintiff rises, but no plaintive cries these, rather,
a bullish bellowing, not unlike that of a wounded animal!

My... colleague... mentioned "parody", but the only parody here is 
his plea, which threatens to make a travesty of the law.  The defendant
has applied simple computer programs to translate, in the barest and most
spartan way, the GNU project's computer programs (available only under license),
into other computer programs, released in such a way as to break the
terms of the license.  How can a computer program be a parody?  And how can computer programs be
said to "understand" anything?  To parodize, or even to express
something, requires intelligence far beyond the infantile mentality
of a computer, a computer which can only do what it is told to do by a human.
We all know to whom I refer.  Beheading is too good for him.

After some astonished gasps from the gallery, this rebuttle.

Who is on trial here?  The machine, or its programmer?  Or, should it
be the license, and its author?  This license, which has attempted to make
excludable that which by its very nature wants to be free. A
wanting-to-be-free that has nevertheless been acknowledged, promoted, and promulgated by the license's
author.  However, the license's sole aim is to exclude excluders -- which
would, at first glance, appear to be a contradiction in terms.

Now, gentle reader, let me translate you from these scenes of depraved
legalism....

--[[file:jcorneli.org][jcorneli]]

* Discussion

I wonder whether it is appropriate to follow the various scholars who
refer to a generic computer as "she".  The point is that before computers
went mechanical, they were, in fact, typically women.  However, I wouldn't
want to perpetuate a stereotype.  Let's try it this way, and if we don't
like it, we can always go back, or change things around a little further.
--[[file:jcorneli.org][jcorneli]]
