#+STARTUP: showeverything logdone
#+options: num:nil

Usually, the term "reparameterization" means the following equivalence relation:  /a = b &#8728; f/ where /f/:[0,1] -> [0,1] is continuous invertible, and orientation-preserving.  This, however, is not good enough for us.  Suppose we have a function /f/:[0,1] -> [0,1] such that /f(x) = 2x/ whenver x &le; 1/2 and /f(x) = 1/ whenver x &ge; 1/2.  We would like to consider /f/ as equivalent to the reparameterization function.  Intuitively, this means that we would like to be able to shrink intervals over which the function is constant to a point or, conversely, expand points into such intervals of constancy.

To define this formally, we will start with the observation that continuous, invertible, and orientation-preserving functions from an interval to itself are monotonically increasing.  To obtain our generalized equivalence relation, we shall consider functions which are monotonic and continuous, but not necessarily invertible.  Note that continuous monotonic functions fail to be invertible exactly if they happen to be constant on a subinterval.  Since our modified definition is supposed to differ exactly when constanct over subintervals is involved, discarding the condition of invertibility looks like a good way to proceed.

If we drop the condition of invertibility, we have to be careful because, in the usual way of defining reparameterization, symmetry is a consequence of invertibility.  However, we can refomulate this definition as follows:  Two parameterized curves, /u/ and /v/ are equivalent if there exists a function /f/:[0,1] -> M and invertible monotonic functions /g,h/:[0,1] -> [0,1] such that /u = f &#8728; g/ and /v = f &#8728; h/.  It is not hard to see that this definition is equivalent to the usual definition.  If one simply wanted to define reparemeterization equivalence, there would be no reason to consider this definition because it is cumbersome; however, it is useful for our purposes because it generalizes readily.

Thus, we define our generalization of reparameterization equivalence as follows:  Two parameterized curves, /u/ and /v/ are equivalent if there exists a continuous function /f/:[0,1] -> M and continuous monotonic functions /g,h/:[0,1] -> [0,1] such that /u = f &#8728; g/ and /v = f &#8728; h/.  

It is clear that, given any choice of /f/,/g/, and /h/ as above, /u/ and /v/ will always be continuous and that the relation is reflexive and symmetric.  In order to check if it is a true equivalence relation, it only remains to check transitivity.  Suppose that /u/ is equivalent to /v/ and that /v/ is equivalent to /w/.  This means that there exist functions /f,k/ :[0,1] -> M and continuous monotonic functions /g,h,m,n/:[0,1] -> [0,1] such that /u = f &#8728; g/ and /v = f &#8728; h/ and /v = k &#8728; m/ and /w = k &#8728; n/.  Then, we have /f &#8728; h = k &#8728; m/.  

Back to [[file:Connections as Functors.org][Connections as Functors]]
