#+STARTUP: showeverything logdone
#+options: num:nil

It can be challenging to get people involved even if they have
interest, skills, and time.  Why is that?  Our personalities can't
be /that/ objectionable, can they ;)?  Sometimes the problem boils down to a lack of communication.

As one simple effort to find like-minded people locally, I posted a
message like this to the craigslist "activities" page and similarly
to the "strictly platonic" page:

: I'm a programmer, amateur mathematician, ex-student, and free-lance
philosopher. I am looking for other folks with similar interests
to get together for hack fests, math seminars, philosophical discussions,
and/or culture jamming.
 Cf. http://planetx.cc.vt.edu/AsteroidMeta/HomePage

Perhaps other folks would like to try similar postings in other locales
(e.g. NYC, Atlanta).  If this is going to be a "free math movement",
it should be a popular movement!

In addition to this sort of shot-in-the-dark (pull) approach, one
should presumably try some shot-in-the-light (push) approaches, e.g.
canvassing local GNU/Linux user groups, or, like Ray is doing, LISP user
groups, etc., insofar as they exist.  

One difficulty is (of course) figuring out which are the relevant groups
to canvass.  --[[file:jcorneli.org][jcorneli]]
