#+STARTUP: showeverything logdone
#+options: num:nil

This is an extension of the discussion on the 
[[file:Difficulty of getting programmers.org][Difficulty of getting programmers]] (sic).  (The somewhat 
obscure sounding title of that pages means something like "the difficulty of getting
programmers involved".)

To sum up, it is can be hard to get anything done!  This is, I guess, a 
philosophical point.  But this is AsteroidMeta, after all, and philosophical
discussions are /OK/ here.  Trust me, I'll try to make this relevant.

I was talking to this guy at a little get together I went to last night, and he
was emphasized the importance of perseverance.  The example was, if I say I want
to walk from Minnesota to Guatemala, people might think I'm crazy, but if I take
off and start walking, and keep going every day, eventually I will get there.

Sure, there might be some trouble crossing borders, and it might be risky or
expensive in other ways, but the statement is probably true.

Another philosophical idea from that conversation was the notion that if you can
imagine something, it is likely to become feasible with sufficient work.  Again,
I suppose that there are certain limits due to physics (and, fundamentally,
mathematics) but again, I suppose the statement is probably true -- especially
if we take simulation into account.  So that is somewhat encouraging, too.

One of the big difficulties associated with trying to get things done is that
sometimes you imagine that other people should be doing them.  After all, you
have a certain skill set, and certain time constraints, and other people may
appear to be much more qualified to work on some task than you are.  Some of the
time this is true.

But other times, it is best just to push ahead with your partial and imperfect skills, and
to try to teach yourself what you need to know to get the task done.
This relates to the discussion about learning new skills and building new systems,
[[file:mathematicians do not want to go out of their way to learn something new|here.org][mathematicians do not want to go out of their way to learn something new|here]].
As you build your own skills, and improve the systems you are working on to the
point where others will be interested in and able to get involved, eventually
things may take off pretty well.  (Something similar is also mentioned
[[file:one week in october|here.org][one week in october|here]]: people won't get involved with something unless
they see benefits associated with their involvement.)

Of course, by then, you will no doubt have dreampt up other difficult goals.

Even when a system is flowing along pretty well, one of the reasons that it can
be difficult to get things done is that it can be difficult to know what other
agents in the system are up to.  It can even be hard to know what you yourself
are up to!  Our understanding of ourselves is, I'd say, pretty limited.

Various
[[file:the relative merits of wiki and other workflow management media|collaboration tools.org][the relative merits of wiki and other workflow management media|collaboration tools]]
can help reduce the difficulty associated with awareness of, and information flow among
various project participants.  If people post detailed TODO lists, you can see:
"oh, I see, the reason so and so isn't doing /this/ is that they are busy with
/that/."  And so on.  The more people spell out what they are up to, and what the 
expected benefits and costs associated with their pet projects are, and the /timelines/
for their involvement with these various projects, the better others will be able to
assess the usefulness of making a contribution of effort, or giving the person room
to think, or whatever.

Again, even in single agent environments, it is good to try to keep track of
various experiential data, since you can use it to better understand yourself,
your motivations, and your capabilities.
--[[file:jcorneli.org][jcorneli]] Sun Mar 27 21:35:03 2005 UTC
