#+STARTUP: showeverything logdone
#+options: num:nil

This page is about [[file:PlanetMath_Board_Meeting--Q2_2006.org][PlanetMath_Board_Meeting--Q2_2006]].

* About paid positions

The last draft of the agenda said that the board meeting would include "determining the roles" of
paid staffers.  I think this is unrealistic, given that the board meeting will only be a few
hours long at most.

In the discussion surrounding the [[file:PlanetMath_whitepaper_for_potential_partners.org][PlanetMath_whitepaper_for_potential_partners]],
we came up with a page named [[file:Vision_for_the_future_of_PlanetMath.org][Vision_for_the_future_of_PlanetMath]].  Eventually
some of the content of this page should be merged into or referenced by the new 
[http://www.ma.utexas.edu/~jcorneli/a/plan.pdf strategic plan] I started working on.
As it is, this page has a lot of content, without a high degree of internal organization
or actionability.

One thing it does include that is particularly worthwhile is a brief
discussion of administrative and research roles.  I'm going to copy
this content to [[file:PlanetMath Roles.org][PlanetMath Roles]] where hopefully we can start talking about
exactly what roles need to be filled.  This of should progress in close combination
with discussion of [[file:PlanetMath_Salaries.org][PlanetMath_Salaries]], and perhaps also with
[[file:PlanetMath Hiring Policies.org][PlanetMath Hiring Policies]].

Several volunteers ([[file:jcorneli.org][jcorneli]], [[file:rspuzio.org][rspuzio]]) essentially require
paid positions with !PlanetMath in order to be able to continue to
contribute a high level of involvement.  If paid positions for these
people can't be created, then someone else will have to take over for
these people.  If such positions can be created, then this is only a
first step: fundraising will have to be done.  And, as per the
discussion on the pages mentioned above, the tasks associated with
certain organizational roles will have to be carried out.

This is a lot to coordinate all at once, so I think for the board
meeting it is best to have a high-level statement of what is being
approved, so that we can then move forward with confidence that we're
doing something organizationally-copacetic by pursuing the creation
and staffing of certain paid positions.

** Concern and disagreement

Some members have expressed their concern on this point and their open
disagreement on the creation of paid positions.

Unless some rational discussion of the objections can be carried out,
I'm not sure what can be done to help these conscientious objectors.

--[[file:jcorneli.org][jcorneli]]

* About plans and work priorities

I suggested in a recent conversation with Aaron and Ray that we should
give the board a short summary of what we've been working on for the
last quarter, and what we plan to work on for the next quarter.  I
still think that this is a good idea.

I also think that the [http://www.ma.utexas.edu/~jcorneli/a/plan strategic plan]
I've been working on should continue to be revised and improved, hopefully
with broader participation.  This may not have anything to do with the board
meeting precisely, but I do think it would be good for board members to know
that such a plan exists and is being worked on.

* Other topics

I don't know what the status of the contributor pact is.  For
licenses, it seems like allowing a choice between 3 different
compatible licenses (PD, CC-attribution-only, FDL) is something people
can agree to.  
