#+STARTUP: showeverything logdone
#+options: num:nil

I can't make it that weekend, would it be possible to move the date? --[[file:alozano.org][alozano]]
: We would probably have to move it back one weekend to May, but otherwise I'm fine with that.  What do other people think? --[[file:akrowne.org][akrowne]] 

The date doesn't matter so much (I'm sure there is some rational
date-blocking-out mechanism we could use to select something that
works for everyone, rather than shooting in the dark!).

However, I have a question about the medium.  Can we use the voice
chat number we've have learned about simultaneously with IRC?  This
way, if someone has difficulty getting on a computer, they can use
voice, and vice versa, if they have difficulty using voice, they can
get on IRC.  Some people may be using both media, and can act (in
part) as relays between them. --[[file:jcorneli.org][jcorneli]]

I see no problem with that, but we will need bridges.  I don't believe I can
participate meaningfully by straddling both media, so I will just be on IRC.
 --[[file:akrowne.org][akrowne]] Mon Mar 20 22:44:36 UTC 2006

You sound like a man in need of voice recognition software! ;)

I'll add the phone information.  --[[file:jcorneli.org][jcorneli]]

: BUMP! Could we agree on a later date for the meeting? --[[file:alozano.org][alozano]]

What do people think of Sunday, April 30, 9PM EST for the meeting? --[[file:akrowne.org][akrowne]]
