#+STARTUP: showeverything logdone
#+options: num:nil


It is somewhat interesting that things like the [[file:FEM.org][FEM]] and [[file:HDM.org][HDM]] projects are
considered (by some) not to be good fare for students.  

I think it is a little bit ironic, first of all, that editorial positions in
traditional mathematics tend to be reserved for the most prestigious
mathematicians.

Sure, it is good to have editors who know a lot about their field, but things
like technical work, clarity of writing, requests for articles with a particular
pedagogical slant, etc., seem like things that students are perfectly well
qualified to do, and indeed, in some cases, things that students might be better
qualified to do than top-ranked mathematicians!

As for the HDM project, it is reasonable to say that it isn't a good thing for
students to do -- but only because of the extremely rigid idea of what a
student's responsibilities are.  

Students for the most part aren't expected to play, or be creative, or think
outside of the box, or work for social change in the area of inquiry that they
are studying.  They are, in general, not supposed to do "meta" things.  Rather,
they are supposed to keep their nose to the grindstone, to follow in the
footsteps of those who went before, etc.

I was interested to see [[file:rspuzio.org][rspuzio]] mention Dionysian and Apollonian approaches
to research in the [[file:Discussion of not really math.org][Discussion of not really math]] page.  Whitehead talks
about something similar in several of his essays on education.  (I hadn't ever
made the connection of these Whiteheadian ideas with this Nietzschean idea; I
think that it is pretty clever, though, so thanks to all involved on that one!)

To me, both the FEM and HDM projects seem to be /quite/ educational, and I
would say that there is room in both of them for students and for experts, as
there is in most mathematical endeavors.

Really, the conception of what is good for students seems very limited, and
seems related to notions of "forced learning" that we all 
[[file:connections between math and programming|seem to agree.org][connections between math and programming|seem to agree]] are not a good
thing.

So, while I'd agree with Karen that HDM and FEM didn't mesh well with being a student
at the University of Texas (which is what I was when I was talking to her about
these issues), maybe they would work great for a student at 
[http://www.ma.utexas.edu/~jcorneli/t/ another sort of educational institution all together].
