#+STARTUP: showeverything logdone
#+options: num:nil

(((Great minds think alike --> Full employment!!! Yeehaw!!!)))


From [http://lists.jacobs-university.de/pipermail/project-omdoc/2008-May/000400.html CFP: DML 2008--Towards Digital Mathematics Library]


    [OMDoc] CFP: DML 2008--Towards Digital Mathematics Library
    dml2008 at easychair.org dml2008 at easychair.org
    Sat May 3 01:16:24 CEST 2008

        * Next message: [OMDoc] CFP: DML 2008--Towards Digital Mathematics Library
        * Messages sorted by: [ date ] [ thread ] [ subject ] [ author ]

    CFP: Towards Digital Mathematics Library (DML 2008)
    July 27th, 2008, Birmingham, UK c/o MKM 2008

    Workshop webpage:
    http://www.fi.muni.cz/~sojka/dml-2008.xhtml

    Deadlines: May 31st: abstract submissions 
               Jun  1st: paper submissions 
               Jun 20th: paper acceptance/rejection decision
               Jun 27th: versions for the proceedings due
               Jul 27th: workshop date, proceedings on site

    Submissions:
    http://www.easychair.org/conferences?conf=dml2008
    Submissions will be refereed on the basis of technical quality, novelty, 
    potential impact for building DML, and clarity. Papers must conform to the 
    Springer LNCS style, preferably using LaTeX2e and the Springer llncs class files.

    Submission categories:
    Full paper: 4-12 LNCS pages
    Short paper/poster/work in progress report: 1-4 LNCS pages 

    Overview:
    Mathematicians dream of a digital archive containing all peer-reviewed 
    mathematical literature ever published, properly linked and 
    validated/verified. It is estimated that the entire corpus of mathematical 
    knowledge published over the centuries does not exceed 100,000,000 
    pages, an amount easily manageable by current information technologies.

    The workshop's objectives are to formulate the strategy and goals of 
    a global mathematical digital library and to summarize the current 
    successes and failures of ongoing technologies and related projects, 
    asking such questions as:
    # What technologies, standards, algorithms and formats should be used
      and what metadata should be shared?
    # What business models are suitable for publishers of mathematical
      literature, authors and funders of their projects and institutions?
    # Is there a model of sustainable, interoperable, and extensible 
      mathematical library that mathematicians can use in their everyday work?
    # What is the best practice for
        * retrodigitized mathematics (from images via OCR to MathML and/or TeX);
        * retro-born-digital mathematics (from existing electronic copy in
          DVI, PS or PDF to MathML and/or TeX);
        * born-digital mathematics (how to make needed metadata and file formats
          available as a side effect of publishing workflow [CEDRAM model])?

    Proceedings:
    will be published by Masaryk University and will be available on site,
    with best papers chosen for postconference proceedings published
    by renowned publisher or for journal.

    Keynote: 
    Thierry Bouche (Universite de Grenoble I, CNRS, Institut Fourier 
    & Cellule Mathdoc): CEDRICS: when CEDRAM meets Tralics

    Topics: 
    (include, but are not limited to)
      o search, indexing and retrieval of mathematical documents
      o ranking of mathematical papers, similarity of mathematical documents
      o math OCR with MathML/TeX output
      o document conversions from/to MathML, OpenMath, LaTeX,
        PostScript and [tagged] PDF
      o conversions between various mathematical formalisms
      o mathematical document compression
      o processing of scanned images
      o algorithms for crosslinking of bibliographical items, 
        intext citations search
      o mathematical document classification, MSC 2010
      o mathematical text mining
      o mathematical documents metadata exchange via OAI-PMH and/or OAI-ORE
      o long term archiving, data migration
      o reports and experience from math digitization projects
      o math publishing with long term archival goal
      o software for creating, handling MathML, OMDoc, OpenMath
        documents, and displaying them in WWW browsers

    Programme Committee:
    (other members upon approval)
      Jose Borbinha (Technical University of Lisbon, IST, PT)
      Thierry Bouche (University Grenoble, Cellule Mathdoc, FR)
      David Carlisle (Numerical Algorithms Group, NAG, UK)
      Thomas Fischer (Goettingen University, Digitization Center, DE)
      Vaclav Hlavac (Czech Technical University, Faculty of Engineering, Prague, CZ)
      Janka Chlebikova (Comenius University, MFF, Bratislava, SK)
      Jiri Rakosnik (Academy of Sciences, Mathematical Institute, Prague, CZ)
      Eugenio Rocha (University of Aveiro, Dept. of Mathematics, PT)
      David Ruddy (Cornell University, Library, US) 
      Petr Sojka (Masaryk University, Faculty of Informatics, Brno, CZ) [chair]
      Masakazu Suzuki (Kyushu University, Faculty of Mathematics, JP)
      Bernd Wegner (Zentralblatt MATH, Berlin, DE)

    Organizing Committee:
      Adam Rambousek, Michal Ruzicka, Petr Sojka, Volker Sorge

    Questions/inquiries:
    to dml2008 at easychair.org

    CFP distribution:
    Please, distribute at your place, if possible.
    Apologies for multiple postings!
