#+STARTUP: showeverything logdone
#+options: num:nil

This page could talk about some theoretical things, like the Moore method and
so on.

* Automatic tutoring
; [http://pact.cs.cmu.edu/koedinger.html Kenneth Koedinger -- Pittsburgh Advanced Cognitive Tutoring Center] :
; [http://www.pitt.edu/~vanlehn/ Kurt VanLehn's Home Page] :
; [http://mnemosyne.csl.psyc.memphis.edu/home/graesser/ Dr.Arthur Graesser] :
; [http://www.cogsci.ed.ac.uk/~jmoore/tutoring/people.html The Tutorial Dialog Group] : (machine tutoring in Physics)

* Automatic problem-solving

Not quite "tutoring", but similar.

; [http://calc101.com calc101.com] : (online automated differentiation and integration, with automatic explaination of the methods used)
; [http://mathulator.com Mathulator.com] : Presumably similar to Calc101.com, below.

* Other software and content

"[http://www.activemath.org ActiveMath] has been engineered according to standard software engineering practices.a It is a rather modular software and some of the components are reusable. ActiveMath has been developed at the DFKI and at the University of Saarland. /It has an open source license for non-commercial applications./"

What's up with this sort of license!!  How wack! --[[file:jcorneli.org][jcorneli]]



*  Meanwhile, in the education community...

Some discussion with Ray about education and mentoring in physics reminds me that this is a topic of general
concern.  I wonder what it has to say in, for example, the work cited here:

Editor's Address: From Adequacy to Excellence: Honoring the
Scholarship of Learning and Teaching, Author: Simpson R.D. Innovative
Higher Education, Volume 26, Number 2, 2001, pp. 83-86(4)
