#+STARTUP: showeverything logdone
#+options: num:nil

(Note: I began a slightly similar discussion at [[file:Outreach to other activist groups.org][Outreach to other activist groups]]
but I mean to take this page in a more general, maybe more interesting, and 
possibly altogether better, although different, direction.)

I started thinking about this topic recently when jolted by two stimuli:

 1. the introduction, out of the blue, of "MathWeb" into my psychic life, and this wiki;
 1. the abstract idea, suggested by me, that PlanetMath might be able to get some substantial support from an organization like the MAA, if we hound them enough.

With !MathWeb, I thought: /Well, it is great to have some discussion and connection
going between people who are interested in "supporting mathematics on the web", that's
swell -- but what about discussion and connection between all of the other people
out there who must be working on math and computers, and AI, and pedagogy, and
linguistics, and free content -- ideally, all the sorts of people who might be
interested in our [[file:Metacommons Manifesto.org][Metacommons Manifesto]] -- but what about even just that
relatively small subset who is really working on substantial meta-level issues
directly related to mathematics?  Why isn't there a webpage or wiki or
mailing list being set up for them?  Certainly "the web" isn't so special that
we should ignore all other mediated mathematical experiences?/

And in response to all of these questions, I was dumbfounded. 

And with the MAA, I thought: /OK, so none of us is located in Washington, so
none of us can show up at the MAA's office to bug them every day -- but maybe
that wouldn't even be the right approach.  We all have phones, and they have
phone numbers, and we can be polite and tactful and, above all, mercilessly
persistent -- and maybe if we keep up the barage of phone calls and suffer
every redirection gracefully, we will eventually find a strong source of
support in this organization./

Who, I might add, really /ought/ to support !PlanetMath and all of the 
other computer-math and generally mediated-math research and experience
that is going on in the world today.  And not just that organization, but
also the other organizations that have some stake in the future of mathematics.

/Now,/ in fact, the [http://www.mathweb.org/ MathWeb homepage] links, prominently,
to a [http://www.mkm-ig.org/ Mathematical Knowledge Management Interest Group homepage]
(which, presumably, is actually maintained by the same people).
The latter looks "closed", "dead", and in every other way insufficient as a point
of actual substantial interesting connection between people.  Just possibly it could
be a vector indication some right direction -- but more likely, it indicates that 
these MKM people haven't got a clue about how to do "live" collaborations, and
wouldn't be intersted in doing them if they could!

Sad day!  This seems to suggest that if we actually wanted to interact with these
people

 1. we would have to change their interests and/or their ways of working
 1. we would have to change our attitude -- and get interested in working with some other group!

I would suggest that in both cases -- so-called "MKM", and traditional mathematics organizations --
we might start by asking ourselves what a good collaboration would look like.  We
could also start by willy-nilly making phone-calls, writing emails, and just generally
tearing the hell out of all available broadcast networks in order to solicit opinions
and interactions from people who we think might have relevant things to say,
either on the basic level of collaboration, or on the meta-level of what makes
a good collaboration.

--[[file:jcorneli.org][jcorneli]] Minneapolis, end of Thanksgiving vacation
