#+STARTUP: showeverything logdone
#+options: num:nil

Finding people to take up our [[file:PlanetMath Code Bounties.org][PlanetMath Code Bounties]] is proving
a bit of a challenge.  This page is for organizing to speed up the
process, using whatever "market means" are available.

Contract work sites we can list bounties on:

 * http://www.e-lance.com
 * http://www.getafreelancer.com

Forums where we could publicize the work:

 * ??

I assume we could also post to varous newsgroups which deal with
programming.  We would want to first check that these newsgroups
permit such posts. --[[file:rspuzio.org][rspuzio]]

There are also math mailing lists; some math profs have CS students
who like making money.  I know one myself who sometimes does; I could
speak with him.  I'm sure that if we put forth a bit of word of mouth
effort, we could get some bounty hunters -- and do a lot to spread the
word about PM.  --[[file:jcorneli.org][jcorneli]]

These are splendid ideas, but lets list these things so they don't
keep slipping away from us!  When we've got a good set of venues we
agree on, we can attack!

Let me also add that we should be sensitive to conventions of various
venues.  Even if solicitations aren't expressly forbidden, we may not
want to "spam" newsgroups with offers for work that most participants
would consider "below" them or otherwise uncompelling. --[[file:akrowne.org][akrowne]]
Fri Feb 24 16:25:06 UTC 2006

Sure, posting job ofers to mailing lists is a tricky business and we
wouldn't want to post something unless we first knew something about
the particular newsgroup well enough to be confident that it would be
received positively.

I would say that we should try these ideas and, if they don't
succeed, do what everyone else looking for a contractor to do a job
does --- take out a want ad.  For instance, we might pay Google to run
an ad for us.  Maybe we might even have an equilibrium situation in
which our revenue from running advertising pays for the cost of
advertising our bounties.  --[[file:rspuzio.org][rspuzio]]
