#+STARTUP: showeverything logdone
#+options: num:nil

First Monday (http://www.firstmonday.org/) is an open-access
peer-reviewed journal about internet-based culture.  It is run by the
University of Illinois at Chicago Library.  Dating to 1996, it is a
pioneering collection of thought about the impact of the internet.

They are having their 10th anniversary conference in may 2006, and are
soliciting contributions.  This page is so Asteroidians can coordinate
submissions and attendance to the conference.

Paper submissions:

 * [[file:First Monday Paper--The Fog of Copyleft.org][First Monday Paper--The Fog of Copyleft]] (Krowne, Puzio)
 * [[file:First Monday Paper--The HDM Manifesto.org][First Monday Paper--The HDM Manifesto]] (Corneli)

----
* Timeline

 * Proposals will be reviewed and contributors will be notified in
December of the special editorial committeey's decision.
 * Completed papers must be received by the first Monday in February
2006 (6 February 2006). This includes papers for which no proposal was
submitted in advance.
 * By the first Monday of March 2006 (6 March 2006), notification will be
sent to those contributors whose papers will be presented at the
conference, FM10 Openness.
 * By the first Monday of April (3 April 2005), contributors to the
special issue in June 2006 will be notified.
