#+STARTUP: showeverything logdone
#+options: num:nil

**  Minimalism

"I am utterly frustrated with the software I have to deal with. Windows is beyond comprehension! UNIX is no better. DOS is no better. There is no reason for an OS. It is a non-thing. Maybe it was needed at one time.

I detest Netscape. I switched to the Internet Explorer even though I detest MicroSoft worse than I detest Netscape. I detest MASM. I discovered MASM clobbers my reserved memory. It says it will respect it but it doesn't. I've tried Word, WordPad, and Edit and they are unusable."
--  Chuck Moore 

http://www.ultratechnology.com/color4th.html

**  Sinners
"My way to/from supermarket was just blocked by thousands of sinners going 
to midnight mass. If they hadn't sinned, they wouldn't need to go!" 

http://twitter.com/alan_kennington

See also Kennington's chef d'oeuvre: http://www.topology.org/tex/conc/dg.html

**  A revelation

"Yes, that was the big revelation to me when I was in graduate school—when 
I finally understood that the half page of code on the bottom of page 13 of 
the Lisp 1.5 manual was Lisp in itself. These were “Maxwell’s Equations of Software!” 

http://www.arcfn.com/2008/07/maxwells-equations-of-software-examined.html

**  A letter of Grothendieck

"Alexandre Grothendieck a malheureusement souhaité que cessent les travaux de réédition de SGA. 
Les pages qui étaient consacrées sont donc closes. 

Dernière actualisation : 2 février 2010. "

http://www.math.polytechnique.fr/~laszlo/sga4.html

Unfortunately Alexandre Grothendieck has wished the reedition of SGA stops. The pages dedicated to
this edition are thus closed.

Last modification: February 2nd, 2010

**  On Hair Color in France  (with Ellen Gilkerson)

"While traveling in France, Gilkerson and I observed many blonde women, but almost no blonde men.  Suspecting that we had stumbled upon a remarkable scientific discovery, we endured several weeks of hardship visiting the auberges and restaurants of France to gather data.  After several years of analysis and rigorous procrastination, we wrote this paper.  Much of our magnificent prose was ruthlessly eliminated by the editor to leave space for less important research."

Leslie Lamport

http://research.microsoft.com/en-us/um/people/lamport/pubs/pubs.html

**  Tortured premises

"Ordinary plane geometry (such as is studied in US secondary schools) holds an irresistible appeal, although many results derive what appear to be unimaginative conclusions from tortured premises. Nonetheless, from time to time something catches our eye and gets us to think about ordinary triangles and circles." -- Dave Rusin

http://www.math.niu.edu/~rusin/known-math/index/51M04.html

**  Telle mère, telle fille

http://arstechnica.com/science/news/2010/01/female-teachers-math-anxiety-influences-female-students.ars

**  A recall

"Some readers may need reminding that numbers are not strings of bits, and 2^33 * 2^33
equals 2^66, not overflow error." -- Lamport "Specifying system p. 7"

http://research.microsoft.com/en-us/um/people/lamport/tla/book-02-08-08.pdf


**  Unhappy customer

"Goddamn it! What I need are third-order existential abstract generalized monadoids, and I cannot believe that Haskell doesn't support this natively!"  -- Mark Vanier blog 17-Mar-2009

http://mvanier.livejournal.com/


**  Mathematics are a science

"euh, aux dernières nouvelles, un corps est commutatif, 
sinon on parle d'algèbre à divisions. Oui, la terminologie a changé en 1996 je crois. 

Remarque, au dernier séminaire Bourbaki (dimanche dernier), 
il y avait encore des algébristes qui se battaient à ce sujet..."  taorendestiny 28-Jun-2005

http://www.ilemaths.net/forum-sujet-42465.html

"Well, according to the latest news, a field is commutative otherwise one 
speaks of division rings. The terminology  changed in 1996 I think.

During the latest Bourbaki seminar (last sunday) I noticed there still were algebraists 
who struggled about this subject..."

[The translation of algèbre à divisions is maybe wrong] 

**  How to improve your people's computer science abilities

"I hasten to add that I am not a hacker. But the Great Firewall is exactly what 
you would create if you _wanted_ a nation of great hackers!" Alan U. Kennington

http://twitter.com/alan_kennington

**  Courses taught by Hausdorff in Leipzig

http://histvv.uni-leipzig.de/dozenten/hausdorff_f.html

**  Alexandre Grothendieck's Favorite Ballad

http://www.youtube.com/watch?v=R0FVm6c-pGI

(According to "The Grothendieck Biography Project")

http://www.fermentmagazine.org/grotsong.html

**  Bolzano and the Austrian police
Les discours de Bolzano ne pouvaient manquer d’enthousiasmer les étudiants qui en apprécièrent l’indépendance et la franchise. Mais les opinions d’un prêtre qui, avec la même droiture, proposa sa vision « utopiste » d’une société fondée sur l’égalité, critiqua la constitution autrichienne, fit de la propagande en faveur de la liberté de penser, se prononça sur le rôle de l’Église et du clergé au sein de la société et ira même jusqu’à mettre en garde les étudiants de théologie contre l’austérité d’une vie de célibat, ne pouvaient pas non plus manquer de déplaire à ses supérieurs et aux promoteurs de la Restauration autrichienne à une époque où, sous le zèle de Metternich, le conservatisme atteignait un nouveau sommet dans l’Empire du Danube. Associé aux prétendues intrigues politiques de son étudiant Josef Fesl[10], Bolzano fut démis de ses fonctions le 24 décembre 1819 et placé sous surveillance policière. Prétextant l’hérésie, on lui fit subir un « procès » particulièrement dégradant qui dura près de cinq ans. Bolzano refusa d’admettre que sa faute eût pu résider ailleurs que dans une « exposition scientifique ou rhétorique incorrecte »[11] et donc de se rétracter. À l’issu de son procès, on lui interdit tout exercice sur le territoire autrichien, interdiction qui, jusqu’à la fin des années 1830, toucha aussi les publications d’ordre scientifique. Contrairement à Fesl, il échappa toutefois à l’incarcération. -- Sandra Lapointe
([http://www.erudit.org/revue/philoso/2003/v30/n1/007729ar.html Bernard Bolzano Contexte et actualité])


Bolzano's discourses couldn't miss out on enthusing his students who appreciated his independance
and frankness. But the opinions of a priest who, with the same rightness, proposed his "utopist" view of a society based on equality, criticized the Austrian constitution, 
gave his opinion on the role of the Church and of the Clergy in the society and 
went as far as to warn away the students in theology against the austerity of celibacy 
couldn't miss out on offending his superiors and the promoters of the Austrian Restoration 
at a time when, thanks to Metternich's zeal, conservatism was reaching 
new heights in the Danube Empire. Associated to the claimed political plots of his student Josef Fes, Bolzano was resigned from
his duties on december the 24th, 1819 and put under police surveillance. He was sued with heresy as a pretext . The trial,
particularly degrading, lasted nearly 5 years. Bolzano refused to accept that his guilt could consist in something else than an "incorrect
explanation either in its scientific or rhetoric aspect". Consequently he didn't accept to forswear. At the end of the trial, he was fordidden to work on the Austrian territory.
This included, up to the end of the 1830s, scientific publishing. Contrary to Fesl, however, he
was not jailed.


**  Yes, sir!

"A computer program is a piece of literature." Knuth ([http://tex.loria.fr/typographie/mathwriting.pdf Mathematical writing] p.21)

**  A hot opinion

David Hilbert soutenait le point de vue formaliste où les résultats devaient être dérivés selon les règles d' une syntaxe mécanique. Des entreprises telles que le projet metamath[55] ou le projet Ghilbert,[56] peuvent donner une idée de cette recherche d'une perfection glacée.[http://fr.wikipedia.org/wiki/Myst%C3%A8re_de_la_v%C3%A9rit%C3%A9#cite_ref-54 source]

David Hilbert upheld the formalist point of view according to which results 
should be derived using the rules of a mechanical syntax. Projects such as Metamath or
Ghilbert can give an idea of such a research for a chilly perfection.

**  The Supreme Fascist
"Erdos believed that God, whom he called the SF (for Supreme Fascist), had an infinitely long Book that contained the most elegant proofs of all mathematical theorems. His colleagues depended on him to produce proofs "straight from the Book." The SF Was always tormenting; Erdos, by hiding his glasses, stealing his plane tickets, or, worst of all, keeping to Himself the, pages of the Book." -- Paul Hoffman

**  An algorithmic success

.>> We can wonder if a human being would be able to produce an
.>> algorithmic source of uncertainness.

.> Windows 95 is a success in this respect.

.                              -- Filh fr.sci.psychanalyse

**  A conjecture

I think sex is more interesting than logic, but I can't prove it.
                                        -- Linux . fortune

**  Mathematic according to Grothendieck

Quand je pense à "la mathématique", ce n’est sûrement pas à la totalité du savoir qu’on peut qualifier de
"mathématique", consigné de l’antiquité à nos jours, dans des publications, des preprints ou des manuscrits et
correspondances. Même en éliminant les répétitions, ça doit faire sans doute quelques millions de pages de
texte compact ; une dizaine de tonnes de bouquins peut-être, ou encore quelques milliers de volumes épais,
de quoi remplir une spacieuse bibliothèque : rien de quoi faire bander c’est sûr, bien au contraire.  -- Grothendieck. Récoltes et semailles p. 545.

When I think to "mathematic", it's certainly not to the totality of the knowledge we can 
qualify of "mathematical", recorded from the antiquity to our days in books, preprints, manuscripts or correspondences. Even if we remove repetitions, it must certainly represent several millions of pages of compact text; ten or so tons of books perhaps, or some thousands of thick volumes, enough to fill up a large library: nothing that makes you have a hard-on, that's sure.

**  A hack

I was talking about this with Bram, and he called ZF set theory a "hack." I more or less agree, but playing with it in the context of Metamath has led me to appreciate how powerful a hack it is. With a small number of relatively simple axioms, it gets you a rich set of infinities, but avoids the particular ones that bring the whole formal system crumbling down. You get integers, reals, tuples, sequences (finite and infinite), transfinites, and functions from set to set. You don't get untyped lambda calculus. Overall, it's probably a good tradeoff. -- Raph Levien's blog 27 Aug 2002

**  Intimidation

When a mathematician writes a text, he has to take good care in order to convince others
of his ideas. He has an arsenal of techniques to do so: by precise formulation, by the use
of natural language and mathematical symbols, and by the use of a well-ordered lay-out. A
mathematical text can also convince a reader by pure intimidation: a proof of a proposition
can be that difficult or impressive that a reader simply takes it for granted. -- G. Geleijnse [http://www.dse.nl/~gijsg/report.pdf Comparing two user-friendly formal languages for mathematics:  Weak Type Theory and Mizar] p. 1.

**  French mathematicians and World War I

The devastation of World War I presented a unique challenge to aspiring mathematicians of the mid 1920's. Among the many casualties of the war were great numbers of scientists and mathematicians who would at this time have been serving as mentors to the young students. Whereas other countries such as Germany were sending their scholars to do scientific work, France was sending promising young students to the front. A war-time directory of the école Normale Supérieure in Paris confirms that about 2/3 of their student population was killed in the war.[DJ] Young men studying after the war had no young teachers, they had no previous generation to rely on for guidance. What did this mean? According to Jean Dieudonné, it meant that students like him were missing out on important discoveries and advances being made in mathematics at that time. He explained : “I am not saying that they (the older professors) did not teach us excellent mathematics (...) But it is indubitable that a 50 year old mathematician knows the mathematics he learned at 20 or 30, but has only notions, often rather vague, of the mathematics of his epoch, i.e. the period of time when he is 50.” He continued : “I had graduated from the école Normale and I did not know what an ideal was! This gives you and idea of what a young French mathematician knew in 1930.”[DJ] Henri Cartan, another student in Paris shortly after the war affirmed : “we were the first generation after the war. Before us there was a vide, a vacuum, and it was necessary to make everything new.”[JA] This is exactly what a few young Parisian math students set out to do. -- PlanetMath article Nicolas Bourbaki

**  A disappointment

There is a romance associated with
these conjectures [ Berge's conjectures about perfect graphs ] that is unparalleled
in the contemporary history of graph
theory. Berge first announced these twin
conjectures at a European conference in
1960, and first wrote them down only in
1963 in a paper surprisingly published at
the Indian Statistical Institute, Kolkata,
where Berge was a frequent visitor for
about two decades. The brilliant Laszlo
Lovász, who was first ‘spotted’ by the
legendary Paul Erdös on one of his customary
visits to Hungarian high schools
to look for nascent talent, resolved the
easier conjecture in 1971. Sadly, Lovász’s
triumph ended the career of D. R. Fulkerson,
who was within a whisker of proving
the conjecture himself till he decided
that the conjecture was false and started
looking for counter-examples. When Fulkerson
received a postcard from Berge
informing him of Lovász’s proof, he
completed his own proof in a matter of
hours! A defeated Fulkerson only lived a
few more months; just long enough to
gracefully acknowledge in a Math Prog
paper that Lovász was the deserving
winner. -- Obituary of Berge by S. Bhogle  

*  Beyond this limit, theres's only private stuff

**  English

http://idioms.thefreedictionary.com/

http://www.wordreference.com/enfr/

http://www.larousse.com/dictionnaires

**  Topology

Topology without tears: http://uob-community.ballarat.edu.au/~smorris/topology.htm

http://www.emis.de/journals/BAMV/conten/vol9/jeanyves.pdf

http://www.iecn.u-nancy.fr/~eguether/archives/bibliographie_Bourbaki.pdf

Topology history: http://www-groups.dcs.st-and.ac.uk/~history/HistTopics/Topology_in_mathematics.html

http://www.halfvalue.com/textbooks-list.htm#Topics_in_mathematics


**  Filters and ultrafilters for betginners

http://at.yorku.ca/cgi-bin/bbqa?forum=ask_a_topologist_2002;task=show_msg;msg=0172

http://arxiv.org/PS_cache/math/pdf/0702/0702587v1.pdf


**  A review of Hausdorff's Grundzüge der Mengenlehre

http://projecteuclid.org/euclid.bams/1183425494

http://projecteuclid.org/euclid.bams/1183492349

**  The genesis of Borel's Covering theorem

http://smf.emath.fr/Publications/RevueHistoireMath/11/html/smf_rhm_11_163-204.html


**  Categories

http://www.cs.virginia.edu/~jlp/po.category.pdf

http://folli.loria.fr/cds/1999/library/pdf/barrwells.pdf

http://www.math.uu.nl/people/jvoosten/syllabi/catsmoeder.pdf

http://math.ucr.edu/home/baez/week73.html

**  Programming

http://en.wikibooks.org/wiki/Haskell/Category_theory

**  Writing

http://tex.loria.fr/typographie/mathwriting.pdf

**  Deletion

To delete a page place "DeletedPage" with a ! in front of the D.

**  My sandbox

[[file:fl's sandbox.org][fl's sandbox]]

**  Earliest Known Uses of Some of the Words of Mathematics

A very impressive site: http://jeff560.tripod.com/mathword.html

**  Dror Bar-Natan's site

http://www.math.toronto.edu/~drorbn/

**  Euclid's geometry

http://arxiv.org/PS_cache/arxiv/pdf/0810/0810.4315v2.pdf

**  Finite set

http://arxiv.org/PS_cache/arxiv/pdf/0809/0809.0105v1.pdf

**  The Heine-Borel theorem

http://www.math.uni-sb.de/ag/schreyer/oliver/calendar.algebraicsurface.net/calendar.php?mode=youTube&day=07

**  Lambda calculus

ftp://ftp.cs.ru.nl/pub/CompMath.Found/lambda.pdf

**  Bourbaki: all the archives and all the redactions of the treatise in their historical order

http://mathdoc.emath.fr/archives-bourbaki/feuilleter.php

**  Kennington's chef-d'oeuvre

http://www.topology.org/tex/conc/dgstats.php

**  Edsger W. Dijkstra's manuscripts

http://www.cs.utexas.edu/users/EWD/

**  Peano : Formulaire de mathematiques

The first volume was published in Turin in 1895. 
The "Formulaire" is one of the sources
for "Principia Mathematica" (as mentionned by Whitehead and Russel in
the first chapter of the first volume p. 5). For instance it is clear that the
order of the chapters of "Principia Mathematica" follows 
the order of those in the "Formulaire".

http://gallica.bnf.fr/ark:/12148/bpt6k84141f.r=Peano.langen

**  Leslie Lamport's Home Page

http://research.microsoft.com/en-us/um/people/lamport/

**  John Savard's home page

http://www.quadibloc.com/main.htm

**  Math 1300Y/427S - Topology

"On an intuitive level, topology is associated with deformability, malleability (excluding from discussion, of course, the tearing and cutting of objects), whilst algebra is associated with rigidity. On this note one is often reminded of how, in topology, a coffee mug is considered equivalent to a doughnut. As we were reminded both in class and on the Course Syllabus, the purpose of this course is to explore the remarkable relationship between topology and algebra."



http://katlas.math.toronto.edu/0506-Topology/index.php?title=Main_Page

**  Algebraic topology ( in French )

http://perso.ens-lyon.fr/nathalie.revol/MEA/NDelanoue-03-02-05.pdf

**  Schützenberger : complete works

http://www-igm.univ-mlv.fr/~berstel/Mps/index.html

**  Harmony == 

http://consequently.org/edit/page/harmony/Home/Proof_Theory_and_Philosophy/Home
