#+STARTUP: showeverything logdone
#+options: num:nil

Although Ben Franklin is rather well known as a printer, writer, statesman, diplomat, scientist, and inventor, it is is not all that well known that he was also an early proponent of free, open source content.  As a matter of principle, he refused to patent any of his numerous inventions such as the Franklin stove, bifocals, swimming fins, or the glass harmonica.  As he put it,

: "As we enjoy great Advantages from the Inventions of others we should be glad of an Opportunity to serve others by any Invention of ours, and this we should do freely and generously."

In addition, he also was also involved in organizing a public library. 

* Discussion
I think the library thing seems quite apropos.  People need
access to information as a first step towards "transparency"
of any sort.  (They also need to know how to read, if books
are to be of any use.)

This note makes me wonder about the history of patents.  If
Franklin was opposed to patenting his own work, maybe he was
opposed to other people patenting theirs too.  I bet there are
some books (still under copyright, even) that talk about 
the history of "IP law" in America (?). --[[file:jcorneli.org][jcorneli]]

After reading some of this history in connection with my contribution to the Emory conference, my guess would be that Franklin pushed for the clause on patent and copyright law in the Constitution.  I would think that, even if he would rather have everything be in the public domain, he would also have recognized that it would be impossible to convince a majority of this point of view, so some compromise would be necessary.  While the constitution does permit patents and copyrights, it does not acknowledge that authors and inventors have a right of ownership to their works (as opposed to all the other rights such as life, freedom of speech, and the like which are mentioned in the constitution) but simply acknowledges patents and copyrights as an incentive which may be used to promote the arts and sciences.  In this respect, U.S. law is completely different from most other countries' laws, and I would suspect that Franklin had a lot to do with this.  

Anyway, this is my guess as to what happened.  However, by reading Franklin's autobiography and looking at documents from the time, one might be able to check this guess or replace it with a more correct statement.  --[[file:rspuzio.org][rspuzio]]
