#+STARTUP: showeverything logdone
#+options: num:nil

In order to make works available to the public and to permit the creation of derivative works which will also be freely available, authors have released works under free licenses.  The legal basis for this practise lies in the the author's right to control distribution and creation of derivative works.  However, to use this right in a way which prevents others from exercising it in the future in order to keep a work free requires a certain amount of legal manouvering; this invariably gives rise to undesirable side effects which can impede the free flow of information.

As an example of a free license, we can take the GNU Free Documentation License.  This is a legal instrument in ten sections, most of which are devoted to ensuring that noone could circumvent the requirement that future versions of the work being licensed be made available on similar terms.  To achieve this goal, it makes use of a system which requires 7 definitions and 15 conditions which govern modifications to the document and makes use of such devices as history lists and invariant sections.  While this may not be overly complex as far as contracts go, it can be overwhelming to the average author who has no experience with law and consequently authors may not comply with all the terms of the license out of ignorance.  This can have devastating results since one of the provisions of the license states that it is not permitted to disseminate copies of the work except as expressly provided by the license and that any attempt to do so will result in termination of the license and, hence, make it impossible to disseminate the work at all.

In an attempt to avoid these Byzantine complexities, the Creative Commons license takes a much starker approach --- it states that derivative works can only be distrubuted under exactly the same license terms, no if's and's, or but's.  While this is easily enough understood, it creates a different problem, "license lock" --- once a work has been licesed under such terms, it and all derivative works are locked into the same license.  This can lead to some unfortunate situations, as the following example shows.   Suppose that an author wishes to make use of two articles in the course of preparing a book and that this use would be in excess of what is permitted by the doctrine of fair use.  Suppose further, that one of these articles was released under a GNU license and the other was released under a Creative Commons license.  Under such circumstances, the author would be no better off than if the articles had  appeared in a journal whose publisher plays copyright agreements close to his vest because the conflicting demands of the GNU license and the Creative Commons license would render the work undistributable.

This situation can appear confusing and paradoxical to a newcomer.  Naively, one would expect that, if an author declares that his work is free, then anyone can to anything which one desires with that work.  However, as we have seen, this is not quite true --- the very mechanism by which free licences are enforced legally places sometimes confusing, sometimes counterintuitive restrictions on authors, creating a "fog of copyleft" through which only those who have made a careful study of free licenses and copyright law or who have access to expert help can safely navigate.  The net effect is to discourage those who are not in such a position (the vast majority) from taking full advantage of the possibilities of free license agreements.

Especially hard hit by this state of affairs are projects like Wikipedia which combines contributions by thousands of authors and is released under the terms of the GNU Free Documentation License.  Since it is safe to say that most contributors will not be familiar with the legal intricacies of free licenses, there is a good chance that users will violate the terms of these licenses unintentionally on a regular basis.  This puts an extra burden on the facilitators of these sites.  In addition to their usual duties, they must educate users on these issues and monitor content to ensure compliance with license terms.  Given that such operations are typically volunteer efforts funded by contributions, this places a hardship on people who have already aassumed a fair load of work on their shoulders.

* Discussion

Back to [[file:Free Math and Potential Bottlenecks.org][Free Math and Potential Bottlenecks]]
