#+STARTUP: showeverything logdone
#+options: num:nil

It is a well-established principle of copyright law that ideas and concepts are in the public domain, exempt from legal protection and free for all to use.  It is an equally well-established principle that the expression of these ideas is entitled to the strictest protection under law [[file:[Free Math and Potential Bottlenecks -- legal basis of free ideas.org][[Free Math and Potential Bottlenecks -- legal basis of free ideas]]] and that authors are entitled to claim recompense for their creativity and control the distribution of their works. [[file:[Free Math and Potential Bottlenecks -- legal basis of royalties.org][[Free Math and Potential Bottlenecks -- legal basis of royalties]]]

Because ideas and concepts cannot be transmitted without somehow expressing them, there is a dynamic tension beween these two principles and the aim of copyright law is to establish a balance between these two conflicting goals which respects both the general public's right to access knowledge and the author's right to be compensated for creative work.  In recent years, this equilibrium has been disturbed by the emergence of computer and network technology which radically changes the nature of the creation, transmission, and storage of information.

The purpose of this essay is to consider some of the effects of this situation in the field of mathematics.  In particular, the author will concentrate his attention on several ways in which provisions of copyright law can impede the progress of mathematics in the age of computers.  It is clear that some restriction of scope was necessary in order to contain the essay within its bounds; the reason for this particular choice are twofold:  First, the author, being a mathematician and having encountered issues of intellectual property law primarily within the context of projects having to do with the use of computers in mathematics, has first-hand personal experience of these issues and of their effects on the progress of the subject on which to draw.  In particular, he has been involved with two projects, Planet Math [[file:[Free Math and Potential Bottlenecks -- Planet Math.org][[Free Math and Potential Bottlenecks -- Planet Math]]] and the Hyperreal Dictionary of Mathematics [[file:[Free Math and Potential Bottlenecks -- Hyperreal Dictionary of Mathematics.org][[Free Math and Potential Bottlenecks -- Hyperreal Dictionary of Mathematics]]], both of which seek to make mathematical knowledge available in digital form under free license terms and provide mathematicians with tools for making use of this knowledge.  In connection with work on these projects he has encountered various situations involving copyright issues which form the basis for the scenarios described in this essay.  Second, mathematics is primarily concerned with ideas and concepts, so these issues manifest themselves in a peculiar form which may not occur in subjects whose primary focus is observable facts or creative expression.

* Discussion

Back to [[file:Free Math and Potential Bottlenecks.org][Free Math and Potential Bottlenecks]]
