#+STARTUP: showeverything logdone
#+options: num:nil

Having expounded a catalogue of woes, the author would like to end is essay on a
more positive note by describing possible remedies to this situation lest theo
reader be abandoned in a quagmire of despair.  This is by no means intended as
an exhaustive list or as a selection of the best proposals, but rather as a
demonstration that the situations described in the preceding sections can be
ameliorated if we, as a society or a subset thereof, are willing to make an
effort to change them and as a starting point for a discussion on plans of
action which will hopefully occur not only at this conference but continue after
we have parted on our separate ways and lead to concrete results.

One remedy would be a reform of copyright law based on a proactive attitude
towards new technology.  As suggested by the examples of bottlenecks, it seems
that the practise of copyright regulation is no longer consonant with the
primary goal of promoting intellectual progress and that the secondary goals of
regulating the publishing trade and enforcing author's rights have overshadowed
the primary goal.  The stance of copyright law towards this emerging technology
may be described as reactive, the primary concern seeming to be the prevention
and circumvention the possibilities of infringement by use of new technologies.
A most distressing aspect of this development has been the tendency to make
copyright a matter of criminal rather than civil law.  As noted long ago by Mo
Tzu and Montesquieu, increases in the severity of legal sanctions are rarely
effective and may be taken as a sign that the government is not able to
effectively deal with a particular menace.  In such circumstances, it may be
wise to pull back and reconsider strategies rather than stubbornly and
mindlessly pursue a hopeless course of action which in the end effects more woe
in the form of collateral damage to innocent, law abiding bystanders than it
averts by thwarting the intentions of the wicked.

Given that computer and network technology in the twentieth century has had at
least as profound an effect on the dissemination, storage, and use of
information as did the invention of printing with movable type in the fifteenth
century, it seems that any legislation-ammending approach which is based upon
the conditions which surronded the use of the older technology is woefully
incommesurate with the end of harmonizing legal practice with the current state
of technological affairs and is hence foreordained to lead to inefficient and
ineffective results--- no matter how skillfully and cleverly such means may be
employed.  Thus, a rational approach to the problem would be to (1) begin with
the basic principles upon which intellectual property law rests, (2) reconsider
the implementation of these in the circumstances afforded by the new technology,
then (3) rebuild the edifice of copyright protection according to a plan which
is consonant with these principles. At the same time, /the secondary goals of
intellectual property must be properly subordinated to the primary goals./

It needs to be borne in mind that application of these laws will increasingly be
made by the authors themselves rather than by specialists, as modern technology
makes it increasingly easier, more efficient and economically feasible for
authors to be their own publishers.  It is not reasonable to demand that all or
most authors invest the time needed to study and master the intricacies of
intellectual property law or hire experts to sort out these intricacies on a
regular basis; as documented earlier, this attitude has the effect that complex,
often counterintuitive regulations serve to envelope the average author in a
"fog of copyright" which can disorient and confuse them, often leading to
disastrous outcomes.  A more helpful approach would be to simplify and clarify
at least those provisions of intellectual property law which arise routinely in
everyday life and create some sort of "easy-filing form" which serves the
everyday needs of author-publishers.  Naturally, they might seek the advice of
professional experts from time to time when more complicated or unusual
circumstances arise, but on everyday matters they could proceed confidently on
their own. Such an approach would respect the valuable time of authors,
copyright professionals, and courts.

Just as copyright evolved from ad hoc contracts between publishers and authors
to public law of license, so too perhaps it is time for free disribution to
graduate from a notion privately defined in various free licenses to one which
is acknowledged and legitimized in public copyright law.  This would offer
several advantages.  In addition to solving the problem of "fog of copyleft",
such an approach would also have the benefit of quelling lingering doubts about
the validity of free licenses and recognizing free distribution as a legitimate
means of promoting intellectual progress.

As we have seen earlier, there is, within the scientific community, a broad
consensus that the progress of mathematical sciences is best served by a
relatively unhampered flow if information.  This attitiude has lead to a de
facto treatment of scientific literature as if it had been released under free
license which clashes with the de jure interpretation which most scientific
publishers cling to.  Such a state of affairs is unacceptable and demonstrates
that copyright regulation is out of touch with its constitutionally sanctioned
goal.  To be sure, the government has a responsibility to ameliorate this
situation, but perhaps the scientific community should take a more active role
by forming a "free math" movement which seeeks to improve the legal climate
within which science operates by such means as supporting resources which make
mathematical knowledge available under free license terms, putting pressure on
publishers to permit alternative modes of distribution, developing means of peer
review and reputation establishment which are not linked to paper journals, and
advising courts and lobbying legislators to take into consideration the
interests of the scientific community.  To be sure, the formation of such a
movement may require mathematicians to leave their comfort zones to assume a
more active stance and require scientific associations to rethink their
priorities, but these sacrifices would be warranted by the gravity of the
situation and the threat posed to the mathmatical progress.

It would help if the legislature were to recognize commons-based peer production
and filesharing as institutions and, just as in the case of such establishments
as restaurants, factories, and apartment houses, regulate these institutuions by
imposing guidelines designed to protect the general public and limiting the
liability of proprietors who follow these guidelines in good faith.  At present,
the only form of regulation, if it may even be called regulation, is through the
judiciary, which is ill-suited to the task because courts can only rule on the
legality of an act after it has been done.  As a result, those involved in
innovative projects have felt unsure of what is legally permissible and of the
limits of their liability, leading them to err on the side of prudence.
Clarifying obligations and liability would lift this cloud of uncertainty and
promote progress by letting pioneers of network-based production proceed with
confidence under an arrangement which protects the interests of all parties
involved.

Before concluding this essay, the author would like to draw the reader's
attention to the observation that, far from being an esoteric matter which is
only of direct relevance to a handful of mathematicians involved in projects
like Planet Math and the Hyperreal Dictionary of Mathematics, the cause of free
access to mathematical knowledge should be of vital importance to all who
cherish the ideal of a free and democratic society.  The very technology which
led to this situation has its foundations in mathematical logic and, indeed, all
off the technology which has become a part of everyday life --- telephones,
automobiles, televisions, refrigerators, electric lighting, washing machines ---
owes its existance to the application the mathematical principles which govern
the workings of the forces of nature.  Since mathematical knowledge is the power
which enables one to create and control this technology, it follows that, in a
highly technological society such as ours, any group which is denied free access
to mathematical knowledge becomes a group of second class citizens.

The reforms suggested above cannot be implemented without a considerable
expenditure of effort.  Even if one disagrees with some or all of these
suggestions, it is doubtful that anyone could come up with a solution which
would not require a significant effort to implement --- the problem is rather
serious with deep roots and there are powerful entites with vested interests in
the status quo who would oppose any efforts at reform.  Any credible attempt at
change will require a movement of a magnitude comparable in size to any of the
great freedom movements.

To build such a movement requires commitment and solidarity.  Those who are
concerned about this issue cannot afford the luxury of assuming that someone
else will take care of the problem or succumb to the illusion that they lack the
skills necessary to contribute but need to contribute in whatever capacity they
can --- whether by documenting the situation and offering scholarly analyses or
by preparing legal challenges and defending authors or by making knowledge
available under free terms or by writing free computer programs or by
publicizing the cause or by speaking out against abuses.

Success in such a campaign will entail uniting members of different intellectual
communities --- scientists, lawyers, educators, artists, philosophers,
historians, librarians, writers --- under the banner of a common cause in a
manner which respects the differing, sometimes conflicting opinions of its
members.  But, though necessarry, this alone will not be sufficient --- the free
culture movement must reach out to society at large and, if not gain mainstream
attention, at least enter the mainstream of the counterculture. Free access to
information has much in common with other freedoms; free culture activists have
much to gain by dialogue and collboration with other activists. In addition, it
will be necessary to form alliances with those businesses and officials who are
sympathetic to the cause.  Only in this manner will it be possible to obtain the
leverage needed to effect the reforms required.

In the final analysis, the only real bottlenecks are apathy and division.  If we
allow them to constrict the flow of knowledge, we will have only ourselves to
blame for the resulting intellectual drought and will rightly deserve the
condemnation of posterity.

* Discussion

Yay!! A 111 word long sentence!!!!  

The folks in the copyright office might do well to listen to what their
neighbors in tax department say:

"As our nation moves forward in this still young century, the Internal Revenue
Service will focus on three areas of tax administration:

 * Improving taxpayer service;

 * Enhancing enforcement of the tax law; and

 * Modernizing the IRS through its people, processes, and technology.

Our working equation at the IRS is simple: service plus enforcement equals
compliance. Not service or enforcement, but service and enforcement. We must do
both in a balanced and consistent manner, with full respect for, and attention
to, taxpayer rights." Mark W. Everson, commissioner of the IRS

It seems that copyright has gone overboard in the direction of enforcement with
the result that authors increasingly see that their interests and rights are not
respected or even paid attention to.  As mentioned in the essay, the issue of
modernization has not recieved due attention in the reactive stance which
characterizes contemporary intellectual property law.

Since the original version has been changed since, I've copied it here so that
Aaron's coments and my replies will make sense:

Just as copyright law originated from ad hoc licenses granted to publishers, so
too perhaps it is time for the notion of free texts and programs should graduate
from a notion privately defined in various free licenses to a notion which is
publically defined in copyright law.  This would offer several advantages.
First, it would put the matter on a more certain footing.  Since free licenses
are a relatively new phenomenon and have not been tested in court, one cannot be
certain to what extent their provisions are legally binding and enforcable
Consequently, some people have shied away from using them in favor of other
arrangements.  Writing the notion of free distibution into law would
definitively clear up any lingering doubts as to legal status.  Second, a
uniform standard would do away with the sorts of inconveniences due to
copmaptibility issues of different licenses whichg were cited earlier.  Third,
an official definition of "free", "open source", and "transparent" would no
longer allow hucksters to fool the public by using these terms in twisted senses
and thereby ruin the intended sense of these terms --- in fact, it would turn
the tables on disreputable closed-source businessmen by making it possible to
sue them for misrepresentation if they use these terms to describe products
which do not conform to recognized standards of freeness and openness.

Ok, here are my comments:

 1. The GPL has been /sorta/ tested in court --- once, a German judge
[http://www.icetalk.com/gpl-gains-clout-in-german-legal-case-N2520.html forced compliance] with the license terms, and another time, a U.S. judge explicitly
[http://library.findlaw.com/2003/Jun/16/132811.html made the assumption that the GPL was a valid copyright license] at the hearing stage.

 1. Eben Moglen has [http://gnu.open-mirror.com/philosophy/enforcing-gpl.html pointed out] that nobody has been serious enough about the GPL being illegal
to actually challenge its legality in court.  This isn't for lack of companies disliking the
GPL or even making public announcements claiming its non-validity (cough SCO cough).  The point is, when anyone
rational actually sits down and reads the license when considering and planning legal action,
they give up challenging it.  Thus, it seems like it will prove pretty solid when it finally 
is challenged.
 1. I wonder what could really be enshrined in law to explicitly permit free licenses.  
Copyleft isn't something built outside of the copyright system -- it depends upon it.  It also
doesn't "detract" from copyright (as Moglen himself oddly claims).   Copyleft is merely the
name for a combination of license requirements predicated upon copyright.
 1. Instead, I think the real emphasis should be upon usability, comprehensibility, flexibility,
and prolificness of free licenses.  This is what I think is so great about the Creative
Commons project--- it addresses all of these points.  A buffet of free licenses useful for 
a variety of common situations is provided, then explained in simple, /natural language/, 
their compatibility with other licenses and scenarios made clear, and conventions provided
for naming, notice, and handling of various license interactions.

--[[file:akrowne.org][akrowne]] Thu Jun 30 03:19:20 UTC 2005

I am glad to see that this portion of the essay is already beginnning to serve
its purpose as a starting point for discussions before it is even fully written!

Certainly the proposal I present here is new and controversial; I am not even
sure I agree with it myself completely but, in the spirit of continuing the
discussion and exploring possibilities let me respond.  My primary reason for
making the proposal is not that I have any doubt that the goal can be achieved
by means of free licenses but that I see this proposal as an efficient means for
acieving the same goal which sidesteps difficulties which I see as intrinsic to
the current approach which seem to be giving rise to a "fog of copyleft" despite
the intentions of those involved.  Let me structure my argument as a reply to
your comments:

1,2.  I agree with you and Mr. Moglen that free license agreeements are
fundamentally sound legally as preliminary results suggest.  To be sure, there
might be some provisions which may be struck down in court, but I would think
that this would be a minor issue.  Nevertheless, there is widespread
apprehension about free licenses, especially in the business community.  While
my proposal would adress this issue, it would certainly not be worth considering
if this was the only reason for considering it --- this apprehension could be
dealt with more directly through education and other methods.  I simply listed
it a first because this reason occurred to me first.  Whlaw ile this may be good
chronological order, it is a poor rhetorical order, so I will change this in the
text.

3.  In this point, methinks you sound like the theorists whom you and Lessig
reject :) I will argue that, while the law contains all that is needed to create
free licenses, there is still a familiar problem --- just because copyright law
enables you to do something doesn't mean that it necessarily enables you to do
it in a simple way which is intuitive to the average person and which is free
from undesirable side effects.  As I understand it, bottlenecks like the ones I
described in the section on incompatible licensing terms are a necessary feature
of any attempt to construct a free license using only the legal tools which one
now has available so the law would need to be modified to allow free licenses
without such side effects.

4. While I agree with your emphasis on usability, comprehensibility, and
flexibility, I am not sure that these goals can be completely realized under the
current state of affairs.  Let us examine the goals of free licenses and how
they are achieved.  One goal is to permit free distribution and use of the work
in question.  This is easy.  All the copyright holder has to do is to waive
certain rights, which means stating that, although one is entitled to these
rights, one chooses to waive them instead.  The other goal is to ensure that the
work stay free in all its future incarnations.  This entails imposing
restrictions not only on authors who base derivative works on the work in
question, but also restrictions on anyone who should base a work on these
derivative works, et cetera ad infinitum aut terminum validitatis licentiae.
Pulling this off in an uncircumventable way by writing a recursive license using
3only a copyright holder's right to grant permission to create derivative works
and the standard tools of contract law is a feat of legal engineering worthy of
a Goedel, but this accomplishment comes at the privce of undesirable side
effects.  As one can see, the bulk of the GNU license is concerned with this
point and, in order to cover loopholes, it includes provisions such as what to
do with history lists when combining documents which confuse most users and, as
a consequence are often not carried out.

By contrast, the Creative Commons approach embodied in the "share alike" clause
is simplicity itself.  This is achieved by an application of Bourbakian scissors
to cut out the complexities of the GNU license --- derivative works can only be
distrubuted under exactly the same license terms, no if's and's, or but's.  This
would be all well and good if this were the only free license in existence.
Unfortunately, it is not, so authors can be left in a paradoxical situation
where, although two works are free, one is not free to combine them because they
were issued under incompatible license terms.  One might try to fix this by
relaxing the condition that the derivative work be released under an identical
license to its being released under a similar license or under a free license,
but that opens a bag of worms because it means that you not only need to define
what a similar license or a free license is in terms precise enough that they
cannot be circumvented, but also make sure that such a license contains such a
definition.  Well, to do this, you need to craft a legal behemoth of fine print
no shorter than the GNU license, so we're back at square one!

To conclude, I would say that, with the tools current copyright law provides,
one is forced to choose between complexity and "license lock".  Neither
alternative is satisfactory, and both contribute to the same "fog of copyleft"
in different ways.  The only way out I can think of would be to modify copyright
law so that one could write free licenses which are free from these side
effects.  --[[file:rspuzio.org][rspuzio]] 30 June 2005

I yet again changed the wording after Aaron pointed out to me the disadvantages
of a situation in which there would be a dichotomy between "copyright" and
"copyleft".  Hopefully, the successive approximations will converge soon.
--[[file:rspuzio.org][rspuzio]] 30 June 2005


I did a copyediting pass. --[[file:akrowne.org][akrowne]] Fri Jul 1 17:29:44 UTC 2005

Thank you.  Please don't be dismayed that I am adding material which I had
already thought out, but haven't had the chance to write down yet.
--[[file:rspuzio.org][rspuzio]] 1 July 2005

Originally, I was going to offer Joe's common carrier suggestion, but the
Supreme court blew that possibility out of the water the other day so I salvaged
what was left as the regulation proposal.  --[[file:rspuzio.org][rspuzio]] 1 July 2005

I think the common carrier (for CBPP projects) idea still needs to be pushed---
an ad hoc decision by the supreme court can still be remedied by specific
legislation. --[[file:akrowne.org][akrowne]] Sun Jul 3 22:38:22 UTC 2005

I agree completely.  However, it will require a pretty big push to squeeze such
a law through and I am not sure that anyone *right now* has the strength to pull
this off.  There seems to be prevalent attitude in government today (the Supreme
court and the Copyright office are both unanimous about it) that websites like
Napster and Grokster are completely unacceptable and that an agressive policy of
copyright enforcement is the only way to keep such disasters from happening
again.  In such an environment, the common carrier idea is likely to be
dismissed without serious consideration, especially since those proposing it
would not have much political influence.  Therefore, a more fruitful srtategy
 *for the short term* might be to work towards gaining official recognition of
CBPP even if it means making some compromises with respect to the "hands off"
policy.  As I see, a reasonable compromise would be to say that if an
organization does as we at Planet Math have done --- post a policy which states
that infringing posts are not allowed, offer suggestions and guidelines to
authors so as to help them avoid infringing on somebody's copyright, and make a
reasonable effort to monitor the site for compliance --- then that organization
is guaranteed limited liability for the actions of users who post material which
they have no right to post and is under no obligation to take more drastic
measures such as installing filtering routines into their programs or hide new
posts on a queue until they have been thoroughly vetted for compliance with
copyright laws.  While such an interpretation seems in line with the Supreme
Court's verdict, we would all breathe easier if it were written into law.

At the same time that I propose this I would like to emphasize that *in the long
term* we should not be content with compromise, but should push for genuine
reform and never lose sight of our ultimate goals (such as common carrier
status).  In fact, the greatest danger is, that if we obtain a partial victory,
people may not feel inclined to keep working towards a real solution which deals
with such issues as the "fog of copyright".  It is not fair for CBPP
organizations to assume the brunt of the responsibility of making sure that
their members comply with confusing and counterintuitive regulations even if
they willingly accept such a compromised position in order to gain official
recognition.  Here, time should help.  On the one hand, we will have time to
organize and make alliances with like minded individuals and organizations.  On
the other hand, it will give CBPP organizations to show that they are, by and
large, composed of hard-working, law-abiding citizens who are concerned with
advancing learning in a democratic way by creating intellectual content and
making knowledge available to the general public not some spoiled brats who
simply wanted to obtain for free entertainment which they could have easily
bought or done without.  --[[file:rspuzio.org][rspuzio]] 5 July 2005

I feel like I'm just getting here at the end of the talk and leafing through the
overheads when people are gathered around chatting with the speaker.  Vacation!

A few comments in spite of their tardiness:

 1. Ray is talking about changing laws to reflect actual behavior.  Aaron, you and
I have both read about this in the De Soto book, "The Mystery of Capital"
(mini-summary: [http://www.pbs.org/wgbh/commandingheights/shared/minitextlo/int_hernandodesoto.html here]).

 1. It seems sort of strange that the Civil Rights movement and the Labor movement
(etc.) would be concerned with legal change, whereas AFAIK, the Free Software
movement is not extremely concerned.  When it is concerned, it is conservative:
don't let software patents become a reality and so forth.  This seems sort
of weird.  It also seems risky.  As in the "Union against Unions" example on
the [[file:free culture as a labor issue.org][free culture as a labor issue]] page, opposition to progressive movements
can be much more advanced than the progressive movements themselves, and can
(preemptively) set them back quite a ways.

 1. In addition to the fogs you are talking about, I'd like to say that I think
that law is one big miasma to me.  So much overlayed complication!  Centuries
of legal thought!  And, then, people (and government agencies) don't always follow
the law, so there is the complexity of actual behavior.  As if copyright
law wasn't enough, there are plenty of other legal issues to consider.  It
is a real mess.  Ray's comments about people taking the law into their own hands,
so to speak, by publishing their own material with their own licenses makes
sense, given this massive body of complexity.  The only problem with this
approach is that from an enforcement point of view, these ULAs are actually
overlayed on top of the rest of the law, so while they can simplify things
in some ways (e.g. by creating a virtual college of GPL users), the legal 
situation can only become more complicated.  This is quite a tangent away from
the topic of the paper, however it ties into the historical investigation
theme from this Part.  It also relates to the [[file:scholium system.org][scholium system]], since
we might well want a Hyperreal Dictionary of Law around if we were to try
to get to the bottom of the legal (and economic) issues that connect to
this topic.

--[[file:jcorneli.org][jcorneli]] Thu Jul 07 00:35:00 2005 UTC

I would say that there are three main reasons why attitudes have been so conservative on this issue and there has been more reaction than action.  First, most people, even some people involved in developing the new technology, did not take the possibility that this technology would revolutionize publishing in the immediate future seriously and hence did not worry its legal implications.  As late as 1980's, the possibility that internet distribution would replace the printing press seemed like science fiction --- sure, most people thought that it would happen, but very few thought that it would happen soon.  Remember that, in 1980, the internet was only available through comuter labs at universities and research institutes and only supported protocols such as e-mail and ftp.  Printers and display devices with a resolution sufficient for typesetting were rare and expensive and most personal computers did not have enough storage space for more that a few books.  It would only be a decade later or so that the web would come out, but initially that was designed as a means for phycisists to collaborate.  However, within a few years of the invention of the web, the internet was opened up for private use and web browsers became a household item.  In the meanwhile, printing and storage technology had improved dramatically so that the average person could afford a system capable of producing text of a quality comparable to that of a book.  Since this change took place in a few years, publishers were surprised and only had time to react to the development.  Likewise, people interested in free software (and more generally, free intellectual content) reacted to the reactions of industry.

Second, I am not sure that most people who are interested in free intellectual content are convinced that legislation is needed.  They may think that undoing some of the more extreme laws passed in the past few years would suffice and have not given serious thought to the possibility that copyright law as it was on the eve of the digital revolution may not have been all that conducive to their cause.

Third, to work on legal change requires foresight and organization.  One needs to take time to consider the situation and and anticipate developments so as to propose suitable laws.  One needs to put effort into to lobbying and builingd coalitions so as to get the legislation enacted.  I am not sure that the proponents of free intellectual content are  sufficiently aware of themselves as a movement or sufficiently organized to undertake legislative action yet.
--[[file:rspuzio.org][rspuzio]] 14 July 2005

----

Back to [[file:Free Math and Potential Bottlenecks.org][Free Math and Potential Bottlenecks]]

----

I am using the rest of this page as scratch space for raw material which will become a bibliography.

http://library.findlaw.com/2003/Jun/16/132811.html
http://72.14.207.104/search?q=cache:tIzFgGp-z0YJ:www.irs.gov/pub/irs-pdf/i1040ez.pdf+1040EZ&hl=en&client=firefox-a
http://arxiv.org/help/endorsement.html
http://arxiv.org/blurb/pg02pr.html
http://en.wikipedia.org/wiki/Sony_Corp._v._Universal_City_Studios
http://polaris.gseis.ucla.edu/pagre/conservatism.html
http://caselaw.lp.findlaw.com/scripts/getcase.pl?court=US&vol=499&invol=340
http://www.eff.org/IP/P2P/MGM_v_Grokster/key_quotes.php
http://www.ludism.org/mentat/
http://64.233.161.104/search?q=cache:poaiHy1nm9EJ:home.imaginet.co.za/liasa/DARCH2001.rtf+shrinking+public+domain&hl=en&client=firefox-a
http://www.library.csuhayward.edu/staff/asoules/copyright_public_domain.htm
http://www.serendipit-e.com/blog/2005/06/an_odd_way_to_b.html
http://www.utsystem.edu/ogc/intellectualproperty/tex2.htm#fn1
http://digital-law-online.info/patry/patry5.html
http://www.lxny.org/welcome.html
http://research.yale.edu/lawmeme/modules.php?name=News&file=article&sid=1720
http://www.intellectual-property.gov.uk/std/resources/copyright/history.htm
http://grapez.blogspot.com/2004/10/yes-virginia-there-is-compilation.html
http://en.wikipedia.org/wiki/Copyright-free
http://www.edu-cyberpg.com/Internet/copyrightleft.html
http://arl.cni.org/info/frn/copy/timeline.html
http://www.funnystrange.com/copyright/bridgeman.htm
http://www.umuc.edu/distance/odell/cip/links_fairuse.html#commentary
http://www.umuc.edu/distance/odell/cip/links_fairuse.html
http://www.utsystem.edu/ogc/intellectualproperty/gslis.htm
http://www.ludism.org/mentat/GinsengHigh
