#+STARTUP: showeverything logdone
#+options: num:nil

Here are a few ideas about fun things to do.  They are microprojects you can do
on your own, and they are "free culture" in the sense that anyone can do them if
they like, and you can share the results of your efforts with others too!
Another title for this page could be "things to do on a rainy day", except some
of these things may require sunlight.

* Build a Hipster PDA

I learned about this on Sacha Chua's page: so I'll just refer
you [http://sacha.free.net.ph/notebook/wiki/HipsterPDA.php there] for now.  I've been using my new model to take notes
on the scholium paper as I rewrite it.  Good stuff.

I've designed a game to be played with HPDAs; I call it "[[file:Hipster The Gathering.org][Hipster The Gathering]]".

* 10 Books Club

As some of you know I don't have very many books.  Less than 10, I'm
pretty sure.  I kind of like it that way.  I also like to read and accordingly
I spend a fair amount of time at the university library.  But I don't
typically talk to the people in the library a lot: bummer, considering
that we've been talking about classical libraries as "social spaces".
I was thinking about a book club that would fit my budget and give
me a chance to talk to other people: the 10 books club is what I came
up with.  Here's how it works: you have 10 books that you pick from
your collection (if your collection is size 10 or less, you're done).
You then find someone else in the club (you may have to prosthelytize).
You then swap /one/ of your books for /one/ of their books.  You can
talk about these books (or other things).  The only rule is that you
must then swap with 9 or more other people before you can swap with 
that person again.

* Developing mnemonics and learning strategies

Math "means" learning, etymologically speaking, but people don't spend a whole
lot of time talking about the theory of learning in introductory math classes.
Presumably some of this theory has been integrated into the various math
curricula, and some of it is probably found in books on education, whereas other
elements of the theory are actually just common sense.  But we should try to
make the theory explicit, especially if we are going to develop ways of doing
"forced learning" (I mean this by analogy to forced growth of seeds, not in the
usual sense of forcing people to go to health class or whatever).  Mnemonics are
one (generally agreed to be useful) example: they aren't just about memorizing
insane quantities of digits of Pi, but also about finding your way around the
psychic spaces you work your way into when giving a talk, or developing a proof,
or even just finding your way around town.  They are one particular kind of
heuristic.  If you were really good with mnemonics, you mightn't need a PDA :)
(see above).

So, given that we think these things are valuable, maybe we should start playing
with them - and with other mental exercises, with of goal of fun and a little
self-betterment on the one hand, and a goal of theoretical inquiry on the other.
Developing good strategies for learning should help both with the construction
of the HDM (teaching the machine) and with the use of the HDM (teaching
ourselves).

* pop culture poetry readings

Gather for reading song lyrics (e.g. stuff by the Eagles, Public Enemy, etc.).
People don't listen to the lyrics enough. --[[file:jcorneli.org][jcorneli]] Tue Jul 19 16:17:36 2005 UTC

* More...

I was pretty sure I had another idea today, but I don't recall what 
it might have been.  Sorry! --[[file:jcorneli.org][jcorneli]] 

Ooh, I remembered it :). --[[file:jcorneli.org][jcorneli]] Sun Jun 19 18:23:14 2005 UTC
