#+STARTUP: showeverything logdone
#+options: num:nil

The individual [[file:Projects.org][Projects]], so far, seem to have given reasonable
descriptions of their associated goals on their own pages.

We can add to that discussion here - maybe taking it in a "meta" direction,
like, what are our over-all goals? - but something else I think we should
talk about some are personal goals... to the extent that these relate to
our work here.

See also [[file:the way of the asteroid|this page.org][the way of the asteroid|this page]].

*  akrowne

My general goals are (in rough order):

 * to do whatever I can to make the PlanetMath project fiscally sustainable.
 * to get myself "out of debt" relative to the project.
 * to be compensated something reasonable for my continuing work on the project.
 * to pull in enough resources to do some research and development around PM, Noosphere, and CBPP.
 * to gradually shift to making this work my primary work (maybe).

[[file:Discussion of akrowne's goals.org][Discussion of akrowne's goals]]

*  jcorneli

So, I'll kick this off by saying that one of my goals - financial, more
than personal - is to be making about $1400 a month (before taxes).  My actual living
expenses are only about $625 a month, but the extra money above would cover
things like loan repayment, building a small savings, and a modest travel
budget. If possible, I'd like to make this money either working on things related to the
AM projects, or at least doing things that don't take too much attention away
from the AM projects.  

My other -- main -- goal is to make the HDM project "happen".  I would
like to live to see this and other amazing hyperreal things - accordingly,
I try to [[file:Activities|work hard.org][Activities|work hard]] and lead a fairly healthy lifestyle.  As insurance against the 
chance event of my dying before I have the opportunity to download my mind and/or
my consciousness into a computer, I would like to find human successors to the
helm of HDM who will see it through to its glorious conclusions.

These include: the destruction of academia and the publishing industry (as we know
them), and perhaps a few other social institutions (like, "reality", for example);
increased social welfare throughout the world via first-rate economic analysis;
and mechanized immortality (as above).  Of course, some of these things go a bit
beyond the official goals of the HDM project.

Lately, another "personal" goal is to get a better sense of the [[file:Plans|timeline.org][Plans|timeline]]
for completion of various activities.  I hope to structure my time in such a way that
my goals and objectives are met... or restructure them appropriately (i.e.
I seek to live according to [[file:the way of the asteroid.org][the way of the asteroid]]).

[[file:Discussion of jcorneli's goals.org][Discussion of jcorneli's goals]]
