#+STARTUP: showeverything logdone
#+options: num:nil

On the way back from Atlanta, I took a stop in Roanoke, Virginia, for the night.

Last night, I took the do-it-yourself commons-based approach to lodging. I went to Mill mountain (the hill overlooking the city), pitched my tent, and slept there.  It was a really gorgeous night with a full moon and fleecy white clouds gently passing by an otherwise clear sky.  One could clearly see Taurus, Auriga, and the Pleiades --- the variosly colored stars, from cherry red Anatares to the hot blues looked like gems against a dark sky; through the trees they looked like Christmas lights.

After a refreshing sleep in the fresh (if chilly :) ) mountain air, I woke up and went for a walk arount the surrounding woods.  As usual, I couldn't help but think about math and what not on my stroll --- while enjoying the woods, I also made some progress in my theories of dialectic and monadology.

Then I headed to the library, where I am on the computer now typing this story.  The building I'm in (appropriately enough, situated by Jefferson street) is a pretty good example of the sort of library-as-institution whic Aaron speaks of.  People come in and out of here to all sorts of things, such as fill resumes, read newspapers, browse books, research, post to and read from (real and virtual) bulletin boards, etc.

One of the things that I have always loved about Roanoke is the cool people I have met there and the fact that, from time to time, the place has transformed from your typical town into a vision of a commons-based freedom.  

One time, when I stopped by here a few years ago on the way to Memphis, it was evening and I hung oug in the town square.  There were a lot of people there, just hanging out in the street, talking, playing or listening to music, and what not.  I took out [[file:my bugarabu.org][my bugarabu]] and started playing.  Pretty soon, other people came to listen.  Some bystandwers also joined in and pretty soon we had a nice little drum circle going.  Later on, I joined an impromptu jazz band as precussionist.

On another visit, there was a street party.  Since the street in front of the main coffee shop was closed to traffic due to road work, so people spontaneously decided to put it to a different use.  They were drawing chalk art on the street, dancing in the street, and what not.

Because of visiting here so many times (it used to be more frequent in the past), I have gotten to know some of the people here.  In fact, once, some of the kids I met while hanging out in the street offered to put me up for the night.  A night easily turned into a week, and when the car broke down and I was waiting for it to be fixed, into the better part of the month during which my unofficial home was Roanoke.

That month was one of the best months of my life!  I had deep conversations on philosophical topics with various people, went to an awesome poetry slam, not to mention all the music.  

At least a few years ago, there used to be a significant part of the population which had a laid-back, tolerant attitude.  For instance, once when I was hanging out in a small shop on the square, a girl went by wearing black lace (i'm not sure how to desribe it --- let's just say it's quite far from typical business attire).  The person with whom I was having the conversation explained she was a paralegal (I think, or maybe some other sort of professional) and that people were cool with the way she dressed and even appreciated it.  As she put it, here you could walk around with a melon on your head if that's how you felt.  It would be viewed as your own personal expression --- to each his own.

When I finish here at the library for the time being (I may come back later for another session, depending on circumstances) I will head downtown.  There a good number of [[file:small shops here.org][small shops here]], run by interesting people with whom I have become friends.  Once, one of them let me put up some shirts I dyed in her shop on commission.  Also, there is the Peace and Justice center and the food co-op where I plan to go soon.

* Discussion

Sounds like you've explored Roanoke way more than I have.  Maybe you should consider Virginia Tech for your next faculty position =) --[[file:akrowne.org][akrowne]] Wed Oct 19 14:03:38 UTC 2005

Plans for going to Virginia for more than just visits will have to wait since, for the forseeable future, I need to stay in the New York area on account of the house.  Also, it might be worth mentioning the sad fact that, should I move to Roanoke in a few years, it is quite likely that the cultural features I mentioned above might be little more than quaint historical oddities by that time.  While the "outdoor block parties" I mentioned above seemed to be a regular feature around 2000, I haven't seen any more of them on any of my visits in the last two years.  To be sure, Roanoke is still a nice place to be, some of the shops and "alternative institutions" are still around and I see some of the people whom I first met a few years ago but, overall, the alternative culture / counterculture / free culture which I so enjoyed seems to be fading away.  Not just in Roanoke but also elsewhere; for instance, in the few years I lived there, I saw midtown Memphis degenrating from a vibrant and growing local centre for alternative culture to a typical urban setting; likewise I saw similar changes elsewhere. --[[file:rspuzio.org][rspuzio]]

I am back in Roanoke for the same reason again.  In the brief time that I stopped through, I manged to put up and hand out a good number of free culture flyers and talk to people about the issue.  I plan to be back here in a week.  --[[file:rspuzio.org][rspuzio]] 5 December 2005

Neat - keep us posted.  Also, can you tell us what sorts of posters
you're putting up?  Maybe others'd want to do the same thing or
suggest additions/changes for yours.  Your experiences with Roanoke
remind me of my experiences at New College of FL.  I think
that that place is also changing (particularly because the college
has a policy of "growth", which I think is risky).  But it is
still probably small enough to be managable for a poster campaign.
I suppose that I might also be able to make something of such
a campaign around here (in MSP) but I'm not sure what objectives I'd
have for such an operation. --[[file:jcorneli.org][jcorneli]]

: The flyers are some orange posters about DRM from the demonstation with Stallman in NY a few weeks back.  By now, I have distributed about 1000 copies all over the south; hopefully that will get the message out.  For future attempts, it would be nice to make some of our own flyers, leaflets, posters and what not with contact information, but this time there was no time to make any up so I wenty with what I had.  Overall, the message was well recieved --- people had heard of what DRM can do through the grapevine and were appreciative of the information.  -- [[file:rspuzio.org][rspuzio]]

On the way back (see previous note) I am passing through Roanoke again after a busy week with various collaborations --- the first few days I was in Memphis working on fractional calculus with my co-authors and then I went to Atlanta to work on the "fog of copyleft" article with Aaron.  I was busy and am now rather tired from the overwork, the hours of driving, and the lack of rest, but it was definitely a productive trip.

When I left Atlanta, the last place we went was the local food co-op to buy food and drop off flyers.  (I was also glad to see that the poster I put on a downtown bulletin board a week ago is still standing.)  Before I came here to the library, I was at the Roanoke food co-op for lunch and to drop off the remaining flyers.  I am quite happy when I come across places like the little five points neighborhood in Atlanta or what I found in Roanoke where I see people trying to implement a free, commons-based approach to living.  While I'm disappointed to see that such approaches to life seem to be declining (they all but dried up in Memphis :( ) in the current political and ideological climate, I (have likely located most of them in the South during the last few years (and of course, there's the Village in NY, where the LISP club happens to meet) and) am more than willing to support these oases of sanity as I can and have hope that this trend will turn around.  In fact, maybe we can even help turn it around by combining real-world and virtual efforts.  (Admittedly, that's rather optomistic but, if I wasn't succeptible to grandiose dreams, I wouldn't be involved with HDM either ;) )  For instance, I was talking half-seriously with Aaron about filling our virtual solar system with a comet website which would be some sort of alternative travel guide which could help people locate offbeat place like this and discuss their experiences.  At any rate, I see that making people with like interests in diverse places aware of each other should be very helpful in making it easier for them to work together and go along way to overcoming frustrating loneliness and the concomittant feelings of helplessness. --[[file:rspuzio.org][rspuzio]] 11 Dec 2005
