#+STARTUP: showeverything logdone
#+options: num:nil

For now, there really isn't any "per se".  We may get one (or if we're
really lucky, more than one) summer internship paid for through Google
Summer of Code.  I personally think that this is a great model for
free software development, and I'd like to thank Google and !LispNYC for 
helping the HDM project network with interested people (if nothing else - but don't
get my hopes up about the money for nothing guys come on!).

It would be cool to "institutionalize" this grant in some way, see
[[file:Grant planning.org][Grant planning]].

Other than that... well, additional sources of funding are in the works
(you know, the free software business model, yeah!).  You've got to be a little
patient.  Don't quit the day job.  Or, as would probably be more accurate for
the HDM staff at present, don't quit the night job - or get a job - or
something!  Anyway, good luck guys... yow!

Seriously, if anyone has any bright ideas about how to make more money
in the short term (or long term), please come forth.  My last good
idea was an April Fool's joke! --[[file:jcorneli.org][jcorneli]]


----
The fact that we can't prove that the HDM will "work" shouldn't
stop us from getting funding.  Working on somewhat "out there"
stuff is valuable!  Some relevant discussion is [[file:Logical positivism and social welfare|here.org][Logical positivism and social welfare|here]].

----
On the other hand, as long as we can work well as an all-volunteer
operation, we shouldn't worry too much about money.  See this
[[file:a poor target for its own fundraising|microessay.org][a poor target for its own fundraising|microessay]] for some comments.
Presumably we need to balance between "just doing our work" and looking
for money.  If we don't follow up on either, we'll get nowhere (which would
be terrible!).  The various routes available to us are only attractive insofar
as we get things done by going along them.  My sense is that money will
be easier to come by when we have a more established project, but 
I'm not completely sure.  This is definitely a source of some tension
for me.

One recent thought, related to [[file:Outsourced Fundraising and Nonprofit Services|something.org][Outsourced Fundraising and Nonprofit Services|something]] that Aaron was talking about, and also to our post-SOC discussion about building a free content consortium,
is the idea of trying to become part of a "fund" that supports various free software projects monetarily.
I was just talking at dinner with a woman who works in city government, and who is
encouraged by here department to donate to one of several "funds" that the city
works with.  I'm not sure if there are matching donations or what, but it seems
sort of likely.  The different funds give employees different things to choose
from, some mainstream, some kind of weird.  If free content was hooked into
some such fund, we might well find some supporters in industry, government,
academia, etc.
