#+STARTUP: showeverything logdone
#+options: num:nil

From [http://yro.slashdot.org/yro/05/08/10/008228.shtml?tid=146&tid=192&tid=17 today's slashdot]
an article on DRM'ed ebooks.  It isn't so much the fact that these ebooks are DRM'ed that bothers me - it is 
the idea that every acceptable textbook may be DRM'ed, which means that people will be able to write free textbooks etc., until they are blue in the face,
but the education-publishing complex won't have anything to do with them.

If true, this is further evidence that education (in the sense of diplomas)
has been cornered by info oligarchs.  

But in the course of the debate a number of interesting and potentially helpful
links came up, e.g., [http://www.lightandmatter.com free physics textbooks at http://www.lightandmatter.com], http://theassayer.org, http://freetechbooks.com, http://techbooksforfree.com (I don't know how many of the books listed are actually FAIF tho). 

Still, I think that these things are a drop in the bucket.  Its sad, but
I think that unless things like [[file:NCT.org][NCT]] become "mainsteam", education
will be owned by Microsoft/Elsiver/Google, etc.; another good reason
to [[file:free_culture_as_a_labor_issue|rebel now.org][free_culture_as_a_labor_issue|rebel now]]. --[[file:jcorneli.org][jcorneli]]
