#+STARTUP: showeverything logdone
#+options: num:nil

* Informal workshops and workshop-like activities

 * [[file:Meetup - Washington DC April 2 to 11 2006.org][Meetup - Washington DC April 2 to 11 2006]]

* Discussion

* New

We will likely have a meeting around May 15 2006 in Chicago, IL.

** Old
Note: maybe we should plan some sort of workshop around the time of the  [[file:Emory Free Culture and the DL Symposium|Emory conference.org][Emory Free Culture and the DL Symposium|Emory conference]]. I should be available from [[file:2005-10-14.org][2005-10-14]] through the afternoon on  [[file:2005-10-20.org][2005-10-20]].  Will
others be able to make free time during this time, for informal mini-classes, pair (or group) programming, general hackfests, and so on and so forth?
Even people who aren't presenting at the conference might like to be involved with something like this.
Of course, there would probably be some costs (food, housing, work space, arranging these; misc. opportunity costs), but probably some of these costs 
can be defrayed or absorbed in various convenient ways.  What I wonder is whether we would be
able to come up with things that we could usefully fill the time with.  Thoughts? --[[file:jcorneli.org][jcorneli]]

I'm game.  Not sure how to organize things, though.  Anyway, I doubt we'd have any
trouble filling up the time--- even if we just end up chatting informally the entire
time.  One idea, if we can't think of any way to do anything useful on our collaborative
efforts, would be to talk a little about what we are all working on in our "other" (i.e.
non-AM) lives. --[[file:akrowne.org][akrowne]] Thu Jul 14 05:37:37 UTC 2005

That's a great idea!  (In my case, there are only a couple of things I've left off of AM - but they could be kind of interesting :).)  It may be
too early to schedule everything in any kind of detail, but that would be one thing that would be well worth
including.  We might want to circulate the idea a bit further (PM collaborators, HDM collaborators, conference participants, invited friends, others?) and make a page to begin sketching the vague outlines of a Plan. --[[file:jcorneli.org][jcorneli]]

I don't want to commit to anything before I am sure, but if circumstances allow me, I would certainly be willing to take you up on the idea of spending some time on our collaboration around the timew and place of the conference. --[[file:rspuzio.org][rspuzio]]


An acadmic workshop or symposium needs a fair bit of lead time, something on the order of 6-9 months, if one wants a reasonable attendance.  One needs a venue.  The easiest way is to get a participating faculty member to approach his/her home institution who is usually quite happy to allocate space (esp. if the meeting is done in the summer months).  Some institutions/departments will even kick in a bit of cash.  One then charges participants a registration fee, which is used to cover workshop expenses and to create a bit of a slush fund to help people with fewer resources to cover their expenses.  In this regard, a sponsor, like a university, an institute, or even a commercial entity is very useful.

One idea along these lines is to approach Wikimedia to organize a symposium on free encyclopedias.  This would provide a gettogether  opportunity for the planetmath community.

Regarding the emory symposium, I could stay an extra day, but probably not more. --[[file:rmilson.org][rmilson]] 14 July 2005
