#+STARTUP: showeverything logdone
#+options: num:nil

There are at least three phases to this letter-writing campaign.

 1. [[file:identifying letter recipients.org][identifying letter recipients]]
 1. [[file:drafting letters.org][drafting letters]]
 1. [[file:sending letters.org][sending letters]]

It would be good to get a lot of people involved in 
all three steps.  Participation of PM folks in identifying
letter recipients and drafting letters that will work
well for those particular recipients could be key to
the success of this endeavor.

One "meta" task is to understand our
[[file:goals for sponsorship relationships.org][goals for sponsorship relationships]].

* The basic goal of the campaign

To get PM involved with sponsors.  These could be organizations
or individuals, who would support PM through financial or 
non-financial channels.

An organization that doesn't want to sponsor PM directly may still be able to
help us network with people who do want to help.

Some potential sponsors might be more interested in other AM projects (like the
[[file:FEM.org][FEM]] or [[file:HDM.org][HDM]]) and we should seek to involve these people, too.

** Some ideas for "support options"

 * monetary donations (w/ or w/o strings)
 * in-kind donations
  * publishing
  * hardware
  * advertising
  * services
  * food, tshirts, beer
 * letters written in support of specific grant proposals
 * help writing grant proposals
 * coding work
 * content creation
 * using the content and/or code
 * involvement in oversight (advisory boards, !AsteroidMeta, email conversation)
 * locating further/different forms of support
 * (?) ... add your ideas

See also: [[file:Goals.org][Goals]], for more discussion of things that we would /like/ people
to help with.

**  What we can offer

 * Links on a Sponsors page
 * specially tailored content or services
 * [[file:Hosting homework solutions.org][Hosting homework solutions]]
 * you name it, right?

* Progress

 * this page was created.
 * the three maint steps have been turned into links

I think that we should /heavily/ advertise this campaign on PM once it has
been sketched out a bit more.

----

See also: [[file:Potential PM supporters.org][Potential PM supporters]], [[file:How to contribute to PM.org][How to contribute to PM]]
