#+STARTUP: showeverything logdone
#+options: num:nil


* Citation

   	Bentley, Arthur Fisher, 1870-1957.
  Linguistic analysis of mathematics, by Arthur F. Bentley.
  Bloomington, Ind., The Principia press, inc., 1932.
  xii, 315 p. front., diagrs. 23 cm.
  	
  CALL NUMBER: 	QA9 .B4

* Comments

I took a look at Bentley's book in the library today.  I was tired, and it is
pretty long, and I only had about an hour to read, so I didn't get through the
whole thing.  My sense was that any linguistic theory of mathematics would be
"dumb" to leave out certain of the things in that book - however, I didn't seem
to gain any earth-shattering insights from my perusal.  Which is not to say that
I think the book is a "bad read" - indeed, I'd say that the opposite is probably
true.

To sum up, to me this book is an "useful addition" of the library of anyone
working on the linguistics of mathematical writing, and it would be worthwhile
for such persons to become familiar with the ideas from the book.

The style was somewhat metamathematical, but also somewhat "metaphysical".

It is interesting to imagine what Bentley might have done if he had a PC
available to him when he was working on this book.  Indeed, in some ways the
style of the writing seemed fairly "contemporary", which was kind of
interesting.  

Some of the /layout/ aspects of the book were very old-school - and, indeed,
kind of interesting (specifically, remarks were unlabeled, but in a smaller
font, which I thought was fairly keen looking).

Looking around on the web, it seems that Bentley is primarily known for his
sociological writings.  (A topic that not at all unrelated to the HDM!)  If
he was alive today, we'd very likely wish to email him about the HDM project!
Given the actual state of affairs, the best we can do is check out his book
a bit more, and be aware of his work, people who he has inspired, and
people who are doing similar things..

Note that I didn't see any citations of the work in mathscinet (maybe there
are some elsewhere!)...  his manuscripts are listed
[http://www.indiana.edu/~liblilly/lilly/mss/subfile/bentleyinv.html here]],
there is a memorial with lots of excepts is
[http://www-personal.monash.edu.au/~dpalmer/bentley.htm here], and
an overview on some apparently somewhat well philosophical/epistemological
work with John Dewey is described [[file:http://www.transactionalview.org/essays/essays.html#WITV here.org][http://www.transactionalview.org/essays/essays.html#WITV here]].
This theory is summed up on that site as follows:

: The trick to transaction is to start with a unitary process or situation that
is both durational and extensional, and to then inquire into the aspects and
phases that may be distinguished within this situation.

I.e., I think, elements of systems are considered relative to the systems within
which they exist, and the "systems" point of view takes precedence.

But I'm very much a novice to this stuff!


Another quote, 

: The notions food-eaten and eater-of-food are co-defining, and make sense only
together, as cooperating partners within the act of eating.

from [http://www.transactionalview.org/essays/TV1200Words.html this overview-summary]
reminds me of our discussion of mutually-dependent "definition clusters"
(specifically, in mathematics, but, as seen here, in any aspect of formal thought).
--[[file:jcorneli.org][jcorneli]] Thu Apr 14 07:38:30 2005 UTC
