#+STARTUP: showeverything logdone
#+options: num:nil

I think it would make sense to display "Latest Rejections" 
in the same way as "Latest Additions", "Latest Revisions"
on the main page. 
This way, all users can verify that the rejection is valid. 
Another thing one could consider is that owners should not be allowed to accept 
a correction without changing the entry. Nor should they be 
allowed to check the correction without offering some 
revision comment. 

.. and a small nuisance. In the "file correction" page, 
it would be helpful if the title would be 

:  File a correction to <entry name>

and not simply

:  File a correction

This is sometimes useful when filing corrections to muliple entries 
simultaneously. 
--- [[file:matte.org][matte]] 20 April 2005


When you say that

: This way, all users can verify that the rejection is valid.

what do you envision happening if the rejection is not OK?

Also, if you're going to display Latest Rejections, it would
make sense to also display Latest Corrections, wouldn't you say?
--[[file:jcorneli.org][jcorneli]] Wed Apr 20 16:36:38 2005 UTC

I usually
usually don't bother to file another correction if someone rejects a correction. 
However, if the latest rejections were displayed on the front page, 
they could at least be read by more than the owner of the object. 
You can currently read all the corrections at
http://planetmath.org/?op=globalcors
They are sorted by date. --[[file:matte.org][matte]] 21 April 2005

I guess I'm pointing out that there is a "bug" in the PM design - but it is so
obvious a bug that everyone treats it as if it was a feature - and indeed maybe
it could be a feature, someday.  But, for now, this "bug" is: people can just
reject any correction!  So, what's the point of even giving corrections, one
might ask.  Usually, people do accept them, which is good.  So I guess that's
the point.  But still, I think the PM design could be made more robust vis a vis
rejections.  I think that the system you are talking about would actually help a
lot, because people could be held accountable for their corrections and their
rejections.  If the rejection looks really dumb, probably someone else would
submit a second correction.

This could go on forever (perpetual check :)) which would be stupid, but it is
still an improvement over the current system.

So, I'm definitely behind this idea.  I think that more work could be done to
actually alleviate the bug (e.g. using the card-based system to slam people who
reject reasonable corrections with a yellow card, for example), but your
proposal - I think - should be part of any working solution.

And, PS, I know about the corrections page, but (a) I don't really like the
interface; and (b) I think it would be nice to have one uniform style of "feed"
for every useful kind of editing event that takes place on the site.
But these sorts of layout issues are much more minor than actual data issues
like the one you pointed out.
--[[file:jcorneli.org][jcorneli]] Thu Apr 21 08:09:40 2005 UTC


Just to point an example why this is a good idea. I've been sending correctiosn
that get rejected (!GeraW and vmoraru). AS a particular example, !GeraW has some
entries where he defines or mentions things which the only references are his
own papers, baptizing them with their smarandache friends names. I ask him for
adding more references that support the use of such namings, but they get
rejected,

 * http://planetmath.org/?op=getobj&from=corrections&id=6399

Now, I'll keep filling them until he slips and object goes to the bin, but
having such list would help me not to miss the day when he rejects my
corrections. Perhaps it'd be useful if more people would send dupe corrections
to these kind of entries so they can never get marked as clean. --[[file:drini.org][drini]]


I don't really want to get involved in the dispute at this point, but maybe you
should make a page over at the [[file:PlanetMath_Writer's_Club.org][PlanetMath_Writer's_Club]] talking about the
entries you find objectionable, and stating why you feel the way you do about
them.  I get the sense that there are many entries, and that submitting repeated
corrections is not necessarily the most effective way to resolve any issues that
there may be with these entries.  A page describing the grievances could be
quite useful for future reference. --[[file:jcorneli.org][jcorneli]] Thu Apr 21 22:10:50 2005 UTC

One cool idea would be to have new entries (maybe also corrected entries, 
new messages, 
and rejected corrections) available under RSS. 
This would be useful mainly for contributers. One would not need to load PM just
to find that there are no new entries. 
--[[file:matte.org][matte]] 07/2005

I like the idea of making rejections more visible.  I'll think about how to pull this off.
Unfortunately
the next major PM thing I have to do is migrate the system to planetx.  However 
we're getting close to being able to offer bounties, so maybe things like this can get
coded up soon!

Another interesting idea might be to allow people to vote on corrections.  Enough "yay"
votes would somehow increase the criticality of the correction, while "nay" vote would
decrease it.  I'm not sure how this could manifest... maybe the more "yay" a correction is,
the more it would be highlighted, and maybe with more "nay" than "yay" votes, it could be
allowed to sit indefinitely (and hidden "below the line"). 

--[[file:akrowne.org][akrowne]] Wed Jul 27 15:58:27 UTC 2005
