#+STARTUP: showeverything logdone
#+options: num:nil

 Articles of incorporation/scope & scale of the project
 (crossover text)
 
 Scope & scale (and maybe name of the Org) depend on hwat we want to do with the software.
 
 There is some overlap between portals and user interests.
 To some degree, users may be able to say how money is spent.
 (Members maybe more.)
 
 Noosphere is common resource to all Planets
 
 Math Research & PlanetMath
 Content management system
 HDM is CBPP project (as well as a research project)
 PM/Noosphere
 Latent vs actionable/explicit knowledge
 
 What is the role of research on PlanetMath?
 Cf. articles of incorporation
 
 Actual research within the subject (coordinating
 research using the tools), vs research that is being
 used to do the sites.
 
 R&D
 
 Something to check proofs is a tool that mathematicians
 would use to help them do math.
 
 (Interesting overlap between content & meta levels.)
 
 How does the similarity & difference relate?
 
 What does the community say about HDM?
 
 Do we fund it piecemeal, or do we fund it with salaries?
 
 Buildung - work to keep the organization running,
 compare work on the HDM research.  ("Organizational
 aspect".)  Also, buildung for making Noosphere
 better!
 
 Some of the things we deliver are research reports,
 some are code.
 
 What we get paid for depends on what there is demand
 for!
 
 Everyone on PM would presumably want to be paying for
 HDM, as long as we can come up with deliverables.
 
 Defined work & deliverables should be pitched to
 the community.
 
 Programs vs projects.  Program component: running
 the organization or running the site.  Projects:
 developing CBPP, developing tools.
 
 Outside applications.  ACMq.  Math/CS researcher.
 Steve Ross-Talbut.
 He is doing math research applied to computing
 & business software.  He knew he had to had support
 for research to do the problem.  Could he have a company
 that would have a sustainable relationship -- to
 sell things but continue to do research.  All of
 the core software is Open Source.  The company is
 the steward of the software; it is a research shell.
 There is another company that does the business
 end.  The research group does consulting for the
 other.  Pi calculus as applied to computing problems.
 pi4tech. 
 
 Can we apply this sort of thing with PM?
 Have someone else run the big business who does
 the nice interface & markets it to industry.
 
 FEM is an easy sell.  (Has a retail outlet.)
 
 We can pitch our platforms to groups like AMS, MAA.
 
 Both the high-techness and the opensourceness are selling points.
 
 Convey the idea that our stuff is compatible with the
 way research works.  
 
 Helps mathematicians.
 
 Stand-alone autolinker would be a "neat" thing to show
 to mathematicians.  Shows defined terms & undefined
 terms.
 
 R&D has timelines & deliverables associated with it.
 
 Research can be firewalled from business/marketing end.
 
 Resolutions?
 
 Membership, fundraising, philanthropists.
 Individuals & institutions.
 Giving money, establishing relationship.
 (Maybe a paid voting membership is a way to keep people involved?)
 Work like a co-op?
 Donor list.
 
 Setting up a member _relationship_ makes people important.
 
 Sliding scale, bonus offerings if you pay more.
 We would want a lot of benefits to be able to charge a lot.
 
 Time to money conversion.
 
 (/ 60 10) 6
 
 Microsoft does time-to-dollar matching.
 What companies do this?
 
 What users work for these companies?
 Can we recruit users from companies that do this?
 
 Joe: sound out the council of nonprofits to see
 what we can put together.   Ask them what we should
 be doing?
 
 2 years
 
 August is a time to get more hope or concretions.
 
 Joe: talk to people about HDM grants.
 
 Question: How do decisions get made?
 
 Can we put something pre- to the whitepaper
 onto the email list.
 
 The licensing questions!
