#+STARTUP: showeverything logdone
#+options: num:nil

/Questions like these will be discussed/:

Open source projects have assumed an important place in our society.
Several academic mathematics projects including MathDL, WeBWorK and   
the MathForum follow this model.  Several open source non-academic    
projects such as PlanetMath and Wikipedia have made mathematical      
information widely available to the general public.  The panel will   
discuss what open source projects exist and what are they doing. What 
other opportunities are there for open source projects in the         
mathematics community?  Is there a way that academics can have their  
open source work recognized in the university setting?  How can it  
affect promotion and tenure decisions?  How can open source projects  
assure the reliability and stability of the materials they produce? 
How do the review processes used in open source projects stack up    
against the traditional peer review process?  What can we learn from  
previous interactions between working mathematicians and              
non-academics?  What incentive and/or business models would encourage 
productive relations between these mathematical constituencies?

/I suggest we get started right away!/ --[[file:jcorneli.org][jcorneli]]

----

* Discussion
