#+STARTUP: showeverything logdone
#+options: num:nil

R616914.
  Study arithmetics, book 8; teacher
guidebook. Mathematics and life, book 2;
teacher's guidebook. By F. B. Knight, J,
W. Studebaker & Gladys Tate. NM:
additions. © 14Oct48; AA103397. Scott,
Foresman and Company (PWH); 31Oct76;
R616914.

R622863.
  Modern school geometry. By John R.
Clark, Rolland R. Saith & Raleigh
Schorling, revisions prepared by authors.
NM: revisions. © 20Feb48; A22233. John
R. Clark (A) & Marie O. Schorling (W);
22Dec75; R622863.

R622877.
  Workbook in mathematics. Book 2. By
Raleigh Schorling, John R. Clark, Rolland
R. Smith & Francis G. Lankford, Jr.
© 2Feb48; AA37739. Marie O. Schorling
(W), John R. Clark & Francis G. Lankford,
Jr. (A); 22Dec75; R622877.

R622878.
  Workbook in general mathematics. Basic
course. By Raleigh Schorling, John R.
Clark & Francis G. Lankford, Jr.
© 2Jan48; AA74967. Marie O. Schorling
(W), John R. Clark & Francis G. Lankford,
Jr. (A); 22Dec75; R622878.

R622879.
  Modern-school geometry; answers and key.
By John R. Clark, Rolland R. Smith &
Raleigh Schorling. NM: revisions.
© 29Jun48; AA92710. John R. Clark (A) &
Marie O. Schorling (W); 22Dec75;
R622879.

R622880.
  Modern-school geometry; teacher's
manual. By John R. Clark, Rolland R.
Smith & Raleigh Schorling. NM: revisions.
© 2Aug48; AA92711. John R. Clark (A) &
Marie O. Schorling (W); 22Dec75; R622880.

R623274.
  A Guide to the use of statistics. By
James W. Knowles & Harry H. Hutzler.
(Reading course in executive technique,
section 1, book 5) © 31Mar48; AA39975.
Funk and Wagnalls publishing company, Inc.
(PWH); 7Jan76; R623274.

R623661.
  Hydrogen in metals. By Donald P. Smith.
© 10Dec48; A28299. Margaret Smith (W);
24Dec75; R623661.

R623897.
  Hydraulics. By Horace W. King, Chester
O. Wisler & James G. Woodburn. 5th ed.
© 2Feb48; A21081. Sarah W. Lepard & John
F. Wisler (C of Chester O. Wisler), James
G. Woodburn (A); 9Jan76; R623897.

R623899.
  Elements of stability calculations. By
Edward Wilson Kimbark. (Power system
stability, vol. 1.) © 20Feb48; A21322.
Edward Wilson Kimbark (A); 9Jan76;
R623899.

R624962.
  Working with numbers. Book 4. By James
T. Shea. © 31Mar48; AA122643. James T.
Shea (A); 29Jan76; R624962.

R624986.
  Reviewing intermediate algebra. By
Isidore Dressler. © 1Oct48; A28784.
Amsco School Publications (PWH); 30Jan76;
R624986.

R625068.
  Fundamentals of electric waves. By Hugh
Hildreth Skilling. 2nd ed. © 24Aug48;
A24807. Hugh Hildreth Skilling (A);
30Jan76; R625068.

R625495.
  Beyond the atom. By John De Vries.
© 22May48; A22975. Sophie De Vries (W);
9Feb76; R625495.

R627219.
  Numerical calculus: approximations,
interpolation, finite differences,
numerical integration and curve fitting.
By William Edmund Milne. © 2Feb49;
A29842. Henry B. Milne (C); 27Feb76;
R627219.

R627395.
  Mathematics for home and business. By
William L. Schaaf. © on additions &
revisions; 21Feb49; A30598. Copeland
and Lamm, Inc. (PWH); 1Mar76; R627395.

R627430.
  Introduction to topology. By Solomon
Lefschetz. © 2Feb49; A29840. Alice B.
Lefschetz (W); 3Mar76; R627430.

R627717.
  A Modern course in trigonometry. By
Alfred Hooper & Alice L. Griswold.
© 19Mar48; A16714. Holt, Rinehart and
Winston (PWH); 4Mar76; R627717.

R627718.
  Our numberland. By Elda L. Merton.
© 12Mar48; AA39543. Holt, Rinehart and
Winston (PWH); 4Mar76; R627718.

R627719.
  Our numberland; teachers edition. By
Elda L. Merton. © 19Mar48; AA77661.
Holt, Rinehart and Winston (PWH); 4Mar76;
R627719.

R627737.
  First year college mathematics with
applications. By Paul H. Daus & William
M. Whyburn. © 11Jan49; A29076. Daphne
H. Dans & Marie B. Whyburn (W); 4Mar76;
R627737.

R627739.
  Intermediate algebra for colleges. By
Paul R. Rider. © 8Feb49; A29861. Paul
R. Rider (A); 4Mar76; R627739.

R627749.
  Chemical calculations. By J. S. Long &
Harold V. Anderson. 5th ed. © 21May48;
A22858. Frank J. Anderson (C); 4Mar76;
R627749.

R627750.
  Practical astronomy. By Jason John
Nassau. 2nd ed. © 11Jun48; A23321.
Sherwood Nassau (C); 4Mar76; R627750.

R627751.
  Applied descriptive geometry problem
book. By Frank M. Warner & Clarence E.
Douglass. © 29Apr48; AA82823. Cornelia
E. Warner (W); 4Mar76; R627751.

R628211.
  Papers of the Michigan Academy of
Science, Arts, and Letters. Vol. 32.
Editors: Eugene Stock McCartney & Henry
Van Der Schalle. © 27Aug48; AA91337.
Henry Van Der Schalle (A); 29Mar76;
R628211.

R628331.
  Physics, a basic science. By Elmer E.
Burns, Frank L. Verwiebe & Herbert C.
Hazel. 2nd ed. © 23Apr48; A22505.
Litton Educational Publishing, Inc. (PWH);
15Mar76; R628331.

R628332.
  Technical descriptive geometry. By
William Ezra Street. © 10Sep48; A25293.
Litton Educational Publishing, Inc. (PWH);
15Mar76; R628332.

R628333.
  Applied mathematics for engineers and
scientists. By S. A. Schelkunoff.
© 1Nov48; A28062. Litton Educational
Publishing, Inc. (PWH); 15Mar76;
R628333.

R628336.
  Answer book for problems in Physics, a
basic science, second edition. By Elmer
E. Burns, Frank L. Verwiebe & Herbert C.
<pb id='139.png' n='1976_h1/A/3145' />
Hazel. NM: additions & revisions.
© 9Aug48; AA92268. Litton Educational
Publishing, Inc. (PWH); 15Mar76;
R628336.

R628337.
  Workbook for use with Physics, a basic
science. By Elmer E. Burns, Frank L.
Verwiebe & Herbert C. Hazel. NM:
additions & revisions. © 31Aug48;
AA93747. Litton Educational Publishing,
Inc. (PWH); 15Mar76; R628337.

R628651.
  Introduction to the differential
equations of physics. By L. Hopf,
translated by Walter Nef. NM: translation.
© 25Mar48; A22930. Dover
Publications, Inc. (PWH); 23Feb76;
R628651.

R628684.
  Economics: principles and problems.
Vol. 1 & 2. By Paul Fleming Gemmill &
Ralph Hamilton Blodgett. 3rd ed.
© 28Apr48; A22249. Paul Fleming Gemmill
& Ralph Hamilton Blodgett (A); 23Feb76;
R628684.

R628874.
  An Introduction to mathematics. By
Alfred North Whitehead. NM: corrections &
redrawn diagrams. © 9Dec48; A59725.
Harriet Whitehead (W); 5Mar76; R628874

R628890.
  Numbers we see; teacher's ed. By Anita
Riess, Maurice L. Hartung & Catherine
Mahoney. © 11Feb49; A30352. Scott,
Foresman and Company (PWH); 5Mar76;
R628890.

R628891.
  Teacher's guidebook for Your mathematics.
By George E. Hawkins & Gladys
Tate. © 25Feb49; AA110182. Scott,
Foresman and Company (PWH); 5Mar76;
R628891.

R628907.
  Heat conduction: with engineering and
geological applications. By Leonard Rose
Ingersoll, Otto Julius Zobel & Alfred C.
Ingersoll. NM: revisions. © 25May48;
A23020. Alfred C. Ingersoll (A);
10Mar76; R628907.

R629411.
  Numerical methods of analysis in
engineering; successive corrections. By
Linton E. Grinter. © 21Feb49; A30390.
Linton E. Grinter (A); 25Mar76; R629411.

R629412.
  Plane geometry. By F. Eugene Seymour &
Paul James Smith. NM: additions &
revisions. © 21Feb49; A30393. Hazel D.
Smith (W), Paul Smith (C of Paul James
Smith) & Frances E. Clark (C of F. Eugene
Seymour); 25Mar76; R629412

R630103.
  Mathematics of finance. By J. B. Linker
& M. A. Hill. © 26Apr48; A22411. Holt,
Rinehart and Winston (PWH); 29Mar76;
R630103.

R631050.
  A First course in algebra. By N. J.
Lennes & J. W. Maucker. 2nd revision.
© 18Jan49; A29196. J. W. Maucker (A);
9Apr76; R631050.

R631054.
  Number play: a number readiness book.
By Mae Knight Clark & Laura Cushman,
illus. by Joanne Adams. NM: new & rev.
material. © 8Mar49; AA109950. Mae
Knight Clark & Laura Cushman (A); 9Apr76;
R631054.

R631303.
  Arithmetic we use. Grade 3. By Leo J.
Brueckner, Foster E. Grossnickle & Elda L.
Merton. 1948 ed. © 6May48; A22403.
Holt, Rinehart and Winston (PWH);
16Apr76; R631303.


R631304.
  Arithmetic we use. Grade 4. By Leo J.
Brueckner, Foster E. Grossnickle & Elda L.
Merton. 1948 ed. © 30Apr48; A22404.
Holt, Rinehart and Winston (PWH);
16Apr76; R631304.


R631305.
  Arithmetic we use. Grade 5. By Leo J.
Brueckner, Foster E. Grossnickle & Elda L.
Merton. 1948 ed. © 28Apr48; A22405.
Holt, Rinehart and Winston (PWH);
16Apr76; R631305.


R631306.
  Arithmetic we use. Grade 6. By Leo J.
Brueckner, Foster E. Grossnickle & Elda L.
Merton. 1948 ed. © 29Apr48; A22406.
Holt, Rinehart and Winston (PWH);
16Apr76; R631306.

R631307.
  Arithmetic we use. Grade 7. By Leo J.
Brueckner, Foster E. Grossnickle & Elda L.
Berton. 1948 ed. © 29Apr48; A22407.
Holt, Rinehart and Winston (PWH);
16Apr76; R631307.


R631308.
  Arithmetic we use. Grade 8. By Leo J.
Brueckner & Foster E. Grossnickle. 1948
ed. © 6May48; A22860. Holt, Rinehart
and Winston (PWH); 16Apr76; R631308.

R631430.
  Arithmetic for young America, revised
edition; teacher's manual. Grade 3. By
John R. Clark, Ruth I. Baldwin & Caroline
Hatton Clark, with the cooperation of
Monica M. Hoye. NM: revisions &
corrections. © 3Jan49; A29505. John R.
Clark & Caroline Hatton Clark (A);
14Apr76; R631430.


R631431.
  Arithmetic for young America, revised
edition; teacher's manual. Grade 4. By
John R. Clark, Ruth I. Baldwin & Caroline
Hatton Clark, with the cooperation of
Monica M. Hoye. NM: revisions &
corrections. © 3Jan49; A29506. John R.
Clark & Caroline Hatton Clark (A);
14Apr76; R631431.


R631432.
  Arithmetic for young America, revised
edition; teacher's manual. Grade 5. By
John R. Clark, Monica M. Hoye & Caroline
Hatton Clark, with the cooperation of Ruth
I. Baldwin. NM: revisions & corrections.
© 3Jan49; A29507. John R. Clark &
Caroline Hatton Clark (A); 14Apr76;
R631432.

R631433.
  Arithmetic for young America, revised
edition; teacher's manual. Grade 6. By
John R. Clark, Monica M. Hoye & Caroline
Hatton Clark, with the cooperation of Ruth
I. Baldwin. NM: revisions & corrections.
© 3Jan49; A29508. John R. Clark &
Caroline Hatton Clark (A); 14Apr76;
R631433.


R631434.
  Arithmetic for young America. Grade 3.
By John R. Clark, Ruth I. Baldwin &
Caroline Hatton Clark, with the cooperation
of Monica M. Hoye. NM: revisions
& corrections. © 3Jan49; A29511. John
R. Clark & Caroline Hatton Clark (A);
14Apr76; R631434.


<pb id='208.png' n='1976_h1/A/3168' />
R631435.
  Arithmetic for young America. Grade 4.
By John B. Clark, Ruth I. Baldwin &
Caroline Hatton Clark, with the cooperation
of Monica H. Hoye. NM: revisions
& corrections. © 3Jan49; A29512. John
R. Clark & Caroline Hatton Clark (A);
14Apr76; R631435.

R631436.
  Arithmetic for young America. Grade 5.
By John R. Clark, Monica M. Hoye &
Caroline Hatton Clark, with the cooperation
of Ruth I. Baldwin. NM:
revisions & corrections. © 3Jan49;
A29513. John B. Clark & Caroline Hatton
Clark (A); 14Apr76; R631436.


R631437.
  Arithmetic for young America; revised
ed. Grade 6. By John R. Clark, Monica R.
Hoye 6 Caroline Hatton Clark, with the
cooperation of Ruth I. Baldwin. NM:
revisions. © 3Jan49; A29514. John R.
Clark & Caroline Hatton Clark (A);
14Apr76; R631437.

R631453.
  Theory of oscillations. By A. A.
Andronow & C. E. Chaikin, editorial
supervisor: Solomon Lefschetz. NM:
translation. © 16Mar49; A31542. Alice
B. Lefschetz (W); 10May76; R631453.

R631576.
  Thermodynamics. By Edward F. Obert.
© 13Aug48; A24564. Edward F. Obert (A);
26Apr76; R631576.


R631577.
  Elements of physics. By Alphens W.
Smith. 5th ed. © 9Aug48; A24602.
Theodore B. Smith & Robert B. Smith (C);
26Apr76; R631577.

R631580.
  Mathematics of finance. By Paul M.
Hummel & Charles L. Seebeck, Jr.
© 31Aug48; A25002. Irma Lee Hummel (W); &
Charles L. Seebeck, Jr. (A); 26Apr76;
R631580.

R631589.
  Fluid dynamics. By Victor L. Streeter.
© 18Nov48; A27741. Victor L. Streeter
(A); 26Apr76; R631589.

R631589.
  Fluid dynamics. By Victor L. Streeter.
© 18Nov48; A27741. Victor L. Streeter
(A); 26Apr76; R631589.

R631591.
  Introduction to complex variables and
applications. By Ruel V. Churchill.
© 26Nov48; A27973. Ruel V. Churchill
(A); 26Apr76; R631591.

R631593.
  Business mathematics--exercises,
problems and tests; college course. By R.
Robert Rosenberg. © 29Nov48; AA101315.
R. Robert Rosenberg (A); 26Apr76;
R631593.

R632156.
  Solid geometry. By F. Eugene Seymour &
Paul James Smith. NM: additions &
revisions. © 29Mar49; A31347. Hazel D.
Smith (W), Paul Smith (C) & Frances E.
Clark (C of F. Eugene Seymour); 4May76;
R632156.

R632329.
  Mathematics we use. Book 1. By Leo J.
Brueckner & Foster E. Grossnickle. NM:
revisions & additions. © 2Jun48; A23253.
Holt, Rinehart and Winston (PWH); 6May76;
R632329.


R632330.
  Mathematics we use. Book 2. By Leo J.
Brueckner & Foster E. Grossnickle.
© 9Jun48; A23254. Holt, Rinehart and
Winston (PWH); 6May76; R632330.

R632456.
  Frequency analysis modulation and noise.
By Stanford Goldman. © 7May48; A22473.
Stanford Goldman (A); 28Apr76; R632456.


R632457.
  Microwave transmission design data. By
Theodore Moreno. © 10May48; A22629.
Theodore Moreno (A); 28Apr76; R632457.

R632486.
  Cardinal algebras. By Alfred Tarski &
Bjarni Jonsson. © 24Feb49; A32746.
Alfred Tarski (A); 26Apr76; R632486.

R633847.
  The Mathematics of solutions and dosage,
including simple arithmetic. By Margene
O. Faddis & Berschel E. Grime. 3rd ed.,
rev. © 28Jun48; A23819. Margene O.
Faddis (A); 30Apr76; R633847.

R634146.
  Algebra. Book 1: elementary course. By
A. M. Welchons & W. R. Krickenberger.
© 11Mar49; A31654. Harriet Blue Welchons
(W); 28May76; R634146.

R634152.
  Aritmetica social. Grade 5. By Pedro
A. Cebollero & Erasto Rivera Tosado.
© 22Apr49; A32951. Pedro A. Cebollero
(A); 28May76; R634152.

R634183.
  In number land; revised. By Mae Knight
Clark & Laura Cushman, illustrated by
Marion & Doris Henderson, NM: additions &
revisions. © 22Mar49; AA111255. Mae
Knight Clark & Laura Cushman (A);
28May76; R634183.


R634184.
  Numbers at work; revised. By Mae Knight
Clark & Laura Cushman, illustrated by
Marion & Doris Henderson. NM: additions &
revisions. © 22Mar49; AA111256. Mae
Knight Clark & Laura Cushman (A);
28May76; R634184.

R634188.
  Elementary practical physics. By Newton
Henry Black & Harvey Nathaniel Davis. NM:
additions & revisions. © 22Mar49;
A31063. Margaret B. Richardson (C of
Newton Henry Black); 28May76; R634188.

R634276.
  Rinehart mathematical tables. By Harold
D. Larsen. © 20Jul48; A24641. Harold D.
Larsen (A); 9Jun76; R634276.

R634496.
  Shea arithmetic essentials test. Grades
7-9, form A. © 20May49; AA229691. James
T. Shea (A); 4Jun76; R634496.


R634497.
  Shea arithmetic essentials test. Grades
5 & 6, form A. © 20May49; AA229695.
James T. Shea (A); 4Jun76; R634497.


R634498.
  Shea arithmetic essentials test. Grades
3 & 4, form A. © 20May49; AA229701.
James T. Shea (A); 4Jun76; R634498.

R635157.
  Instructional tests in algebra. By
Raleigh Schorling. NM: revisions &
<pb id='278.png' />
corrections. © 4May49; AA117919. Marie
O. Schorling (W); 27May76; R635157.

R635273.
  Self-help mathematics. Tests 1-33. By
G. E. Hawkins & L. S. Walker. © 12May49;
AA119554. Scott, Foresman and Company
(PWH); 7Jun76; R635273.

R635882.
  Practical shop mathematics. By John H.
Woolfe & Everett R. Phelps. 3rd ed.
© 23Nov48; A28857. Mary Ann Lindsay (NK
<pb id='289.png' n='1976_h1/A/3195' />
of John H. Wolfe) & Charlotte Mann (C of
Everett R. Phelps); 26May76; R635882.

R635883.
  Mechanics. By John W. Breneman. 2nd
ed. © 2Sep48; A25187. Catherine R.
Breneman (W); 26May76; R635883.

R636330.
  Arithmetic for young America, revised
edition: teacher's manual. Grade 7. By
Raleigh Schorling, John R. Clark & Rolland
R. Smith. NM: revisions. © 3Jan49;
A29509. Marie O. Schorling (W) & John R.
Clark (A); 15Apr76; R636330.


R636331.
  Arithmetic for young America, revised
edition; teacher's manual. Grade 8. By
Raleigh Schorling, John R. Clark, &
Rolland R. Smith. NM: revisions.
© 3Jan49; A29510. Marie O. Schorling (W)
& John R. Clark (A); 15Apr76; R636331.


R636332.
  Arithmetic for young America. Grade 7.
By Raleigh Schorling, John R. Clark &
Rolland R. Smith. NM: revisions.
© 3Jan49; A29515. Marie O. Schorling (W)
& John R. Clark (A); 15Apr76; R636332.


R636333.
  Arithmetic for young America. Grade 8.
By Raleigh Schorling, John R. Clark &
Rolland R. Smith. NM: revisions.
© 3Jan49; A29516. Marie O. Schorling (W)
& John R. Clark (A); 15Apr76; R636333.

R636334.
  Algebra; first course. By Raleigh
Schorling, Rolland R. Smith & John R.
Clark. © 27Jan49; A32394. Marie O.
Schorling (W) & John R. Clark (A);
15Apr76; R636334.

R636339.
  Danger! curves ahead! By Miriam Lincoln
(Miriam Lincoln Loomis) © 16Nov48;
A27673. Miriam Lincoln Loomis (A);
6Jul76; R636339.

R636347.
  Radio and television mathematics. By
Bernhard Fischer. © 24May49; A33084.
Bernhard Fischer (A); 6Jul76; R636347.

R636355.
  A Short course in differential
equations. By Earl D. Rainville.
© 14Jun49; A33535. Esther G. Rainville
(W); 6Jul76; R636355.

R636619.
  Mechanics. By J. P. Dan Hartog.
© 18Aug48; A24603. J. P. Dan Hartog (A);
9Jul76; R636619.

R636620.
  Introduction to applied mathematics. By
Francis D. Murnaghan. © 24Aug48; A24701.
Francis D. Murnaghan (A); 9Jul76;
R636620.

R637311.
  Philosophy of mathematics and natural
science. By Hermann Weyl. NM: translation.
© 20Jun49; A33813. Fritz J.
Weyl & Michael Weyl (C); 23Jul76;
R637311.

R637549.
  Modern-school solid geometry. By
Rolland B. Smith & John R. Clark. NM:
revisions. © 11May49; A33191. John R.
Clark (A); 26Jul76; R637549.

R637554.
  Algebra: first course; chapter tests.
By Raleigh Schorling, John R. Clark &
Rolland R. Smith. © 6Jul49; AA126789.
Marie O. Schorling (W) & John R. Clark
(A); 26Jul76; R637554.

R637768.
  Fundamentals of symbolic logic. By
Alice Ambrose & Morris Lazerowitz.
© 8Sep48; A26058. Alice Ambrose & Morris
Lazerowitz (A); 11Aug76; R637768.


R637769.
  College algebra. By Lewis M. Reagan,
Ellis R. Ott & Daniel T. Sigley. NM:
additions, revised & reset. © 28Sep48;
A26059. Lewis M. Reagan, Ellis R. Ott &
Daniel T. Sigley (A); 11Aug76; R637769.

R638670.
  Advanced examination in physics. Form
XRC. By a group of ten. NM: additions.
© 26Feb49; AA108286. Educational Testing
Service (PWH); 17May76; R638670.

R638677.
  United States Military Academy regular
and validating examination in Mathematics.
Form XWP, 1949. By a group of ten.
© 2Mar49; AA108823. Educational Testing
Service (PWH); 17May76; R638677.

R638693.
  Chicago elementary examinations in
English and mathematics. Editorial
assistants: Rita Mann & Bernard Tchorni.
© 26Feb49; AA110874. Educational Testing
Service (PWH); 17May76; R638693.

R638725.
  Examination for admission to the United
States Naval Academy: algebra. Form XNA.
© 28Apr49; AA114243. Educational Testing
Service (PWH); 17May76; R638725.

R638727.
  Examination for admission to the United
States Naval Academy: plane geometry and
trigonometry. Form XNA. © 20Apr49;
AA114096. Educational Testing Service
(PWH); 17May76; R638727.

R638794.
  Number theory and its history. By
Oystein Ore. © 10Sep48; A25281. Gudrun
Ore (W); 12Aug76; R638794.

R639145.
  Supersonic flow and shock waves. By
Richard Courant & K. O. Friedrichs. (Pure
and applied mathematics, vol. 1)
© 2Dec48; A28516. Nina Courant (W) & K.
O. Friedrichs (A); 2Aug76; R639145.

R639798.
  A Guide for teaching arithmetic in
grades one to eight. By John R. Clark.
© 16May49; AA120524. John R. Clark (A);
21Jun76; R639798.

R639804.
  Algebra: first course; teacher's manual.
By Raleigh Schorling, Rolland R. Smith &
John R. Clark. © 27Jul49; AA126790.
Marie O. Schorling (W) & John R. Clark
(A); 20Aug76; R639804.

R640077.
  Fundamental mathematics. Vol. 1. By
Eugene P. Northrop. 3rd ed. © 25Sep48;
A25919. University of Chicago Press
(PWH); 23Aug76; R640077.

R640079.
  Introduction to physics. Pt. 1. By
Alexander Kolin. NM: revisions.
© 23Sep48; A26382. University of Chicago
(PWH); 23Aug76; R640079.

R640263.
  Sources of engineering information. By
Blanche Harris Dalton. NM: revised &
entries brought up to date from 1944-1947.
© 23Sep48; A28069. Blanche Harris Dalton
(A); 11Aug76; R640263.

R640549.
  Basic theory: administration and
application of activity vector analysis.
By Walter Vernon Clarke. © 15Jun49;
A34268. Walter Vernon Clarke (A);
1Sep76; R640549.

R642258.
  Arithmetic readiness cards. Set 1:
grouping. By Maurice L. Hartung, Henry
Van Engen & Helen Palmer. © 22Sep49;
AA130169. Scott, Foresman and Company
(PWH); 27Sep76; R642258.

R642397.
  Partial differential equations in
physics. By Ernst G. Straus. Translation
of German work entitled Partielle
Differentialgleichungen der Physik. NM:
translation. © 24May49; A33803.
<pb id='434.png' />
Academic Press, Inc. (PWH); 27Sep76;
R642397.

R642891.
  First year mathematics for colleges. By
Paul R. Rider. © 9Aug49; A34824. Paul
R. Rider (A); 3Sep76; R642891.

R643248.
  Principles of electric and magnetic
fields. By Warren B. Boast. © 10Nov48;
A27266. Warren B. Boast (A); 8Oct76;
R643248.

R643254.
  An Introduction to college geometry. By
E. H. Taylor & G. C. Bartoo. NM:
additions & revisions. © 14Jun49;
A33534. Catherine I. Taylor (C) &
Harriette V. Bartoo (W); 1Oct76;
R643254.

R643270.
  Number play: a number readiness book;
revised, teacher's edition. By Mae Knight
Clark & Laura Cushman, illustrated by
Joanne Adams. (Self-help number series)
NM: additional material. © 6Sep49;
AA127772. Mae Knight Clark & Laura
Cushman (A); 1Oct76; R643270.

R644598.
  Reviewing elementary algebra. By
Isidore Dressier & Eva Mizerek. © 1Sep49;
AA132273. Amsco School Publications, Inc.
(PWH); 26Oct76; R644598.

R645206.
  Making arithmetic plain. Book 1. By
Rose Lollie Weber & Ruth Hollie Weber.
© 21Jan49; AA105074. Litton Educational
Publishing, Inc. (PWH); 2Nov76; R645206.

R645209.
  Teachers answers for all exercises and
tests for Making arithmetic plain, book 1.
By Rose Weber & Ruth Weber. © 15Aug49;
AA125296. Litton Educational Publishing,
Inc. (PWH); 2Nov76; R645209.

R645211.
  Making arithmetic plain. Book 2. By
Rose Weber & Ruth Weber. © 4Oct49;
AA129303. Litton Educational Publishing,
Inc. (PWH); 2Nov76; R645211.


R645212.
  Tests for use with Making arithmetic
plain, book 2. By Ruth Weber & Rose
Weber. © 7Oct49; AA129882. Litton
Educational Publishing, Inc. (PWH);
2Nov76; R645212.


R645213.
  Making arithmetic plain; teacher's
answers for all exercises and tests. Book
2. By Ruth Weber & Rose Weber.
© 13Oct49; AA130354. Litton Educational
Publishing, Inc. (PWH); 2Nov76; R645213.

R645344.
  Reviewing physics. By Walter L. Abner.
© 15Mar49; AA116178. Amsco School
Publications (PWH); 22Nov76; R645344.

R645366.
  Earth conduction effects in transmission
systems. By Erling D. Sunde. © 21Jan49;
A29225. Bell Telephone Laboratories, Inc.
(PWH); 8Nov76; R645366.

R645652.
  Technical drawing. By Frederick E.
Giesecke, Alva Mitchell & Henry Cecil
Spencer. 3rd ed. © 30Aug49; A35336.
Linda Giesecke Geren, Alma Giesecke
Hodges, Minnie Giesecke Wight & R. Howard
Mitchell (C) & Juanita M. Spencer (W);
5Nov76; R645652.

R645666.
  In number land; revised teacher's
edition. By Mae Knight Clark & Laura
Cushman. (Self-help number series) NM:
additional material. © 11Oct49;
AA130069. Mae Knight Clack & Laura
Cushman (A); 5Nov76; R645666.

R646030.
  English and mathematics. Form XNT. By
group of eight. © 17Sep49; AA128429.
Educational Testing Service (PWH);
8Nov76; R646030.

R646049.
  Mathematics; advanced tests. Form A.
<pb id='520.png' n='1976_h2/A/3279' />
(Graduate record examination) © 28Oct49;
AA131869. Educational Testing Service
(PWH); 8Nov76; R646049.

R646572.
  Quantum mechanics. By Leonard I.
Schiff. © 3Jan49; A28936. Frances B.
Schiff (W); 19Nov76; R646572.

R646575.
  Standard handbook for electrical
engineers. By Archer E. Knowlton. 8th
<pb id='533.png' />
ed. © 6Jan49; A29055. McGraw-Hill, Inc.
(PWH); 19Nov76; R646575.


R646576.
  Introduction to atomic physics. By Otto
Oldenberg. © 7Jan49; A29056. Otto
Oldenberg (A); 19Nov76; R646576.

R646578.
  Principles of mechanics. By John L.
Synge & Byron R. Griffith. 2nd ed.
© 16Feb49; A30168. John L. Synge & Byron
A. Griffith (A); 19Nov76; R646578.

R646581.
  Practical shop mathematics. Vol. 2:
advanced. By John H. Wolfe & Everett R.
Phelps. 3rd ed. © 17Mar49; A31265.
Mary Ann Lindsay (NK of John H. Wolfe) &
Charlotte Mann (C of Everett R. Phelps);
19Nov76; R646581.

R646582.
  Mathematics for electricians. By Martin
H. Kuehn. 3rd ed. © 4Mar49; A31268.
Marie Kuehn (W); 19Nov76; R646582.

R646771.
  Facts with fractions. By Bernard Ernest
Tobin. © 1Jun49; AA119468. Jeannette E.
Tobin (W); 19Nov76; R646771.

R647761.
  Nuclear physics. By Jay Orear, Arthur
H. Rosenfeld & Robert A. Schluter.
© 24Oct49; A39290. Jay Orear (A);
29Nov76; R647761.

R647763.
  Arithmetic 1949. By Guy T. Buswell &
Maurice L. Hartung. (Supplementary
educational monographs, no. 70)
© 11Nov49; AA134174. The University of
Chicago (PWH); 29Nov76; R647763.

R647841.
  Numbers at work, revised; teacher's ed.
By Mae Knight Clark & Laura Cushman,
<pb id='549.png' />
illustrated by Marion Henderson & Doris
Henderson. (Self-help number series) NM:
additions. © 7Nov49; AA133193. Mae
Knight Clark & Laura Cushman (A); 2Dec76;
R647841.

R649879.
  Making sure of arithmetic. Grade 1. By
Robert Lee Morton & Merle Gray. © on
revisions; 26Feb49; AA110188. Merle
Gray (A); 28Dec76; R649879.


R649880.
  Making sure of arithmetic; teacher's
guide. Grade 1. By Robert Lee Morton &
Merle Gray. © on revisions; 5Apr49;
AA113226. Merle Gray (A); 28Dec76;
R649880.

R649883.
  Making sure of arithmetic; text-workbook.
Grade 2. By Robert Lee Morton
& Merle Gray. © on revisions; 8Apr49;
AA114336. Merle Gray (A); 28Dec76;
R649883.

R649887.
  Making sure of arithmetic; teacher's
guide. Grade 2. By Robert Lee Morton &
Merle Gray. © on revisions; 18Aug49;
AA126496. Merle Gray (A); 28Dec76;
R649887.
