#+STARTUP: showeverything logdone
#+options: num:nil

The aim of this page is to chart sites on the web where people discuss
math. Maybe we can get some new ideas for making Noosphere's
fora more math friendly.

See also: [[file:Mathematical Counter-cultural Appeal.org][Mathematical Counter-cultural Appeal]], [[file:Latex rendering in forums.org][Latex rendering in forums]]

* Wikipedia's math help desk
http://en.wikipedia.org/wiki/Wikipedia:Reference_desk/Mathematics

FDL and wiki's Latex support. 

* Dr. Math
Text based. Anyone can submit a question using
[http://mathforum.org/dr.math/ask/submit.html this web form]. 
Volunteers answer the question. Old problems are organized by subject. 
They also have a formula collection.

* Art of problem solving
[http://www.artofproblemsolving.com/Forum/index.php www.artofproblemsolving.com]. 
This site seems to be targeted to people who train for math competitions. 

The fora have math support. Looks like Latex, but I could find no references.
Examples: [http://www.artofproblemsolving.com/Forum/topic-33860.html].

The statistics are impressive: 400000 articles, 16000 users, founded in 2003.
The software is released under the GPL [http://www.artofproblemsolving.com/Forum/faq.php#40].

Users can create blogs hosted on the site. They also have
[http://www.artofproblemsolving.com/Community/AoPS_Y_Math_Jams.php math jams]. These
seem to resemble supervised IRC sessions about specific topics mostly related to 
math competitions. They also offer [http://www.artofproblemsolving.com/Classes/AoPS_C_ClassesS.php online classes]
on grade 7-12 material and competitions.

** Discussion

Interesting.  Apparently they have a lot of content.  How did they get so much! --[[file:jcorneli.org][jcorneli]]

Maybe one of us should try to talk to these people... --[[file:jcorneli.org][jcorneli]]

* Math newgroups
..
