#+STARTUP: showeverything logdone
#+options: num:nil

This is a page for planning participation of PlanetMath folks in !MathFest 2007
in  San Jose, CA, August 3-5, 2007.

The main page for this meeting appears to be [http://www.register123.com/event/profile/web/index.cfm?PKwebID=0x66406eae8 here].

Unfortunately, registration doesn't seem to be open there yet.

Other information about MAA meetings is [http://www.maa.org/meetings/meetings.html here].

* Draft blurb suitable for posting as PlanetMath news

Several !PlanetMath members are planning to go to MAA's summer
MathFest in San Jose, California, this upcoming August (3rd-5th, see
http://www.maa.org/mathfest).  We were too late to organize a special
session for !PlanetMath and related things, but we plan to have an
informal summit and would like to have the chance to meet you there.
Participation in !MathFest will be part of an ongoing effort to foster
discussions between the !PlanetMath community and the mathematics
community at large, and a simultaneous effort to get people in the
PlanetMath community talking to each other in person.


Read more about future MAA meetings at
http://www.maa.org/meetings/meetings.html
and future AMS meetings at
http://www.ams.org/meetings
For information specifically on Mathfest, please see
www.maa.org/mathfest
To register for !MathFest, please see
http://www.register123.com/event/profile/form/index.cfm?PKformID=0x303659cf82

Hope to see you at one of these :).  And put up a post if you plan to
be at !MathFest so we can in contact there.  




After making a few changes like putting in the actual dates for
registration, I will post this.  --[[file:rspuzio.org][rspuzio]]
