#+STARTUP: showeverything logdone
#+options: num:nil

The thesis here seems to be /free math makes life better for most
mathematicians/.  One set of references that would be interesting to
consult/critique is Ewing's work on "open access publishing" etc.;
another is the book "Policy Analysis" by Weimer and Vining that
my dad recommended (here we should get some info about the economics
of public goods etc.).  [[file:bloftin.org][bloftin]] mentioned "Freakonomics"; the
example he cited seems to be mainly useful in a negative sense,
i.e., we would want to show that control of information in math
is not the same as control of information in real estate.
--[[file:jcorneli.org][jcorneli]]

Note that the energetic & in some cases vitriolic conversation about
Public Domain and licensing after the board meeting can only
underscore my point that this is an important issue at this time.
--[[file:jcorneli.org][jcorneli]]

Some of that discussion wound up on the [[file:PM Licenses.org][PM Licenses]] page.
(Which is still in progress.)  I think we should [[file:letter to Ewing|reach out to John Ewing.org][letter to Ewing|reach out to John Ewing]]
about some of the questions here.
--[[file:jcorneli.org][jcorneli]]

I think we can also emphasize the "developing scholars" angle here again.
Note that non-free math mostly benefits an insular community of scholars ("the
academic priesthood"), and keeps the knowledge locked in.  It is monopolized. 
Members of such cabals want to profit off this "secret knowledge" in various ways
(I won't go into them; you doubtless know them).

Ways of maintaining this lock-in of knowledge (either intentional or not) have
been expensive journal subscriptions, high conference rates, expensive textbooks,
the need for particular credentials to join professional associations or attend
conferences, and of course, restrictive licensing.

There are two levels of going beyond this: open access, and then open creation.

When you attain the first level, you have allowed information to "flow out" to 
two constituencies that go beyond the "priesthood": (1) students who are pursuing
study in that area (either formally or informally), and (2) the general public.   
When students can get to the knowledge, they can use it to augment their study
(if formal), or more successfully learn a topic if informal (typically without
open access they will entirely fail to gain high levels of understanding; hence
an apathic general public and crackpots).

Beyond this, the constituency of the general public that is not pursuing study
in the field may chance upon some of its knowledge if it is open access, and then
/become/ interested.  At this point they become a de facto member of the first
group, the students, and choose to learn more, which they can now do.  Or they may
take small bits of the knowledge and use it to augment their life in general or 
their main area(s) of expertise.

This is all very good, but it is only the beginning.  Open access mostly benefits
the /public/; that is, everyone outside of the core productive scholarly community.
Open creation takes the benefit to the next level, actually benefitting that
core community itself.

In the case where the outsiders have chosen to pursue study or continue with it
because of open access to the knowledge, they will also have the option of 
becoming a full member of the scholarly community by actually participating in
the expression and/or development of the knowledge.   

This connects back to the main point about producing scholars, which is
a good altruistic thing to do.  But beyond this, the scholarly community itself
benefits in a number of ways.  Trivially speaking, open production increases the size of this
community both in members and content.  But even more importantly, open production
enriches the community by exposing it to new perspectives and ideas.  

In the past system of 
closed knowledge production, this could happen only when sufficient momentum
was gained for a new knowledge community to break out of an old one.  However,
without anything but the same closed "architecture" to implement as the backbone
for the new community, it was always doomed to eventually attain the same 
unfortunate fate: stasis of ideas, lack of creativity and innovation, and 
increasing irrelevance.

20th century science and mathematics is rife with examples of thinkers who were 
beyond their time but were easily rejected by closed knowledge systems, only to
have their ideas finally picked up and recognized to be superior 25, 50, or even
75 years later.  Perhaps with open versions of the same scholarly communities 
available, it would have been more difficult for these people's ideas to be
ignored.  Now is the time we can act to save society in general from the 
negative consequences of this effect in this century.

--[[file:akrowne.org][akrowne]] Sat Feb 11 06:05:39 UTC 2006


Guys: I think that our current [[file:Detailed_PM_whitepaper_outline|outline.org][Detailed_PM_whitepaper_outline|outline]] gets
pretty /meager/ in the free math section.  I feel I won't really know how useful our
discussions have been (including our general [[file:Discussions.org][Discussions]] and the
[[file:Understanding free math|other.org][Understanding free math|other]] ad hoc free math discussion page) until
I see a recognizably good outline of the major points.  Since I know that
some of the key experts on the issue of free math frequently use this wiki,
I'd appreciate it if they can all check in on that section of the outline.

--[[file:jcorneli.org][jcorneli]]
