#+STARTUP: showeverything logdone
#+options: num:nil

/These comments apply to [[file:NSF Cyberinf 2007 Grant Draft 1.org][NSF Cyberinf 2007 Grant Draft 1]]:/

I would like to come back and capsulize the statements here to make
them easy to swallow.  Will be a little while: Aaron if you read this
and are working on the same thing, please go ahead!

--[[file:jcorneli.org][jcorneli]]

I did that for the introduction.  Next step, I think, is to make sure
this matches up with our problem/solution pairs, and ultimately, to
make sure it matches up with the "proposal" part.  

Indeed, there are several "gaps to bridge" -- between the NSF-CIO's
writings (see [[file:NSF Cyberinf 2007 stick to the agenda.org][NSF Cyberinf 2007 stick to the agenda]]) and our
statement of the social problem, between our statement of the problem
and the solution(s), etc.

Some important "glue" could say why we are going to introduce an
/infrastructural/ solution to the issues described in the
introduction, as opposed to, say, a social solution.

--[[file:jcorneli.org][jcorneli]]

I think a version with the relevant additional components appropriately
glued together could well be called [[file:NSF Cyberinf 2007 Grant Draft 2.org][NSF Cyberinf 2007 Grant Draft 2]],
so I'll put what I have to say there.

--[[file:jcorneli.org][jcorneli]]
