#+STARTUP: showeverything logdone
#+options: num:nil

The full proposal should present the (1) objectives and scientific,
engineering, or educational significance of the proposed work; (2)
suitability of the methods to be employed; (3) qualifications of the
investigator and the grantee organization; (4) effect of the activity
on the infrastructure of science, engineering and education; and (5)
amount of funding required. It should present the merits of the
proposed project clearly and should be prepared with the care and
thoroughness of a paper submitted for publication. The requisite
proposal preparation instructions are contained in GPG Chapter
II. Sufficient information should be provided to enable reviewers to
evaluate the proposal in accordance with the two merit review criteria
established by the National Science Board. (See GPG Chapter III for
additional information on NSF processing and review of proposals.)

-- From the NSF Grant Proposal Guide (GPG), available at http://www.nsf.gov/pubs/gpg/nsf04_23/nsf04_23.pdf 

(The Guide provides lots more info and specifics, just check out the
table of contents!)

----

Alright, let's treat this as some sort of checklist and see how we
stack up.

 *(1)* /objectives and scientific,
engineering, or educational significance of the proposed work;/

 *(2)* /suitability of the methods to be employed;/

 *(3)* /qualifications of the investigator and the grantee organization;/

The organization has been operating for five years and has amassed
considerable experincs in CBPP for scientists.  It also has 
partnerships with the MAA (via the math Gateway), Wikipedia(sharing 
content).

In addition to whatever qualification we may have in the usual sense,
we should point out that, because we are heavily involved in the
day-to-day activities of a CBPP project, we have considerable 
practical experience with the infrastructural needs of such concerns.
While it may be possible to find a team of computer scientists
and mathematicians who have more experience and credentials in their
respective fields, it is doubtful that they would have much understanding
of CBPP.  We feel that this experience is an important qualification
because our goal is not merely to produce cyberinfrastructure in some
abstract sense, but to design and produce cyberinfrastructure which
adresses the concrete needs of scientists collaborrating within a 
CBPP framework.  Somewhere, the cyberinfrastructure panel talks about
some "new breed of professional".  We should argue that we qualify 
as early examples of such.

 *(4)* /effect of the activity on the infrastructure of science, 
engineering and education;/

 *(5)* /amount of funding required./

$200,000 or so.  Because we are a thoroughly virtual organization,
practically all of this money goes towards paying people to do the 
work as opposed to also maintaining facilities, so we can deliver
more for the same price.
