#+STARTUP: showeverything logdone
#+options: num:nil

Me: cramped inside of an airplane waiting for access to
the gate, has to urinate.  The human flotsam discharges into the
airport and disperses quickly.  I too have the chance to relieve
myself. Certain properties, relationships between individuals or
certain facts about individuals themselves, do not change.  I am
still Joseph Angus Corneli, whether I am held impatiently waiting in
an airplane or seated happily on the curb waiting for a bus.  We are
continually re-categorized.  The fact that we can be in more than one
mutally overlapping category at once is rather neat, from a logic
standpoint; but it is more interesting, I think, to observe how
different the categories are: the conditions of sharing a common
space, a common memory, or belonging to some co-defining relation are
all rather strikingly different.  Each is differently "consistent",
along different axes (time, space, identity).

--[[file:jcorneli.org][jcorneli]] Jan 11, 06
