#+STARTUP: showeverything logdone
#+options: num:nil

I just spent the morning down at the local cafe, outside
of the range of wireless internet.  Got a decent amount
of work done on the browser for the [[file:scholium system.org][scholium system]],
a solid new beginning anyway.  Given that I like to talk
a lot (which no doubt other wiki users have noticed) I sometimes
find it very helpful to be offline when I'm actually working.
Furthermore, since I'm naturally a bit of an extrovert
(albeit in a weird way), if I have an internet connection,
I'm rather likely to spend most of my time blabbing or otherwise
conversing.  I wonder what will become of me when the whole
city is on one wireless network!  I may have to move (gulp) or
figure some sort of other way to limit my access.  The fact of the matter is that I tend
to have rather bad self-control, so the idea of turning off
my wireless card, though simple enough to suggest, is actually
sort of hard for me to do.  I sometimes need to find somewhat "harder limitations".

One nice thing about the [[file:scholium system.org][scholium system]] is that it works
with a very low online component: one needs only a few minutes
a day to sync up.  This gives users the possibility of steering
away from the "hit mentality" and towards a more laid back form
of interaction.  Remember "the medium is the message"?

Another (almost completely different) issue in the comparison of
online versus offline life is that of local (analog) resources.  Face-to-face
conversations are more data-rich than online conversations.  By saying this, I don't mean
to disparage either type of communication, mind you.  For face to face
conversations, you have to remember to shower and so on.  Online conversations
give you a more "global" scope - but the semi-holographic nature of
information means that you can sometimes find very "global" things stored
locally, too.  The difference between physical hacking and computer hacking
is palpable, even though there are some similarities too.  The best
black hat hackers talk extensively about the "human factor", i.e., combining
online and offline activities.  

It is interesting to think about what sort of balance between these
sorts of interactions works "best" - which is of course a judgement
that would be relative to the individual, the work, and presumably the
other agents involved in the interaction.

--[[file:jcorneli.org][jcorneli]]
