#+STARTUP: showeverything logdone
#+options: num:nil

A list of articles from the AMS Notices about open content, journal pricing, and mathematics DL

; [http://www.ams.org/notices/200410/comm-biss.pdf The Elephant in the Internet], 
Daniel K. Biss, November 2004  : a quality-based arguement against accessibility and open content.     Strong echoes of the the criticisms leveled against wikipedia.

; [http://www.ams.org/notices/200308/comm-jackson.pdf The Digital Mathematics Library],
Allyn Jackson,  August 2003  : "The grand vision of the DML is to have all of the
mathematical literature online and available
through a central source to anyone who has a computer
and an Internet connection."  An institutionalized expression of /the dream/

; [http://www.ams.org/notices/200306/comm-peerreview.pdf Three Views of Peer Review]
Steven G. Krantz, Greg Kuperberg, Alf van der Poorten,  June/July 2003 :  a key issue in the open access debate is /quality/ and peer review.  These points are usually made in defense of proprietary models.  I include this, because of the interesting proposal by Greg Kuperberg of how to implement peer review in an open access setting.

; [http://www.ams.org/notices/200201/fea-preprints.pdf From Preprints to E-prints: The Rise of Electronic Preprint Servers in Mathematics]
Allyn Jackson,  January 2002 : Allyn Jackson is another high-profile supporter of open access in the maths community.  The article is a useful survey and overview on the topic of preprints and open access servers.

; [http://www.ams.org/notices/200009/fea-eljnl.pdf The Slow Revolution of the Free Electronic Journal], Allyn Jackson, September 2000 : "Free electronic mathematics journals, which are run independently by mathematicians and are available for free on the Web, provide some important advantages over traditional print journals. This article examines how a number of such journals are run and discusses why there are not more such journals."

; [http://www.ams.org/notices/199810/beschler.pdf  Pricing of Scientific Publications: A Commercial Publisher's Point of View], 
Edwin F. Beschler, November 1998 : The view from the commercial side.  Central argument: commercial publishers add value and doing scientific publication w/o them would degrade scholarly communication.  An attempted rebuttal to the article below.

; [http://www.ams.org/notices/199804/branin.pdf Reforming Scholarly Publishing in the Sciences: A Librarian Perspective],
Joseph J. Branin and Mary Case, April 1998 : report on the academic journal pricing crisis.  

: "As a result of the high cost and continuing double-
digit annual price increases for scientific journals,
research librarians have had to shift everlarger
portions of their acquisitions budgets into
science journal subscriptions, even as they cancel
journal titles and buy fewer books. With growing
frustration and boldness, librarians are blaming the
scientific community, particularly the commercial
publishers of scientific journals, for this unfortunate
situation. ...

: *The Barschall Study*
In 1986 and again in 1988 Henry Barschall, now
deceased but at the time a physics professor at the University of Wisconsin and an editor of Physical
Review, published a series of studies on the cost
and cost effectiveness of scholarly journals in several
scientific disciplines ...  

: *Blame the Commercial Publishers of Science
Journals*
Barschall's findings confirmed the experience of
many research librarians: commercial publishers
in the scientific disciplines were at the core of
their economic woes. One commercial publisher,
Gordon and Breach, who came out at the bottom
of Barschall's survey of cost effectiveness, disagreed
and sued Barschall, the American Physical
Society (APS), and the American Institute of Physics
(AIP) in West Germany, Switzerland, France, and the
United States over the publication of the journal
cost surveys"


By relative measures the AMS is  a very progressive entity on the subject of copyrights and accessibility.   Here are a couple of representative editorials by two presidents of the AMS.

; [http://www.ams.org/notices/199901/editorial.pdf Copyright Policies], Anthony W. Knapp,  January 2000 : The AMS position on copyrights

; [[file:Archimedes and the Internet|Archimedes and the Internet.org][Archimedes and the Internet|Archimedes and the Internet]], Harold P. Boas, September 2001 (local link) : "I prefer to think of scientific knowledge as a shared public
resource rather than as a commodity to be sold to the
highest bidder." Another vocalization of the dream.  The above link
is a fair use, local mirror.  Link to original (free, but registration required) is   http://www.ams.org/notices/200108/commentary.pdf
