#+STARTUP: showeverything logdone
#+options: num:nil

This page lists and discusses influential (or high-profile, or famous, or somewhat 
famous) advocates of the
PlanetMath project.  These are people who we have made contact with (that is, at
the very least, one round of two-way communication) and who have expressed their
interest in or intellectual support for PlanetMath.

We may be able to get additional help from these people, either directly, or
indirectly (indeed, some already have helped).  They may provide weighty letters 
of support for grants, for example.

The list and discussion of each follows.

*  Influential folks who've indicated that they like and/or plan to support PM

**  Edward A. Fox

Profile:

: Ed is well-known and highly regarded in the digital libraries community.  He was
my ([[file:akrowne.org][akrowne]]'s) master's thesis advisor.

Potential for support:

: Ed has already demonstrated generous support by providing facilities and even 
servers for PlanetMath, Noosphere, and related projects.  However, due to his 
continuing interest in this field, he remains a promising friend to our efforts,
for PIing of grant projects, writing letters of support, or collaborating on 
formal academic research.

Contact with us: Direct and through [[file:akrowne.org][akrowne]].

**  Lawrence Lessig

Profile:

: Larry is a famous legal scholar, lawyer, and defender of digital rights. Last 
year he argued in front of the Supreme Court on Eldred v. Ascroft.  He has written
a trilogy of digital rights and general copyright books, including /Code and other
Laws of Cyberspace/, and /Free Culture/.

Potential for support:

: Evangelizing PlanetMath, especially in connection with his own "Creative Commons"
project.  We may be able to do some link exchanging here.  Helping us to find grants
and other forms of funding.  Writing letters of support. Giving us legal advice.

Contact with us: Through [[file:akrowne.org][akrowne]].

**  John Taylor Gatto

Profile:

: Award-winning former NYC school teacher, turned activist against the formal 
education system.  He now has written a number of books which serve as "exposes"
of the system, and which discuss his ideas for alternatives which would (or are)
better for society and the individual.

Potential for support:

: We can connect over our common interest in genuine, participatory, learner-driven 
education.  I see potential for Gatto to evangelize us, write letters of support,
connect us with financial support, and more.  We should also be willing to help 
with his efforts to raise interest in alternative education methods (think Robert
Milson's exploration of using Noosphere for teaching).

Contact with us: [[file:akrowne.org][akrowne]].

**  Jimmy Wales

Profile:

: Former worker in the finance industry, turned entrepreneur, turned free culture
activist.  Wales founded Wikipedia with Larry Sanger in 2001, as a spin-off of the
"traditional" (but online) encyclopedia startup "Nupedia".  Wikipedia of course 
quickly eclipsed Nupedia, and within four short years, became one of the most
staggering intellectual achievements of mankind.  Wikipedia is today ranked up 
there with Linux as one of the top two successes of CBPP.

Potential for support:

: Wikipedia is CBPP, we're CBPP.  The projects are in many ways the same structurally.
Wikipedia is even sharing content with PlanetMath.  We can share ideas, people, 
software, data, and perhaps even fundraising efforts.  We've also been publicized 
on the same "ticket" before (see
[http://www.freesoftwaremagazine.com/free_issues/issue_01/wiki_value/ Aaron Klemm's article] for a past example).

Contact with us: extensive, through [[file:akrowne.org][akrowne]].

**  Daniel Mayer

Profile:

: Top contributor to Wikipedia, turned Wikimedia CFO.  

Potential for support:

: Much the same as with Wales.  Mayer is considerably more accessible, however.

Contact with us: extensive, through [[file:akrowne.org][akrowne]] (we live in the same town and have 
met in person).

----
* Discussion

I've made some edits to the introduction, and here are some comments about that.

I haven't renamed the page, but in general, I would prefer to say "supporters",
instead of "advocates", because it is a less active term.  That is, unless the
parties involved have made statements or actions that show that they really are
going to get out there and advocate (/v./).  I'm not sure any of the people on
this list has done that - but if they have, then a description of their advocacy
contributions should be included.

I also think "famous" is a better word to use than "high-profile".  I'm not even
sure what "high-profile" means, but I get the feeling that it is somewhat more
judgemental than "famous", i.e., if you aren't "high-profile" then somehow you
aren't "cool" or whatever, but if you're "famous" that could be good /or/ bad.

Given the fact that I don't understand & am somewhat uncomfortable with the term
"high-profile", it should come as no surprise that I did't know what to make of

: Note: readers shouldn't get the impression that non-high-profile advocates aren't 
important.  In fact, these kind of people are the backbone of PlanetMath.  However,
we have in the past shirked efforts to evangelize our efforts and garner wide,
and official, support for them.  So this page is part of organizing that effort to 
repair that shortcoming.

And that I prefer the introduction without it.  If "non-high-profile" people are
so important, then certainly their support is just as relevant to garnering wide
and official support for !PlanetMath.  15 letters from non-famous math
professors written in support of PM's usefulness might carry more weight with
the NSF than a letter from Lawrence Lessig or President Bush or Marylin Manson
(and I personally think that would be for the best).

I'm even a little suspicious of the idea of making this page emphasize famous
people.  If it talks about /credentials/ of individuals would be fine, but
making a special page just for famous VIP's seems a little not-in-keeping-with
PM's philosophy.

I recognize that I talk about famous people on one of the HDM pages -- perhaps
that should be reevaluated too.  There, I was trying to paraphrase actual
conversations, and my intent was not to use the "merit" of these people as a
support for the HDM, but as a support for what they themselves had to say about
the HDM, and also as documentation of the fact that I did talk to these people
about it - so they are either on the "no call list" or perhaps the "announce"
list.

I think concrete statements from the people listed here, in their own words,
would be useful.  Maybe that is the planned next step.  But let's not leave out
other people!!
--[[file:jcorneli.org][jcorneli]] Thu May 05 21:46:18 2005 UTC

A more neutral and less value-laden term to consider might be "well-known".  I
certainly think that whatever changes are proposed or made here ought to apply
to the corresponding page about HDM. --[[file:rspuzio.org][rspuzio]] 5 May 2005

Honestly I am not making any value judgements here.  But it would be naive to deny
that some have more connectivity and resources than others.  This page is bookkeeping
so we know who we can tap for help.  I think "supporters" should be changed back to 
"advocates" because it is more honest.  I think "famous" is a synonym of "high profile".
And I think it is asking too much to get
these people to make statements for some arbitrary Wiki page.  BTW good luck getting 
funded with 15 letters from people grantors don't know as opposed to 1 they do. 
--[[file:akrowne.org][akrowne]] Fri May 6 02:53:26 UTC 2005

No one's denying anything of the sort -- I'm just saying it sounds (a) a bit
weird to single out all the contributors with property foo; (b) quite weird to
designate these people as "bar" contributors when they haven't produced tangible
evidence of bar.  The particular words are relatively unimportant.

To me it seems that it would best to have letters of support from everyone who
actually supports PM and who can write a good letter, famous or not.

Indeed, if you want this page to be about people who can be "tapped for
support", I see no reason to focus on well-known people to the exclusion of
little-known people.  What matters is the ability of the people in question to
support PM.

I'll repeat that "advocate" denotes a particular kind of active support, and
that I think it should be reserved for people who actually engage in that
particular kind of activity, because otherwise the usage seems
misleading. --[[file:jcorneli.org][jcorneli]] Fri May 06 16:38:07 2005 UTC

Indeed, I think we might all add our names to the list, and each write our own
short letter of support.  We can change the heading, of course... an I'm going
to wait until I have a real keyboard.... --[[file:jcorneli.org][jcorneli]]

And by the way --

: /I think it is asking too much to get these people to make statements for some arbitrary Wiki page./

But: this isn't an arbitrary wiki page ;).  This wiki is pretty close to being
the Central Command Station for !PlanetMath and affiliated projects, and this
page, in particular, is about PM supporters and/or advocates.  If these folks
(supporters) can't bring themselves to put a statement up /here/, then I really
wonder... where /will/ they put up statements?  But, anyway, wherever they
make their statements, I think we ought to be able to quote or paraphrase those
statements here.  --[[file:jcorneli.org][jcorneli]] Sat May 07 01:21:10 2005 UTC

----

: /But: this isn't an arbitrary wiki page.  /

I think high-profile supporters are likely to land in one of two bins: either
willing to directly work with us on this wiki site, or are willing to lend us
their reputations by writing a letter of support /for some known grant
program/.  Personally I would find it very difficult to write a letter of 
support without knowing who the audience was to be.

: /... it sounds (a) a bit
weird to single out all the contributors with property foo; (b) quite weird to
designate these people as "bar" contributors when they haven't produced tangible
evidence of bar.  The particular words are relatively unimportant./

If "foo" is that they are influential, then I don't find this weird at all.  And
I think "contributor" is a bit too strong a word.  To me, "advocate" just meant 
they are willing to at least speak in favor of the project.  I wouldn't want to
trivialize direct contribution (like adding content or sending in money) by also
calling advocating "contributing". 

I'm removing the separate "letters of support" section.  I think it would be better
to have links from the individuals listed, when the content is available.  Letters 
from all kinds of supporters could be linked off the PM grant seeking page.  
--[[file:akrowne.org][akrowne]] Mon May 9 04:12:06 UTC 2005
