#+STARTUP: showeverything logdone
#+options: num:nil

Presumably any salaried positions would correspond to work items
associated with 

 * serving some of the core goals of PM
 * an ongoing demand for labor 
 * tasks that can only be done (very) effectively by a specialist
 * a job that /can't/ be done effectively by pure-volunteer labor
 * suitable funding
 * ...

Examples may include things like fundraising, systems administration,
public relations, research, editing, system programming, and perhaps
writing content for the site.

Of course, currently all of these things /are/ exclusively done by
volunteers labor, but it may be that we won't be able to continue to
find volunteers in the future -- bearing in mind that the specific
tasks are changing as PM evolves, and that current PM specialists may
have shifting financial needs.

That said, it seems fairly likely that all of the jobs mentioned will
be staffed by some combination of volunteer and paid labor.

As for who gets paid -- I'd say that given the fundamentally DIY
nature of the site, anyone who can figure out a way to get income from
work related to the site can get paid.  For example, if you are a
researcher and you want to do research on some topic related PM,
there's nothing about PM that will stop you from getting started,
applying for grants, and getting a paycheck.  Similarly with
publishing or writing content, teaching or tutoring students, etc.

Sometimes it will make sense for PM to administer grants or write
paychecks out of other funds.  Getting this sort of a paycheck will
involve meeting the various criteria on the bulleted list above (and
no doubt some others as well).

Currently, three people seem particularly interested in figuring out
how to get PM paychecks, these are Ray, Joe, and Aaron.  The positions
that these three people would fill would cut across the various tasks
mentioned in the list of examples above -- essentially constituting
business as usual for these three folks, except that they would be
getting paid something for their labor.  (There are several notable
ways that the "for pay" situation would differ from the current
business-as-usual plan, and we'll touch on these below.)  The job
names of these positions might be President, Untitled 1, and Untitled
2.

Other likely positions include a Nonprofit Administrator (or Executive
Director), and a Staff Hacker (who would be responsible for keeping
the system up and running, independently making improvements to the
system, addressing feature requests, and working with other PM team
members on R&D).

Specific job descriptions should follow before long.


(See [[file:PlanetMath Roles.org][PlanetMath Roles]].)
