#+STARTUP: showeverything logdone
#+options: num:nil

* Contextualizing documents

 * [[file:Improving the Donations Page.org][Improving the Donations Page]]
 * [[file:Overview of current PlanetMath finances.org][Overview of current PlanetMath finances]]
 * [[file:Timetable for PlanetMath development.org][Timetable for PlanetMath development]]
 * [[file:sources of funding for PM.org][sources of funding for PM]]

* Discussion

See also: [http://www.archrespite.org/archfs6.htm ARCH Factsheet no. 6: Some General Principles of Charitable Nonprofit Fundraising].

This includes the following quote WRT whitepaper-style documents:

: /The strategic organizational market plan comprehensively
re-defines the organization for a specific term...usually three to
five years...and it acts as an operational blueprint. It analyzes the
needs of constituents, offers programs to suit those needs, projects
costs and reliable income, provides a specific fundraising plan for
each program, and provides sub-plans to recruit human resources,
communicate effectively to the world about the group, implement itself
over time, and continue to evaluate constituents' needs and responses
to the organization's current work./

Also, what they say about the importance of having an annual campaign
is interesting.  I suppose we might want to schedule our drive with
Wikipedia to make use of the click-through, or maybe not, but
whatever we do, this factsheet is definitely worth studying now that
we are serious about raising funds and growing the non-profit
organization.

([[file:rspuzio.org][rspuzio]])

I am curious about actually partnering with Wikipedia in a more direct
sense: could we just get a slice of their budget?

--[[file:jcorneli.org][jcorneli]]

In return for what?  I suppose we could do it in a way where they 
pay us and we keep supplying them with mathematical content.  Also,
there is the issue of how independant we would be if we got a slice 
of their budget.  It might be that the arrangement would be like the
usual relation with a corporate donor or it might be that we become
something like a subsidiary of Wikipedia.  Even the latter alternative
might not be so bad if we would retain a certain degree of autonomy 
and are able to pursue what we would have done anyhow (although I 
would much favour a scenario in which we have our own independant 
organization even if that requires more work).
--[[file:rspuzio.org][rspuzio]]
