#+STARTUP: showeverything logdone
#+options: num:nil



* Types of membership

There are at least two different kinds of membership we could consider.

**  "make a donation, become a member"

The first is a somewhat standard "make a donation, become a member" model,
familiar to us from PBS, FSF, and of course, scholarly societies and unions.

In this model, users pay some fee to become a member, and usually receive
some "perks" associated with membership (in addition to knowing that they
are helping to fund a useful, generally no-cost, resource).

If PM was to go this route, we would have to decide how much to charge for
membership (see [[file:proposed fee schedule for PM membership.org][proposed fee schedule for PM membership]]) and also what the
specific membership benefits would be (see [[file:PM Membership Benefits.org][PM Membership Benefits]]).

**  worker-member: the old-school co-op model

Many co-operative grocery stores work according to the "make a donation, become
a member" model.  The perk that they offer is a discount on your grocery bill.
The co-op typically uses the donation to make investments (as far as I
understand the story anyway).

A few grocery co-ops don't accept memberships of this sort.  The only members in
these kinds of co-ops are the people who work there.  And, again, these people
also get a discount on their groceries.  In addition, their fortune may rise or
fall with the fortunes of the co-operative.  I.e., if the store makes a lot of
money, they get a bonus on top of their usual paycheck.

*  Discussion

There are some nice things about the worker-member model -- but note that it
isn't going to /directly/ increase the amount of money in an organization's
coffers.  It relies on their being something to /sell/ for anyone to benefit.

It might help motivate people working on the site, though, if sales (of whatever
it was that was being sold) led to more money in their pocket.  Personally, as
someone who already puts a lot of work in on AM, FEM, etc., I think this would
be a nice model.  I see no reason why everyone shouldn't shouldn't be
financially rewarded for their efforts, assuming money is coming in from
somewhere.  And of course, if someone didn't want to take money, they wouldn't
have to.

The economics of the "membership type" decision are interesting.  To the extent
that capital is needed, the "make a donation" model may be the most important.
But PM has gotten many of its capital needs taken care of.  Now it needs income!

Well, to be fair, getting a loan from Aaron may not really be "having its
capital needs taken care of" -- maybe a "make a donation" membership drive could
be put together to try to pay that money back.  (If it could help pay for my
rent this month that would be cool too :).)

Note that the worker-member model is really the opposite of the so-called
author-pays model of publishing.  I.e., if PM finds a way to make some money
(e.g. through FEM publications) then there is a very real chance of authors
getting /paid/ to contribute.

However, it may be that author's don't need to get paid to contribute?  I don't
think anyone has /expected/ to get paid.  Maybe the title of "worker member"
should be only apply to people who are doing coding work, or people who are
doing editorial work, or people who are doing administrative work, or other
things like that, and the actual writing could be done 100% by volunteers.
(I don't know to what extent the public charity stuff forbids us from paying
authors; I sort of hope doesn't.)

I think it would be a good idea to sketch out the economics of the PM/Noosphere
(and friends) operations, so we can get more ideas about where money is needed
-- and of course, we should continue to discuss 
[[file:thoughts_on_the_viability_of_free-software_style_business|where it is going to come from.org][thoughts_on_the_viability_of_free-software_style_business|where it is going to come from]]
too.
--[[file:jcorneli.org][jcorneli]] Sat Apr 09 00:25:02 2005 UTC
