#+STARTUP: showeverything logdone
#+options: num:nil

Tuesday, March 30, 2010 *
3:00 PM -- 4:55 PM Eastern Daylight Time *
Dial-in Number: 1-605-475-6333  (Midwest) *
Access Code: 173949

** Possible agenda items

Left overs from last time:

 * *Springer template/design work completed, merging with PM*
 * *Schedule for moving to new server and resolving any remaining outstanding major performance issues, e.g. search*
 * *noosphere hacking has been put on hold until the above 2 points are resolved*
 * *Finishing up the re-import of our bib data*
 * *design science partnership proposal* (no update yet...)
 * ...

Newer stuff:

 * How do we feel about these "transparency docs"? http://metameso.org/~joe/docs/transparency.pdf (also live on PM in HTML)
 * How do we feel about this "strategic evaluation"? http://metameso.org/~joe/docs/pm-swot.pdf
 * Joe's Ph. D. prospectus will outline some development work related to PlanetMath http://metameso.org/~joe/docs/prospectus.pdf
 * Figuring out protocol for the new/potential "online math pavilion"; Dessci, Educator, other possible partnerships...
 * "Ad Free" subscriptions?
 * James -- Job title: Head of R&D? Senior Developer?
 * Board -- who is retiring, who is staying put, any new blood? (Protocol for elections?)  What constitutes good/bad/indifferent use of PlanetMath resources?  Does anyone (e.g. Joe) need to be asked politely modify his mode of participation and/or leave the project all together?  (And just out of curiousity what would that mean for my thesis...? Hm...)
 * ...
