#+STARTUP: showeverything logdone
#+options: num:nil

I feel like things have gotten a bit decayed at PM, and this page
is about getting things back in order (and better than before,
hopefully).  This all starts with a question "What would !PlanetMath
be like if we had an organizational secretary working on the project
5 to 10 hours a week, for a while?".  (For September, anyway, that person
will be me! -- see [[file:PlanetMath Admin.org][PlanetMath Admin]].)
I think there are a lot of things we could see happen in the remaining
months of 2009 and over the course of 2010.

So, this will be a place to start talking about that.  My "agenda"
is going to start to take shape below.

--[[file:jcorneli.org][jcorneli]]

----

** "whatever we need to move things forward"

Including:

 * maintaining the planetmath schedule, and keeping relevant parties plugged into it

 * "shepherding" ongoing tasks forward
  * [[file:PlanetMath Ongoing Tasks.org][PlanetMath Ongoing Tasks]]

 * helping out with (if not spearheading) intra-organizational communications
  * [[file:Hitchhiker's Guide to PlanetMath.org][Hitchhiker's Guide to PlanetMath]]

 * outside communications (ongoing relationships, fundraising, etc.)
  * [[file:Surveying the Math Metacommons.org][Surveying the Math Metacommons]]

 * taking care of certain admin/overhead tasks
