#+STARTUP: showeverything logdone
#+options: num:nil

Date Posted: Thursday Jan 8 2006.

Status: *available*

Time: 10 hrs (est.)

Bounty Price: $200 (US est.)

Objective:

Create a whitepaper or whitepaper-like document to bring about institutional collaboration between PM and other organizations.   Hopefully this will lead to support and development, with a particular emphasis on sustainable activities.

(No, this is not a "code" bounty at all, but it is a bounty).

Skills needed:

 * writing
 * experience with PM and CBPP
 * a diplomatic sense

* Background

Through our travel activities, we have connected with a number of important people who could help support PM, and whom we could help to develop related useful things for society in general.  These people include Ed Valauskas, of First Monday, and Lee Zia, of NSF/NSDL.  At this point they are basically waiting for a whitepaper from us.   Thus, this can be considered something of a pre-pre- grant; it is not quite to start the discussion, but to "get serious" about the discussion and ramp it up.

The document should discuss PlanetMath but be couched in a more general basis of developing CBPP and bringing about beneficial social impact, so that people other than "PM insiders" will be interested.   We are not necessarily out to get grants to do "just what we want", but to encourage the support of activities that we will be a part of that go in the directions we want to go, at least somewhat.

A number of documents that could form the basis for this document or contribute to it, including the PM "CBPP manifesto", the whitepaper, and past grant proposals or pre-proposals. 

* Plan

 1. pound out a document in the next few weeks (the author will work with Aaron, at minimum, and perhaps the PM board and community members)
 1. deliver it to key parties (Ed, Lee)
 1. post it and circulate it for general consumption

* Contact

Contact feedback@planetmath.org to inquire about this bounty.  See [[file:PlanetMath Code Bounties.org][PlanetMath Code Bounties]] for more on how bounties work.

* Discussion

See for preliminary drafts of relevant material:

 * http://planetmath.org/~jcorneli/manifesto-4j.pdf {.tex, .diff} (My latest revisions of a document by me, Aaron, and Ray).
 * http://planetmath.org/~jcorneli/superplan.txt (Aaron's notes with some !PlanetMath development ideas in it)
 * http://planetmath.org/~jcorneli/plan.tex {.pdf} (my version of a strategic plan, coming out of our earlier [[file:whitepaper.org][whitepaper]] effort)

These will likely be updated individually and then refactored into the
final document that this bounty describes.

--[[file:jcorneli.org][jcorneli]]
