#+STARTUP: showeverything logdone
#+options: num:nil

** PM Newsletter

On this page we will organize efforts for the first Newsletter for PlanetMath.  --[[file:bloftin.org][bloftin]]

* Newsletters

Here is an example I'd like to follow

http://giant.gd-ais.com/public_documents/newsletters/GIANT_Newsletter_V1_Issue_2_HIGH.pdf

Pathetic text examples on PlanetPhysics

http://aux.planetphysics.org/newsletters/

*  Regular Features

Just Ideas right now:

 * .org report - what is "officially" going on
 * highlights of recent entries
 * highlights of subprojects, and calls for participation
 * upcoming meetings
 * announcements of software developments
 * perhaps "ads" for math opportunities
 * recruiting for various things (such as representing us at conferences)
 * Tips and hints for users writing PM entries
 * LaTeX corner
 * Is budget info worth putting in, is it under .org report, etc.
 * A math puzzle, math problem
 * Noosphere code corner
 * Math History
 * Do we want anything outside PM, what's going on in the Math world around us, interview with a Mathematician, etc.
 * Book Review

**  On Assignment

Here to organize Assignments for Newsletters.

* Tools

For now unless others have better ideas, I will build it using  Apple's Pages.

** NEEDS

 * Please submit pictures of people/events, etc. related to PM to possibly be added to NL.
 * Please submit reviews of articles (quick blurbs)
 * Please submit favorite entries
 * I would like a small interview with ANYONE doing good for PM, ie. Aaron, pahio, mathcam, matte, rspuzio, joe, etc., please email me at (bloftin _a_t_ phys-x d_o_t_ org) if you are interested or hit me up on PM, user bloftin

 * Please submit interview questions.

* Pictures

* Reviews

* Favorite Entries

I think we should feature one of the well-put-tother [http://planetmath.org/?filters.type=0&op=enlist&mode=hits topic entries]. --[[file:akrowne.org][akrowne]] 

Ben's favorites:

[http://planetmath.org/?op=getobj&from=objects&id=3866 Set theory]

[http://planetmath.org/?op=getobj&from=objects&id=2263 induction]

[http://planetmath.org/?op=getobj&from=objects&id=6878 Algebraic Number Theory] (For trying to tie entries for learning a subject)


* Interview Questions
