#+STARTUP: showeverything logdone
#+options: num:nil

Advertise, advertise, advertise. If we want PlanetMath to grow, we need people to know PlanetMath, to understand the idea of PM and to appreciate PM to the point that these people become active and caring contributors. How do you get people to know PlanetMath? Advertisement! Actually, the way most people find PlanetMath is through Google, when they search for the favorite mathematical object and a PlanetMath hit appears in the listing. However, there are other ways of advertisement which should be exploited. Here comes the marketing:

We need creative and crafty people who are willing and able to design and produce advertisements for PlanetMath. Any sort of advertisement! The sky is the limit here, so shoot for the best you can manage to build. It can be a 1-page poster, it may be a large poster, or a simple jpg/gif banner, or a movie, a song, a poem, or it can be a cool design for a t-shirt, hat or sweater, or a design for a mug. Anything goes! The idea is to create forms of advertisement which can be easily placed online so people can download them, play with them and post them in their favorite mathematics departments, libraries, or coffee shops.

How can you contribute? It is simple! Create something cool and let us know! (email [[file:alozano.org][alozano]] or [[file:bloftin.org][bloftin]]). Also, see below. In this page we will be collecting items which you may want to use during the creative process.

In this page we will keep links to the available forms of advertisement for PlanetMath, and perhaps organize competitions for best posters. --[[file:alozano.org][alozano]]

** Posters

The easiest way to advertise PlanetMath is through 1-page posters that people can easily download, print and post. One idea is to create several posters, with different themes: algebra theme, analysis theme, geometry theme, high-school math, calculus, logic,... or posters of a general combination of themes. In fact, it would be useful to have a selection of posters covering all of those themes, so people can print the poster that will attract the larger audience.

Here is one example (by [[file:alozano.org][alozano]]) on a number-theory theme: http://www.math.cornell.edu/~alozano/PMposter.pdf This poster was created rather quickly, using MS Word and several images obtained from several entries in PlanetMath.

** PM Banners

Two banners can be found at the CafePress Planetmath store at http://www.cafepress.com/planetmath

** PM Graphics created for existing entries

In this section you can find links to entries which contain graphics or entries which look particularly good. One important tip: if you see an entry in html mode, and there is an image or graph or diagram that you like, you can right-click the image and save it to your computer as a .png object which you can later use to compose ads. --[[file:alozano.org][alozano]]

Notice that the word "quality" is being used in multiple ways, like a simple square isn't necessarily low quality, just low snazz. We are not trying to hurt anyone's feelings here.

"Aliasing, seems to be a problem in html mode"

 * Not quite done *

Why didn't I remember about Blender, check out 1st high quality pick, we need more. Way to go mathwizard.

* High Quality
http://planetmath.org/encyclopedia/MengerSponge.html
http://planetmath.org/?method=png&from=objects&name=Tetrahedron2&op=getobj
http://planetmath.org/encyclopedia/BridgesOfKoenigsberg.html
http://planetmath.org/encyclopedia/Torus.html
http://planetmath.org/encyclopedia/EllipticCurve.html
http://planetmath.org/encyclopedia/NiemytzkiPlane.html
http://planetmath.org/?method=png&from=objects&name=CommonFourierSeries&op=getobj
http://planetmath.org/encyclopedia/FrechetDerivative.html
http://planetmath.org/?method=png&from=objects&name=NewtonsMethodWorksForConvexRealFunctions&op=getobj
http://planetmath.org/encyclopedia/GreensFunctionForDifferentialOperator.html
http://planetmath.org/encyclopedia/FourColorConjecture.html
http://planetmath.org/?method=png&from=objects&name=SierpinskiTriangle&op=getobj
http://planetmath.org/?method=png&from=objects&name=HuffmanEncoding&op=getobj
http://planetmath.org/encyclopedia/RingHierarchy.html

* Medium Quality
http://planetmath.org/encyclopedia/HawaiianRings.html
http://planetmath.org/encyclopedia/FeigenbaumDeltaConstant.html
http://planetmath.org/encyclopedia/PerspectiveDrawing.html
http://planetmath.org/?method=png&from=objects&id=7789&op=getobj
http://planetmath.org/?op=getobj;from=objects;id=2779
http://planetmath.org/encyclopedia/AngleSumIdentity.html
http://planetmath.org/encyclopedia/UniversalMorphism.html
http://planetmath.org/encyclopedia/SawBladeFunction2.html
http://planetmath.org/?op=getobj;from=objects;id=3641
http://planetmath.org/?method=png&from=objects&name=WeierstrassFunction&op=getobj
http://planetmath.org/?method=png&from=objects&name=NapoleonsTheorem&op=getobj
http://planetmath.org/encyclopedia/ProofOfPappussTheorem.html
http://planetmath.org/?method=png&from=objects&name=NonCommutingGraphOfAGroup&op=getobj
http://planetmath.org/encyclopedia/HartogsTriangle.html
http://planetmath.org/encyclopedia/Orthocenter.html
http://planetmath.org/encyclopedia/ProofOfJordansInequality.html
http://planetmath.org/?method=png&from=objects&name=SpernersLemma&op=getobj
http://planetmath.org/encyclopedia/Homothetic.html
http://planetmath.org/encyclopedia/OcticGroup.html
http://planetmath.org/encyclopedia/Triangle.html
http://planetmath.org/encyclopedia/ProofOfVanAubelsTheorem.html
http://planetmath.org/encyclopedia/AristotelianLogic.html
http://planetmath.org/encyclopedia/ProofOfGoursatsTheorem.html
http://planetmath.org/encyclopedia/ShannonsTheoremEntropy.html
http://planetmath.org/?method=png&from=objects&id=3454&op=getobj
http://planetmath.org/?method=png&from=objects&name=TriangleSolving&op=getobj
http://planetmath.org/encyclopedia/ProofThatAnEqualizerIsAMonomorphism.html
http://planetmath.org/encyclopedia/NOmino.html
http://planetmath.org/encyclopedia/QuadraticInequality.html
http://planetmath.org/encyclopedia/RamificationPoint.html
http://planetmath.org/encyclopedia/KleinFourGroup.html
http://planetmath.org/encyclopedia/NorthPole.html
http://planetmath.org/encyclopedia/SecondFundamentalTheoremOfProjectiveGeometry.html
http://planetmath.org/encyclopedia/ProofThatTheSlopeOfALineIsWellDefined.html
http://planetmath.org/encyclopedia/Unramified.html
http://planetmath.org/?op=getobj&from=objects&id=6782
http://planetmath.org/encyclopedia/ClassificationOfIndecomposableRootSystems.html
http://planetmath.org/?op=getobj&from=objects&id=6790
http://planetmath.org/?op=getobj&from=objects&id=7720
http://planetmath.org/?op=getobj;from=objects;id=3092
http://planetmath.org/?op=getobj;from=objects;id=3064
http://planetmath.org/?op=getobj;from=objects;id=3079

* Low Quality

http://planetmath.org/encyclopedia/Hexagon.html
http://planetmath.org/encyclopedia/ConnectedSum.html
http://planetmath.org/encyclopedia/HeapsLaw.html
http://planetmath.org/encyclopedia/ButterflyTheorem.html
http://planetmath.org/encyclopedia/LeafNodeOfATree.html
http://planetmath.org/encyclopedia/ProofOfApolloniusTheorem2.html
http://planetmath.org/encyclopedia/PedalTriangle.html
http://planetmath.org/encyclopedia/Centroid.html
http://planetmath.org/encyclopedia/KneserGraphs.html
http://planetmath.org/encyclopedia/HeightOfATriangle.html
http://planetmath.org/encyclopedia/AlternativeProofOfTheSinesLaw.html
http://planetmath.org/encyclopedia/ChildNodeOfATree.html
http://planetmath.org/encyclopedia/Median.html
http://planetmath.org/?op=getobj;from=objects;id=1990
http://planetmath.org/encyclopedia/ParentNodeInATree.html
http://planetmath.org/encyclopedia/InternalNodeOfATree.html
http://planetmath.org/encyclopedia/ContinuityOfConvexFunctions.html
http://planetmath.org/encyclopedia/CantorFunction.html
http://planetmath.org/encyclopedia/KochCurve.html
http://planetmath.org/encyclopedia/SecantMethod.html
http://planetmath.org/encyclopedia/Perspectivity.html
http://planetmath.org/encyclopedia/Vector.html
http://planetmath.org/encyclopedia/PowerObject.html
http://planetmath.org/?method=png&from=objects&name=ZipfsLaw&op=getobj
