#+STARTUP: showeverything logdone
#+options: num:nil


I wonder about posting stuff that has no licensing terms.  This might be
annoying, but shouldn't this stuff be held to the same (or, anyway, similar)
standards for freedom as the encyclopedia? --[[file:jcorneli.org][jcorneli]] Sun Feb 27 15:24:49 2005 UTC

: IMO, no licensing terms are good licensing terms =).  The problem is restrictive licensing
terms, but people generally know well enough not to post such things.  And you know I'm not 
interested in holding everything to the GPL definition of freedom =) --[[file:akrowne.org][akrowne]] Sun Feb 27 16:28:39 UTC 2005

:: Well, copyright without any form of release is pretty darn restrictive.  I
don't even know about the legality of reposting such stuff on the web.  Legal
issues aside, I don't particularly care about the current PB&E stuff per se; the
issue in my mind is that the existence of a non-free section for PB&E may
decrease the motivation to create and develop free PB&E (whether copylefted or
no).  I would like to see PM become the premier place on the web for free PB&E
-- but it will take a lot of work to get there. --[[file:jcorneli.org][jcorneli]] Sun Feb 27 18:03:08 2005 UTC
