#+STARTUP: showeverything logdone
#+options: num:nil

** Board of Directors


 1. The purpose of the Board of Directors is to oversee the operations of
  the organization, make sure that they are consonant with the mission
  of the organization, and set goals for the organization.  
 1. The board represents the interests of the members and the nonmember
  "stakeholders" of the organization's activities (such as primary or
  secondary mathematics students).
 1. The oversight provided by the board is at a high level, dealing
  with the overall operation.
 1. The board is responsible for setting the organizational budget.    
 1. The board serves as a court of appeals for disputes within the
  organization which cannot be settled by ordinary means and
  investigates complaints of impropriety raised by members or
  employees of the organization.
 1. The board creates and destroys permanent positions within the
  organization. 
 1. The board creates and destroys committees to perform specific tasks
  (be they limited-term or ongoing).
 1. The board approves officers for the organization and reviews the
  performance of officers on an annual basis (and can relieve officers
  of their duties and replace them if it deems that they are not
  carrying out these duties in a manner consonant with the mission of
  the organization).
 1. A quorum of the board is a majority of the board.
 1. The board can create arbitrary operational policy by a majority vote.  
  This policy should be recorded in an officially-posted document.
 1. Board elections take place every other year.  
 1. A board member is automatically a member of the organization.

** Officers and Employees

 1. The officers and employees serve to conduct the day-to-day operations of
  the organization.  While the board sets the agenda in broad terms,
  it is the officers who implement this agenda, deciding how it is to
  be carried out and setting up subagendas and subgoals for that purpose.
 1. The President is also Executive Director and supervises the activities of the 
  other officers and ad hoc and non-officer ongoing hires.  The President
  has full discretion over hiring of non-officers, unless the board sets
  forth special policy dictating otherwise.
 1. For accountability, there will be at least annual reports to the board, which 
  will be also available publicly to the members.  The reports will be
  coordinated by the President, who can delegate portions to other officers.
 1. The officers are to be responsive to the needs to the community and
  their requests.  Officers should engage in and encourage discussion 
  within the community.

** Membership

 1. There are three ways one can become eligible to be member of the organization:
## Working Member --- Someone who has contributed at least 1000 points 
   to the PlanetMath.org web site, or who has contributed code to the codebase.
## Paying Member --- Someone who has donated at least $20 to the organization 
   within the last year.
## Board Member --- Someone who has been elected to the Board.
 1. Powers of Members:
## Members may propose
  board nominees but board members or officers may also nominate themselves or 
  other parties.
## Members ratify changes in the bylaws.
## Members vote on formal referenda.

** Board Meetings

 1. Official meetings shall take place quarterly at a time and date
  and venue set by the board with at least two week's public notice.
 1. Unless otherwise stated, board meetings shall be open to members.
