#+STARTUP: showeverything logdone
#+options: num:nil

Title:         Contributions to the mechanics of solids
                  dedicated to Stephen Timoshenko by his friends on the
                  occasion of his sixtieth birthday anniversary.
Published:     [New York, Boston, etc., The Macmillan Company,
                  1938]
Description:   viii p., 1 l.,, 277 p. front. (port.) illus.,
                  diagrs. 24 cm.
LC Call No.:   QA801.C65
Dewey No.:     620.1
Notes:         On cover: Stephen Timoshenko. 60th anniversary
                  volume.
               Contributions by J. M. Lessells. C. B. Biezeno
                  and J. J. Koch, J. P. Den Hartog, L. H. Donnell, O. W. Ellis,
                  Ludwig Föppl, J. N. Goodier, M. Hetényi, O. J. Horger,
                  William Hovgaard, M. T. Huber, L. S. Jacobsen, G. B.
                  Karelitz, Th. von kármán, B. F. Langer, C. W. MacGregor, R.
                  von Mises, A. Nadai, J. Ormondroyd, R. E. Peterson, L.
                  Prandtl, C. R. Soderberg, R. V. Southwell, G. I. Taylor, A.
                  M. Wahl, E. O. Waters, Stewart Way, E. E. Weibel, H. M.
                  Westergaard.
               Bibliography at end of some of the chapters.
Subjects:      Timoshenko, Stephen, 1878-
               Mechanics, Applied.
Control No.:   6905251

Author:        Andrade, J. (Jules), b. 1857.
Title:         Le mouvement, mesures de l'étendue et mesures du
                  temps, par J. Andrade. Avec 46 figures dans le texte.
Published:     Paris, F. Alcan, 1911.
Description:   vi, 328 p. illus., diagrs. 21 cm.
LC Call No.:   QA802.A5
Subjects:      Motion
               Length measurement
               Time measurements
               Force and energy
Control No.:   8725293

Author:        Boltzmann, Ludwig, 1844-1906. [from old catalog]
Title:         Über die grundprincipien und grundgliechungen
                  der mechanik.
Published:     [Worcester, Mass., Printed for the University,
                  1899]
Description:   p. 261-309. front. (port.) illus. 27 cm.
LC Call No.:   QA802.B69
Subjects:      Mechanics, Analytic. [from old catalog]
Other authors: Clark university, Worcester, Mass. [from old
                  catalog]
Control No.:   7261224

Author:        Brasch, Frederick Edward, 1875- [from old
                  catalog]
Title:         The Newtonian epoch in the American colonies
                  (1680-1783)
Published:     Worcester, Mass., The Society, 1940.
Description:   21 p. 25 cm.
LC Call No.:   QA802.B8
Subjects:      Newton, Isaac, Sir, 1642-1727 -- Influence.
               Science -- United States -- History -- 18th
                  century.
Other authors: American antiquarian society, Worcester, Mass.
                  [from old catalog]
Control No.:   8792471

Author:        Dugas, René. [from old catalog]
Uniform Title: Histoire de la mecanique. English. [from old
                  catalog]
Title:         A history of mechanics.
Published:     Neuchaten, Éditions du Griffon; New York,
                  Central Book Co. [c1955]
Description:   671 p. illus. 24 cm.
LC Call No.:   QA802.D8613
Subjects:      Mechanics -- History. [from old catalog]
               Wave mechanics. [from old catalog]
Control No.:   9341950

Author:        Duhem, Pierre Maurice Marie, 1861-1916.
Title:         L'évolution de la mécaníque,
Published:     Paris, A. Joanin et cie, 1903.
Description:   2 p. l., 348 p. 21 cm.
LC Call No.:   QA802.D87
Subjects:      Mechanics. [from old catalog]
Other authors: Revue générale des sciences pures et
                  appliquées. [from old catalog]
Control No.:   8203654

Author:        Duhem, Pierre Maurice Marie, 1861-1916.
Title:         Les origines de la statique, par P. Duhem.
Published:     Paris, A. Hermann, 1905-1906.
Description:   2 v. diagrs. 25.5 cm.
LC Call No.:   QA802.D89
Notes:         At head of title: Les sources des théories
                  physiques.
               Includes index.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Mechanics -- History.
               Statics.
Control No.:   8676244

Author:        Dühring, Eugene Karl, 1833-1921. [from old
                  catalog]
Title:         Kritische geschichte der allgemeinen principien
                  der mechanik ...  Von dr. E. Dühring ...
Edition:       2., theilweise umgearb. und mit einer anleitung
                  zum studium der mathematik verm aufl.
Published:     Leipzig, Fues (R. Reisland) 1877.
Description:   xx, 562 p. 22 cm.
LC Call No.:   QA802.D85 1877
               Microfilm 30031 QA
Notes:         LC copy replaced by microfilm.
Subjects:      Mechanics -- History. [from old catalog]
Control No.:   5916771

Author:        Freycinet, Charles de, 1828-1923.
Title:         Sur les principes de la mécanique rationelle,
                  par C. de Freycinet ...
Published:     Paris, Gauthier-Villars, 1902.
Description:   viii, 167, [2] p. 23 cm.
LC Call No.:   QA802.F9.
Subjects:      Mechanics.
Control No.:   5856161

Author:        Girvin, Harvey Frank, 1886-
Title:         A historical appraisal of mechanics.
Published:     Scranton, International Textbook Co., 1948.
Description:   ix, 275 p. diagrs. 24 cm.
Series:        International textbooks in civil engineering
LC Call No.:   QA802.G5
Dewey No.:     531.09
Notes:         Bibliography: p. 253-263.
Subjects:      Mechanics -- History.
Control No.:   9288683

Author:        Hielscher, Johannes, 1871-
Title:         Untersuchungen zur geschichtlichen entweikelung
                  der Logik in den prinzipien der Mechanik ...
Published:     Leipzig, W. Engelmann, 1901.
Description:   1 p. l., 84 p., 1 l. 23 cm.
LC Call No.:   QA802.H6
Notes:         Inaug.-Dis.--Zürich.
               Lebenslauf.
Subjects:      Mechanics.
Control No.:   9606156

Author:        Jourdain, Philip Edward Bertrand, [from old
                  catalog] ed.
Title:         Abhandlungen über jene grundsätze der
                  mechanik,
Published:     Leipzig und Berlin, W. Engelmann, 1914.
Description:   p. cm.
LC Call No.:   QA802.J6
Subjects:      Mechanics. [from old catalog]
Other authors: Newton, Isaac, Sir, 1642-1727. [from old
                  catalog]
               Bernoulli, Daniel, 1700-1782. [from old catalog]
               Arcy, Patrick d', 1725-1779. [from old catalog]
               Oettingen, Arthur Joachim von, 1836- [from old
                  catalog] tr.
Control No.:   8237150

Author:        [K. Akademie der wissenschaften, Berlin] [from
                  old catalog]
Title:         Jugement de l'Académie royale des sciences et
                  belles lettres sur une lettre prétendue de M. de Leibnitz.
Published:     [Berlin? 1752?]
Description:   1 p.l., 178, [4], ccxv p. diagrs. 26 x 20 cm.
LC Call No.:   QA802.A3
Subjects:      Mechanics -- History. [from old catalog]
               Least action.
               Literary forgeries and mystifications. [from old
                  catalog]
Other authors: Leibniz, Gottfried Wilhelm, freiherr von,
                  1646-1716. [from old catalog]
               Maupertuis, 1698-1759.
               König, Samuel, 1712-1757. [from old catalog]
               Euler, Leonhard, 1707-1783. [from old catalog]
Control No.:   8683907

Author:        Körner, Theodor, 1880-
Title:         Der begriff des materiellen punktes in der
                  mechanik des 18. jahrhunderts ...
Published:     Gera, Druck von T. Hofmann, 1904.
Description:   50, [2] p. diagr. 25 cm.
LC Call No.:   QA802.K77
Notes:         Inaug.-diss.--Kiel.
               Lebenslauf.
Subjects:      Mechanics -- History.
Control No.:   8673322

Author:        Lange, Ludwig, 1863- [from old catalog]
Title:         Der bewegungsbegriff während der reformation der
                  himmelskunde von Copernicus bis zu Newton (1543-1687)
Published:     Leipzig, W. Engelmann, 1886.
Description:   1 p. l., [1], [352]-419, [1] p. 23 cm.
LC Call No.:   QA802.L27
Subjects:      Motion. [from old catalog]
Control No.:   9146287

Author:        Lecornu, L. (Léon François Alfred), 1854-
Title:         La mécanique, les idées et les faits.
Published:     Paris, E. Flammarion, 1918.
Description:   2 p. l., 304 p. diagrs. 18 1/2 cm.
Series:        Bibliothèque de philosophie scientifique
LC Call No.:   QA802.L4
Dewey No.:     15614
Notes:         At head of title: Léon Lecornu.
Subjects:      Mechanics.
Control No.:   6376309

Author:        Lindt, Richard [August], 1876- [from old
                  catalog]
Title:         Das prinzip der virtuellen geschwindigkeiten ...
Published:     [Leipzig, B. G. Teubner, 1904]
Description:   3 p.l., [147]-19, [1] p. diagrs. 23 cm.
LC Call No.:   QA802.K75
Subjects:      Mechanics. [from old catalog]
Control No.:   9141187

Author:        Lipschitz, Rudolf Otto Sigismund, 1832-1903.
                  [from old catalog]
Title:         Bedeutung der theoretischen mechanik.
Published:     Berlin, C. Habel, 1876.
Description:   32 p. 21 cm.
LC Call No.:   AC30.S3 ser. 11, heft. 244
Subjects:      Mechanics -- History. [from old catalog]
Control No.:   6345249

Author:        Mach, Ernst, 1838-1916.
Title:         Die Mechanik in ihrer Entwickelung
                  historisch-kritisch Dargestellt, von Dr. Ernst Mach ... Mit
                  257 Abbildungen.
Edition:       5. verb. und verm. aufl.
Published:     Leipzig, F.A. Brockhaus, 1904.
Description:   xvi, 561 p. incl. illus., port. 19 cm.
Series:        Internationale wissenschaftliche Bibliothek. LIX.
                  Bd
LC Call No.:   QA802.M13 1904
Notes:         "Chronologische uebersicht einiger hervorragender
                  Forscher und ihrer für die Grundlengung der Mechanik
                  wichtigern Schriften": p. [556]-557.
Subjects:      Mechanics.
Control No.:   6393936

Author:        Mach, Ernst, 1838-1916.
Uniform Title: Mechanik in ihrer Entwickelung. English
Title:         The science of mechanics, a critical and
                  historical account of its development, by Dr. Ernest Mach ...
                  translated from the German by Thomas J. McCormack, containing
                  additions and alterations up to the ninth (final) edition,
                  with two hundred and fifty cuts and illustrations.
Edition:       5th ed.
Published:     La Salle, Ill., London, The Open court publishing
                  co., 1942.
Description:   xxxi, 635 p. incl. front. (port.) illus., diagrs.
                  20 cm.
LC Call No.:   QA802.M15 1942
Dewey No.:     531
Notes:         "Chronological table of a few eminent inquirers
                  and of their more important mechanical works": p. [617]-619.
Subjects:      Mechanics.
Other authors: McCormack, Thomas J. (Thomas Joseph), 1865-1932,
                  tr.
Control No.:   4527708

Author:        Mach, Ernst, 1838-1916.
Title:         The science of mechanics; a critical and
                  historical account  of its development, by Dr. Ernst Mach...
                  tr. from the German by Thomas J. McCormack.
Edition:       2d rev. and enl. ed., with 259 cuts and
                  illustrations.
Published:     Chicago, The Open Court publishing company;
                  [etc., etc.] 1902
Description:   xix p., 1 l., 605 p. illus., diagrs. 20 cm.
LC Call No.:   QA802.M15
Notes:         "Chronological table of a few eminent inquirers
                  and of their more important works": p. [589]-591.
Subjects:      Mechanics.
Other authors: McCormack, Thomas J. (Thomas Joseph), 1865-1932,
                  tr.
Control No.:   10071220

Author:        Mach, Ernst, 1838-1916.
Title:         The science of mechanics; a critical and
                  historical exposition of its principles, by Dr. Ernst
                  Mach...Tr. from the 2d German ed. by Thomas J. McCormack.
                  With two hundred and fifty cuts and illustrations.
Published:     Chicago, The Open court publishing co. [c1893]
Description:   xiv p., 1 l., 534 p. illus., diagrs. 20 cm.
LC Call No.:   QA802.M14
Notes:         "Chronological table of a few eminent inquirers
                  and of their more important mechanical works": p. [519]-521.
Subjects:      Mechanics.
Other authors: McCormack, Thomas J. (Thomas Joseph), 1865-1932,
                  tr.
Control No.:   9602921

Author:        Mach, Ernst, 1838-1916. [from old catalog]
Title:         Die mechanik in ihrer entwickelung;
Edition:       3. verb. und verm. aufl.
Published:     Leipzig, F. A. Brockhaus, 1897.
Description:   xii, 505, [1] p. illus., diagrs. 19 cm.
LC Call No.:   QA802.M13
Subjects:      Mechanics. [from old catalog]
Control No.:   8245751

Author:        Painlevé, Paul, 1863-1933.
Title:         Les axiomes de la mécanique, examen critique;
                  note sur la propagation de la lumière, par Paul Painlevé.
Published:     Paris, Gauthier-Villars et Cie, 1922.
Description:   xvii, 111, [1] p., 2 l. diagrs. 19 cm.
Series:        Les maitres de la pensée scientifique
LC Call No.:   QA802.P3
Subjects:      Mechanics.
               Light.
Control No.:   8744927

Author:        Ray, David H. (David Heydorn)
Title:         A history of mechanics ; a brief review of the
                  chief contributions of the eminent masters of the science, a
                  table of its development, a critique of the fundamental
                  mechanical concepts, and a bibliography of the science / by
                  David H. Ray.
Published:     Lancaster, Pa. : [New era] 1910.
Description:   vi, 147 p. : diagrs. ; 24 cm.
LC Call No.:   QA802.R2
Notes:         Bibliography: p. 146-147.
Subjects:      Mechanics -- History.
Control No.:   6353669

Author:        Reuterdahl, Arvid, 1876-1933.
Title:         A synthesis of number, space-time and energy, and
                  a physical basis for Planck's and Rydberg's constants. By
                  Arvid Reuterdahl ...
Published:     Brooklyn, N.Y., The Academy of Nations Press,
                  1923.
Description:   54 p. diagrs. 24 cm.
Series:        The Academy of Nations monographs. Scientific
                  series P. no. 1
LC Call No.:   QA802.R4
Subjects:      Mechanics.
Control No.:   7323530

Author:        Rühlmann, Moritz, 1811-1896.
Title:         Vorträge über geschichte der technischen
                  mechanik und theoretischen maschinenlehre, sowie der damit in
                  zusammenhang stehenden mathematischen wissenschaften.
                  Zunächst für technische lehranstalten bestimmt, von dr. M.
                  Rühlmann ... Mit zahlreichen holzschnitten und portraits in
                  stahlstich. 1. th.: Technische mechanic.
Published:     Leipzig, Baumgärtner, 1885.
Description:   xii, 553 p. illus., 5 port., diagrs. 23 cm.
LC Call No.:   QA802.R8
Dewey No.:     531.09
Notes:         With special t.-p.: Vorträge über geschichte
                  der technischen mechanik und der damit in zusammenhang
                  stehenden mathematischen wissenschaften.
               No more published.
Subjects:      Mechanics -- History.
Control No.:   6906064

Author:        Ziwet, Alexander, 1853-1928.
Title:         The relation of mechanics to physics. An address
                  by Alexander Ziwet, vice-president and chairman of Section A
                  for 1905 before the Section of mathematics and astronomy.
                  American association for the advancement of science. New
                  Orleans meeting, December 29, 1905-January 4, 1906.
Published:     Washington, D.C., Gibson bros., printers, 1906.
Description:   cover-title, p. [235]-248. 23 1/2 cm.
LC Call No.:   QA802.Z6
Notes:         Reprinted from the Proceedings of the American
                  association for the advancement of science, vol. LV, 1906.
Subjects:      Mechanics.
Control No.:   9624933

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. English
Title:         Newton's Principia. The mathematical principles
                  of natural philosophy, by Sir Isaac Newton; translated into
                  English by Andrew Motte. To which is added Newton's System of
                  the world; with a portrait taken from the bust in the Royal
                  observatory at Greenwich.
Edition:       1st American ed., carefully rev. and cor., with a
                  life of the author by N.W. Chittenden ...
Published:     New-York, D. Adee, 1848.
Description:   4, [v]-vii, [9]-581 p. front. (port.) diagrs. 24
                  cm.
LC Call No.:   QA803.A45 1848
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: Motte, Andrew, tr.
               Chittenden, N. W.
Control No.:   272618


Author:        Newton, Isaac, Sir, 1642-1727.
Title:         De mundi systemate liber / Isaaci Newtoni ; opus
                  diu integris suis partibus desideratum.
Published:     Londini : Impensis J. Tonson, J. Osborn & T.
                  Longman, T. Ward & E. Wicksteed, & F. Gyles, 1731.
Description:   iv, 108 p., II leaves of plates (folded) : ill. ;
                  24 cm. (4to)
LC Call No.:   QA803.N47 1731
Notes:         "Newtoni Princip. math. lib. III. initio"--P.
                  [iii]
               Signatures: Ap2s B-Op4s Pp2s.
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
               Celestial mechanics -- Early works to 1800.
Control No.:   983576

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia
Title:         Philosophiae naturalis principia mathematica /
                  auctore Isaaco Newtono ; perpetuis commentariis illustrata,
                  communi studio Thomae Le Seur et Francisci Jacquier.
Edition:       Editio nova, summa cura recensita.
Published:     Glasguae : G. Brookman ; Londini : T.T. et J.
                  Tegg, 1833.
Description:   2 v. : ill. ; 25 cm.
LC Call No.:   QA803.A2x 1833
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: Leseur, Thomas, 1703-1770.
               Jacquier, François, 1711-1788.
Control No.:   983639

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: De mundi systemate. English
Title:         A treatise of the system of the world. By Sir
                  Isaac Newton. Translated into English.
Edition:       The 2d ed., wherein are interspersed some
                  alterations and improvements.
Published:     London, Printed for Fayram, 1731.
Description:   vi, [9], 152 p. diagrs. 21 cm.
LC Call No.:   QA803.N48 1731
Notes:         Translation of De mundi systemate.
Subjects:      Celestial mechanics -- Early works to 1800.
               Newton, Isaac, Sir, 1642-1727. Principia.
Control No.:   1219841

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. English
Title:         The mathematical principles of natural
                  philosophy. By Sir Isaac Newton. Translated into English by
                  Andrew Motte. To which are added, Newton's System of the
                  world; A short comment on, and defence of, the Principia, by
                  William Emerson. With The laws of the moon's motion according
                  to gravity. By John Machin ...
Edition:       A new ed. (with the life of the author; and a
                  portrait, taken from the bust in the Royal observatory at
                  Greenwich) carefully rev. and cor. by W. Davis ...
Published:     London, Printed for H.D. Symonds, 1803.
Description:   3 v. front. (port.) 52 fold. pl. (diagrs.) fold.
                  tab. 22 cm.
LC Call No.:   QA803.A45 1803
Dewey No.:     531
Notes:         Superexlibris: arms of Trinity college, Dublin.
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: Motte, Andrew, d. 1734, tr.
               Davis, William, 1771-1807, ed.
               Emerson, William, 1701-1782.
               Machin, John, d. 1751.
Control No.:   2162705

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia
Title:         Sir Isaac Newton®s Principia reprinted for Sir
                  William Thomson ... and Hugh Blackburn ...
Published:     Glasgow, J. Maclehose, 1871.
Description:   xxxvi, 538 p. diagrs. 27 cm.
LC Call No.:   QA803.A2 1871
Notes:         Includes reprint of t.-p.: Philosophiae naturalis
                  principia mathematica. Auctore Isaaco Newtono, eq. aur.
                  Editio tertia aucta & emendata. Londini, apud G. & J. Innys,
                  1726.
               "Finding that all the editions of the Principia
                  are now out of print, we have been induced to reprint
                  Newton®s last edition without note or comment, only
                  introducing the "Corrigenda" of the old copy and correcting
                  typographical errors."--Editors® notice.
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: Kelvin, William Thomson, Baron, 1824-1907, ed.
               Blackburn, Hugh, jt. ed.
Control No.:   2634052

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. English
Title:         The mathematical principles of natural
                  philosophy, by Sir Isaac Newton; translated into English by
                  Andrew Motte: to which are added, Newton®s System of the
                  world; A short comment on, and defense of, the Principia, by
                  William Emerson; with The Laws of the moon®s motion according
                  to gravity, by John Machin ...
Edition:       A new ed. (with the life of the author; and a
                  portrait, taken from the bust in the Royal Observatory at
                  Greenwich) carefully rev. and corr. by William Davis ...
Published:     London, Printed for Sherwood, Neely, and Jones,
                  [etc.] 1819.
Description:   3 v. front. (port.) 54 pl. (7 fold.) tables,
                  diagrs. 22 cm.
LC Call No.:   QA803.A45 1819
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: Motte, Andrew, d. 1734, tr.
               Davis, William, 1771-1807, ed.
               Emerson, William, 1701-1782.
               Machin, John, d. 1751.
Control No.:   2634053

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. Liber I. English. Selections
Title:         Newton's Principia sections I., II., III. : with
                  notes and illustrations : also a collection of problems
                  principally intended as examples of Newton's methods / by
                  Percival Frost.
Published:     Cambridge : Macmillan, 1854.
Description:   vii, 275, 16 p. : ill. ; 19 cm.
LC Call No.:   QA803.F7x 1854
Notes:         Publisher's advertisements: p. 1-16 (3rd set)
Subjects:      Dynamics of a particle.
               Curves, Plane.
Other authors: Frost, Percival, 1817-1898.
Control No.:   2873449

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia
Title:         Philosophiæ naturalis principia mathematica.
Edition:       Editio 3. aucta & emendata.
Published:     Londini, G. & J. Innys, 1726.
Description:   530 p. port., diagrs. 25 cm.
LC Call No.:   QA803.A2 1726
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: John Davis Batchelder Collection (Library of
                  Congress) DLC
Control No.:   3112394

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. Liber I. English. Selections
Title:         The first three sections of Newton's Principia :
                  with copious notes and illustrations, and a great variety of
                  deductions and problems / by John Carr.
Published:     London : Baldwin, Cradock, and Joy, 1821.
Description:   iv, 167 p., [6] folded leaves of plates : ill. ;
                  22 cm.
LC Call No.:   QA803.C3x 1821
Notes:         "Designed for the use of students."
Subjects:      Dynamics of a particle.
               Curves, Plane.
Other authors: Carr, John, Rev.
Control No.:   3346105

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. Liber I. English. Selections
Title:         Newton's Principia, first book, sections I., II.,
                  III. : with notes and illustrations, and a collection of
                  problems principally intended as examples of Newton's methods
                  / by Percival Frost.
Published:     London : Macmillan, 1878.
Description:   xv, 292 p. : ill. ; 23 cm.
LC Call No.:   QA803.F7x 1878
Subjects:      Dynamics of a particle.
               Curves, Plane.
Other authors: Frost, Percival, 1817-1898.
Control No.:   3346161

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. Liber I. English. Selections
Title:         The first three sections of Newton's Principia :
                  with an appendix and the ninth and eleventh sections / by
                  John H. Evans.
Edition:       5th ed. / by P.T. Main.
Published:     Cambridge : Deighton, Bell ; London : Bell and
                  Daldy, 1871.
Description:   200, 15 p. : ill. ; 17 cm.
Series:        Cambridge school and college text books
LC Call No.:   QA803.E9x 1871
Notes:         Publisher's advertisements: p. 1-15 (2nd set)
Subjects:      Dynamics of a particle.
               Curves, plane.
Other authors: Evans, John H. (John Harrison), 1805-1880.
               Main, P. T. (Philip Thomas)
Control No.:   3346168

Author:        Brougham and Vaux, Henry Brougham, Baron,
                  1778-1868.
Title:         Analytical view of Sir Isaac Newton's Principia.
                  By Henry lord Brougham ... and E.J. Routh ...
Published:     London, Longman, Brown, Green & Longmans; [etc.,
                  etc.] 1855.
Description:   xxxi, [1], 442 p. diagrs. 23 cm.
LC Call No.:   QA803.B8
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
Other authors: Routh, Edward John, 1831-1907. joint author.
Control No.:   3579403

Author:        Ball, W. W. Rouse (Walter William Rouse),
                  1850-1925.
Title:         An essay on Newton's "Principia", by W.W. Rouse
                  Ball ...
Published:     London, New York, Macmillan and co., 1893.
Description:   x, 175 p. diagr. 20 cm.
LC Call No.:   QA803.B18
Notes:         Introductory. -- Investigations in 1666. -- In
                  1679. -- In 1684. -- Preparation of the Principia, 1685-1687.
                  -- Analysis of the Principia. -- Investigations from 1687 to
                  1726. -- Appendices. a. Correspondence between Hooke and
                  Newton, 1678-1680. b. Correspondence between Halley and
                  Newton, 1686-1687. c. On the correspondence concerning the
                  production of the 2d edition of the Principia. d. On the
                  correspondence concerning the production of the 3d edition of
                  the Principia.
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
Control No.:   4052134

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. Liber I. English. Selections
Title:         The first three sections of Newton's Principia;
                  with copious notes and illustrations, and a great variety of
                  deductions and problems. Designed for the use of students. By
                  the Rev. John Carr ...
Edition:       2d ed., imp. and enl.
Published:     Cambridge, Printed for Deighton and sons, 1826.
Description:   iv, [5]-183 p. diagrs. on 6 fold. pl. 22 cm.
LC Call No.:   QA803.C3
Subjects:      Dynamics of a particle.
               Curves, Plane.
Other authors: Carr, John, Rev., ed.
Control No.:   4052248

Author:        Pemberton, Henry, 1694-1771.
Title:         A view of Sir Isaac Newton's philosophy.
Published:     London, Printed by S. Palmer, 1728.
Description:   25 p.l., 407 p. 12 fold. pl. 29 cm.
LC Call No.:   QA803.P4
Notes:         Title vignette; head and tail pieces; initials.
               Dedication signed: Henry Pemberton.
               A poem of Sir Isaac Newton, by R. Glover: [15] p.
                  following the preface.
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
Other authors: Glover, Richard, 1712-1785.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   4052279

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: De mundi systemate. English
Title:         A treatise of the system of the world / by Sir
                  Isaac Newton ; translated into English.
Edition:       The third edition.
Published:     London : Printed for B. Motte and C. Bathurst
                  ..., 1737.
Description:   vi, [10], 152 p., [2] leaves of plates : ill.
                  (engravings) ; 21 cm. (8vo)
LC Call No.:   QA803.N48 1737
Notes:         Translation of: De mundi systemate.
               "From Sir Isaac Newton's Mathematical principles,
                  lib. III. introd."--P. [v].
               Signatures: A-Kp8s Lp4s.
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
               Celestial mechanics -- Early works to 1800.
Control No.:   4291569

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. Liber I. English. Selections
Title:         The first three sections of Newton's Principia :
                  with an appendix, and the ninth and eleventh sections /
                  edited by John H. Evans.
Edition:       3rd ed.
Published:     Cambridge : Printed at the University Press for
                  J. and J.J. Deighton, 1843.
Description:   93 p. : ill. ; 23 cm.
LC Call No.:   QA803.E9x 1843
Subjects:      Dynamics of a particle.
               Curves, Plane.
Other authors: Evans, John H. (John Harrison), 1805-1880.
Control No.:   4291570

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia
Title:         Philosophiæ naturalis principia mathematica.
                  Autore Is. Newton ... Imprimatur S. Pepys, Reg. soc. præses.
                  Julii 5. 1686.
Published:     Londini, Jussu Societatis Regiæ ac Typis Josephi
                  Streater. Prostat apud plures Bibliopolas. Anno 1687.
Description:   4 p.l., 383, 400-510 p., 1 l. fold. pl., diagrs.
                  25 cm.
LC Call No.:   QA803.A2 1687
Notes:         Signatures: [A]-Zp4s, (Hb2s lettered Gb2s),
                  Aa-Zzp4s, ***p4s, Aaa-Ooop4s.
               The second and third books were apparently
                  printed by different printers as indicated by the different
                  type in the headings and the break in paging between the two
                  books.
               Imperfect: folded plate wanting. Sig. Fff
                  reinforced with crepeline and badly discolored.
               "E libris Collegii Episcopalis a Societate de
                  propagando apud exteros evangelio prope Calcuttam fundati."
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Control No.:   4526738

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. English
Title:         Sir Isaac Newton's Mathematical principles of
                  natural philosophy and his System of the world, translated
                  into English by Andrew Motte in 1729. The translations
                  revised, and supplied with an historical and explanatory
                  appendix, by Florian Cajori ...
Published:     Berkeley, Calif., University of California press,
                  1934.
Description:   xxxv, 680 p. incl. front. (port.) facsim., 26
                  cm.
LC Call No.:   QA803.A45 1934
Dewey No.:     531
Notes:         With reproduction of the title-page of the first
                  edition of the Principia, London, 1687.
               "Editor's note to the present revision" signed:
                  R.T. Crawford.
Subjects:      Mechanics -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: Motte, Andrew, d. 1734, tr.
               Cajori, Florian, 1859-1930, ed.
               Crawford, R. T. (Russell Tracy), b. 1876, ed.
Other titles:  System of the world.
Control No.:   4527122

Author:        Maclaurin, [Colin], 1698-1746. [from old
                  catalog]
Title:         Exposition des découvertes philosophiques de M.
                  le chevalier Newton.
Published:     Paris, Durand [etc.] 1749.
Description:   lvii, [3], 422, [2] p. 6 fold. pl., fold. map. 27
                  cm.
LC Call No.:   QA803.M2
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia. [from
                  old catalog]
Other authors: Lavirotte, Louis-Anne, 1725-1759.
Control No.:   5859141

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         The mathematical principles of natural
                  philosophy. By Sir Isaac Newton. Tr. into English by Andrew
                  Motte. To which are added, The laws of the moon's motion
                  according to gravity. By John Machin.
Published:     London, Printed for B. Motte, 1729.
Description:   2 v. illus., tables (2 fold.) 47 pl. (22 fold.)
                  20 cm.
LC Call No.:   QA803.A45 1729
Notes:         Title of v.2 reads: The mathematical principles
                  of natural philosophy. By Sir Isaac Newton. Translated into
                  English.
               "The laws of the moon's motion according to
                  gravity," with half-title and separate pagination is appended
                  to both volumes.
Subjects:      Mechanics.
               Celestial mechanics.
Other authors: Motte, Andrew, d. 1730.
               Machin, John, d. 1751.
Control No.:   5860796

Author:        Voss, Albert.
Title:         Über die mechanischen Grundsätze und die
                  mathematische Entwickelungform Newton's in seinem Werke:
                  "Philosophiae naturalis principia mathematica".
Published:     Berlin, Druck von Liebheit & Thiesen, 1875.
Description:   40 p. diagrs. 22 cm.
LC Call No.:   QA803.V9
Notes:         Inaug.-Diss.--Göttingen.
Subjects:      Newton, Sir Isaac, 1642-1727. Principia.
Control No.:   6328120

Author:        Maclaurin, Colin, 1698-1746. [from old catalog]
Title:         An account of Sir Isaac Newton's philosophical
                  discoveries,
Published:     London, Printed for the author's children: and
                  sold by A. Millar, and J. Nourse; [etc., etc.] 1748.
Description:   p. cm.
LC Call No.:   QA803.M18 1748
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia. [from
                  old catalog]
Other authors: Murdoch, Patrick, d. 1774, [from old catalog]
                  ed.
Control No.:   6419139

Author:        [Voltaire, François Marie Arouet de] 1694-1778.
                  [from old catalog]
Title:         Élémen de philosophie de Newton,
Edition:       Nouv. éd.
Published:     Neuchatel [i.e. Paris, Panckoucke] 1772.
Description:   514 p. diagrs. 18 cm.
LC Call No.:   QA803.V6 1772
Subjects:      Newton, Isaac, Sir, 1642-1727. [from old
                  catalog]
               Du Châtelet, Gabrielle Emilie Le Tonnelier de
                  Breteuil, marquise, 1706-1749.
Control No.:   6846598

Author:        Maclaurin, Colin, 1698-1746. [from old catalog]
Title:         An account of Sir Isaac Newton's philosophical
                  discoveries,
Edition:       3d ed.
Published:     London, Printed for J. Nourse [etc.] 1775.
Description:   p. cm.
LC Call No.:   QA803.M18 1775
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia. [from
                  old catalog]
Other authors: Murdoch, Patrick, d. 1774, [from old catalog]
                  ed.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   7263562

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         Principes mathématiques de la philosophie
                  naturelle, par feue Madame la marquise du Chastellet ...
Published:     Paris, Desaint & Saillant [etc.] 1759.
Description:   2 v. tables, diagrs. on 14 fold. pl. 26 cm.
LC Call No.:   QA803.A53 1759
Notes:         "... Revue par M. Clairaut." --Avertissement de
                  l'éditeur.
               "Preface historique" by Voltaire: v. 1, p.
                  [v]-xiii.
               "Exposition abregée du Systéme du monde, et
                  explication des principaux phénomenes astronomiques tirée
                  des Principes de M. Newton" in v. 2, with separate
                  pagination.
Subjects:      Mechanics.
               Celestial mechanics.
Other authors: Du Châtelet, Gabrielle Emilie Le Tonnelier de
                  Breteuil, marquise, 1706-1749, ed. and tr.
               Clairaut, M., 1713-1765.
Control No.:   7265242

Author:        Newton, Isaac, Sir, 1642-1727. [from old
                  catalog]
Title:         The first three sections of Newton's Principia,
Edition:       2d ed.
Published:     Cambridge, Printed for T. Stevenson; [etc., etc.]
                  1837.
Description:   2 p. l., 95 p. diagrs. 22 cm.
LC Call No.:   QA803.E9
Subjects:      Dynamics of a particle. [from old catalog]
               Curves, Plane. [from old catalog]
Other authors: Evans, John Harrison, [from old catalog] ed.
Control No.:   7731802

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         Philosophiæ naturalis principia mathematica.
                  Auctore Issaco Newtono, equite aurato.
Edition:       Editio ultima, auctior et emendatior.
Published:     Amstælodami, sumptibus Societatis, 1714.
Description:   14 p. l., 484, [7] p. fold. pl., diagrs. 27 x 21
                  cm.
LC Call No.:   QA803.A2 1714
Notes:         Reprinted from the 2d edition, Cambridge, 1713.
                  cf. Gray, G.J. Bibl. of the works of Sir Isaac Newton. 1907.
               Edited by R. Cotes.
Subjects:      Mechanics.
               Celestial mechanics.
Other authors: Cotes, Roger, 1682-1716.
Control No.:   7806090

Author:        Clarke, John, 1682-1757.
Title:         A demonstration of some of the principal sections
                  of Sir Isaac Newton's Principles of natural philosophy. In
                  which his peculiar method of treating that useful subject, is
                  explained, and applied to some of the chief phaenomena of the
                  system of the world / by John Clarke ...
Published:     London : J. and J. Knapton, 1730.
Description:   xvi, 313, [7] p. : XVII fold. pl. (incl. diagrs.)
                  ; 24 cm.
LC Call No.:   QA803.C6
Notes:         Pages 62-63 incorrectly numbered.
               On spine: Clarke's Newton's philosophy.
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
               Mechanics.
               Celestial mechanics.
Control No.:   7866748

Author:        Whewell, William, 1794-1866.
Title:         An introduction to dynamics, containing the laws
                  of motion and the first three sections of the Principia. By
                  the Rev. W. Whewell.
Published:     Cambridge [Eng.] For J. & J. J. Deighton; [etc.,
                  etc.] 1832.
Description:   xvi, 64 p. diagrs. on 2 fold. pl. 22 cm.
LC Call No.:   QA803.W5
Subjects:      Dynamics of a particle.
               Newton, Isaac, Sir, 1642-1727. Principia.
Control No.:   8200346

Author:        Wright, J. M. F. (John Martin Frederick)
Title:         A commentary on Newton's Principia.
Published:     London, For T. T. & J. Tegg; [etc., etc.] 1833.
Description:   2 v. diagrs. 25 cm.
LC Call No.:   QA803.W92
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
Control No.:   8668498

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         Philosophiae naturalis principia mathematica /
                  auctore Isaaco Newtono, eq. aurato; perpetuis commentariis
                  illustrata, communi studio p. p. Thomae Le Seur & Francisci
                  Jacquier, ex gallicana Minimorum familia, matheseos
                  professorum.
Edition:       Editio altera longè accuratior & emendatior.
Published:     Coloniae Allobrogum : sumptibus C. & A.
                  Philibert, 1760.
Description:   3 v. : diagrs. ; 26 cm.
LC Call No.:   QA803.A2 1760
Notes:         "Traité sur le flux et reflux de la mer. Par mr.
                  Daniel Bernoulli": v.3, p. 133-246.
               Title vignette.
               Initials; head and tail pieces.
               "De causa physica fluxus et refluxus maris ad d.
                  Mac-laurin": v.3, p. 247-282.
               "Inquisitio physica in causam fluxus ac refluxus
                  maris ad d. Euler": v.3, p. 283-374.
Subjects:      Mechanics.
               Celestial mechanics.
               Tides.
Other authors: Leseur, Thomas, 1703-1770, ed.
               Jacquier, François, 1711-1788, joint ed.
               Bernoulli, Daniel, 1700-1782.
               MacLaurin, Colin, 1698-1746.
               Euler, Leonhard, 1707-1783.
Control No.:   8670152

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Principia. 1739
Title:         Philosophiæ naturalis principia mathematica.
                  Auctore Isaaco Newtono, eq. aurato.  Perpetuis commentariis
                  illustrata, communi studio pp. Thomæ Le Seur & Francisci
                  Jacquier ...
Published:     Genevæ, typis Barrillot & filii, bibliop. &
                  typogr., 1739-42.
Description:   3 v. diagrs. 26 cm.
LC Call No.:   QA803.A2 1739
Dewey No.:     531
Notes:         Title vignettes.
               "Traité sur le flux et reflux de la mer.  Par
                  mr. Daniel Bernoully": v. 3, p. 133-246.
               "De causa physica fluxus et refluxus maris.  A d.
                  d. Mac-Laurin": v. 3, p. 247-282.
               "Inquisitio physica in causam fluxus et refluxus
                  maris.  A d. d. Euler": v. 3, p. 283-374.
Subjects:      Mechanics.
               Celestial mechanics.
               Tides.
Other authors: Leseur, Thomas, 1703-1770, ed.
               Jacquier, François, 1711-1788, joint ed.
               Bernoulli, Daniel, 1700-1782.
               MacLaurin, Colin, 1698-1746.
               Euler, Leonhard, 1707-1783.
Control No.:   9222071

Author:        Newton, Isaac, Sir, 1642-1727. [from old
                  catalog]
Title:         Excerpta quædam e Newtoni Principiis philosophie
                  naturalis,
Published:     Veneunt apud T. & J. Merrill, et J. Nicholson;
                  [etc., etc.] 1765.
Description:   ix, [1], 180 p. xii fold. diagr. 27 cm.
LC Call No.:   QA803.A4 1765 (Rare Bk Coll)
Subjects:      Mechanics. [from old catalog]
               Celestial mechanics.
Other authors: Jebb, John, 1736-1786, ed.
Control No.:   9256902

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         The three first sections and part of the seventh
                  section of Newton's Principia, with a preface recommending a
                  geometrical course of mathematical reading, and an
                  introduction on the atomic constitution of matter, and the
                  laws of motion.
Published:     Oxford [etc.] J.H. Parker, 1850.
Description:   iv, 163 p. diagrs. 23 cm.
LC Call No.:   QA803.C7
Subjects:      Dynamics of a particle.
               Curves, Plane.
Other authors: Cooke, George Leigh, 1780?-1853, ed.
Control No.:   10073686

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         Philosophiæ naturalis principia mathematica.
                  Auctore Isaaco Newtono, eq. aurato. Perpetuis commentariis
                  illustrata, communi studio pp. Thomæ Le Seur et Francisci
                  Jacquier ex gallicana Minimorum familia, matheseos
                  professorum.
Edition:       Ed. nova, summa cura recensita ...
Published:     Glasguæ, ex prelo academico, typis A. et J.M.
                  Duncan; [etc.,etc] 1822.
Description:   4 v. in 3. diagrs. 24 cm.
LC Call No.:   QA803.N4 1822
Dewey No.:     531
Notes:         Edited by John Martin Frederick Wright.
Subjects:      Mechanics.
               Celestial mechanics.
               Tides.
Other authors: Leseur, Thomas, 1703-1770.
               Jacquier, François, 1711-1788.
               Wright, J. M. F. (John Martin Frederick) ed.
Control No.:   10159329

Author:        Wright, J. M. F. (John Martin Frederick)
Title:         Principia of Newton 1830.
Published:     [n.p., n.d.]
Description:   1 v. cm.
LC Call No.:   QA803.W9
Control No.:   10484217

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         Axiomata sive leges motus [graphic].
Published:     [published 1687]
Description:   2 p.
LC Call No.:   Illus. in QA803.A2 1687
Notes:         Newton's three laws of motion and diagram of
                  parallelogram, in chapter entitled Axiomata sive leges
                  Motus.
               Illus. and text in: Philosophiae naturalis
                  principia mathematica / Isaac Newton. Londini : Jussu
                  Societatis Regia ac Typus J. Streator, 1687, pp. 12-13.
               Published in: The tradition of science / Leonard
                  C. Bruno. Washington, D.C. : Library of Congress, 1987, p.
                  39.
Availability:  LC-USZ62-95173 DLC (b&w film copy neg.)
Subjects:      Physics -- England -- London -- 1680-1690. lctgm
               Scientific illustrations -- 1680-1690. gmgpc
               Book illustrations -- 1680-1690. gmgpc
Control No.:   11606862
Access:        b&w film copy neg.

Author:        Pemberton, Henry, 1694-1771.
Uniform Title: View of Sir Isaac Newton's philosophy. Italian
Title:         Saggio della filosofia del signor cav. Isacco
                  Newton / esposto con chiarezza dal signor Enrico Pemberton
                  con una dissertazione dello stesso su la misura della forza
                  de'corpi in moto cavata dagli atti filosofici d'Inghilterra ;
                  opera tradotta dall'inglese ; aggiuntovi l'estratto di altra
                  dissertazione contraria su lo stesso argomento.
Published:     In Venezia : Presso Francesco Storti ..., 1733.
Description:   [8], xviij, 232, [2] p., XII folded leaves of
                  plates : ill. (1 woodcut, engravings) ; 25 cm. (4to)
LC Call No.:   QA803.P416 1733
Notes:         Imprint date precedes publisher.
               Signatures: Ap4s p2sAp4s B-2Gp4s
                  [2H]p2s.
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
Control No.:   12299344

Author:        Akademiëiìa nauk SSSR.
Title:         Commentarii Academiae scientiarvm imperialis
                  petropolitanae.
Published:     Petropoli, typis Academiae, 1728-51.
Description:   14 v. plates, maps, tables, diagrs. 26 cm.
LC Call No.:   QA804.E88
Control No.:   9620127

Author:        Alembert, Jean Le Rond d', 1717-1783.
Title:         Traité de dynamique, dans lequel les loix de
                  l'équilibre & du mouvement des corps sont réduits au plus
                  petit nombre possible, & démontrées d'une maniere nouvelle,
                  & où l'on donne un principe général pour trouver le
                  mouvement de plusieurs corps qui agissent les uns sur les
                  autres d'une maniere quelconque. Par M. d'Alembert.
Edition:       Nouv. ed., ref. & fort augm. par l'auteur.
Published:     Paris, David, 1758.
Description:   6 p. l., xl, 272, xiii p. diagrs. on 5 fold. pl.
                  23 x 17 cm.
LC Call No.:   QA804.A35
Control No.:   7264907

Author:        Alembert, Jean Le Rond d', 1717-1783.
Title:         Traité de l'équilibre et mouvement de fluides,
                  pour servir de suite au Traité de dynamique.
Edition:       Nouv. éd., rev. & augm.
Published:     Paris, Briasson, 1770.
Description:   xlvi p., 1 l., 476 p. diagrs. on 10 fold. pl. 23
                  x 17 cm.
LC Call No.:   QA804.A37
Subjects:      Fluid mechanics.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   9138068

Author:        Bossut, Charles, 1730-1814.
Title:         Traité élementaire de méchanique et de
                  dinamique : appliqué principalement aux mouvemens des
                  machines / par M. l'abbé Bossut ...
Published:     A Charleville : Chez Pierre Thesin ..., 1763.
Description:   [4], xvj, 239, [3] p., 7 folded leaves of plates
                  : ill. ; 21 cm. (8vo)
LC Call No.:   QA804.B67 1763
Notes:         Signatures: pip2s ap8s A-Pp8s [Q]1.
               LC copy has bookseller's label of P. Gadury,
                  Bordeaux. DLC
Subjects:      Mechanics -- Early works to 1800.
               Dynamics -- Early works to 1800.
Control No.:   12305325

Author:        Carnot, Lazare, 1753-1823.
Title:         Essai sur les machines en général,
Published:     Dijon, A. M. Defay, 1782.
Description:   x, [11]-107, [1] p. 20 cm.
LC Call No.:   QA804.C3 1782 (Rare bk. Coll.)
Subjects:      Equilibrium. [from old catalog]
               Mechanics. [from old catalog]
Control No.:   10218186

Author:        Carnot, Lazare, 1753-1823.
Title:         Principes fondamentaux de l'équilibre et du
                  mouvement; par L. N. M. Carnot ...
Published:     Paris, Chez Deterville, an XI. 1803.
Description:   xxii, 262 p., 1 l. II fold. pl. 21 cm.
LC Call No.:   QA804.C3 1803
Dewey No.:     531
Notes:         The first edition was published in 1783 under
                  title: Essai sur les machines en général.  cf. Pref.
Subjects:      Equilibrium.
               Mechanics.
Control No.:   7364811

Author:        Euler, Leonhard, 1707-1783.
Title:         Theoria motvs corporvm solidorvm sev rigidorvm ex
                  primis nostrae cognitionis principiis stabilita et ad omnes
                  motvs, qvi in hvivsmodi corpora cadere possvnt, accommodata.
                  Avctore Leonh. Eulero.
Edition:       Editio nova, desideratissimi avtoris svpplementis
                  locvpletata et emendata.
Published:     Gryphiswaldiae, litteris et impensis A. F. Röse,
                  1790.
Description:   18 p.l., [3]-624 p. XVIII pl. (diagrs.) 23 x 18
                  cm.
LC Call No.:   QA804.E89 1790
Notes:         Title vignette (publisher's device?)
               Previously published 1765.
               Preface signed: Wencesl. Joh. Gvstavus Karsten.
Subjects:      Dynamics, Rigid.
Other authors: Karsten, Wenceslaus Johann Gustav, 1732-1787,
                  ed.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   5979876

Author:        Hermann, Jacob, 1678-1733.
Title:         Phoronomia, sive De viribus et motibus corporum
                  solidorum et fluidorum libri duo. Autore Jacobo Hermanno
                  Basil. ...
Published:     Amstelædami, apud R. & G. Wetstenios, h. ff.,
                  1716.
Description:   10 p.l., 401, [1] p., 1 l. diagrs. on 12 fold.
                  pl. 26 x 21 cm.
LC Call No.:   QA804.H55
Notes:         Added t.-p. engr.
Subjects:      Mechanics, Analytic -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   1217100

Author:        Lagrange, J. L. (Joseph Louis), 1736-1813.
Title:         Mécanique analytique, par J.L. Lagrange.
Edition:       4. éd. contenant les notes de l'édition de M.J.
                  Bertrand. Publiée par Gaston Darboux ...
Published:     Paris, Gauthier-Villars et fils, 1888-89.
Description:   2 v. 29 x 23 cm.
Series:        Œuvres de Lagrange, publiées sous les auspices
                  de M. le ministre de l'instruction publique, t. XI-XII
LC Call No.:   QA804.L2
Subjects:      Mechanics, Analytic.
Other authors: Bertrand, Joseph, 1822-1900.
               Darboux, Gaston, 1842-1917, ed.
Control No.:   9606573

Author:        Lagrange, J. L. (Joseph Louis), 1736-1813.
Title:         Mécanique analytique, par J.L. Lagrange ...
Edition:       Nouv. éd., rev. et augm. par l'auteur ...
Published:     Paris, Ve Courcier, 1811-15.
Description:   2 v. 27 x 21 cm.
LC Call No.:   QA804.L17
Notes:         "Liste des ouvrages de M. Lagrange, communiquée
                  par M. Lacroix": v. 2, p. [372]-378.
Subjects:      Mechanics, Analytic.
Control No.:   3579385

Author:        Laplace, P[ierre] S[imon] marquis de, 1749-1827.
                  [from old catalog]
Title:         A treatise upon analytical mechanics; being the
                  first book of the Mechanique celeste of P. S. Laplace ...
Published:     Nottingham, Printed by H. Barnett, 1814.
Description:   vii, 286 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA804.L31
Subjects:      Mechanics, Analytic. [from old catalog]
Other authors: Toplis, John, [from old catalog] tr.
Control No.:   7731239

Author:        Marie, Joseph-François, 1738-1801.
Title:         Traité de méchanique / par M. l'abbé Marie
                  ...
Published:     A Paris : Chez la Veuve Desaint ..., 1774.
Description:   viij, 440 p., XII folded leaves of plates : ill.
                  (engravings) ; 26 cm. (4to)
LC Call No.:   QA804.M375 1774
Notes:         "De l'imprimerie de L.F. Delatour ...":
                  colophon.
               Signatures: pip4s A-3Ip4s.
               LC copy has pencilled annotations throughout.
                  DLC
Subjects:      Mechanics -- Early works to 1800.
Control No.:   12338040

Author:        Prony, [Gaspard Clair François Marie Riche],
                  baron de, 1755-1839. [from old catalog]
Title:         Leçons de mécanique analytique, données à
                  l'École royale polytechnique par Mr de Prony ...
Published:     Paris, Impr. de l'École royale des ponts et
                  chaussées, 1815.
Description:   2 v. diagrs. on 4 fold. pl. 27 cm.
LC Call No.:   QA804.P97
Subjects:      Mechanics, Analytic. [from old catalog]
Control No.:   10073548

Author:        Prony, R. (Riche), 1755-1839.
Title:         Mécanique philosophique, ou Analyse raisonnée
                  des diverses parties de la science de l'équilibre et du
                  mouvement; par R. Prony ...
Published:     Paris, Imprimerie de la République, an VIII
                  [1800]
Description:   1 p.l., vii, 477, [2] p. 27 cm.
LC Call No.:   QA804.P96
Notes:         "Ouvrage faisant partie du Journal de l'École
                  polytechnique; il n'est pas complet.  L'auteur avait promis
                  cinq parties avec un tableau synoptique de toutes les parties
                  de la mécanique, mais le volume ci-dessus ne contient que
                  les trois premières parties." -- Quérard, La France
                  littéraire.
Subjects:      Mechanics, Analytic.
Control No.:   4052239

Author:        Sigorgne, M. l'abbé (Pierre), 1719-1809.
Title:         Institutions Newtoniennes, ou, Introduction a la
                  philosophie de M. Newton / par M. Sigorgne ...
Published:     A Paris : Chez Jacques-François Quillau ...,
                  1747.
Description:   2 v. (xlviij, 528 p., [5] folded leaves of
                  plates) : ill. (engravings) ; 20 cm. (8vo)
LC Call No.:   QA804.S57 1747
Notes:         Paged continuously.
               Vol. 1: xlviij, 243, [1] p.; v. 2: [3], 244-528
                  p., A, IV folded leaves of plates.
               LC copy bound into 1 v. DLC
Subjects:      Mechanics -- Early works to 1800.
               Newton, Isaac, Sir, 1642-1727.
Control No.:   12503465

Author:        Sigorgne, M. l'abbé (Pierre), 1719-1809.
Title:         Institutions newtoniennes / par M. Sigorgne ...
Edition:       Seconde edition, revûe, corrigée & augmentée,
                  avec figures.
Published:     A Paris : Chez Guillyn, libraire ..., 1769.
Description:   lvi, xlix, [3], 393, [3] p., 7 [i.e. 6] folded
                  leaves of plates : ill. (engravings) ; 20 cm. (8vo)
LC Call No.:   QA804.S57 1769
Notes:         Plates 3 and 4 are on same leaf.
               Signatures: a-cp8s dp4s, p2sa-cp8s
                  p2sdp2s A-2Ap8s 2Bp6s.
               Errata: p. [2-3] at end.
               LC copy has bookplate of C.-M. Gabriel, Paris,
                  1879 on front paste-down. DLC
Subjects:      Mechanics -- Early works to 1800.
               Newton, Isaac, Sir, 1642-1727.
Control No.:   12381560

Author:        Stewart, Matthew, 1717-1785.
Title:         Tracts, physical and mathematical : containing,
                  an explication of several important points in physical
                  astronomy and a new method for ascertaining the sun's
                  distance from the earth, by the theory of gravity / by
                  Matthew Stewart.
Published:     Edinburgh : Printed for W. Sands, 1761.
Description:   vii, 411 p., [19] folded leaves of plates : ill.
                  ; 21 cm.
LC Call No.:   QA804.S84
Subjects:      Mechanics, Analytic -- Early works to 1800.
               Celestial mechanics -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   7731662

Author:        Airlines War Training Institute.
Title:         Mechanical principles, prepared for aircraft
                  flight and ground crews, by Sherman E. Crites, illustrated by
                  William Damon.
Published:     Washington, The Infantry journal, 1944.
Description:   3p. l., 66 p. illus., diagrs. 20 cm.
LC Call No.:   QA809.A5 1944
Dewey No.:     531.9
Notes:         Reproduced from type-written copy.
               "Revised October 1943."
               "Originally published by Airlines war training
                  institute."
Subjects:      Mechanics -- Problems, exercises, etc.
Other authors: Crites, Sherman Edwin, 1918-
Control No.:   8336511

Author:        Airlines War Training Institute.
Title:         Mechanical principles, prepared for aircraft
                  flight and ground crews.  Copyright ... by Airlines war
                  training institute ...
Published:     Washington, D.C., c 1942.
Description:   1 p. l., 68 p. illus., diagrs. 28 x 21 cm.
LC Call No.:   QA809.A4
Dewey No.:     531.9
Notes:         Reproduced from type-written copy.
               "Preparation:  Sherman E. Crites; illustration: 
                  William Damon."
Subjects:      Mechanics -- Problems, exercises, etc.
Other authors: Crites, Sherman Edwin, 1918-
Control No.:   8795036

Author:        [Bland, Miles], 1786-1868. [from old catalog]
Title:         Mechanical problems, adapted to the course of
                  reading pursued in the University of Cambridge: collected and
                  arranged for the use of students.
Published:     London, G. B. Whittaker; [etc., etc.] 1828.
Description:   vi, [2], 184 p. 22 cm.
LC Call No.:   QA809.B64
Subjects:      Mechanics -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   8200323

Author:        Dadourian, Haroutune Mugurditch, 1878- [from old
                  catalog]
Title:         A general method for working on problems in
                  mechanics
Published:     New York, D. Van Nostrand company, 1919.
Description:   2 p.l., 10 p. diagrs. 23 cm.
LC Call No.:   QA809.D3
Subjects:      Mechanics -- Problems, exercises, etc.
Control No.:   6845571

Author:        Hedrick, E. R. (Earle Raymond), 1876-1943.
Title:         Applications of the calculus to mechanics, by
                  E.R. Hedrick ... and O.D. Kellogg ...
Published:     Boston, New York [etc.] Ginn and company,
                  [c1909]
Description:   vi, 116 p. diagrs. 21 cm.
LC Call No.:   QA809.H4
ISBN:          $1.25.
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Mechanics -- Problems, exercises, etc.
Other authors: Kellogg, O. D. (Oliver Dimon), b. 1878, joint
                  author.
Control No.:   3579920

Author:        Jullien, Michel Marie, b. 1827.
Title:         Problèmes de mécanique rationelle disposés
                  pour servir d'applications aux principes enseignés dans les
                  cours, par le p. M. Jullien ...
Published:     Paris, Mallet-Bachelier, 1855.
Description:   2 v. diagrs. 22 cm.
LC Call No.:   QA809.J8
Subjects:      Mechanics, Analytic.
               Mechanics -- Problems, exercises, etc.
Control No.:   8792577

Author:        Karelitz, George Boris, 1895- [from old catalog]
Title:         Problems in mechanics, based on the original
                  collection of I.V. Mestchersky, by G.B. Karelitz ... J.
                  Ormondroyd ... [and] J.M. Garrelts.
Published:     New York, The Macmillan company, 1939.
Description:   ix, 271 p. illus., diagrs. 24 cm.
Series:        Engineering science series
LC Call No.:   QA809.K3
Subjects:      Mechanics -- Problems, exercises, etc.
Other authors: Ormondroyd, J. (Jesse), 1897- joint author.
               Garrelts, Jewell Milan, 1903- [from old catalog]
                  joint author.
               Meshcherskiæi, I. V. (Ivan Vsevolodovich),
                  1859-1935.
Control No.:   12906261

Author:        Sanborn, Frank B. (Frank Berry), 1865-
Title:         Mechanics : problems for engineering students /
                  by Frank B. Sanborn.
Edition:       2nd ed., rev. and enl.
Published:     New York : J. Wiley, 1906.
Description:   viii, 194 p. : ill. ; 21 cm.
LC Call No.:   QA809.S22
Subjects:      Mechanics -- Problems, exercises, etc.
Control No.:   6334941

Author:        Sanborn, Frank B[erry]. [from old catalog]
Title:         Mechanics--problems, for engineering students,
Published:     New York, The Engineering news publishing
                  company, 1902.
Description:   1 p.l., 155 p. illus. 21 cm.
LC Call No.:   QA809.S2
Subjects:      Mechanics -- Problems, exercises, etc.
Control No.:   9132270

Author:        Seely, Fred B., 1884-
Title:         Analytical mechanics for engineers [by] Fred B.
                  Seely [and] Newton E. Ensign.
Edition:       4th ed.
Published:     New York, Wiley [1952]
Description:   xiv, 443 p. illus. 22 cm.
LC Call No.:   QA809.S4 1952
Dewey No.:     531
Subjects:      Mechanics, Analytic.
               Mechanics -- Problems, exercises, etc.
Control No.:   8842198

Author:        Seely, Fred B., 1884-
Title:         Analytical mechanics for engineers [by] Fred B.
                  Seely [and] Newton E. Ensign.
Edition:       3d ed., rewritten.
Published:     New York, Wiley; London, Chapman & Hall, limited,
                  1941.
Description:   xv, 450 p. illus. 24 cm.
LC Call No.:   QA809.S4 1941
Dewey No.:     531
Subjects:      Mechanics, Analytic.
Other authors: Ensign, Newton Edward, 1882- joint author.
Control No.:   5980154

Author:        Seely, Fred B., 1884-
Title:         Analytical mechanics for engineers, by Fred B.
                  Seely ... and Newton  E. Ensign.
Published:     New York, J. Wiley & sons, 1921.
Description:   xiv, 486 p. diagrs. 24 cm.
LC Call No.:   QA809.S4 1921
Subjects:      Mechanics, Analytic.
Other authors: Ensign, Newton Edward, 1882- joint author.
Control No.:   10128054

Author:        Seely, Fred B., 1884-
Title:         Analytical mechanics for engineers, by Fred B.
                  Seely ... and Newton E. Ensign ... Total issue, twenty
                  thousand, seventh printing, with additional problems.
Published:     New York, J. Wiley & Sons, inc.; London, Chapman
                  & Hall, limited, 1927.
Description:   2 p. l., iii-xiv, 508 p. diagrs. 24 cm.
LC Call No.:   QA809.S4 1927
Subjects:      Mechanics, Analytic.
Other authors: Ensign, Newton Edward, 1882- joint author.
Control No.:   6865296

Author:        Seely, Fred B., 1884-
Title:         Analytical mechanics for engineers [by] Fred B.
                  Seely, Newton E. Ensign [and] Paul G. Jones.
Edition:       5th ed.
Published:     New York, Wiley [1958]
Description:   475 p. illus. 22 cm.
LC Call No.:   QA809.S4 1958
Dewey No.:     531
Subjects:      Mechanics, Analytic.
               Mechanics -- Problems, exercises, etc.
Control No.:   6538631

Author:        Seely, Fred B., 1884- [from old catalog]
Title:         Analytical mechanics for engineers,
Edition:       2d ed.
Published:     New York, J. Wiley & sons, inc; 1933.
Description:   p. cm.
LC Call No.:   QA809.S4 1933
Subjects:      Mechanics, Analytic. [from old catalog]
Other authors: Ensign, Newton Edward, 1882- [from old catalog]
                  joint author.
Control No.:   6882418

Author:        Walton, William, 1813-1901.
Title:         A collection of problems in illustration of the
                  principles of theoretical mechanics, by William Walton ...
Edition:       2d ed.
Published:     Cambridge, Deighton, Bell and Co.; [etc., etc.]
                  1855.
Description:   viii, 566 p. diagrs. on 7 fold. pl. 22 cm.
LC Call No.:   QA809.W24
Subjects:      Mechanics -- Problems, exercises, etc.
Control No.:   10073689
