#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Wiecke, Paul, 1829- [from old catalog]
Title:         Quaeritur, num duae ellipsoides quocunque modo
                  sitae parallelos habeant diametros coniugatas...
Published:     Bonnae, typis C. Georgii [1857]p
Description:   1 p.l., 26, [2] p. 21 cm.
LC Call No.:   QA651.W64
Subjects:      Ellipsoid. [from old catalog]
Control No.:   8669729

Author:        Beenken, May Margaret, 1901-
Title:         Surfaces in five-dimensional space.
Published:     1928.
Description:   ii, 48 l. 29 cm.
LC Call No.:   QA660.B43
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Projective differential geometry.
               Hypersurfaces.
Control No.:   4572151

Author:        Clement, Mary Dean, 1914-
Title:         Loci of osculants of asymptotic plane sections of
                  a surface ... by Mary Dean Clement.
Published:     Chicago, Ill., 1944.
Description:   iv, 35 p. incl. tables, diagrs. 23 cm.
LC Call No.:   QA660.C55
Notes:         Thesis (PH. D.)--University of Chicago, 1941.
               Lithoprinted.
               Vita.
               Bibliographical foot-notes.
Subjects:      Projective differential geometry.
Control No.:   3581895

Author:        Davis, Watson M., 1903-
Title:         Contributions to the theory of conjugate nets ...
                  by Watson M. Davis ...
Published:     [Chicago] 1935.
Description:   2 p.l., 29 p. 24 cm.
LC Call No.:   QA660.D3 1933
Dewey No.:     513.7
Notes:         Thesis (PH. D.)--University of Chicago, 1933.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Projective differential geometry.
               Curves on surfaces.
Other titles:  Conjugate nets.
Control No.:   2163058

Author:        Green, Louis, 1912-
Title:         Systems of quadrics associated with a point of a
                  surface ... by Louis Green ...
Published:     [Chicago, 1938]
Description:   1 p.l., p. 649-666. 25 cm.
LC Call No.:   QA660.G7 1937
Dewey No.:     516.5
Notes:         Thesis (PH. D.)--University of Chicago, 1937.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from American journal of mathematics,
                  vol. 60, no. 3, July 1938."
Subjects:      Quadrics.
               Projective differential geometry.
Control No.:   2636066

Author:        Harding, Arthur M. (Arthur McCracken), b. 1884.
Title:         On certain loci projectivly connected with a
                  given plane curve ... by Arthur McCracken Harding ...
Published:     [Chicago, 1916]
Description:   1 p.l., 38 p., 1 l. 24 cm.
LC Call No.:   QA660.H3 1916
Dewey No.:     513.7
Notes:         Thesis (PH. D)--University of Chicago, 1916.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Giornale di matematiche di
                  Battaglini vol. LIV, 1916."
Subjects:      Projective differential geometry.
Control No.:   4526299

Author:        Lane, Ernest Preston, 1886-
Title:         Projective differential geometry of curves and
                  surfaces.
Published:     Chicago, University of Chicago Press [1932]
Description:   xi, 321 p. diagrs. 26 cm.
Series:        The University of Chicago science series
LC Call No.:   QA660.L3
Notes:         Bibliography: p. 305-311.
Subjects:      Geometry, Differential.
Control No.:   6880451

Author:        Lane, Ernest Preston, 1886-
Title:         A treatise on projective differential geometry,
                  by Ernest Preston Lane ...
Published:     Chicago, Ill., The University of Chicago press
                  [1942]
Description:   ix, 466 p. 25 cm.
LC Call No.:   QA660.L32
Dewey No.:     513.7
Notes:         "A sequel to the author's Projective differential
                  geometry of curves and surfaces."--Pref.
               Bibliography: p. 453-461.
Subjects:      Projective differential geometry.
Control No.:   3581757

Author:        Levine, Jack, 1907-
Title:         Projective scalar differential invariants, by
                  Jack Levine.
Published:     Princeton, 1936.
Description:   p. 618-634. 26 cm.
LC Call No.:   QA660.L48 1934
Notes:         Cover title.
               Thesis (Ph. D.)--Princeton university, 1934.
               "Reprinted freom the Annals of mathematics, vol.
                  37, July, 1936."
Subjects:      Projective differential geometry.
               Differential invariants.
Control No.:   8770994

Author:        MacDonald, Janet, 1905-
Title:         Conjugate nets in asymptotic parameters.
Published:     Chicago, 1943.
Description:   ii, 29 l. 32 cm.
LC Call No.:   QA660.M179
Dewey No.:     516.3/6 19
Notes:         Thesis--University of Chicago.
               Vita.
Subjects:      Projective differential geometry.
               Curves on surfaces.
Control No.:   1367663

Author:        MacDonald, Janet, 1905-
Title:         Conjugate nets in asymptotic parameters ... by
                  Janet MacDonald ...
Published:     [n.p., 1944]
Description:   1 p.l., 697-709 p. 25 cm.
LC Call No.:   QA660.M18
Notes:         Part of thesis (PH. D.)--University of Chicago,
                  1943.
               "Reprinted from the Bulletin of the American
                  mathematical society, vol. 50, no. 10 ... October, 1944."
Subjects:      Projective differential geometry.
               Curves on surfaces.
Control No.:   2163737

Author:        MacQueen, Marion Leigh, 1896-
Title:         A projective generalization of Euclidean
                  parallelism of surfaces ... by Marion Leigh MacQueen ...
Published:     [Chicago] 1936.
Description:   2 p.l., 43 p. 24 cm.
LC Call No.:   QA660.M2 1933
Dewey No.:     516.5
Notes:         Thesis (PH. D.)--University of Chicago, 1933.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Projective differential geometry.
Control No.:   274515

Author:        Newton, Abba Verbeck, 1908-
Title:         Consecutive covariant configurations at a point
                  of a space curve ... by Abba Verbeck Newton ...
Published:     [New York, 1934]
Description:   1 p.l., [1], 44-62 p., 1 l. 27 cm.
LC Call No.:   QA660.N4 1933
Dewey No.:     513.7
Notes:         Thesis (Ph. D.)--University of Chicago, 1933.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Transactions of the American
                  mathematical society, vol. 36, no. 1, 1934."
Subjects:      Projective differential geometry.
Other titles:  Covariant configurations.
Control No.:   3108659

Author:        Olson, Emma Julia, 1892-
Title:         Conjugate systems characterized by special
                  properties of their ray congruences ... by Emma Julia Olson
                  ...
Published:     [Chicago] 1934.
Description:   2 p.l., 57 p. 24 cm.
LC Call No.:   QA660.O4 1932
Dewey No.:     516.5
Notes:         Thesis (PH. D.)--University of Chicago, 1932.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Bibliography: p.55-56.
Subjects:      Projective differential geometry.
               Congruences (Geometry)
Control No.:   746712
Author:        Sachs, Jerome Michael, 1914-
Title:         Theory of surfaces in conjugate parameters ... by
                  Jerome Michael Sachs.
Published:     Chicago, Ill., 1944.
Description:   ii numb. l., 26 p. 23 cm.
LC Call No.:   QA660.S3
Notes:         Thesis (PH. D.)--University of Chicago, 1940.
               Lithoprinted.
               Vita.
Subjects:      Projective differential geometry.
Control No.:   3581892

Author:        Sun, Kuang-yüan.
Title:         Projective differential geometry of quadruples of
                  surfaces with points in correspondence, by Dan Sun.
Published:     1928.
Description:   46 l. 29 cm.
LC Call No.:   QA660.S94
Dewey No.:     516/.36
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Projective differential geometry.
               Differential equations, Partial.
               Surfaces.
Control No.:   1256526


Author:        Wilcox, L. R. (Lee Roy), 1912-
Title:         Pairs of surfaces in five-dimensional space ...
                  by Lee Roy Wilcox ...
Published:     [Chicago] 1938.
Description:   ii numb. l., 40 p. 24 cm.
LC Call No.:   QA660.W48 1935
Dewey No.:     516.5
Notes:         Thesis (PH. D.)--University of Chicago, 1935.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Projective differential geometry.
               Hypersurfaces.
Control No.:   1219241

Author:        Wilczynski, Ernest Julius, 1876-1932. [from old
                  catalog]
Title:         Projective differential geometry of curves and
                  ruled surfaces.
Edition:       1st ed.
Published:     New York, Chelsea Pub. Co. [19-]
Description:   298 p. 21 cm.
LC Call No.:   QA660.W5
Subjects:      Projective differential geometry.
Control No.:   7496143

Author:        Hinton, Charles Howard, 1853-1907.
Title:         The fourth dimension.
Published:     [n. p., n. d.]
Description:   p. cm.
LC Call No.:   QA669.H6 1973
Control No.:   10011216

Author:        Barthel, Ernst. [from old catalog]
Title:         Polargeometrie,
Published:     Berlin, L. Simion nf., 1919.
Description:   95 p. diagrs. 23 cm.
LC Call No.:   QA681.B3
Subjects:      Geometry -- Foundations. [from old catalog]
Control No.:   9657945

Author:        Beez, Richard, 1827-
Title:         Über euklidische und nicht-euklidische
                  geometrie.
Published:     Plauen i. V., Gedruckt bei M Wieprecht, 1888.
Description:   32 p. 26 x 21 cm.
Series:        Programm--Gymnasium und realgymnasium, Plauen i.
                  V.
LC Call No.:   QA681.B41
Subjects:      Geometry -- Foundations.
Control No.:   8669411

Author:        Bell, John Clarence, 1915- [from old catalog]
Title:         An extension of the parallelism of Clifford, by
                  John Clarence BEll.
Published:     Urbana, Ill., 1943.
Description:   1 p.l., 16 p., 1 l. 23 cm.
LC Call No.:   QA681.B43
Subjects:      Parallels (Geometry) [from old catalog]
               Geometry, Differential. [from old catalog]
Other titles:  Parallelism of Clifford.
Control No.:   5990202

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Un precursore italiano di Legendre e di
                  Lobatschewsky. Nota del socio Eugenio Beltrami.
Published:     Roma, Tip. della R. Accademia dei Lincei, 1889.
Description:   [441]-448 p. 28 cm.
LC Call No.:   QA681.B45
Subjects:      Saccheri, Girolamo, 1667-1733. [from old
                  catalog]
               Geometry -- Foundations.
Control No.:   9138067

Author:        Blackhurst, James Herbert, 1890- [from old
                  catalog]
Title:         Euclidean geometry;
Published:     Des Moines, Garner Pub. Co. [1947]
Description:   208 p. illus., map. 22 cm.
LC Call No.:   QA681.B55
Subjects:      Geometry -- Foundations. [from old catalog]
Control No.:   6945971

Author:        Bonnel, J. F. (Joseph Florentin), 1826-1902.
Title:         Les atomes et hypothèses dans la géométrie,
                  par J.F. Bonnel ...
Edition:       3. éd., rev. et augm. avec 27 figures
                  intercalées dans la texte.
Published:     Paris, A. Hermann; [etc., etc.] 1899.
Description:   197 p., 1 l. illus. 23 cm.
LC Call No.:   QA681.B6 1899
Notes:         Imprint covered by label of Gauthier-Villars,
                  Paris.
Subjects:      Geometry -- Foundations.
               Atoms.
Control No.:   3580552

Author:        California. University. Dept. of Mathematics.
                  [from old catalog]
Title:         The axiomatic method, with special reference to
                  geometry and physics:
Published:     Berkeley, 1958.
Description:   viii, 174 l. diagrs. 28 cm.
LC Call No.:   QA681.C18
Subjects:      Geometry -- Foundations -- Congresses. [from old
                  catalog]
               Physics -- Congresses. [from old catalog]
               Axioms. [from old catalog]
Control No.:   6543443

Author:        Callahan, Jeremiah Joseph, 1878-
Title:         Euclid or Einstein; a proof of the parallel
                  theory and a critique of metageometry, by J.J. Callahan ...
Published:     New York, The Devin-Adair Company [c1931]-
Description:      v. diagrs. 23 cm.
LC Call No.:   QA681.C2
Dewey No.:     513.01
Subjects:      Parallels (Geometry)
               Geometry, Non-Euclidean.
               Euclid's Elements.
               Einstein, Albert, 1879-1955.
Control No.:   5943145

Author:        Carus, Paul, 1852-1919.
Title:         The foundations of mathematics; a contribution to
                  the philosophy of geometry, by Dr. Paul Carus ...
Published:     Chicago, The Open court publishing co.; [etc.,
                  etc.] 1908.
Description:   iv, 141 p. illus. 20 cm.
LC Call No.:   QA681.C25
ISBN:          $0.75
Subjects:      Geometry -- Foundations.
Control No.:   3107310

Author:        Delbëoìsu, Joseph Remi Léopold. [from old
                  catalog]
Title:         Prolégomènes philosophiques de la géométrie
                  et solution des postulats,
Published:     Liége. J. Desoer; [etc., etc.] 1860.
Description:   308 p. 23 cm.
LC Call No.:   QA681.D4
Control No.:   9085915

Author:        Dietrich, Walther Robert, 1880-
Title:         Kants Raumlehre und ihr Verhältnis zur Geometrie
                  ...
Published:     Halle a.S., H. John, 1904.
Description:   26 p., 2 l. 22 cm.
LC Call No.:   QA681.D5
Notes:         "Berüchsichtigte litteratur": 1 p. following p.
                  26
Subjects:      Geometry -- Foundations.
               Space and time.
Other authors: Kant, Immanuel, 1724-1804.
Control No.:   6813177

Author:        Donadt, Alfred, 1857-
Title:         Das mathematische Raumproblem und die
                  geometrischen Axiome / von Alfred Donadt.
Published:     Leipzig : Metzger & Wittig, 1881.
Description:   68 p. ; 23 cm.
LC Call No.:   QA681.D67
Notes:         Vita.
               Thesis--Leipzig.
Subjects:      Geometry -- Foundations.
Control No.:   6327917

Author:        Einstein, Albert, 1879-1955.
Title:         Geometrie und Erfahrung; erweiterte fassung des
                  festvortrages gehalten an der Preussischen akademie der
                  wissenschaften zu Berlin am 27. januar 1921 von Albert
                  Einstein, mit 2 textabbildungen.
Published:     Berlin, J. Springer, 1921.
Description:   20 p. diagrs. 22 cm.
LC Call No.:   QA681.E5
Subjects:      Geometry -- Foundations.
               Mathematics -- Philosophy.
               Relativity (Physics)
Other authors: Deutsche Akademie der Wissenschaften zu Berlin.
Control No.:   3108001

Author:        Enriques, Federigo, 1871-1946.
Title:         Fragen der Elementargeometrie / Aufsätze von U.
                  Amaldi, E. Baroni [et al.]; gesammelt und zusammengestellt
                  von Federigo Enriques.
Published:     Leipzig, Berlin : B. G. Teubner, 1911.
Description:   2 v. : diagrs. ; 23 cm.
LC Call No.:   QA681.E6
Notes:         I.T. Die Grundlagen der Geometrie...Deutsche
                  Ausg. von H. Thieme.--II.T. Die geometrischen Aufgaben; ihre
                  Lösung und Lösbarkeit.  Deutsche Ausg. von Dr. H.
                  Fleischer.
Subjects:      Geometry -- Foundations.
Other authors: Thieme, Hermann, 1852-1926, tr.
               Fleischer, Hermann, tr.
Control No.:   7758646

Author:        Frankland, William Barrett, 1875-
Title:         Theories of parallelism; an historical critique,
                  by William Barrett Frankland ...
Published:     Cambridge, University press, 1910.
Description:   xviii, 70 p., 1 l. 23 cm.
LC Call No.:   QA681.F8
Subjects:      Parallels (Geometry)
Control No.:   3107435

Author:        Hilbert, David, 1862-1943.
Uniform Title: Grundlagen der geometrie. English
Title:         The foundations of geometry, by David Hilbert ...
                  authorized translation by E.J. Townsend ...
Published:     Chicago, The Open court publishing company;
                  London, K. Paul, Trench, Trübner & co., ltd., 1902.
Description:   vii, 132 p. diagr. 20 cm.
LC Call No.:   QA681.H6
Notes:         The original formed the first part of
                  "Festschrift zur feier der enthüllung des
                  Gauss-Weber-denkmals in Göttingen, Grundlagen der
                  geometrie," with the additions made by the author in the
                  French translation, Paris, 1901, incorporated.
Subjects:      Geometry -- Foundations.
Other authors: Townsend, E. J. (Edgar Jerome), 1864- , tr.
Control No.:   4052111

Author:        Hilbert, David, 1862-1943.
Title:         Grundlagen der geometrie, von Dr. David Hilbert
                  ...
Edition:       2., durch zusätze vermehrte und mit fünf
                  anhängen versehene aufl. Mit zahlreichen iu den text
                  gedrucklen figuren.
Published:     Leipzig, B.G. Teubner, 1903.
Description:   v, 175 p. diagrs. 25 cm.
LC Call No.:   QA681.H58
Notes:         I. Über du gerade linie als kürzeste verbindung
                  zweier punkte. [Math. ann., bd. 46].--II. Über den satz von
                  der gleichheit der basiswinkel im gleichschenkligen dreieck.
                  [London math soc. Proc. vol. 35].--III. Neue begründung der
                  Bolayi-Lobatschefskyschen geometrie [Math. ann., bd. 57,
                  1903].--IV. Über die grundlagen der geometrie. [Math. ann.,
                  bd. 56, 1902].--V. Über flachen von konstanter Gausscher
                  krümmlung. [Amer. math. soc. Trans. vol. 2, 1901].
Subjects:      Geometry -- Foundations.
Control No.:   273034

Author:        Killing, Wilhelm, 1847-
Title:         Einführung in die grundlagen der geometrie. Von
                  Dr. Wilhelm Killing ...
Published:     Paderborn, F. Schöningh, 1893-98.
Description:   2 v. diagrs. 23 cm.
LC Call No.:   QA681.K48
Notes:         "Litteratur-nachweis": v. 1, [350]-357 p.; v. 2,
                  [355]-361 p.
               1. bd. 1. abschnitt. Berechtigung der
                  nicht-euklidischen raumformens. 2. abschnitt. Die projektive
                  geometrie. 3. abschnitt. Der mehrdimensionale raum. 4.
                  abschnitt. Die Clifford-Kleinschen raumformen.--2. bd. 5.
                  abschnitt. Kongruenz und messung. 6. abschnitt. Abschlues der
                  projektiven geometrie. 7. abschnitt. Grundbegriffe und
                  grundsätze der geometrie. 8. abschnitt. Anwendung der
                  transformations-gruppen.
Subjects:      Geometry.
Control No.:   272631

Author:        Moore, R. L. (Robert Lee), 1882-
Title:         Sets of metrical hypotheses for geometry / by
                  Robert Lee Moore.
Published:     Lancaster, Pa. : Press of the New Era Printing
                  Company, [1908]
Description:   p. 487-512 ; 27 cm.
LC Call No.:   QA681.M7
Notes:         Vita.
               From the Transactions of the American
                  Mathematical Society, October, 1908.
               "Presented to the Chicago section of the American
                  Mathematical Society in a somewhat different form, April 22,
                  1905."
               Thesis (Ph. D.)--University of Chicago.
Subjects:      Geometry -- Foundations.
Control No.:   5878068

Author:        Rabinovitch, Israel Euclid, b. 1861.
Title:         The foundations of the Euclidian geometry as
                  viewed from the standpoint of kinematics ... by Israel Euclid
                  Rabinovitch ...
Published:     New York, The author, 1903.
Description:   xi, 116 p. diagrs. 23 cm.
LC Call No.:   QA681.R14
Notes:         Thesis (Ph.D.)--Johns Hopkins university.
               "Autobiography."
               "List of works quoted in the introduction or
                  consulted by the author in preparing the dissertation": p.
                  x-xi.
Subjects:      Geometry -- Foundations.
Control No.:   4525347

Author:        Reinecke, Wilhelm Eduard, 1880- [from old
                  catalog]
Title:         Die grundlagen der geometrie nach Kant und
                  neueren autoren.
Published:     Haale a. S., 1903.
Description:   56, [2] p. 22 cm.
LC Call No.:   QA681.R36
Subjects:      Geometry -- Foundations. [from old catalog]
               Space and time. [from old catalog]
Control No.:   5862892

Author:        Rougier, Louis Auguste Paul, 1889-
Title:         La philosophie géométrique de Henri Poincaré,
                  par Louis Rougier.
Published:     Paris, F. Alcan, 1920.
Description:    208 p. 22 1/2 cm.
LC Call No.:   QA681.R6
Notes:         Thèse--Univ. de Paris.
               Bibliography: p. [205] and in foot-notes.
Subjects:      Geometry -- Foundations.
               Poincaré, Henri, 1854-1912.
Control No.:   9672689

Author:        Russell, Bertrand, 1872-1970.
Title:         An essay on the foundations of geometry, by
                  Bertrand A.W. Russell ...
Published:     Cambridge, University press, 1897.
Description:   xvi, 201, [1] p. diagrs. 23 cm.
LC Call No.:   QA681.R96
Subjects:      Geometry -- Foundations.
Control No.:   2634127

Author:        Schur, Friedrich, 1856-
Title:         Grundlagen der geometrie, von dr. Friedrich Schur
                  ... mit 63 figuren im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1909.
Description:   x, 192 p. diagrs. 25 cm.
LC Call No.:   QA681.S3
Subjects:      Geometry -- Foundations.
Control No.:   745348

Author:        Veblen, Oswald, 1880-1960.
Title:         A system of axioms for geometry ...
Published:     [Lancaster, Pa., Press of The new era printing
                  company] 1904.
Description:   2 p.l., 343-384 p. diagrs. 27 cm.
LC Call No.:   QA681.V4
Notes:         Thesis (PH. D.)--University of Chicago, 1903.
               Life.
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 5, no. 3."
Subjects:      Geometry -- Foundations.
               Geometry, Projective.
Control No.:   3107029

Author:        Withers, John William. [from old catalog]
Title:         Euclid's parallel postulate:
Published:     Chicago, The Open court publishing company;
                  [etc., etc.] 1905.
Description:   vii p., 1 l., 192 p. 20 cm.
LC Call No.:   QA681.W82
Subjects:      Geometry, Non-Euclidean. [from old catalog]
               Parallels (Geometry) [from old catalog]
Control No.:   6331940

Author:        Vening Meinesz, Felix Andries, 1887- [from old
                  catalog]
Title:         Bijdragen tot de theorie der slingerwaarnemingen
                  ... door Felix Andries Vening Meinesz ...
Published:     Amsterdam, J. H. de Bussy, 1915.
Description:   5 p.l., 162 p. diagrs., 3 fold. pl. 25 cm.
LC Call No.:   QA682.P4V4 1915
Notes:         Proefschrift--Delft.
Subjects:      Pendulum. [from old catalog]
Control No.:   10164101

Author:        Abbott, James Crawford. [from old catalog]
Title:         The projective theory of non-Euclidean geometry
                  ... by James C. Abbott ...
Published:     [Notre Dame, Ind.] 1941.
Description:   1 p.l., 15 p. 23 cm.
LC Call No.:   QA685.A3
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   7385251

Author:        Arkhimovich, Zinoviæi Aloizovich, 1858- [from old
                  catalog]
Title:         N. I. Lobachevsk¯iæi.
Published:     1895.
Description:   23 p. 23 cm.
LC Call No.:   QA685.A68
Notes:         Romanized.
Subjects:      Geometry, Non-Euclidean. [from old catalog]
               Lobachevskiæi, Nikolaæi Ivanovich, 1793-1856.
                  [from old catalog]
Control No.:   9359754

Author:        Barbarin, Paul, 1855-
Title:         La géométrie non euclidienne / par P.
                  Barbarin.
Published:     Paris: C. Naud, 1902.
Description:   79p. : ill., facsim., ports.; 20 cm.
Series:        Scientia. Serie physico-mathematique ; no 15
LC Call No.:   QA685.B2
Subjects:      Geometry, Non-Euclidean.
Control No.:   8665176Author:        Barbarin, Paul, 1855-
Title:         La géométrie non euclidienne / par P.
                  Barbarin.
Published:     Paris: C. Naud, 1902.
Description:   79p. : ill., facsim., ports.; 20 cm.
Series:        Scientia. Serie physico-mathematique ; no 15
LC Call No.:   QA685.B2
Subjects:      Geometry, Non-Euclidean.
Control No.:   8665176

Author:        Black, Amos Hale, 1902-
Title:         Non-Euclidean geometry for teachers.
Published:     [Carbondale? Ill.] 1956.
Description:   95 p. illus. 28 cm.
LC Call No.:   QA685.B52
Dewey No.:     513.81
Subjects:      Geometry, Non-Euclidean.
Control No.:   8401903

Author:        Bólyai, János, 1802-1860. [from old catalog]
Title:         Appendix scientiam spatii absolute veram
                  exhibens:
Published:     Lipsiæ, in ædibus B. G. Teubneri;  1903.
Description:   3 p.l., 40 p. diagrs. on vii fold. pl. 30 x 23
                  cm.
LC Call No.:   QA685.B68
Subjects:      Geometry, Non-Euclidean.
Other authors: K¯urschák, Józef, 1864- [from old catalog] ed.
               Réthy, Móricz, 1846- [from old catalog] ed.
               Tõtèssy de Zepethnek, Béla, [from old catalog]
                  ed.
               Bólyai, Farkas, 1775-1856. [from old catalog]
Other authors: Magyar tudómanyos akadémia, Budapest. [from old
                  catalog]
Control No.:   7264439

Author:        Bonnesen, T. (Tommy), 1873-
Title:         Analytiske studier over ikke-euklidisk geometri.
Published:     København, G.C. Ursins efterfølger, 1902.
Description:   4 p.l., 103 p. 23 cm.
LC Call No.:   QA685.B75 1902
Dewey No.:     513.81
Notes:         At head of title: T. Bonnesen.
               Thesis--Copenhagen.
Subjects:      Geometry, Non-Euclidean.
Control No.:   1690818

Author:        Bonola, Roberto, 1874-1911.
Title:         Die nichteuklidische geometrie,
                  historisch-kritische darstellung ihrer entwicklung.
                  Autorisierte deutsche ausg. besorgt von prof. dr. Heinrich
                  Liebmann. Mit 76 figuren im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1908.
Description:   viii, 244, [2] p. diagrs. 20 cm.
Series:        Wissenschaft und hypothese, IV
LC Call No.:   QA685.B8
Subjects:      Geometry, Non-Euclidean.
Other authors: Liebmann, Heinrich, 1874- ed.
Series Entry:  Wissenschaft und Hypothese ; 4.
Control No.:   3579900

Author:        Bonola, Roberto, 1874-1911.
Uniform Title: Geometria non euclidea. English
Title:         Non-Euclidean geometry; a critical and historical
                  study of its development. Authorized English translation with
                  additional appendices by H. S. Carslaw. With an introd. by
                  Federigo Enriques. With a suppl. containing the George Bruce
                  Halsted translations of The science of absolute space, by
                  John Bolyai [and] The theory of parallels, by Nicholas
                  Lobachevski.
Published:     [New York] Dover Publications [1955]
Description:   xii, 268, xxx, 71, 50 p. illus., diagrs. 21 cm.
LC Call No.:   QA685.B83 1955
Dewey No.:     513.8
Notes:         Bibliographical footnotes.
Subjects:      Geometry, Hyperbolic.
Other authors: Bólyai, János, 1802-1860. Appendix scientiam
                  spatii absolute veram exhibens. English. 1955.
               Lobachevskiæi, N. I. (Nikolaæi Ivanovich),
                  1793-1856. Geometrische Untersuchungen zur Theorie der
                  Parallellinien. English. 1955.
Control No.:   4529234

Author:        Carslaw, H. S. (Horatio Scott), 1870-1954.
Title:         The elements of non-Euclidean plane geometry and
                  trigonometry, by H.S. Carslaw ...
Published:     London, New York [etc.] Longmans, Green and co.,
                  1916.
Description:   xii, 179 p. diagrs. 19 cm.
Series:        Longmans' modern mathematical series
LC Call No.:   QA685.C3
Subjects:      Geometry, Non-Euclidean.
               Trigonmetry.
Control No.:   745759

Author:        Coolidge, Julian Lowell, 1873-1954
Title:         Die dual-projektive Geometrie im elliptischen und
                  sphärischen Raume ... von Julian Coolidge.
Published:     Greifswald, Druck von J. Abel, 1904.
Description:   2 p. L., 54, [2] p. fold. tab. 23 cm.
LC Call No.:   QA685.C7
Notes:         Half-title: The dual projective geometry of
                  elliptic and spherical space. Julian Lowell Coolidge, B. SC.
               English text.
               Lebenslauf.
               Inaug.-diss.--Bonn.
Subjects:      Geometry, Non-Euclidean
Other titles:  [Pamphlets. Mahtematics. 1841-1906] v.6.
Control No.:   6344937

Author:        Coolidge, Julian Lowell, 1873-1954.
Title:         The elements of non-Euclidean geometry, by 
                  Julian Lowell Coolidge ...
Published:     Oxford, At the Clarendon press, 1909.
Description:   291, [1] p. diagrs. 23 cm.
LC Call No.:   QA685.C75
Subjects:      Geometry, Non-Euclidean.
Control No.:   2161703

Author:        Dannmeyer, Ferdinand Diedrich Hermann, 1880-
Title:         Die oberflächen- und Volumenberchnung für den
                  Lobatschefskij'schen raum mit besonderer berücksichtigung
                  der Rotationskörper und Polyeder.
Published:     Göttingen, Druck der Univ.-buchdruckerei von W.
                  F. Kästner, 1904.
Description:   4 p. l., 57, [1] p., 1 l. diagrs. 24 cm.
LC Call No.:   QA685.D2
Notes:         Lebenslauf
               Inaug.-diss.--Kiel.
               "Litterturangaben": p. [56]-57
Subjects:      Geometry, Non-Euclidean.
               Surfaces -- Areas and volumes.
               Volume (Cubic content)
Control No.:   5867333

Author:        Davis, Edwin, 1879-
Title:         Die geometrische Addition der Stäge in der
                  hyperbolischen Geometrie ...
Published:     Greifswald, Druck von J. Abel, 1904.
Description:   2 p. L., 71, [3] p. diagrs. 23 cm.
LC Call No.:   QA685.D26
Notes:         Lebenslauf.
               Inaug.-diss.--Greifswald.
Subjects:      Geometry, Non-Euclidean
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.6.
Control No.:   7268059

Author:        Delaporte, L. J.
Title:         Essai philosophique sur les géométries
                  non-euclidiennes, par L.J. Delaporte ...
Published:     Paris, C. Naud, 1903.
Description:   139 p., 2 l. diagrs. 23 cm.
LC Call No.:   QA685.D33
Notes:         "Appendice: Tableau comparative des géométries
                  euclidienne, lobatschewskienne, et riemannienne": p.
                  [114]-133.
               "Ouvrages à consulter": p. [134]-139.
Subjects:      Geometry, Non-Euclidean.
Control No.:   1217082

Author:        Dieck, Wilhelm.
Title:         Nichteuklidische geometrie in der kugelebene, von
                  dr. Wilh. Dieck. Mit 12 figuren im text.
Published:     Leipzig und Berlin, B. G. Teubner, 1918.
Description:   1 p. l., 51 p. illus. (port.) diagrs. 19 cm.
Series:        Mathematisch-physikalische bibliothek. 31
LC Call No.:   QA685.D5
Subjects:      Sphere.
               Geometry, Non-Euclidean.
Control No.:   10136475

Author:        Ferrari, Ricardo. [from old catalog]
Title:         Teorema de Euclides.
Published:     Buenos Aires, Imprenta "Alsina", 1913.
Description:   40 p. diagrs. 27 cm.
LC Call No.:   QA685.F4
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   6851413

Author:        Fresdorf, Gustav. [from old catalog]
Title:         Ueber die geometrie und die potentialfunktion im
                  Gaussischen und Riemannschen raume ...
Published:     Göttingen, Druck der Deiterichschen
                  univ.-buchdruckerei (W. F. Kaestner) 1873.
Description:   42 p. 21 cm.
LC Call No.:   QA685.F88
Subjects:      Geometry, Non-Euclidean. [from old catalog]
               Potential theory (Mathematics)
Control No.:   6329598

Author:        Halsted, George Bruce, 1853- [from old catalog]
Title:         The value of non-Euclidean geometry.
Published:     [New York, 1905]
Description:   [639]-646 p. 25 cm.
LC Call No.:   QA685.H3
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   6337568

Author:        Hilbert, David, 1862-1943.
Title:         Anschauliche geometrie, von D. Hilbert und S.
                  Cohn-Vossen, mit 330 abbildungen ...
Published:     New York, Dover publications, 1944.
Description:   viii, [2], 314 p. illus., diagrs. 23 cm.
Series:        Die Grundlehren der mathematischen wissenschaften
                  in einzeldarstellungen mit besonderer berücksichtigung der
                  anwendungsgebiete ... bd. XXXVII
LC Call No.:   QA685.H5 1944
Dewey No.:     513
Notes:         "First American edition."
Subjects:      Geometry, Non-Euclidean.
Other authors: Cohn-Vossen, S. (Stephan), 1902-1936, joint
                  author.
Series Entry:  Grundlehren der mathematischen Wissenschaften in
                  Einzeldartsellungen mit besonderer Berücksichtigung der
                  Anwendungsgebiete ; Bd. 37.
Control No.:   4054835

Author:        Hilbert, David, 1862-1943.
Title:         Anschauliche Geometrie, von D. Hilbert und S.
                  Cohn-Vossen, mit 330 Abbildungen.
Published:     Berlin, J. Springer, 1932.
Description:   viii, 310 p. illus., diagrs. 24 cm.
Series:        Die Grundlehren der mathematischen Wissenschaften
                  in Einzeldarstellungen mit besonderer Berücksichtigung der
                  Anwendungsgebiete ... Bd. XXXVII
LC Call No.:   QA685.H5 1932
Dewey No.:     513
Subjects:      Geometry.
Other authors: Cohn-Vossen, S. (Stephan), 1902-1936, joint
                  author.
               Courant, Richard, 1888-1972, ed.
Control No.:   6882462

Author:        Hilbert, David, 1862-1943.
Uniform Title: Anschauliche Geometrie. English
Title:         Geometry and the imagination, by D. Hilbert and
                  S. Cohn-Vóssen; translated by P. Nemenyi.
Published:     New York, Chelsea Pub. Co., 1952.
Description:   357 p. illus. 24 cm.
LC Call No.:   QA685.H515
Dewey No.:     513
Notes:         Translation of Anschauliche Geometrie.
Subjects:      Geometry, Non-Euclidean.
Control No.:   1220396

Author:        Klein, Felix, 1849-1925.
Title:         Nicht-Euklidische Geometrie. Von F. Klein. 
                  Ausgearb. von Fr. Schilling.
Edition:       2. Abdruck.
Published:     Göttingen, 1893.
Description:   2 v. in 1. diagrs. 22 cm.
LC Call No.:   QA685.K6
Notes:         Autographed; printed title-page and contents.
               I. Vorlesung, gehalten während des
                  Wintersemesters 1889-90.--II. Vorlesung, gehalten während
                  des Sommersemesters 1890.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Geometry, Non-Euclidean.
Other authors: Schilling, Friedrich, 1868-1950, ed.
Control No.:   7728591

Author:        Kline, John Robert, 1891- [from old catalog]
Title:         Double elliptic geometry in terms of point and
                  order alone ...
Published:     [Lancaster, Pa., and Princeton, N.J., 1916]
Description:   1 p. l., p. [31]-44. 26 cm.
LC Call No.:   QA685.K65
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   7306918

Author:        Lieber, Lillian (Rosanoff) Mrs. 1886- [from old
                  catalog]
Title:         Non-Euclidean geometry;
Published:     [Lancaster, Pa., The Science press printing
                  company, c1940]
Description:   1 p.l., 40 (i.e.46) p. col. illus., col. plates.
                  22 cm.
LC Call No.:   QA685.L65 1940
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Other titles:  Three moons in mathesis.
Control No.:   7847937

Author:        Lieber, Lillian (Rosanoff) Mrs. 1886- [from old
                  catalog]
Title:         Non-Euclidean geometry;
Published:     [New York, Academy press, c1931]
Description:   1 p.l., 34 (i.e. 41) p. col. illus., col. pl. 22
                  cm.
LC Call No.:   QA685.L65
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   6877323

Author:        Liebmann, Heinrich, 1874-
Title:         Nichteuklidische Geometrie, von Heinrich
                  Liebmann.
Published:     Leipzig, G. J. Göschen, 1905.
Description:   viii, 248 p. diagrs. 20 cm.
Series:        Sammlung Schubert, 49
LC Call No.:   QA685.L7
Subjects:      Geometry, Non-Euclidean.
Control No.:   9140065

Author:        Lobachevskiæi, N. I. (Nikolaæi Ivanovich),
                  1792-1856.
Uniform Title: Geometrische Untersuchung zur Theorie des
                  Parallellinien. French
Title:         Etudes géométriques sur la théorie des
                  parallèls, par N.I. Lobatschewsky ... traduit de l'allemand
                  par J. Hoüel ... suivi d'un extrait de la correspondence de
                  Gauss et de Schumacher.
Published:     Paris, Gauthier-Villars, 1866.
Description:   1 p., l., iv, 42 p. diagrs. 25 cm.
LC Call No.:   QA685.L785
Notes:         With this is bound: Quetelet, L.A.J. Histoire des
                  sciences mathématiques et physiques chez les Belges.
                  Bruxelles, 1864.
Subjects:      Geometry, Non-Euclidean.
Other authors: Houel, M. (Guillaume Jules), 1823-1886.
Control No.:   12760148

Author:        Lobachevskiæi, N. I. (Nikolaæi Ivanovich),
                  1792-1856.
Title:         Geometrical researches on the theory of
                  parallels, by Nicholas Lobachevski ... tr. from the original
                  by George Bruce Halsted ...
Edition:       New ed.
Published:     Chicago [etc.] Open Court Publishing Company,
                  1914.
Description:   50 p. front. (port.) diagrs. 25 cm.
LC Call No.:   QA685.L78 1914
Notes:         Bibliography: p. 49-50.
Subjects:      Geometry, Non-Euclidean.
Other authors: Halsted, George Bruce, 1853-1922, tr.
Control No.:   5895890

Author:        Lobachevskiæi, N. I. (Nikolaæi Ivanovich),
                  1792-1856.
Title:         Zwei geometrische abhandlungen aus dem russischen
                  uebersetzt, mit anmerkungen und mit einer biographie des
                  verfassers / von Friedrich Engel.
Published:     Leipzig : B. G. Teubner, 1898-99.
Description:   2 pts. in 1 v. : front. (port.), diagrs. ; 25
                  cm.
LC Call No.:   QA685.L83
Notes:         Added t.p.: Urkunden zur geschichte der
                  nichteuklidischen geometrie, hrsg. von F. Engel und P.
                  Stäckel.
               Paged continuously; 1.t.: xvi, 235, [1] p.; 2.t.:
                  [6], 239-476 p.
               "Verzeichniss der gedruckten werke
                  Lobatschefskijs nach der zeitfolge ihres erscheinens": p.
                  [446]-449.
               1.t. Die uebersetzung: I. Ueber die
                  anfangsgründe der geometrie.--II. Neue anfangsgründe der
                  geometrie mit einer vollständigen theorie der
                  parallelinien.--2.t. Anmerkungen. Lobatschevskijs leben und
                  schriften. Register.
Subjects:      Geometry, Non-Euclidean.
Other authors: Engel, Friedrich, 1861-1941, ed. and tr.
Control No.:   5862506

Author:        Lobachevskiæi, Nikolaæi Ivanovich, 1792-1856.
                  [from old catalog]
Uniform Title: Geometrische Untersuchung zur Theorie des
                  Parallellinien. English. [from old catalog]
Title:         Geometrical researches on the theory of
                  parallels.
Published:     Austin, University of Texas, 1891.
Description:   50 p. diagrs. 23 cm.
LC Call No.:   QA685.L78 1891
               Microfilm 59788 QA
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   7267103

Author:        Lobachevskiæi, Nikolaæi Ivanovich, 1792-1856.
                  [from old catalog]
Uniform Title: Pangéométrie. German. [from old catalog]
Title:         Pangeometrie, von N.J. Lobatschefskij. Kasan
                  1856.
Published:     Leipzig, W. Engelmann, 1902.
Description:   95, [1] p. diagr. 20 cm.
LC Call No.:   QA685.L8
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   10071245

Author:        Ludwig, W. (Walther), 1876-
Title:         Projektive untersuchungen über die
                  kreisverwandtschaften der nichteuklidischen geometrie ...
Published:     Karlsruhe i. B., G. Braunsche hofbuchdr., 1904.
Description:   54 p., 1 l. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA685.L94
Notes:         Zur erlangung der venia legendi--Tech.
                  hochschule, Karlsruhe.
Subjects:      Geometry, Non-Euclidean.
               Transformations (Mathematics)
Control No.:   2634183

Author:        Magyar Királyi Ferenc József Tudományegyetem.
Title:         Libellus post saeculum quam Ioannes Bolyai de
                  Bolya anno MDCCCII A.D. XVIII kalendas ianuarias Claudiopoli
                  natus est ad celebrandam memoriam eius immortalem. Ex
                  consilio Ordinis mathematicorum et naturae scrutatorum Regiae
                  litterarum universitatis hungaricae Francisco-Josephinae
                  claudiopolitanae editus.
Published:     Claudiopoli [typis Societatis franklinianae
                  budapestinensis] 1902.
Description:   xv, 154 p., 1 l. facsim. 26 x 20 cm.
LC Call No.:   QA685.B7
Notes:         Title in red and black.
               Preface signed: Ludovicus Schlesinger, huius
                  libri redactor. Iulius Farkas, h.t. decanus.
               Half-title: Regia litt. universitas hung.
                  claudiopolitana. Ioannis Bolyai in memoriam.
               I. Epistola, cuius simulacrum huic libro
                  praefixum est, a Ioanne Bolyai ad Wolfgangum Bolyai patrem
                  data, in latinum conversa.--II. Schlesinger, L. De nonnullis
                  absolutae geometriae ad theoriam complexae variabilis
                  functionum applicationibus.--III. Stäckel, P. De ea
                  mechanicae analyticae parte, quae ad varietates complurium
                  dimensionum spectat.--IV. Bonola, R. Index operum ad
                  geometriam absolutam spectantium.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Bólyai, János, 1802-1860.
               Geometry, Hyperbolic.
Other authors: Schlesinger, Ludwig, 1864- ed.
Control No.:   272539

Author:        Manning, Henry Parker, 1859-
Title:         Non-Euclidean geometry, by Henry Parker Manning
                  ...
Published:     Boston, U.S.A., Ginn & company, 1901.
Description:   v, 95 p. diagrs. 20 cm.
LC Call No.:   QA685.M2
Dewey No.:     513.8
Subjects:      Geometry, Non-Euclidean.
Control No.:   272432

Author:        Mott-Smith, Morton Churchill, 1877-1944.
Title:         Metageometrische raumtheorien. Eine
                  philosophische untersuchung ...
Published:     Halle a. S., Hofbuchdr. von C. A. Kaemmerer &
                  co., 1907.
Description:   vi, 243, [1] p. 23 cm.
LC Call No.:   QA685.M8
Notes:         Lebenslauf.
               Inaug.-diss.--Halle.
               "Literaturverzeichnis": p. [238]-243.
Subjects:      Geometry, Non-Euclidean
               Space and time
Control No.:   7283707

Author:        Newcomb, Simon, 1835- [from old catalog]
Title:         Elementary theorems relating to the geometry of a
                  space of three dimensions and of uniform positive curvature
                  in the fourth dimension.
Published:     [Berlin, Druck von G. Reimer, 1877]
Description:   293-299, [1] p. 28 cm.
LC Call No.:   QA685.N5
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   7263536

Author:        Opitz, Paul Hermann, 1859-
Title:         Einige sätze über die anziehung in mehrfach
                  ausgedehnten Gaussischen und Riemannschen räumer ...
Published:     Dresden, Buchdruckerei T.M. Hofmann, 1881.
Description:   44 p., 1 l. 22 cm.
LC Call No.:   QA685.O61
Notes:         Inaug.-dis.--Göttingen.
               Lebenslauf.
Subjects:      Geometry, Non-Euclidean.
Control No.:   7733324

Author:        Quensen, Karl, 1857- [from old catalog]
Title:         Analytische betrachtungen über die raumformen,
Published:     [Gandersheim, Druck von C. F. Hertel, 1884]
Description:   p. cm.
LC Call No.:   QA685.Q3
Other authors: Geometry--Non-Euclidean. [from old catalog]
Control No.:   7265243

Author:        Quetelet, Adolphe, 1796-1874.
Title:         Histoire des sciences mathématiques et physiques
                  chez les Belges, par Ad. Quetelet.
Published:     Bruxelles, Hayez, 1864.
Description:   2 p.l.,479 p. tables (part fold.) 25 cm.
LC Call No.:   QA685.L785
Subjects:      Science -- Belgium -- History.
Control No.:   7260189

Author:        Rath, Emil, 1868- [from old catalog]
Title:         Die grundformeln der allgemeinen kurven- und
                  flächen theorie im nicht euclid'schen raum ...
Published:     Tübingen, Druck von H. Laupp, jr., 1894.
Description:   41, [1] p. 23 cm.
LC Call No.:   QA685.R23
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Control No.:   9606168

Author:        Saccheri, Girolamo, 1667-1733.
Title:         Girolamo Saccheri's Euclides vindicatus, ed. and
                  tr. by George Bruce Halsted ...
Published:     Chicago, London, The Open court publishing
                  company, 1920.
Description:   xxx, 246 p. diagrs. 23 cm.
LC Call No.:   QA685.S3
Notes:         Latin and English on opposite pages.
               With reproduction of t.-p. of original edition.
Subjects:      Geometry, Non-Euclidean.
Other authors: Halsted, George Bruce, 1853-1922, ed. and tr.
Other titles:  Euclides vindicatus.
Control No.:   745897

Author:        Scanavino, Elias. [from old catalog]
Title:         de Euclides? ...
Published:     Buenos Aires, Imprenta "Alsina", 1913.
Description:   4 p. l., [5]-32 p. 27 cm.
LC Call No.:   QA685.S35
Subjects:      Geometry, Non-Euclidean. [from old catalog]
               Lobachevsk¯i¯i, Nikola¯i Ivanovich, 1793-1856.
                  [from old catalog]
Control No.:   6383214

Author:        Stäckel, Paul, 1862-1919.
Title:         Die Theorie der Parallellinien von Euklid bis auf
                  Gauss; eine Urkundensammlung zur Vorgeschichte der
                  nichteuklidischen Geometrie, in Gemeinschaft mit Friedrich
                  Engel, hrsg. von Paul Stäckel. Mit 145 Figuren im Text und
                  der Nachbildung eines Brieges von Gauss.
Published:     Leipzig, B. G. Teubner, 1895.
Description:   x, 325 p. illus. 24 cm.
LC Call No.:   QA685.S76
Notes:         Includes bibliographies.
               PCMI collection.
               Ultrafiche. Dayton, Ohio, Microlection Pub.
                  Corp., 1974. 1 sheet. 11 x 15 cm.
Subjects:      Parallels (Geometry)
               Geometry, Non-Euclidean.
Other authors: Engel, Friedrich, 1861-1941.
Control No.:   6998102

Author:        Stäckel, Paul, 1862-1919.
Title:         Leben und Schriften der beiden Bolyai.
Published:     Leipzig, Teubner, 1913 [New York, Johnson Reprint
                  Corp., 1972]
Description:   x, 281 p. illus. 25 cm.
Series:        B[ibliotheca] m[athematica] T[eubneriana] 71
LC Call No.:   QA685.S78 t. 1
Notes:         Originally issued as pt. 1 of the author's
                  Wolfgang und Johann Bolyai: geometrische Untersuchungen,
                  which was v. 2 of Urkunden zur Geschichte der
                  nichteuklidischen Geometrie.
               Includes bibliographical references.
Subjects:      Bolyai, Farkas, 1775-1856.
               Bólyai, János, 1802-1860.
Series Entry:  Stäckel, Paul, 1862-1919. Wolfgang und Johann
                  Bolyai: geometrische Untersuchungen ; T. 1.
Series Entry:  Urkunden zur Geschichte der nichteuklidischen
                  Geometrie ; 2.
Control No.:   8980527

Author:        Stäckel, Paul, 1862-1919, comp.
Title:         Wolfgang und Johann Bolyai: geometrische
                  Untersuchungen. Mit Unterstützung der Ungarischen Akademie
                  der Wissenschaften hrsg. von Paul Stäckel.
Published:     Leipzig, Teubner, 1913. [New York, Johnson
                  Reprint Corp., 1972]
Description:   2 v. in 1. illus. 25 cm.
Series:        B[ibliotheca] m[athematica] T[eubneriana] 71
LC Call No.:   QA685.S78
Dewey No.:     516/.9/08
Notes:         Originally issued as v.2. of Urkunden zur
                  Geschichte der nichteuklidischen Geometrie.
               Includes bibliographical references.
Subjects:      Geometry, Non-Euclidean.
Other authors: Bolyai, Farkas, 1775-1856.
               Bólyai, János, 1802-1860.
Other authors: Magyar Tudományos Akadémia
Series Entry:  Urkunden zur Geschichte der nichteuklidischen
                  Geometrie ; 2.
Control No.:   6171098

Author:        Stäckel, Paul Gustav, 1862-1919, [from old
                  catalog] comp.
Title:         Stücke aus den Schriften der beiden Bolyai.
Published:     Leipzig, Teubner, 1913. [New York, Johnson
                  Reprint Copr., 1972]
Description:   274 p. illus. 25 cm.
LC Call No.:   QA685.S78 t. 2
Subjects:      Geometry, Non-Euclidean. [from old catalog]
Other authors: Bólyai, Farkas, 1775-1856. [from old catalog]
               Bólyai, János, 1802-1860. [from old catalog]
Series Entry:  Stäckel, Paul Gustav, 1862-1919. comp. Wolfgang
                  und Johann Bolyai: geometrische Untersuchungen, T. 2. [from
                  old catalog]
Series Entry:  Urkunden zur Geschichte der nichteuklidischen
                  Geometrie, 2. [from old catalog]
Control No.:   8512323

Author:        Wolfe, Harold Eichholtz, 1891-
Title:         Introduction to non-Euclidean geometry, by Harold
                  E. Wolfe ...
Published:     New York, The Dryden Press [1945]
Description:   xiii, 247 p. diagrs. 21 cm.
Series:        The Dryden Press mathematics publications
LC Call No.:   QA685.W6 1945
Dewey No.:     513.81
Notes:         Preliminary edition published 1941.
Subjects:      Geometry, Non-Euclidean.
               Geometry, Non-Euclidean -- History.
Control No.:   5996598

Author:        Wolfe, Harold Eichholtz, 1891-
Title:         Introduction to non-Euclidean geometry, by Harold
                  E. Wolfe.
Edition:       Preliminary ed.
Published:     Bloomington, Ind. [Ann Arbor, Mich., Edwards
                  Brothers, Inc., lithoprinters] 1941.
Description:   ix, 117 p. diagrs. 28 x 21 cm.
LC Call No.:   QA685.W6 1941
Dewey No.:     513.81
Subjects:      Geometry, Non-Euclidean.
               Geometry, Non-Euclidean -- History.
Control No.:   5977349

Author:        Allendoerfer, Carl Barnett, 1911- [from old
                  catalog]
Title:         The imbedding of Riemann spaces in the large ...
Published:     Princeton, 1939.
Description:   p. 317-333, 633-644. 25 cm.
LC Call No.:   QA689.A55 1936
Subjects:      Generalized spaces.
Control No.:   8314817

Author:        Aronszajn, Nachman, 1907-
Title:         Introduction to the theory of Hilbert spaces.
Published:     Stillwater, Okla., Reasearch [sic] Foundation,
                  1950-
Description:   v. <1   > diagrs. 28 cm.
Series:        Oklahoma Agricultural and Mechanical College
                  mathematical monographs
LC Call No.:   QA689.A7
Dewey No.:     513.8
Subjects:      Hilbert space.
Control No.:   3582547

Author:        Blumenthal, Leonard Mascot, 1901-
Title:         Distance geometries; a study of the development
                  of abstract metrics [by] Leonard M. Blumenthal. With an
                  introduction by Karl Menger.
Published:     Columbia, University of Missouri, 1938.
Description:   2 p. l., 145 p. 27 cm.
Series:        Missouri. University. The University of Missouri
                  studies; a quarterly of research, v. 13, no. 2
LC Call No.:   QA689.B5
Dewey No.:     513.8
Notes:         Bibliography; p.[138]-142.
Subjects:      Generalized spaces.
               Set theory.
               Topology.
Other titles:  Abstract metrics.
Control No.:   8309292

Author:        Busemann, Herbert, 1905-
Title:         Metric methods in Finsler spaces and in the
                  foundations of geometry, by Herbert Busemann.
Published:     Princeton, Princeton university press; London, H.
                  Milford, Oxford university press, 1942.
Description:   243 p. diagrs. 23 cm.
Series:        Annals of mathematics studies, no. 8
LC Call No.:   QA689.B8
Dewey No.:     513.8
Notes:         "Lithoprinted."
               Bibliography: p. 235-239.
Subjects:      Generalized spaces.
               Geometry -- Foundations.
Control No.:   9262838

Author:        Ficken, Frederick Arthur, 1910- [from old
                  catalog]
Title:         The Riemannian and affine differential geometry
                  of product-spaces ...
Published:     [Princeton, N.J., 1939]
Description:   1 p.l., p. [891]-913. 26 cm.
LC Call No.:   QA689.F55 1938
Subjects:      Generalized spaces.
Control No.:   5973566

Author:        Kaplan, Samuel, 1916 Sept. 13-
Title:         Homology properties of arbitrary subsets of
                  Euclidean spaces.
Published:     [n. p., 1947]
Description:   248-271 p. 27 cm.
LC Call No.:   QA689.K3
Subjects:      Generalized spaces.
Control No.:   9317535

Author:        Knebelman, Morris Samuel, 1891-
Title:         Collineations and motions in generalized spaces
                  ... by M.S. Knebelman.
Published:     Princeton, 1928.
Description:   1 p. l., p. 527-564. 25 cm.
LC Call No.:   QA689.K6 1928
Notes:         Thesis (PH. D.)--Princeton University, 1928.
               "Reprint from the American Journal of
                  Mathematics, vol. LI, number 4. "
Subjects:      Collineation.
               Hyperspace.
Control No.:   10150924

Author:        Levy, Harry, 1902- [from old catalog]
Title:         Tensors determined by a hypersurface in a Riemann
                  space ...
Published:     [Menasha, Wis., and New York, 1926]
Description:   p. 671-694. 28 cm.
LC Call No.:   QA689.L4 1924
Subjects:      Hyperspace. [from old catalog]
Control No.:   6396138

Author:        Lovell, Clarence Anding, 1898-
Title:         On certain associated metric spaces [by] Clarence
                  Anding Lovell.
Published:     Philadelphia, 1934.
Description:   19 p. 23 cm.
LC Call No.:   QA689.L6 1933
Dewey No.:     513.8
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1933.
Subjects:      Generalized spaces.
Control No.:   6423070

Author:        Maddaus, Ingo, 1909- [from old catalog]
Title:         On types of "weak" convergence in linear normed
                  spaces,
Published:     [Princeton, N.J., 1941]
Description:   1 p.l., p. 229-246. 26 cm.
LC Call No.:   QA689.M3 1941
Subjects:      Generalized spaces.
               Convergence. [from old catalog]
Other titles:  "Weak" convergence in linear normed spaces.
Control No.:   7850132

Author:        Meyer, Herman, 1912-
Title:         Polynomial approximations to functions defined on
                  abstract spaces ... by Herman Meyer.
Published:     Chicago, Ill., 1944.
Description:   ii, 30 p. 23 cm.
LC Call No.:   QA689.M4
Dewey No.:     513.8
Notes:         Thesis (PH. D.)--University of Chicago, 1941.
               Reproduced from type-written copy.
               Vita.
               Bibliography: p. 29.
Subjects:      Generalized spaces.
Control No.:   275144

Author:        Pogorelov, A. V. (Alekseæi Vasil§evich), 1919-
Uniform Title: Nekotorye voprosy teorii poverkhnosteæi. English
Title:         Topics in the theory of surfaces in elliptic
                  space. Translated by Royer and Roger, inc. Edited and with a
                  pref. by Richard Sacksteder.
Published:     New York, Gordon and Breach [1961]
Description:   131 p. 23 cm.
Series:        Russian tracts on advanced mathematics and
                  physics, v. 1
LC Call No.:   QA689.P613
Dewey No.:     513.8
Notes:         Translation of Nekotorye voprosy teorii
                  poverkhnosteæi v ellipticheskom prostranstve.
               Includes bibliography.
Subjects:      Elliptic space.
               Convex surfaces.
Control No.:   3584891

Author:        Robinson, Charles Vernon, 1915- [from old
                  catalog]
Title:         Contributions to distance geometry
Published:     [n. p., 1942]
Description:   1 p. l., 818-819, 260-272 p. diagrs. 24 cm.
LC Call No.:   QA689.R57
Subjects:      Generalized spaces.
               Congruences (Geometry)
               Set theory.
Control No.:   9268104

Author:        Robinson, Virgil Nelson, 1912- [from old
                  catalog]
Title:         Generalized intersector varieties ...
Published:     [Chicago] 1939.
Description:   ii numb. l., 28 p. 24 cm.
LC Call No.:   QA689.R6 1939
Subjects:      Generalized spaces.
Control No.:   6440839

Author:        Schatten, Robert, 1911-
Title:         A theory of cross-spaces.
Published:     Princeton, Princeton University Press, 1950.
Description:   vi, 153 p. 26 cm.
Series:        Annals of mathematics studies, no. 26
LC Call No.:   QA689.S35
Dewey No.:     513.8
Notes:         Bibliography: p. 151-153.
Subjects:      Generalized spaces.
Other titles:  Cross-spaces.
Control No.:   7426786

Author:        Sobczyk, Andrew, 1915- [from old catalog]
Title:         Projections in Minkowski and Banach spaces,
Published:     Princeton, 1939 [i.e. 1941]
Description:   [1], 78-106 p. 26 cm.
LC Call No.:   QA689.S6
Subjects:      Projection. [from old catalog]
               Generalized spaces.
Other titles:  Minkowski and Banach spaces.
               Banach spaces.
Control No.:   8789661

Author:        Spanier, Edwin Henry, 1921- [from old catalog]
Title:         Cohomology theory for general spaces.
Published:     [n. p., 1948]
Description:   407-427 p. 26 cm.
LC Call No.:   QA689.S63
Subjects:      Generalized spaces.
Control No.:   7444350

Author:        Stauder, Mary Francis Borgia, Sister. [from old
                  catalog]
Title:         Studies on projective generalizations of metric
                  geometry.
Published:     Notre Dame, Ind., University Press [1948]
Description:   49-57 p. 23 cm.
LC Call No.:   QA689.S7
Subjects:      Generalized spaces.
Other titles:  Projective generalizations of metric geometry.
Control No.:   6508069

Author:        Teles, Morris, 1912- [from old catalog]
Title:         Geodesic correspondence between Riemannian
                  spaces,
Published:     Urbana, Ill., 1938.
Description:   [4] p. 23 cm.
LC Call No.:   QA689.T4 1938
Subjects:      Generalized spaces.
Control No.:   9247216

Author:        Thomas, Tracy Y. (Tracy Yerkes), 1899-
Title:         The geometry of paths by Tracy Yerkes Thomas.
Published:     Princeton, 1924.
Description:   p. 551-608 28 cm.
LC Call No.:   QA689.T53 1923
Notes:         Cover title.
               Thesis (Ph. D.)--Princeton University, 1923.
               Caption title: ... By Oswald Veblen and Tracy
                  Yerkes Thomas.
               "Reprinted from the Transactions of the American
                  Mathematical Society, vol. 25, no. 4 ... October, 1923."
Subjects:      Geometry, Differential.
               Differential equations.
Other authors: Veblen, Oswald, 1880-1960, joint author.
Control No.:   6857663

Author:        Thomas, Tracy Y. (Tracy Yerkes), 1899-
Title:         Lectures on differential geometry. Basic topics
                  in the theory of generalized spaces, by T. Y. Thomas ...
                  notes by J. F. Daly. Appendix by T. C. Doyle. A comparison of
                  the gauge transformations of Thomas and Veblen based on a
                  canonical form of the equations of flat intrinsic projective
                  differential geometry.
Published:     Ann Arbor, Mich., Planographed by Edwards
                  brothers, inc., 1938.
Description:   2 p. 1., 52 p. 28 x 21 cm.
LC Call No.:   QA689.T54
Dewey No.:     513.8
Subjects:      Generalized spaces.
               Projective differential geometry.
Other authors: Doyle, Thomas Carlson.
               Daly, Joseph Francis.
Control No.:   6906680

Author:        Thurman, George Raymond.
Title:         The characterization of pseudo-spherical sets
                  ...
Published:     [Baltimore, 1940]
Description:   1 p. l., 835-854 p. 25 cm.
LC Call No.:   QA689.T55 1940
Subjects:      Generalized spaces.
               Aggregates. [from old catalog]
Other authors: Blumenthal, Leonard Mascot, 1901- [from old
                  catalog] joint author.
Other titles:  Pseudo-spherical sets.
Control No.:   10191370

Author:        Alderton, Nina May, 1890- [from old catalog]
Title:         Involutory quartic transformations in space of
                  four dimensions,
Published:     [Berkeley, 1923]
Description:   p. [345]-358. 28 cm.
LC Call No.:   QA691.A4
Subjects:      Trasformations (Mathematics) [from old catalog]
               Hyperspace. [from old catalog]
Control No.:   8261382

Author:        Bates, William Hunt, 1870-
Title:         An application of symbolic methods to the
                  treatment of mean curvatures in hyperspace / by William Hunt
                  Bates.
Published:     Lancaster, Pa. : New Era Printing Company, 1911.
Description:   19-38 p., 1 leaf ; 28 cm.
LC Call No.:   QA691.B3
Notes:         Thesis (Ph. D.)--University of Chicago.
               "Biographical sketch."
               Reprinted from the Transactions of the American
                  Mathematical Society, v. 12 (1911).
Subjects:      Hyperspace.
Control No.:   5887594

Author:        Borgman, William Martin, 1903-
Title:         Intersector varieties in hyperspace ... by
                  William Martin Borgman, jr.
Published:     [Chicago] 1934.
Description:   2 p.l., 37 p. diagr. 24 cm.
LC Call No.:   QA691.B7 1934
Dewey No.:     513.8
Notes:         Thesis (PH. D.)--University of Chicago, 1934.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Hyperspace.
Control No.:   1690929

Author:        Boucher, Maurice, scientist.
Title:         Essai sur l'hyperspace, le temps, la matière et
                  l'energie / par Maurice Boucher.
Published:     Paris : F. Alcan, 1903.
Description:   204 p. : illus. ; 19 cm.
LC Call No.:   QA691.B75
Notes:         "Index alphabétique des ouvrages et des articles
                  cités": p.[201]-202.
Subjects:      Hyperspace.
               Space and time.
               Matter.
Control No.:   6794314

Author:        Browne, Robert T.
Title:         The mystery of space; a study of the hyperspace
                  movement in the light of the evolution of new psychic
                  faculties and an inquiry into the genesis and essential
                  nature of space, by Robert T. Browne.
Published:     New York, E.P. Dutton & company [c1919]
Description:   xvi p., 1 l., 395 p. diagrs. 21 cm.
LC Call No.:   QA691.B8
Notes:         Bibliography: p. 359-365.
Subjects:      Hyperspace.
Control No.:   4053326

Author:        Carp, Jacob Arnoud. [from old catalog]
Title:         Combinatorische configuraties in meerdimensionale
                  ruæimten ...
Published:     Utrecht, J. van Druten, 1902.
Description:   4 p.l., 78 p. 23 cm.
LC Call No.:   QA691.C29
Subjects:      Hyperspace. [from old catalog]
Control No.:   8197321

Author:        Conner, James Ryals, 1878-
Title:         Basic systems of rational norm-curves ...
Published:     Baltimore, 1910.
Description:   1 p. l., p. [115]-176, 1 l. 30 cm.
LC Call No.:   QA691.C6
Notes:         Thesis (PH. D.)--John Hopkins University.
               Biographical note.
               Reprinted from American journal of mathematics,
                  vol. 32, no. 2.
Subjects:      Curves on surfaces.
Control No.:   8222163

Author:        Coxeter, H. S. M. (Harold Scott Macdonald),
                  1907-
Title:         Regular polytopes.
Edition:       2d ed.
Published:     New York, Macmillan [1963]
Description:   321 p. illus. 25 cm.
LC Call No.:   QA691.C68 1963
Dewey No.:     513.8
Notes:         Includes bibliography.
Subjects:      Polytopes.
Control No.:   3113045

Author:        Coxeter, H. S. M. (Harold Scott Macdonald),
                  1907-
Title:         Regular polytopes.
Published:     New York, Pitman [1948]
Description:   xix, 321 p. illus. 22 cm.
LC Call No.:   QA691.C
Dewey No.:     513.8
Notes:         Bibliography: p. 306-314.
Subjects:      Polytopes.
Control No.:   275815

Author:        Dreher, Eugen. [from old catalog]
Title:         Die vierte dimension des raumes ...
Published:     Halle a. S., Plötz'sche buchdr. (R. Nietschmann)
                  1879.
Description:   26 p., 1 l. 26 cm.
LC Call No.:   QA691.D7
Subjects:      Fourth dimension. [from old catalog]
Control No.:   8220120

Author:        Dutka, Harold Jacques, 1919-
Title:         Transversality in higher space, by Harold Jacques
                  Dutka ...
Published:     [N.p.] 1943.
Description:   126-133, [1] p. 26 cm.
LC Call No.:   QA691.D8
Notes:         Cover title.
               Thesis (Ph. D.)--Columbia University, 1943.
               "Reprinted from Journal of mathematics and
                  physics, vol. XXIII, no. 3, August, 1944."
               Vita.
               Bibliographical foot-notes.
Subjects:      Contact transformations.
               Transformations, Infinitesimal.
               Hyperspace.
Control No.:   6931927

Author:        Flanders, Donald A.
Title:         Double elliptic geometry in terms of point, order
                  and congruence, [by] Donald A. Flanders.
Published:     Philadelphia, 1927.
Description:   [1], 534-548 p. 23 cm.
LC Call No.:   QA691.F6 1927
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1927.
               "Reprint from the Annals of mathematics, vol. 28,
                  no. 4."
Subjects:      Hyperspace.
Control No.:   7336124

Author:        Fontené, G. (Georges), b. 1848.
Title:         L'hyperspace à (n-1) dimensions. Propriétés
                  métriques de la corrélation générale, par G. Fontené
                  ...
Published:     Paris, Gauthier-Villars et fils, 1892.
Description:   xviii, 132 p., 1 l. diagrs. 25 cm.
LC Call No.:   QA691.F68
Subjects:      Hyperspace.
Control No.:   744951

Author:        Fromm, Hubert, 1853- [from old catalog]
Title:         Ueber die krümmungsverhältnisse einer kurve im
                  n-fach ausgedehnten homogenen raume mit verschwindendem
                  krümmungsmasse ...
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1878.
Description:   2 p.l., 21, [1] p., 1 l. 27 cm.
LC Call No.:   QA691.F93
Subjects:      Hyperspace. [from old catalog]
               Curvature. [from old catalog]
Control No.:   7263125

Author:        Gore, Greenville D., 1899- [from old catalog]
Title:         Surfaces associated with a congruence ... by
                  Greenville D. Gore ...
Published:     [Chicago] 1932.
Description:   1 p. l., [1], 53 p. 24 cm.
LC Call No.:   QA691.G6 1932
Notes:         Thesis (Ph. D.)--University of Chicago, 1932.
               Vita.
               Lithographed.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Hyperspace.
Control No.:   12926397

Author:        Guichard, C. (Claude), b. 1861.
Title:         Sur les systémes triplement indéterminés et
                  sur les systémes triple-orthogonaux,
Published:     [Paris, Gauthier-Villars, 1905]
Description:   95, [1] p. diagrs. 20 cm.
LC Call No.:   QA691.G94
Subjects:      Hyperspace. [from old catalog]
               Surfaces, Orthogonal. [from old catalog]
Control No.:   10081295

Author:        Hagen, Beatrice Liberty, 1899-
Title:         Quintuples of three-dimensional varieties in a
                  four-dimensional linear space ... by Beatrice Liberty Hagen
                  ...
Published:     [Chicago] 1932.
Description:   2 p.l., 48 p. 24 cm.
LC Call No.:   QA691.H3 1930
Dewey No.:     513.8
Notes:         Thesis (PH. D.)--University of Chicago, 1930.
               Vita.
               Lithographed.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Bibliography: p. 47.
Subjects:      Hyperspace.
Control No.:   4527050

Author:        Halmos, Paul R. (Paul Richard), 1916-
Title:         Introduction to Hilbert space and the theory of
                  spectral multiplicity.
Edition:       2d ed.
Published:     New York, Chelsea Pub. Co. [c1957]
Description:   114 p. 24 cm.
LC Call No.:   QA691.H34 1957
Dewey No.:     513.8
Subjects:      Spectral theory (Mathematics)
Control No.:   1221305

Author:        Halmos, Paul R. (Paul Richard), 1916-
Title:         Introduction to Hilbert space and the theory of
                  spectral multiplicity.
Published:     New York, Chelsea, 1951.
Description:   114 p. 24 cm.
LC Call No.:   QA691.H34
Dewey No.:     513.8
Notes:         Bibliography:  p. 112-114.
Subjects:      Spectral theory (Mathematics).
Other titles:  Spectral multiplicity.
Control No.:   9773915

Author:        James, G[eorge] O[scar], 1873- [from old
                  catalog]
Title:         Some differential equations connected with
                  hypersurfaces ...
Published:     Baltimore, The Lord Baltimore press, The
                  Friedenwald company, 1903.
Description:   1 p.l., 25 p, 1 l. 32 x 25 cm.
LC Call No.:   QA691.J28
Subjects:      Hyperspace. [from old catalog]
               Differential equations. [from old catalog]
Control No.:   6796782

Author:        Jouffret, E. (Esprit), 1837-
Title:         Mélanges de géométrie à quatre dimensions,
                  par E. Jouffret.
Published:     Paris, Gauthier-Villars, 1906.
Description:   xi, 227, [1] p. diagrs. 26 cm.
LC Call No.:   QA691.J82
Subjects:      Hyperspace.
Control No.:   6852856

Author:        Jouffret, E. (Esprit), 1837-
Title:         Traité élémentaire de géométrie à quatre
                  dimensions et introduction à la géométrie à n dimensions,
                  par E. Jouffret ...
Published:     Paris, Gauthier-Villars, 1903.
Description:   xxx, 215, [1] p. diagrs. 26 cm.
LC Call No.:   QA691.J84
Notes:         "Recueils académiques et scientifiques
                  mentionnés": p. 209-212.
Subjects:      Hyperspace.
Control No.:   3106833

Author:        Jung, Heinrich W. E. (Heinrich Wilhelm Ewald),
                  1876-
Title:         Über die kleinste kugel die eine räumliche
                  figur einschliesst ...
Published:     1899.
Description:   26, [2] p. 25 cm.
LC Call No.:   QA691.J9
Notes:         Inaug.-diss.--Marburg.
               Lebenslauf.
Subjects:      Hyperspace.
Control No.:   6785905

Author:        Kaiser, Ludwig, 1848- [from old catalog]
Title:         Beiträge zur theorie eines raumes von n
                  dimensionen
Published:     Bonn, Universitäts - buchdruckerei von C. Georgi
                  [1877]
Description:   36, [2] p. 22 cm.
LC Call No.:   QA691.K2
Subjects:      Hyperspace. [from old catalog]
Control No.:   7264719

Author:        Kendall, Maurice G. (Maurice George), 1907-
Title:         A course in the geometry of n dimensions.
Published:     New York, Hafner Pub. Co., 1961 [i.e. 1962]
Description:   63 p. 22 cm.
Series:        Griffin's statistical monographs & courses, no.
                  8
LC Call No.:   QA691.K4
Dewey No.:     513.82
Notes:         Includes bibliography.
Subjects:      Hyperspace.
Other titles:  Geometry of n dimensions.
Series Entry:  Griffin's statistical monographs & courses ; no.
                  8.
Control No.:   1222666

Author:        Kommerel, Karl. [from old catalog]
Title:         Die krümmung der zweidimensionalen gebilde im
                  ebenen raum von vier dimensionen ...
Published:     Tübingen, Druck von H. Laupp, jr., 1897.
Description:   53 p. 23 cm.
LC Call No.:   QA691.K81
Subjects:      Hyperspace. [from old catalog]
Control No.:   10074478

Author:        Kühne, Hermann Ernst Gustav Albert, 1867-
Title:         Beiträge zur Lehre von der n-fachen
                  Mannigfaltigkeit ...
Published:     Greifswald, Druck von F.W. Kunike, 1892.
Description:   1 p. l., 57 p. 22 cm.
Series:        [Berlin. Universität. Dissertationen, v. 17, no.
                  11]
LC Call No.:   QA691.K94
Notes:         Inaug.-diss.--Berlin.
               Vita.
Subjects:      Hyperspace.
Control No.:   9613250

Author:        Kwietniewski, Stefan.
Title:         Ueber flächen des vierdimensionalen raumes,
                  deren sämtliche tangentialebenen untereinander gleichwinklig
                  sind, und ihre beziehung zu den ebenen kurven ... von Stefan
                  Kwietniewski ...
Published:     Zürich, E. Speidel, 1902.
Description:   51 p. diagrs. 23 cm.
LC Call No.:   QA691.K98
Notes:         Inaug.-diss.--Zürich.
Subjects:      Hyperspace.
               Hypersurfaces.
Control No.:   1217125

Author:        Laurent, H. (Hermann), 1841-1908.
Title:         Sur les principes fondamentaux de la théorie des
                  nombres et de la géométrie, par H. Laurent.
Published:     [Évreux, C. Hérissey] 1902.
Description:   68 p. 20 cm.
Series:        Scientia. Série physico-mathématique, no. 20
LC Call No.:   QA691.L4
Notes:         At head of title: Scientia, juin 1902.
Subjects:      Hyperspace.
               Geometry, Analytic.
               Number theory.
Series Entry:  Scientia. Série physico-mathématique ; no. 20.
Control No.:   272489

Author:        Lipka, Joseph, 1883-
Title:         Natural families of curves in a general curved
                  space of N-dimensions, by Joseph Lipka ...
Published:     Lancaster, Pa., New era printing company, 1912.
Description:   1 p. l., p. 77-95, 1 l. 28 cm.
LC Call No.:   QA691.L6
Notes:         Thesis (Ph. D.)--Columbia university, 1912.
               Vita.
               Reprinted from the Transactions of the American
                  mathematical society, vol. 13."
Subjects:      Hyperspace.
               Curves.
Control No.:   9635834

Author:        MacNeish, Harris Franklin.
Title:         Linear polars of the k-hedron in n-space ...
Published:     Chicago, Ill., The University of Chicago press
                  [1912]
Description:   v, 25 p. 25 cm.
LC Call No.:   QA691.M3
Notes:         Thesis (PH. D.)--University of Chicago, 1909.
Subjects:      Hyperspace.
Control No.:   1217805

Author:        Manning, Henry Parker, 1859-
Title:         Geometry of four dimensions, by Henry Parker
                  Manning ...
Published:     New York, The Macmillan Company, 1914.
Description:   ix, 348 p. diagr. 21 cm.
LC Call No.:   QA691.M35
Subjects:      Hyperspace.
Control No.:   9642240

Author:        Moreno, Halcott Cadwalader, 1873-
Title:         On ruled loci in n-fold space ... [by] Halcott
                  Cadwalader Moreno.
Published:     [Boston], [1901].
Description:   cover-title, [119]-157, [1] p., 25 cm.
LC Call No.:   QA691.M8
Notes:         Thesis (Ph. D.)--Clark university, 1900.
               "Proceedings of the American academy of arts and
                  sciences, v. xxxvii, no.5., September 1901."
Subjects:      Hyperspace.
Control No.:   6339372

Author:        Neville, Eric Harold. [from old catalog]
Title:         The fourth dimension,
Published:     Cambridge [Eng.] The University press, 1921.
Description:   4 p. l., 55, [1] p. 22 cm.
LC Call No.:   QA691.N4
Subjects:      Hyperspace. [from old catalog]
Control No.:   7320250

Author:        Oss, S. L. van (Salomon Levi van), 1864-
Title:         Das regelmässige sechshundertzell und seine
                  selbstdeckenden bewegungen, von S. L. van Oss.
Published:     Amsterdam, J. Müller, 1899.
Description:   18 p. fold. diagrs. 27 cm.
Series:        Verhandelingen der Koninklijke akademie van
                  wetenschappen te Amsterdam.  [Afdeeling voor de wis- en
                  natuurkundige wetenschappen]  1.sectie, deel VII, no. 1
LC Call No.:   Q57.A532 deel 7, no. 1
Dewey No.:     508 s
Subjects:      Polyhedra
               Hyperspace.
Control No.:   9742059

Author:        Oss, Salomon Levi van, 1864- [from old catalog]
Title:         Die bewegungsgruppen der regelmässigen gebilde
                  von vier dimensionen ...
Published:     Utrecht, P. Den Boer, 1892.
Description:   2 p. l., 38, [2] p. diagrs. on 2 fold. pl. 24
                  cm.
LC Call No.:   QA691.O84
Subjects:      Hyperspace. [from old catalog]
Control No.:   7732597

Author:        Owens, Frederick William, b. 1880.
Title:         The introduction of ideal elements and
                  construction of projective n-space in terms of a planar
                  system of points involving order and Desargues's theorem ...
                  by Frederick William Owens.
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1910.
Description:   1 p.l., 141-171, [1] p. diagrs. 27 cm.
LC Call No.:   QA691.O94
Notes:         Thesis (PH. D.)--University of Chicago, 1907.
               Vita.
               "This paper originally appeared in the
                  Transactions of the American mathematical society, vol. 11,
                  1910, p. 141-171, and is here reprinted under the different
                  title."
Subjects:      Hyperspace.
               Geometry, Projective.
Control No.:   4052875

Author:        Rhenius, Max i.e. Otto Adolf Eugen Max. [from old
                  catalog]
Title:         Grundzüge einer allgemeinen theorie
                  vieldimensionaler räume ...
Published:     Halle a/S., Buchdruckerei von E. Karras, 1884.
Description:   21, [1] p., 1 l. 21 cm.
LC Call No.:   QA691.R47
Notes:         Inaug.-dis.--Halle.
               Vita.
Subjects:      Hyperspace.
Control No.:   13198466

Author:        Richardson, Davis Payne, 1902- [from old
                  catalog]
Title:         Quadric Cremona transformations in
                  five-dimensional space ...
Published:     [Chicago] 1932.
Description:   1 p.l., [1], 31 p., 1 l. 24 cm.
LC Call No.:   QA691.R5 1930
Subjects:      Hyperspace. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Other titles:  Cremona transformations.
Control No.:   6415810

Author:        Scher, Marie N. [from old catalog]
Title:         O geometr¯iëiìakh i prostranstvakh.
Published:     1918.
Description:   1 p.l., ii, 27 p. diagrs. 22 cm.
LC Call No.:   QA691.S327
Notes:         Romanized.
Subjects:      Hyperspace.
               Geometry, Non-Euclidean.
               Parallels (Geometry)
Control No.:   7414124

Author:        Schlumberger, Gottfried.
Title:         Über n-dimensionale lineare und quadratische
                  Kugelsysteme / von Gottfried Schlumberger.
Published:     Zürich : Opell Füssli, 1896.
Description:   78 p. : ill. ; 22 cm.
LC Call No.:   QA691.S34
Notes:         Thesis--Universität Zürich.
Subjects:      Hyperspace.
Control No.:   7264497

Author:        Schoute, P. H. (Pieter Hendrik), 1846-1913.
Title:         Mehrdimensionale geometrie, von Dr. P.H. Schoute
                  ...
Published:     Leipzig, G.J. Göschen, 1902-05.
Description:   2 v. diagrs. 20 cm.
Series:        Sammlung Schubert XXXV-XXXVI
LC Call No.:   QA691.S4
Notes:         "Auhang: Gemischte aufgaben": v. 2, p.
                  [321]-326.
               1. t. Die linearen räume.--2. t. Die polytope.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Hyperspace.
Series Entry:  Sammlung Schubert ; 35-36.
Control No.:   3579577

Author:        Schoute, P. H. (Pieter Hendrik), 1846-1913.
Title:         Les hyperquadriques dans l'espace à quatre
                  dimensions. (Étude de géométrie énumérative) Par P. H.
                  Schoute.
Published:     Amsterdam, J. Müller, 1900
Description:   66 p. incl. tables. 27 cm.
Series:        Verhandelingen der Koninklijke akademie van
                  wetenschappen te Amsterdam. [Afdeeling voor de wis- en
                  natuurkundige wetenschappen] 1. sectie, deel VII, no. 4
LC Call No.:   Q57.A532 deel 7, no. 4
Dewey No.:     508 s
Subjects:      Geometry, Enumerative.
               Quadrics.
               Hyperspace.
Control No.:   8805039

Author:        Schoute, P. H. (Pieter Hendrik), 1846-1913.
Title:         Regelmässige schnitte und projectionen des
                  hundertzwanzigzelles und sechshundertzelles im
                  vierdimensionalen raume, von P.H. Schoute.
Published:     Amsterdam, J. Müller, 1894-1907.
Description:   2 v. tables (part fold.) fold. diagrs. 27 cm.
Series:        Verhandeling en der Koninklijke akademie van
                  wetenschappen te Amsterdam.  [Afdeeling voor de wis- en
                  natuurkundige wetenschappen]  1. sectie, deel II, no. 7; deel
                  IX, no. 4
LC Call No.:   Q57.A532 deel 2, no. 7; deel 9, no. 4
Dewey No.:     508 s
Subjects:      Hyperspace.
               Topology.
Control No.:   7377329

Author:        Schoute, P. H. (Pieter Hendrik), 1846-1913.
Title:         Het vierdimensionale prisomoïde, door P. H.
                  Schoute.
Published:     Amsterdam, J. Müller, 1896.
Description:   20 p. diagrs. on fold. l. 27 cm.
Series:        Verhandelingen der Koninklijke akademie van
                  wetenschappen te Amsterdam.  [Afdeeling voor de wis- en
                  natuurkundige wetenschappen] 1.sectie, deel V, no. 2
LC Call No.:   Q57.A532 deel 5, no. 2
Subjects:      Hyperspace.
Other titles:  Prismoïde.
Control No.:   7868644

Author:        Schoute, Pieter Hendrik, 1846-1913. [from old
                  catalog]
Title:         Regelmässige schnitte und projectionen des
                  aclitzelled und des sechszehnzelles im vierdimensionalen
                  raume.
Published:     Amsterdam, J, Müller, 1894.
Description:   p. cm.
LC Call No.:   Q57.A532 deel 2, no. 2
Subjects:      Hyperspace. [from old catalog]
Control No.:   6917141

Author:        Skarstedt, Marcus, 1884- [from old catalog]
Title:         The normal quartic curve of four-space,
Published:     [Berkeley, Calif., University of California
                  press, 1925]
Description:   2 p.l., p. [19]-34. 28 cm.
LC Call No.:   QA691.S5 1924
Subjects:      Hyperspace. [from old catalog]
               Curves, Quartic. [from old catalog]
Control No.:   9203643

Author:        Skarstedt, Marcus [from old catalog]
Title:         The normal quartic curve of four-space.
Published:     [n.p.] 1925
Description:   1 v. cm.
LC Call No.:   QA691.S5 1924
Control No.:   6736340

Author:        Sommerville, Duncan M'Laren Young, 1879-1934.
Title:         An introduction to the geometry of n dimensions.
Published:     New York, Dover Publications [1958]
Description:   xvii, 196 p. diagrs. 21 cm.
LC Call No.:   QA691.S6 1958
Dewey No.:     513.82
Notes:         "An unabridged and unaltered republication of the
                  first edition."
               Includes bibliographies.
Subjects:      Hyperspace.
Control No.:   6539453

Author:        Staniland, Albert Edward, 1898- [from old
                  catalog]
Title:         A note on the Serge curved four-space
                  representation of the plane of two complex variables,
Published:     [Pittsburgh, 1933]
Description:   7 p. 23 cm.
LC Call No.:   QA691.87 1932
Subjects:      Hyperspace. [from old catalog]
               Numbers, Complex. [from old catalog]
Control No.:   10165814

Author:        Steed, Daniel Victor, 1890-
Title:         The hyperspace generalization of the lines on the
                  cubic surface, by Daniel Victor Steed ...
Published:     [Berkeley, 1924]
Description:   p. [425]-443 diagr. 28 cm. bound 26 cm.
LC Call No.:   QA691.S74 1921
Notes:         Cover-title.
               Thesis (Ph. D.)--University of California, 1921.
               University of California publications in
                  mathematics, v. 1, no. 20, May 17, 1924, with a special
                  thesis t.-p. attached to the cover.
Subjects:      Hyperspace.
               Surfaces.
Control No.:   5921479

Author:        Stott, Alicia Boole.
Title:         On certain series of sections of the regular
                  four-dimensional hypersolids, by Alicia Boole Stott.
Published:     Amsterdam, J. Müller, 1900.
Description:   21 p. v. fold. diagrs. 27 cm.
Series:        Verhandelingen der Koninklijke akademie van
                  wetenschappen te Amsterdam. [Afdeeling voor de wis-
                  ennatuurkundige wetenschappen] 1. sectie, deel VII, no. 3
LC Call No.:   Q57.A532 deel 7, no. 3
Dewey No.:     598 s
Subjects:      Polyhedra.
               Hyperspace.
Control No.:   6463818

Author:        Stott, Alicia Boole.
Title:         On the sections of a block of eight cells by a
                  space rotating about a plane. By Mrs. A. Boole Stott and Dr.
                  P. H. Schoute.
Published:     Amsterdam, J. Müller, 1908.
Description:   25 p. incl. tables. II fold. diagrs. 26 cm.
Series:        Verhandelingen der Koninklijke akademie van
                  wetenschappen te Amsterdam.  [Afdeeling voor de wis- en
                  natuurkundige wetenschappen] 1.sectie, deel IX, no. 7
LC Call No.:   Q57.A532 deel 9, no. 7
Dewey No.:     508 s
Subjects:      Polyhedra.
               Hyperspace.
Other authors: Schoute, P. H. (Pieter Hendrik), 1846-1913, joint
                  author.
Control No.:   10210281

Author:        Sznyter, Mary Helen, 1893- [from old catalog]
Title:         The hypersurface of the second degree in
                  four-dimensional space,
Published:     [Berkeley, Calif., 1924]
Description:   2 p.l., 18 p. 27 cm.
LC Call No.:   QA691.S9 1918
Subjects:      Hyperspace. [from old catalog]
Control No.:   6391422

Author:        Vries, Hendrik de, 1867- [from old catalog]
Title:         "De vierde dimensie" eene inleiding tot de
                  vergelijkende studie der verschillende meetkunden,
Published:     Groningen, P. Noordhoff, 1915.
Description:   xii, 142 p. diagrs. 25 cm.
LC Call No.:   QA691.V7
Subjects:      Fourth dimension. [from old catalog]
Control No.:   10113587

Author:        Weitzenböck, Roland, 1885-
Title:         Komplex-symbolik.
Published:     Leipzig, G. J. Gòschen, 1908.
Description:   vi, 191 p. diagrs. 20 cm.
LC Call No.:   QA691.W4
Subjects:      Hyperspace.
Control No.:   9624598

Author:        Wernicke, Paul, 1866- [from old catalog]
Title:         Ueber die analysis situs mehrdimensionaler räume
                  ...
Published:     Göttingen, Dieterich'sche universitäts-buchdr.,
                  1904.
Description:   48, [2] p. diagrs. 24 cm.
LC Call No.:   QA691.W49
Subjects:      Hyperspace. [from old catalog]
               Topology. [from old catalog]
Control No.:   8208572

Author:        Woo, Kamcheung. [from old catalog]
Title:         The projective tranformation-group on a
                  hyperquadric in four-dimensional space.
Published:     Berkeley, Calif., 1933.
Description:   1 v. cm.
LC Call No.:   QA691.W6
Control No.:   9547511

Author:        Abbott, Edwin Abbott, 1838-1926.
Title:         Flatland: a romance of many dimensions, with
                  illus. by the author, A Square (Edwin A. Abbott)
Edition:       6th ed., rev. with introd. by Banesh Hoffmann.
Published:     New York, Dover Publications [1953, c1952]
Description:   103 p. illus. 21 cm.
LC Call No.:   QA699.A13 1953
Dewey No.:     513.088
Subjects:      Fourth dimension.
Control No.:   4055895

Author:        [Abbott, Edwin Abbott], 1838-1926. [from old
                  catalog]
Title:         Flatland; a romance of many dimensions, by A
                  Square, with illustrations by the author ...
Published:     Boston, Little, Brown and company, 1899.
Description:   viii p., 1 l., [11]-155 p. diagrs. 18 cm.
LC Call No.:   QA699.A13
Subjects:      Fourth dimension.
Control No.:   8201147

Author:        [Abbott, Edwin Abbott], 1838-1926. [from old
                  catalog]
Title:         Flatland; a romance of many dimensions, by A
                  Square, with illustrations by the author ...
Published:     Boston, Roberts brothers, 1885.
Description:   viii p., 1 l., [11]-155 p. diagrs. 18 cm.
LC Call No.:   QA699.A12
Subjects:      Fourth dimension.
Control No.:   8677852

Author:        Granville, William Anthony, 1863-1943.
Title:         The fourth dimension and the Bible, by William
                  Anthony Granville.
Published:     Boston, R.G. Badger [c1922]
Description:   ix, 119 p. illus., diagrs. 22 cm.
LC Call No.:   QA699.G7
Subjects:      Fourth dimension.
               Bible -- Criticism, interpretation, etc.
Control No.:   6851796

Author:        Hinton, C[harles] Howard, 1853-1907.
Title:         The fourth dimension.
Published:     London, S. Sonnenschein & co., ltd.; 1904.
Description:   viii, 247 p. fold. col. front., diagrs. 20 cm.
LC Call No.:   QA699.H6
               Microfilm 64790 QA
Subjects:      Hyperspace. [from old catalog]
Control No.:   8670184

Author:        Hinton, Charles Howard, 1853-1907.
Title:         A new era of thought. By Charles Howard Hinton
                  ...
Published:     London, S. Sonnenschein & co., 1888.
Description:   xvi, 216 p. 31 pl., diagrs. 19 cm.
LC Call No.:   QA699.H64
Notes:         "The MSS. which formed the basis of this book
                  were committed to us by the author ... It was his wish that
                  we should construct upon them a much more complete treatise
                  than we have effected ... Part I [has been printed] almost
                  exactly as it came from his hands ... Part II has been
                  written from a hurried sketch ... Chapter XI of this part
                  [and Appendix E have] been entirely re-written by us ...
                  Appendix H, and all the exercises have ... been written
                  solely by us." From the Preface signed: Alicia Boole, H. John
                  Falk.
Subjects:      Fourth dimension.
Other authors: Stott, Alicia Boole.
               Falk, H. John.
Control No.:   744982

Author:        Hinton, Charles Howard, 1853-1907.
Title:         The recognition of the fourth dimension,
Published:     Washington, The Society, 1902.
Description:   179-203 p. diagrs. 25 cm.
LC Call No.:   QA699.H65
Subjects:      Fourth dimension. [from old catalog]
Control No.:   9620377

Author:        Hinton, Charles Howard, 1853-1907.
Title:         Scientific romances,
Edition:       2d ser.
Published:     London, S. Sonnenschein & co., limd., 1902.
Description:   177 p. 19 cm.
LC Call No.:   QA699.H66 vol. 2
Other titles:  Stella.
               An unfinished communication.
Control No.:   10072529

Author:        Hinton, C[harles] H[oward], 1853-1907.
Title:         Scientific romances.
Published:     London, S. Sonnenschein & co., lim., 1886.
Description:   229 p. incl. illus., diagrs. 19 cm.
LC Call No.:   QA699.H66
Control No.:   6793386

Author:        Hinton, Charles Howard, 1853-1907.
Title:         What is the fourth dimension?
Published:     [London, 1883]
Description:   [31]-52 p. diagrs. 23 cm.
LC Call No.:   QA699.H68
Subjects:      Fourth dimension. [from old catalog]
Control No.:   8686409

Author:        [Lewis, George], 1885- [from old catalog]
Title:         The fourth dimension considered expecially with
                  relation to the Rosicrucian cosmology;
Published:     [New York, Commercial printing company], 1913.
Description:   15 p. 18 cm.
LC Call No.:   QA699.L4
Subjects:      Fourth dimension. [from old catalog]
Control No.:   5894983

Author:        Manning, Henry Parker, 1859- ed.
Title:         The fourth dimension simply explained; a
                  collection of essays selected from those submitted in the
                  Scientific American's prize competition, with an introduction
                  and editorial notes, by Henry P. Manning.
Published:     London, Methuen & co. ltd. [1921]
Description:   2 p. l., [3]-251, [1] p. illus., diagrs. 20 cm.
LC Call No.:   QA699.M3 1921
Dewey No.:     516.182
Notes:         "Articles and books [which] treat in a
                  non-mathematical way of the fourth dimension of other modern
                  ideas of geometry":  p. 40-41.
Subjects:      Fourth dimension.
Control No.:   7319860

Author:        Manning, Henry Parker, 1859-, ed.
Title:         The fourth dimension simply explained; a
                  collection of essays selected from those submitted in the
                  Scientific American's prize competition, with an introduction
                  and editorial notes, by Henry P. Manning ...
Published:     New York, Munn & company, inc. 1910.
Description:   251 p. illus., diagrs. 21 cm.
LC Call No.:   QA699.M3
ISBN:          $1.50
Subjects:      Fourth dimension.
Control No.:   2161708

Author:        Schofield, A. T. (Alfred Taylor), 1846-1929.
Title:         Another world; or, The fourth dimension, by A. T.
                  Schofield.
Edition:       5th ed.
Published:     London, G. Allen & Unwin [1920]
Description:   92 p. illus. 19 cm.
LC Call No.:   QA699.S35 1920
Subjects:      Fourth dimension.
Control No.:   9224793

Author:        Uspenskiæi, Petr Dem§ëiìanovich, 1878-1947. [from
                  old catalog]
Title:         Chetvertoe izmëiìerenie.
Published:     1921.
Description:   116 p. 20 cm.
LC Call No.:   QA699.U86 1921
Notes:         Romanized.
Subjects:      Fourth dimension. [from old catalog]
Control No.:   6043132
