#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Anderson, Rose Lucile, 1900- [from old catalog]
Title:         A problem in the simultaneous reduction of two
                  quadratic forms in infinitely many variables,
Published:     [Princeton, N.J., 1932]
Description:   1 p.l., p. 229-230, 1 l. 26 cm.
LC Call No.:   QA201.A6 1930
Subjects:      Forms, Quadratic. [from old catalog]
Control No.:   7354414

Author:        Autonne, Léon, 1859-1916.
Title:         Sur les formes mixtes,
Published:     Lyon, A. Rey; [etc., etc.] 1905.
Description:   2 p.l., 194 p., 1 l. 25 cm.
LC Call No.:   QA201.A93
               Microfilm 47186 QA
Subjects:      Forms (Mathematics)
               Connexes.
               Contact transformations.
Control No.:   8675692

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Ricerche sulla geometrica delle forme binarie
                  cubiche. Memoria del Prof. E. Beltrami ...
Published:     1869.
Description:   p. [607]-657.
LC Call No.:   Q54.B6
Notes:         In: R. Accademia delle scienze dell'Istituto di
                  Bologna. Memorie. Bologna, 1869. 30 cm. ser. 2, t. ix, p.
                  [607]-657.
Subjects:      Forms, Binary. [from old catalog]
Control No.:   7732841

Author:        Black, Florence Lucile.
Title:         A reduced system of differential equations for
                  the invariants of ternary forms / [by] Florence Black.
Published:     Lawrence, Kansas : University of Kansas, 1929.
Description:   p. 17-25 ; 23 cm.
Series:        University of Kansas science bulletin ; v. 19,
                  no. 2
LC Call No.:   QA201.B5 1929
Notes:         Kansas State Documents Classification Number:
                  E50.13 : v. 19, no. 2
               Published also as thesis (Ph. D.)--University of
                  Kansas, 1926.
Availability:  KD08200
Subjects:      Forms, Ternary.
               Differential equations.
Other authors: University of Kansas.
Control No.:   5940446

Author:        Blumenthal, Leonard Mascot, 1901-
Title:         Lagrange resolvents in Euclidean geometry / by
                  Leonard M. Blumenthal.
Published:     [Baltimore, 1927]
Description:   p. 511-522 : ill. ; 25 cm.
LC Call No.:   QA201.B55 1927
Notes:         Thesis (Ph. D.)--Johns Hopkins University, 1927.
Control No.:   8272231

Author:        Bonsdorff, Ernst Jacob Waldemar, 1842- [from old
                  catalog]
Title:         Härledning och geometrisk tydning af de
                  vigtigaste combinanterna i det ternära kubiska
                  formsystemet.
Published:     Helsingfors, J.C. Frenckell & son, 1876.
Description:   1 p. l., 66 p. 24 cm.
LC Call No.:   QA201.B7
Notes:         Akademisk afhandling--Helsingfors.
Subjects:      Forms, Ternary.
Control No.:   13393208

Author:        Capelli, Alfredo, 1855-1910.
Title:         Lezioni sulla teoria delle forme algebriche, per
                  Alfredo Capelli ...
Published:     Napoli, B. Pellerano, 1902.
Description:   viii, 295 p. 24 cm.
LC Call No.:   QA201.C23
               Microfilm 16303 QA
Notes:         Autographed; title-page and table of contents
                  printed.
               Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Forms (Mathematics)
Control No.:   2161066

Author:        Carus, Edward Hegeler, 1890-
Title:         Invariants as products and a vector
                  interpretation of the symbolic method ... by Edward Hegeler
                  Carus ...
Published:     [Chicago, The Open court publishing co., 1927]
Description:   3 p.l., 44 p. diagrs. 24 cm.
LC Call No.:   QA201.C3 1921
Notes:         Thesis (PH. D.)--University of Chicago, 1921.
               Published also without thesis note.
Subjects:      Invariants.
               Vector analysis.
               Forms, Binary.
Other titles:  Symbolic method, A vector interpretation of the.
Control No.:   4053656

Author:        Carus, Edward Hegeler, 1890-
Title:         Invariants as products and a vector
                  interpretation of the symbolic method, by Edward Hegeler
                  Carus.
Published:     Chicago, London, The Open court publishing co.
                  [c1927]
Description:    4 p. l., 44 p. diagrs. 24 cm.
LC Call No.:   QA201.C3 1927
Subjects:      Invariants.
               Vector analysis.
               Forms, Binary.
Other titles:  Symbolic method, A vector interpretation of the.
Control No.:   9206596

Author:        Chanler, Josephine Hughes, 1906- [from old
                  catalog]
Title:         Poristic double binary forms,
Published:     [Baltimore, 1934]
Description:   2 p.l., p. 529-546, 1 l. 25 cm.
LC Call No.:   QA201.C45 1933
Subjects:      Forms, Binary. [from old catalog]
               Curves, Algebraic. [from old catalog]
Other titles:  Double binary forms.
Control No.:   5954787

Author:        Clebsch, Alfred, 1833-1872.
Title:         Théorie der binären algebraischen Formen, von
                  A. Clebsch ...
Published:     Leipzig, B.G. Teubner, 1872.
Description:   viii, 467, [1] p. 24 cm.
LC Call No.:   QA201.C5
Subjects:      Forms, Binary.
Control No.:   8664412

Author:        Clifford, William Kingdon, 1845-1879.
Title:         Mathematical fragments, being facsimiles of his
                  unfinished papers relating to the theory of graphs.
Published:     London, Macmillan and co., 1881.
Description:   1 p.l., xxii numb. l. diagrs. 34 cm.
LC Call No.:   QA201.C6
Subjects:      Forms (Mathematics) [from old catalog]
Control No.:   7737801

Author:        Copeland, Lennie Phoebe, 1881-
Title:         On the theory of invariants of n-lines / by
                  Lennie Phoebe Copeland.
Published:     Lancaster, Pa. : New Era, [1914]
Description:   1 leaf, 7-14 p. ; 26 cm.
LC Call No.:   QA201.O65
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1913.
               "Reprinted from Annals of mathematics, second
                  series, vol. 16, no. 1, September, 1914."
Subjects:      Invariants.
Control No.:   10111096

Author:        Cresse, George Hoffman, b. 1871.
Title:         The class number of binary quadratic forms ... by
                  George Hoffman Cresse ...
Published:     [Washington] 1923.
Description:   [1], 92-197 p., 1 l. 26 cm.
LC Call No.:   QA201.C7
Notes:         Thesis (PH. D.)--University of Chicago, 1918.
               "Reprinted from Dickson's History of the theory
                  of numbers, vol. III, ch. VI. The Carnegie institution of
                  Washington."
Subjects:      Forms, Binary.
               Forms, Quadratic.
Control No.:   2635110

Author:        Daub, Emil, 1863- [from old catalog]
Title:         Ueber einige die binären und ternären formen
                  betreffende aufgaben ...
Published:     Darmstadt, 1888.
Description:   32 p. 27 x 22 cm.
LC Call No.:   QA201.D23
Subjects:      Forms (Mathematics) [from old catalog]
Control No.:   6328261

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         Algebraic invariants, by Leonard Eugene Dickson
                  ...
Edition:       1st ed., 1st thousand.
Published:     New York, J. Wiley & Sons, inc.; [etc., etc.]
                  1914.
Description:   x, 100 p. diagrs. 24 cm.
Series:        Mathematical monographs. No. 14
LC Call No.:   QA201.D5
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Forms (Mathematics)
Control No.:   10110672

Author:        Dorner, Otto, 1884- [from old catalog]
Title:         Über teiler von formen ... von Otto Dorner.
Published:     Königsberg i, Pr., Buch- und steindr. von O.
                  Kümmel, 1908.
Description:   67, [1] p. 23 cm.
LC Call No.:   QA201.D8
Notes:         Inaug.-diss.--Königsberg.
               Lebenslauf.
Subjects:      Forms (Mathematics)
Control No.:   13181359

Author:        Dressel, Paul Leroy, 1910-
Title:         Statistical seminvariants and their setimates [!]
                  with particular emphasis on their relation to algebraic
                  invariants ... by Paul L. Dressel.
Published:     [Ann Arbor, Mich.] 1939 [i. e. 1940]
Description:   p. 33-57 incl. tables. 26 cm.
LC Call No.:   QA201.D87 1940
Dewey No.:     512.88
Notes:         Cover title.
               "Reprinted from the Annals of mathematical
                  statistics, vol. XI, no. 1, March, 1940."
               Thesis (Ph. D.)--University of Michigan, 1939.
               "References": p. 57.
Subjects:      Invariants
               Mathematical statistics
Other titles:  Seminvariants.
Control No.:   7380246

Author:        Dribin, Daniel Maccabaeus, 1913-
Title:         Representation of binary forms by sets of ternary
                  forms / by Daniel Maccabaeus Dribin.
Published:     [Chicago, 1938]
Description:   1 leaf, p. [115]-132, 1 leaf ; 24 cm.
LC Call No.:   QA201.D88 1936
Notes:         Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Thesis (Ph. D.)--University of Chicago, 1936.
               "Reprinted from Travaux de l'Institut
                  mathématique de Tbilissi, vol. 5, 1938."
Subjects:      Forms, Binary.
               Forms, Ternary.
Control No.:   7374153

Author:        Echols, William H. (William Holding), 1859-1934
Title:         On a certain quadratic form with its geometric
                  and kinematic interpretations, by William H. Echols.
Published:     Charlottesville, Va., University of Virginia
                  [1912]
Description:   p. 231-242. 27 cm.
Series:        Bulletin of the Philosophical Society. 
                  Scientific series, vol. 1, no. 9
               University of Virginia publications.
LC Call No.:   QA201.E3
Notes:         Cover title.
Subjects:      Forms, Quadratic.
Control No.:   8700427

Author:        Elliott, Edwin Bailey, 1851-1937. [from old
                  catalog]
Title:         An introduction to the algebra of quantics,
Published:     Oxford, The Clarendon press, 1895.
Description:   xiii, [1], 423, [1] p. 23 cm.
LC Call No.:   QA201.E4
Subjects:      Forms (Mathematics) [from old catalog]
Control No.:   8333861

Author:        Faà di Bruno, Francesco, 1825-1888.
Title:         Théorie des formes binaires, par le Chev. F.
                  Faà de Bruno ... Résumé des leçons faites à
                  l'Université de Turin.
Published:     Turin, Brero succr. de P. Marietti; [etc., etc.]
                  1876.
Description:   1 p.l., xvi, 320, [31] p. tables (3 fold.) 23
                  cm.
LC Call No.:   QA201.F12
Notes:         "Mémoires et ouvrages de divers auteurs relatifs
                  à la théorie des formes binaires": p. [ix]-xiii.
Subjects:      Forms, Binary.
Control No.:   2634047

Author:        Foethke, Ernst, 1882-
Title:         Anwendung des erweiterten Euklidischen
                  Algorithmus auf Resultantenbildungen / von Ernst Foethke.
Published:     Königsberg i. Pr. : Hartungsche Buchdr., 1907.
Description:   75, [1] p. ; 22 cm.
LC Call No.:   QA201.F6
Notes:         Lebenslauf.
               Inaug.-diss.--Albertus-Universität.
Subjects:      Forms (Mathematics)
Control No.:   9622269

Author:        Glenn, Oliver E. (Oliver Edmunds), b. 1878.
Title:         A treatise on the theory of invariants, by Oliver
                  E. Glenn ...
Published:     Boston, New York [etc.] Ginn and company [c1915]
Description:   x, 245 p. 22 cm.
LC Call No.:   QA201.G5
ISBN:          $2.75
Subjects:      Invariants.
Control No.:   273446

Author:        Gordan, Paul, 1837-1912.
Title:         Dr. Paul Gordan's Vorlesungen über
                  invariantentheorie. Herausgegeben von dr. Georg
                  Kerschensteiner ...
Published:     Leipzig, B.G. Teubner, 1885-87.
Description:   2 v. in 1. 25 cm.
LC Call No.:   QA201.G62
               Microfilm 48463 QA
Notes:         1. bd. Determinanten.--2. bd. Binäre formen.
               LC copy replaced by microfilm.
               Microfilm. Washington, D.C., Library of
                  Congress.
Subjects:      Invariants.
               Determinants.
               Forms, Binary.
Other authors: Kerschensteiner, Georg, 1854-1932, ed.
Control No.:   744776

Author:        Gordan, Paul, 1837-1912.
Title:         Über das formensystem binaerer formen ... von
                  Paul Gordan ...
Published:     Leipzig, Druck von B.G. Teubner, 1875.
Description:   1 p.l., 52 p. 23 cm.
LC Call No.:   QA201.G6
Notes:         Programm zum eintritt in die philosophische
                  facultät und den senat der Königl.
                  Friedrich-Alexanders-universität zu Erlangen.
Subjects:      Forms, Binary.
Control No.:   3579289

Author:        Grace, J. H. (John Hilton), b. 1873.
Title:         The algebra of invariants by J.H. Grace ... and
                  A. Young ...
Published:     Cambridge, Cambridge University Press, 1903.
Description:   vi p., 1 l., 384 p. diagrs. 23 cm.
LC Call No.:   QA201.G72
               Microfilm 15979 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Invariants.
Other authors: Young, Alfred, joint author.
Control No.:   2161170

Author:        Grau, Albert A., 1916- [from old catalog]
Title:         Ternary Boolean algebra.
Published:     [n.p., 1947]
Description:   567-572 p. 25 cm.
LC Call No.:   QA201.G75
Subjects:      Forms, Ternary.
Other titles:  Boolean algebra.
Control No.:   7884126

Author:        Guradze, Hans, 1875-
Title:         Die Reye'sche geometrie der mannigfaltigkeiten
                  projectiver grundgebilde behandelt mittelts einer besonderen
                  art bilinearer formen ...
Published:     Breslau, R. Galle's buchdruckerei, 1900.
Description:   3 p. l., 68, [2] p., 1 l. 23 cm.
LC Call No.:   QA201.G97
Notes:         Inaug.-diss.--Breslau.
               Lebenslauf.
Subjects:      Bilinear forms.
               Reye, Theodor, 1838-
Control No.:   9610204

Author:        Hilbert, David, 1862- [from old catalog]
Title:         Ueber die invarianten eigenschaften spezieller
                  binärer formen, insbesondere der kugelfunctionen ...
Published:     Königsberg in Pr., Buchdruckerei von R. Leupold,
                  1885.
Description:   2 p.l., 30, [2] p. 29 x 23 cm.
LC Call No.:   QA201.H72
Subjects:      Forms, Binary. [from old catalog]
               Spherical harmonics. [from old catalog]
Control No.:   5860306

Author:        Huber, Clyde Mortimer, 1899-
Title:         On complete systems of irrational invariants of
                  associated point sets / by Clyde Mortimer Huber.
Published:     [Baltimore, 1927]
Description:   1 leaf, p. 251-267, 1 leaf ; 25 cm.
LC Call No.:   QA201.H77 1926.
Notes:         Vita.
               Thesis (Ph. D.)--University of Illinois, 1926.
               "Reprinted from American journal of mathematics,
                  vol. XLIX, number 2."
Subjects:      Invariants.
Control No.:   6398641

Author:        Hurst, John Wildeboor, 1895-
Title:         The classification of ternary algebras, by John
                  Wildeboor Hurst ...
Published:     Urbana, Ill., 1927.
Description:   7 p. 24 cm.
LC Call No.:   QA201.H8
Notes:         Digest of thesis (PH. D.)--University of
                  Illinois, 1925.
               Vita.
Subjects:      Forms, Ternary.
Other titles:  Ternary algebras.
Control No.:   1690519

Author:        Irwin, Thomas J.
Title:         The binary scale; systems of numeration,
                  rudiments of algebra, theory of binary numbers, correlative
                  geometry, binary network.
Edition:       1st ed.
Published:     [Atlanta? 1961]
Description:   126 p. 24 cm.
LC Call No.:   QA201.I7
Subjects:      Binary system.
               Forms, Binary.
               Locus (Mathematics)
Control No.:   10335382

Author:        Junker, Josef Hilarius, 1858- [from old catalog]
Title:         Die verallgemeinerung der Hermiteschen
                  transformation im zusammenhang mit der invarianten
                  theoretischen reduktion der gleichungen ...
Published:     Köln, Druck von M. Dumont-Schauberg, 1887.
Description:   2 p.l., 32 p. 30 x 23 cm.
LC Call No.:   QA201.J8
Subjects:      Forms, Binary. [from old catalog]
Control No.:   6339373

Author:        Krathwohl, William Charles, b. 1882.
Title:         Modular invariants of two pairs of cogredient
                  variables ... by William Charles Krathwohl ...
Published:     Baltimore, Md., The Lord Baltimore press [1914]
Description:   1 p.l., [449]-460 p., 1 l. 31 cm.
LC Call No.:   QA201.K8
Notes:         Thesis (PH. D.)--University of Chicago, 1913.
               Vita.
               "Reprinted from American journal of mathematics,
                  vol. XXXVI, no. 4, October, 1914."
Subjects:      Forms (Mathematics)
Control No.:   1217966

Author:        Krey, H.
Title:         Die Invarianten und Covarianten der binären
                  Formen siebenter Ordnung / von H. Krey.
Published:     Striegau : E. Gröger, 1874.
Description:   27 p. ; 21 cm.
LC Call No.:   QA201.K9
Notes:         Inaug.-diss.
Subjects:      Forms, Binary.
Control No.:   9134680

Author:        Lapsley, Janie Campbell, 1913-
Title:         Apolar systems of bilinear forms / by Janie
                  Campbell Lapsely.
Published:     Urbana, Ill., 1943.
Description:   [13] p. ; 23 cm.
LC Call No.:   QA201.L3
Notes:         Reproduced from type-written copy.
               Vita.
               Abstract of thesis (Ph. D.)--University of
                  Illinois, 1943.
               Bibliography:  p. [12]
Subjects:      Bilinear forms.
Control No.:   8327120

Author:        Lewis, Florence Parthenia, 1877- [from old
                  catalog]
Title:         A geometrical application of the theory of the
                  binary quintic ...
Published:     [Baltimore, 1914]
Description:   1 p. l., [333]-356 p., 1 l. diagrs. 31 cm.
LC Call No.:   QA201.L4
Subjects:      Forms, Binary.
               Curves, Quintic.
Control No.:   8705567

Author:        Loewy, Alfred, 1873- [from old catalog]
Title:         Ueber bilineare formen mit konjugirt imaginären
                  variablen ...
Published:     Halle, Druck von E. Karras, 1898.
Description:   70 p. 33 x 25 cm.
LC Call No.:   QA201.L8
Subjects:      Bilinear forms.
Control No.:   7254444

Author:        Logsdon, Mayme Irwin. [from old catalog]
Title:         Equivalence and reduction of pairs of hermitian
                  forms ...
Published:     [Baltimore, 1922]
Description:   1 p. l., p. 247-260. 26 cm.
LC Call No.:   QA201.L85
Subjects:      Forms (Mathematics) [from old catalog]
Control No.:   10132691

Author:        MacKinnon, Annie L. (Annie Louise)
Title:         Concomitant binary forms in terms of the roots.
                  By Miss Annie L. MacKinnon ...
Published:     [Washington, 1898?]
Description:   [95]-157, 95-109 p. tables 30 x 24 cm.
LC Call No.:   QA201.M18
Notes:         Dissertation: Cornell.
               Reprinted from Annals of mathematics, v. 9 and 
                  12.
               "References": p. 155-157.
               The part reprinted from v. 9 was presented to the
                  Faculty of Cornell university in partial fulfilment of the
                  requirements for the degree of doctor of philosophy; that
                  from v. 12 is supplementary, and contains tables.
Subjects:      Forms, Binary.
Control No.:   1216889

Author:        Maennchen, Philipp, 1869- [from old catalog]
Title:         Die transformation der trilinearen ternären form
                  in eine teilweise symmetrische ...
Published:     Leipzig, Druck von B. G. Teubner, 1898.
Description:   34 p. 24 cm.
LC Call No.:   QA201.M2
Subjects:      Forms, Ternary.
Control No.:   7254512

Author:        Mey, Oscar, 1858- [from old catalog]
Title:         Ueber die darstellung binärer formen auf den
                  normcurven ...
Published:     Greifswald, Druck von F. W. Kunike, 1886.
Description:   2 p.l., 40 p. 22 cm.
LC Call No.:   QA201.M61
Subjects:      Forms, Binary. [from old catalog]
Control No.:   9133690

Author:        Meyer, W. Franz (Wilhelm Franz), 1856-
Title:         Allgemeine formen- und invariantentheorie. 1. bd.
                  Binäre formen, von W.Fr. Meyer ...
Published:     Leipzig, G.J. Göschen, 1909.
Description:   viii, 376 p. 20 cm.
Series:        Sammlung Schubert XXXIII
LC Call No.:   QA201.M7
Notes:         No more published.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Forms, Binary.
Series Entry:  Sammlung Schubert ; 33.
Control No.:   4525873

Author:        Moore, Thomas Walker. [from old catalog]
Title:         On the invariant combinants of two binary
                  quintics,
Published:     [Baltimore, 1928]
Description:   1 p.l., p. 415-430. 25 cm.
LC Call No.:   QA201.M75 1927
Subjects:      Forms, Binary.
               Curves, Quintic.
Control No.:   5932949

Author:        Morley, Raymond Kurtz, 1882-
Title:         On the fundamental postulate of tamisage, by
                  Raymond K. Morley  ...
Published:     [Worcester, Mass., 1912]
Description:   Cover-title, p. [47]-68 ; 26 cm.
LC Call No.:   QA201.M8
Notes:         Thesis (Ph. D.)--Clark University, 1910.
               "Reprinted from American journal of mathematics
                  [January 1912] vol. XXXIV, no. 1."
Subjects:      Invariants.
Control No.:   6357539

Author:        National Research Council (U.S.). Committee on
                  Tables of Positive Ternary Quadratic Forms. [from old
                  catalog]
Title:         A table of Eisenstein-reduced positive ternary
                  quadratic forms of determinant [less than or equal to] 200.
                  Report of the Committee on tables of positive ternary
                  quadratic forms. Burton W. Jones [chairman].
Published:     [Washington, D.C., Published by the National
                  research council of the National academy of sciences, 1935]
Description:   51 p. 25 cm.
Series:        Bulletin of the National Research Council, no.
                  97
LC Call No.:   QA201.N3
Notes:         Running title: Eisenstein-reduced quadratic
                  forms.
Subjects:      Forms, Ternary.
               Forms, Quadratic.
Other authors: Jones, Burton Wadsworth, 1902-
Other titles:  Eisenstein-reduced quadratic forms.
Control No.:   13410588

Author:        Noether, Emmy, 1882-1935.
Title:         Über die bildung des formensystems der ternären
                  biquadratischen form.
Published:     Berlin, Druck von G. Reimer, 1908.
Description:   72 p. fold. tab. 29 cm.
LC Call No.:   QA201.N7
Notes:         Inaug.-diss.--Erlangen.
               Lebenslauf.
Subjects:      Forms, Ternary.
Control No.:   13410594

Author:        Peters, Joseph William, 1903- [from old catalog]
Title:         Invariants of sets of points under inversion ...
Published:     [Baltimore, 1929]
Description:   1 p.l., p. 599-611, 1 l. 25 cm.
LC Call No.:   QA201.P4 1928
Subjects:      Invariants. [from old catalog]
               Aggregates. [from old catalog]
Control No.:   9215595

Author:        Ross, Arnold E. (Arnold Ephraim), 1906-
Title:         On representation of integers by indefinite
                  ternary quadratic forms of quadratfrei determinant ... by
                  Arnold E. Ross ...
Published:     [Baltimore, 1933]
Description:   1 p.l., p. 293-302. 25 cm.
LC Call No.:   QA201.R6 1931
Dewey No.:     512.87
Notes:         Thesis (PH. D.)--University of Chicago, 1931.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from the American journal of
                  mathematics, vol. LV, number 2."
Subjects:      Forms (Mathematics)
Control No.:   2635674

Author:        Salmon, George, 1819-1904.
Title:         Lessons introductory to the modern higher
                  algebra.
Edition:       4th ed.
Published:     Dublin, Hodges, Figgis, and co., 1885.
Description:   xv, [1], 360 p. 23 cm.
LC Call No.:   QA201.S17
Subjects:      Determinants.
               Forms, Binary.
Control No.:   10070484

Author:        Sanderson, Mildred, 1889-
Title:         Formal modular invariants with application to
                  binary modular covariants ... by Mildred Sanderson.
Published:     [Lancaster, Pa., New York] 1913.
Description:   1 p.l., p. 489-500, 1 l. 28 cm.
LC Call No.:   QA201.S2
Notes:         Thesis (PH. D.)--University of Chicago, 1913.
               Vita.
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 14, no. 4, October, 1913, pp.
                  489-500."
Subjects:      Forms (Mathematics)
Control No.:   273364

uthor:        Scheibner, W. (Wilhelm), 1826-1908.
Title:         Beiträge zur theorie der linearen
                  transformationen als einleitung in die algebraische
                  invariantentheorie, von W. Scheibner ...
Published:     Leipzig, B.G. Teubner, 1907.
Description:   250 p. 26 cm.
LC Call No.:   QA201.S33
Notes:         Published in the Berichte der
                  Mathematisch-physischen klasse der Königl. Sächsischen
                  gesellschaft der wissenschaften, 1903-07.
Subjects:      Forms (Mathematics)
               Equations, Theory of.
               Differential forms.
               Functions.
Control No.:   3579841

Author:        Scheibner, W[ilhelm], 1826- [from old catalog]
Title:         Beiträge zur theorie der linearen
                  transformationen,
Published:     [Leipzig, 1903-04]
Description:   3 v. 23 cm.
LC Call No.:   QA201.S31
Subjects:      Forms (Mathematics)
               Equations, Theory of.
               Differential forms.
Control No.:   6332162

Author:        Schlesinger, Otto, 1860- [from old catalog]
Title:         Ueber conjugirte binäre formen ...
Published:     Breslau, T. Schatzky's buchdruckerei, 1882.
Description:   2 p.l., 57, [2] p. 22 cm.
LC Call No.:   QA201.S35
Subjects:      Forms, Binary. [from old catalog]
Control No.:   7268455

Author:        Sensenig, Wayne. [from old catalog]
Title:         Concerning the invariant theory of involutions of
                  conics ...
Published:     [Baltimore, 1919]
Description:   1 p. l., p. [111]-122. 32 cm.
LC Call No.:   QA201.S4
Subjects:      Invariants. [from old catalog]
Control No.:   9655128

Author:        Shenton, Walter Francis, 1886- [from old
                  catalog]
Title:         Linear combinants of systems of binary forms,
                  with the syzygies of the second degree connecting them ...
Published:     [Baltimore, 1915]
Description:   1 p.l., [247]-271, [1] p. 31 cm.
LC Call No.:   QA201.S5
Subjects:      Forms, Binary. [from old catalog]
Control No.:   9178337

Author:        Sherwood, G. E. F. (George Eulas Foster), b.
                  1883.
Title:         Equivalence of triples of bilinear forms.
Published:     [n. p.] 1923.
Description:   59 l. 29 cm.
LC Call No.:   QA201.S53
Subjects:      Bilinear forms.
               Numbers, Complex.
Control No.:   8042630

Author:        Stickelberger, Ludwig, 1850- [from old catalog]
Title:         De problemate quodam ad duarum formarum
                  bilinearium vel quadraticarum transformationen pertinente.
Published:     Berolini, typis expressit G. Schade (O. Francke)
                  [1874]
Description:   22 p. 26 cm.
LC Call No.:   QA201.S77
Subjects:      Forms, Binary. [from old catalog]
Control No.:   8201474

Author:        Story, William Edward, 1850-1930.
Title:         On the algebraic relations existing between the
                  polars of a binary quantic.
Published:     Leipzig, Printed by Metzger & Wittig, 1875.
Description:   58 p., [1] l. 22 cm.
LC Call No.:   QA201.S8
Notes:         Inaug.-dis.--Leipzig.
               Vita.
Subjects:      Forms, Binary.
Control No.:   12928751

Author:        Strobel, Charles Frederick, 1911-
Title:         The quadrilinear form (1, 1, 1, 2) / by Charles
                  Frederick Strobel.
Published:     Urbana, Ill., 1941.
Description:   1 leaf, 4 p., 1 leaf ; 23 cm.
LC Call No.:   QA201.S9
Notes:         Reproduced from type-written copy.
               Vita.
               Abstract of thesis (Ph. D.)--University of
                  Illinois, 1941.
Subjects:      Forms, Quadrilinear.
Control No.:   7383061

Author:        Stroh, Emil. [from old catalog]
Title:         Über die symbolische darstellung der
                  grundsyzyganten einer binären form sechster ordnung und eine
                  erweiterung der symbolik von Clebsch ...
Published:     Leipzig, Druck von B. G. Teubner, 1890.
Description:   44 p. 25 cm.
LC Call No.:   QA201.S92
Subjects:      Forms, Binary. [from old catalog]
Control No.:   5856104

Author:        Study, Eduard, 1862-1930. [from old catalog]
Title:         Methoden zur theorie der ternaeren formen.
Published:     Leipzig, B. G. Teubner, 1889.
Description:   xi, [1], 210 p. 25 cm.
LC Call No.:   QA201.S955
Subjects:      Forms, Ternary.
Control No.:   6931308

Author:        Thaer, Clemens, b. 1883.
Title:         Über Invarianten, die symmetrischen
                  eigenschaften eines Punktsystems entsprechen / von Clemens
                  Thaer.
Published:     Leipzig : B. G. Teubner, 1906.
Description:   31, [1] p. ; 24 cm.
LC Call No.:   QA201.T4
Notes:         Lebenslauf.
               Inaug. diss.--Giessen.
Subjects:      Forms (Mathematics)
Control No.:   7283833

Author:        Thomas, Tracy Y. (Tracy Yerkes), 1899-
Title:         The concept of invariance in mathematics, by
                  Tracy Y. Thomas ...
Published:     Berkeley, Los Angeles, University of California
                  Press, 1944.
Description:   1 p. l., 14 p. 24 cm.
Series:        Faculty research lecture (University of
                  California, Los Angeles)... 1943
               Faculty research lecture 
LC Call No.:   QA201.T45
Dewey No.:     512.88
Subjects:      Invariants.
               Relativity (Physics)
Control No.:   8331407

Author:        Wade, Thomas Leonard, 1905-
Title:         Syzygies for Weitzenböck's irreducible complete
                  system of Euclidean concomitants for the conic, with an
                  algebraically complete system of such concomitants ... by
                  Thomas L. Wade, Jr. ...
Published:     [Baltimore, 1934]
Description:   1 p. l., p. 349-358. 25 cm.
LC Call No.:   QA201.W2 1933
Dewey No.:     512.88
Notes:         Part of thesis (PH. D.)--University of Virginia,
                  1933.
               "Reprinted from the American journal of
                  mathematics, vol. 56, number 3."
Subjects:      Invariants.
               Conic sections.
Other titles:  Weitzenböck's irreducible complete system.
Control No.:   7827130

Author:        Wagner, Rudolf, 1882-
Title:         Über binäre bilineare und quaternäre
                  quadratische Formen / von Rudolf Wagner.
Published:     Giessen : Münchow, 1909.
Description:   24 p., 1 leaf ; 23 cm.
LC Call No.:   QA201.W25
Notes:         Lebenslauf.
               Inaug.-diss.--Giessen.
Subjects:      Forms (Mathematics)
Control No.:   9164405

Author:        Wedekind, Ludwig. [from old catalog]
Title:         Studien im binären werthgebiet ...
Published:     Carlsruhe, Druck der G. Braun'schen
                  hofbuchdruckerei, 1876.
Description:   51 p. diagrs. on fold. pl. 25 cm.
LC Call No.:   QA201.W33
Subjects:      Forms, Binary. [from old catalog]
Control No.:   9606415

Author:        Wedeking, L[udwig] [from old catalog]
Title:         Beiträge zur geometrischen interpretation
                  binärer formen.
Published:     Erlangen, Druck von E. T. Jacob, 1875.
Description:   55 p. 11 diagr. on 2 fold. pl. 22 cm.
LC Call No.:   QA201.W3
Subjects:      Forms, Binary. [from old catalog]
Control No.:   9134516

Author:        Wellstein, Josef, 1869-1919.
Title:         Über das Lindemannsche uebertragungsprincip ...
Published:     Strassburg i. E., Buchdruckerei C. Gœller, 1894.
Description:   30 p., 1 l. 23 cm.
LC Call No.:   QA201.W46
Subjects:      Forms (Mathematics)
Control No.:   6796131

Author:        Williams, W. L. G. (William Lloyd Garrison)
Title:         Fundamental systems of formal modular
                  seminvariants of the binary cubic, by W.L.G. Williams ...
Published:     [Lancaster, Pa., New York, 1921]
Description:   1 p.l., p. 56-79. 28 cm.
LC Call No.:   QA201.W58
Notes:         Thesis (Ph. D.)--University of Chicago, 1920.
               "Private edition distributed by the University of
                  Chicago libraries."
               "Reprinted from Transactions of the American
                  mathematical society, volume 22, number 1 (January, 1921)"
Subjects:      Forms, Binary.
Other titles:  Formal modular seminvariants.
Control No.:   4053431

Author:        Wilson, Albert Harris, b. 1872.
Title:         The canonical types of nets of modular conics ...
                  by Albert Harris Wilson ...
Published:     Baltimore, The Lord Baltimore press [1914]
Description:   1 p.l., p. [187]-210, 1 l. 28 cm.
LC Call No.:   QA201.W6
Notes:         Thesis (Ph. D.)--University of Chicago, 1911.
               Life.
               "Reprinted from American Journal of mathematics,
                  vol. XXXVI, no. 2, April, 1914."
Subjects:      Forms, Quadratic.
Control No.:   1217922

Author:        Wölffing, Ernst, 1864-
Title:         Über die Hess'sche Covariante einer ganzen
                  rationalen Function von ternären Formen / von Ernst
                  Wölffing.
Published:     Leipzig : B. G. Teubner, 1890.
Description:   26 p. ; 24 cm.
LC Call No.:   QA201.W84
Notes:         Inaug.-diss.--Tübingen.
Subjects:      Forms, Ternary.
Control No.:   7260494

Author:        Wright, Harry M. [from old catalog]
Title:         On a tabulation of reduced binary quadratic forms
                  of a negative determinant.
Published:     [n.p.] 1914.
Description:   1 v. cm.
LC Call No.:   QA201.W9
Control No.:   8609548

Author:        Zeisler, Ernest Bloomfield, 1899-
Title:         Definite integral representation of invariants.
Edition:       Private ed.
Published:     Distributed by the University of Chicago
                  Libraries, 1922.
Description:   24 l. 29 cm.
LC Call No.:   QA201.Z44 1922
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
Subjects:      Invariants.
               Integrals.
               Matrices.
               Integral representations.
Control No.:   4564924

Author:        Barton, Samuel Marx, 1859-1926.
Title:         An elementary treatise on the theory of
                  equations, by Samuel Marx Barton.
Published:     Boston, D.C. Heath & co., 1899.
Description:   xii, 199 p. 22 cm.
LC Call No.:   QA211.B2
Dewey No.:     512.82
Subjects:      Equations, Theory of.
               Determinants.
Control No.:   4055327

Author:        Borofsky, Samuel, 1907-
Title:         Elementary theory of equations.
Published:     New York, Macmillan [1950]
Description:   x, 302 p. diagrs. 22 cm.
LC Call No.:   QA211.B63
Dewey No.:     512.82
Subjects:      Equations, Theory of.
Control No.:   9772835

Author:        Burnside, William Snow, 1839-(ca.) 1921.
Title:         The theory of equations: with an introduction to
                  the theory of binary algebraic forms. By William Snow
                  Burnside ... and Arthur William Panton ...
Published:     Dublin, Hodges, Figgis & co.; London, Longmans,
                  Green, & co., 1881.
Description:   xvi, 387 p. 23 cm.
Series:        Dublin University Press series
LC Call No.:   QA211.B88
Subjects:      Equations, Theory of.
               Determinants.
               Forms, Binary.
Other authors: Panton, Arthur William, d. 1906.
Control No.:   13881655

Author:        Byerly, William Elwood, b. 1849.
Title:         Syllabus of a course in the theory of equations.
Published:     Boston, Ginn, Heath, & co., 1883.
Description:   8 p. 23 cm.
LC Call No.:   QA211.B99
Notes:         Cover-title.
Subjects:      Equations, Theory of.
Control No.:   4052178

Author:        Cajori, Florian, 1859-1930.
Title:         An introduction to the modern theory of
                  equations, by Florian Cajori ...
Published:     New York, London, The Macmillan company, 1904.
Description:   ix, 239 p. 21 cm.
LC Call No.:   QA211.C13
Notes:         1969 ed. published under title: An introduction
                  to the theory of equations.
Subjects:      Equations, Theory of.
               Group theory.
Control No.:   3106907

Author:        Carlitz, Leonard.
Title:         Galois fields of certain types [by] Leonard
                  Carlitz.
Published:     Philadelphia, 1930.
Description:   1 p. l., p. 451-472. 27 cm.
LC Call No.:   QA211.C3 1930
Dewey No.:     512.82
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1930.
               "Reprint from Transactions of the American
                  mathematical society, vol. 32."
Subjects:      Equations, Theory of.
               Galois theory.
Control No.:   5939181

Author:        Chapman, C[harles] H[iram] [from old catalog]
Title:         An elementary course in theory of equations, by
                  C.H. Chapman.
Published:     New York, J. Wiley & sons, 1892.
Description:   viii, 90 p. diagr. 20 cm.
LC Call No.:   QA211.C4
Subjects:      Equations, Theory of.
Control No.:   13204228

Author:        Conkwright, Nelson Bush, 1898-
Title:         Introduction to the theory of equations.
Published:     Boston, Ginn [c1957]
Description:   viii, 213 p. diagrs. 22 cm.
LC Call No.:   QA211.C65 1957
Dewey No.:     512.82
Subjects:      Equations, Theory of.
Control No.:   7006345

Author:        Conkwright, Nelson Bush, 1898-
Title:         Introduction to the theory of equations, by
                  Nelson Bush Conkwright ...
Published:     Boston, New York [etc.] Ginn and company [c1941]
Description:   viii, 213, [1] p. diagrs. 22 cm.
LC Call No.:   QA211.C65
Dewey No.:     512.82
Subjects:      Equations, Theory of.
Control No.:   4527603

Author:        Corral, José Isaac del. [from old catalog]
Title:         Nuevos métodos para resolver ecuaciones
                  numéricas,
Published:     Madrid, A. Romo, 1912.
Description:   xxii, 303, [1] p. diagrs. 24 cm.
LC Call No.:   QA211.C7
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   7294300

Author:        Dehn, Edgar, 1890-
Title:         Algebraic equations; an introduction to the
                  theories of Lagrange and Galois, by Edgar Dehn.
Published:     New York, Columbia University Press, 1930.
Description:   xi, 208 p. 23 cm.
LC Call No.:   QA211.D4
Dewey No.:     512.82
Subjects:      Equations, Theory of.
               Group theory.
               Dynamics.
               Galois theory.
Control No.:   7341527

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         First course in the theory of equations, by
                  Leonard Eugene Dickson ...
Published:     New York, J. Wiley & sons, inc.; [etc., etc.]
                  1922.
Description:   vi, 168 p. diagrs. 22 cm.
LC Call No.:   QA211.D54 1922
ISBN:          $1.75
Subjects:      Equations, Theory of.
Control No.:   2162262

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         Elementary theory of equations, by Leonard Eugene
                  Dickson ...
Edition:       1st ed., 1st thousand.
Published:     New York, J. Wiley & sons, inc.; [etc., etc.]
                  1914.
Description:   v, 184 p. diagrs. 23 cm.
LC Call No.:   QA211.D53
ISBN:          $1.75
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Equations, Theory of.
Control No.:   745626

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         Introduction to the theory of algebraic
                  equations. By Leonard Eugene Dickson ...
Edition:       1st ed., 1st thousand.
Published:     New York, J. Wiley & sons [etc., etc.], 1903.
Description:   v, 104 p. 21 cm.
LC Call No.:   QA211.D55
               Microfilm 15980 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Equations, Theory of.
               Group theory.
               Galois theory.
Control No.:   3106747

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         New first course in the theory of equations, by
                  Leonard Eugene Dickson ...
Published:     New York, J. Wiley & sons, inc.; London, Chapman
                  & Hall, limited, 1939.
Description:   ix, 185 p. diagrs. 23 cm.
LC Call No.:   QA211.D54 1939
Dewey No.:     512.82
ISBN:          $1.75
Subjects:      Equations, Theory of.
Control No.:   274706

Author:        Dietrich, Richard. [from old catalog]
Title:         Ueber die darstellung der wurzeln der
                  algebraischen gleichungen durch unendliche reihen ...
Published:     Greifswald, Druck von F. W. Kunike, 1883.
Description:   1 p. l, 44 p. 24 cm.
LC Call No.:   QA211.D58
Subjects:      Equations, Theory of.
Control No.:   5863973

Author:        Euler, Leonhard, 1707-1783.
Title:         Drei abhandlungen über die auflösung der
                  gleichungen, von Leonhard Euler (1783, 1764, 1790) Übersetzt
                  und hrsg. von dr. Samson Breuer.
Published:     Leipzig, Akademische verlagsgesellschaft m.b.h.,
                  1928.
Description:   94 p. 19 cm.
Series:        Ostwald's klassiker der exakten wissenschaften.
                  [nr. 226]
LC Call No.:   QA211.E8
Subjects:      Equations, Theory of.
Other authors: Breuer, Samson, 1891- ed. and tr.
Control No.:   6400942

Author:        Favaro, Antonio, 1847-1922.
Title:         Notizie storico-critiche sulla costruzione delle
                  equazioni / per Antonio Favaro.
Published:     Modena : Società tipografica, 1878.
Description:   206 p., 2 folded leaves of plates : ill. ; 32
                  cm.
LC Call No.:   QA211.F38x 1878
Notes:         Includes bibliographical references.
Subjects:      Equations.
Control No.:   511478

Author:        Galois, Évariste, 1811-1832. [from old catalog]
Title:         Œuvres mathématiques, publiées en 1897;
Edition:       2. éd. rev. et corr.
Published:     Paris, Gauthier-Villars, 1951.
Description:   x, 61, 56 p. port., facsims. 25 cm.
LC Call No.:   QA211.G3 1951
Subjects:      Galois theory. [from old catalog]
Other authors: Verriest, Gustave, 1880-1951. Évariste Galois et
                  la théorie des équations algébriques. [from old catalog]
Control No.:   6038958

Author:        Garver, Raymond Joseph, 1901-
Title:         On Tschirnhausen transformations. Division
                  algebras of order sixteen.
Published:     1926.
Description:   33 l. 29 cm.
LC Call No.:   QA211.G35
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
Subjects:      Equations, Theory of.
               Transformations (Mathematics)
               Galois theory.
               Division algebras.
Other titles:  Division algebras of order sixteen.
Control No.:   3610919

Author:        Griffiths, Lois Wilfred, 1899-
Title:         Introduction to the theory of equations.
Edition:       2d ed.
Published:     New York, J. Wiley [1947]
Description:   ix, 278 p. 22 cm.
LC Call No.:   QA211.G7 1947
Dewey No.:     512.82
Notes:         "Copyright, 1945 ... under the title:
                  Determinants and systems of linear equations."
               Bibliography: p. 267.
Subjects:      Equations, Theory of.
               Determinants.
Control No.:   6474119

Author:        Hayes, Ellen, 1851-
Title:         Lessons on higher algebra / Ellen A. Hayes.
Published:     Boston : Press of F. I. Brown, 1891.
Description:   61 p. ; 22 cm.
LC Call No.:   QA211.H41
Notes:         Black cloth wrappers.
Subjects:      Equations, Theory of.
Control No.:   7728543

Author:        Hecht, Benno, 1860- [from old catalog]
Title:         Ueber die form der lösungen algebraisch
                  auflösbarer gleichungen vom primzahlgraden, insbesondere vom
                  fünften und siebenten grade ...
Published:     Königsberg in Pr., Buchdruckerei von R. Leupold,
                  1885.
Description:   2 p.l., 32 p., 2 l. 29 x 23 cm.
LC Call No.:   QA211.H44
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   8205177

Author:        Hecker, Joseph, 1859- [from old catalog]
Title:         Ueber Ruffinis beweis für die unmöglichkeit der
                  algebraischen auflösung der allgemeinen gleichung von einem
                  höheren als dem vierten grade ...
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1886.
Description:   29, [1] p., 1 l. 22 cm.
LC Call No.:   QA211.H47
               Microfilm 57983 QA
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   8673338

Author:        Hymers, J[ohn], 1803-1887. [from old catalog]
Title:         A treatise on the theory of algebraical
                  equations.
Published:     Cambridge, J. & J. j. Deighton; London, J. G. &
                  F. Rivington, 1837.
Description:   xi, [1], 196 p. diagr. on 1 fold. pl. 22 cm.
LC Call No.:   QA211.H9
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   8197179

Author:        Kaluza, Theodor, 1885- [from old catalog]
Title:         Die Tschirnhaustransformation algebraischer
                  gleichungen mit einer unbekannten ...
Published:     Königsberg I. Pr., Hartungsche buchdruckerei,
                  1907.
Description:   103, [1] p. 22 cm.
LC Call No.:   QA211.K3
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   9156844

Author:        Knabe, Helmut. [from old catalog]
Title:         Gleichungen, Ungleichungen und Mengen.
Published:     Berlin, Pädagogisches Zentrum, 19
Description:   v. 30 cm.
LC Call No.:   QA211.K53
Subjects:      Equations. [from old catalog]
               Inequalities (Mathematics) [from old catalog]
               Set theory. [from old catalog]
Other authors: Koch, Aries, [from old catalog] joint author.
Control No.:   9921654

Author:        Krzyçzanowski, Adryan, 1788-1852.
Title:         Teorya równaân wszech stopni podlug binomu
                  Newtona.
Published:     W Warszawie, W Druk. nro 646. przy Nowolipiu,
                  1816.
Description:   75 p. 23 cm.
LC Call No.:   QA211.K79
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   9930770

Author:        Lovitt, William Vernon, 1881- [from old catalog]
Title:         Elementary theory of equations,
Published:     New York, Prentice-Hall, inc., 1939.
Description:   xi p., 1 l., 237 p. diagrs. 24 cm.
LC Call No.:   QA211.L6
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   7845180

Author:        MacDuffee, Cyrus Colton, 1895-
Title:         Theory of equations.
Published:     New York, Wiley [1954]
Description:   120 p. illus. 24 cm.
LC Call No.:   QA211.M15
Dewey No.:     512.82
Subjects:      Equations, Theory of.
Control No.:   6045556

Author:        Macnie, John.
Title:         A treatise on the theory and solution of
                  algebraical equations, by John Macnie.
Published:     New York, A.S.Barnes, 1876.
Description:    x, 184 p. 22 cm.
LC Call No.:   QA211.M17
Subjects:      Equations, Theory of.
Control No.:   5855961

Author:        Maseres, Francis, 1731-1824.
Title:         A dissertation on the use of the negative sign in
                  algebra: containing a demonstration of the rules usually
                  given concerning it;
Published:     London, Printed, by S. Richardson; 1758.
Description:   2 p.l., viii, 293, [1] p. diagrs. 26 x 21 cm.
LC Call No.:   QA211.M37
Subjects:      Equations, Theory of.
               Circle-squaring.
               Machin, John, d. 1751.
               Mathematics -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9271544

Author:        Mathews, G. B. (George Ballard), 1861-1922.
Title:         Algebraic equations / by G. B. Mathews.
Published:     Cambridge, [Eng.] : University Press, 1907.
Description:   64 p. ; 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics ; no. 6
LC Call No.:   QA211.M39
Notes:         Bibliography: p. [62]-64.
Subjects:      Equations, Theory of.
               Galois theory.
Control No.:   7745463

Author:        Mathews, G. B. (George Ballard), 1861-1922.
Title:         Algebraic equations. Rev. by W.E.H. Berwick.
Published:     New York, Hafner Pub. Co. [1960]
Description:   69 p. 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics, no. 6
LC Call No.:   QA211.M39 1960
Dewey No.:     512.82
Subjects:      Equations, Theory of.
               Galois theory.
Control No.:   7020949

Author:        Matthiessen, Ludwig, 1830-1906.
Title:         Grundzüge der antiken und modernen Algebra der
                  litteralen Gleichungen, von Ludwig Matthiessen.
Edition:       2. wohlfeile Ausg.
Published:     Leipzig, B.G. Teubner, 1896.
Description:   xvi, 1001, [1] p. diagrs. 24 cm.
LC Call No.:   QA211.M43
Notes:         "Gesammtlitteratur der Algebra der Gleichungen":
                  p. [964]-1001.
Subjects:      Equations, Theory of.
Control No.:   6334084

Author:        Murphy, Robert, 1806-1843. [from old catalog]
Title:         A treatise on the theory of algebraical
                  equations.
Published:     London, Society for the diffusion of useful
                  knowledge, 1839.
Description:   xii, 171 p. 22 cm.
LC Call No.:   QA211.M9
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   7728215

Author:        Netto, Eugen, 1846-1919.
Title:         Vorlesungen über algebra, von Eugen Netto ...
                  Mit eingedruckten holzschnitten.
Published:     Leipzig, B.G. Teubner, 1896-1900.
Description:   2 v. diagrs. 25 cm.
LC Call No.:   QA211.N47
Notes:         1. Bd. I. Ganze functionen und algebraische
                  Gleichungen.--II. Numerische Auflösung der
                  Gleichungen.--III. Algebraische Lösung der Gleichungen.--2.
                  Bd. IV. Gleichungen mit mehreren Unbekannten.--V. Allgemeine
                  Theorie der algebraischen Gleichung unter Verwendung der
                  Substitutionengruppen.
Subjects:      Equations, Theory of.
               Elimination.
               Group theory.
Control No.:   8665268

Author:        Riesz, Frigyes, 1880-1956.
Title:         Les systèmes d'équations linéaires à une
                  infinité d'inconnues, par Frédéric Riesz.
Published:     Paris, Gauthier-Villars, 1913.
Description:   vi, 182 p. 26 cm.
Series:        Collection de monographies sur la théorie des
                  fonctions
LC Call No.:   QA211.R5
Subjects:      Equations.
Control No.:   7329822

Author:        Schapira, Hermann [Hirsch] 1840- [from old
                  catalog]
Title:         Darstellung der wurzeln einer allgemeinen
                  gleichung nten grades ...
Published:     Leipzig, Druck von B. G. Teubner, 1883.
Description:   2 p. l., 224 p. 23 cm.
LC Call No.:   QA211.S3
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   6331843

Author:        Spence, William.
Title:         Outlines of a theory of algebraical equations,
                  deduced from the principles of Harriott, and extended to the
                  fluxional or differential calculus, by William Spence.
Published:     London, Printed for the author by Davis &
                  Dickson, 1814.
Description:   2 p.l., 90 p. 21 cm.
LC Call No.:   QA211.S7
Subjects:      Equations, Theory of.
Control No.:   1217044

Author:        Stevenson, Robert.
Title:         A treatise on the nature and properties of
                  algebraic equations, by R. Stevenson ...
Published:     Cambridge, J. & J.J. Deighton; London, Whittaker
                  & Co., 1835.
Description:   iv, 144 p. 22 cm.
LC Call No.:   QA211.S8
Subjects:      Equations, Theory of.
Control No.:   6324858

Author:        Thomas, Joseph Miller, 1898-
Title:         Theory of equations, by Joseph Miller Thomas.
Edition:       1st ed.
Published:     New York and London, McGraw-Hill book company,
                  inc., 1938.
Description:   x, 211 p. diagrs. 21 cm.
LC Call No.:   QA211.T45
Dewey No.:     512.82
Notes:         Bibliography: p. 107.
               "Answers to exercises": p. 205-211.
Subjects:      Equations, Theory of.
Control No.:   9245258

Author:        Todhunter, I[saac], 1820-1884. [from old
                  catalog]
Title:         An elementary treatise on the theory of
                  equations,
Edition:       3d ed.
Published:     London, Macmillan and co., 1875.
Description:   vi p., 1 l., 328 p. 20 cm.
LC Call No.:   QA211.T6
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   8665310

Author:        University of Chicago. Extension division.
                  Home-study dept.
Title:         Mathematics 222 (elementary theory of equations)
                  / by Harry S. Everett.
Published:     [Chicago] : The University of Chicago, c1940.
Description:   1 p. l., 37 numb. l. : diagrs. ; 22 x 28 cm.
LC Call No.:   QA211.C5
Notes:         At head of title : The University of Chicago. 
                  Extension division.  Home-study department.
               Reproduced from type-written copy.
Subjects:      Equations, Theory of.
Other authors: Everett, Harry Scheldy, 1891-
Control No.:   9730981

Author:        Uspensky, James Victor, 1883-
Title:         Theory of equations.
Edition:       1st ed.
Published:     New York, McGraw-Hill Book Co., 1948.
Description:   vii, 353 p. diagrs. 22 cm.
LC Call No.:   QA211.U75
Dewey No.:     512.82
Subjects:      Equations, Theory of.
Control No.:   275449

Author:        Weisner, Louis, 1899-
Title:         Introduction to the theory of equations, by Louis
                  Weisner ...
Published:     New York, The Macmillan company, 1938.
Description:   ix, 188 p. 22 cm.
LC Call No.:   QA211.W4
Dewey No.:     512.82
Subjects:      Equations, Theory of.
Control No.:   3108925

Author:        Welcker, William T. [from old catalog]
Title:         Advanced algebra,
Published:     San Francisco, W. M. Hinton & co. [1880]
Description:   p. cm.
LC Call No.:   QA211.W44
               Microfilm 57984 QA
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   8666338

Author:        White, Charles E. [from old catalog]
Title:         Theory of the irreducible cases of equation...
                  and its applications in Algebra...
Published:     [n.p.] 1913-
Description:   v. cm.
LC Call No.:   QA211.W5
Control No.:   9550854

Author:        Wilshaus, Friedrich.
Title:         Ueber die algebraische auflösbarkeit der
                  gleichungen achten grades ... von Friedrich Wilshaus ...
Published:     Marburg, Universitätsbuchdruckerei(C.L. Pfeil),
                  1888.
Description:   40 p. 22 cm.
LC Call No.:   QA211.W74
Notes:         Inaug.-diss.--Marburg.
Subjects:      Equations, Theory of.
Control No.:   1217255

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         Theory and solution of algebraical equations of
                  the higher orders. By J.R. Young ...
Edition:       2d ed., enl.
Published:     London, Souter & Law, 1843.
Description:   xxiii, [1], 476 p. 22 cm.
LC Call No.:   QA211.Y7
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Equations, Theory of.
Control No.:   1217014

Author:        Brewer, Burns Winfred. [from old catalog]
Title:         A criterion for solvability by radicals,
Published:     [n. p., 1941]
Description:   cover-title, 119-126 p. 24 cm.
LC Call No.:   QA212.B7
Subjects:      Equations, Roots of. [from old catalog]
Control No.:   8794879

Author:        Critchfield, Charles L. [from old catalog]
Title:         A method for finding the roots of the equation
                  f(x)=0 where f is analytic.
Published:     [Wash., 1936]
Description:   1 v. cm.
LC Call No.:   QA212.C7
Control No.:   10482130

Author:        David, F. N. (Florence Nightingale), 1909-
Title:         Symmetric function and allied tables, by F.N.
                  David, M.G. Kendall and D.E. Barton.
Published:     Cambridge, Cambridge U.P., for the Biometrika
                  Trustees, 1966.
Description:   x, 278 p. tables. 29 cm.
LC Call No.:   QA212.D3
Dewey No.:     519
ISBN:          70/-
Notes:         Bibliography: p. 63-64.
Subjects:      Symmetric functions.
Other authors: Kendall, Maurice G. (Maurice George), 1907-
               Barton, D. E., joint author.
Other titles:  Biometrika.
Control No.:   3586693

Author:        Fedorov, Evgraf Stepanovich, 1853-1919. [from old
                  catalog]
Title:         Simmetr¯iëiìa pravil§nykh sistem figur.
Published:     1890.
Description:   146 p. 25 cm.
LC Call No.:   QA212.F42
Notes:         Romanized.
Subjects:      Symmetric functions. [from old catalog]
Control No.:   9916946

Author:        Fordemann, Adolf. [from old catalog]
Title:         Geometrische betrachtungen über algebraische
                  gleichungen ...
Published:     Jena, Druck von A. Nenenhahn, 1882.
Description:   62 p. diagrs. on fold. pl. 21 cm.
LC Call No.:   QA212.F7
Subjects:      Equations, Roots of. [from old catalog]
Control No.:   8201529

Author:        Fourier, Jean Baptiste Joseph, baron, 1768-1830.
                  [from old catalog]
Title:         Analyse des équations déterminées.
Published:     Paris, Firmin Didot frères, 1830.
Description:   p. cm.
LC Call No.:   QA212.F73 (Rare bk. Coll.)
Subjects:      Equations, Theory of. [from old catalog]
Other authors: Navier, Claude Louis Marie Henri, 1785-1836,
                  [from old catalog] ed.
Control No.:   9751077

Author:        Fourier, Jean Baptiste Joseph, baron, 1768-1830.
                  [from old catalog]
Title:         Die auflösung der bestimmten gleichungen
Published:     Leipzig, W. Engelmann, 1902.
Description:   vi. 263 p. diagr. 20 cm.
LC Call No.:   QA212.F77.
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   9604095

Author:        Frisiani, Paolo, 1795-1880. [from old catalog]
Title:         Genesi delle funzioni simetriche ed alternate,
Published:     Milano, 1844.
Description:   p. [97]-262. 24 cm.
LC Call No.:   QA212.F9
Subjects:      Symmetric functions. [from old catalog]
Control No.:   6801678

Author:        Gauss, [Karl Friedrich], 1777-1855. [from old
                  catalog]
Title:         Die vier Gauss'schen beweise für die zerlegung
                  ganzer algebraischer functionen in reelle factoren ersten
                  oder zweiten grades. (1799-1849.)
Published:     Leipzig, W. Engelmann, 1890.
Description:   81, [1] p. diagrs. on 1 pl. 20 cm.
LC Call No.:   QA212.G27
Subjects:      Algebraic functions.
               Factors (Algebra)
               Equations, Theory of.
Control No.:   10071671

Author:        Jourdain, Philip Edward Bertrand, 1879-1919,
                  [from old catalog] ed.
Title:         Rein analytischer beweis des lehrsatzes, dass
                  zwischen je zwey werthen, die ein entgegengesetztes resultat
                  gewähren, wenigstens eine reelle wurzel der gleichung
                  liege,
Published:     Leipzig, W. Engelmann, 1905.
Description:   115, [1] p. 19 cm.
LC Call No.:   QA212.J86
Subjects:      Equations, Roots of. [from old catalog]
               Functions. [from old catalog]
Other authors: Bolzano, Bernhard, 1781-1848. [from old catalog]
               Hankel, Hermann, 1839-1873. [from old catalog]
Control No.:   9148713

Author:        Leesekamp, Adolph. [from old catalog]
Title:         Ueber die theorie der algebraischen gleichungen
                  mit complexen wurzeln ...
Published:     Hannover, Druck von W. Riemschneider, 1867.
Description:   39 p. 28 cm.
LC Call No.:   QA212.L48
Subjects:      Equations, Theory of. [from old catalog]
Control No.:   8669669

Author:        Canard, N. F. (Nicolas François), ca.
                  1750-1833.
Title:         Traité élémentaire du calcul des inéquations,
                  par N. F. Canard.
Published:     Paris, Chez Bernard, 1808.
Description:   viii, 476 p., 1 l., [2] p. v fold. pl. (diagrs.)
                  3 fold. tab. 21 cm.
LC Call No.:   QA214.C3
Subjects:      Equations.
               Numerical analysis.
Other titles:  Inéquations, Calcul des.
Control No.:   8293518

Author:        Garrett, James Richard, 1917- [from old catalog]
Title:         Normal equations and resolvents in fields of
                  characteristic p
Published:     [Durham, N.C., 1951]
Description:   373-384 p. 26 cm.
LC Call No.:   QA214.G37
Subjects:      Equations. [from old catalog]
Control No.:   8393170

Author:        Hegemann, E. (Ernst), b. 1857.
Title:         Übungsbuch für die Anwendung der
                  Ausgleichungsrechung nach der Methode der kleinsten Quadrate
                  auf die praktische Geometrie / von E. Hegemann.
Edition:       2. verb. und erw. Aufl.
Published:     Berlin : Verlagsbuchhandlung Paul Parey, 1902.
Description:   vi, 169 p. : ill. ; 22 cm.
LC Call No.:   QA214.H43x 1902
Subjects:      Equations, Theory of.
Control No.:   3346266

Author:        Kreuzberg, Georg [Johann Hubert], 1871- [from old
                  catalog]
Title:         Ein beweis für die zerlegbarkeit rationaler
                  ganzer funktionen einer veränderlichen mit reellen
                  koefficienten in reelle faktoren 1. und 2. grades ...
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1896.
Description:   32, [2] p. 23 cm.
LC Call No.:   QA214.K92
Subjects:      Equations, Theory of.
               Factors (Algebra)
Control No.:   7271593

Author:        Philip, Robert Ashby.
Title:         Multifoliate cyclic equations.
Published:     Fairhaven, Mass., The Monographic Press, 1936.
Description:   [26] p. 28 x 22 cm.
Series:        His Multifoliate monographs. monograph 6
LC Call No.:   QA214.P5
Dewey No.:     512.82
Subjects:      Equations.
Other titles:  Cyclic equations.
Series Entry:  Philip, Robert Ashby. Multifoliate monographs.
                  monograph 6.
Control No.:   7838961

Author:        Abel, Niels Henrik, 1802-1829.
Title:         Abhandlung über eine besondere klasse
                  algebraisch auflösbarer gleichungen. Von N.H. Abel (1829)
                  Hrsg. von Alfred Loewy.
Published:     Leipzig, W. Engelmann, 1900.
Description:   50 p. 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 111
LC Call No.:   QA215.A14
Notes:         From Crelle's Journal für die reine und
                  angewandte mathematik, bd. 4, 1829.
Subjects:      Equations, Abelian.
Other authors: Loewy, Alfred, ed.
Series Entry:  Ostwalds Klassiker der exakten Wissenschaften ;
                  Bd. 111.
Control No.:   744797

Author:        Berger, A[lexander Frederik], 1844-1901. [from
                  old catalog]
Title:         Sur quelques relations entre les racines de
                  certaines équations du troisième degré,
Published:     Upsal, E. Berling, 1899.
Description:   3 p.l., 14 p. 29 x 22 cm.
LC Call No.:   QA215.B49
Subjects:      Equations, Cubic.
Control No.:   9602988

Author:        Hack, Franz.
Title:         Beiträge zur Anwendung der Gruppentheorie auf
                  kubische und biquadratische Gleichungen / Franz Hack.
Published:     Tübingen : H. Laupp jr., 1895.
Description:   36 p., 1 leaf ; 23 cm.
LC Call No.:   QA215.H12
Notes:         Inaug.-diss.--Tübingen.
Subjects:      Equations, Biquadratic.
Control No.:   9606509

Author:        Hargreave, Charles James, 1820-1866.
Title:         An essay on the resolution of algebraic
                  equations. By the late Charles James Hargreave ... Printed
                  for private circulation.
Published:     Dublin, Hodges, Smith and co., 1866.
Description:   xii, 122 p. 23 cm.
LC Call No.:   QA215.H3
Notes:         Preface signed: George Salmon.
Subjects:      Equations, Theory of.
Other authors: Salmon, George, 1819-1904.
Control No.:   3580345

Author:        Hutt, Eduard Johannes, 1843- [from old catalog]
Title:         Die auflösung der gleichungen vierten grades
                  durch elliptische funktionen ...
Published:     Königsberg, Druck von E. J. Dalkowski, 1870?
Description:   16 p. 27 cm.
LC Call No.:   QA215.H98
Subjects:      Equations, Biquadratic.
               Elliptic functions.
Control No.:   9137932

Author:        Klein, Felix, 1849-1925.
Uniform Title: Vorlesungen über das Ikosaeder und die
                  Auflösung der Gleichungen vom fünften Grade. English
Title:         Lectures on the icoshedron and the solution of
                  equations of the fifth degree. Translated by George Gavin
                  Morrice.
Edition:       2d and rev. ed.
Published:     New York, Dover Publications [1956]
Description:   xvi, 289 p. 21 cm.
LC Call No.:   QA215.K513 1956
Subjects:      Quintic equations.
               Icosahedra.
               Transformations (Mathematics)
Control No.:   13204210

Author:        Ku, Y. H. [from old catalog]
Title:         Note on a method of evaluating the complex roots
                  of a quartic equation.
Published:     [n.p.] 1926.
Description:   1 v. cm.
LC Call No.:   QA215.K77
Control No.:   8141448

Author:        Kuschke, Charles G. P. [from old catalog]
Title:         The Abelian equations of the tenth degree
                  irreducible in a given domain of rationality.
Published:     1914.
Description:   p. cm.
LC Call No.:   QA215.K8
Control No.:   10000024

Author:        Lloyd, Daniel Boone, 1901-
Title:         Some properties of rational quintic equations, by
                  Daniel Boone Lloyd.
Published:     Washington, The Catholic university of America
                  press, 1940.
Description:   35 p. tables. 23 cm.
LC Call No.:   QA215.L5
Dewey No.:     512.82
Notes:         Thesis--Catholic university of America, 1940.
               Bibliography: p. 35.
Subjects:      Equations, Quintic.
Control No.:   9253648

Author:        Morgenstern, Arthur, 1880-
Title:         Beiträge zur numerischen Lösung der Gleichungen
                  fünften Grades / von Arthur Morgenstern.
Published:     Halle a. S., 1907.
Description:   49, [1] p. ; 23 cm.
LC Call No.:   QA215.M8
Notes:         Lebenslauf.
               Inaug.-diss.--Friedrichs Universität.
Subjects:      Equations, Quintic.
Control No.:   9624216

Author:        Salzer, Herbert E.
Title:         Table for the solution of cubic equations [by]
                  Herbert E. Salzer, Charles H. Richards [and] Isabelle
                  Arsham.
Published:     New York, McGraw-Hill, 1958.
Description:   161 p. 21 cm.
LC Call No.:   QA215.S3
Dewey No.:     512.82
Subjects:      Equations, Cubic.
Control No.:   3583674

Author:        Siebel, Alfred. [from old catalog]
Title:         Ein beitrag zur geometrischen und algebraischen
                  auflösung der cubischen gleichungen ...
Published:     Düsseldorf, Hofbuchdr. von Voss & comp., 1866.
Description:   1 p. ., 52 p., 1 l. 9 diagr. on 2 l. 22 cm.
LC Call No.:   QA215.S5
Subjects:      Equations, Cubic.
Control No.:   9134570

Author:        Varnhorn, Mary Catherine.
Title:         Some properties of quartic functions of one
                  variable, by Mary Catherine Varnhorn.
Published:     Washington, Catholic university of America press,
                  1939.
Description:   29 p. diagrs. 23 cm.
LC Call No.:   QA215.V37 1939
Dewey No.:     512.82
Notes:         Thesis--Catholic university of America.
               Bibliographical foot-notes.
Subjects:      Equations, Quartic.
               Equations, Roots of.
Control No.:   8312167

Author:        Weill, Alexander, 1876-
Title:         Die geometrische interpretation der gleichung
                  fünften grades auf invarianten-theoretischer grundlage ...
Published:     Strassburg i.E., J. Singer, buchhandlung, 1900.
Description:   2 p. l., [7]-60 p., 1 l. col. diagrs. on 4 fold.
                  pl. 23 cm.
LC Call No.:   QA215.W42
Notes:         Inaug.-dis.--Strassburg.
               Lebenslauf.
Subjects:      Equations, Quintic.
Control No.:   6328175

Author:        Wolfe, Clyde Lynne Earle, 1885- [from old
                  catalog]
Title:         On the indeterminate cubic equation x>3 + Dy>3 +
                  D>2z>2 - 3Dxyz = 1,
Published:     [Berkley, Calif., 1923]
Description:   p. [359]-369. 28 cm.
LC Call No.:   QA215.W65 1919
Subjects:      Equations, Cubic.
Control No.:   6856738

Author:        Adamuccio, Antonio, 1761-ca. 1830. [from old
                  catalog]
Title:         Nuovo metodo generale per l'annichilazione di due
                  termini nell'equazioni.
Published:     Napoli, 1786.
Description:   62 p. 19 cm.
LC Call No.:   QA218.A33
Subjects:      Equations -- Numerical solutions. [from old
                  catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   8511046

Author:        Bryns, J. Oliver. [from old catalog]
Title:         A solution of the general equation of the nth
                  degree ...
Published:     St. Paul, J. O. Byrns, 1890.
Description:   24 p. 13 x 17 cm.
LC Call No.:   QA218.B99
Subjects:      Equations -- Numerical solutions. [from old
                  catalog]
Control No.:   6792992

Author:        Buchanan, L. A. (Louis Alexander)
Title:         The algebraic solution of equations of any
                  degree; a novel, simple and direct method for the solution of
                  equations of the nth degree, by L.A. Buchanan ... and J.
                  Lewis André ...
Published:     San Francisco, Cal., Pub. for the authors by the
                  Whitaker & Ray company, 1899.
Description:   iv, 61 p. 19 cm.
LC Call No.:   QA218.B9
Subjects:      Equations -- Numerical solutions.
Other authors: André, J. Lewis (John Lewis), 1879- joint
                  author.
Control No.:   3582478

Author:        Buck, John. [from old catalog]
Title:         A new, general, and algebraical solution of the
                  higher orders of equations, with solutions of equations to
                  the tenth degree inclusive.
Published:     London, Carpenter and son; Cambridge; Deighton
                  and sons; [etc., etc.] 1823.
Description:   xi, [1], 95 p. 21 cm.
LC Call No.:   QA218.B92
Subjects:      Equations -- Numerical solutions. [from old
                  catalog]
Control No.:   7729466

Author:        Clowes, T. [from old catalog]
Title:         The root extractor.
Published:     Hempstead, N.Y., 1831.
Description:   68 p. 18 cm.
LC Call No.:   QA218.C64
Control No.:   9548591

Author:        Duncan, David B. (David Beattie)
Title:         On the solution of normal equations and related
                  topics, by David B. Duncan ... and John F. Kenney ...
Published:     [Ann Arbor, Mich., Lithoprinted by Edwards
                  brothers, inc.] 1946.
Description:   2 p.l., 35 p. 28 x 22 cm.
LC Call No.:   QA218.D8
Notes:         Bibliography: p. 35.
Subjects:      Equations -- Numerical solutions.
               Matrices.
Other authors: Kenney, John F. (John Francis), 1897-, joint
                  author.
Control No.:   2636693

Author:        Katz, David. [from old catalog]
Title:         Pocket tables for cubics; a systematic method for
                  algebraic treatment of cubic equations...
Published:     [South Milwaukee, Wis.] c1933.
Description:   1 v. cm.
LC Call No.:   QA218.K3
Control No.:   9546936

Author:        Lagrange, J. L. (Joseph Louis), 1736-1813.
Title:         Traité de la résolution des équations
                  numériques de tous les degrés : avec des notes sur
                  plusieurs points de la théorie des équations algébriques /
                  par J.L. Lagrange.
Edition:       Nouv. éd., rev. et augm. / par l'auteur.
Published:     Paris : Chez Courcier, 1808.
Description:   xii, 311, [1] p. ; 26 cm.
LC Call No.:   QA218.L17 1808
Notes:         First published Paris, 1798 under title: De la
                  résolution des équations numériques de tous les degrés.
               Errata: p. [1] at end.
               NUC pre-1956 NL 0032585
               LC copy includes marginalia. DLC
Subjects:      Equations -- Numerical solutions.
Other authors: Lagrange, J. L. (Joseph Louis), 1736-1813. De la
                  résolution des équations numériques de tous les degrés.
Control No.:   12434369

Author:        Lagrange, J. L. (Joseph Louis), 1736-1813.
Title:         Traité de la résolution des équations
                  numériques de tous les degrés, aved des notes sur plusieurs
                  points de la théorie des équatins algébriques. Par J. L.
                  Lagrange.
Edition:       3. éd. conforme à celle de 1808, et précédée
                  d'une analyse de l'ouvrage, par M. Poinsot.
Published:     Paris, Bachelier, 1826.
Description:   xxviii, 314 p., 1 l. 27 x 21 cm.
LC Call No.:   QA218.L3 1826
Subjects:      Equations -- Numerical solutions.
Other authors: Poinsot, Louis, 1777-1859.
Control No.:   7728452

Author:        Lagrange, Joseph Louis, comte, 1736-1813.
Title:         De la résolution des équations numériques de
                  tous les degrés; par J. L. Lagrange ...
Published:     Paris, Duprat, an VI [1798?]
Description:   1 p.l., [v]-viii, 268 p. 25 cm.
LC Call No.:   QA218.L3 1798
Dewey No.:     512.82
Notes:         Subsequently published under title: Traité de la
                  resolution des équations numériques de tous les degrés.
Subjects:      Equations -- Numerical solutions.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   3581287

Author:        Lefébure de Fourcy, M. (Louis Etienne),
                  1785-1869.
Title:         Théorie du plus grand commun diviseur
                  algébrique et de l'élimination entre deux équations à
                  deux inconnues / par M. Lefébure de Fourcy.
Published:     Paris : Bachelier, 1827.
Description:   iv, 45 p. ; 22 cm.
LC Call No.:   QA218.L43x 1827
Subjects:      Equations -- Numerical solutions.
Control No.:   4764700

Author:        Lockhart, James, 1763-1852.
Title:         Resolution of equations. By James Lockhart ...
                  Part the first.
Published:     Oxford, Printed for the author, 1837.
Description:   vi, 46 p. 28 X 22 cm.
LC Call No.:   QA218.L84
Notes:         Title vignette.
Subjects:      Equations -- Numerical solutions.
Control No.:   5857169

Author:        Lockhart, James, 1763-1852. [from old catalog]
Title:         The nature of the roots of numerical equations.
Published:     London, Printed by C. and J. Adlard, 1850.
Description:   iv, [5]-20 p. 21 cm.
LC Call No.:   QA218.L82
Subjects:      Equations, Roots of. [from old catalog]
Control No.:   10070698

Author:        Lockhart, James, 1763-1852. [from old catalog]
Title:         Resolution of two equations.
Published:     Oxford, Printed for the author, 1839.
Description:   10 p., 1 l. 28 x 22 cm.
LC Call No.:   QA218.L84
Subjects:      Equations -- Numerical solutions. [from old
                  catalog]
Control No.:   8198174

Author:        Lookhart, James, 1763-1852.
Title:         A method of approximating towards the roots of
                  cubic equations belonging to the irreducible case, by James
                  Lockhart.
Published:     London, Printed for the author, 1813.
Description:   vi, [7]-87 p. diagr. 25 cm.
LC Call No.:   QA218.L8
Subjects:      Equations -- Numerical solutions.
               Equations, Cubic.
Control No.:   7728804

Author:        McGinnis, M. A. (Michael Angelo)
Title:         The universal solution for numerical and literal
                  equations; by which the roots of equations of all degrees can
                  be expressed in terms of their coefficients; by M.A.
                  McGinnis.
Published:     Kansas City, Mo., The Mathematical book company,
                  1900.
Description:   vi p., 1 l., 195 p. 19 cm.
LC Call No.:   QA218.M2
Subjects:      Equations -- Numerical solutions.
               Equations, Theory of.
Control No.:   2160901

Author:        Montague, Mich. Educational Research
                  Laboratories. [from old catalog]
Title:         The multitrig solution of algebraic equations; a
                  progress report concerning the astronomical validation of the
                  correlation between electromagnetism and gravitation.
Published:     Montague, 1954.
Description:   24 l. 28 cm.
LC Call No.:   QA218.M6
Subjects:      Trigonometrical functions. [from old catalog]
               Equations -- Numerical solutions. [from old
                  catalog]
Other authors: Beyers, Meredith, 1899- [from old catalog]
Control No.:   9400825

Author:        Pinet, Henri.
Title:         Mémoire sur une nouvelle méthode pour la
                  résolution des équations numériques / par Henri Pinet ;
                  suivi d'un appendice donnant le détail des opérations par
                  Emile Krauss.
Published:     Paris : Librairie Nony, 1899.
Description:   45 p. ; 29 cm.
LC Call No.:   QA218.P56 1899
Notes:         BN CXXXVII, column 928
               NUC pre-1956 NP 0373947
Subjects:      Equations -- Numerical solutions.
Other authors: Krauss, Emile.
Control No.:   12531442

Author:        Pratt, Orson, 1811-1881.
Title:         New and easy method of solution of the cubic and
                  biquadratic equations, embracing several new formulas,
                  greatly simplifying this department of mathematical science.
                  Designed as a sequel to the elements of algebra, and for the
                  use of schools and academies. By Orson Pratt, sen.
Published:     London, Longmans, Green, Reader, and Dyer;
                  Liverpool, B. Young, 1866.
Description:   xvi, 151 p. 22 cm.
LC Call No.:   QA218.P9
Subjects:      Equations -- Numerical solutions.
Control No.:   10071364

Author:        Rutherford, William, 1798-1871. [from old
                  catalog]
Title:         The complete solution of numerical equations,
Published:     London G. Bell; 1849.
Description:   28 p. 27 x 21 cm.
LC Call No.:   QA218.R9
Subjects:      Equations -- Numerical solutions. [from old
                  catalog]
Control No.:   9602034

Author:        Aley, Robert J. (Robert Judson), 1863-1935.
Title:         Graphs, by Robert J. Aley ...
Published:     Boston, D.C. Heath & co., 1902.
Description:   v, 21 p. diagrs. 20 cm.
Series:        Heath's mathematical monographs, no. 6
LC Call No.:   QA219.A38
Subjects:      Algebra -- Graphic methods.
Series Entry:  Heath's mathematical monographs ; no. 6.
Control No.:   1689209

Author:        Auerbach, Matilda. [from old catalog]
Title:         An elementary course in graphic mathematics,
Published:     Boston, New York [etc.] Allyn and Bacon [c1910]
Description:   3 p. l., 54 p. diagrs. 19 cm.
LC Call No.:   QA219.A8
Subjects:      Graphic methods.
               Albegra -- Graphic methods.
Control No.:   10097119

Author:        Baker, Arthur Latham, 1853-1934.
Title:         Graphic algebra. An elementary text book for
                  college students. Graphs. By Arthur Latham Baker ...
Published:     Rochester, N.Y. Scrantom, Wetmore & co. [1892]
Description:   vi p., 1 l., 73 p. diagr. on 1 fold. pl. 19 cm.
LC Call No.:   QA219.B1
Subjects:      Algebra -- Graphic methods.
Control No.:   272522

Author:        Bixby, William H[erbert], 1849- [from old
                  catalog]
Title:         Graphical method for finding readily the real
                  roots of numerical equations of any degree if containing but
                  one variable.
Published:     West Point, N.Y., 1879.
Description:   16 p. diagr. 23 cm.
LC Call No.:   QA219.B6
Subjects:      Algebra -- Graphic methods.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
Control No.:   6324859

Author:        Brown, Stimson Joseph, 1854- [from old catalog]
Title:         Analytic geometry; or, Graphic algebra, an
                  elementary treatise prepared for the use of the midshipmen at
                  the United States Naval academy,
Published:     [Baltimore, Md., The Lord Baltimore press] 1907.
Description:   p. cm.
LC Call No.:   QA219.B87
Subjects:      Algebra -- Graphic methods.
Control No.:   9618783

Author:        Bürklen, [Otto Th.], 1856- [from old catalog]
Title:         Graphisches rechnen und graphische darstellungen
                  im mathematikunterricht ...
Published:     Gmünd, Buchdruckerei von Scharpf & Kraus, 1899.
Description:   1 p.l., 58 p. diagrs. 27 x 22 cm.
LC Call No.:   QA219.B92
Subjects:      Algebra -- Graphic methods.
Other authors: Gmünd. K. Realgymnasium. [from old catalog]
Control No.:   9614666

Author:        Cremona, Luigi, 1830-1903.
Title:         Elemente des graphischen calculs. Von dr. Luigi
                  Cremona ... Autorisierte deutsch ausg. Unter mitwirkung des
                  verfassers übertragen von Maximilian Curtze. Mit 131 in den
                  text gedruckten holzschnitten.
Published:     Leipzig, Quandt & Händel, 1875.
Description:   viii, 105, [3] p. diagrs. 23 cm.
LC Call No.:   QA219.C9
Dewey No.:     512 19
Notes:         Two pages following p. 105 contain
                  advertisements.
Subjects:      Algebra -- Graphic methods.
               Center of mass.
Other authors: Curtze, E. L. W. M. (Ernst Ludwig Wilhelm
                  Maximilian), 1837-1903, tr.
Control No.:   4052500

Author:        Cremona, Luigi, 1839-1903. [from old catalog]
Title:         Elemente des grapjischen calculs.
Published:     Leipzig, Quandt & Händel, 1875.
Description:   viii, 105, [3] p. diagrs. 23 cm.
LC Call No.:   QA219.C9
Subjects:      Algebra -- Graphic methods.
               Center of mass.
Other authors: Curtze, Maximilian i. e. Ernst Ludwig Wilhelm
                  Maximilian, 1837- tr. [from old catalog]
Control No.:   9609496

Author:        Dehn, Edgar, 1890- [from old catalog]
Title:         Algebraic charts.
Published:     New York, Nomographic press, 1930.
Description:   p. cm.
LC Call No.:   QA219.D4
Subjects:      Algebra -- Graphic methods.
Control No.:   8281707

Author:        Duncan, R. Howard.
Title:         Practical curve tracing with chapters on
                  differentiation and integration, by R. Howard Duncan ... With
                  diagrams.
Published:     London, New York [etc.], Longmans, Green and co.,
                  1910.
Description:   vi p., 1 l., 137 p. diagrs. 22 cm.
LC Call No.:   QA219.D8
Subjects:      Algebra -- Graphic methods.
               Curves, Plane.
Control No.:   745430

Author:        Favaro, Antonio, 1847-1922. [from old catalog]
Title:         Sulle prime operazioni del calcolo grafico
Published:     Venezia, Tipografia Grimaldo e c., 1872.
Description:   1 p.l., 74 p., 1 l. diagrs. on 2 fold. pl. 22
                  cm.
LC Call No.:   QA219.F27
Subjects:      Algebra -- Graphic methods.
Control No.:   6803269

Author:        Frost, Percival, 1817-1898. [from old catalog]
Title:         An elementary treatise on curve tracing,
Edition:       2d ed.
Published:     London and New York, Macmillan and co., 1892.
Description:   xvi, 184 p. fold. diagrs. 23 cm.
LC Call No.:   QA219.F8 1892
Subjects:      Graphic methods. [from old catalog]
               Curves, Plane. [from old catalog]
Other titles:  Curve tracing.
Control No.:   10223487

Author:        Gibson, George A. (George Alexander), 1858-1930.
Title:         An elementary treatise on graphs, by George A.
                  Gibson ...
Published:     London, Macmillan and co., limited ; New York,
                  The Macmillan company, 1905.
Description:   x, 183 p. tables, diagrs. 19 cm.
LC Call No.:   QA219.G44
Notes:         First edition, 1904; reprinted 1905.
Subjects:      Algebra -- Graphic methods.
Control No.:   6334395

Author:        Newson, H. B. (Henry Byron), 1860-1910.
Title:         Graphic algebra for secondary schools, by H.B.
                  Newson ...
Published:     Boston, New York [etc.] Ginn & company [1905]
Description:   iii, 19 p. diagrs. 19 cm.
LC Call No.:   QA219.N55
Subjects:      Algebra -- Graphic methods.
Control No.:   3579489

Author:        Nipher, Francis E. (Francis Eugene), b. 1847.
Title:         An introduction to graphical algebra : for the
                  use of high schools / by Francis E. Nipher.
Published:     New York : H. Holt, 1898.
Description:   iv, 61 p. : ill. ; 19 cm.
LC Call No.:   QA219.N7
Subjects:      Algebra -- Graphic methods.
Control No.:   10070350

Author:        Phillips, Andrew W. (Andrew Wheeler), 1844-1915.
Title:         Graphic algebra ; or, Geometrical interpretation
                  of the theory of equations of one unknown quantity. By A. W.
                  Phillips and W. Beebe.
Published:     New York, H. Holt and company, 1882.
Description:   1 p. l., 154 p. incl. diagr. 23 cm.
LC Call No.:   QA219.P5
Subjects:      Algebra -- Graphic methods.
Control No.:   6791983

Author:        Schultze, Arthur, 1861-
Title:         Graphic algebra, by Arthur Schultze ...
Published:     New York, The Macmillan company, 1908.
Description:   viii p., 1 l., 93 p. incl. tables, diagrs. 20
                  cm.
LC Call No.:   QA219.S38
Notes:         With answers.
Subjects:      Algebra -- Graphic methods.
Control No.:   273024

Author:        Short, Robert L. (Robert Louis), b. 1866.
Title:         Supplementary algebra / by R. L. Short.
Published:     Boston : D. C. Heath, 1905.
Description:   45 p. : ill. ; 20 cm.
Series:        Heath's mathematical monographs ; no. 10
LC Call No.:   QA219.S55
Subjects:      Algebra -- Graphic methods.
               Algebra -- Problems, exercises, etc.
Control No.:   7266997

Author:        Turner, G. C. (George Charles)
Title:         Graphics applied to arithmetic, mensuration and
                  statics, by G.C. Turner ...
Published:     London, Macmillan and co., limited, 1908.
Description:   viii p., 1 l., 388 p. diagrs. 19 cm.
LC Call No.:   QA219.T8
Subjects:      Graphic methods.
Control No.:   273091

Author:        Allen, Deryck Norman de Garrs.
Title:         Relaxation methods.
Published:     New York, McGraw-Hill, 1954.
Description:   257 p. illus. 24 cm.
LC Call No.:   QA225.A5
Dewey No.:     512.8
Subjects:      Relaxation methods (Mathematics)
Control No.:   7438113

Author:        Shaw, F. S. (Frederick S.)
Title:         An introduction to relaxation methods.
Published:     [New York] Dover Publications [1953]
Description:   396 p. illus. 21 cm.
LC Call No.:   QA225.S4
Dewey No.:     512.8
Notes:         Includes bibliography.
Subjects:      Relaxation methods (Mathematics)
Other titles:  Relaxation methods.
Control No.:   276150

Title:         Addition and subtraction of decimals
Description:   p. cm.
LC Call No.:   QA242.A3
Control No.:   6721879

Author:        Bork, Heinrich Carl Theodor, 1849-
Title:         Untersuchungen über das verhalten zweier
                  primzahlen in bezug auf ihren quadritschen restcharakter ...
Published:     Halle, 1889.
Description:   21, [2] p. diagrs. on 1 pl. 31 cm.
LC Call No.:   QA242.B73
Notes:         Inaug.-diss.--Halle.
               Lebenslauf.
Subjects:      Congruences and residues.
Control No.:   5856277

Author:        Brixey, John Clark, 1904-
Title:         The null forms Axp2s+Byp2s+Czp2s+Dup2s
                  which represent all integers / by John Clark Brixey.
Published:     [Chicago], 1937.
Description:   ii leaves, 55 p. ; 24 cm.
LC Call No.:   QA242.B8 1936
Notes:         Vita.
               Lithoprinted.
               Thesis (Ph. D.)--University of Chicago, 1936.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Forms, Quadratic.
               Diophantine analysis.
Control No.:   5965814

Author:        Busche, Edmund, 1861-
Title:         Ueber eine Beweismethode in der Zahlentheorie und
                  einige Anwendungen derselben : insbesondere auf das
                  Reciprocitätsgesetz in der Theorie der quadratischen Reste /
                  Edmund Busche.
Published:     Göttingen : Druck der Dietrich'schen
                  univ.-buchdr., 1883.
Description:   59 p. ; 22 cm.
LC Call No.:   QA242.B97
Notes:         Lebenslauf.
               Inaug.-diss.--Universität Göttingen.
Subjects:      Number theory.
Control No.:   6792911

Author:        Caris, Perry Aquila, 1890-
Title:         A solution of the quadratic congruence, modulo p,
                  p = 8n+1, n Odd ... [by] Perry A. Caris ...
Published:     Philadelphia, 1925.
Description:   1 p. l., p. [294]-297. 26 cm.
LC Call No.:   QA242.C25 1925
Notes:         Thesis (Ph. D.)--University of Pennsylvania.
               "Reprinted from the American mathematical
                  monthly, vol. XXXII, no. 6, June-July, 1925."
Subjects:      Congruences and residues.
Other titles:  The quadratic congruence, modulo p, p = 8n+1, n
                  Odd.
Control No.:   9670029

Author:        Carmichael, R. D. (Robert Daniel), 1879-1967.
Title:         Diophantine analysis, by Robert D. Carmichael
                  ...
Edition:       1st ed. 1st thousand.
Published:     New York, John Wiley & sons, inc.; [etc., etc.]
                  1915.
Description:   vi, 118 p. 24 cm.
Series:        Mathematical monographs, ed. by M. Merriman and
                  R.S. Woodward. no. 16
LC Call No.:   QA242.C3
ISBN:          $1.25
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Diophantine analysis.
Series Entry:  Mathematical monographs (New York, N.Y.) ; no.
                  16.
Control No.:   3580276

Author:        Chebyshev, P. L. (Pafnutiæi L§vovich),
                  1821-1894.
Uniform Title: Teoriëiìa sravneniæi
Title:         Teor¯iëiìa sravnen¯iæi / sochinen¯ie P.L.
                  Chebysheva.
Edition:       2-e izd.
Published:     Sanktpeterburg : Tip. T-va "Obshchestvennaëiìa
                  pol§za", 1879.
Description:   viii, iii, iii, 223, 26 p. ; 23 cm.
LC Call No.:   QA242.C528 1879
Subjects:      Congruences and residues.
Control No.:   2446502

Author:        Cicioni, G. C. (Giulio C.)
Title:         La divisibilità dei numeri e la teoria delle
                  decimali periodiche / per G.C. Cicioni.
Published:     Perugia : Tip. Perugina, 1908.
Description:   150 p. ; 20 cm.
LC Call No.:   QA242.C52x 1908
Subjects:      Division.
               Fractions, Decimal.
Control No.:   4291723

Author:        Cooper, Albert Everett, 1893-1960.
Title:         A topical history of the theory of quadratic
                  residues.
Published:     1926.
Description:   98 l. 29 cm.
LC Call No.:   QA242.C66
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Includes bibliographical references.
Subjects:      Congruences and residues -- History.
Control No.:   1765089

Author:        Cunningham, Allan, 1842- comp.
Title:         A binary canon, showing residues of powers of 2
                  for divisors under 1000, and indices to residues. Comp. by
                  Lt.-Col. Allan Cunningham ...
Published:     London [Printed by C.F. Hodgson & son] 1900.
Description:   2 p.l., viii, 172 p. 29 cm.
LC Call No.:   QA242.C8
Subjects:      Congruences and residues.
               Mathematics -- Tables.
Control No.:   4053128

Author:        Desmarest, E. [from old catalog]
Title:         Théorie des nombres.
Published:     Paris, L. Hachette et cie, 1852.
Description:   ix, [1], 312 p. 28 x 22 cm.
LC Call No.:   QA242.D4
Subjects:      Diophantine analysis. [from old catalog]
Control No.:   6436452

Author:        Eichenberg, Siegmund, 1862- [from old catalog]
Title:         Ueber das quadratische reciprocitätsgesetz und
                  einige quadratische zerfällungen der primzahlen ...
Published:     Berlin, Druck von Marschner & Stephan, 1886.
Description:   54, [2] p. 21 cm.
LC Call No.:   QA242.E34
Subjects:      Congruences and residues. [from old catalog]
Control No.:   9602987

Author:        Funkenbusch, William. [from old catalog]
Title:         The factorial function
Published:     [Houghton, Mich.] c1944.
Description:   4 p. l, 21 numb. l. diagrs. 29 x 23 cm.
LC Call No.:   QA242.F8
Subjects:      Number theory.
Control No.:   6930727

Author:        Gauss, Carl Friedrich, 1777-1855.
Title:         Sechs beweise des fundamentaltheorems über
                  quadratische reste, von Carl Freidrich Gauss. Hrsg. von Eugen
                  Netto.
Published:     Leipzig, W. Engelmann, 1901.
Description:   111, [1] p. 20 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften,
                  nr. 122
LC Call No.:   QA242.G25
Notes:         "Beweise" I-II published in Disquisitiones
                  arithmeticae, Leipzig, 1801; III in Commentationes Societatis
                  regiae scientiarum gottingensis, vol. XVI, 1808; IV-VI in
                  Commentationes Societatis regiae scientiarum gottingensis
                  recentiores, vol. I, 1811, and vol. IV, 1818.
Subjects:      Congruences and residues.
Other authors: Netto, Eugen, 1846-1919, ed.
Control No.:   9134454

Author:        Hennekeler, Gysbert van. [from old catalog]
Title:         Verhandeling over de primitieve wortels van alle
                  getallen, en hunne toepassing op de decimale breuken ...
Published:     Leyden, E. J. Brill, 1855.
Description:   1 p.l., xv p., 1 l., 210 p. 24 cm.
LC Call No.:   QA242.H5
Subjects:      Congruences and residues. [from old catalog]
               Decimal fractions.
Control No.:   9605228

Author:        Jacobsthal, Ernst Erich, 1882-
Title:         Anwendungen einer Formel aus der Theorie der
                  quadratischen Reste ...
Published:     [Göttingen, Univ.-Buchdruckerei von W.F.
                  Kästner] 1906.
Description:   39, [1] p. 22 cm.
LC Call No.:   QA242.J2
Notes:         Lebenslauf.
               Inaug.-diss.--Berlin.
Subjects:      Congruences and residues
Other titles:  [Pamphlets. Mathematics. 1841-1906] v. 10.
Control No.:   6807587

Author:        Karpinski, Louis Charles, 1878-1956.
Title:         Über die Verteilungen der quadratischen Reste.
Published:     Strassburg i E., Druck der "Strassburger neueste
                  Nachrichten," 1903.
Description:   21 p. 22 cm.
LC Call No.:   QA242.K18
Notes:         Lebenslauf.
               Inaug.-diss.--Strassburg.
Subjects:      Congruences and residues
Other authors: Karpinski, Louis Charles, 1878-1956. Mathematical
                  pamphlets.
Control No.:   5863585

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Recherches d'analyse indéterminée.
Published:     [Paris, 1785]
Description:   465-559 p. 26 cm.
LC Call No.:   QA242.L53
Subjects:      Diophantine analysis.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9136341

Author:        Leman, Alfred Karl Hugo, 1855- [from old
                  catalog]
Title:         Vom periodischen dezimalbruch zur zahlentheorie,
Published:     Leipzig und Berlin, G. B. Teubner, 1916.
Description:   iv p., 1 l., 59, [1] p. front. (port.) 19 cm.
LC Call No.:   QA242.L6
Subjects:      Decimal fractions.
               Number theory.
Control No.:   6369113

Author:        Martin, Artemas, 1835- [from old catalog]
Title:         About biquadrate numbers whose sum is a
                  biquadrate number.
Published:     Washington, D.C., The author, 1896.
Description:   p. cm.
LC Call No.:   QA242.M38
Notes:         ca7-3193
Subjects:      Diophantine analysis. [from old catalog]
Control No.:   9615777

Author:        Martin, Artemas, 1835- [from old catalog]
Title:         About biquadrate numbers whose sum is a
                  biquadrate number.
Published:     Washington, D.C., The author, 1896.
Description:   p. cm.
LC Call No.:   QA242.M38
Notes:         ca7-3193
Subjects:      Diophantine analysis. [from old catalog]
Control No.:   9615777

Author:        Martin, Artemas, 1835- [from old catalog]
Title:         About cube numbers whose sum is a cube number.
Published:     Washington, D.C., The author, 1896.
Description:   p. cm.
LC Call No.:   QA242.M39
Subjects:      Diophantine analysis. [from old catalog]
Control No.:   6332261

Author:        Martin, Artemas, 1835- [from old catalog]
Title:         Notes about square numbers whose sum is either a
                  square or the sum of other squares.
Published:     Washington, D.C., The author, 1897.
Description:   1 p.l., [209]-220 p. 31 x 24 cm.
LC Call No.:   QA242.M395
Subjects:      Diophantine analysis. [from old catalog]
Control No.:   8205582

Author:        Matteson, James, d. 1876.
Title:         A collection of Diophantine problems with
                  solutions. Comp. by James Matteson.
Published:     Washington, A. Martin, 1888.
Description:   2 p. l., 24 p. 24 cm.
LC Call No.:   QA242.M43
Notes:         Introductory note signed:  Artemas Martin.
Subjects:      Diophantine analysis
Other authors: Martin, Artemas, 1835-1918.
Control No.:   5859286

Author:        Meyer, Georg. [from old catalog]
Title:         Zur theorie der quadratischen und kubischen reste
                  ...
Published:     Greifswald, Druck von F. W. Kunike [1879]
Description:   1 p.l., 49 p. 24 cm.
LC Call No.:   QA242.M62
Subjects:      Congruences and residues. [from old catalog]
Control No.:   7264704

Author:        Minkowski, H. (Hermann), 1864-1909.
Title:         Diophantische approximationen; eine einführung
                  in die zahlentheorie, von Hermann Minkowski ... Mit 82 in den
                  text gedruckten figuren.
Published:     Leipzig, B.G. Teubner, 1907.
Description:   viii, 235, [1] p. diagrs. 23 cm.
Series:        Mathematische vorlesungen an der Universität
                  Göttingen. II
LC Call No.:   QA242.M7
Subjects:      Diophantine approximation.
               Number theory.
Series Entry:  Mathematische Vorlesungen an der Universität
                  Göttingen ; 2.
Control No.:   273156

Author:        Moraes de Almeida, Carlos Augusto, b. 1843. [from
                  old catalog]
Title:         Estudo sobre algumas propriedades dos numeros e
                  sua applicação á analyse indeterminada.
Published:     Lisboa, Typ. da Academia Real das Sciencias,
                  1874.
Description:   43 p. 29 cm.
LC Call No.:   QA242.M82
Subjects:      Congruences and residues. [from old catalog]
               Diophantine analysis. [from old catalog]
Control No.:   8669444

Author:        Niven, Ivan Morton, 1915-
Title:         Diophantine approximations.
Published:     New York, Interscience Publishers [1963]
Description:   vi, 68 p. diagr. 24 cm.
Series:        The ninth annual series of Earle Raymond Hedrick
                  lectures of the Mathematical Association of America
               Interscience tracts in pure and applied
                  mathematics, no. 14
LC Call No.:   QA242.N55
Dewey No.:     512.23
Notes:         Bibliography: p. 63-65.
Subjects:      Diophantine analysis.
Series Entry:  Annual series of Earle Raymond Hedrick lectures
                  of the Mathematical Association of America ; 9th.
Control No.:   1223210

Author:        Peck, Leslie G., 1922- [from old catalog]
Title:         Diophantine equations in algebraic number
                  fields.
Published:     [n. p., 1949]
Description:   387-402 p. 24 cm.
LC Call No.:   QA242.P4
Subjects:      Diophantine analysis. [from old catalog]
               Number theory.
Control No.:   8381154

Author:        Plateau, J[oseph Antoine Ferdinand], 1801-1883.
                  [from old catalog]
Title:         Sur une récréation arithmétique (deuxième
                  note);
Published:     Bruxelles, F. Hayez, imprimeur, 1874.
Description:   10 p. 22 cm.
LC Call No.:   QA242.P71
Subjects:      Mathematical recreations. [from old catalog]
               Numbers, Divisibility of. [from old catalog]
Control No.:   8669443

Author:        Pratt, L. E. [from old catalog]
Title:         On the divisor of n>r--n and Bernoulli's
                  numbers.
Published:     [Tecumseh? Neb., 189-?]
Description:   6 p. cm.
LC Call No.:   QA242.P91
Control No.:   7725507

Author:        Uspensky, James Victor, 1883- [from old catalog]
Title:         Nëiìekotoryëiìa prilozhen¯iëiìa  neprerynykh
                  parametrov.
Published:     1910.
Description:   vi, 214 p. diagrs. 27 cm.
LC Call No.:   QA242.U76
Notes:         Romanized.
Subjects:      Number theory.
Control No.:   7898670

Author:        Whitford, Edward Everett, 1864- [from old
                  catalog]
Title:         The Pell equation,
Published:     New York, E. E. Whitford, 1912.
Description:   iv, 193 p. diagrs. 24 cm.
LC Call No.:   QA242.W6
               Microfilm 71275 QA
Subjects:      Pell's equation.
Control No.:   6357652

Author:        Wright, J. M. F. (John Martin Frederick)
Title:         An elementary treatise on the theory of numbers;
Published:     Cambridge [Eng.] W. P. Grant, 1831.
Description:   3 p. l., 126 p. incl. tab. 22 cm.
LC Call No.:   QA242.W95
Subjects:      Number theory.
Control No.:   5860081

Author:        Zuschlag, Heinrich. [from old catalog]
Title:         Diophantische gleichungen,
Edition:       3. aufl.
Published:     Berlin-Schöneberg, Mentor-verlag, gesellschaft
                  mit beschränkter haftung [192-]
Description:   viii, 51 p. 23 x 12 cm.
LC Call No.:   QA242.Z8
Subjects:      Diophantine analysis. [from old catalog]
Control No.:   10170926

Author:        Bauer, J. Peter (Johann Peter), 1871-
Title:         Bestimmung des Grenzwertes für das Produkt der
                  Hauptkoefficienten in reducierten quadratischen quaternären
                  Formen / von J. Peter Bauer.
Published:     Bonn : C. Georgi, 1894.
Description:   29, [1] p., 1 leaf ; 22 cm.
LC Call No.:   QA243.B34
Notes:         Lebenslauf.
               Inaug.-diss.--Bonn.
Subjects:      Forms, Quadratic.
Control No.:   6810304

Author:        Beinhorn, Johannes Dietrich Hermann, b. 1873.
Title:         Zur theorie der quadratischen formen ...
Published:     Marburg, 1900.
Description:   42, [2] p. 22 cm.
LC Call No.:   QA243.B42
Notes:         Inaug.-dis.--Marburg.
               Lebenslauf.
Subjects:      Forms, Quadratic.
Control No.:   1689166

Author:        Borisov, Evgen¯iæi, b. 1854.
Uniform Title: O privedenii polozhitel§nykh troæinichnykh
                  kvadratichnykh form po sposobu Zellinga
Title:         O privedeni¯ii polozhitel§nykh troæinichnykh
                  kvadratichnykh form po sposobu Zellinga : s prilozhen¯iem
                  tabliëtìsy privedennykh form dlëiìa vsëiìekh
                  oprëiìedeliteleæi ot 1 do 200 / razsuzhden¯ie Evgen¯iëiìa
                  Borisova.
Published:     Sanktpeterburg : Tip. Imp. akadem¯ii nauk, 1890.
Description:   viii, 116 p. ; 25 cm.
LC Call No.:   QA243.B67 1890
Notes:         Originally presented as the author's thesis
                  (master's)
               Bibliography: p. [iii]-vi.
Subjects:      Forms, Quadratic.
Control No.:   1974132

Author:        Bromwich, Thomas John I'Anson, 1875-1929.
Title:         Quadratic forms and their classification by means
                  of invariant-factors, by T. J. I'A. Bromwich.
Published:     Cambridge, University Press, 1906.
Description:   viii, 100 p. 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics, no. 3
LC Call No.:   QA243.B86
Dewey No.:     512.944
Notes:         "References": p. 95-97.
Subjects:      Forms, Quadratic.
Control No.:   8214227

Author:        Cantor, Georg, 1845-1918.
Title:         De equationibus secundi gradus indeterminatis
                  ...
Published:     Berolini, typis C. Schultzii [1867]
Description:   2 p. l., 25, [1] p. 25 cm.
LC Call No.:   QA243.C23
Subjects:      Diophantine analysis.
Control No.:   6797775

Author:        Chapelon, Jacques.
Title:         Sur les relations entre les nombres des classes
                  de formes quadratiques binaires de déterminant négatif :
                  propositions données par la faculté / par Jacques
                  Chapelon.
Published:     Paris : Gauthier-Villars, 1914.
Description:   195 p. ; 27 cm.
LC Call No.:   QA243.C52x 1914
Notes:         "Thèses présentées à la Faculté des sciences
                  de Paris pour obtenir le grade de docteur es sciences
                  mathématiques, soutenues le mai 1914, devant la Commission
                  d'examen."
               Includes bibliographical references.
Subjects:      Forms, Quadratic.
Control No.:   4764764

Author:        Collins, Matthew. [from old catalog]
Title:         A tract on the possible and impossible cases of
                  quadratic duplicate equalities in the Diophantine analysis:
Published:     Dublin, The author, 1858.
Description:   2 p.l., 60 p. 23 cm.
LC Call No.:   QA243.C7
Subjects:      Forms, Quadratic.
               Diophantine analysis.
Control No.:   8201302

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         Studies in the theory of numbers, by Leonard
                  Eugene Dickson.
Published:     Chicago, Ill., University of Chicago Press
                  [1930]
Description:   x, 230 p. diagrs. 26 cm.
Series:        University of Chicago science series
LC Call No.:   QA243.D5
Dewey No.:     512.81
Notes:         "This book contains numerous original
                  investigations in the theory of quadratic forms in three or
                  four variables."--Pref.
Subjects:      Forms, Quadratic.
               Number theory.
Control No.:   9215308

Author:        Dubisch, Roy, 1917-
Title:         Composition of quadratic forms ... by Roy Dubisch
                  ...
Published:     [n.p., 1946]
Description:   [1], 510-527 p. 26 cm.
LC Call No.:   QA243.D8
Dewey No.:     512.81
Notes:         Expansion of thesis (PH. D.)--University of
                  Chicago, 1943.
               "Reprinted from the Annals of mathematics, vol.
                  47, no. 3, July, 1946."
               Bibliography: p. 527.
Subjects:      Forms, Quadratic.
Control No.:   1691846

Author:        Goldschmidt, Ludwig, 1853- [from old catalog]
Title:         Beiträge zur theorie der quadratischen formen
                  ...
Published:     Sondershausen, Gedruckt in der Hof-buchdruckerei
                  [1881]
Description:   37, [1] p. 21 cm.
LC Call No.:   QA243.G62
Subjects:      Forms. Quadratic. [from old catalog]
Control No.:   5860270

Author:        Griffiths, Lois Wilfred, 1899-
Title:         Certain quaternary quadratic forms and
                  diophantine equations by generalized quaternion algebras.
Published:     1927.
Description:   46 l. illus. 19 cm.
LC Call No.:   QA243.G75
Dewey No.:     512/.87
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Includes bibliographical references.
Subjects:      Forms, Quadratic.
               Diophantine equations.
Control No.:   1713318

Author:        Hadlock, Edwin Harold, 1901- [from old catalog]
Title:         On the progressions associated with a ternary
                  quadratic form ...
Published:     Ithaca, N.Y., 1933.
Description:   [3] p. 23 cm.
LC Call No.:   QA243.H3
Subjects:      Forms, Quadratic. [from old catalog]
Other titles:  Ternary quadratic form.
Control No.:   7356038

Author:        Jones, Burton Wadsworth, 1902- [from old
                  catalog]
Title:         The arithmetic theory of quadratic forms.
Published:     [New York, 1950]
Description:   p. cm.
LC Call No.:   QA243.J6
Subjects:      Forms, Quadratic. [from old catalog]
Series Entry:  The Carus mathematical monographs, no. 10. [from
                  old catalog]
Control No.:   9299454

Author:        Jones, Burton Wadsworth, 1902- [from old
                  catalog]
Title:         Representation by positive ternary quadratic
                  forms.
Published:     [n.p.] 1928.
Description:   138 l. 29 cm.
LC Call No.:   QA243.J62
Subjects:      Forms, Quadratic.
               Forms, Ternary.
Control No.:   6159511

Author:        Lagrange, J. L. (Joseph Louis), 1736-1813.
Title:         Über die lösung der unbestimmten probleme
                  zweiten grades, von Joseph Louis Lagrange (1768) Aus dem
                  französischen übers. und hrsg. von Eugen Netto.
Published:     Leipzig, W. Engelmann, 1904.
Description:   131 p. 19 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften.
                  nr. 146
LC Call No.:   QA243.L15
Subjects:      Diophantine analysis.
Other authors: Netto, Eugen, 1846-1919, ed.
Control No.:   9143093

Author:        Lagrange, Joseph Louis, comte, 1736-1813. [from
                  old catalog]
Title:         Joseph Louis Lagrange's Zusäntze zu Eulers
                  Elementen der algebra.
Published:     Leipzig, W. Engelmann, 1898.
Description:   170 p., 1 l. 20 cm.
LC Call No.:   QA243.L17.
Subjects:      Diophantine analysis. [from old catalog]
               Fractions, Continued. [from old catalog]
Control No.:   10071345

Author:        Lejeune Dirichlet, Peter Gustav, 1805-1859.
Title:         Untersuchungen über verschiedene anwendungen der
                  infinitesimalanalysis auf die zahlentheorie, von G. Lejeune
                  Dirichlet (1839-1840) Deutsch hrsg. von R. Haussner.
Published:     Leipzig, W. Englemann, 1897.
Description:   128 p. 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 91
LC Call No.:   QA243.L3
Notes:         First published under original title, Recherches
                  sur diverses applications de l'analyse infinitésimale à la
                  théorie des nombres, in Crelle's Journal für die reine und
                  angewandte mathematick, bd. 19, 1839, and bd. 21, 1840.
Subjects:      Number theory.
Other authors: Haussner, Robert Karl Hermann, 1863-1948, ed. and
                  tr.
Control No.:   9603054

Author:        Marquis, Robert Houghton, 1902-
Title:         The representation of integers by certain
                  indefinite ternary and quaternary quadratic forms.
Published:     1929.
Description:   v, 35 l. 29 cm.
LC Call No.:   QA243.M43
Dewey No.:     512.9/44
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Forms, Quadratic.
               Forms, Quaternary.
               Forms, Ternary.
               Numbers, Natural.
Control No.:   311956

Author:        McAtee, James Elijah, 1885-1918.
Title:         Modular invariants of a quadratic form for a
                  prime power modulus / by James Elijah McAtee.
Published:     [Baltimore, 1919]
Description:   1 leaf, p. [225]-242, 1 leaf ; 29 cm.
LC Call No.:   QA243.M3 1917
Notes:         Vita.
               "A private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Thesis (Ph. D.)--University of Chicago, 1917.
               "Reprinted from the American journal of
                  mathematics, vol. XLI, no. 3, July, 1919."
Subjects:      Forms, Quadratic.
               Invariants.
Control No.:   8251618

Author:        McGavock, William Gillespie, 1909- [from old
                  catalog]
Title:         Annihilators of quadratic forms with applications
                  to Pfaffian systems,
Published:     [Durham, N.C., 1940]
Description:   p. cm.
LC Call No.:   QA243.M35 1940
Subjects:      Forms, Quadratic. [from old catalog]
               Algebraic fields.
Control No.:   8786087

Author:        Meyer, Arnold, 1844-1896. [from old catalog]
Title:         Zur theorie der unbestimmten ternären
                  quadratischen formen ...
Published:     Zürich, Druck von Zürcher und Furrer, 1871.
Description:   37 p. 22 cm.
LC Call No.:   QA243.M61
Subjects:      Forms, Quadratic. [from old catalog]
Control No.:   5860252

Author:        Minkowski, Hermann, 1864- [from old catalog]
Title:         Untersuchungen über quadratische formen.
Published:     Königsberg, Typ. E. Erlatis [1885]
Description:   1 p.l., 58, [2] p. 28 x 22 cm.
LC Call No.:   QA243.M66
Subjects:      Forms, Quadratic. [from old catalog]
Control No.:   7729384

Author:        Morrow, David Clarence, 1900- [from old catalog]
Title:         The determination of all quaternary quadratic
                  forms which represent every positive integer.
Published:     [n. p.] 1928.
Description:   v, 341 l. 29 cm.
LC Call No.:   QA243.M76
Subjects:      Forms, Quadratic.
               Forms, Quaternary.
               Numbers, Natural.
Control No.:   6228879

Author:        O'Meara, O. T. (Onorato Timothy), 1928-
Title:         Introduction to quadratic forms.
Published:     New York, Academic Press, 1963.
Description:   342 p. illus. 24 cm.
Series:        Die Grundlehren der mathematischen Wissenschaften
                  in Einzeldarstellungen mit besonderer Berücksichtigung der
                  Anwendungsgebiete, Bd. 117
LC Call No.:   QA243.O4
Dewey No.:     512.87
Notes:         Includes bibliography.
Subjects:      Forms, Quadratic.
Series Entry:  Grundlehren der mathematischen Wissenschaften in
                  Einzeldarstellungen mit besonderer Berücksichtigung der
                  Anwendungsgebiete ; Bd. 117.
Control No.:   751022

Author:        Oppenheim, Alexander, 1903-
Title:         The minima of indefinite quaternary quadratic
                  forms ... by Alexander Oppenheim ...
Published:     Chicago, Ill., 1931.
Description:   1 p.l., p. 271-298, 1 l. 26 cm.
LC Call No.:   QA243.O6 1930
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1930.
               Vita.
               "Private edition distributed by the University of
                  Chicago libraries."
               "Reprinted from the Annals of mathematics, vol.
                  32, no. 2."
               "References": p. 298.
Subjects:      Forms, Quadratic.
Control No.:   2162764

Author:        Silberfarb, Samuel, 1904- [from old catalog]
Title:         Representation by indefinite ternary quadratic
                  forms,
Published:     [n.p.] 1929.
Description:   v, 44 l. 29 cm.
LC Call No.:   QA243.S52
Control No.:   8143163

Author:        Sparks, Fred Winchell, 1891-
Title:         Universal quadratic zero forms in four variables
                  / by Fred Winchell Sparks.
Published:     [Chicago], 1933.
Description:   2 leaves, iii-iv, 49, [1] p. ; 24 cm.
LC Call No.:   QA243.S6 1931
Notes:         Vita.
               Lithoprinted.
               Thesis (Ph. D.)--University of Chicago, 1931.
               "Private edition distributed by the University of
                  Chicago libraries, Chicago, Illinois."
Subjects:      Forms, Quadratic.
Control No.:   6887033

Author:        Szpunar, Val Mar. [from old catalog]
Title:         On Pythagorean numbers and on Fermat's last
                  theorem,
Published:     Chicago [University of Chicago press] 1913.
Description:   16 p. 24 cm.
LC Call No.:   QA243.S8
Subjects:      Forms, Quadratic. [from old catalog]
               Fermat's theorem. [from old catalog]
Control No.:   7767394

Author:        Townes, Stanmore Brooks, 1899-
Title:         Reduced positive quaternary quadratic forms / by
                  Stanmore Brooks Townes.
Published:     [Chicago], 1936.
Description:   iii leaves, 65 p. : diagr. ; 24 cm.
LC Call No.:   QA243.T65 1936
Notes:         Vita.
               Lithoprinted.
               Thesis (Ph. D.)--University of Chicago, 1936.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Forms, Quadratic.
               Forms, Quaternary.
Control No.:   8772211

Author:        Underwood, R. S. (Ralph Sylvester), 1891-
Title:         On universal quadratic null forms in five
                  variables.
Published:     1930.
Description:   104 l. 29 cm.
LC Call No.:   QA243.U5
Dewey No.:     512.9/44
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
Subjects:      Forms, Quadratic.
               Congruences and residues.
Control No.:   1728589

Author:        Yanney, Benjamin Franklin. [from old catalog]
Title:         Modular invariants of the binary quartic.
Published:     Chicago, 1923.
Description:   48, 9 l. 29 cm.
LC Call No.:   QA243.Y3
Subjects:      Forms, Binary. [from old catalog]
               Forms, Quadratic. [from old catalog]
Control No.:   6115738

Author:        Amberg, Ernst Julius. [from old catalog]
Title:         Über den körper, dessen zahlen sich rational
                  aus zwei quadratwurzeln zusammensetzen ...
Published:     Zürich, Art. institut O. Füssli, 1897.
Description:   50 p., 1 l. 23 cm.
LC Call No.:   QA244.A5
Subjects:      Number theory.
Control No.:   6796376

Author:        Anderson, Mae Ruth, 1899-
Title:         Representation as a sum of multiples of polygonal
                  numbers ... by Mae Ruth Anderson ...
Published:     [Chicago] 1936.
Description:   2 p.l., 54 p. 24 cm.
LC Call No.:   QA244.A7 1936
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1936.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "List of references": p. 53.
Subjects:      Number theory.
Other titles:  Polygonal numbers.
Control No.:   3108821

Author:        Baker, Frances Ellen, 1902-
Title:         A contribution to the Waring problem for cubic
                  functions ... by Frances Ellen Baker ...
Published:     [Chicago] 1934.
Description:   2 p.l., 39 p. incl. tables. 24 cm.
LC Call No.:   QA244.B27 1934
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1934.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Partitions (Mathematics)
               Congruences and residues.
Control No.:   1690896

Author:        Ballantine, Constance Rummons. [from old
                  catalog]
Title:         Modular invariants of a binary group with
                  composite modulus ...
Published:     [Baltimore, 1923]
Description:   1 p.l., p. 286-293. 26 cm.
LC Call No.:   QA244.K3 1923
Subjects:      Invariants. [from old catalog]
Control No.:   6388062

Author:        Bernstein, Felix, 1878-1956.
Title:         Über den Klassenkörper eines algebraischen
                  Zahlkörpers ...
Published:     [Göttingen, Dieterich, 1903]
Description:   [45]-58 p. 24 cm.
LC Call No.:   QA244.B45
Notes:         Cover-title.
               Einladungschrift z.s. Antrittsvorlesung--Halle.
Subjects:      Number theory.
Control No.:   9140504

Author:        Chandler, Emily McCoy, 1904-
Title:         Waring's theorem for fourth powers ... by Emily
                  McCoy Chandler ...
Published:     [Chicago] 1933.
Description:   2 p.l., 62 p. incl. tables. 24 cm.
LC Call No.:   QA244.C53 1931
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1931.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Partitions (Mathematics)
Control No.:   746615

Author:        Chatland, Harold, 1911-
Title:         The asymptotic Waring problem for homogeneous
                  polynomial summands ... by Harold Chatland ...
Published:     [Princeton, N.J., 1938]
Description:   1 p.l., p. 49-57, 1 l. 26 cm.
LC Call No.:   QA244.C55 1937
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1937.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from the Annals of mathematics, vol.
                  39, no. 1, January, 1938."
Subjects:      Partitions (Mathematics)
Control No.:   1219155

Author:        Church, Alonzo, 1903-
Title:         Fermat's last theorem, by Alonzo Church. A
                  lecture given at the Galois institute of mathematics at Long
                  Island university.
Published:     Brooklyn, N.Y. [c1937]
Description:   1 p. l., 9 numb. l. 28 cm.
LC Call No.:   QA244.C6
Notes:         Mimeographed.
Subjects:      Diophantine analysis.
               Fermat's theorem.
Control No.:   9722836

Author:        Damm, Ivar, 1862- [from old catalog]
Title:         Bidrag til lären om kongruenser med
                  primatalsmodyl ...
Published:     Upsala, Upsala nya tidnings aktie-bolags tr.,
                  1896.
Description:   1 p. l., 86 p., 1 l. tables. 24 cm.
LC Call No.:   QA244.D3
Subjects:      Congruences and residues. [from old catalog]
Control No.:   9617600

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         On invariants and the theory of numbers.
Published:     New York, Dover Publications [1966]
Description:   ix, 110 p. 22 cm.
LC Call No.:   QA244.D47
Dewey No.:     512/.87
Notes:         "Unabridged and unaltered republication of the
                  work originally published by the American Mathematical
                  Society in 1914 as part I of The Madison Colloquium (1913),
                  volume IV of the [society's] Colloquium lectures."
Subjects:      Invariants.
               Number theory.
Other authors: American Mathematical Society.
Control No.:   4060684

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         Researches on Waring's problem, by L.E. Dickson.
Published:     [Washington] Carnegie institution of Washington,
                  1935.
Description:   v, 257 p. incl. tables. 26 cm.
Series:        Carnegie institution of Washington. Publication
                  no. 464
LC Call No.:   QA244.D5
Dewey No.:     512.81
Subjects:      Waring's problem.
               Mathematics -- Tables.
Series Entry:  Carnegie Institution of Washington publication ;
                  464.
Control No.:   3108685

Author:        Fuëter, Rudolf, 1880- [from old catalog]
Title:         Die theorie der zahlstrahlen ...
Published:     Marburg, 1905.
Description:   1 p.l., 41 p. 29 x 23 cm.
LC Call No.:   QA244.F8
Subjects:      Number theory.
               Galois theory. [from old catalog]
Control No.:   7747430

Author:        Ghent, Kenneth Smith, 1911-
Title:         On sums of values of a polynomial multiplied by
                  constants ... by Kenneth Smith Ghent ...
Published:     [Durham, N.C., 1937]
Description:   1 p.l., p. 518-528, 1 l. 26 cm.
LC Call No.:   QA244.G35 1935
Dewey No.:     512.81
Notes:         Part of thesis (PH. D.)--University of Chicago,
                  1935.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Duke mathematical journal, vol.
                  3, no. 3, 1937."
Subjects:      Diophantine analysis.
               Polynomials.
               Mathematical constants.
Control No.:   4054306

Author:        Gibason, Thomas Crawford, 1855- [from old
                  catalog]
Title:         Fermat's last theorum,
Published:     [Menasha, Wis., c1932]
Description:   [15] p. illus. (port.) diagr. 23 cm.
LC Call No.:   QA244.G4
Subjects:      Fermat's last theorem.
Control No.:   8287152

Author:        Goering, L. [from old catalog]
Title:         Ueber die theorie derjenigen complexen zahlen,
                  welche aus drei quadratwurzeln gebildet sind ...
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buchdruckerei (W. F. Kaestner) 1874.
Description:   50 p. 21 cm.
LC Call No.:   QA244.G5
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   8201473

Author:        Grant, Harold Sinclair, 1905- [from old catalog]
Title:         Concerning powers of certain classes of ideals in
                  a cyclotomic realm which give the principal class ...
Published:     Philadelphia, 1934.
Description:   1 p. l., [1], 220-238 p. 26 cm.
LC Call No.:   QA244.G7 1933
Subjects:      Number theory.
Control No.:   6422523

Author:        Haberzetle, Mary Barbara, 1912-
Title:         Two new universal Waring theorems ... by Mary
                  Barbara Haberzetle ...
Published:     [Chicago, 1939]
Description:   1 p.l., p. 49-57, 357-364. 24 cm.
LC Call No.:   QA244.H13 1938
Dewey No.:     512.81
Notes:         Thesis (Ph. D.)--University of Chicago, 1938.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Duke mathematical journal, vol.
                  5, no. 1, March 1939 [and] American journal of mathematics,
                  vol. 61, no. 2, April 1939."
Subjects:      Partitions (Mathematics)
Control No.:   274746

Author:        Hall, Marshall, 1910- [from old catalog]
Title:         An isomorphism between linear recurring sequences
                  and algebraic rings,
Published:     [New York, 1938]
Description:   p. cm.
LC Call No.:   QA244.H15 1936
Subjects:      Number theory.
               Algebraic fields.
Other titles:  Recurring sequences.
Control No.:   9248845

Author:        Hancock, Harris, 1867-1944.
Title:         Foundations of the theory of algebraic numbers,
                  by Harris Hancock ...
Published:     New York, The Macmillan Company, 1931-
Description:      v. fold. pl., diagrs. 21 cm.
LC Call No.:   QA244.H17
Dewey No.:     512.81
Notes:         "Published with the aid of the Charles Phelps
                  Taft Memorial Fund, University of Cincinnati."
               Includes references.
Subjects:      Number theory.
Other authors: University of Cincinnati. Charles Phelps Taft
                  Memorial Fund.
Other titles:  Algebraic numbers, Foundations of the theory of.
Control No.:   8752266

Author:        Hancock, Harris, 1867-1944.
Title:         Mémoire sur les systèmes modulaires de
                  Kronecker / par M. Harris Hancock.
Published:     Paris : Gauthier-Villars, 1901.
Description:   115 p. ; 27 cm.
LC Call No.:   QA244.H2
Notes:         Issued also in Annales de l'École normale
                  supérieure, 1901, suppl.
               Thèse--Université de Paris.
Subjects:      Number theory.
Control No.:   10085924

Author:        Hensel, Kurt, 1861-1941.
Title:         Theorie der algebraischen Zahlen. Von Dr. Kurt
                  Hensel.
Published:     Leipzig, Berlin, B. G. Teubner, 1908-
Description:   v. 25 cm.
LC Call No.:   QA244.H3
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Number theory.
Control No.:   5889615

Author:        Hightower, Ruby Usher, 1880- [from old catalog]
Title:         On the classification of the elements of a ring,
Published:     [Lancaster, Pa., Lancaster press, inc., 1927?]
Description:   21 p. 23 cm.
LC Call No.:   QA244.H5 1927
Subjects:      Number theory.
Control No.:   6887445

Author:        Hull, Ralph, 1903-
Title:         The numbers of solutions of congruences involving
                  only kth powers ... by Ralph Hull ...
Published:     [New York, 1932]
Description:   [1], 908-937 p. 28 cm.
LC Call No.:   QA244.H8 1932
Dewey No.:     512.8
Notes:         Thesis (PH. D.)--University of Chicago, 1932.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               From Transactions of the American mathematical
                  society, v. 34 ... October, 1932.
Subjects:      Congruences and residues.
Control No.:   2162858

Author:        Humphreys, Mabel Gweneth, 1911-
Title:         On the Waring problem with polynomial summands
                  ... by Mabel Gweneth Humphreys ...
Published:     [Durham, N.C., 1935]
Description:   2 p.l., p. 361-375, 1 l. 25 cm.
LC Call No.:   QA244.H83 1935
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1935.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Duke mathematical journal, vol.
                  I, no. 3, September 1935."
Subjects:      Partitions (Mathematics)
Control No.:   3108742

Author:        James, Ralph Duncan, 1909-
Title:         Analytical investigations in Waring's theorem ...
                  by Ralph Duncan James ...
Published:     [Chicago] 1934.
Description:   2 p. l., 43 p. 24 cm.
LC Call No.:   QA244.J3 1932
Dewey No.:     512.81
Notes:         Thesis (Ph. D.)--University of Chicago, 1932.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Number theory.
Other titles:  Waring's theorem.
Control No.:   10168990

Author:        Kircher, Edward August Theodore, 1890-
Title:         Group properties of the residue classes of
                  certain Kronecker modular systems and some related
                  generalizations in number theory / by Edward August Theodore
                  Kircher.
Published:     Lancaster, Pa. : Press of the New era printing
                  company, 1915.
Description:   1 leaf, p. 413-434, 1 leaf ; 28 cm.
LC Call No.:   QA244.K5
Notes:         Vita.
               Thesis (Ph. D.)--University of Illinois, 1914.
               "Reprinted from the Transactions of the American
                  mathematical society, October, 1915."
Subjects:      Number theory.
Control No.:   7773129

Author:        Kollros, Louis, 1878-
Title:         Un algorithme pour l'approximation simultanée de
                  deux grandeurs ...
Published:     Genève, Imprimerie Soullier, 1905.
Description:   47, [1] p. diagrs. 23 cm.
LC Call No.:   QA244.K8
Notes:         Inaug.-diss.--Zürich.
Subjects:      Number theory.
Control No.:   272881

Author:        Kronecker, Leopold, 1823-1891.
Title:         Grundzüge einer arithmetischen theorie der
                  algebraischen grössen ... von L. Kronecker. Angefügt ist
                  eine neue ausgabe der am 10. sept. 1845 erschienenen
                  inaugural-dissertation: De unitatibus complexis.
Published:     Berlin, G. Reimer, 1882.
Description:   viii, 174 p. 30 x 24 cm.
LC Call No.:   QA244.K9
Notes:         "Festschrift zu herrn Ernst Eduard Kummer's
                  fünfzig-jährigem doctor-jubiläum, 10. september 1881."
Subjects:      Number theory.
Other titles:  De unitatibus complexis.
Control No.:   2160960

Author:        Lamson, Franklin Silas. [from old catalog]
Title:         Fermat's last theorum.
Published:     [Washington, D.C., The press of Judd & Detweiler,
                  inc., c1913]
Description:   2 l. diagrs. 28 cm.
LC Call No.:   QA244.L3
Subjects:      Fermat's last theorem.
Control No.:   7766175

Author:        Litzinger, Marie, 1899-
Title:         A basis for residual polynomials in n variables
                  ... by Marie Litzinger ...
Published:     [New York, 1935]
Description:   1 p.l., [1], 216-225 p., 1 l. 28 cm.
LC Call No.:   QA244.L5 1934
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1934.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Transactions of the American
                  mathematical society, vol. XXXVII, no. 2, March, 1935."
Subjects:      Polynomials.
               Congruences and residues.
Other titles:  Residual polynomials in n variables.
Control No.:   2162988

Author:        Mason, Ruth Glidden, 1906-
Title:         Studies in the Waring problem ... by Ruth Glidden
                  Mason ...
Published:     [Chicago] 1934.
Description:   2 p.l., 32 p. 24 cm.
LC Call No.:   QA224.M35 1932
Dewey No.:     512.81
Notes:         Thesis (PH. D.)--University of Chicago, 1932.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Partitions (Mathematics)
Other titles:  Waring problem, Studies in.
Control No.:   4054087

Author:        McGinnis, M. A. (Michael Angelo)
Title:         Proof of Fermat's theorem, and McGinnis' theorem
                  of derivative equations in an absolute proof of Fermat's
                  theorem; reduction of the general equation of the fifth
                  degree to an equation of the fourth degree; and supplementary
                  theorems, by Michael Angelo McGinnis.
Published:     Meadowdale, Wash., L.C. Hjorth & sons [c1913]
Description:   xi, 34 p. 19 cm.
LC Call No.:   QA244.M3
ISBN:          $2.00
Subjects:      Fermat's theorem.
               Equations, Theory of.
Control No.:   1217867

Author:        Mordell, L. J. (Louis Joel), 1888-
Title:         Three lectures on Fermat's last theorem, by L. J.
                  Mordell.
Published:     Cambridge [Eng.] The University press, 1921.
Description:   31 p. 22 cm.
LC Call No.:   QA244.M6
Subjects:      Fermat's theorem.
Control No.:   7788829

Author:        Niven, Ivan Morton, 1915-
Title:         A Waring problem / by Ivan Morton Niven.
Published:     [Chicago], 1939.
Description:   ii leaves, 11 p. ; 24 cm.
LC Call No.:   QA244.N58 1938
Notes:         Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Thesis (Ph. D.)--University of Chicago, 1938.
Subjects:      Partitions (Mathematics)
Control No.:   6909097

Author:        Pierce, George Winslow, 1841-1917.
Title:         The greater Fermat theorem proved, and by George
                  Winslow Pierce.
Edition:       [3d ed.].
Published:     Boston, Mass., c1917.
Description:   1 p.l., 22 (i.e. 26), [2] p. front. (port.) 23
                  cm.
LC Call No.:   QA244.P5 1917
Subjects:      Fermat's theorem.
Control No.:   4526309

Author:        Reid, Legh Wilber.
Title:         The elements of the theory of algebraic numbers,
                  by Legh Wilber Reid ... with an introduction by David Hilbert
                  ...
Published:     New York, The Macmillan company, 1910.
Description:   xix, 454 p. 24 cm.
LC Call No.:   QA244.R3
ISBN:          $3.50.
Subjects:      Number theory.
Control No.:   1217692

Author:        Sauer, Richard, 1858-
Title:         Eine polynomische Verallgemeinerung der
                  Fermatschen Satzes ...
Published:     Giessen, v. Müchow'sche druckerei (O. Kindt)
                  1905.
Description:   18 p. 23 cm.
LC Call No.:   QA244.S3
Notes:         Lebenslauf.
               Inaug.-diss.--Giessen.
Subjects:      Congruences and residues
Control No.:   7743943

Author:        Schütz, Harald. [from old catalog]
Title:         Untersuchungen über functionale congruenzen ...
Published:     Frankfurt a. M., Druck von Mahlau und
                  Waldschmidt, 1867.
Description:   2 p.l., 23 p. 28 x 22 cm.
LC Call No.:   QA244.S4
Subjects:      Congruences and residues. [from old catalog]
Control No.:   7260670

Author:        Shook, Robert Clarence, 1904-
Title:         Concerning Waring's problem for sixth powers / by
                  Robert Clarence Shook.
Published:     [Chicago], 1934.
Description:   2 leaves, 38 p. ; 24 cm.
LC Call No.:   QA244.S5 1934
Notes:         Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Thesis (Ph. D.)--University of Chicago, 1934.
Subjects:      Number theory.
Other titles:  Waring's problems for sixth powers.
Control No.:   10168834

Author:        Thompson, William Rae. [from old catalog]
Title:         On the possible forms of discriminants of
                  algebraic fields I,
Published:     [Baltimore, 1931]
Description:   p. 81-90. 25 cm.
LC Call No.:   QA244.T5 1930
Subjects:      Forms (Mathematics) [from old catalog]
Control No.:   8753260

Author:        Turner, John Sidney, b. 1884.
Title:         A fundamental system of invariants of a modular
                  group of transformations ... by John Sidney Turner ...
Published:     [Lancaster, Pa., New York, 1922]
Description:   1 p.l., p. 129-134, 1 l. 28 cm.
LC Call No.:   QA244.T8 1922
Notes:         Thesis (PH. D.)--University of Chicago, 1922.
               Biography.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Transactions American
                  mathematical society, vol. XXIV, no. 2, September, 1922."
Subjects:      Invariants.
               Transformations (Mathematics)
Control No.:   746050

Author:        Webber, G. Cuthbert (George Cuthbert), 1906-
Title:         Waring's problem for cubic functions, by George
                  Cuthbert Webber.
Published:     [New York, 1934]
Description:   1 p. l., p. 493-510. 27 cm.
LC Call No.:   QA244.W4 1934
Notes:         "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               From Transactions of the American mathematical
                  society, vol. 36 ... July, 1934.
               Thesis (Ph. D.)--University of Chicago, 1934.
Subjects:      Number theory.
Control No.:   9232102

Author:        Wendt, Ernst, 1872- [from old catalog]
Title:         Arithmetische studien über den "letzten"
                  Fermatschen satz,
Published:     Berlin, Druck von G. Reimer, 1894.
Description:   p. cm.
LC Call No.:   QA244.W47
Subjects:      Congruences and residues. [from old catalog]
Control No.:   10071276

Author:        Whelan, Anna Marie, 1895- [from old catalog]
Title:         The theory of the binary octavic ...
Published:     [Baltimore, 1926]
Description:   1 p.l., p. 73-100, 1 l. 26 cm.
LC Call No.:   QA244.W5 1923
Subjects:      Number theory.
Control No.:   10141513

Author:        Wolff, Georg, 1881- [from old catalog]
Title:         Ueber gruppen der reste eines beliebigen moduls
                  im algebraischen zahlkörper ...
Published:     Göttingen, Druck der Dieterich'schen
                  Univ-buchdruckerei W. F. Kaestner, 1905.
Description:   46 p., 1 l. 23 cm.
LC Call No.:   QA244.W8
Subjects:      Number theory.
Control No.:   7740020

Author:        Yang, Ko-chuen, 1896- [from old catalog]
Title:         Various generalizations of Waring's problem.
Published:     Chicago, 1928.
Description:   ii, 43 l. tables. 29 cm.
LC Call No.:   QA244.Y3
Subjects:      Partitions (Mathematics). [from old catalog]
Control No.:   9385934

Author:        Bell, Eric Temple, 1883-1960.
Title:         The cyclotomic quinary quintic, by Eric T. Bell
                  ...
Published:     Lancaster, Pa., The new era printing company,
                  1912.
Description:   v, 97 p. 27 cm.
LC Call No.:   QA245.B5
Notes:         Thesis (Ph.D.)--Columbia university, 1912.
               Vita
Subjects:      Cyclotomy.
Control No.:   3580123

Author:        Heidke, Paul Wilhelm Herrmann, 1877- [from old
                  catalog]
Title:         Ueber kreisteilungsgleichungen vom primzahlgrad
                  p=pb1s[pi]1·pb2s[pi]2···p[mu][pi][mu]+1. ([mu]>1) ... von
                  Paul Heidke.
Published:     Greifswald, Druck von F.W. Kunike, 1899.
Description:   2 p. l., 28 p. 23 cm.
LC Call No.:   QA245.H46
Notes:         On t.p. "[pi]1", "[pi]2", and "[pi][mu]" are
                  superscript and "[mu]" is subscript after "p".
               Inaug.-diss.--Greifswald.
               Lebenslauf.
Subjects:      Cyclotomy.
Control No.:   13190059

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Mémoire sur la détermination des fonctions Y et
                  Z qui satisfont à l'équation
Published:     [Paris, 1830]
Description:   19 p. 26 cm.
LC Call No.:   QA245.L51
Subjects:      Congruences and residues.
Control No.:   7263150

Author:        Scheibner, Wilhelm. [from old catalog]
Title:         Zur theorie des Legendre-Jacobischen symbols
                  (n/m).
Published:     [n.p.] 1900-02.
Description:   2 v. cm.
LC Call No.:   QA245.S3
Control No.:   8152604

Author:        Teege, Hermann, 1864- [from old catalog]
Title:         Ueber die p-1/2 gliedrigen Gaussischen perioden
                  in der lehre von der kreisteilung und ihre beziehungen zu
                  anderen teilen der höheren arithmetik.
Published:     Kiel, Druck von P. Peters, 1900.
Description:   38, [6] p., 2 l. incl. tables 23 cm.
LC Call No.:   QA245.T2
Notes:         Inaug.-diss.--Kiel.
               Lebenslauf.
Subjects:      Cyclotomy.
Control No.:   13181337

Author:        Beaupain, J[ean] [from old catalog]
Title:         Sur une classe de fonctions.
Published:     [n.p.] [1901]
Description:   1 v. cm.
LC Call No.:   QA246.B38
Control No.:   6746211

Author:        Beiter, Marion, Sister.
Title:         Coefficients in the cyclotomic polynomial for
                  numbers with at most three distinct odd primes in their
                  factorization.
Published:     Washington, Catholic University of America Press,
                  1960.
Description:   47, [1] p. 23 cm.
LC Call No.:   QA246.B39
Dewey No.:     512.814
Notes:         Thesis - Catholic University of America.
               Bibliography: p. 47-[48]
Subjects:      Cyclotomy.
               Numbers, Prime.
               Symmetric functions.
Control No.:   8429240

Author:        Bell, Eric Temple, 1883-1960. [from old catalog]
Title:         An arithmetical theory of certain numerical
                  functions, by Eric Temple Bell.
Published:     Seattle, Wash., The University, 1915.
Description:   1 p.l., 44 p. 26 cm.
LC Call No.:   QA246.B4
Subjects:      Numerical functions. [from old catalog]
Series Entry:  University of Washington publications in
                  mathematical and physical sciences. v. 1, no. 1. [from old
                  catalog]
Control No.:   9177998

Author:        Blind, August, 1852- [from old catalog]
Title:         Ueber die potenzsummen der unter einer zahl m
                  liegenden und zu ihr relativ primen zahlen ...
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1876.
Description:   2 p.l., 37, [1] p., 1 l. 22 cm.
LC Call No.:   QA246.B64
Subjects:      Numerical functions. [from old catalog]
Control No.:   6330768

Author:        Dehn, Edgar, 1890-
Title:         Prime numbers, a study of their distribution.
Published:     Yonkers, N.Y., Rock Way House, 1952.
Description:   48 p. 23 cm.
LC Call No.:   QA246.D4
Dewey No.:     512.81
Subjects:      Numbers, Prime.
Control No.:   7908375

Author:        Dolze, Paul, 1875-
Title:         Über Bernouillische Zahlen und Funktionen :
                  welche zu einer Fundamentaldiskriminante gehören, und deren
                  Anwendung auf die summation unendlicher Reihen / von Paul
                  Dolze.
Published:     Dresden : B. G. Teubner, 1907.
Description:   44 p. : diagrs. ; 27 cm.
LC Call No.:   QA246.D65
Notes:         Lebenslauf.
               Inaug.-diss.--Rostock.
               "Literaturnachweis":  p. 44.
Subjects:      Bernoullian numbers.
Control No.:   9156968

Author:        Dwyer, Wendell Arthur.
Title:         On certain fundamental identities due to
                  Uspensky, by W. A. Dwyer.
Published:     [Lincoln, Neb., 1937]
Description:   p. 290-294. 25 cm.
LC Call No.:   QA246.D9 1937
Dewey No.:     512.81
Notes:         Cover-title.
               Thesis (Ph. D.)--University of Nebraska, 1937.
               Thesis note type-written on cover.
               "Reprinted from American journal of mathematics,
                  vol. LIX, no. 2, April, 1937."
Subjects:      Numerical functions.
               Functions, Theta.
Control No.:   5966681

Author:        Ehrenfels, Christian, Freiherr von, 1859-1932.
Title:         Das Primzahlengesetz, entwickelt und dargestellt
                  auf Grund der Gestalttheorie.
Published:     Leipzig, O. R. Reisland, 1922.
Description:   vi, 116 p. illus. 23 cm.
LC Call No.:   QA246.E5
Notes:         "Nachtrag zum fünften Kapitel, von Paul Kuhn":
                  p. 57-65.
               Bibliographical footnotes.
Subjects:      Numbers, Prime.
               Number theory.
               Gestalt psychology.
Other authors: Kuhn, Paul, mathematician.
Control No.:   6478613

Author:        Hacks, Jakob, 1863- [from old catalog]
Title:         Über summen von grössten ganzen ...
Published:     Bonn, Universitäts-buchdr. von C. Georgi, 1887.
Description:   1 p.l., 52, [2] p. 29 x 23 cm.
LC Call No.:   QA246.H13
Subjects:      Numerical functions. [from old catalog]
Control No.:   8205660

Author:        Harmuth, Theodor i. e. Friedrich Traugott
                  Theodor, 1854- [from old catalog]
Title:         Beiträge zur theorie der function E (x) ...
Published:     Göttingen, Druck der Dieterichschen
                  univ.-buchdruckerei (W. F. Kaestner) 1875.
Description:   45 p. 22 cm.
LC Call No.:   QA246.H2
Subjects:      Numerical functions. [from old catalog]
Control No.:   10076184

Author:        Henneberger, Moritz.
Title:         Beiträge zur Theorie der Integrale der
                  Bernoullischen Funktion ...
Published:     Bern, Buchdruckerei K. J. Wyss, 1902.
Description:   66 p., 1 L. 23 cm.
LC Call No.:   QA246.H5
Notes:         Inaug.-diss.--Bern.
Subjects:      Bernoullian numbers
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.9.
Control No.:   10078403

Author:        Huassner, Robert [Karl Hermann], 1863- [from old
                  catalog]
Title:         Zur theorie der Bernoulli'schen und Euler'schen
                  zahlen ...
Published:     Göttingen, Druck der Dieterich'schen
                  universitäts-buchdruckerei, 1894.
Description:   35 p. 25 cm.
LC Call No.:   QA246.H37
Subjects:      Bernoulli numbers.
               Euler's numbers.
Control No.:   7732813

Author:        Ibn Ezra, Abraham ben Meïr, 1092-1167. [from old
                  catalog]
Uniform Title: Seter ha-eòhad. German [from old catalog]
Title:         Buch der Einheit;
Published:     Berlin, Welt-Verlag [1921]
Description:   80 p. 19 cm.
LC Call No.:   QA246.I25
Subjects:      Numbers, Prime. [from old catalog]
Control No.:   7493041

Author:        Ibn Ezra, Abraham ben Meïr, 1092-1167. [from old
                  catalog]
Title:         Sefer ha-eòhad.
Published:     [Odessae, 1867]
Description:   iii, 70 p. 21 cm.
LC Call No.:   QA246.I2
Notes:         Romanized.
Subjects:      Numbers, Prime.
Control No.:   7910457

Author:        Landau, Edmund, 1877-1938.
Title:         Handbuch der lehre von der verteilung der
                  primzahlen.
Published:     Leipzig und Berlin, B. G. Teubner, 1909.
Description:   2 v. 23 cm.
LC Call No.:   QA246.L2
Subjects:      Numbers, Prime.
Control No.:   6348114

Author:        Landau, Edmund, 1877-1938.
Title:         Neuer beweis der gleichung [superscript infinity
                  sign][Greek letter sigma]k=1 [Greek letter mu](k)/k = 0 ...
Published:     Berlin, 1899.
Description:   16 p., 1 l. 24 cm.
LC Call No.:   QA246.L25
Notes:         On. t.p. "k=1" is subscript.
               Inaug.-diss.--Berlin.
Control No.:   13181326

Author:        Lehmer, Derrick Norman, 1868-
Title:         Asymptotic evaluation of certain totient sums /
                  by Derrick Norman Lehmer.
Published:     [Baltimore], 1900.
Description:   45 p., 1 leaf : diagrs ; 31 x 25 cm.
LC Call No.:   QA246.L52
Notes:         Vita.
               Thesis (Ph. D.)--University of Chicago.
               From the American journal of mathematics.
Subjects:      Numerical functions.
Control No.:   6810413

Author:        Matter, Karl. [from old catalog]
Title:         Die den Bernoulli'schen zahlen analogen zahlen im
                  körper, per der dritten einheitswurzeln ...
Published:     Zürich, Druck von Zürcher & Furrer, 1900.
Description:   38 p., 1 l. incl. tab. 23 cm.
LC Call No.:   QA246.M43
Subjects:      Numerical functions. [from old catalog]
Control No.:   8201491

Author:        Meyer, Gustav Ferdinand.
Title:         Über Bernoulli'sche zahlen ...
Published:     Göttingen, E. A. Huth, 1859.
Description:   56 p.
LC Call No.:   QA246.M6
Notes:         Inaug.-diss.--Göttigen.
Subjects:      Bernoullian numbers
Control No.:   6462542

Author:        Meyer, Peter Gerdes, 1882- [from old catalog]
Title:         Beweis eines von Euler entdeckten satzes,
Published:     Strassburg i. E., Buchdruckerei C. & J. Gœller,
                  1906.
Description:   29 p., 1 l. 23 cm.
LC Call No.:   QA246.M62
Subjects:      Numbers, Prime. [from old catalog]
Control No.:   7746476

Author:        Nogrady, Henry A.
Title:         A new method for finding prime numbers and
                  factors.
Published:     Ann Arbor, Mich., Lithographed by Edwards Bros.
                  [1963]
Description:   95 p. illus. 28 cm.
LC Call No.:   QA246.N6
Dewey No.:     511.3
Subjects:      Numbers, Prime.
Control No.:   9382415

Author:        Piltz, Adolf.
Title:         Über die häufigkeit der primzahlen in
                  arithmetischen progressionen und über verwandte gesetze /
                  Adolf Piltz.
Published:     Jena : A. Neuenhahn, 1884.
Description:   48 p. ; 22 cm.
LC Call No.:   QA246.P64
Notes:         Zur erlangung der venia docendi--Jena.
Subjects:      Numbers, Prime.
Control No.:   9606419

Author:        Renfer, Hermann. [from old catalog]
Title:         Die definitionen der Bernoullischen funktion und
                  untersuchung der frage welche von denselben für die theorie
                  die zutreffendste ist.  ...
Published:     Bern, Buchdruckerei K. J. Wyss, 1900.
Description:   2 p.l., 100 p. 4 fold. pl., diagrs. 23 cm.
LC Call No.:   QA246.R4
Subjects:      Bernoulli numbers.
Control No.:   7736497

Author:        Torelli, Gabriele, 1849-
Title:         Sulla totalità dei numeri primi fino ad un
                  limite assegnato; monografia di Gabriele Torelli ...
Published:     Napoli, Tip. della Reale accademia delle scienze
                  fisiche e matematiche, 1901.
Description:   VIII p., 1 l., 212, [3] p. fold. diagr. 34 cm.
LC Call No.:   QA246.T5
Notes:         "Premiata dalla R. Accademia delle scienze
                  fisiche e matematiche di Napoli nell'adunanza del 15 dicembre
                  1900."
               "Memoria estratta dal vol. XI, serie 2a, no. 1,
                  degli Atti della R. Accademia delle scienze fis. e mat. di
                  Napoli."
Subjects:      Numbers, Prime.
Other authors: Reale Accademia delle scienze fisiche e
                  matematiche di Napoli.
Control No.:   1218144

Author:        Vieth, Carl Johann von, 1856- [from old catalog]
Title:         Anwendungen einer vielfach komplexen grösse auf
                  die zahlentheorie ...
Published:     Dresden, Druck von B. G. Teubner, 1893.
Description:   p. cm.
LC Call No.:   QA246.V66
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   9602986

Author:        Von Ammon, F. E. [from old catalog]
Title:         Primes, a strictly empirical study.
Published:     [Fort Lauderdale? Fla., 1960]
Description:   25 p. 22 cm.
LC Call No.:   QA246.V7
Subjects:      Numbers, Prime. [from old catalog]
Control No.:   9860193

Author:        Warga, Jack, 1922- [from old catalog]
Title:         On the representation of large integers as sums
                  of primes.
Published:     [n.p., 1950]
Description:   153-176 p. 25 cm.
LC Call No.:   QA246.W3
Subjects:      Numbers, Prime. [from old catalog]
               Integrals. [from old catalog]
Other authors: Shapiro, Harold N., [from old catalog] joint
                  author.
Control No.:   6507825

Author:        Wintner, Aurel, 1903-
Title:         The theory of measure in arithmetical
                  semi-groups, by Aurel Wintner.
Published:     Baltimore [The Waverly press, inc.] 1944.
Description:   v, 56 p. 25 cm.
LC Call No.:   QA246.W5
Dewey No.:     512.81
Notes:         Bibliography: p. 55-56.
Subjects:      Numbers, Prime.
               Functions, Zeta.
Control No.:   4527849

Author:        Smith, James F., 1930- [from old catalog]
Title:         Structure theorems for certain scalar-products
                  algebras.
Published:     Washington, Catholic University of America Press,
                  1959.
Description:   vi, 50 p. 23 cm.
LC Call No.:   QA249.S59
Control No.:   8145568
