#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Cesari, Lamberto.
Title:         Surface area.
Published:     Princeton, Princeton University Press, 1956.
Description:   595 p. illus. 26 cm.
Series:        Annals of mathematics studies, no. 35
LC Call No.:   QA571.C4
Dewey No.:     516.59
Notes:         Includes bibliography.
Subjects:      Surfaces.
Series Entry:  Annals of mathematics studies ; no. 35.
Control No.:   748558

Author:        Dennis, Foster Leroy, 1910- [from old catalog]
Title:         Some geometric applications of algebraic
                  correspondences,
Published:     Urbana, Ill., 1938.
Description:   2 p.l., 10 p., 1 l. 21 cm.
LC Call No.:   QA571.D4 1938
Subjects:      Surfaces. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Other titles:  Correspondences, Algebraic.
Control No.:   10183948

Author:        Geck, Erwin. [from old catalog]
Title:         Ueber die singulären punkte algebraischer
                  flächen ...
Published:     Tübingen, Druck von H. Laupp, jr., 1900.
Description:   40 p. 24 cm.
LC Call No.:   QA571.G29
Subjects:      Surfaces. [from old catalog]
Control No.:   9137972

Author:        Hamdorff, Karl, 1842- [from old catalog]
Title:         De superficiebus algebraicis in planum
                  explicabilibus ...
Published:     Halis Saxonum, formis Ploetzianis [1863]
Description:   2 p. l., 34, [2] p. 21 cm.
LC Call No.:   QA571.H21
Subjects:      Surfaces. [from old catalog]
Control No.:   7732900

Author:        Johanson, Ralph Nathanael, 1914- [from old
                  catalog]
Title:         Rules surfaces with interseting generators ...
Published:     [Chicago] 1941.
Description:   ii numb. l. 28 p. 24 cm.
LC Call No.:   QA571.J6
Subjects:      Surfaces. [from old catalog]
Control No.:   6916751

Author:        Levänen, Sakris, 1841-1898. [from old catalog]
Title:         Om linierbara ytor ...
Published:     Helsingfors, J. C. Frenckell & son, 1874.
Description:   1 p.l., 33 p. 26 cm.
LC Call No.:   QA571.L65
Subjects:      Surfaces. [from old catalog]
Control No.:   6331450

Author:        Moore, Walter Lee, 1898- [from old catalog]
Title:         On the geometry of the Weddle surface,
Published:     Urbana, Ill. [1929]
Description:   [1], 492-498 p., 1 l. 26 cm.
LC Call No.:   QA571.M6 1928
Subjects:      Surfaces. [from old catalog]
               Collineation. [from old catalog]
Other titles:  Weddle surface.
Control No.:   9215036

Author:        Plücker, Julius, 1801-1868.
Title:         System der analytischen geometrie, auf neue
                  betrachtungsweisen gegründet, und insbesondere eine
                  ausführliche theorie der curven dritter ordnung enthaltend.
                  Von dr. Julius Plücker ...
Published:     Berlin, Duncker und Humblot, 1835.
Description:   xvi, 292 p., 1 l. pl. 28 x 22 cm.
LC Call No.:   QA571.P73
Notes:         With his System der geometrie des raumes in neuer
                  analytischer behandlungsweise, insbesondere die theorie der
                  flächen zweiter ordnung und classe enthaltend. Düsseldorf,
                  1846.
Subjects:      Curves, Plane.
Control No.:   744721

Author:        Plücker, Julius, 1801-1868.
Title:         System der geometrie des raumes in neuer
                  analytischer behandluungsweise, insbesondere die theorie der
                  flächen zweiter ordnung und classe enthaltend. Von dr.
                  Julius Plücker ...
Published:     Düsseldorf, Schaub'sche buchhandlung, W.H.
                  Scheller, 1846.
Description:   ix, 334 p. pl. 28 x 22 cm.
LC Call No.:   QA571.P73
Notes:         With this copy is bound the author's "System der
                  analytischen geometrie, auf neue betrachtungsweisen
                  gegründet, und insbesondere eine ausführliche theorie der
                  curven dritter ordnung enthaltend. Berlin, 1835.
Subjects:      Surfaces.
Control No.:   3106700

Author:        Walker, Robert John, 1909-
Title:         Reduction of the singularities of an algebraic
                  surface, by Robert J. Walker.
Published:     Princeton university, 1934.
Description:   p. 336-365 26 cm.
LC Call No.:   QA571.W3 1934
Notes:         Cover-title.
               Thesis (Ph. D.)--Princeton university, 1934.
               Running title: Singularities of surfaces.
               "Reprinted from the Annals of mathematics, vol.
                  36, number 2."
Subjects:      Surfaces.
Other titles:  Singularities of surfaces.
Control No.:   9702274

Author:        Blythe, W. H. (William Henry)
Title:         On models of cubic surfaces, by W.H. Blythe ...
Published:     Cambridge, At the University press, 1905.
Description:   xii, 106 p. diagrs. 20 cm.
LC Call No.:   QA573.B66
Subjects:      Surfaces, Cubic.
               Surfaces, Models of.
Control No.:   4525636

Author:        Bowen, Lawrence Henry, 1889- [from old catalog]
Title:         Composite double curves on rational ruled
                  surfaces ...
Published:     [Ithaca, N.Y., 1936]
Description:   [6] p. 23 cm.
LC Call No.:   QA573.B75 1936
Subjects:      Surfaces. [from old catalog]
Other titles:  Ruled surfaces.
Control No.:   8303915

Author:        Bützberger, F[riedrich] [from old catalog]
Title:         Ein mit der theorie algebraischer flächen
                  zusammenhängendes planimetrisches problem ...
Published:     Bern, Buchdruckerei K. J. Wyss, 1889.
Description:   35 p. 23 cm.
LC Call No.:   QA573.B98
Subjects:      Triangle. [from old catalog]
               Surfaces. [from old catalog]
Control No.:   10074764

Author:        Cremona, L[uigi], 1830-1903. [from old catalog]
Title:         Mémoire de géométrie pure sur les surfaces du
                  troisième ordre, mémoire qui a obtenu la moitié du prix
                  Steiner décerné par l'Académie des sciences de Berlin dan
                  sa séance du 5 juillet 1866.
Published:     Berlin, Imprimé chez G. Reimer, 1868.
Description:   1 p.l., 133 p. 28 cm.
LC Call No.:   QA573.C91
Subjects:      Surfaces, Cubic. [from old catalog]
Control No.:   9608008

Author:        Crull, Harry Edward, 1909- [from old catalog]
Title:         Quartic surfaces invariant under the symmetric
                  group, Gb24s,
Published:     Urbana, Ill., 1933.
Description:   12 p. 23 cm.
LC Call No.:   QA573.C95 1933
Subjects:      Surfaces, Quartic. [from old catalog]
               Collineation. [from old catalog]
Control No.:   10165933

Author:        Diekmann, Franz Josef Konrad, 1848-1905. [from
                  old catalog]
Title:         Ueber die modificationen, welche die ebene
                  abbildung einer fläche dritter ordnung durch auftreten von
                  singularitäten erhält.
Published:     Leipzig, Druck von B. G. Teubner, 1871.
Description:   36 p. fold. pl. (diagrs.) 22 cm.
LC Call No.:   QA573.D5
Subjects:      Surfaces, Cubic. [from old catalog]
Control No.:   6873664

Author:        Ernst, Christian. [from old catalog]
Title:         Ueber haupttangentencurven auf einigen
                  singulären flächen dritter ordnung ...
Published:     Göttingen, Druck der Dieterichschen
                  Univ.-buchdruckerei (W. F. Kaestner) 1873.
Description:   59 p. 21 cm.
LC Call No.:   QA573.E6
Subjects:      Surfaces. [from old catalog]
Control No.:   8668261

Author:        End, Wilhelm, 1864- [from old catalog]
Title:         Algebraische untersuchungen über flächen mit
                  gemeinschaftlicher curve ...
Published:     München, Akademische buchdruckerei von F.
                  Straub, 1888.
Description:   p. cm.
LC Call No.:   QA573.E55
Subjects:      Surfaces. [from old catalog]
Control No.:   10078389

Author:        Fink, Karl. [from old catalog]
Title:         Über windschiefe flächen im allgemeinen und
                  insbedere über solche des sechsten grades ...
Published:     Tübingen, L. F. Fues'sche buchdruckerei (Fues &
                  Kostenbader) 1887.
Description:   1 p.l., 30 p. 21 cm.
LC Call No.:   QA573.F5
Subjects:      Surfaces. [from old catalog]
Control No.:   8676277

Author:        Greve, Emil. [from old catalog]
Title:         Über die spirische oberfläche und ihre
                  durchschnittscurven mit ebenen ...
Published:     Hannover, Schrift und druck von F. Culemann,
                  1875.
Description:   1 p.l., 46 p. diagrs. on fold. pl. 25 cm.
LC Call No.:   QA573.G8
Subjects:      Surfaces. [from old catalog]
Control No.:   8200103

Author:        Heermann, Rudolf, (Oskar Rudolf Engelhard) 1857-
Title:         Ueber gewisse krumme flächen, welche bei der
                  bewegung einter mit den berührungsebenen einer gegebenen
                  fläche zweiter ordnung mit endlichem mittelpunkt parallelen
                  und durch einen festen punkt gehenden ebene erzeugt werden.
Published:     Marburg, Druck von C.L. Pfeil, 1880.
Description:   41 p. 22 cm.
LC Call No.:   QA573.H45
Notes:         Inaug.-diss.--Marburg.
Subjects:      Surfaces.
Control No.:   7732873

Author:        Henderson, Archibald, 1877-1963.
Title:         The twenty-seven lines upon the cubic surface.
Published:     New York, Hafner Pub. Co. [1960?]
Description:   100 p. illus. 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics, no. 13
LC Call No.:   QA573.H47 1960
Dewey No.:     516.5
Subjects:      Surfaces, Cubic.
Control No.:   9362498

Author:        Hill, John Ethan, 1865-
Title:         On quintic surfaces, / by John E.Hill...
Published:     Worcester, Mass., 1896.
Description:   59 leaves ; 25 cm.
LC Call No.:   QA573.H64
Notes:         Cover-title
               Thesis (Ph. D.)--Clark University, 1895.
               "Reprinted from the Mathematical review."
               Includes bibliographical references.
Subjects:      Surfaces, Quintic.
Control No.:   10078015

Author:        Holgate, Thomas F. (Thomas Franklin), 1859-1945.
Title:         On certain ruled surfaces of the fourth order /
                  By Thomas F. Holgate.
Published:     Baltimore : Press of the Friedenwald Company,
                  1893.
Description:   iv, 43 p. ; 30 cm.
LC Call No.:   QA573.H73
Notes:         Thesis (Ph. D.)--Clark University, 1893.
               From the American journal of science, v. 15.
Subjects:      Surfaces, Quartic.
Control No.:   8672931

Author:        Hubbs, Horace Newton, 1893- [from old catalog]
Title:         Analytic study of rational quintic surfaces
                  having no multiple curves ...
Published:     [New York, 1932]
Description:   p. cm.
LC Call No.:   QA573.H83 1931
Subjects:      Surfaces, Quintic.
               Cremona transformations.
Control No.:   7821361

Author:        Hyden, John Albert, 1893- [from old catalog]
Title:         The Weddle and Kummer surfaces for restricted
                  positions of six base points ...
Published:     [Ithaca, N.Y., 1934]
Description:   [5] p. 23 cm.
LC Call No.:   QA573.H9 1934
Subjects:      Surfaces, Quartic. [from old catalog]
Other titles:  Weddle ... surfaces.
               Kummer surfaces.
Control No.:   7363847

Author:        Jaeckel, Waldemar, 1880-
Title:         Uber [!] flächen 5. ordnung mit einer doppelten
                  Kubischen raumkurve ...
Published:     Breslau, Buchdruckerei H. Fleischmann, 1904.
Description:   113, [3] p. 22 cm.
LC Call No.:   QA573.J22
Notes:         Inaug.-dis.--Breslau.
               Lebenslauf.
Subjects:      Surfaces.
Control No.:   1217183

Author:        Jessop, C. M. (Charles Minshall), 1861-1939.
Title:         Quartic surfaces with singular points, by C. M.
                  Jessop.
Published:     Cambridge [Eng.] University Press, 1916.
Description:   xxxv, 197, [1] p. 23 cm.
LC Call No.:   QA573.J5
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Surfaces, Quartic.
Control No.:   6839655

Author:        Kalbfleisch, Georg, 1877-
Title:         Symmetrische cykliden ...
Published:     Strassburg i. E., Buchdruckerei C. & J. Gœller,
                  1902.
Description:   47 p., 1 l. 23 cm.
LC Call No.:   QA573.K14
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Surface, Quartic.
Control No.:   7736484

Author:        Killing, Wilhelm, 1847-
Title:         Der flächenbüschel zweiter ordnung ...
Published:     Berlin, Druck von G. Schade (O. Francke) [1872]
Description:   2 p. l., 39, [1] p. 22 cm.
LC Call No.:   QA573.K4
Subjects:      Surfaces. [from old catalog]
Control No.:   5858902

Author:        Lampe, Emil i. e. Karl Otto Emil, 1840- [from old
                  catalog]
Title:         De superficiebus quarti ordinis quibus puncta
                  triplica insunt...
Published:     Berolini, typis expressit G. Schade [1864]
Description:   17, [1] p. 25 cm.
LC Call No.:   QA573.L2
Subjects:      Surfaces. [from old catalog]
Control No.:   7263318

Author:        Liebheit, Edmund, 1862- [from old catalog]
Title:         Ueber die Dupin'sche cyclide ...
Published:     Halle a. S., 1886.
Description:   38 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA573.L71
Subjects:      Surfaces. [from old catalog]
Control No.:   7264782

Author:        Löffler, Karl. [from old catalog]
Title:         Ueber eine algebraische fläche 4. ordnung welche
                  durch die auf ein rechtwinkliges coordinaten-system bezogene
                  gleichung: cp2szp2s=(xp2s sinê2 [phi] --cp2s) (yp2s
                  cosp2s [phi]--cp2s) dargestellt ist ...
Published:     Darmstadt, Buchdruckerei von G. Otto, 1874.
Description:   2 p.l., 19 p. 18 cm.
LC Call No.:   QA573.L8
Subjects:      Surfaces. [from old catalog]
Control No.:   9136508

Author:        Melde, Franz [Emil], 1832-1901. [from old
                  catalog]
Title:         Ueber einige krumme flächen, welche von ebenen,
                  parallel einer bestimmten ebene, durchschnitten, als
                  durchschnittsfigur einen kegelschnitt liefern ...
Published:     Marburg, Druck von J. A. Koch, 1859.
Description:   32 p. 21 x 17 cm.
LC Call No.:   QA573.M5
Subjects:      Surfaces. [from old catalog]
Control No.:   5864122

Author:        Noether, Max, 1844- [from old catalog]
Title:         Ueber flächen, welche schaaren rationaler curven
                  besitzen ...
Published:     Leipzig, G. B. Teubner, 1870.
Description:   1 p.l., 67 p. 24 cm.
LC Call No.:   QA573.N77
Subjects:      Surfaces. [from old catalog]
Control No.:   8205321

Author:        Pabst, Karl. [from old catalog]
Title:         ueber die elliptischen und die hyperbolischen
                  cono-cunei ...
Published:     Marburg, Druck von J. A. Koch, 1884.
Description:   36 p. 22 cm.
LC Call No.:   QA573.P12
Subjects:      Surfaces, Quartic. [from old catalog]
Other titles:  Cono-cunei.
Control No.:   9141566

Author:        Parker, William Vann, 1901- [from old catalog]
Title:         On the Kummer surface,
Published:     [New York, 1932]
Description:   p. 403-408. 24 cm.
LC Call No.:   QA573.P3 1931
Subjects:      Surfaces, Quartic. [from old catalog]
Other titles:  Kummer surface.
Control No.:   8763605

Author:        Pobanz, John Frederick, 1889- [from old catalog]
Title:         A study of cubic surfaces by means of involutory
                  cubic space transformations,
Published:     [Berkeley, Calif., 1924]
Description:   p. [401]-423. 28 cm.
LC Call No.:   QA573.P6 1923
Subjects:      Surfaces, Cubic. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Control No.:   6388591

Author:        Renfer, Adrian.
Title:         Ueber Schraubenlinien und Schraubenflächen / von
                  Adrian Renfer.
Published:     Burgdorf : S. Haller, 1900.
Description:   68 p. : ill. ; 28 cm.
LC Call No.:   QA573.R4
Notes:         "Litteraturnachweis" : p. 68.
               Thesis--Universität Bern.
Subjects:      Surfaces.
               Curves of double curvature.
Control No.:   7268438

Author:        Rodenberg, Karl [Friedrich], 1851- [from old
                  catalog]
Title:         Das pentaeder der flächen dritter ordnung beim
                  auftreten von singularitäten ...
Published:     Göttingen, Druck von E. A. Huth, 1874.
Description:   31 p. 22 cm.
LC Call No.:   QA573.R6
Subjects:      Surfaces. [from old catalog]
Control No.:   7731406

Author:        Shreve, Darrell Rhea, 1908- [from old catalog]
Title:         A certain class of algebraic hypersurfaces in
                  projective space Sr invariant under the symmetric
                  substitution group G (r+2) !
Published:     Urbana, Ill., 1938.
Description:   9 p., 1 l. 23 cm.
LC Call No.:   QA573.S55 1938
Subjects:      Surfaces. [from old catalog]
               Group theory.
Other titles:  Hypersurfaces.
               Hypersurfaces, Algebraic.
Control No.:   7842291

Author:        Stoltz, Karl, 1858- [from old catalog]
Title:         Untersuchung der fläche dritter ordnung
                  hinsichtlich der projectiv verallgemeinerten
                  mittelpunkts-eigenschaften ...
Published:     Mainz, Buchdruckerei von H. Prickarts, 1890.
Description:   18 p., 1l. 27 x 22 cm.
LC Call No.:   QA573.S87
Subjects:      Surfaces. [from old catalog]
Control No.:   5860333

Author:        Strobel, [Adolf] [from old catalog]
Title:         Über flächen, welch durch veränderliche
                  kegelschnitte erzeugt werden ...
Published:     Heilbronn, Druck von C. Rembold & co., 1901.
Description:   47 p. diagrs. 25 x 21 cm.
LC Call No.:   QA573.S9
Subjects:      Surfaces. [from old catalog]
Other authors: Heilbronn. K. Oberrealschule. [from old catalog]
Control No.:   9614189

Author:        Uth, Karl. [from old catalog]
Title:         Die fläche,
Published:     Marburg, 1865.
Description:   1 p. l., 13 p. diagrs. on 6 pl. 24 cm.
LC Call No.:   QA573.U89
Subjects:      Surfaces. [from old catalog]
Control No.:   5860206

Author:        Waelsch, Emil, 1863- [from old catalog]
Title:         Ueber das normalsystem und die centralfläche
                  algebraischer flächen,
Published:     Halle, 1888.
Description:   28 p. 33 x 25 cm.
LC Call No.:   QA573.W12
Subjects:      Surfaces. [from old catalog]
Control No.:   8201557

Author:        Walden, Emory Earl, 1898- [from old catalog]
Title:         Algebraic surfaces invariant under the symmetric
                  Gb1s20,
Published:     Urbana, Ill., 1936.
Description:   p. cm.
LC Call No.:   QA573.W2 1935
Subjects:      Surfaces, Quintic. [from old catalog]
               Surfaces, Sextic. [from old catalog]
               Group theory.
Control No.:   7835308

Author:        Wiegner, Georg [Sebald Paul], 1864- [from old
                  catalog]
Title:         Über eine besondere klasse von
                  translationsflächen ...
Published:     Kristiania og Kjøbenhavn, A. Cammermeyers forlag
                  (F. G. Knudtzon og L Swanstrøm) [1893]
Description:   2 p.l., 82 p. 2 pl., diagrs. 23 cm.
LC Call No.:   QA573.W64
Subjects:      Surfaces. [from old catalog]
Control No.:   8201269

Author:        Worms, Eugen i.e. Johannes Eugen, 1861-
Title:         Untersuchungen über die oberflächen, deren
                  gleichung für die rechtwinkligen coordinaten x, y, z die
                  gestalt hat xõm [plus or minus] yõm [plus or minus] zõm = 1,
                  wobei m eine beliebige positive gerade zahl bedeutet.
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1888.
Description:   2 p.l., 40 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA573.W92
Notes:         On t.p. õm is superscript.
               Lebenslauf.
               Inaug.-dis.--Freiburg.
Subjects:      Surfaces.
Control No.:   3106895

Author:        Zacharies, Max. [from old catalog]
Title:         Ueber die beziehungen zwischen den 27 geraden auf
                  einer fläche 3. ordnung und den 28 doppeltangenten einer
                  ebenen kurve 4. ordnung ...
Published:     Göttingen, Druck von W. F. Kaestner, 1903.
Description:   38 p. 22 cm.
LC Call No.:   QA573.Z16
Notes:         Inaug-dis.--Rostock.
Subjects:      Surfaces, Cubic. [from old catalog]
               Curves, Quartic. [from old catalog]
Control No.:   10074825

Author:        Zimmermann, Fritz, 1879-
Title:         Untersuchungen über flächen 4. ordnung mit
                  einer doppelten geraden ...
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buchdruckerei von W.F. Kaestner, 1904.
Description:   2 p.l., 81, [3] p. fold. tab. 22 cm.
LC Call No.:   QA573.Z73
Notes:         Inaug.-dis.--Breslau.
               Lebenslauf.
               "Literatur": 1 p. following p. 81.
Subjects:      Quartic surfaces.
Control No.:   744937

Author:        Polley, Joseph Crawford, 1897- [from old
                  catalog]
Title:         Rational surfaces defined by linear systems of
                  plane curves
Published:     [Baltimore, 1930]
Description:   1 p.l., p. 877-888. 25 cm.
LC Call No.:   QA578.P65 1929
Subjects:      Surfaces. [from old catalog]
Control No.:   9218158

Author:        Adams, Helen Schlauch, 1907-
Title:         On the normal rational n-IC ... by Helen Schlauch
                  Adams ...
Published:     [New York, 1936]
Description:   p. [441]-448. 24 cm.
LC Call No.:   QA581.A35 1933
Dewey No.:     516.58
Notes:         Cover-title.
               Abstract of thesis (Ph. D.)--Cornell University,
                  1933.
               "Reprinted from the Bulletin of the American
                  Mathematical Society, no. 6, June, 1936."
Subjects:      Curves of double curvature.
               Hyperspace.
Control No.:   5962457

Author:        Autonne, Léon, 1859-1916.
Title:         Sur la représentation des courbes gauches
                  algébriques et sur le nombre des conditions qui expriment
                  qu'une courbe algébrique est située sur une surface
                  algébrique,
Published:     Paris, G. Masson, 1896.
Description:   2 p.l., 37 p. 24 cm.
LC Call No.:   QA581.A93
Subjects:      Curves of double curvature.
               Curves on surfaces.
Control No.:   5872214

Author:        Baule, Anton, 1850- [from old catalog]
Title:         Ueber raumcurven sechster ordnung ...
Published:     Göttingen, Druck von E. A. Huth, 1872.
Description:   46 p. 21 cm.
LC Call No.:   QA581.B3
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   10074635

Author:        Briggs, Garland B.
Title:         On types of knotted curves / by Garland B.
                  Briggs.
Published:     Princeton : Princeton University Press, 1927.
Description:   p. 562-586 : ill. ; 26 cm.
LC Call No.:   QA581.B7 1927
Notes:         Caption title: On types of knotted curves by J.
                  W. Alexander and G. B. Briggs.
               Thesis (Ph. D.)--Princeton University, 1927.
Subjects:      Curves of double curvature.
Control No.:   7336321

Author:        Colpitts, Elmer Clifford.
Title:         On twisted quintic curves ...
Published:     Baltimore, Md., The Lord Baltimore Press, 1907.
Description:   1 p. L., [309]-344 p. 31 x 25 cm.
LC Call No.:   QA581.C72
Notes:         Reprinted from the American Journal of
                  Mathematics, vol. XXIX, no. 4.
               Thesis (PH. D.)--Cornell university.
Subjects:      Curves of double curvature
               Curves, Quintic
Control No.:   8215392

Author:        Eichler, Carl. [from old catalog]
Title:         Uebertragung eines Steiner'schen problems aus der
                  ebene auf den raum ...
Published:     Göttingen, Druck der Dieterich'-schen
                  univ.-buchdruckerei (W. F. Kaestner) 1871.
Description:   38 p. 21 cm.
LC Call No.:   QA581.E34
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   9140502

Author:        Enders, Maximilian Adolf, 1883- [from old
                  catalog]
Title:         Über die darstellung der raumkurve vierter
                  ordnung von geschlecht 1 durch thetafunktionen ...
Published:     Halle a. d. S., Druck von E. Karras, 1906.
Description:   1 p.l., [401]-430 p., 1 l. 23 cm.
LC Call No.:   QA581.E6
Subjects:      Curves of double curvature. [from old catalog]
               Functions, Theta. [from old catalog]
Control No.:   6346055

Author:        Frauenfelder, Gustav.
Title:         Büschel von Raumkurven 4. Ordnung II. Art mit
                  zwei stationären Tangenten ...
Published:     Zürich, Druck von Züricher & Furrer, 1903.
Description:   29 p. diagrs., 2 double pl. 23 cm.
LC Call No.:   QA581.F84
Notes:         Inaug.-diss.--Zürich.
Subjects:      Curves of double curvature
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.7.
Control No.:   8669410

Author:        Haseman, Mary Gertrude, 1889-
Title:         On knots with a census of the amphicheirals with
                  twelve crossings / by Mary Gertrude Haseman.
Published:     Edinburgh : Neill, 1918.
Description:   p. [235]-255 : ill. ; 31 cm.
LC Call No.:   QA581.H3
Notes:         Thesis (Ph. D.)--Byrn Mawr College.
               From the Transactions of the Royal Society of
                  Edinburgh, v. 52 (1917).
Subjects:      Knot theory.
Control No.:   7312110

Author:        Jackstein, Hans Gottlieb Alfred, 1861-
Title:         Ausdehnung eines von Puiseux für ebene curven
                  behandelten problems auf raumcurven ...
Published:     Halle a.S., Plötz'sche buchdruckerei, R.
                  Nietschmann, 1888.
Description:   50, [4] p., 1 l. incl. diagrs. 24 cm.
LC Call No.:   QA581.J14
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Curves of double curvature.
Control No.:   6328204

Author:        Johannes, Joseph. [from old catalog]
Title:         Die rationalen raumkurven sechster ordung,
                  erzeugt durch geometrische transformation aus einem
                  kegelschnitte ...
Published:     [Neustadt a. S., Druck der Mayer'schen
                  buchdruckerei (G. Rötter) 1888]
Description:   1 p. 1., 31, [1] p. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA581.J65
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   6796405

Author:        Jolles, Stanislaus, 1857-
Title:         Die Raumcurve IV. Ordnung II. Species synthetisch
                  behandelt / von Stanislaus Jolles.
Published:     Dresden : C. Engelmann, 1883.
Description:   19, [1] p. ; 28 cm.
LC Call No.:   QA581.J75
Notes:         Thesis--Strassburg.
               Lebenslauf.
Subjects:      Curves of double curvature.
Control No.:   6327916

Author:        Kippels, Karl, 1880-
Title:         Involutorische regelscharen zweiter und
                  raumkurven dritter und vierter ordnung im geschart
                  involutorischen raum ...
Published:     Strassburg i. E., Buchdruckerei C. & J. Gœller,
                  1904.
Description:   24 p., 1 l. 23 cm.
LC Call No.:   QA581.K6
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Curves of double curvature.
               Quadrics.
Control No.:   7275945

Author:        Lange, Ernst [Julius Martin], 1858- [from old
                  catalog]
Title:         Die sechzehn wendeberührungspunkte der raumcurve
                  vierter ordnung erster species ...
Published:     Dresden, Druck von B. G. Teubner, 1882.
Description:   2 p.l., 41 p., 1 l. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA581.L27
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   9606449

Author:        Lipkin, Lipmann, 1840- [from old catalog]
Title:         Ueber die räumlichen strophoiden ...
Published:     Jena, 1870.
Description:   32 p. 21 cm.
LC Call No.:   QA581.L7
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   7732748

Author:        Lyon, Joseph, 1858-1907. [from old catalog]
Title:         Sur les courbes à torsion constante...
Published:     Paris, Gauthier-Villars et fils, 1890.
Description:   3 p.l., 70 p., 1 l. 27 cm.
LC Call No.:   QA581.L9
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   9277810

Author:        Niedermüller, H. [from old catalog]
Title:         Darstellung der stationären ebenen einer
                  allgemeinen algebraischen raumcurve ...
Published:     Rostock, C. Boldt's buchdruckerei, 1873.
Description:   27 p. 21 cm.
LC Call No.:   QA581.N6
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   9137818

Author:        Nikolai, E. L. [from old catalog]
Title:         K zadachëiìe ob uprogoæi lin¯ii dvoëiìakoæi
                  krivizny.
Published:     [s.l. : s.n.], 1916.
Description:   x, 200 p., [2] leaves of plates : ill. ; 27 cm.
LC Call No.:   QA581.N63
               Microfilm 61476 QA
Notes:         Romanized.
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   10427910

Author:        Nugteren, Gerrit Karel. [from old catalog]
Title:         Rationale ruimtekrommen va de vijfde orde ...
Published:     Groningen, J. B. Wolters, 1901.
Description:   5 p.l., 73 p. 25 cm.
LC Call No.:   QA581.N9
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   6324774

Author:        Routh, Edward John, 1831-1907.
Title:         A treatise on dynamics of a particle. With
                  numerous examples.
Published:     Cambridge, University Press, 1898.
Description:   xi, 417 p. diagrs. 23 cm.
LC Call No.:   QA581.R86
Subjects:      Dynamics of a particle.
Control No.:   8199498

Author:        Sauerbeck, Paul [Julius], 1866- [from old
                  catalog]
Title:         Über die raumkurve VI. ordnung mit vier
                  wirklichen doppelpunkten...
Published:     Tübingen, L. F. Fues'sche buchdruckerei (W.
                  Armbruster & O. Riecker) 1889.
Description:   36 p. 21 cm.
LC Call No.:   QA581.S25
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   10074763

Author:        Schafer, Alice Turner, 1916-
Title:         Two singularities of space curves ... by Alice
                  Turner Schafer ...
Published:     [n.p., 1944]
Description:   1 p.l., 655-670 p. 26 cm.
LC Call No.:   QA581.S28
Dewey No.:     516.58
Notes:         Part of thesis (PH. D.)--University of Chicago,
                  1942.
               "Reprinted from Duke mathematical journal, vol.
                  11, no. 4, December, 1944."
Subjects:      Curves of double curvature.
               Projective differential geometry.
Control No.:   2636527

Author:        Schell, Wilhelm, 1826-1904.
Title:         Wilhelm Schells allgemeine Theorie der Kurven
                  doppelter Krümmung.
Edition:       3. Aufl. neu Bearb. / von Erich Salkowski.
Published:     Leipzig ; Berlin : B.G. Teubner, 1914.
Description:   xi, 196 p. : ill. ; 23 cm.
LC Call No.:   QA581.S3 1914
Subjects:      Curves of double curvature.
Other authors: Salkowski, E. (Erich), 1881-1943, ed.
Control No.:   8241925

Author:        Schell, Wilhelm Joseph Friedrich Nikolaus,
                  1826-1904. [from old catalog]
Title:         Allgemeine theorie der curven doppelter krümmung
                  in rein geometrischer darstellung.
Published:     Leipzig, B. G. Teubner 1859.
Description:   p. cm.
LC Call No.:   QA581.S3
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   8242828

Author:        Timerding, Heinrich Carl Franz Emil, 1873- [from
                  old catalog]
Title:         Über die kugeln, welche eine cubische raumcurve
                  mehrfach oder mehrpunktig berühren ...
Published:     Strassburg, Strassburger druckerei und
                  verlagsanstalt vorm. R. Schultz & co, 1894.
Description:   43 p. 24 cm.
LC Call No.:   QA581.T58
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   7732872

Author:        Weyr, Eduard, 1852-1903. [from old catalog]
Title:         Ueber algebraische raumcurven ...
Published:     Prag, Selbstverlag, 1873.
Description:   27 p. 31 cm.
LC Call No.:   QA581.W5
Subjects:      Curves of double curvature.
Control No.:   7264659

Author:        Winzer, Julius [August], 1859- [from old
                  catalog]
Title:         Analytische entwickelung der raumcurve dritter
                  ordnung aus ihren drei reellen brennstrahlen und weitere
                  behandlung einer speciellen raumcurve dritter ordnung ...
Published:     Leipzung, Druck von A. Mehnert, 1888.
Description:   p. cm.
LC Call No.:   QA581.W79
Subjects:      Curves of double curvature. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9137943

Author:        Wood, P. Worsley (Philip Worsley)
Title:         The twisted cubic, with some account of the
                  metrical properties of the cubical hyperbola.
Published:     New York, Hafner Pub. Co. [1960]
Description:   78 p. illus. 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics, no. 14
LC Call No.:   QA581.W8 1960
Dewey No.:     516.5
Subjects:      Curves of double curvature.
               Curves, Cubic.
Control No.:   7957688

Author:        Wood, P. Worsley (Philip Worsley)
Title:         The twisted cubic, with some account of the
                  metrical properties of the cubical hyperbola, by P. W. Wood.
Published:     Cambridge, University Press, 1913.
Description:   x, 78 p. diagrs. 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics, no. 14
LC Call No.:   QA581.W8
Notes:         "Bibliographical note": p. [73]
Subjects:      Curves of double curvature.
               Curves, Cubic.
Control No.:   7766564

Author:        Wylie, Clarence Raymond, 1911- [from old
                  catalog]
Title:         Space curves belonging to a non-special linear
                  line complex ...
Published:     [Baltimore, 1935]
Description:   p. 937-942. 24 cm.
LC Call No.:   QA581.W9 1934
Subjects:      Curves of double curvature. [from old catalog]
Control No.:   7832445
