#+STARTUP: showeverything logdone
#+options: num:nil


Author:        Battin, Isaac Lucius, 1903-
Title:         On the use of triangular nets and generalized
                  differences in the solution of the first boundary value
                  problem for the Laplace equation in the plane.
Published:     New York, New York University, 1952.
Description:   21 p. diagrs. 23 cm.
LC Call No.:   QA405.B3
Notes:         Abridgment of thesis-New York University.
               Bibliography: p. 20-21.
Subjects:      Harmonic functions.
Other titles:  Boundary value problem.
Control No.:   8395725

Author:        Evans, Griffith Conrad, 1887-
Title:         Lectures on multiple valued harmonic functions in
                  space.
Published:     Berkeley, University of California Press, 1951.
Description:   281-340 p. 26 cm.
Series:        University of California publications in
                  mathematics, new ser., v. 1,no. 8
LC Call No.:   QA1.C3 n.s., vol. 1, no. 8
Dewey No.:     517.35
Notes:         "List of citations": p. 340.
Subjects:      Harmonic functions.
Series Entry:  California. University. University of California
                  publications in mathematics. new ser. ; v. 1, no. 8.
Control No.:   6027968

Author:        Farrell, Orin J.
Title:         Solved problems: gamma and beta functions,
                  Legendre polynomials, Bessel functions, by Orin J. Farrell
                  and Bertram Ross.
Published:     New York, Macmillan [1963]
Description:   410 p. illus. 21 cm.
LC Call No.:   QA405.F3
Dewey No.:     517.3
Notes:         Includes bibliography.
Subjects:      Harmonic functions.
               Gamma functions.
Other authors: Ross, Bertram, joint author.
Control No.:   9850543

Author:        Flammer, Carson.
Title:         Spheroidal wave functions.
Published:     Stanford, Calif., Stanford University Press,
                  1957.
Description:   ix, 220 p. diagrs., tables. 26 cm.
Series:        A Stanford Research Institute monograph
LC Call No.:   QA405.F55
Dewey No.:     517.35
Notes:         "The basis for this monograph was work done at
                  Stanford Research Institute for the United States Air Force
                  Cambridge Research Center under Contract AF 19 (604)-1296."
               Bibliography: p. 82-84.
Subjects:      Spheroidal functions.
Control No.:   2165318

Author:        Miles, Ernest Percy, 1919-
Title:         Certain properties of functions harmonic within a
                  sphere.
Published:     [Lancaster, Pa., n.p., 1951]
Description:   213-221 p. 24 cm.
LC Call No.:   QA405.M5
Notes:         Cover title.
               Part of thesis--Duke University.
               "Reprinted from the Proceedings of the American
                  Mathematical Society, vol. 2, no. 2 ... April, 1951."
               Bibliography: p. 220-221.
Subjects:      Harmonic functions.
Control No.:   10266442

Author:        Radó, Tibor, 1895-1965.
Title:         Subharmonic functions.
Published:     New York, Chelsea Pub. Co., 1949.
Description:   iv, 56 p. 23 cm.
Series:        Ergebnisse der Mathematik und ihrer Grenzgebiete,
                  5. Bd., 1
LC Call No.:   QA405.R3 1949
Dewey No.:     517.35
Notes:         Bibliography: p. 54-56.
Subjects:      Harmonic functions.
Control No.:   7425379

Author:        Schou, Erik, 1873-
Title:         Analytiske studier over harmoniske funktioner med
                  tre variable, af Erik Schou.
Published:     København, J. Frimodt, 1912.
Description:   xii, 126 p. 26 cm.
LC Call No.:   QA405.S35 1912
Dewey No.:     517.35
Notes:         Thesis--Copenhagen.
Subjects:      Spherical harmonics.
Other titles:  Harmoniske funktioner med tre variable.
Control No.:   8286120

Author:        Seward, Donald Monfort, 1905- [from old catalog]
Title:         Harmonic continuation in space,
Published:     [n. p., 1944]
Description:   255-267 p. 25 cm.
LC Call No.:   QA405.S4
Subjects:      Harmonic functions. [from old catalog]
               Spherical harmonics. [from old catalog]
Control No.:   10205504

Author:        Shortley, George Hiram, 1910- [from old catalog]
Title:         Numerical solution of axisymmetrical problems,
Published:     Columbus, College of Engineering, Ohio State
                  Univ., 1947.
Description:   viii, 21 p. illus. 23 cm.
LC Call No.:   QA405.S427
Subjects:      Harmonic functions. [from old catalog]
Series Entry:  Ohio. State University. Columbus. Engineering
                  Experiment Station. Bulletin no. 128. [from old catalog]
               Ohio. State University. Columbus Engineering
                  series, v. 16, no. 2. [from old catalog]
Control No.:   7877677

Author:        Shortly, George Hiram, 1910-
Title:         Numerical solution of Laplace's and Poisson's
                  equations with applications to photoelasticity and torsion,
                  by George H. Shortley, Royal Weller [and] Bernard Fried.
Published:     Columbus, College of Engineering, the Ohio State
                  University, 1940.
Description:   51 p. illus.
Series:        The Ohio State University, the Engineering
                  Experiment Station. Bulletin no. 107. September, 1940
               Ohio State University studies. Engineering
                  series. vol. IX, no. 5. September, 1940
LC Call No.:   QA405.S43
Notes:         "The material ... has appeared in three articles
                  ... [in] Journal of applied physics, 9, 334-338 (1938).
                  Journal of applied mechanics, 6, A-71-A-78 (1939). Journal of
                  applied physics, 11, 283-290 (1940)."--Foreword.
Subjects:      Harmonic functions.
               Photoelasticity.
               Torsion.
Other authors: Weller, Royal, joint author.
               Fried, Bernard, joint author.
Series Entry:  Ohio State University. Engineering series. v. IX,
                  no. 5.
Series Entry:  Bulletin (Ohio State University. Engineering
                  Experiment Station : 1963) ; no. 107.
Control No.:   5975114

Author:        Stratton, Julius Adams, 1901-
Title:         Spheroidal wave functions, including tables of
                  separation constants and coefficients, by J.A. Stratton [and
                  others].
Published:     New York, Published jointly by the Technology
                  Press of M.I.T. and Wiley [c1956]
Description:   xiii, 613 p. tables. 29 cm.
LC Call No.:   QA405.S8
Dewey No.:     530.1
Notes:         Includes bibliographies.
Subjects:      Wave mechanics.
               Spheroidal functions.
Control No.:   2164832

Author:        United States. Aerospace research Laboratories,
                  Wright-Patterson Air Force Base, Ohio. [from old catalog]
Title:         Tables relating to the radial mathieu functions.
Published:     Washington, For sale by the Superintendent of
                  Documents, U. S. Govt. Print. Off. [1962-65]
Description:   2 v. 27 cm.
LC Call No.:   QA405.U5
Subjects:      Mathieu functions.
Control No.:   7512888

Author:        Banning, Rudolf, 1865- [from old catalog]
Title:         Ueber kugel- und cylinderfunktionen und deren
                  kettenbruchentwickelung ...
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1894.
Description:   33, [1] p., 1 l. 22 cm.
LC Call No.:   QA406.B2
Subjects:      Spherical harmonics.
               Bessel functions.
Control No.:   6793107

Author:        Dressel, Francis George, 1914-
Title:         A boundary value problem for the heat equation,
                  by F. G. Dressel ...
Published:     [Baltimore, n.p., 1933]
Description:   p. 641-653. 25 cm.
LC Call No.:   QA406.D7 1933
Notes:         Cover-title.
               Thesis (Ph. D.)--Duke university, 1933.
               Thesis note on p. 641.
               "Reprinted from American jouranl of mathematics,
                  vol. LV, no. 4, October, 1933."
Subjects:      Differential equations, Partial.
               Integral equations.
Control No.:   7367955

Author:        Dressel, Francis George, 1914-
Title:         A class of solutions for the heat equation and
                  associated boundary value problems, by F.G. Dressel and E. R.
                  Elliot ...
Published:     [N .p., n.p., 1943]
Description:   408-422 p. 25 cm.
LC Call No.:   QA406.D72
Notes:         Cover-title.
               "The results of part 1 of this paper are taken
                  from E. R. Elliot's doctral dissertation [Ph. D.] ... Duke
                  University [1935]"
               "Reprinted from American journal of mathematics,
                  vol. LXV, no. 3, July. 1943.
               Bibliographical footnotes.
Subjects:      Differential equations, Partial.
               Integral equations.
Other authors: Elliott, Emmet, 1908-
Other titles:  Heat equation.
Control No.:   8331621

Author:        Ferrers, N. M. (Norman Macleod), 1829-1903.
Title:         An elementary treatise on spherical harmonics and
                  subjects connected with them. By the Rev. N.M. Ferrers ...
Published:     London, Macmillan and co., 1877.
Description:   xi, [1], 160 p. diagr. 20 cm.
LC Call No.:   QA406.F38
Subjects:      Spherical harmonics.
Control No.:   4525340

Author:        Frobenius, Ferdinand Georg, 1849-1917.
Title:         De functionum analyticarum unius variabilis per
                  series infinitas repraesentatione ... Von Georgius Frobenius
                  ...
Published:     Berolini, typis A.W. Schadii [1870]
Description:   2 p.l., 36 p. 21 cm.
LC Call No.:   QA406.F92
Dewey No.:     515/.2433 19
Notes:         Inaug.-diss.--Berlin.
               Vita.
Subjects:      Spherical harmonics.
Control No.:   1689250

Author:        Gumprecht, R. O. (Roland Oscar), 1919-
Title:         Tables of functions of first and second partial
                  derivatives of Legendre polynomials, prepared by R. O.
                  Gumprecht [and] C. M. Sliepcevich.
Published:     [Ann Arbor] Engineering Research Institute,
                  University of Michigan, 1951.
Description:   xii, 310 p. 24 cm.
Series:        University of Michigan. Engineering Research
                  Institute. Special publications: tables
LC Call No.:   QA406.G8
Dewey No.:     517.35 518.2
Notes:         Bibliography: p. xii.
Subjects:      Legendre's polynomials.
Other authors: Sliepcevich, C. M. (Cedomir M.), 1920- joint
                  author.
Series Entry:  Special publications (University of Michigan.
                  Engineering Research Institute). Tables.
Control No.:   4055743

Author:        Heine, Eduard, 1821-1881.
Title:         Handbuch der Kugelfunctionen, Theorie und
                  Anwendungen, von Dr. E. Heine ...
Edition:       2. umgearb. und verm. Aufl.
Published:     Berlin, G. Reimer, 1878-81.
Description:   2 v. diagrs. 24 cm.
LC Call No.:   QA406.H55 1878
Notes:         I. Bd. Theorie der Kugelfunctionen und der
                  Verwandten Functionen.--II. Bd. Anwendungen der
                  Kugelfunctionen und der Verwandten Functionen.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Spherical harmonics.
Other titles:  Kugelfunctionen, Handbuch der.
Control No.:   9682722

Author:        Heun, Karl, 1859-
Title:         Die kugelfunctionen und Lamé'schen functionen
                  als determinanten ...
Published:     Göttingen, Druck der Dieterichschen
                  univ.-buchdruckerei, 1881.
Description:   iv, 32 p., 1 l. 27 x 21 cm.
LC Call No.:   QA406.H6
Notes:         Inaug.-dis.--Göttingen.
               Vita.
Subjects:      Spherical harmonics.
               Lamé's functions.
Control No.:   744889

Author:        Hille, Einar, 1894-
Title:         Some problems concerning spherical harmonics / by
                  Einar Hille.
Published:     Stockholm : Almqvist & Wiksells Boktryckeri,
                  1918.
Description:   76 p. : ill. ; 22 cm.
Series:        Arkiv för matematik, astronomi och fysik ; bd.
                  13, n:o 17
LC Call No.:   QA406.H54x 1918
Notes:         Includes bibliographical references.
Subjects:      Spherical harmonics.
Control No.:   1456208

Author:        Hsü, Hsien-yü, 1910- [from old catalog]
Title:         Certain integrals and infinite series involving
                  ultraspherical polynomials and Bessel functions ...
Published:     St. Louis, Washington university [1938]
Description:   cover-title, p. 374-383. 25 cm.
LC Call No.:   QA406.H85 1938
Subjects:      Spherical harmonics.
               Bessel functions.
Control No.:   7375698

Author:        Huss, Joseph, 1880-
Title:         Über eine anwendung der theorie der linearen
                  differentialgleichungen auf die differentialgleichung der
                  kugelfunctionen einer variablen ...
Published:     Greifswald, Druck von F.W. Kunike, 1903.
Description:   2 p.l., 18 p. 23 cm.
LC Call No.:   QA406.H97
Notes:         Inaug.-dis.--Greifswald.
               Lebenslauf.
Subjects:      Spherical harmonics.
               Differential equations, Linear.
Control No.:   272637

Author:        Neumann, F. E. (Franz Ernst), 1798-1895.
Title:         Vorlesungen über die Theorie des Potentials und
                  der Kugelfunctionen; gehalten an der Universität Königsberg
                  von dr. Franz Neumann. Hrsg. von Carl Neumann. Mit Figuren im
                  Text.
Published:     Leipzig, B.G. Teubner, 1887.
Description:   xvi, 364 p. diagrs. 25 cm.
Series:        Vorlesungen über mathematische
                  physik...von...Neumann. [6. hft.]
LC Call No.:   QA406.N5
Subjects:      Potential theory (Mathematics)
               Harmonic analysis.
Other authors: Neumann, Karl Gottfried, 1832-1925, ed.
Control No.:   10070757

Author:        Olbricht, Richard, 1859-
Title:         Studien über die Kugel- und Cylinderfunctionen
                  ...
Published:     Halle, 1887.
Description:   1 p. l., 48 p., 1 l. 2 fold. pl. 32 cm.
LC Call No.:   QA406.O43
Notes:         Inaug.-diss.--Leipzig.
               Lebenslauf.
Subjects:      Spherical harmonics.
               Bessel functions.
Control No.:   5858701

Author:        Rudin, Walter, 1921-
Title:         [Uniqueness theory for Laplace series.]
Published:     [N.p. n.p. 1950]
Description:   2 pts. 28 cm.
LC Call No.:   QA406.R8
Notes:         Based on thesis-Duke University.
               Title from original thesis. Part 1 has special t.
                  p.; part 2 has cover title.
               "Reprinted from the Transactions of the American
                  Mathematical Society, vol. 68, no. 2 ... March 1950."
               Bibliography at end of each part.
               [pt. 1] Integral representation of continuous
                  functions.--[pt. 2] Uniqueness theory for Laplace series.
Subjects:      Harmonic functions.
               Spherical harmonics.
Control No.:   9304970

Author:        Thomé, Ludwig Wilhelm, 1841- [from old catalog]
Title:         De seriebus secundum functiones, quae vocantur
                  sphaericae, progredientibus ...
Published:     Berolini, typis C. Schultze [1865]
Description:   21, [1] p., 1 l. 25 cm.
LC Call No.:   QA406.T46
Subjects:      Spherical harmonics. [from old catalog]
Control No.:   5860301

Author:        United States. National Bureau of Standards.
                  Computation Laboratory.
Title:         Tables of associated Legendre functions. Prepared
                  by the Mathematical tables project, conducted under the
                  sponsorship of the National bureau of standards. Present
                  volume begun under the auspices of the Work projects
                  administration of the city of New York and completed with the
                  support of the Office of scientific research and development.
                  Lyman J. Briggs, director, National bureau of standards,
                  official sponsor. Arnold N. Lowan, project director,
                  Mathematical tables project.
Published:     New York, Columbia university press, 1945.
Description:   xlvi, 303, [3] p. 28 cm.
LC Call No.:   QA406.U5 1945
Dewey No.:     517.35
Notes:         Reproduced by a photo offset process.
               "Tables prepared by the Mathematical tables
                  project": [3] p. at end.
               Bibliography: p. xxxv-xlvi.
Subjects:      Legendre's functions.
Control No.:   2636541

Title:         Table of the Bessel functions Jb0s(Z) and
                  Jb1s(Z) for complex arguments. Prepared by the Mathematical
                  Tables Project, National Bureau of Standards.
Edition:       2d ed.
Published:     New York, Columbia University Press, 1947.
Description:   xliv, 403, [4] p. diagrs. 28 cm.
LC Call No.:   QA408.U5 1947
Dewey No.:     515/.53
Notes:         "Tables": [4] p. at end.
               Bibliography: p. [xxxv]-xliv.
Subjects:      Bessel functions -- Tables.
               Mathematics -- Tables.
Control No.:   2636675

Author:        Anding, E. (Ernst), 1860-
Title:         Sechsstellige tafeln der Bessel'schen funktionen
                  imaginären argumentes, von prof. dr. E. Anding ...
Published:     Leipzig, W. Engelmann, 1911.
Description:   2 p.l., 72 p. 30 cm.
LC Call No.:   QA408.A6
ISBN:          DM00.70
Subjects:      Bessel functions -- Tables.
Control No.:   2161844

Author:        Bowman, Frank, 1891-
Title:         Introduction to Bessel functions, by F. Bowman.
Published:     London, New York, Longmans, Green [1938]
Description:   x, 134 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA408.B68
Dewey No.:     517.35
Notes:         "First published in 1938."
Subjects:      Bessel functions.
Control No.:   5970862

Author:        Cambi, Enzo.
Title:         Eleven and fifteen-place tables of Bessel
                  functions of the first kind, to all significant orders.
Published:     New York, Dover Publications [1948]
Description:   vi, 154 p. 28 cm.
LC Call No.:   QA408.C3
Dewey No.:     517.35
Notes:         Bibliography: p. 154.
Subjects:      Bessel functions -- Tables.
Control No.:   2636791

Author:        Cohen, Louis, 1876- [from old catalog]
Title:         Note on the approximate values of Bessel's
                  functions for large arguments,
Published:     [Washington, Govt. print. off., 1908]
Description:   227-230 p. 26 cm.
LC Call No.:   QA408.C7
Subjects:      Bessel functions.
Other authors: United States. Bureau of standards. Reprint no.
                  100. [from old catalog]
Control No.:   5876682

Author:        Crelier, Louis.
Title:         Sur quelques propriétés des fonctions
                  Besséliennes tirées de la théories des fractions continues
                  ...
Published:     Milan, Imp. Bernardoni de C. Rebeschini et c.e,
                  1896.
Description:   xxii p., 1 l., 31 p. 29 cm.
LC Call No.:   QA408.C9
Notes:         Thèse--Univ. de Bern.
               From "Annali di matematica, tome XXIV, à Milan
                  (1896)."
Subjects:      Bessel functions.
Control No.:   8666253

Author:        Dannacher, Simon.
Title:         Zur Theorie der Funktionen des elliptischen
                  Zylinders / von Simon Dannacher.
Published:     Frauenfeld : Huber, 1906.
Description:   38 p. : ill. ; 27x21 cm.
LC Call No.:   QA408.D2
Notes:         Inaug.-diss.--Universität Zürich.
               "Literatur":  p. 38.
Subjects:      Bessel functions.
Control No.:   9150623

Author:        Gray, Andrew, 1847-1925.
Title:         A treatise on Bessel functions and their
                  applications to physics, by Andrew Gray ... and G.B. Mathews
                  ...
Edition:       2d ed. prepared by A. Gray and T.M. MacRobert
                  ...
Published:     London, Macmillan and co., limited, 1922.
Description:   xiv, 327 p. diagrs. 23 cm.
LC Call No.:   QA408.G8 1922
Notes:         Bibliography: p. 318-322.
Subjects:      Bessel functions.
               Mathematical physics.
Other authors: Mathews, G. B. (George Ballard), 1861-1922, joint
                  author.
               MacRobert, Thomas Murray, 1884-1962, ed.
Control No.:   4053452

Author:        Gray, Andrew, 1847-1925. [from old catalog]
Title:         A treatise on Bessel functions and their
                  applications to physics.
Published:     London and New York, Macmillan and co., 1895.
Description:   x, 291, [1] p. vi tab., diagrs. 23 cm.
LC Call No.:   QA408.G8
               Microfilm 19168 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Bessel functions.
               Mathematical physics.
Other authors: Mathews, G. B. (George Ballard), 1861-1922, joint
                  author.
               Meissel, Ernst, 1826-1895. [from old catalog]
Control No.:   7260893

Author:        Gumprecht, R. O. (Roland Oscar), 1919-
Title:         Tables of Riccati Bessel functions for large
                  arguments and orders, prepared by R. O. Gumprecht [and] C.M.
                  Sliepcevich.
Published:     [Ann Arbor, Engineering Reserach Institute,
                  University of Michigan, 1951.
Description:   xvi, 260. 24 cm.
Series:        University of Michigan. Engineering Research
                  Institute. Special publications: tables
LC Call No.:   QA408.G85
Dewey No.:     517.35 518.3
Notes:         Bibliography: p. xvi.
Subjects:      Bessel functions -- Tables.
Other authors: Sliepcevich, C. M. (Cedomir M.), 1920- joint
                  author.
Series Entry:  Special publications (University of Michigan.
                  Engineering Research Institute). Tables.
Control No.:   748367

Author:        Koestler, Waldemar Karl Ernst, 1875-
Title:         Beiträge zu Reihen-entwicklungen nach
                  Bessel'schen Zylinderfunktionen ...
Published:     Bern, Buchdr. Berger & Albrecht, 1907.
Description:   110 p., 1 l. 24 cm.
LC Call No.:   QA408.K7
Notes:         Inaug.-diss.--Bern.
Subjects:      Bessel functions.
Control No.:   5879273

Author:        Kummer, M.
Title:         Darlegung der Weber'schen und verwandter
                  Integrale : ihre Theorie und Anwendung / von M. Kummer.
Published:     Bern : K. J. Wyss, 1902.
Description:   63, [1] p. ; 23 cm.
LC Call No.:   QA408.K96
Notes:         Inaug.-diss.--Bern.
               "Benutzte litteratur":  1 p. at end.
Subjects:      Bessel functions.
Control No.:   8201272

Author:        Luke, Siu-kay. [from old catalog]
Title:         Bessel functions of imaginary order and imaginary
                  argument
Published:     [College Park] University of Maryland, Institute
                  for Molecular Physics, [available from U. S. Dept. of
                  Commerce, Technical Services, Washington]
Description:   8 l., [77] l. of tables. 28 cm.
LC Call No.:   QA408.L85
Subjects:      Bessel functions.
Other authors: Weissman, Stanley, [from old catalog] joint
                  author.
Other authors: Maryland. University. Institute of Molecular
                  Physics. [from old catalog]
Control No.:   7130157

Author:        Luke, Yudell L.
Title:         Integrals of Bessel functions.
Published:     New York, McGraw-Hill [1962]
Description:   419 p. 24 cm.
LC Call No.:   QA408.L8
Dewey No.:     517.353
Subjects:      Bessel functions.
               Integrals.
Control No.:   750702

Author:        Moore, Charles N. (Charles Napoleon), 1882-
Title:         The summability of the developments in Bessel
                  functions : with applications / by Charles N. Moore.
Published:     New York : [s.n.], 1909.
Description:   p. 391-435 ; 28 cm.
LC Call No.:   QA408.M7
Notes:         Cover-title.
               "Reprinted from the Transactions of the American
                  mathematical society, vol. X, no. 4, pp. 391-435."
Subjects:      Bessel functions.
Control No.:   6355482

Author:        Nielsen, Niels, 1865-1931.
Title:         Handbuch der theorie der cylinderfunktionen, von
                  Dr. Niels Nielsen ...
Published:     Leipzig, B. G. Teubner, 1904.
Description:   xii, 408 p. 25 cm.
LC Call No.:   QA408.N6
Notes:         "Literaturverzeichnis": p. [389]-404.
Subjects:      Bessel functions.
Control No.:   6802997

Author:        Onoe, Morio.
Title:         Tables of modified quotients of Bessel funcions
                  of the first kind for real and imaginary arguments.
Published:     New York, Columbia University Press, 1958.
Description:   338 p. 28 cm.
LC Call No.:   QA408.O5
Dewey No.:     517.35 518.3*
Subjects:      Bessel functions -- Tables.
Control No.:   2638468

Author:        Otti, Hans. [from old catalog]
Title:         Eigenschaften der Bessel'schen funktionen zweiter
                  art...
Published:     Bern, Buchdr. K. J. Wyss, 1899.
Description:   1 p. l., 57 p. 23 cm.
LC Call No.:   QA408.O9
Subjects:      Bessel functions.
Control No.:   7722424

Author:        Schafheitlin, Paul, 1861-1924.
Title:         Die theorie der Besselschen funktionen, von prof.
                  dr. Paul Schafheitlin ... mit einer figurentafel.
Published:     Leipzig, Berlin, B.G. Teubner, 1908.
Description:   v, 129, [1] p. fold. diagr. 21 cm.
Series:        Mathematisch-physikalische schriften für
                  ingenieure und studierende ... 4
LC Call No.:   QA408.S3
Subjects:      Bessel functions.
Series Entry:  Mathematisch-physikalische Schriften für
                  Ingenieure und Studierende ; 4.
Control No.:   4053055

Author:        Stevenson, Guy, 1892-
Title:         Expansions of the Neumann type in terms of
                  products of Bessel functions / by Guy Stevenson.
Published:     Urbana, Ill., [1928]
Description:   p. 569-590 ; 25 cm.
LC Call No.:   QA408.S7
Notes:         Vita.
               Reprinted from the American journal of
                  mathematics, v. 50, no. 4, Oct. 1928.
               Thesis (Ph. D.)--University of Illinois, 1926.
Subjects:      Bessel functions.
Control No.:   8742832

Author:        United States. National Bureau of Standards.
                  Computation Laboratory.
Title:         Table of the Bessel functions Yb0s(z) and
                  Yb1s(z) for complex arguments.
Published:     New York, Columbia University Press, 1950.
Description:   xi, 427 p. 28 cm.
LC Call No.:   QA408.U5 1950
Dewey No.:     517.35
Subjects:      Bessel functions -- Tables.
Control No.:   2164297

Author:        United States. National Bureau of Standards.
                  Computation Laboratory.
Title:         Tables of spherical Bessel functions. Prepared by
                  the Mathematical Tables Project, National Bureau of
                  Standards.
Published:     New York, Columbia University Press, 1947.
Description:   2 v. 28 cm.
LC Call No.:   QA408.U5 1947a
Dewey No.:     517.35
Subjects:      Bessel functions -- Tables.
Control No.:   4054956

Author:        United States. National bureau of standards.
                  Computation laboratory. [from old catalog]
Title:         A short table of spherical Bessel functions to
                  five significant figures.
Published:     [New York, 1941?]
Description:   2 p l., 9 numb. l. 33 cm.
LC Call No.:   QA408.U48
Subjects:      Bessel functions.
Control No.:   6450817

Author:        Wagner, Karl. [from old catalog]
Title:         Beiträge zur entwicklung der Bessel'schen
                  funktion I. art. ...
Published:     Bern, Buchdruckerei K. J. Wyss, 1894.
Description:   65 p. 23 cm.
LC Call No.:   QA408.W13
               Microfilm 21948 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Bessel functions.
Control No.:   5856887

Author:        Bôcher, Maxime, 1867-1918.
Title:         Ueber die Reihenentwickelungen der
                  Potentialtheorie ...
Published:     Göttingen, Dieterich'sche univ.-buchdr. (W.F.
                  Kaestner) 1891.
Description:   iv, 66 p., 1 l. diagrs. 29 x 23 cm.
LC Call No.:   QA409.B66
Notes:         Inaug.-diss.--Göttingen.
               Lebenslauf.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Lamé's functions.
               Potential theory (Mathematics)
               Cyclide.
Control No.:   8669761

Author:        Chittenden, J. Brace (Jonathan Brace), 1864-
Title:         A presentation of the theory of Hermite's form of
                  Lamé's equation : with a determination of the explicit forms
                  in terms of the p function for the case n equal to three / by
                  J. Brace Chittenden.
Published:     Leipzig : B. G. Teubner, 1893.
Description:   88 p. ; 24 cm.
LC Call No.:   QA409.C54
Notes:         "Table of forms n=3": p. [79]-85.
               Vita.
               Inaug.-diss.--Königsberg.
Subjects:      Lamé's functions.
Control No.:   9134485

Author:        Cohn, Fritz, 1866- [from old catalog]
Title:         Über Lamésche funktionen mit komplexen
                  parametern ...
Published:     Königsberg, Hartungsche buchdruckerei, 1888.
Description:   2 p.l., 49, [3] p. 21 cm.
LC Call No.:   QA409.C67
Subjects:      Lamé's functions.
Control No.:   7261279


Author:        Doormann, Karl, 1858- [from old catalog]
Title:         Anwendung der Lamé'schen functionen auf probleme
                  der potentialtheorie bezüglich des dreiaxigen ellipsoids und
                  der Fresnel'schen elasticitätsfläche ...
Published:     Leipzig, Druck von B. G. Teubner, 1882.
Description:   p. cm.
LC Call No.:   QA409.D7
Subjects:      Lamé's functions.
               Attractions of ellipsoids.
Control No.:   6328264

Author:        Haentzschel, Emil [Esaias Rudolf], 1858- [from
                  old catalog]
Title:         Ueber die reduktion der gleichung
                  [delta]p2sV/[delta]xp2s+[delta]p2sV/[delta]yp2s+[delta]p2sV/[delta]zp2s=0
                  auf gewöhnliche differentialgleichungen. Ein beitrag zur
                  theorie der Lamé'schen funktionen 2. ordnung ...
Published:     Berlin, Buchdruckerei von G. Schade, 1883.
Description:   47, [1] p. 22 cm.
LC Call No.:   QA409.H13
Notes:         Vita.
               Inaug.-diss.--Jena.
               "Bibliographie": p. [46]-47.
Subjects:      Lamé's functions.
Control No.:   6802853

Author:        Palmström, Arnfinn, 1867- [from old catalog]
Title:         Sur l'equation de Lamé ... par A. Palmström
                  ...
Published:     [Kristiania] J. Dybwad, 1895.
Description:   12 p. 27 cm.
Series:        Det Norske videnskaps-akademi i Olso. Skrifter.
                  I. Mathematisk-naturvidenskabelig klasse. 1894, no. 6 [from
                  old catalog]
LC Call No.:   AS283.O56 1894, no. 6
Subjects:      Equations, Lamé. [from old catalog]
Control No.:   7252189

Author:        Butts, William Henry.
Title:         The elliptic cylinder function of class K :
                  synthetic treatment and computation of tables / by William
                  Henry Butts.
Published:     Baltimore, Md. : The Lord Baltimore Press, 1908.
Description:   29 p. : ill. ; 31 cm.
LC Call No.:   QA411.B88
Notes:         Inaug.-diss.--Zürich.
               "Literature": p. 29.
Subjects:      Harmonic analysis.
Control No.:   9156966

Author:        Lindskog, Nat[anael], 1858- [from old catalog]
Title:         En rings rörelse i en vätska ...
Published:     Upsala, Akademiska boktryckeriet E. Berling,
                  1885.
Description:   2 p.l., 44 p. 26 cm.
LC Call No.:   QA411.L75
Subjects:      Toroidal harmonics. [from old catalog]
Control No.:   5860392

Author:        Evans, Griffith Conrad, 1887-
Title:         The logarithmic potential, discontinuous
                  Dirichlet and Neumann problems.
Published:     New York, American Mathematical Society, 1927.
Description:   viii, 150 p. diagrs. 24 cm.
Series:        American Mathematical Society. Colloquium
                  publications, v. 6
LC Call No.:   QA425.E8
Subjects:      Integral equations.
               Potential theory (Mathematics)
               Differential equations.
Series Entry:  Colloquium publications (American Mathematical
                  Society) ; v. 6.
Control No.:   9210531

Author:        Hecke, Erich, 1887-1947.
Title:         Lectures by Erich Hecke on Dirichlet series,
                  modular functions and quadratic form ; spring term, 1938 /
                  Notes by Hyman Serbin.
Published:     Ann Arbor, Mich., Edwards brothers, inc., 1938.
Description:   2 p. leaves, 48 p. ; 27 cm.
LC Call No.:   QA425.H4
Notes:         At head of title: The Institute for advanced
                  study.
               Planographed.
               Bibliography: p.48.
Subjects:      Dirichlet series.
               Modular functions.
               Forms, Quadratic.
Other authors: Serbin, Hyman.
Other authors: Institute for Advanced Study (Princeton, N.J.)
Control No.:   8316601

Author:        Kampé de Fériet, Joseph, 1893-
Title:         Generalized harmonic analysis and some boundary
                  value problems [lectures] given 1951-1952, Prepared by S. I.
                  Pai.
Published:     New York, Stevens & Co., [195-?]
Description:   103 l. diagrs.
Series:        Lecture series, no. 12
LC Call No.:   QA425.K3
Notes:         Bibliography: l. 102-103.
Subjects:      Harmonic analysis.
               Generalized spaces.
Control No.:   7454839

Author:        Raynor, George E. (George Emil), 1895-
Title:         Dirichlet's problem / by George E. Raynor.
Published:     Lancaster, Pa. : Press of the New Era Printing
                  Company, 1923.
Description:   p. [183]-197 ; 26 cm.
LC Call No.:   QA425.R3
Notes:         Cover title.
               "Reprinted from Annals of mathematics, vol.
                  XXIII., no. 3, March, 1922."
               Thesis (Ph. D.)--Princeton University, 1923.
Subjects:      Dirichlet problem.
Control No.:   5918572

Author:        International Symposium on Nonlinear Differential
                  Equations and Nonlinear Mechanics (1961 : Colorado Springs,
                  Colo.)
Title:         International Symposium on Nonlinear Differential
                  Equations and Nonlinear Mechanics; [proceedings] edited by
                  Joseph P. LaSalle and Solomon Lefschetz.
Published:     New York, Academic Press, 1963.
Description:   xiv, 505 p. diagrs. 24 cm.
LC Call No.:   QA427.I5 1961
Dewey No.:     517.382
Notes:         The symposium was held at the U.S. Air Force
                  Academy, and was sponsored by the Air Force Office of
                  Scientific Research and RIAS.
               Includes bibliographies.
Subjects:      Differential equations, Nonlinear -- Congresses.
               Nonlinear mechanics -- Congresses.
Other authors: LaSalle, Joseph P., ed.
               Lefschetz, Solomon, 1884-1972, ed.
Other authors: United States Air Force Academy.
               United States. Air Force. Office of Scientific
                  Research.
               Research Institute for Advanced Study (Baltimore,
                  Md.)
Control No.:   3113024

Author:        Barrett, Leonard Lovering, 1890-
Title:         An introduction to tensor analysis.
Published:     Palo Alto, Ca., National Press [1956]
Description:   33 p. 22 cm.
LC Call No.:   QA433.B36
Dewey No.:     517.2
Subjects:      Calculus of tensors.
Control No.:   9339578

Author:        Bickley, W. G. (William Gee)
Title:         Via vector to tensor; an introduction to the
                  concepts and techniques of the vector and tensor calculus
                  [by] W.G. Bickley [and] R.E. Gibson.
Edition:       [1st ed.].
Published:     New York, Wiley [1962]
Description:   152 p. illus. 23 cm.
LC Call No.:   QA433.B5
Dewey No.:     516.83
Notes:         Includes bibliography.
Subjects:      Calculus of tensors.
               Vector analysis.
Other authors: Gibson, R. E. (Robert Edward), 1901- joint
                  author.
Control No.:   3585426

Author:        Borg, Sidney F.
Title:         An introduction to matrix tensor methods in
                  theoretical and applied mechanics.
Published:     Ann Arbor, Mich., J. W. Edwards [1956]
Description:   202 p. illus. 29 cm.
LC Call No.:   QA433.B6
Dewey No.:     517.2
Subjects:      Calculus of tensors.
               Matrices.
               Mechanics.
Control No.:   7931328

Author:        Borg, Sidney F.
Title:         Matrix-tensor methods in continuum mechanics.
Published:     Princeton, N.J., Van Nostrand [1963]
Description:   313 p. illus. 23 cm.
LC Call No.:   QA433.B62
Dewey No.:     517.2
Notes:         Includes bibliography.
Subjects:      Calculus of tensors.
               Matrices.
               Continuum mechanics.
Control No.:   1695158

Author:        Carter, Hobart C. (Hobart Clinton), 1907-
Title:         Relation of Maschke's symbolic method to the
                  tensor theory / by Hobart C. Carter.
Published:     Ann Arbor, Mich. : Edwards Brothers, [1931?]
Description:   21, [1] p. ; 21 cm.
LC Call No.:   QA433.C3 1931
Notes:         Vita.
               "Photo-lithoprint reproduction of author's
                  manuscript."
               "Presented to the American mathematical society
                  December 31, 1929."
               Thesis (Ph. D.)--University of Missouri, 1931.
               Bibliography:  p. 20-21.
Subjects:      Calculus of tensors.
               Differential invariants.
Other titles:  Maschke's symbolic method.
Control No.:   5948224

Author:        Chevalley, C. (Claude), 1909-
Title:         The algebraic theory of spinors.
Published:     New York, Columbia University Press, 1954.
Description:   128 p. 24 cm.
Series:        Columbia bicentennial editions and studies
LC Call No.:   QA433.C4
Dewey No.:     517.2
Subjects:      Spinor analysis.
Control No.:   9323213

Author:        Churchill, Ruel Vance, 1899-
Title:         On the geometry of the Riemann tensor, by R. V.
                  Churchill.
Published:     [New York, 1932]
Description:   [1], 126-152 p. 28 cm.
LC Call No.:   QA433.C5 1929
Dewey No.:     517.2
Notes:         "Reprinted from the Transactions of the American
                  mathematical society, vol. 34, no. 1."
               Thesis (Ph. D.)--University of Michgian, 1929.
Subjects:      Calculus of tensors
Control No.:   7817158

Author:        Givens, James Wallace, 1910-
Title:         Tensor coördinates of linear spaces, by James
                  Wallace Givens, jr.
Published:     Princeton, 1937.
Description:   355-385 26 cm.
LC Call No.:   QA433.G5 1936
Notes:         cover-title.
               "Reprinted from Annals of mathematics, vol. 38,
                  no. 2."
               Thesis (Ph. D.)--Princeton University, 1936.
Subjects:      Calculus of tensors.
               Geometry, Projective.
               Generalized spaces.
Control No.:   8308665

Author:        Guiot, J. (Joseph)
Title:         Le calcul vectoriel et ses applications à la
                  géométrie réglée / par J. Guiot.
Published:     Paris : A. Hermann et fils, 1912.
Description:   128 p. : ill. ; 25 cm.
LC Call No.:   QA433.G856 1912
Notes:         BN LXVI, column 949
               Includes bibliographical references.
               LC copy is author's autograph presentation copy.
                  DLC
Subjects:      Vector analysis
Control No.:   12585604

Author:        Hawkins, George A. (George Andrew), 1907-
Title:         Multilinear analysis for students in engineering
                  and science.
Published:     New York, Wiley [1963]
Description:   xiv, 219 p. diagrs. 22 cm.
LC Call No.:   QA433.H36
Dewey No.:     517.52
Notes:         Includes bibliographies.
Subjects:      Calculus of tensors.
               Vector analysis.
Control No.:   9382536

Author:        Kron, Gabriel, 1901-1968.
Title:         A short course in tensor analysis for electrical
                  engineers, by Gabriel Kron ...
Published:     New York, J. Wiley & sons, inc; London, Chapman &
                  Hall, limited, 1942.
Description:   xv, 250 p. incl. tables, diagrs. 24 cm.
Series:        [General electric series]
LC Call No.:   QA433.K7
Dewey No.:     517.2
Notes:         "One of a series written in the interest of the
                  advanced course in engineering of the General electric
                  company."
Subjects:      Calculus of tensors.
Series Entry:  General Electric series.
Control No.:   274927

Author:        Kron, Gabriel, 1901- [from old catalog]
Uniform Title: A short course in tensor analysis for electrical
                  engineers. English. [from old catalog]
Title:         Tensors for circuits (formerly entitled A short
                  course in tensor analysis for electrical engineers)
Edition:       2d ed.
Published:     New York, Dover Publications [1959]
Description:   250 p. illus. 21 cm.
LC Call No.:   QA433.K7 1959
Subjects:      Calculus of tensors. [from old catalog]
Control No.:   7481440

Author:        Michal, Aristotle D., 1899-
Title:         Matrix and tensor calculus, with applications to
                  mechanics, elasticity, and aeronautics, by Aristotle D.
                  Michal ...
Published:     New York, J. Wiley & Sons, inc.; London, Chapman
                  & Hall, limited [1947]
Description:   xiii, 132 p. 24 cm.
Series:        Galcit aeronautical series
LC Call No.:   QA433.M45
Dewey No.:     517.2
Notes:         "Based on a series of lectures ... given under
                  the sponsorship of the Engineering, science, and management
                  war training (ESMWT) program, from August 1942 to March
                  1943."--Pref.
               "References": p. 124-127.
Subjects:      Calculus of tensors.
               Matrices.
Control No.:   9282902

Author:        Mitchell, Alfred King, 1903- [from old catalog]
Title:         The derivation of tensors from tensor functions,
Published:     [Baltimore, 1931]
Description:   1 p.l., p. 195-203, 1 l. 25 cm.
LC Call No.:   QA433.M5 1929
Subjects:      Calculus of tensors. [from old catalog]
Control No.:   6876474

Author:        Smith, Matthew S.
Title:         Principles & applications of tensor analysis.
Edition:       [1st ed.].
Published:     Indianapolis, H.W. Sams [1963]
Description:   128 p. illus. 23 cm.
Series:        A Howard W. Sams photofact publication
LC Call No.:   QA433.S63
Dewey No.:     517.2
Notes:         "TAS-1."--Dust jacket.
Subjects:      Calculus of tensors.
Control No.:   2640180

Author:        Sokolnikoff, Ivan Stephen, 1901-
Title:         Tensor analysis: theory and applications.
Published:     New York, Wiley, 1951.
Description:   ix, 335 p. diagrs. 24 cm.
Series:        Applied mathematics series
LC Call No.:   QA433.S6
Dewey No.:     517.2
Notes:         Bibliography: p. 327.
Subjects:      Calculus of tensors.
Series Entry:  Applied mathematics series (John Wiley & Sons)
Control No.:   4055549

Author:        Spain, Barry.
Title:         Tensor calculus.
Published:     London, Oliver and Boyd; New York, Interscience
                  Publishers, 1953.
Description:   125 p. 19 cm.
Series:        University mathematical texts
LC Call No.:   QA433.S65
Notes:         Bibliography: p. [122].
Subjects:      Calculus of tensors.
Control No.:   6040451

Author:        Spiegel, Murray R.
Title:         Schaum's outline of theory and problems of vector
                  analysis and an introduction to tensor analysis / by Murray
                  R. Spiegel.
Published:     New York : McGraw-Hill, [2002?], c1959.
Description:   225 p. : ill. ; 28 cm.
Series:        Schaum's outline series
LC Call No.:   QA433.S66 2002
Dewey No.:     515/.63 21
ISBN:          007060228X
Notes:         Originally published: New York : Schaum Pub. Co.,
                  1959.
               Includes index.
Subjects:      Vector analysis.
Control No.:   12775981
Access:        Publisher description

Author:        Springer, C. E. (Charles Eugene), 1903-
Title:         Tensor and vector analysis; with applications to
                  differential geometry.
Published:     New York, Ronald Press Co. [1962]
Description:   242 p. illus. 24 cm.
LC Call No.:   QA433.S68
Dewey No.:     516.83
Subjects:      Calculus of tensors.
               Vector analysis.
               Geometry, Differential.
Control No.:   1694926

Author:        Temple, George Frederick James, 1901-
Title:         Cartesian tensors; an introduction.
Published:     London, Methuen; New York, Wiley [c1960]
Description:   92 p. illus. 20 cm.
Series:        Methuen's monographs on physical subjects
LC Call No.:   QA433.T4
Dewey No.:     516.83
Subjects:      Calculus of tensors.
Control No.:   4530612

Author:        Thomas, Tracy Y. (Tracy Yerkes), 1899-
Title:         The elementary theory of tensors, with
                  applications to geometry and mechanics, by Tracy Yerkes
                  Thomas ...
Edition:       1st ed.
Published:     New York, London, McGraw-Hill book company, inc.,
                  1931.
Description:   ix, 122 p. diagrs. 24 cm.
LC Call No.:   QA433.T5
Dewey No.:     517.2
ISBN:          $2.00
Subjects:      Calculus of tensors.
Control No.:   1218658

Author:        Lardner, Dionysius, 1793-1859.
Title:         A treatise on geometry and its application in the
                  arts. By the Rev. Dionysius Lardner.
Published:     London, Printed for Longman, Orme, Brown, Green,
                  & Longmans [etc.] 1840.
Description:   4 p.l., [vii]-xxiv, 314, [30] p. incl. tables,
                  diagrs. 17 cm.
Series:        The cabinet cyclopædia. Conducted by ... D.
                  Lardner ... [v. 71] Natural philosophy
LC Call No.:   AC1.L3 v. 71
Notes:         Added t.-p.: The cabinet of natural philosophy
                  ...
               Added t.-p., engr.
Subjects:      Geometry.
               Curves, Plane.
Series Entry:  Cabinet cyclopaedia ; v. 71.
Control No.:   3107092

Author:        Rees, Paul Klein, 1902-
Title:         Analytic geometry.
Published:     Englewood Cliffs, N.J., Prentice-Hall, 1956.
Description:   237 p. illus. 24 cm.
Series:        Prentice-Hall mathematics series
LC Call No.:   QA441.R413
Subjects:      Geometry, Analytic.
Control No.:   6994687

Author:        Caporali, Ettore, 1855-1886. [from old catalog]
Title:         Memorie di geometria,
Published:     Napoli, B. Pellerano, 1888.
Description:   3 p.l., [iii]-vii, 378 p., 1 l. front. (port.) 25
                  cm.
LC Call No.:   QA443.C3
Subjects:      Geometry -- Collected works. [from old catalog]
Other authors: Padelletti, Dino, 1852-1892. [from old catalog]
Control No.:   5992519

Author:        Chasles, M. (Michel), 1793-1880.
Title:         Aperçu historique sur l'origine et le
                  développement des méthodes en géométrie :
                  particulièrement de celles qui se rapportent à la
                  géométrie moderne : suivi d'un mémoire de géométrie sur
                  deux principes généraux de la science, la dualité et
                  l'homographie / par M. Chasles.
Edition:       3. éd., conforme à la première.
Published:     Paris : Gauthier-Villars et fils, 1889.
Description:   ii, 851 p. ; 30 cm.
LC Call No.:   QA443.5.C52x 1889
Notes:         Includes bibliographical references and index.
Subjects:      Geometry -- History.
               Geometry, Projective.
Control No.:   4764629

Author:        Hollcroft, Temple Rice, 1889-
Title:         [Collected papers, reprints, etc. in geometry].
Published:     1921-1927.
Description:   11 pamphlets in 1 v. illus. 25 cm.
LC Call No.:   QA443.H6
Notes:         [1] On (2,3) compound involutions.--[2] Plane
                  involutions of order four.--[3] Singularities of curves of
                  given order--[4] Maximal cuspidal curves.--[5] Limits for
                  actual double points of space curves.--[6] Conditions for
                  self dual curves.--[7] Self dual space curves.--[8] Harmonic
                  cubics.--[9] Singularities of Hessian--[10] On (3,3) and
                  higher point correspondences.--[11] On the reality of
                  singularities of plane curves.
Subjects:      Geometry.
Control No.:   13114070

Author:        Arnauld, Antoine, 1612-1694.
Title:         Nouveaux elemens de geometrie : contenant, outre
                  un ordre tout nouveau & de nouvelles demonstrations des
                  propositions les plus communes, de nouveaux moyens de faire
                  voir quelles lignes sont incommensurables, de nouvelles
                  mesures des angles, dont on ne s'estoit point encore avisé,
                  et de nouvelles manieres de trouver & de demontrer la
                  proportion des lignes.
Published:     A Paris : Chez Charles Savreux, libraire juré
                  ..., 1667.
Description:   [24], 340 p., leaves 340, 343-345 : diagrams ; 25
                  cm. (4to)
LC Call No.:   QA444.A75 1667
Notes:         "A reworking and reordering of the Euclidean
                  theorems in the light of the contemporary literature ... and
                  Pascal's influence"--Dict. of scientific biog.
               Published anonymously. By Antoine Arnauld. Cf.
                  Dict. de biog. franç. According to L. Verga (Il pensiero
                  filosofio e scientifico di Antoine Arnauld, 1972, v. 1, p.
                  [246]) the pref. is by Pierre Nicole.
               Signatures: ãp4s äep4s äip4s A-2Tp4s
                  V-Yp2s. Cancel slip on 2G3.
               With errata leaf.
               Cioranescu 8116.
               "Solution d'un des plus celebres et des plus
                  difficiles problemes d'arithmetique, appellé communement les
                  quarrez magiques": p. [325]-340, followed by 4 engraved
                  squares on the concluding leaves.
               LC copy has the errata leaf following äi4.
Subjects:      Geometry -- Early works to 1800.
Other authors: Nicole, Pierre, 1625-1695.
Control No.:   3815771

Author:        Benedetti, Giovanni Battista, 1530-1590.
Uniform Title: Resolutio omnium Euclidis problematum
Title:         Resolvtio omnivm Evclidis problematvm
                  aliorumqb3s ad hoc necessario inuentorum vna tantummodo
                  circini data apertura, per Ioannem Baptistam de Benedictis
                  inventa.
Published:     Venetiis [Apvd B. Caesanum] 1553.
Description:   [12], 57, [1] l. ill. 22 cm.
LC Call No.:   QA444.B45
Notes:         Based on Euclid's Elementa.
               Dedicatory letter to Abbot G. de Guzman (leaves
                  [2]-[12]) includes the author's first revision of
                  Aristotelian mechanics. (Cf. Diz. biog. degli italiani.
Subjects:      Geometry -- Early works to 1800.
               Euclid's Elements.
               Mechanics -- Early works to 1800.
Other authors: Euclid. Elements.
Control No.:   807183

Author:        Borelli, Giovanni Alfonso, 1608-1679.
Title:         Euclides restitutus, siue, Prisca geometriae
                  elementa : breuiùs, & faciliùs contexta, in quibus
                  prñecipuè proportionum theoriae noua, firmiorique methodo
                  promuntur / a Io. Alphonso Borellio ...
Published:     Pisis : ex Officina Francisci Honophri, 1658.
Description:   [8], 456, xxx, [2] p. : ill. ; 22 cm.
LC Call No.:   QA444.B67x 1658
Notes:         Signatures: pip4s A-3Lp4s a-dp4s.
Subjects:      Geometry -- Early works to 1800.
               Ratio and proportion -- Early works to 1800.
               Euclid. Elements.
Other titles:  Euclides restitutus.
               Prisca geometriae elementa.
Control No.:   983560

Author:        Boulliau, Ismael, 1605-1694.
Uniform Title: Exercitationes geometricae tres.
Title:         Ismaelis Bullialdi Exercitationes geometricae
                  tres ... ; Astronomiae philolaicae fundamenta clariùs
                  explicata, & asserta aduersùs clariss. viri Sethi Wardi
                  Oxoniensis professoris impugnationem.
Published:     Parisiis : Apud Sebastianum Cramoisy, regis ac
                  reginae architypographum, et Gabrielem Cramoisy ..., 1657.
Description:   44, 56 p. : ill. ; 23 cm. (4to)
LC Call No.:   QA567.B68 1657; Alternative class.: QA444
Notes:         "Astronomiae philolaicae fundamenta" has special
                  t.p. with title: Ismaelis Bullialdi Astronomiae philolaicae
                  fundamenta ...
               Signatures: A-Ep4s Fp2s, p2sA-Gp4s.
               BLC, v. 39, p. 173
               BN, v. 17, col. 588
               NUC pre-1956, NB 0692797
               (of 1st work, from t.p.) I. Circa demonstrationes
                  per inscriptas & circimscriptas figuras -- II. Circa
                  conicarum sectionum quasdam propositiones -- III. De
                  porismatibus.
               With: Ismaelis Bullialdi De lineis spiralibus
                  demonstrationes nouae. Parisiis : Apud Sebastianum Cramoisy,
                  regis & reginae architypographum, et Gabrielem Cramoisy ...,
                  1657. Probably bound together subsequent to publication.
Subjects:      Geometry -- Early works to 1800.
Other authors: Boulliau, Ismael, 1605-1694. Astronomiae
                  philolaicae fundamenta. 1657.
Other titles:  Exercitationes geometricae tres.
               Astronomiae philolaicae fundamenta clariùs
                  explicata, & asserta aduersùs clariss. viri Sethi Wardi
                  Oxoniensis professoris impugnationem.
               Ismaelis Bullialdi Astronomiae philolaicae
                  fundamenta ...
               Astronomiae philolaicae fundamenta.
Control No.:   2475208

Author:        Grzebski, Stanislaw, 1524-1570. [from old
                  catalog]
Title:         Stanislawa Grzebskiego Geometria r. 1566
Published:     [W Krákowie, L. Andrysowic, 1566]
Description:   1 v. (unpaged) illus. 15 cm.
LC Call No.:   QA444.G79
Subjects:      Geometry -- Early works to 1800. [from old
                  catalog]
Control No.:   8539495

Author:        Le Clerc, Sébastien, 1637-1714.
Title:         Traité de geometrie / par Sebastien Le Clerc
                  ...
Published:     A Paris : Chez André Cailleau ..., 1719.
Description:   [4], 229 [i.e. 249], [1] p. : ill. ; 20 cm.
                  (8vo)
LC Call No.:   QA444.L43x 1719
Notes:         Signatures: pip2s A-Np8s Op8s chi1
                  pp8s(P4 + 2chi1) 3chi1 Qp2s.
Subjects:      Geometry -- Early works to 1800.
Control No.:   511233

Author:        Martinovics, Ignác, 1755-1795.
Title:         Dissertatio de micrometro ope cuius vnus digitus
                  geometricus diuiditur in 2,985,984 puncta quinti ordinis / ab
                  Ignatio Martinovics ... conscripta anno MDCCLXXXIV.
Published:     Leopoli : Typis viduae Iosephae Piller ...,
                  [1784]
Description:   [22] p., II folded leaves of plates : ill. ; 22
                  cm. (4to)
LC Call No.:   QA444.M37 1784
Notes:         Printing date from Estreicher and Poggendorff.
               Signatures: A-Cp4s (C4, probably blank,
                  wanting).
               Estreicher, XXII, 197
               Source: Transfer, Aug. 12, 1970. DLC
Subjects:      Geometry -- Early works to 1800.
               Mathematical instruments -- Early works to 1800.
Control No.:   1464167

Author:        Nakcijanaviˆcius, Jok¯ubas, 1725-1790.
Title:         Praelectiones mathematicae ex Wolfianis elementis
                  adornatae, atqué sic usui auditorum matheseos accomodatae :
                  ut quae ibi praetermissa, vel in alium locum rejecta
                  desiderari poterant à Tyronibus, adjicerentur, quae verò
                  vel obscuritatis, vel prolixitatis accusari solebant,
                  dilucidiùs & breviùs exponerentur / à P. Jacobo
                  Nakcyanowicz ...
Published:     Vilnae : Typis S.R.M. Academicis, 1761.
Description:   [10], 310, [2] p., [16] folded leaves of plates :
                  16 ill. ; 17 cm. (8vo)
LC Call No.:   QA444.N37 1761
Dewey No.:     516.2 20
Notes:         "Tomus primus." No more published?
               Signatures: [superscript pi]Ap4s(-A4) A-Tp8s
                  Up4s W1.
               Errata on last leaf.
               Backer-Sommervogel, v. 5, column 1554
               Elementa geometriae. Pars prior, Elementa
                  geometriae planae exhibet. Pars posterior, Elementa
                  geometriae solidae proponit -- Elementa trigonometriae
                  planae.
Subjects:      Geometry -- Early works to 1800.
               Plane trigonometry -- Early works to 1800.
Control No.:   1514533

Author:        Ozanam, Jacques, 1640-1717.
Title:         La géométrie pratique : contenant la
                  trigonométrie théorique & pratique, la longimétrie, la
                  planimétrie, & la stéréométrie : avec un petit traité de
                  l'arithmétique par géométrie / par M. Ozanam ...
Edition:       Nouvelle édition, revue, corrigée, &
                  augmentée.
Published:     A Paris : Chez Jombert ..., 1757.
Description:   v, [3], 316 p., 10 folded leaves of plates : ill.
                  (engravings) ; 17 cm. (12mo)
LC Call No.:   QA444.O93 1757
Notes:         Signatures: ap4s A-Np12s Op2s.
Subjects:      Geometry -- Early works to 1800.
               Mathematics -- Early works to 1800.
Control No.:   12336279

Author:        Pagnini, Giovanni. [from old catalog]
Title:         Costruzione ed uso del compasso di proporzione.
Published:     Napoli, I. Russo, 1753.
Description:   56 p. illus. 26 cm.
LC Call No.:   QA444.P33 (Rare Bk Coll)
Subjects:      Geometry -- Early works to 1800.
               Mathematical instruments -- Early works to 1800.
               Ratio and proportion -- Early works to 1800.
Control No.:   10436898

Author:        Pardies, Ignace Gaston, 1636-1673.
Uniform Title: Works. 1725. Bruyset
Title:         Œuvres du R.P. Ignace-Gaston Pardies, de la
                  Compagnie de Jesus ...
Edition:       Augmenté dans cette nouvelle edition d'une table
                  pour l'intelligence des elemens de geometrie, sélon
                  Euclide.
Published:     A Lyon : Chez les freres Bruyset ..., 1725.
Description:   [24], 499, [5] p. : ill. ; 17 cm. (12mo)
LC Call No.:   QA444.P36 1725
Notes:         Signatures: ap8s ep4s A-2Tp8s/p4s.
               (from t.p.) Contenant: 1. Les elemens de
                  geometrie -- 2. Un discours du mouvement local -- 3. La
                  statique, ou, La science des forces mouvantes -- 4. Deux
                  machines propres à faire les quadrans -- 5. Un discours de
                  la connoissance des bêtes.
               LC copy imperfect: last leaf wanting. DLC
Subjects:      Geometry -- Early works to 1800.
               Dynamics -- Early works to 1800.
               Quadrant -- Early works to 1800.
               Zoology -- Pre-Linnean works.
Control No.:   12307950

Author:        Pico, Fonticolano, Geronimo. [from old catalog]
Title:         Tesoro di matematiche considerationi,
Published:     Roma, Stamperia d'A. Fei, 1645.
Description:   278 p. illus. 31 cm.
LC Call No.:   QA444.P5 (Rare Bk Coll)
Subjects:      Geometry -- Early works to 1800. [from old
                  catalog]
Control No.:   9500120

Author:        Renaldini, Carlo, conte, 1615-1698.
Title:         Caroli Renaldinii Geometra promotvs.
Published:     Patavii, Typis Petri Mariae Frambotti
                  bibliopolae, 1670.
Description:   88 p. illus. 34 cm.
LC Call No.:   QA33.R42; Alternative class.: QA444
Notes:         Bound with the author's De resolutione, &
                  compositione mathematica, libri dvo. Patavii, 1668.
Subjects:      Geometry -- Early works to 1800.
Other titles:  Geometra promotus.
Control No.:   3690309

Author:        Snellius, Willebrordus, 1581-1626.
Title:         Cyclometricvs; de circuli dimensione secundum
                  logistarum abacos & ad mechanicem accuratissima atque omnium
                  parabilissima; eiusdemque usus ...
Published:     Lvgdvni Batavorvm, Ex Officina Elzeviriana,
                  1621.
Description:   [20], 102 p. 21 cm.
LC Call No.:   QA444.S62
Subjects:      Geometry -- Early works to 1800.
Other titles:  Cyclometricus.
Control No.:   4622375

Author:        Solski, Stanislaw, 1622-1701. [from old catalog]
Title:         Geometra polski;
Published:     W Krakowie, w Druk. G. y M. Schedlow, 1683.
Description:   3 v. in 1. illus. 30 cm.
LC Call No.:   QA444.S64 (Rare Bk Coll)
Subjects:      Geometry -- Early works to 1800. [from old
                  catalog]
               Surveying -- Early works to 1800. [from old
                  catalog]
Other titles:  Geometra y architekt polski.
Control No.:   9463416

Author:        Habich, E. J. (Eduardo Juan), 1835-1909.
Title:         Etudes géométriques et cinématiques : note sur
                  quelques questions de géométrie et de cinématique et
                  réponse aux réclamations de M. l'abbé Aoust / par E.J.
                  Habich.
Published:     Lima : Carlos Paz Soldan, 1880.
Description:   80 p. ; 24 cm.
LC Call No.:   QA446.H32x 1880
Notes:         Includes bibliographical references.
Subjects:      Geometry.
               Kinematics.
Other authors: Aoust, M. l'abbé (Louis Stanislas Xavier
                  Barthélemy), 1814-1885.
Control No.:   1928188

Author:        Spottiswoode, William, 1825-1883. [from old
                  catalog]
Title:         Remarks on some recent generalizations of
                  algebra.
Published:     [London, 1872]
Description:   p. [145]-164. 22 cm.
LC Call No.:   QA446.E5
Subjects:      Quaternoins. [from old catalog]
Control No.:   7839340

Author:        Altshiller-Court, Nathan, b. 1881.
Title:         Modern pure geometry for high school mathematics
                  teachers.
Published:     Stillwater, Dept. of Mathematics, Oklahoma
                  Agricultural and Mechanical College, 1955.
Description:   101 l. diagrs. 28 cm.
Series:        National Science Foundation (U.S.) Summer
                  Mathematics Institute notes
LC Call No.:   QA447.C6
Dewey No.:     513.04
Notes:         Includes bibliographical references.
Subjects:      Geometry.
Control No.:   10277603

Author:        Bordage, Edmond. [from old catalog]
Title:         Sur la possibilité d'édifier la géometrie
                  euclidienne sans le postulatum des paralèlles.
Published:     Saint-Denis (Réunion) Typographie G. Lahuppe et
                  ce, 1902.
Description:   19 p. pl. (diagrs.) 24 cm.
LC Call No.:   QA447.B6
Subjects:      Geometry. [from old catalog]
               Parallels (Geometry) [from old catalog]
Control No.:   10151849

Author:        Cave, William P. [from old catalog]
Title:         Addenda to Discoveries in geometry.
Published:     c1917.
Description:   p. cm.
LC Call No.:   QA447.C32
Control No.:   10000178

Author:        Cave, William P. [from old catalog]
Title:         Discoveries in geometry,
Published:     [New York, W. E. Herrold, printer] c1916.
Description:   [32] p. 23 cm.
LC Call No.:   QA447.C3
Subjects:      Geometry. [from old catalog]
Control No.:   5901886

Author:        Ellis, Alexander John, 1814-1890. [from old
                  catalog]
Title:         Algebra identified with geometry ...
Published:     London, C. F. Hodgson & sons, 1874.
Description:   p. cm.
LC Call No.:   QA447.E5
Subjects:      Geometry -- History. [from old catalog]
               Numbers, Complex. [from old catalog]
Control No.:   9244305

Author:        Hallett, George Hervey, jr. [from old catalog]
Title:         Linear order in three dimensional Euclidean and
                  double elliptic spaces,
Published:     [Lancaster, Pa., Press of the New era printing
                  company, 1921]
Description:   1 p.l., p. 185-202. 24 cm.
LC Call No.:   QA447.H3
Subjects:      Geometry. [from old catalog]
Control No.:   9660478

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Elements of geometry,
Published:     [Scranton, 1941]
Description:   cover-title, 36 p. 19 cm.
LC Call No.:   QA447.I58
Subjects:      Geometry, Plane. [from old catalog]
               Plane trigonometry.
Control No.:   9263512

Author:        Mira, Julio A.
Title:         Geometry through practical applications / Julio
                  A. Mira.
Published:     New York : Barnes and Noble, 1961 c1942.
Description:   vi, 280 p. : ill. ; 21 cm.
Series:        An everyday handbook ; no. 219
LC Call No.:   QA447.M5
Notes:         Index : p. 273-280.
Subjects:      Geometry
Control No.:   8432563

Author:        Ravielli, Anthony.
Title:         An adventure in geometry, written and illustrated
                  by Anthony Ravielli.
Published:     New York, Viking Press [1957]
Description:   117 p. illus. 25 cm.
LC Call No.:   QA447.R3
Dewey No.:     513
Subjects:      Geometry.
               Nature (Aesthetics)
Control No.:   6058377

Author:        Russell, John Scott, 1808-1882.
Title:         Geometry in modern life, being the substance of
                  two lectures on useful geometry, given before the Literary
                  Society at Eton. By J. Scott Russell.
Published:     Eton, Willians and Son; London, Simpkin,
                  Marshall, and Co., 1878.
Description:   xiv, p., 1 l, 197, [1] p. illus., diagrs. 22 cm.
LC Call No.:   QA447.R8
Subjects:      Geometry.
Control No.:   9734366

Author:        Smith, Vincent Edward, 1915- [from old catalog]
Title:         St. Thomas on the object of geometry.
Published:     Milwaukee, Marquette University Press, 1954.
Description:   99 p. 19 cm.
LC Call No.:   QA447.S5
Subjects:      Thomas Aquinas, Saint, 1225?-1274. [from old
                  catalog]
               Geometry. [from old catalog]
Control No.:   6982300

Author:        Waltsch, Simeon ben Nathan Nata.
Title:         Naòveh kodesh : kolel òhokhmat ha-medidah
                  òveha-meshulashim u-ve®ur °al hilkhot òkidush ha-òhodesh
                  leha-Rambam...
Published:     Berlin : Bi-defus òHevrat òhinukh ne°arim [546]
                  1786.
Description:   10, 42 leaves ; 20 cm.
LC Call No.:   QA447.W24
Subjects:      Maimonides, Moses, 1135-1204. Hilkhot òKidush
                  ha-òhodesh.
               Geometry -- Early works to 1800.
               Calendar, Jewish.
Control No.:   6518385

Author:        Wayne, Alan.
Title:         Basic mathematics.
Published:     Albany : University of the State of New York,
                  State Education Dept., Bureau of Vocational Curriculum
                  Development and Industrial Teacher Training, [1951]
Description:   253 p. : ill. ; 27 cm.
LC Call No.:   QA447.W3
Subjects:      Geometry -- Study and teaching.
               Arithmetic -- Study and teaching.
Other authors: New York (State). Bureau of Vocational Curriculum
                  Development and Industrial Teacher Training.
Control No.:   7910940
