#+STARTUP: showeverything logdone
#+options: num:nil


Author:        Bruggen, Jochum van. [from old catalog]
Title:         De hoofdstelling der axonometrie ...
Published:     Utrecht, Electr. drukkerij "De industrie" J. van
                  Druten, 1915.
Description:   5 p.l., 141 p., 1 l. diagrs. 24 cm.
LC Call No.:   QA502.B7
Subjects:      Projection. [from old catalog]
Control No.:   8798831

Author:        Leroy, C. F. A. (Charles François Antoine),
                  1780-1854.
Uniform Title: Traité de géométrie descriptive. German
Title:         Die darstellende Geometrie : (géométrie
                  descriptive) / von C.F.A. Leroy ; Deutsch mit Anmerkungen von
                  E.F. Kauffmann.
Edition:       3. Aufl.
Published:     Stuttgart : Bach & Kitzinger, 1873.
Description:   v, xiii, 266 p., 62 leaves of plates : ill. ; 28
                  cm.
LC Call No.:   QA502.L4715x 1873
Notes:         Translation of: Traité de géométrie
                  descriptive.
Subjects:      Geometry, Descriptive.
Control No.:   2400472

Author:        Roever, William Henry, 1874-
Title:         The axonometric method of descriptive geometry.
Published:     St. Louis, 1949.
Description:   v, 75 p. diagrs. 28 cm.
LC Call No.:   QA502.R6
Dewey No.:     515
Notes:         The first part, Representations and solutions in
                  orthographie axonometric descriptive geometry, is a free
                  translation from Loria's Vorlesungen über darstellende
                  Geometrie.
Subjects:      Axonometric projection.
Other authors: Loria, Gino. Vorlesungen über darstellende
                  Geometrie.
Control No.:   6963931

Author:        Schudeisky, Albrecht. [from old catalog]
Title:         Projektionslehre; die rechtwinklige
                  parallelprojektion und ihre anwendung auf die darstellung
                  technischer gebilde nebst einem anhang über die
                  schiefwinklige parallelprojektion in kurzer,
Published:     Leipzig und Berlin, B. G. Teubner, 1918.
Description:   v. 83 p. diagrs. 19 cm.
LC Call No.:   QA502.S35
Subjects:      Projection. [from old catalog]
Control No.:   8330690

Author:        Vonderlinn, J. [from old catalog]
Title:         Parallelperspektive.
Published:     Leipzig, G. J. Göschen, 1905.
Description:   112 p. illus., diagrs. 16 cm.
LC Call No.:   QA502.V94
Subjects:      Projection. [from old catalog]
Control No.:   9143056

Author:        Vonderlinn, J. [from old catalog]
Title:         Parallelperspektive; rechtwinklige und
                  schiefwinklige axonometrie,
Published:     Berlin und Leipzig, W. de Gruyter & co., 1920.
Description:   112 p. illus., diagrs. 16 cm.
LC Call No.:   QA502.V94 1920
Subjects:      Projection. [from old catalog]
Control No.:   6457233

Author:        Weiler, A. (Adolf), b. 1851.
Title:         Neue Behandlung der Parallelprojektionen und der
                  Axonometrie / von A. Weiler.
Edition:       2., wohlfeile Ausg.
Published:     Leipzig : B.G. Teubner, 1896.
Description:   vii, 210 p. : ill. ; 23 cm.
LC Call No.:   QA502.W44x 1896
Subjects:      Axonometric projection.
Control No.:   1928190

Author:        Graves, Otho M. (Otho McCarroll), 1882-
Title:         Orthographic projection; the elementary
                  principles of orthographic projection, with their
                  applications to technical drawing, by Otho M. Graves ...
Published:     Easton, Pa., Eschenbach brothers, 1912.
Description:   3 p.l., [9]-89 p. diagrs. 24 cm.
LC Call No.:   QA503.G8
ISBN:          $1.60
Subjects:      Orthographic projection.
Control No.:   3107519

Author:        Gueth, Oswald.
Title:         Twelve plates on projection drawing. By Oswald
                  Gueth ...
Edition:       1st ed.
Published:     New York, Spon & Chamberlain; London, E. & F.N.
                  Spon, limited, 1903.
Description:   2 p.l., 12 diagr. 22 x 28 cm.
LC Call No.:   QA503.G9
Subjects:      Projection.
Control No.:   4525294

Author:        Street, William Ezra, 1901-
Title:         Technical descriptive geometry.
Published:     New York, D. Van Nostrand Co. [1948]
Description:   ix, 179 p. illus. 25 cm.
LC Call No.:   QA503.S76
Dewey No.:     515
Subjects:      Geometry, Descriptive.
               Projection.
Control No.:   9757639

Author:        Engel, Ferdinand i. e. Christian Gottlieb
                  Ferdinand, 1805-1866. [from old catalog]
Title:         Axonometrical projections on the most important
                  geometrical surfaces.
Published:     New York, H. Goebeler; [etc., etc.] 1855.
Description:   3 p. l., 5-10 p. diagrs. on IX pl. 26 x 34 cm.
LC Call No.:   QA505.E5
Notes:         A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Surfaces, Models of. [from old catalog]
               Projection. [from old catalog]
Control No.:   7266206

Author:        Torroja, E. [from old catalog]
Title:         Axonometria.
Published:     1879.
Description:   l v. cm.
LC Call No.:   QA505.T6
Control No.:   7194730

Author:        Weisbach, Julius, 1806-1871. [from old catalog]
Title:         Anleitung zum axonometrischen zeichnen,
Published:     Freiburg, J. G. Engelhardt, 1857.
Description:   p. cm.
LC Call No.:   QA505.W4
Subjects:      Projection. [from old catalog]
Control No.:   9139351

Author:        Fiedler, O[tto] W[ilhelm], 1832- [from old
                  catalog]
Title:         Die centralprojection als geometrische
                  wissenschaft ...
Published:     Leipzig, Druck von F. A. Brockhaus [1860]
Description:   41 p. diagrs. 27 x 22 cm.
LC Call No.:   QA511.F45
Subjects:      Projection. [from old catalog]
Other authors: Chemnitz. K. Gewerb-akademie. [from old catalog]
Control No.:   9610050

Author:        Beal, George Malcolm. [from old catalog]
Title:         Perspective; a practical development of basic
                  principles,
Published:     Ann Arbor, Mich., Edwards brothers, inc.,
                  lithoprinters, 1939.
Description:   2 p.l., ii-iv, 52 p. diagrs. 28 x 22 cm.
LC Call No.:   QA515.B4
Subjects:      Perspective. [from old catalog]
Control No.:   6939390

Author:        Choquet, Charles, b. 1798. [from old catalog]
Title:         Traité de perspective linéaire, à l'usage des
                  artistes; comprenant la perspective des ombres linéaires, et
                  celle des réflexions produites par l'eau et les miroirs
                  plans; précédé des notions de géométrie nécessaires
                  pour l'intelligence des opérations;
Published:     Paris, A. André, 1823.
Description:   2 p.l., iii, [1], 184 p. diagrs. on 28 pl. (2
                  fold.) 27 cm.
LC Call No.:   QA515.C5
Subjects:      Perspective. [from old catalog]
Control No.:   8668302

Author:        Cousin§ery, B. E. (Barth§el§emy §Edouard),
                  1790-1851.
Title:         Géométrie perspective; ou, Principles de
                  projection polaire, appliqués à la description des corps;
                  par B.-É. Cousinéry.
Published:     Paris, Carilian-Goeury, 1828.
Description:   viii, 96 p. diagrs. on 7 fold. pl. 26 cm.
LC Call No.:   QA515.C8
Subjects:      Perspective
Control No.:   6794984

Author:        Gordon, John William, 1853-
Title:         Generalised linear perspective, treated with
                  special reference to photographic land surveying and military
                  reconnaissance, by J. W. Gordon.
Published:     London, Constable, 1922.
Description:    xvi, 184 p. front., plates (1 fold.) diagrs.
                  (part fold.) 23 cm.
LC Call No.:   QA515.G6
Subjects:      Perspective.
Control No.:   9197677

Author:        Hamilton, John, F. R. S. [from old catalog]
Title:         Stereography,
Published:     London, Printed for the author by W. Bowyer,
                  1738.
Description:   9 p.l., 400, 37 p. diagrs. on 130 fold. pl. 40
                  cm.
LC Call No.:   QA515.H2
Subjects:      Perspective. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   8200141

Author:        Hertzer, H. (Hugo), 1831-1908.
Title:         Die geometrischen Grundprincipien der Perspective
                  / von H. Hertzer.
Published:     Berlin : Nicolaische Verlagsbuchhandlung, 1868.
Description:   62 p. : ill. ; 19 cm.
LC Call No.:   QA515.H47x 1868
Subjects:      Perspective.
Control No.:   3818829

Author:        Heyn, Rudolph.
Title:         Haupsätze der Perspective, Speigelung und
                  perspectivischen Schatteconstruction mit Übungsbeispielen /
                  von Rudolph Heyn ; herausgegeben durch den Architekten-Verein
                  am Königl. Polytechnikum zu Dresden.
Published:     Leipzig : Arthur Felix, 1885.
Description:   15 p., [20] leaves of plates : ill. ; 35 cm.
LC Call No.:   QA515.H49x 1885
Subjects:      Perspective.
               Reflections.
Control No.:   2400482

Author:        Hill, John E. (John Edward), 1864-
Title:         A text-book on shades and shadows, and
                  perspective. Prepared for the use of students in technical
                  schools by John E. Hill.
Edition:       2d ed., rev. and enl. 1st thousand.
Published:     New York, Wiley, 1896.
Description:   v, 101 p. XII fold. pl. (incl. diagrs.) 24 cm.
LC Call No.:   QA515.H6
Subjects:      Shades and shadows.
               Perspective.
Control No.:   5860795

Author:        Hill, John Edward, 1864- [from old catalog]
Title:         A text-book on the shades and shadows, and
                  perspective.
Edition:       1st ed.
Published:     Ithaca, N.Y., The author, 1894.
Description:   3 p.l., 61 p. xi fold. pl. (incl. diagrs.) 24
                  cm.
LC Call No.:   QA515.H5
Subjects:      Shades and shadows. [from old catalog]
               Perspective. [from old catalog]
Control No.:   8202013

Author:        Honey, F: R. [from old catalog]
Title:         Linear perspective.
Published:     [n.p.] 1877.
Description:   1 v. cm.
LC Call No.:   QA515.H77
Control No.:   6266720

Author:        Lebel, J. [from old catalog]
Title:         Résumé des principes da la perspective
                  linéaire,
Published:     Paris, Vuibert, 1921.
Description:   43 p., 1 l. diagrs. 25 cm.
LC Call No.:   QA515.L4
Subjects:      Perspective. [from old catalog]
Control No.:   8722657

Author:        Merian, Rudolf, 1797-1871. [from old catalog]
Title:         Grundsätze der linearperspektive...
Published:     Basel, Gedruckt bei A. Wieland [1832]
Description:   14 p. diagrs. on 2 fold. pl. 26 x 21 cm.
LC Call No.:   QA515.M56
Subjects:      Perspective. [from old catalog]
Control No.:   10074468

Author:        Ozanam, Jacques, 1640-1717.
Title:         La perspective theorique et pratique, ou, L'on
                  enseigne la maniere de mettre toutes sortes d'objets en
                  perspective & d'en representer les ombres causées par le
                  soleil ou par une petite lumiere / tirée du Cours de
                  mathematique de M. Ozanam, de l'Academie royale des
                  sciences.
Published:     A Paris, Quay des Augustins : Chez Claude Jombert
                  ..., 1711.
Description:   [10], 108 p., 36 leaves of plates : ill. ; 19 cm.
                  (8vo)
LC Call No.:   QA515.O93 1711
Notes:         Signatures: pi1 ap4s A-Fp8s Gp6s.
               Plates signed: Berey, sec.
               Includes index.
Subjects:      Perspective -- Early works to 1800.
               Geometry -- Early works to 1800.
Other authors: Berey, Claude Auguste, fl. 1689-1722, engraver.
Control No.:   12180626

Author:        Ozanam, Jacques, 1640-1717.
Title:         La perspective theorique et pratique ou l'on
                  enseigne la maniere de mettre toutes sortes d'objets en
                  perspective & d'en representer les ombres causées par le
                  soleil ou par une petite lumiere / tirée du Cours de
                  mathematique de M. Ozanam, de l'Academie royale des
                  sciences.
Edition:       Nouvelle édition corrigée.
Published:     A Paris, rue Dauphine : Chez Claude-Antoine
                  Jombert, fils aîné, libraire ..., 1769.
Description:   xvi, 108, [4] p., 36 folded leaves of plates :
                  ill. ; 21 cm. (8vo)
LC Call No.:   QA515.O93 1769
Notes:         Signatures: ap8s A-Gp8s.
               Includes index.
               LC copy has ink-stamp on t.p.: Ecole royale
                  militaire. DLC
Subjects:      Perspective -- Early works to 1800.
               Geometry -- Early works to 1800.
Control No.:   12362482

Author:        Priestley, Joseph, 1733-1804.
Title:         A familiar introduction to the theory and
                  practice of perspective. By Joseph Priestly.
Published:     London, Printed for J. Johnson and J. Payne,
                  1770.
Description:   1 p. l., xv, 132, [6] p. 23 fold. pl. 22 cm.
LC Call No.:   QA515.P94
Subjects:      Perspective.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   6342843

Author:        Randall, O. E. (Otis Everett), b. 1860.
Title:         Shades and shadows and perspective; a text-book
                  based on the principles of descriptive geometry, by O.E.
                  Randall ...
Published:     Boston, Ginn & company, 1902.
Description:   v, 64 p. XI diagr. 20 cm.
LC Call No.:   QA515.R2
Subjects:      Shades and shadows.
               Perspective.
Control No.:   744736

Author:        Royal Military Academy, Woolwich.
Title:         Linear perspective projection, &c. A text-book
                  for the use of the Royal military academy, Woolwich. In two
                  parts. By Major E.H. Stafford ...
Published:     London, Printed for H.M. Stationery off., by
                  Harrison and sons, 1904.
Description:   2 v. 35 pl. 23 cm. (v. 2: 35 cm.)
LC Call No.:   QA515.W9
Notes:         Ruled leaves for notes inserted.
               Part I: Text (82 p.) Part II: Plates.
Subjects:      Perspective.
Other authors: Stafford, E. H. (Edmund Hyde), 1868-
Control No.:   2634107

Author:        Stuhlmann, Adolf, 1838- [from old catalog]
Title:         Lehrbuch der reliefperspektive,
Published:     Hamburg, Boysen & Maasch, 1914.
Description:   3 p.l., [v]-vi, 134 p. diagrs. 23 cm.
LC Call No.:   QA515.S7
Subjects:      Perspective. [from old catalog]
Other titles:  Reliefperspektive.
Control No.:   7770844

Author:        Warren, S. Edward (Samuel Edward), 1831-1909.
Title:         General problems in the linear perspective of
                  form, shadow, and reflection; or the scenographic projections
                  of descriptive geometry. By S. Edward Warren ...
Published:     New York, J. Wiley & son, 1868.
Description:   xvii, 197 p. xvii fold. pl., diagrs. 24 cm.
LC Call No.:   QA515.W3
               Microfilm 15787 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Perspective.
Control No.:   4525366

Author:        Warren, S. Edward (Samuel Edward), 1831-1909.
Title:         A manual of elementary problems in the linear
                  perspective of form and shadow; or the representation of
                  objects as they appear, made from the objects as they are. In
                  two parts. By S. Edward Warren.
Published:     New York, J. Wiley, 1863.
Description:   ix, 116 p. illus., diagrs. 24 cm.
LC Call No.:   QA515.W2
Notes:         Pt. 1. Primitive methods; with an
                  introduction.--pt. 2. Derivative methods; with some notes on
                  aerial perspective.
Subjects:      Perspective.
Control No.:   9605044

Author:        Adhémar, J, (Joseph), 1797-1862.
Title:         Traité des ombres, par J. Adhémar.
Edition:       2. éd., rev. et augm.
Published:     Paris, Mathias [etc.] 1852.
Description:   x p., 1 L., 386 p., 1 L. 22 cm. and atlas of
                  diagr. on 41 (i.e. 42) pl. 39 x 29 cm.
Series:        His Cours de mathématiques à l'usage de
                  l'ingénieur civil
LC Call No.:   QA519.A2
Notes:         Atlas has title: Applications de géométrie
                  descriptive. Ombres. 2. éd., rev. et augm. Paris,
                  Carilian-Goeury et V. Dalmont [etc.]
Subjects:      Shades and shadows
Series Entry:  Adhémar, Joseph Alphonse, 1797-1862. Cours de
                  mathématiques à l'usage de l'ingénieur civil
Control No.:   9133306

Author:        Lange, David C. (David Christoph)
Title:         Shades and shadows, by David C. Lange ...
Published:     New York, John Wiley & sons, inc.; [etc., etc.]
                  1921.
Description:   v, [1], 135 p. front., illus., diagrs. 22 cm.
LC Call No.:   QA519.L3
ISBN:          $2.50
Subjects:      Shades and shadows.
               Geometry, Descriptive.
Control No.:   3580477

Author:        Pillet, Jules, 1842-1912.
Title:         Shades and shadows. An exposition and
                  demonstration of short and convenient methods for determining
                  the shades and shadows of objects illuminated by the
                  conventional parallel rays; the methods in use at The École
                  des beaux arts at Paris. From the French of M. Jules Pillet
                  ... Tr. and rev. by Julian Millard ...
Published:     Philadelphia, Franklin printing company, 1896.
Description:   43 p. incl. diagrs. 32 x 24 cm.
LC Call No.:   QA519.P6
Notes:         Running title: Conventional shades and shadows.
Subjects:      Shades and shadows.
Other authors: Millard, Julian, tr.
Control No.:   3106912

Author:        Reder, A. C. [from old catalog]
Title:         Prilozhenie...
Published:     1858.
Description:   2 v. fol. cm.
LC Call No.:   QA519.R3
Notes:         Romanized.
Control No.:   6744347

Author:        Schnitzler, Heinrich.
Title:         Über die belichtung von krummen flächen,
                  speziell von rotationsflächen II. ordnung ...
Published:     Rostock, C. Hinstorffs buchdruckerei, 1904.
Description:   37, [1] p. diagrs. 22 cm.
LC Call No.:   QA519.S36
Notes:         Inaug.-diss.--Rostock.
               Bibliographical foot notes.
Subjects:      Shades and shadows.
Control No.:   7742244

Author:        Vonderlinn, J.
Title:         Schattenkonstruktionen, von professor J.
                  Vonderlinn ... Mit 114 figuren.
Published:     Leipzig, G.J. Göschen, 1904.
Description:   118 p. incl. diagrs. 16 cm.
Series:        Sammlung Göschen. [236]
LC Call No.:   QA519.V94
Subjects:      Shades and shadows.
Control No.:   2161263

Author:        Vonderlinn, J. [from old catalog]
Title:         Schattenkonstruktionen,
Edition:       Neudruck.
Published:     Berlin, Leipzig, G.J. Göschen, 1918.
Description:   118 p. diagrs. 16 cm.
LC Call No.:   QA519.V94 1918
Subjects:      Shades and shawdows. [from old catalog]
Control No.:   8798396

Author:        Ware, William R. (William Robert), 1832-1915.
Title:         Shades and shadows : with applications to
                  architectural details, and exercises in drawing them with the
                  brush and pen / by William R. Ware.
Published:     Scranton, Pa. : International Textbook Co.,
                  c1912-1913.
Description:   2 v. : ill., diagrams ; 32 cm.
LC Call No.:   QA519.W17
Notes:         part 1. Rectilinear figures.--part 2. Curvilinear
                  figures.
Subjects:      Shades and shadows.
               Architectural drawing.
Control No.:   7294854

Author:        Warren, S. Edward (Samuel Edward), 1831-1909.
Title:         General problems of shades and shadows. Formed
                  both by parallel and by radial rays; and shown both in common
                  and in isometrical projection: together with the theory of
                  shading. By S. Edward Warren ...
Published:     New York, J. Wiley & son, 1867.
Description:   xiii, 140 p. incl. tab. 65 diagr. on xv fold. pl.
                  (incl. front.) 24 cm.
LC Call No.:   QA519.W2 1867
Notes:         A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
               A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Shades and shadows.
Control No.:   3579395

Author:        Warren, Samuel Edward, 1831-1909. [from old
                  catalog]
Title:         General problems of shades and shadows.
Published:     New York, J. Wiley & sons, 1895.
Description:   xiii, 140 p. incl. tab. 65 diagr. on xv fold. pl.
                  24 cm.
LC Call No.:   QA519.W2 1895
Subjects:      Shades and shadows. [from old catalog]
Control No.:   7731448

Author:        Watson, William, 1834- [from old catalog]
Title:         A course in shades and shadows for the use of
                  colleges and scientific schools.
Published:     Boston, Damrell and Upham [c1889]
Description:   iv, 24 p. diagrs. on ix pl. 31 cm.
LC Call No.:   QA519.W3
Subjects:      Shades and shadows. [from old catalog]
Control No.:   7263360

Author:        Leone, Fred Charles. [from old catalog]
Title:         The gnomonic projection.
Published:     Washington, 1943.
Description:   54 l. illus. 28 cm.
LC Call No.:   QA520.L46
Subjects:      Spherical projection. [from old catalog]
Control No.:   9892154

Author:        Bakker, Nanke. [from old catalog]
Title:         De bicentrale projectie ...
Published:     's-Gravenhage, C. Bredée [1909]
Description:   4 p. l., 92 p., 3 l. 24 cm.
LC Call No.:   QA521.B3
Subjects:      Projection. [from old catalog]
Control No.:   8335280

Author:        Bünau, Heinrich von, 1808-1878. [from old
                  catalog]
Title:         Descriptive lösung des problems der um- end
                  eingeschreibenen kugel eines tetraëders ...
Published:     Leipzig, Druck von F. A. Brockhaus, [1852]
Description:   16 p. 2 fold. pl., diagrs. 30 x 23 cm.
LC Call No.:   QA521.B92
Subjects:      Sphere. [from old catalog]
               Geometry, Descriptive. [from old catalog]
Other authors: Chemnitz. K. Gewerb- und Baugewerkenschule. [from
                  old catalog]
Control No.:   6330765

Author:        Cousinéry, B[arthélémy] É[douard], 1790-1851.
                  [from old catalog]
Title:         La calcul par le trait,
Published:     Paris, Carilian-Gœury et V. Dalmont, 1839.
Description:   2 p.l., iv, 264 p. diagrs. on viii fold. pl. 21
                  cm.
LC Call No.:   QA521.C86
Subjects:      Graphic methods.
Control No.:   6334807

Author:        Disteli, Martin, 1862- [from old catalog]
Title:         Die Steiner'schen schliessungsprobleme nach
                  darstellend geometrischer methode ...
Published:     Leipzig, Druck von B. G. Teubner, 1888.
Description:   viii, 79, [1] p. diagrs. on vi pl. 23 cm.
LC Call No.:   QA521.D6
Subjects:      Geometry, Descriptive. [from old catalog]
Control No.:   6817961

Author:        Granville, Willam A. [from old catalog]
Title:         Plane and spherical trigonometry, and four place
                  table of logarithms.
Edition:       Teachers ed.
Published:     [n.p.] [c1912]
Description:   1 v. cm.
LC Call No.:   QA521.G78 1912
Control No.:   6269097

Author:        Hoover, Enos. [from old catalog]
Title:         Two new problems in geometry, for the
                  construction of hollow cones and frustums of cones of any
                  given bases and altitudes.
Published:     Frankfort, Ind. [E. Hoover] 1869.
Description:   [4] p. diagrs. 17 cm.
LC Call No.:   QA521.H78
Subjects:      Cone. [from old catalog]
Other authors: YA Pamphlet Collection (Library of Congress) DLC
                  [from old catalog]
Control No.:   6794985

Author:        Kliphardt, Raymond A.
Title:         Analytical graphics.
Edition:       2d ed.
Published:     Evanston, Principia Press of Illinois, [1957]
Description:   301 p. illus. 25 cm.
LC Call No.:   QA521.K5 1957
Dewey No.:     515
Subjects:      Geometry, Descriptive.
               Graphic methods.
Control No.:   8410292

Author:        Reuschle, Carl, 1847-1909. [from old catalog]
Title:         Die deck-elemente.
Published:     Stuttgart, J. B. Metzlersche buchhandlung, 1882.
Description:   iv, 37 p., 1 l. diagrs. on fold. pl. 21 cm.
LC Call No.:   QA521.R4
Subjects:      Geometry, Descriptive. [from old catalog]
Control No.:   9617579

Author:        Schiappa Monteiro de Carvalho, Alfredo Augusto,
                  1838- [from old catalog]
Title:         Mémoire de géométrie descriptive sur
                  l'intersection des surfaces du second ordre et des surfaces
                  de révolution soit entre elles-mêmes, soit avec quelques
                  surfaces particulières,
Published:     Coimbre, Imprimerie de l'Université, 1875.
Description:   72 p., 1 l. diagrs. on viii fold. pl. 24 cm.
LC Call No.:   QA521.S32
Subjects:      Geometry, Descriptive. [from old catalog]
               Surfaces. [from old catalog]
Control No.:   9605045

Author:        Torroja y Caballé, Eduardo, 1847-1918.
Title:         Teoría geométrica de las líneas alabeadas y de
                  las superficies desarrollables, por Eduardo Torroja y
                  Caballé ...
Published:     Madrid, Impr. de Fortanet, 1904.
Description:   388 p., 1 l. diagrs. 27 cm.
LC Call No.:   QA521.T7
               Microfilm 15386 QA
Notes:         "Obras publicadas por D. Eduardo Torroja": 1 p.
                  at end.
               Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Geometry, Descriptive.
               Curves of double curvature.
               Surfaces.
Control No.:   4525612

Author:        Briggs, George R. (George Russell), b. 1853.
Title:         The elements of plane analytic geometry. A
                  text-book including numerous examples and applications, and
                  especially designed for beginners. By George R. Briggs ...
Edition:       7th ed., rev. and enl. by Maxime Bôcher ...
Published:     New York, J. Wiley & sons; [etc., etc.] 1903.
Description:   iv p., 1 l., 191 p. diagrs. 19 cm.
LC Call No.:   QA522.B852
Subjects:      Geometry, Analytic -- Plane.
Other authors: Bôcher, Maxime, 1867-1918, ed.
Control No.:   272506

Author:        Lacroix, Silvestre François, 1765-1843. [from
                  old catalog]
Title:         An elementary treatise on plane and spherical
                  trigonometry and on the application of algebra to geometry;
Edition:       2d ed.
Published:     Cambridge, N.E., Printed by Hilliard and Metcalf,
                  1826.
Description:   2 p. l., [iii]-iv, 165 p. diagrs. on v pl. 25 x
                  15 cm.
LC Call No.:   QA522.L149
Subjects:      Trigonometry. [from old catalog]
               Geometry, Analytic -- Plane. [from old catalog]
Other authors: Farrar, John, 1779-1853, [from old catalog] tr.
               Bézout, Étienne, 1730-1783. [from old catalog]
Control No.:   6322093

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         Sir Isaac Newton's Enumeration of lines of the
                  third order, generation of curves by shadows, organic
                  description of curves, and construction of equations by
                  curves. Translated from the Latin. With notes and examples.
                  By C.R.M. Talbot ...
Published:     London, H.G. Bohn, 1860.
Description:   xii, [7]-140 p. diagrs. (part fold.) 23 cm.
LC Call No.:   QA522.N4
Notes:         "'Enumeratio linearum tertii ordinis,' originally
                  printed as an appendix to the treatise on Optics, and
                  subsequently in the 'Opuscula,' has not hitherto been
                  published in a separate form."--Pref.
Subjects:      Geometry, Analytic -- Plane.
Other authors: Talbot, C. R. M. (Christopher Rice Mansel),
                  1803-1890, tr.
Other titles:  Enumeration of lines of the third order.
Control No.:   3109387

Author:        Bangma, Obbe Sikkes, 1768-1829.
Title:         Verhandeling over de klootsche driehoeken, waar
                  in onderzocht en aangetoond wordt, in hoe verre men, door
                  drie bekende termen eens klootschen driehoeks, over het stomp
                  of scherp zijn der onbekende termen oordeelen kan. Door O. S.
                  Bangma. Lid van het Koninklijk-Nederlandsche instituut van
                  wetenschappen, letterkunde en schoone kunsten, enz. enz.
                  Uitgegeven door de eerste klasse van het Instituut.
Published:     Te Amsterdam, Gedrukt en te bekomen bij Pieper en
                  Ipenbuur, 1817.
Description:   1 p. l., 35 p. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA525.B3
Subjects:      Spherical trigonometry.
Other authors: Nederlandsch instituut van wetenschappen,
                  letterkunde en schoone kunsten, Amsterdam. 1. klasse.
Control No.:   7745585

Author:        Nicholson, James William, 1844- [from old
                  catalog]
Title:         The trigonometrical circle,
Published:     [Homer, La., Printed at the office of
                  "Blackburn's Homer Iliad," 187-]
Description:   6 p. 19 cm.
LC Call No.:   QA528.N6
Subjects:      Trigonometry. [from old catalog]
Control No.:   9606193

Author:        Beez, Richard, 1827- [from old catalog]
Title:         Die elemente der geometrie.
Published:     Plauen, F. E. Neupert, 1869.
Description:   vii, [1], 216 p. diagrs. 22 cm.
LC Call No.:   QA529.B41
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9603098

Author:        Benson, Lawrence Sluter. [from old catalog]
Title:         Geometry: the elements of Euclid and Legendre
                  simplified and arranged to exclude from geometrical reasoning
                  the reductio ad absurdum; with the elements of plane and
                  spherical trigonometry, and exercises in elementary geometry
                  and trigonometry. Adapted for schools and colleges.
Published:     New York, The author; Burnton Bros., agents,
                  1868.
Description:   vi, 264 p. diagrs. 23 cm.
LC Call No.:   QA529.B47 1868
Subjects:      Geometry.
               Trigonometry.
               Euclid's Elements.
               Legendre, A. M. (Adrien Marie), 1752-1833.
Control No.:   9765325

Author:        Benson, Lawrence S[luter] [from old catalog]
Title:         Geometry: the elements of Euclid and Legendre
                  simplified and arranged to exclude from geometrical reasoning
                  the reductio ad absurdum; with the elements of plane and
                  spherical trigonometry, and exercises in elementary geometry
                  and trigonometry ... By Lawrence S. Benson ...
Published:     New York, Published for the author by Davies &
                  Kent, 1867.
Description:   vi, [7]-264 p. 23 cm.
LC Call No.:   QA529.B47
Subjects:      Geometry.
               Trigonometry.
               Euclid's Elements.
               Legendre, A. M. (Adrien Marie), 1752-1833.
Control No.:   6793015

Author:        Bradbury, William F. (William Frothingham),
                  1829-1914.
Title:         An elementary geometry and trigonometry.
Published:     Boston, Thompson, Bigelow and Brown, 1872.
Description:   vi, 110, 66, 62 p. tab., diagr. 21 cm.
LC Call No.:   QA529.B79
Subjects:      Geometry.
               Plane trigonometry.
Control No.:   6324884

Author:        Bradbury, William F. (William Frothingham),
                  1829-1914.
Title:         An elementary geometry and trigonometry.
Published:     Boston, Thompson, Brown, and company [pref.
                  1872]
Description:   iv p., 1 l., 110, 66, 62 p. incl. illus. tables,
                  diagrs. 21 cm.
LC Call No.:   QA529.B79 1872a
Subjects:      Geometry.
               Plane trigonometry.
               Logarithms.
Control No.:   10010302

Author:        Bradbury, William F. (William Frothingham),
                  1829-1914.
Title:         Key to Elementary geometry & trigonometry ...
Published:     [n.p.] 1872.
Description:   1v. cm.
LC Call No.:   QA529.B8
Subjects:      Geometry.
               Trigonometry.
Control No.:   9544735

Author:        Brooks, Edward, 1831-1912.
Title:         The normal elementary geometry: embracing a brief
                  treatise on mensuration and trigonometry ... By Edward Brooks
                  ...
Published:     Philadelphia, Sower, Barnes & Potts, 1866.
Description:   164, 49, 62 p. tab., diagr. 19 cm.
LC Call No.:   QA529.B87
Subjects:      Geometry.
               Plane trigonometry.
Control No.:   8666365

Author:        Davies, Charles, 1798-1876.
Title:         Elements of geometry and trigonometry from the
                  works of A.M. Legendre : revised and adapted to the course of
                  mathematical instruction in the United States / by Charles
                  Davies.
Published:     New York : A.S. Barnes & Co., 1858.
Description:   254, 132, 62 p. : ill. ; 22 cm.
LC Call No.:   QA529.L43 1858
Notes:         "A table of logarithms of numbers from 1 to
                  10,000": 62 p. at end.
               A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Geometry.
               Trigonometry.
Other authors: Legendre, A. M. (Adrien Marie), 1752-1833.
Control No.:   10068991

Author:        Davies, Charles, 1798-1876. [from old catalog]
Title:         Elements of geometry and trigonometry.
Published:     New York and Chicago, A. S. Barnes and company
                  [c1886]
Description:   1 p. l., [5]-262, 62 p. tab., diagr. 19 cm.
LC Call No.:   QA529.D26
Subjects:      Geometry. [from old catalog]
               Plane trigonometry.
Control No.:   7261387

Author:        Davies, Charles, 1798-1876. [from old catalog]
Title:         Elements of geometry and trigonometry,
Published:     New York, A. S. Barnes & co.; 1851.
Description:   1 p. l., [5]-262, 62 p. tab., diagr. 19 cm.
LC Call No.:   QA529.D25
Subjects:      Geometry. [from old catalog]
               Plane trigonometry.
Control No.:   5856998

Author:        Docharty, Gerardus Beekman, 1804-1889. [from old
                  catalog]
Title:         Elements of plane and solid geometry.
Edition:       6th ed.
Published:     New York, Harper & brothers, 1862.
Description:   vi p., 1 l., 221 p. diagrs. 20 cm.
LC Call No.:   QA529.D6 1862
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   7729493

Author:        Docharty, Gerardus Beekman, 1804-1889. [from old
                  catalog]
Title:         Elements of plane and solid geometry.
Published:     New York, Harper & brothers, 1857.
Description:   2 p. l., [vii]-viii, 189 p. diagr. 20 cm.
LC Call No.:   QA529.D62 1857
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9134594

Author:        Docharty, Gerardus Beekman, 1804-1889. [from old
                  catalog]
Title:         Elements of plane and solid geometry, and plane
                  and spherical trigonometry.
Edition:       8th ed.
Published:     New York, Harper & brothers, 1866.
Description:   vi p., 1 l., 283 p. diagrs. 20 cm.
LC Call No.:   QA529.D6 1866
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9603099

Author:        [Flauti, Vincenzo], 1782-1863.
Title:         Corso di geometria elementare e sublime ...
Published:     [Napoli, Nella stamperie privata dell'autore,
                  1846-52]
Description:   4 v. in 3. diagr. on fold. pl. 26 cm.
LC Call No.:   QA529.F58
Subjects:      Euclid's Elements.
               Conic Sections.
               Trigonometry.
Other authors: Fergola, Nicola, 1753-1824.
               Archimedes. De sphaera et cylindro. Dimensio
                  circuli.
Control No.:   7728201

Author:        Greenleaf, Benjamin, 1786-1864. [from old
                  catalog]
Title:         Elements of geometry and trigonometry;
Published:     Boston, R. S. Davis & co.; 1862.
Description:   vi, [7]-320, 108, 62 p. tab., 21 cm.
LC Call No.:   QA529.G79
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   6793018

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Geometry and trigonometry,
Published:     Scranton, Pa., International textbook company
                  [1939]
Description:   2 p. l., 73, 25 p., 1 l., 18 p. incl. tables,
                  diagrs. 20 cm.
LC Call No.:   QA529.I55 1939
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9721445

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Eléments de géométrie,
Edition:       11. éd.
Published:     Paris, F. Didot, 1817.
Description:   3 p. l., 431 p. diagrs. on 14 fold. pl. 20 cm.
LC Call No.:   QA529.L4 1817
Subjects:      Geometry.
               Trigonometry.
Control No.:   9649074

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Éléments de géométrie ; avec des notes / par
                  A.M. Legendre.
Edition:       12. éd.
Published:     Paris : Firmin Didot, pére et fils, 1823.
Description:   431 p. : 14 fold. pl. ; 21 cm.
LC Call No.:   QA529.L4 1823
Subjects:      Geometry.
               Trigonometry.
Control No.:   10068301

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry,
Published:     New York, A. S. Barnes & Burr, 1862.
Description:   viii, [9]-259, 134, 62 p. diagr. 21 cm.
LC Call No.:   QA529.L43 1862
Subjects:      Geometry.
               Trigonometry.
Control No.:   6790627

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry.
Published:     Philadelphia, A. S. Barnes & co., 1844.
Description:   vi p., 1 l., [9]-297, 62 p. diagr. 21 cm.
LC Call No.:   QA529.L43 1844
Subjects:      Geometry.
               Trigonometry.
Other authors: Brewster, David, Sir, 1781-1868, tr.
               Davies, Charles, 1798-1876, ed.
Control No.:   6839049

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry.
Published:     Philadelphia, A. S. Barnes & co., 1843.
Description:   vi p., 1 l., [9]-297, 62 p. diagr. 21 cm.
LC Call No.:   QA529.L43 1843
Subjects:      Geometry.
               Trigonometry.
Control No.:   7258995

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry from the
                  works of A. M. Legendre.
Published:     New York and Chicago, A. S. Barnes & company,
                  1869.
Description:   viii, [9]-259, 134, 62 p. diagr. 21 cm.
LC Call No.:   QA529.L43 1869
Subjects:      Geometry.
               Trigonometry.
Control No.:   6322909

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry, from the
                  works of A. M. Legendre.
Published:     New York, A. S. Barnes & co., 1868.
Description:   viii, [9]-259, 134, 62 p. diagrs. 21 cm.
LC Call No.:   QA529.L43 1868
Subjects:      Geometry.
               Trigonometry.
Other authors: Davies, Charles, 1798-1876.
Control No.:   9650801

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry, from the
                  works of A. M. Legendre.
Published:     New York, A. S. Barnes & co.; 1857.
Description:   viii, [9]-254, 132, 62 p. diagrs. 22 cm.
LC Call No.:   QA529.L43 1857
Subjects:      Geometry.
               Trigonometry.
Other authors: Davies, Charles, 1798-1876, rev.
Control No.:   7727103

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry from the
                  works of A. M. Legendre.
Published:     New York, A. S. Barnes & co.; Cincinnati, H. W.
                  Derby & co., 1854.
Description:   viii, [9]-370, 62 p. diagrs. 22 cm.
LC Call No.:   QA529.L43 1854
Subjects:      Geometry.
               Trigonometry.
Control No.:   9600696

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry, from the
                  works of A. M. Legendre.
Published:     New York, A. S. Barnes & co.; 1851.
Description:   viii, [9]-370, 62 p. diagr. 21 cm.
LC Call No.:   QA529.L43 1851
Notes:         A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Geometry.
               Trigonometry.
Control No.:   9132182

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Uniform Title: Eléments de géométrie. English
Title:         Elements of geometry and trigonometry; with
                  notes. Translated from the French of A.M. Legendre [by T.
                  Carlyle] ... Edited by David Brewster ... With notes and
                  additions, and an introductory chapter on proportion [by the
                  translator].
Published:     Edinburgh, Oliver & Boyd; [etc., etc.] 1824.
Description:   xvi p., 1 l., 367, [1] p. diagr. 22 cm.
LC Call No.:   QA529.L43 1824
Subjects:      Geometry.
               Trigonometry.
Other authors: Brewster, David, Sir, 1781-1868, ed.
               Carlyle, Thomas, 1795-1881, tr.
Control No.:   4052107

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Selected propositions in geometrical
                  constructions and application of algebra to geometry. Being a
                  key to the appendix of Davies' Legendre.
Published:     New York, Chicago [etc.] A. S. Barnes & company
                  [c1882]
Description:   iv, [5]-181 p. diagrs. 21 cm.
LC Call No.:   QA529.L45 1882
Subjects:      Geometry.
Other authors: Davies, Charles, 1798-1876.
Control No.:   6324885

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Selected propositions in geometrical
                  constructions and applications of algebra to geometry. Being
                  a key to the appendix of Davies' Legendre.
Published:     New York, Chicago [etc.] A.S. Barnes & company,
                  1875.
Description:   iv, [5]-70 p. diagrs. 21 cm.
LC Call No.:   QA529.L45 1875
Subjects:      Geometry.
Other authors: Davies, Charles, 1798-1876.
Control No.:   6793016

Author:        Legendre, A[drien] M[arie] 1752-1833. [from old
                  catalog]
Title:         Elements of geometry and trigonometry;
Published:     New York, J. Ryan, 1828,
Description:   xvi, 316 p. diagr. 22 cm.
LC Call No.:   QA529.L43 1828
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   6789936

Author:        Leslie, John, Sir, 1766-1832.
Title:         Rudiments of plane geometry, including
                  geometrical analysis, and plane trigonometry ... By John
                  Leslie ...
Published:     Edinburgh, Oliver & Boyd, 1828.
Description:   v, 206 p. 22 cm.
LC Call No.:   QA529.L64
Subjects:      Geometry, Plane.
               Plane trigonometry.
Control No.:   8666368

Author:        Leslie, John, Sir, 1766-1832. [from old catalog]
Title:         Elements of geometry and plane trigonometry.
Edition:       3d ed.
Published:     Edinburgh, Printed for A. Constable & co.; [etc.,
                  etc.] 1817.
Description:   viii, 432 p. diagr. 21 cm.
LC Call No.:   QA529.L63
Subjects:      Geometry, Plane. [from old catalog]
               Plane trigonometry.
Control No.:   8198223

Author:        Lewis, Enoch, 1776-1856.
Title:         A treatise on plane and spherical trigonometry;
                  including the construction of the auxiliary tables; a concise
                  tract on the conic sections, and the principles of spherical
                  projection. By Enoch Lewis.
Published:     Philadelphia, H. Orr, 1844.
Description:   1 p. l., v-ix, [11]-228 p. diagr. 22 cm.
LC Call No.:   QA529.L67
Subjects:      Trigonometry.
               Conic sections.
               Spherical projection.
Control No.:   8666366

Author:        Loomis, Elias, 1811-1889.
Title:         Elements of geometry, conic sections, and plane
                  trigonometry / by Elias Loomis.
Edition:       Rev. ed.
Published:     New York : Harper & Brothers, 1871.
Description:   388, 12 p. : ill. ; 20 cm.
LC Call No.:   QA529.L7 1871
Notes:         "Logarithms of numbers from 1 to 10,000": p.
                  321-342.
               "Logarithmic sines and tangents for every degree
                  and minute of the quadrant": p. 343-388.
               "Loomis's series of text-books": 12 p. at end.
Subjects:      Geometry.
               Trigonometry.
Control No.:   10065502

Author:        Loomis, Elias, 1811-1889. [from old catalog]
Title:         Elements of geometry, conic sections and plane
                  trigonometry.
Edition:       Rev. ed.
Published:     New York, Harper & brothers, 1890.
Description:   vi, [7]-443 p. incl. tables, diagrs. 21 cm.
LC Call No.:   QA529.L7
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   6373112

Author:        Loomis, Elias, 1811-1889. [from old catalog]
Title:         Elements of geometry, conic sections and plane
                  trigonometry.
Edition:       Rev. ed.
Published:     New York, Harper & brothers, 1877.
Description:   vi, [7]-443 p. incl. tables, diagrs. 20 cm.
LC Call No.:   QA529.L7 1877
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9597239

Author:        Loomis, Elias, 1811-1889. [from old catalog]
Title:         Elements of geometry, conic sections and plane
                  trigonometry.
Published:     New York, Harper & brothers, 1869.
Description:   vi p., 1 l., [9]-234, [7]-58 p. diagrs. 20 cm.
LC Call No.:   QA529.L7 1869
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   7723589

Author:        Moˆcnik, Franc, 1814-1892.
Title:         Corso di goemetria ad uso dei ginnasi superiori
Edition:       2. ed.
Published:     Vienna, Presso l'I. R. amministrazione per la
                  vendita dei libri scolastici, 1865.
Description:   viii, 286 p. diagr. 24 cm.
LC Call No.:   QA529.M68
Subjects:      Geometry.
               Trigonometry.
Control No.:   8198221

Author:        Newcomb, Simon, 1835- [from old catalog]
Title:         Elements of plane geometry and trigonometry,
Published:     New York, H. Holt and company, 1882.
Description:   vii, [1], 335 p. tab., diagr. 20 cm.
LC Call No.:   QA529.N53
Subjects:      Geometry, Plane. [from old catalog]
               Plane trigonometry.
Control No.:   5856999

Author:        Olney, Edward, 1827-1887. [from old catalog]
Title:         Key to Olney's elements of geometry and plan and
                  spherical trigonometry,
Published:     New York, Sheldon and company, 1880.
Description:   109 p. diagrs. 20 cm.
LC Call No.:   QA529.O53
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Other authors: Beman, Wooster Woodruff, 1850-1922. [from old
                  catalog]
Control No.:   7261388

Author:        Olney, Edward, 1827-1887. [from old catalog]
Title:         A treatise on special or elementary geometry.
Published:     New York, Sheldon & company, 1872.
Description:   ix, 239 p., 1 l., [2], 113, 88 p. front., diagrs.
                  22 cm.
LC Call No.:   QA529.O52
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   8659803

Author:        Peck, William G. (William Guy), 1820-1892.
Title:         Manual of geometry and conic sections, with
                  applications to trigonometry and mensuration. By William G.
                  Peck ...
Published:     New York, Chicago [etc.] A.S. Barnes & company,
                  1876.
Description:   304, 62 p. tab., diagr. 20 cm.
LC Call No.:   QA529.P36
Subjects:      Geometry.
               Conic sections.
               Trigonometry.
Control No.:   3579326

Author:        Perkins, George R. (George Roberts), 1812-1876.
Title:         Plane and solid geometry. To which is added plane
                  and spherical trigonometry and mensuration.
Published:     New York, London, D. Appleton & co., 1855.
Description:   vii, 235 p., 1 l., 124, 84 p. tab., diagr. 24
                  cm.
LC Call No.:   QA529.P44
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   7729494

Author:        Robinson, Horatio N[elson], 1806-1867. [from old
                  catalog]
Title:         Elements of geometry,
Published:     New York, Ivison, Phinney & co.; [etc., etc.]
                  1860.
Description:   viii, 9-383, 70 p. tab., diagr. 21 cm.
LC Call No.:   QA529.R66
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   10071392

Author:        Robinson, Horatio Nelson, 1806-1867. [from old
                  catalog]
Title:         Elements of geometry,
Published:     Cincinnati, J. Ernst; 1850.
Description:   viii, [9]-270, 65 p. incl. tables, diagrs. 21
                  cm.
LC Call No.:   QA529.R65
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
               Conic sections. [from old catalog]
Control No.:   9603100

Author:        Robinson, Horatio N[elson], 1806-1867. [from old
                  catalog]
Title:         Elements of geometry, and plane spherical
                  trigonometry.
Edition:       New ed.
Published:     New York and Chicago, Ivison, Blakeman & company
                  [1889]
Description:   viii, 9-383, 70 p. diagr. 21 cm.
LC Call No.:   QA529.R68
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   6793017

Author:        Robinson, Horatio N[elson], 1806-1867. [from old
                  catalog]
Title:         Elements of plane and spherical trigonometry,
Published:     New York, Cincinnati [etc.] American book company
                  [c1895]
Description:   1 p. l., [1], 244-383, [1], 70 p. tab. 21 cm.
LC Call No.:   QA529.R68
Subjects:      Trigonometry. [from old catalog]
Control No.:   6324906

Author:        Robinson, [Horatio Nelson], 1806-1867. [from old
                  catalog]
Title:         Key to Robinson's new geometry and trigonometry,
Published:     New York and Chicago, Ivison, Blakeman & company
                  [1889]
Description:   iv, [5]-270 p. diagr. 21 cm.
LC Call No.:   QA529.R69
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
               Conic sections. [from old catalog]
               Geometry, Analytic. [from old catalog]
Control No.:   8666367

Author:        Robinson, [Horatio Nelson], 1806-1867. [from old
                  catalog]
Title:         Key to Robinson's new geometry and trigonometry,
                  and conic sections and analytical geometry.
Published:     New York, Ivison, Phinney & co.; Chicago, S. C.
                  Griggs & co., 1862.
Description:   iv, [5]-186 p. diagr. 21 cm.
LC Call No.:   QA529.R67
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
               Conic sections. [from old catalog]
               Geometry, Analytic. [from old catalog]
Control No.:   6324886

Author:        [Robinson, Horatio Nelson] 1806-1867. [from old
                  catalog]
Title:         Plane trigonometry and spherical geometry and
                  trigonometry.
Published:     New York and Chicago [c1889]
Description:   243-383, 70 p. incl. tables, diagrs. 21 cm.
LC Call No.:   QA529.R68
Subjects:      Trigonometry. [from old catalog]
Control No.:   8666385

Author:        Rusinoff, S. E. (Samuel Eugene), 1894-
Title:         Shop geometry and trigonometry.
Published:     Chicago, American Technical Society, 1949.
Description:   viii, 210 p. diagrs. 22 cm.
LC Call No.:   QA529.R8
Dewey No.:     513
Notes:         "Reprinted from Mathematics for industry,
                  chapters v, vi, and vii."
Subjects:      Geometry.
               Trigonometry.
Control No.:   10229854

Author:        Scholfield, Nathan.
Title:         A series on elementary and higher geometry,
                  trigonometry, and mensuration, containing many valuable
                  discoveries and impovements in mathematical science ...
                  designed as a text book for collegiate and academic
                  instruction, and as a practical compendium on mensuration. By
                  Nathan Scholfield.
Published:     New York, Collins brothers & co., 1845.
Description:   4 v. in 2. diagr. 22 cm.
LC Call No.:   QA529.S36
Notes:         pt. 1. Elements of plane geometry and
                  mensuration, on the basis of Legendre's elements.--pt. 2.
                  Elements of solid geometry and mensuration.--pt. 3. Higher
                  geometry and trigonometry.--pt. 4. Higher geometry and
                  mensuration.
Subjects:      Geometry.
               Trigonometry.
               Mensuration.
               Conic sections.
Control No.:   8198222

Author:        Scholfield, Nathan. [from old catalog]
Title:         Higher geometry & trigonometry.
Published:     [n.p.] 1845.
Description:   1 v. cm.
LC Call No.:   QA529.S37
Control No.:   6733773

Author:        Sestini, B[enedict] [from old catalog]
Title:         Elements of geometry and trigonometry.
Published:     Baltimore, J. Murphy & co., 1856.
Description:   303, 62 p. tab., diagr. 24 cm.
LC Call No.:   QA529.S49
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   5857000

Author:        Sharpless, Isaac, 1848- [from old catalog]
Title:         The elements of geometry and trigonometry and a
                  treatise on mensuration;
Published:     Philadelphia, Porter & Coates [1882]
Description:   266, 56, 64 p. tab., diagr. 20 cm.
LC Call No.:   QA529.S53
Subjects:      Geometry. [from old catalog]
               Plane trigonometry.
Control No.:   7261389

Author:        Tappan, Eli T[odd], 1824- [from old catalog]
Title:         Treatise on geometry and trigonometry; for
                  colleges, schools and private students.
Published:     Cincinnati, Sargent, Wilson & Hinkle; Chocago,
                  Cobb, Pritchard & co.; [etc., etc., c1868]
Description:   viii, 9-420 p. tab., diagr. 21 cm.
LC Call No.:   QA529.T17
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9134595

Author:        Tate, Thomas, 1807-1888.
Title:         Principles of geometry, mensuration,
                  trigonometry, land-surveying, and levelling:
Edition:       3d ed.
Published:     London, Longman, Brown, Green, and Longmans,
                  1848.
Description:   viii p., 2 l., 261, [1] p. diagr. 18 cm.
LC Call No.:   QA529.T21
Subjects:      Geometry.
               Mensuration.
               Trigonometry.
               Surveying.
Control No.:   7729495

Author:        Thieme, Friedrich Eduard. [from old catalog]
Title:         Lehrbuch zur niedern geometrie,
Published:     Plauen, A. Schröter, 1847-50.
Description:   2 v. diagr. 21 cm.
LC Call No.:   QA529.T43
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   10071393

Author:        United correspondence schools. [from old
                  catalog]
Title:         Instruction paper. Geometry, trigometry &
                  mensuration.
Published:     [n.p.] [1897]
Description:   1 v. cm.
LC Call No.:   QA529.U58
Control No.:   8607572

Author:        United correspondence schools. [from old
                  catalog]
Title:         Question paper. Geometry, trigonometry &
                  mensuration.
Published:     [n.p.] [1898]
Description:   1 v. cm.
LC Call No.:   QA529.U59
Control No.:   9079193

Author:        Vallín y Bustillo, Acisclo Fernández,
                  1835-1904. [from old catalog]
Title:         Elementos de matematicas,
Edition:       8. ed.
Published:     Madrid, Impr. de S. Aguado, 1859.
Description:   168 p., 1 l., [5]-116, 4 p. 22 cm.
LC Call No.:   QA529.V18 1859
Subjects:      Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9603101

Author:        Ballou, Donald H. (Donald Henry), 1908-
Title:         Spherical trigonometry : with tables / by Donald
                  H. Ballou and Frederick H. Steen.
Published:     Boston : Ginn, 1943.
Description:   iv, 109-176, 3, [1], 84 p. ill., maps, diagrs.
LC Call No.:   QA535.B17
Notes:         "The material ... has been taken from the
                  authors' Plane and spherical trigonometry, with tables"--
                  Pref.
               "Answers": 3, [1] p. following p. 176.
               "Proportional parts of differences" (table) on
                  card in pocket.
               Includes index.
Subjects:      Spherical trigonometry.
Other authors: Steen, Frederick Henry, 1907-
Control No.:   7395359

Author:        Bangma, Obbe Sikkes, 1768-1829. [from old
                  catalog]
Title:         Verhandeling over de regtlijnige en klootsche
                  driehoeksmeting;
Published:     Te Amsterdam, Bij J. van der Hey, 1808.
Description:   vi, 126 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA535.B3
Subjects:      Spherical trigonometry.
Other authors: Wiskundig genootschap, onder de zinspreuk: "Een
                  onvermoeide arbeid komt alles te boven," Amsterdam. [from old
                  catalog]
Control No.:   10087569

Author:        Bell, Herbert.
Title:         A course on the solution of spherical triangles
                  for the mathematical laboratory, by Herbert Bell ...
Published:     London, G. Bell & sons, limited. 1915.
Description:   viii, 66 p. diagrs. 22 cm.
Series:        Edinburgh mathematical tracts ; no. 5
LC Call No.:   QA535.B4
Subjects:      Spherical trigonometry.
Control No.:   273483

Author:        Brenke, William Charles, b. 1874.
Title:         Spherical trigonometry, by W. C. Brenke. Chapters
                  XI and XII of "Plane and spherical trigonometry."
Published:     New York, The Dryden Press [1943].
Description:   viii, 71, 27 p. diagrs. 21 cm.
Series:        The Dryden press Mathematics publications;
                  general editor, E. R. Smith.
LC Call No.:   QA535.B68
Dewey No.:     514.6
Notes:         Plane and spherical trigonometry is a complete
                  rewriting of the author's Elements of trigonometry.
               "Answers to the odd numbered exercises": p. 49.
Subjects:      Spherical trigonometry.
Control No.:   8327923

Author:        Brink, Raymond Woodward, 1890- [from old
                  catalog]
Title:         Spherical trigonometry,
Published:     New York, London, D. Appleton-Century company,
                  incoporated [1942]
Description:   viii p., 1 l., 62 p. diagrs. 21 cm.
LC Call No.:   QA535.B7
Subjects:      Spherical trigonometry.
Control No.:   6450810

Author:        Byrne, Oliver. [from old catalog]
Title:         A short practical treatise on spherical
                  trigonometry ...
Published:     London, A. J. Valpy, 1835.
Description:   xi, 37 p. diagr. 21 cm.
LC Call No.:   QA535.B9
Subjects:      Spherical trigonometry.
Control No.:   7729804

Author:        Casey, John, 1820-1891.
Title:         A treatise on spherical trigonometry, and its
                  application to geodesy and astronomy, with numerous examples.
                  By John Casey ...
Published:     Dublin, Hodges, Figgis, & co.; [etc., etc.]
                  1889.
Description:   xv, [1], 165 p. diagrs. 19 cm.
LC Call No.:   QA535.C3
Notes:         "Intended as a sequel to the author's Treatise on
                  plane trigonometry."--Pref.
Subjects:      Spherical trigonometry.
Control No.:   1219744

Author:        Constan, Paul Armand Jean Marie.
Title:         Cours de trigonométrie sphérique, à l'usage
                  des marins et des personnes qui ont en vue l'étude de
                  l'astronomie ou de la géodésie, par P. Constan.
Edition:       3d. éd., en harmonie avec les derniers
                  programmes.
Published:     Paris, Société d'éditions géographiques,
                  maritimes et coloniales, 1941.
Description:   125, [1] p. diagrs. 23 cm.
Series:        Bibliothèque des capitaines de commerce et des
                  candidats aux examens de la marine marchande
LC Call No.:   QA535.C6 1941
Subjects:      Spherical trigonometry -- Textbooks.
Control No.:   8346400

Author:        Crantz, Paul.
Title:         Sphärische Trigonometrie nebst anwendungen zum
                  Selbstunterricht, von prof. P. Crantz. Mit 114 gelösten
                  Aufgaben, 67 Figuren und einem Nomogramm des allgemeinen
                  Kugeldreicks.
Edition:       2. Aufl. neubearbeitet von Dr. M. Hauptmann.
Published:     Leipzig, Berlin, B. G. Teubner, 1929.
Description:   107 p. diagrs. 19 cm.
Series:        Mathematisch-physikalische Bibliothek, Reihe 2,
                  7
LC Call No.:   QA535.C7 1929
Subjects:      Spherical trigonometry.
Other authors: Hauptmann, M. (Max), 1876-
Control No.:   10167434

Author:        Crantz, Paul.
Title:         Sphärische Trigonometrie zum Selbstunterricht,
                  von prof. P. Crantz. Mit 27 Figuren im Text.
Published:     Leipzig, Berlin, B. G. Teubner, 1920.
Description:   98 p. diagrs. 19 cm.
Series:        Aus Natur und Geisteswelt; Sammlung
                  wissenschaftlich-gemeinverständlicher Darstellungen. 605.
                  Bdchen
LC Call No.:   QA535.C7 1920
Subjects:      Spherical trigonometry.
Series Entry:  Aus Natur und Geisteswelt ; 605. Bdchen.
Control No.:   6925653

Author:        Curtiss, David Raymond, b. 1878.
Title:         Essentials of spherical trigonometry with
                  applications,
Published:     Boston, New York [etc.] D. C. Heath and company
                  [1942]
Description:   iii, 109-160, [8] p. diagrs. 23 cm.
LC Call No.:   QA535.C8
Subjects:      Spherical trigonometry.
Other authors: Moulton, Elton James, b. 1887, joint author.
Control No.:   9073508

Author:        Donnay, J. D. H. (Joseph Désiré Hubert), 1902-
Title:         Spherical trigonometry after the Cesàro method
                  [by] J.D.H. Donnay ...
Published:     New York, N.Y., Interscience publishers, inc.,
                  1945.
Description:   xi, 83 p. diagrs. 19 cm.
LC Call No.:   QA535.D6
Dewey No.:     514.6
Notes:         "Answers to exercises": p. 74-75.
Subjects:      Spherical trigonometry.
               Cesàro, Giuseppe, 1849-1939.
Control No.:   275169

Author:        Euler, Leonhard, 1707-1783.
Title:         Zwei abhandlungen über sphärische
                  trigonometrie. Grundzüge der sphärischen trigonometrie und
                  Allgemeine sphärische trigonometrie 1753 und 1779. Von
                  Leonhard Euler. Aus dem französischen und lateinischen
                  übers. und hrsg. von E. Hammer. Mit 6 figuren im text.
Published:     Leipzig, W. Engelmann, 1896.
Description:   65, [1] p. diagr. 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 73
LC Call No.:   QA535.E88
Notes:         Original titles: I. Principes de la
                  trigonométrie sphérique, tirés de la méthode des plus
                  grands et plus petits; mémoires de l'Académie royale des
                  sciences et belles-lettres (Berlin), classe de philosophie
                  experimentale, tome 9, année 1753. [Berlin, 1755]--II.
                  Trigonometria sphaerica universa, ex primis principiis
                  breviter et dilucide derivata; Acta Academiae scientiarum
                  imperialis petropolitanae, pro anno 1779, pars prior. [St.
                  Petersburg, 1782]
Subjects:      Spherical trigonometry.
Other authors: Hammer, E. (Ernst), 1858- ed. and tr.
Series Entry:  Ostwalds Klassiker der exakten Wissenschaften ;
                  Bd. 73.
Control No.:   744787

Author:        Freilich, Aaron. [from old catalog]
Title:         Spherical trigonometry
Published:     New York, Chicago [etc.] Silver Burdett company,
                  c1943.
Description:   iii, [1], 140 p. illus. (incl. port.) diagrs. 19
                  cm.
LC Call No.:   QA535.F7
Subjects:      Spherical trigonometry.
Other authors: Shanholt, Henry Harris, [from old catalog] joint
                  author.
               Seidlin, Joseph, 1892- [from old catalog] joint
                  author.
Control No.:   6454760

Author:        Granville, William Anthony, 1863-1943.
Title:         Spherical trigonometry and tables, by William
                  Anthony Granville. Revised by Percey F. Smith and James S.
                  Mikesh.
Published:     Boston, New York, Ginn [1942]
Description:   xviii, 211-270 p., 1 l., iv, 43 p. diagrs. 24
                  cm.
Series:        Mathematical texts for colleges
LC Call No.:   QA535.G7
Dewey No.:     514.6
Notes:         "Four-place logarithmic and trigonometric tables"
                  (iv, 43 p. at end) has special t.-p.
               A reissue, with the addition of an introduction
                  on "Applications to sailing," of a part of the author's Plane
                  and spherical trigonometry and Four-place tables ... [1941]
Subjects:      Spherical trigonometry.
Other authors: Smith, Percey F. (Percey Franklyn), 1867-1956.
               Mikesh, James S. (James Stephens)
Control No.:   9260159

Author:        Granville, William Anthony, 1863- [from old
                  catalog]
Title:         Spherical trigonometry and tables,
Published:     Boston, New York [etc.] Ginn and company [1943]
Description:   xviii, 211-272, iv, 44, [3] p. diagrs. 23 cm.
LC Call No.:   QA535.G7 1943
Subjects:      Spherical trigonometry.
Other authors: Smith, Percey F. (Percey Franklyn), 1867-1956.
               Mikesh, James Stephens. [from old catalog]
Control No.:   7863044

Author:        Griffin, Frank Loxley, b. 1881.
Title:         An introduction to spherical trigonometry : the
                  solution of triangles / by Frank Loxley Griffin.
Published:     Boston ; New York : Houghton Mifflin, [1943]
Description:   1 p. leaf, 30 p. : ill. ; 21 cm.
LC Call No.:   QA535.G76
Subjects:      Spherical trigonometry.
Control No.:   5991054

Author:        Hammond, Jacques Redway. [from old catalog]
Title:         Concise spherical trigonometry,
Published:     Boston, New York [etc.] Houghton Mifflin company
                  [1943]
Description:   xii, 256 p. double chart, diagrs. 22 cm.
LC Call No.:   QA535.H3
Subjects:      Spherical trigonometry.
Control No.:   7859200

Author:        880-01 Kakud¯o, fl. 18th/19th cent.
Title:         880-02 Enri kiku sanp¯o : tetsujutsu s¯okai.
Published:     880-03 T¯oky¯o : Suharaya Moh¯e, [between 1868
                  and 1878]
Description:   2 v. : ill. ; 24 cm.
LC Call No.:   QA535.K35 1868
Notes:         Cataloged from title piece mounted on cover.
               Originally written in Kanbun by Seik¯u Kakud¯o
                  (pref. dated 1794); annotated with reading marks added by
                  Takeda Nobumasa (pref. dated 1836). Cf. v. 1, pref. for both
                  editions.
               On double leaves, oriental style.
               Originally published: ¯Osaka : Itamiya Zenb¯e,
                  1863.
Subjects:      Spherical trigonometry.
Other authors: 880-04 Takeda, Nobumasa.
Control No.:   5297629

Author:        Kells, Lyman M. (Lyman Morse), 1888-
Title:         Spherical trigonometry, with naval and military
                  applications, by Lyman M. Kells ... Willis F. Kern ... and
                  James R. Bland ...
Edition:       1st ed.
Published:     New York, London, McGraw-Hill book company, inc.,
                  1942.
Description:   xiii, 163 p. incl. front., illus., diagrs. 24
                  cm.
LC Call No.:   QA535.K4
Dewey No.:     514.6
Notes:         "Answers": p. 153-163.
Subjects:      Spherical trigonometry.
Other authors: Kern, Willis F. (Willis Frederick), 1903- joint
                  author.
               Bland, James R., joint author.
Control No.:   2636302

Author:        Magini, Giovanni Antonio, 1555-1617.
Title:         Primum mobile : duodecim libris contentum : in
                  quibus habentur trigonometria sphaericorum, et astronomica,
                  gnomonica, geographicaâq[ue] problemata, ac pr[a]eterea
                  magnus trigonometricus canon emendatus et auctus, ac magna
                  primi mobilis tabula ad decades primorum scrupulorum per
                  utrumq[ue] latus supputata / auctore Io. Antonio Magino ...
Published:     Bononiae : Impensis ipsius auctoris, 1609.
Description:   [8], 290, 182, 15 [i.e. 22] leaves : ill. ; 35
                  cm. (fol.)
LC Call No.:   QA535.M26 1609
Notes:         Engraved t.p., illustrated.
               Books 5-12 have special t.p. with imprint:
                  Bononiae : Apud Io. Baptistam Bellagambam, 1609.
               The tabular section has special t.p., with title:
                  Io. Antonii Magini ... Tabulae generales ad primum mobile
                  spectantes : & primò quidem sequitur Magnus canon
                  mathematicus seu trigonometriae : nunc primùm ab auctore
                  ipso auctus ..., and with imprint: Bononiae : Apud haeredes
                  Ioannis Rossij, 1609, and colophon: Venetiis : Apud Gratiosum
                  Perchacinum, 1609.
               Signatures: ap2s bp4s cp2s A-4Bp4s
                  4Cp6s, p2sA-Kp4s Lp6s M-2Yp4s, p3sA-Bp4s Cp2s
                  D-Fp4s.
Subjects:      Spherical trigonometry -- Early works to 1800.
               Trigonometry -- Tables -- Early works to 1800.
               Astronomy -- Early works to 1800.
               Sundials -- Early works to 1800.
Other authors: Magini, Giovanni Antonio, 1555-1617. Tabulae
                  generales ad primum mobile spectantes. 1609.
Other titles:  Tabulae generales ad primum mobile spectantes.
Control No.:   1922260

Author:        M'Clelland, William J. [from old catalog]
Title:         A treatise on spherical trigonometry,
Published:     London and New York, Macmillan and co., 1886-
Description:   1 v. diagrs. 19 cm.
LC Call No.:   QA535.M32
Subjects:      Spherical trigonometry.
Other authors: Preston, Thomas, 1860-1900, [from old catalog]
                  joint author.
Control No.:   6940601

Author:        M'Clelland, William J. [from old catalog]
Title:         A treatise on spherical trigonometry, with
                  numerous examples ...
Published:     Dublin, Hodges, Figgis, & co. [etc., etc.] 1885-
Description:   1 v. diagrs. 20 cm.
LC Call No.:   QA535.M3
Subjects:      Spherical trigonometry.
Other authors: Preston, Thomas, 1860-1900, [from old catalog]
                  joint author.
Control No.:   6472383

Author:        Moritz, Robert Edouard, 1868-1940.
Title:         A text-book on spherical trigonometry, by Robert
                  E. Moritz.
Edition:       1st ed. 1st thousand.
Published:     New York, J. Wiley & sons; [etc., etc.] 1913.
Description:   vi 67 p. diagrs. 24 cm.
LC Call No.:   QA535.M7
Subjects:      Spherical trigonometry.
Control No.:   13194863

Author:        Murray, Daniel A. (Daniel Alexander), 1862-1934.
Title:         Spherical trigonometry, for colleges and
                  secondary schools, by Daniel A. Murray ...
Published:     New York, London, Bombay, Longmans, Green and
                  Co., 1900.
Description:   ix, 114 p. pl., diagrs. 21 cm.
LC Call No.:   QA535.M9
Subjects:      Spherical trigonometry.
Control No.:   9594826

Author:        Peirce, Benjamin, 1809-1880.
Title:         First part of an elementary treatise on spherical
                  trigonometry / by Benjamin Peirce.
Published:     Boston : J. Munroe, 1836.
Description:   iv, 71 p., [1] folded leaf of plates : ill. ; 20
                  cm.
LC Call No.:   QA535.P3
Subjects:      Spherical trigonometry.
Control No.:   10071702

Author:        Pires, Francisco Miguel, d. 1853. [from old
                  catalog]
Title:         Tratado de trigonometria espherica,
Edition:       [2d. ed.]
Published:     Rio de Janeiro, Reimpresso na Typographia
                  nacional, 1856.
Description:   36, [1] p. fold. pl. 22 cm.
LC Call No.:   QA535.P66
Subjects:      Spherical trigonometry.
Control No.:   8197294

Author:        Richard, Eugene Lamb, 1838-1912. [from old
                  catalog]
Title:         The elements of spherical trigonometry.
Published:     New York, D. Appleton and company, 1879.
Description:   iv p., 1 l., p [113-207. diagrs. 20 cm.
LC Call No.:   QA535.R5
Subjects:      Spherical trigonometry.
Control No.:   9603414

Author:        Saija, Giuseppe, 1864-1900. [from old catalog]
Title:         Beitrag zur graphischen sphärishen
                  trigonometrie.
Published:     [Berlin, 1896]
Description:   [695]-703 p. diagrs. 23 cm.
LC Call No.:   QA535.S13
Subjects:      Spherical trigonometry.
Control No.:   7732588

Author:        Saldías, Eulogio S. [from old catalog]
Title:         Curso de trigonometría esférica,
Published:     La Punta-Callao, Talleres tipográficos de la
                  Escuela naval del Perú, 1923.
Description:   276, vii p. diagrs. 24 cm.
LC Call No.:   QA535.S2
Subjects:      Spherical trigonometry.
Control No.:   10206459

Author:        Sniadecki, Jan, 1756-1830. [from old catalog]
Title:         Trygonometrya kulista analitycznie wyloçzona; z
                  przysto-sowaniem do rozmiaru ziemi i do zadaân
                  astronomicznych.
Edition:       Wyd. 2.
Published:     W. Wilnie, Nakl. i drukiem J. Zawadzkiego, 1820.
Description:   166 p. illus. 22 cm.
LC Call No.:   QA535.S57 1820
Subjects:      Spherical trigonometry.
Control No.:   7107265

Author:        Snowball, J[ohn] C[harles], d. 1855. [from old
                  catalog]
Title:         The elements of spherical trigonometry.
Published:     Cambridge, Printed by J. Smith, 1834-
Description:   v, [1], 65 p. fold. pl. 22 cm.
LC Call No.:   QA535.S
Subjects:      Spherical trigonometry.
Control No.:   7729514

Author:        Sperry, Pauline, b. 1885.
Title:         Short course in spherical trigonometry, by
                  Pauline Sperry.
Published:     Richmond, Atlanta, Johnson Publishing Company
                  [c1928]
Description:   ix p., 1 l., 60 p. diagrs. 24 cm.
Series:        Johnson's mathematics series
LC Call No.:   QA535.S6
Subjects:      Spherical trigonometry.
Control No.:   6399760

Author:        Stanley, Anthony Dumond, 1810-1853. [from old
                  catalog]
Title:         An elementary treatise of spherical geometry and
                  trigonometry.
Published:     New Haven, Durrie & Peck, 1848.
Description:   2 p. l., [7]-122 p. diagrs. 19 cm.
LC Call No.:   QA535.S8
Subjects:      Spherical trigonometry.
               Sphere. [from old catalog]
Control No.:   10113021

Author:        Thompson, James Edgar, 1892-
Title:         Elements of spherical trigonometry, by James E.
                  Thompson.
Published:     New York, D. Van Nostrand company, inc., c1942.
Description:   xi, [1] 144 p. diagrs. 20 cm.
LC Call No.:   QA535.T45
Dewey No.:     514.6
Subjects:      Spherical trigonometry.
Control No.:   7854782

Author:        Todhunter, I. (Isaac), 1820-1884.
Title:         Spherical trigonometry, for the use of colleges
                  and schools. By the late I. Todhunter.  Revised by J. G.
                  Leathem.
Published:     London Macmillan and co., limited; New York, The
                  Macmillan company, 1901.
Description:   xii, 275 p. diagr. 19 cm.
LC Call No.:   QA535.T6 1901
Subjects:      Spherical trigonometry.
Other authors: Leathem, J. G. (John Gaston), b. 1871, ed.
Control No.:   6322295

Author:        Todhunter, I. (Isaac), 1820-1884.
Title:         Spherical trigonometry, for the use of colleges
                  and schools : with numerous examples / by I. Todhunter.
Edition:       2d ed., enl.
Published:     Cambridge; London : Macmillan, 1863.
Description:   4 l., 132 p. : illus. ; 20 cm.
LC Call No.:   QA535.T6 1863
Notes:         A sequel to the author's Plane trigonemetry.
Subjects:      Spherical trigonometry.
Control No.:   8330224

Author:        Turnbull, William. [from old catalog]
Title:         A new practical system of spherical trigonometry
                  ... By William Turnbull.
Published:     London, J. Imray, [1850]
Description:   xv, [1], 168 p. diagrs. 22 cm.
LC Call No.:   QA535.T8
               Microfilm 15788 QA
Notes:         "Supplemented by Key to the exercises of
                  spherical trigonometry ... By William Turnbull." (2 p.l., 36
                  p. 23 cm.) published: London, J. Imray, 1850. Call number
                  [QA535.T81  Suppl.]
               Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Spherical trigonometry.
Control No.:   6793326

Author:        United States Naval Academy. Dept. of
                  Mathematics.
Title:         Spherical trigonometry. Prepared for the
                  Department of mathematics, United States Naval academy by H.
                  T. Muhly and S. S. Saslaw.
Published:     Annapolis, Md., United States Naval academy,
                  1946.
Description:   viii, 85 p. diagrs. 26 cm.
LC Call No.:   QA535.U5 1946
Dewey No.:     514.6
Subjects:      Spherical trigonometry.
               Geometry, Solid.
Other authors: Muhly, Harry Townsend, 1916-
               Saslaw, Samuel Saul, 1909-
Control No.:   6471121

Author:        Ward, Seth, 1617-1689.
Title:         Idea trigonometriae demonstratae : (in usum
                  juventutis Oxoniensis) ; item praelectio De cometis et
                  Inquisitio in Bullialdi Astronomiae philolaicae fundamenta /
                  authore Setho Wardo ...
Published:     Oxoniae : Excudebat L. Lichfield, academiae
                  typographus, 1654.
Description:   [6], 22, [8], 44, [12], 47, [1] p. : ill. ; 19
                  cm. (4to)
LC Call No.:   QA535.W37x 1654
Notes:         The De cometis and the Inquisitio each have
                  special t.p.; the latter has title: In Ismaelis Bullialdi
                  Astronomiae philolaicae fundamenta, inquisitio brevis.
               Signatures: Ap4s(A1+'A2.3') B-Cp4s 2A-Fp4s
                  Gp2s H-Op4s Pp2s.
               Madan 2263
               Wing W821
Subjects:      Spherical trigonometry -- Early works to 1800.
               Comets -- Early works to 1800.
               Astronomy -- Early works to 1800.
               Boulliau, Ismael, 1605-1694. Astronomiae
                  philolaicae fundamenta.
Other authors: Ward, Seth, 1617-1689. De cometis. 1654.
Control No.:   2873306

Title:         Smith's regents review books. Trigonometry.
Published:     Buffalo, N.Y. W. Hazleton Smith, c1926.
Description:   47, [19] p. illus. 19 cm.
LC Call No.:   QA537.S6 1904-26
Subjects:      Trigonometry -- Problems, exercises, etc.
               Trigonometry -- Examinations, questions, etc.
Control No.:   13198772

Title:         Exams and answers: trigonometry.
Published:     Great Neck, N.Y.
Description:   v. 19 cm.
LC Call No.:   QA537.E9
Subjects:      Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   10923920

Title:         Smith's regents review books. Trigonometry
                  solutions.
Published:     Buffalo, N.Y. W. Hazleton Smith, c1926.
Description:   206 p. illus. 19 cm.
LC Call No.:   QA537.S6 1904-26a
Subjects:      Trigonometry -- Problems, exercises, etc.
Control No.:   13198781

Author:        Adams, C. W. [from old catalog]
Title:         A graphical solution of one case of spherical
                  triangles: also a new method of solving some spherical
                  triangles by plain trigonometry.
Published:     Wellington, N.Z., Printed by Ferguson & Osborn,
                  1915.
Description:   17 p. diagrs. 25 cm.
LC Call No.:   QA537.A4
Subjects:      Spherical trigonometry.
               Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   7786477

Author:        Brink Raymond W. (Raymond Woodward), 1890-
Title:         Tutorial exercises in trigonometry / by Raymond
                  W. Brink.
Published:     New York : The Century company, [1931]
Description:   102 leaves : ill. ; 28 cm.
LC Call No.:   QA537.B7
Notes:         Cover-title.
               Printed on one side of leaf only.
Subjects:      Trigonometry -- Problems, exercises, etc.
Other authors: Thorp, Ella.
Control No.:   8749526

Author:        Carnot, Lazare, 1753-1823.
Title:         Mémoire sur la relation qui existe entre les
                  distances respectives de cinq points quelconques pris dans
                  l'espace; suivi d'un Essai sur la théorie des transversales,
                  par L.N.M. Carnot ...
Published:     Paris, Courcier, 1806.
Description:   2 p.l., 111, [1] p. 3 fold. pl. (diagrs.) 26 x 21
                  cm.
LC Call No.:   QA537.C28
Subjects:      Trigonometry -- Problems, exercises, etc.
               Geometry -- Problems, exercises, etc.
Control No.:   2163724

Author:        Crawley, Edwin S. (Edwin Schofield), 1862- comp.
Title:         One thousand exercises in plane and spherical
                  trigonometry, comp. by Edwin S. Crawley ...
Published:     Philadelphia, E. S. Crawley, 1914.
Description:   v, 70 p. 22 cm.
LC Call No.:   QA537.C7
Subjects:      Trigonometry -- Problems, exercises, etc.
Control No.:   7300647

Author:        Crowder, Norman A.
Title:         Trigonometry: a practical course, by Norman A.
                  Crowder and Grace C. Martin. Prepared under the direction of
                  Western Design & Electronics.
Edition:       [1st ed.]
Published:     Garden City, N.Y., Doubleday, 1961.
Description:   250 p. illus. 22 cm.
Series:        A Tudor text
LC Call No.:   QA537.C74
Dewey No.:     514.9
Subjects:      Trigonometry -- Problems, exercises, etc.
               Programmed instruction.
Other authors: Martin, Grace C., joint author.
Control No.:   6558768

Author:        Curtiss, David Raymond, b. 1878.
Title:         Exercises in trigonometry,
Published:     Boston, New York [etc.] D. C. Heath and company
                  [c1931]
Description:   cover-title, 223 p. diagrs. 28 cm.
LC Call No.:   QA537.C8
Subjects:      Trigonometry -- Problems, exercises, etc.
Other authors: Moulton, Elton James, b. 1887, joint author.
Control No.:   8282505

Author:        Folena, Bruce.
Title:         Industrial trigonometry.
Published:     New Brunswick, N.J. Curriculum Laboratory, Dept.
                  of Vocational-Technical Education, Graduate School of
                  Education, Rutgers University, 1963.
Description:   163 p. illus. 28 cm.
LC Call No.:   QA537.F6
Subjects:      Trigonometry -- Problems, exercises, etc.
Other authors: New Jersey. Division of Vocational Education.
                  Curriculum Laboratory, New Brunswick.
Control No.:   7052870

Author:        Gaskin, Thomas, 1811-1887.
Title:         Solutions of the trigonometrical problems,
                  proposed at St. John's college, Cambridge, from 1829 to 1846.
                  By Thomas Gaskin ...
Published:     Cambridge, Printed at the University press for
                  Deightons, 1847.
Description:   2 p.l., 228 p. diagrs. on III fold. pl. 22 cm.
LC Call No.:   QA537.G2
Subjects:      Trigonometry -- Problems, exercises, etc.
Control No.:   4525367

Author:        Gelder, Jacob de. [from old catalog]
Title:         Meetkundige analysis.
Published:     [n.p.] 1811-13.
Description:   1 v. cm.
LC Call No.:   QA537.G31
Control No.:   9084944

Author:        Hewitt, David, 1791-1867. [from old catalog]
Title:         Problems and theorems in plane trigonometry.
Published:     Cambridge, J. & J. J. Deighton; [etc., etc.]
                  1840.
Description:   xv, 127 p. 22 cm.
LC Call No.:   QA537.H6
Subjects:      Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   7731449

Author:        Hirsch, [Meyer], 1765-1851. [from old catalog]
Title:         Hirsch's geometry;
Published:     London, Black, Young and Young, 1827.
Description:   x, [2], 264 p. diagrs. 22 cm.
LC Call No.:   QA537.H7
Subjects:      Trigonometry -- Problems, exercises, etc.
Other authors: Ross, John Alexander, 1796-1868, [from old
                  catalog] tr.
               Wright, J. M. F. (John Martin Frederick), ed.
Control No.:   9136548

Author:        Hirsch, Meyer, 1765-1851. [from old catalog]
Title:         Sammlung geometrischer aufgaben,
Published:     Berlin, H. Frölich, 1805-
Description:   v. fold. plates (diagrs.) 17 cm.
LC Call No.:   QA537.H68
Subjects:      Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   9706394

Author:        Hite, Melville P.
Title:         The magic of plane trigonometry automatically.
Published:     Jacksonville, Fla., Technical Press, c1948.
Description:   99 p. ill. 20 cm.
LC Call No.:   QA537.H75
Subjects:      Trigonometry -- Problems, exercises, etc.
               Mensuration.
Control No.:   6949093

Author:        Jones, Franklin Turner, [from old catalog] comp.
Title:         Problems and questions on trigonometry and
                  logarithms, compiled from examinations of Amherst college
                  (Amherst) Boston university (Boston) ... and other examining
                  bodies,
Published:     Cleveland, Ohio [The University supply and book
                  co., c1930]
Description:   iv, 75 p. 19 cm.
LC Call No.:   QA537.J6 1930
Subjects:      Trigonometry -- Problems, exercises, etc.
               Logarithms -- Problems, exercises, etc.
               Universities and colleges -- Examinations --
                  Trigonometry. [from old catalog]
Control No.:   6405976

Author:        Jones, Franklin Turner, [from old catalog] comp.
Title:         Problems and questions on trigonometry and
                  logarithms, compiled from examinations of Amherst college,
                  Boston university ... and other examining bodies,
Edition:       [3d ed.]
Published:     Cleveland, Ohio [The University supply and book
                  co.] 1924.
Description:   iv, 72 p. 19 cm.
LC Call No.:   QA537.J6 1924
Subjects:      Trigonometry -- Problems, exercises, etc.
               Logarithms -- Problems, exercises, etc.
               Universities and colleges -- Examinations --
                  Trigonometry. [from old catalog]
Control No.:   6856470

Author:        Longley, William Raymond, 1880-1965.
Title:         Twelve lessons in trigonometry [by] Longley and
                  Wilson.
Published:     New Haven, Conn., Whitlock's book store, inc.
                  [c1928]
Description:   48 p. 23 cm.
LC Call No.:   QA537.L6
Notes:         Cover title.
               At head of title: Yale University, the freshman
                  year.
Subjects:      Trigonometry -- Problems, exercises, etc.
Other authors: Wilson, Wallace Alvin.
Control No.:   8739503

Author:        Malament, Daniel, 1913-
Title:         Review digest of plane trigonometry.
Edition:       [Rev.]
Published:     New York, Republic Book Co. [c1949]
Description:   86, [62] p. diagrs. 19 cm.
LC Call No.:   QA537.M3 1949
Dewey No.:     514.9
Notes:         On cover: Plane and spherical.
               "Meets the latest requirements of the New York
                  State Regents syllabus."
Subjects:      Trigonometry -- Problems, exercises, etc.
Control No.:   6011128

Author:        Malament, Daniel, 1913- [from old catalog]
Title:         Review digest of plane trigonometry
Published:     New York [1947]
Description:   71 p. diagrs. 18 cm.
LC Call No.:   QA537.M3
Subjects:      Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   7410720

Author:        Murray, Daniel A. (Daniel Alexander), 1862-1934.
Title:         Essentials of trigonometry and mensuration,
Edition:       New ed.
Published:     New York [etc.] Longmans, Green, and co., 1909.
Description:   x, 157 p. diagrs. 21 cm.
LC Call No.:   QA537.M973
Subjects:      Trigonometry.
               Mensuration.
               Algebra -- Graphic methods.
Control No.:   5879970

Author:        Murray, Daniel A. (Daniel Alexander), 1862-1934.
Title:         Practical mathematics : including solution of
                  triangles, measurement of areas, heights and distances, the
                  use of logarithms, plotting of graphs, and finding the slopes
                  of curves with four-place tables / by Daniel A. Murray ...
Published:     New York ; London : Longmans, Green, and co.,
                  1905.
Description:   x, 113 p. : diagrs. ; 21 cm.
LC Call No.:   QA537.M97
Notes:         With answers.
Subjects:      Trigonometry -- Problems, exercises, etc.
               Algebra -- Graphic methods.
Control No.:   7735658

Author:        Padley, A[ugustus] F[rederick] [from old
                  catalog]
Title:         Solutions of trigonometrical problems, together
                  with problems for exercise, chiefly collected from the
                  Cambridge examination papers.
Published:     Cambridge, W. P. Grant, 1841.
Description:   1 p.l., x, 72 p. diagrs. on 2 fold. pl. 22 cm.
LC Call No.:   QA537.P1
Subjects:      Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   7263361

Author:        Randolph, John F. (John Fitz), 1904-
Title:         Trigonometry.
Published:     New York, Macmillan [1953]
Description:   220 p. illus. 22 cm.
LC Call No.:   QA537.R35
Dewey No.:     514.9
Subjects:      Trigonometry -- Problems, exercises, etc.
Control No.:   6507348

Author:        Richards, Eugene Lamb.
Title:         Applications of plane and spherical trigonometry.
                  By Eugene L. Richards ...
Published:     New York, D. Appleton and Company, 1880.
Description:   2 p. l., [207]-295 p. diagrs. 19 cm.
LC Call No.:   QA537.R5
Notes:         Chapters XVI-XX of the author's Elements of plane
                  and spherical trigonometry.
Subjects:      Mensuration.
               Surveying.
               Navigation.
Control No.:   7734285

Author:        Robbins, Jack. [from old catalog]
Title:         New brief review in plane trigonometry;
Published:     New York, College Entrance Book Co. [1950]
Description:   iv, 63, [58] p. diagrs. 19 cm.
LC Call No.:   QA537.R58
Subjects:      Plane trigonometry -- Problems, exercises, etc.
Control No.:   10235286

Author:        Roeder, Hermann. [from old catalog]
Title:         Aufgaben aus der ebenen trigonometrie.
Published:     Breslau, F. Hirt, 1892.
Description:   145, [5] p. incl. tables. 22 cm.
LC Call No.:   QA537.R6
Subjects:      Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   6419054

Author:        Roeder, Hermann. [from old catalog]
Title:         Auflösungen der Aufgaben aus der ebenen
                  trigonometrie.
Published:     Breslau, F. Hirt, 1893.
Description:   62 p. 21 cm.
LC Call No.:   QA537.R62
Subjects:      Trigonometry -- Problems, exercises. etc. [from
                  old catalog]
Control No.:   8760233

Author:        Sides, Winfield Michael.
Title:         Examples in plane trigonometry, by Winfield M.
                  Sides.
Edition:       1st ed.
Published:     New York, London, McGraw-Hill Book Company, inc.,
                  1931.
Description:   vii, 79 p. 19 1/2 cm.
LC Call No.:   QA537.S5
Notes:         Blank pages for "Notes" (73-79)
Subjects:      Plane trigonometry.
Control No.:   8751541

Author:        [White, Charles Joyce], 1839- [from old catalog]
Title:         Problems in plane trigonometry.
Published:     Cambridge [Mass.] C. W. Sever [c1886]
Description:   24 p. diagr. 20 cm.
LC Call No.:   QA537.W5
Subjects:      Trigonometry -- Problems, exercises, etc.
Control No.:   5858948

Author:        Adams, C. E. [from old catalog]
Title:         On the construction of a table of natural sines
                  by means of a new relation between the leading dofferences.
Published:     [Wellington, 1903]
Description:   [408]-413 p. 22 cm.
LC Call No.:   QA538.A21
Subjects:      Trigonometry -- Tables.
Control No.:   6796466

Author:        Beez, [Richard], 1827- [from old catalog]
Title:         Ueber den dualismus in den metrischen relationen
                  am vollständigen viereck und vierseit auf der kugel und in
                  der ebene.
Published:     [Leipzig, 1862]
Description:   [129]-143 p. 22 cm.
LC Call No.:   QA538.B4
Subjects:      Trigonometry. [from old catalog]
Control No.:   6331986

Author:        Cole, John.
Title:         Stereogoniometry : also, leeway and magnetic
                  sailings / by John Cole, purser of H.M.S. Aboukir.
Published:     London : Printed by A.J. Valpy ... : Sold by Lunn
                  ... Sherwood, Neely, and Jones ..., 1812.
Description:   xv, [1], 326, [2] p., 8 folded leaves of plates :
                  ill. ; 23 cm.
LC Call No.:   QA538.C6
Notes:         Title vignette (monogram TF).
               Publisher's advertisements : p. [xvi] and
                  [327]-[328].
Subjects:      Spherical trigonometry.
               Mathematics -- Methodology.
               Astronomy -- Study and teaching.
Other authors: Dibner, Bern, b. 1897, donor. DSI
Control No.:   9137684

Author:        Dufour, Charles, 1827-1903. [from old catalog]
Title:         Note sur une nouvelle formule trigonométrique.
Published:     [n.p., 1878?]
Description:   2 p. 22 cm.
LC Call No.:   QA538.D8
Subjects:      Triangle. [from old catalog]
Control No.:   10074502

Author:        Kase, Gustav, 1865-
Title:         Beziehung zwischen den radien der einem
                  sphärischen n eck ein- und umbeschriebenen kreise und ihrer
                  centralentfernung ...
Published:     Halle a.S., Hofbuchdruckerei von C.A. Kaemmerer &
                  Co., 1890.
Description:   1 p. l., [5]-49, 1 p. diagrs. on 2 pl. 22 cm.
LC Call No.:   QA538.K22
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Spherical trigonometry.
               Elliptic functions.
Control No.:   10078391

Author:        Lagrive, Jean de, 1689-1757.
Title:         Manuel de trigonométrie pratique; par M. l'abbé
                  Delagrive. Rev. et augm. de tables de logarithmes à l'usage
                  des ingénieurs, et principalement de ceux qui s'occupent de
                  l'arpentage et du cadastre; par A. A. L. Reynaud. Haros.
                  Plausol, et Bauzon.
Edition:       Nouv. éd.
Published:     Paris, Courcier, 1806.
Description:   [318] p. tables, diagrs. on 5 fold. pl. 22cm.
LC Call No.:   QA538.L17
Notes:         Various paging.
Subjects:      Plane trigonometry.
Other authors: Reynaud, M. (Antoine André Louis), 1770-1844.
                  ed.
Control No.:   7732620

Author:        Sheel, H[erman] W[illiam], 1860- [from old
                  catalog]
Title:         A graphic method for memorizing the fundamental
                  relations of the trigonometric functions.
Published:     Decorah, Ia., Lutheran publishing house print,
                  1903.
Description:   [4] p. 23 cm.
LC Call No.:   QA538.S54
Subjects:      Trigonometry. [from old catalog]
Control No.:   7728764

Author:        Waith, William S. [from old catalog]
Title:         The circle of trigonometric functions.
Published:     Buffalo, N.Y., P. Paul & bro., 1891.
Description:   32 p. diagrs. 25 cm.
LC Call No.:   QA538.W1
Subjects:      Trigonometry. [from old catalog]
Control No.:   10073295

Author:        Klein, Felix, 1849-1925.
Title:         Vorlesungen über die Theorie der elliptischen
                  Modulfunctionen, Ausgearbeitet und Vervollständigt von Dr.
                  Robert Fricke ...
Published:     Leipzig, B.G. Teubner, 1890-92.
Description:   2 v. diagr. 25 cm.
LC Call No.:   QA543.K64
Notes:         1. Bd. Grundlegung der Theorie.--2. Bd.
                  Fortbildung und Anwendung der Theorie.
Subjects:      Modular functions.
Other authors: Fricke, Robert, 1861-1930, ed.
Control No.:   7260342
