#+STARTUP: showeverything logdone
#+options: num:nil


Author:        Arbogast, L. F. A. (Louis François Antoine),
                  1759-1803.
Title:         Du calcul des dérivations; par L.F.A. Arbogast
                  ...
Published:     Strasbourg, Impr. de Levrault, frères, an VIII
                  (1800).
Description:   2 p.l., xxii p., 1 l., 404 p. 28 x 23 cm.
LC Call No.:   QA302.A7
Subjects:      Calculus -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   4054815


Author:        Bach, M. (Xavier Dagobert), 1813-1885.
Title:         Thèse d'analyse / présentée par M. Bach.
Published:     Paris : Mallet-Bachelier, 1857.
Description:   66 p. ; 27 cm.
LC Call No.:   QA302.B3x 1857
Notes:         Caption title: Recherches sur quelques formules
                  d'analyse, et en particulier sur les formules d'Euler et de
                  Stirling.
               Includes bibliographical references.
Subjects:      Calculus.
               Euler, Leonhard, 1707-1783.
               Stirling, James, 1692-1770.
Other titles:  Recherches sur quelques formules d'analyse, et en
                  particulier sur les formules d'Euler et de Stirling.
Control No.:   1928082

Author:        Ditton, Humphry, 1675-1715.
Title:         An institution of fluxions: containing the first
                  principles, the operations, with some of the uses and
                  applications of that admirable method; according to the
                  scheme perfix'd to his tract of quadratures, by (its first
                  inventor) the incomparable Sir Isaac Newton. By Humphry
                  Ditton.
Published:     London, J. Knapton, 1706.
Description:   8 p.l., 240 p. diagrs. 19 cm.
LC Call No.:   QA302.D6 1706
Subjects:      Calculus -- Early works to 1800.
Control No.:   747539

Author:        Ditton, Humphry, 1675-1715.
Title:         An institution of fluxions: containing the first
                  principles, the operations, with some of the uses and
                  applications of that admirable method; according to the
                  scheme prefix'd to his tract of quadratures, by (its first
                  inventor) the incomparable Sir Isaac Newton. By Humphry
                  Ditton ...
Edition:       2d ed., rev., cor. and improv'd, by John Clarke
                  ...
Published:     London, Printed for J. and J. Knapton, 1726.
Description:   8 p.l., 240 p. diagrs. 21 cm.
LC Call No.:   QA302.D6 1726
Notes:         Title in red and black.
Subjects:      Calculus -- Early works to 1800.
Other authors: Clarke, John, 1682-1757, ed.
Control No.:   3107024

Author:        Emerson, William, 1701-1782.
Title:         The doctrine of fluxions:
Edition:       3d ed.
Published:     London, 1768.
Description:   xvi, [4], 432, [2] p. diagrs. on xii fold. pl. 22
                  cm.
LC Call No.:   QA302.E531
Subjects:      Calculus. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   6331987

Author:        Emerson, William, 1701-1782.
Title:         The doctrine of fluxions: not only explaining the
                  elements thereof, but also its application and use in the
                  several parts of mathematics and natural philosophy.
Edition:       The 2d ed., cor. and greatly enlarged ...
Published:     London, Printed for J. Richardson, 1757.
Description:   xvi, [4], 432, [2] p. diagrs. on XII fold. pl. 21
                  cm.
LC Call No.:   QA302.E53
Notes:         Preface signed: W. Emerson.
Subjects:      Calculus -- Early works to 1800.
Control No.:   1217257

Author:        Euler, Leonhard, 1707-1783.
Title:         Introductio in analysin infinitorum / auctore
                  Leonhardo Eulero ...
Edition:       Editio nova.
Published:     Lugduni : Apud Bernuset, Delamolliere, Falque &
                  soc., 1797.
Description:   2 v. : ill. ; 27 cm. (4to)
LC Call No.:   QA302.E85x 1797
Notes:         Vol 1 : xvi, 320 p., 17 leaves of plates
                  (folded); v. 2: [2], 398, [1] p.
Subjects:      Calculus -- Early works to 1800.
               Geometry, Infinitesimal -- Early works to 1800.
Control No.:   511289

Author:        Euler, Leonhard, 1707-1783. [from old catalog]
Title:         Institutiones calculi differentialis cum eius vsu
                  in analysi finitorum ac doctrina serierum.
Published:     Petropolitanae, impensis Academiae imperialis
                  scientiarum, 1755.
Description:   2 v. 24 x 20 cm.
LC Call No.:   QA302.E88 (Rare Bk Coll)
Subjects:      Differential calculus.
Control No.:   10078040

Author:        Fiorentino, Niccola, 1755-1799. [from old
                  catalog]
Title:         Saggio sulle quantità infinitesime e sulle forze
                  vive, e morte.
Published:     [Napoli, Si vende da M. Stasi, 1781?]
Description:   4, 116 p. illus. 19 cm.
LC Call No.:   QA302.F56
Subjects:      Calculus -- Early works to 1800.
               Mechanics -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9916343

Author:        Hodgson, James, 1672-1755.
Title:         The doctrine of fluxions, Founded on Sir Isaac
                  Newton's method, published by himself in his tract upon the
                  quadrature of curves. By James Hodgson ...
Published:     London, Printed by T. Wood, for the author; sold
                  by W. Mount and T. Page [etc.] 1736.
Description:   xvi, 452, [11] p. diagrs. 26 cm.
LC Call No.:   QA302.H6
Subjects:      Calculus -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   1691619

Author:        Holliday, F[rancis] [from old catalog]
Title:         An introduction to fluxions,
Published:     London, Printed for J. Nourse, 1777.
Description:   xix, [1], iv, 343 p. diagrs. on vii fold. pl. 22
                  cm.
LC Call No.:   QA302.H73
Subjects:      Calculus. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9610207

Author:        Langsdorf, Karl Christian von, 1757-1834. [from
                  old catalog]
Title:         Erläuterungen über die Kästnerische Analysis
                  des unendlichen,
Published:     Giessen, In der Kriegerischen buchhandlung,
                  1778-
Description:   v. fold. diagr. 18 cm.
LC Call No.:   QA302.L3
Subjects:      Calculus. [from old catalog]
               Kästner, Abraham Gotthelf, 1719-1800.
                  Anfangsgründe der analysis des unendlichen. [from old
                  catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   7860912

Author:        Leibniz, Gottfried Wilhelm, Freiherr von,
                  1646-1716.
Uniform Title: Prose works. German. [from old catalog]
Title:         Leibniz über die analysis des unendlichen.
Published:     Leipzig, W. Engelmann, 1908.
Description:   89 p. diagrs. 20 cm.
LC Call No.:   QA302.L5
Subjects:      Calculus.
Other authors: Kowalewski, Gerhard, 1876-1950.
Control No.:   5875546

Author:        L'Hospital, marquis de (Guillaume François
                  Antoine), 1661-1704.
Title:         Analyse des infiniment petits, pour
                  l'intelligence des lignes courbes.
Published:     Paris, Imprimerie royale, 1696.
Description:   9 p. l. 181, [1] p., 1 l. : fold. digrs. 26 cm.
LC Call No.:   QA302.L6
Notes:         Title vignette: arms of France. Head- and
                  tail-pieces; initials.
Subjects:      Differential calculus.
               Mathematics -- Early works to 1800.
Control No.:   8801262

Author:        L'Hospital, marquis de (Guillaume François
                  Antoine), 1661-1704.
Uniform Title: Analyse des infiniment petits. English
Title:         The method of fluxions both direct and inverse :
                  the former being a translation from the celebrated Marquis De
                  L'Hospital's Analyse des infinements petits / and the latter
                  supply'd by the translator, E. Stone ...
Published:     London : Printed for William Innys ..., 1730.
Description:   xix, [1], i-iv, 238, [2], 212, [2] p., 11, IV
                  leaves of plates : ill. (engravings) ; 21 cm. (8vo)
LC Call No.:   QA302.L613x 1730
Notes:         Translation of: Analyse des infiniment petits.
               Signatures: Ap8s ap4s B-Qp8s R-2Tp4s
                  2Up4s(-2U4).
               Part II. being an appendix, containing the
                  inverse method of fluxions ... / [by E. Stone].
Subjects:      Differential calculus -- Early works to 1800.
               Mathematics -- Early works to 1800.
Other authors: Stone, Edmund, d. 1768.
Control No.:   2400283

Author:        L'huiler, Simon Antoine Jean, 1750-1840.
Title:         Principiorum calculi differentialis et entegralis
                  expositio elementaris : ad normam dissertationis ab Academia
                  scient. reg. prussica anno 1786 / præmii honore decoratæ
                  elaborata auctore Simone L'huilier.
Published:     Tubingæ : J. G. Cottam, 1795.
Description:   3 p. l., xxviii, 339, [1] p. : diagrs. on ix
                  fold. pl. ; 26 cm.
LC Call No.:   QA302.L69
Subjects:      Calculus.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC

Author:        MacLaurin, Colin, 1698-1746.
Title:         A treatise of fluxions. In two books. By Colin
                  MacLaurin ...
Published:     Edinburg, Printed by T. W. & T. Ruddimans, 1742.
Description:   2 v. XL (i.e. 41) fold. pl. 23 x 18 cm.
LC Call No.:   QA302.M16
Notes:         Paged continuously.
Subjects:      Calculus -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   4052379

Author:        Meerman, Gerard, 1722-1771.
Title:         Specimen calculi fluxionalis : quo exhibetur
                  generalis methodus duarum pluriumve quantitatum variabilium
                  in semet multiplicatarum fluxiones et fluentes cujuscunque
                  ordinis ope serierum infinitarum adinveniendi : accedunt alia
                  quaedam miscellanea / auctore Gerardo Meerman, Jcto.
Published:     Lugduni Batavorum : Apud Danielem Goetval, 1742.
Description:   [16], 95, [1] p. ; 27 cm. (4to)
LC Call No.:   QA302.M44 1743
Notes:         Colophon: Hagae-Comitum, Ex Typographia ANTONII
                  DE GROOT. M D C C X L I I.
               Signatures: *-2*p4s A-Mp4s.
               Title page vignette.
Subjects:      Calculus -- Early works to 1800.
Control No.:   12510766

Author:        Newton, Isaac, Sir, 1642-1727.
Title:         La Méthode des fluxions et des suites infinies
                  [par] Isaac Newton.  Traduit par M. de Buffon.
Published:     Paris, Libraire scientifique A. Blanchard, 1966.
Description:   xxxii, 150 p. illus. 28cm.
LC Call No.:   QA302.N414 1740a
Dewey No.:     517
Notes:         Translation of The method of fluxions and
                  infinite series.
               Facsim. reproduction of the 1740 ed., Paris, De
                  Bure.
Subjects:      Calculus -- Early works to 1800.
Control No.:   7550279

Author:        Pfaff, Johann Friedrich, 1765-1825. [from old
                  catalog]
Title:         Disqvisitiones analyticae maxime ad calcvlvm
                  integralem et doctrinam serivm pertinentes ...
Published:     1 v. 23 x 19 cm.
Description:   p. cm.
LC Call No.:   QA302.P52
Notes:         For full entry see Main Card Catalog.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   8188604

Author:        Reyneau, Charles René, 1656-1728. [from old
                  catalog]
Title:         Analyse demontrée, ou, La méthode de résoudre
                  les problêmes des mathematiques, et d'apprendre facilement
                  ces sciences; : expliquée & démontrée dans le premier
                  volume, & appliquée, dans le second, à découvrir les
                  proprietez des figures de la géometrie simple & composée;
                  à résoudre les problêmes de ces sciences & les problêmes
                  des sciences physico-mathématiques, en employant le calcul
                  ordinaire de l'algebre, le calcul differentiel & le calcul
                  intégral. Ces derniers calculs y sont aussi expliquez &
                  démontrez. / Par le R.P. Reyneau ...
Edition:       Seconde edition, augmentée des remarques de M.
                  de Varignon.
Published:     Paris, Quillau, imprimeur-juré-libraire de
                  l'Université, 1736-1738.
Description:   2 v. fold. tab., 5 fold. pl. (diagrs.) 26 cm.
LC Call No.:   QA302.R48
Subjects:      Mathematics -- Early works to 1800.
               Calculus.
Other authors: Varignon, Pierre, 1654-1722.
Control No.:   6467636

Author:        Rowe, John, mathematician.
Title:         An introduction to the doctrine of fluxions :
                  with fourteen copper-plates / by John Rowe.
Edition:       The fourth edition, with additions and
                  alterations, to which is added an essay on the theory / the
                  whole revised, carefully corrected, and prepared for the
                  press by the late William Davis ...
Published:     London : Printed for Anne Davis ... and sold by
                  Sherwood and Co. ... [and 4 others], 1809.
Description:   12, 197, [1] p., XIV folded leaves of plates :
                  ill. ; 22 cm.
LC Call No.:   QA302.R87
Notes:         "An explanation of fluxions" (p. [183]-197) has
                  special t.p.
               Signatures: Ap6s B-Np8s Op2s P1.
               Bibliography: p. 177-181.
Subjects:      Calculus.
Other authors: Davis, William, 1771-1807.
               Rowe, John, mathematician. Explanation of
                  fluxions.
Control No.:   7736642

Author:        Simpson, Thomas, 1710-1761.
Title:         The doctrine and application of fluxions:
                  containing (besides what is common on the subject) a number
                  of new improvements in the theory, and the solutions of a
                  variety of new and very interesting problems in different
                  branches of the mathematics. By Thomas Simpson, F.R.S. To
                  which is prefixed an account of his life.
Edition:       The whole rev. and carefully cor. by William
                  Davis.
Published:     London, Printed for H.D. Symonds [1805]
Description:   xxiv, 442 p. incl. tables, diagrs. 22 cm.
LC Call No.:   QA302.S5 1805
Subjects:      Calculus.
Other authors: Davis, William, 1771-1807, ed.
Control No.:   13168352

Author:        Simpson, Thomas, 1710-1761.
Title:         The doctrine and application of fluxions.
                  Containing (besides what is common to the subject) a number
                  of new improvements in the theory, and the solution of a
                  variety of new and very interesting problems in different
                  branches of mathematics. By Thomas Simpson ...
Edition:       A new ed. carefully rev. and adapted, by copious
                  appendixes, to the present advanced state of science.  By a
                  graduate of the University of Cambridge.
Published:     London, Printed for J. Collingwood [etc.] 1823.
Description:   2 v. diagrs. 22 cm.
LC Call No.:   QA302.S5 1823
Subjects:      Calculus.
Control No.:   1217092

Author:        Smith, James, 18th cent.
Title:         A new treatise of fluxions ... / by James Smith
                  ...
Published:     London : Printed for the author, and sold by G.
                  Strahan ..., T. Woodward ..., J. Nourse ..., A. Millar ...,
                  T. Woodman ..., H. Noorthouck ..., 1737.
Description:   [4], 59, [1] p. : ill. ; 21 cm. (8vo)
LC Call No.:   QA302.S65x 1737
Notes:         Signatures: [A]p2s B-Hp4s Ip2s.
               Includes bibliographical references.
               (from t.p.) I. The elements of fluxions,
                  demonstrated in two easy propositions, without first or last
                  ratios -- II. A treatise of nascent and evanescent
                  quantities, first and last ratios -- III. Sir Isaac Newton's
                  demonstration of the fluxions enlarged and illustrated -- IV.
                  Answers to the principal objects in the anylist.
Subjects:      Calculus -- Early works to 1800.
Other authors: Newton, Isaac, Sir, 1642-1727. Analysis per
                  quantitatum series, fluxiones, ac differentias.
Control No.:   511279

Author:        Strabbe, Arnoldus Bastiaan, 1741-1805.
Title:         Erste beginselen der fluxie-rekening. Behelzende
                  eene duidelyke verklaaring van de gronden deezer
                  voortreffelyke weetenschap, benevens haare toepassing en
                  gebruik in onderscheidene deelen der wiskunde. Door Arnoldus
                  Bastiaan Strabbe ...
Published:     Amsterdam, J.B. Elwe, 1799.
Description:   viii, 336 p. 85 diagr. on 5 fold. plates. 23 cm.
LC Call No.:   QA302.S89
Notes:         Published at the expense of the "Genootschap der
                  mathematische weetenschappen, onder de spreuk: 'Een
                  onvermoeide arbeid komt alles te boven.'" cf. p. iii-iv.
Subjects:      Calculus.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   8666714

Author:        Sunderson, Nicholas, 1682-1739. [from old
                  catalog]
Title:         The method of fluxions applied to a select number
                  of useful problems:
Published:     London, Printed for A. Millar [etc.] 1756.
Description:   xxiv, 309 [1] p. diagrs. on xii fold. pl. 21 cm.
LC Call No.:   QA302.S25
Subjects:      Calculus. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9141726

Author:        Varignon, Pierre, 1654-1722. [from old catalog]
Title:         Eclaircissemens sur l'Analyse des infiniment
                  petits
Published:     Paris, Chez Rollin, 1725.
Description:   4 p. l., 118, [2] p. diagrs. on 6 fold. pl. 24 x
                  19 cm.
LC Call No.:   QA302.V2
Subjects:      Differential calculus.
Other authors: L'Hôpital, Guillaume François Antoine de,
                  marquis de St. Mesme, 1661-1704. Analyse des infiniment
                  petits. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   7284422

Author:        Waring, Edward, 1734-1798.
Title:         Meditationes analyticæ, ab Edvardo Waring.
Published:     Cantabrigiæ, typis academicis excudebat J.
                  Archdeacon; veneunt apud J. Nicholson; [etc., etc.] 1785.
Description:   2 p. l., xiii, 722 p., 2 l. fold. diagr. 28 x 21
                  cm.
LC Call No.:   QA302.W3 1785
Notes:         "Prima editio imprimebatur annis 1773, 4 & 5:
                  secunda cum nonnullis additionibus annis 1783, 4 & 5, et
                  edita jun. 4, 1785."
Subjects:      Mathematics -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   7881762

Author:        Bass, Edgar W. (Edgar Wales), 1843-1918.
Title:         Elements of differential calculus / by Edgar W.
                  Bass.
Edition:       3d ed., 1st thousand.
Published:     New York : J. Wiley & sons ; London : Chapman &
                  Hall, limited, 1905.
Description:   x, 356 p. : diagrs. ; 19 cm.
LC Call No.:   QA304.B35
Subjects:      Differential calculus
Control No.:   7733820

Author:        Bass, Edgar W. (Edgar Wales), 1843-1918.
Title:         Introduction to the differential calculus / by
                  Edgar W. Bass.
Published:     West Point, N.Y. : United States Military Academy
                  Press, 1887.
Description:   95 p. : ill. ; 22 cm.
LC Call No.:   QA304.B31
Subjects:      Differential calculus.
Control No.:   6792964

Author:        Bass, Edgar W[ales] 1843-
Title:         Elements of differential calculus. By Edgar W.
                  Bass.
Edition:       2d ed. 1st thousand.
Published:     New York, J. Wiley & sons ; London, Chapman &
                  Hall, limited, 1901.
Description:   viii, 356 p. diagrs. 19 cm.
LC Call No.:   QA304.B34
Subjects:      Differential calculus
Control No.:   7256348

Author:        Bass, Edgar W[ales] [from old catalog]
Title:         Differential calculus ...
Published:     West Point, N.Y., U. S. military academy press
                  and bindery, 1889-92.
Description:   2 v. diagr. 21 cm.
LC Call No.:   QA304.B32
Subjects:      Differential calculus.
Control No.:   6324828

Author:        Bass, Edgar W[ales]. [from old catalog]
Title:         Elements of differential calculus.
Edition:       1st ed.
Published:     New York, J. Wiley & sons; 1896.
Description:   viii, 354 p. diagr. 20 cm.
LC Call No.:   QA304.B33
Subjects:      Differential calculus
Control No.:   8666333

Author:        Belon y Torres, Alejandro. [from old catalog]
Title:         Lecciones de calculo diferencial, por el teniente
                  coronel comandante de ejército Don Alejandro Belon y
                  Torres...
Published:     Madrid, Imprenta del Memorial de ingenieros,
                  1876.
Description:   vii, 240 p. fold. diagr. 23 cm.
LC Call No.:   QA304.B4
Subjects:      Differential calculus.
Control No.:   8693039

Author:        Bergbohm, Julius. [from old catalog]
Title:         Neue rechnungsmethoden der höheren mathematik.
Published:     Stuttgart, Selbstverlag des verfassers, 1891.
Description:   4 p.l., 30 p. 23 cm.
LC Call No.:   QA304.B46
Subjects:      Differential calculus.
Control No.:   9697289

Author:        Boggio, Tommaso, 1877- [from old catalog]
Title:         Calcolo differenziale con applicazioni
                  geometriche ...
Published:     Torino-Genova, S. Lattes & c., 1921-
Description:   v. diagrs. 16 cm.
LC Call No.:   QA304.B7
Subjects:      Differential calculus.
Control No.:   5960246

Author:        Byerly, W[illiam] E[lwood] 1849- [from old
                  catalog]
Title:         Elements of the differential calculus,
Published:     Boston, Ginn & Heath, 1879.
Description:   xv, 258 p. diagr. 22 cm.
LC Call No.:   QA304.B96
Subjects:      Differential calculus.
Control No.:   8198161

Author:        Chicago. University. University extension
                  division. Home-study dept. [from old catalog]
Title:         Mathematics 218 (differential calculus)
Published:     [Chicago] The University of Chicago, c1942.
Description:   1 p.l., 35 numb. l. 28 x 22 cm.
LC Call No.:   QA304.C53 1942
Subjects:      Differential calculus.
Other authors: Everett, Harry Scheidy, 1891- [from old catalog]
Control No.:   7854972

Author:        Chicago. University. University extension
                  division. Home-study dept. [from old catalog]
Title:         Mathematics 218 (differential calculus)
Published:     [Chicago] The University of Chicago, c1937.
Description:   1 p.l., 30 numb. l. 28 x 22 cm.
LC Call No.:   QA304.C53 1937
Subjects:      Differential calculus.
Other authors: Everett, Harry Scheidy, 1891- [from old catalog]
Control No.:   10199151

Author:        Dvivedi, Sudhakara. [from old catalog]
Title:         Calanakalana.
Published:     1886.
Description:   iii, viii, 8, 11, 479 p. 22 cm.
LC Call No.:   QA304.D85
Notes:         Romanized.
Subjects:      Differential calculus.
Control No.:   7500085

Author:        Edwards, Joseph, 1854-1931. [from old catalog]
Title:         Differential calculus,
Published:     London and New York, Macmillan and co., 1886.
Description:   xiv p., 1 l., 439 p. diagrs. 19 cm.
LC Call No.:   QA304.E26 1886
Subjects:      Differential calculus.
Control No.:   6477255

Author:        Edwards, Joseph, 1854-1931. [from old catalog]
Title:         An elementary treatise on the differential
                  calculus,
Published:     London, Macmillan and co., limited; 1900.
Description:   xiii p., 1 l., 529 p. diagrs. 23 cm.
LC Call No.:   QA304.E26 1900
Subjects:      Differential calculus.
Control No.:   8663756

Author:        Grünbaum, Heinrich, b. 1876.
Uniform Title: Lehr- und Übungsbuch der Differentialrechnung
Title:         Funktionenlehre und Elemente der Differential-
                  und Integralrechnung : Lehrbuch und Aufgabensammlung für
                  höhere Lehranstalten, besonders für technische Fachschulen
                  sowie zum Selbstunterricht / von Heinrich Grünbaum.
Edition:       3., umgearbeitete und verm. Aufl. des Lehr- und
                  Übungsbuchs der Differentialrechnung.
Published:     Stuttgart ; Berlin : Fr. Grub, 1912.
Description:   xii, 196 p. : ill. ; 22 cm.
LC Call No.:   QA304.G78x 1912
Subjects:      Differential calculus.
               Calculus, Integral.
Control No.:   4291728

Author:        Hackley, [Charles William], 1809-1861. [from old
                  catalog]
Title:         Differential calculus,
Published:     New York, Baker & Godwin, printers, 1856.
Description:   32 p. 19 cm.
LC Call No.:   QA304.H11
Subjects:      Differential calculus.
Control No.:   5856941

Author:        Hardy, Arthur Sherburne, 1847-1930.
Title:         Elements of the differential and integral
                  calculus : method of rates / by Arthur Sherburne Hardy.
Published:     Boston : Ginn, 1903, c1890.
Description:   xi, 239 p. : ill. ; 21 cm.
LC Call No.:   QA304.H37x 1903
Subjects:      Differential calculus.
               Calculus, Integral.
Control No.:   983732

Author:        Johnson, William Woolsey, 1841-1927.
Title:         An elementary treatise on the differential
                  calculus founded on the method of rates.
Edition:       Abridged ed. 1st ed., 1st thousand.
Published:     New York, J. Wiley, 1908.
Description:    x, 191 p. diagrs. 21 cm.
LC Call No.:   QA304.J72
Subjects:      Differential calculus.
Control No.:   8217298

Author:        Johnson, William Woolsey, 1841-1927.
Title:         An elementary treatise on the differential
                  calculus, founded on the method of rates, by William Woolsey
                  Johnson.
Edition:       1st ed. 1st thousand.
Published:     New York, J. Wiley & sons; [etc., etc.] 1904.
Description:   xiv, 404 p. diagrs. 21 cm.
LC Call No.:   QA304.J71
Subjects:      Differential calculus.
Control No.:   7265351

Author:        Lasley, J. W. (John Wayne), 1891-
Title:         Differential calculus for students of economics,
                  by J.W. Lasley, Jr. and M.A. Hill, Jr.
Published:     Ann Arbor, Mich., Edwards Brothers, inc., 1941.
Description:   vii, 150 p. : diagrs. ; 23 cm.
LC Call No.:   QA304.L3
Notes:         "Lithoprinted."
Subjects:      Differential calculus.
Other authors: Hill, M. A. (Michael Arendell), 1898-
Control No.:   7381337

Author:        Lindow, Martin Paul Johannes, 1880- [from old
                  catalog]
Title:         Differentialrechnung, unter berücksichtigung der
                  praktischen anwendung in der technik mit zahlreichen
                  beispielen und aufgaben, versehen,
Edition:       3. aufl.
Published:     Leipzig und Berlin, B. G. Teubner, 1919.
Description:   vi, 100, [1] p. diagrs. 19 cm.
LC Call No.:   QA304.L5 1919
Subjects:      Differential calculus.
Control No.:   9735501

Author:        Martini, Raynerius Bonaventura, 1723-1774.
Title:         Analyseos infinite parvorum, sive Calculi
                  differentialis elementa / auctore Raynerio Bonaventura
                  Martini ...
Published:     Pisis : Ex typographis archiep. apud Jo. Dom.
                  Carotti, 1761.
Description:   xii, 187, [1] p., [3] folded leaves of plates :
                  diagrams ; 22 cm. (4to)
LC Call No.:   QA304.M28 1761
Dewey No.:     515/.33 20
Notes:         Signatures: [cross]p6s A-Yp4s Zp6s.
               BLC, v. 213, p. 256
Subjects:      Differential calculus -- Early works to 1800.
Other titles:  Analyseos infinite parvorum.
               Calculi differentialis elementa.
Control No.:   3421396

Author:        Mayr, Alois, 1807-1890.
Title:         Theorie des Differenzial-Calculs/ von Aloys
                  Mayr.
Published:     München : E.A. Fleischmann, 1836.
Description:   66 p. : ill. ; 21 cm.
LC Call No.:   QA304.M39x 1836
Subjects:      Differential calculus.
Control No.:   3346264

Author:        McMahon, James, 1856-
Title:         Elements of the differential calculus, by James
                  McMahon and Virgil Snyder.
Published:     New York, Cincinnati [etc] American book company
                  [1898]
Description:   xiv, 337 p. diagrs. 21 cm.
Series:        The Cornell mathematical series
LC Call No.:   QA304.M16
Subjects:      Differential calculus.
Other authors: Snyder, Virgil, 1869-1950, joint author.
Control No.:   9594061

Author:        Meyer, Anton, 1802-1857. [from old catalog]
Title:         Manuel d'un cours de calcul différentiel,
Published:     Liége, H. Dessain, 1855.
Description:   1 p.l., [v]-x, 438 p., 1 l. 23 cm.
LC Call No.:   QA304.M4
Subjects:      Differential calculus.
Control No.:   10161186

Author:        Navier, M. (Claude-Louis-Marie-Henri),
                  1785-1836.
Uniform Title: Résumés des leçons d'analyse données à
                  l'Ecole polytechnique. German
Title:         Lehrbuch der Differential- und Integralrechnung /
                  von Louis Navier ; mit Zusätzen von Liouville ; Deutsche
                  herausgegeben, und mit einer Abhandlung der Methode der
                  kleinsten Quadrate begleitet von Theodor Wittstein.
Published:     Hannover : Hahn'sche Hofbuchhandlung, 1854.
Description:   2 v. ; 20 cm.
LC Call No.:   QA304.N3815x 1854
Notes:         Translation of : Résumés des leçons d'analyse
                  données à l'Ecole polytechnique.
Subjects:      Differential calculus.
               Calculus, Integral.
Control No.:   2873544

Author:        O'Brien, M. (Matthew), 1814-1855.
Title:         An elementary treatise on the differential
                  calculus. By the Rev. M. O'Brien ...
Published:     Cambridge [Eng.] J. & J. J. Deighton; [etc.,
                  etc.] 1842.
Description:   x, 231 p. 6 fold. pl. 22 cm.
LC Call No.:   QA304.O13
Subjects:      Differential calculus.
Control No.:   9135316

Author:        [Osborne, George Abbott], 1839- [from old
                  catalog]
Title:         Notes on differentiation of functions. With
                  examples ...
Published:     Boston, J. S. Cushing & co., printers [c1884]
Description:   1 p.l., 40 p. 20 cm.
LC Call No.:   QA304.O811
Subjects:      Differential calculus.
Control No.:   5856962

Author:        [Osborne, George Abbott] [from old catalog]
Title:         The differential calculus applied to plane curves
                  and maxima and minima ...
Published:     Boston, J. S. Cushing & co., printers, c1889.
Description:   1 p.l., 73-102 p. diagr. 21 cm.
LC Call No.:   QA304.O81
Subjects:      Differential calculus.
Control No.:   7729439

Author:        Osgood, William F. (William Fogg), 1864-1943.
Title:         Elementary calculus, by William F. Osgood ...
Published:     New York, The Macmillan company, 1921.
Description:   ix, 224 p. diagrs. 19 cm.
LC Call No.:   QA304.O85
Subjects:      Differential calculus.
Control No.:   745905

Author:        Ottley, W. C. (William Campbell), 1808-1843.
Title:         A treatise on the differential calculus; with a
                  collection of examples. By W.C. Ottley ...
Published:     Cambridge [Eng.] Printed for W.P. Grant [etc.]
                  1838.
Description:   xxxiv, 253 p. diagr. 22 cm.
LC Call No.:   QA304.O89
Subjects:      Differential calculus.
Control No.:   3106782

Author:        Pauly, J. (Jean)
Title:         Notions élémentaires du calcul différentiel et
                  du calcul intégral / par J. Pauly.
Published:     Paris : Baudry, 1887.
Description:   ii, 329 p. : ill. ; 25 cm.
LC Call No.:   QA304.P38x 1887
Subjects:      Differential calculus.
               Calculus, Integral.
Control No.:   2873542

Author:        Phillips, H. B. (Henry Bayard), 1881-
Title:         Differential calculus, by H.B. Phillips ...
Edition:       1st ed., 1st thousand.
Published:     New York, J. Wiley & sons, inc.; [etc., etc.]
                  1916.
Description:   v, 162 p. diagrs. 19 cm.
LC Call No.:   QA304.P5
ISBN:          $1.25
Subjects:      Differential calculus.
Control No.:   3580314

Author:        Price, Bartholomew, 1818-1898.
Title:         A treatise on the differential calculus, and its
                  application to geometry : founded chiefly on the method of
                  infinitesimals / by Bartholomew Price.
Published:     London : George Bell, 1848.
Description:   xv, 279 p., [4] folded leaves of plates : ill. ;
                  23 cm.
LC Call No.:   QA304.P74x 1848
Subjects:      Differential calculus.
Control No.:   1456198

Author:        Raabe, J. L. (Joseph Ludwig), 1801-1859.
Title:         Die Differenzial- und Integralrechnung mit
                  Functionen einer Variabeln / von J.L. Raabe.
Published:     Zürich : Orell, Füssli und Compagnie,
                  1839-1847.
Description:   3 v. ; 22 cm.
LC Call No.:   QA304.R32x 1839
Notes:         Half-title: Differenzial- und Integralrechnung.
Subjects:      Differential calculus.
               Calculus, Integral.
Other titles:  Differenzial- und Integralrechnung.
Control No.:   3818830

Author:        Rice, John Minot, 1833-1901.
Title:         An elementary treatise on the differential
                  calculus founded on the method of rates or fluxions, by John
                  Minot Rice ... and William Woolsey Johnson ...
Edition:       Abridged ed.
Published:     New York, J. Wiley and sons, 1880.
Description:   ix, 199 p. diagrs. 21 cm.
LC Call No.:   QA304.R52
Subjects:      Differential calculus.
Other authors: Johnson, William Woolsey, 1841-1927, joint
                  author.
Control No.:   1689170

Author:        Rice, John Minot, 1833-1901.
Title:         An elementary treatise on the differential
                  calculus founded on the method of rates or fluxions. By John
                  Minot Rice ... and William Woolsey Johnson ...
Edition:       Rev. ed.
Published:     New York, J. Wiley and sons, 1879.
Description:   xvi, 469 p. diagrs. 22 cm.
LC Call No.:   QA304.R5 1879
Notes:         A preliminary edition with title "The elements of
                  the differential calculus ..." was printed in 3 parts,
                  1874-76.
Subjects:      Differential calculus.
Other authors: Johnson, William Woolsey, 1841-1927, joint
                  author.
Control No.:   272555

Author:        Rice, John Minot, 1833-1901.
Title:         On a new method of obtaining the differentials of
                  functions with especial reference to the Newtonian conception
                  of rates or velocities, by J. Minot Rice and W. Woolsey
                  Johnson.
Edition:       Rev. ed.
Published:     New York, D. Van Nostrand, 1875.
Description:   32 p. diagrs. 19 cm.
LC Call No.:   QA304.R524
Subjects:      Differential calculus.
Other authors: Johnson, William Woolsey, 1841-1927, joint
                  author.
Control No.:   9134612

Author:        Rice, John Minot, 1833-1901. [from old catalog]
Title:         The elements of the differential calculus,
Published:     New York, J. Wiley & son, 1874;
Description:   3 v. diagrs. 24-24 cm.
LC Call No.:   QA304.R5 1874
Subjects:      Differential calculus.
Other authors: Johnson, William Woolsey, 1841-1927, [from old
                  catalog] joint author.
Control No.:   8198241

Author:        Sailer, Engelbert.
Title:         Die Aufgaben aus der Differential- und
                  Integralrechnung aus der analytischen und synthetischen
                  Geometrie : welche bei der Prüfung für das Lehramt der
                  Mathematik und Physik an den K. Bayerischen Humanistischen
                  und Technischen Unterrichts-Anstalten in den Jahren 1873 bis
                  1893 gestellt wurden / bearbeitet von Engelbert Sailer.
Published:     München : Theodor Ackermann, 1901.
Description:   187 p. : ill. ; 22 cm.
LC Call No.:   QA304.S24x 1901
Subjects:      Differential calculus.
               Calculus, Integral.
Control No.:   1928187

Author:        Spare, John, 1816-1901.
Title:         The differential calculus : with unusual and
                  particular analysis of its elementary principles, and copius
                  illustrations of its practical application / by John Spare.
Published:     Boston : Bradley, Dayton and Company, 1865
                  (Boston : Press of Geo. C. Rand and Avery)
Description:   xix, 244 p. ; 21 cm.
LC Call No.:   QA304.S73
Notes:         Spine title: Spare's differential calculus.
               "Electrotyped at the Boston Stereotype
                  Foundry"--T.p. verso.
               A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Differential calculus.
Other titles:  Spare's differential calculus.
Control No.:   7729512

Author:        Tannenberg, Wladimir de, 1860- [from old
                  catalog]
Title:         Leçons nouvelles sur les applications
                  géométriques du calcul différentiel,
Published:     Paris, A. Hermann, 1899.
Description:   2 p.l., 192 p. diagrs. 25 cm.
LC Call No.:   QA304.T3
Subjects:      Differential calculus.
Control No.:   8713813

Author:        Walton, William, 1813-1901.
Title:         A treatise on the differential calculus. By
                  William Walton ...
Published:     Cambridge, Deightons; London, Whittaker & co.
                  [etc.] 1846.
Description:   1 p.l., xi, [1], 263 p. diagrs. 22 cm.
LC Call No.:   QA304.W24
Subjects:      Differential calculus.
Control No.:   4525307

Author:        Wardlaw, George A. [from old catalog]
Title:         Differential calculus in the workaday world ...
Published:     [n.p.] c1923.
Description:   1 v. cm.
LC Call No.:   QA304.W3
Control No.:   9083578

Author:        Weyr, Eduard, 1852-1903. [from old catalog]
Title:         Poˆcet differenciˆalnˆy. Sepsal Eduard Weyr.
Published:     V Praze, Nákladem Jednoty ˆceských
                  mathematikêu, 1902.
Description:   xii, 416 p. diagr. 24 cm.
Series:        Sborník Jednoty ˆceských mathematikêu v Praze.
                  ˆcislo 5
LC Call No.:   QA304.W54
Subjects:      Differential calculus.
Series Entry:  Jednota ˆceskoslovenských matematikêu a fyskiêu
                  v Praze. Sbornik ; císlo 5.
Control No.:   12906268

Author:        Williamson, Benjamin, 1827-1916.
Title:         An elementary treatise on the differential
                  calculus, containing the theory of plane curves, with
                  numerous examples. By Benjamin Williamson.
Edition:       9th ed., rev.
Published:     London, New York, Longmans, Green, and Co.,
                  1899.
Description:   xvi, 472 p. diagr. 20 cm.
LC Call No.:   QA304.W7
Subjects:      Differential calculus.
Control No.:   9600216

Author:        Woolhouse, W. S. B. (Wesley Stoker Barker),
                  1809-1893.
Title:         Elements of the differential calculus / W. S. B.
                  Woolhouse ...
Edition:       7th ed.
Published:     London : C. Lockwood and co., 1882.
Description:   viii, 160 p. : diagrs. ; 18 cm.
Series:        Weale's Rudimentary series ; 101
LC Call No.:   QA304.W8 1882
Subjects:      Differential calculus.
Control No.:   8249191

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         The elements of the differential calculus;
Published:     Philadelphia, Hogan and Thompson, 1839.
Description:   xx, 255 p. 24 cm.
LC Call No.:   QA304.Y74 1839
Subjects:      Differential calculus.
               Curves.
               Surfaces.
Control No.:   6031565

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         The elements of the differential calculus;
Published:     New York, G. F. Hopkins & sons, 1833.
Description:   xx, 255 p. 24 cm.
LC Call No.:   QA304.Y74
Subjects:      Differential calculus.
               Curves.
               Surfaces.
Control No.:   6322813

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         Elements of the differential calculus :
                  comprehending the general theory of curve surfaces, and of
                  curves of double curvature / by J.R. Young.
Edition:       2nd ed., corr. and enl.
Published:     London : J. Souter, 1836.
Description:   xxii, 312 p. ; 19 cm.
LC Call No.:   QA304.Y74x 1836
Notes:         Includes bibliographical references.
Subjects:      Differential calculus.
               Curves.
               Surfaces.
Control No.:   2400467

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         The elements of the differential calculus;
                  comprehending the general theory of curve surfaces, and of
                  curves of double curvature. Intended for the use of
                  mathematical students in schools and universities. By J.R.
                  Young ...
Published:     London, J. Souter, 1833.
Description:   xxiv, 252 p. 19 cm.
LC Call No.:   QA304.Y72
Subjects:      Differential calculus.
               Curves.
               Surfaces.
Control No.:   12908787

Author:        Young, W. H. (William Henry), 1863-1942.
Title:         The fundamental theorems of the differential
                  calculus / by W.H. Young.
Published:     Cambridge, : The University press, 1910.
Description:   ix, 72 p. : 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics ... no. 11
LC Call No.:   QA304.Y77
Notes:         Series title also at head of t.-p.
Subjects:      Differential calculus.
Control No.:   8223685

Author:        Hind, John, 1796-1866.
Title:         A digested series of examples in the applications
                  of the principles of the differential calculus ...
Published:     Cambridge, Printed by J. Smith, 1832.
Description:   xviii p., 1 l., 175 p. 22 cm.
LC Call No.:   QA305.H66
Subjects:      Differential calculus -- Problems, exercises,
                  etc.
Control No.:   13478686

Author:        Junker, Friedrich Heinrich, 1864- [from old
                  catalog]
Title:         Repetitorium und aufgabensammlung zur
                  differentialrechnung,
Edition:       3., verb. aufl.
Published:     Berlin und Leipzig, G. J. Göschen, 1914.
Description:   129 p. diagrs. 16 cm.
LC Call No.:   QA305.J95 1914
Subjects:      Differential calculus -- Problems, exercises,
                  etc.
Control No.:   8753991

Author:        Junker, Friedrich Heinrich, 1864- [from old
                  catalog]
Title:         Repetitorium und aufgabensammlung zur
                  differentialrechnung,
Published:     Leipzig, G. J. Göschen, 1902.
Description:   119 p. diagr. 16 cm.
LC Call No.:   QA305.J95
Subjects:      Differential calculus -- Problems, exercises,
                  etc.
Control No.:   9132643

Author:        Bessell, F. [from old catalog]
Title:         Ueber die entwickelung der höheren differentiale
                  zusammengesetzter und implicirter functionen ...
Published:     Jena, Druck von W. Ratz, 1872.
Description:   13, [1] p. 25 x 21 cm.
LC Call No.:   QA306.B55
Subjects:      Differential calculus.
Control No.:   10076332

Author:        Biedermann, W. G. Adolf. [from old catalog]
Title:         Über die prinzipien der differentialrechnung
                  ...
Published:     Zürich, Druck von E. Kiesling, 1853.
Description:   31 p. 21 cm.
LC Call No.:   QA306.B58
Subjects:      Differential calculus.
Control No.:   8669662

Author:        Buchanan, Roberdeau, 1839-1916.
Title:         An introduction to the differential calculus by
                  means of finite differences, by Roberdeau Buchanan.
Published:     [Washington, D.C.] 1905.
Description:   27 p. diagrs. 24 cm.
LC Call No.:   QA306.B89
Notes:         "Reprinted from Popular Astronomy, vol. XIII,
                  nos. 5 and 6."
Subjects:      Differential calculus.
Control No.:   6331378

Author:        Buchholz, Ernst. [from old catalog]
Title:         Ueber die verschiedene darstellung des restes in
                  der reihe von Lagrange ...
Published:     Minden, Gedruckt bei J. C. C. Bruns, 1876.
Description:   12 p. 22 cm.
LC Call No.:   QA306.B92
Subjects:      Series, Lagrange's. [from old catalog]
Control No.:   7734434

Author:        Ficklin, Joseph, 1833- [from old catalog]
Title:         To find the differential of a variable quantity
                  without the use of infinitesimals or limits. By Prof. Joseph
                  Ficklin ...
Published:     [Des Moines, Iowa, Mills & co., 1878]
Description:   2 p. 27 cm.
LC Call No.:   QA306.F4
Notes:         Caption title.
               Also found in the Analyst, Des Moines, 1878. Vol.
                  V, p. 177-178.
Subjects:      Differential calculus.
Control No.:   12802700

Author:        Frege, Gottlob, 1848- [from old catalog]
Title:         Rechnungsmethoden, die sich auf eine erweiterung
                  des grössenbegriffes gründen ...
Published:     Jena, Druck von F. Frommann, 1874.
Description:   1 p.l., 26 p., 1 l. 26 x 21 cm.
LC Call No.:   QA306.F85
Subjects:      Calculus. [from old catalog]
Control No.:   6328169

Author:        Greene, William Batchelder, 1819-1878.
Title:         Explanation of the "Theory of the calculus."
Published:     Boston, Lee and Shepard, 1870.
Description:   cover-title, 12 p. diagrs. 21 cm.
LC Call No.:   QA306.G8
Subjects:      Differential calculus.
Control No.:   9606192

Author:        Hadamard, Jacques, 1865-1963.
Title:         La série de Taylor et son prolongement
                  analytique, par Jacques Hadamard.
Published:     [Évreux, Impr. de C. Hérissey] 1901.
Description:   1 p.l., viii, 102 p. 20 cm.
Series:        Scientia. Série physico-mathématique ; no. 12
LC Call No.:   QA306.H12
Notes:         "Bibliographie": p. i-viii.
               At head of title: Scientia, mai 1901.
Subjects:      Series, Taylor's.
               Analytic functions.
Control No.:   1689107

Author:        Hancock, Harris, 1867-1944.
Title:         Theory of maxima and minima, by Harris Hancock
                  ...
Published:     Boston, New York, [etc.] Ginn and company
                  [c1917]
Description:   xiv, 193 p. diagrs. 21 cm.
LC Call No.:   QA306.H13
Subjects:      Maxima and minima.
Control No.:   3580367

Author:        Hardy, Joseph Johnston, 1844-1915.
Title:         Infinitesimals and limits. By Joseph Johnston
                  Hardy ...
Published:     Easton, Pa., The Chemical publishing co., 1900.
Description:   22 p. diagrs. 20 cm.
LC Call No.:   QA306.H2
Dewey No.:     515 19
Subjects:      Calculus.
Control No.:   2160903

Author:        Hess, Adolf, 1879- [from old catalog]
Title:         Stetige abbildung einer linie auf ein quadrat
                  ...
Published:     Uster, Buchdr. E. Weileman, 1905.
Description:   45 p. diagrs. on 5 pl. 23 cm.
LC Call No.:   QA306.H58
Subjects:      Functions. [from old catalog]
               Differential calculus.
Control No.:   10093786

Author:        Lagrange, Charles, 1851-
Title:         Étude du principe de la limite. Limites et
                  infiniment petits. Cas en défaut du principe de la limite,
                  et remarque sur le symbole zéro. Par Charles Lagrange ...
Published:     Bruxelles, Hayez, 1901.
Description:   43 p. 22 cm.
LC Call No.:   QA306.L2
Notes:         "Extrait des Bulletins de l'Académie royale de
                  Belgique (Classe des sciences), nos 9-10 (sept.-oct.) 1901":
                  p. [549]-589.
Subjects:      Mathematics -- Philosophy.
               Calculus.
Control No.:   2161097

Author:        Lyle, John Newton. [from old catalog]
Title:         The first differential coefficient,
Published:     St. Louis, Review steam press, 1872.
Description:   35 p. diagrs. 21 cm.
LC Call No.:   QA306.L9
Subjects:      Differential calculus.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
                  [from old catalog]
Control No.:   6796156

Author:        Marloh, Ernst, 1860- [from old catalog]
Title:         Geschichte des restes der Taylor'schen reihe ...
Published:     Göttingen, Druck der Dieterichschen
                  Univ.-buchdruckerei, W. F. Kaestner, 1881.
Description:   29 p., 1 l. 21 cm.
LC Call No.:   QA306.M34
Subjects:      Series, Taylor's. [from old catalog]
Control No.:   6328167

Author:        Palmer, G. A. [from old catalog]
Title:         Palmer's studies in limit.
Published:     [n.p.] (c1911)
Description:   1 v. cm.
LC Call No.:   QA306.P3
Control No.:   6766824

Author:        Rutgers, Johannes George.
Title:         Over differentialen van gebroken orde en haar
                  gebruik bij de afleiding van bepaalde integralen ...
Published:     Utrecht, Typ. J. van Boekhoven [1904]
Description:   4 p. l., 56 p. 29 x 23 cm.
LC Call No.:   QA306.R8
Notes:         Proefschrift--Utrecht.
Subjects:      Differential calculus.
               Definite integrals.
Control No.:   9620802

Author:        Scherk, Heinrich Ferdinand, 1798-1885. [from old
                  catalog]
Title:         De evolvenda functione
Published:     Berolini, formis L. Quienii [1823]
Description:   2 p. l., 38, [2] p. fold tab. 24 cm.
LC Call No.:   QA306.S3
Subjects:      Differential calculus.
               Bernoulli numbers.
Control No.:   6327952

Author:        Steinbrink, Gustav [Paul Eduard], 1847- [from old
                  catalog]
Title:         Theoria derivatarum altiorum ordinum ...
Published:     Berolini, typis A. W. Schadii [1876]
Description:   2 p.l., 49, [2] p. 24 cm.
LC Call No.:   QA306.S8
Subjects:      Differential calculus.
Control No.:   8669445

Author:        Vidal y Rua, Antonio. [from old catalog]
Title:         Aplicacion del cálculo diferencial á la toería
                  de líneas y superficies,
Published:     Madrid, Impr. del Memorial de ingenieros, 1880.
Description:   p. cm.
LC Call No.:   QA306.V5
Subjects:      Differential calculus.
               Curves. [from old catalog]
               Surfaces. [from old catalog]
               Maxima and minima. [from old catalog]
Control No.:   5906261

Author:        Walsh, J. L. (Joseph Leonard), 1895-
Title:         A rigorous treatment of maximum-minimum problems
                  in the calculus.
Published:     Boston, Heath [1962]
Description:   22 p. 21 cm.
LC Call No.:   QA306.W28
Subjects:      Maxima and minima.
Control No.:   2166974

Author:        Wilson, William D., 1816-
Title:         Differentials and the method of finding them / by
                  Prof. William D. Wilson.
Published:     [Albany? N.Y. : s.n., 1873?]
Description:   p. 58-70 : ill. ; 24 cm.
LC Call No.:   QA306.W7
Notes:         Cover-title.
               From the Proceedings of the University of
                  Convocation, held at Albany, N. Y., July, 1873.
Subjects:      Differential calculus.
Control No.:   8201303

Author:        Bernoulli, Jean, 1667-1748.
Title:         Die erste integralrechnung; eine auswahl aus
                  Johann Bernoullis Mathematischen vorlesungen über die
                  methode der integrale und anderes, aufgeschrieben zum
                  gebrauch des herrn marquis de l'Hospital in den jahren 1691
                  und 1692 als der verfasser sich in Paris aufhielt. Mit 119
                  textfiguren. Aus dem lateinischen übers. und hrsg. von dr.
                  Gerhard Kowalewski.
Published:     Leipzig, Berlin, W. Engelmann, 1914.
Description:   187, [1] p. diagrs. 19 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften nr.
                  194
LC Call No.:   QA308.B4
Subjects:      Calculus, Integral.
Other authors: Kowalewski, Gerhard, 1876-1950.
Control No.:   7768720

Author:        Bertrand, Joseph, 1822-1900.
Title:         Traité de calcul différentiel et de calcul
                  intégral. Calcul intégral : intégrales définies et
                  indéfinies / par J. Bertrand.
Published:     Paris : Gauthier-Villars, 1870.
Description:   xii, 725 p. ; 28 cm.
LC Call No.:   QA308.B47 1870
Notes:         "Ce volume qui fait suite au Traité de calcul
                  différentiel publié il y a six ans déjà, en 1864,
                  contient la première section du calcul
                  intégral."--Avertissement, p. [xi]
Subjects:      Calculus, Integral.
Control No.:   8283518

Author:        Bruno, Karl.
Title:         Die Grundlehren der Integral- und
                  Differentialrechnung / von Karl Bruno.
Published:     Wien : Alfred Hölder, 1908.
Description:   54 p. : ill. ; 25 cm.
LC Call No.:   QA308.B78x 1908
Subjects:      Calculus, Integral.
               Differential calculus.
Control No.:   4764775

Author:        Byerly, William Elwood, 1849- [from old catalog]
Title:         Elements of the integral calculus,
Edition:       2d ed.
Published:     Boston, Ginn and company, 1889.
Description:   xvi, 339 p., 1 l., 65-76, 32 p. incl. tables,
                  diagrs. 22 cm.
LC Call No.:   QA308.B99
Subjects:      Calculus, Integral. [from old catalog]
               Functions. [from old catalog]
               Differential equations. [from old catalog]
Other authors: Peirce, Benjamin Osgood, 1854-1914. [from old
                  catalog]
Control No.:   8196085

Author:        Byerly, William Elwood, 1849- [from old catalog]
Title:         Elements of the integral calculus,
Published:     Boston, Ginn, Heath, & co., 1881.
Description:   xi, 182 p., 1 l., 65-76 p. diagr. 22 cm.
LC Call No.:   QA308.B98
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   7259258

Author:        Condorcet, Jean-Antoine-Nicolas de Caritat,
                  marquis de, 1743-1794.
Title:         Du calcul integral / par M. le marquis de
                  Condorcet.
Published:     A Paris : De l'imprimerie de Didot, 1765.
Description:   vii [i.e. viii], 94, [2] p. ; 23 cm. (4to)
LC Call No.:   QA308.C663 1768
Notes:         Signatures: ap4s A-Mp4s.
               BN XXXI, column 502
               Errata: p. [2] at end.
               With: Condorcet, Jean-Antoine-Nicolas de Caritat.
                  Essais d'analyse ... A Paris : De l'imprimerie de Didot,
                  1768. As issued.
Subjects:      Calculus, Integral -- Early works to 1800.
Control No.:   13051898

Author:        Condorcet, Jean-Antoine-Nicolas de Caritat,
                  marquis de, 1743-1794.
Title:         Du probleme des trois corps / par M. le marquis
                  de Condorcet.
Published:     A Paris : De l'imprimerie de Didot, 1767.
Description:   [4], 83, [1] p. ; 23 cm. (4to)
LC Call No.:   QA308.C663 1768
Notes:         Signatures: pip2s A-Kp4s Lp2s.
               BN XXXI, column 512
               With: Condorcet, Jean-Antoine-Nicolas de Caritat.
                  Essais d'analyse ... A Paris : De l'imprimerie de Didot,
                  1768. As issued.
Subjects:      Three-body problem -- Early works to 1800.
Control No.:   13051938

Author:        Condorcet, Jean-Antoine-Nicolas de Caritat,
                  marquis de, 1743-1794.
Title:         Essais d'analyse / par M. le marquis de
                  Condorcet.
Published:     A Paris : De l'imprimerie de Didot, 1768.
Description:   [4], li, [1] p. ; 23 cm.
LC Call No.:   QA308.C663 1768
Notes:         "Tome premier." All published?
               Signatures: pip2s a-fp4s gp2s.
               BN XXXI, column 508
               Errata, covering the preface and the following 3
                  works: p. [xlvi]-li.
               With: Condorcet, Jean-Antoine-Nicolas de Caritat.
                  Du calcul integral ... A Paris : De l'imprimerie de Didot,
                  1765 -- Condorcet, Jean-Antoine-Nicolas de Caritat. Du
                  probleme des trois corps ... A Paris : De l'imprimerie de
                  Didot, 1767 -- Condorcet, Jean-Antoine-Nicolas de Caritat. Le
                  marquis de Condorcet a Mr. d'Alembert ... A Paris : De
                  l'imprimerie de Didot, 1768. Issued together.
Subjects:      Calculus, Integral -- Early works to 1800.
Control No.:   13051761

Author:        Condorcet, Jean-Antoine-Nicolas de Caritat,
                  marquis de, 1743-1794.
Title:         Le marquis de Condorcet a Mr. d'Alembert : sur le
                  systême du monde et sur le calcul intégral.
Published:     A Paris : De l'imprimerie de Didot, 1768.
Description:   93 [i.e. 95], [1] p. ; 23 cm. (4to)
LC Call No.:   QA308.C663 1768
Notes:         Signatures: [A]p4s B-Mp4s.
               Error in paging: 39-40 repeated.
               With: Condorcet, Jean-Antoine-Nicolas de Caritat.
                  Essais d'analyse ... A Paris : De l'imprimerie de Didot,
                  1768. As issued.
Subjects:      Alembert, Jean Le Rond d', 1717-1783. Recherches
                  sur differens points importans du systême du monde.
               Astronomy -- Early works to 1800.
               Calculus, Integral -- Early works to 1800.
Control No.:   13051970

Author:        Cox, Homersham, 1821-1897. [from old catalog]
Title:         A rudimentary treatise on the integral calculus,
Published:     London, C. Lockwood and son [1910?]
Description:   xii, 124 p. diagrs. 18 cm.
LC Call No.:   QA308.C68
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   7857562

Author:        Dvivedi, Sudhakara. [from old catalog]
Uniform Title: Calarasikalana [from old catalog]
Title:         Calar¯aâsikalana.
Published:     [1895]
Description:   6, 4, 16, 443 p. 24 cm.
LC Call No.:   QA308.D83
Notes:         Romanized.
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   7500093

Author:        Edwards, Joseph, 1854-1931.
Title:         A treatise on the integral calculus with
                  applications, examples and problems, by Joseph Edwards ...
Published:     London, Macmillan and co., limited, 1921-22.
Description:   2 v. diagrs. 23 cm.
LC Call No.:   QA308.E3
Subjects:      Calculus, Integral.
Control No.:   4526453

Author:        Hermite, Charles, 1822-1901. [from old catalog]
Title:         Cours de M. Hermite,
Edition:       4. éd.
Published:     Paris, A. Hermann, 1891.
Description:   2 p.l., vi, 293 p. diagrs. 27 cm.
LC Call No.:   QA308.H4 1891
Subjects:      Calculus, Integral. [from old catalog]
               Geometry. [from old catalog]
Other authors: Andoyer, Henri, 1862-1929. [from old catalog]
Control No.:   6852989

Author:        Hymers, J[ohn], 1803-1887. [from old catalog]
Title:         A treatise on the integral calculus.
Edition:       2d ed.
Published:     Cambridge, Printed by J. Smith, for J. & J. J.
                  Deighton ; [etc., etc.] 1835.
Description:   xv, 255, [1] p. 2 pl. 22 cm.
LC Call No.:   QA308.H99
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   6324905

Author:        Johnson, William Woolsey, 1841-1927.
Title:         An elementary treatise on the integral calculus,
                  founded on the method of rates or fluxions; by William
                  Woolsey Johnson ...
Published:     New York, J. Wiley and sons, 1881.
Description:   ix, 228 p. diagrs. 21 cm.
LC Call No.:   QA308.J7 1881
Subjects:      Calculus, Integral.
Control No.:   1689171

Author:        Johnson, William Woolsey, 1841-1927.
Title:         A treatise on the integral calculus founded on
                  the method of rates, by William Woolsey Johnson.
Edition:       1st ed. 1st thousand.
Published:     New York, J. Wiley & sons; [etc., etc.] 1907.
Description:   xiv, 440 p. diagrs. 21 cm.
LC Call No.:   QA308.J72
Notes:         "The present volume is an enlargement and an
                  extension of my Elementary treatise on the integral calculus,
                  of which a revised edition was published in 1898 ... The book
                  forms a companion volume to my Treatise on the differential
                  calculus, founded on the method of rates (John Wiley & sons,
                  1904) to which belong the references made in the
                  text."--Pref.
Subjects:      Calculus, Integral.
Control No.:   9618961

Author:        Johnson, William Woolsey, 1841- [from old
                  catalog]
Title:         An elementary treatise on the integral calculus,
Edition:       Rev. ed.
Published:     New York, J. Wiley & sons; [etc., etc] 1898.
Description:   ix, 234 p. diagrs. 21 cm.
LC Call No.:   QA308.J7 1898
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   7252437

Author:        MacNeish, Harris Franklin.
Title:         Algebraic technique of integration.
Edition:       [2d ed.]
Published:     Dubuque, Iowa, W. C. Brown Co. [1952]
Description:   133 p. 23 cm.
LC Call No.:   QA308.M25 1952
Subjects:      Calculus, Integral.
Control No.:   10247142

Author:        Moigno, abbé (François Napoléon Marie),
                  1804-1884.
Uniform Title: Leçons de calcul différential et de calcul
                  intégral. German
Title:         Vorlesungen über die Integralrechnung.
                  Vorzüglich nach den Methoden von A.L. Cauchy, bearb. von
                  Moigno. Deutsch hrsg. von Dr. C.H. Schnuse.
Published:     Braunschweig, G.C.E. Meyersen, 1846.
Description:   1 p. l., [v]-xxxvi, 618 p. 22 cm.
LC Call No.:   QA308.M71
Subjects:      Calculus, Integral.
               Differential equations.
Control No.:   13168581

Author:        [Osborne, George Abbott] [from old catalog]
Title:         The integral calculus applied to plane curves.
Published:     Boston, Printed by J. S. Cushing & co., 1889.
Description:   1 p.l., 24 p. diagr. 21 cm.
LC Call No.:   QA308.O82
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   5857018

Author:        Ottley, W[illiam] C[ambell], 1808-1843. [from old
                  catalog]
Title:         A treatise on the integral calculus, with a
                  collection of examples.
Published:     Cambridge, Printed for W. P. Grant; London,
                  Whittaker and co., and Simpkin and co., 1838.
Description:   viii, 104 p. 22 cm.
LC Call No.:   QA308.O91
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   8198242

Author:        Percival, A. S. (Archibald Stanley), 1862-
Title:         Practical integration for the use of engineers,
                  etc., by A.S. Percival ...
Published:     London, Macmillan and co., limited, 1909.
Description:   4 p.l., 114 p. tables, diagrs. 19 cm.
LC Call No.:   QA308.P42 1909
Subjects:      Calculus, Integral.
Control No.:   3580171

Author:        Percival, A. S. (Archibald Stanley), 1862-
Title:         Practical integration for the use of engineers,
                  etc., by A.S. Percival ...
Published:     London, Macmillan and co., limited, 1907.
Description:   3 p.l., 86 p. tables 19 cm.
LC Call No.:   QA308.P42
Subjects:      Calculus, Integral.
Control No.:   745298

Author:        Phillips, H. B. (Henry Bayard), 1881-
Title:         Integral calculus, by H. B. Phillips.
Edition:       1st ed.
Published:     New York, John Wiley, 1917.
Description:   v, 194 p. diagrs. 19 cm.
LC Call No.:   QA308.P5
Subjects:      Calculus, Integral.
Control No.:   8245928

Author:        Ritt, Joseph Fels, 1893-1951.
Title:         Integration in finite terms; Liouville's theory
                  of elementary methods.
Published:     New York, Columbia Univ. Press, 1948.
Description:   vii, 100 p. 22 cm
LC Call No.:   QA308.R5 1948
Dewey No.:     517.3
Notes:         "References": p. [99]-100.
Subjects:      Calculus, Integral.
Other authors: Liouville, Joseph, 1809-1882.
Control No.:   747652

Author:        Rosenthal, Arthur, 1887-
Title:         Introduction to the theory of measure and
                  integration.
Published:     Stillwater, Dept. of Mathematics, Oklahoma
                  Agricultural and Mechanical College, 1955.
Description:   125, iv l. diagrs. 28 cm.
Series:        U.S. National Science Foundation. Summer
                  Mathematics Institute notes.
LC Call No.:   QA308.R6
Notes:         Bibliography: iv l.
Subjects:      Calculus, Integral.
               Functions.
Other titles:  Theory of measure and integration.
Control No.:   7467634

Author:        Souza, Joaquim Gomes de, 1829-1863. [from old
                  catalog]
Title:         Mélanges de calcul intégral.
Published:     Leipzig, F. A. Brockhaus, 1882.
Description:   viii p., 1 l., 280 p. 28 x 23 cm.
LC Call No.:   QA308.S72
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   6794075

Author:        Todhunter, Isaac, 1820-184. [from old catalog]
Title:         A treatise on the integral calculus and its
                  applications with numerous examples.
Published:     London, Macmillan and co., limited; New York, The
                  Macmillan company, 1906.
Description:   vi p., 1 l., 408 p. diagrs. 20 cm.
LC Call No.:   QA308.T6
               Microfilm 22352 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Calculus. Integral. [from old catalog]
               Calculus of variations. [from old catalog]
Control No.:   7750914

Author:        Williamson, Benjamin, 1827-1916.
Title:         An elementary treatise on the integral calculus,
                  containing applications to plane curves and surfaces, and
                  also chapters on the calculus of variations, with numerous
                  examples. By Benjamin Williamson.
Edition:       7th ed., rev. and enl.
Published:     New York, London, Longmans, Green, and Co.,
                  1896.
Description:   xvii, 512 p. diagr. 19 cm.
LC Call No.:   QA308.W7
Subjects:      Calculus, Integral.
               Calculus of variations.
Control No.:   9600210

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         The elements of the integral calculus;
Published:     London, J. Souter, 1833.
Description:   xi, [1], 306 p. diagr. 19 cm.
LC Call No.:   QA308.Y73
Subjects:      Calculus, Integral.
               Differential equations.
Control No.:   9134613

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         The elements of the integral calculus; with its
                  applications to geometry and to the summation of infinite
                  series. Intended for the use of mathematical students in
                  schools and universities. By J. R. Young ... Rev. and cor. by
                  Michael O'Shannessy, A. M.
Published:     Philadelphia, Lea & Blanchard, 1833.
Description:   xiii, [1], 292 p. diagr. 23 cm.
LC Call No.:   QA308.Y74
Subjects:      Calculus, Integral.
               Differential equations.
Control No.:   8663738

Author:        Brahy, Ed. (Edouard)
Title:         Exercices méthodiques de calcul intégral, par
                  M. Ed. Brahy.
Edition:       Nouv. éd. entièrement rev.
Published:     Paris, Gauthier-Villars & fils, 1903.
Description:   viii, 301 p. diagrs. 23 cm.
LC Call No.:   QA309.B8
Control No.:   5896926

Author:        [Greene, Dascom], 1825- [from old catalog]
Title:         Examples of the integration of simple
                  differentials.
Published:     Troy, N.Y., Rensselaer polytechnic institute,
                  1866.
Description:   40 p. 24 cm.
LC Call No.:   QA309.G7
Subjects:      Calculus, Integral -- Problems, etc. [from old
                  catalog]
Control No.:   9137817

Author:        Hann, James, 1799-1856.
Title:         Examples on the integral calculus.
Published:     London, J. Weale, 1850.
Description:   2 p. l., 128 p. diagrs. 18 cm.
LC Call No.:   QA309.H3
Subjects:      Calculus, Integral -- Problems, etc. [from old
                  catalog]
Control No.:   9642275

Author:        [British association for advancement of science]
                  [from old catalog]
Title:         Calculation of the G (r.v)-integrals.
Published:     [London, Printed by Spottiswoode and co., 1896]
Description:   13 p. tables. 22 cm.
LC Call No.:   QA310.B84
Subjects:      Integrals.
Other authors: Pearson, Karl, 1857- [from old catalog]
Control No.:   9614766

Author:        British Association for the Advancement of
                  Science.
Title:         Tables of F (r,v) and H (r,v) functions.
Published:     London, Offices of the Association [1899]
Description:   56 p. 22 cm.
LC Call No.:   QA310.B86
Notes:         Cover-title.
               From the Report of the 69th meeting of the
                  association at Dover, 1899.
               Tables of the G (r,v)-integrals.--Report of the
                  committee consisting of Rev. Robert Harley (chairman),
                  Professor A.R. Forsyth (secretary), Dr. J.W. Glaisher,
                  Professor A. Lodge, and Professor Karl Pearson. (Drawn up by
                  Professor Karl Pearson)--Appendix. Tables of F (r,v) and H
                  (r,v) functions. By Miss Alice Lee.
Subjects:      Integrals.
Other authors: Pearson, Karl, 1857-1936
               Lee, Alice Elizabeth.
Control No.:   7739213

Author:        Dwight, Herbert Bristol, b. 1885.
Title:         Tables of integrals and other mathematical data.
Edition:       4th ed.
Published:     New York, Macmillan [1961]
Description:   336 p. illus. 22 cm.
LC Call No.:   QA310.D8 1961
Dewey No.:     517.39
Subjects:      Integrals.
Control No.:   1694425

Author:        Dwight, Herbert Bristol, b. 1885.
Title:         Tables of integrals and other mathematical data.
Edition:       3d ed.
Published:     New York, Macmillan [1957]
Description:   288 p. illus. 22 cm.
Series:        A Series of mathematical texts for colleges
LC Call No.:   QA310.D8 1957
Dewey No.:     517.39
Subjects:      Integrals.
Control No.:   1693376

Author:        Dwight, Herbert Bristol, b. 1885.
Title:         Tables of integrals and other mathematical data,
                  by Herbert Bristol Dwight ...
Edition:       Rev. ed.
Published:     New York, The Macmillan Company, 1947.
Description:   viii p., 1 l., 250 p. diagrs. 21 cm.
Series:        [A Series of mathematical texts]
LC Call No.:   QA310.D8 1947
Dewey No.:     517.39
Notes:         "First edition ... published 1934."
               "References": p. 246-248.
Subjects:      Integrals.
Control No.:   9752178

Author:        Dwight, Herbert Bristol, b. 1885.
Title:         Tables of integrals and other mathematical data,
                  by Herbert Bristol Dwight ...
Published:     New York, The Macmillan company, 1934.
Description:   viii p., 1 l., 222 p. diagrs. 22 cm.
Series:        A series of mathematical texts
LC Call No.:   QA310.D8
Dewey No.:     517.39
Notes:         "References": p. 219-220.
Subjects:      Integrals.
Series Entry:  Series of mathematical texts.
Control No.:   4054006

Author:        Haan, D. Bierens de (David Bierens), 1822-1895.
Title:         Nouvelles tables d'intégrales définies, par D.
                  Bierens de Haan ...
Edition:       Ed. of 1867--corrected; with an English
                  translation of the introduction by Professor J. F. Ritt ...
Published:     New York, G. E. Stechert & Co., 1939.
Description:   6 p. l., xiv, 716 p. 28 x 22 cm.
LC Call No.:   QA310.B58 1939
Dewey No.:     517.32
Subjects:      Definite integrals.
Other authors: Ritt, Joseph Fels, 1893-1951, tr.
Control No.:   10185087

Author:        Haan, D. Bierens de (David Bierens), 1822-1895.
Title:         Nouvelles tables d'intégrales définies, par D.
                  Bierens de Haan ...
Published:     Leide, P. Engels, 1867.
Description:   xiv, 732 p., 1 l. 28 x24 cm.
LC Call No.:   QA310.B58
Subjects:      Definite integrals.
Control No.:   3579760

Author:        Harvard University. Computation Laboratory.
Title:         Tables of generalized sine- and cosine-integral
                  functions.
Published:     Cambridge, Harvard Univ. Press, 1949.
Description:   2 v. diagrs. 28 cm.
Series:        Harvard University. Annals, v. 18-19
LC Call No.:   QA310.H3
Dewey No.:     517.39
Notes:         Includes "References."
Subjects:      Integrals.
Control No.:   9293585

Author:        Hirsch, Meyer, 1765-1851. [from old catalog]
Title:         Integral tables;
Published:     London, Printed for W. Baynes & son, 1823.
Description:   xxx p., 1 l. 279 p. 22 cm.
LC Call No.:   QA310.H6
Subjects:      Integrals. [from old catalog]
Control No.:   6794592

Author:        Hudson, Ralph Gorton. [from old catalog]
Title:         A table of integrals,
Edition:       1st ed.
Published:     New York, John Wiley & sons, inc.; [etc., etc.]
                  1917.
Description:   25 p. 20 cm.
LC Call No.:   QA310.H8
Subjects:      Integrals. [from old catalog]
Other authors: Lipka, Joseph, 1883- [from old catalog]
Control No.:   9649888

Author:        Markov, A. A. (Andreæi Andreevich), 1856-1922.
Title:         Table des valeurs de l'intégrale [symbol for
                  integral from x to infinity] e-tp2s dt. Par André Markoff.
                  (Présenté le 12 janvier 1888.).
Published:     St. Pétersbourg, Académie impériale des
                  sciences; [etc., etc.] 1888.
Description:   1 p. l., xxvii, 98 p. 25 cm.
LC Call No.:   QA310.M3
Notes:         On t.p. "-tp2s" is superscript.
Subjects:      Integrals, Definite.
Control No.:   12850697

Author:        Peirce, B. O. (Benjamin Osgood), 1854-1914.
Title:         A short table of integrals, by B.O. Peirce ...
Edition:       2d rev. ed.
Published:     Boston, New York [etc.] Ginn & company [c1910]
Description:   144 p. incl. tables. 21 cm.
LC Call No.:   QA310.P42
ISBN:          $1.00
Subjects:      Integrals.
Control No.:   273164

Author:        Peirce, B. O. (Benjamin Osgood), 1854-1914.
Title:         A short table of integrals, comp. by B.O.
                  Peirce.
Edition:       Abridged ed.
Published:     Boston, New York [etc.] Ginn and company [c1914]
Description:   32 p. 21 cm.
LC Call No.:   QA310.P42 1914
ISBN:          $0.15
Subjects:      Integrals.
Control No.:   4053079

Author:        Peirce, Benjamin Osgood, 1854-1914.
Title:         A short table of integrals, by B.O. Peirce.
Edition:       Rev. ed.
Published:     Boston, U.S.A., Ginn & Company, 1899.
Description:   134 p. incl. tables. 21 cm.
LC Call No.:   QA310.P4
Subjects:      Integrals.
Control No.:   7252962

Author:        Peirce, Benjamin Osgood, 1854-1914.
Title:         A short table of integrals, by B.O. Pierce ...
Edition:       3d rev. ed.
Published:     Boston, New York [etc.] Ginn and Company [c1929]
Description:   1 p. l., 156 p. incl. tables, diagrs. 22 cm.
LC Call No.:   QA310.P42 1929
Subjects:      Integrals.
Control No.:   7338062

Author:        Peirce, Benjamin Osgood, 1854-1914.
Title:         A short table of integrals. Rev. by Ronald M.
                  Foster.
Edition:       4th ed.
Published:     New York, Ginn, [1956]
Description:   189 p. illus. 22 cm.
LC Call No.:   QA310.P42 1956
Dewey No.:     517.39
Subjects:      Integrals.
Control No.:   6058849

Author:        Peirce, B[enjamin] O[sgood], 1854- [from old
                  catalog]
Title:         A short table of integrals.
Published:     Boston, Ginn & company, 1889.
Description:   32 p. 22 cm.
LC Call No.:   QA310.P3
Subjects:      Integrals. [from old catalog]
Control No.:   8664199

Author:        Rogers, William Martin, 1928-
Title:         Tables of transport integrals.
Published:     Washington, U.S. Govt. Print. Off., 1958.
Description:   ii, 46 p. diagrs., tables. 26 cm.
Series:        United States. National Bureau of Standards.
                  Circular no. 595
LC Call No.:   QC100.U555 no. 595
Subjects:      Integrals.
Other authors: Powell, Robert L., joint author.
Other titles:  Transport integrals.
Control No.:   6075447

Author:        Ballantyne, James, 1859-
Title:         The integral calculus on the integration of the
                  powers of transcendental functions, new methods and theorems,
                  calculation of the Bernoullian numbers, rectification of the
                  logarithmic curve, integration of logarithmic binomials etc.,
                  by James Ballantyne.
Published:     Boston, The author, 1919.
Description:   41 p. diagrs. 24 cm.
LC Call No.:   QA311.B3
Subjects:      Calculus, Integral.
Control No.:   1218191

Author:        Benner, Henry, 1861-1901. [from old catalog]
Title:         Bestimmung der coefficienten, welche bei der
                  berechnung der integrale õS xõndx [divided by] die
                  Quadratwurzel von 1+ax+bxp2s und õS xõndx [divided by] die
                  Quadratwurzel von 1+ax+bxp2s+cxp3s auftreten ...
Published:     Boston, Ginn & company, 1899.
Description:   ix, 59, [1] p. 23 cm.
LC Call No.:   QA311.B46
Notes:         Inaug.-diss.--Erlangen.
Subjects:      Integrals. [from old catalog]
Control No.:   6328190

Author:        Bergbohm, Julius.
Title:         Entwurf einer neuen integralrechnung auf grund
                  der potenzial-, logarithmal- und numeralrechnung, von dr.
                  Julius Bergbohm ...
Published:     Leipzig, B.G. Teubner, 1892-93.
Description:   2 v. 24 cm.
LC Call No.:   QA311.B47
Dewey No.:     517.3
Notes:         [1. hft.] Die rationalen algebraischen und die
                  goniometrischen integrale.--2. hft. Die irrationalen,
                  exponentiellen, logarithmischen und cyclometrischen
                  integrale.
Subjects:      Calculus, Integral.
Control No.:   1690876

Author:        Blomstrand, Fredr[ik] Theod[or], 1824- [from old
                  catalog]
Title:         De magnis logarithmi integralis valoribus apte
                  computandis ...
Published:     Lundæ, typis Berlingianis, 1852.
Description:   1 p.l., 28 p. 24 cm.
LC Call No.:   QA311.B6
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   5860205

Author:        Bohren, Arnold.
Title:         Über die Fresnelschen integrale ...
Published:     Bern, Buchdruckerei K.J. Wyss, 1901.
Description:   48 p. pl., diagrs. 23 cm.
LC Call No.:   QA311.B67
Notes:         Inaug.-dis.-Bern.
               "Benutzte litteratur": p. 48.
Subjects:      Definite integrals.
               Diffraction.
Control No.:   6796368

Author:        Cauchy, Augustin Louis, Baron, 1789-1857.
Title:         Abhandlung über bestimmte integrale zwischen
                  imaginären grenzen. Von Augustin-Louis Cauchy (1825) Hrsg.
                  von P. Stäckel.
Published:     Leipzig, W. Engelmann, 1900.
Description:   80 p. 20 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften,
                  nr. 112
LC Call No.:   QA311.C37
Notes:         First published Paris, 1825, under title:
                  Mémoire sur les intégrales définies, prises entre des
                  limites imaginaires.
Subjects:      Definite integrals.
Other authors: Stäckel, Paul, 1862-1919.
Control No.:   9602949

Author:        Christen, Theophil.
Title:         Beiträge zur verwendung des freien
                  integrationsweges ...
Published:     Greifswald, Druck von F.W. Kunike, 1897.
Description:   2 p. l., 35 p. pl. 24 cm.
LC Call No.:   QA311.C5
Notes:         Inaug.-diss.--Basel.
Subjects:      Calculus, Integral.
Control No.:   8658530

Author:        Ehrat, Jacob. [from old catalog]
Title:         Über das algebraischwerden der integrale
                  irrationaler differentiale von der form II(x, y)dx, in
                  welchen II(x, y) eine rationale funktion ist und zwischen x
                  und y eine allgemeine gleichung 2ter ordnung besteht ...
Published:     Zürich, 1906.
Description:   50 p. diagrs. 22 cm.
LC Call No.:   QA311.E6
Subjects:      Integrals. [from old catalog]
Control No.:   9154632

Author:        Frey, Hermann, 1880- [from old catalog]
Title:         Ueber das vorzeichen gewisser bestimmter
                  integrale ...
Published:     Heidelberg, Buchdr. von K. Rössler, 1905.
Description:   47 p. 23 cm.
LC Call No.:   QA311.F8
Subjects:      Definite integrals.
Control No.:   7271982

Author:        Gubler, Eduard, 1845- [from old catalog]
Title:         Ueber ein discontinuirliches integral ...
Published:     Leipzig, Druck von B. G. Teubner, 1896.
Description:   1 p.l., [37]-48 p. diagrs. 24 cm.
LC Call No.:   QA311.G92
Subjects:      Definite integrals.
               Bessel functions.
Control No.:   9606413

Author:        Gunther, Charles Otto, 1879-
Title:         Integration by trigonometric and imaginary
                  substitution, by Charles O. Gunther ... with an introduction
                  by J. Burkitt Webb ...
Published:     New York, D. Van Nostrand company, 1907.
Description:   vi, 79 p. diagrs. 21 cm.
LC Call No.:   QA311.G94
Subjects:      Calculus, Integral.
Other authors: Webb, John Burkitt, 1841-
Control No.:   7745573

Author:        Gutknecht, Alfred.
Title:         Integrallogarithmus ...
Published:     Bern, Druck von K.J. Wyss, 1903.
Description:   55, [1] p. diagrs. 23 cm.
LC Call No.:   QA311.G97
Notes:         Inaug.-dis.--Bern.
               "Verzeichnis der benutzten litteratur": p. [56]
Subjects:      Definite integrals.
Control No.:   272648

Author:        Hardy, G[odfrey] H[arold] [from old catalog]
Title:         The integration of functions of a single
                  variable,
Published:     Cambridge, University press, 1905.
Description:   viii, 53 p. 22 cm.
LC Call No.:   QA311.H2
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   6335177

Author:        Herzberg, Rudolf, 1837- [from old catalog]
Title:         De integralium multiplicium reductione ...
Published:     Halis, typis Ploetzianis [1858]
Description:   2 p.l., 19, [1] p. 26 cm.
LC Call No.:   QA311.H58
Subjects:      Integrals, Multiple. [from old catalog]
Control No.:   8669635

Author:        Jonquière, Alfred, 1862-1899. [from old
                  catalog]
Title:         Ueber einige transcendente, welche bei der
                  wiederholten integration rationaler funktionen auftreten ...
Published:     Stockholm, K. Boktryckeriet, P. A. Norstedt &
                  söner, 1889.
Description:   50 p. diagrs. 22 cm.
LC Call No.:   QA311.J6
Subjects:      Integrals, Multiple. [from old catalog]
Control No.:   10074728

Author:        [Kapteyn, Willem], 1849- [from old catalog]
Title:         Voordrachten over den Grondslag van een
                  bibliographisch repertorium der wiskundige wetenschappen.
Published:     Amsterdam, W. Versluys, 1893.
Description:   1 p.l., [17] p. 22 cm.
LC Call No.:   QA311.K2
Subjects:      Definite integrals.
               Répertoire bibliographique des sciences
                  mathématiques. [from old catalog]
               Classification -- Books -- Mathematics. [from old
                  catalog]
Control No.:   9635247

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Exercices de calcul intégral sur divers ordres
                  de transcendantes et sur les quadratures / par A. M.
                  Legendre.
Published:     Paris : Courcier, 1811-17.
Description:   3 v. : ill. ; 25 cm.
LC Call No.:   QA311.L49
Notes:         Vol. 1: 1811; v. 2: 1817; v. 3: 1816.
Subjects:      Calculus, Integral.
               Elliptic functions.
               Gamma functions.
Control No.:   9604827

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Recherches sur diverses sortes d'intégrales
                  définies,
Published:     [Paris, 1809]
Description:   97 p. tables. 26 x 20 cm.
LC Call No.:   QA311.L51
Subjects:      Definite integrals.
               Gamma functions.
Control No.:   10073130

Author:        Lejeune Dirichlet, Peter Gustav, 1805-1859.
Title:         G. Lejeune-Dirichlets Vorlesungen über die Lehre
                  von den Einfachen und Mehrfachen Bestimmten Integralen. Hrsg.
                  von G. Arendt.
Published:     Braunschweig, F. Vieweg und sohn, 1904.
Description:   xxiii, 476 p. diagrs. 24 cm.
LC Call No.:   QA311.L53
Notes:         "Mit in den text eingedruckten abbildungen."
Subjects:      Definite integrals.
               Gamma functions.
               Attractions of ellipsoids.
Other authors: Arendt, Gustav, 1832-1915, ed.
Control No.:   6798524

Author:        Lester, Oliver Clarence, 1873-
Title:         The integrals of mechanics, by Oliver Clarence
                  Lester ...
Published:     Boston, New York [etc.] Ginn and company [c1909]
Description:   vi, 67 p. diagrs. 24 cm.
LC Call No.:   QA311.L6
Subjects:      Integrals.
Control No.:   3107352

Author:        Miles, Egbert J., 1886-
Title:         The absolute minimum of a definite integral in a
                  special field ... by Egbert J. Miles.
Published:     Lancaster, Pa., The New era printing company,
                  1912.
Description:   1 p.l., 35-49 p., 1 l. diagrs. 28 cm.
LC Call No.:   QA311.M5
Notes:         Thesis (Ph. D.)--University of Chicago, 1910.
               From the Transactions of the American
                  mathematical society, vol. 4.
               Vita.
Subjects:      Definite integrals.
Control No.:   3580118

Author:        Mott-Smith, Harold Meade, 1897- [from old
                  catalog]
Title:         Certain integral transformations connected with
                  the summation problem,
Published:     Urbana, Ill., 1934.
Description:   2 p. l., 12 p., 1 l. 27 x 22 cm.
LC Call No.:   QA311.M6 1933
Subjects:      Integrals. [from old catalog]
               Series. [from old catalog]
Control No.:   10169495

Author:        Nehls, Christian, 1841-1897. [from old catalog]
Title:         Uber graphische integration und ihre anwendung in
                  der grpahischen statistik. Von Chr. Nehls ... Mit 13
                  figurentafeln.
Published:     Hannover, C. Rümpler, 1877.
Description:   viii, 223 p. xiii fold. pl. (diagrs.) 26 cm.
LC Call No.:   QA311.N4
Subjects:      Calculus, Integral.
               Graphic statics.
Control No.:   12850610


Author:        Schmid, Eugen.
Title:         Die Cauchy'sche methode der auswertung bestimmter
                  integrale zwischen reellen grenzen ...
Published:     Stuttgart, Hofbuchdruckerei zu Gutenberg, C.
                  Grüninger (Klett & Hartmann), 1903.
Description:   93 p. diagrs. 28 x 21 cm.
LC Call No.:   QA311.S34
Notes:         Inaug.-dis.--Marburg.
Subjects:      Definite integrals.
Control No.:   7266172

Author:        Stenberg, [Isak] Ludvig, 1834- [from old
                  catalog]
Title:         Om integration af logarithmiskt-rationela
                  differentialformler ...
Published:     Lund, Tryckt uti Berlingska boktryckeriet, 1857.
Description:   1 p.l., 30 p. 28 cm.
LC Call No.:   QA311.S8
Subjects:      Calculus, Integral. [from old catalog]
Control No.:   8201427

Author:        Thomae, J. (Johannes), 1840-1921.
Title:         Vorlesungen über bestimmte integrale und die
                  Fourierschen reihen, von J. Thomae ... Mit 10 figuren im
                  text.
Published:     Leipzig, Berlin, B.G. Teubner, 1908.
Description:   vi, 182 p. diagrs. 25 cm.
LC Call No.:   QA311.T6
Subjects:      Definite integrals.
               Fourier series.
Control No.:   3107337

Author:        Vidal y Rua, Antonio. [from old catalog]
Title:         Aplicaciones geométricas del cálculo integral
                  á la rectificacion de líneas, cuadratura de superficies y
                  cubatura de sólidos, por el teniente coronel, comandante, D.
                  Antonio Vidal y Rua ...
Published:     Madrid, Impr. del Memorial de ingenieros, 1882.
Description:   viii, 114 p., 1 l. diagrs. on 6 fold. pl. 23 cm.
LC Call No.:   QA311.V5
Subjects:      Calculus, Integral. [from old catalog]
               Curves -- Rectification and quadrature. [from old
                  catalog]
               Surfaces -- Areas and volumes. [from old
                  catalog]
Control No.:   7310751

Author:        Willers, Friedrich Adolf, 1883-1959.
Title:         ... Graphische integration, von dr. Fr. A.
                  Willers ... Mit 53 figuren.
Published:     Berlin und Leipzig, Vereinigung
                  wissenschaftlicher verleger, 1920.
Description:   142 p. diagrs. 16 cm.
Series:        (Sammlung Goschen. [801]).
LC Call No.:   QA311.W5
Notes:         "Literatur": p. 4.
Subjects:      Calculus, Integral.
Control No.:   6381176

Author:        Winston, Clement, 1902-
Title:         On mechanical quadratures formulae involving the
                  classical orthogonal polynomials ... [by] Clement Winston.
Published:     Philadelphia, 1933.
Description:   1 p. l., 658-677 p. 26 cm.
LC Call No.:   QA311.W53 1933
Dewey No.:     517.3
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1933.
               "Reprint from the Annals of mathematics, vol. 35,
                  no. 3."
               Bibliography: p. 677.
Subjects:      Polynomials.
               Interpolation.
               Processes, Infinite.
Other titles:  Mechanical quadratures formulae.
               Orthogonal polynomials.
Control No.:   8296353

Author:        Worpitzky, Julius [Daniel Theodor], 1835- [from
                  old catalog]
Title:         Ueber die endlichkeit von bestimmten integralen
                  und reihensummen ...
Published:     Jena, Druck von W. Ratz, 1867.
Description:   47, [1] p. 22 cm.
LC Call No.:   QA311.W92
Subjects:      Definite integrals.
               Convergence.
Control No.:   5860268

Author:        Zinin, Nikolaæi Nikolaevich, 1854-1910. [from old
                  catalog]
Title:         Razlichnye præiemy priveden¯iëiìa kratnykh
                  integralov.
Published:     1892.
Description:   iii, 222 p. ; 26 cm.
LC Call No.:   QA311.Z56
Notes:         Romanized.
Subjects:      Integrals, Multiple. [from old catalog]
Control No.:   6255019

Author:        Todhunter, I. (Isaac), 1820-1884.
Title:         A history of the progress of the calculus of
                  variations during the nineteenth century. By I. Todhunter
                  ...
Published:     Cambridge, London, Macmillan and co., 1861.
Description:   xii, 532 p. 12 diagr. on 1 fold pl. 23 cm.
LC Call No.:   QA315.T63
Subjects:      Calculus of variations -- History -- 19th
                  century.
Control No.:   272497

Author:        Byerly, William Elwood, b. 1849.
Title:         Introduction to the calculus of variations, by
                  William Byerly ...
Published:     Cambridge, Harvard university press, 1917.
Description:   2 p.l., 48 p., 1 l. diagrs. 22 cm.
Series:        Mathematical tracts for physicists
LC Call No.:   QA315.B9
Subjects:      Calculus of variations.
Control No.:   745776

Author:        Stäckel, Paul, 1862-1919, ed.
Title:         Abhandlungen über variations-rechnung ... Hrsg.
                  von P. Stäckel ...
Published:     Leipzig, W. Engelmann, 1894.
Description:   2 v. diagr. 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 46-47
LC Call No.:   QA315.S77
Notes:         1. th. Bernoulli, Johann. I. Einladung zur
                  lösung eines neuen problems [Problema pure geometricum, Acta
                  eruditorum, 1696] II. Ankündigung (Mechanisch-geometrisches
                  problem über die linie des schnellsten falles, Programm)
                  hrsg. Gröningen, 1697. III. Die krümming eines lichtstrahls
                  in ungleichförmigen medien und die lösung des problems die
                  brachistochrone zu finden [Acta eruditorum, 1697] Bernoulli,
                  Jacob. Lösung der aufgaben meines bruders, dem ich dafür
                  andere vorlege [Acta eruditorum, 1697] Euler, L. Methode
                  curven zu finden, denen eine eigenschaft im höchsten oder
                  geringsten grade zukommt. [Lausanne und Genf, 1744]--2. th.
                  Lagrange, [J.L.] I. Versuch einer neuen methode um die maxima
                  und minima unbestimmter integralformeln zu bestimmen [Miscel.
                  taurinensia, t. II, 1762] II. Ueber die methode der
                  variationen [Miscel. taurinensia, t. IV, 1770] Legendre,
                  [A.M.] Abhandlung über die unterscheidung der maxima und
                  minima in der variations-rechnung [Paris, Mém. Acad. sci.
                  année 1786] Jacobi, C.G.J. Zur theorie der
                  variations-rechnung und der differential-gleichungen.
                  [Crelle's journal, bd. 17, 1837]
Subjects:      Calculus of variations.
Other authors: Bernoulli, Jean, 1667-1748.
               Bernoulli, Jakob, 1654-1705.
               Euler, Leonhard, 1707-1783.
               Lagrange, J. L. (Joseph Louis), 1736-1813.
               Legendre, A. M. (Adrien Marie), 1752-1833.
               Jacobi, C. G. J. (Carl Gustav Jakob), 1804-1851.
Series Entry:  Ostwalds Klassiker der exakten Wissenschaften ;
                  Bd. 46-47.
Control No.:   1217023

Author:        Pascal, Ernesto, b. 1865.
Uniform Title: Calcolo delle variazioni. German
Title:         Die variationsrechnung.
Edition:       Autorisierte deutsche ausgabe von Adolf Schepp
                  ...
Published:     Leipzig, B.G. Teubner, 1899.
Description:   vi, 146 p. 23 cm.
LC Call No.:   QA315.P2
Notes:         "Alphabetisches verzeichniss der im text citirten
                  schriften": p. [137]-145.
Subjects:      Calculus of variations.
Other authors: Schepp, Adolf, b. 1837, ed.
Control No.:   1217362

Author:        Todhunter, I. (Isaac), 1820-1884.
Title:         Researches in the calculus of variations,
                  principally on the theory of discontinuous solutions: an
                  essay to which the Adams prize was awarded in the University
                  of Cambridge in 1871. By I. Todhunter ...
Published:     London, Cambridge, Macmillan and co., 1871.
Description:   viii, 278 p. diagr. 23 cm.
LC Call No.:   QA315.T65
Subjects:      Calculus of variations.
Control No.:   2161043

Author:        Hadamard, Jacques, 1865-1963.
Title:         Leçons sur le calcul des variations professées
                  par J. Hadamard ... recueillies par M. Fréchet. Tome
                  premier. La variation première et les conditions du premier
                  ordre. Les conditions de l'extremum libre.
Published:     Paris, A. Hermann et fils, 1910.
Description:   2 p.l., [vii]-viii, 520 p. diagrs. 26 cm.
LC Call No.:   QA315.H2
ISBN:          18.00F
Notes:         At head of title: Cours du Collège de France.
               No more published.
Subjects:      Calculus of variations.
Other authors: Fréchet, Maurice, 1878-
Control No.:   2161692

Author:        Wren, Frank Lynwood, 1894-
Title:         A new theory of parametric problems in the
                  calculus of variations ... by Frank Lynwood Wren ...
Published:     [Chicago] 1930.
Description:   iii, [1], 29, [2] p. 24 cm.
LC Call No.:   QA315.W7 1930
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1930.
               Vita.
               Photolithographed.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Also included in "Contributions to the calculus
                  of variations, 1930; theses submitted to the Department of
                  mathematics of the University of Chicago", Chicago, Ill.
                  [1931]
Subjects:      Calculus of variations.
Other titles:  Parametric problems.
Control No.:   2162767

Author:        Carll, Lewis Buffett.
Title:         A treatise on the calculus of variations.
                  Arranged with the purpose of introducing, as well as
                  illustrating, its principles to the reader by means of
                  problems, and designed to present in all important
                  particulars a complete view of the present state of the
                  science. By Lewis Buffett Carll, A.M.
Published:     New York, J. Wiley & sons, 1881.
Description:   xvii, 568 p. 22 cm.
LC Call No.:   QA315.C28
Notes:         Calculus of variations.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Control No.:   3106863

Author:        Hickson, A. O. (Arthur Owen), 1896-
Title:         An application of the calculus of variations to
                  boundary value problems.
Published:     Chicago, 1928.
Description:   iii, 36 l. 29 cm.
LC Call No.:   QA315.H52
Notes:         Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Boundary value problems.
Control No.:   3638015

Author:        Kneser, Adolf, 1862-1930.
Title:         Lehrbuch der variationsrechnung, von Adolf Kneser
                  ...
Edition:       Mit 24 eingedruckten abbildungen.
Published:     Braunschweig, F. Vieweg und sohn, 1900.
Description:   xiv p., 1 l., 311, [1] p., 1 l. diagr. 23 cm.
LC Call No.:   QA315.K7
Notes:         "Literaturverzeichniss": p. [307]-311.
Subjects:      Calculus of variations.
Control No.:   4052146

Author:        Huke, Aline.
Title:         An historical and critical study of the
                  fundamental lemma in the calculus of variations ... by Aline
                  Huke ...
Published:     [Chicago] 1930.
Description:   v, 110 p., 1 l. diagrs. 24 cm.
LC Call No.:   QA315.H8 1930
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1930.
               Vita.
               Photolithographic reproduction of type-written
                  copy.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               Appeared also in "Contributions to the calculus
                  of variations, 1930; theses submitted to the Department of
                  mathematics of the University of Chicago."
               Bibliography: p. 95-110.
Subjects:      Calculus of variations.
Control No.:   4526958

Author:        Adler, Claire Fisher, 1895- [from old catalog]
Title:         An isoperimetric problem with an inequality
Published:     [n.p., 1945]
Description:   59-69 p. diagrs. 25 cm.
LC Call No.:   QA315.A2
Subjects:      Calculus of variations. [from old catalog]
Control No.:   5996144

Author:        Euler, Leonhard, 1707-1783.
Title:         Methodus inveniendi lineas curvas maximi minimive
                  proprietate gaudentes, sive Solutio problematis
                  isoperimetrici latissimo sensu accepti. Auctore Leonhardo
                  Eulero.
Published:     Lausannæ, Genevæ, apud Marcum-Michaelem Bousquet
                  & socios, 1744.
Description:   1 p. l., 322 p., 1 l. diagrs. on 5 fold. pl. 25 x
                  19 cm.
LC Call No.:   QA315.E88
Subjects:      Calculus of variations.
Control No.:   6328328

Author:        Bolza, O. (Oskar), 1857-1942.
Title:         Lectures on the calculus of variations; by Oskar
                  Bolza ...
Published:     Chicago, The University of Chicago Press, 1904.
Description:   xv, 271 p. diagrs. 23 cm.
Series:        Chicago. University. The decennial publications.
                  2d series, vol. XIV
LC Call No.:   QA315.B7
Subjects:      Calculus of variations.
Control No.:   6796990

Author:        Duren, William Larkin, 1905-
Title:         The development of sufficient conditions in the
                  calculus of variations ... by William Larkin Duren, jr.
Published:     [Chicago] 1930.
Description:   1 p. l., ii-iv, 99 p. 1 l. diagrs. 24 cm.
LC Call No.:   QA315.D8 1930
Notes:         Thesis (PH. D.)--University of Chicago, 1930.
               Vita.
               Photolithographic reproduction of type-written
                  copy.
               Appeared also in "Contributions to the calculus
                  of variations, 1930; theses submitted to the Department of
                  mathematics of the University of Chicago".
               Bibliography: p. 91-99.
Subjects:      Calculus of variations.
Control No.:   6879652

Author:        Fox, Ralph H. (Ralph Hartzler), 1913-
Title:         On the Lusternik Schnirelmann category ...
Published:     Princeton, 1939 [i.e. 1941]
Description:   1 p.l., 333-370 p. diagrs. 26 cm.
LC Call No.:   QA315.F65
Subjects:      Calculus of variations. [from old catalog]
Other titles:  Lusternik Schnirelmann category.
Control No.:   6912889

Author:        Weinstock, Robert, 1919- [from old catalog]
Title:         Calculus of variations,
Edition:       1st ed
Published:     New York, McGraw-Hill, 1952.
Description:   326 p. illus. 24 cm.
LC Call No.:   QA315.W4
Subjects:      Calculus of variations. [from old catalog]
Control No.:   6964618

Author:        Symposium in Applied Mathematics (8th : 1956 :
                  University of Chicago)
Title:         Calculus of variations and its applications.
                  [Proceedings of the Eighth Symposium in Applied Mathematics
                  of the American Mathematical Society. Cosponsored by the
                  Office of Ordnance Research]
Published:     New York, McGraw-Hill, 1958.
Description:   v, 153 p. diagrs. 26 cm.
Series:        Proceedings of Symposia in Applied Mathematics,
                  v. 8
LC Call No.:   QA315.S9 1956
Dewey No.:     517.4082
Notes:         Includes bibliographies.
Subjects:      Calculus of variations -- Congresses.
Other authors: American Mathematical Society.
               University of Chicago
Series Entry:  Symposia in Applied Mathematics. Proceedings, v.
                  8
Control No.:   7033273

Author:        Pars, L. A.
Title:         An introduction to the calculus of variations.
Published:     New York, Wiley [1962]
Description:   350 p. illus. 24 cm.
LC Call No.:   QA315.P18
Dewey No.:     517.4
Notes:         Includes bibliography.
Subjects:      Calculus of variations.
Control No.:   7039523

Author:        Morse, Marston, 1892-1977.
Title:         The calculus of variations in the large, by
                  Marston Morse.
Published:     New York, The American mathematical society,
                  1934.
Description:   ix, 368 p. 16 cm.
Series:        American Mathematical Society.  Colloquium
                  publications.  Vol. xviii
LC Call No.:   QA315.M6
Dewey No.:     517.4
Notes:         "The research of the writer has been oriented by
                  a conception of what might be termed
                  macro-analysis."--Foreword.
               Bibliography: p. [359]-366.
Subjects:      Calculus of variations.
Control No.:   7358508

Author:        Bliss, Gilbert Ames, 1876-1951.
Title:         Lectures on the calculus of variations, by
                  Gilbert A. Bliss.
Published:     Chicago, Ill., University of Chicago Press
                  [1946]
Description:   ix, 296 p. diagrs. 24 cm.
LC Call No.:   QA315.B53
Dewey No.:     517.4
Notes:         "A bibliography for the problem of Bolza": p.
                  287-291.
Subjects:      Calculus of variations.
Control No.:   7406134

Author:        Miller, Abraham, 1910-
Title:         The isoperimetric problem in three or more
                  dimensions.
Published:     New York, New York University 1949.
Description:   10 p. diagrs. 23 cm.
LC Call No.:   QA315.M5
Notes:         Abridgement of thesis- New York University.
Subjects:      Calculus of variations.
Control No.:   7425248

Author:        Abbatt, Richard. [from old catalog]
Title:         A treatise on the calculus of variations. By
                  Richard Abbatt, F.R.A.S., &c.
Published:     London, J. Richardson, 1836.
Description:   xi, 207 p. diagrs. on fold. pl. 17 cm.
LC Call No.:   QA315.A12
Subjects:      Calculus of variations. [from old catalog]
Control No.:   7731240

Author:        University of Chicago. Dept. of Mathematics.
Title:         Contributions to the calculus of variations,
                  1930-      theses submitted to the Department of Mathematics
                  of the University of Chicago.
Published:     Chicago, Ill., The University of Chicago Press
                  [1931-
Description:   v. diagrs. 25 cm.
LC Call No.:   QA315.C5
Notes:         Photolithographed.
               Each thesis has special t.-p. and separate paging
                  and is also issued separately.
               PREMARC/SERLOC merged record
Subjects:      Calculus of variations.
               Dissertations, Academic -- United States.
Control No.:   7814239

Author:        Raab, Albert William, 1903- [from old catalog]
Title:         Jacobi's condition for multiple integral problems
                  of the calculus of variations.
Published:     Chicago, 1932.
Description:   ii, 26 l. 32 cm.
LC Call No.:   QA315.R2
Subjects:      Calculus of variations. [from old catalog]
Control No.:   7988707

Author:        Bliss, Gilbert Ames, 1876-1951.
Title:         Calculus of variations, by Gilbert Ames Bliss.
Published:     Chicago, Ill., Pub. for the Mathematical
                  Association of America by the Open Court Publishing Company
                  [c1925]
Description:   xiii, 189 p. diagrs. 20 cm.
Series:        The Carus mathematical monographs
LC Call No.:   QA315.B5
Notes:         "A list of references": p. 180-181.
Subjects:      Calculus of variations.
Control No.:   8264528

Author:        Bolza, O. (Oskar), 1857-1942.
Title:         Vorlesungen über variationsrechnung von dr.
                  Oskar Bolza ...  Umgearb. und stark verm. deutsche Ausg. der
                  "Lectures on the calculus of variations" desselben
                  verfassers. Mit 117 figuren im text.
Published:     Leipzig, Berlin, B. G. Teubner, 1909.
Description:   ix, 705, [1], 10 p. diagrs. 24 cm.
LC Call No.:   QA315.B75
Notes:         Issued in 3 parts, 1908-09.
Subjects:      Calculus of variations.
Control No.:   9627441

Author:        Boyce, Moffatt Grier, 1900-1975.
Title:         An envelope theorem and necessary conditions for
                  a problem of Mayer with variable end points ... by Moffatt
                  Grier Boyce.
Published:     [Chicago s.n.] 1930.
Description:   2 p. l., 39 p., 1 l. diagrs. 24 cm.
LC Call No.:   QA315.B8 1930
Notes:         Thesis (PH. D.)--University of Chicago, 1930.
               Vita.
               Photolithographic reproduction of type-written
                  copy.
               Appeared also in "Contributions to the calculus
                  of variations, 1930; theses submitted to the Department of
                  mathematics of the University of Chicago."
Subjects:      Calculus of variations.
Control No.:   9689849

Author:        Powell James Ellis, 1903- [from old catalog]
Title:         Edge conditions for multiple integrals in the
                  calculus variations.
Published:     Chicago, 1931.
Description:   iii, 60 l. 29 cm.
LC Call No.:   QA315.P6
Subjects:      Calculus of variations. [from old catalog]
Control No.:   9861945

Author:        McShane, E. J. (Edward James), 1904-
Title:         Semi-continuity in the calculus of variations,
                  and absolute minima for isoperimetric problems by Edward
                  James McShane.
Published:     [Chicago] 1930.
Description:   2 p. l., 45 p., 1 l. 24 cm.
LC Call No.:   QA315.M3 1930
Notes:         Thesis (PH. D.)--University of Chicago, 1930.
               Vita.
               Photolithographic reproduction of type-written
                  copy.
               Appeared also in "Contributions to the calculus
                  of variations, 1930; theses submitted to the Department of
                  mathematics of the University of Chicago."
Subjects:      Calculus of variations.
Control No.:   10158163

Author:        Tonelli, Leonida, 1885-
Title:         Fondamenti di calcolo delle variazioni.
Published:     Bologna, N. Zanichelli [1921-23]
Description:   2 v. diagrs. 24 cm.
LC Call No.:   QA315.T7
Subjects:      Calculus of variations.
Control No.:   13163883

Author:        Cope, Thomas Freeman, 1900-
Title:         An analogue of Jacobi's condition for the problem
                  of Mayer with variable endpoints.
Published:     1927.
Description:   ii, 36 l. 29 cm.
LC Call No.:   QA316.C58
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Maxima and minima.
               Boundary value problems.
Control No.:   379682

Author:        Wilson, Norman Richard.
Title:         A certain type of isoperimetric problem, in
                  particular, the solid of maximum attraction ...
Published:     [Chicago? 1907]
Description:   1 p.l., 39-84 p., 1 l. diagrs. 24 cm.
LC Call No.:   QA316.W6
Notes:         Thesis (PH. D.)--University of Chicago.
               Vita.
               From Proceedings and transactions of the Royal
                  society of Canada, 3d ser., vol. 1.
Subjects:      Calculus of variations.
Control No.:   745320

Author:        Bardell, Ross Harvey, 1903-
Title:         The inequalities of Morse for a parametric
                  problem of the calculus of variations ... by Ross Harvey
                  Bardell ...
Published:     [Chicago, 1937]
Description:   2 p.l., 32 p. 2 diagr. 24 cm.
LC Call No.:   QA316.B3 1936
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1936.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
               Bibliography: p. 32.
Subjects:      Calculus of variations.
Control No.:   746912

Author:        Wiggin, Evelyn Prescott, 1900-
Title:         A boundary value problem of the calculus of
                  variations ... by Evelyn Prescott Wiggin ...
Published:     [Chicago, 1937]
Description:   2 p.l., 29 p. 24 cm.
LC Call No.:   QA316.W57 1936
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1936.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
               Bibliography: p. 28-29.
Subjects:      Calculus of variations.
Control No.:   746914

Author:        Goldstine, Herman Heine, 1913-
Title:         Conditions for a minimum of a functional ... by
                  Herman Heine Goldstine ...
Published:     [Chicago] 1937.
Description:   2 p.l., 41 p. 24 cm.
LC Call No.:   QA316.G7 1936
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1936.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
               Bibliographical foot-notes.
Subjects:      Calculus of variations.
Control No.:   1219115

Author:        Eshleman, Joel David, 1887-
Title:         The Lagrange problem in parametric form in the
                  calculus of variations.
Published:     1922.
Description:   56 l. 29 cm.
LC Call No.:   QA316.E85
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
Subjects:      Calculus of variations.
               Lagrange problem.
Control No.:   1747262

Author:        Hu, K°un-shêng, 1901-1958.
Title:         The problem of Bolza and its accessory boundary
                  value problem, by Kuen-sen Hu.
Published:     1931.
Description:   ii, 79 l. 32 cm.
LC Call No.:   QA316.H8
Dewey No.:     515/.64 19
Notes:         Typescript (carbon copy)
               Thesis-University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Boundary value problems.
               Bolza, O. (Oskar), 1857-1942.
Control No.:   1855727

Author:        Mancill, Julian Dossy, 1904-
Title:         The minimum of a definite integral with respect
                  to unilateral variations ... by Julian Dossy Mancill ...
Published:     [Chicago, 1937]
Description:   2 p.l., 76 p. diagrs. 24 cm.
LC Call No.:   QA316.M33 1934
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1934.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
Subjects:      Calculus of variations.
Control No.:   2163180

Author:        Davis, David Roy.
Title:         The inverse problem of the calculus of variations
                  in higher space.
Published:     1927.
Description:   31 l. 29 cm.
LC Call No.:   QA316.D3
Dewey No.:     515/.64
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
Subjects:      Calculus of variations.
               Integrals.
               Inverse problems (Differential equations)
Control No.:   2200821

Author:        Wren, Frank Lynwood, 1894-
Title:         A new theory of parametric problems in the
                  calculus of variations.
Published:     Chicago, Distributed by the University of Chicago
                  Libraries, 1930.
Description:   iii, 29 p. 25 cm.
LC Call No.:   QA316.W74
Dewey No.:     515/.64
Notes:         At head of title: The University of Chicago.
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
Control No.:   2200883

Author:        White, Marion Ballantyne.
Title:         The dependence of focal points upon curvature for
                  problems of the calculus of variations in space ... by Marion
                  Ballantyne White.
Published:     Lancaster, Pa., The New era printing company,
                  1912.
Description:   1 p.l., 175-198 p., 1 l. diagrs. 28 cm.
LC Call No.:   QA316.W5
Notes:         Thesis (PH. D.)--University of Chicago, 1910.
               From the Transactions of The American mathematics
                  society, v. 13, 1912.
Subjects:      Calculus of variations.
Control No.:   3107556

Author:        Bower, Julia Wells, 1903-
Title:         The problem of Lagrange with finite side
                  conditions ... by Julia Wells Bower ...
Published:     [Chicago, 1937]
Description:   2 p.l., 47 p. diagrs. 24 cm.
LC Call No.:   QA316.B77 1933
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1933.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
               "List of references": p. 47.
Subjects:      Calculus of variations.
Control No.:   3108898

Author:        Denbow, Carl Herbert, 1911-
Title:         A generalized form of the problem of Bolza ... by
                  Carl Herbert Denbow ...
Published:     [Chicago] 1937.
Description:   2 p.l., 32 p. 24 cm.
LC Call No.:   QA316.D4 1937
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1937.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
               Bibliographical foot-notes.
Subjects:      Calculus of variations.
Control No.:   3108900

Author:        Mackie, Ernest Lloyd, 1893-
Title:         The Jacobi condition for a problem of Mayer with
                  variable end points.
Published:     1927.
Description:   30 l. 29 cm.
LC Call No.:   QA316.M32
Notes:         Typescript (carbon copy)
               Thesis--Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
Control No.:   3138483

Author:        Jackson, Rosa Lea.
Title:         The boundary value problem of the second
                  variation for parametric problems in the calculus of
                  variations.
Published:     1928.
Description:   38 l. 29 cm.
LC Call No.:   QA316.J3
Dewey No.:     517/.4
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Boundary value problems.
Control No.:   3158253

Author:        Bolza, O. (Oskar), 1857-1942.
Title:         Concerning the geodesic curvature and the
                  isoperimetric problem on a given surface and proof of the
                  sufficiency of Jacobi's condition for a permanent sign of the
                  second variation in the so-called isoperimetric problems, by
                  Oskar Bolza ...
Published:     Chicago, The University of Chicago press, 1902.
Description:   1 p.l., 8, 7 p. 28 cm.
LC Call No.:   QA316.B7
Notes:         Printed from v. 9 (p. 13-25) of the Decennial
                  publications of the University of Chicago.
Subjects:      Calculus of variations.
               Curves on surfaces.
Control No.:   3579243

Author:        Coral, Max, 1905-
Title:         Euler-Lagrange multiplier rule for double
                  integrals.
Published:     1931.
Description:   ii, 29 l. 29 cm.
LC Call No.:   QA316.C59
Dewey No.:     515/.64
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Multiple integrals.
Control No.:   3618920

Author:        Fischer, Charles Albert, b. 1884.
Title:         A generalization of Volterra's derivative of a
                  function of a curve ... by Charles Albert Fischer ...
Published:     Baltimore, Md., The Lord Baltimore press, 1913.
Description:   1 p.l., p. [369]-394, 1 l. diagr. 28 cm.
LC Call No.:   QA316.F5
Notes:         Thesis (Ph. D.)--University of Chicago, 1912.
               Vita.
               "Reprinted from American journal of mathematics,
                  vol. XXXV, no. 4."
Subjects:      Calculus of variations.
Other titles:  Volterra's derivative of a function of a curve.
Control No.:   4053056

Author:        Smith, David Melville, b. 1884.
Title:         Jacobi's condition for the problem of Lagrange in
                  the calculus of variations ... by David Melville Smith ...
Published:     [Lancaster, Pa., New York, 1916]
Description:   1 p.l., 459-475, [1] p. 28 cm.
LC Call No.:   QA316.S5
Notes:         Thesis (Ph. D.)--University of Chicago, 1916.
               Vita.
               "A private edition distributed by the University
                  of Chicago libraries, 1916."
               "Reprinted from the Transactions of the American
                  mathematical society, volume 17, number 4, October, 1916."
Subjects:      Calculus of variations.
Control No.:   4053219

Author:        Smiley, Malcolm F. (Malcolm Finlay), 1912-
Title:         Discontinuous solutions for the problem of Bolza
                  in parametric form ... by Malcolm Finlay Smiley ...
Published:     [Chicago, 1937]
Description:   2 p.l., 36 p. 24 cm.
LC Call No.:   QA316.S45 1937
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1937.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
               Bibliography: p. 36.
Subjects:      Calculus of variations.
Control No.:   4054311

Author:        Hefner, Ralph Aubrie, 1902-
Title:         The condition of Mayer for discontinuous
                  solutions of the Lagrange problem.
Published:     1931.
Description:   ii, 33 l. 29 cm.
LC Call No.:   QA316.H44
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Lagrange problem.
Control No.:   4073697

Author:        Sanger, R. G. (Ralph Grafton), 1905-
Title:         Functions of lines and the calculus of
                  variations.
Published:     1931.
Description:   iii, 99 l. 29 cm.
LC Call No.:   QA316.S2
Dewey No.:     515/.64
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Bibliography: l. 93-99.
Subjects:      Calculus of variations.
               Functional equations.
Control No.:   4091924

Author:        Stark, Marion Elizabeth, 1894-
Title:         A self-adjoint boundary value problem associated
                  with a problem of the calculus of variations.
Published:     1926.
Description:   22 l. 29 cm.
LC Call No.:   QA316.S67
Notes:         Title on spine: Boundary value problem and a
                  problem of the calculus of variations.
               Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
Subjects:      Calculus of variations.
               Boundary value problems.
Other titles:  Boundary value problem and a problem of the
                  calculus of variations.
Control No.:   4110606

Author:        Hughes, Jewell Constance, 1896-
Title:         A problem of the calculus of variations in which
                  one end-point is variable on a one parameter family of
                  curves.
Published:     Chicago, 1924.
Description:   26 l. illus. 29 cm.
LC Call No.:   QA316.H83
Dewey No.:     515/.64
Notes:         Thesis--University of Chicago.
               Vita.
Subjects:      Calculus of variations.
               Curves.
Control No.:   4179759

Author:        Perlin, Irwin Earl, 1911-
Title:         Sufficient conditions for a minimum in the
                  problem of Lagrange with isoperimetric conditions ... by
                  Irwin Earl Perlin ...
Published:     [Chicago] 1937.
Description:   2 p.l., 31 p. 24 cm.
LC Call No.:   QA316.P4 1935
Dewey No.:     517.4
Notes:         Thesis (PH. D.)--University of Chicago, 1935.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
               Bibliography: p. 31.
Subjects:      Calculus of variations.
Control No.:   4527383

Author:        Downing, Harold Hardesty, 1886-
Title:         Absolute minima for space problems of the
                  calculus of variations in parametric form.
Published:     1929.
Description:   ii, 46 l. illus. 29 cm.
LC Call No.:   QA316.D68
Dewey No.:     515/.64
Notes:         Binder's title: The calculus of variations in
                  parametric form.
               Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Maxima and minima.
               Generalized spaces.
Other titles:  Calculus of variations in parametric form.
Control No.:   4583494

Author:        Kaiser, H. [from old catalog]
Title:         Analytische auflösung der isoperimetrischen
                  aufgabe Steiners für ein polygon auf einer gegebenen
                  abwickelbaren oberfläche bei gegebenen grenzbedingungen ...
Published:     Leipzig, Druck von B. G. Teubner, 1884.
Description:   p. cm.
LC Call No.:   QA316.K13
Subjects:      Calculus of variations. [from old catalog]
Control No.:   5860364

Author:        Carathéodory, Constantin, 1873-1950.
Title:         Ueber die diskontinuirlichen lösungen in der
                  variationsrechnung ...
Published:     Göttingen, Dieterich, 1904.
Description:   3 p. l., 71, [1] p. diagrs. 24 cm.
LC Call No.:   QA316.C2
Notes:         Inaug.-diss.--Göttingen.
               Lebenslauf.
Subjects:      Calculus of variations.
Control No.:   5867483

Author:        Rider, Paul R. (Paul Reece), b. 1888.
Title:         The space problem of the calculus of variations
                  in terms of angle.
Published:     [Baltimore, 1917]
Description:   p. [241]-256. 31 cm.
LC Call No.:   QA316.R5
Subjects:      Calculus of variations.
Control No.:   5905211

Author:        Larew, Gillie Aldah, 1882-
Title:         Necessary conditions in the problem of Mayer in
                  the calculus of variations / by Gillie Aldah Larew.
Published:     [Lancaster, Pa., 1919].
Description:   22 p. : ill. ; 28 cm.
LC Call No.:   QA316.L3
Notes:         Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois, 1919."
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 20, no. 1, January, 1919."
               Thesis (Ph. D.)--University of Chicago, 1916.
Subjects:      Calculus of variations.
Control No.:   5908894

Author:        Ewing, George M. (George McNaught), 1907-
Title:         A contribution to the theory of discontinuous
                  solutions in the calculus of variations, by George M. Ewing.
Published:     Ann Arbor, Mich., Edwards brothers, inc. [1935]
Description:   1 p. l., 33 p., 1 l. diagr. 21 cm.
LC Call No.:   QA316.E9
Notes:         Thesis (PH. D.)--University of Missouri.
               Vita.
               "Photo-lithoprint reproduction of author's
                  manuscript."
               Bibliography: p. 33.
Subjects:      Calculus of variations.
Other titles:  Discontinuous solutions in the calculus of
                  variations.
Control No.:   5958807

Author:        Widder, D. V. (David Vernon), 1898-
Title:         The Laplace transform, by David Vernon Widder.
Published:     Princeton, Princeton University Press; London, H.
                  Milford, Oxford University Press, 1941.
Description:   x, 406 p. 24 cm.
Series:        [Princeton mathematical series ... 6]
LC Call No.:   QA316.W53
Dewey No.:     517.35
Notes:         Bibliography: p. 392-397.
Subjects:      Laplace transformation.
Control No.:   5980720

Author:        Clarke, Elbert Howard, 1887- [from old catalog]
Title:         On the minimum of the sum of a definite integral
                  and a function of a point.
Published:     [n.p.] 1922.
Description:   28 l. 29 cm.
LC Call No.:   QA316.C55
Subjects:      Calculus of variations. [from old catalog]
               Definite integrals.
               Maxima and minima. [from old catalog]
Control No.:   6171563

Author:        Graves, Lawrence Murray, 1896- [from old
                  catalog]
Title:         The derivative as independent function in the
                  calculus of variations.
Published:     [n.p.] 1924.
Description:   31 l. illus. 29 cm.
LC Call No.:   QA316.G8
Subjects:      Calculus of variations. [from old catalog]
Control No.:   6171570

Author:        Lundström, Carl Erik, 1840-1869. [from old
                  catalog]
Title:         Utkast till isoperimetriska problemers
                  fullständiga solution ...
Published:     Upsala, Edquist & Berglund, 1866.
Description:   1 p.l., 108 p., 1 l. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA316.L96
Subjects:      Calculus of variations. [from old catalog]
Control No.:   6328121

Author:        Bobonis, Augusto, 1907-
Title:         Differential systems with boundary conditions
                  involving the characteristic parameter, by Augusto Bobonis.
Published:     [Chicago], The University Press, 1942.
Description:   2 p. l., 37 p. ; 24 cm.
LC Call No.:   QA316.B65
Notes:         Thesis (Ph. D.)--University of Chicago, 1939.
               Lithoprinted.
               "Reprinted from Contributions to the calculus of
                  variations, 1938-1941."
               Vita.
               Bibliography: p. 36.
Subjects:      Calculus of variations.
               Differential equations, Linear.
Control No.:   6448874

Author:        Bobonis, Augusto, 1907-
Title:         Differential systems with boundary conditions
                  involving the characteristic parameter, by Augusto Bobonis.
Published:     [Chicago], The University Press, 1942.
Description:   2 p. l., 37 p. ; 24 cm.
LC Call No.:   QA316.B65
Notes:         Thesis (Ph. D.)--University of Chicago, 1939.
               Lithoprinted.
               "Reprinted from Contributions to the calculus of
                  variations, 1938-1941."
               Vita.
               Bibliography: p. 36.
Subjects:      Calculus of variations.
               Differential equations, Linear.
Control No.:   6448874

Author:        Lundström, C[arl] E[r ] [from old catalog]
Title:         Distinction des maxima et des minima dans un
                  problème isopérimétrique,
Published:     Upsal. E. Berling, imprimeur de l'Université,
                  1869.
Description:   1 p. l., 39 p. 28 cm.
LC Call No.:   QA316.L97
Subjects:      Calculus of variations. [from old catalog]
               Maxima and minima. [from old catalog]
Control No.:   6796323

Author:        Müller, Hermann. [from old catalog]
Title:         Ein Problem der Variations-Rechnung.
Published:     Rostock, C. Boldt's Buchdruckerei, 1875.
Description:   17 p. diagr. 21 cm.
LC Call No.:   QA316.M9
Subjects:      Calculus of variations. [from old catalog]
Control No.:   6797801

Author:        Merrill, Archibald Shepard, 1887- [from old
                  catalog]
Title:         An isoperimetric problem with variable end-points
                  ...
Published:     [Baltimore, 1919]
Description:   [1], [60]-78 p., 1 l. diagrs. 29 cm.
LC Call No.:   QA316.M4
Subjects:      Calculus of variations. [from old catalog]
Control No.:   6844288

Author:        Stokes, Ellen Clayton, 1900- [from old catalog]
Title:         Application of the covariant derivative of Cartan
                  in the calculus of variations ...
Published:     [Chicago] The University of Chicago press, 1942.
Description:   p. cm.
LC Call No.:   QA316.S7
Subjects:      Calculus of variations. [from old catalog]
Control No.:   6917080

Author:        Morrey, Charles Bradfield, 1907-
Title:         Multiple integral problems in the calculus of
                  variations and related topics, by Charles B. Morrey, jr.
Published:     Berkeley, Los Angeles, University of California
                  press,  1943.
Description:   2 p. l., 130 p. 27 cm.
Series:        University of California publications in
                  mathematics. New series, v. 1, no. 1
LC Call No.:   QA1.C3 n. s., v. 1, no. 1
Dewey No.:     517.4
Notes:         Bibliographical foot-notes.
Subjects:      Calculus of variations.
               Integrals, Multiple.
Control No.:   6926343

Author:        Hestenes, Magnus Rudolph, 1906- [from old
                  catalog]
Title:         Sufficient conditions for the general problem of
                  Mayer with variable end-points.
Published:     Chicago, 1932.
Description:   ii, 19 l. 32 cm.
LC Call No.:   QA316.H58
Subjects:      Calculus of variations. [from old catalog]
               Maxima and minima. [from old catalog]
Control No.:   7044469

Author:        Simmons, Harvey Alexander, b. 1894.
Title:         The first and second variations of a double
                  integral for the case of variable limits.
Published:     Chicago, 1925.
Description:   26 l. illus. 29 cm.
LC Call No.:   QA316.S4
Subjects:      Calculus of variations.
               Multiple integrals.
Control No.:   7106186

Author:        Anton, Ludwig, 1862- [from old catalog]
Title:         Geschichte des isoperimetrische problems, eine
                  geschichtliche darstellung der variationsrechnung von
                  Bernouilli bis Lagrange ...
Published:     Dresden, Lehmannsche buchdruckerei, 1888.
Description:   2 p.l., 77 p., 1 l. diagrs. on 2 fold. pl. 21
                  cm.
LC Call No.:   QA316.A63
Subjects:      Calculus of variations. [from old catalog]
Control No.:   7264813

Author:        McFarlan, Lee Horace, 1895- [from old catalog]
Title:         The transformation of the Euler condition in the
                  calculus of variations
Published:     Columbia, 1926.
Description:   p. 3-16. 27 cm.
LC Call No.:   QA316.M3
Subjects:      Calculus of variations. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Other titles:  Euler condition in the calculus of variations.
Control No.:   7334217

Author:        Rawles, Thomas Howard. [from old catalog]
Title:         The invariant integral and the inverse problem in
                  the calculus of variations,
Published:     [New York, 1928]
Description:   1 p.l., p. 765-784 p. 28 cm.
LC Call No.:   QA316.R3 1927
Subjects:      Calculus of variations. [from old catalog]
Control No.:   7343329

Author:        Carson, Albert B. (Albert Bertie), 1908-
Title:         An analogue of Green's theorem for multiple
                  integral problems in the calculus of variations, by Albert B.
                  Carson.
Published:     [Chicago] The University of Chicago Press, 1942.
Description:   2 p. l., 34 p. ; 24 cm.
LC Call No.:   QA316.C25
Notes:         Thesis (Ph. D.)--University of Chicago, 1941.
               Lithoprinted.
               "Reprinted from Contributions to the calculus of
                  variations, 1938-1941".
               Vita.
               Bibliography: p. 32-33.
Subjects:      Calculus of variations.
Other titles:  Green's theorem for multiple integral problems in
                  the calculus of variations.
Control No.:   7385459

Author:        Landers, Mary Virginia (Kenny), 1905- [from old
                  catalog]
Title:         The Hamilton-Jacobi theory for the problems of
                  Bolza and Meyer ...
Published:     [Chicago] The University of Chicago press, 1942.
Description:   2 p.l., 80 p. 24 cm.
LC Call No.:   QA316.L26
Subjects:      Calculus of variations. [from old catalog]
Control No.:   7385592

Author:        Karlin, Meyer, 1913- [from old catalog]
Title:         Characterization of the system of extremals of a
                  variation problem of higher order in the plane,
Published:     [n.p., 1943]
Description:   cover-title 158-189 p. diagrs. 26 cm.
LC Call No.:   QA316.K3
Subjects:      Calculus of variations.
Control No.:   7395047

Author:        Crathorne, A. R. (Arthur Robert), 1873-1946.
Title:         Das räumliche isoperimetrische Problem /
                  vorgelegt von Arthur R. Crathorne.
Published:     Göttingen : W. Fr. Kaestner, 1907.
Description:   59 p. : ill. ; 24 cm.
LC Call No.:   QA316.C8
Notes:         Vita.
               Thesis--Georg-Augusts-Universität, 1907.
Subjects:      Calculus of variations.
Control No.:   7750614

Author:        Valentine, Frederick A. (Frederick Albert), 1911-
                     .
Title:         The problem of Lagrange with differential
                  inequalities as added side conditions, by Frederick Albert
                  Valentine.
Published:     Chicago, [s.n.] 1937.
Description:   ii numb l., 41 p. diagrs. 24 cm.
LC Call No.:   QA316.V3 1937
Notes:         Thesis (Ph. D.)--University of Chicago, 1937.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
Subjects:      Calculus of variations.
Control No.:   7839149

Author:        Hazard, Katharine Elizabeth, 1915-
Title:         Index theorems for the problem of Bolza in the
                  calculus of variations / by Katharine Elizabeth Hazard.
Published:     [Chicago] : University of Chicago, 1942.
Description:   2, 61 p. ; 24 cm.
LC Call No.:   QA316.H35
Dewey No.:     517.4
Notes:         Thesis (Ph. D.)--University of Chicago, 1940.
               "Reprinted from Contributions to the calculus of
                  variations, 1938-1941."
               Vita.
               Bibliography: p. 60.
Subjects:      Calculus of variations.
Control No.:   7853682

Author:        Venske, Oswald Martin, 1867- [from old catalog]
Title:         Behandlung einiger aufgaben der
                  variationsrechlung, welche sich auf raumcurven constanter
                  erster krümmung beziehen ...
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buchdruckerei (W. F. Kaestner.) 1891.
Description:   66 p., 1 l. diagrs. 24 cm.
LC Call No.:   QA316.V46
Subjects:      Calculus of variations. [from old catalog]
               Curves of double curvature. [from old catalog]
Control No.:   8201591

Author:        Wilkins, Jesse Ernest, 1923-
Title:         Multiple integral problems in parametric form in
                  the calculus of variations ... by J. Ernest Wilkins, jr. ...
Published:     [n. p., 1944]
Description:    [1], 312-334 p. 26 cm.
LC Call No.:   QA316.W59
Notes:         Thesis (PH. D.) -- University of Chicago, 1942.
               "Reprinted from Annals of mathematics, vol. 54,
                  no. 2, April, 1944."
               Bibliography: p. 333-334.
Subjects:      Calculus of variations.
               Integrals, Multiple.
Control No.:   8332172

Author:        Putnam, Calvin Richard, 1924- [from old catalog]
Title:         An application of spectral theory to a singular
                  calculus of variations problem.
Published:     Baltimore, 1948.
Description:   p. cm.
LC Call No.:   QA316.P8
Subjects:      Calculus of variations. [from old catalog]
Control No.:   8356444

Author:        La Paz, Lincoln. [from old catalog]
Title:         An inverse problem of the calculus of
                  variations.
Published:     [n. p.] 1928.
Description:   ii, 36 l. 29 cm.
LC Call No.:   QA316.L2
Subjects:      Calculus of variations.
               Inverse problems (Differential equations)
Control No.:   8587509

Author:        Greve, Adolf. [from old catalog]
Title:         Ein problem aus der variations-rechnung ...
Published:     Frankfurt a. M., Druck von Mahlau & Waldschmidt,
                  1875.
Description:   46 p. diagrs. 22 cm.
LC Call No.:   QA316.G83
Subjects:      Calculus of variations. [from old catalog]
Control No.:   8669576

Author:        Grühn, Philipp. [from old catalog]
Title:         Über die criterien der integrabilität der
                  differential-ausdrücke.
Published:     Göttingen, Druck von E. A. Huth, 1865.
Description:   33 p. 22 cm.
LC Call No.:   QA316.G88
Subjects:      Calculus, Integral. [from old catalog]
               Calculus of variations. [from old catalog]
Control No.:   8669618

Author:        Underhill, Anthony Lispenard, 1877-
Title:         Invariants of the function F (x, y, x', y') in
                  the calculus of variations / by Anthony Lispenard Underhill.
Published:     Lancaster, Pa. : Press of the New Era Printing
                  Company, 1908.
Description:   p. 316-338, 4 p. : ill. ; 28 cm.
LC Call No.:   QA316.U6
Notes:         Vita.
               From the Transactions of the American
                  mathematical society, July, 1908.
               Thesis (Ph. D.)--University of Chicago.
Subjects:      Calculus of variations.
Control No.:   8687509

Author:        Brady, Carroll Parker, 1906- [from old catalog]
Title:         The minimum of a function of integrals in the
                  calculus of variations ... by Carroll Parker Brady ....
Published:     [Chicago] The University of Chicago press, 1942.
Description:   2 p.l, 49 p. diagr. 24 cm.
LC Call No.:   QA316.B78
Notes:         Thesis (Ph. D.)--University of Chicago,1938.
               Lithoprinted.
               "Reprinted from Contributions to the calculus of
                  variations, 1938-1941."
               Vita.
               Bibliography: p. 48.
Subjects:      Calculus of variations. [from old catalog]
Control No.:   8790015

Author:        Duncan, Finis Omer, 1878-
Title:         An extension of the theory of envelopes [by]
                  Finis Omer Duncan.
Description:   p. 17-42 27 cm.
LC Call No.:   QA316.M3
Notes:         Without thesis note.
               Thesis (Ph. D.)--University of Missouri.
Subjects:      Envelopes (Geometry)
Control No.:   9207430

Author:        Ader, Olin B.
Title:         An affine invariant of convex regions [by] Olin
                  B. Ader.
Published:     [Durham, N.C., 1938]
Description:   p. 291-299. diagr. 26 cm.
LC Call No.:   QA316.A3 1937
Notes:         Cover title.
               Thesis (Ph. D.)--University of Kentucky.
               "Reprinted from Duke mathematical journal, vol.
                  4, no. 2, June, 1938."
Subjects:      Calculus of variations.
Other titles:  Convex regions.
Control No.:   9246246

Author:        Landers, Aubrey Wilfred, 1906-
Title:         Invariant multiple integrals in the calculus of
                  variations, by Aubrey Wilfred Landers, jr.
Published:     Chicago, The University of Chicago press, 1942.
Description:   2 p. l., 30 p. ; 24 cm.
LC Call No.:   QA316.L25
Notes:         Thesis (Ph. D.)--University of Chicago, 1939.
               Lithoprinted.
               "Reprinted from Contributions to the calculus of
                  variations, 1938-1941.
               Vita.
               Bibliography: p. 29.
Subjects:      Calculus of variations.
               Integrals, Multiple.
Control No.:   9258541

Author:        Light, George H. (George Heyser).
Title:         The dependence of the topography of envelopes of
                  systems of extremals on curvature / by George H. Light.
Published:     Lancaster, Pa. : Press of the New Era Printing
                  Company, 1917.
Description:   32 p. : ill. ; 28 cm.
LC Call No.:   QA316.L6
Notes:         Thesis (Ph. D.)--Yale University, 1916.
Subjects:      Calculus of variations.
Control No.:   9649708

Author:        Levin, Joseph Harmon, 1915- [from old catalog]
Title:         Minima of double integrals with respect to
                  unilateral variations and applications to subharmonic
                  functions ...
Published:     [Chicago] The University of Chicago press, 1942.
Description:   2 p. l. 52 p. 24 cm.
LC Call No.:   QA316.L48
Subjects:      Calculus of variations.
Control No.:   9727137

Author:        Hetz, Wilhelm Arthur, 1878- [from old catalog]
Title:         Ueber partielle differentialgleichungen, die in
                  der variationsrechnung vorkommen ...
Published:     Göttingen, Druck der Univ.-buchdr. von W. F.
                  Kästner, 1903.
Description:   54, [2] p. 29 x 23 cm.
LC Call No.:   QA316.H57
Subjects:      Calculus of variations. [from old catalog]
               Differential equations, Partial. [from old
                  catalog]
Control No.:   10089163

Author:        Cairns, William De Weese. [from old catalog]
Title:         Die anvendung der integralgleichungen auf die
                  zweite variation bei isoperimetrischen,problemen ...
Published:     Göttingen, Univ.-Wuchdr, von K. F.. Raestner,
                  1907.
Description:   2 p.l., 68 p. 24 cm.
LC Call No.:   QA316.C16
Subjects:      Calculus of variations.
Control No.:   10092584

Author:        Householder, Alston Scott, 1904-
Title:         The dependence of a focal point upon curvature in
                  the calculus of variations, by Alston Scott Householder.
Published:     [Chicago] 1937.
Description:   2 p. l., 38 p. 24 cm.
LC Call No.:   QA316.H7 1937
Notes:         Thesis (Ph. D.)--University of Chicago, 1937.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Contributions to the calculus of
                  variations, 1933-37."
Subjects:      Calculus of variations.
               Generalized spaces.
Control No.:   10181254

Author:        Nordhaus, Edward Alfred.
Title:         The problem of Bolza for double integrals in the
                  calculus of variations, by Edward Alfred Nordhaus.
Published:     [Chicago] The University of Chicago Press, 1942.
Description:   2 p. l., 42 p. : diagrs. ; 24 cm.
LC Call No.:   QA316.N6
Notes:         Thesis (Ph. D.)--University of Chicago, 1939.
               Lithoprinted.
               "Reprinted from Contributions to the calculus of
                  variations, 1938-1941".
               Vita.
               Bibliography: p. 41.
Subjects:      Calculus of variations.
               Integrals, Multiple.
Control No.:   10195306

Author:        Johnson, Marie Mathilda, 1898- [from old
                  catalog]
Title:         Tensors of the calculus of variations.
Published:     1928.
Description:   ii, 39 l. 29 cm.
LC Call No.:   QA316.J65
Notes:         Typescript (carbon copy)
               Thesis--Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Calculus of variations.
               Calculus of tensors.
Control No.:   13152379

Author:        Dvived¯i, Durg¯apras¯ada.
Title:         Kòsetramitiòh [microform] /
                  Durg¯apras¯adadvivedenapraòn¯it¯a ; Girij¯apras¯adadvivedena
                  viâseòsaiòh saòmyojy¯anus¯aòmskôrtaòm.
Edition:       Dvit¯iy¯avôrttiòh.
Published:     Lakòsmaònapure : Navalakiâsorayantr¯alaye, 1920-
Description:   v. <1-   > ; 18 cm.
LC Call No.:   QA317
               Microfiche 91/61140
Notes:         In Sanskrit.
               Cover title: The kshetramiti, a Sanskrit treatise
                  on Euclid's elements.
               Master microform held by : DLC
               Microfiche. New Delhi : Library of Congress
                  Office ; Washington, D.C. : Library of Congress
                  Photoduplication Service, 1991-    microfiches <3-   > ; 11 x
                  15 cm.
Subjects:      Geometry, Plane.
               Euclid's Elements.
               Mathematics, Greek.
Other authors: Dvived¯i, Girij¯apras¯ada.
Other titles:  Kshetramiti, a Sanskrit treatise on Euclid's
                  elements.
Control No.:   4392008
