#+STARTUP: showeverything logdone
#+options: num:nil


Title:         A companion to Euclid:
Published:     London, J. W. Parker; [etc., etc.] 1837.
Description:   iv, [5]-88 p. diagr. 18 cm.
LC Call No.:   QA451.C73
Subjects:      Euclid's elements. [from old catalog]
Control No.:   7261253

Author:        Bonnycastle, John, 1750?-1821. [from old
                  catalog]
Title:         Elements of geometry;
Edition:       6th ed.
Published:     London, Printed for J. Richardson [etc.] 1818.
Description:   1 p., 1 l., 431 p. diagrs. 22 cm.
LC Call No.:   QA451.B72
Subjects:      Euclid's elements. [from old catalog]
               Triangle. [from old catalog]
Control No.:   8198317

Author:        Byrne, Oliver.
Title:         The first six books of the elements of Euclid, in
                  which coloured diagrams and symbols are used instead of
                  letters for the greater ease of learners / by Oliver Byrne.
Published:     London : William Pickering, 1847.
Description:   xxix, 268 p. : col. ill. ; 25 cm.
LC Call No.:   QA451.B99
Subjects:      Euclid's Elements.
               Geometry.
Other authors: Rogers, Bruce, 1870-1957, former owner. DLC
Other authors: Pforzheimer Bruce Rogers Collection (Library of
                  Congress) DLC
Control No.:   272545

Author:        Castillon, Frédéric Adolphe Maximilien Gustav
                  de, 1747-1814, [from old catalog] tr.
Title:         Élémens de géométrie;
Published:     Berlin, C. F. Himburg, 1777.
Description:   430 p. fold. pl., diagrs. 18 cm.
LC Call No.:   QA451.C3
Subjects:      Euclid's elements. [from old catalog]
Other authors: Simson, Robert, 1687-1768. [from old catalog]
Control No.:   9213900

Author:        Cooley, W[illiam] D[esborough], d. 1883. [from
                  old catalog]
Title:         Euclid's elements of plane geometry. With
                  explanatory appendix, and supplementary propositions ... By
                  W.D. Cooley, A. B.
Published:     London, Whittaker and co., 1840.
Description:   184 p. diagr. 18 cm.
LC Call No.:   QA451.C77
Subjects:      Euclid's elements. [from old catalog]
Control No.:   9134462
Author:        Cuthbertson, Francis.
Title:         Euclidian geometry / by Francis Cuthbertson.
Published:     London : Macmillan, 1874.
Description:   xvi, 266, 83 p. : ill. ; 18 cm.
LC Call No.:   QA451.C87x 1874
Notes:         Publisher's advertisements: 83 p. at end.
Subjects:      Geometry.
               Euclid's Elements.
Control No.:   1456202

Author:        Edwards, J[oseph] [from old catalog]
Title:         The figures of Euclid; with questions, and a
                  praxis of geometrical exercises. By the Rev. J. Edwards ...
Published:     London, J.W. Parker, 1846.
Description:   104 p. diagr. 18 cm.
LC Call No.:   QA451.E26
Subjects:      Euclid's elements. [from old catalog]
Control No.:   9603183

Author:        Ehrig, G. (Georg), b. 1877.
Title:         Geometrie für Baugewerkenschulen und verwandte
                  technische und gewerbliche Lehranstalten : mit besonderer
                  Berücksichtigung der praktischen Anwendungen / von G.
                  Ehrig.
Edition:       2. verm. und verb. Aufl.
Published:     Leipzig : F. Leineweber, 1906-09.
Description:   2 v. : ill. ; 21 cm.
LC Call No.:   QA451.E37x 1906
Notes:         Cover title: Geometrie für Baugewerkenschulen.
               Includes bibliographical references.
               1. T. Geometrie der Ebene -- 2. T. Geometrie des
                  Raumes.
Subjects:      Geometry, Plane.
               Geometry, Solid.
Control No.:   4291730

Author:        Euclid.
Title:         The contents of the fifth and sixth books of
                  Euclid (with a note on irrational numbers) arranged and
                  explained by M. J. M. Hill...
Edition:       2d ed.
Published:     Cambridge [Eng.] The University Press, 1908.
Description:   xix, [1], 167 p. diagrs. 24 1/2 cm.
LC Call No.:   QA451.H5 1908
Subjects:      Euclid's Elements.
Other authors: Hill, Micaiah John Muller, 1856-1929, ed.
Control No.:   9266504

Author:        Euclid.
Uniform Title: Elements
Title:         Elemens de geometrie,
Published:     A La Haye, Chez P. van Os, 1762.
Description:   4 p. l., [v]-vii p., 1 l., 394 p. diagrs. 27 cm.
LC Call No.:   QA451.K6
Subjects:      Geometry -- Early works to 1800.
Other authors: Koenig, Samuel, 1712-1757.
               Blassière, J. J. (Jean Jacques), 1736-1791.
               Kuypers, A.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   8297950

Author:        Euclid.
Uniform Title: Elements. English
Title:         The Elements of Euclid,
Published:     Glasgow, Printed by R. and A. Foulis, 1756.
Description:   4 p. l., 431 p. diagrs. 26 x 20 cm.
LC Call No.:   QA451.S61
Subjects:      Geometry -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   8198292

Author:        Euclid.
Uniform Title: Elements. English
Title:         The Elements of Euclid for the use of schools and
                  colleges;
Published:     London, Macmillan and co., ltd. 1903.
Description:   2 p. l., [vii]-xvi, 400 p. diagrs. 15 cm.
LC Call No.:   QA451.T63 1903
               Microfilm 15984 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Mathematics, Greek.
               Geometry -- Early works to 1800.
Other authors: Todhunter, I. (Isaac), 1820-1884.
               Simson, Robert, 1687-1768.
Control No.:   9136439

Author:        Euclid.
Uniform Title: Elements. English
Title:         The Elements of Euclid for the use of schools and
                  colleges;
Edition:       New ed.
Published:     London and Cambridge, Macmillan and co., 1867.
Description:   2 p. l., [vii]-xvi, 400 p. diagrs. 16 cm.
LC Call No.:   QA451.T63 1867
Subjects:      Euclid's Elements.
               Mathematics, Greek.
               Geometry -- Early works to 1800.
Other authors: Todhunter, I. (Isaac), 1820-1884.
Control No.:   9267085

Author:        Euclid.
Uniform Title: Elements. Book 1-6. Latin.
Title:         Euclidis Elementorum geometricorum libri sex
                  priores breuiùs demonstrati / A.P. Georgio Fournier è
                  Societate Iesu.
Edition:       Secunda editio correctior.
Published:     Parisiis : Apud Ioannem Henault ..., 1654.
Description:   [10], 302 p. : ill. ; 12 cm. (12mo)
LC Call No.:   QA451.F687 1654
Notes:         Signatures: pi1 ap4s A-2Ap8s/p4s 2Bp6s.
Subjects:      Euclid. Elements.
               Geometry -- Early works to 1800.
               Mathematics, Greek -- Early works to 1800.
Other authors: Fournier, Georges, 1595-1652.
Control No.:   12734613

Author:        Euclid.
Uniform Title: Elements
Title:         Euclidis Elementorum libri XV. breviter
                  demonstrati, opera Is. Barrow.
Published:     Londini, excudebat R. Daniel, impensis G.
                  Nealand, 1659.
Description:   8 p. l., 399 p. diagrs. 14 1/2 cm.
LC Call No.:   QA451.B3
Notes:         "Euclidis Data succincte demonstrata" (with
                  special t.p.): p. [353]-399.
Subjects:      Geometry -- Early works to 1800.
Other authors: Euclid. Data.
               Barrow, Isaac, 1630-1677.
Other titles:  Elementorum libri XV.
Control No.:   9164406

Author:        Euclid.
Uniform Title: Elements. English
Title:         The fifth book of Euclid,
Published:     Oxford and London, J. Parker and co., 1868.
Description:   2 p. l., 37 p. 22 cm.
LC Call No.:   QA451.D6 (Rare bk. Coll.)
Subjects:      Euclid's Elements.
               Ratio and proportion.
Other authors: Dodgson, Charles Lutwidge, 1832-1898.
Control No.:   9277275

Author:        Fine, Henry B. (Henry Burchard), 1858-1928.
Title:         Euclid's elements.
Published:     [Princeton, N.J.] The Princeton press, 1891.
Description:   cover-title, 82 p. 19 cm.
LC Call No.:   QA451.F49
Subjects:      Euclid's elements. [from old catalog]
Control No.:   10071254

Author:        Frankland, William Barrett, 1875-
Title:         The story of Euclid, by W.B. Frankland ... With
                  illustrations.
Published:     London, G. Newnes, limited, 1902.
Description:   176 p. incl. front., illus., ports. 17 cm.
Series:        [Library of useful stories. English ed.]
LC Call No.:   QA451.A1F
Subjects:      Geometry -- History.
               Euclid's elements.
Series Entry:  Library of useful stories (London, England)
Control No.:   1216980

Author:        Hubbell, Horatio. [from old catalog]
Title:         The geometry of Euclid:
Published:     Philadelphia, J. B. Lippincott & co., 1861.
Description:   8, [5]-90 (i. e. 164 p.) diagr. 23 cm.
LC Call No.:   QA451.H87
Subjects:      Euclid's elements. [from old catalog]
Control No.:   6792888

Author:        Ingram, Alexander.
Title:         The elements of Euclid;
Published:     Edinburgh, Oliver and Boyd; [etc., etc.] 1819.
Description:   20, [9]-397, [1] p. diagr. 22 cm.
LC Call No.:   QA451.I54
Subjects:      Euclid. Elements.
               Trigonometry.
Control No.:   9602960

Author:        Isbister, Alexander Kennedy, 1822-1883. [from old
                  catalog]
Title:         The college Euclid:
Published:     London, Longman, Green, Longman, Roberts, &
                  Green, 1865.
Description:   v, 310, xlv p. diagrs. 18 cm.
LC Call No.:   QA451.I7
Control No.:   6892564

Author:        Keith, Thomas, 1759-1824.
Title:         The elements of plane geometry : containing the
                  first six books of Euclid, from the text of Dr. Simson, with
                  notes critical and explanatory : to which are added book VII,
                  including several important propositions which are not in
                  Euclid, and book VIII, consisting of practical geometry,
                  also, book IX, of planes and their interesections, and book
                  X, of the geometry of solids / by Thomas Keith.
Published:     London : Printed for Longman, Hurst, Rees, Orme,
                  and Brown, and the author, 1814.
Description:   xv, 398 p. : ill. ; 21 cm.
LC Call No.:   QA451.K4
Subjects:      Euclid's Elements.
               Geometry.
Other authors: Simson, Robert, 1687-1768.
Control No.:   6372145

Author:        Lardner, Dionysius, 1793-1859. [from old
                  catalog]
Title:         The first six books of the elements of Euclid,
Published:     London, Printed for J. Taylor, 1834.
Description:   16, 332 p. diagr. 22 cm.
LC Call No.:   QA451.L32
Subjects:      Euclid's elements. [from old catalog]
               Geometry, Solid. [from old catalog]
Control No.:   6324750

Author:        M'Curdy, Dennis.
Title:         Euclid's elements; or, Second lessons in
                  geometry,in the order of Simson's and Playfair's editions ...
                  by D. M'Curdy.
Published:     New York, Collins, Brother & Co., 1846.
Description:   138 p. diagr. 18 1/2 cm.
LC Call No.:   QA451.M13
Notes:         Subject entries: Euclid's elements.
Subjects:      Geometry.
Other titles:  Second lessons in geometry.
Control No.:   8666227

Author:        Narrien, John, 1782-1860. [from old catalog]
Title:         Elements of geometry;
Edition:       3d ed.
Published:     London, Longman, Brown, Green, and Longmans,
                  1850.
Description:   xi, 269 p. diagr. 22 cm.
LC Call No.:   QA451.N23
Subjects:      Euclid's elements. [from old catalog]
Control No.:   8198073

Author:        Playfair, John, 1748-1819.
Title:         Elements of geometry;
Edition:       10th ed.
Published:     Edinburgh, Bell & Bradfute; [etc., etc.] 1846.
Description:   1 p. l., [v]-xv, 306 p. diagrs. 20 cm.
LC Call No.:   QA451.P6 1846
Subjects:      Euclid. Elements.
               Trigonometry.
Other authors: Wallace, William, 1768-1843.
               Kelland, Philip, 1808-1879.
Control No.:   9606510

Author:        Playfair, John, 1748-1819.
Title:         Elements of geometry;
Published:     Edinburgh, Bell & Bradfute; [etc., etc.] 1836.
Description:   1 p. l., [v]-xxiv, [17]-503 p. diagrs. 22 cm.
LC Call No.:   QA451.P6 1836
Subjects:      Euclid. Elements.
               Trigonometry.
Other authors: Wallace, William, 1768-1843.
               Davidsons, John, 1797-1836. [from old catalog]
Control No.:   10074823

Author:        Playfair, John, 1748-1819. [from old catalog]
Title:         Elements of geometry:
Published:     Philadelphia, J. B. Lippincott & co., 1863.
Description:   2 p. l., [5]-317, [1] p. 23 cm.
LC Call No.:   QA451.P6 1863
Subjects:      Euclid's elements. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   7261254

Author:        Playfair, John, 1748-1819. [from old catalog]
Title:         Elements of geometry:
Published:     New York, W. E. Dean [etc.] 1835.
Description:   2 p. l., [vii]-viii, 316 p. 22 cm.
LC Call No.:   QA451.P6 1935
Subjects:      Euclid's elements. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   9134463

Author:        Playfair, John, 1748-1819. [from old catalog]
Title:         Elements of geometry:
Published:     New York: Published by James Eastburn and co. at
                  the Literary rooms, Broadway, G. Long, printer. 1819.
Description:   xvi, [17]-333 p. diagrs. 21 cm.
LC Call No.:   QA451.P6 1819
Subjects:      Euclid's elements. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   10157443

Author:        Potts, Robert, 1805-1885. [from old catalog]
Title:         Euclid's elements of geometry,
Edition:       [The school ed.]
Published:     Cambridge, Printed at the University press;
                  1850.
Description:   vi, [2], 327 p. 19 cm.
LC Call No.:   QA451.P88
Subjects:      Euclid's elements. [from old catalog]
Control No.:   9602961

Author:        Potts, Robert, 1805-1885. [from old catalog]
Title:         Euclid's elements of geometry,
Published:     Cambridge, Printed at the University press;
                  1845.
Description:   vi, [2], xl, 383 p. diagr. 22 cm.
LC Call No.:   QA451.P87
Subjects:      Euclid's elements. [from old catalog]
Control No.:   7729363

Author:        Pryde, James, 1802-1879. [from old catalog]
Title:         Euclid's elements of plane geometry,
Published:     London and Edinburgh, W. and R. Chambers [186-]
Description:   2 p. l., vi, 255 p. diagrs. 18 cm.
LC Call No.:   QA451.P9
Subjects:      Euclid's elements. [from old catalog]
Control No.:   8292256

Author:        Smith, Thomas, D.D.
Title:         Euclid, his life and system, by Thomas Smith ...
Published:     New York, Charles Scribner's sons, 1902.
Description:   vi, 227 p. 19 cm.
Series:        The world's epoch-makers
LC Call No.:   QA451.S55
Subjects:      Euclid's Elements.
               Geometry -- History.
Control No.:   3579280

Author:        Chauvenet, William, 1820-1870. [from old
                  catalog]
Title:         Teachers' edition of Byerly's Chauvenet's
                  geometry,
Published:     Philadelphia, J. B. Lippincott company, 1893.
Description:   [3]-129 p. diagr. 21 cm.
LC Call No.:   QA452.C5 1891a
Subjects:      Geometry. [from old catalog]
Control No.:   10068992

Author:        Vogdes, William, 1802-1886.
Title:         An elementary treatise on mensuration and
                  practical geometry : together with numerous problems of
                  practical importance in mechanics / by William Vogdes.
Published:     Philadelphia : E.C. & J. Biddle, 1846.
Description:   299 p. : ill. ; 20 cm.
LC Call No.:   QA456.V87
Notes:         Spine title: Vogdes' mensuration.
Subjects:      Mensuration.
Other titles:  Vogdes' mensuration.
Control No.:   5857046

Author:        American school, Chicago. [from old catalog]
Title:         Solid geometry ...
Published:     Chicago, [c1906]
Description:   p.
LC Call No.:   QA457.A5
Notes:         For full entry see Main Card Catalog.
Control No.:   8188424

Author:        Atkinson, E. H. de V. (Edwin Henry de Vere), Sir,
                  1867-
Title:         Text-book of practical solid geometry, etc., for
                  the use of the Royal military academy, Woolwich, by Capt.
                  E.H. de V. Atkinson ...
Published:     London, E. & F.N. Spon, ltd.; New York, Spon &
                  Chamberlain, 1899.
Description:   viii, 115 p. XVI fold. pl. (diagrs.) 22 cm.
LC Call No.:   QA457.A75 1899
Subjects:      Geometry, Solid.
Other authors: Royal Military Academy, Woolwich.
Control No.:   1691809

Author:        Avery, Royal A.
Title:         Solid geometry, by Royal A. Avery.
Published:     Boston, Allyn and Bacon [c1928]
Description:   xiv, 186 p. front., illus., plates., diagrs. 20
                  cm.
LC Call No.:   QA457.A8
Subjects:      Geometry, Solid.
Control No.:   9679156

Author:        Avery, Royal A. [from old catalog]
Title:         Solid geometry.
Edition:       Rev.
Published:     Boston, Allyn and Bacon, 1960.
Description:   245 p. illus. 24 cm.
LC Call No.:   QA457.A8 1960
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   7019148

Author:        Avery, Royal A. [from old catalog]
Title:         Solid geometry.
Edition:       [New ed.]
Published:     Boston, Allyn and Bacon, 1951.
Description:   212 p. illus. 20 cm.
LC Call No.:   QA457.A8 1951
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8373481

Author:        Avery, Royal A. [from old catalog]
Title:         Solid geometry,
Published:     Boston, New York [etc.] Allyn and Bacon [c1939]
Description:   xii, [2], 212 p. front., illus., plates, diagrs.
                  20 cm.
LC Call No.:   QA457.A8 1939
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   7377334

Author:        Avery, Royal A. [from old catalog]
Title:         Teacher's manual for solid geometry
Published:     Boston, N.Y., [etc.] [c1930]
Description:   1 v. cm.
LC Call No.:   QA457.A8 Manual
Control No.:   6740927

Author:        Baker, Arthur Latham, 1853-1934.
Title:         The elements of solid geometry : with numerous
                  exercises / by Arthur Latham Baker.
Published:     Boston : Ginn & Company, c1893.
Description:   x, 126 p. : ill. ; 19 cm.
Series:        Ginn's mathematical series
LC Call No.:   QA457.B16
Subjects:      Geometry, Solid.
Series Entry:  Mathematical series (Boston, Mass.)
Control No.:   9134526

Author:        Bartol, William C.
Title:         The elements of solid geometry, by William C.
                  Bartol.
Published:     Boston, New York, Leach, Shewell & Sanborn
                  [c1893]
Description:   vi, 95 p. diagr. 21 cm.
LC Call No.:   QA457.B29
Subjects:      Geometry, Solid.
Control No.:   7729422

Author:        Bartoo, G. C. (Grover Cleveland), 1884-
Title:         Solid geometry, by Grover C. Bartoo and Jesse
                  Osborn.
Published:     St. Louis, Dallas, Webster [c1940]
Description:   ix, 298 p. incl. front., illus., diagrs. 20 cm.
LC Call No.:   QA457.B33
Notes:         "List of good histories of mathematics": p. 292.
Subjects:      Geometry, Solid.
Other authors: Osborn, Jesse Otto, 1894- joint author.
Control No.:   7377562

Author:        Bartoo, Grover Cleveland, 1884- [from old
                  catalog]
Title:         Solid geometry,
Published:     St. Louis, Webster Pub. Co. [1953]
Description:   298 p. illus. 21 cm.
LC Call No.:   QA457.B33 1953
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Osborn, Jesse Otto, 1894- [from old catalog]
                  joint author.
Control No.:   6039697

Author:        Beman, Wooster Woodruff, 1850-1922. [from old
                  catalog]
Title:         Solid geometry, by Wooster Woodruff Beman ... and
                  David Eugene Smith ...
Published:     Boston, Ginn & company, 1900.
Description:   iii, 244-382 p. diagrs. 20 cm.
LC Call No.:   QA457.B45
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Smith, David Eugene, 1860-1944, [from old
                  catalog] joint author.
Control No.:   6784796

Author:        Bernard, David Meade.
Title:         Solid geometry, by D. Meade Bernard ... with the
                  editorial cooperation of Alfred Wilson Phillips ...
Published:     Richmond, Atlanta [etc.] Johnson publishing
                  company [1932]
Description:   iix, p., 1 l., 202 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.B47
Subjects:      Geometry, Solid.
Other authors: Phillips, Alfred Wilson, ed.
Control No.:   7349486

Author:        Betz, William, 1879-
Title:         Solid geometry, by William Betz and Harrison E.
                  Webb with the editorial cooperation of Percey F. Smith.
Published:     Boston, Ginn [c1916]
Description:   xxii, 327-504 p. front., illus., plates, diagrs.
                  20 cm.
LC Call No.:   QA457.B5
Notes:         A sequel to Plane geometry by the same authors.
Subjects:      Geometry, Solid.
Other authors: Webb, Harrison Emmett, 1876- joint author.
               Smith, Percey F. (Percey Franklyn), 1867-1956,
                  ed.
Control No.:   10114628

Author:        Bohnert, Felix, 1862- [from old catalog]
Title:         Elementare stereometrie,
Published:     Leipzig, G. J. Göschen, 1902.
Description:   vii, 183 p. diagrs. 20 cm.
LC Call No.:   QA457.B67
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   9602529

Author:        Brennecke, [Wilhelm] [from old catalog]
Title:         Lehrbuch der stereometrie für den höheren
                  schulunterricht ...
Published:     Berlin, T. C. F. Enslin, 1862.
Description:   1 p.l., ii, 78 p. 16 pl. 23 cm.
LC Call No.:   QA457.B83
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   10071318

Author:        Breslich, Ernst R. (Ernst Rudolph), 1874-
Title:         Solid geometry, by Ernst R. Breslich ...
Published:     Chicago, Ill., The University of Chicago press
                  [c1929]
Description:   xxiv, 157 p. illus., diagrs. 20 cm.
Series:        The University of Chicago mathematical series,
                  E.H. Moore, general editor. The school of education. Texts
                  and manuals, G.W. Myers, editor
LC Call No.:   QA457.B85
Subjects:      Geometry, Solid.
Series Entry:  University of Chicago mathematical series.
               School of Education texts and manuals (University
                  of Chicago)
Control No.:   4526784

Author:        Breslich, Ernst Rudolph, 1874- [from old
                  catalog]
Title:         High school mathematics; solid geometry and
                  related subjects,
Published:     Chicago, New York [etc.] Laidlaw brothers
                  [c1935]
Description:   x, 171 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.B85 1935
Subjects:      Geometry, Solid. [from old catalog]
               Geometry, Plane. [from old catalog]
Control No.:   6907661

Author:        Bützberger, Friedrich. [from old catalog]
Title:         Lehrbuch der stereometrie,
Edition:       3. aufl.
Published:     Zürich, Orell Füssli, 1916.
Description:   1 p.l., [v]-viii, 119 p. diagrs. 21 cm.
LC Call No.:   QA457.B9
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8710530

Author:        Clark, John Roscoe, 1887-
Title:         Modern solid geometry, by John R. Clark and
                  Arthur S. Otis.
Published:     Yonkers-on-Hudson, N.Y., and Chicago, Ill., World
                  book company [c1928]
Description:   xix, 323-461 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.C5
Subjects:      Geometry, Solid.
Other authors: Otis, Arthur Sinton, 1886-1963, joint author.
Control No.:   6866815

Author:        Clark, John Roscoe, 1887- [from old catalog]
Title:         Modern solid geometry,
Edition:       Rev. and enl. ed.
Published:     Yonkers-on-Hudson, N.Y. and Chicago, Ill. World
                  book company [c1933]
Description:   vi p., 1 l., 195-249 p. 19 cm.
LC Call No.:   QA457.C52
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Other authors: Otis, Arthur Sinton, 1886- [from old catalog]
                  joint author.
Control No.:   8608959

Author:        Clark, John Roscoe, 1887- [from old catalog]
Title:         Modern solid geometry,
Edition:       Rev. and enl. ed.
Published:     Yonkers-on-Hudson, N.Y. and Chicago, Ill., World
                  book company [c1932]
Description:   xx, 323-494 p. illus.,diagrs. 20 cm.
LC Call No.:   QA457.C5 1932
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Otis, Arthur Sinton, 1886- [from old catalog]
                  joint author.
Control No.:   7818321

Author:        Cowley, Elizabeth Buchanan.
Title:         Solid geometry, by Elizabeth Buchanan Cowley ...
Published:     New York, Newark [etc.] Silver, Burdett and
                  Company [c1934]
Description:   ix, [1], 230 p. incl. front., illus., diagrs. 19
                  cm.
LC Call No.:   QA457.C6
Dewey No.:     513.3
Notes:         "Helpful material for teachers": p. 225-226.
Subjects:      Geometry, Solid.
Control No.:   9699205

Author:        Dupuis, N. F. (Nathan Fellowes), 1836-1917.
Title:         Elements of synthetic solid geometry, by N. F.
                  Dupuis.
Published:     New York, London, Macmillan, 1893.
Description:   xii, 239 p. diagrs. 19 cm.
LC Call No.:   QA457.D94
Subjects:      Geometry, Solid.
Control No.:   9603023

Author:        Durell, Fletcher, 1859-1946.
Title:         New solid geometry,
Published:     New York and Chicago, Charles E. Merrill company
                  [c1932]
Description:   xviii, 319-535 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.D95 1932
Subjects:      Geometry, Solid.
Control No.:   7204479

Author:        Durell, Fletcher, 1859-1946.
Title:         New solid geometry, by Fletcher Durell and E. E.
                  Arnold.
Published:     New York and Chicago, Charles E. Merrill [c1924]
Description:   xviii, 319-511 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.D95 1924
Notes:         Previous editions have title: Solid geometry.
               Continues paging of the author's Plane geometry,
                  1916.
Subjects:      Geometry, Solid.
Other authors: Arnold, E. E. (Elmer Ellsworth), b. 1872, joint
                  author.
Control No.:   10135534

Author:        Durell, Fletcher, 1859-1946.
Title:         New solid geometry, by Fletcher Durell and E. E.
                  Arnold with review and diagnostic tests.
Published:     New York, Charles E. Merrill [c1932]
Description:   xviii, 319-531 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.D95 1932a
Subjects:      Geometry, Solid.
Other authors: Arnold, E. E. (Elmer Ellsworth), b. 1872, joint
                  author.
Control No.:   10159661

Author:        Durell, Fletcher, 1859-1946.
Title:         Solid geometry
Published:     [n.p.] 1905.
Description:   1 v. cm.
LC Call No.:   QA457.D95
Subjects:      Geometry, Solid.
Control No.:   8145329

Author:        Durell, Fletcher, 1859-1946.
Title:         Solid geometry, by Fletcher Durell ... and E.E.
                  Arnold ...
Published:     New York, Chicago, Charles E. Merrill Company
                  [c1917]
Description:   xviii, 311-499 p. diagrs. 20 cm.
LC Call No.:   QA457.D95 1917
Notes:         Continues paging of the authors' Plane geometry,
                  1916.
Subjects:      Geometry, Solid.
Other authors: Arnold, E. E. (Elmer Ellsworth), b. 1872.
Control No.:   5907431

Author:        Ford, Walter Burton, 1874-
Title:         Solid geometry, by Walter Burton Ford ... and
                  Charles Ammerman ... ed. by Earle Raymond Hedrick.
Published:     New York, The Macmillan company, 1913.
Description:   ix, 215-321, xlix p. illus. 19 cm.
LC Call No.:   QA457.F7
Notes:         "This book contains the chapters on solid
                  geometry form the Plane and solid geoemtry by the same
                  authors."--Pref.
               On cover: Solid geometry with a syllabus of Plane
                  geometry.
Subjects:      Geometry, Solid.
Other authors: Ammerman, Charles, 1870- joint author.
               Hedrick, E. R. (Earle Raymond), 1876-1943.
Control No.:   7298639

Author:        Frame, James Sutherland, 1907-
Title:         Solid geometry.
Edition:       1st ed.
Published:     New York, McGraw-Hill Book Co., 1948.
Description:   ix, 339 p. diagrs. 21 cm.
LC Call No.:   QA457.F75
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Control No.:   3582345

Author:        Frost, Percival, 1817-1898. [from old catalog]
Uniform Title: A treatise on solid geometry. [from old catalog]
Title:         Solid geometry.
Edition:       new ed.
Published:     London, Macmillan, 1875-
Description:   1 v. diagrs. 23 cm.
LC Call No.:   QA457.F77
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Wolstenholme, Joseph, 1829-1891. [from old
                  catalog]
Control No.:   6009416

Author:        Glaser, Robert, 1865-
Title:         Stereometrie, von dr. Robert Glaser ...
Edition:       2. umgearb. und verm. aufl., mit 66 figuren.
Published:     Leipzig, G.J. Göschen, 1903.
Description:   1 p.l., [5]-140 p. diagrs. 16 cm.
Series:        Sammlung Göschen. [97]
LC Call No.:   QA457.G54 1903
Subjects:      Geometry, Solid.
               Mensuration.
Control No.:   4053441

Author:        Glaser, Robert, 1865- [from old catalog]
Title:         Stereometrie,
Edition:       3., verb. aufl. Neudruck.
Published:     Berlin und Leipzig, W. de Gruyter & co., 1920.
Description:   139 p. diagrs. 16 cm.
LC Call No.:   QA457.G54 1920
Subjects:      Geometry, Solid. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   8798392

Author:        Glaser, Robert, 1865- [from old catalog]
Title:         Sterometrie,
Published:     Leipzig, G. J. Göschen, 1899.
Description:   126 p. diagrs. 16 cm.
LC Call No.:   QA457.G54
Subjects:      Geometry, Solid. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   8196300

Author:        Good, Warren R. (Warren Randall)
Title:         Solid geometry, by Warren R. Good and Hope H.
                  Chipman.
Published:     Philadelphia, Chicago, J.B. Lippincott company
                  [c1934]
Description:   v, 267-402 p. illus., diagrs. 21 cm.
LC Call No.:   QA457.G6
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Chipman, Hope H. (Hope Howland), joint author.
Control No.:   5951068

Author:        Good, Warren Randall. [from old catalog]
Title:         Solid goemetry,
Published:     Philadephia, Chicago, J. B. Lippincott company
                  [c1935]
Description:   v, 267-402 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.G6 1935
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Chipman, Hope Howland, [from old catalog] joint
                  author.
Control No.:   8767414

Author:        Grund, Francis J[oseph] [from old catalog]
Title:         An elementary treatise on geometry,
Published:     Boston, Carter, Hendee and Babcock; 1831.
Description:   viii, 195, [1] p. diagr. 19 cm.
LC Call No.:   QA457.G88
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   6792946

Author:        Guldberg, Cato Maximilian, 1836-1902.
Title:         Lærebog i stereometri / af C.M. Guldberg.
Edition:       5. udg.
Published:     Christiania : I Kommission hos P.F. Steensballe,
                  1883.
Description:   54 p. : ill. ; 20 cm.
LC Call No.:   QA457.G84x 1883
Notes:         Includes bibliographical references.
Subjects:      Geometry, Solid.
               Mensuration.
Control No.:   2873477

Author:        Haertter, Leonard Daum, 1895- [from old catalog]
Title:         Solid geometry,
Published:     New York, London, The Century co. [c1930]
Description:   ix p., 1 l., p. 331-554. illus., plates, diagrs.
                  20 cm.
LC Call No.:   QA457.H2
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8278625

Author:        Hart, C. A. (Clara Avis), b. 1863.
Title:         Solid geometry / by C.A. Hart and Daniel D.
                  Feldman ; with the editorial cooperation of J.H. Tanner and
                  Virgil Snyder.
Published:     New York : American Book Company, c1912.
Description:   xvi, p. 299-486 : ill. ; 19 cm.
LC Call No.:   QA457.H3
Notes:         Supplements the authors' Plane geometry: c1911.
               Includes index.
Subjects:      Geometry, Solid.
Other authors: Feldman, Daniel D., b. 1872.
               Tanner, J. H. (John Henry), b. 1861.
               Snyder, Virgil, 1869-1950.
               Hart, C. A. (Clara Avis), b. 1863. Plane
                  geometry. 1911.
Control No.:   7294242

Author:        Hart, Walter W. (Walter Wilson), 1879-
Title:         Progressive solid geometry, by Walter W. Hart.
Edition:       2d ed.
Published:     Boston, New York [etc.] D. C. Heath and company
                  [1943]
Description:   ix, [1], 363-596 p. incl. front, illus., diagrs.
                  20 cm.
LC Call No.:   QA457.H32 1943
Dewey No.:     513.8
Notes:         On cover: Wells-Hart mathematics.
Subjects:      Geometry, Solid.
Control No.:   6453900

Author:        Hart, Walter W. (Walter Wilson), 1879-
Title:         Progressive solid geometry, by Walter W. Hart
                  ...
Published:     Boston, New York [etc.] D. C. Heath and company
                  [c1936]
Description:   ix, [1], 363-596 p. incl. front., illus., diagrs.
                  20 cm.
LC Call No.:   QA457.H32
Dewey No.:     513.3
Notes:         On cover: Wells-Hart mathematics.
Subjects:      Geometry, Solid.
Control No.:   7363617

Author:        Hart, Walter W. (Walter Wilson), 1879-
Title:         Solid geometry and spherical trigonometry, by
                  Walter W. Hart ... and William L. Hart ...
Published:     Boston, D. C. Heath and company [1942]
Description:   v, 151-268, lll, 124 p. illus., diagrs. 23 cm.
LC Call No.:   QA457.H325 1942a
Dewey No.:     513.3
Notes:         On cover: With tables.
               "Composed of parts II and III of the authors'
                  Plane trigonometry, solid geometry, and spherical
                  trigonometry." -- p. III, foot-note.
               "Answers to exercises": p. 257-265.
               "Logarithmic and trigonometric tables, compiled
                  by William L. Hart." Boston, New York, [etc.] D. C. Heath and
                  company [c1938]  (ill, 124 p. at end)has special t-p.
               Published also without tables.
Subjects:      Geometry, Solid.
               Spherical trigonometry.
Other authors: Hart, Walter W. (Walter Wilson), 1879- Plane
                  trigonometry, solid  geometry and spherical trigonometry.
               Hart, William Le Roy, 1892- joint author.
Control No.:   6458462

Author:        Hart, Walter Wilson, 1879- [from old catalog]
Title:         Solid geometry
Published:     [Boston] Heath [1952]
Description:   198 p. illus. 21 cm.
LC Call No.:   QA457.H324
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   6500170

Author:        Hart, Walter Wilson, 1879- [from old catalog]
Title:         Solid geometry and spherical trigonometry,
Published:     Boston, D. C. Heath and company [1942]
Description:   v, 15-268 p. illus., diagrs. 23 cm.
LC Call No.:   QA457.H325
Subjects:      Geometry, Solid. [from old catalog]
               Spherical trigonometry.
Other authors: Hart, Walter Wilson, 1879- Plane trigonometry,
                  solid geometry and spherical trigonometry. [from old
                  catalog]
               Hart, William Le Roy, 1892- [from old catalog]
                  joint author.
Control No.:   8791690

Author:        Hassler, J. O. (Jasper Ole), 1884-
Title:         Solid geometry / by J. O. Hassler.
Published:     Chicago ; New York : Lyons & Carnahan, [c1930]
Description:   xii, 131 p. : ill. ; 20 cm.
LC Call No.:   QA457.H33
Subjects:      Geometry, Solid.
Control No.:   9683246

Author:        Hawkes, Herbert E. [from old catalog]
Title:         Solid geometry...
Edition:       Teachers ed.
Published:     [n.p.] [c1924]
Description:   1 v. cm.
LC Call No.:   QA457.H36
Control No.:   10486589

Author:        Hawkes, Herbert E. (Herbert Edwin), 1872-1943.
Title:         Solid geometry, by Herbert E. Hawkes ... William
                  A. Luby ... and Frank C. Touton ...
Edition:       New ed.
Published:     Boston, New York [etc.] Ginn and company [c1932]
Description:   xvi, 216 p. illus. 20 cm.
LC Call No.:   QA457.H35 1932
Subjects:      Geometry, Solid.
Other authors: Luby, William A. (William Arthur), 1872- joint
                  author.
               Touton, Frank C. (Frank Charles), 1880-1936,
                  joint author.
Control No.:   8754243

Author:        Hawkes, Herbert E. (Herbert Edwin), 1872-1943.
Title:         Solid geometry, by Herbert E. Hawkes ... William
                  A. Luby ... and Frank C. Touton ...
Published:     Boston, New York [etc.] Ginn and Company [c1922]
Description:   xv, 303-494 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.H35
Subjects:      Geometry, Solid.
Other authors: Luby, William A. (William Arthur), 1872- joint
                  author.
               Touton, Frank C. (Frank Charles), 1880-1936,
                  joint author.
Control No.:   6383714

Author:        Hobbs, Charles A. (Charles Austin), b. 1857.
Title:         Solid geometry, by Charles A. Hobbs.
Published:     Cambridge, G.H. Kent, 1921.
Description:   1 p. l., xiii-xxvi, 267-458 p. diagrs. 20 cm.
LC Call No.:   QA457.H6
Notes:         Continues the paging of author's Plane geometry.
Subjects:      Geometry, Solid.
Control No.:   8255155

Author:        Howard, John, 1753-1799.
Title:         A treatise on spherical geometry, containing its
                  fundamental properties; the doctrine of its loci; the maxima
                  and minima of spherical lines and areas: with an application
                  of these elements to a variety of problems.
Published:     Newcastle upon Tyne, Printed by E. Walker, 1798.
Description:   xix, 156 p. 7 fold. pl. 21 cm.
LC Call No.:   QA457.H84
Subjects:      Sphere -- Early works to 1800.
Control No.:   6324811

Author:        Kern, Willis Frederick, 1903- [from old catalog]
Title:         Geometry, with military and naval applications
Published:     New York, J. Wiley and sons, inc.; [1943]
Description:   vii, 152 p. illus., diagrs. 21 cm.
LC Call No.:   QA457.K4
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Bland, James R., [from old catalog] joint
                  author.
Control No.:   9733497

Author:        Leighton, Henry Leland Chapman.
Title:         Solid geometry and spherical trigonometry [by]
                  Henry L. C. Leighton.
Published:     New York, D. Van Nostrand, 1943.
Description:   xix, 210 p. diagrs. 24 cm.
LC Call No.:   QA457.L33
Notes:         "A revision and expansion of the author's earlier
                  text [Solid geometry, 1940] (privately lithoprinted)"-Pref.
Subjects:      Geometry, Solid.
               Spherical trigonometry.
Control No.:   6923178

Author:        Leighton, Henry Leland Chapman
Title:         Solid geometry [by] Henry L. C. Leighton.
Published:     New York, D. Van Nostrand, 1944.
Description:   xx, 157 p. diagrs. 24 cm.
LC Call No.:   QA457.L3 1944
Dewey No.:     513.3
Notes:         A revision and expansion of the lithoprinted
                  edition of 1940.  Published also as chapters 1-14 of the
                  author's Solid geometry and spherical trigonometry, 1943.
Subjects:      Geometry, Solid
Control No.:   5991137

Author:        Leighton, Henry Leland Chapman. [from old
                  catalog]
Title:         Solid geometry,
Published:     Exeter, N.H. [Ann Arbor, Mich., Lithoprinted by
                  Edwards brothers, inc.] 1940.
Description:   iii, 108 p. diagrs. 28 x 22 cm.
LC Call No.:   QA457.L3
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   7381313

Author:        Leventhal, Murray Jerome, 1889- [from old
                  catalog]
Title:         Solid gometry, including recent examination
                  questions,
Published:     New York, Globe book company [c1921]
Description:   48 p. 20 cm.
LC Call No.:   QA457.L4
Subjects:      Geometry, Solid -- Examinations, questions, etc.
Control No.:   10128285

Author:        Lyman, Elmer A. (Elmer Adelbert), 1861-
Title:         Solid geometry, by Elmer A. Lyman.
Published:     New York, Cincinnati [etc.] American book company
                  [c1908]
Description:   xvi, 225-336 p. incl. front., diagrs. 19 cm.
LC Call No.:   QA457.L8
Subjects:      Geometry, Solid.
Control No.:   9621891

Author:        Mallory, Virgil Sampson, 1888-1959.
Title:         New solid geometry.
Edition:       Rev. ed. By Virgil S. Mallory.
Published:     Chicago, B.H. Sanborn & co. [1943]
Description:   viii, 302 p. incl. front., illus., diagrs. 20
                  cm.
LC Call No.:   QA457.M34
Dewey No.:     513.3
Notes:         Published in 1930 under title: Stone-Mallory
                  modern solid geometry; in 1937 under title: New solid
                  geometry, by John C. Stone and Virgil S. Mallory.
Subjects:      Geometry, Solid.
Other authors: Stone, John C. (John Charles), 1867-1940.
Control No.:   9733150

Author:        Mallory, Virgil Sampson, 1888-1959.
Title:         Solid geometry, by Virgil S. Mallory and Chauncey
                  W. Oakley.
Published:     Chicago, B. H. Sanborn [1954]
Description:   252 p. illus. 21 cm.
LC Call No.:   QA457.M35
Subjects:      Geometry, Solid.
Other authors: Oakley, Chauncey W., joint author.
Control No.:   10259150

Author:        Mandelbaum, Hugo.
Title:         Solid geometry [by] Hugo Mandelbaum [and] Samuel
                  Conte.
Published:     New York, Ronald Press Co. [c1957]
Description:   261 p. illus. 21 cm.
LC Call No.:   QA457.M37
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Conte, Samuel Daniel, 1917- joint author.
Control No.:   6064480

Author:        McCormack, Joseph Patrick.
Title:         Solid geometry, by Joseph P. McCormack.
Published:     New York, D. Appleton and company [c1931]
Description:   ix p., 1 l., 369-536 p. illus. 20 cm.
LC Call No.:   QA457.M3
Subjects:      Geometry, Solid.
Control No.:   9217799

Author:        McCormack, Joseph Patrick. [from old catalog]
Title:         Solid geometry,
Published:     New York, D. Appleton and company c[1931]
Description:   ix p., 1 l, 369-556 p. illus. 20 cm.
LC Call No.:   QA457.M3 1931a
Control No.:   10018497

Author:        Mirick, Gordon R., (Gordon Richmond)
Title:         Solid geometry and its uses, by Gordon R. Mirick,
                  Marquis J. Newell and George A. Harper; with the cooperation
                  of George Walker Mullins; illustrations by Dorothy Handsaker,
                  Nelson Handsaker and others.
Published:     Evanston, Ill., New York [etc.] Row, Peterson and
                  company [c1929]
Description:   xvi, 285-460 p. front., illus., diagrs. 21 cm.
LC Call No.:   QA457.M5
Notes:         Continues the pagination of the author's Plane
                  geometry and its uses, Evanston, Ill., 1929.
Subjects:      Geometry, Solid.
Other authors: Newell, Marquis J. (Marquis Joseph), joint
                  author.
               Harper, George A. (George Andrew), joint author.
               Mullins, George W. (George Walker), b. 1881,
                  joint author.
Control No.:   5935505

Author:        Mirick, Gordon R., (Gordon Richmond)
Title:         Solid geometry and its uses. Enl. and rev. By
                  Gordon R. Mirick, Marquis J. Newell, George A. Harper, with
                  the cooperation of George Walker Mullins.
Published:     Evanston, Ill., New York [etc.] Row, Peterson and
                  company [c1935]
Description:   xv p., 1 l., 181 p., 1 l., xxi-xxv p. illus.,
                  diagrs. 21 cm.
LC Call No.:   QA457.M5 1935
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Newell, Marquis J. (Marquis Joseph), joint
                  author.
               Harper, George A. (George Andrew), joint author.
               Mullins, George W. (George Walker), b. 1881,
                  joint author.
Control No.:   6894877

Author:        Mohan, Brij, 1908-1990.
Title:         òTh¯osa jy¯amiti. L¯ekhaka Braja M¯ohana.
Published:     Pray¯aga, Hind¯i S¯ahitya Samm¯elana [1945]
Description:   189 p. illus. 18 cm.
LC Call No.:   QA457.M53
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8434093

Author:        Molenbroek, Pieter, 1861- [from old catalog]
Title:         Leerboek der stereometrie,
Edition:       8. druk.
Published:     Groningen [etc.] P. Noordhoff, n.v., 1934.
Description:   iv, 337, [1] p. diagrs. 25 cm.
LC Call No.:   QA457.M55 1934
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Wijdenes, Piet, 1872- [from old catalog] ed.
Control No.:   6892258

Author:        Morgan, Frank Millett, 1886-
Title:         Solid geometry [by] Frank M. Morgan [and] W. E.
                  Breckinridge.
Edition:       Rev. ed.
Published:     Boston, Houghton Mifflin [c1953]
Description:   330 p. illus. 21 cm.
LC Call No.:   QA457.M6 1953
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Breckinridge, William Edwin, 1869- joint author.
Control No.:   7443307

Author:        Morgan, Frank Millett, 1886-
Title:         Solid geometry. [By] Frank M. Morgan [and] W. E.
                  Breckinridge.
Edition:       Rev. ed.
Published:     Boston, Houghton Mifflin [1946]
Description:   viii, 330 p. incl. front., illus., diagrs. 21
                  cm.
LC Call No.:   QA457.M6 1946
Subjects:      Geometry, Solid.
Other authors: Breckinridge, William Edwin, 1869- joint author.
Control No.:   10215132

Author:        Morgan, Frank Millett, 1886-
Title:         Solid geometry [by] Frank M. Morgan [and] W. E.
                  Breckinridge.
Published:     Boston, Houghton Mifflin [c1934]
Description:   vi, [437]-722, viii p. diagrs. 19 cm.
LC Call No.:   QA457.M6
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Breckinridge, William Edwin, 1869- joint author.
Control No.:   10167396

Author:        Morgan, Frank Millett, 1886- [from old catalog]
Title:         Solid Geometry
Edition:       Rev ed.
Published:     Boston, Houghton Mifflin [1957]
Description:   342 p. illus. 21 cm.
LC Call No.:   QA457.M6 1957
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Breckenridge, William Edwin, 1869- [from old
                  catalog] joint author.
Control No.:   8874269

Author:        Nyberg, Joseph A. (Joseph Antonius), 1891-
Title:         Fundamentals of solid geometry / Joseph A.
                  Nyberg.
Published:     New York : American Book Co., 1947.
Description:   vi, [2], 267 p. : col. front., ill., diagrs.
LC Call No.:   QA457.N77
Notes:         Includes index.
Subjects:      Geometry, Solid.
Control No.:   6005145

Author:        Nyberg, Joseph A. (Joseph Antonius), 1891-
Title:         Solid geometry, by Joseph A. Nyberg.
Published:     New York, Cincinnati [etc.] American book company
                  [c1929]
Description:   xxii, 287-456 p. diagrs. 19 cm.
LC Call No.:   QA457.N8
Subjects:      Geometry, Solid.
Control No.:   9211583

Author:        Oriol, René, 1901- [from old catalog]
Title:         Géométrie,
Published:     Paris, Dunod, 1958 [c1957]
Description:   277 p. illus. 22 cm.
LC Call No.:   QA457.O7
Subjects:      Geometry, Solid. [from old catalog]
               Trigonometry. [from old catalog]
Other authors: Bouthenet, J., [from old catalog] joint author.
Control No.:   9818864

Author:        Palmer, Claude Irwin, 1871-1931.
Title:         Solid geometry, by Claude Irwin Palmer and Daniel
                  Pomeroy Taylor. Ed. by George William Myers.
Published:     Chicago, New York, Scott, Foresman and company
                  [1918]
Description:   vi, 273-449 p. diagrs. 19 cm.
LC Call No.:   QA457.P3
Notes:         Paged continuously with the authors' "Plane
                  geometry [1915]"
               "Combination ruler and protractor" in pocket.
Subjects:      Geometry, Solid.
Other authors: Taylor, Daniel Pomeroy.
               Myers, George William, b. 1864.
Control No.:   7779937

Author:        Palmer, Claude Irwin, 1871-1931.
Title:         Solid geometry by Claude Irwin Palmer, Daniel
                  Pomeroy Taylor, Eva Crane Farnum.
Edition:       (Revised)
Published:     Chicago, Atlanta [etc.] Scott, Foresman and
                  company [c1925]
Description:   xxvi, 343-521 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.P3 1925
Notes:         Paged continuously with the author's "Plane
                  geometry, [c1924]"
               Cardboard protractor in pocket.
Subjects:      Geometry, Solid.
Other authors: Taylor, Daniel Pomeroy, joint author.
               Farnum, Eva Crane, joint author.
Control No.:   8265390

Author:        Richardson, Sophia Foster.
Title:         Solid geometry / by Sophia Foster Richardson.
Published:     Boston ; New York : Ginn, [c1914]
Description:   v, 209 p. : ill. ; 20 cm.
LC Call No.:   QA457.R5
Subjects:      Geometry, Solid.
Control No.:   6364394

Author:        Robbins, Edward Rutledge, 1870-1941.
Title:         Robbins's new Solid geometry, by Edward Rutledge
                  Robbins ...
Published:     New York, Cincinnati [etc.] American book company
                  [c1916]
Description:   xviii, 261-458 p. illus., diagrs. 21 cm.
LC Call No.:   QA457.R65
ISBN:          $0.80
Notes:         Continues the paging of, Robbins's new Plane
                  geometry, published 1915.
Subjects:      Geometry, Solid.
Control No.:   1218032

Author:        Robbins, Edward Rutledge, 1870- [from old
                  catalog]
Title:         Solid geometry,
Published:     New York, Cincinnati [etc.] American book company
                  [c1907]
Description:   xv, 251-409 p. diagrs. 21 cm.
LC Call No.:   QA457.R63
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   7744165

Author:        Rohn, Karl Friedrich Wilhelm, 1855-1920. [from
                  old catalog]
Title:         Stereometrie, ein handbuch für studierende und
                  lehrer
Published:     Borna-Leipzig, R. Noske, 1922.
Description:   xvi, 188 p. diagrs. 23 cm.
LC Call No.:   QA457.R7
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8259268

Author:        Ross, William Gordon, b. 1843. [from old
                  catalog]
Title:         A manual of practical solid geometry,
Published:     London, New York [etc.] Cassell & company,
                  limited, 1887.
Description:   64 p. diagrs. 19 cm.
LC Call No.:   QA457.R75
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8345792

Author:        Sanders, Alan.
Title:         Elements of solid geometry; being books VI to IX
                  of "Elements of plane and solid geometry", by Alan Sanders
                  ...
Published:     New York, Cincinnati [etc.] American book company
                  [1903]
Description:   [1], [248]-384 p. diagrs. 19 cm.
LC Call No.:   QA457.S21
Subjects:      Geometry, Solid.
Control No.:   272558

Author:        Schnell, Leroy H.
Title:         Solid geometry, a clear thinking approach, [by]
                  Leroy H. Schnell [and] Mildred G. Crawford.
Published:     New York, McGraw-Hill [1953]
Description:   198 p. illus. 24 cm.
LC Call No.:   QA457.S34
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Crawford, Mildred Gordon, joint author.
Control No.:   7437934

Author:        Scholfield, Nathan. [from old catalog]
Title:         Elements of solid geometry and mensuration:
Published:     New York, Collins brothers & co., 1845.
Description:   148, 20 p. diagr., tab. 22 cm.
LC Call No.:   QA457.S36
Subjects:      Geometry, Solid. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   8666289

Author:        Seymour, F. Eugene (Francis Eugene), b. 1883.
Title:         Solid geometry
Published:     New York Cincinnati [etc.] American book company
                  [c1930]
Description:   viii, 231 p. illus., diagrs. 19 cm.
LC Call No.:   QA457.S4
Subjects:      Geometry, Solid.
Control No.:   6874083

Author:        Seymour, F. Eugene (Francis Eugene), b. 1883.
Title:         Solid geometry [by] F. Eugene Seymour [and] Paul
                  James Smith.
Published:     New York, The Macmillan company, 1943.
Description:   vii, 263 p. illus., diagrs. 22 cm.
LC Call No.:   QA457.S4 1943
Dewey No.:     513.3
Notes:         Revised and enlarged edition of "Solid geometry,
                  by F. Eugene Seymour," published 1930.
Subjects:      Geometry, Solid.
Other authors: Smith, Paul James, joint author.
Control No.:   7858826

Author:        Seymour, F. Eugene (Francis Eugene), b. 1883.
Title:         Solid geometry / F. Eugene Seymour, Paul James
                  Smith.
Edition:       Rev. ed.
Published:     New York : Macmillan Co., 1949.
Description:   vii, 263 p. : ill.
LC Call No.:   QA457.S4 1949
Notes:         Includes index.
Subjects:      Geometry, Solid.
Other authors: Smith, Paul James, joint author.
Control No.:   8824627

Author:        Shute, William George, 1887-
Title:         Solid geometry / William G. Shute, William W.
                  Shirk, George F. Porter.
Published:     New York : American Book Co., 1953.
Description:    280 p. : ill.
LC Call No.:   QA457.S44
Notes:         Includes index.
Subjects:      Geometry, Solid.
Control No.:   10254387

Author:        Shute, William George, 1887- [from old catalog]
Title:         Solid geometry
Published:     New York, American Book Co. [1957]
Description:   vii, 280 p. illus. 23 cm.
LC Call No.:   QA457.S44 1957
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   6063605

Author:        Sigley, Daniel Tell, 1908-
Title:         Solid geometry and mensuration.
Published:     [New York, The Dryden press, 1942]
Description:   ix p., 1 l., 13-163 (i.e. 167) p. incl. tables,
                  diagrs. 21 cm.
Series:        The Dryden press mathematics publications.
                  General editor: E.R. Smith
LC Call No.:   QA457.S48
Dewey No.:     513.3
Notes:         By Daniel T. Sigley and William T. Stratton.
Subjects:      Geometry, Solid.
Other authors: Stratton, William Timothy, 1880- joint author.
Series Entry:  Dryden Press mathematics publications.
Control No.:   1219411

Author:        Sigley, Daniel Tell, 1908-
Title:         Solid geometry [by] Daniel T. Sigley and William
                  T. Stratton.
Edition:       Rev.
Published:     New York, Dryden Press [1956]
Description:   197 p. illus. 22 cm.
LC Call No.:   QA457.S48 1956
Dewey No.:     513.3
Notes:         Previous editions published under title: Solid
                  geometry and mensuration.
Subjects:      Geometry, Solid.
Other authors: Stratton, W. T. (William Timothy), 1880- joint
                  author.
Control No.:   9803959

Author:        Simpson, James Lennard.
Title:         Solid geometry, a brief elementary course for
                  college students.
Published:     New York, Harper [1960]
Description:   97 p. illus. 21 cm.
Series:        Harper's mathematics series
LC Call No.:   QA457.S485
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Control No.:   10298831

Author:        Skolnik, David. [from old catalog]
Title:         Dynamic solid geometry,
Published:     New York, Van Nostrand [1952]
Description:   231 p. illus. 24 cm.
LC Call No.:   QA457.S49
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   6969270

Author:        Slaught, H. E. (Herbert Ellsworth), 1861-1937.
Title:         Solid geometry, with problems and applications.
                  By H. E. Slaught and N. J. Lennes.
Edition:       Rev. ed.
Published:     Boston, New York [etc.] Allyn and Bacon [1919]
Description:   vi p., 1 l., 211 p. front., illus., ports.,
                  diagrs. 20 cm.
LC Call No.:   QA457.S5
Subjects:      Geometry, Solid.
Other authors: Lennes, N. J. (Nels Johann), 1874- joint author.
Control No.:   10123356

Author:        Slaught, H. E. (Herbert Ellsworth), 1861-1937.
Title:         Solid geometry, with problems and applications /
                  by H. E. Slaught and N. J. Lennes.
Published:     Boston : Allyn and Bacon, 1911.
Description:   vi, 190 p. : illus. ; 19 cm.
LC Call No.:   QA457.S5
Subjects:      Geometry, Solid.
Other authors: Lennes, N. J. (Nels Johann), 1874-
Control No.:   7290000

Author:        Smith, David Eugene, 1860-1944.
Title:         Essentials of solid geometry / by David Eugene
                  Smith.
Published:     Boston : Ginn & Co., c1924.
Description:   238 p. : ill. ; 20 cm.
Series:        Wentworth-Smith mathematical series
LC Call No.:   QA457.S58
Subjects:      Geometry, Solid.
Control No.:   10134463

Author:        Smith, David P. (David Pettit), 1897-
Title:         Solid geometry, by David P. Smith, Jr. and
                  Anthony I. Marino; with review and diagnostic tests.
Published:     Columbus, Ohio, C. E. Merrill Co. [1950]
Description:   314 p. illus. 19 cm.
LC Call No.:   QA457.S59
Notes:         "Successor to the famous Durell and Arnold New
                  solid geometry."
Subjects:      Geometry, Solid.
Other authors: Marino, Anthony I., joint author.
               Durell, Fletcher, 1859-1946. Solid geometry.
Control No.:   6021369

Author:        Smith, Eugene Randolph. 1876- [from old catalog]
Title:         Solid geometry developed by the syllabus method,
Published:     New York, Cincinnati [etc.] American book company
                  [c1913]
Description:   xii, 193-403 p. illus., diagrs. 19 cm.
LC Call No.:   QA457.S6
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Metzler, William H. (William Henry), b. 1863.
Control No.:   10106576

Author:        Smith, Rolland R. (Rolland Ryther), 1894-
Title:         Modern-school solid geometry, by Rolland R. Smith
                  and John R. Clark.
Edition:       New ed.
Published:     Yonkers-on-Hudson, N.Y., World Book Co., [1949]
Description:   viii, 256 p. illus. 21 cm.
Series:        Schorling-Clark-Smith modern-school mathematics
                  series
LC Call No.:   QA457.S65 1949
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Clark, John Roscoe, 1887- joint author.
Control No.:   8824797

Author:        Smith, Rolland R. (Rolland Ryther), 1894-
Title:         Modern-school solid geometry, by Rolland R. Smith
                  and John R. Clark.
Published:     Yonkers-on-Hudson, N.Y., World book company
                  [c1939]
Description:   viii, 248 p. incl. front., illus., diagrs. 21
                  cm.
Series:        Schorling-Clark-Smith modern-school mathematics
                  series
LC Call No.:   QA457.S65
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Clark, John Roscoe, 1887- joint author.
Control No.:   10184972

Author:        Smith, Rolland R. (Rolland Ryther), 1894-
Title:         Solid geometry,
Published:     New York, The Macmillan company, 1930.
Description:   vii, 238 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.S67
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Smith, Leland William, [from old catalog] joint
                  author.
Control No.:   7342220

Author:        Smith, Rolland R. (Rolland Ryther), 1894-
Title:         Solid geometry, by Rolland R. Smith and James F.
                  Ulrich.
Published:     Yonkers-on-Hudson, N.Y., World Book Co. [1957]
Description:   266 p. illus. 24 cm.
LC Call No.:   QA457.S67 1957
Subjects:      Geometry, Solid.
Other authors: Ulrich, James F., joint author.
Control No.:   8872675

Author:        Stone, John C. (John Charles), 1867-1940.
Title:         New solid geometry, by John C. Stone and Virgil
                  S. Mallory.
Published:     Chicago, New York [etc.] B.H. Sanborn & co.
                  [c1937]
Description:   x, 447-748 p. incl. front., illus., diagrs. 20
                  cm.
LC Call No.:   QA457.S83 1937
Dewey No.:     513.3
Notes:         Published in 1930 under title: Stone-Mallory
                  modern solid geometry.
Subjects:      Geometry, Solid.
Other authors: Mallory, Virgil Sampson, 1888-1959, joint
                  author.
Control No.:   8771276

Author:        Stone, John C. (John Charles), 1867-1940.
Title:         Solid geometry, by John C. Stone and James F.
                  Millis.
Published:     Chicago, New York [etc.] B. H. Sanborn, 1916.
Description:   vii, 277-450 p. illus. 20 cm.
LC Call No.:   QA457.S8
Subjects:      Geometry, Solid.
Other authors: Millis, James F. (James Franklin), 1875-
Control No.:   10115734

Author:        Stone, John C. (John Charles), 1867-1940.
Title:         Stone-Mallory modern solid geometry, by John C.
                  Stone ... and Virgil S. Mallory.
Published:     Chicago, New York [etc.] B.H. Sanborn & co.,
                  1930.
Description:   vi, 44--748 p. front., illus., pl., diagrs. 20
                  cm.
LC Call No.:   QA457.S83
Subjects:      Geometry, Solid.
Other authors: Mallory, Virgil S., [from old catalog] joint
                  author.
Control No.:   13162112

Author:        Strader, William W. (William Weller)
Title:         Solid geometry ; modern text for schools and
                  colleges, by William W. Strader and Lawrence D. Rhoads ...
Published:     Philadelphia, Chicago [etc.] The John C. Winston
                  company [1945]
Description:   viii, 170, [5] p. incl. col. front., illus.,
                  diagrs. 19 cm.
LC Call No.:   QA457.S85 1945
Subjects:      Geometry, Solid.
Other authors: Rhoads, Lawrence D., joint author.
Control No.:   8806153

Author:        Strader, William Weller. [from old catalog]
Title:         Solid geometry, modern text for schools and
                  colleges,
Published:     Philadelphia, Chicago [etc.] The John C. Winston
                  company [c1929]
Description:   viii, 170, [5] p. incl. col. front., illus., map,
                  diagrs. 19 cm.
LC Call No.:   QA457.S85
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Rhoads, Lawrence D., [from old catalog] joint
                  author.
Control No.:   6405256

Author:        Sykes, Mabel, 1868-
Title:         Solid geometry, by Mabel Sykes and Clarence E.
                  Comstock.
Published:     Chicago, New York, Rand, McNally and company
                  [c1922]
Description:   viii, 218 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.S9
Notes:         "References and topics for mathematics clubs": p.
                  202-207.
Subjects:      Geometry, Solid.
Other authors: Comstock, Clarence E. (Clarence Elmer), 1866-
                  joint author.
Control No.:   8256780

Author:        Sykes, Mabel, 1868-
Title:         Solid geometry / by Mabel Sykes, Clarence E.
                  Comstock, and Charles M. Austin.
Published:     New York ; Chicago : Rand, McNally, [1933]
Description:   x, 309 p. : ill. ; 20 cm.
Series:        Life interest series
LC Call No.:   QA457.S9 1933
Notes:         Scale in pocket mounted on lining-paper.
Subjects:      Geometry, Solid.
Other authors: Comstock, Clarence E. (Clarence Elmer), 1866-
               Austin, Charles M.
Control No.:   7820238

Author:        Thompson, Henry Dallas, 1864-1927.
Title:         Elementary solid geometry and mensuration, by
                  Henry Dallas Thompson ...
Published:     New York, The Macmillan company; [etc., etc.]
                  1896.
Description:   xi, 199 p. diagrs. 20 cm.
LC Call No.:   QA457.T48
Subjects:      Geometry, Solid.
               Mensuration.
Control No.:   272549

Author:        Thompson, H[enry] D[allas] [from old catalog]
Title:         Elementary solid geometry,
Published:     [Princeton, N.J.] Princeton press, 1895.
Description:   58 p. 24 cm.
LC Call No.:   QA457.T47
Subjects:      Geometry, Solid. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   8198143

Author:        United States. Armed forces institute, Madison,
                  Wis. [from old catalog]
Title:         Solid geometry, a self-teaching course. Based on
                  Solid geometry,
Published:     [Madison] Pub. for the United States Armed forces
                  institute by Ginn and company [1944]
Description:   v, [1], 317 p. illus. (incl. map) diagrs. 19 cm.
LC Call No.:   QA457.U6 1944
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Welchons, Alvin M. Solid geometry. [from old
                  catalog]
Control No.:   7867126

Author:        Van Velzer, C. A. (Charles Ambrose), b. 1851.
Title:         Solid geometry; suggestive method,
Published:     Madison, Wis., Tracy, Gibbs & co. c[1895]
Description:   2 p.l., [241]-392 p. 20 cm.
LC Call No.:   QA457.V28
Subjects:      Geometry, Solid.
Control No.:   7261315

Author:        Welchons, A. M. (Alvin M.)
Title:         New solid geometry, by A. M. Welchons and W. R.
                  Krickenberger.
Published:     Boston, Ginn [1955]
Description:   326 p. illus. 22 cm.
LC Call No.:   QA457.W38
Dewey No.:     513.3
Notes:         "Based on the authors' Solid geometry, revised
                  edition."
Subjects:      Geometry, Solid.
Other authors: Krickenberger, William R., joint author.
Control No.:   8393694

Author:        Welchons, A. M. (Alvin M.)
Title:         Solid geometry, by A. M. Welchons and W. R.
                  Krickenberger.
Edition:       Rev. ed.
Published:     Boston, Ginn [1950]
Description:   vii, 300 p. illus. 21 cm.
LC Call No.:   QA457.W4 1950
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Other authors: Krickenberger, William R., joint author.
Control No.:   10241434

Author:        Welchons, A. M. (Alvin M.)
Title:         Solid geometry / by A. M. Welchons and W. R.
                  Krickenberger.
Published:     Boston ; New York : Ginn, [c1936]
Description:   xi, 259 p. : ill. ; 21 cm.
LC Call No.:   QA457.W4 1936
Subjects:      Geometry, Solid.
Other authors: Krickenberger, William R.
Control No.:   5961405

Author:        Welchons, A. M. (Alvin M.)
Title:         Solid geometry, by A. M. Welchons and W. R.
                  Krickenberger.
Published:     Boston, Ginn [c1933]
Description:   xi, 251 p. incl. front., illus., diagrs. 21 cm.
LC Call No.:   QA457.W4
Subjects:      Geometry, Solid.
Other authors: Krickenberger, William R., joint author.
Control No.:   7819403

Author:        Welchons, A. M. (Alvin M.)
Title:         Solid geometry, by A. M. Welchons, W. R.
                  Krickenberger, and Helen R. Pearson.
Published:     Boston, Ginn [1959]
Description:   345 p. illus. 24 cm.
LC Call No.:   QA457.W4 1959
Dewey No.:     513.3
Subjects:      Geometry, Solid.
Control No.:   7482672

Author:        Welchons, Alvin M. [from old catalog]
Title:         Essentials of solid geometry including spherical
                  geometry,
Published:     Boston, Ginn [1959]
Description:   123 p. illus. 23 cm.
LC Call No.:   QA457.W37
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8418200

Author:        Welchons, Alvin M. [from old catalog]
Title:         Solid geometry.
Edition:       Rev. ed.
Published:     Boston, New York [etc.] Ginn and company [1943]
Description:   vii, [1]. 276 p. incl. front., illus., diagrs. 21
                  cm.
LC Call No.:   QA457.W4 1943
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Krickenberger, William R., [from old catalog]
                  joint author.
Control No.:   9732420

Author:        Wells, Webster, 1851-1916.
Title:         The essentials of geometry (solid)
Published:     Boston, D.C. Heath & co., 1899.
Description:   vii, 233-391 p. diagrs. 20 cm.
LC Call No.:   QA457.W45
Subjects:      Geometry, Solid.
Control No.:   10530973

Author:        Wells, Webster, 1851-1916.
Title:         Modern solid geometry, graded course, by Webster
                  Wells and Walter W. Hart.
Published:     Boston, New York, D. C. Heath and company
                  [c1927]
Description:   311-509 p. diagrs. 20 cm.
LC Call No.:   QA457.W462 1927
Notes:         Successor to the authors' Solid geometry,
                  published in 1916.
Subjects:      Geometry, Solid.
Other authors: Hart, Walter W. (Walter Wilson), 1879- joint
                  author.
Control No.:   9207005

Author:        Wells, Webster, 1851-1916.
Title:         New solid geometry / by Webster Wells.
Published:     Boston : D. C. Heath, 1908.
Description:   vii, 175-298 p. : ill. (part col.) ; 18 cm.
LC Call No.:   QA457.W46
Notes:         "In the preparation of this text the author
                  acknowledges joint authorship with Robert L. Short."--Pref.
               Also published in author's New plane and solid
                  geometry.  Boston, 1908.
Subjects:      Geometry, Solid.
Other authors: Short, Robert L. (Robert Louis), b. 1866.
Control No.:   10089702

Author:        Wells, Webster, 1851-1916.
Title:         Solid geometry, by Webster Wells and Walter W.
                  Hart.
Published:     Boston, D.C. Heath [c1916]
Description:   v, 307-477 p. diagrs.
LC Call No.:   QA457.W462
Notes:         "The Solid geometry is designed as a sequel to
                  the authors' Plane geometry."--Pref.
Subjects:      Geometry, Solid.
Other authors: Hart, Walter W. (Walter Wilson), 1879- joint
                  author.
Control No.:   5900193

Author:        Wentworth, G. A. (George Albert), 1835-1906.
Title:         Solid geometry / by G.A. Wentworth.
Edition:       Rev. ed.
Published:     Boston : Ginn and Company, c1899.
Description:   xvii, 251-468 p. : ill. ; 20 cm.
LC Call No.:   QA457.W47
Notes:         Includes index.
Subjects:      Geometry, Solid.
Control No.:   9594498

Author:        Wentworth, George, b. 1868.
Title:         Solid geometry / by George Wentworth and David
                  Eugene Smith.
Published:     Boston : Ginn and Company, c1913.
Description:   xiii, 273-463 p. : ill. ; 20 cm.
Series:        Wentworth-Smith mathematical series
LC Call No.:   QA457.W465
Notes:         Earlier editions by George Albert Wentworth.
               Published also as 2d part of the author's Plane
                  and solid geometry.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Geometry, Solid.
Other authors: Smith, David Eugene, 1860-1944.
               Wentworth, G. A. (George Albert), 1835-1906.
Control No.:   7298043

Author:        Wiegand, August, 1814-1871.
Title:         Lehrbuch der Stereometrie und sphärischen
                  Trigonometrie nebst zahlreichen Übungsaufgaben : für die
                  oberen Klassen höherer Lehranstalten / bearbeitet von August
                  Wiegand.
Edition:       10., verb. Aufl.
Published:     Halle : H.W. Schmidt, 1885.
Description:   viii, 142 p. : ill. ; 23 cm.
Series:        Lehrbuch der Mathematik
LC Call No.:   QA457.W53x 1885
Subjects:      Geometry, Solid.
               Trigonometry.
Series Entry:  Lehrbuch der Mathematik (Halle an der Saale,
                  Germany)

Author:        Wijdenes, Piet, 1872- [from old catalog]
Title:         Beknopte stereometrie.
Edition:       6. druk.
Published:     Groningen, P. Noordhoff, 1954.
Description:   112 p. illus. 22 cm.
LC Call No.:   QA457.W53 1954
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   8887995

Author:        Williams, John H., 1854- [from old catalog]
Title:         Solid geometry,
Published:     Chicago, New York, Lyons & Carnahan [c1916]
Description:   xii, 257-418 p. illus., diagrs. 20 cm.
LC Call No.:   QA457.W55
Subjects:      Geometry, Solid. [from old catalog]
Other authors: Williams, Kenneth Powers, 1887- [from old
                  catalog] joint author.
Control No.:   8241406

Author:        Wilson, J. M. (James Maurice), 1836-1931.
Title:         Solid geometry and conic sections,
Published:     London, Macmillan and co., limited; New York, The
                  Macmillan company, 1903.
Description:   2 p.l., [iii]-vii, 156 p. diagrs. 17 cm.
LC Call No.:   QA457.W58 1903
Subjects:      Geometry, Solid. [from old catalog]
               Conic sections. [from old catalog]
Control No.:   10185240

Author:        Wilson, J. M. (James Maurice), 1836-1931.
Title:         Solid geometry and conic sections,
Published:     London, Macmillan and co., limited; New York, The
                  Macmillan company, 1898.
Description:   vii p., 1 l., 156 p. diagrs. 17 cm.
LC Call No.:   QA457.W58 1898
Subjects:      Geometry, Solid. [from old catalog]
               Conic sections. [from old catalog]
Control No.:   9717165

Author:        Young, John Wesley, 1879-1932.
Title:         Solid geometry / by John W. Young...and Albert J.
                  Schwartz...
Published:     New York : H. Holt, 1925.
Description:    xvi, 275-399 p. : ill. ; 20 cm.
Series:        American mathematical series
LC Call No.:   QA457.Y6
Notes:         Paged continuously with their Plane geometry.
Subjects:      Geometry, Solid.
Other authors: Schwartz, Albert John, 1879- joint author.
Control No.:   9200438

Author:        Zehme, Walther.
Title:         Die Geometrie der Körper : für Gewerbeschulen
                  und zum Selbstunterrichte / von Walther Zehme.
Published:     Iserlohn : Julius Bädeker, 1859.
Description:   x, 118 p., 12 leaves of plates : ill. ; 24 cm.
LC Call No.:   QA457.Z43x 1859
Subjects:      Geometry, Solid.
Control No.:   983738

Title:         College board and Regents questions and answers
                  in geometry,
Published:     New York, N.Y., College entrance publishing
                  company [c1922]
Description:   v, [1], 98 p. diagrs. 17 cm.
LC Call No.:   QA459.C6
Notes:         I, New York (State) University.
Subjects:      Geometry -- Examinations, questions, etc. [from
                  old catalog]
               New York (State) University -- Examinations --
                  Geometry. [from old catalog]
               Universities and colleges -- United States --
                  Examinations -- Geometry. [from old catalog]
Other authors: College entrace examination board. [from old
                  catalog]
Control No.:   10132028

Title:         The geometry problem solver : a complete solution
                  guide to any textbook / staff of Research and Education
                  Association ; M. Fogiel, director ; special chapter reviews
                  by Ernest Woodward.
Published:     Piscataway, N.J. : The Association, c1995.
Description:   xviii, 933 p. : ill. ; 26 cm.
Series:        REA's problem solvers
LC Call No.:   QA459.G367 1995
Dewey No.:     516/.0076 20
ISBN:          0878915109
Notes:         Includes index.
Subjects:      Geometry -- Problems, exercises, etc.
Other authors: Fogiel, M. (Max)
Other authors: Research and Education Association.
Control No.:   4928044

Author:        Aleksandrov, Ivan (Ivan Ivanovich)
Title:         Aufgaben aus der niederen Geometrie : nach
                  Lösungsmethoden geordnet und zu einem Übungsbuche /
                  zusammengestellt von Iwan Alexandroff ; mit einem Vorwort von
                  M. Schuster.
Published:     Leipzig ; Berlin : B.G. Teubner, 1903.
Description:   v, 123 p. : ill. ; 23 cm.
LC Call No.:   QA459.A4315x 1903
Notes:         Translated from French.
               Includes index.
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   1456140

Author:        Amiot, A., d. 1865. [from old catalog]
Title:         Solutions raisonnées des problèmes énoncés
                  dans les éléments de géométrie de M. A. Amiot ...
Edition:       8. éd. rev. et augm.
Published:     Paris, C. Delagrave, 1881.
Description:   vii, 367 p. 25 pl. (diagrs.) 22 cm.
LC Call No.:   QA459.A5
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Desvignes, A. [from old catalog]
Control No.:   7325374

Author:        Andrews, George A. (George Arthur), 1870-
Title:         Composite geometrical figures, by George A.
                  Andrews ...
Published:     Boston, London, Ginn & company, 1896.
Description:   vi, 57 p. 19 cm.
Series:        Mathematical series
LC Call No.:   QA459.A56
Dewey No.:     516 19
Subjects:      Geometry -- Problems, exercises, etc.
Series Entry:  Mathematical series (Boston, Mass.)
Control No.:   3579320

Author:        Bland, Miles, 1786-1868. [from old catalog]
Title:         Geometrical problems deducible from the first six
                  books of Euclid, arranged and solved:
Edition:       3d ed.
Published:     Cambridge, Printed by J. Smith, 1827.
Description:   1 p. l., ii, lii, 377 p. diagr. 22 cm.
LC Call No.:   QA459.B64
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   7729423

Author:        Bökeler, Anton. [from old catalog]
Title:         Mathematische aufgaben aus den reifeprüfungen
                  der gymnasialabitwienten IIt. Aufgoben aus der stereometrie.
Published:     [n.p.] 1904.
Description:   1 v. cm.
LC Call No.:   QA459.B68
Control No.:   9084838

Author:        Boynton, F[rank] D[avid], 1863- [from old
                  catalog]
Title:         Theorems and examples of geometry,
Published:     [Ithaca, N.Y., c1894]
Description:   19 p. 15 cm.
LC Call No.:   QA459.B79
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   10071319

Author:        Campbell, Colin, 1774-1851.
Title:         Lucubrations in various branches of the
                  mathematics.
Published:     Liverpool : [G. Smith, Watts & co. prs.], 1848.
Description:   x, 106, [1] p. ; 23 cm.
LC Call No.:   QA459.C18
Notes:         Preface signed: Colin Campbell.
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   9603024

Author:        Conant, Levi L. (Levi Leonard), 1857-1916.
Title:         Original exercises in plane and solid geometry,
                  by Levi L. Conant ...
Published:     New York, Cincinnati [etc.] American book company
                  [c1905]
Description:   124 p. diagrs. 19 cm.
LC Call No.:   QA459.C74
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   745017

Author:        Do Bell, Howard Adams. [from old catalog]
Title:         A review book in plane geometry; questions and
                  answers, useful information
Published:     Syracuse, N.Y., The C. W. Bardeen co., c1924.
Description:   63, 3 p. diagrs. 18 cm.
LC Call No.:   QA459.D6
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   6858246

Author:        Dressler, Isidore.
Title:         Reviewing plane geometry.
Published:     New York, Amsco School Publications [1950]
Description:   iv, 240, [41] p. diagrs. 17 cm.
LC Call No.:   QA459.D7
Dewey No.:     513.1076
Notes:         "Exminations": [41] p. at end.
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Control No.:   7894960

Author:        Edgett, Grace Lawrence.
Title:         Exercises in geometry / by Grace Lawrence
                  Edgett.
Published:     Boston : D.C. Heath, 1909.
Description:   vi, [2], 81 p. ; 17 cm.
LC Call No.:   QA459.E4
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   10094427

Author:        Elmore, Earle Brown, 1891- [from old catalog]
Title:         Regents original exercises in plane geometry,
                  selected in accordance with the list of propositions adopted
                  by the New York state examinations board,
Published:     Syracuse, N.Y., C. W. Bardeen, 1918.
Description:   1 p.l., 5-84 p. diagrs. 18 cm.
LC Call No.:   QA459.E5
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
               Examinations -- New York (State) -- Questions.
                  [from old catalog]
Control No.:   5906436

Author:        Elmore, Earle Brown, 1891- [from old catalog]
Title:         Regents original exercises in plane geometry,
                  selected in accordance with the list of propositions adopted
                  by the New York state examinations board, with full
                  solutions,
Published:     Syracuse, N.Y., C. W. Bardeen, c1919.
Description:   328 p. diagrs. 19 cm.
LC Call No.:   QA459.E5 1919
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
               Examinations -- New York (State) -- Questions.
                  [from old catalog]
Control No.:   9188672

Author:        Estill, J. G. (Joe Garner), b. 1863.
Title:         Numerical problems in plane geometry with metric
                  and logarithmic tables, by J.G. Estill ...
Published:     New York, London [etc.] Longmans, Green and co.,
                  1897.
Description:   1 p.l., [v]-vii p., 1 l., 144 p. 20 cm.
LC Call No.:   QA459.E81
Notes:         "Questions selected from the entrance examination
                  papers of a number of the leading colleges and scientific
                  schools": p. [50]-101.
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   1217041

Author:        Fabricius, Alma Marie, 1897-
Title:         Plane geometry exercises, organized according to
                  basic figures and concepts, by Alma M. Fabricius and William
                  Hance.
Published:     [New York, Progressive review book company,
                  c1930]
Description:   83 p. diagrs. 20 cm.
LC Call No.:   QA459.F3
Dewey No.:     543.1
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Other authors: Hance, William, 1880-
Control No.:   10150748

Author:        Germino, Eugene, 1911- [from old catalog]
Title:         Review digest of plane geometry.
Edition:       Rev. and enl.
Published:     New York, Republic Book Co., 1949.
Description:   110, [47] p. diagrs. 19 cm.
LC Call No.:   QA459.G4 1949
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   9767003

Author:        Germino, Eugene, 1911- [from old catalog]
Title:         Review digest of plane geometry ...
Published:     New York [1947]
Description:   93 p. diagrs. 18 cm.
LC Call No.:   QA459.G4
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   9752352

Author:        Goff, Robert Remington, b. 1870.
Title:         Drill book in plane geometry
Published:     Boston, The Palmer company [c1937]
Description:   vi p., 1 l., 180 p. diagrs. 20 cm.
LC Call No.:   QA459.G7 1937
Subjects:      Geometry -- Problems, exercises, etc.
Other authors: Weld, Mildred Gardner. [from old catalog]
Control No.:   9241619

Author:        Goff, Robert Remington, b. 1870.
Title:         Drill book in plane geometry, [by] Robert
                  Remington Goff.
Published:     Boston, The Riverdale press, 1916.
Description:   vii, 113 p. diagrs. 19 cm.
LC Call No.:   QA459.G7
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Control No.:   5900890

Author:        Hansen, Lena B. [from old catalog]
Title:         Exercises that make geometry easier,
Published:     [Enid, Okla., Enid events, c1925]
Description:   48 p. 21 cm.
LC Call No.:   QA459.H3
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Smith, Grace, [from old catalog] joint author.
Control No.:   7797045

Author:        Hausle, Eugenie C.
Title:         Manual of plane geometry plus specimen college
                  entrance examinations, by Eugenie C. Hausle and Nathan
                  Silberstein.
Published:     New York, D.H. Perlman co. [c1929]
Description:   67 p. diagrs. 21 cm.
LC Call No.:   QA459.H35
Dewey No.:     513.1
Subjects:      Geometry, Plane -- Examinations, questions, etc.
Other authors: Silberstein, Nathan.
Other authors: College Entrance Examination Board.
Control No.:   9682353

Author:        Heppa, Victor. [from old catalog]
Title:         Mathematics I-for masons.
Published:     New Brunswick, N.J., Vocational Division,
                  Curriculum Laboratory, 1959.
Description:   144, 32 p. illus. 28 cm.
LC Call No.:   QA459.H4
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
               Fractions. [from old catalog]
               Masonry. [from old catalog]
Other authors: New Jersey, Division of Vocational Education.
                  Curriculum Laboratory, New Brunswick. [from old catalog]
Control No.:   8893927

Author:        Hirt, John H. [from old catalog]
Title:         A treatise on some geometrical problems,
Published:     Minneapolis, Minn., Printed by Argus, inc.,
                  1937.
Description:   27 p. diagrs. 19 cm.
LC Call No.:   QA459.H5
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   7371682

Author:        Horblit, Marcus.
Title:         Problems in plane geometry, with solutions, by
                  Marcus Horblit and Kaj L. Nielsen.
Published:     New York, Barnes & Noble, inc. [1947]
Description:   v, 197 p. diagrs. 21 cm.
Series:        College outline series
LC Call No.:   QA459.H64
Dewey No.:     513.1076
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Other authors: Nielsen, Kaj Leo, 1914- joint author.
Control No.:   6943463

Author:        Hurd, George Henry, 1886- [from old catalog]
Title:         Hurdometry; introducing relation as a dimension;
Published:     [Cambridge, Mass., Kendall printing company,
                  inc., 1936-]
Description:   v. diagrs. 24 cm.
LC Call No.:   QA459.H87
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other titles:  Relation as a dimension.
Control No.:   8300601

Author:        Jones, Franklin Turner.
Title:         Solid geometry problems and questions, compiled
                  by Franklin T. Jones.
Edition:       "Third ed."
Published:     Cleveland, O., The University supply and book
                  company [1928]
Description:   2 p. l., 58 p. 19 cm.
LC Call No.:   QA459.J65 1928
Subjects:      Geometry, Solid -- Examinations, questions, etc.
               Universities and colleges -- United States --
                  Examinations -- Geometry, Solid.
Control No.:   8272684

Author:        Jones, Franklin Turner, [from old catalog] comp.
Title:         Problems and questions on plane geometry,
Published:     Cleveland, Ohio, The University supply and book
                  company, 1924.
Description:   iv, 65 p. 19 cm.
LC Call No.:   QA459.J6
Subjects:      Geometry, Plane -- Examinations, questions, etc.
                  [from old catalog]
               Universities and colleges -- United States --
                  Examinations -- Geometry, Plane. [from old catalog]
Control No.:   7324399

Author:        Kasper, Louis, 1891-
Title:         There is fun in geometry.
Published:     New York, Fortuny's [1937]
Description:   135 p. illus. 21 cm.
LC Call No.:   QA459.K3
Dewey No.:     513.9
Subjects:      Geometry, Plane -- Problems, exercises, etc.
               Mathematical recreations.
Other titles:  Fun in geometry.
Control No.:   8308475

Author:        Kasper, Louis, 1891-
Title:         There is fun in geometry.
Published:     New York, Fortuny's [1937]
Description:   135 p. illus. 21 cm.
LC Call No.:   QA459.K3
Dewey No.:     513.9
Subjects:      Geometry, Plane -- Problems, exercises, etc.
               Mathematical recreations.
Other titles:  Fun in geometry.
Control No.:   8308475

Author:        King, W. J. [from old catalog]
Title:         A condensed geometry review with answers,
Published:     Annapolis, Md., C.G. Feldmeyer, 1918.
Description:   35 p. 23 cm.
LC Call No.:   QA459.K5
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   6374584

Author:        Kingsbury, Howard Baker, 1879- [from old
                  catalog]
Title:         Plane geometry workbook
Published:     New York, Milwaukee [etc.] The Bruce publishing
                  company [c1931]
Description:   [80] p. diagrs. 28 cm.
LC Call No.:   QA459.K53
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Other authors: Wallace, Raymond Randall, 1897- [from old
                  catalog] joint author.
Control No.:   9686552

Author:        Lane, Ruth O. [from old catalog]
Title:         Manual of directions for geometry rapid drill
                  cards
Published:     Chicago, Atlanta [etc.] Scott, Foresman and
                  company [c1929]
Description:   64 p. illus., diagrs. 24 cm.
LC Call No.:   QA459.L3
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Knight, Frederic Butterfield, 1891- [from old
                  catalog] joint author.
               Ruch, G. M. (Giles Murrel), 1892-1943, joint
                  author.
Other titles:  Geometry rapid drill cards, Manual of directions
                  for.
Control No.:   8745447

Author:        Lane, Ruth Onetta, 1892- [from old catalog]
Title:         The Lane-Greene unit tests in plane geometry,
Published:     Iowa City, Bureau of educational research and
                  service, state University of Iowa, c1944.
Description:   2 v. diagrs. 28 x 22 cm.
LC Call No.:   QA459.L28
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Other authors: Greene, Harry Andrews, 1889- [from old catalog]
                  joint author.
Other authors: Iowa. University. Bureau of educational research
                  and service. [from old catalog]
Control No.:   10210124

Author:        Le Frémoire, H. Charette de. [from old catalog]
Title:         Théorèmes et problèmes de géométrie
                  élémentaire,
Edition:       2. éd., entièrement rev. et cor.
Published:     Paris, Carilian-Goeury et V. Dalmont, 1852.
Description:   li, [1], 347 p. 14 pl. 22 cm.
LC Call No.:   QA459.L16
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   6324812

Author:        Leighton, Frederick, 1874- comp.
Title:         Selected regents problems in plane geometry,
                  including practically all of the original problems issued to
                  academies and high schools by the Examinations division of
                  the New York state education department during the past ten
                  years. Comp. by Frederick Leighton ...
Published:     Oswego, N.Y., F. Leighton [c1912]
Description:   30 p. 18 cm.
LC Call No.:   QA459.L5
ISBN:          $0.25
Subjects:      Geometry, Plane.
Other authors: University of the State of New York. Examinations
                  Division.
Control No.:   273306

Author:        Leighton, Frederick, 1874- [from old catalog]
Title:         Exercises in plane geometry,
Published:     Oswego, N.Y., F. Leighton [c1920]
Description:   63 p. diagrs. 18 cm.
LC Call No.:   QA459.L4
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   8720312

Author:        Leventhal, Murray Jerome, 1889-
Title:         Exercises in plane geometry, including recent
                  examination questions, by Murray J. Leventhal and Joseph P.
                  McCormack.
Published:     New York, Globe book company [c1922]
Description:   v. 117 p. illus. 20 cm.
Series:        Globe mathematics series
LC Call No.:   QA459.I55
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Other authors: McCormack, Joseph P. (Joseph Patrick)
Control No.:   8256922

Author:        Leventhal, Murray Jerome, 1889-
Title:         Self-teaching geometry, by Murray J. Leventhal.
Published:     New York, N.Y., Globe book company [c1935]
Description:   vii, 131, 4, 16 p. diagrs. 19 cm.
LC Call No.:   QA459.L552
Dewey No.:     513.10761
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Control No.:   6895014

Author:        Loomis, Elisha S. (Elisha Scott), 1852-1940.
Title:         Original investigation; or, How to attack an
                  exercise in geometry; with many model solutions and a
                  complete discussion of the principles underlying the same, by
                  Elisha S. Loomis ...
Published:     Boston, U.S.A., Ginn & company, 1901.
Description:   vi, 63 p. 19 cm.
LC Call No.:   QA459.L86
Notes:         Bibliography: p. 63.
Subjects:      Geometry -- Problems, exercises, etc.
               Geometry -- Study and teaching.
Control No.:   2633803

Author:        Lyman, E[lmer] A[delbert] [from old catalog]
Title:         Exercises in geometry.
Published:     Boston and New York, Leach, Shewell & Sanborn,
                  c1890.
Description:   cover-title, 60 l. 15 x 22 cm.
LC Call No.:   QA459.L98
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   8666290

Author:        Marsh, Charles A., comp.
Title:         College entrance examination papers in plane
                  geometry, comp. by Charles A. Marsh, A. M. [and] Harrie J.
                  Phipps.
Published:     New York, Charles E. Merrill company, 1911.
Description:   178 p. diagrs. 20 cm.
LC Call No.:   QA459.M3
Subjects:      Geometry, Plane -- Examinations, questions, etc.
Other authors: Phipps, Harrie Jean, 1880- joint comp.
Control No.:   5886206

Author:        Mascheroni, Lorenzo, 1750-1800. [from old
                  catalog]
Title:         Problemi di geometria di Lorenzo Mascheroni ...
                  colle dimostrazioni del capitano Sacchi.
Edition:       3. ed., con cinque tavole.
Published:     Milano, G. Silvestri, 1832.
Description:   viii, 198, [2] p. 5 fold. pl. (diagrs.) 17 cm.
LC Call No.:   QA459.M33 1832
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Sacchi, XXX, capitano, fl. 1802. [from old
                  catalog]
Control No.:   8285576

Author:        Mascheroni. Lorenzo, 1750-1800. [from old
                  catalog]
Title:         Problemi per gli agrimensori con varie soluzioni
                  dell'ab.
Published:     Pavia, B. Comino, 1793.
Description:   viii, 76 p., 1 l. iv fold. pl. (diagrs.) 23 cm.
LC Call No.:   QA459.M32
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   8753562


Author:        Mérel, E.
Title:         Pour s'amuser dans la tranchée, to pass time in
                  the trenches ... 16 démonstrations du théorème de
                  Pythagore.
Published:     Paris, Nancy, Berger-Levrault, 1916.
Description:   22 p. diagrs. 20 cm.
LC Call No.:   QA459.M4
Subjects:      Pythagorean theorem.
               Geometry -- Problems, exercises, etc.
Control No.:   6375222

Author:        Mitchell, Robert, 1944-
Title:         Contemporary's number power 4 : geometry / Robert
                  Mitchell and Donald Prickel.
Published:     Lincolnwood, Ill. : Contemporary Books, c2000.
Description:   vi, 202 p. : ill. ; 28 cm.
Series:        Number power series
LC Call No.:   QA459.M58 2000
Dewey No.:     516 21
ISBN:          0809223821 (pbk.)
Notes:         Includes index.
Subjects:      Geometry -- Problems, exercises, etc.
               Geometry -- Study and teaching.
Other authors: Prickel, Donald.
Control No.:   12238163

Author:        Mix, Ebenezer.
Title:         Practical mathematics : for the use of common
                  schools and academies, and for self-instruction / by Ebenezer
                  Mix.
Published:     New York : The Author, 1846.
Description:   322 p. : ill. ; 20 cm.
LC Call No.:   QA459.M68
Notes:         On spine: Practical mathematics.
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   8198144

Author:        Moskowitz, David H. [from old catalog]
Title:         Exercises in geometry, analyzed and graded,
Published:     New York city, Regents publishing company,
                  incorporated [c1928]
Description:   3 p. l., 149 p. diagrs. 17 cm.
LC Call No.:   QA459.M7
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   9677559

Author:        880-01 Muragaki, Sok¯o.
Title:         880-02 Kika reidai : tsuketari kaishiki /Muragaki
                  Sok¯o chojutsu.
Published:     880-03 [Tokyo] : Okamura Sh¯osuke, Meiji 14-17
                  [1881-1884]
Description:   3 v. : ill. ; 13 x 19 cm.
LC Call No.:   QA459.M86 1881
Notes:         Title from title piece mounted on cover.
               On double leaves, oriental style.
               LC set incomplete: v. 3 wanting.
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   5216517

Author:        Myers, George William, 1864- [from old catalog]
Title:         Elementary algebraic geometry,
Published:     Chicago, New York, Scott, Foresman and company
                  [c1921]
Description:   111 p. illus., diagrs. 19 cm.
LC Call No.:   QA459.M88
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   7318439

Author:        Newton, Frederick Edwin, 1870- [from old
                  catalog]
Title:         Exercises in plane geometry, with syllabus and
                  definitions;
Published:     [Andover, Mass.] The authors, 1918.
Description:   86 p. 19 cm.
LC Call No.:   QA459.N4
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Other authors: Lynde, Lester Edward, 1879- [from old catalog]
                  joint author.
Control No.:   8247138

Author:        Norton, Monte Scott.
Title:         Geometric constructions.
Published:     St. Louis, Webster Pub. Co., c1963.
Description:   64 p. illus. 23 cm.
Series:        Exploring mathematics on your own
LC Call No.:   QA459.N6
Dewey No.:     513.9
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   8912585

Author:        Owen, Charles Henry, 1888-
Title:         Drill, original exercises, and problems in plane
                  geometry, by Charles H. Owen.
Published:     Auburn, N.Y., The Fenton press [c1926]
Description:   109 p. diagrs. 19 cm.
LC Call No.:   QA459.O8
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Control No.:   10140321

Author:        Peterson, Julius, 1839-1910. [from old catalog]
Title:         Méthodes et théories pour la résolution des
                  problèmes de constructions géométriques, avec application
                  à plus de 400 problèmes,
Edition:       3. éd.
Published:     Paris, Gauthier-Villars & fils; Copenhague, A. F.
                  Høst & fils, 1901.
Description:   4 p.l., 110 p., 1 l. diagrs. 21 cm.
LC Call No.:   QA459.P48
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Chemin, Octave, 1844- [from old catalog] tr.
Control No.:   9135964

Author:        Peterson, Julius, 1839-1910. [from old catalog]
Title:         Méthodes et théories pour la résolution des
                  problèmes de constructions géométriques, avec application
                  à plus de 400 problèmes,
Published:     Paris, Gauthier-Villars; Copenhague, A. F. Høst &
                  fils, 1880.
Description:   4 p.l., 110 p., 1 l. diagrs. 21 cm.
LC Call No.:   QA459.S38
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Chemin, Octave, 1844- [from old catalog] tr.
Control No.:   5965250

Author:        Pickett, Hale Clifford, 1892-
Title:         An analysis of proofs and solutions of exercises
                  used in plane geometry tests. New York, Bureau of
                  Publications, Teachers College, Columbia University, 1938.
Published:     [New York, AMS Press, 1972]
Description:   120 p. 22 cm.
LC Call No.:   QA459.P53 1972
Dewey No.:     516/.22/076
ISBN:          0404557473
Notes:         Reprint of the 1938 ed., issued in series:
                  Teachers College, Columbia University. Contributions to
                  education, no. 747.
               Originally presented as the author's thesis,
                  Columbia.
               Bibliography: p. 117-120.
Subjects:      Geometry, Plane -- Examinations, questions, etc.
Series Entry:  Columbia University. Teachers College.
                  Contributions to education, no. 747.
Control No.:   4159661

Author:        Prestel, Michael August Friedrich, 1809-1880.
                  [from old catalog]
Title:         Die geometrische heuristik.
Published:     Emden, In commission bei J. Nateboom, 1856.
Description:   32 p., 1 l. diagrs. on pl. 29 cm.
LC Call No.:   QA459.P93
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   6333522

Author:        Proctor, Richard A[nthony], 1837-1888. [from old
                  catalog]
Title:         First steps in geometry:
Published:     London, Longmans, Green, and co., 1887.
Description:   1 p. l., [v]-viii, 179, [1] p. 18 cm.
LC Call No.:   QA459.P96
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   5856927

Author:        Salkind, Charles T., 1898-
Title:         New type questions in plane geometry, by Charles
                  Salkind.
Published:     New York, Globe book company [1929]
Description:   3 p. l., 37, [18] p. diagrs. 19 cm.
LC Call No.:   QA459.S3
Notes:         "Speciment examinations": 18 p. at end.
Subjects:      Geometry, Plane -- Examinations, questions, etc.
Control No.:   5934244

Author:        Serret, Paul Joseph, 1827-1898. [from old
                  catalog]
Title:         Des méthods en géométrie,
Published:     Paris, Mallet-Bachelier, 1885.
Description:   xv, 144 p. diagrs. 21 cm.
LC Call No.:   QA459.S38
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   9242898

Author:        Seymour, F. Eugene (Francis Eugene), b. 1883.
Title:         A unit workbook in plane geometry,
Published:     New York, The Macmillan company, 1934.
Description:   1 p.l., 126 p. diagrs. 28 cm.
LC Call No.:   QA459.S4
Subjects:      Geometry, Plane -- Problems, exercises, etc.
Other authors: Poole, Hallie Shoedde, [from old catalog] joint
                  author.
Control No.:   10164592

Author:        Shanholt, Henry H. [from old catalog]
Title:         New aid in plane geometry for reviews and tests,
Published:     New York city, Regents publishing co., inc.
                  [c1934]
Description:   3 p.l., 76, [45] p. diagrs. 17 cm.
LC Call No.:   QA459.S45
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
               Geometry, Plane -- Examinations, questions, etc.
                  [from old catalog]
Control No.:   5951020

Author:        Shew, Gertrude W. [from old catalog]
Title:         A student's drill and review book in plane
                  geometry,
Published:     Syracuse, N.Y., Iroquois publishing company, inc.
                  [c1928]
Description:   125 p. 19 cm.
LC Call No.:   QA459.S5
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   8740938

Author:        Shiff, Vera. [from old catalog]
Title:         Metody rëiìeshenæiæi voprosov çelementarnoæi
                  geometr¯ii.
Published:     1894.
Description:   iv, 113 p. diagrs. 24 cm.
LC Call No.:   QA459.S513
Notes:         Romanized.
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   10245589

Author:        Simon, P.
Title:         Guide méthodique de résolution des problèmes
                  de géométrie élémentaire / par P. Simon.
Edition:       3e éd.
Published:     Paris : Belin, 1905.
Description:   272 p. : ill. ; 18 cm.
LC Call No.:   QA459.S55x 1905
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   983724

Author:        Smith, David E. [from old catalog]
Title:         Teachers' key and manual to accompany Exercises
                  and tests in plane geometry ...
Published:     [n.p.] [c1928]
Description:   1 v. cm.
LC Call No.:   QA459.S56 Key
Control No.:   9082379

Author:        Stewart, Matthew, 1717-1785.
Title:         Propositiones geometricae, more veterum
                  demonstratae, ad geometriam antiquam illustrandam et
                  promovendam idoneae / auctore Matthaeo Stewart ...
Published:     Edinburgi : Typis Sands, Murray, et Cochran ...,
                  1763.
Description:   viii, 218 [i.e. 216] p., xxi folded leaves of
                  plates : ill. ; 21 cm. (8vo)
LC Call No.:   QA459.S82 1746
Notes:         Signatures: pip4s A-2Dp4s.
               With: Stewart, Matthew. Some general theorems of
                  considerable use in the higher parts of mathematics.
                  Edinburgh : Printed by W. Sands, A. Murray, and J. Cochran,
                  sold by said W. Sands ... and by J. and P. Knapton ..., 1746.
                  DLC
Subjects:      Geometry -- Problems, exercises, etc. -- Early
                  works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   272644

Author:        Stewart, Matthew, 1717-1785.
Title:         Some general theorems of considerable use in the
                  higher parts of mathematics / by Matthew Stewart, Minister at
                  Rosneath.
Published:     Edinburgh : Printed by W. Sands, A. Murray, and
                  J. Cochran , sold by said W. Sands ... and by J. and P.
                  Knapton ..., 1746.
Description:   [4], 163, [1] p., iv folded leaves of plates :
                  ill. ; 21 cm. (8vo)
LC Call No.:   QA459.S82 1746
Notes:         Signatures: pip2s A-Up4s Xp2s.
               Errata slip mounted on p. [4].
               With: Stewart, Matthew. Propositiones
                  geometricae, more veterum demonstratae, ad geometriam
                  antiquam illustrandam et promovendam idoneae. Edinburgi :
                  Typis Sands, Murray et Cochran ..., 1763. DLC
Subjects:      Geometry -- Problems, exercises, etc. -- Early
                  works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   272606

Author:        Stewart, Seth T[hayer] [from old catalog]
Title:         Exercises in Stewart's Plane and solid geometry,
Published:     New York, Cincinnati [etc.] American book co.
                  [c1893]
Description:   1 p. l., 225 p. diagr. 19 cm.
LC Call No.:   QA459.S85
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   7261316

Author:        Sykes, Mabel, 1868-
Title:         A source book of problems for geometry, based
                  upon industrial design and architectural ornament, by Mabel
                  Sykes ... with the coöperation of H.E. Slaught and N.J.
                  Lennes.
Published:     Boston, Allyn and Bacon, 1912.
Description:   viii, 372 p. illus., diagrs. 20 cm.
LC Call No.:   QA459.S9
ISBN:          $2.50
Notes:         Bibliographies: p. 327-336.
Subjects:      Geometry -- Problems, exercises, etc.
               Decoration and ornament.
Other authors: Slaught, H. E. (Herbert Ellsworth), 1861-1937.
               Lennes, N. J. (Nels Johann), 1874-
Control No.:   4526061

Author:        Taylor, Charles. [from old catalog]
Title:         Useful geometry practically exemplified by a
                  series of diagrams, with clear and concise directions;
                  showing the construction, division, inscribing,
                  circumscribing, and proportions of plane figures: calculated
                  to assist the young beginner and every one who uses the rule,
                  the square, and the compasses.
Published:     London, Sherwood, Gilbert, and Piper, 1832.
Description:   viii, 173, [1] p. front., diagrs. 18 cm.
LC Call No.:   QA459.T3
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   10117686

Author:        Toft, Robert. [from old catalog]
Title:         Applied geometry (carpentry)
Published:     New Brunswick, N.J., Vocational Division,
                  Curriculum Laboratory, 1960.
Description:   p. cm.
LC Call No.:   QA459.T6
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Lally, Dominic A., [from old catalog] joint
                  author.
Other authors: New Jersey. Division of Vocational Education.
                  Curriculum Laboratory, New Brunswick. [from old catalog]
Control No.:   7027189

Author:        Tower, Oswald. [from old catalog]
Title:         Exercises in plane geometry with syllabus and
                  definitions,
Published:     [Andover, Mass.] c1937.
Description:   iv, 130 p. 19 cm.
LC Call No.:   QA459.T65
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Other authors: Sanborn, George Knight, 1907- [from old catalog]
                  joint author.
               Newton, Frederick Edwin, 1870- [from old
                  catalog]
               Lynde, Lester Edward, 1879- [from old catalog]
Control No.:   5965471

Author:        Uspenskiæi, V. A. (Vladimir Andreevich)
Title:         Some applications of mechanics to mathematics.
                  Translated from the Russian by Halina Moss. Translation
                  editor: Ian N. Sneddon.
Published:     New York, Blaisdell Pub. Co. [c1961]
Description:   58 p. illus. 22 cm.
Series:        Popular lectures in mathematics series, v. 3
LC Call No.:   QA459.U83 1961
Dewey No.:     513.9
Notes:         A Blaisdell scientific paperback.
Subjects:      Geometry -- Problems, exercises, etc.
               Mechanics.
Control No.:   7027753

Author:        Vose, George L. (George Leonard), 1831-1910.
Title:         A graphic method for solving certain algebraic
                  problems / by George L. Vose ...
Published:     New York : D. Van Nostrand, 1875.
Description:   62 p. : front., diagrs. ; 16 cm.
LC Call No.:   QA459.V96
Notes:         "A portion of the following pages first appeared
                  in Van Nostrand's engineering magazine for June, 1875."
                  --Pref.
Subjects:      Algebra -- Graphic methods.
               Geometry -- Problems, exercises, etc.
Control No.:   6322275

Author:        Vose, George L. (George Leonard), 1831-1910.
Title:         A graphic method for solving certain questions in
                  arithmetic, or algebra, by George L. Vose ...
Edition:       2d ed.
Published:     New York, D. Van Nostrand company, 1902.
Description:   62 p. incl. front., diagr. 15 cm.
Series:        Van Nostrand science series, no. 16
LC Call No.:   QA459.V97
Subjects:      Algebra -- Graphic methods.
               Geometry -- Problems, exercises, etc.
Series Entry:  Van Nostrand's science series ; no. 16.
Control No.:   2633852

Author:        Welte, Herbert David, 1898- [from old catalog]
Title:         Standard service geometry work-book.
Edition:       Teacher's ed.
Published:     Chicago, New York [etc.] Scott, Foresman and
                  company [c1929]
Description:   xvii, [1], 74 [i.e. 134] p. diagrs., forms. 28
                  cm.
LC Call No.:   QA459.W4
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Knight, Frederic Butterfield, 1891- [from old
                  catalog] joint author.
Control No.:   9684191

Author:        Wentworth, G. A. (George Albert), 1835-1906.
Title:         An examination manual in plane geometry.
Published:     Boston, Ginn & company, 1894.
Description:   2 p. l., 138 p. 18 cm.
LC Call No.:   QA459.W46
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   9134527

Author:        Wentworth, G. A. (George Albert), 1835-1906.
Title:         Wentworth & Hill's exercise manuals no. 3.
                  Geometry.
Published:     Bost. 1884.
Description:   p. cm.
LC Call No.:   QA459.W477
Control No.:   9551787

Author:        Wilder, George Fay. [from old catalog]
Title:         Plane geometry,
Published:     New York, Oxford book company [c1927]
Description:   vi, 149 p. diagrs. 19 cm.
LC Call No.:   QA459.W5
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   10143507

Author:        Wright, David Sands, 1847-
Title:         Exercises in concrete geometry, with
                  supplementary discussions, by D. Sands Wright.
Published:     Boston, D.C. Heath & co., 1906.
Description:   iv, [2], 84 p. diagrs. 19 cm.
LC Call No.:   QA459.W7
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   7739669

Author:        Wright, D[avid] Sands, 1847- [from old catalog]
Title:         Exercises in concrete geometry with supplementary
                  discussions,
Published:     [Cedar Falls? Iowa, 1903]
Description:   82 p. 19 cm.
LC Call No.:   QA459.W7 1903
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   8197317

Author:        Wright, David Sands, 1847- [from old catalog]
Title:         Geometrical exercises,
Published:     Chicago, A. Flanagan, 1892.
Description:   vii, 9-104 p. diagrs. 19 cm.
LC Call No.:   QA459.W94
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   7729424

Author:        Wright, J. M. F. (John Martin Frederick)
Title:         Self-examinations in Euclid by J.M.F. Wright.
Published:     Cambridge, W.P. Grant, 1829.
Description:   x, 188 p. diagrs. 22 cm.
LC Call No.:   QA459.W95
Notes:         Appendix I.  Theory of coordinates.  -II. A
                  skeleton of the two books of Apollonius Pergaeus on
                  tangencies, as restored by Vieta and Ghetaldus.  -III.
                  Miscellaneous deductions.
Subjects:      Geometry -- Problems, exercises, etc.
               Apollonius, of Perga. De tractionibus
Control No.:   10071320
