#+STARTUP: showeverything logdone
#+options: num:nil


Author:        Allen, Florence Eliza. [from old catalog]
Title:         The cyclic involutions of third order determined
                  by nets of curves of deficiency 0, 1, and 2.
Published:     [London, 1914]
Description:   [1], 258-288 p. diagr. 22 cm.
LC Call No.:   QA601.A5
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   7301278

Author:        Alrich, George Frederick, 1888-
Title:         Hyperconformal transformations, by George
                  Frederick Alrich.
Published:     [College Park, Md., 1937]
Description:   3 p. l., 25 numb. l. 29 x 24 1/2 cm.
LC Call No.:   QA601.A4
Notes:         Thesis (Ph. D.)--University of Maryland, 1937.
               Type-written (carbon copy)
               Bibliography : leaf 25.
Subjects:      Transformations (Mathematics)
Control No.:   6446365

Author:        Amson, Ernst, 1877-
Title:         Ueber eine zwei-zweideutige Punktverwandtschaft
                  der Ebene und eine ein-eindeutige, Welche mit ihr in
                  Zusammenhang steht ...
Published:     München, Druck der Akademischen Buchdruckerei
                  von F. Straub, 1904.
Description:   45, [1] p. fold. col. pl., diagrs. 22 cm.
LC Call No.:   QA601.A52
Notes:         Inaug.-diss.--Erlangen.
               Lebenslauf.
Subjects:      Transformations (Mathematics)
Control No.:   8671074

Author:        Berner, Theodor Moritz, 1843- [from old catalog]
Title:         De transformatione secundi ordinis ad figuras
                  geometricas adhibita...
Published:     Berolini, typis C. Schultze [1865]
Description:   33, [1] p. 26 cm.
LC Call No.:   QA601.B5
Subjects:      Transformations (Math.) [from old catalog]
Control No.:   6328083

Author:        Beyel, Christian, 1854- [from old catalog]
Title:         Centrische collineation nter ordnung in der ebene
                  vermittelt durch aehnlichkeitspunkte von kreisen ...
Published:     Zürich, Druck von Zürcher & Furrer, 1882.
Description:   2 p.l., 48 p. diagrs. on pl. 22 cm.
LC Call No.:   QA601.B57
Subjects:      Collineation. [from old catalog]
Control No.:   7264781

Author:        Blanch, Gertrude K., 1897- [from old catalog]
Title:         Properties of the Veneroni transformation in
                  Sb4s ...
Published:     [Baltimore, 1936]
Description:   p. 639-645. 24 cm.
LC Call No.:   QA601.B6 1935
Subjects:      Transformation (Mathematics) [from old catalog]
               Hyperspace. [from old catalog]
Other titles:  Veneroni transformation in Sb4s.
Control No.:   7835306

Author:        Blichfeldt, Hans Frederik, 1873- [from old
                  catalog]
Title:         Finite collineation groups,
Published:     Chicago, Ill., The University of Chicago press
                  [1917]
Description:   xi, 194 p. 19 cm.
LC Call No.:   QA601.B63
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Collineation. [from old catalog]
Control No.:   9649835

Author:        Bobek, Karl [Joseph], 1855-1899. [from old
                  catalog]
Title:         Über gewisse eindeutige involutorische
                  tranformationen der ebene ...
Published:     Wien, Aus der K. K. Hof- und staatsdruckerei,
                  1885.
Description:   1 p.l., 43 p. 24 cm.
LC Call No.:   QA601.B66
Subjects:      Transformations (Math.) [from old catalog]
Control No.:   6796121

Author:        Böger, Rudolf, 1854- [from old catalog]
Title:         Die optische verwandschaft in projektiver
                  darstellung ...
Published:     Hamburg, 1907.
Description:   3 p.l., 52 p. diagrs. 21 cm.
LC Call No.:   QA601.B7
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   10093787

Author:        Boyd, Paul P. (Paul Prentice), 1877-
Title:         On the perspective Jonquières involutions
                  associated with the (2, 1) ternary correspondence ... by Paul
                  Prentice Boyd ...
Published:     [Baltimore] 1912.
Description:   1 p. l., p. [291]-324. 31 cm.
LC Call No.:   QA601.B75
Notes:         Thesis (Ph. D.)--Cornell university, 1911.
               "Reprinted from American journal of mathematics,
                  vol. XXXIV, no. 3."
Subjects:      Transformations (Mathematics)
Control No.:   7295435

Author:        Bramble, Charles Clinton, 1890-
Title:         A collineation group isomorphic with the group of
                  the double tangents of the plane quartic ...  by C. C.
                  Bramble.
Published:     [Baltimore, 1918]
Description:   1 p. L., [351]-365 p., 1 L. 30 cm.
LC Call No.:   QA601.B77
Notes:         Biographical note.
               "Reprinted from American journal of mathematics,
                  vol xi, no. 4, October, 1918."
               Thesis (Ph. D.)--John Hopkins university, 1917.
Subjects:      Collineation
Control No.:   9185298

Author:        Brill, Alexander von, 1842-1935.
Title:         Beiträge zur lehre von den eindeutigen
                  transformationen ...
Published:     Darmstadt, Buckdruckerei von H. Brill, 1867.
Description:   1 p. l., 15 p. 27 cm.
LC Call No.:   QA601.B8
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   10074681

Author:        Brückel, Philipp, 1864- [from old catalog]
Title:         Untersuchungen über die reciproke verwandschaft
                  in der ebene...
Published:     Giessen, Druck von W. Keller, 1888.
Description:   19, [1] p. 27 x 22 cm.
LC Call No.:   QA601.B88
Subjects:      Transformations (Math.) [from old catalog]
Control No.:   9606155

Author:        Bücking, Ferdinand, 1862- [from old catalog]
Title:         Die winkelgegenpunkte des dreiecks.
Published:     Metz, Druckerei der Lothringer zeitung, 1892.
Description:   2 p.l., 23 p., 1 l. diagrs. on 2 pl. 26 x 21 cm.
LC Call No.:   QA601.B9
Subjects:      Transformations (Mathematics) [from old catalog]
               Triangle. [from old catalog]
Control No.:   9149137

Author:        Buecking, Hugo, i.e. Ferdinand Carl Bertram Hugo,
                  1851- [from old catalog]
Title:         Beitrag zur theorie der geometrischen
                  verwandtschaft zweiten grades ...
Published:     Marburg, N.G. Elwertsche
                  universitäts-buchdruckerei, 1874.
Description:   1 p.l., 29, [1] p. 27 x 22 cm.
LC Call No.:   QA601.B92
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   10078798


Author:        Carver, Walter Buckingham, 1879-
Title:         On the Cayley-Veronese class of configurations
                  ...
Published:     [Lancaster, Pa., Press of the New era printing
                  company] 1905.
Description:   1 p. L., 534ö545 p., 1 L. diagrs. 28 cm.
LC Call No.:   QA601.C33
Notes:         Reprinted from the Transactions of the American
                  mathematical society, v. 6, no. 4, October, 1905.
               Biography.
               Thesis (Ph. D.)--John Hopkins university.
Subjects:      Configurations
Control No.:   8678130

Author:        Chambers, Livingston Hunter, 1907- [from old
                  catalog]
Title:         On (2, 2) planar correspondences ...
Published:     [New York, 1936]
Description:   [1], [382]-388 p. 24 cm.
LC Call No.:   QA601.C48 1935
Subjects:      Transformation (Mathematics) [from old catalog]
               Geometry, Algebraic. [from old catalog]
Other titles:  Planar correspondences.
Control No.:   5962529

Author:        Civin, Paul, 1919- [from old catalog]
Title:         Two-to-one mappings of manifolds,
Published:     [n.p., 1943]
Description:   49-57 p., 1 l. 26 cm.
LC Call No.:   QA601.C57
Subjects:      Transformations (Mathematics) [from old catalog]
               Aggregates. [from old catalog]
Control No.:   9736514

Author:        Clebsch, Alfred, 1833-1872.
Title:         Vorlesungen über geometrie mit besonderer
                  benutzung der vorträge von Alfred Clebsch, bearb. und hrsg.
                  von dr. Ferdinand Lindemann ...
Edition:       2., verm. aufl.
Published:     Leipzig, B.G. Teubner, 1906-10.
Description:   1 v. in 2. diagrs. 24 cm.
LC Call No.:   QA601.C61
Subjects:      Geometry, Analytic.
               Forms (Mathematics)
               Transformations (Mathematics)
Other authors: Lindemann, Ferdinand, 1852-1939, ed.
Control No.:   4052532

Author:        Clebsch, Alfred, 1833-1872.
Title:         Vorlesungen über geometrie, von Alfred Clebsch.
                  Bearbeitet und herausgegeben von Dr. Ferdinand Lindemann, mit
                  einem vorworte von Felix Klein ...
Published:     Leipzig, B.G. Teubner, 1876-91.
Description:   2 v. diagrs. 23 cm.
LC Call No.:   QA601.C6
Notes:         Vol. 1 issued in two parts.
               Vol. 2 has title: Vorlesungen über Geometrie,
                  unter besonderer Benutzung der Vorträge von Alfred Clebsch.
                  Bearb. von Dr. Ferdinand Lindemann ...
               1 Bd. Geometrie der Ebene. 1876.--2. Bd. 1. Th.
                  Die Flaèchen erster und Zweiter Ofdnung oder Klasse und der
                  lineare Complex. 1891.
               No more published.
Subjects:      Geometry, Analytic.
               Forms (Mathematics)
               Transformations (Mathematics)
Other authors: Lindemann, Ferdinand, 1852-1939, ed.
Control No.:   5863602

Author:        Clements, Guy Roger. [from old catalog]
Title:         Singular point transformations in two complex
                  variables.
Published:     [Lancaster, Pa., and Princeton, N.J., 1913]
Description:   19 p. 26 cm.
LC Call No.:   QA601.C63
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9641493

Author:        Cooley, James Avas, 1901- [from old catalog]
Title:         Certain symmetric surfaces and curves invariant
                  in De Jonquières transformations,
Published:     Urbana, Ill. [1935]
Description:   1 p. l., 7 p., 1 l. 21 cm.
LC Call No.:   QA601.C64 1935
Subjects:      Transformations (Mathematics) [from old catalog]
               Geometry, Algebraic. [from old catalog]
Other titles:  De Jonquières transformations.
               Jonquières transformations.
Control No.:   7828808

Author:        Cooley, James Avas, 1901- [from old catalog]
Title:         Certain symmetric surfaces and curves invariant
                  in De Jonquières transformations,
Published:     Urbana, Ill. [1935]
Description:   1 p. l., 7 p., 1 l. 21 cm.
LC Call No.:   QA601.C64 1935
Subjects:      Transformations (Mathematics) [from old catalog]
               Geometry, Algebraic. [from old catalog]
Other titles:  De Jonquières transformations.
               Jonquières transformations.
Control No.:   7828808

Author:        Cordier, Joseph, 1880-
Title:         Über eine gruppe von 96 collineationen und
                  correlatiotionen ...
Published:     Strassburg, Strassburger druckerei u.
                  verlagsanstalt, vorm. R. Schultz u. Co., 1905.
Description:   39 p. diagrs. on 2 pl. 24 cm.
LC Call No.:   QA601.C7
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Collineation.
Control No.:   7743926

Author:        Cox, Lewis Clark, 1882- [from old catalog]
Title:         The finite groups of birational transformations
                  of a net of cubics ...
Published:     [Baltimore, 1917]
Description:   1 p. l., p. [59]-74. 31 cm.
LC Call No.:   QA601.C77
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9649434

Author:        Davis, Hannibal Albert. [from old catalog]
Title:         Involutorial transformations belonging to a
                  linear complex ...
Published:     [Baltimore, 1930]
Description:   1 p.l., p. 53-71. 25 cm.
LC Call No.:   QA601.D3 1928
Subjects:      Transformations (Mathematics) [from old catalog]
               Complexes. [from old catalog]
Control No.:   8279175

Author:        Delin, Carl, 1865- [from old catalog]
Title:         Über zwei ebene punktsysteme, die algebraisch
                  auf einander bezogen sind ...
Published:     Lund, H. Ohlsson's buchdruckerei, 1893.
Description:   1 p.l., 85, [1] p. fold. tab. 23 cm.
LC Call No.:   QA601.D35
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   5860332

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         The quadratic Cremona transformation. By Leonard
                  E. Dickson ... Issued February 1, 1898.
Published:     San Francisco, The Academy, 1898.
Description:   1 p. l., p. 13-23. diagr. 26 cm.
Series:        Proceedings of the California academy of
                  sciences. 3d series. math-physics. v. 1, no. 2 [from old
                  catalog]
LC Call No.:   Q11.C22 v.1, no. 2
Notes:         Issued in single cover with v. 1, no. 1 and 3.
Subjects:      Transformations, Quadratic.
Control No.:   5892085

Author:        Diesing, Max.
Title:         Über eine gewisse Cremonasche verwandtschaft
                  vierter ordnung und eine lineare construction der
                  oberflächen zweiten grades aus 9 punkten ...
Published:     Magdeburg, Pansa'sche buchdruckerei (H. Otto)
                  [1887]
Description:   37 p. diagrs. on pl. 22 cm.
Series:        Friedrich-Schiller-Universität Jena.
                  Dissertationen. v. 10, no. 7
LC Call No.:   QA601.D56
Notes:         Inaug.-dis.--Jena.
Control No.:   8201556

Author:        Doehlemann, Karl, 1864-1926.
Title:         Geometrische transformationen ... von Dr. Karl
                  Doehlemann ...
Published:     Leipzig, G.J. Göschen, 1902-08.
Description:   2 v. illus., diagrs. 20 cm.
Series:        Sammlung Schubert. XXVII-XXVIII
LC Call No.:   QA601.D64
Notes:         Series title also at head of t.-p.
               I. t. Die projektiven transformationen nebst
                  ihren anwendungen.--II. t. Die quadratischen und höheren,
                  birationalen punkttransformationen.
Subjects:      Transformations (Mathematics)
               Geometry, Projective.
Series Entry:  Sammlung Schubert ; 27-28.
Control No.:   2634411

Author:        Dye, Leaman Andrew. [from old catalog]
Title:         Involutorial transformations in S3 of order n
                  with an (n-1)--fold line ...
Published:     [New York, 1930]
Description:   1 p.l., p. 251-161. 27 cm.
LC Call No.:   QA601.D8 1930
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9218513

Author:        Eisenhart, Luther Pfahler, b. 1876.
Title:         Transformations of surfaces, by Luther Pfahler
                  Eisenhart ...
Published:     Princeton, Princeton university press; [etc.,
                  etc.] 1923.
Description:   ix, 379, [1] p. diagrs. 23 cm.
LC Call No.:   QA601.E4
Notes:         "Published with the cooperation of the National
                  research council."
Subjects:      Transformations (Mathematics)
               Surfaces.
Other authors: National Research Council (U.S.)
Control No.:   12762349

Author:        Emch, Arnold, b. 1871.
Title:         Projective groups of perspective collineations in
                  the plane treated synthetically / by Arnold Emch.
Published:     Lawrence, Kan. : Journal Press, 1896.
Description:   1 p. leaves, 35 p. : ill. ; 24 cm.
LC Call No.:   QA601.E55
Notes:         Thesis (Ph. D.)--University of Kansas, 1895.
               Reprinted from the Kansas University quarterly,
                  vol. v, no. 1 (July 1896).
               Bibliography : p. 34-35.
Subjects:      Transformations (Mathematics)
Control No.:   6369295

Author:        Epstein, Benjamin, 1918-
Title:         On a certain class of transforms / by Benjamin
                  Epstein.
Published:     Urbana, Ill., 1941.
Description:   2 p. ; 23 cm.
LC Call No.:   QA601.E6
Notes:         Abstract of thesis (Ph. D.)--University of
                  Illinois, 1941.
               Vita.
Subjects:      Transformations (Mathematics)
Control No.:   8319645

Author:        Farnum, Fay, 1888- [from old catalog]
Title:         On triadic Cremona nets of plane curves ...
Published:     [Baltimore, 1928]
Description:   1 p.l., p. 357-370 p. 25 cm.
LC Call No.:   QA601.F3 1926
Subjects:      Transformations (Mathematics) [from old catalog]
               Curves, Plane. [from old catalog]
Control No.:   9680599

Author:        Feder, Julius, 1873- [from old catalog]
Title:         Die configuration (12b6s, 163) und die
                  zugehörige gruppe von 2304 collineationen und correlationen
                  ...
Published:     Leipzig, Druck von B. G. Teubner, 1896.
Description:   1 p. l., 35 p., 1 l. diagrs. 25 cm.
LC Call No.:   QA601.F3
Subjects:      Configurations. [from old catalog]
               Collineation. [from old catalog]
Control No.:   7741501

Author:        Fraleigh, Percy Austin, 1895- [from old catalog]
Title:         Regular bilinear transformations of sequences
                  ...
Published:     [Ithaca, N.Y., 1927]
Description:   [6] p. 23 cm.
LC Call No.:   QA601.F7 1927
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   8292763

Author:        Frisch, Elizabeth, sister.
Title:         Determination of a set of independent relations
                  characterizing a certain system consisting of a conic and
                  quartic curve, by Sister M. Elizabeth Frisch.
Published:     Washington, D.C., Catholic University of America
                  Press, 1939.
Description:   2 p. l., 23 p. diagrs. 23 cm.
LC Call No.:   QA601.F75
Dewey No.:     516.54
Notes:         Thesis (PH. D.)--Catholic University of America.
Subjects:      Curves, Quartic.
               Conic sections.
Control No.:   5972870

Author:        Grossmann, Marcel. [from old catalog]
Title:         Ueber die metrischen eigenschaften kollinearer
                  gebilde ...
Published:     Frauenfeld, Huber & co. buchdruckerei, 1902.
Description:   1 p.l., 27 p. diagrs. on 3 pl. 27 cm.
LC Call No.:   QA601.G87
Subjects:      Collineation. [from old catalog]
Control No.:   10074481

Author:        Halmos, Paul Richard, 1914- [from old catalog]
Title:         Finite dimensional vector spaces,
Published:     Princeton, Princeton university press; 1942.
Description:   2 p. l., v, 196 p. 23 cm.
LC Call No.:   QA601.H23
Subjects:      Transformations (Mathematics) [from old catalog]
               Generalized spaces.
Control No.:   9262862

Author:        Hartley, Robert William.
Title:         Determination of the ternary collineation groups
                  whose coefficients lie in the GF (2n) [by] Robert William
                  Hartley.
Published:     Philadelphia, 1925.
Description:   1 p. l., [1], 140-158 p. 26 cm.
LC Call No.:   QA601.H3 1925
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1925.
               "Reprinted from the Annals of mathematics, vol.
                  27, no. 2."
Subjects:      Collineation.
Control No.:   5926839

Author:        Haskell, M(ellen) W. [from old catalog]
Title:         On rational quadratic transformations.
Published:     [n.p.] 1898.
Description:   1 v. cm.
LC Call No.:   QA601.H34
Control No.:   9097526

Author:        Hassler, Jasper O. (Jasper Ole), 1884-
Title:         Plane nets periodic of period 3 under the
                  Laplacian transformation / by Jasper Ole Hassler.
Published:     [Palermo : Tipografia matematica], 1916.
Description:   22 p. ; 25 cm.
LC Call No.:   QA601.H4
Notes:         Thesis (Ph. D.)--University of Chicago, 1915.
               Vita.
               "A private edition distributed by the University
                  of Chicago libraries."
               From Rediconti del Circola matematico di Palermo,
                  tomo 40, fasc. 2-3 (sept.-dic., 1915)
Subjects:      Transformations (Mathematics)
Control No.:   9649488

Author:        Henschel, Albert. [from old catalog]
Title:         Versuch einer räumlichen darstellung complexer
                  ebener gebilde ...
Published:     Weimar, Druck der Hof-buchdruckerei, 1892.
Description:   26 p. 22 cm.
LC Call No.:   QA601.H52
Subjects:      Transformation (Mathematics) [from old catalog]
Control No.:   9623107

Author:        Hollcroft, Temple Rice, 1889-
Title:         A classification of general (2, 3) point
                  correspondences between two planes ...
Published:     [Baltimore, 1919]
Description:   1 p. l., [5]-24 p. 31 cm.
LC Call No.:   QA601.H7
Subjects:      Transformations (Mathematics)
Control No.:   5908748

Author:        Hirschman, I. I. (Isidore Isaac), 1922-
Title:         The convolution transform, by I.I. Hirschman and
                  D.V. Widder.
Published:     Princeton, Princeton University Press, 1955.
Description:   268 p. illus. 24 cm.
Series:        Princeton mathematical series, 20
LC Call No.:   QA601.H58
Dewey No.:     512.86
Subjects:      Convolutions (Mathematics)
Other authors: Widder, D. V. (David Vernon), 1898- joint
                  author.
Series Entry:  Princeton mathematical series ; 20.
Control No.:   3583083

Author:        Holmqvist, Ivan, 1876- [from old catalog]
Title:         Über (2-2)-deutige correspondenzen der
                  elliptischen und hyperelliptischen curven ...
Published:     Lund, H. Ohlssons buchdruckerei, 1900.
Description:   1 p.l., 45 p. 25 cm.
LC Call No.:   QA601.H75
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   8669698

Author:        Howe, Anna Mayme, 1884- [from old catalog]
Title:         The classification of plane involutions of order
                  (3) ...
Published:     [Baltimore, 1919]
Description:   1 p. l., [25]-48. 31 cm.
LC Call No.:   QA601.H8
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   8249937

Author:        Kantor, S. (Seligmann), 1857-
Title:         Premiers fondements pour une théorie des
                  transformations périodiques univoques / par M. S. Kantor;
                  Mémoire couronné par l'Académie des sciences physiques et
                  mathématiques de Naples dans le concours pour 1883.
Published:     Naples : Imprimerie de la Académie, par M. de
                  Rubertis, 1891.
Description:   iv, 335 p. : 3 fold. tables ; 33 cm.
LC Call No.:   QA601.K1
Notes:         Tables I, II et IVième.  La IIIième table n'a
                  été pas plus imprimée."--Tables des matières.
               "Memoria estratta dalla serie 2a degli Atti della
                  R. Accademia delle scienze fis. e mat. di Napoli vol. III, no
                  7, e vol. IV, no. 2."
Subjects:      Transformations (Mathematics)
Control No.:   9136889

Author:        Klein, Felix, 1849-1925.
Title:         Einleiting in die höhere geometrie.
Edition:       2. unveränderter abdruck.
Published:     Leipzig, In kommission bei B. G. Teubner, 1907.
Description:   2 v. diagrs. 22 x 17 cm.
LC Call No.:   QA601.K64 1907
Subjects:      Coordinates.
               Transformations (Mathematics)
               Group theory.
Other authors: Schilling, Fr. (Friedrich), 1868-1950, ed.
Control No.:   9711412

Author:        Klein, Felix, 1849-1925.
Title:         Einleitung in die höhere geometrie ... von F.
                  Klein. Ausgearb. von Fr. Schilling.
Published:     Göttingen, 1893.
Description:   2 v. diagrs. 21 x 17 cm.
LC Call No.:   QA601.K64
Notes:         Autographed.
               I. Vorlesung, gehalten im wintersemester 1892-93:
                  Der allgemeine coordinatenbegriff. Transformationslehre.--II.
                  Vorlesung gehalten im sommersemester 1893: Continuirliche
                  transformationsgruppen. Discontinuirliche gruppen.
Subjects:      Coordinates.
               Transformations (Mathematics)
               Group theory.
Other authors: Schilling, Fr. (Friedrich), 1868-1950, ed.
Control No.:   3579285

Author:        Klein, Felix, 1849-1925.
Title:         Vergleichende betrachtungen über neuere
                  geometrische forsuchungen.
Published:     Erlangen, A. Deichert, 1872.
Description:   48 p. 24 cm.
LC Call No.:   QA601.K66
Notes:         Programm zum eintritt in die Philosophische
                  facultät und den Senat der K.
                  Friedrich-Alexanders-universität zu Erlangen.
Subjects:      Transformations (Mathematics)
               Continuous groups.
Control No.:   6328203

Author:        Klein, Felix, 1849-1925.
Title:         Vorlesungen über höhere Geometrie.
Edition:       3. Aufl., bearb. und hrsg. von W. Blaschke ...
                  Mit 101 Abbildungen.
Published:     Berlin, J. Springer, 1926.
Description:   viii, 405, [1] p. diagrs. 24 cm.
Series:        Die Grundlehren der mathematischen Wissenschaften
                  ... Bd. XXII
LC Call No.:   QA601.K7 1926
Notes:         Parts 1-2 constitute v. 1 of the author's
                  Einleitung in die höhere Geometrie, published 1893; part 3
                  consists of studies by the editor.
               Der allgemeine Koordinatenbegriff.--Lehre von den
                  Transformationen.--Beispiele Geometrischer forschung aus den
                  Letzten Jahrzehnten.
Subjects:      Coordinates.
               Transformations (Mathematics)
Other authors: Blaschke, Wilhelm, 1885- ed.
Control No.:   8737879

Author:        Kraus, Jacob, 1863- [from old catalog]
Title:         Die geometrische deutung von invarianten,
Published:     Giessen, Druck von W. Keller, 1886.
Description:   22 p., 1 l. 27 x 22 cm.
LC Call No.:   QA601.K99
Subjects:      Collineation. [from old catalog]
Control No.:   7732600

Author:        Krieg [von Hochfelden], Franz, freiherr, 1857-
                  [from old catalog]
Title:         Ueber die eindeutige beziehung von räumen
                  mittelst projectiver ebenenbüschel und ihre anwendung auf
                  constructionsaufgaben ...
Published:     Dresden, Druck von B. G. Teubner, 1884.
Description:   37 p. diagrs. on pl. 23 cm.
LC Call No.:   QA601.K94
Subjects:      Transformations (Math.) [from old catalog]
Control No.:   8202922

Author:        Kübel, Karl G. J., 1881-
Title:         Anwendungen einer anschaulichen darstellung des
                  imaginären ...
Published:     Leipzig, Druck von B.G. Teubner, 1907.
Description:   27, [1] p. diagrs. 24 cm.
LC Call No.:   QA601.K96
Notes:         Inaug.-diss.--Giessen.
               Lebenslauf.
               "Literatur": p. [7]
Subjects:      Transformations (Mathematics)
Control No.:   9633684

Author:        Laurin, Paul Johan Gerhard, 1863-
Title:         Sur la transformation isogonale défine par une
                  fonction rationnelle ...
Published:     Lund, Imprimerie Malmström & c:ie, 1887.
Description:   2 p. l., 106 p., 1 l. diagrs. on fold pl. 23 cm.
LC Call No.:   QA601.L3
Notes:         Akademisk afhandling.--Lund.
               Added t.-p.
Subjects:      Transformations (Mathematics)
Control No.:   9606367

Author:        Leibmann, Heinrich i. e. Karl Otto Heinrich,
                  1874- [from old catalog]
Title:         Die einzweideutigen projektiven
                  punktverwandtschaften der ebene ...
Published:     Jena, Druck von A. Kämpfe, 1895.
Description:   52 p. diagr. 22 cm.
LC Call No.:   QA601.L71
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   6796404

Author:        Lorch, Edgar R. (Edgar Raymond), 1907-
Title:         Elementary transformations, Edgar Raymond Lorch
                  ...
Published:     Princeton, N.J., 1932.
Description:   [1], 214-228 p., 1 l. 26 cm.
LC Call No.:   QA601.L787 1933
Dewey No.:     512.86
Notes:         Thesis (Ph. D.)--Columbia university, 1933.
               Vita.
               "Reprinted from the Annals of mathematics, vol.
                  33 (1932)"
Subjects:      Transformations (Mathematics)
Control No.:   10162130

Author:        Lovitt, William Vernon, 1881-
Title:         A type of singular points for a transformation of
                  three variables ... by William Vernon Lovitt.
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1915.
Description:   1 p.l., p. 371-386, 1 l. diagrs. 28 cm.
LC Call No.:   QA601.L8
Notes:         Thesis (Ph. D.)--University of Chicago, 1914.
               Vita.
               Reprinted from Transactions of the American
                  mathematical society, v. 16, no. 4, 1915.
Subjects:      Transformations (Mathematics)
Control No.:   4526226

Author:        Lüroth, Jakob, 1844- [from old catalog]
Title:         Rationale flæchen und involutorische
                  transformationen ...
Published:     Freiburg, Universitæts-buchdruckerei von C.
                  Lehmann, 1889.
Description:   4 p.l., 25 p. 27 x 21 cm.
LC Call No.:   QA601.L94
Subjects:      Transformation (Mathematics) [from old catalog]
               Surfaces. [from old catalog]
Control No.:   6332243

Author:        Maegis, Eduard, 1844- [from old catalog]
Title:         Ueber die allgemeinste eindeutige correlation
                  zweier räumlicher gebilde ...
Published:     Königsberg, Druck von E. J. Dalkowski [1868]
Description:   31, [1] p. 27 x 22 cm.
LC Call No.:   QA601.M18
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9606448

Author:        McKelvey, Joseph Vance.
Title:         The groups of birational transformations of
                  algebraic curves of genus 5 ... By Joseph Vance McKelvey.
Published:     [Baltimore] 1912.
Description:   1 p. L., p. 115-146. 31 cm.
LC Call No.:   QA601.M15
Notes:         "Reprinted from American Journal of Mathematics,
                  vol. 34, no. 2, 1912."
               Thesis (PH. D.)--Cornell University, 1909.
Subjects:      Transformations (Mathematics)
Control No.:   10104984

Author:        Metcalf, Ida Martha. [from old catalog]
Title:         Geometric duality in space ...
Published:     [Ithaca, N.Y., E. D. Norton, printer] 1893.
Description:   24 p. diagrs. 22 cm.
LC Call No.:   QA601.M58
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   8684486

Author:        Mitchell, Ulysses Grant, 1872- [from old
                  catalog]
Title:         Geometry and collineation groups of the finite
                  projective plane PG (2, 2>2)
Published:     [Lawrence, Kan., Press of the Journal-world,
                  1914]
Description:   1 p. l., 45 p. diagrs. 28 cm.
LC Call No.:   QA601.M64
Subjects:      Collineation. [from old catalog]
               Geometry, Projective. [from old catalog]
Control No.:   5895378

Author:        Moody, Ethel Isabel. [from old catalog]
Title:         A Cremona group of order thirty-two of cubic
                  transformations in three-dimensional space ...
Published:     [Baltimore, 1931]
Description:   [1], 460-474 p. 25 cm.
LC Call No.:   QA601.M66 1930
Other authors: Transformations (Mathematics) [from old catalog]
Control No.:   6879239

Author:        Morgan, Frank Millett, 1886-
Title:         Involutorial transformations ... by Frank M.
                  Morgan.
Published:     [Baltimore] 1913.
Description:   1 p. L., p. [79]-104. 31 cm.
LC Call No.:   QA601.M7
Notes:         "Reprinted from American journal of mathematics,
                  vol. xxxv, no. 1, 1913."
               Thesis (PH. D.)--Cornell university, 1912.
Subjects:      Transformations (Mathematics)
Control No.:   8702572

Author:        Morris, Frank Ray, 1885-
Title:         Classification of involutory cubic space
                  transformations ... by Frank Ray Morris ...
Published:     [Berkeley, 1920]
Description:   p. [223]-240. 28 cm.
LC Call No.:   QA601.M8 1920a
Notes:         Cover-title.
               Thesis (Ph. D.)--University of California, 1918.
               University of California publications in
                  mathematics, vol. 1, no. 11, February 17, 1920, with a
                  special thesis t.-p. attached to the cover- title.
Subjects:      Transformations (Mathematics).
Control No.:   10126212

Author:        Morris, Max, 1890-1963.
Title:         Nets of collineations in n-space.
Published:     1929.
Description:   ii, 45 l. 29 cm.
LC Call No.:   QA601.M83
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Collineation.
               Nets (Mathematics)
Control No.:   4099247

Author:        Murray, Francis J. (Francis Joseph), 1911-
Title:         An introduction to linear transformations in
                  Hilbert space, by F. J. Murray.
Published:     Princeton, Princeton University Press, 1941.
Description:   135 p. 23 cm.
Series:        [Annals of mathematics studies, no. 4]
LC Call No.:   QA601.M95
Dewey No.:     512.86 510.82
Notes:         Cover-title: Linear transformations in Hilbert
                  space.
               Lithoprinted.
               Includes bibliographies.
Subjects:      Transformations (Mathematics)
               Hyperspace.
Other titles:  Linear transformations in Hilbert space.
Control No.:   5978431

Author:        Muth, Peter, 1860-
Title:         Ueber ternäre Formen mit linearen
                  Transformationen in sich selbst / von Peter Muth.
Published:     Giessen : W. Keller, 1890.
Description:   25, [1] p. ; 29 cm.
LC Call No.:   QA601.M98
Notes:         Lebenslauf.
               Inaug.-dis.--Giessen.
Subjects:      Transformations (Mathematics)
               Forms, Ternary.
Control No.:   10074762

Author:        Osborn, Jesse Otto, 1894-
Title:         A study of the rational involutorial
                  transformations in space which leave a web of sextic surfaces
                  invariant ... by Jesse Otto Osborn.
Published:     Ithaca, N.Y., 1923.
Description:   1 p.l., p. 17-36. 25 cm.
LC Call No.:   QA601.O8 1923
Notes:         Thesis (Ph.D.)--Cornell university, 1923.
Subjects:      Transformations (Mathematics)
Other titles:  Sextic surfaces.
               Surfaces, Sextic.
Control No.:   1690409

Author:        Pampuch, Andreas, 1855- [from old catalog]
Title:         Über doppelinvolutorische systeme im raume ...
Published:     Strassburg, Buchdruckerei von E. Bauer, 1886.
Description:   52 p., 1 l. 23 x 18 cm.
LC Call No.:   QA601.P2
Subjects:      Collineation.
Control No.:   8214210

Author:        Pfeiffer, George Adam, 1889-
Title:         On the conformal geometry of analytic arcs, by
                  George Adam Pfeiffer ...
Published:     Baltimore, Md., The Lord Baltimore Press, 1915.
Description:   1 p. l., [395]-430 p., 1 l. 31 cm.
LC Call No.:   QA601.P5
Notes:         Thesis (PH. D.)--Columbia University, 1914.
               Vita.
               "Reprinted from American journal of mathematics,
                  vol. XXXVII, no. 4 ... 1915."
Subjects:      Transformations (Mathematics)
Control No.:   5900616

Author:        Phillips, H. B. (Henry Bayard), 1881-
Title:         Some invariants and covariants of ternary
                  collineations...
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1907.
Description:   30 p. diagrs. 27x20 cm.
LC Call No.:   QA601.P6
Notes:         Vita.
               Thesis (PH. D.)--Johns Hopkins university.
Subjects:      Collineation
Control No.:   8682380

Author:        Prenowitz, Walter, 1906-
Title:         The characterization of plane collineations in
                  terms of homologous families of lines, by Walter Prenowitz
                  ...
Published:     [New York, 1935]
Description:   [1], 564-599 p. diagrs. 28 cm.
LC Call No.:   QA601.P75 1936
Dewey No.:     513.57
Notes:         Thesis (Ph. D.)--Columbia University, 1936.
               Vita.
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 38, no. 3 ... November, 1935."
Subjects:      Collineation.
               Topology.
Control No.:   9706316

Author:        Rathke, Fritz, 1860- [from old catalog]
Title:         Zwei configurationen von punkten, welche sich aus
                  fünf resp. sechs beliebigen punkten eines kegelschnittes
                  ergeben ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich), 1885.
Description:   2 p.l., 44 p. diagr. on fold. pl. 21 cm.
LC Call No.:   QA601.R23
Subjects:      Configurations. [from old catalog]
               Conic sections. [from old catalog]
Control No.:   5869025

Author:        Renner, Ludwig, 1858-
Title:         Über die Gruppe der 24 Kollineationen, durch
                  welche ein ebenes Viereck oder ein Vierkant in sich selbst
                  übergeht ...
Published:     Bayreuth, Druck von L. Ellwanger vorm. T. Burger,
                  1896.
Description:   26 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA601.R4
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Collineation.
Control No.:   6803451

Author:        Riess, Georg. [from old catalog]
Title:         Die singulären eindeutigen ebenen- und
                  raum-transformationen niederer ordnung ...
Published:     Freising, Buchdruckerei F. P. Datterer, 1893.
Description:   63 p. 23 cm.
LC Call No.:   QA601.R56
Subjects:      Transformations (Math.) [from old catalog]
Control No.:   9137665

Author:        Rose, Eduard Georg, 1879- [from old catalog]
Title:         Die aziome der projektiven geometrie linearer
                  mannigfaltigkeiten ...
Published:     Strassburg i. E. Buchdruckerei C. Müh & cie.,
                  1905.
Description:   58 p., 1 1. fold. pl., diagrs. 24 cm.
LC Call No.:   QA601.R7
Subjects:      Transformations (Mathematics)
               Geometry -- Foundations.
Control No.:   10085904

Author:        Ruckdeschel, Fritz, 1869- [from old catalog]
Title:         Transformationen in linien- u. ebenenkoordinaten
                  nach neueren systemen ...
Published:     Marburg, J. Hamel, 1897.
Description:   2 p.l., 74 p., 1 l. pl. (diagrs.) 22 cm.
LC Call No.:   QA601.R9
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9127562

Author:        Schilling, Clarence George, 1903-
Title:         Some geometric applications of algebraic
                  correspondences / by Clarence George Schilling.
Published:     Urbana, Ill., [1935]
Description:   2 leaves, 7 p. ; 21 cm.
LC Call No.:   QA601.S3 1935
Notes:         Abstract of thesis (Ph. D.)--University of
                  Illinois, 1935.
               Vita.
               "Lithoprinted by Edwards Brothers, inc. ... Ann
                  Arbor, Michigan."
Subjects:      Transformations (Mathematics)
               Geometry, Algebraic.
Other titles:  Algebraic correspondences.
Control No.:   9702177

Author:        Schmitt, Alois. [from old catalog]
Title:         Über involutorische transformationen ...
Published:     Leipzig, Druck von B. G. Teubner, 1904.
Description:   31 p. 22 cm.
LC Call No.:   QA601.S32
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9143564

Author:        Schneckenburger, Edith Ruth, 1908- [from old
                  catalog]
Title:         On 1-bounding monotonic transformations which are
                  equivalent to homeomorphisms ... by Edith R. Schneckenburger
                  ...
Published:     [n.p., 1941]
Description:   [1], 768-776 p. 25 cm.
LC Call No.:   QA601.S33
Notes:         Thesis (Ph. D.)--University of Michigan, 1940.
               "Presented to the American mathematical society,
                  September 7, 1939."
               "Reprinted from the American journal of
                  mathematics, vol. LXIII, number 4 ... [Oct. 1941]"
               Bibliographical foot-notes.
Subjects:      Transformations (Mathematics)
Control No.:   12941811

Author:        Scholim, Paul, 1862- [from old catalog]
Title:         Ueber eine geometrische verwandtschaft und deren
                  ergebnisse in ebene und raum...
Published:     Breslau, Buchdruckerei von S. Schottlaender,
                  1884.
Description:   3 p.l., 26, [2] p. 23 cm.
LC Call No.:   QA601.S35
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   7732871

Author:        Schoonmaker, Hazel Edith, 1888- [from old
                  catalog]
Title:         Non-monoidal involutions having a congruence of
                  invariant conics ...
Published:     [Baltimore, 1929]
Description:   1 p.l., p. 439-464. 25 cm.
LC Call No.:   QA601.S36 1927
Subjects:      Transformations (Mathematics) [from old catalog]
               Congruences (Geometry) [from old catalog]
Control No.:   7342382

Author:        Schur, Friedrich [Heinrich] 1856- [from old
                  catalog]
Title:         Über die durch collineare grundgebilde erzeugten
                  curven und flächen ...
Published:     Leipzig, Druck von B.G. Teubner, 1881.
Description:   1 p.l., 32 p. 23 cm.
LC Call No.:   QA601.S41
Subjects:      Collineation.
Control No.:   7736884

Author:        Shanks, Daniel, 1917-
Title:         Non-linear transformations of divergent and
                  slowly convergent sequences.
Published:     1954.
Description:   66 l. diagrs. 28 cm.
LC Call No.:   QA601.S48
Notes:         Typescript.
               Thesis - University of Maryland, College Park.
               Vita.
               "References": leaves [64]-66.
Subjects:      Transformations (Mathematics)
Control No.:   8392881

Author:        Shaub, Howard Conway. [from old catalog]
Title:         Rational involutorial transformations in Sb4s
                  which leave invariant [Infinity Symbol] 4 quadric varieties
                  ...
Published:     [Baltimore, 1927]
Description:   1 p.l., p. 367-382. 25 cm.
LC Call No.:   QA601.S5 1927
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9677336

Author:        Sommer, Julius, 1871- [from old catalog]
Title:         Ueber die bestimmung ausgezeichneter punktgruppen
                  auf kurven vom geschlecht p ...
Published:     Tübingen, Druck von H. Laupp, jr., 1898.
Description:   33 p. 23 cm.
LC Call No.:   QA601.S69
Subjects:      Groups of points. [from old catalog]
Control No.:   9612175

Author:        Sousley, Clarence Piersall, 1889- [from old
                  catalog]
Title:         Invariants and covariants of the Cremona cubic
                  surface ...
Published:     [Baltimore, 1917]
Description:   1 p.l., p. [135]-146, 1 l. 31 cm.
LC Call No.:   QA601.S75
Subjects:      Transformation (Mathematics) [from old catalog]
               Surfaces. [from old catalog]
Control No.:   6840037

Author:        Staigmüller, Hermann [Christian Otto], 1857-
                  [from old catalog]
Title:         Die harmonische configuration ...
Published:     Stuttgart, Druck von W. Kohlhammer, 1886.
Description:   iv, 43, [4] p. diagrs. on 2 pl. 23 cm.
LC Call No.:   QA601.S78
Subjects:      Configurations. [from old catalog]
Control No.:   8210262

Author:        Steinitz, Ernst, 1871-1928.
Title:         Über die construction der configurationen nb3s
                  ...
Published:     Breslau, Druck von R. Galle, 1894.
Description:   45, [1] p., 1 l. 23 cm.
LC Call No.:   QA601.S8
Subjects:      Configurations. [from old catalog]
Control No.:   8678447

Author:        Stender, Hugo, 1874-
Title:         Invariante Flächen und Curven bei conformen
                  Gruppen des Raumes / von Hugo Stender.
Published:     Leipzig : Breitkopf & Härtel, 1899.
Description:   59, [1] p. ; 23 cm.
LC Call No.:   QA601.S82
Notes:         Vita.
               Inaug.-diss.--Leipzig.
Subjects:      Transformations (Mathematics)
               Continuous groups.
Control No.:   9141986

Author:        Sturm, Rudolf, 1841-1919.
Title:         Die lehre von den geometrischen verwandtschaften,
                  von Rudolf Sturm ...
Published:     Leipzig, Berlin, B.G. Teubner, 1908-09.
Description:   4 v. 23 cm.
Series:        B.G. Teubners Sammlung von lehrbüchern auf dem
                  gebiete der mathematischen wissenschaften mit einschluss
                  ihrer anwendungen. bd. XXVII, I-IV
LC Call No.:   QA601.S88
Notes:         1. bd. Die verwandtschaften zwischen gebilden
                  erster stufe.--2. bd. Die eindeutigen linearen
                  verwandtschaften zwischen gebilden zweiter stufe.--3. bd. Die
                  eindeutigen linearen verwandtschaften zwischen gebilden
                  dritter stufe.--4. bd. Die nichtlinearen und die mehrdeutigen
                  verwandtschaften zweiter und dritter stufe.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Transformations (Mathematics)
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit einschluss
                  ihrer Anwendungen ; Bd. XXVII, 1-4.
Control No.:   2161611

Author:        Tannenberg, W. de (Wladimir), b. 1860.
Title:         Conférences sur les transformations en
                  géométrie plane, par W. de Tannenberg ...
Published:     Paris, Vuibert, 1921.
Description:   3 p.l., [3]-49 p., 1 l. diagrs. 25 cm.
LC Call No.:   QA601.T25
ISBN:          4.00F
Subjects:      Transformations (Mathematics)
Control No.:   3580488

Author:        Tappan, Anna Helen, 1888- [from old catalog]
Title:         Plane sextic curves invariant under birational
                  transformations,
Published:     [Baltimore, 1915]
Description:   1 p.l., p. [309]-336. 31 cm.
LC Call No.:   QA601.T3
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9646047

Author:        Third, John Alexander, 1865- [from old catalog]
Title:         Two geometrical transformations.
Published:     [Edinbrugh? 1900?]
Description:   14 p. 22 cm.
LC Call No.:   QA601.T4
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   9129160

Author:        Torrance, Charles Chapman, 1902- [from old
                  catalog]
Title:         On plane Cremona tridic characteristics ...
Published:     [Baltimore, 1931]
Description:   1 p.l., p. 911-919. 25 cm.
LC Call No.:   QA601.T55 1931
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   6880896

Author:        Torrey, Marian N. [from old catalog]
Title:         Classification of moncidal invelutions having a
                  fixed tangent cone...
Published:     1924.
Description:   1 v. cm.
LC Call No.:   QA601.T6 1924
Control No.:   6260348

Author:        Tuch, Th. [from old catalog]
Title:         Eine Cremona§sche punkt-gerade-verwandschaft
                  zweiter ordnung nebst einer untersuchung über die einer
                  curve dritter ordnung gleichzeitig ein-und umgeschriebenen
                  dreiecke ...
Published:     Jena, Fromannsche buchdruckerei, H. Pohle, 1890.
Description:   51 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA601.T88
Subjects:      Transformations (Math.) [from old catalog]
Control No.:   6796122

Author:        Uhrig, Karl, 1863- [from old catalog]
Title:         Ueber trilineare & tetraedrale kollineation ...
Published:     Giessen, C. v. Münchow, Universitäts-buch- und
                  steindruckerei, 1891.
Description:   41 p. diagrs. on pl. 23 cm.
LC Call No.:   QA601.U31
Subjects:      Collineation.
Control No.:   9606157

Author:        Van Benschoten, Anna Lavinia, 1866-1927. [from
                  old catalog]
Title:         The birational transformations of algebraic
                  curves ...
Published:     Baltimore, 1909.
Description:   1 p. l., p. [213]-252. 31 x 25 cm.
LC Call No.:   QA601.V3 1908
Subjects:      Transformations (Mathematics) [from old catalog]
               Curves, Algebraic. [from old catalog]
Control No.:   6887743

Author:        Vest, Marvin Lewis, 1906- [from old catalog]
Title:         [Birational space transformations associated with
                  congruences of lines.
Published:     n. p., 1942-46]
Description:   4 pts. 26 cm.
LC Call No.:   QA601.V48
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   6507785

Author:        Walker, B. M. (Buz M.), b. 1863.
Title:         On the resolution of higher singularities of
                  algebraic curves into ordinary modes, by B.M. Walker ...
Published:     Chicago, 1906.
Description:   54 p. diagr. 24 cm.
LC Call No.:   QA601.W18
Notes:         Thesis (PH. D.)--University of Chicago, 1907.
               Autobiography.
Subjects:      Transformations (Mathematics)
               Curves.
Control No.:   273021

Author:        Wenzel, Georg, 1847- [from old catalog]
Title:         Ueber die einfachste allgemeine beziehung
                  zwischen räumlichen gebilden ...
Published:     Breslau, F. W. Jungfer's buchdruckerei, 1870.
Description:   2 p.l., 38, [2] p. 22 cm.
LC Call No.:   QA601.W48
Subjects:      Transformations (Mathematics) [from old catalog]
Control No.:   7268846

Author:        Williams, Arthur Robinson, b. 1884.
Title:         On a birational tranformation connected with a
                  pencil of cubics ...
Published:     [Berkeley, 1920]
Description:   p. [211]-222. 28 cm.
LC Call No.:   QA601.W7 1920a
Subjects:      Transformations (Mathematics)
               Curves, Cubic.
Control No.:   9657925

Author:        Wimmer, Bartholomäus.
Title:         Ueber eine allgemeine classe von ein-zweideutigen
                  raumtransformationen ...
Published:     Dresden, Druck von B.G. Teubner, 1891.
Description:   19 p. 23 cm.
Series:        Universität Erlangen. Dissertationen. v. 12, no.
                  14
LC Call No.:   QA601.W75
Notes:         Inaug.-dis.--Erlangen.
Control No.:   10074467

Author:        Ayres, Frank, 1901-
Title:         A Cremona transformation generated by a pencil of
                  surfaces ... by Frank Ayres, jr. ...
Published:     [Chicago] 1938.
Description:   ii numb. l., 25 p. 24 cm.
LC Call No.:   QA602.A8 1938
Dewey No.:     512.86
Notes:         Thesis (PH. D.)--University of Chicago, 1938.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Cremona transformations.
Control No.:   4527466

Author:        Barber, Sherburne Frederick, 1907- [from old
                  catalog]
Title:         Planar Cremona transformations,
Published:     [Baltimore, 1934]
Description:   2 p.l., p. 109-121, 1 l. 25 cm.
LC Call No.:   QA602.B3 1933
Subjects:      Cremona transformations.
Control No.:   8760681

Author:        Bennett, Theodore Lake, 1899- [from old catalog]
Title:         Mapping by means of linear systems of curves
                  invariant under Cremona involutions, by Theodore Lake Bennett
                  ...
Published:     [Baltimore, 1926]
Description:   1 p.l., p. 257-276, 1 l. 26 cm.
LC Call No.:   QA602.B4 1926
Subjects:      Cremona transformations.
               Curves, Algebraic.
Other titles:  Cremona involutions.
Control No.:   7801044

Author:        Dye, Leaman Andrew. [from old catalog]
Title:         A qintic transformation in S3,
Published:     Charleston, The Citadel, the Military College of
                  South Carolina, 1962.
Description:   22 p. 23 cm.
LC Call No.:   QA602.D9
Subjects:      Cremona transformations.
               Mathematics, Ancient.
Other authors: Reves, George Everett. Modern miscoceptions of
                  the mathematical achievements of the ancients. [from old
                  catalog]
Control No.:   7969549

Author:        Gentry, Frank Cook, 1903- [from old catalog]
Title:         Quaternary Cremona groups of ternary type,
Published:     [Durham, N.C., 1938]
Description:   1 p.l., 107-124, 1 l. 26 cm.
LC Call No.:   QA602.G4 1937
Subjects:      Cremona transformations.
Control No.:   5969571

Author:        Harrison, Ross Arthur, 1911- [from old catalog]
Title:         Cremona webs in SK without base curves ...
Published:     Ithaca, N.Y., 1936.
Description:   [1], 3 p. 23 cm.
LC Call No.:   QA602.H37 1936
Subjects:      Cremona transformations.
Control No.:   6439110

Author:        Hudson, Hilda P. (Hilda Phoebe), b. 1881.
Title:         Cremona transformations in plane and space, by
                  Hilda P. Hudson.
Published:     Cambridge [Eng.] The University Press, 1927.
Description:   xx, 454 p. diagrs. 27 cm.
LC Call No.:   QA602.H8
Notes:         Bibliography: p. [396]-433.
Subjects:      Transformations (Mathematics)
Control No.:   8740458

Author:        Huff, Gerald Boone, 1909-
Title:         Discontinuous groups associated with the Cremona
                  groups / by Gerald Boone Huff.
Published:     Urbana, Ill., [1936]
Description:   1 p. leaf, p. 627-636, 1 leaf ; 25 cm.
LC Call No.:   QA602.H83 1935
Notes:         Vita.
               Thesis (Ph. D.)--University of Illinois, 1935.
               "Reprinted from the American journal of
                  mathematics, vol. LVIII, number 3...July, 1936."--Label
                  mounted over imprint.
               "References":  p. 635-636.
Subjects:      Cremona transformations.
Control No.:   7366411

Author:        Johnson, Roberta Frances, 1902- [from old
                  catalog]
Title:         Involutions of order two associated with surfaces
                  of genera,
Published:     [Baltimore, 1934]
Description:   1 p.l., p. 199-213. 25 cm.
LC Call No.:   QA602.J6 1933
Subjects:      Cremona transformations.
               Surfaces.
Control No.:   8763255

Author:        Montague, Harriet Frances, 1905- [from old
                  catalog]
Title:         Certain non-involutorial Cremona transformations
                  of hyperspace ...
Published:     [New York, 1936]
Description:   1 p.l., p. 727-731. 24 cm.
LC Call No.:   QA602.M65 1935
Subjects:      Cremona transformations.
               Hyperspace.
Control No.:   8304149

Author:        Purcell, Edwin J. (Edwin Joseph), 1901-
Title:         Involutorial space Cremona transformations
                  determined by non-linear null reciprocities ...
Published:     [Baltimore, 1933]
Description:   1 p.l., p. 381-389 25 cm.
LC Call No.:   QA602.P8 1932
Subjects:      Cremona transformations.
Control No.:   7355915

Author:        Rempfer, Robert Weir, 1914- [from old catalog]
Title:         Space Cremona groups of transformations of planar
                  type,
Published:     Urbana, Ill., 1938 [i.e. 1939]
Description:   1 p.l., 5 p. 21 cm.
LC Call No.:   QA602.R4 1938
Subjects:      Cremona transformations.
Control No.:   10184679

Author:        Sisk, Augustus, 1889- [from old catalog]
Title:         The plane symmetric quintic Cremona involutions
                  ...
Published:     Ithaca, N.Y., 1932.
Description:   [5] p. 23 cm.
LC Call No.:   QA602.S47
Subjects:      Cremona transformations.
Other titles:  Quintic Cremona involutions.
Control No.:   7364349

Author:        Slaught, H. E. (Herbert Ellsworth), 1861-1937.
Title:         The cross-ratio group of 120 quadratic Cremona
                  transformations of the plane / by Herbert Ellsworth Slaught.
Published:     [Baltimore : Friedenwald, 1901?]
Description:   iv, 86 p. : plates, tables ; 30 cm.
LC Call No.:   QA602.S5
Notes:         Thesis (Ph. D.)--University of Chicago.
               Reprinted from the American journal of
                  mathematics, vol. 22-23, 1900-1901.
Subjects:      Transformations, Quadratic.
Control No.:   7264840

Author:        Steidl, Hans, 1908- [from old catalog]
Title:         Eine Cremonsasche Geometrie des dreidimensionalen
                  Raumes.
Published:     Bonn, Wurm & Kroth, 1941.
Description:   48 p. 22 cm.
LC Call No.:   QA602.S78
Subjects:      Cremona transformations.
               Hyperspace.
Control No.:   6536799

uthor:        Wallstaff, Wilhelm, 1877-
Title:         Ueber eine besondere Cremona'sche transformation
                  ...
Published:     Breslau, Buchdruckerei H. Fleischmann, 1902.
Description:   73, [3] p. diagr. 23 cm.
LC Call No.:   QA602.W3
Notes:         Inaug.-dis.--Breslau.
               Lebenslauf.
Subjects:      Cremona transformations.
Control No.:   3579429

Author:        Adkisson, Virgil William, 1901- [from old
                  catalog]
Title:         Cyclicly connected continuous curves whose
                  complementary domain boundaries are homeomorphic,
Published:     Philadelphia, 1930.
Description:   1 p. l., 30 p. 23 cm.
LC Call No.:   QA603.A4 1930
Subjects:      Curves. [from old catalog]
Control No.:   9226078

Author:        Atchison, William Franklin, 1918- [from old
                  catalog]
Title:         Virtual sets on an algebraic curve as contrasted
                  with Abelian function theory,
Published:     Urbana, Ill., 1943.
Description:   1 p.l., 7, [1] p. 23 cm.
LC Call No.:   QA603.A8
Subjects:      Curves, Algebraic.
               Point set theory.
Control No.:   8327118

Author:        Bennett, Albert A. (Albert Arnold), 1888-1971.
Title:         An algebraic treatment of the theorem of closure
                  ... by Albert Arnold Bennett ...
Published:     [Lancaster, Pa., Press of the New era printing
                  company] 1915.
Description:   p. 97-118. 26 cm.
LC Call No.:   QA603.B4
Subjects:      Curves.
Control No.:   8239584

Author:        Benton, Thomas Casselberry. [from old catalog]
Title:         On continuous curves which are homogeneous except
                  for a finite number of points ... [by] Thomas C. Benton ...
Published:     Philadelphia, 1928.
Description:   1 p.l., [151]-177. diagrs. 23 cm.
LC Call No.:   QA603.B47 1928
Subjects:      Curves, Plane.
Other titles:  Continuous curves.
Control No.:   7342113

Author:        De Porte, Joseph Vital, 1889- [from old catalog]
Title:         Irrational involutions on algebraic curves...
Published:     [Baltimore, 1918]
Description:   1 p.l., p. [47]-68. 31 cm.
LC Call No.:   QA603.D4
Subjects:      Curves, Algebraic. [from old catalog]
               Transformations. [from old catalog]
Control No.:   8715580

Author:        Galvin, Catharine Francis, Sister.
Title:         Two geometrical representations of the symmetric
                  correspondence C [subscript] n, n, with their interrelations,
                  by Sister Catharine Francis Galvin.
Published:     Washington, Catholic University of America,
                  1938.
Description:   24 p. diagrs. 26 cm.
LC Call No.:   QA603.G3 1938
Dewey No.:     512.86
Notes:         Thesis--Catholic University of America.
Subjects:      Point set theory.
               Curves.
Control No.:   7839983

Author:        Gossard, Harry Clinton, 1884- [from old catalog]
Title:         On a special elliptic ruled surface of the ninth
                  order ...
Published:     [Baltimore, 1916]
Description:   1 p.l., p. [431]-445, 1 l. 31 cm.
LC Call No.:   QA603.G6
Subjects:      Surfaces. [from old catalog]
Control No.:   10116787

Author:        Graves, Gordon Harwood, 1884-
Title:         Complete linear systems of algebraic curves of
                  least order of genera three and four, by Gordon Harwood
                  Graves ...
Published:     Lancaster, Pa., Press of the New Era Printing
                  Company, 1914.
Description:   25 p. 24 cm.
LC Call No.:   QA603.G7
Notes:         Thesis (Ph. D.)--Columbia University, 1914.
               Vita.
Subjects:      Transformations (Mathematics)
               Curves.
Control No.:   9173426

Author:        Haynes, Euphemia (Lofton), 1890- [from old
                  catalog]
Title:         Determination of sets of independent conditions
                  characterizing certain special cases of symmetric
                  correspondences ...
Published:     Washington, D.C., The Catholic university of
                  America press, 1943.
Description:   3 p. l., 29 p. 23 cm.
LC Call No.:   QA603.H38
Subjects:      Groups of points. [from old catalog]
               Curves. [from old catalog]
Control No.:   6921891

Author:        Hebbert, Clarence Mark, 1890-
Title:         Some circular curves generated by pencils of
                  stelloids and their polars, by Clarence Mark Hebbert.
Published:     [Urbana, 1918]
Description:   2 p. L., 14 p., 1 L. diagr. 24 cm.
LC Call No.:   QA603.H45
Notes:         Vita.
               "Extracted from the Tokohu mathematical journal,
                  vol. 13, 1918, edited by tsuruichi Hayashi."
               Thesis (PH. D.)--University of Illinois, 1917.
               Bibliography: p. 13-14.
Subjects:      Curves
Other titles:  Pencils of stelloids and their polars.
Control No.:   6375223

Author:        Henderson, Archibald, 1877-1963.
Title:         The twenty-seven lines upon the cubic surface ...
                  by Archibald Henderson.
Published:     Chicago, 1915.
Description:   4 p.l., 100 p. tables (1 fold.) 13 fold. diagr.
                  (in pocket) 22 cm.
LC Call No.:   QA603.H5 1915
Notes:         Thesis (Ph. D.)--University of Chicago, 1915.
               Vita.
               Published also as Cambridge tracts in mathematics
                  and mathematical physics, no. 13, Cambridge, University
                  press, 1911.
               Bibliography: p. [96]-100.
Subjects:      Surfaces, Cubic.
Control No.:   4053160

Author:        Henderson, Archibald, 1877-1963.
Title:         The twenty-seven lines upon the cubic surface, by
                  Archibald Henderson.
Published:     Cambridge, University Press, 1911.
Description:   100 p. tables (1 fold.) 13 fold. diagr. (in
                  pocket) 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics, no. 13
LC Call No.:   QA603.H5
Notes:         Bibliography: p. [96]-100.
Subjects:      Surfaces, Cubic
Control No.:   8697578

Author:        Kingston, H. R. (Harold Reynolds), b. 1886.
Title:         Metric properties of nets of plane curves ... by
                  H.R. Kingston ...
Published:     [Baltimore, 1916]
Description:   1 p.l., p. [407]-430, 1 l. 24 cm.
LC Call No.:   QA603.K5
Notes:         Thesis (Ph. D.)--University of Chicago, 1914.
               Vita.
               "Reprinted from American journal of mathematics,
                  vol. XXXVIII, no. 4, October, 1916."
Subjects:      Curves, Plane.
Control No.:   3580328

Author:        Lie, Sophus, 1842-1899.
Title:         Classification der flächen nach der
                  transformationsgruppe ihrer geodätischen curven, von Sophus
                  Lie. Universitätsprogram für das erste semester 1879.
Published:     Kristiania, Gedruckt bei Grøndahl & Søn, 1879.
Description:   1 p. l., 45 p. 30 x 24 cm.
LC Call No.:   QA603.L71
Subjects:      Surfaces.
               Transformations, Infinitesimal.
Control No.:   7729671

Author:        Miller, Edwin Wilkinson, 1905- [from old
                  catalog]
Title:         On subsets of a continuous curve which lie on an
                  arc of the continuous curve ...
Published:     [Baltimore, 1932]
Description:   1 p.l., p. 397-416. 25 cm.
LC Call No.:   QA603.M6 1930
Subjects:      Curves. [from old catalog]
Control No.:   8754306

Author:        Musselman, John Rogers, 1890-
Title:         The set of eight self-associated points in space
                  / by John Rogers Musselman.
Published:     [Baltimore, 1918]
Description:   1 p. leaf, p. [69]-86, 1 leaf ; 31 cm.
LC Call No.:   QA603.M9
Notes:         Vita.
               Thesis (Ph. D.)--Johns Hopkins University, 1916.
               "Reprinted from American journal of mathematics,
                  vol. XL, no. 1, January, 1918."
Subjects:      Point set theory.
Control No.:   5906318

Author:        Rawlins, Charles Henry, 1889-
Title:         Complete systems of concomitants of the
                  three-point and the four-point in elementary geometry ... by
                  Charles Henry Rawlins, jr. ...
Published:     [Baltimore, 1918]
Description:   1 p.l., [155]-173 p., 1 l. diagrs. 31 cm.
LC Call No.:   QA603.R3
Notes:         Thesis (Ph. D.)--Johns Hopkins university, 1916.
               Biographical note.
               "Reprinted from American journal of mathematics,
                  vol. XL, no. 2, April, 1918."
Subjects:      Transformations (Mathematics)
               Forms, Binary.
Control No.:   1218104

Author:        Roberts, John Henderson. [from old catalog]
Title:         Concerning non-dense plane continua ...
Published:     [New York, 1930]
Description:   [1], 6-30 p. diagrs. 28 cm.
LC Call No.:   QA603.R6 1930
Subjects:      Curves, Plane. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Control No.:   7811041

Author:        Rowe, Joseph Eugene, 1883-
Title:         Important covariant curves and a complete system
                  of invariants of the rational quartic curve.
Published:     Lancaster, Pa., The New era printing company,
                  1911.
Description:   1 p. L., p. 295-310, 1 L. 28 cm.
LC Call No.:   QA603.R7 1911
Notes:         Thesis (PH. D.)--Johns Hopkins university.
Subjects:      Curves
Control No.:   9164792

Author:        Rutt, Norman Eby. [from old catalog]
Title:         Concerning the cut points of a continuous curve,
Published:     Philadelphia, 1929.
Description:   1 p. l., p. 217-246. illus. 23 cm.
LC Call No.:   QA603.R8 1928
Subjects:      Curves. [from old catalog]
Control No.:   9212342

Author:        Smith, William Mackey, 1881-
Title:         Simply infinite systems of plane curves; a study
                  of isogonals, equitangentials and other families of
                  trajectories ...
Published:     Easton, Pa. [Baltimore, The Lord Baltimore press]
                  1912.
Description:   38 p., 1 l. incl. diagrs. 30 x 24 cm.
LC Call No.:   QA603.S7
Notes:         Thesis (PH. D.)--Columbia university, 1912.
               Vita.
Subjects:      Curves, Plane.
Control No.:   3107497

Author:        Swingle, Paul McCartney, 1899- [from old
                  catalog]
Title:         A certain type of continuous curve and related
                  point sets.
Published:     [New York, 1931]
Description:   [1], 544-556 p. 28 cm.
LC Call No.:   QA603.S8 1929
Subjects:      Curves. [from old catalog]
Other titles:  Continuous curve and related point sets.
Control No.:   6411160

Author:        Symposium on Convexity, University of Washington,
                  1961. [from old catalog]
Title:         Convexity.
Published:     Providence, American Mathematical Society, 1963.
Description:   xv, 516 p. diagrs. 26 cm.
LC Call No.:   QA603.S9 1961
Subjects:      Convex domains -- Congresses.
Other authors: Klee, Victor L., [from old catalog] ed.
Other authors: Washington (State) University. [from old
                  catalog]
               American Mathematical Society. [from old
                  catalog]
Series Entry:  Proceedings of symposia in pure mathematics, v.
                  7. [from old catalog]
Control No.:   9382058

Author:        Taylor, Mildred Ellen, 1898-
Title:         A determination of the types of planar Cremona
                  transformations with not more than 9 F-points / by Mildred
                  Ellen Taylor.
Published:     [Baltimore, 1932]
Description:   2 p. leaves, p. 123-128, 1 leaf ; 25 cm.
LC Call No.:   QA603.T3 1931
Notes:         Vita.
               Abstract of thesis (Ph. D.)--University of
                  Illinois, 1931.
               "Reprinted from the American journal of
                  mathematics, vol. LIV, number 1."
               Bibliography:  p. 127-128.
Subjects:      Transformations (Mathematics)
Other titles:  Cremona transformations.
Control No.:   8286318

Author:        Van der Vries, John Nicholas, 1876-
Title:         On the multiple points of twisted curves. By John
                  N. Van der Vries ...
Published:     [Boston, 1903]
Description:   [471]-532 p., 1 l. diagrs. on pl. 25 cm.
LC Call No.:   QA603.V3
Notes:         Thesis (PH. D.)--Clark University, 1902.
               "Proceedings of the American academy of arts and
                  sciences, vol. XXXVII, no. 17, January, 1903."
Subjects:      Curves of double curvature.
Control No.:   9617580

Author:        Vreeswijk, Johannes Adrianus, jr.
Title:         Involuties op rationale krommen.
Published:     Utrecht, Stoomdrukkerij "De Industrie" J. van
                  Druten, 1905.
Description:   viii, 109 p. 23 cm.
LC Call No.:   QA603.V7
Notes:         Proefschrift--Utrecht.
Subjects:      Curves.
               Geometry, Enumerative.
Control No.:   6807567

Author:        Williams, Franklin Grandey, 1893- [from old
                  catalog]
Title:         Families of plane involutions of genus 2 or 3
                  ...
Published:     [Baltimore, 1931]
Description:   cover-title, p. 127-138. 25 cm.
LC Call No.:   QA603.W5 1929
Subjects:      Curves. [from old catalog]
Control No.:   9219196

Author:        Young, Mabel Minerva, 1872- [from old catalog]
Title:         Dupin's cyclide as a self-dual surface ...
Published:     [Baltimore, 1916]
Description:   1 p. l., p. [267]-286, 1 l. 31 cm.
LC Call No.:   QA603.Y5
Subjects:      Cyclide.
               Surfaces.
Control No.:   6369583

Author:        Domsch, Paul Richard, 1860- [from old catalog]
Title:         Ueber die darstellung der flächen vierter
                  ordnung mit doppelkegelschnitt durch hyperelliptische
                  functionen ...
Published:     Greifswald, Druck von F. W. Kunike, 1885.
Description:   1 p.l., 67 p. diagrs. on double pl. 21 cm.
LC Call No.:   QA605.D67
Subjects:      Surfaces. [from old catalog]
               Functions, Theta. [from old catalog]
Control No.:   7264780

Author:        Harnack, Axel, 1851-1888.
Title:         Über die Verwerthung der elliptischen Functionen
                  für die Geomtrie der curven dritten Grades / von Axel
                  Harnack.
Published:     Leipzig : B. G. Teubner, 1875.
Description:   1 p. leaf, 54 p. : ill. ; 23 cm.
LC Call No.:   QA605.H28
Notes:         Thesis--Erlangen.
Subjects:      Elliptic functions.
               Curves, Cubic.
Control No.:   6329933

Author:        Heinze, Louis, 1857-
Title:         Beiträge zur Anwendung der Dreiteilung der
                  elliptischen Functionen auf die Theorie der Wendepunkte einer
                  kurve dritter Ordnung ...
Published:     Greifswald, Drunk von F.W. Kunike, 1883.
Description:   2 p. l., 29, [2] p. 23 cm.
LC Call No.:   QA605.H47
Notes:         Inaug.-Dis.--Königsberg.
               Lebenslauf.
Subjects:      Elliptic functions.
               Curves, Plane.
Control No.:   9138399

Author:        Maltbie, William Henry, 1867- [from old catalog]
Title:         On the curve y [superscript m]--G(x)=0, and its
                  associated Abelian integrals ...
Published:     Baltimore, Press of the Friedenwald company,
                  1894.
Description:   2 p.l., 25, [1] p. diagr. 25 cm.
LC Call No.:   QA605.M26
Subjects:      Curves, Algebraic. [from old catalog]
               Functions, Abelian. [from old catalog]
Control No.:   7265162

Author:        Ott, Ellis Raymond, 1906- [from old catalog]
Title:         A modular manifold associated with the
                  generalized Kummer manifold (p-3),
Published:     [New York, 1933]
Description:   1 p.l., p. 427-433, 1 l. 24 cm.
LC Call No.:   QA605.08 1933
Subjects:      Geometry, Algebraic. [from old catalog]
               Functions, Theta. [from old catalog]
Other titles:  Kummer manifold.
Control No.:   8759854

Author:        Reichardt, Wilibald, 1864-
Title:         Ueber die Darstellung der Kummer'schen Fläche
                  durch hyperelliptische Funtionen / von Wilibald Reichardt.
Published:     Halle, 1887.
Description:   111 p. ; 33 cm.
LC Call No.:   QA605.R34
Notes:         Vita.
               Separat-abdruck aus : Nova acta der K.
                  Leop.-Carol. deutschen akademie der naturforscher, bd. L. 
                  [1887] [375]-483 p.
               Inaug.-dis.--Leipzig.
Subjects:      Transformations (Mathematics)
               Surfaces.
               Functions, Theta.
Control No.:   5860331

Author:        Weiss, Wilhelm, 1859-1904. [from old catalog]
Title:         Über eine algebraische theorie der schaaren
                  nichtadjungirter berührungscurven, welche zu einer
                  algebraischen curve gehören ...
Published:     Prag, 1890.
Description:   2 p.l., 34 p. 24 cm.
LC Call No.:   QA605.W43
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6800450

Author:        Bernhard, Max. [from old catalog]
Title:         Über lineare scharen von kurven und flächen
                  ...
Published:     Stuttgart, J. B. Metzlersche buchdruckerei,
                  1897.
Description:   1 p.l., 30 p. 26 x 20 cm.
LC Call No.:   QA607.B53
Subjects:      Curves, Plane. [from old catalog]
               Surfaces. [from old catalog]
Control No.:   7271594
Author:        Brockmann, Friedrich.
Title:         Zur theorie der Linienflächen zweiter Ordnung
                  ...
Published:     Rostock, C. Hinstorffs Buchdruckerei, 1904.
Description:   74, [2] p. 22 cm.
LC Call No.:   QA607.B86
Notes:         Inaug.-diss.--Rostock.
Subjects:      Complexes.
               Quadrics.
Control No.:   6805126

Author:        Büchel, Wilhelm, 1877-
Title:         Über die durch gewöhnliche
                  differentialgleichungen definierten kurven.
Published:     Hamburg, 1906.
Description:   26 p. diagrs. on 2 pl. (1 fold.) 23 1/2 cm.
LC Call No.:   QA607.B9
Notes:         Separate, from Programm--Realschule in Eppendorf,
                  Hamburg.
Subjects:      Curves, Plane.
Control No.:   9625425

Author:        Büchel, Wilhelm, 1877-
Title:         Zur Topologie der durch eine gewöhnliche
                  Differentialgleichung erster Ordnung und ersten Grades
                  definierten Kurvenschar ...
Published:     Leipzig, Druck von B. G. Teubner, 1903.
Description:   2 p. L., p. [133]-170. 2 fold. pl. (diagrs.) 23
                  cm.
LC Call No.:   QA607.B92
Notes:         Lebenslauf.
               "Gedruckt in den Mitteilungen der Mathematischen
                  Gesellschaft in Hamburg. Bd. IV, Heft 4."
               Inaug.-diss.--Jena.
Subjects:      Curves
               Topology
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.5.
Control No.:   7270400

Author:        Cassity, C. Ronald, 1908- [from old catalog]
Title:         The maps determined by the principal curves
                  associated with five and six points in the plane,
Published:     [Durham, N.C., 1939]
Description:   [1], 146-163 p., 1 l. diagrs. 26 cm.
LC Call No.:   QA607.C35 1938
Subjects:      Curves, Algebraic.
               Surfaces.
               Group theory.
               Topology.
Other titles:  Maps in the plane.
Control No.:   9719269

Author:        Cowley, Elizabeth Buchanan. [from old catalog]
Title:         Plane curves of the eighth order with two real
                  four-fold points having distinct tangents and with no other
                  point singularities, by Elizabeth Buchanan Cowley.
Published:     Lancaster, Pa. Press of the New era printing
                  company, 1908.
Description:   23, [12] p. diagrs. 25 cm.
LC Call No.:   QA607.C8
Notes:         Thesis (Ph. D.)--Columbia university, 1908.
               Life.
Subjects:      Curves.
Control No.:   13194723

Author:        Dalhuisen, Aleida Alberdina.
Title:         Over eenige aantallen van kegelsneden die aan
                  acht voorwaarden voldoen / door Aleida Alberdina Dalhuisen.
Published:     Utrecht : J. van Druten, 1905.
Description:   85 p. ; 23 cm.
LC Call No.:   QA607.D3
Notes:         Thesis--Utrecht.
Subjects:      Geometry, Enumerative.
               Conic sections.
               Surfaces.
Control No.:   8212700

Author:        Echols, Robert Lewis Harrison.
Title:         A correspondence in geometry and some properties
                  of pseudo homochiral and pseudo heterochiral configurations,
                  by Robert Lewis Echols ...
Published:     [Charlottesville, Va.] 1929.
Description:   38 p. diagrs. 23 cm.
LC Call No.:   QA607.E3
Dewey No.:     513.57
Notes:         Thesis (Ph. D.)--University of Virginia.
               "Private edition, distributed by the University
                  of Virginia  Library, University, Virginia.
Subjects:      Configurations.
Control No.:   7814080

Author:        Grove, Charles Clayton, 1875- [from old catalog]
Title:         I. The syzygetic pencil of cubics with a new
                  geometrical development of its Hesse group, G216. II. The
                  complete Pappus hexagon ...
Published:     Baltimore, Md., 1906.
Description:   43 p., 1 l. pl., diagrs. 31 x 25 cm.
LC Call No.:   QA607.G84
Subjects:      Curves, Cubic.
               Collineation.
Control No.:   7746577

Author:        Grüttner, Adalbert, 1881-
Title:         Das räumliche fünfeck ...
Published:     Breslau, Buchdruckerei H. Fleischmann, 1903.
Description:   85, [1] p., 2 l., [2] p. tables (1 fold.) 23 cm.
LC Call No.:   QA607.G88
Notes:         Inaug.-diss.--Breslau.
               Lebenslauf.
Subjects:      Configurations.
Control No.:   9146686


Author:        Haure, Marcel, 1859-
Title:         Recherches sur les points de Weierstrass d'une
                  courbe plane algébrique / par Marcel Haure.
Published:     Paris : Gauthier-Villars et fils, 1896.
Description:   88 p. : ill. ; 28 cm.
LC Call No.:   QA607.H3
Notes:         Thesis--Université de Paris.
Subjects:      Curves.
Control No.:   5871771

Author:        Herbst, Walter, 1886- [from old catalog]
Title:         Mongesche gleichungen zweiten grades als
                  schnittbedingungen von kurvenscharen ...
Published:     Berlin, R. Trenkel, 1912.
Description:   50, [2] p. 23 cm.
LC Call No.:   QA607.H4
Subjects:      Curves. [from old catalog]
               Differential equations. [from old catalog]
Control No.:   10209495

Author:        Hierholzer, Karl [Fridolin Bernhard], 1840-1871.
                  [from old catalog]
Title:         Über kegelschnitte im raume ...
Published:     Leipzig, Druck von B. G. Teubner, 1870.
Description:   1 p.l., 24 p. 23 cm.
LC Call No.:   QA607.H63
Subjects:      Conic sections.
               Geometry, Enumerative.
Control No.:   5864380

Author:        Himpel, Hugo, 1881-
Title:         Ueber die Gruppe der 120 Collineationen, durch
                  die ein räumliches Fünfeck in sich selbst übergeht ...
Published:     Strassburg i.E., Buchdruckerei C. & J. Goeller,
                  1903.
Description:   40 p., 1 l. fold. pl., diagrs. 23 cm.
LC Call No.:   QA607.H66
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Collineation.
               Configurations.
Control No.:   7273500

Author:        Junker, Friedrich, 1864-
Title:         Über algebraische Korrespondenzen / von
                  Friedrich Junker.
Published:     Tübingen : L. F. Fues (W. Armbruster & O.
                  Riecker), 1889.
Description:   iv, [7]-62 p. ; 22 cm.
LC Call No.:   QA607.J95
Notes:         Thesis--Tübingen.
Subjects:      Curves, Plane.
               Geometry, Enumerative.
Control No.:   9610467

Author:        Levi, Friedrich Wilhelm Daniel, 1888- [from old
                  catalog]
Title:         Geometrische konfigurationen,
Published:     Leipzig, S. Hirzel, 1929.
Description:   viii, 310 p. diagrs. 26 cm.
LC Call No.:   QA607.L4
Subjects:      Configurations. [from old catalog]
Control No.:   10152397

Author:        Meyer, Hans, 1852- [from old catalog]
Title:         Ueber die von geraden linien und von
                  kegelschnitten gebildeten schaaren von isothermen; sowie
                  über einige von speciellen curven dritter ordnung gebildete
                  schaaren von isothermen ...
Published:     Zürich, Druck von Zürcher & Furrer, 1879.
Description:   3 p.l., 60 p. diagrs. on xiv pl. 30 x 23 cm.
LC Call No.:   QA607.M6
Subjects:      Curves, Isothermic.
Control No.:   6800814

Author:        Tramm, Wilhelm. [from old catalog]
Title:         Geometrische diskussion des Hermite'schen
                  polynoms.
Published:     Zürich, Buchdr. Gebr. Leemann & co., 1908.
Description:   1 p. l., 32 p. diagrs. 27 x 21 cm.
LC Call No.:   QA607.T7
Subjects:      Curves. [from old catalog]
Control No.:   6815481

Author:        Wünschmann, Karl, 1881-
Title:         Über Berührungsbedingungen bei Integralkurven
                  von Differentialgleichungen ...
Published:     Leipzig, Druck von B.G. Teubner, 1905.
Description:   35, [1] p. 24 cm.
LC Call No.:   QA607.W91
Notes:         Inaug.-diss.--Greifswald.
               Lebenslauf.
Subjects:      Curves.
               Differential equations.
Control No.:   6344085

Author:        Zeuthen, H. G. (Hieronymus Georg), 1839-1920.
Title:         Lehrbuch der abzählenden methoden der geometrie,
                  von H.G. Zeuthen. Mit 38 figuren im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1914.
Description:   xii, 394 p. diagrs. 23 cm.
Series:        B.G. Teubners Sammlung von lehrbüchern auf dem
                  gebiete der mathematischen wissenschaften ... bd. XXXIX
LC Call No.:   QA607.Z4
Subjects:      Geometry, Enumerative.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit Einschluss
                  ihrer Anwendungen ; Bd. XXXIX.
Control No.:   3107653

Author:        Akers, Oscar Perry.
Title:         On the congruence of axes in a bundle of linear
                  line complexes.
Published:     Baltimore, Md., The Lord Baltimore press, 1907.
Description:   1 p. L., [23]-47 p. diagrs. 31x25 cm.
LC Call No.:   QA608.A32
Notes:         From American journal of mathematics, vol. 29,
                  no. 1, January, 1907.
               Thesis (Ph. D.)--Cornell university.
Subjects:      Complexes
Control No.:   6342885

Author:        Andriessen, Carl Otto Gottfried, 1874-
Title:         Über erzeugnisse Kongruenter Grundgebilde ...
Published:     Strassburg i.E., Buchdr. C. Müh & cie., 1906.
Description:   45, [1] p. 23 cm.
LC Call No.:   QA608.A56
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Congruences (Geometry)
Control No.:   6811238

Author:        Autonne, Léon, 1859-1916.
Title:         Sur les formes quaternaires à deux séries de
                  variables; applications à la géométrie et au calcul
                  intégral,
Published:     Bruxelles, Hayez, 1901.
Description:   254 p. diagrs. 30 cm.
LC Call No.:   QA608.A93
Subjects:      Connexes.
               Forms, Quaternary.
Control No.:   6796340

Author:        Beck, Hans, 1876-
Title:         Die Strahlenketten im hyperbolischen Raum ...
Published:     Hannover, Druck von W. Riemschneider, 1905.
Description:   2 p. l., 55, [1] p. 22 cm.
LC Call No.:   QA608.B4
Notes:         Inaug.-diss.--Bonn.
               Lebenslauf.
Subjects:      Complexes.
Control No.:   6347253

Author:        Bettle, Ralph Dennison, 1886- [from old catalog]
Title:         Congruences associated with one-parameter family
                  of curves ...
Published:     [Baltimore, 1915]
Description:   1 p. l., p. [281]-308. 31 cm.
LC Call No.:   QA608.B45
Subjects:      Congruences (Geometry) [from old catalog]
               Curves. [from old catalog]
Control No.:   10113542

Author:        Black, Amos Hale, 1902- [from old catalog]
Title:         Types of involutorial space transformations
                  associated with certain rational curves ...
Published:     [New York, 1932]
Description:   1 p.l., p. 795-810. 28 cm.
LC Call No.:   QA608.B6 1932
Subjects:      Transformation (Mathematics) [from old catalog]
               Complexes. [from old catalog]
Control No.:   7821108

Author:        Carroll, Evelyn Teresa, 1900-
Title:         Systems of involutorial birational
                  transformations contained multiply in special linear line
                  complexes ... by Evelyn Teresa Carroll ...
Published:     [Baltimore, 1932]
Description:   1 p. l., p. 707-717. 25 cm.
LC Call No.:   QA608.C3 1932
Dewey No.:     516
Notes:         Thesis (Ph. D.)--Cornell University, 1932.
               From the American journal of mathematics, v.54,
                  no. 4, October, 1932.
Subjects:      Transformations (Mathematics)
               Complexes.
Control No.:   7353468

Author:        Cook, Alexander Joseph, 1896-
Title:         Pairs of rectilinear congruences with generators
                  in one-to-one correspondence.
Published:     Chicago, 1929.
Description:   ii, 72 l. 29 cm.
LC Call No.:   QA608.C6
Dewey No.:     516/.7
Notes:         Thesis--University of Chicago.
               Typescript (carbon copy)
               Vita.
               Bibliography: leaf 71.
Subjects:      Congruences (Geometry)
               Differential equations, Partial.
Control No.:   303911

Author:        Demoulin, A. (Alphonse), 1869-
Title:         Mémoire sur l'application d'une méthode
                  vectorielle à l'étude de divers systèmes de droits
                  (complexes, congruences, surfaces réglées) par Alphonse
                  Demoulin. (Mémoire couronné au concours de l'enseignement
                  supérieur pour 1890-1891.)
Published:     Bruxelles, A. Castaigne, 1894.
Description:   vi, 118 p. 24 cm.
LC Call No.:   QA608.D3
Subjects:      Line geometry.
Control No.:   8668499

Author:        Gerlich, Paul, 1880-
Title:         Ueber den Tangentencomplex der Fläche 2. Grades
                  ... von Paul Gerlich.
Published:     Breslau, Buchdruckerei H. Fleishmann, 1905.
Description:   59, [1] p. 23 cm.
LC Call No.:   QA608.G3
Notes:         Lebenslauf.
               Inaug.-diss.--Breslau.
Subjects:      Complexes
               Quadrics
Other titles:  Über den Tangentencomplex der Fläche 2.
                  Grades.
               [Pamphlets. Mathematics. 1841-1906] v.8.
Control No.:   9613481

Author:        Hudson, R. W. H. T. (Ronald William Henry
                  Turnbull), 1875-1904.
Title:         Kummer's quartic surface, by R.W.H.T. Hudson ...
Published:     Cambridge, University press, 1905.
Description:   xi, 222 p. front., diagrs. 23 cm.
LC Call No.:   QA608.H8
Notes:         Prefatory note by H.F. Baker.
Subjects:      Line geometry.
               Kummer surfaces.
               Functions, Theta.
Other authors: Baker, H. F. (Henry Frederick), 1866-1956.
Control No.:   272863

Author:        Hun, John Gale, 1877- [from old catalog]
Title:         On certain invariants of two triangles,
Published:     [Lancaster, Pa., Press of the New era printing
                  company, 1904]
Description:   39-55, [1] p. 27 cm.
LC Call No.:   QA608.H93
Subjects:      Connexes.
Control No.:   9140619

Author:        Jessop, C. M. (Charles Minshall), 1861-1939.
Title:         A treatise on the line complex, by C.M. Jessop
                  ...
Published:     Cambridge, University press, 1903.
Description:   xv, [1], 364 p. 22 cm.
LC Call No.:   QA608.J58
               Microfilm 13892 QA
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
               Replace; LC copy replaced by preservation
                  microfilm. DLC
Subjects:      Complexes.
               Line geometry.
Control No.:   2161145

Author:        Kiefer, Carl Ludwig, 1879- [from old catalog]
Title:         Über strahlenkongruenzen zweiter klasse fünfter
                  und niedrigerer ordnung ...
Published:     Strasburg i. E., Buchdr. C. Müh & cie., 1905.
Description:   40 p., 1 l. 23 cm.
LC Call No.:   QA608.K47
Subjects:      Congruences (Geometry)
Control No.:   9621196

Author:        Klein, Felix, 1849-1925.
Title:         Ueber die Transformation der allgemeinen
                  Gleichung des zweiten Grades zwixchen Linien-coordinaten auf
                  eine canonische Form ...
Published:     Bonn, Druck von C. Georgi [1868]
Description:   2 p. L., 53, [2] p. 22 cm.
LC Call No.:   QA608.K64
Notes:         Vita.
               Inaug.-diss.--Bonn.
Subjects:      Complexes
Other titles:  Über die Transformation der allgemeinen
                  Gleichung der zweiten Grades zwischen Linien-coordinaten auf
                  eine cannonische Form.
Control No.:   8205584

Author:        Knothe, Emil Paul, 1867- [from old catalog]
Title:         Bestimmung aller untergruppen der projectiven
                  gruppe des linearen complexes ...
Published:     Kristiania, Det Mallingske bogtrykkerei, 1892.
Description:   2 p. l., 68 p. 23 cm.
LC Call No.:   QA608.K72
Subjects:      Complexes. [from old catalog]
               Continuous groups.
Control No.:   5861711

Author:        Lane, Ernest Preston, 1886-
Title:         Conjugate systems with indeterminate axis curves
                  ... by Ernest Preston Lane ...
Published:     [Baltimore, 1921]
Description:   1 p.l., [1], 52-68 p., 1 l. 26 cm.
LC Call No.:   QA608.L3
Notes:         Thesis (PH. D.)--University of Chicago, 1918.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from the American journal of
                  mathematics, vol. XLIII, no. 1, January, 1921."
Subjects:      Congruences (Geometry)
               Geometry, Differential.
Control No.:   1690218

Author:        Leib, David D. (David Deitch), 1879-
Title:         On a complete system of invariants of two
                  triangles...
Published:     Lancaster, Pa., New era printing company, 1909.
Description:   p. [361]-390, 1 L. 28 cm.
LC Call No.:   QA608.L4
Notes:         Vita.
               Reprinted from the Transactions of the American
                  society, v. 10, 1909.
               Thesis (Ph. D.)--Johns Hopkins university.
               Bibliographical foot-notes.
Subjects:      Connexes
Control No.:   7757286

Author:        Magee, Gordon Richard, 1902-
Title:         Conjugate nets of ruled surfaces in a congruence
                  ... by Gordon Richard Magee ...
Published:     [Chicago] 1931.
Description:   iii, 81 p. 24 cm.
LC Call No.:   QA608.M25 1933
Dewey No.:     516
Notes:         Thesis (PH. D.)--University of Chicago, 1933.
               Vita.
               Lithographed.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Congruences (Geometry)
               Surfaces, Ruled.
Control No.:   4527053

Author:        Mangelsdorf, Ernst Ludwig, 1882-
Title:         Eine neue Abbildung des linearen
                  Strahlencomplexes auf dem Punktraum / von Ernst Ludwig
                  Mangelsdorf.
Published:     Strassburg i. E. : C. Müh, 1906.
Description:   32 p., 1 leaf ; 23 cm.
LC Call No.:   QA608.M27
Notes:         Lebenslauf.
               Thesis--Strassburg.
Subjects:      Complexes.
Control No.:   10089557

Author:        Moore, Clarence Lemuel Elisha.
Title:         Classification of the surfaces of singularities
                  of the quadratic spherical complex ...
Published:     Baltimore, The Lord Baltimore Press, the
                  Friedenwald Company, 1905.
Description:   [1], [248]-279 p. 31 x 25 cm.
LC Call No.:   QA608.M82
Notes:         Thesis (Ph. D.)--Cornell university, 1904.
               From the American journal of mathematics.
Subjects:      Complexes
Control No.:   6801787

Author:        Newman, Philip, 1904- [from old catalog]
Title:         The geometry of the planar [2, 2] connex
Published:     New York, 1941.
Description:   14 p., 1 l. 27 x 20 cm.
LC Call No.:   QA608.N45
Subjects:      Connexes.
Control No.:   8785819

Author:        Oppenheimer, Hermann. [from old catalog]
Title:         Anwendung des Amesederschen nullsystems...
Published:     [Horb, Druck von H. Christian, 1892]
Description:   p. cm.
LC Call No.:   QA608.O62
Subjects:      Line geometry.
Control No.:   7732587

Author:        Owens, Helen (Brewster), Mrs. 1881- [from old
                  catalog]
Title:         Conjugate line congruences of the third order
                  defined by a family of quadrics ...
Published:     [Baltimore] 1913.
Description:   cover-title, p. [323]-356. diagr. 31 cm.
LC Call No.:   QA608.O8
Subjects:      Congruences (Geometry) [from old catalog]
Control No.:   7297988

Author:        Pell, Alexander, 1857-1921.
Title:         On the focal surfaces of the congruences of
                  tangents to a given surface.
Published:     Baltimore. The Friedenwald company, 1897.
Description:   1 p. L., 34 p., 1 L. 31 x 25 cm.
LC Call No.:   QA608.P38
Notes:         Biographical sketch.
               Thesis (Ph. D.)--Johns Hopkins university.
Subjects:      Congruences (Geometry)
Other titles:  Pamphlets. Mathematics. Quartos. v. 2, no. 9.
Control No.:   8673484

Author:        Peter, Arnold i. e. Julius Arnold, 1868- [from
                  old catalog]
Title:         Die flächen,
Published:     Christiania und Kopenhagen, A. Cammermeyers
                  forlag (L. Swanstrøm) [1895]
Description:   cover-title, 87 p., 2 l. 23 cm.
LC Call No.:   QA608.P4T
Subjects:      Complexes. [from old catalog]
               Surfaces. [from old catalog]
Control No.:   5866888

Author:        Pierce, Archie Burton.
Title:         Classification and properties of dual conical
                  congruences ...
Published:     Zürich, Druck von Meyer & Hendess, 1903.
Description:   60 p. 23 cm.
LC Call No.:   QA608.P6
Notes:         Inaug.-diss.--Zürich.
Subjects:      Congruences (Geometry)
Control No.:   272898

Author:        Schaumberger, Hugo, 1875-
Title:         Ueber einen besonderen Linienkomplex vierten
                  Grades ...
Published:     Giessen, Von Münchow'sche Hof- und Universitäts
                  Druckerei (O. Kindt) 1904.
Description:   25, [1] p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA608.S31
Notes:         Lebenslauf.
               Inaug.-diss.--Giessen.
Subjects:      Complexes
Other titles:  Über einen besonderen Linienkomplex vierten
                  Grades ...
               [Pamphlets. Mathematics. 1841-1906] v.16.
Control No.:   8673185

Author:        Shively, Levi S. (Levi Stephen), b. 1884.
Title:         A new basis for the metric theory of congruences
                  ... by Levi Stephen Shively ...
Published:     Chicago, Ill., 1921.
Description:   1 p.l., 28 p. 24 cm.
LC Call No.:   QA608.S4
Notes:         Thesis (PH. D.)--University of Chicago, 1917.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries."
Subjects:      Congruences (Geometry)
Control No.:   1690225

Author:        Thomas, Joseph Miller.
Title:         Congruences of circles studied with reference to
                  the surface of centers / [by] Joseph Miller Thomas.
Published:     Philadelphia : [s.n.], 1923.
Description:   p. 221-237 ; 26 cm.
LC Call No.:   QA608.T5 1923
Notes:         Thesis (PH. D.)--University of Pennsylvania,
                  1923.
               "Reprint from Annuals of mathematics, vol. XXV,
                  no. 3".
Subjects:      Circle.
               Congruences (Geometry).
Control No.:   9200474

Author:        ÷Ti÷tçeica, George, 1873- [from old catalog]
Title:         Sur les congruences cycliques et sur les
                  systèmes triplement conjugués ...
Published:     Paris, Gauthier-Villars, 1899.
Description:   2 p.l., 56 p., 1l. 28 x 22 cm.
LC Call No.:   QA608.T55
Subjects:      Congruences (Geometry) [from old catalog]
               Differential equations, Partial. [from old
                  catalog]
Control No.:   5871474

Author:        Uven, Marie Johan van, 1878-
Title:         Conforme afbeelding door stralencongruenties ...
Published:     Utrecht, Gedrukt bij J. van Boekhoven [1908]
Description:   5 p.l., 140 p. fold. pl., diagrs. 30 x 23 cm.
LC Call No.:   QA608.U8
Notes:         Proefschrift--Utrecht.
Subjects:      Congruences (Geometry)
Control No.:   1217578

Author:        Veblen, Oswald, 1880-1960.
Title:         Geometry of complex domains : a seminar conducted
                  by Professors Oswald Veblen and John Von Neumann, 1935-36. /
                  First term lectures by Professor Veblen, second term lectures
                  by Mr. J.W. Givens, notes by Dr. A.H. Taub and Mr. J.W.
                  Givens.
Published:     Princeton : The Institute for Advanced Study,
                  [1937?].
Description:   231 leaves : diagrs. ; 28 cm.
LC Call No.:   QA608.V4
Dewey No.:     512.86
Notes:         Leaves variously numbered.
Subjects:      Complexes.
               Transformations (Mathematics)
               Generalized spaces.
Other authors: Von Neumann, John, 1903-1957.
               Givens, James Wallace, 1910-
               Taub, Abraham Haskel, 1911-
Other authors: Institute for Advanced Study (Princeton, N.J.)
Control No.:   9724290

Author:        Weiler, Adolf, 1851- [from old catalog]
Title:         Über die verschiedenen gattungen der complexe
                  zweiten grades ...
Published:     Leipzig, Druck von B. G. Teubner, 1874.
Description:   1 p.l., [145]-207 p. diagrs. 24 cm.
LC Call No.:   QA608.W42
Subjects:      Complexes. [from old catalog]
Control No.:   8201555

Author:        Wood, Frank Edwin, 1891-
Title:         On certain relations between the projective
                  theory of surfaces and the projective theory of congruences
                  ... by Frank Edwin Wood ...
Published:     [Lancaster, Pa., New York, 1922]
Description:   1 p.l., p. 386-408, 1 l. 28 cm.
LC Call No.:   QA608.W6
Notes:         Thesis (PH. D.)--University of Chicago, 1920.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 23, no. 4, June 1922."
Subjects:      Surfaces.
               Congruences (Geometry)
Control No.:   2162363

Author:        Zaalberg, Albertus Lodewijk.
Title:         Differentiaal-meetkundige eigenschappen van
                  stralenstelsels ...
Published:     Leiden, S.C. van Doesburgh, 1905.
Description:   xi, 120 p. 23 cm.
LC Call No.:   QA608.Z2
Notes:         Proefschrift--Leiden.
Subjects:      Congruences (Geometry)
Control No.:   1689546

Author:        Zindler, Konrad, 1866-1934.
Title:         Liniengeometrie mit Anwendungen, von Dr. Konrad
                  Zindler ...
Published:     Leipzig, G.J. Göschen, 1902-
Description:   v. diagrs. 20 cm.
Series:        Sammlung Schubert XXXIV, LI
LC Call No.:   QA608.Z8
Notes:         Series title also at head of t.-p.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Line geometry.
Control No.:   5867049
