#+STARTUP: showeverything logdone
#+options: num:nil

This was one of the things we talked about in Atlanta.

Following Ray's suggestion to think about rewriting the law
from scratch in a way that would suit the contemporary world,
here's one contributed idea.  

That since information is "global" these days, because of the "global"
nature of the internet (albeit sometimes subject to the whims of nations),
perhaps "copyright law", or whatever its replacement should be called,
should also be "global" in nature. --[[file:jcorneli.org][jcorneli]]

You may also want to look at the [http://www.ipcharter.org/ Aldephi Charter].

This was
[http://yro.slashdot.org/article.pl?sid=05/10/16/2156221&threshold=5&tid=99&tid=17 discussed]
(for better or worse) on slashdot. --[[file:norm.org][norm]]

I have very serious reservations about global law and am opposed to it
given the current situation.  United States copyright law is based on
the principle that the purpose of copyright is to promote progress in
the arts and sciences whilst copyright law in most of the rest of the
world is based on the idea that an author has an intrinsic right to
his/her work.  Unless the rest of the world first accepts the
conception given in the U. S. constitution, I think that any attempt
at a global law would be disastrous.  In particular, consider
WIPO. --[[file:rspuzio.org][rspuzio]]

: A couple points: First, the right /to be identified as the author/
is the one that comes to mind for me in non-US copyright law, and while
I don't know the details, that single right is the one that we'd been
focusing on in our conversations.  Second, an international law might
not be as relevant as a world-wide license.  In the end, I'm not
going to cling to the international nature of the law as a driving point, but
I do think that if we can put together a proposal for the US, we should
then ask ourselves whether it can be "continued" to a proposal that would
apply on a world-wide basis.  --[[file:jcorneli.org][jcorneli]]

You're right --- I might have been a bit panicky there (which is not hard to do, given the sorts of abuses that have been prepetrated).  Perhaps the right thing to do is to pick and choose the best features from the different laws around the world to combine into the new proposal.  So far, two ideas seem to be:

 1. (From U.S. law) The purpose of copyright is to promote progress in the arts and sciences.

 1. (From U.K. law) The author of a work has a right to be recognized as such.

--[[file:rspuzio.org][rspuzio]]
