#+STARTUP: showeverything logdone
#+options: num:nil

Recently, there has been a flurry of discussion surrounding how to
establish and build the organization.  An important issue here is
exactly what purpose the organization serves.  At least to me it seems
that, when considering such issues as roles within the organization or
the role which members of the community might play, it is not possible
to come to any definitive conclusions until one understands exactly
what role the organization plays with respect to the community.  

Since CBPP is relatively new, at least in the computerized form, there
is no established role for the organization and no a priori reason to
expect that such an organization should fit into some pre-existing
classification.  Rather, it seems that its role is somewhat analagous
to several different sorts of existing organizations.  Therefore, this
role needs to be considered and discussed.

As a starting point for such a discussion, one may take Aaron's
manifesto.  From that document and from thoughts informed by various
discussions, some possibilities come to mind.  These analogies to
existing well-established types of organizations might serve as
sources for relevant background material and models. --[[file:rspuzio.org][rspuzio]]

*** The Organization as Broker

The organization serves as some sort of brokerage firm or advocacy
organization to negotiate for resources which the community needs or
wants, promote the causes and productions of the community within the
wider world, and publicize the efforts of the community, thereby
attracting new members and supporters.

*** The Organization as Manager

The PM community is centered around a common resource, the PM website.
The purpose of the organization is as some sort of management and
development corporation.  In this respect, it is similar to other
sorts of organizations which mamage and develop public goods, such as
an organization whose purpose is the upkeep and improvement of a
public park or a utility.
