#+STARTUP: showeverything logdone
#+options: num:nil

The Hyperreal Dictionary of Mathematics is a step in a much broader
Simulationist Programme, which includes, in the real world, things
like science, mathematics, the economy, GNU, and even things like the
Internet and (in a sense) your mind.  For the mind is but a reflection
of things around it -- an involuntary simulation -- and humans have,
over time, invented various strategies for communicating between these
simulations, and for making them "happy".  Thus, science existis that
we might find food & shelter amid the wilderness; mathematics exists
that we may count correct change & send space probes to scope out
distant planets for possible colonization; the economy exists that
bananas grown in Costa Rica can be sold in Minnesota for 99 cents/lb.;
GNU exists so that everyone in the world can have access to free or at
least cheap software that anyone can make improvements to without
starting from scratch; the Internet exists that we may talk about
ourselves & our friends on !LiveJournal, buy books with one click on
Amazon, keep tabs on the political process in Washington such as it is
through CNN and the congress's own website; and your mind itself
exists -- because it has to.  Echoes & images, memories, insights,
intuitions, -- these all evolved at some point in history because
there was no other option, given the state of the world at that time.

Now we begin to see the necessity of a new kind of mind: a global
mind.  A mind that knows everything anyone knows, or can find it out
in a hurry.  This mind has been aroud in nascent form for as long as
simulationism has.  Within our lifetimes, it will come to take on a
life of its own.

----

Pie in the sky promises come from all over.  Every group seems to
promise rewards without effort, pleasure without investment.  And the
discerning minds of every generation recognize these empty promises
for what they are.

I don't have pie in the sky to offer you: maybe you'll get it & maybe
you won't, and if you get it, maybe you'll realize "I don't even
_like_ pie... although I think I used to.  That's odd."  This is none
of my business.

My business is to offer you a job: hard work, for little or no pay.
My business is to fill you to the brim with community spirit; to ask
you to lay it on the line... &c. ... OK, you get the point.

If you don't _want_ to do this, you don't have to.  Maybe you'll get
to freeride on the efforts of others.  But you'll be missing out on a
lot of excitement, and you'll never know what else you might miss out
on.

"But what is it you're asking me to do!?" you ask.

I'm trying to motivate you to help bring about a better future.  Not
just for yourself, because honestly, I couldn't care less: but for
everyone.

How you do that is up to you, of course.  I have my own ideas about
what _I_ want to do to help bring about a better future.  If they
strike your fancy, you might help with them.

----

The world around us has always been changing.  These days, we notice
it changing in more and more fundamental ways.  People are changing
too.  This is not simply a matter of sociological trends.  People, as
a species, are entering a new era, a new phase of existence.  If you
hadn't noticed, then maybe an example would help.  Your fine, squishy,
body resembles that of a rhinoceros, in the sense that it bears the
mark of a bygone age, and is hardly suited to the exigencies of Today.
You may manage to hang onto this body for the rest of your life, as
will numerous humans in the wilder regions of this world.  But I
wouldn't count on it.  If you or your friends have childre,n I think
the likelihood of them hanging onto their fine squishy bodies will be
next to nothing.

(But I'm not a doctor.  I'm a mathematician and computer scientist and
the reluctant author of this Manifesto.  Maybe I should say aspirant
mathematician, because my abilities haven't really been put to the
test.)

Your body probably won't be the first to go; more likely, it will be
your mind.  If you happen to be one of the lucky ones I'm talking
about, this shouldn't bother you much.

Because, you'll be getting a new mind, much shinier than the old one,
and much smarter.  It's true, you might miss your old mind some (like
you miss your childhood), but you'll find yourself living in a new &
more prosperous happier world...

----

Social movements aren't the work of individuals.  Well, they are, but
_many_ individuals, that's the point.  While you might not have any
particular interest in mathematics... maybe that isn't important.
Because the Hyperreal Dictionary of Mathematics isn't just for mathy
types.  It isn't just for computer users, either.  A pack of 3X5 index
cards & a pen & a bit of time and thought, and you can build yourself
a little hyperreal dictionary on any topic you might find interesting.
By which I mean, a dictionary covering some topic completely, more or
less -- as completely as can be given the circumstances -- that you
can add to or change around at will.  I use mine to keep track of my
thoughts: if something seems conceptually important, I make a card
about it.  Then I can use this collection of cards like a personalized
I Ching.  And I can play games with my friends who have decks of cards
like these, where we try to connect the concepts that each of us finds
to be important with the concepts that the other(s) find to be
important.

Of course, if you put these things on the computer & get a suitable
system for keeping track of comments & connections set up, you could
play these sorts of games with anyone in the world.

The Hyperreal Dictionary of Mathematics is my name for the game you
play when the concepts come from mathematics, and the computer is
taught how to play this game.

----

Why is math the next logical thing to make computers proficient at?
They are alreayd good at communication -- sending a message from one
corner of the world to another -- and they are good at following
directions (very good at that); they are good at Chess, and they are
good at sums -- in fact, they are very good at all sorts of
mathematical problems, as long as someone tells them what to do, or
how to figure out what to do.  But _math_ -- real math -- is both
about following directions, and about creatively figuring out
solutions to new problems based on what you already know.

We might teach a computer how to do sums, thes; indeed, it already
knows _that_; and we could probably teach it simple algebra problems
without too much trouble, solving equations, that kind of thing.  We
might have considerably more trouble teaching it about geometry --
because it can't see -- but I suppose they must teach geometry to
blind children, so maybe we could teach it something like that.  And
we could teach it a _lot_ of definitions, and some basic strategies
for doing proofs.  And then we can see what it will do.  Probably it
will fall flat on its face; but then, so did the first Chess
computers.  After a few decades they were much better at Chess.

You have to walk before you can run.

Right now, we're just ramping up to the point where we can usefully
teach the computer anything new about math whatsoever.

----

It seems like in art and science -- in life -- we are always starting
over again.  You never step in the same river twice (unless it is Paul
Bunyan's Round River) -- but still, it seems we're always encountering
known territory anew.

Are we cursed to live the same day over and over again, like in
"Groundhog's Day"?  Or is it curse enough to have to live day after
day, always slightly different, always somehow the same.

In ancient Greek mythology, there was a land called Hyperborea. There,
the sun never set, and a hale & fair race (we can only assume, Nordic)
lived long & prospered.

To us, of course, a sun that never set would be something of a curse,
too.  We need our rest.

Still.

In some Zen monastaries, once a year they do something called 7-days-as-1-day,
where they don't sleep for 7 days.  They say, when you are tired, your enemy
is also tired.  To not go that last day could be a real shame; when the potential
promize is enlightenment.

Light again.

On the 7th day, do you know how many days came before?

Probably we will always be starting over as individuals.  But as
something _besides_ individuals, we can grow.  Meaning and culture can
build.

Perhaps the life of culture -- especially now, in the era of world
culture -- is living one continual day.  Perhaps we are in Hyperborea
after all, and never realize it.
