#+STARTUP: showeverything logdone
#+options: num:nil

One way which we might be able to raise some money for PlanetMath is by
offerring sponsorhip opportunities for businesses.  The way this would
work is that we would approach marketing departments and ask them to 
sponsor PM at some level or underwrite some event or project.  To be
sure, because PM is a tax-exempt non-profit organization, we cannot
advertise in the strict sense of promoting products but we can name
various companies as sponsors in more or less prominent places, but we
would be contacting the same people and the underlying economics is
quite similar --- in exchange for a payment, we would provide publicity
which would help make a company be known to an audience and perhaps also
improve their image by presenting them as a patron of the sciences; the
value of a sponsorship opportunity is likewise determined by such factors
as the size of the audience and its demographics.

To start the discussion, here are some possibilities:

General sponsorship:

 * $1000 and up:
Be listed on the great wall of donors as a sponsor and have a link
to your company's homepage.

 * $5000 and up:
In addition to being listed as a sponsor, be listed on the top of PM pages 
and have your company's logo displayed there.  The idea here would be that,
in lieu of the Google advertisement, we would have a "thank our sponsor"
spot which would link to the company's homepage.  Every time the computer
serves a webpage, it will place a company from the pool in that spot.

Specific sponsorship:

 * $12000:
Underwrite the [[file:Free Math Award.org][Free Math Award]].   Your company will be named on the award 
(e.g. "PlanetMath / [http://suburbanjungle.com/w/20021028.html Amalgatronix ]
Award for Free Mathematical Content")
and on anouncements. press releases, awards ceremony program, and the like.
$2000 of the sum will be offerred as a prize.  (We could get cute and
award something like $1,618.03
or $2.718.28)

 * $ 15000:
Underwrite the PM annual meeting.  Your company will be listed as sponsor
of the meeting in all promotional literature, advertising, programs, etc.
pertaining to the meeting.

In order to underwrite renovating their headquarters, the MAA is selling
sponsorships of bricks --- for a certain feee, your name goes on a brick!
A close analogy might be sponsoring an entry, but this is not so good because
entries come and go.  A better idea might be to offer sponsorship of
subject areas.  For a certain fee, a donor would be listed on all entries 
pertaining to a certain subject area in a manner somewhat like the little
plaques on park benches.  Likewise, we could also offer sponsorship of
sections such as books, various fora, and the like.  As with MAA, this 
could be a way of getting money to build new sections and add new
services.  This way, instead of applying for a reseach grant from the
[http://www.suburbanjungle.com/d/19990614.html MegaHuge ConGloMaCo Foundation],
we go to the marketing department of 
[http://suburbanjungle.com/w/20000807.html MegaHuge ConGloMaCo]
instead and ask them underwrite the new section instead.

The amounts and offerrings need to be tweaked some, but hopefully the ideas
are reasonable.  When we sort out the details, we can start writing a brochure 
of sponsorhip opportunities (say as a PM collaboration) and then start
contacting companies and sending out brochures.
--[[file:rspuzio.org][rspuzio]]

I think it looks real good.  Now we just need to generate a roster of 
companies to call, and decide who is going to do it an when. --[[file:akrowne.org][akrowne]]

After thinking about it a few days, I noticed some gaffes and improvements.
Most importantly, something which shows up on all pages of the site should
cost more than something which only shows up in one section.  Here is a
revised catalogue:


 * $1000 and up: (unlimited number of sponsors per year)
Be listed on the great wall of donors as a sponsor and have a link
to your company's homepage.

 * $5000 and up: (up to 63 sponsors per year)
Adopt a subject area.  Your company will be acknowledged on the bottom of every
entries in that subject with a link back to the company website.  20% of the money
will me earmarked for improving coverage in that area, either by projects which
directly target that area or projects which generallly improve all subjects.

 * $10000 and up: (up to 4 sponsors per year)
Adopt a section.  Your company will be acknowledged on the bottom of every
entries in that section with a link back to the company website.  20% of the money
will me earmarked for improving coverage in that area, either by projects which
directly target that area or projects which generallly improve all ections.

 * $20000 and up: (unlimited number of sponsors per year)
Be listed on the top of PM pages and have your company's logo displayed there.  
The idea here would be that, in lieu of the Google advertisement, we would have 
a "thank our sponsor" spot which would link to the company's homepage.  Every time 
the computer serves a webpage, it will place a company from the pool in that spot.

 * $12000: (one sponsor per year)
Underwrite the [[file:Free Math Award.org][Free Math Award]].   Your company will be named on the award 
(e.g. "PlanetMath / [http://suburbanjungle.com/w/20021028.html Amalgatronix ]
Award for Free Mathematical Content")
and on anouncements. press releases, awards ceremony program, and the like.
$2000 of the sum will be offerred as a prize.  (We could get cute and
award something like $1,618.03
or $2.718.28)

 * $ 15000: (one sponsor per year)
Underwrite the PM annual meeting.  Your company will be listed as sponsor
of the meeting in all promotional literature, advertising, programs, etc.
pertaining to the meeting.

--[[file:rspuzio.org][rspuzio]]
