#+STARTUP: showeverything logdone
#+options: num:nil

*  2005-2006

The below list contains all users that
 * joined during 2005-04-07 to 2006-04-07,
 * have earned 200 points as of 2006-04-07.

 name,           points, objects, joined,        last login
 stevecheng      6164    49      2005-07-07      this week
 GrafZahl        2941    26      2005-04-24      February 2006
 cvalente        2410    21      2005-10-23      this week
 juanman         1611    11      2006-02-14      last month
 lars_h          1556    10      2005-06-12      February 2006
 kompik          1474    12      2005-09-04      last month
 aplant          1426    19      2006-01-31      last month
 smw             959     8       2005-04-17      last month
 Mravinci        738     7       2006-03-18      this week
 CompositeFan    732     7       2006-03-06      this week
 RobKing         645     4       2005-05-25      November 2005
 neapol1s        606     4       2005-05-12      January 2006
 Lando47         545     4       2005-12-22      this week
 avf             495     4       2005-05-14      January 2006
 ncrom           465     4       2005-04-06      this week
 Andy Baker      450     0       2005-12-24      December 2005
 thesoulofmynumber       450     0       2005-09-04       October 2005
 Algeboy         437     3       2006-03-10      this week
 kronos          394     3       2006-01-12      this week
 apmc            390     3       2005-04-19      October 2005
 rm50            361     3       2005-07-18      this week
 plinko          355     3       2005-11-30      last month
 guffin          320     3       2006-02-07      last month
 abdollahi       280     1       2005-05-26      July 2005
 porton          270     2       2005-05-03      December 2005
 kahuja          245     2       2005-09-15      October 2005
 florisje        225     2       2005-01-11      December 2005
 manjula6604     220     2       2005-09-17      October 2005
 prat            210     2       2006-03-27      this week
 a4karo          205     2       2006-01-22      this week
 eligetiv        200     2       2005-10-04      December 2005 

In addition there were 53 users with points between 200 and 100.
Total new users around 4200.

*  2004-2005

The below list contains all users that
 * joined during 2004-04-07 to 2005-04-07,
 * have earned 200 points as of 2006-04-08.

 name           score objects joined     last login
 ------------------------------------------------------
 rspuzio        31493 262   2004-07-19   last week
 marijke         2375  21   2005-03-27   last month
 aoh45           2230  22   2004-04-08   February 2006
 evin290         2026  19   2004-06-20   March 2005
 Andrea Ambrosio 1877  16   2004-11-24   last month
 smruiz          1659   0   2004-04-17   last month
 Simone          1532  11   2004-06-29   last month
 GeraW           1491  13   2004-07-28   April 2005
 jonnathan       1178   2   2004-04-14   August 2005
 HkBst           1004   5   2004-08-04   April 2005
 para0doxa        994   3   2004-04-18 
 Cosmin           945   9   2005-03-08 
 FOUKZON          600   0   2004-07-22 
 bloftin          527   4   2004-07-23 
 jduchon          474   0   2004-04-28 
 ncrom            465   4   2005-04-06 
 acastaldo        430   3   2005-01-30
 Wolfgang         397   2   2004-04-29 
 skubeedooo       383   3   2004-05-06
 daveagp          373   2   2004-07-22 
 kamala           368   2   2004-05-13 
 ppirrip          365   3   2004-05-20
 staylor4         350   1   2005-02-15
 nuntius          317   3   2005-02-15
 scypa            295   1   2004-06-15
 snoringcat       265   1   2005-03-27 
 classicleft      244   2   2004-06-11 
 flyer            240   2   2004-05-14 
 mathpeter        225   1   2004-05-13 
 florisje         225   2   2005-01-11 
 amador           215   2   2005-02-28
 Tobi             210   1   2004-09-05 

23 users with score 100-200, around 3800 new users


*  2003-2004

The below list contains all users that
 * joined during 2003-04-07 to 2004-04-07,
 * have earned 200 points as of 2006-04-08.

 user            points objects joined        last login
 ---------------------------------------------------------------
 pahio	         41229	256	2003-08-06    this week
 mathcam	 35963	483	2003-07-16    this week
 CWoo	         25630	197	2003-11-26    this week
 alozano	 23298	173	2003-06-03    this week
 archibal	  9671	55	2004-02-09    April 2004
 gumau	          4230	32	2003-11-06    August 2005
 apmxi	          3941	0	2003-10-06    November 2003 
 jac	          2471	2	2004-01-30    last month
 ocastill	  2400	0	2003-11-28    April 2005
 aoh45	          2230	22	2004-04-08    February 2006
 Grayum	          1700	14	2004-03-10    December 2005
 mathforever	  1662	5	2004-02-05    December 2005
 waj	          1428	9	2004-02-08    December 2005
 Gunnar	          1287	7	2003-11-08    last month
 almann	          1268	11      2003-06-20    January 2006
 whm22	          1265	10	2003-04-08
 Aatu	          1201	6	2003-06-25
 ratboy	           985	10	2003-12-21
 brianbirgen	   818	7	2003-05-06
 scineram	   798	5	2003-12-26
 Sabean	           765	5	2003-06-22
 msihl	           759	4	2003-05-01
 vernondalhart	   750	4	2003-05-07
 perucho	   721	1	2003-05-07
 iddo	           711	5	2003-08-26
 alek_thiery	   607	1	2003-06-19
 Mindspa	   565	1	2003-07-12
 lha	           565	3	2003-09-09
 Gorkem	           557	4	2003-11-15
 olivierfouquetx   504	4	2003-06-04
 dooder0001	   485	3	2004-01-28
 justice	   360	3	2004-03-27
 x_bas	           291	2	2003-08-20
 mike	           260	3	2003-08-01
 debosberg	   260	1	2003-11-13
 ruiyang	   260	0	2003-12-02
 gaurminirick	   255	2	2003-12-02
 uzeromay	   255	5	2004-03-30
 gholmes74	   235	1	2003-12-04
 grouprly	   205	0	2003-12-02
 gmelfi	           205	0	2004-02-27
 kudos	           204	0	2003-06-19
 jamika_chris	   200	2	2003-12-02
 seonyoung	   200	0	2003-12-02
 fremdh	           200	0	2003-12-23
 zeanhzj	   200	0	2004-03-30


25 members with points 100-199
total 3067 new members

The data was collected at 2006-04-07 from PM's user list.

*  Discussion

For users who need more interactivity, it might be fun to have someone managing
the "incoming class" each month.  This might keep those who wouldn't stick
around otherwise tuned in. --[[file:jcorneli.org][jcorneli]]-
 * I have filed quite a lot of requests. At least some of these have
been fulfilled by new users. These might make it a bit easier to start contributing. 
However, they are no solution for keeping users tuned in. 
--[[file:matte.org][matte]]

Something more indidivually active, like pairing a new user with a mentor, would be interesting (if we had the human resources to support that!). --[[file:jcorneli.org][jcorneli]]

Comparing data from 2004 and 2005 show that we are getting more users. We
also have almost twice as many users how start contributing 
(in the 100-200 class).
Your idea of some kind of mentoring could be a really good idea. 
The above data suggest that many users keep visiting PM, 
although they stop contributing quite quickly.  
What about a user survey? This could maybe give 
us some idea of why users stop contributing. 
-- [[file:matte.org][matte]]
