#+STARTUP: showeverything logdone
#+options: num:nil

"Good pedagogy" will mean different things to different people, but certainly it
is related to "good communication" and "good exposition".  There are many
different theories of learning (including IMO simplistic mathematical models),
and different ideas about the role of teachers in learning.  (Of course,
[http://mathforum.org/epigone/math-history-list/dwaydimpken etymologically speaking, "mathematics" and "learning" are closely related].)

* Comparison of Free Math and public schools

While I am not going to weigh in at this particular moment as a proponent of
public schools vs. private schools, or public universities vs. private colleges,
or tutoring vs. autodidacticism, I do want to point out that /mathematics is a
public resource/ and many of the projects discussed on [[file:AM.org][AM]] aim to be public
resources as well.  We are in a somewhat similar situation, financially, to
enterprises like public radio or public libraries -- or public schools.  We wish
to cater to a wide audience, and the Free nature of our work largely rules out
certain ways of making "easy money".  To the extent that we are really creating
a resource for public education, perhaps we need to think about what makes
public schools work.

** Examples of public education that works
From page 147 of /I won't learn from you, and other thoughts on creative maladjustment/ by Herbert Kohl:

 * /Embracing Diversity/ edited by Laurie Olsen, San Francisco, California Tomorrow, 1991
 * /The Good Common School: Making the Vision Work for All Children/ by George Wood, Boston, National Coalition of Advocates for Students, 1992
 * /Schools that work: America's Most Innovative Public Education Programs/, New York, Dutton, 1992
 * /Rethinking Schools/ (journal), 1001 E Keefe Ave., Milwaukee, WI, 53212

* When learning works

Deep, broad, quick, applicable, enjoyable, meaningful -- these are all words
that could describe different conceptions of "good learning".  

If someone understands the foundations of Calculus as found in Real Analysis, the basic mathematical ideas that underly the key theorems, and how these sorts of theorems are proved, that is looked well upon; 
if someone knows a lot of elementary facts about Calculus, and also how they can be used in Economics, Physics, Statistics, and Biology, that is looked well upon;
if someone learns Calculus as a youngster, that is looked well upon;
if someone knows the ins and outs of Calculus as it is used in, say, the standard applications found in Mechanical Engineering, that is looked well upon;
if someone has fun learning Calculus, that is looked well upon;
if someone finds Calculus to be philosophically intersting, and comes away with metaphors that can be used in numerous contexts, that is looked well upon.

I'm using passive constructions here because I'm not sure who "looks well upon"
these different aspects of learning or experience; not everyone, certainly.  I'm
trying to be sort of general and Aristotelian at this point.

Good pedagogy should have as at least one of its effects good learning on the
part of the student or students involved.  Or at least, it would if the students
always responded the way the teacher hoped that they would; it should be obvious
that learning is a two-way street, and that even "good pedagogy" is a somewhat
subjective valuation -- hopefully the student's... though it is conceivable that
there could be a good teacher none of who's students would recognize her or him
as good.

The point I'm really after here is that there are different kinds of learning
that are good, and it probably isn't entirely likely that all students will
learn in each of these good ways.  Sometimes there are tradeoffs that have to be
made in learning, and that is OK.  It might not be completely accurate to say
that it would be "best" if everyone learned well in all of these different good
ways.  Perhaps there are as many different kinds of learning that works as there
are students.  Ideal pedagogy would be capable of identifying what would work
best for every student.  Often in "the real world", teachers end up catering
mostly to the people in the "middle" (whatever that happens to be defined in
terms of at the moment).  This is probably done with the idea that everyone who
is attending can get something out of the discussion.

* When learning fails

There can be many different reasons why someone doesn't learn something that
they "tried to" learn, or something that they were "supposed to" learn.  Not
learning something isn't necessarily a bad thing: sometimes things that one
wants to learn are too hard or too confusing, in which case, by trying to learn
them, one learns instead that one should be doing something else first or
instead.  Something things that one is "supposed to" learn are philosophically
or otherwise offputting, and in this case, one learns, or reaffirms, something
about oneself and one's educational environment (the two do not get along all
that well).

Learning can "fail" before it even begins, if one doesn't try - I have "failed"
to learn Latin, but then again, I don't think I've put more than one hour in on
it.

It can be good not to learn some things: bad habits make a good example.  There
are tradeoffs when learning something requires a compromise of some sort (a time
expenditure is probably OK, but how much time is acceptable?; bending your will
to a certain extent is probably OK, but some things are unendurable; etc.).
Sometimes it is better not to learn something, when the tradeoffs (including the
opportunity costs of not knowing) are disadvantageous.  (Or when the end result
itself is objectionable.)

* What sorts of success are we after?

Speaking for the [[file:HDM.org][HDM]] project, it would be great to be able to make it
possible to learn things that are "difficult" both quickly and well.  I'm not
completely sure how possible this is, but I think that it is easier to do than
the current educational system tends to make it.  It is easier to explore a
physical region if you already have a map.  The HDM is supposed to provide a --
highly detailed -- map (or collection of maps) for mathematics, together with
easy-to-use map-reading instructions.  It would be great to make it easy for
people to do useful, valuable things.  (Hopefully there won't ever stop being a
demand for useful, valuable things -- though the nature of the things themselves
may change with time.)

In general, kinds of successes we are after depend on the goals of our projects.
These should be discussed more throughout [[file:AM.org][AM]].  Warning: these sorts of
discussions can get pretty philosophical.

* Recommended reading

I am currently reading the book "Paradoxes of Education in a Republic" by Eva
T. H. Brann (U of Chicago Press).  It is really a top-notch piece of
philosophical writing, and I recommend it to anyone who is interested in the
educational aspects of the [[file:PM.org][PM]]/[[file:Noösphere.org][Noösphere]] enterprise, or of free
documentation in general.  The work was published in 1979, so you might think it
dated -- I would rather say that the ideas are quite foundational, maybe even
somewhat "timeless", and that contemporary culture really is asking us to
revisit them.  Even if you end up disagreeing with things the book says, and
have to take sick leave to read it, I think it is worth your time: the prose is
delicious, and the ideas thought provoking.  I'll post again when I've finished
reading it. --[[file:jcorneli.org][jcorneli]] Sat Mar 05 02:40:41 2005 UTC

----
[[file:Discussions.org][Discussions]]
