#+STARTUP: showeverything logdone
#+options: num:nil

First of all, when.  I'm proposing Friday afternoons at 4:30 PM, EST (recurring
on a weekly basis).

Second of all, why.  (Since you might be curious.)  To change the mood a little
bit, see if that helps us be more productive.

Third of all, where.  I don't know.  Doesn't PM have an IRC channel set up
somewhere already?

--[[file:jcorneli.org][jcorneli]] Thu May 12 22:24:16 2005 UTC

Yes, #planetmath on irc.endernet.org.  For a fixed meeting time, I don't see anything
but Sunday afternoon/evening working.  But why don't we all just hang out there
and chat whenever? --[[file:akrowne.org][akrowne]] Fri May 13 12:08:07 UTC 2005

By the way, I don't think we're particularly unproductive.  In fact, I think we may
be just about as productive as possible, given that we have other things going on
in our lives.  --[[file:akrowne.org][akrowne]] Fri May 13 12:11:45 UTC 2005

Sunday afternoon could work.  Same time, 4:30 your time?  I'm not sure about
hanging out there all the time - but weekly meetings could be good.  I like the
asynch. nature of the wiki for most day-to-day stuff.  But I will probably check
in sometime before Sunday to make sure my irc client is working. :)

Also, productivity... can be quantified.  I know I've had a certain amount of
personal bullsh1t going on this week (sick, "personal", theft, jobs, rent,
fatigue, bla bla bla) but once that all settles down -- which it should, honest!
-- then, yeah, I hope to be working pretty much at my optimum. :) --[[file:jcorneli.org][jcorneli]]
Fri May 13 14:49:51 2005 UTC
