#+STARTUP: showeverything logdone
#+options: num:nil

Public domain content is relevant to all of the projects here in different ways,
and it is an interesting topic in and of itself.

My initial reason for making this page is to make it a hub for the various
discussions that are going on about public domain on the wiki.

The pages so far are:

 * [[file:Public domain content and PM.org][Public domain content and PM]] -- General discussion of public domain math.
 * [[file:finding new content for PM.org][finding new content for PM]] -- list of various concrete sources of public domain math
(or other FDL compatible things to be ingested/integrated)
 * [[file:Copyright renewals for math books.org][Copyright renewals for math books]] -- A project to find post-1923 books that have
fallen into the public domain.

----

Note that even though these pages focus on math, they do contain some
information that is relevant for non-math subjects too.
--[[file:jcorneli.org][jcorneli]] Sat Apr 30 02:37:01 2005 UTC
