#+STARTUP: showeverything logdone
#+options: num:nil

Source material is [http://www.echo.ucla.edu/volume3-issue2/kassabian/kassabian.pdf this essay by Anahid Kassabian].
Perhaps not entirely remarkable in its own right as an article, but the ideas
seem pertinent (not at all /impertinent/) and besides, I love the lingo!

The key term is /ubiquitous subjectivity/ (in the paper, this
subject is examining music).  Like "ubiquitous computing."  Here the
progression is: music is everywhere around us, and symmetrically, we
are paying attention to music everywhere; from this, the question
becomes, who is this /we/?  "We" becomes a ubiquitous subject; it
isn't that /I/ hear music everywhere, but /we/ do.  The comparison
is made to "SETI@Home" -- people as nodes in a distributed
subjectivity project.

Well, whether or not you buy this idea as applies to music, let's take
it and run with a little while as it might be applied to, guess what,
mathematics.

It seems intuitive to compare and contrast /ubisub/ with the
isolated subject (/isosub/) we heard about from R. L. Moore.  I say
"compare and contrast" because in some ways the comparison is tight;
isosub and ubisub in some ways mirror each other.  After all, the idea
of isosub is that each subject is interacting with the /same/
material in eir own way.  That isolated subjectivity is not the same
as an isotropic subjectivity is evidenced by the fact that we're all
different, we all bring our own views and perspectives to a given
object.  In the Moore Method, these views are kept separate from one
another; this is right proper [[file:a paroxysm of parallax|parallax.org][a paroxysm of parallax|parallax]] for
you.

Contrast that with teamwork, in the results are not "mine" but "ours".
Again, the analogy to SETI (or any other distributed computing
problem) makes sense.

In teamwork and collaboration, individual perspectives may still
matter a lot; but no doubt, sometimes the the distinction between
different perspectives may blur.  It isn't so much that we don't see
things in different ways, but that we come to agree upon certain
things as well.  Moore would of course regard this as very dangerous.

I'm not so sure: and moreover, I suspect that this sort of
subjectivity has been around for a long time (even if the theory
is new).

----

I suppose that along with ubiquitous subjectivity one might
also find [[file:ubiquitous agency.org][ubiquitous agency]].  (I don't completely understand
the relationship between agent, subject, and object... but
then again, I don't know if anyone does.)
