#+STARTUP: showeverything logdone
#+options: num:nil

Given the nature of the math community and the fact that
PM is actually /part of/ this thing, perhaps a better
question would be what /can't/ they offer PM.  

But to make one easy statement on the proposed topic --

After I told Jean Taylor both what PM
does and what my research interests with it are (I talked
some about finding patterns in social systems, which I thought
might interest her, since she has been interested in patterns
in (other) natural systems), she said she didn't know what
she could contribute to that.  Well, we were in a rush
and so I didn't have my reparteebest  ready immediately,
I just said I'd email her.  But I think the best answer
is that you can always contribute your work (writing)
to PM.  As I've  said elsewhere, better support for research
writing on PM is vital.  If it was easy enough for Jean
to upload her writings (whatever parts of it she has copyright to)
and she wanted to contribute that, it would be a great contribution.
And immagine if 100 other first-rate mathematicians also contributed,
say, 5 articles a piece.  Odds are, we'd soon see an additional
5000 entries in the encyclopedia, to define the important and
as yet not PM-defined terms from those papers.

Another thought that occurred to me is that PM should really consider
sending a contingent to the International Congress of Mathematicians
(in Madrid, August, this year).  The two groups share the global
perspective, and this would be a good way to network with people from
around the world.

There are many networking possibilities.  I forgot to mention that
I met Robert Ossermann (again) at dinner; he presides at MSRI.
I did say somewhere that I think it would be great if PM could
become both a physical and "virtual" Institute, and I got to
tell Robert that MSRI is my psychic model for this organization
(which is true).  I think it would be great if we could collaborate
with them on a summer school / hackfest at some point in the
not too distant future.

Obviously a very partial list (see first paragraph above).  I'd
like to see more suggestions... about things we can ask math
people and math organizations to do that they might very likely
want to do once they know they can. --[[file:jcorneli.org][jcorneli]]
