#+STARTUP: showeverything logdone
#+options: num:nil

; formatting : Some people need to use screen readers or big fonts or Braille.
Some people just like to look at things in a certain way.  Free Math can be
transformed into any format anyone cares to put it in, and redistributed
in that format, whether for money or at no cost, 100% legally.

; access : Many people do not have libraries or trained teachers or other
high-cost educational resources at their disposal.  Free Math is available to
anyone who has a computer, and gives access to mathematical knowledge and to the
process of creating mathematics.  Proprietary online resources may also provide
people with access to mathematical knowledge, but Free Math emphasizes the
rights of the user: to modify, redistribute, and resell content.  This promotes
wider distribution, and helps create economic incentives for a wider range of
individuals to participate in the spread and growth of mathematical knowledge.

; examples : Sometimes it is hard to figure out how to do something with !LaTeX
or other computer languages.  Access to the source code that generated the
specific examples that one is viewing can help one learn how to do similar
things in one's own work.

; utility : Source code makes other useful applications possible, including
searches for matching information and other forms of enhanced computerized
access.  As opposed to non-free works that also come with source, uses for Free
Math are limited only by the imaginations of the users, not by that of the
original author.  New resources based on existing Free Math resources can be
created without compunction.

; naturality : Mathematics itself is already free in many ways (as are many
other areas of human inquiry), in that one can already reformulate and propagate
ideas.  Free Math is well adjusted to what people actually do in day to day
practice, and it gives people a chance to relax about some things that would
otherwise be legally questionable (e.g. copying extensively from a textbook and
posting the content on a public site on the internet) but that might be
pedagogically or scientifically useful.

----
[[file:Discussions.org][Discussions]]

[[file:What is Free Math.org][What is Free Math]]
