#+STARTUP: showeverything logdone
#+options: num:nil

I think that a manifesto (at least, these days) is supposed to be
a document that stands behind a social movement.  Everyone from
[http://www.law.indiana.edu/uslawdocs/declaration.html Jefferson et al.] 
to [http://www.anu.edu.au/polsci/marx/classics/manifesto.html Marx and Engles] 
to [http://www.infopool.org.uk/6003.html Debord et al.] 
to [http://www.gnu.org/gnu/manifesto.html Stallman] 
to [http://emoglen.law.columbia.edu/publications/dcm.html Moglen] 
to [http://www.thecourier.com/manifest.htm Kaczinski]
to [http://homes.eff.org/~barlow/Declaration-Final.html Barlow]
has at least managed to make that part fairly convincing.

I don't think the issue is that these people /understand/ social movements all that much better
than I do; but neither do I claim to be an expert in that area at all.  I am, however,
friends with one and you can read some of what he has to say about these things
[http://www.rand.org/pubs/monograph_reports/MR1382/MR1382.ch9.pdf here].

I think the problem is that the HDM project does not necessarily lend
itself to being or becoming a social movement.  Perhaps it will, but
at this point, I doubt it.  

Now, I do think something like "free math" or "computer math" might be a social
movement (although the later tends to be typically woefully apolitical).

The HDM project, although it is political, seems somewhat unlikely to reach the
"oppressed" and/or "deprived" groups that it targets before it is close to ready!  These groups include
students, who don't know there is a problem, professors (similarly),
as well as persons without information access (again, similarly, but
for a different reason, although they may have a sense that something
is wrong or unjust that where most more-privileged people have trained
themselves to ignore the issues).  How to reach out to these people?
And what would reaching out to them accomplish?

I would hope that HDM might function something like Morpheus's rag-tag
group of geeks with guns, finding like spirits with capabilities to
help the cause.  

(Aside: Isn't it ironic that I'm such a fan of the rise of the
machines, and yet regard Morpheus as a sort of role model?  Well, I
think I'm coming to see the situation as sort of reversal of the one
we saw in the Matrix.  We already live in a "Matrix" -- but it is a
cultural matrix, not a computer matrix.  Whether this matrix is "real"
or not is perhaps not very significant.  Maybe we can get into those
parts of the philosophy later.  The point is, that it imposes limits
on people who may not even know the limits that are being imposed, or
who accept them willingly, or who are perhaps mostly powerless --
and/or disempowered -- to do anything about it.)

But this may be unlikely too.  If we're trying to run this show like
/that/, then I think we have not been very successful.

So, not through recruiting individuals, not through a social
movement... what's left?

A few options I can see.

 1. DIY.  That's right.  This crew.  No messing around.  We code, learn
enough metamathematics & linguistics, etc., to at least build a good
proof of concept.  To some extent this is what we've been trying to
do.

 1. Sell out (at least to some extent).  Follow the brilliant example of
F. H. Hsu & his team and find a corporate sponsor.  This may depend on
prior success of #1.  I don't mean to sacrifice the /principles/ of
the project, but simply to focus it on one base of operations.  Maybe
this isn't really selling out at all.  Another similar option would be
to try to get a research grant.  Again, we probably need #1 and maybe
a bit more.

 1. Go against what I said and actually try to make this into a social
movement and/or copyright terrorist faction a la Morpheus et al. --
write letters, put up fliers, tack manifestos on the front of
departments, libraries, churches, and very small rocks.  Again, this
could be combined willy-nilly with #1 and #2.

Well, I remain hesitant about #3, and #2, but that doesn't mean I
haven't been working on them.  I've also been working on programming,
at least some.  It seems to me that we're more in a phase were
division of effort between the various options takes away from any one
of them; but maybe I'm wrong.

And with regard to any one of these options... I feel weak.  Why?  Am
I bad at programming, networking, rhetoric?  Perhaps; I've only been
practicing these things in a dedicated way for about 3 years.  That
may not be enough time given my native skill.  As for the current
crew, they are in about the same situation as I am.  I think each of
us is improving in skill, and our efficacy as a team is also
improving.  But is it enough... and for what?

-----

Invest in this: "How to Master the Art of Selling" by 
Tom Hopkins --

http://www.tomhopkins.com/store/product.php?productid=16251&cat=254&page=1

Invest in the hardcopy ($29.95), which is probably available at 
your local mega-bookstore, instead of the paperback; you will want
a permanent, indestructible copy for future reference and
study.

The book will repay the investment in many ways. You will be
successful in every aspect of life that requires persuasion.

People tend to think of *selling* as something underhanded
or despicable, like politics. Tom debunks those ideas. Selling
can be a very moral profession, it all depends on the person
and how s/he uses the gifts. This applies to the professional
salesperson as well as the job seeker, underground revolutionary
leader, guy looking for a date, etc. It simply is not necessary
to deceive in order to sell a good product or service. 

Here is an example from the book: use the word "invest" instead
of "pay" (as in "Why you must pay".) 

--[[file:ocat.org][ocat]]

"[[file:why you must pay|Why you must pay.org][why you must pay|Why you must pay]]."  Er... I can explain that.  Well, actually, 
I'm not sure.  We all have our darker angels.  (If
you believe the false etymology angel->angle -- which there's
no particular reason to -- then its a highly
[[file:a paroxysm of parallax|parallaxical.org][a paroxysm of parallax|parallaxical]] situation.)  This
"pay" was intended to /sound/ somewhat malevolent.  But I
think it was /meant/ well.  It may be that statements made
in this particular voice need to be quarantined somewhere
relatively non-public.  But I don't think they should be
denied.  Considering the particulars of the situation,
I think it is good to consider
[http://www.barcelona2004.org/eng/banco_del_conocimiento/documentos/ficha.cfm?IdDoc=509 conflict resolution via plastic expression].

There's even another manifesto relevant to this point,
[http://caad.arch.ethz.ch/teaching/nds/ws96/exercises/nds9606/text/Theo_manifesto.html Towards a plastic architecture] (1924).

As for the use of the word "invest" as an alternative, and "selling"
as an approach -- I don't view these things as underhanded or slimy
or anything like that!  They are totally viable ways of looking at
the things we're talking about.  I don't know if I'm fully inclined
to run out and buy the book, but I'll certainly look for it next time I'm
at B&N.  (I love to /read/ books there.)  And if you're already
trained in this artform, please feel free to apply your skills to
HDM anytime!  Remember, "social movements are segmented, polycentric, and networked";
there's plenty of room for another participant & point of view.
Not that HDM is necessarily a social movement at all (as above).

--[[file:jcorneli.org][jcorneli]]


----
[[file:The HDM Manifesto.org][The HDM Manifesto]]
