#+STARTUP: showeverything logdone
#+options: num:nil

* Introduction

On April 4, 2005, Aaron Krowne (lead of the PlanetMath project) went to visit Wolfram Research
in Urbana-Champaign, Illinois.  He was invited to give a technical talk on PlanetMath, and so
gave a talk entitled "How PlanetMath Works". 

Part of the purpose of the trip was to explore connections between PlanetMath and MathWorld or
Wolfram in general.   I'll list some of the ideas for this for discussion here, along with other
thoughts and insights spurred by the visit. --[[file:akrowne.org][akrowne]] Fri Apr 8 21:06:00 UTC 2005

* The Talk

There is a whole page on this Wiki for the talk Aaron gave: [[file:Discussion of Wolfram Talk.org][Discussion of Wolfram Talk]].

* Possible Collaborations With Wolfram

Some potential collaborations are:

 * sponsorship arrangements between Wolfram and PlanetMath                                                                    
 * sharing of PlanetMath content with MathWorld                                                                               
 * sharing of Noosphere with Wolfram projects                                                                                 
 * helping to adopt portions or ideas behind Noosphere for use on MathWorld

Any other ideas?  Comments? --[[file:akrowne.org][akrowne]] Fri Apr 8 21:05:48 UTC 2005

See also [[file:Should Mathematica Become Free Software.org][Should Mathematica Become Free Software]].

* General Discussion

Post here for anything not sectioned out above, especially any questions you might have for Aaron
about his visit.
