#+STARTUP: showeverything logdone
#+options: num:nil

The last day, Sunday, and you'd probably think I'd be most tired of
all.  I can't really tell.  I think I'm probably exhausted.

Right now, I'm back in Austin, on Kyle's couch.  We started out
the morning at around 11 'o' clock (checkout time) waking up and
going to a "Mexican market" in San An.  The market turned out not
exactly to be all that, but it was an interesting diversion, and
provided a chance to get some exercise (walking there and back
to the conference center).

After that, I went to several talks in the undergraduate section,
one talk in the math history section (on Laplace and "sufficient reason",
the latter being a rather hideous thing cooked up by Leibnitz
as a sort of terrible combination of Ockham's razor and the
fruit of the tree of knowledge... to be used in constructing
proofs of things you can observe, or in other words, a triumph
of intuition over formalism; obviously not un-interesting, but
a mite painful to my modern-day sensibilities -- although it seems
to have almost lead Laplace to discover spherical and hyperbolic
geometry, if only he hadn't followed adhered so tightly to the 
arrogance of his own intuition, as he had been taught to do
by the sufficient reason principle -- makes me wonder what we might
be just missing because of the particular foibles of our own intellectual
apparatus), and Frank's talk on "Manifolds with Density".  Not
necessarily in that order.  There were some interesting connections
between the "MWD" talk and one of the ungrad talks, an some
schwarzchild space thing or other.  Apparently Frank had been
working on this topic some time ago.

I think that it is /absolutely vital/ for PM to start really supporting
contemporary research.  As you see I feel very strongly about this.
If even just the research reports from all of the REU's around the
country were uploaded to PM (perhaps reasonable, if free math became
a youth movement), think of how much new content we would have
on a yearly basis -- assuming that these reports were autolinked
to the relevant portions of the Encyclopedia, just think how much
more content.  As well as a premier check on the /relevance/ of
the encyclopedia, and /simultaneously/, a check on the groundedness
of the research.  (I feel I've made this type of argument before.)

Furthermore, when I've talked with people at the conference about
what PM has to offer, I've typically stressed either its usefulness
for research communications (while noting that much of this usefulness
is still "potential"), or its usefulness for teaching and/or curriculum
development (citing the [[file:Adapting_CBPP_platforms_for_instructional_use| 2003 experiment.org][Adapting_CBPP_platforms_for_instructional_use| 2003 experiment]]  as "the canonical example",
but pointing out that this experiment essentially constitutes a beta
test -- more likely a pre-alpha test -- and that significantly more
beta testing is needed before noosphere will really be "universally"
useful for education applications).  I don't think these are empty
promises at all, however, I don't want to be creating preconditions
for a new "AI winter"!  The point is, these are key promises of !PlanetMath,
and I think that is obvious: but these promises need to be worked
on a lot in order to be realized.  (Which, incidentally, could
make a great theme for a white paper to submit to people who
might fund us, eg. NSDL.)

After the talks I went out for margaritas with Kyle and Tobias
and we played a couple card games.  Then it was time for the pre-dinner
reception.

The people who are paying the bills for me to be here should
really say thanks to Frank Morgan for helping me out with my
"debut" here on the math social scene.  Also (not to sound
prideful), they should realize that there may not be anyone
in PM who is so well connected in math as I am (thanks again largely
to Frank Morgan) -- you'll see more about why I say that later.
My point is, I think I was a good choice for someone to go
to this conference, and I think it will have been money well
spent, sending me here.  It is too bad that Aaron couldn't
make it, but several times his reputation preceded him, in terms
of his connections and contacts within the DL world.  These two
universes, math and DL, certainly overlap non-trivially; it
would have been nice to have two of us know more about both
groups, but maybe that will come later.

Anyway, to make a long story short, I talked with Don Albers
(head of various MAA things, including some of the online
stuff), also the president of the MAA, the president of the AMS,
one "Ima" who works on books, the executive director of the MAA,
and a guy named Phillipe who works in the NSF... always putting PM
in a good and contextually appropriate light, and sometimes
talking about my research.  Also Jean Taylor, a mathematician
whose work is related to Frank's (and my old geometry work of course).
Lots of other less "famous" people throughout the conference,
several undergrads, etc. etc.

Its been a great time.  I have to leave for the bus to the airport
in about 2 hours.

* PS

The NSF guy is Philippe Tondeur, the Director of the Division of
Mathematical Sciences at NSF, who is described by John Ewing as being
the person who motivated Ewing's authorship of "Twenty centuries of
mathematics: Digitizing and disseminating the past mathematical
literature"!  Now I think I have a better sense of why we got
on so well during dinner.  I also feel foolish, not to have known
who I was talking to.  I feel like this was the closest to an
encounter with greatness I had at the conference.

----
[[file:2006 JMM.org][2006 JMM]]
