#+STARTUP: showeverything logdone
#+options: num:nil

Today is Thursday.  My first day at the conference.

We arrived at around 4:00 PM.  My talk (actually "Aaron's talk", but I
gave it, using this [[file:outline of PlanetMath and Free Mathematics|outline.org][outline of PlanetMath and Free Mathematics|outline]]),
and I think it went very well.  Someone in the audience helped
me out by loaning me his computer (mine froze up when I tried
switching between X and Aqua, probably another reason I should
jettison OS X soon).  He types in the Dvorak layout, like me, and
asked about possible employment with !PlanetMath after the talk.  I
forgot to get his name and contact information, but if I run into him
again at the conference, I'll find this stuff out.  I told him about
the bounties and the various do-it-yourself funding possibilities.
Oh yes, and someone else asked about whether we were planning
to add !MathML support; I told him I would bring it up for
discussion.

I was just a little tired, having just come from NYC the day before.
But I think I fielded all the questions well and showed the audience
a good time.

After the talk (I was last in the section) I walked around the
exhibit hall and chatted with various people.  I talked to Paul
Fishback, who is a councillor for [http://www.pme-math.org Pi Mu Epsilon] (the national
mathematics honorary society), fishbacp@gvsu.edu.  The first
thing he said when I told him that I work for !PlanetMath was
that "!PlanetMath Rocks!" which I thought was a great way to
kick off the conversation.  On various possible connections
between PM and PME, one idea that came to mind was to look
for students in the overlap who could give lectures at
!MathFest on PM.  There's also the Frame lecture, but I think
it is challenging to get invited to give that.

Next I went to harass the representative of Wolfram Research about
their lack of open source offerings.  He said that they needed to keep
Mathematica closed in order to pay the programmers and testers.  I
basically left it at that.  Maybe I'll have more for him tomorrow.
(I got a postcard from their display that points at http://www.MathematicaGuideBooks.org --
I wonder if the ".org" there means anything.)

I then got captivated by some physical displays put together
by Bradford Hansen-Smith of [http://wholemovement.com wholemovement.com]
that certainly rivaled anything Mathematica could produce (and
plus, were in 3D).  Seems like something worth looking at (not
all math holds up to inspection).  I'm not sure yet about the
philosophy behind this work, but I liked the idea that it was more about the
process than about the individual products on display.

Then I went and talked to one of the co-authors of a book called
Write Your Own Proofs (in Set Theory and Discrete Mathematics).
I told her that I liked the sound of that.  She told
me that the book is based on a modified Moore method, and
explained how she uses it with her students (who are sometimes
challenged by the notion of proof).  I told her that
I think my student is much more challenged at proofs than
hers are at this point (and explained this remark).  I heard
her and the other person working the display laughing
about it as I left.  But really, it might not be such a bad
idea to look at a book like this and see what we can get
out of it for HDM.

From there onto the main Moore method display (this is
Texas, after all), where I got just about everything they
had to offer, including a two-CD set and a bunch of
offprints.  And a little flier with a quote from
Blaise Pascal, that says "All men's miseries
derive from not being able to sit in a quiet room
alone."  I wonder.

Next I talked to Sharon Clarke (sharon.clarke@pepperdine.edu)
about possible connections between Project !NExT and !PlanetMath.
Similar to the conversation with Fishback of PME described
above, but she hadn't heard of PM before, I don't think.
However she promised to forward the message on to the director
of Project !NExT.  (Its my opinion that PM could help a lot
with "new teacher development" for new math Ph. D.'s -- indeed,
it seems likely that we could get some great partnerships
going with this organization.)

And that was it in the exhibit hall.  After that, I met
up with my friend Kyle, met up briefly with my ex-undergrad research advisor
Frank Morgan, and went to chow down on free food at several
receptions.  At one of them I got as many handouts as I could
from the various math research institutes that were being represented
there (including [http://www.msri.org MSRI], for example).  I like these
sorts of places a lot (particularly as I was at one point in my life
one of the first undergrads to get to attend a graduate summer school
at MSRI... where we got a lot of work done and had a ton of fun! --
talk about a great mathematical experience!).  While MSRI does offer
some post-docs, I don't think it is very likely that I could get
one, as I neither have a Ph. D. nor any plans for acquiring one.
Still, I'd love to have a year of paid research time, somehow.
(Maybe we'll talk about this more later.)  The point to make here
is that other PM/AM affiliates might want to look into post-docs
at places like this -- and moreover, we might want to work with
a place like this to get a summer school on computer math, knowledge
communities, etc., going.  And try to be aware, since any of
them might have something like this at some point.  My sense is
that these places are somehow rather close in spirit to PM/AM etc.,
but I don't really know how to tap this psychic connection yet.

That was about the end of the networking and investigation.
Kyle and I chatted some with a friend of Kyle's from UT who also
loves !PlanetMath (as a reference tool), and I basically wound
down for the night.  Not sure what my plans are tomorrow, I think
there is an invited address I want to hear in the morning, then of course I
give another talk at 2:45 (I'll want to plan that one out a little more
too).  Just now, I think I need to rest.  The alarm is set for 7, so
there's no messing around.  I hope I can get to at least a couple
of math talks.  I wonder if there is anything math/computer related,
or logic related, or community related.  One of the invited talks
(I think I missed it) was on voting in agreeable societies; that
sounded potentially interesting.  OK.  Signing off now.
More tommorow.  Will check back on the wiki from time to time to see if there
are any suggestions.

--[[file:jcorneli.org][jcorneli]]



----
[[file:2006 JMM.org][2006 JMM]]
