#+STARTUP: showeverything logdone
#+options: num:nil

* What?

Page for general strategies and discussion having to do with [http://www.ams.org/amsmtgs/2095_intro.html JMM 2006].  We think this meeting will be
a good outreach/networking/pulse-taking opportunity.

We were invited at the suggestion of Rob Minor, I believe.  I ([[file:akrowne.org][akrowne]]) ran into
him at the NSDL fall meeting in Chicago, and talked about potential PM collaborations
(with his company).

We are presenting two PM/AM related talks,

 * [[file:Metamathematical Visions - metadata, learning, and knowledge communities.org][Metamathematical Visions - metadata, learning, and knowledge communities]]
 * [[file:PlanetMath and Free Mathematics.org][PlanetMath and Free Mathematics]]

* Who?

Aaron and Joe were going to both go and give the two above talks, but we decided that 
time and money were too short for both to do this.  So Joe ended up going to
give the talks, and to act as PM's "official" emissary.

* Notes from the field

 * [[file:2006 JMM - Day 1.org][2006 JMM - Day 1]]
 * [[file:2006 JMM - Day 2.org][2006 JMM - Day 2]]
 * [[file:2006 JMM - Day 3.org][2006 JMM - Day 3]]
 * [[file:2006 JMM - Day 4.org][2006 JMM - Day 4]]

* Followup to meeting

 * [[file:2006 JMM Followthrough.org][2006 JMM Followthrough]]

* Shiny bits of paper

It might have been nice to have some shiny pieces of paper or posters
or whatever to hand out or put up.  People at conferences seem to really
go in for these things.  I could probably hand-draw a sign for the
sign area... there is an art store nearby my hotel for paper.

(Speaking of posters, I am planning an interesting hack; to put a
borrowed sign advertising internet security month on the podium
or behind the speaker, whenever there is a speaker important enough
to make this funny and exciting.  I already borrowed the sign,
which I found at some reception.)

--[[file:jcorneli.org][jcorneli]]

* Discussion

We should plan what is going to go into these talks (which will be
given only a month from today!).  The contents should depend on the
probable audience of the talks (something we can do some research on)
and our political objectives, as well as the usual expository objectives.
I think we should take care to plan the talks out along all of these
dimensions before writing them, and maybe a few others besides.
Please discuss, and I'll update with my comments soon. --[[file:jcorneli.org][jcorneli]]

The page [[file:user lib.org][user lib]] contains some themes that I think could gel
up to a section of the "metamathematical visions" talk. --[[file:jcorneli.org][jcorneli]]

----
[[file:Conference planning.org][Conference planning]] / [[file:Talk planning.org][Talk planning]]
