#+STARTUP: showeverything logdone
#+options: num:nil

Having cut loose from my moorings, and shoved off into the Sea of
Known Mathematics on a small but stalwart trawler, hoping to map the
waters and find, if I can, a Northwest passage through hyperborean
realms to the Ocean of Unknown Mathematics and its ports of more than
Oriental splendor; and finding little wind in my sails today, but fair
weather nonetheless, I thought it mete to sound the depth of the
surrounding waters.  However, I find myself unable to fathom them,
save to say that they are most deep indeed.  

Most seafarers stay near the shore, and though this sea is watered by
the Ocean of the Unknown, only the bravest captains will actually
travel 'round the horn to trade or to explore that vaster and almost
wholly uncharted expanse.  They say that the earth is warming and that
perhaps navigable passageways through the Arctic will open any day, so
there may be something to find even where others have failed before.
Still, this is considered to be a fool's quest by many, mostly
permanent residents of small port towns who have made for themselves a
modest living off of the sea's vast wealth.

Some, too, who grew up on houseboats and learned at a very young age
to prefer swimming to sinking.  But despite their comfortability with
the sea, and their familiarity with its major ports, and their noted
skill as navigators, if they are interested in exploring or mapmaking,
which many are, its as a captain in the South Seas, and 'round the
horn they go, some never to return; almost never do they travel to the
North.

Whose is the fool's errand?  By all accounts, its mine.  And yet, a
map has never been made.  How ironic, that for want of knowing the
Known we might be missing our greatest chances with the Unknown
completely; and also, that the ocean's most famous adventurers travel
highways as well-worn as those used by the whales.

* Afterward, by the Author

This piece was written as a hopeful contribution towards understanding the
"Moore/anti-Moore paradox" (as I've [[file:next steps for HDM project][termed it]]).

In less flowery language, this is the problem of learning-anew; on the
one hand we have the Socratic ideal of learning /de novo/ at the
hands of a Good Teacher; on the other, we have the
student-sans-teacher learning from Worldly Experience, including the
experience of written texts.  Both, in fact, are (somewhat grainy)
simulations of "independent learning"; the paradox being that
independent learning can't exist, since "/a student can't learn in a
box/".

The piece hinges on the pun "moorings" /qua/ "Moore-ings"; the
thought being that the Moore method tethers the student to a given
teacher and a given set of assumptions, and furthermore restrains the
student from exploring some interesting parts of the world (e.g. the
library).  The allusion to a "sea of assertions" comes from [[http://www.cyc.com/cyc/technology/whatiscyc_dir/whatsincyc][AI]].

After that, I go on about a "Northwest Passage" - it might be more
apposite to talk about a Panama Canal. ("A man, a plan, a cat, a ham,
a yak, a yam, a hat, a canal: Panama!")  But I had to get the part
about "hyperborean realms" in there.  This has an interesting
[[http://www.kheper.net/topics/Anthroposophy/Hyperborean.html][occult significance]],
as well as being a reference to [[http://www.thefreedictionary.com/Hyperborean][the northern climate]]
I now inhabit, and, moreover, to the ideal mathematical world I imagine the [[file:HDM.org][HDM]] to bring
into being (further information on this term is available [[http://en.wikipedia.org/wiki/Hyperborea][from Wikipedia]]).
The careful reader of Mary Shelley's "Frankenstein" may suspect that there is an allusion to the idea
of Hyperborea therein, especially towards end of the work.  Notice that both pieces assume a basic plot of
north-bound explorations.  Of course, "Frankenstein" is also relevant to the HDM project for other
more obvious reasons.  --[[file:jcorneli.org][jcorneli]], Happy Halloween 2005
 
