#+STARTUP: showeverything logdone
#+options: num:nil

In this section, one can add ideas for the promotion and advertisement of
PlanetMath to the World Wide community, and in particular, to the mathematical
community.

 * [[file:Posters for PlanetMath.org][Posters for PlanetMath]].
 * Merchandise.
 * [[file:Article for FOCUS.org][Article for FOCUS]], one of the MAA publications.
 * [[file:Google Grants for PlanetMath.org][Google Grants for PlanetMath]]

** Discussion of Advertising

This one if for Aaron and any other willing to write some input. I am not sure
if this is the right place for this, so feel free to move it, or remove it and
make it private. I happen to know the editor of Focus, which is one of the main
periodical publications of the MAA (Mathematics Association of
America). Obviously, he has many contacts in the MAA (and beyond). So, it
occurred to me that he would be an ideal person to talk to about PlanetMath. In
particular, I could ask him for advice on how to advertise PlanetMath. Or even
better, I can ask him if he could help us and try to get an interview (with
Aaron and myself?) that would be published in Focus or the online version...So
my question is, what do people (Aaron) think of this and should we do it, and if
we do it, how do we do it? He is a super nice guy, so I can approach him anytime
about this. Another thing to have in mind: is it the right time? Maybe we should
wait a little longer to use this card. --[[file:alozano.org][alozano]]

: I think that we could do an interview or a contributed article in about a
month.  I also have a contact with the MAA - I really think it would be nice to
establish a bonafide partnership with them.  If that happens, then I bet they'd
be asking us to do an interview or article of some sort, or they would have
someone write a feature article about us.  So my suggestion would be to talk to
the Focus editor /about/ !PlanetMath and see what he says about it.  In the
mean time I will also talk to my contact there.  It is up to you about when to
do this, but I'm going to wait until the FEM release is ready (shouldn't be long
now).  In general, I think that more of us should be talking to more people
about PM more often.  Incidentally, you could mention to him that we're looking
for associate editors for the FEM and see if he's interested or if he could
suggest anyone. --[[file:jcorneli.org][jcorneli]] Thu Mar 03 14:05:37 2005 UTC (revised Thu Mar  3 15:15:28 2005)

: I'm always willing to do press.  However, Joe is right, we also want to forge
working connections.  The MAA is not Wired or Free Software Magazine -- their 
business is math, our business is math.  It would be a shame if our only 
connections were pure "advertising".  So please do work with your contacts, but
keep in mind that we need more substantial help than just advertising, from the
appropriate organizations.  --[[file:akrowne.org][akrowne]] Thu Mar  3 20:38:47 UTC 2005

:: Of course, a partnership of any kind with the MAA would be just wonderful,
but I have no idea if that is actually possible. I think some kind of
advertising is a good start. I will talk to Fernando and see what he thinks of
PlanetMath and what he thinks the possibilities are.  He is a *busy* man, so for
sure he would not be able to collaborate with the FEM but certainly he might be
able to suggest suitable volunteers. I'll report back once we chat. --[[file:alozano.org][alozano]]

I happened to skip by Alvaro's home page, and saw that he linked to PM and in
specific some articles he wrote there.  This is another great way to advertise PM, 
besides the direct endorsement and show of pride for one's contributions, it 
will mechanically increase our visibility in search engines.  We should keep this
in mind and promote it as a way to help PM.  --[[file:akrowne.org][akrowne]] Fri Apr 29 05:23:05 UTC 2005


Don't forget to put your favorite entries on your Google Personalized Home Page!  It certainly won't hurt the search engine visibility. --[[file:bloftin.org][bloftin]]

We're getting some not-so-amazing publicity from Ed Pegg Jr:

: The reference I use the most is the website !MathWorld. Full disclosure: I'm now the associate editor. Eric originally designed his Treasure Troves to be a website with occasional printed snapshots. CRC was interested, and printed the first book. Unfortunately, CRC then shut !MathWorld down, which led to immediately to the creation of PlanetMath  (a good site for long proofs), and spurred greater development on Wikipedia. More than a year later, the courts allowed !MathWorld to return. I am personally boycotting all CRC books until they make amends. The !MathWorld website is much better than the book, but I'll still recommend it. http://www.maa.org/editorial/mathgames/mathgames_01_02_06.html

Maybe if we ever write that FOCUS article (or other articles or letters to MAA),
we should cite this reference, and point out that PM isn't just a MW clone,
and is useful for more than just "long proofs"; indeed, that it is a very
different kind of math reference tool from the usual; maybe even to the
point of being something entirely different.  --[[file:jcorneli.org][jcorneli]]
