#+STARTUP: showeverything logdone
#+options: num:nil



: "... I cordially dislike allegory in all its manifestations, and always have done so since I grew old and wary enough to detect its
presences. I much prefer history, true or feigned. ... I think many confuse 'applicability' with 'allegory'; but the one resides to the
freedom of the reader, and the other in the proposed domination of the author."

:: -- J. R. R. Tolkien


I thought this quote was interesting & relevant to a discussion of "freedom".

It makes me think of the translation to film -- say of the Chronicles of Narnia
(originally by Tolkien's contemporary C. S. Lewis, dontchaknow).  The power
of /imagination/ is strong; do filmic versions of stories interfere with
imagination, or enhance it?  I'm a somewhat obsessive person, and I often
particularly like stories that have many cross-over versions of themselves.

On the other hand, I'm not exactly sure what effects cross-over stories have on
my imagination or my appreciation of the "base story".  This is of course
relevant to a discussion of the [[file:scholium system.org][scholium system]] and other "value-added"
texts.  Sometimes it seems like a "with friends like that, who needs enemies"
sort of thing -- after seeing someone else's interpretation of a story,
their version tends to infect your future interpretations.  This also relates to
the Moore method -- which essentially says, let's educate from 1st principles,
rather than from "value-added" texts.

Philosophically speaking, both approaches seem somewhat disturbing!  Perhaps it
has mainly to do with how the added value is used -- i.e., there may be some
techniques that avoid dogma.  But maybe dogma isn't so bad, as long as it is
understood to be dogma.  The "proposed domination" of the author may or may not
hold up to scrutiny.  (I don't know if the "proposed freedom" of the reader
does either!)

Tolkien isn't talking here about all forms of "added value" or "interpretation".
He's talking about ones that force a certain interpretation upon the reader.  I
like the idea of contrasting that with history, which tends to be entirely open
(in a free society) to interpretation.  Construction of history as "allegory"
(manifest destiny, Bolshevik revolution, etc.) seems quite powerful.  Indeed,
sometimes history does seem to "tell a story".  But my guess is that such
stories are typically big lies.  History is a collection of facts (or, more
generally, fact-like statements).  Stories, by contrast, are (perhaps)
collections of assertions.  It seems like a thin separation (and confusing)
between the two, but it may be very important!  I do rather like the idea of
"letting facts speak for themselves".  (This is one reason why things like
"Marxist economics" tend to be somewhat repellent; theories are fine and good,
but without due exercise of control, a theory can easily become dogma.)

And yet... I think of Borges (whose work I would like to study...)
and wonder.  Are allegories so "bad"?  Are they not, sometimes, the
purest expression of an idea?  Is Tolkien really one to talk?  Etc.  I find myself
going around in circles.  Maybe this is the best one can hope for with
philosophical questions of this sort...?

--[[file:jcorneli.org][jcorneli]] Sat May 28 21:30:20 2005 UTC

Here's a random (related) quote from Borges (found on wikipedia):

: "...as I think of the many myths, there is one that is very harmful, and that
is the myth of countries. I mean, why should I think of myself as being an
Argentine, and not a Chilean, and not an Uruguayan. I don't know really. All of
those myths that we impose on ourselves - and they make for hatred, for war, for
enmity - are very harmful. Well, I suppose in the long run, governments and
countries will die out and we'll be just, well, cosmopolitans."

:: -- Borges, 1980


----
[[file:Discussions.org][Discussions]]
