#+STARTUP: showeverything logdone
#+options: num:nil

* Where is Everybody?

AM seems to be getting a bit more traffic these days, but we could still
use more involvement!  At a particularly sad moment, I wrote this
mini essay, and then got some interesting responses:
[[file:Where is Everybody.org][Where is Everybody]].
--[[file:jcorneli.org][jcorneli]] Thu Apr 21 04:17:46 2005 UTC

* Improvements

Things got more lively after a while, see [[file:Feedback.org][Feedback]] --[[file:jcorneli.org][jcorneli]] Sat Jun 25 01:30:32 2005 UTC

* Salon culture

It would be nice to get some more involvement from people working
on other "free cbpp" projects.  Of course, these people may not
really want to put notes on this wiki if they have their own collaboration
systems set up (see [[file:Wikipedia.org][Wikipedia]]), but people should know that they
can have a home here.  I think we should make an effort to contact
project leaders on the list of [[file:Projects.org][Projects]] and give them a standing
invitation (or use public mailing lists for the same in cases where
the leaders may be less interested than the developer or user
community at large).  Furthermore, we should be making an ongoing effort
to identify other projects that match the description given on that
page, particularly young projects who (I think) might most benefit from the sort
of discussions we have on AM.  There are some projects (e.g. probably
tons of wikis) that aren't doing anything particularly novel in 
terms of free CBPP even if they qualify as such, so we may not really
need to link to these.  But it would be a shame to miss anyone who actively
works in the area!  Keep your eyes peeled, and make an effort to get
in touch with other people and groups who might like to participate.
This sort of networking seems likely to help everyone.  --[[file:jcorneli.org][jcorneli]]
