#+STARTUP: showeverything logdone
#+options: num:nil

* Improvements AsteroidMeta's "literature review"

A bunch of old information (and a few new leads) have been given improved
organization.  There is still work to do, and we could use your help.

http://planetx.cc.vt.edu/AsteroidMeta/HDM-related_things_to_check_out

All of the pages in which we've put together collections of links relevant to
free CBPP should appear on this page: 

http://planetx.cc.vt.edu/AsteroidMeta/Links_and_bibliographies

* Discussion of Emory preprints

Some useful discussion of "free culture" has taken place in connection with all
of the Emory papers posted to the wiki.  We've been talking about issues like
"license (in)compatibility", "free math", and "open access", and trying to come
up with some useful statements that combine the things we've learned in our
separate efforts and which inform an Agenda.  What exactly this Agenda will
be remains to me seen.

* A few new proofs

Our collection of proofs written in "experimental hcode" is growing,
see

http://planetx.cc.vt.edu/AsteroidMeta/a_dozen_proofs


* Discussion
Wishing you all a good week. --[[file:jcorneli.org][jcorneli]]

----
[[file:Bulletins.org][Bulletins]]
