#+STARTUP: showeverything logdone
#+options: num:nil

* Op Ed: Getting more people involved

Now that you're involved in PM (doing whatever it
is you do), presumably you like it.  What steps are
you taking or might you take to get other people
involved too?

Just as an example, I recently suggested to one of my math
friends that he post a math question on PM.  I think
that the experience turned out well for him, so
I was glad about that.  PM really does seem to
help people around the world connect over math!

I'd be curious to know what other people are doing by
way of "outreach" - please post some info on your
thoughts or reports on your outreach activities. --[[file:jcorneli.org][jcorneli]]


*  NSF Advanced Learning Technologies Grant

The grant proposal has been submitted!  Thanks to all who helped brainstorm ideas for the proposal
or critique and help draft the actual document.  

The proposal will focus on educational evaluation and development of Noosphere.  Assuming we
get awarded (a big "if"), Aaron will be supervising one CS grad student on the development side
of things for two years at Emory.  PIs at Virginia Tech will supervise a grad student on evaluation, and
work with consultants from schools.  There is exciting potential here to study and improve the
pedagogy of Noosphere (and PlanetMath).

Details, including work items are at

http://planetx.cc.vt.edu/AsteroidMeta/NSF_Advanced_Learning_Technologies_Grant_Planning_Page.

An important thing to note from the list of work items is that people's suggestions /did/ make 
it into the grant proposal.  This proves that your feedback is important and invaluable, so please
keep it coming!  

*  social, political, and economic scholium systems

Discussion has continued.  The theme is using free software ideas to
revolutionize trade and even democracy.  Take a look if you like thinking about
political, revolutionary stuff!

The link again is

http://planetx.cc.vt.edu/AsteroidMeta//social%2c_political%2c_and_economic_scholium_systems

*  New suggestion for PM: centralized figure database

One of my former collaborators was talking to me about
how useful she finds example latex and figure source
code to be -- and she said that's one of the main reasons
that PM is cool.  Matte's suggestion, that we should
try to make a centralized database of all of the figures
on PM (with source code) seems like it would help make
PM's figures more educational - and of course it would
make it easier for PMers to produce new figures based
on the old ones.  

Any other suggestions about educational/usability enhancements? :)

* Discussion

These are DIY bulletins that people just /love/ to read.  Don't forget to sum up your wiki activities here! --[[file:jcorneli.org][jcorneli]]
----
[[file:Bulletins.org][Bulletins]]
