#+STARTUP: showeverything logdone
#+options: num:nil

* Feature: HDM debate

If you were on PlanetMath in October of 2003, you may
have overheard or participated in the great APM-Xi debate (and debacle).
If you missed it, my writeup is on AsteroidMeta, here:

http://planetx.cc.vt.edu/AsteroidMeta/one_week_in_october

and you'll also find the original postings in the PlanetMath archives.
This experience has had a lasting effect on my work both with HDM
and other AsteroidMeta projects.  

We are currently engaged in another (smaller) debate about
the HDM project: is it feasible? is it working well?  

While I feel that our critic has not given some of his points
due consideration, combined with our responses, a casual
reader can probably get a sense of the strengths and weaknesses
of the HDM project.  I invite you to take a look, and if you wish,
add to the discussion.  --[[file:jcorneli.org][jcorneli]]

http://planetx.cc.vt.edu/AsteroidMeta/HDM_criticism

* Feature: HDM problem-of-the-day club

Several of the items on our list of HDM subprojects seem amenable to a
distributed piecemeal effort.  Like a daily math problem, these tasks shouldn't
take up too much time, but should be intellectually rewarding, and should
provide something you can socialize with other HDM folks about.  

If you work on tasks under this effort, please add "problem of the day" to your
edit summaries, so we can better keep track of what's been accomplished this
way. --[[file:jcorneli.org][jcorneli]]

http://planetx.cc.vt.edu/AsteroidMeta/Focused_HDM_subprojects

* Feature: discussion of Emory papers

A number of the Emory FCDL papers are available through AM now, and
we're having fun thinking about and discussing them.  The conference
seems to be shaping up to be a useful tool for coordinating future
work - and it doesn't even actually take place until October!  Thanks
to Aaron and other Emory folks for helping with the coordination.

To see some representative work and discussion, check out the effort
headed up by Robert Milson at

http://planetx.cc.vt.edu/AsteroidMeta/Adapting_CBPP_platforms_for_instructional_use

For any teachers in the audience, this could be fairly inspiring.  --[[file:jcorneli.org][jcorneli]]

For discussion for some of the issues of copyright law which are relevant to the mathematical community and projects like Planet Math, please see

http://planetx.cc.vt.edu/AsteroidMeta/Free_Math_and_Potential_Bottlenecks

--[[file:rspuzio.org][rspuzio]]

* Dot-org Business: Corporate Accounts, Matching Donations

We're getting more serious about the PlanetMath nonprofit, PlanetMath.org, Ltd..
This past week, I (Aaron) opened an independent, non-profit corporate checking
account for PM.org with Wachovia, closing the previous private account which 
was under my name.  In addition, our Treasurer and registered agent, Bonnie Rabichow,
will now be vetting the account monthly and will have "r/w" access to it.

I'd also like to re-iterate a call--- for people from corporations which make matching
donations to charities, and who support our efforts ---to donate and apply with their 
employer to have the donation matched.  We are in the process of receiving our first
such matching donation.  After taxes, this arrangement allows supporters to have
each donation dollar approximately tripled.  We are on the eve of having the .org's
debts paid off, so that we can begin offering "code bounties" for improvements to 
the Noosphere system and PM web site.

For more details as well as other finance updates for the organization, see

http://planetx.cc.vt.edu/AsteroidMeta/PlanetMath_Budget_and_Resources

* Discussion

Posted (using a slightly different order).  --[[file:jcorneli.org][jcorneli]]

----
[[file:Bulletins.org][Bulletins]]
