#+STARTUP: showeverything logdone
#+options: num:nil

* Editorial: Independance Day

Today, Americans are celebrating Independance day, which commemorates the American Revolution.  Among the many changes resulting from this event, perhaps one of the lesser known is the new conception of intellectual property.  According to the United States Constitution, the purpose of copyright law is to promote the progress of science.  Not to reward authors for their labors, not to protect publishers from piracy, but to benefit the public by creating conditions under which information is easily accessible and science flourishes.

Hence, it is an appropriate time to ask whether the conditions of contemporary copyright regulation are consistent with the goal of promoting science.

Does issuing electronic versions of books under restrictive license terms which preclude reproduction and innovative uses of these texts promote the progress of science?

Do publishers who force their own authors to take down online versions of their works promote the progress of science?

Does replacing free preprint servers with pay-per-view electronic journals promote the progress of science?

Does punishing scientists who make copies of journal articles for their own use promote the progress of science?

If the answers to these questions is less than affirmative, then perhaps the practise of copyright today is out of touch with the ideal mentioned above.  Equally alarming is the possibility that licensing fees may be creating a situation in which science becomes the exclusive domain of an elite class.  Back when the only way of having access to a large body of scientific knowledge was to build a library and fill it with books and journals, it was inevitable that only those who could afford such a library themselves or were fortunate enough to have  access to one could participate meaningfully in the pursuit of science.  Now, however, when the average citizen can afford a hard disk with a capacity sufficient to store a library of several million volumes, it would be unconscionable if the only barrier to using it to its full capacities were licensing arrangements sanctioned by laws which are out of touch with their times and the purpose which the end were designed to promote.

If this possibility at all bothers you, then it will not suffice to stand back and watch in the hope that someone else will fix the situation --- you must act. Nor does meaningful action necessarily entail a large commitment --- writing an entry for Planet Math, releasing a research article of yours for free distributuion and use, publicizing the issue all help the cause.   Far too often, scientists have felt that it is not fitting for them to take an active role in such matters which lie outside their field of expertise.  However, the subject written on one's diploma is no excuse for shirking the ethical duty of acting on the basis of what one knows.  As a quotation by a South American revolutionary on a colleague's office door once said, intellectuals who do not speak out become part of the history of tears.

Just as the American revolution required organized effort, so too those who are concerned about these threats to mathematical progress will need to unite in a Free Math movement.  Already, we see the beginnings of such a movement in such places as Planet Math and Asteroid Meta and in John Ewing's proposals.  It is high time for concerned elements in the mathematical community to unite under the banner of free math, declare independance from outside entities who restrict the free flow of mathematical knowledge and storm the virtual Bastilles being erected to lock away our literature under sentences of 70 years plus life.

To some this might seem more like a tempest in a teapot than the occasion for another Boston Tea Party.  How can one worry about such trifles when innocent civilians perish in wars, when the poor die of hunger, when human beings are denied basic rights and are mistreated on account of their opinions or their ethnicity?  To such I would respond that I in no wise mean to disparage the importance of their concerns but would, with all due respect, like to point out that this issue of access to scientific information, although by no means of the same immediacy as the issues they raise, is nevertheless vital to the survival of a democratic way of life.  Technology based on the application of mathematical principles has become a part of everyday life.  Since mathematical knowledge is the power which enables one to create and control this technology, it follows that any group which is denied free access to mathematical knowledge becomes a group of second class citizens.  Just as in antiquity the peasant was dependant on the priest's astronomical knowledge and ability to plead with the gods in order to make his crops prosper, so too there is a very real possibility that the majority of people will become modern-day peasants at the mercy of a scientific priesthood if mathematical knowledge is denied to the masses.

If there is any truth in the sayings that knowledge is power and that truth sets one free, then any regime which restricts access to scientific literature is a menace.  For, just as the ordinary tyrant seeks to subjugate by starving the body, so this fiend seeks to starve the mind.  Insofar as the pen is more powerful than the sword, a dicatator who succeeds in denying the people access to the library is more dangerous than one who merely denies them access to the arsenal; even if he does not succeed in ensuring his own survival, he almost surely can ensure the survival of totalitarianism.

While there is some truth in the observation that the internet is a plaything of the well-off, this is being less true each passing day as the prices of computers drop.  Given the potential of the internet to democratize the media by putting a means of mass distribution in the hands of the masses and opening a free public library in every living room, it would a tragedy if this potential were stifled by overweening regulation.  Just as Benjamin Franklin's research on electricity ultimately provided the means of putting a print shop on a desktop, so too we would do well to follow his precedent with respect to free, open source distribution of knowledge.  The invention of the web by Franklin's latter-day colleagues at CERN is at least as significant as the invention of the nuclear bomb at Los Alamos and the ethical responsibilities of the scientific community to ensure the good behaviour of its brainchildren should be commesurate.  We need to take heed of this issue not only because it hampers the progress of our own science, but because we understand the nature of this technology and its potential rather intimately.  We cannot afford to sit by idly but must take a lead in educating the public and in lobbying for legal measures which would ensure that it lives up to its promise of promoting intellectual progress on an unprecedented scale.

Just as our predecessors two centuries ago, we find ourselves in times of revolutionary change with historical opportunities.  The eyes of future and past generations are upon us, waiting to see if the scientists of today will rise to this challenge as their predecessors Franklin and Jeferson did in their day.  Although we may still have time to act, we cannot afford to wait too long and the issue is too important to be neglected.  To paraphrase a famous quote, we face a choice between intellectual liberty and intellectual death.

--[[file:rspuzio.org][rspuzio]] 4 July 2005

* Discussion
Things are lively here.  New (and old) users: please don't forget to record
the highlights of your editing activities in our bulletins, for publication and posterity.
(Should we think about publishing these bulletins in some other venues?  Are there any other groups concerned with free content, e.g., maybe the "free culture kids", who would be interested in receiving these?) --[[file:jcorneli.org][jcorneli]]

When I get a chance, probably at the meeting on the 12th, I will ask LISP NYC about publishing to their discussion group.  Perhaps, after a rousing talk on HDM, a few people working on this project in connection with the Summer of LISP, and a few beers, the idea will sound appealing. --[[file:rspuzio.org][rspuzio]]

----
[[file:Bulletins.org][Bulletins]]
