#+STARTUP: showeverything logdone
#+options: num:nil

RMS is [http://www.stallman.org/harry-potter.html suggesting] that people not buy harry potter books.

If his "[http://blog.taragana.com/index.php/archive/stallmans-tirade-against-harry-potter/ fatwa]" was against reading the books,
this might be seen as extreme.  But it isn't.

I am thinking about taking this issue one step further to suggest that we
(the scientists of conscience) stop buying math/science books & periodicals that are circulated
under non-permissive copyright terms.  Like RMS, I would not be suggesting
that we cease to read these books, but that we make no further direct contributions to the
lucre-over-liberty publication industry to procure them.

I'm not completely confident in issuing this as a suggestion (much less
a fatwa) at this point in time.  But I would like to get the idea out there
to see what other people here think of it.  

One logical objection is that it would be inconvenient to be unable to buy
math and science books.  I don't disagree with this point.  Libraries are often
badly understocked, and books that are in high demand are often checked out.

I'll mention, however, that when I was a grad student, I successfully
negotiated for all the books that were mentioned on the exam syllabi
(and that were also available in the library; there were a few that
weren't; all but one of these were published on the internet) to be
kept on reserve, available for overnight checkout.  It is possible
that sensible library practices like this one -- actually having the
books that people need to use available for use -- could cure many of
the problems we might have with using libraries.

I'll also mention that this not-yet-activated proposal seems to have a
pretty powerful analogical edge to it, by which I mean that it seems
to sum up, in a politically-charged way, the goals and difficulties of
"free math".  Libraries are public, shared, freedom-enhancing spaces.
On the other hand, if we're used to paying, not for the right to read
(as one might in a fee-based library) but for the right to own a copy
and redistribute it (by selling it again on the used market), I fear
that we'll be playing right into the publication industry's
profiteering agenda.  I've talked to a few people who go so far as to
doubt the usefulness of "free math" because all they know is the
(already proved) usefulness of mathematical consumer culture.  A
properly described and advertised book-buying boycott might do a bit
to help these people see the difference between what they know and
where we would like things to go with math in the future.

Comments are appreciated.

--[[file:jcorneli.org][jcorneli]]

I think this is a good idea: people should vote with their dollars against
the abusive practices of Big Copyright (in all its forms).  A signal can
start being sent without even cutting onesself off from the resources: consumers
can simply switch to purchasing used copies, which is easier to do with
buyer-to-buyer systems these days.

However, the problem is a bit deeper in the library, where subscription decisions 
are made for entire institutions.  Individual faculty members at a university don't
directly "buy" any journals; the library does.  And these decisions are made
by a group, thus they are very politicial and have a lot of 
momentum.  Libraries are only really angry with journals because of the sheer
economics of the situation: they can't subscribe to as many of them because they 
are getting so expensive.

It is simply not feasible to expect a boycott en masse among working academics.
I think the best we can hope for is gradual pressure over time having an effect,
combined with the montonically falling budgets of libraries and growth of new
publications.  We need to educate scholars about copyright, an area where they have
in the past had the luxury of not thinking too hard or caring much.  Eventually,
the votes as to which journals to subscribe to (if any), and which journals to 
submit to, will add up to real change.

--[[file:akrowne.org][akrowne]] Tue Nov 15 18:33:00 UTC 2005

The proposed boycott doesn't apply at the level of libraries: I think
libraries should be able to buy whatever the usership wants to buy.
If these are expensive all-rights-reserved works, so be it.  I'm just
proposing here that individuals drop their subscriptions to these
sorts of journals.  I think that the revenues due to individual
subscriptions are high for many math journals.  If these individuals
found a good way to share a minimal number of for-cost works (through
libraries for example!), this would send a strong message to the
publishers that things have got to change.  

Later, I'd expect to see libraries being increasingly interested in
FAIF publications and technologies that support them.  I don't know
how closely related this fight and the individual boycott would be.

One of the benefits of the individual boycott would be to get people
thinking about /sharing/.  Instead of 20 people in a department
subscribing to the same journal, 1 or 2 persons could subscribe and
put the work into a shared reading room.  The remaining people might
even consider donating to a fund that would make the physical
environment of the reading room more pleasant.

It might be argued that the individual copies of the work on display
in the reading room are "rival goods", and that it won't do to have
only one copy on hand.  But the fact of the matter is, it might be
even better to have only one copy, if it gets people who would
otherwise be reading alone in their own rooms talking to each other
about the material.  I could imagine placing that one scarce copy onto
one of those document projecting devices and having a nice little live
discussion about it as it is deciphered.  Indeed, today's seminars are
a lot like this (and perhaps motivated my similar economics of
scarcity).

--[[file:jcorneli.org][jcorneli]]

My 2 cents: The context of the IP wars involving
copyrights, patents and trademarks is Post-Capitalism,
at least in the U.S. What is "Post-Capitalism"?
Official Cronyism and Looting. Copyrights were extended
to 99 years so that Disney Corp. could retain
the rights to Mickey Mouse, not because of "the
common good". Corporations rule the US today.
Politicians are not selected by the voters anymore. 
Gerrymandering is used by the politicians to select 
their voters. This is the end game for America, 
the once mighty empire, and now it is every man, 
woman and child for him or herself (unless they
choose to work together for their mutual benefit).
So if, say, Mr. X wishes to charge $Y for Book Z
who am I to complain? I just won't be buying a copy,
in part because $Z represents about N months
worth of my "People Chow" (tm), and I take eating very
seriously :) Going forward the "game" is about
doing guerrilla capitalism within the overall
context of Government by Looters during the 
long term fall of the U.S. into 2nd World status.
Now, if "democracy" and the Constitution are
restored one day, then I'll be the first to
start generating tax revenues again and going shopping.
During the Clinton years I paid huge wheelbarrows
full of tax dollars. It was massive! So I am not 
against paying taxes. I am against supporting a 
corrupt regime of Looters. I recommend forming groups 
and associations to assist you in achieving your 
objectives, including getting fed. Vote not just 
with your wallets, but with your feet, and by the 
way you invest your intellectual energies. 
--[[file:ocat.org][ocat]]

I agree with Ocat about camaraderie; and also with Burning Spear, who
said "social living is the best."  Culture building has been [[file:Discussions|discussed.org][Discussions|discussed]]
on this wiki some before and IMO it would be swell to see more of that.
I'm a strong investor in my shared kitchen and have a number of other
neighbor-relationship-building activities in the works.  Oddly enough,
I was never half as successful with these sorts of things in school.
Maybe because school culture is a sort of top-down culture; even my
reasonable-seeming efforts to make the math library work well for 
math students met with tons of resistance from the local Honchos. --[[file:jcorneli.org][jcorneli]]

----

The market for specialized scientific books
is primarily university libraries, along
with a few interested researchers who will buy a copy for their
departments.  Even at that price, these books often don't make a profit
after the editors and proofreaders are paid, in addition to production
and marketing expenses.  If Mladen's book is successful, I would guess a
more reasonably priced paperback version might appear.  In the meantime,
it is the kind of book that most people will just check out of their
university libraries.  Of course some professors "market" their books by
making it required reading for their courses - but that's another issue.

This is a far, far different situation from Harry Potter.  I lost
respect for the author when I read she was threatening a lawsuit against
some child who posted her homework about Harry Potter on the
internet.  When someone has already made more money off of it than 1000
average people will see in their lifetimes, something like this seems, well, petty.  She'll probably say it's protecting the brand name or
maintaining artistic purity or some such.  But to me it seems to point
to some kind of deep personality defect I don't quite understand.  Greed
does funny things to people.

In any case I removed my announcement of the book in case it is
construed as an advertisement, which has no place on this forum.  You'll
forgive my exuberance since I put a bit of work into the book myself (on
a volunteer basis, with no financial remuneration).
 --[[file:norm.org][norm]] 15-Nov-2005

If this book is relevant to research on Metamath then I don't see any
reason not to cite it on AM.  The above wasn't directed against any
book in particular, indeed, it isn't directed against books per se at
all.  I think it is fine to recommend books you contributed to; why
not?

But I'm not convinced that the difference between Potter and, say,
Springer, is really all that different.  Both organizations (might as
well use that word to describe the Potter Empire) enforce terms that
restrict the rights of buyers.  Springer's version of "buyer's rights"
is is pretty clearly within the law (at least, thus far), whereas
Potter version has at least part of its foundations nearer to the
boundary (per the lawsuit that RMS got riled about).

While it might be true that "the market for specialized scientific
books is primarily university libraries", I'm sure that if students
refused to buy non-free textbooks, that would have a huge impact on
the publishing industry (and academia as a whole, besides). --[[file:jcorneli.org][jcorneli]]
