#+STARTUP: showeverything logdone
#+options: num:nil



This is a place to talk about the overall budget of AM-affiliated projects.  The
discussion is partly, or largely, "potential".  For example, the FEM hasn't been
published yet, so we aren't getting any money from it yet.  Similarly for
the money out.

More description of each item would be good - how much money is associated
with each item?  How much money would we /like/ to be associated with
each item?

* Money in

 * [[file:FEM sales.org][FEM sales]]
 * other book sales
 * [[file:Grant planning|grants.org][Grant planning|grants]]
 * commissions
 * Google ads
 * sponsorship arrangements
 * individual donations
 * membership fees
 * payment for services (e.g. [[file:for-pay question answering.org][for-pay question answering]])

* Money out

 * [[file:Honoraria for FEM editors.org][Honoraria for FEM editors]]
 * payments to programmers working on commission (including on grants or commissions from outside of PM)
 * payments to site maintainers
 * payments to people working on administrative things (grantwriting, AM)
 * payments for content creation (something to consider)
 * payments for pure research (incl. academics who share grants with PM.org)

Also (maybe slightly different):

 * scholarships, grants, awards, or stipends to students/artists/etc. who are doing good work related to the above

----
[[file:the way of the asteroid.org][the way of the asteroid]]
