#+STARTUP: showeverything logdone
#+options: num:nil

In order to help us (a) communicate with a wider audience and (b) keep track of
what's going on ourselves better, I am adding a space for weekly bulletins.
These can be browsed here or copied (w/o modification, please) to the PM forums
or elsewhere.  I would like to propose that bulletins go into production by
Friday at the latest and that they released to PM on Sunday. Anyone is free to
contribute to a bulletin, and [[file:Users.org][Users]] are requested to add a short summary of
their activities on the wiki at some point.  Friday afternoon before taking off
for the weekend would work, for example, or late Saturday night if you're
working here til the last possible minute.  I will personally take
responsibility for doing last minute editing and final delivery of bulletins to
PM on Sunday.

Old bulletins will be archived here; further discussion of their contents should
take place either on separate pages or in a separate "Discussion" section added
below the original content.

New bulletin pages will be created when the old Bulletin is posted -- except for
this week, when the new bulletin page will be created NOW.  Thus, if you wish to
log your activities as you go, you'll be entirely free to do that.

Please do contribute to the bulletins, even it is something very brief!  Longer
articles are welcome too!

 * [[file:Asteroid Bulletin for the week of July 31 2005.org][Asteroid Bulletin for the week of July 31 2005]] (in progress)
 * [[file:Asteroid Bulletin for the week of July 24 2005.org][Asteroid Bulletin for the week of July 24 2005]] 
 * [[file:Asteroid Bulletin for the week of July 17 2005.org][Asteroid Bulletin for the week of July 17 2005]] 
 * [[file:Asteroid Bulletin for the week of July 10 2005.org][Asteroid Bulletin for the week of July 10 2005]] 
 * [[file:Asteroid Bulletin for the week of July 3 2005.org][Asteroid Bulletin for the week of July 3 2005]] 
 * [[file:Asteroid Bulletin for the week of June 26 2005.org][Asteroid Bulletin for the week of June 26 2005]] 
 * [[file:Asteroid Bulletin for the week of June 19 2005.org][Asteroid Bulletin for the week of June 19 2005]] 
 * [[file:Asteroid Bulletin for the week of June 12 2005.org][Asteroid Bulletin for the week of June 12 2005]] 
 * [[file:Asteroid Bulletin for the week of June 5 2005.org][Asteroid Bulletin for the week of June 5 2005]]
 * [[file:Asteroid Bulletin for the week of May 29 2005.org][Asteroid Bulletin for the week of May 29 2005]] 
 * [[file:Asteroid Bulletin for the week of May 22 2005.org][Asteroid Bulletin for the week of May 22 2005]]
 * [[file:Asteroid Bulletin for the week of May 15 2005.org][Asteroid Bulletin for the week of May 15 2005]]
 * [[file:Asteroid Bulletin for the week of May 8 2005.org][Asteroid Bulletin for the week of May 8 2005]]
 * [[file:Asteroid Bulletin for the week of May 1 2005.org][Asteroid Bulletin for the week of May 1 2005]]
 * [[file:Asteroid Bulletin for the week of April 24 2005.org][Asteroid Bulletin for the week of April 24 2005]] 
 * [[file:Asteroid Bulletin for the week of April 17 2005.org][Asteroid Bulletin for the week of April 17 2005]]
 * [[file:Asteroid Bulletin for the week of April 10 2005.org][Asteroid Bulletin for the week of April 10 2005]]
 * [[file:Asteroid Bulletin for the week of April 3 2005.org][Asteroid Bulletin for the week of April 3 2005]]

----

I think this is a great idea!! Looking at your draft of the first bulletin, I wonder if there is some way to use the revision history of the Wiki to generate a condensed summary of changes of the past week (after all, I do much the same thing every time I visit the Wiki and hit "recent changes").  Such a thing could bootstrap much of the bulletin.  --[[file:akrowne.org][akrowne]] Sun Apr 3 00:16:32 UTC 2005


: I was thinking we would just look at the recent changes, and craft the
bulletin by hand - just hitting the highlights.  My outline for this week's
stuff was special too - in the future, I expect people to just add reports on
their own things directly.  If the recent changes seems useful, go ahead
and use it! --[[file:jcorneli.org][jcorneli]] Sun Apr 03 07:18:17 2005 UTC
