#+STARTUP: showeverything logdone
#+options: num:nil

As Ross has pointed out, we shouldn't have anything in the XX
sections, so we'll need to get these things reclassified.

: Fait accompli.  I put in appropriate classifications to the 13 such entries I
had write access to and posted corrections to the remaining 28 entries.  Perhaps
it would be a good idea to post a note to a forum and say something in the new
user guide about this to keep it from happening in the future.  Among other
things, I can't imagine it's good for the linker. --[[file:rspuzio.org][rspuzio]] 26 February 2005

:: If PM was a wiki, I'd say you were being a "!WikiGnome" -- the complementary
name for the entities that clean things up and generally take care of the wiki.
Thanks!  But for next time it may be easier on you if you use the
new/in-the-works mechanised means.  I'll send you info on that by
email. --[[file:jcorneli.org][jcorneli]] Sat Feb 26 15:26:46 2005 UTC


There are some other classification issues.  For example, pretty much everything
under AMS-00 is questionably-classified in my mind.  For example, 00A20 is
supposed to contain entries /about/ dictionaries and other reference works. --[[file:jcorneli.org][jcorneli]] Sat Feb 26 15:36:39 2005 UTC
