#+STARTUP: showeverything logdone
#+options: num:nil

Without attempting to get involved in a complicated philosophical debate which has been going on for quite some time, let me sidestep the issue somewhat by asking exactly how relevant it is.  As I see it, the important issue here is whether a machine can think about mathematics in a meaningful and useful way.  Whether or not a machine can think of mathematics like a human is certainly an interesting question, but it may not be directly relevant.

Let me illustrate with an analogy.  Computers are already able to play board games (chess, checkers, go, etc.) well enough to give humans a run for the money.  However, as one can see from the fact that books on playing board games written for humans (as opposed to books on how to program computers to play board games) don't mention such things as alpha-beta pruning on search trees suggests to me that the way that the computer plays the game is rather different from the way that a human goes about it.  Further evidence for this possibility comes from the fact that it is often noted that the type of board configurations which occur when computers play are rather different from the types of board configurations which occur when humans play.  Nevertheless, the fact that computers may play board games in a completely different way than their human opponents doesn't mean that they can't play the game.

I suspect that something similar will be the case with math.  Already, we can see some examples.  On a trivial note, while adding and multiplying large numbers is a hard, time-consuming chore for a human (and people who can multiply even six digit numbers in their heads are a great rarity), it is completely trivial for a computer, so I suppose one could also make a case that  humans can't be made to think like computers!  Less trivial examples occur in such cases as computer proofs of binomial identities, numerical analysis, and computer algebra systems.  Therefore, it would seem to me that the fact that what comes naturally to computers is not necessarily what comes naturally to humans may not be all that much of an obstacle.  Naturally, it is an obstacle because one can't simply give a computer a math book to read, but it seems reasonable to hope that even if the computer will not think like a human, it will be possible to program a computer to understand math in a way which allows meaningful interaction between people and machines such as having a computer read through a proof in a book and verify if is correct or present the results of a numerical calculation in a user-friendly form which resembles an article that might have been written by a human who performed the calculation by hand.
--[[file:rspuzio.org][rspuzio]] 27 March 2005
