#+STARTUP: showeverything logdone
#+options: num:nil

* Against freedom

Spotting an apparent contradiction in my writings today,
I figured I should say something about it.

How can I advocate "choice" in one place ([[file:the pricepoint.org][the pricepoint]]) and rail against it in another ([[file:ubiquitous agency.org][ubiquitous agency]])?

I think it is because my definition of freedom ([[file:towards a definition of freedom.org][towards a definition of freedom]])
is simply one of reduction-to-consequences.  Every action has its consequences.
There is no "freedom" to be found if you look closely.

Nevertheless, it is established that we /feel/ like we have a choice.
Actually, I think what is going on here is that we feel the sum of
our past motivations bearing upon us.  Either there is a choice or
there isn't; and we've already ruled out the possibility that
there is a choice.

There is the sum (or perhaps, integral) of past motivations.  And there is the interesting
possibility of communication in the present time.  I.e., changing
the inputs to one's own or someone else's perceptual field.  Nothing
more than Turing's tape projected into three dimensions there.
This is physics, not philosophy.

When the "agent" (who has no choice to do otherwise) acts upon another
agent (who, similarly, is just some machine), the latter can change state.

Yet, the abstraction of "agent" is hardly necessariy for this dynamics.
In Newtonian physics, we might call a mass with some momentum a "particle", 
but we would be foolish to attribute a will to this ordered pair!
We don't say "the particle wants to fall", we say "the particle is 
being acted upon by the force of gravity".  Or whatever.

Point is, "agent" seems to have potential to be a misleading term, 
since it takes a quantity of motivational qualities and ascribes
an extra-physical will to their conglomeration.  Obviously a mistake.

To sum up.  "Freedom" means "consequences", and "choice" means
roughly the same thing.  In particular, it means precisely the
opposite of what "choice" would naively be thought to mean.  You
have a "choice" only when you have no choice at all.  Perhaps
choice means "internal computation to weigh given alternatives."
But this is all pre-programmed (or, if you don't accept that,
at least pre-meta-programmed, which comes to the same thing in the end).

Ain' it a lovely world we're living in?

* Against unnecessary force

Notice that while freedom may not exist, due to the physics of the
situation, /force/ does exist.  Conditions appear right and left.

Accordingly, I don't think I can argue against force in the same
categorical way I argued against freedom above.  But I can point out
that force itself has consequences.

For example, in the discussion of [[file:PM Licenses.org][PM Licenses]], I mentioned that
/copyleft/ is used in situations in which there /is no way to
ensure the various desiderata of the copyright owners will be met by
non-owners if no license is used/.  I contrasted this with the public
domain case, in which /no particular desiderata are imposed on
non-owners/.  (Indeed, in the PD case, everyone is a non-owner.)

The consequences of using the "forceful" copyleft license may include
non-uptake by persons who can not abide by its terms.  This
consequence may be perfectly acceptable to the copyright owner
(indeed, more likely, the consequence is actively desired).

But it would be ridiculous to impose the "forceful" terms of use on
someone if one in fact did not desire (or at least accept) the
consequence mentioned above (together with any other known
consequences of this particular course of action).

This is, I think, an "ethical" argument.  I am appealing to the
humanity of the readership.  One does not want to impose undesirable
conditions on one's peers, nor on oneself; not unnecessarily.  Which
is to say, conditions are truly undesirable if and only if they are
unnecessary (for the greater good, or whatever).

I do not say force is unnecessary.  I say unnecessary force is wrong.

----
[[file:Discussions.org][Discussions]]
