#+STARTUP: showeverything logdone
#+options: num:nil

I actually love programming.  And I am, I think, somewhat addicted to it.
(Along with email, thinking about HDM, editing this wiki, etc.)  Programming is,
for me, intensely interesting and fun.

However, despite some theoretical connections between programming and math
(which, of course, is something I also enjoy), I do not tend to think of them as
being "the same".

If you look at the couple of math research papers I've contributed to, you won't
see much of anything like the programming or HDM work I do.  What I saw when I
was working on these papers (and when I was taking math classes) certainly
inspired me.  I saw my name on documents without all the details spelled out -
with results that I didn't even completely understand - and I said, my goodness,
isn't there a better way?  Writing that was confusing -- hell, the whole
mathematical process is confusing!

What I think I would like -- for me, personally -- would be for mathematics to
be /more like/ programming.  But again, I like programming.  Some people might
prefer to have programming be more like doing math - whatever that means.

Actually, I wouldn't mind at all if programming became something that one did in
a conversational mode.  The disappearance of code wouldn't sadden me, much.

[[file:connections between math and programming | Back.org][connections between math and programming | Back]]
