#+STARTUP: showeverything logdone
#+options: num:nil


There are various KBs, notably the encyclopedia, the Noosphere
codebase, the !AsteroidMeta wiki, records of previous forum postings,
and perhaps also of informal email exchanges, although typically
elements of this last category aren't publicly available.  The
community has various practices in place for getting things done and
making decisions, including rules that say who has permission to
modify what, as well as a distribution of habits, skills, and
interests that dictate who will modify what.  Among these practices
are certain structures of authority or control, some informal and some
formal.  Examples of control structures range from ACLs and
corrections for encyclopedia entries, to Aaron's ability to ban users
or grant superuser access, to board meetings, bylaws, use-licenses,
and commit access.  Various factors go into workflow management; these
range from formal correction expiry and orphaning to informal email,
wiki, forum, or non-electronic discussions between constituents.  The
current capabilities of Noosphere have a lot to do with what sorts of
participation we see when we look at the !PlanetMath website.  Factors
bearing on an individual's participation (both on the website and away
from it) likely include relationships with other organizations and
individuals outside of !PlanetMath, for example, academic departments,
workplaces, professional societies, students, researchers, and so on.
Individual motivations are likely to include economic factors,
educational or research goals, and simple sociability.  The level and
style of an individual's participation may be influenced by the
availability of alternative sources of the resources !PlanetMath would
provide to that person.  Finally, whether or not a person actively
participates in !PlanetMath, and how they participate, may depend on
what they feel about the ideology expressed by site documents
(including both formal and informal documentation, such as licenses,
bylaws, wikis, and strategic plans), and by other site users; as well
as on other intellectual or emotional factors, such as the perceived
knowledgeably or friendliness of other constituents.

At present, these are the sorts of things PMers are working on.
Many people are adding to the encyclopedia on an ongoing
basis, speaking to their desire to make that resource more complete;
the ongoing stream of corrections indicate that people also want to
make this resource better; updates to the software and the site speak
to the desire of its maintainers to make these both stable and more
useful; the long list of feature requests indicate that site users
have quite a few specific improvements in mind; initiatives on the
wiki and in private conversations indicate that some constituents are
concerned with better understanding and better facilitating
communication and other organizational features of !PlanetMath; several
of these individuals have been working on fundraising issues in hopes
that !PlanetMath can start writing more checks and accordingly get more
done; similarly, on understanding how !PlanetMath can develop a
sustainable economy; and on outreach efforts aimed at creating
partnerships with existing organizations; and finally, a number of
discussions have taken place with the goal of generating better
expressions and codifications of !PlanetMath's ideology.
