#+STARTUP: showeverything logdone
#+options: num:nil

No, I don't mean the river delta, or the delta blues, or anything
having to do human anatomy -- I'm talking about the Greek capital letter "D",
which as we all know, stands for "change" (and sometimes for "increment").

An important feature of [[file:the way of the asteroid.org][the way of the asteroid]] is to /self-update/.
As you reflect on your [[file:Goals.org][Goals]], your [[file:Plans.org][Plans]], your [[file:Activities.org][Activities]],
and your [[file:Budget.org][Budget]], you should be reassessing on an ongoing basis:
how can you bring these things into better alignment with each other?

I am indebted to Angus Errington for describing this fundamental question
to me at an apropos moment in my life.  The quote from the Dao on "the way of the asteroid"
page also elucidates the point: there is no one "way" that can be spelled out - the way should
changing be constantly changing and shifting.

* jcorneli

The "Delta" I have in mind for myself is made up of lots of little "Deltas".
I think that email and this wiki are great places to discuss & hash things
out, but I feel that I need to be spending more time /thrashing/ things
out with my computer.  CVS seems to be a big recent improvement in the
way that the projects I'm interested will work, and I look forward to further
enhancements to my /offline/ lifestyle.  With finite time, and finite
(but growing) skill, I think I should be optimizing for "getting work done".
Now that my finances appear to be getting into focus (another recent improvement),
I'm more keyed into the importance of structuring my free time.  
Accordingly, I'm planning to spend increasing amounts of time offline at
the local library, working on code.  Also, since FEM is getting ready,
I may spend time working on editing offline too.  I'm excited about the
prospects here, but I admit that the proposed changes are driven partly
by fear of not being able to get enough done quickly enough.  I hope to
cultivate a mindset that dispenses with this fear, and simply 
focus on getting work done. (The Zen approach?)  Sequestering myself
for sufficient ammts of time each day seems like a useful strategy for
achieving this goal.  I anticipate continued participation in /discussion/
as part of this plan: but only within a more regular schedule that is 
centered on coding.
--[[file:jcorneli.org][jcorneli]] Thu Apr 28 18:58:12 2005 UTC

----
[[file:the way of the asteroid.org][the way of the asteroid]]
