#+STARTUP: showeverything logdone
#+options: num:nil

This is a wikified and unfrozen version of
http://www.ma.utexas.edu/~jcorneli/d/related/.  Feel free to reorganize,
/annotate/, cull dead links - or whatever.  

: Indeed, this is a very preliminary import, so /your help with getting it into
shape is requested/.  Putting HDM into its context (aka a literature review)
will probably be important for uptake, but also for our own sanity.  Your help
is appreciated - and hopefully reading about some of the items linked to here
would be fun.

If you want to make a separate page to talk about a particular item listed here,
please leave the item on the list here together with some initial annotations,
and then link to your new separate page from this page.

If you think an item is spurious or whatever, please mark it that way.  Items
can appear in more than one /subcategory/, but please put these subcategories
on separate pages (follow instructions above and treat the subpage like an
independent resource).

Thanks, --[[file:jcorneli.org][jcorneli]] Sat Jun 18 02:20:40 2005 UTC

: Also, when working on this page, /please try to note the connection you see
between the item you are describing and the HDM project/.  Many of the existing
entries badly fail to give explicit comparisons or connections, and they should
be fixed.  --[[file:jcorneli.org][jcorneli]] Sun Jun 19 02:52:44 2005 UTC

For other content see my [http://www.ma.utexas.edu/~jcorneli/l/ personal links] 
(lots and lots), especially http://www.ma.utexas.edu/~jcorneli/l/HDM-related.html
(more managable and more uniformly relevant).


----
* Note of distinction

This is the "page of the beast"; page number 666 on AsteroidMeta. --[[file:jcorneli.org][jcorneli]]

That many pages already ??!??!!!??!??!!!??!??!!!??!??!!!??!??!!!??!??!!!??!??!!!
We've only been at this project a few months.  This beast is sure growing fast.  Maybe it will grow up to be an elephant :) --[[file:rspuzio.org][rspuzio]]

Sorry to disappoint, but earlier this year the oldest-known fragment of the 
new testament was [http://news.independent.co.uk/uk/this_britain/article4086.ece discovered], and the actual "number of the beast" recorded there
was 616 =) --[[file:akrowne.org][akrowne]] Sun Jul 10 20:33:05 UTC 2005


----
[[file:HDM-related things to check out.org][HDM-related things to check out]]
