#+STARTUP: showeverything logdone
#+options: num:nil


Some PlanetMath members, including me ([[file:alozano.org][alozano]]), [[file:matte.org][matte]] and drini have expressed concern and disagreement on creating paid positions and have openly opposed the idea of paid positions. This should be taken into account and discussed during the meeting. --[[file:alozano.org][alozano]]

Also, even in the case that paid positions are approved by the board, why is there
the need of two (not one or three) positions (besides the president and
treasurer, positions which already exist)? You are surely forgetting many other volunteers on the meta side. All of the following seem to be doing some helping:

[[file:ocat.org][ocat]], [[file:SteveCheng.org][SteveCheng]], [[file:frl.org][frl]], [[file:bloftin.org][bloftin]], [[file:norm.org][norm]], [[file:pekuja.org][pekuja]], [[file:shargestam.org][shargestam]], [[file:omasaveu.org][omasaveu]], [[file:matte.org][matte]]

among others (see user's list). Are they all going to be paid or not? They are all doing things that "need to happen" in some way or another. So if we are going to pay some people, shouldn't we pay everyone who works on the meta side of things?--[[file:alozano.org][alozano]]

Any "open disagreement on the creation of paid positions" will need to
be significantly justified before it can be a (counter-)proposal.  I'm
not going around saying that math professors should all be volunteers,
now am I? :) --[[file:jcorneli.org][jcorneli]]

Our position has been explained in PlanetMath.org and it is indeed
not a proposal but an opposition to a proposal, which is quite
different. The proposal (paid positions) should be justified and then
voted by the board, taking into account the opinion of the
members.--[[file:alozano.org][alozano]]

I think you do a reasonable job explicating your position on the
page [[file:Sketch_of_a_Possible_Organizational_Structure.org][Sketch_of_a_Possible_Organizational_Structure]].  However,
I also think Ray did a reasonable job addressing your concerns.
So, I'd like to understand, do you still object to the creation of paid positions under the
conditions stated at the bottom of
[http://planetx.cc.vt.edu/AsteroidMeta/?action=browse;id=Sketch_of_a_Possible_Organizational_Structure;revision=37  revision 37] of that page?
--[[file:jcorneli.org][jcorneli]]

: There is no money in the budget to allow the board to pay positions, so the board cannot allocate money to pay positions, and the officers, if the positions are created and members are elected as officers, will have to act in a volunteer basis until there is money in the budget. Then (when there is enough money in the budget) and only then one can ask the board if the board agrees on paying for these positions. In any case, I still oppose the creation of paid positions even if there was money in the budget for it. I believe bounties, when needed, are more useful. And the rest of us should work as volunteers. There are many who volunteer in the meta side and in the content side, so it is rather arbitrary to pay some and no others, even if the others are not pursuing getting paid. If at some point all the other volunteers do pursue getting paid we will have a very difficult case to obstruct every one getting paid, which will be probably impossible to fit in the budget. --[[file:alozano.org][alozano]]

:: At the very least, there is still a high burden on me in managing the bounties and the facilities, so I support paid positions for this kind of ongoing work.  I think there is plenty of precedent for organizations that have paid staffers and unpaid volunteers---namely, any widely-known charity.  In fact I would be surprised if you could find a purely unpaid organization that has any sort of longevity or social impact.  You simply need a paid infrastructure to sustain.  --[[file:akrowne.org][akrowne]] Mon Mar 20 15:54:28 UTC 2006

#+BEGIN_VERSE Actually, I should say that Aaron is an exception to all my arguments. As president, cofounder, leader programmer, moderator and everything else, Aaron is clearly an exception to everything I have said above and at this point I don't see how PlanetMath could exist without your presence. Thus, if Aaron thinks he cannot be involved in all his current roles unless there is some sort of paycheck for him, then I would not oppose if he received compensation for it. But again, Aaron is a very exceptional Planetmath member, whose role seems fundamental to me. PlanetMath has been running smoothly since its creation, without any paid infratructure, but only because Aaron has been there all this time, even paying expenses from his own pocket.--[[file:alozano.org][alozano]]

#+BEGIN_VERSE: Exception that proves this rule: People who (a) make major sacrifices to work on PM and (b) do necessary work, should get paid.  (A fuller argument will appear elsewhere.)  --[[file:jcorneli.org][jcorneli]]
#+BEGIN_VERSE:: Be careful how you interpret my words. Aaron is an exception because I do believe that PM *absolutely needs* his presence to run smoothly. I think you will have a much harder time convincing me or any other that we absolutely need other positions. Other oddjobs can get done by volunteers and if there are no volunteers then it can be posted as a bounty.--[[file:alozano.org][alozano]] 

#+BEGIN_VERSE#+BEGIN_VERSE Perhaps you would be convinced (a) if Aaron said so; (b) if Ray and I went on an extended vacation to focus on other things ;). --[[file:jcorneli.org][jcorneli]]
#+BEGIN_VERSE#+BEGIN_VERSE: Yes, it would be a really bad thing if we lost both of you guys, but I do hope you are helping PM because you like PM and not because you expect to get paid from PM. But again, regardless of my view on volunteering, I think it is just an impossible to pay you guys at this point in time. Is it not? What figures do you have in mind to support the idea that we will have enough money in the bank to pay salaries? I don't think PM should compromise to pay salaries until the money is actually in the bank, or it is evident that the money will show up in the bank. For one thing, it would be unfair to you if you were told that you are going to get paid only to find out later on that the money never came through.--[[file:alozano.org][alozano]]  

#+BEGIN_VERSE#+BEGIN_VERSE:: The idea I like is that of a contigency.  If the money shows up, then we get paid.  --[[file:jcorneli.org][jcorneli]]
#+BEGIN_VERSE#+BEGIN_VERSE#+BEGIN_VERSE Hmmm, that sounds like working on commission, and I dislike that idea too. Honestly, it would really suck for you guys if you expect the money but the bank never comes to the point that money can be used to pay you. As I said in the finances page, I don't think PM.org should let people work for the organization on contigency. It is not a responsible plan and not fair to those who may/may not get paid. I think it would be wiser to spend our time thinking how to increase the budget and only when the budget is large enough we can retake the proposal of paying some of the officers. That's what a responsible non-profit organization is ought to do.--[[file:alozano.org][alozano]]  

Alozano, I appreciate the vote of confidence =)  But it is not so simple.  Many of the burdens I shoulder I would like to see partially or entirely offloaded to other people, and I certainly have Joe and Ray in mind for some of them.  Also, the bounties actually constitute a sort of "shadow training" of a crack team of Noosphere admins/coders---not only can we use these people for more bounties, but they become good candidates for becoming "salaried" due to the knowledge and skills they build up.   I agree with you that we shouldn't "sign any contracts" right now, but frankly, without a "light at the end of the tunnel" in terms of having some ongoing staff to help me, I am not sure how long I can continue.  This is why I favor these planning activities, by my "gut feeling". --[[file:akrowne.org][akrowne]] Mon Mar 20 22:39:07 UTC 2006

I'm not sure what you mean by "vote of confidence", but I can state
that it seems to me that whether or not I engage in fundraising
activities may (a) have a fairly significant impact on whether we get
funding any time soon (b) be contingent upon me knowing that when
funds come in, I will get some of them.  So, Alvaro, the fact is, I
already do "expect" to get paid, and I would very much like to have
some documents to point to that would lend some concreteness to that
expection.

Thus, a contract or similar statement would be a good idea in my view,
any time we can come up with something reasonable; I don't know why we
would want to avoid it.  All a contract is in this case is a
formalized statement of one portion of the projected budget, and we're
going to have to come up with a projected budget before we'll be able
to do any serious fundraising.

In particular, some formalized statement of the tasks that folks "have
in mind" for me (or have me in mind for or whatever) would be nice for
me (and our potential funders) to see.  As you know I am already
working rather hard on a few PM-related tasks of my own choosing, and
more tasks I become responsible for, the more reason I will want to be
paid (more).

Some preliminary material along the lines of what I'm talking about
has been laid out at [[file:Vision_for_the_future_of_PlanetMath.org][Vision_for_the_future_of_PlanetMath]].--[[file:jcorneli.org][jcorneli]]
: No one (except maybe Aaron) should expect to be paid from PlanetMath. We are all *volunteers* in this project and it is the understanding of all of us that we all work and collaborate as volunteers. Only a board-approved payment-action could lead you to expect payment, and as I understand there has been no sign from the board on that respect. Again, Aaron is an exception for the reasons stated before.--[[file:alozano.org][alozano]]

I am only in favor of any sort of promissary action if it passes through the appropriate
controls of oversight, in which case, it is isomorphic to the setting of budget 
allocation.  Logically this should be a non-issue, so it appears there is something 
about the chronology of this situation that is raising concerns.  --[[file:akrowne.org][akrowne]]
: Of course, there is no other way, since this is a non-profit organization and the funds should be distributed and used according to the board criteria. By the way, I will agree with whatever decision the board comes up with, but it should be the board who approves any positions and any payments for positions, and no one should expect payment unless the board has ratified a move to that end.--[[file:alozano.org][alozano]] 
:: Then we agree.  This is what Aaron, Joe and I have been saying all along ---that the
board would create (and destroy) positions and set the budget.  Who was expceting payment
under any other conditions???  To be sure, we also suggested that, unless the board were to take
an active role in the day-to-day operations of the organization, then the budget they set
should be in broad terms and that whomever has been given the responsibility for the day-to-day 
operations be able to decide exactly how the chunk of budget allocated to an activity be spent 
without having to ask the board every few minutes but be held accountable for these choices.
This second suggestion doesn't really contradict the fact that the board is in charge (and
that the community is in charge of the board), it is simply a matter of delegating responsibility
in a reasonable and practical way.  For instance, if the board is not going to play an active
role in administering the bounties, then a sensible course of action would be for the board to
appoint a bounty committee (as it has done), allocate a portion of the budget for bounties (as
it has not done because we don't have an official, board-approved budget yet), then let the
committee spend that budget as it sees fit without having to go running to the board every time
it issues a bounty or hires someone to obtain specific approval for that action.  However, the
board would expect that this committee conduct its operations in a  reasonable open fashion
and, if the board sees that inappropriate things are being done (like committee members paying 
themselves bounty money) or that the committee is incomepent then it might take action to correct
the situation, maybe replacing some of the people on the committee or even dissolving the 
committee altogether. --[[file:rspuzio.org][rspuzio]]


I've switched two items in the agenda, now the goals go first, then discussing the creation of paid positions. See my comment on [[file:Vision for the future of PlanetMath.org][Vision for the future of PlanetMath]]. The goals should be discussed first in order to understand why new positions may be needed. --[[file:alozano.org][alozano]]
