#+STARTUP: showeverything logdone
#+options: num:nil

Comment about website on [[file:PlanetMath Budget and Resources.org][PlanetMath Budget and Resources]] (section on Organizational
Structure) is not entirely accurate, if you mean [[file:AM.org][AM]].  I wish it
was true.  It would be great if these people were involved, but AFAIK (and I've
been here from day 1) the only board member who has used !AsteroidMeta is Logan,
and he has not exactly been a top contributor.  Perhaps the board members are
/reading/ !AsteroidMeta, in which case, considerable 1-way correspondence
/to/ the board has been taking place on this web site.  But we haven't gotten
a "hi, how ya doin'" from most of these folks.  In the mean time, you, me, and
Ray have done a lot of organizational work, and we've been nicely supported by
some other PM contributors.  Perhaps this is as it should be: AM constituting a
"shadow governance" structure to PM's explicit and legally sanctified governance
structure.  One benefit of this structure is that the board comprises the more
conservative "higher functions" of PM, whereas we on AM make up the more active
"lower functions".  Nonetheless, if there is no communication between lower and
higher agencies, then the utility of this arrangement is called into question.
I would personally like to see /timetables/ for board meetings, and I would
also like to see homepages for each of the board members here on AM, so we can
leave them public comments and /actually/ communicate with them directly.
Their history of commitment to PM is noble and worth recognizing, but I would
not want to see them fall out of touch with recent events.  We have been very
busy these past few months!  IMO, minimally these people would be reading the
bulletins, and presumably commenting on them from time to time.  It is great if
you are communicating with these people on a regular basis, but I am sort of
dismayed by their lack of involvement with AM.  While there may be /much/
communication between the president and the board, my ego does not appreciate
the fact that other folks have the stylish appellation of "board member" and yet
they do not seem to cast a glance in the direction of some of the other volunteers who (at
least to all appearances) are working hardest to support the organization.  No
disrespect to the history (and unknown present activities) of this board, but they appear to be quite
disconnected from AM, and this bothers me, because I think this place should
be important to them: like it says above "This page is the official home
page of !PlanetMath.org, Ltd."  

--[[file:jcorneli.org][jcorneli]] Sat Jul 09 00:39:50 2005 UTC

Ok, the comment was partially wishful thinking wrt/this wiki.  However, the board
members have all at least been /readers/ of the pertinent sections of AM.  I am 
working on getting them involved in both r/w modes. --[[file:akrowne.org][akrowne]] Sun Jul 10 00:09:36 UTC 2005

Note, I'm not asking that they be involved with everything, but they should have
a sense of what's going on.  This probably means that they should be reading the
bulletins.  What I do think they should be involved with is fundraising; are
they?  Maybe people like these PIs who joined up with the recent NSF grant
should be invited to join the board.  In any event, the actual (not just
potential) responsibilities of the board should be made clear.  When will there
be a meeting, for example? --[[file:jcorneli.org][jcorneli]] Thu Jul 14 03:31:12 2005 UTC

And one more thing: in addition to direct fundraising, maybe some involvement in
helping us find additional volunteers.  Networking, right!  --[[file:jcorneli.org][jcorneli]] Thu Jul 14 03:42:33 2005 UTC
