#+STARTUP: showeverything logdone
#+options: num:nil



With respect to the copyright pact, there really needs to be a new pact.  That draft
was wtritten before any of us were aware of how the DMCA works.  As it turns out, in
order to qualify for the DMCA safe harbor, it is not enough that one simply file for
designated agent status (as we have already done) but also that one do some very specific
things in order to qualify as a service provider under the definition given in the law.
As I understand it, this pretty much dictates the form of certain provisions which need
to go into this pact and provisions of this law supersede some of the protection we were 
trying to obtain via the pact.

Therefore, what I would propose in the way of this is as follows:

 1. Study the DMCA, secondary literature from the copyright office and elsewhere, and examples
of user agreements for other entities which have this status.  I would be willing to do this,
but I estimate that it would entail something like 40 hours of work to do at least a half-decent
job, so I would pretty much have to leave alone from the other stuff I am involved in 
(whitepaper, organization) for a week or so to concentrate on this.

 1. Make a third draft of the pact informed by what has been learned.

 1. Get some expert advice on how this likely to play out in practise.  As we said before, while
we can and should make sure that the document at least conforms to the basic principles of 
contract law (and it would be wasteful of an expert's time to be presented with a poorly
designed document in which any freshman law student could find serious flaws), at the same time
it really would need someone like Moglen or Lessig who has years of practical experience closely
monitoring trends in copyright law to say something authoritative and credible on what such a 
document is likely to really mean in court and suggest improvements.

 1. In addition to advice on the document itself, we might also want to get some advice on matters
related to its implementation like "Do we need to re-register all users in order to make it take
effect?" or "How valid is clicking on a button for entering into an agreement or is there some
other procedure we shold implement?".

I would be reluctant to rush the process and omit some of these important steps and double-checks
in the interest of getting up a user pact sooner.  If nothing else, having a pact which is not
likely to hold up in court or otherwise seriously flawed could give a false sense of security.
As I said, I think that I could carry out the first and the second steps this month if I ignore
other things to free up time for them and, if that seems like the way to go, I could finish 
whatever else I was doing this week, and then focus on DMCA for next week and perhaps the week
after that.  Maybe we could get and expert to weigh in by 4/20 but that sounds like a tall order.

So what I would propose is that the agenda item be interpreted to me that, at the upcoming
meeting, it will be decided whether to implement the pact with the undeerstanding that we would
not do so until we had obtained expert advice and that the document and the way in which it is
implemented might be ammended so as to bring them into conformity with the current interpretation
of the law but in the spirit of the original document.
--[[file:rspuzio.org][rspuzio]]

Ray, that sounds reasonable. --[[file:akrowne.org][akrowne]] Mon Mar 20 22:45:12 UTC 2006
