#+STARTUP: showeverything logdone
#+options: num:nil


Back to [[file:Goals.org][Goals]].

----

For your current set of goals, it seems like [[file:Grant planning|grants.org][Grant planning|grants]] are a
good way to go.  I think the comments we got from eaf (both on the wiki and by
email) suggest some good directions to go in for future grant planning and
preparation.  

One possible tactic to use WRT his idea of "letters of support" would be to make
a list of possible supporters.  If you got people like 
[[file:Personage - John McCarthy|John McCarthy.org][Personage - John McCarthy|John McCarthy]], Donald Knuth, Richard Stallman, etc.,
you'd probably be swimming in money before you knew it.  (OK, maybe that's a slight
exaggeration.)  Maybe the [[file:important figures.org][important figures]] page would be a good place to work
on such a list, or we could make a separate lists, of "[[file:PM supporters.org][PM supporters]]" and 
"[[file:Potential PM supporters.org][Potential PM supporters]]".

WRT grants in general, it would be good to keep our radar on & turned up, so we
can pick up possibilities sufficiently far in advance -- and keep working on the
grant planning pages to add the sorts of details eaf was talking about (which
will likely be somewhat similar from grant to grant).

I would also strongly suggest that we keep talking about, and, when possible,
working on, [[file:thoughts on the viability of free-software style business|alternative ways.org][thoughts on the viability of free-software style business|alternative ways]]
to raise money for the PM project (and related projects).

Good luck!
--[[file:jcorneli.org][jcorneli]] Fri Apr 08 22:26:13 2005 UTC

----

It also occurred to me that there are probably a lot of PM users who are full professors
and would endorse the site.   This is something to keep in mind.  

On a related note, I was talking to Martin Halbert (my boss) today in another context
and we were discussing the usefulness of advisory boards.  The idea is, on grant projects,
to provide endorsements and continual guidance from representatives of the community 
served.  Then I realized that the board of the PlanetMath nonprofit could function something
like this.   I also remembered someone else's suggestion that we stack this board with 
notables in mathematics, education, digital libraries, and computing whom support our
project.  So, getting people like this on PM's board could serve to raise the profile of 
PM's nonprofit, get it funding, and provide a pool of supporters we could repeatedly draw
upon to help us get grants and guide their development.

--[[file:akrowne.org][akrowne]] Fri Apr 8 23:48:42 UTC 2005
