#+STARTUP: showeverything logdone
#+options: num:nil

This page totally rocks today!  Wow, thanks to [[file:rspuzio.org][rspuzio]] and [[file:rmilson.org][rmilson]]
and [[file:pekuja.org][pekuja]] and [[file:shargestam.org][shargestam]] for giving me so much to respond to today
I'm gonna have to take a break.  [[file:akrowne.org][akrowne]], where are you, you gotta check 
the RecentChanges out!  This all makes me think that we should write a paper about AsteroidMeta
and coordinating free software development projects and nonprofits using
a wiki.  Well... maybe there is some other literature out there about this;
something to look into, because it is a neat example of "intraCBPP" (of
course actually out in the open too). --[[file:jcorneli.org][jcorneli]] Jun 18 2005

I think there is definitely the potential to write about using a wiki to coordinate
projects, especially nonprofits.  Nonprofits are /supposed/ to be run with 
minimal overhead resources, but all too often they end up being managed like 
lumbering corporate behemoths.  I've found it a bit difficult to explain to 
people what we're doing here, so maybe that means sometime I should work on 
articulating it better and more formally. --[[file:akrowne.org][akrowne]] Mon Jun 20 22:27:34 UTC 2005

There's some feedback now on the [[file:HDM criticism.org][HDM criticism]] page. Unfortunately, not very positive such... --[[file:shargestam.org][shargestam]]

I enjoy AM, but it is missing one major feature or at least I am ignorant on how to do something similar.  When a page gets lengthy it can be quite hard to find the newest change.  Is it possible to get highlighting/text color change for recent additions? --[[file:bloftin.org][bloftin]]

See [[file:A_note_from_some_members_of_PlanetMath_who_dislike_this_media.org][A_note_from_some_members_of_PlanetMath_who_dislike_this_media]]. --[[file:alozano.org][alozano]]
