#+STARTUP: showeverything logdone
#+options: num:nil

If we go with a print-on-demand resource like lulu.com, we can set our own
"royalties" for the FEM.

I estimate that the /actual/ cost of a copy will be about $45.  I think we
should limit the cost to purchasers to $60.  Thus, if this estimate is correct,
each copy sold should earn us $15.

I would imagine anywhere between 10 and 100 copies will be purchased per month,
producing a total income to PM.org of anywhere from $150 to $1500 per month.

See also [[file:Honoraria for FEM editors.org][Honoraria for FEM editors]].

----


We need to check on things like posting revised version.  Can we do this if we
use the ISBN option?.  How about if not?


Note that the book has not yet gone on sale - it is not ready to go quite yet.
See the [[file:FEM.org][FEM]] page for more details.

----

Is the FEM going to be available for free online? If not, why do we call it the **free** encyclopedia of mathematics? I understand we are trying to use this revenue to improve and pay the bills of Planetmath and other projects, but then, we should not call the encyclopedia *free* if it is not so. For some reason I thought the encyclopedia would be available to be downloaded online for free, am I wrong? --[[file:alozano.org][alozano]]

It surely will be available for free online.  It would be amusing if we tried to "keep it under wraps", in fact, as the source entries are PlanetMath itself. --[[file:akrowne.org][akrowne]] Tue Apr 12 12:40:54 UTC 2005

"Free" in the title is a matter of freedom, not price!
But (accordingly) sources will be avaliable at no cost.

Probably a PDF version too, since it is good advertising
for the print version and the site and of course people will find it
useful.

Anyway, the idea for fundraising is to sell /printed versions/!
These are never going to be cost-free.
Our versions will be cheaper than what someone could make by
photocopying the book.  To undercut us, they would have to use
a publisher... e.g. lulu.com.  But that wouldn't be very nice,
would it?  We could find a way to make people who did that look bad.
Besides, it  would involve a little work to keep the "royalty free"
version up to date.  Does that help clarify things?
 --[[file:jcorneli.org][jcorneli]] Tue Apr 12 14:24:42 2005 UTC

: Thanks, that is much more clear, and precisely the situation I like. A free PDF version should be posted somewhere and then users can buy a nicer printed version, (a) because it should be nice to have, (b) to help out with PM. --[[file:alozano.org][alozano]]

:: FYI, there are already offline-browsable "snapshots", which could conceivably be burned to a CD and toted around with you. See http://aux.planetmath.org/snapshots/ . --[[file:akrowne.org][akrowne]] Tue Apr 12 19:06:34 UTC 2005

[[file:Budget.org][Budget]]
