#+STARTUP: showeverything logdone
#+options: num:nil

As a help for determining which books are in the public domain, I am compiling a
list of math books published from 1923 to 1963 whose copyright was renewed.
This is being done by looking through
[http://www.kingkong.demon.co.uk/ccer/ccer.htm the list of copyright renewals]
and picking out the math books by hand.

The reason for doing this is as follows: Under U.S. law, any work first
published in the U.S. in those years required to have its copyright renewed
after 28 years.  Hence, if a work which was copyrighted between 1923 and 1963 in
the U.S. did not have its copyright renewed, the copyright will have expired.
(Material published before 1923 has reverted to the public domain regardless.)

With some exceptions having to do with forign authors and publishers which are
explained [http://onlinebooks.library.upenn.edu/renewals.html here], books whose
copyrights were not renewed have passed into the public domain.

Hence, this list may be of assistance in determining if a math book published in
the U.S. between 1923 and 1963 is in the public domain or is still under
copyright protection.  In using this list, you need to keep in mind that simply
because a book does not appear in the list does not mean that you should
automatically assume that the book is in the public domain.  Rather, you should
perform a proper search to determine whether the book is really in the public
domain or not.  Rather this list is only meant as a quick test one can apply to
exclude certain books and thereby spare yourself from having to perform a
lenghty search in the case of some books which are known not to be in the public
domain.

 * [[file:Mathematical works whose copyrights were renewed - 1923.org][Mathematical works whose copyrights were renewed - 1923]]
 * [[file:Mathematical works whose copyrights were renewed - 1924.org][Mathematical works whose copyrights were renewed - 1924]]
 * [[file:Mathematical works whose copyrights were renewed - 1925.org][Mathematical works whose copyrights were renewed - 1925]]
 * [[file:Mathematical works whose copyrights were renewed - 1926.org][Mathematical works whose copyrights were renewed - 1926]]
 * [[file:Mathematical works whose copyrights were renewed - 1927.org][Mathematical works whose copyrights were renewed - 1927]]

 * [[file:Mathematical works whose copyrights were renewed in 1976 - original copyright ca. 1948.org][Mathematical works whose copyrights were renewed in 1976 - original copyright ca. 1948]]


** Note

The best thing to complement these list with would be lists of math books that
were published during the time period under consideration here.

Searching through the Library of Congress for mathematical works published in the Uninted States yielded the following:

 * [[file:Mathematical works published in the U.S. in 1923.org][Mathematical works published in the U.S. in 1923]]

Since this is letting a lot slip through the cracks, I decided to systematically search through call numbers.  Some of the material I found so far listing books which may be in the public domain will be posted here:

[[file:Raw data from Library of Congress searches.org][Raw data from Library of Congress searches]]
 * [[file:Raw data from Library of Congress searches QA1 - QA99.org][Raw data from Library of Congress searches QA1 - QA99]]
 * [[file:Raw data from Library of Congress searches QA100 - QA200.org][Raw data from Library of Congress searches QA100 - QA200]]
 * [[file:Raw data from Library of Congress searches QA200 - QA299.org][Raw data from Library of Congress searches QA200 - QA299]]
 * [[file:Raw data from Library of Congress searches QA249 - QA299.org][Raw data from Library of Congress searches QA249 - QA299]]
 * [[file:Raw data from Library of Congress searches QA300 - QA325.org][Raw data from Library of Congress searches QA300 - QA325]]
 * [[file:Raw data from Library of Congress searches QA326 - QA349.org][Raw data from Library of Congress searches QA326 - QA349]]
 * [[file:Raw data from Library of Congress searches QA350 - QA399.org][Raw data from Library of Congress searches QA350 - QA399]]
 * [[file:Raw data from Library of Congress searches QA400 - QA450.org][Raw data from Library of Congress searches QA400 - QA450]]
 * [[file:Raw data from Library of Congress searches QA450 - QA459.org][Raw data from Library of Congress searches QA450 - QA459]]
 * [[file:Raw data from Library of Congress searches QA460 - QA469.org][Raw data from Library of Congress searches QA460 - QA469]]
 * [[file:Raw data from Library of Congress searches QA470 - QA499.org][Raw data from Library of Congress searches QA470 - QA499]]
 * [[file:Raw data from Library of Congress searches QA500 - QA549.org][Raw data from Library of Congress searches QA500 - QA549]]
 * [[file:Raw data from Library of Congress searches QA550 - QA559.org][Raw data from Library of Congress searches QA550 - QA559]]
 * [[file:Raw data from Library of Congress searches QA560 - QA569.org][Raw data from Library of Congress searches QA560 - QA569]]
 * [[file:Raw data from Library of Congress searches QA570 - QA599.org][Raw data from Library of Congress searches QA570 - QA599]]
 * [[file:Raw data from Library of Congress searches QA600 - QA609.org][Raw data from Library of Congress searches QA600 - QA609]]
 * [[file:Raw data from Library of Congress searches QA610 - QA649.org][Raw data from Library of Congress searches QA610 - QA649]]
 * [[file:Raw data from Library of Congress searches QA650 - QA699.org][Raw data from Library of Congress searches QA650 - QA699]]
 * [[file:Raw data from Library of Congress searches QA700 - QA809.org][Raw data from Library of Congress searches QA700 - QA809]]

This is not meant to be complete.  Later, I will explain more about exactly what this is, but for now take this to be a list of some (not all) math books published before 1963 or with no publication date indicated.

** Question

Can you add links describing the relevant portions of law?  (Or detailed
summaries thereof.)  This is a bit confusing, since it has to do with /old/
copyright law and its interface with /new/ copyright law.
--[[file:jcorneli.org][jcorneli]] Wed Apr 13 06:51:54 2005 UTC

Exacly what is in the public domain is explained on Project Gutenberg.

(Links would still be helpful...) --[[file:jcorneli.org][jcorneli]]


** Comment
Ray, I just wanted to mention that I think that this project you're undertaking
has quite a lot of promise.  Its exciting to think about what might be
available here.  One thing that this just made me think is that maybe the
LOC should maintain Copyright metadata, that would say if a work was in
the public domain.  Certainly, a field like this could be added to PM's
shared bibliography, when it is created.  Anyway, good job & looking
forward to seeing the final results of the search -- and the eventual
integration of the results into PM -- which could be the topic for a 
whole 'nother grant, and partnerships with people like the folks at
Cornell or elsewhere.  --[[file:jcorneli.org][jcorneli]]

* Improvement

Since the Library of Congress has redone its online catalog, it is now
much easier to obtain the lists of math books published in a given year.
To obtain the list of all books published in the year Y, one may proceed as follows:

1. Browse the url http://catalog.loc.gov/

2. Click on "Basic Search"

3. Click "Set Search Limits"

4. Type Y in "Date" box

5. Click "Set Search Limits"

6. Choose "Command Keyword*" from menu

7. Type "KCLA qa?" in "Search Text" box

8. Choose "100 records per page" from drop-down menu

9. Click "Begin Search"

10. Scroll down to bottom of page

11. Click "All (this page only)" button

12. Choose "MARC (non-Unicode/MARC-8)" from drop-down menu

13. Click "Press to SAVE or PRINT"

14. Save the file

15. Go back a page on browser

16. If there are more pages click on "Next" and repeat steps 10-15 

Using this new interface, I found the following numbers of mathematical
works published in differrent years

< 1699 268

1700-1799 568 

1800-1849 1407

1850-1899 1801

1900-1909 <2569 (some "19uu" bug in the system)

1910-1919 1464

1920-1929 2064

1930-1939 2759

1940-1949 3518

1950-1959 5263

1960-1969 13584

1970-1979 20470

1980-1989 25986

1990-1999 35067

2000-2007 26283

Also, in the period of interest, 1923-1963, the library catalog lists 16313
math books.  Using the figure that 85% of books did not have their copyright renewed,
this suggest that there there are something like a myriad math books in the
public domain from this period. (This, by the way, is more books than were 
published prior to 1923 (!)) Using the rule of thumb that graduate level math
is math in about this period, we should be able to come up with a library of
graduate level math books in the public domain.

--[[file:rspuzio.org][rspuzio]] 10 October 2007

Joe has automated the procedure outlined above in an 
[http://planetx.cc.vt.edu/~jcorneli/marc/record-fetcher.el emacs script].
The results of these searches are in the directory
http://planetx.cc.vt.edu/~jcorneli/marc/
As described in the next section, I subjected these to some further processing.

** MARC File Format

The records of the Library of Congress and the Copyright office are stored in the
MARC file format.  This format consists of a number of fields, each of which begin
with a three number code stating the content of the field (title, author, etc.) 
followed by the data divided into subfields by dividers of the form
$a
$b
$c ...
For instance, consider the following record:

 001 8264528
 005 20050715190526.0
 008 730103s1925    ilua     b    000 0 eng  
 035   $9(DLC)   25010087
 906   $a7$bcbc$coclcrpl$du$encip$f19$gy-gencatlg
 010   $a   25010087 
 035   $a(OCoLC)528073
 040   $aDLC$cODaWU$dOCoLC$dDLC
 042   $apremarc
 050 00$aQA315$b.B5
 100 1 $aBliss, Gilbert Ames,$d1876-1951.
 245 10$aCalculus of variations,$cby Gilbert Ames Bliss.
 260   $aChicago, Ill.,$bPub. for the Mathematical Association of America by the Open Court Publishing   Company$c[c1925]
 300   $axiii, 189 p.$bdiagrs.$c20 cm.
 440  4$aThe Carus mathematical monographs
 504   $a"A list of references": p. 180-181.
 650  0$aCalculus of variations.
 985   $eOCLC REPLACEMENT cdsdistr
 991   $bc-GenColl$hQA315$i.B5$p00004351174$tCopy 1$wOCLCREP

It might be worth pointing out that every record has a field 008 --- looking at it, it
might look like gibberish, but that is because each character in the string encodes
something.  In particular, to tell whether a book was published in the United states, look
at the 21-st character to see if it is a "u".  To locate the author, look at field
100, subfield $a.

The MARC records do not come nicely formatted as above from the Library of Congress;
rather, they come in a communications format which needs to be unpacked.  This, however,
is relatively easy to do.  A program to do this follows, but note that it has no error
checking and does not make use of the redundancy in the format to make sure all is well
so it can choke if fed corrupted data.

 /* This is a simple program to unpack MARC-8 files. To use
    it, type

            unpack file
 
    and the unpacked file will be written to standard output. */

 #include <stdio.h>
 #include <stdlib.h>

 int main (int argc, char *argv[])
 {
   FILE *raw;  /* MARC-8 file in communications format. */
   int size;  /* Place for size of record. */
   int base; /* Base address of data. */
   int done; /* Do we have more records to process? */

   int tag[128]; /* Tags for data fields */
   int len[128]; /* Lengths of data fields */
   int start[128]; /* Starting points for data fields */

   char foo[8], goo[8];

   int tg, ln, st;
   int j, k, m, n;
   char c;


   /* Open the file of raw data */

  raw = fopen (argv[1],"r") ;
  done = fscanf (raw, "%5d", &size);

   while (done != EOF)
     {

       /* Read leader. */
      
      
       fgets (foo, 8, raw);
       fscanf (raw, "%5d", &base);
       fgets (goo, 8, raw);
      
       /* Unpack tag and length information into their
   	  respective arrays */
      
       m = 0;
       n = 25;
       while (n < base)
    	 {
	   fscanf (raw, "%3d %4d %5d", &tg, &ln, &st);
	   tag[m] = tg;
	   len[m] = ln;
 	   start[m] = st;
	   m++;
	   n += 12;
	 }
      
       /* Unpack records. */
      
       for (j = 0; j < m; j++)
	 {
	   printf ("%03d ", tag[j]);
	  
	   getc (raw);
	   n++;
	   for (k = 1; k < len[j]; k++)
	     {
	       c =  getc(raw);
	       n++;
	       if (c == 31)
		 putchar ('$');
	       else
		 putchar(c);
	     }
	   printf ("\n");
	 }


       printf ("\n");
       getc(raw);
       getc(raw);
       done = fscanf (raw, "%5d", &size);
     }
 }

For a proper account of this file format and for specifications, please see the 
following documents from the Library of Congress.

http://www.loc.gov/marc/umb/
http://www.loc.gov/marc/

Using this program, the records which were retrieved as explained in the last
section were unpacked to produce files LOC.19??.QA.MARC (which are currently on 
my disk, but soon will be posted somewhere).  These were then passed through the
following AWK program, which filtered out the works published in the U.S. to 
produce the files LOC.19??.QA.USA:

 BEGIN {
      FS = "\n"
      RS = ""
 }

 domestic = 0;
 {
     for (i=1; i <= NF; i++)
     {
 	 if ((match ($i, /^008/)) && 
 	    (substr ($i, 22, 1) == "u")) domestic = 1;
     }

     if (domestic)
     {
 	 print;
  	 printf ("\n");
     }
 }
