#+STARTUP: showeverything logdone
#+options: num:nil

Majerus, Laura A.  2003
"Court Evaluates Meaning of "Derivative Work" in an Open Source License"
Findlaw
http://library.findlaw.com/2003/Jun/16/132811.html

Berry, R. Stephen 2001 "Is electronic publishing being used in the best interests of science? The scientist's view", Electronic Publishing in Science II, UNESCO HQ, Paris, (eds. Sir R. Elliot and D. Shaw), http://users.ox.ac.uk/~icsuinfo/berryfin.htm
(This link does not work. Do you mean
http://www.unesco.org/science/publication/electronic_publishing_2001/proceedings_recommendations.shtml#haank  ?)

Jean-Claude Guédon, 2001 "In Oldenburg's Long Shadow: Librarians, Research Scientists, Publishers, and the Control of Scientific Publishing", Proc. ARL Membership Meeting, May 2001  Available at http://www.arl.org/arl/proceedings/138/guedon.html

John Willinsky, 2002. "Copyright Contradictions in Scholarly Publishing", First Monday, 7,11 (November 2002), http://firstmonday.org/issues/issue7_11/willinsky/index.html

Greg Kuperberg, 2002 "Scholarly mathematical communication at a crossroads", arXiv:math.HO/0210144, Nieuw Arch. Wisk. 5,3:262--264. 

Steven Bachrach, R. Stephen Berry, Martin Blume, Thomas von Foerster, Alexander Fowler, Paul Ginsparg, Stephen Heller, Neil Kestner, Andrew Odlyzko, Ann Okerson, Ron Wigington, Anne Moffat, 1998 ``Who should own scientific papers?/ Science 281: 1459-1460 Available at http://www.sciencemag.org/cgi/content/full/281/5382/1459

Winners and Losers in the Global Research Village, P. Ginsparg 1996
Conference held at UNESCO HQ, Paris, 19-23 Feb 1996

Paul Ginsparg 1996
Los Alamos XXX
APS News November 1996 Available at
http://www.aps.org/apsnews/1196/11718.cfm

Sony Corp. of America v. Universal City Studios, Inc.
Wikipedia
http://en.wikipedia.org/wiki/Sony_Corp._v._Universal_City_Studios
	
United States Supreme Court 1984
Sony Corp v. Universal City Studios
464 U.S. 417 
Docket Number: 81-1687

The Oyez Project. 1984 Oyez: Sony Corp v. Universal City Studios, 464 U.S. 417 (1984), available at: <http://www.oyez.org/oyez/resource/case/768/> 
	
U.S. Supreme Court. 1991.
FEIST PUBLICATIONS, INC. v. RURAL TEL. SERVICE CO.,
499 U.S. 340 (1991)

UNITED STATES COURT OF APPEALS FOR THE NINTH CIRCUIT. 2004.
MGM Studios, Inc. v. Grokster, Ltd., 259 F. Supp. 2d 1029 (C. D. Cal. 2003), appeal argued, No. 03-55894 (9[th] Cir. Feb. 3, 2004).
Available at http://www.techlawadvisor.com/docs/mgm-grokster.html

Electronic Forntier Foundation. 2005
MGM v. Grokster
http://www.eff.org/IP/P2P/MGM_v_Grokster/

Fred von Lohmann 2004
Tech Dodges a Bullet
LAW.COM 08-27-2004
http://www.law.com/jsp/article.jsp?id=1090180416759

Consumer Electronics Association 2005
CEA Expresses Concerns Over Supreme Court Grokster Ruling
Consumer Electronics Association. Available at
http://www.eff.org/IP/P2P/MGM_v_Grokster/cea.php

Electronic Frontier Foundation 2005
Supreme Court Ruling Will Chill Technology Innovation
Electronic Frontier Foundation
Available at
http://www.eff.org/news/archives/2005_06.php#003748

Consumer Federation of America, Consumers Union, and Free Press. 2005
Statement of the Consumer Federation of America, Consumers Union and Free Press on the Supreme Court's Decision in MGM v. Grokster
Mark Cooper, Gene Kimmelman, Ben Scott
Available at
http://www.eff.org/IP/P2P/MGM_v_Grokster/statement_consumer.php

Fred von Lohmann 2005
1984 COURT RULING LAUNCHED A TECHNOLOGICAL REVOLUTION
Mercury News  Available at
http://www.eff.org/IP/P2P/MGM_v_Grokster/betamax_20th.php

Colin Darch 2001
The 'Alexandrian' Library, Digital Resources, and the Shrinking Public Domain:
the Current Model for Delivering Academic Information in Africa.
In LIASA Conference on “African Renaissance through Libraries”
Pretoria, 24-28 September 2001
Available at http://home.imaginet.co.za/liasa/DARCH2001.rtf.
http://64.233.161.104/search?q=cache:poaiHy1nm9EJ:home.imaginet.co.za/liasa/DARCH2001.rtf+shrinking+public+domain&hl=en&client=firefox-a

California State University, East Bay Library
Copyright and Intellectual Property
http://www.library.csuhayward.edu/staff/asoules/copyright_public_domain.htm

Kathryn Balint
Snap judgments 
San Diego UNION-TRIBUNE
May 30, 2005

Georgia Harper 2001
Professional Fair Use after Texaco
Austin: The University of Texas System
Office of General Counsel
http://www.utsystem.edu/ogc/intellectualproperty/tex2.htm#fn1

Georgia Harper 2004
WILL WE NEED FAIR USE IN THE TWENTY-FIRST CENTURY?
Austin: The University of Texas System
Office of General Counsel
http://www.utsystem.edu/ogc/intellectualproperty/FAIR_USE.HTM

Georgia Harper 2001
Copyright and the University Community
Austin: The University of Texas System
Office of General Counsel
http://www.utsystem.edu/ogc/intellectualproperty/mono4.htm

CARL/ABRC Task Force on Academic Libraries and Scholarly Communication 1995
TOWARDS A NEW PARADIGM FOR SCHOLARLY COMMUNICATION
Association of Universities and Colleges of Canada
http://library.uwaterloo.ca/documents/scholarly(aucc-carl).html

John Perry Barlow, 1994 The Economy of Ideas: A Framework for Rethinking Patents and Copyrights in the Digital Age, Wired, March 1994

Richard Stim
Getting Permission: How to License & Clear Copyrighted Materials Online & Off
Nolo, Berkeley, CA  2004
Also see http://fairuse.stanford.edu/Copyright_and_Fair_Use_Overview/index.html

U.S. Consitution  Article I, Section 8, Clause 8

United States District Court for the Southern District of New York 1991
Basic Books, Inc. v. Kinko'S Graphics Corporation
758 F. Supp. 1522   Available at
http://fairuse.stanford.edu/primary_materials/cases/c758FSupp1522.html

United States District Court for the Western District of New York 1983
Encyclopaedia Britannica v. Crooks
58 F. Supp. 1247  Available at
http://fairuse.stanford.edu/primary_materials/cases/c558FSupp1247.html

Pamela Samuelson 1996
The Copyright Grab 
Wired News
Issue 4.01 - Jan 1996  Available at
http://www.wired.com/wired/archive/4.01/white.paper_pr.html

Ann Okerson 1991
With Feathers: Effects of Ownership on Scholarly Publishing
http://www.library.yale.edu/%7Eokerson/feathers.html

William F. Patry 2000
Copyright Law and Practice
The Bureau of National Affairs, Inc.
http://digital-law-online.info/patry/patry1.html

Rob Kendall 2005
DRM Creep: Fair Use Dies Not with a Bang, but with a Whimper
Yale University Law Meme Friday, June 17 2005
http://research.yale.edu/lawmeme/modules.php?name=News&file=article&sid=1720

The UK Patent Office 2000
A history of copyright
The UK Patent Office
http://www.intellectual-property.gov.uk/std/resources/copyright/history.htm

U.S. COPYRIGHT OFFICE
REPORT ON LEGAL PROTECTION FOR DATABASES
U.S. COPYRIGHT OFFICE
August 1997
http://www.copyright.gov/reports/dbase.html

Karl-Erik Tallmo 2005
The History of Copyright:
A Critical Overview With Source Texts in Five Languages
work in progress
http://www.copyrighthistory.com/index.html

Thomas Jefferson 1813
Letter from Thomas Jefferson to Isaac McPherson
August 13, 1813
http://odur.let.rug.nl/%7Eusa/P/tj3/writings/brf/jefl220.htm

Carrie McLaren and Siva Vaidhyanathan ???? 
Copyrights and Copywrongs
Interview with Siva Vaidhyanathan
By Carrie McLaren 
Stay Free!  Issue #20
http://www.stayfreemagazine.org/archives/20/siva_vaidhyanathan.html
(Why does this magazine not give dates for issues!!!!!)

Siva Vaidhyanathan 2001
Copyrights and Copywrongs: The Rise of Intellectual Property and How It Threatens Creativity. New York: New York University Press

Kimberly Stedman ????
So what do I do about it?
Stay Free!  Issue #20
http://www.stayfreemagazine.org/archives/20/take-action.html

Lydia Pallas Loren 1997
REDEFINING THE MARKET FAILURE APPROACH TO FAIR USE IN AN ERA OF COPYRIGHT PERMISSION SYSTEMS
Journal of Intellectual Property Law, Volume 5 Fall 1997 1:1
Available at http://www.lclark.edu/~loren/articles/fairuse.htm

DAVID NIMMER 2003
"FAIREST OF THEM ALL" AND OTHER FAIRY TALES OF FAIR USEHarvard Law Review, 112(7), 1705-1722. 
Law & Contemp. Probs. 66:263 (Winter/Spring 2003) Available at
http://www.law.duke.edu/shell/cite.pl?66+Law+&+Contemp.+Probs.+263+(WinterSpring+2003))

Harvard Law Review. "The Criminalization of Copyright Infringement in the Digital Era" Harvard Law Review. Vol 112: 1705-1722

Christopher M. Kelty
Free Software/Free Science
First Monday, volume 6, number 12 (December 2001) Available at
URL: http://firstmonday.org/issues/issue6_12/kelty/index.html

Eric Raymond, 1999 The Cathedral and the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary. Cambridge, Mass.: O'Reilly.
http://www.catb.org/~esr/writings/cathedral-bazaar/

Jerome H. Reichman and Paul F. Uhlir, 2001. "Promoting Public Good Uses of Scientific Data: A Contractually Reconstructed Commons for Science and Innovation," Proceedings of the Conference on the Public Domain, Duke Law School, 9--11 November 2001 Availableat http://www.law.duke.edu/pd/papers/ReichmanandUhlir.pdf

Corynne McSherry, 2001. Who Owns Academic Work? Battling for Control of Intellectual Property. Cambridge, Mass.: Harvard University Press.

Siva Vaidhyanathan, 2002. "Copyright as Cudgel," Chronicle of Higher Education (2 August), B7--B9.

John Willinsky, 2002. "Scholarly Associations and the Economic Viability of Open Access Publishing," unpublished paper, Vancouver: University of British Columbia, at http://research2.csci.educ.ubc.ca/workingpapers/association.pdf

John Willinsky 2002
Copyright Contradictions in Scholarly Publishing 
First Monday, 7:11 (November 2002),
URL: http://firstmonday.org/issues/issue7_11/willinsky/index.html

Mary Minow 2004
How I Learned to Love FAIR USE
Stanford University Libraries
http://fairuse.stanford.edu/commentary_and_analysis/2003_07_minow.html

Robert S. Boynton, The Tyranny of Copyright, New York Times Magazine, January 25, 2004

Ginsburg, Jane C. 2002. "Essay - How Copyright Got a Bad Name For Itself" Columbia Journal of Law and the Arts, 26:1, 2002

Rob Kasunic
Solving the P2P "Problem" - An Innovative Marketplace Solution
Stanford University Libraries
http://fairuse.stanford.edu/commentary_and_analysis/2004_03_kasunic.html

Netanel, Neil Weinstock, "Impose a Noncommercial Use Levy to Allow Free P2P File-Swapping and Remixing" (Nov. 2002). Unpublished manuscript, available at: http://www.utexas.edu/law/faculty/nnetanel/Levies_chapter.pdf)

John Borland 2004
P2P companies say they can't filter
CNET
January 28, 2004
http://news.com.com/2100-1038_3-5149720.html

John Borland 2003
Teamwork brings P2P spying app closer
September 10, 2003
CNET
http://news.com.com/Teamwork+brings+P2P+spying+app+closer/2100-1027_3-5074429.html?tag=st.rn

United States Department of Justice 1998
The No Electronic Theft ("NET") Act
Relevant portions of 17 U.S.C. and 18 U.S.C. as amended (redlined) 
http://www.usdoj.gov/criminal/cybercrime/17-18red.htm

U.S. Department of Justice 2001
Man Sentenced in Michigan for Offering Software Programs for Free Downloading on "Hacker Hurricane" Web site
http://www.cybercrime.gov/baltutatsent.htm

David Goldstone 2001
Deciding Whether to Prosecute an Intellectual Property Case
 United States Attorneys’ USA Bulletin
March 2001 Vol. 49, No.2
http://www.cybercrime.gov/usamarch2001_1.htm
  (Does this relflect the intent of the Consittution?)

U.S. Department of Justice 1999
Defendant Sentenced for First Criminal Copyright Conviction Under the
 "No Electronic Theft" (NET) Act for Unlawful Distribution of Software on the Internet
November 23, 1999 
http://www.cybercrime.gov/levy2rls.htm

U.S. Department of Justice 2001
Nine Indicted in Chicago in $1 Million "Fastlane" Software Piracy Conspiracy
Feb. 16, 2001
http://www.cybercrime.gov/fastlane.htm

Department Of Justice 2005
Federal Law Enforcement Announces Operation D-Elite,
Crackdown on P2P Piracy Network:
May 25, 2005
http://www.cybercrime.gov/BitTorrent.htm

Declan McCullagh 2003
Perspective: The new jailbird jingle
CNET
January 27, 2003
http://news.com.com/Perspective+The+new+jailbird+jingle/2010-1071_3-982121.html?tag=nl

Declan McCullagh 2003
Share 'True Crime,' do the time
CNET
November 12, 2003
http://news.com.com/Share+True+Crime%2C+do+the+time/2100-1026_3-5106684.html?tag=st.rn

U.S. Department of Justice
Virginia Man Sentenced for Violation of the "No Electronic Theft" (NET) Act for Unlawful
Distribution of Software on the Internet
March 3, 2000
http://www.cybercrime.gov/thorntonSent.htm

Christine Schweidler and Sasha Costanza-Chock 2005
Piracy
vecam
http://www.vecam.org/edm/article.php3?id_article=93

---

Ann Okerson 1986
PERIODICAL PRICES: A HISTORY AND DISCUSSION
Originally appeared in: Advances in Serials Management
JAI Press
Volume 1 (101-134)
http://www.library.yale.edu/~okerson/pricing.html

Ritchie T. Thomas, Esq. et al. 1993
 *AMICUS CURIAE* BRIEF OF ASSOCIATION OF RESEARCH LIBRARIES,
AMERICAN ASSOCIATION OF LAW LIBRARIES, SPECIAL LIBRARIES ASSOCIATION,
MEDICAL LIBRARY ASSOCIATION, AMERICAN COUNCIL OF LEARNED SOCIETIES,
NATIONAL HUMANITIES ALLIANCE, AND ASSOCIATION OF ACADEMIC HEALTH
SCIENCES LIBRARY DIRECTORS
Available at http://fairuse.stanford.edu/primary_materials/cases/texaco/joint.amicus.html

Lydia Pallas Loren 2000
The Purpose of Copyright
Open Spaces Quarterly 2:1
Available at http://open-spaces.com/article-v2n1-loren.php

Brendan Scott 2001
Copyright in a Frictionless World: Toward a Rhetoric of Responsibility
First Monday, 6:9
http://firstmonday.org/issues/issue6_9/scott/index.html

A. Birrell, Seven Lectures on the Law and History of Copyright in Books, Rothman Reprints Inc., 1899 (1971 reprint).

Eric W. Weisstein 2001
Author's Detailed Commentary
http://mathworld.wolfram.com/about/erics_commentary.html

CRC PRESS, LLC, vs. WOLFRAM RESEARCH, INC., STEPHEN
WOLFRAM and ERIC WEISSTEIN,
UNITED STATES DISTRICT COURT
SOUTHERN DISTRICT OF FLORIDA
CASE NO. 00-893-CIV-GRAHAM/TURNOFF 
http://mathworld.wolfram.com/docs/CRCComplaint.html

Open Source Initiative 2005
The Approved Licenses
http://www.opensource.org/licenses/index.php

Richard Stallman 1985
The GNU Manifesto
http://www.gnu.org/gnu/manifesto.html

Free Software Foundation 2002
GNU Free Documentation License
http://www.gnu.org/copyleft/fdl.html

Richard Stallman 2002
Misinterpreting Copyright
http://www.gnu.org/philosophy/misinterpreting-copyright.html

Eben Moglen 2001
Enforcing the GNU GPL
http://www.gnu.org/philosophy/enforcing-gpl.html

Felten v. RIAA
US DC NJ Case #CV-01-2669(GEB)
2001

Richard Stallman 2004
Did You Say "Intellectual Property"? It's a Seductive Mirage
http://www.gnu.org/philosophy/not-ipr.xhtml

by Roderick T. Long 1995
The Libertarian Case Against Intellectual Property Rights 
/Formulations/ Autumn 1995 
Free Nation Foundation
Available at http://libertariannation.org/a/f31l1.html

S.Chopra and S. Dexter 
A Comparative Ethical Assessment of Free Software Licensing Schemes
http://www.sci.brooklyn.cuny.edu/~sdexter/copyleft_ethics.html

Johan Söderberg 2002
Copyleft vs. Copyright: A Marxist critique by 
First Monday, volume 7, number 3 (March 2002),
Available at http://firstmonday.org/issues/issue7_3/soderberg/index.html

Creative Commons 2005
Homepage
http://creativecommons.org/

Cornell University Library 2004 	
Guidelines for Using Text and Images from Cornell Digital Library Collections
http://cdl.library.cornell.edu/guidelines.html

Tufts University	
Perseus Copyrights
http://www.perseus.tufts.edu/copyright.html

Milton S. Eisenhower Library and Pierpont Morgan Library	
CONDITIONS FOR USE OF THIS SITE
http://rose.mse.jhu.edu/pages/intro_frameset.htm

Library of Congress 2005
About Copyright and the Collections
http://www.loc.gov/homepage/legal.html

Lawrence Lessig 2004
Free Culture 
How Big Media Uses Technology and the Law to Lock Down Culture and Control Creativity
The Penguin Press
Available at http://www.easylum.net/freeculture

J. Corneli 2005
What is the Hyperreal Dictionary of Mathematics?
http://www.ma.utexas.edu/~jcorneli/d/

John Baez 2003
What We Can Do About Science Journals
http://math.ucr.edu/home/baez/journals.html

The Elephant in the Internet, Daniel K. Biss, Notices AMS, November 2004

The Digital Mathematics Library, Allyn Jackson, Notices AMS, August 2003 

Three Views of Peer Review Steven G. Krantz, Greg Kuperberg, Alf van der Poorten, Notices AMS, June/July 2003

From Preprints to E-prints: The Rise of Electronic Preprint Servers in Mathematics Allyn Jackson, Notices AMS, January 2002

The Slow Revolution of the Free Electronic Journal, Allyn Jackson, Notices AMS, September 2000

Pricing of Scientific Publications: A Commercial Publisher's Point of View, Edwin F. Beschler, Notices AMS, November 1998

Reforming Scholarly Publishing in the Sciences: A Librarian Perspective, Joseph J. Branin and Mary Case, Notices AMS, April 1998

Sam Vaknin, Ph.D. 2002
The Second Gutenberg 
United Press International
Available at http://www.planetebook.com/mainpage.asp?webpageid=376

Michael S. Hart 1992
History and Philosophy of Project Gutenberg
http://www.gutenberg.org/about/history

By Scott Carlson 2004
In the Copyright Wars, This Scholar Sides With the Anarchists
chronicle.com, Information Technology
Volume 51, Issue 13:A29 

Negativland
CHANGING COPYRIGHT
http://negativland.com/changing_copyright.html

Steven Benowitz 1996
Is Corporate Research Funding Leading To Secrecy In Science?
The Scientist. 10, 7:1

Esther Dyson
Intellectual Value
Wired 3.07 
Available at http://www.wired.com/wired/archive/3.07/dyson_pr.html





----

I read over the whole set of copy for the paper you have here on !AsteroidMeta, but 
no real inspirations for "digital library" citations came to me.  I'll give it another
pass tomorrow maybe, but it looks like your content is pretty well supported by
this bibliography. --[[file:akrowne.org][akrowne]] Wed Jul 6 08:34:37 UTC 2005
