#+STARTUP: showeverything logdone
#+options: num:nil

Yesterday I had the opportunity to take a bus tour of famous sites
in Minneapolis labor history.  It was a fun trip; we went on an
old bus (hired from the transportation museum) and the tour guide was
an expert on the subject of local labor history.  Minneapolis is a place with a 
lot of history, and of course this trip presented just one little slice of the picture.
(But history may have a few holographic properties.)

I was interested in going on the trip after thinking about [[file:What is Free Culture|free culture.org][What is Free Culture|free culture]]
as an issue akin to the 8-hour day of days yore (and writing about this
in a [[file:Asteroid Bulletin for the week of May 1 2005|May 1 commemorative article.org][Asteroid Bulletin for the week of May 1 2005|May 1 commemorative article]] with [[file:akrowne.org][akrowne]]).

One of the people on the bus ride was the author of the book
[http://www.mnhs.org/market/mhspress/products/0873513983.html A Union Against Unions].  
Interesting stuff (as it was described on the bus ride and at that link; I haven't
read the book yet!) - about how local business leaders banded together to
try to keep unions out of Minneapolis industry.  The brutality with which police
handled demonstrators was fairly shocking (though not as horrific as what is going
on right now in Uzbekistan).  Of course, the tour guide gave evidence
to support the idea that the business leaders were working very closely with the police.
(There may be further evidence of this sort in the book, but it isn't
an unprecidented idea.)

As I try to apply my parallel, I have to stretch things a little.  Typically
hackers (in the "good" sense) are not guilty of "cybercrimes".  Enforcing
patents and so on is hardly "brutal".  But I assume that there are plenty of
examples of force being applied -- even if it is mainly the 
[http://www.zdnet.com.au/news/software/0,2000061733,39191668,00.htm force of inertia].

But maybe this is because free software (and culture more generally) has not yet
organized, not yet pushed the powers that be to do anything truly egregious.

Students, for example, are generally /clueless/ about free culture, and accept
their lot in life.  A student's union that demanded that free culture replace
proprietary culture in education would be a very powerful force.  But students
are typically /so/ clueless... it would be quite the uphill battle.
(I'm not even sure if we have a general student union here in the US, though
[http://www.nusonline.co.uk/ there is one in the UK]).  I don't know how much
of an active role students are ready to play in their own educations.  But the
power is certainly there, and this [http://www.efn.org/~jamesd/StudentLife.html has been recognized by some].

And yet (quoting from this link) "student unionism [is] nothing but a travesty
of a travesty, the useless burlesque of a trade unionism itself long totally
degenerate."   

According to these folks, the power of students is to reject education -- and
substitute revolution.

: /The student, if he rebels at all, must first rebel against his studies, though
the necessity of this initial move is felt less spontaneously by him than by the
worker, who intuitively identifies his work with his total condition. At the
same time since the student is a product of modern society just like Godard or
Coca-Cola, his extreme alienation can only be fought through the struggle
against this whole society. It is clear that the university can in no
circumstances become the battlefield; the student, insofar as he defines himself
as such, manufactures a pseudo-value which must become an obstacle to any clear
consciousness of the reality of his dispossession. The best criticism of student
life is the behavior of the rest of youth, who have already started to
revolt. Their rebellion has become one of the signs of a fresh struggle against
modern society./

Through struggle and rebellion,

: /The commodity and its laws [...] will be superseded by a new social form./

Well, I think that free culture is a pretty good contender to be this "new
social form".  Let's review a couple of details.

 * The artifacts of free culture are not "commodities"; while copies can
be bought and sold, they can also be infinitely replicated at small cost,
changed, and so on.
 * Producers of free artifacts need to have their basic needs taken care of
-- food is typically /not/ free as in beer (FAIB).  However, if
we think about rerouting the huge amount of money that go into the trade in
cultural artifacts that are not free as in freedom (FAIF) towards the production
of things that are FAIF, presumably there would be enough money to keep
the producers fed.

To say that "free culture is a labor issue" is probably to do it a disservice -
but it may well be a labor-like issue.  In other words, a way for people to organize for social change. To say that "free culture is
/revolutionary/ culture" -- may be getting somewhere.  But the revolution, in
the situationist lingo, must be /total/.

Educational reform would be nice, but I don't think it can happen in isolation:
we're talking about reforming society, and maybe even human life, here.

: /The new proletariat inherits the riches of the bourgeois world and this
gives it its historical chance. Its task is to transform and destroy these
riches, to constitute them as part of a human project: the total appropriation
of nature and of human nature by man./

If our decedents literally can /live for free/ -- whether it is because
mechanized, self-servicing, production facilities spread throughout the world,
or because humans are themselves superceded by thinking machines that run on
solar power (hey, 
[http://web.media.mit.edu/~minsky/papers/sciam.inherit.html Minsky] and [http://www.techsoc.com/genome.htm Dyson]
are allowed to talk this way) -- then I think we'd be pretty well qualified
to say that we had totally approprated nature and human nature.

Coming back to my theme for a little recapitulation (and no, I don't mean I was
backing off before).  Where is the /organization/ behind this revolution?  And
is one needed? - one certainly might think so.  On the other hand, it is also
the case that different people will do different bits and pieces of the work.

This is not a Catch-22: people can do work without being organized, and people
can attempt to organize a revolution without actually doing any work.
The best situation, however, would probably combine aspects of both work and
organization.

In order to be ready to rebel, people need to see how crummy their situation is
(comparatively speaking) and to do that, they may need to see a little glimmer
of how things might be.  Some science fiction movies and books are good for
that.  Science may even be somewhat better.

But science typically and society typically seem to support gradual change.
Some of the powers that be may be directly opposed to certain kinds of reform
that many others might like, or they may promise reforms and progress without
offering any truly revolutionary change.  That's what we're used to.

--[[file:jcorneli.org][jcorneli]] Tue May 17 03:54:31 2005 UTC (revised Tue May 17 18:45:55 2005 UTC)

----

I think libraries are becoming a bastian of free culture, which I especially realized 
after reviewing
submissions to the FCDL conference.  There really seems to be a general recognition
that libraries need to do something to ensure they will even have content to make
publicly available in the future.  And part of the solution --- perhaps the most important
part --- seems to be to assist efforts to produce "born free" culture.

I think they are just one constituency that is, and needs to, take part in this 
"revolution".  Another is students, and efforts like freeculture.org are aimed 
towards them.   And in a way, so is PlanetMath.  I wonder how many students PlanetMath
has made aware of free culture, and how many it has "converted" to the cause...

By the way, I don't agree with your "total" revolution remark (if I understand it
correctly).  In the same way that it is (or at least, seems to me) perfectly fine 
for closed software to co-exist with free software, why can't locked-down culture
co-exist with free culture?  Of course, I think we need /more/ free culture, but 
I would find it hard to make a case that there should be no permission-culture (to 
use Lessig's terminology) at all.

--[[file:akrowne.org][akrowne]] Tue May 17 04:13:37 UTC 2005

Total revolution is in the sense of "the total appropriation of nature and of
human nature by man".  Proprietary or free is actually somewhat irrelevant to
/this/ concern, at least at first glance.

But the issue with "proprietary" in the situationist rubric is that it means
commodifiable.  The situationists don't like that.  Personally, I'm currently
basically neutral on this issue, though I do think that a number of things that
/are/ commodified in our society shouldn't be, or should be seriously
reconsidered (e.g. I'm not that thrilled about the notion of elected
representatives).

I suppose that one theoretical problem with commodifiable stuff is that it
creates situations in which people are likely to be "kept down" -- think of the
unions and the Citizen's Alliance (union against unions) that I described at the
beginning of the note; more generally, it seems to be associated with conflicts
of interest.

By contrast, economically speaking, free stuff seems somewhat less likely to
have conflicts of interest associated with it.  As more freedoms become
supported, presumably fewer and fewer conflicts arise.  My interpretation of the
"total appropriation" thing is that the world should become an increasingly
hyperreal place.  More freedoms, less conflicts of interest.  The logic
kind of fits together.

But the primary reason I'd choose to support free stuff in this "total
revolution" is the hypothesis that it is a mode of production that is better
suited to revolutionary doings than the proprietary mode.  This is a hypothesis
that can be refuted (after the terms have been sufficiently defined).

I'm not talking about a revolution from proprietary culture to free culture per
say, I'm talking about social (and scientific) revolution that just happens to
find a friend in free culture.  If this makes sense.

BTW, I don't know off hand what "permission culture" means, maybe you could
create a wiki page about that.

--[[file:jcorneli.org][jcorneli]] Tue May 17 05:12:22 2005 UTC

Thanks to some [http://www.cybercrime.gov/CFAleghist.htm recent trends in copyright law], specifically the provisions which not only make certain cases of infringement a criminal offense but a felony at that, your analogy is not all that stretched anymore.  As of April 21, 2004, the Department of Justice has an "intellectual property taskforce" and the FBI has raided people who are running websites which distribute copyrighted material without the copyright owners authorization.  Computers have been confiscated and webmasters sent to jail.  While this isn't as brutal as what happened to striking workers, let alone what went on in Uzbekhistan, it is certainly not the genteel world of nineteenth and twentieth century copyright which was mostly a matter of civil law.  (In fact, from 1783 to 1897, copyright was entirely a matter of civil law, from 1897 to 1982, certain types of infringement were misdemanors, nowadays there is felony infringement.  Also, it might be worth adding that prior to 1992, infringement
could only be considered as a criminal offense if it was done "for purposes of commercial advantage or private financial gain." but nowadays not only is it considered a more serious crime but this provosion has been dropped, although the retail value of the work infringed is a criterion in determining whether a particular case constitutes a felony.  This sounds really lopsided to me --- why should someone who distributes copies of a commercial program go to jail and have his computer confiscated and lose the right to vote in addition to paying damages while someone who sells copies of a free program only have to pay statutory damages? )

--[[file:rspuzio.org][rspuzio]] 6 July 2005

-----

"Political Appointees Re-Write Commerce Department 
Report On Offshore Outsourcing; Original Analysis 
Is Missing From Final Version"
http://www.manufacturingnews.com/news/05/1012/art1.html


"U.S. urged to back science education, research
National Academy committee warns of foreign competition"
http://msnbc.msn.com/id/9675847/

 ..... 

Someone ought to connect the dots, maybe help those
folks who worry about outsourcing *and* the state of
US education. Why learn about math and science if
there won't be a job waiting for you one day in
America because you're competing globally and
US corporations are incentivized to replace Americans
with Indians, Chinese, etc.? 

And is there a connection with Open Source? Why do
programmers write code for zero pay? How can India
and China compete with *that* wage scale!@#?

{I started programming before there were cubicles :)
I will write code as long as I breathe. It is more
pleasant now, especially since we got rid of the
punch card machines :) Who wants to work for a
corporation *anyway*! You want to be a monkey for
the guys in suits and ties? IMO, knowledge is not
only its own reward, but will be rewarding otherwise.}

I applaud the efforts of Planet Math and the folks
that are working to make knowledge accessible to
all, regardless of nationality or economic status.

Keep up the good work!

[[file:ocat.org][ocat]] -- 15-Oct-2005


This point about accessibility is really tops.

The essay above alludes (vaguely) to the fact that even
many people at the "top" of the economic hierarchy
are being denied content, as they are caught in
a mechanizing/commodifying educational system that
reduces them to cogs in a machine.

I'm not sure about the connection with programmers willing to write
for zero pay: as you say, knowledge is rewarding.  Personally
speaking, my experience coding & interacting with other people
interested in free software, free content, and free culture has been
more fun and educational than my experiences in higher education.
Said coding experience even made me employable, once upon a time, and
maybe it will do it again in the future.  But for the future, while I
think I'd be happy to get money as part of my reward-basket, I'm keen
on sticking to free software development only.  The main ideological
reason for this, in my case, is that I think free software, content,
and culture are the ways to bring about "total revolution" in the
situationist sense.  

This conversation relates to a topic we were talking about in
Atlanta recently, namely the idea of [[file:revising copyright law.org][revising copyright law]].
-- [[file:jcorneli.org][jcorneli]] Oct 16 05

This sci-fi novel is new and relevant:

http://www.accelerando.org/2005/06/28/#download-2

I am deep into chapter 7, and maybe the ending will
suck, but so far I am quite happy with my time
investment :) 

Mind candy. I don't think any buzzwords were omitted!

Just download the html zipped version at 360K size,
then text zoom once in the browser so you can kick 
wayyyy back and relax, hitting page down in comfort
as each page gestalt registers in the back of your
skull :0)

--[[file:ocat.org][ocat]] 16-Oct-2005
