#+STARTUP: showeverything logdone
#+options: num:nil

In the course of writing, one often finds it expedient to quote or adapt an exposition of some subject from an already existing source.  To do so legally, one needs to obtain the permission of the copyright owner.  If the work has not been released under a license which grants these rights, one needs to obtain explicit writeen permission.

Traditionally, checking that such permissions are in order is one of the services which publishers have offered their authors.  Nowadays, however, as authors are increasingly becoming their own publishers online, they are forced to take this responsibility onto themselves.  At times, the result is that well-meaning but naive authors run afoul of copyright law despite their best efforts to the contrary.

This can be illustrated with two incidents which the author of this essay is familiar personally.  Someone based a number of entries for an online encyclopaedia on a book which was in print.  Before posting the entries, their author took care to obtain the permission of the author of the book on which they were based.   Later on, this led to some consternation when it was realized that these entries may nevertheless infringe on the book's copyright.  The problem was the publisher of the book has a policy of obtaining all rights to books which they publish and asks that requests for permission to adapt works be made through their permissions department.  Apparently, the author of the original work did not fully understand the terms of the contract which he had signed with the publisher and the author of the derived work saw no reason to suspect that this might be the case.

The other incident involves the posting of an electronic version of a book to a digital library.  The poster saw that this file was available through its author's homepage and so reasoned that it would be permissible to also make copies available through the online library.  This line of reasoning was faulty because, while the author had made a special arrangement with the publisher to distribute the book through his website, this contract did not permit anyone else to distribute the work electronically.

* Discussion

Back to [[file:Free Math and Potential Bottlenecks.org][Free Math and Potential Bottlenecks]]
