#+STARTUP: showeverything logdone
#+options: num:nil

After the recent conference at Emory, I wrote a page about [[file:next steps for HDM project.org][next steps for HDM project]].
And it was good.  But I think that in addition to that page, the rather general and relatively static (and perhaps no longer looked at) page on
[[file:Plans.org][Plans]] for all AM projects, and the general [[file:Guide to the HDM.org][Guide to the HDM]], it would be good to
have a page that can be used as a place to sketch out HDM plans.  
Anything major that concretely hangs together can be split off into another separate page.

* Human Resources

I am essentially "full time" on the project, although I do still have
some outside interests and responsibilities (including work on the
[[file:FEM.org][FEM]]).  However, I don't know if my time is being used as well as
it would be if I was part of a full time co-located research team.
Its a lot to ask for, I know, when I still have trouble networking
with local researchers who are doing only vaguely related stuff; when
the next-most-directly-involved contributor so far only has a few
hours per week; and when many of the people who have expressed
interest in the project are not actually interested in contributing
and live very far away to boot.  Sad day.  But maybe not so bad.
Still, any thoughts about how the project can amp up its Human
Potential would be apprecaited.  What would we need to
permit/entice/induce Ray to go full time?  Are there other people out
there (anyone?) who would like to put in a few hours a week
volunteering?  I've come to terms with the fact that out of all the
projects in the world, HDM might not be the most exciting one for some
people to work on - imagine that!  But surely there must be some other
math grad students who have grown egregiously frustrated with their
programs but who still love math, or Ph. D.'d mathematicians who want
more than just a math career, or linguists who recognize mathematics
as a potentially useful domain to investigate, or free software fans
who also dig the idea of free math.  Of course there are.  Some of
these people are even publishing research articles on these topics!
So why does the HDM team feel so small?  Perhaps we aren't doing
enough outside reading, or perhaps our communication tools are (so far
anyway) too limited.  People have [[file:HDM criticism|suggested this.org][HDM criticism|suggested this]] in
the past.

And as for me... I feel like doing something in-between becoming a sequestered
HDM otaku and taking a vacation to get some exercise and fresh air.  No doubt
this just means business will continue as usual.  But I thought I'd throw
this little piece up here and see if anyone has any feedback.

: What's an otaku? --[[file:rspuzio | Ray.org][rspuzio | Ray]]

:: "Obsessive shut-in" (see the [http://en.wikipedia.org/wiki/Otaku wikipedia page]) --[[file:jcorneli|Joe.org][jcorneli|Joe]]

* HDM funding

There is a whole page about this, [[file:HDM funding|here.org][HDM funding|here]].  Maybe it would 
be easier to get funding if there were some more publications associated
with the HDM project.  Since I've now published a non-technical description
of the [[file:scholium system.org][scholium system]], perhaps its getting closer to time to publish
a more technical description.  The more stuff we put out there the easier
it will be to find clients, in general.  While it might be nice to get
funding to e.g. make PM more scholiumific, we might also spend some time thinking
about ways to productize (or service-ize) HDM.  Funding isn't really
necessary if we have sufficient outside+volunteer support (see above)
but it would probably be helpful even if not necessary.  Maybe we 
could "sell out" like the Deep Blue team & keep all the FAIF
aspects of the project intact.

* Discussion

 * [[file:HDM practitioner work habits.org][HDM practitioner work habits]]
 * [[file:HDM Feasibility Study discussion.org][HDM Feasibility Study discussion]]


----
[[file:HDM.org][HDM]]
