#+STARTUP: showeverything logdone
#+options: num:nil

* Further comments (on the reaction to my suggestion of starting over)

(*pant pant*)

Running from the editing conflicts (that was intense)...

** Responses to akrowne

: I think we may be belaboring it at this point.

Maybe so.

: he would like to offer up a rewrite?

(I think I'll just stick with suggestions for now, given that Alvaro owns the
task; he can accept or reject those, and I'm willing to continue to discuss if
he wishes.)

: started when another popular mathematics reference site was taken down in a copyright lawsuit

This "genesis" of PM is important to understanding the site as a whole, but I
don't know if it needs to be part of a basic introduction & overview of what the
site is today, in 2005.

** Responses to rspuzio


: "Although this may have been the original motivation for founding Planet Math,
we soon discovered that Planet Math was much more than simply a mathematical
reference work --- it evolved into an online mathematical community ..."

Better in my view too.

: Although we know it quite well and may be sick of hearing it
repeated, I would guess that a good portion of the intended audience has not
heard of it.

Still, if we're going to talk about !MathWorld, can we please say something that we haven't
seen so many times before?  If I was reading this article, and then I logged
onto PM for the first time, I would feel a little ripped off to find that that
part of the article came more or less directly from the "About" page.

: be shocked and thereby appreciate why some people consider Free
Math to be important and contribute in some way.

I'd rather make the "initial motivation" for free math /positive/ -- maybe
that's my problem with the !MathWorld story.  I think that when PM "discovered
itself" as an online knowledge community might be the "real" beginning of the
site.  The rest may be apocrypha.

: It makes for a more interesting story when one finds out how something which
was designed for one purpose turns out in the end into something entirely
different than what its designer intended.

Well, true, that is a good point.  If that is the approach that this article
takes, I think the wording would end up being rather different from the current
wording, or the "About" story.
--[[file:jcorneli.org][jcorneli]] Mon May 02 02:32:17 2005 UTC

* Responses to alozano



: I think the thesis is clear, it is just a short description of the site and
the different aspects that I think are relevant.


That is a /theme/, not a thesis.  It is misleading to write a POV article
(which I think this is) without providing your thesis up front.  If you wanted
to make the article completely NPOV, then it would be OK to have no thesis and
simply have a theme.

If you decided to make the article completely NPOV, then I guess you could keep
the same basic structure w/o trouble, but you would want to be very careful to
make all of your statements very objective.  This approach sounds harder to me
than rewriting the article as an openly POV piece.  Even though it would
probably involve less restructuring, it would involve a lot of editing and
rewriting, since every point you made would have to be intersubjectively
verifiable.  If you go the POV route, you don't have that particular load on
your back.

That's why I'm suggesting a merge of the two: a short NPOV section (the hard
part) and then a longer POV part (the fun part).

Its totally up to you, certainly, but please, whatever you write, use your
discretion!  A lot may depend on this article (even if it is only 600 words long).

Please look at the fact that I had lots of comments as being similar to the fact
that usually movies have 50 hours of shooting time to 1 minute of screen time.
(Or whatever it is... the ratio is huge.)
--[[file:jcorneli.org][jcorneli]] Mon May 02 02:53:26 2005 UTC



----
[[file:Discussion of Article for FOCUS.org][Discussion of Article for FOCUS]]
