#+STARTUP: showeverything logdone
#+options: num:nil


I would assume that our goals for sponsorship relationships are, generally
speaking, to accomplish ends that are pursuant to our personal [[file:Goals.org][Goals]].  (Now
might be a good time to reflect on whether the goal statements given on this
aforementioned page need updating.)

For example, for [[file:jcorneli.org][jcorneli]] (and presumably [[file:akrowne.org][akrowne]]), goals include:
getting some income.  But there's more to it than just that.

* How to?

The income thing could be accomplished in several ways.  

The short-term ways are fairly obvious (and there is no guarantee that they will
work).

Long-term ways include things like building a "coalition" or "team" that will
help us get grants in the future.  There is no guarantee that this will work
either.

Other goals (what are they?) may require different approaches.  E.g., if we want
to get more people to add things to PM, or more people to write code for PM,
we'll have to do some serious work to facilitate that happening.


* Something to consider

If we had membership fees going, maybe we could get some organization or other
to do matching donations.  Just a thought.  
