#+STARTUP: showeverything logdone
#+options: num:nil

Google ([http://www.google.com external link]) is not a project for creating "free content" or any 
of the other things that this wiki is supposed to be about.

However, if you read their documentation, they do seem to
have some high-minded ideals, e.g. their core goal
of "making the world's information universally accessible and useful" -- whatever that means! Here's what they say about
how their mission relates to one of their products, Gmail:

: Google's mission is to organize the world's information and make it universally useful and accessible. We know that more and more of the information that's important to people is being exchanged and kept in email and chats. It can be overwhelming to keep track of this information, or to find later. We believe we can help with that. 


This relates tangentially to commons-based peer production. 
(In a way, Google's !PageRank technology simply exploits existing CBPP). 

At any rate, Google is mentioned all over the wiki, and at
least for the past year or two, when I describe the things
I do to casual passers by (e.g. my family) they say, why
don't you get a job at Google? (After hearing this advice
enough times, I actually sent a letter of interest to
a few Google types, but never heard back.)

What does Google do that's relevant to what we're doing?
Perhaps we can start to answer that question here, as
the core part of a general open-minded critique.

One thing they /did/ was answer questions.  I even
went so far as to call them the web's ultimate answering
machine once upon a time, in a fit of Adamsesque good humor.

But [http://slashdot.org/articles/06/11/30/1858254.shtml they don't do that anymore].
(I feel privilaged to be the one bringing that interesting recent news to
the Asteroid.)

Here is an article describing the
[http://www.infotoday.com/SEARCHER/oct02/west.htm experience one person had working for Google Answers] (back in the day). (Short epilogue [http://www.infotoday.com/SEARCHER/jan03/west.shtml here].)

--[[file:jcorneli.org][jcorneli]]
