#+STARTUP: showeverything logdone
#+options: num:nil

This is an interesting and potentially effective way to advertise for free: the [http://www.google.com/grants/ Google Grants] 
program.  It's not so aptly named--- it really doesn't have anything to do with making
monetary grants.  Instead, they give free !AdWords to 501(c)3 organizations.  This could
get us free publicity by delivering a set of targeted messages based on keywords.  
 
The big problem with this, as I see it, is that we can't be both a Google Grants recipient and an
!AdSense customer.  Thus, we should only go for Google Grants if it seems like that the additional 
users acquired will bring in more donations than the current !AdSense revenue averages (i.e. $100-$130
a month).  This is a big "if".  It won't be until donations dwarf !AdSense revenues that we should attempt
it, in my opinion. --[[file:akrowne.org][akrowne]] Thu Jun 30 21:32:42 UTC 2005

Of course, in making this assesment, one also needs to keep in mind that the ads now come with an overhead in the form of a limit on the proportion of toal revenue to the site which they can provide and the requirement to report such income in a special way.  In particular, if donations don't outweigh (if not overwhelm) advertising revenue by a factor of at least 3 to 1 (or maybe 10 to 1) won't the tax-exempt status be in jeopardy?  However, I would agree that as long as the ads are what pays the bills, it would be imprudent to drop it prematurely. --[[file:rspuzio.org][rspuzio]] 30 June 2005 (Oh dear, is is this close to the Emory deadline already :( )
