#+STARTUP: showeverything logdone
#+options: num:nil

An idea for Planet Math (and team): create logic/math courseware,
and sponsor classes using that courseware. 

The work to develop the courseware would be done
by "students" and volunteers who want to obtain
work experience in video production, technology, 
teaching, project management, marketing, writing, 
tutoring, administration, clerical, record-keeping,
personnel management, etc. 

A requirement for the plan to work is that there 
is/will be free software available that is good 
enough for doing homework exercises. This means that 
students can independently do their work and check 
their results.

The courses would be multi-media, consisting of
DVD, html *and* software, so this means plenty
of opportunities for people wishing to learn about
making videos and building webpages! 

The key to the whole thing would be Planet Math
and its renowned President, Aaron Krowne, lending their reputations
to the enterprise. The workers would apply/register with
Planet Math -- real identities -- and would be able
to obtain, upon successful completion of work assignments,
valuable resume line items and references! And that
means employability for people wanting to join the
workforce!

There are spin-off possibilities that might benefit
Planet Math, by the way. Has anyone noticed that
cable TV has non-commerical channels available in
each locality? It is possible that the DVD's could
be presented on cable TV, with tie-ins to the Planet
Math website. And the videos could be distributed
over the internet, assuming someone wants to pay
for the bandwidth...

The actual class "delivery" side of this would include internet,
via Planet Math, with a forum for each on-going class
where students could ask questions and receive quizzes.
At the end of each class there could also be a final
exam, which would be mailed to the student's designated
"proctor" (priest, teacher, counselor, etc. ) for 
administration to the student and grading by staff at 
Planet Math -- for a nominal fee, of course.

I'm sure others can develop this idea more concretely,
but what I think would make it work would be the 
commitment to do each part of the work at a professional
level, regardless of how long it takes to develop the
courses. Thus, each area of specialization will require
a cadre of budding experts who are developing the skills
to do professional work in support of the projects. 

(By the way, in case there is a shortage of volunteers
to appear on video presenting the course material, it
may be that costumes could be used to hide the instructor's
identity -- like an Einstein costume, or a bunny suit,
or something designed by the video producers for the
purpose.)

The first course should be, I believe, elementary symbolic
logic, a subject sorely needed in American culture.

----

My reputation?! I wouldn't want to curse the project so.  

Probably better to get known names in their respective
fields to participate in something like this.

MIT Open Courseware serves as inspiration (do they have math?),
but we could somehow provide "bundling" of courses that would
include a community and instructional element.

We needn't go to the extravagance of TV and Videos... we could
start with lectures and Q&A via internet chat and message boards.
Math IRC channels have been doing this for years (one thing we
could do NOW is to start archiving these lectures).

--[[file:akrowne.org][akrowne]] Thu Feb 23 15:21:31 UTC 2006

[http://ocw.mit.edu/index.html MIT OpenCourseWare]
[http://ocw.mit.edu/OcwWeb/Global/all-courses.htm 1250 Courses!]
----

This is the video age. People don't read much anymore,
and anyway...to make converts to strange philosophies
like math and logic you need tasty Kool-Aid! Seriously.

I see this as making Stone Soup. 

Yesterday I reviewed a software package with some
very admirable qualities. But the help/documentation
and GUI were flawed. I know the author really had a
heart for doing the coding, but the other parts were
not of the same quality. 

Remember, Stone Soup requires only a stone and a big
cooking pot. Everything else is brought by the people
who want to eat. So making videos would require at least
one aspiring video producer, and you can bet that 
someone like that can get h/er hands on equipment,
at least as a loaner. (Visit the local JC and see...)

That's my story, anyway -- in 10 or 15 years a fine crop
of researchers will be ready :)

--[[file:ocat.org][ocat]]

----

Maybe a partnership/(sell it to them) with someone like The Teaching
Company, http://www.teach12.com/teach12.asp?ai=16281 I really enjoyed
a couple of their lectures, but all they have are tapes, DVD, VHS,
mp3, etc. and not a interactive environment.  Chips for thought.

--[[file:bloftin.org][bloftin]]

I certainly like this idea of looking for partnerships, however when I
looked at this particular firm, I find it hard to see what we
could offer that they might want.  The way their business is very much
founded upon tradidtional academia --- the lecturers for their tapes
are all university professors who have been chosen according to the
usual criteria of prestige.  From reading their description, I get the
feeling that we would have about as much chance of patnering with them
as Wikipedia would have of partnering with Brittanica.

However, this idea of a partnership with a company which makes
educational recordings, videos and the like is a good one, it is just
a matter of finding a suitable firm.  The deal would be that we
provide them with mathematical knowledge and they make video and audio
lectures out of it --- it is worth noting that our stuff has the
advantage of not having to pay royalties to a textbook company --- and
in return we get some procees from their sales in order to keep up the
good work.  We could also accommodate specific needs --- for instance,
if our collection is lacking in some subject area which they plan to 
making a film on, we could put up some requests and issue a bounty to
encourage people to write those entries.
-[[file:rspuzio.org][rspuzio]]

I saw an engrossing program on actuarial science on some educational TV network/syndicate
a while ago.  I don't remember what the name of the station was, but I think they circulate content all over the country.
Even places like WBGH or PBS might be interested in becoming part of the modular
system folks are discussing here.  I think Ben has a good point, to capitalize on existing producers & distributors of content.  --[[file:jcorneli.org][jcorneli]]
