#+STARTUP: showeverything logdone
#+options: num:nil

A simple, flippant answer to your question about me going full-time
might be "a full-time salary of $30 000 per annum and a decent
benefits package".

However, there is another aspect of this issue that needs to be
considered --- while I could definitely spend more time on this
project, I am quite sure that there is a definite limit to how much
more time I could put into the project and still maintain productivity
based on the way my mind works.  The aspects of the project which I am
working on nowadays are conceptual and theoretical topics related to
proof checking.  To make any useful headway in these endeavors
requires sustaining intense mental concentration for hours on end.
The effort involved puts an immense strain on my brain and I need time
in order to recover and rest and reorganize my thoughts before
returning to the topic.  For instance, coming out with the theory of
systems and meta-systems which I outlined in Atlanta and
[[file:Monadology of systems|am now writing up.org][Monadology of systems|am now writing up]] required several brainstorms over the
course of a few weeks or so to figure out, the final one being at
Aaron's place.  While I find few things as exhilarating as these peak
times of immense creativity and mental clarity during which I can
effortlessly sustain a dozen or more distinct streams of consciousness
simultaneously, equally aware of all of them and able to switch
attention betwen them at will without getting lost or confused, see
connections between all sorts of apparrently unrelated topics, recall
most of what I know about math and related subjects at a glance, deal
with a flood of creative insights and compose texts several pages long
almost instantaneously (well, at any rate, much faster than I could
possibly write them down or speak them), these experiences can also be
immensely draining.  For a second-person account of me during one of
these states (and for some information on what circumtances help me
induce and maintain these states), please ask Aaron about the time
over his house Saturday night when I simultaneously put the finishing
touches on the definition of meta-system, explained the basics of
quantum mechanics, concieved the notion of quantum mechanics as a
meta-theory of classical mechanics and discussed the operation of
radar speed guns.  While I can stay in these states of consciousness
and concentrate my focus on a single mathematical problem for hours on
end (my record is 100 hours without food or sleep concentrating on a
system of differential equations), this comes a price --- for every
hour I spend in this heightened state, I need somewhere from 2 to 8
hours (depending primarily on the depth of thought during the active
phase) of rest lest I burn my nervous system out from the intensity of
thought.  By "rest" here, I don't mean lying down for a nap as much as
I mean leaving math alone and doing something completely unrelated
such as playing music, talking about the social/legal aspects of what
we are doing, working with my hands (building a cabinet, installing
plumbing, building a machine, or what not).  (In fact, simply lying
down doesn't necessarily work here --- something is needed to focus my
mind from wandering back to math.)

Another of my idiosyncracies is that my brain seems to run on a
multi-tasking operating system and am most efficient while doing
several (perhaps unrealted) things at the same time.  For instance,
right now I am writing both this reply and working on my
"[[file:Monadology of systems.org][Monadology of systems]]" entry.  while my fingers are typing in one window, I am
simultaneously thinking of what to wrote in the other window.  I seem
to work best this way and would not necessarily proceed much faster on
a task were I to work on it alone to the exclusion of all else.

Therefore, if I am to contribute to HDM to the fullest of my
potential, the notion of full-time work that is relevant might be
somewhat different from the usual notion; it might look more like
part-time work, once one figures in the fact the periods of rest in
that are needed to support the periods of activity.  That isn't to say
that the current state of affairs couldn't be improved upon, just that
the sort of improvement that would result in my maximum productivity
might bear little resemblance to the usual arrangement.  As mentioned
earlier, I likely could put in a bit more time than I am presently
putting in.  Certainly, not having to worry about where the next
paycheck is coming from and not feeling constrained to do something
unrelated simply for the money would help.  Also, for optimum
performance, I do best in a relatively calm, safe, stress-free and
low-pressure environment with access to a diverse, tolerant,
open-minded, curious, creative, playful, flexible, self-experimenting
(counter-)culture for socializing.

I seem to do best with a judicious mix of working together and working
alone.  For instance, the experience of meeting with you both in
Princeton and Atlanta and having the opportunity to discuss what we
were working on was awesome; it really inspired me and led to a lot of
wonderful results.  At the same time, I'm not sure I'd do that well if
I would do all my work closely collaborating with someone else on
every step --- perhaps because of the way I grew up, I need to spend
time alone with a problem, understanding it in my own terms and
working on it my own way before talking to others and working
together.  In particular, I think that a set-up in which I do some
work by myself, do most of the communication and collaboration online,
and meet every so often in person to talk would be ideal.  The only
thing that I would change about the current situation in this regard
is adding the means for us to meet more often (say a travel budget)
and for us to be able to meet in person for longer periods of time,
maybe even a month or more on end as the nature of our collaboration
warrants.

Alright, this response has gone more in the direction of describing my
idiosyncratic work habits and preferences.  However, I don't
necessarily see this as a digression.  In my opinion, the correct
question here is not how to push me to work full time, but how to
create a situation in which I am likely to contribute the most to the
project.  Even if the ideal situation outlined above is unattainable
in every detail in the near future, I can certainly try to arrange my
environment to come as close to this ideal as circumstances
allow. --[[file:rspuzio|Ray.org][rspuzio|Ray]]

Nice response!  I'm probably too tired to give it its due or even to
reply in kind - but I'll mention that some of my best-documented and
funnest mental functioning for HDM-related stuff has been when I've
sat down with a long printout of the scholium system, and attempted to
regard the text as a whole, jumping from page to page adding marginal
notes all over the place.  I'm mentioning this to point out that I
have a sort of multi-tasking strategy too.  But I've also been working
in big cycles (e.g. particularly, (code, theory)).  Since Atlanta I've
taken a sort of break from both.  I think I may need some sort of more
serious rest... I'm not sure what kind (sleep might be good for
starters).  I've done a little work on my apartment, and that's nice,
but not exactly sufficient.  I'm also trying to figure out what the
next big thing is going to be - maybe I should chill out about that
and spend more time with the next small steps (they could turn out to
be important).  I think we've both got work to do in terms of making
our personal and group dynamics closer to ideal, and I look forward to
that taking place (and to the ever-improving results).  I agree
(talking from personal experience) that "full-time" doesn't
necessarily imply fullest-productivity.  It is interesting to think
about the sorts of steps that might lead to that most-ideal dynamic,
or to a better approximation thereof.  --[[file:jcorneli.org][jcorneli]]

One step towards a more ideal dynamic is definitely having good tools at hand.  To use a different example as illustration, I am now installing a new bathtub spigot in the downstairs apartment and adding new telephone and data lines in my apartment.  Since I have a nice collection of wrenches, pliers and screwdrivers, this job is a breeze.  However, if all I had was a rusty old pair of pliers, I _could_ still pull off the job, but it would be a nagging chore.  (Interestingly, the same notion of passing to meta levels appears here as well --- the well-known fact about certain machine tools (such as lathes) being able to reproduce themselves can, I suppose, be regarded as the transposition of Goedel's metamathematical theme to the key of Planet Technae (a meta-lathe is a lathe).)

Likewise, having the right mental tools is definitely important to being productive with HDM.  What we are working on now --- the scholium system and the theory of systems and meta-systems --- can be seen in this light.  Both of these projects have as their aim the development of general frameworks (what a mathematician of the Bourbaki school might term "high-powered "general nonsense" machinery") --- the scholium sytem is a general framework for interlinked text and my theory is a general framsework for a certain kind of mathematical systems (and maybe even non-mathematical systems).  We hope that these tools, along with similar gadgets such as lambda-calculus, set theory, and category theory, will help us to formulate and express the ideas we are dealing with.

An aspect of organology which could definitely use improvement on my end is my computer connection.  As I mentioned in Atlanta, my internet connection is atrocious.  While I will make the best of this in the meanwhile, I also have a quite definite plan to ameliorate this situation which I am working on:

 1. Locate the package of material which Verizon sent me --- this is now buried away somewhere in storage ;)

 1. Surf the web for more information on using Verizon DSL under GNU/Linux --- I have already found a webpage stating that this is possible, but it would be nice to have some more specific information, ideally a step-by-step recipe.

 1. Finish installing the new phone/data lines and building the new desk in my personal library so as to have a better physical space in which to work (right now I am putting up with a rather makeshift arrangement).

 1. Combining the information gleaned in the first two steps, come out with a plan and test it on my laptop (which runs GNU/Linux)

 1. Reformat my computer hard drive on my workstation (which now runs windows (I think some latter-day Edison deserves a Darwin award for having concocted an operating system which so blithely manages to eat up my 80 gigabytes of storage and fil up my megabytes of RAM, crashes whenever I try to download a PDF file, and slows my gigahertz box to the point where I feel like I'm using my old Z80 or 8086 at a megahertz or slower :)  I suppose that I could probably fix most of these shortcomings if I were willing to shell out money periodically to buy upgraded versions (these people are masters at backwards-incompatibility) or pay more than the price of my computer for the _real_ manual (as opposed to the silly book with the cute cartoons that came with the product) but even if I did, it's not like I'd ever get a peek at the source code.) and will be located in the library when I get to this step), install an intelligent operating system, and then carry out the procedure tested in the last step on the new set-up.

 1. Get CVS, the scholium system, and all the other good stuff up and running and have fun being productive with the new set-up.

I assume that it will take a month or so to accomplish this, so I should enter the new year with a lean, mean machine ready to do some serious data crunching.

While on this topic, it might be worth mentioning the importance of automation.  Our critics have repeatedly pointed out that the vast amount of work necessary to carry out our plans --- the latest estimate was a person-century.  One of the ways which we hope to adress this issue is by making use of the dynamics of commons-based production.  While we have talked about this extensively, it might also be worth noting another strategy we hope to employ --- automation.  Rather than doing many of these tasks by hand, we hope to make use of the good-old Yankee strategy of building a shop full of gizmos which will do the job for us with minimal human intervention.  Admittedly, doing this takes a bit more sophistication than simply doing the original job.  This is why we have been so keen about trying to pass to meta-levels all the time.  (I suppose, part of the motivation for the name of this website.)  For the task we have set ourselves, this means things like writing programs which write programs, automatically translating notations, and even natural language parsing.  Admittedly, this plan involves doing things which we now don't know how to do.  However, we would also point out that there are no compelling reasons why these things should be impossible and the rate of progress of computer science seems encouraging.  Therefore I would say that bets are off on whether we can pull this off and I tend to regard this as something of a gamble --- if we win, then it will be possible for a small group of people to pull off a task of this magnitude.  --- [[file:rspuzio | Ray.org][rspuzio | Ray]]

----

[[file:HDM planning.org][HDM planning]]
