#+STARTUP: showeverything logdone
#+options: num:nil

I imagine that some PM contributors could use additional/new small-scale
hardware. If there is a way to make such donations work, I think they should be
encouraged rather than discouraged (as appears to be the case on
http://aux.planetmath.org/doc/donate.html currently). We don't have warehouse
space... so there would probably have to be a way to have the donor and the
recipient connect directly.  Can the wording be changed to make it less
discouraging?  Maybe create a forum for "p2p donations"? --[[file:jcorneli.org][jcorneli]] Mon Feb 7 13:23:58 2005

: This isn't a bad idea.  Maybe the best thing to do would put up a Wiki page
where PM developers/deployers can request hardware, and then link to this page
in the donations page.  If anyone needs hardware, please start such a page, and
I'll link to it on donate.html. --[[file:akrowne.org][akrowne]] Tue Feb 15 18:02:09 UTC 2005

:: Good idea, maybe I should create a general [[file:Classifieds.org][Classifieds]] section. --[[file:jcorneli.org][jcorneli]] (done)

----

* Comments

Dear /80.58.35.236.proxycache.rima-tde.net/, thanks for your comment

: I think social networking programs could be modified for this type of purposes. This could be highly benefial for reordering economy beyond planetmath social network, simple social network based logistics program should do it.

Please log in and sign your contributions to the wiki so we know who we're
talking to (for instructions and other details, please see the wiki [[file:Policy.org][Policy]]).
Once it you've signed the comment feel free to re-introduce it in the page
above.  I don't mean to be annoying, but I think the policy is worth enforcing,
and maybe moving your comment down here will help motivate you... As for the
comment itself, lots of metropolitan areas have webpages that help you share or
trade things locally (thereby saving shipping costs). --[[file:jcorneli.org][jcorneli]]
