#+STARTUP: showeverything logdone
#+options: num:nil

*  FYI: You need to obtain a password to edit

Due to spam, this wiki is password protected.  Email holtzermann17@gmail.com with subject line "Edit !AsteroidMeta" to get the password.

*  What is it?

This is a wiki for discussing commons based peer-production of free content.  One of the purposes of this site is to help coordinate work on [[file:Noösphere.org][Noösphere]] and the Planet-named sites that use it. But it isn't a Planet itself; it is more of a proto-planet. Hence -- AsteroidMeta. AM is also, fittingly, the wiki home of the [[file:metamath.org][metamath]] family of projects. You'll find discussion about these projects and other even more meta things here. Enjoy!

*  Sections

 * [[file:Projects.org][Projects]] A list of projects using or being discussed on this wiki.
 * [[file:Project Home Pages.org][Project Home Pages]] Some projects have their homepages on the wiki; here's quick access to those.
 * [[file:Tasks.org][Tasks]] The projects require work, and we need volunteers.
 * [[file:Bugs.org][Bugs]] If you find a problem with one of the projects, you can report it here.
 * [[file:Feature Requests.org][Feature Requests]] If you'd like to see something new in one of our projects, please let us know.
 * [[file:Discussions.org][Discussions]] Threads that aren't associated with any particular project, but that still tie in to our theme.
 * [[file:Collaborations.org][Collaborations]] Cross-project collaborative work, jointly-written papers, etc.
 * [[file:Links and bibliographies.org][Links and bibliographies]] An index of various link and bibliography pages on this site.
 * [[file:Users.org][Users]] Our roster/guestbook. We appreciate it if you sign your edits in accordance with our Policy (see below).
 * [[file:Policy.org][Policy]] Specific policy items relevant to this Wiki.
 * [[file:Funding Opportunities.org][Funding Opportunities]] Every so often we have jobs, internships, or other kinds of money to offer (and we're interested in learning about these opportunities too!)
 * [[file:Classifieds.org][Classifieds]] Miscellaneous stuff wanted or offered by AM users.
 * [[file:Schedule.org][Schedule]] Events on or around the asteroid you should know about.
 * [[file:Calendar.org][Calendar]] A tool for monitoring the passage of time.
 * [[file:Bulletins.org][Bulletins]] Weekly summaries of AM activities.
 * [[file:Commons.org][Commons]] Miscellaneous stuff can go here.
 * [[file:Feedback.org][Feedback]] Tell us how you feel about AM, we want to know!

* License

Copyright (c) 2005-2011, !AsteroidMeta Users 

The content of this wiki is available under your choice of the [[file:GNU Free Documentation License.org][GNU Free Documentation License]] (FDL) and the [[file:GNU General Public License.org][GNU General Public License]] (GPL). If the FDL is selected, be advised that this document has no Invariant Sections, no Front-Cover Texts, and and no Back-Cover Texts. /By contributing to this wiki, you agree to make your contributions available under these licensing terms./



* About AsteroidMeta

For help with markup, see [http://www.oddmuse.org/cgi-bin/wiki/Text_Formatting_Rules Oddmuse:Text_Formatting_Rules] and [http://www.oddmuse.org/cgi-bin/wiki/Usemod_Markup_Extension Oddmuse:Usemod_Markup_Extension], and [[file:latex-test.org][latex-test]] for LaTeX. !AsteroidMeta was founded on January 30th, 2005.  

* Disclaimers

[[file:A note from some members of PlanetMath who dislike this media.org][A note from some members of PlanetMath who dislike this media]].

For those who do like the medium, there are more wiki postings at
the separate [http://metameso.org/cgi-bin/wiki.pl/HomePage Meteorite] wiki.
