#+STARTUP: showeverything logdone
#+options: num:nil

* Proposed Budget= 

1/3 of total PM profit from FEM sales.

* Proposed Distribution

From the proposed budget, 50% divided among the principal editors, 
and the other 50% divided among associate editors.

Payment to principal editors continues as long as the principal editor in
question continues in that role.

Payment to associate editors is pending review by the principal editors and/or
the PM board.  In order to qualify for an honorarium, an associate editor must
have made a sufficient impact on the project that month (i.e., they should be
"active" in their role).

Checks are to be issued monthly.

* What this boils down to

If the estimate of ten dollars per copy from the [[file:FEM sales.org][FEM sales]] page is correct,
under this proposal, principal editors would earn about $.50USD per copy sold
and associate editors about $.05-$.10USD per copy sold.  This may seem pretty
measly but it adds up to $50 and $5-$10 per month, if we manage to sell 100
copies per month.  Personally, I'd like more, but that would require increasing
the percentage of the profit that goes to FEM honoraria.  Which might be fine -
but it depends on what else the money might be needed for.  See the [[file:Budget.org][Budget]].

* Declining honoraria

Maybe editors should be able to decline honorarium, so that the money can be
added back to the pool, and re-divvied up amongst those who need it more.  This
could actually also be considered a tax write-off, in which case they wind up
getting a hefty fraction of the honorarium at no cost to us. --[[file:akrowne.org][akrowne]] Sat
Apr 9 02:10:10 UTC 2005

Sure, but I think in all fairness the money should not be used for honoraria
then, but rather go back into the PM general coffers.  (This could be debated
further.)  

To me, it seems that "someone who needs it more" might end up being a programmer
or author, not an editor.  But note that we could also offer special editorial
assignments on commission (just like we might do with writing or programming
assignments), so people in need of more cash who have the right skills could
qualify for more money that way (as long as there was more money available to
pay out).

But we have a long way to go before anyone is going to be making enough money to
live on off of this.  (Now, if we could get matching funds for the honoraria
from someone, then we might be getting someplace.)

By the way, note that the estimate for honoraria is similar to the estimate we
might have for paying programmers and authors.  If we decided not to pay
authors, then /two/ programmers could make up to $500 a month each off of this
money-flow.  That might be almost enough to live on.  Division into smaller
chunks (more programmers) increases the need for outside income sources.
--[[file:jcorneli.org][jcorneli]] Sat Apr 09 02:39:20 2005 UTC

----
[[file:Budget.org][Budget]]
