#+STARTUP: showeverything logdone
#+options: num:nil

Coming up with proofs "from scratch" is hard.  Luckily we never have
to do that.

Huh?

I mean, we've got a lot of experience to go on.  Powerful minds and prior knowledge.
Some of us even have instincts, or at least heuristics.  So how does it all
work?

Well, just like the Deep Blue team had to learn something about how to 
play chess but managed to avoid having to become world class, we should
learn something about how to prove things.  And, like I said, we all
already know something about that.  Becoming self-aware of our own proof
strategies (and meta-strategies) may be somewhat hard.  But we can try.
We can also look at other things that people have written down about
this stuff.  One thing that caught my eye recently was Popper's /Logic of Scientific Discovery/.
But there are some famous books by famous mathematicians about the 
topic of how to prove things, too.  I think Buchberger talks about this
when he teaches.  Thurston wrote a paper that has at least the title
in common with this inquiry.  This seems like the sort of question
mathematicians should be asking, you know what I mean!?
