#+STARTUP: showeverything logdone
#+options: num:nil

* Hyderabad 2010

Date: August 19, 2010

See http://www.icm2010.org.in/geninfo.php -- preregistration and
paper submission is already open!  This conference is once every
four years... we should try to go this time.

* Madrid 2006

Dates: 22-30 August 2006

Home page: http://www.icm2006.org/

I think given our global scope and the fact that these congresses
happen only somewhat infrequently, we should really try to send
a small group to this one.  We should at least investigate to find out more about what
the congress is about and whether we could do productive networking there.  Alvaro would be a good person to have
as part of this group, since he's both a mathematician and knows
his way around Madrid.  Robert Milson would be another good candidate, bringing some more internationality into it.  

Now that I've nominated you guys, would either of you be interested
in doing the pre-investigations? :)  Anyone else interested?

: Of course, I would love to go, but I am still trying to figure out my summer. Tons of interesting things happening. Moreover, classes start at Cornell at the end of August, which conflicts with the congress. A suggestion: there will be a poster session. We could make a poster out of PlanetMath. --[[file:alozano.org][alozano]]

Note: the deadline for cheapest registration is the /15th of May/.
Figuring out exactly what we would want to be /doing/ at the conference
should be done by then! (http://www.icm2006.org/registration/fees/ for details.) --[[file:jcorneli.org][jcorneli]]
