#+STARTUP: showeverything logdone
#+options: num:nil

* Things I'm currently working on

Lately I want to work on [[file:Arxana.org][Arxana]], but also on an "annotated
bibliography" supporting my work.  Ideally the two projects would be
combined to make a nice semantically-linked-together bibliography.  In
the mean time, my goal is just to work on both of them every day til
I'm satisfied.

Today, in addition to noting that there are a lot of bibliography
items listen in the [[file:HDM-related things to check out|HDM Related.org][HDM-related things to check out|HDM Related]] pages, I'll mention 
some additional items here.

Before I get into that, I'll first mention that one
department chair who I knew told me never to trust
books, because they are never really up to date.
I suppose that may be true, but one could contrast
that with Donald Knuth's statement about wanting to
get to the bottom of things.  Books may be helpful
for that.


** Things People Have Recommended to Me

 * Maps of the imagination (a book about fiction)
 * House of leaves, Mark Z. Danielewski
 * Gravity's rainbow illustrated by Zak Smith
 * ...

** Things I've selected as being worth checking out

 * The revolution of everyday life
 * ...

** Things on my current reading list

 * The Mind's I, by Douglas Hofstadter
 * Women, Fire, and Dangerous Things, by George Lakoff
 * Middlemarch
 * The life and opinions of Tristam Shandy
 * The artist and the mathematician
 * Virginia Woolf
 * ...

** Things I've read that seemed worth reading

 * If on a winter's night a traveller
 * Literary Machines
 * Thus Spoke Zarathustra
 * The Illiad
 * The Orestea
 * Franz Kafka
 * William Burroughs
 * Kathy Acker
 * ...

** As above, but with pictures

 * Watchmen
 * Berlin
 * Ariel Schrag
 * Epileptic
 * Scott McCloud
 * ...

** Things I've elevated to the level of "personal classics"

 * Dirk Gently's Holistic Detective Agency
 * From Ritual to Romance
 * The Society of Mind
 * Riddley Walker
 * ...

* Placeography?

Another task that I want to work on, which could merge with the
bibliography project if we expand it to include some other classes of
useful media resources... finding a new job or some other position.

I recently submitted [http://planetx.cc.vt.edu/~jcorneli/papers/ias-proposal/proposal-3.pdf an application for a fellowship]
and that does a reasonable job describing the sort of thing I'd
like to be doing.  So, with that as a prototype, the next big bibliogaphy-like
question is: what are possible places to do this sort of thing?

--[[file:jcorneli.org][jcorneli]]

Given that you -- apparently -- require funding to perform your
work, I suggest approaching this from an Out Of Context perspective.
Different modes of thought manifest in the actions of doers of the
four Ways: the Way of the farmer, the Way of the merchant, the Way
of the gentleman warrior, and the Way of the artisan. 
[http://www.samurai.com/5rings/ A Book Of Five Rings]. 

Therefore, go out into the field and spend time working in each of these Ways. When you return, gold coins and data in hand, you will have the
resources to write a book and create software embodying the vision
of your book. And /then/ the money will flow in from people and
groups who wish to gain from your mastery. One place to begin would be building Earthships in Taos... --[[file:ocat.org][ocat]]

The details are: I need income primarily to survive,
and I have that; and I can work on both writing and
coding at present.  What I don't have is a particularly
supportive environment from the point of view of
non-monetary, non-survival-oriented, life-enhancing resources. It
is true that money can be exchanged for those sorts
of resources (for example, if I had a car, I could
drive to XYZ location to talk to someone who I was
interested in talking to), but the primary purpose
I had in mind with that fellowship was to get
plugged in directly to such resources.  It is true
that they pay, but lots of jobs that pay don't
give much access to relevant resources apart
from money.  Most end up taking a lot of time, too!
So, I'm strongly in favor of salutory worldly experience...
but I wanted to clarify, I don't view a new job or additional
funding or even new interesting experiences as
additional ingredients I need to continue to do good work.
After I completely exhaust the resources here, then
I will absolutely need to move on/up/out.  But I don't want
to massively interupt the patterns I have engaged here
right now!
Your example seems like a great idea for something to
look forward to as a "buffer" into which I could leap
if I don't locate and obtain a job like the fellowship that seems
like a smooth transition from what I am currently
up to.

--[[file:jcorneli.org][jcorneli]]
