#+STARTUP: showeverything logdone
#+options: num:nil

 RESUME FOR JOSEPH ANGUS CORNELI  (Jan 18 2006)
 
   Email: jcorneli@planetmath.org  Tel. (612) 333-1251
   Post: 421 Cedar Ave. #17, Minneapolis MN 55454
 
 EDUCATION
 
 University of Texas at Austin, 2002-2004
 - Mathematics graduate student
 
 New College of Florida, 1998-2002 
 - B.A., with area of concentration in Mathematics
 
 University of Minnesota, 1996-1998
 - full time during last two years of high school
 
 CS background: Artificial Intelligence, Programming Languages,
 Knowledge Representation and Reasoning, Algorithms.
 
 Mathematics background: Differential geometry, Topology, Real
 and Differential Analysis, Bayesian Statistics, Graph Theory.
 
 OPEN PROJECTS
 
 * 2003-ongoing Hyperreal Dictionary of Mathematics, lead developer
   - building a mathematical artificial intelligence
 
 * 2003-ongoing PlanetMath.org, volunteer
   - strategic planning, technical editing
 
 PREVIOUS RESEARCH
 
 * 2001 NSF REU, Geometry group, Williams College
   - studied constrained optimization problems in nonstandard geometries
 
 * 2000 NSF REU, Inverse Problems for Electrical Networks, UW-Seattle
   - studied inverse scattering on graphs
 
 INDUSTRY EXPERIENCE
 
 * 2004 Associate Member of the Technical Staff, Cycorp, Inc.
   - developed programmatic methods for cleaning a large AI knowledge base
 
 SKILLS
 
 Languages: Emacs Lisp, other Lisps, scripting (e.g. Bash), C/C++/Java,
 LaTeX, HTML
 
 Other: Teaching and tutoring college mathematics, large-scale online
 collaborations, cultural anthropology
 
 PUBLICATIONS
 
 4.  A scholia-based document model for commons-based peer production
 (with Aaron Krowne) (Proc. Emory Symposium on Free Culture and the
 Digital Library 2005).
 
 3. The double bubble problem on the flat two-torus (with P. Holt,
 G. Lee, N.  Leger, E. Shoenfeld, and B. Steinhurst)
 (Trans. Amer. Math. Soc., 356 (2004) 3769-3820).
 
 2. Double bubbles in the three-torus (with M. Carrion, G. Walsh, and
 S. Beheshti) (Experimental Mathematics 12 (2003)).
 
 1. "Double Bubbles in Spaces of Constant Curvature", 
 (Undergraduate Thesis, New College of Florida (2002))
