#+STARTUP: showeverything logdone
#+options: num:nil


I noticed that under the entry !LehmersConjecture, there is a note pointing out
that this entry was copied verbatim from somebody's home page.  We might need to
look more closely into this matter so we don't get in trouble printing the
entry.  As mentioned elsewhere, this business of possible plagarism and
infringement needs to be dealt with somehow.--[[file:rspuzio.org][rspuzio]] 26 February 2005

: The entry should probably be removed from the encyclopedia immediately: it is
only OK to copy FDL, public domain, or otherwise FDL-compatible material, and in
the case of copying from FDL works, a certain protocol must be followed.  The
copying/legal stuff is described in the site docs.  I think that the author
should be referred to these docs and asked to remove the entry. --[[file:jcorneli.org][jcorneli]]
Sat Feb 26 15:33:13 2005 UTC

:: I posted about this and the only comments I received were that the entry doesn't seem to be verbatim anymore. --[[file:drini.org][drini]]

Pictures and other attachments must have no copyright problems. (Maybe Wikipedia
has sensible guidelines for pictures?)
