#+STARTUP: showeverything logdone
#+options: num:nil

* Preface

I may be disqualified from including this letter in a grant application, because
of being "too close" to the project, but I figure I might as well write it
anyway, to say what I like about PM, and why it seems worthwhile to be involved.
Perhaps my statements will be useful to others in some way, or perhaps they
could go into grant applications... or who knows, they may be useless or
worse... but without further ado:

* What I like about PM

I think that PM is a model resource for education and research.  It makes math
content available to anyone, anywhere; it promotes freedom with this content so
that anyone can do anything they like with that content; it provides a "live"
internet-based community that anyone with an internet connection can participate
in.  PM has no fixed "agenda" or "curriculum" -- users who wish to use PM as
part of their education are free to pick and choose the content and activities
that they find most pertinent.  Users who wish to contribute a curiculum or
other "themed content" may find uptake to be limited -- but by contributing
content to PM, they certainly have a chance for their work to reach a broad
audience.  Publishing on PM is not the same as publishing on a web page --
because the PM users care about making their "commons" nice and useful, one must
be prepared to have ones work critiqued.  By contrast, fewer people are likely
to care what you publish on your own web page -- if they strongly like or
dislike it, they /might/ send you a letter, but unless people feel very
strongly about the issues you talk about, two-way communication is much less
likely.  The "mainstream" mathematics community works in a fashion somewhat more
like PM, but it has significantly greater barriers to participation - academic
credentials and the ability to do original research being two of the primary
ones.  PM provides a way for anyone (whether or not they have crossed these
barriers or have the potential to do so) to be involved in the creation of a
useful mathematical resource.  As I stated above, users can participate at any
level they wish - a research mathematician has a "home" on PM just as much as a
grade school student.  The diverse PM community is united by an interest in
mathematics.

* Why it seems worthwhile to be involved

There are several reasons that I choose to be involved in the PM project.  The
first is as a way to learn more mathematics.  A fairly phenomenal amount of
material contributed to the PM encyclopedia, the contents of which focus
especially on things that one will need to understand /more/ mathematics.

Another reason is the free nature of the site.  I can read the text from PM the
way I want; not only that, I can alter it however I wish; do research on the
content without having anything left out; send corrections back to the original
authors when I find mistakes or things I don't like; and turn part or all of it
into a book to sell and hope to make some money for my efforts (and indeed, I am
doing all of these things).

I personally think that the free, community-driven, commons-based nature of PM
gives it the potential to become an increasingly useful and increasingly used
part of mathematics education and research, at all levels, around the world.  In
this belief, one of the goals of my involvement is to improve technical aspects
of the site in order to make PM more useful to students, educators, and
researchers.  I would personally like to have access to more and more Free Math,
but it isn't just personal: PM creates opportunities for learning, research, and
economic gain for just about anyone who wants to use it.

Finally, the interests held by a significant fraction of people involved with
the leadership of PM intersect with my own research interests (in the area of
mathematics AI), and I have had many, many provocative and enriching
conversations with these folks on topics of mutual interest.  I've found friends
and great collaborators through the site; the personal and professional rewards
have been huge.  I think anyone who wants to participate in PM will find similar
opportunities -- and perhaps share my view that the more you put in, the more
you get back.

**  Conclusion

PM is a healthy and diverse mathematical community that meets primarily on the
internet.  There are many ways for it to grow and become more useful, but it is
already vibrant.  Supporting PM's various efforts to better serve more people
makes sense personally and economically.  PM provides opportunities that the
competition simply won't or can't offer.  Furthermore, for quite a range of
products and services, the "bang for your buck" to be gotten through support for
PM is quite a bit better than anything other purveyors of mathematics content or
collaboration software can offer.  PM is recognized as /the/ home for Free
Math on the internet, and there are quite a few people out there, who, like me,
are highly motivated to make ongoing improvements.

I urge you to support PM directly, and to talk with PM's director or other
participants in the PM leadership about ways PM can better serve your needs and
the needs of your organization.

--[[file:jcorneli.org][jcorneli]] Fri May 06 22:43:23 2005 UTC

* Comments

are welcome. --[[file:jcorneli.org][jcorneli]] Fri May 06 22:43:37 2005 UTC
