#+STARTUP: showeverything logdone
#+options: num:nil

 *Theorem*:  The subring generated by any element of a cyclic ring of finite characteristic is cyclic.

 *Proof*:  Denote the ring $R$ and the element $\phi$.  If $\phi = 0$, the result is trivial;
henceforth we assume $\phi \neq 0$.  Since $R$ is locally cyclic, there must exist an element $\psi$ 
of $R$ and integers $m',n'$ such that $\phi = m' \psi$ and $\psi^2 = n' \psi$.  Set 
$m = m' / \operatorname{gcd} (m',n')$ and $n = n' / \operatorname{gcd} (m',n')$.  Then $n$ and $m$
are relatively prime and $m' n = m n'$, so $m \phi^2 = n \phi$.

Since $R$ has characteristic zero, there exists an integer $k$ such that $k \phi = 0$.  We may
assume that $k > 0$ and that, if $0 \le j \le k$, then $j \phi \neq 0$.  Set
$h = \operatorname{gcd} (m,k)$.  Then $(nk/h) \phi = (mk/h) \phi^2 = (m/h) \phi \cdot (k \phi) = 0$.  
This implies that $k$ divides $nk/h$, which is only possible if $n/h$ is an integer, i.e. 
$h$ divides $n$.  However, $m$ and $n$ are relatively prime and $h$ divides $m$, so this only 
way this could happen is if $h = \pm 1$, which means that $m$ and $k$ are relatively prime. 

By Euclid VII 1, there exist integers $p,q$ such that $mp + kq = 1$.  Since $k \phi = 0$, 
also $kq \phi^2 = 0$, hence $mp \phi^2 = \phi^2$, so $\phi^2 = mp \phi^2 = np \phi$.
Thus, we see that the subring generated by $\phi$ is a cyclic ring of order $k$ with
behavior $np$.
 *Q.E.D.*

 *Theorem*:  A subring generated by a finite subset of a locally cyclic ring of finite 
characteristic is cyclic.

Denote the ring $R$ and the subset $S$.  The additive group generated by $S$ is cyclic, hence
is generated by a generator $\phi$, which is a linear combination of elements of $S$.  By the
foregoing theorem, the ring generated by $\phi$ is cyclic.  However, since the elements of
$S$ are all multiples of $\phi$, and $\phi$ is a linear combination of elements of $S$, the
ring generated by $\phi$ is the same as the ring generated by $S$.
 *Q.E.D.*

 *Theorem*:  A ring $R$ is locally cyclic with finite characteristic if and only if there exists
a chain of finite cyclic groups of which it is the union:
$$R_0 \subseteq R_1 \subseteq R_2 \subseteq R_3 \subseteq \cdots \subseteq R$$
$$R = \bigcup_{n=0}^{\infty} R_n$$

 *Proof*:  Suppose that $R$ is a locally cyclic ring.  Since locally cyclic groups have countable order, 
the elements of $R$ may be enumerated.  Let $R_n$ be the subring of $R$ generated by the first $n$ elements
in the enumeration.  By the foregoing theorem, $R_n$ is a finite cyclic group for each $n$.  By construction,
$R_n \subseteq R_{n+1}$ and $R = \bigcup_{n=0}^{\infty} R_n$.

Suppose that we have a chain of finite cyclic groups,
$$R_0 \subseteq R_1 \subseteq R_2 \subseteq R_3 \subseteq \cdots \subseteq ,$$
and set $R = \bigcup_{n=0}^{\infty} R_n$.  Then $R$ is locally cyclic because, given $\alpha, \beta \in R$,
there exists $n$ such that $\alpha, \beta \in R_n$ so $\alpha$ and $\beta$ will be multiples of the 
generator of $h_n$.
 *Q.E.D.*

 *Theorem*:  If $R$ is an infinite locally cyclic ring of characteristic zero , then 
$R = \bigcup_{n=0}^{\infty} R_n$ where, for each $n$, the ring $R_n$ is cyclic and $[R_{n+1} : R_n]$ 
is prime.

 *Proof*: By the last theorem, we know that the $R = \bigcup_{n=0}^{\infty} T_n$ for some
chain of cyclic rings $\{T_n\}_{n=0}^\infty$ such that $T_n \subseteq T_{n+1}$.  By throwing
away redundancies, we may obtain a subchain $\{S_n\}_{n=0}^\infty$ such that $S_n \subset S_{n+1}$.

Suppose that $A$ and $B$ are cyclic rings and that $A$ is a proper subring of $B$.  Then $|A|$
divides $|B|$.  Suppose that $|B|/|A|$ is composite and let $n$ be a proper multiple of $A$ 
which is a proper divisor of $B$.  By theorem 12 of Warren's thesis, there exists a subring $C$ 
of $B$ whose order is $n$ and, in turn, there exists a subring $A'$ of $C$ whose order equals the
order of $A$.  As a subring of the subring $C$ of $B$, it follows that $A'$ is also a subring
of $B$.  However, by the aforementioned theorem, subgroups are uniquely determined by their
order, so $A' = A$.  Hence, we have $A \subset C \subset B$.

Repeating this construction as often as neded, we can find rings $C_1, \ldots, C_k$ such that
$A \subset C_1 \subset \cdots C_k \subset B$ with the ratio of orders of successive rings being
prime.  Applying this procedure to $\{T_n\}_{n=0}^\infty$, we may make a chain $\{R_n\}_{n=0}^\infty$
such that $R_n \subset R_{n+1}$ and $[R_{n+1} : R_n]$.
 *Q.E.F.*

 *Theorem*:  Let $\{R_k\}_{k=0}^\infty$ be a chain of finite cyclic rings and let 
$R = \bigcup_{k=0}^{\infty} R_k$.  There exists an element $\phi$ of $R$ with order $n$
if and only if $n$ divides $|R_k|$ for some $k$.

 *Proof*:   Suppose that there is an element $\phi$ of $R$ with order $n$.  Then
$\phi$ belongs to $R_k$ for some $k$, and hence $|\phi|$ divides $|R_k|$.  Suppose that
$n$ is a divisor of $|R_k|$ for some $k$.  Since $R_k$ is cyclic, it has a generator
$\psi$, whose order equals the order of $R_k$.  Set $\phi = (|R_k|/n) \psi$.  Then we
have $|\phi| = n$.
 *Q.E.D.*

 *Theorem*:  Let $p$ be a prime number.  Then if $R$ is a locally cyclic ring such that
$|\phi|$ is a power of $p$ for every $\phi \in R$, it follows that $R$ is a zero ring.

 *Proof*:  By the foregoing theorems, we should have $R = \cap_{k=0}^\infty R_k$ where
$R_k \subset R_{k+1}$ and $[R_{k+1} : R_k] = p $.  Assume that $R$ is not a zero ring.
Then there must exist $\phi, \psi \in R$ such that $\phi \psi \neq 0$.  There must exist
some $n$ such that $\phi, \psi \in R_n$.  Then $R_n$ is not a zero ring.  Moreover, if
$k > n$, it cannot be the case that $R_k$ is a zero ring either because then we would
have a non-zero ring as a subring of a zero ring.

Now consider behaviors.  Let $b_k$ denote the behavor of the ring $R_k$.  When $k \ge n$,
we must have $0 < b_k < |R_k|$ because the ring is not a zero ring.  Furthermore, since
$b_k$ is a factor of $|R_k|$, it must be a power of $p$.  By the formula for behavior of
subrings, we have $b_k = \operatorname{gcd} (p b_{k+1}, |R_k|)$.  Since both $b_{k+1}$ 
and $|R_k|$ are powers of $p$ and the greatest common divisor of two powers of the same
number is their maximum, $b_k$ must be the greater of $p b_{k+1}$ and $|R_k|$.  When
$k \ge n$, it cannot equal the latter, so we have $b_k = p b_{k+1}$ when $k > n$.
Since we also have $b_k > 0$, this means that $b_k > b_{k+1}$ when $k \ge n$.  This,
however, would mean an infinite descending sequence of positive integers, which is not
possible, so we conclude that $R$ must be a zero ring.
 *Q.E.D.*

 *Theorem*: Let all of the following be true:

 * $n$ is a positive integer;
 * $p_1, \dots, p_{n+1}$ are distinct primes;
 * $\displaystyle P=\prod_{j=1}^n p_j$;
 * $Q=p_{n+1}P$;
 * $K$ is a positive divisor of $P$

Then there exists a $c \in \mathbb{Z}$ such that 
$\varphi \colon K\mathbb{Z}_{KP} \to K\mathbb{Z}_{KQ}$ defined by $\varphi(m)=p_{n+1}cm$ is a ring 
homomorphism (if $K=1$, it is not insisted upon that $\varphi(1)=1$) and $\varphi$ yields a ring 
isomorphism between $K\mathbb{Z}_{KP}$ and $p_{n+1}K\mathbb{Z}_{kQ}$.

 *Proof*:
It is clear that $\varphi\left(K\mathbb{Z}_{KP}\right)=p_{n+1}K\mathbb{Z}_{kQ}$ and that $\varphi$ preserves the additive structures of these two rings. Since $K$ is a divisor of $P$, the ring $K\mathbb{Z}_{KP}$ has order $P$ and behavior $K$. Since $$\frac{KQ}{p_{n+1}K}=P,$$ we also have that $p_{n+1}K\mathbb{Z}_{KQ}$ has order $P$. To determine the ring's behavior, let us consider what happens when we square $p_{n+1}K$, which is a generator of the ring. Note that $p_{n+1}$ is relatively prime to $P$. Since $(p_{n+1}K)^2=(p_{n+1}K)(p_{n+1}K)$, we have a generator $r$ of the ring such that $r^2=(p_{n+1}K)r$. Within the theorem that proves existence of behavior for cyclic rings, it is proven that this fact implies that the behavior of the ring is $\gcd(p_{n+1}K,P)=K$, and the $c \in \mathbb{Z}$ as described in the statement of the theorem is constructed. Hence, $\varphi$ yields a ring isomorphism between $K\mathbb{Z}_{KP}$ and $p_{n+1}K\mathbb{Z}_{kQ}$. This completes the proof.
 *Q.E.D.*

Back to [[file:Locally Cyclic Rings.org][Locally Cyclic Rings]]
