#+STARTUP: showeverything logdone
#+options: num:nil


For Wikipedia's take on logical positivism, read this: http://en.wikipedia.org/wiki/Logical_positivism

It is an interesting question to think about: how should society decide which
research projects to fund?  Those that can prove that they will have good
results might not even qualify as "basic science"!

One neat thing about math is that sometimes when you are working on a theorem,
it doesn't matter if it turns out that the theorem is false, because then you've
come up with a counterexample - which may be as good as the theorem.  One gets
the feeling that enough "good work" on the problem will lead to good results of
some kind.

Funding agencies want to know that you have a good problem and they want to know
that you're qualified to do "good work" on the problem.  

Since I'm sure we are all somewhat confident that we know how to do good work
(maybe overly confident), let's ask: What defines a good problem?

--[[file:jcorneli.org][jcorneli]] Sat Jun 25 01:24:17 2005 UTC
