#+STARTUP: showeverything logdone
#+options: num:nil

I wonder if we could have a Metamath Logo a bit less -- let's say -- californian. Something
in a circle for instance (looks academic) with colors a bit more elaborate than red, yellow 
and black.  At least if Norm agrees. -- [[file:fl.org][fl]] 3-Jun-2008

I don't have time to design a new logo, and may not be good at it
anyway, but I will look at proposals.  I mentioned it in a discussion
of the Ghilbert logo with Raph.  Here is an excerpt from his
17 Feb 2004 email:

  > Someday I should revisit the Metamath's aleph - it was done in the early
  > 90s on a Mac with 16 colors.  I thought it amusing that someone actually
  > stole it for their own logo:  http://www.netcrucible.com/blog/

  Hey, I remember noticing that! It does have an early-90's feel to it,
  but it is distinctive. I'm starting to fantasize about the visual feel
  for the Ghilbert site; the Aqua UI on Mac OS X is inspiring. I'm also
  thinking of a visual theme of containers, not unlike the representation
  of finite sets in Appendix 2 of http://www.uwec.edu/andersrn/sets.htm

  (while on that URL, check out Ch. 11 if you haven't already, which
  covers the surreals)

-- [[file:norm.org][norm]] 4 Jun 2008

I don't know if you have already had a look to the font Raph had designed 
and called "inconsolata". It was really beautiful. -- [[file:fl.org][fl]] 3-Jun-2008
