#+STARTUP: showeverything logdone
#+options: num:nil


By [[file:akrowne.org][akrowne]].

Being anarchistic doesn't obviate having goals.  I think the PlanetMath
community should embrace its (thus far) anarchistic nature.  Through the
anarchistic lens, I think we can say at least two things about goals: (1) there
are no /official/ (as in, top-down) goals.  There can still be /grassroots/
(bottom-up) or /folk/ goals; (2) there can be many sets of orthogonal goals,
so long as none of them dilute or undermine the universal protocols,
conventions, and norms of the core project.

Universally speaking, I think the broad mission statement for PlanetMath that I
arbitrarily (but, hopefully, correctly) selected from the outset and put up on
the home page has served as a functional guiding maxim.  Generally, everyone in
the community agrees on the goal of making mathematical knowledge more
accessible, and doing it in a collaborative way.  I'm not sure what more the
community needs to universally agree on.

There is also the /official/ PlanetMath.org, Ltd. organization, which has
(nay, *must* have) stated goals.  But all of these goals flow from the same
mission statement, so there is no real conflict here.

However, I would suggest that we should continue to uphold a distinction between
the nonprofit org and the community.  As the nonprofit org does not orchestrate
the activities of the community, the community may remain anarchistic (and in
many ways, democratic).  The org itself must be structured like a firm, which is
/not/ how CBPP is structured.  Therefore, we should keep the two entities
separate, so that one does not pollute the organization of the other.

Of course, there is an obvious symbiosis between the two.  I think the org's
main purposes should be to raise money (and other resources) for the community,
and interact with other official organizations toward this end.  It can act as a
broker to find "buyers" for any worthwhile activities that emerge as ideas from
the community.

Let me use the FEM project as an example.  I am starting to see this project as
a sub-project of PlanetMath, separate but completely emergent from the
community.  I think the effort should see itself this way as well.  The FEM
project is best qualified to organize itself, not be organized by the nonprofit.
I surely am not qualified to organize it, and it is a process of exploration
anyway.  Thus, the FEM is not identical with the nonprofit.  But on the other
hand, the FEM project needs to recognize that it is not identical with the
PlanetMath project either.  Were FEM to confuse itself with PlanetMath, it would
risk imposing its slightly different values and goals on the underlying project.

In specific, inasmuch as the FEM is a quality filter over PlanetMath content, it
should keep this filter appropriately /superimposed/ over PlanetMath.  Of
course, inasmuch as the FEM's quality goals /overlap/ with PlanetMath's, the
FEM can enhance PlanetMath proper, through a feedback process.

Basically, I think PlanetMath's goals are appropriately vague.  The FEM has the
same /type/ of goals, but they are more /specific/ -- in a way that produces
real differences in organization.  So as the FEM project chugs along, the FEM
participants (including me) should stop and think about whether any proposed
changes to PlanetMath, invented because they would "make building the FEM so
much easier," do not also conflict with or inappropriately narrow PlanetMath's
/general/ goals.

I don't think there's anything particular to the relationship between the FEM
and PM that engenders these principles, so they should serve as a good template
for other current and future efforts.

In fact, I think this dynamic between the PlanetMath community and the nonprofit
is a good model for how many nonprofits should start working.  The way things
are now, there is a big political game played in order to get grants.  The
nature of this game alienates user communities, fosters an "if you build it,
they will come" attitude, and produces top-down organization for what should
often be grassroots efforts.  I've heard higher-ups at organizations like NSF
complain about this, but they don't seem to know what to do about it.  The
result is a tremendous inefficiency in how money is spent for the general
welfare, unstimulating and unsuccessful ventures, and typically a lack of means
to evaluate these ventures.

So, let CBPP projects be anarchistic or democratic, as best suits their
individual nature.  And let their nonprofit organizations act as distinct
/broker/ entities to channel benefits and sustenance between the CBPP
community, third parties, and additional user communities.


----
[[file:PlanetMath Goals.org][PlanetMath Goals]]
