#+STARTUP: showeverything logdone
#+options: num:nil

/Of 37 items which the Library of Congress showed under the subject "mathematics" which were published in 1923, the following were published in the U.S.:  Unfortunately, not all math books show up this way since, for instance, Love's book is classified under "Geometry", but not under "Mathematics".  However, this is a start.  Also, note that Dickson's History of number theory seems not to have its copyright renewed, and therefore might be in the public domain./

Author:        Alderton, Nina May, 1890- [from old catalog]
Title:         Involutory quartic transformations in space of
                  four dimensions,
Published:     [Berkeley, 1923]
Description:   p. [345]-358. 28 cm.
LC Call No.:   QA691.A4
Subjects:      Trasformations (Mathematics) [from old catalog]
               Hyperspace. [from old catalog]
Control No.:   8261382

Author:        Bender, Harry Albert, 1895- [from old catalog]
Title:         Sylow subgroups in the group of isomorphisms of
                  prime power Albelian groups, by Harry Albert Bender ...
Published:     [Baltimore, 1923]
Description:   1 p.l., p. 223-250, 1 l. 26 cm.
LC Call No.:   QA171.B38
Subjects:      Group theory.
               Isomorphisms (Mathematics)
               Sylow subgroups.
Control No.:   5920230

Author:        Dickson, Leonard E. (Leonard Eugene), 1874-
Title:         History of the theory of numbers ... by Leonard
                  Eugene Dickson ...
Published:     Washington, Carnegie Institution of Washington,
                  1919-1923.
Description:   3 v. 27 cm.
Series:        Carnegie Institution of Washington publication
                  no. 256, vol. I-III
LC Call No.:   QA241.D49
Notes:         I. Divisibility and primality.--II. Diophantine
                  analysis.--III. Quadratic and higher forms.
Subjects:      Number theory.
               Mathematics -- History.
Control No.:   7313243

Author:        Eisenhart, Luther Pfahler, b. 1876.
Title:         Transformations of surfaces, by Luther Pfahler
                  Eisenhart ...
Published:     Princeton, Princeton university press; [etc.,
                  etc.] 1923.
Description:   ix, 379, [1] p. diagrs. 23 cm.
LC Call No.:   QA601.E4
Notes:         "Published with the cooperation of the National
                  research council."
Subjects:      Transformations (Mathematics)
               Surfaces.
Other authors: National Research Council (U.S.)
Control No.:   12762349

Author:        Glover, James Waterman, 1868-1941, ed.
Title:         Tables of applied mathematics in finance,
                  insurance, statistics, ed. by James W. Glover ... compound
                  interest functions and logarithms of compound interest
                  functions, life insurance and disability insurance functions,
                  probability and statistical functions and seven place
                  logarithms of numbers from 1 to 100,000.
Published:     Ann Arbor, Mich., G. Wahr, 1923.
Description:   xiii, 676 p. 24 cm.
LC Call No.:   HG1632.G46 1923
Subjects:      Mathematics -- Tables.
               Interest -- Tables.
               Logarithms.
               Insurance, Life -- Mathematics.
Control No.:   6853725

Author:        Goff, Thomas Theodore, 1882-
Title:         Self-proving business arithmetic / by Thomas
                  Theodore Goff.
Published:     New York : Macmillan, 1923.
Description:   xv, 316 p. : ill., tables, forms ; 20 cm.
LC Call No.:   HF5691.G6
Subjects:      Business mathematics.
Control No.:   8728219

Author:        Kiggen, Helen J. [from old catalog]
Title:         Answer book to Practical business arithmetic,
Published:     New York, The Macmillan company, 1923.
Description:   p. cm.
LC Call No.:   HF5691.K52
Subjects:      Business mathematics.
Control No.:   9195808

Author:        National Committee on Mathematical Requirements.
Title:         The reorganization of mathematics in secondary
                  education; a report of the National Committee on Mathematical
                  Requirements under the auspices of the Mathematical
                  Association of America, inc.
Published:     [Oberlin, Ohio] The Mathematical Association of
                  America, inc., 1923.
Description:   x p., 2 l., 3-652 p. diagrs. 24 cm.
LC Call No.:   QA11.N25 1923
Notes:         "Bibliography of the teaching of
                  mathematics--1911-1921": p. [539]-627.
Subjects:      Mathematics -- Study and teaching.
Other authors: Mathematical Association of America.
Control No.:   7790744

Author:        Osborn, Jesse Otto, 1894-
Title:         A study of the rational involutorial
                  transformations in space which leave a web of sextic surfaces
                  invariant ... by Jesse Otto Osborn.
Published:     Ithaca, N.Y., 1923.
Description:   1 p.l., p. 17-36. 25 cm.
LC Call No.:   QA601.O8 1923
Notes:         Thesis (Ph.D.)--Cornell university, 1923.
Subjects:      Transformations (Mathematics)
Other titles:  Sextic surfaces.
               Surfaces, Sextic.
Control No.:   1690409

Author:        Pennsylvania. Dept. of Public Instruction.
Title:         Course of study in mathematics, years VII-XII.
Published:     Harrisburg, Pa., J.L.L. Kuhn, printer to the
                  commonwealth, 1923.
Description:   40 p. 23 cm.
LC Call No.:   QA11.P4
Notes:         At head of title: Commonwealth of Pennsylvania. 
                  Department of  public instruction.
Subjects:      Mathematics -- Study and teaching.
Control No.:   10131723

Author:        Swenson, John August.
Title:         High school mathematics : a first course / by
                  John A. Swenson.
Published:     New York : Macmillan, 1923.
Description:   ix, 419 p. : ill., diagrs. ; 20 cm.
LC Call No.:   QA39.S9
Notes:         Includes index.
Subjects:      Mathematics.
               Algebra.
               Geometry.
Control No.:   6854103

Author:        Wentworth, G. A. (George Albert), 1835-1906.
Title:         Junior high school mathematics,
Edition:       Teachers' ed.
Published:     [n.p.] [1923]
Description:   v. cm.
LC Call No.:   QA39.W43
Subjects:      Mathematics.
Control No.:   7203015

Author:        West, Clarence J. (Clarence Jay), 1886-1953.
Title:         List of manuscript bibliographies in astronomy,
                  mathematics and physics / compiled for Research Information
                  Service, National Research Council by Clarence J. West and
                  Callie Hull.
Published:     Washington, D.C. : National Research Council,
                  1923.
Description:   14 p. ; 27 cm.
Series:        Reprint and circular series of the National
                  Research Council ; no. 41
LC Call No.:   Q11.N293 no. 41
Notes:         Cover title.
Subjects:      Astronomy -- Bibliography of bibliographies.
               Mathematics -- Bibliography of bibliographies.
               Physics -- Bibliography of bibliographies.
               Astronomy -- Bibliography.
               Mathematics -- Bibliography.
               Physics -- Bibliography.
Other authors: Hull, Callie.
Other authors: National Research Council (U.S.). Research
                  Information Service.
Control No.:   7790956

/More items found later:/

Author:        Buchanan, Margaret, 1885-
Title:         Systems of two linear integral equations with two
                  parameters and symmetrizable kernels / by Margaret Buchanan.
Published:     [Baltimore : s.n., 1923]
Description:   155-185, [1] p. ; 26 cm.
LC Call No.:   QA431.B8
Notes:         Vita.
               Thesis (Ph. D.)--Bryn Mawr College, 1922.
               "Reprinted from American journal of mathematics,
                  vol. XLV, no. 3, July 1923."
Subjects:      Integral equations.
Control No.:   8729151

Author:        Buchanan, Herbert Earle, b. 1881.
Title:         Periodic oscillation of three finite masses about
                  the Lagrangian circular solutions ... by Herbert Earle
                  Buchanan ...
Published:     [Baltimore, 1923]
Description:   1 p.l., p. 93-121. 26 cm.
LC Call No.:   QB362.B88
Notes:         Thesis (PH. D.)--University of Chicago, 1909.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from American journal of mathematics,
                  vol. XLV, no. 2, April, 1923."
Subjects:      Three-body problem.
Control No.:   2162343

Author:        Barnett, I. A. (Isaac Albert), 1894-
Title:         Differential equations with a continuous
                  infinitude of variables ... by Isaac Albert Barnett ...
Published:     [Baltimore, 1923]
Description:   1 p.l., [1], 172-190 p., 1 l. 26 cm.
LC Call No.:   QA372.B3
Notes:         Thesis (PH. D.)--University of Chicago, 1918.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from American journal of mathematics,
                  vol. XLIV, no. 3, July, 1922."
Subjects:      Differential equations.
Control No.:   746021
