#+STARTUP: showeverything logdone
#+options: num:nil

Michael Gorman is the president of the ALA (American Library Association), who has emerged as a staunch opponent of many types of collaborative knowledge-organization efforts.   In [http://www.libraryjournal.com/article/CA502009?display=BackTalkNews&industry=BackTalk&industryid=3767&verticalid=151&& this piece], for instance, he fires back at bloggers for criticising his negative stance on Google (which gives him a chance to attack blogs in addition to Google).  Like [[file:Robert McHenry.org][Robert McHenry]], Gorman is supposed to be a knowledge egalitarian, yet he has bizarrely situated himself in opposition to the most egalitarian of knowledge organization trends and technologies.  The end result is that he has revealed himself to be an info-oligarch, first and foremost.  

Here is a small [http://www.furl.net/item.jsp?id=2081623 blurb] in my quasi-blog, discussing the above Gorman piece. --[[file:akrowne.org][akrowne]] Sat Feb 26 15:55:55 UTC 2005

----

Amusing blurb. --[[file:jcorneli.org][jcorneli]]
