#+STARTUP: showeverything logdone
#+options: num:nil

From Greg Egan's Sci-Fi neo-classic, "Diaspora"

http://gregegan.customer.netspace.net.au/DIASPORA/01/Orphanogenesis.html

(Background: "[...] It is the
thirtieth century. The "world" has evolved into
a vast network of probes, satellites, and
servers knitting the solar system into one scape
from the outer planets to the sun. Humanity,
too, has reconfigured itself. Most people have
chosen immortality, joining the polises to
become conscious software. Others have opted for
disposable, renewable robotic bodies that remain
in contact with the physical world. A few
holdouts stubbornly remain fleshers struggling
to shape an antiquated existence in the muck and
jungle of Earth. [...]"

Chapter 2, "Truth Mining" (page 47):

"Every tunnel in the Mines was built from the
steps of a watertight proof; every theorem,
however deeply buried, could be traced back
to every one of its assumptions. And to pin
down exactly what was meant by a "proof,"
every field of mathematics used its own 
collection of formal systems: sets of axioms,
definitions, and rules of deduction, along
with the specialized vocabulary needed to
state theorems and conjectures precisely."

forward [[file:MMHDM1_introduction.org][MMHDM1_introduction]]
