#+STARTUP: showeverything logdone
#+options: num:nil

I selected the Truth Mines passage above
because it is obvious that Greg Egan has
done some serious homework on the problem.
Call it fiction or fantasy, or merely
hypothetical, Egan provides us with a key
truth that may be applicable to HDM: all
of "mathematics" won't fit into one logic,
one notation, one vocabulary. Different
mathematics may even seem to contradict each
other! 

http://en.wikipedia.org/wiki/Category:Mathematics

    "[...]In the formalist view, it is the 
    investigation of axiomatically defined 
    abstract structures using logic and 
    mathematical notation.[...]"

An American friend who has travelled extensively on
business informed me that in other languages there
are words which cannot be translated into English.
There is no common referent. Meaning exchange can
be attempted by telling a few stories, but
translation is *impossible*.

A genius, or a crazy-man, or an extra-solar
alien might devise a system so deeply orthogonal
to our experience that even if we could
recognize the very existence of his symbols and
axioms, we might be no more capable of
applying them than a 2 year old child given
keys to a car and a road map could drive
from Texas to Bolivia.

The challenge and opportunity for HDM is to
be agnostic, or noncommital, but not just about
logic and language, but philosophically and
existentially! Or, as another friend is fond
of pointing out:

    "To be is to do" -- Socrates 

    "To do is to be" -- Jean-Paul Sartre 

    "Do be do be do" -- Frank Sinatra...  

forward [[file:MMHDM1_objectives.org][MMHDM1_objectives]]
