#+STARTUP: showeverything logdone
#+options: num:nil

I'd like to get someone to write this article... the question about
the proper or preferred role of computers, machines, robots, etc., in
human affairs has been long discussed by fiction writers and futurists
(as well as romantics).  I'm going to look into finding a contributing
author, since I don't know if I'm capable of kicking off a good discussion
about this topic: I'd personally like to have a computer for a teacher.

In order to preemptively counter one line of argument (or maybe it is just a
diversion? - ooo, or it could be a leading question!) I'll mention that having a
computer as a teacher and having a community of learners who communicated with
you via computer may not be so different.  If the computer can simulate many
aspects of this community, then can it be so bad?  Someone might say, well,
I don't want to learn from an online community either - maybe.  I don't know!
I'd be interested to see what sorts of criticisms people can put together.

--[[file:jcorneli.org][jcorneli]]


Here is a short essay by a fellow Minnesotan that seems to indicate
that we may have a bit of the best of both worlds: http://www.dtc.umn.edu/~odlyzko/doc/electronics.education.short.txt
and, briefly, that people who don't want a computer for a teacher
may have little to worry about. --[[file:jcorneli.org][jcorneli]]
