#+STARTUP: showeverything logdone
#+options: num:nil

*  Principals

 * Pitman, as lead PI
 * Krowne, as co-PI

Relevant existing collaborations between these people:

 * lecture notes linking, work on NNexus (ongoing)

 * founded, formulated Math Atlas plan and design, some steps underway
  (e.g. OJS install, converting over Rusin site)

 * formulating a new open information infrastructure for the IMS and
  mathstat in general

*  Staff


 * krowne as technical mgr., maybe 1/4 time worth of support??
 * what does jim need?
 * maybe 1-3 (or more?) developers to work on various aspects of above tasks
 * probably need someone doing outreach (e.g. to potential atlas
  editors, for classroom use of our products, maybe focus groups
  and/or other studies, etc)

*  Letters of Support

Seek from people like:

 * Martin Halbert (Emory)
 * Ed Fox (VT)
 * Other MathWeb folks (David Rusin, Michael Kohlhase, ...)
 * Other Emory folks (e.g. Li Xiong, some folks from math dept?)
 * folks from previous PM NSF grant attempt (Dunlap, Tatar, ...)
 * Kyle Siegrist (JOMA -- possibly a collaborator)
 * Jon Borwein (Dhalousie and other Canadian institutions, 
  as well as MathResources -- another possible collaborator)

----

* Building the team

I remarked at the Evolution of Math. Comm. workshop that the NSF likes
to see multiple PIs because they at least know that that many people
will be interested in seeing the result through to successful
completion -- it's a robustness thing!

Additionally, having lots of PIs typically means that there will be a
lot of available "grunt work", in the form of the employees and/or
(more likely) students of these PIs.

I think that if this grant application is going to be successful it
would be great to have a better sense of who exactly this "team" of
PIs and students/staffers is going to be.  As with PM, we always have
to ask -- who's going to do the work? :).  (I can't imagine that many
of Pitman's statistics students will be interested.)

So, let's clarify this stuff.

My sense is that it would be a good idea to get some version of the
document ready for wide circulation among relevant people (potential
PI's, potential reviewers, supporters, etc.) very soon, in an effort
to get more people on board.  (See first paragraph above.)

Specifically, I think it would be a very good idea for us to really
work hard on the possibilities for /international/ collaboration
through "partner funding" (e.g. Jon, Michael, unknown others?).

--[[file:jcorneli.org][jcorneli]]

I'm a little iffy on "partner funding" internationally.  I'd like to
talk to Borwein to find out more about this and what his desired status
on this grant is, but he's been a bit quiet thus far on the listserv.  I'll
have to prod further.

Also, I'm reticent to crowd the PI roster too much.  In my past experience,
that has just resulted in way too many meetings and way too much overhead,
relative to the productive work being done.  

One must be very selective in these matters: most grad students are horrible
workers: the numbers game works against you here.

--[[file:akrowne.org][akrowne]]

A crowded team would be bad, that's true.  But we can still build the
team w/o crowding by asking for letters of support from many people...

And it would be super to say what sort of staff would need to be hired.

--[[file:jcorneli.org][jcorneli]]

* Expertise

I think it is fair to say A. Krowne has "expert status" in the field
of digital libraries.  Hopefully the past experience stuff we talked
about (e.g. Citadel etc.) will be described in overview (or cleverly placed references).

--[[file:jcorneli.org][jcorneli]]

* Partners (at least, in our dream team)

Some organizations we might want to get onboard with !PlanetMath and
the Math Atlas and friends, in some sort of partnership:

 * [http://www.bridgesmathart.org/ BRIDGES Mathematical Connections in Art, Music, and Science]
 * [http://www-history.mcs.st-andrews.ac.uk/index.html the MacTutor people]
 * ...

Everything old is new again!

--[[file:jcorneli.org][jcorneli]]

Even [http://www.pen.k12.va.us/Div/Winchester/jhhs/math/quotes.html a list of quotes about mathematics] could be a valuable learning resource, since it contains interesting implicit heuristics, and other facts.  Of course, with the right permissions
you could just put this list online as a PM entry.  

(The business about heuristics reminds me, again, of Polya.  It would
be just peachy if we could find some people who were continuing his
work and get them wetwired into HDM.)

--[[file:jcorneli.org][jcorneli]]

[http://math.cofc.edu/faculty/kasman/MATHFICT/ This cool list of mathematical fiction] illustrates the fact that in a Noosphere type of system, anything goes, from Zippy
on up to Zeilburger.  You don't have to worry about what's formal, correct, or
any of that, just what's fun and interesting.

--[[file:jcorneli.org][jcorneli]]
