#+STARTUP: showeverything logdone
#+options: num:nil


 1. enable specific communities to revolutionize how they do things and
  who participates -- so: talk about a changable/changing community.

 1. exploit mutual self-interest -- so: the voluntary spirit of the MM

 1. cyberinfrastructure IS "core infrastructure" (for some suitable
  definition of the word "core")

 1. there's a discrepancy between what's actually possible now and what
  would be ideal but is only indirectly possible (i.e. those things
  which will require work)

 1. the `balkanization' issue is a big deal -- and needs to be addressed
  on several levels

 1. we should talk about the interdisciplinary future of Noosphere

 1. talk about the idea of a meta-commons -- or Galois's `associations'

 1. Why hasn't "Xanadu" been built and widely deployed (interesting
  research question having little or nothing to do with Ted Nelson)

 1. discuss commercial -- and non-commercial -- spin-off possibilities
  (How does this grant fit into a 10-year plan?)

 1. Note that Arxana may have a LOT of links.  How many links are in PM
  currently?  If it ends up having really a lot, then this may
  effectively become a high-power computing project (e.g. of the sort
  Borwein likes)

 1. (1) educate new generations in best techniques; (2) span discipline
  boundaries; (3) democratize participation.  All key things to plan
  to address.

 1. Ask for support for building translation infrastructure!  (or
  plugging in someone else's preexisting translation infrastructure,
  or some combination) We can talk about this relative to
  "subinstances" or "indexes" or whatever the term is for "areas" in
  NooXana.

## emphasize translation as steps towards broad international partnership!

 1. talk sustainability, stewardship, guidance, oversight -- and BTW,
  what are our qualifications in these areas?  Some but limited.
  Maybe hurry up and seek an MAA partnership to deal with the aspects
  of these long-term issues which would benefit from
  mega-institutional support.

## We don't always have to do "oversight" ourselves, but we should
   talk about how we will interface with relevant "overseers", whether
   they are higher or lower in the "oversight {hier,heter}archy".

## GOVERNANCE is going to be a big deal since PM is "open", and of
   course it is going to be even more of an issue the more hackable
   Noosphere becomes.  (Talk about creating governance structures
   relative to organizational sustainability.)

 1. hackable Noosphere pumps math-sci folks into programming experinces!

 1. Mention HDM stuff in the long-term plan

 1. What OUTLINE do they specify?  (I.e. what are they physically
  expecting to see, not just contentfully, which is what we learned
  about in this document.)

 1. Relate our work to MathWeb/MBase and the UK e-Science initiative
  (and projects administered within these and other related projects!)

 1. Non- or fuzzily-separated `planets' will be good for working towards
  interdisciplinary science.  Someone working in Biology might choose
  to turn up the "math knob" locally, for example, and control various
  other info-overlap settings with various other knobs.

 1. Emphasize the learn-at-your-own-chosen-speed option provided by PM.
  (And tie this in to long-term education support.)

 1. Emphasize PM's inclusivity -- and the connections it affords between
  interested students and interested experts.  (Note that this will go
  much better when subchanneling is in effect.)

 1. Emphasize "pricing, terms, and conditions" of communication
  artifacts as topics we have been and will continue to be concerned
  with and working on.

 1. Explain why we are applying here and not under the NSF CISE digital
  library initiative.

 1. Respond to their advice on tutorials, documentation, tools
  (i.e. having these things at all levels)

 1. emphasize dynamic curricula formed by repeated teacher-student
  interaction.  (Again this will tie into future curricular strategies
  -- over the long run it should be possible to do more experiments on
  how people learn best.  Right now there is research on these topics.
  We should, ideally, integrate such research into the materials
  hosted on Noosphere/Arxana.)

 1. Talk about the challenge of creating public goods!  (public
  education and citizen science being two of the examples we've
  thought about but there are more)

 1. provide evidence as to the insufficiency of existing tools (such as
  relational databases)

 1. speak especially to the top-level category "interaction" that
  they've introduced

 1. Include evaluation methodology, esp. for our shorter-term items
  (assume a 10-year plan, with possible new grant funding coming from
  NSF-CIO or others, later).

 1. Examine figures from their report and talk in terms of these figures.

 1. Build a small interdisciplinary "team" to work on the project -- and
  talk about long-term approaches to interdisciplinary-ness.
  (E.g. from hiring social scientist to help guide development of
  modules and governance structures, to interactions between hosted
  domains).  Talk some about what's wrong with interdisciplinary-ness
  at present, e.g. with reference to the uni-directional link model.

 1. Discuss the balance between "base" and "meta" in PlanetMath.

 1. Talk about realistic future applications of the PM/Atlas materials

 1. Talk about "related work" at each point -- how do we know we aren't
  being redundant.  Note that when people are working on related
  things, that doesn't immediately imply redundancy (they talk about
  "competition" between research after it's been completed).
  Something interesting that can potentially help in some cases is the
  idea of an "interlingua".  (I made a little model that shows uses
  graph theory to argue that an interlingua can cut down on redundancy
  even when there are research groups who insist on doing things their
  own way.)  Redundancy at some level isn't at all fatal.  But still,
  saving work in the long run is a good idea.  This is actually an
  interesting research topic (which we may be building the "virtual
  laboratory" to study, BTW).

 1. Note that what I've referred to as "exchanges" in correspondence may
  be what they refer to as "middleware".

 1. Mention the domain-specific needs of Mathematics (esp. vis-a-vis
  Communication of Mathematics).

 1. Talk about specific impact our work will have on research activities
  and styles of doing research

 1. "Development, operations, and use are not separate" -- I very much
  like this way of thinking.

 1. what services does PlanetMath provide?  What (new) services do we
  envision ourselves providing after the grant work is completed?

 1. Budget to study the impact at each stage -- have criteria for
  "success" and even for "failure"! (loose ones, maybe)

 1. Talk about funding relevant human resources -- they do!  (Again, the
  ten-year plan!)

 1. Relevance to school education -- this is a "hot-button topic" right
  now. (I just saw Bill and Melinda on TV tonight talking about this
  stuff -- American high schools being outdated and so on.)

 1. Outreach to women?  I haven't had any luck personally.  To other
  groups?  (I imagine the translation thing would be a big deal
  there.)

 1. New methodologies that get facilitated through our work: talk about
  future HDM, Kohlhase/MKM styles of work being made POSSIBLE by work
  at this stage

 1. Check out all of their previously-funded projects for overlap.

 1. Talk about "outreach" and "administration" in terms of serving the
  user community with subsequent adjustments to the things we've
  built, question answering, even "hand-holding".

 1. Talk about addressing (technology-related and just plain
  community-related) social challenges -- and opportunities, as they
  say -- not just the technical challenges.

 1. Finding and removing bottlenecks -- this relates to our conception
  of improvements to "integration"
