#+STARTUP: showeverything logdone
#+options: num:nil

When compared with the goals of the PlanetMath project (see [[file:PlanetMath Goals.org][PlanetMath Goals]]),
the FEM project seems -- at least on the surface -- to have a comparatively much simpler
goal:

: To make the world's best printed mathematical reference work.

(Anyway, this is my -- stated, now -- goal for the FEM.)

But of course to anyone who wants to think about it, this goal is not
particularly simple.

Best - for who?  for what?

And is it feasible, given that the FEM is a derivative work of another project
(the PM encyclopedia)?

~

My take is that, if this goal is earnestly adopted by the FEM editors, it will
become a "guiding force" for the PM project -- even if it not adopted as a
formal goal of the PM project.

"Best for who and what?" means best for everyone, and, in all innocence and
sincerity, everything.  FEM and PM together are the freest openly comprehensive
expository math reference works available.  This is the key advantage, from
which others derive.

As an editor and organizer for the project, I hope to help build the
/coverage/ of the PM/FEM collection until it is as comprehensive as anyone
might like.  The vision of a collection of volumes, each the size of the current
FEM, and one for each MSC -- is somewhat appealing to me.  Let it grow!  Let it
also be condensed, organized, self-reflexive and intra-referential.  Let it come
to contain the most agreeable and enjoyable treatments of all mathematical
subjects, done in many different ways, in different languages, in different
forms - "macro", "micro", "handbook", "textbook".  Let it have a franchise -
journals, research letters, workshops, public talks, free software.  Whatever is
required.

But - to be realistic - for the foreseeable future there will be An
Encyclopedia, which will sit (as the PM encyclopedia does now) at the center of
this web of connected resources.

It will make math available (compare PM) and it will hopefully help enhance the
mathematical experience for those who use it.  It will also help spread the
message of freedom to people who haven't heard freedom speak in mathematical
terms before.

Is this all feasible?  Well, it depends on the user community, as well as on the
leadership of the FEM makers and others in the free content business and in
mathematics.  I think it is.  But it will not happen without time, effort, and
sacrifice.

~

Beyond this, I would like to spell out a couple of personal goals I have for the
project.  (I have done this a little in the article on [[file:scope and clarity.org][scope and clarity]],
where I said that my goal is to understand everything in the FEM.)  I think that
the FEM will be good practice and a good source of sample info for what I
consider to be my primary project, the [[file:HDM.org][HDM]].  I want the FEM to be of high
quality, not just because I "care", but because I want to have some idea about
what high quality is, so I can have a clear idea about aims for the HDM.
Understanding quality is one of the research efforts that the two projects can
share.  From the beginning, I was attracted to PM because of the presence of
transparent texts.  The FEM project is giving me a chance to play with some of
the interesting details of these texts, and to learn things about their creation
and processing that might not have been so easy to learn about otherwise.  So, I
want to work on the FEM as part of my preparation for building the HDM.

I also want to use the FEM as a vehicle to create cash flow to people working in
the area of free mathematics (including myself).  This is another reason for
wanting the work to be of high quality.  I also want the work to be available
cheaply, so that students can buy it and in the process help fund the creation
of more new free math.  When the book is ready for a high-quality printing, I
want an expensive deluxe edition to be made so that people who care for such
fineries can have something they value, and make even bigger funding
contributions.  If we can have the book printed overseas, that will not only
help distribute the content to other people - but help provide more funding for
us.  I don't know yet whether the financial impact of this work will be small or
large - but if it is really the best work, and not only that, the best value,
then I'm sure the impact will be felt.

----
