#+STARTUP: showeverything logdone
#+options: num:nil

Oscar E. Masaveu

I am an Associate Professor and the Chair of the Division of Sciences, Mathematics, Engineering, and Technologies at Potomac State College of West Virginia University. My home page is at:

http://math1.psc.wvu.edu

My research interests include general topology, topological groups, and nonstandard logics.

On [[file:PlanetMath.org][PlanetMath]], Efnet, and Undernet I am better known as loner. I am the administrator for the undernet channel #math-zfc. It's home page is at:

http://br.endernet.org/~loner

the channel is for seminars and courses on mathematical topics.

I have been interested in [[file:PlanetMath.org][PlanetMath]] since its start and I have been following it's progress. Personal concerns have kept me from being an active participant until very recently. I think that both [[file:PlanetMath.org][PlanetMath]] and the [[file:FEM.org][FEM]] are very worthwhile projects and I hope I can make positive contributions to both.

----
Hi Oscar - welcome to AsteroidMeta.  Greetings, --[[file:jcorneli.org][jcorneli]] Thu Mar 03 02:59:11 2005 UTC
