#+STARTUP: showeverything logdone
#+options: num:nil

* Adbusters

I've always been a little skeptical of [http://www.adbusters.org Adbusters],
maybe partly because several people warned me to be wary of them.
However, they have some interesting ideas, and they also seem to have
one (or more) relatively viable business/activism models.

 * http://www.adbusters.org/network/about_us.php
 * http://adbusters.org/metas/corpo/blackspotshoes/aboutblackspot.php
 * http://www.gadflyonline.com/lastweek/kalle%20lasn.html (interview)

My sense is that if we could get Kalle Lasn (I think he is the lead editor)
interested in free culture, we could find a great advocate (or advertiser).  Similarly,
we might find some useful contacts within the "antipreneur" network
they have already put together.  (Although I haven't quite been able
to figure out the media they are using.  They do list a number in Vancouver, so
we could just call up and find out...)

I'd also be interested in anyone who could tell me more about why I think
it is good to be skeptical enough to go into this with at least
one eye open ;).

--[[file:jcorneli.org][jcorneli]]

* tlaxcala

Snagged at www.AxisOfLogic.com concerning the new 
activist group for translations: 

http://www.tlaxcala.es/

Tlaxcala Against the Unique, or How to Translate a Lamb

By Santiago Alba Rico (translated from Spanish into English by Manuel 
Talens and revised by Mary Rizzo)

Feb 21, 2006, 12:54

http://www.axisoflogic.com/artman/publish/article_21158.shtml


[...]

The mysteries are three. The first one is that we speak. The second is that we speak different languages. The third is that we can translate them. Of the three, the most enigmatic and definitive, the one which better defines us as human beings, is the last one. A lion and a butterfly do not have anything to say each other, a zebra and a lamb can collide, but they do not change places. What distinguishes human beings from animals is that only human beings can translate and be translated. Only what does not admit a translation is a species, only what is not possible to translate is a race and that's why a zebra is a jail. If something is impossible to translate it is not free. Racism, xenophobia, male chauvinism, imperialism, capitalism, are fiercely opposed to any translation, they want to exhaust the world in their watertight species, they treat men as zebras of a unique version, as untranslatable lambs. To translate is to go out of the zebra, that is to say, to go out of jail. Translating a lamb is
converting it into a human being.

[...]

--[[file:ocat.org][ocat]] 28-Feb-2006

Cool prose!  Of course, these people would be good to talk to
when PM is ready to host translations of encyclopedia pages.
--[[file:jcorneli.org][jcorneli]]

* Ubuntu

These folks seem to have the, or at least some, right idea(s)
about making linux distros.  And they are interested in education
(mainly for young people it seems).  Are they also potentially
interested in !PlanetMath content?  We should ask.

(They aren't necessarily activists per se, but maybe they
are sort of?)

They definitely have an OK map!

https://wiki.ubuntu.com/UbuntuWorldWide

Also they have nice community spirit!!

http://www.ubuntu.com/community/conduct 

and they are connected with a foundation...

http://www.shuttleworthfoundation.org/

although said foundation does not fund "international programs and institutions" :(.


--[[file:jcorneli.org][jcorneli]]

I think with a little determination we could snag some shuttleworth money.  I have discussed it before
with my colleage, Hussein Suleman, who is in south africa.  We decided the problems were (1) the need 
to spend the money in south africa, and (2) the inability to pay money to people outside south africa.

But both of these can be worked around.  South africa could be used as a physical pilot for work applicable
anywhere, for example, instituting a translations infrastructure, making it easier or supporting the creation 
of more pedagogical entries, doing distros-on-a-CD, or developing/marketing the FEM.    And we could use local
labor for all of these, so the spending itself would all be in the country.  So I suggest we not discard this
option.

It would be really good if we could learn more about the needs of South Africa, and figure out how 
our project might address them in ways that further some of our aims.

--[[file:akrowne.org][akrowne]]

Cool! PM, by being global, can work around all artifical boundaries,
and do socially responsible things for various localities!  I like it.
Globalization usually is vilified (although even !AdBusters, above,
will hedge on that some).  In this case it seems really smart.  All we
need to do to take advantage of any local money is apply with a local
wing of the organization (and hopefully we can do transparent
accounting so that they always have one entity to write checks to).  I
hope Suleman will continue to be interested in this.  --[[file:jcorneli.org][jcorneli]]

* Independent Media Center

(I a compeer of this woman Tish in '97 or so... I should really get
back in touch; anyway, the stuff here looks interesting, and very on
topic for all of our work, but especially the more radical 
[[file:scholium system.org][scholium system]] stuff.)

http://www.ruf.rice.edu/~tish/researchproposal.html

--[[file:jcorneli.org][jcorneli]]
