#+STARTUP: showeverything logdone
#+options: num:nil

This page is relevant to the [[file:PlanetMath Budget and Resources.org][PlanetMath Budget and Resources]]
page; it discusses the "future" version of the same topic, and
how we are going to get to that future, or anyway, to some
desirable future.  "Desirable" is in terms of the organization's
[[file:PlanetMath Goals|goals.org][PlanetMath Goals|goals]], of course.

* Other related pages

 * [[file:PM Fundraising.org][PM Fundraising]] an older page with the same general goals.  It has been inactive for a while,
and I think we should re-evaluate the content there and depreciating that page in favor of
this one (moving relevant content here or creating separate pages as needed).
 * [[file:thoughts_on_the_viability_of_free-software_style_business.org][thoughts_on_the_viability_of_free-software_style_business]] An older page on AM talking about various fundraising and financing approaches.
 * [[file:Grant planning.org][Grant planning]] So far, a significant portion (but not all) of the PM fundraising effort has been directed towards grant applications.


* Discussion

It would be good to get feedback from the PM board on their ideas
about fundraising: the role of a non-profit's board is typically
to /specialize/ in fundraising matters.  Other's can and should (of course) contribute their thoughts too.  --[[file:jcorneli.org][jcorneli]]

I would be particularly interested to know djao's thoughts on funding
from Gates/MS (just for example). --[[file:jcorneli.org][jcorneli]]
