#+STARTUP: showeverything logdone
#+options: num:nil

This is the main page for talking about PM goals.  Some of the major portions of
the discussion have been split off onto separate pages.

 * [[file:PlanetMath Goal Tree.org][PlanetMath Goal Tree]]
 * [[file:Manifesto on Goals and Roles of The PlanetMath Community and The PlanetMath Nonprofit.org][Manifesto on Goals and Roles of The PlanetMath Community and The PlanetMath Nonprofit]]
 * [[file:PlanetMath whitepaper for potential partners.org][PlanetMath whitepaper for potential partners]]
 * [[file:Timetable for PlanetMath development.org][Timetable for PlanetMath development]]
 * [[file:Vision for the future of PlanetMath.org][Vision for the future of PlanetMath]]
 * [[file:Still more Questions and Goals for PlanetMath.org][Still more Questions and Goals for PlanetMath]]
 * [[file:PlanetMath ByLaws 2.0.org][PlanetMath ByLaws 2.0]] (contains a description of !PlanetMath's tentative official goals)

* Discussion

In [[file:First_Monday_Paper--The_HDM_Manifesto|the Dec 5 draft of the HDM Manifesto.org][First_Monday_Paper--The_HDM_Manifesto|the Dec 5 draft of the HDM Manifesto]],
I have a short paragraph on !PlanetMath.  The actual text of this paragraph
is basically completely inappropriate for publishing in First Monday (should
some revised version of the manifesto be accepted), but that didn't stop me
from writing it or putting it in my hastily-composed paper-proposal.  Despite
its shortcomings, this paragraph could be part of a reasonable beginning,
together with our recent phone conversation about "the relationship between
HDM and !PlanetMath", towards... understanding the relationship between HDM
and !PlanetMath!  I wrote a few words on this subject on the [[file:Noosphere documentation.org][Noosphere documentation]] page
(talking about how the [[file:scholium system.org][scholium system]] could potentially help with
both the documentation task and also with subsequent evolution of the Noosphere system),
and I also approached this the question of PM & HDM from a broader philosophical perspective
on the page [[file:totalizing projects.org][totalizing projects]].  The reason for posting this summary
paragraph here is that partly because the HDM is so "goal oriented" (not having
quite as much in the way of concretion to offer as one might hope, all else equal),
thinking some about the relationships between the two projects and the relationships
between the goals of the two projects might be a good way to kick off a renewed
discussion of !PlanetMath's goals -- and long-term plans.  There are a number
of different angles on the relationships between the projects that
we could discuss (collaborative, financial, end-goal, code-sharing, etc.),
but the focus for this page is how these things (or anything else, really) relate
to PM goals and long-term plans!   --[[file:jcorneli.org][jcorneli]]

----
[[file:PlanetMath.org][PlanetMath]]
