#+STARTUP: showeverything logdone
#+options: num:nil


While getting REU reports onto PM would I think be a great draw to the
site and value-add for the reports, the real value here is the connections
with universities, teachers, and developing scholars.   We expose them
all to PlanetMath and the environment of open production of mathematical 
knowledge, and presumably it will "take" for many of them (especially the
upcoming scholars).

I wonder how we go about doing this.  We have a great resource we can tap
along these lines: Ed Fox.  As director of the NDLTD (Networked DL of Theses
and Dissertations), Ed has for a half-decade been an activist for increasing
the visibility of the work of emerging scholars at the post-undergraduate
level.  Many hundreds of universities worldwide contribute to NDLTD, and what is 
astounding is how this contribution is not "extra" but is implemented by
being worked into the procedures of getting a MS or PhD.

Now, undergrad research is not quite such Big Business.  But many of the 
methods Ed must have learned to get universities on board for NDLTD must apply
to getting them to contribute in some capacity to an undergrad version of the
same.  Perhaps just convincing professors or even just the students that 
it is in their best interest to get their reports on PlanetMath would get
us a lot of content and people, without even making it part of the delivery
requirements.

Here's a thought: it might be easiest to start with the NDLTD universities, 
and leverage those connections and systems.

--[[file:akrowne.org][akrowne]] Sat Feb 11 06:22:41 UTC 2006

I think we can start in a few places roughly simultaneously --
specific REU programs, the REU main office, and NDLTD maintainers, and
the specific NDLTD institutions.

Note that getting the NDLTD /content/ into PM would be valuable.
(This presumably concerns both undergraduate research and /graduate/
research.)

--[[file:jcorneli.org][jcorneli]]
