#+STARTUP: showeverything logdone
#+options: num:nil

** job description

 * "whatever we need to move things forward", including:
 * maintaining the planetmath schedule, and keeping relevant parties plugged into it
 * "shepherding" ongoing tasks forward
 * helping out with (if not spearheading) organizational communications
 * outside communications (ongoing, into fundraising, etc.)
 * taking care of certain admin/overhead tasks.

** hours of work

5-10 hours per week; specific activities to be documented after
(at most) every five hours of work!

Documentation will appear at http://hyperrealenterprises.blogspot.com/.

** pay

I propose to do this at my standard PM contractor rate of $10/hr,
however I understand that this puts a new steady flow "out" from
the !PlanetMath budget and that I may eventually be required to
find money to go "in" to replace it.

** evaluation/oversight

I propose we reevaluate the effectiveness of this position after a month,
and vote about whether or not it should continue or change.

* Organization-wide Roadmap

This is a high-level overview of everything I'm aware of and assisting with;
for a more detailed task list, see [[file:PlanetMath Ongoing Tasks.org][PlanetMath Ongoing Tasks]].
I will supplement with projected dates when I figure out what the dates are!

 * Document "legacy" resources in one place ([[file:Hitchhiker's Guide to PlanetMath.org][Hitchhiker's Guide to PlanetMath]])
 * Assist other members of the organization in creating their own roadmaps
to document ongoing work and new developments
([http://code.google.com/p/noosphere/wiki/RoadMap Code Roadmap],
[http://planetmath.org/?method=l2h&from=collab&id=130&op=getobj Content Roadmap]--tentative,
[http://4.bp.blogspot.com/_vU10oTR0KWM/SrWMVUwvm-I/AAAAAAAAACE/qkFTWLfXMtM/s1600-h/road-to-free-math.jpg HDM project Roadmap]!,...)

 * Sort out organizational membership stuff.

 * Come up with a policy/toolkit/workflow for copying from Wikipedia and other
!CCBySA sources.
