#+STARTUP: showeverything logdone
#+options: num:nil

I sent this in to nameadmininc.com via their contact form, with my
return email address:

: I feel that www.planetmath.com, as the second google hit for
"planetmath" on google, is lowering the value of the "planetmath"
name. PlanetMath is a 501(c)3 non-profit organization, funded largely
by member donations, and dedicated to providing math as a public
service.  The www.planetmath.com site is, I think, not an appropriate
use of the "PlanetMath" name, and I would like you to take down that
site, if possible.

I hope they listen; if not I will probably email the people who are
using the planetmath.com site for advertising. --[[file:jcorneli.org][jcorneli]]

Good Luck, has there ever been a scrupulous internet company based out of the Cayman Islands.  --[[file:bloftin.org][bloftin]]

www.planetmath.net is also registered. Even if this means that people are making money out of PM, I would take this as a compliment. --[[file:matte.org][matte]]

If you find this troublesome, one possible solution would be to register a trademark on PlanetMath (and our logo), so that others could not take advantage of our name for their purposes without our permission.  I don't know that I am in favor (or oppose) this option, but I thought it would be worth mentioning since that is the usual way that situations like this are handled nowadays --- whilst people might toss a note like the one Joe wrote to the trash without thinking twice, they will take a letter informing them that they are infringing on a trademark seriously. --[[file:rspuzio.org][rspuzio]]

A slighly more guerrilla way of doing things might be to get in touch
with the advertisers who use pm.com, .net, etc., and mention to them
that we think they are choosing to advertise in a not-socially-responsible
manner.  That could lead to loss of business for the name admin people. --[[file:jcorneli.org][jcorneli]]
