#+STARTUP: showeverything logdone
#+options: num:nil

What about the [http://www.cafepress.com/planetmath PM cafepress] income - has there been any?
Is there a way to single that income out?  There is a place here in Minneapolis that makes
[http://www.northlandposter.com/cgi-bin/Web_store/web_store.cgi?mt=&page=stickers&cart_id=2050246.18762 bumper stickers]
and [http://www.northlandposter.com/cgi-bin/Web_store/web_store.cgi?page=posters&cart_id=2050246.18762 posters] 
t-shirts, mugs, and other stuff --
and whether or not we agree with everything that they say or sell, I would personally rather PM "support"
them than Cafepress (I don't know if Cafepress does posters and bumperstickers?) and in order to make my
actions speak even louder, I offer to take care of shipping (note: not pay, but do, i.e. physically
ship items) and help assimilate payment (whatever seemed helpful). 
The set-up work to do this would be non-trivial -- and 
we'd need some cool designs -- but I think we might be able to get some nice and /different/
stuff and maybe make some extra money.  Just for example, 500 
"Math for the people / By the people (SVG PM logo)" bumper stickers would cost PM $230.00, and supposing we
charged $2 + S&H a piece, they would make PM $770.00 by the time they all sold -- and they
would generate some nice propaganda.  Posters and other stuff would require a custom order,
but to get a sense of their prices, see 
[http://www.northlandposter.com/cgi-bin/Web_store/web_store.cgi?mt=&page=custom&cart_id=2050246.18762 this page].
I'd be happy to work out any details in person, but they do have a 1800 phone number.

--[[file:jcorneli.org][jcorneli]] Thu May 19 14:23:01 2005 UTC

I think there has been a tiny bit of cafepress income, but not even enough for them to issue us one check
(so, less than 50$).  

I dont know if they do posters or bumper stickers now, but they didn't back when we started the store (which
was admittedly a couple years ago).

I strongly oppose any sales-based fundraising efforts that require nontrivial up-front costs.  On the other hand,
if we can get people to "pledge" money provided we reach some threshold where we can deliver the goodies, that
would be fine.

We could even sell some related-but-not-specifically-PM-branded wares, such as "FREE THE MATH" bumper stickers
or something.

Hmm... maybe this would be another use for a generalized economic-activity-coordination engine that we could use
on PM (related to a couple of your past suggestions, at least).   We could have a list of items which could either
be goods or labor for the site, or goods to be sent to those who sign up as pledges (so, promotional items that
require up-front investment).  This list could be kept on the PM homepage.  Hmmmm.... it seems like there should
already be a system out there that does this...

--[[file:akrowne.org][akrowne]] Mon May 30 01:55:12 UTC 2005

This ties in nicely with the topic of [[file:social, political, and economic scholium systems.org][social, political, and economic scholium systems]].  I suppose that Joe is in the process of inventing the system you are looking for. --[[file:rspuzio.org][rspuzio]] 14 June 2005

----
[[file:PlanetMath Budget and Resources.org][PlanetMath Budget and Resources]]
