#+STARTUP: showeverything logdone
#+options: num:nil

/Note: The loans are now completely repaid---this is now an entirely historical page./

Since there is a catch-22 of startup costs for a nonprofit (i.e. you can't get 
major donations until you have a nonprofit, preferably tax-exempt, but you can't
get the money to create one before it exists), akrowne paid for most of the
costs up-front, with an understanding that they would be paid back after
not too long.  The reason this money was not just given up as donations is
because of akrowne's large time and effort commitments to the PlanetMath 
project.  He feels the material support for the project should come from
other parties, in order to (1) prove the project's social worth, and (2) 
keep the burden on himself managable.

In effect, then, a number of small to sizeable loans from akrowne to PM.org
were made, with no interest or set payback period.  Here is a detail of what is 
owed, and what remains (relative to akrowne):

||/date/||/charge/||/entity/||/purpose/||
||9/??/03||25.00||VA||nonprofit corp. reg. fees||
||9/??/03||75.00||VA||annual fees + processing||
||12/??/03||1718.54||DSBPC||research and filing||
||12/??/03||-250.00||PM.org||repayment||
||9/14/04||500.00||USG||tax-exempt public charity reg. fees||
||9/18/04||-450.00||PM.org||repayment||
||11/18/04||73.40||VA||annual corp. fees||
||11/??/04||-73.40||PM.org||repayment||
||5/29/05||-500.00||PM.org||repayment||
||9/07/05||-700.00||PM.org||repayment||
||9/07/05||-418.54||PM.org||repayment||
||*total*||0.0||||||

/Notes: (1) Coded entities are as follows: VA = The state of Virginia, mostly the 
corporation commission; USG = The US Government, mostly the Internal Revenue
Service; DSBPC = Dave S. Bracken, P.C., our initial lawyer and registered agent;
PM.org = the PlanetMath nonprofit org.
(2) Not all transactions are showed here; only ones paid up-front by akrowne.
(3) Dates are imprecise for purposes of rapid disclosure on this page; exact dates
can be produced by reviewing financial records if necessary./
