#+STARTUP: showeverything logdone
#+options: num:nil

This is a place to talk about ways to get a higher score on PM by abusing the
system in some way.  Or maybe some of these things aren't abuse?  Anyway, please
consider this to be totally "white hat", since presumably the people who are
debating the points here aren't going to actually go and abuse the system.

The only thing I can think of off the top of my head would be making
trivial/nonexistent revisions.  Other thoughts?

: One can create bogus entries (100pts/each), people would be furious and file
corrections galore, and then you wait for them to be orphaned or even orphan it
yourself (-50pts/each). Net profit: 50pts/each bogus entry. Am I missing
something?

: I'm not sure how the deleting affects score when there are multiple authors. But here's a thought.
A user with 2 accounts, one creates entries (+100) then gives full right to the other account, and then the other deletes it (-100) then you can get scores as high and as low as you want. This comes to my mind, since sometimes I delete orphaned entriesof very lousy quality, which causes a net loss to me (+50 for adopting it, -100 for deleting it) and then the original author preserves his +50. --[[file:drini.org][drini]]

I thought of that after I signed off -- apmxi still has a fairly high score for
this reason.  I don't think you could get onto the highscores list that easily
(because you'd need double the points...), but you could get a rather high
score.  This becomes more of an issue if mass uploading of files is available
(like it was to a short time for APM-Xi, and like it might be again in the
future for Wikipedia articles).  I think that one way to help with this
particular loophole would be for the original author to lose all the points
associated with an article whenever that article was deleted, no matter by whom. --[[file:jcorneli.org][jcorneli]] Thu Mar 03 14:00:10 2005 UTC


One loophole could be to create an entry, and en mass file requests as filled by this entry. This would give you extra points. However, maybe a more relevant problem is the following: what should we do with requests that are clearly in the wrong place. Despite the clear text at the beginning of the request page, there are always new users that ask homework questions there. Would it be OK to fill these in some way? Maybe to a dummy entry? These tend to clutter up the list. Feb. 2006 [[file:matte.org][matte]]
