#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Johnson, Hubert Rex, 1858- [from old catalog]
Title:         The Pythagorean theorem; a collection of original
                  and copied proofs, by Hubert Rex Johnson.
Published:     Washington, D.C., 1930.
Description:   3 p. l., 226 p. diagrs. 29 cm.
LC Call No.:   QA460.P8J6
Notes:         Autographic reproduction of type-written copy.
Subjects:      Pythagorean theorem.
Control No.:   12903518

Author:        Lietzmann, Walther, 1880-
Title:         Der pythagoreische Lehrsatz, mit einem Ausblick
                  auf das Fermatsche Problem, von dr. W. Lietzmann ... mit 44
                  Figuren im Text.
Published:     Leipzig, Berlin, B. G. Teubner, 1912.
Description:   2 p. l., 72 p. diagrs. 18 1/2 cm.
Series:        Mathematische Bibliothek, 3
LC Call No.:   QA460.P8L5
Notes:         "Einiges über die Literatur zum pythagoreischen
                  Lehrsatz": p. 70-72.
Subjects:      Pythagorean theorem.
               Fermat's theorem.
Control No.:   9166302

Author:        Loomis, Elisha S. (Elisha Scott), 1852-1940.
Title:         The Pythagorean proposition; its demonstrations
                  analyzed and classified and bibliography of sources for data
                  of the four kinds of "proofs".
Edition:       2d ed. 1940. By Elisha S. Loomis ...
Published:     [Ann Arbor, Mich., Edwards brothers, inc.,
                  lithoprinters, 1940]
Description:   xvi, 284 p., 1 l. incl. front., diagrs. ports. 24
                  cm.
LC Call No.:   QA460.P8L6 1940
Dewey No.:     513.14
Notes:         Bibliography: p. 271-276.
Subjects:      Pythagorean theorem.
Control No.:   3109084

Author:        Ayre, Henry Glenn, 1898- [from old catalog]
Title:         An analytical study of individual differences in
                  plane geometry,
Published:     Nashville, Tenn., George Peabody college for
                  teachers, 1939.
Description:   p. cm.
LC Call No.:   QA461.A9 1937
Subjects:      Geometry, Plane -- Study and teaching. [from old
                  catalog]
Control No.:   9719228

Author:        Benedict, Harry Yandell, 1869-1937. [from old
                  catalog]
Title:         The teaching of plane geometry, by H.Y. Benedict
                  ... and J.W. Calhoun ... (2d issue)
Published:     [Austin, Tex.] The University [1914]
Description:   57 p. diagrs. 23 cm.
LC Call No.:   QA461.B4
Subjects:      Geometry, Plane -- Study and teaching. [from old
                  catalog]
Other authors: Calhoun, John William, 1871- [from old catalog]
                  joint author.
Series Entry:  Bulletin of the University of Texas. no. 356.
                  Official ser. no. 104. Sept. 1, 1914. [from old catalog]
Control No.:   9177084

Author:        Christofferson, Halbert Carl, 1894-
Title:         Geometry professionalized for teachers, by
                  Halbert Carl Christofferson.
Published:     Oxford, Ohio, 1933.
Description:   vi, 204 p. diagrs. 24 cm.
LC Call No.:   QA461.C5 1933a
Dewey No.:     513.07
Notes:         "Selected bibliography": p. 193-201.
Subjects:      Geometry -- Study and teaching.
Control No.:   10162549

Author:        Coleman, Robert, 1915-1941.
Title:         The development of informal geometry, by Robert
                  Coleman,jr...
Published:     New York, Teachers college, Columbia university,
                  1942.
Description:   xii, 178 p. 24 cm.
Series:        Contributions to education, no. 865
LC Call No.:   QA461.C6 1942
Notes:         Bibliography: p. 169-178.
Subjects:      Geometry -- Study and teaching.
Other titles:  Informal geometry.
Control No.:   6919085

Author:        Coleman, Robert, 1915-1941. [from old catalog]
Title:         The development of informal geometry,
Published:     New York, Teachers college, Columbia university,
                  1942.
Description:   xii, 178 p., 1 l. 23 cm.
LC Call No.:   QA461.C6 1942a
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Other titles:  Informal geometry.
Control No.:   7385696

Author:        Davis, Margaret Rae. [from old catalog]
Title:         Teaching second year high school mathematics.
Published:     Hammond, La., The College, 1948.
Description:   36 p. diagrs. 23 cm.
LC Call No.:   QA461.D3
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   8841306

Author:        Del Grande, John J.
Title:         Geometry and spatial sense / John Del Grande,
                  Lorna Morrow; consultants, Douglas Clements, John Firkins,
                  Jeane Joyner.
Published:     Reston, Va. : National Council of Teachers of
                  Mathematics, c1993.
Description:   viii, 55 p. : ill. ; 28 cm.
Series:        Curriculum and evaluation standards for school
                  mathematics addenda series. Grades K-6
LC Call No.:   QA461.D35 1993
Dewey No.:     372.7 20
ISBN:          0873533178
Notes:         Includes bibliographical references (p. viii).
Subjects:      Geometry -- Study and teaching (Primary)
               Geometry -- Study and teaching (Elementary)
               Curriculum evaluation.
Other authors: Morrow, Lorna J.
Other authors: National Council of Teachers of Mathematics.
Control No.:   3467942

Author:        Durell, Fletcher, 1859-1946.
Title:         Suggestions on the teaching of geometry, with
                  especial reference to the use of Durell and Arnold's New
                  plane geometry,
Published:     New York, Chicago, Charles E. Merrill company
                  [c1924]
Description:   27 p. diagrs. 19 cm.
LC Call No.:   QA461.D8 1924
Subjects:      Geometry -- Study and teaching.
Control No.:   7324640

Author:        Durell, Fletcher, 1859-1946.
Title:         Suggestions on the teaching of geometry, with
                  special reference to the use of Durell and Arnold's geometry,
                  by Fletcher Durell ...
Published:     New York, Chicago, Charles E. Merrill Company
                  [c1921]
Description:   22 p. 19 cm.
LC Call No.:   QA461.D8
Notes:         Cover-title.
Subjects:      Geometry -- Study and teaching.
Control No.:   9191519

Author:        Eilberg, Arthur.
Title:         The Dalton plan versus the recitation method in
                  the teaching of plane geometry, books III, IV, and V and a
                  study of responses in the solution of original exercises [by]
                  Arthur Eilberg ...
Published:     Philadelphia, 1931.
Description:   145 p. diagrs. 24 cm.
LC Call No.:   QA461.E5
Dewey No.:     513.107
Notes:         Thesis (ED. D.)--Temple university.
               Bibliography: p. 132-134.
Subjects:      Geometry, Plane -- Study and teaching.
               Dalton laboratory plan.
Control No.:   4053879

Author:        Fawcett, Harold Pascoe, 1894-
Title:         The nature of proof; a description and evaluation
                  of certain procedures used in a senior high school to develop
                  an understanding of the nature of proof, by Harold Pascoe
                  Fawcett ..
Published:     New York city, Teachers college, Columbia
                  university, 1938.
Description:   1 p.l., v-xi, 146 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA461.F3 1938
Dewey No.:     513.0712
Notes:         Thesis (PH. D.)--Columbia university, 1938.
               Vita.
               Published also as the thirteenth yearbook of the
                  National council of teachers of mathematics.
               "Every pupil test, April, 1936, conducted by the
                  state Department of education, Columbus, Ohio. Plane
                  geometry": [4] p. inserted between p. 126 and 127.
               Bibliography: p. 145-146.
Subjects:      Geometry -- Study and teaching.
Control No.:   3581504

Author:        Henderson, Archibald, 1877-1963.
Title:         The teaching of geometry, by Archibald
                  Henderson.
Published:     Chapel Hill, N.C. [The University] 1920.
Description:   49 p. diagrs. 23 cm.
Series:        University of North Carolina record, no. 181,
                  October, 1920. [Extension series, no. 39
LC Call No.:   QA461.H4
Notes:         "Bibliographical note": p.48-49.
Subjects:      Geometry -- Study and teaching.
Control No.:   6380264

Author:        Iles, George, 1852-1942.
Title:         A class in geometry : lessons in observation and
                  experiment / by George Iles.
Published:     New York ; Chicago : E.L. Kellog, c1894.
Description:   46 p. : ill. ; 19 cm.
LC Call No.:   QA461.I27
Subjects:      Geometry.
Control No.:   10071427

Author:        Judson, C. H. [from old catalog]
Title:         Text-books on geometry. An essay read before the
                  educational institute of South Carolina.
Published:     Philadelphia, J. B. Lippincott & co., 1872.
Description:   22 p. 23 cm.
LC Call No.:   QA461.J93
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   7729513

Author:        Klein, Felix, 1849-1925.
Uniform Title: Elementarmathematik von höheren Standpunkte aus.
                  English
Title:         Elementary mathematics from an advanced
                  standpoint. Geometry; translated from the third German
                  edition by E.R. Hedrick ... and C.A. Noble ... with 141
                  figures.
Published:     New York, The Macmillan company, 1939.
Description:   ix, 214 p. illus., diagrs. 24 cm.
LC Call No.:   QA461.K45 1939
Dewey No.:     513
Notes:         A translation of v. 2 of the author's
                  three-volume work entitled Elementarmathematik vom höheren
                  standpunkte aus.
Subjects:      Geometry -- Study and teaching.
Other authors: Hedrick, E. R. (Earle Raymond), 1876-1943, tr.
               Noble, C. A. (Charles Albert), b. 1867, joint
                  tr.
Control No.:   1691263

Author:        Lazar, Nathan, 1898-
Title:         The importance of certain concepts and laws of
                  logic for the study and teaching of geometry, by Nathan Lazar
                  ...
Published:     New York, 1938.
Description:   67 p. illus. (facism.) diagrs. 26 cm.
LC Call No.:   QA461.L3 1938
Dewey No.:     513.07
Notes:         Thesis (PH. D.)--Columbia university, 1938.
               Vita.
               Published also without thesis note.
               Bibliography: p. 63-65.
Subjects:      Geometry -- Study and teaching.
               Logic.
Control No.:   274628

Author:        Lazar, Nathan, 1898-
Title:         The importance of certain concepts and laws of
                  logic for the study and teaching of geometry, by Nathan
                  Lazar, PH.D.
Published:     New York, 1938.
Description:   66 p. illus. (facsim.) diagrs. 26 1/2 cm.
LC Call No.:   QA461.L3 1938a
Dewey No.:     513.07
Notes:         Bibliography: p. 63-65.
               Includes index.
Subjects:      Geometry -- Study and teaching.
               Logic.
Control No.:   8775338

Author:        Mallory, Arthur Ernest.
Title:         The significance of plane geometry as a college
                  entrance requirement / by Arthur E. Mallory.
Published:     Nashville, Tenn. : George Peabody College for
                  Teachers, 1932.
Description:   108 p. ; 23 cm.
Series:        George Peabody College for Teachers.
                  Contributions to education ; no. 110
LC Call No.:   QA461.M3 1932
Notes:         Thesis (Ph. D.)--George Peabody College for
                  Teachers, 1932.
               Bibliography: p. 105-108.
Subjects:      Geometry, Plane -- Study and teaching.
               Universities and colleges -- United States --
                  Entrance requirements.
Control No.:   7354284

Author:        McCurdy, D[ennis]
Title:         An essay on the means and importance of
                  introducing the natural sciences into the family library, and
                  diffusing the elements of geometry into the plan of the
                  popular education: by D. McCurdy.
Edition:       2d ed., improved.
Published:     Washington, Blair and Rives, Printers, 1842.
Description:   46 p. 21 cm.
LC Call No.:   QA461.M14
Subjects:      Geometry -- Study and teaching.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
Control No.:   5864123

Author:        McCurdy, D[ennis] [from old catalog]
Title:         An essay on the means and importance of
                  introducing the elements of geometry into the general plan of
                  the popular education:
Published:     Washington, Blair and Rives, 1841.
Description:   40 p. 23 cm.
LC Call No.:   QA461.M13
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Other authors: YA Pamphlet Collection (Library of Congress) DLC
                  [from old catalog]
Control No.:   9603136

Author:        Milner, Florence.
Title:         On teaching geometry. By Florence Milner ...
Published:     Boston, D.C. Heath & co., 1900.
Description:   1 p.l., 18 p. 20 cm.
Series:        Heath's mathematical monographs
LC Call No.:   QA461.M65
Subjects:      Geometry -- Study and teaching.
Control No.:   272431

Author:        Minnick, John Harrison, 1877-
Title:         An investigation of certain abilities fundamental
                  to the study of geometry, by John Harrison Minnick.
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1918.
Description:   vii, 108 p. diagrs. 25 cm.
LC Call No.:   QA461.M7
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1918.
Subjects:      Geometry -- Study and teaching.
Control No.:   8715387

Author:        Mueller, Clara Henrietta.
Title:         Geometric concepts, by Clara H. Mueller.
Published:     New York, J. Wiley & Sons, Inc.; London, Chapman
                  & Hall, Limited, 1931.
Description:   2 p.l., iii-xi, 205 p. illus., pl., diagrs. 19
                  cm.
LC Call No.:   QA461.M8
Dewey No.:     513.07
Subjects:      Geometry -- Study and teaching.
Control No.:   10154489

Author:        National Education Association of the United
                  States. National Committee of Fifteen on Geometry Syllabus.
Title:         Final report of the National Committee of Fifteen
                  on geometry syllabus. July, 1912.
Published:     [Chicago, University of Chicago Press, 1913?]
Description:   54 p. illus., diagrs. 23 cm.
LC Call No.:   QA461.N3
Notes:         At head of title: National Education
                  Association.
               Herbert E. Slaught, chairman.
Subjects:      Geometry -- Outlines, syllabi, etc.
Other authors: Slaught, H. E. (Herbert Ellsworth), 1861-1937.
Control No.:   9169468

Author:        New York (State) University. [from old catalog]
Title:         Syllabus in plane geometry.
Published:     Albany, The University of the state of New York
                  press, 1943.
Description:   15 p. 23 cm.
LC Call No.:   QA461.N4 1943
Subjects:      Geometry, Plane -- Outlines, syllabi, etc. [from
                  old catalog]
Control No.:   10208831

Author:        O'Brien, Katharine E. (Katharine Elizabeth)
                  comp.
Title:         Successful devices in teaching geometry. Edited
                  by Katharine E. O'Brien.
Published:     Portland, Me., J. W. Walch, c1955.
Description:   166 p. illus. 28 cm.
LC Call No.:   QA461.O2
Dewey No.:     513.07
Subjects:      Geometry -- Study and teaching.
Control No.:   7930833

Author:        Perry, Winona M. (Winona Merle), 1890-
Title:         A study in the psychology of learning in
                  geometry, by Winona M. Perry ...
Published:     New York city, Teachers college, Columbia
                  university, 1925.
Description:   4 p.l., 60 p. incl. tables, diagrs. 25 cm.
LC Call No.:   QA461.P4 1925
Notes:         Thesis (Ph. D.)--Columbia university, 1925.
               Vita.
               Published also as Teachers college, Columbia
                  university, Contributions to education, no. 179.
               Bibliography: p. 39-40.
Subjects:      Geometry -- Study and teaching.
Other titles:  Psychology of learning in geometry, A study in
                  the.
Control No.:   746119

Author:        Perry, Winona M. (Winona Merle), 1890-
Title:         A study in the psychology of learning in
                  geometry, by Winona M. Perry ...
Published:     New York city, Teachers college, Columbia
                  university, 1925.
Description:   4 p.l., 59 p. incl. tables, diagrs. 24 cm.
Series:        Teachers college, Columbia university.
                  Contributions to education, no. 179
LC Call No.:   QA461.P4 1925a
Notes:         Published also as thesis (Ph. D.) Columbia
                  university, 1925.
               Bibliography: p. 39-40.
Subjects:      Geometry -- Study and teaching.
Other titles:  Psychology of learning in geometry, A study in
                  the.
Series Entry:  Contributions to education ; no. 179.
Control No.:   1218392

Author:        [Phœbus, Virginia C., Mrs.], [from old catalog]
                  comp.
Title:         Geometry.
Published:     New York, Phillips & Hunt; Cincinnati, Walden &
                  Stowe, 1883.
Description:   16 p. diagr. 19 cm.
LC Call No.:   QA461.P57
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   6793055

Author:        Pickett, Hale Clifford, 1892-
Title:         An analysis of proofs and solutions of exercises
                  used in plane geometry tests by Hale Pickett.
Published:     New York, Teachers College, Columbia University,
                  1938.
Description:   120 p. 22 cm.
Series:        Teachers College, Columbia University.
                  Contributions to education, no. 747
LC Call No.:   QA461.P6 1938a
Dewey No.:     516/.22/76
Notes:         Originally presented as the author's thesis,
                  Columbia.
               Bibliography: p. 117-120.
Subjects:      Geometry, Plane -- Examinations, questions, etc.
Series Entry:  Contributions to education ; no. 747.
Control No.:   9246170

Author:        Pickett, Hale Clifford, 1892- [from old catalog]
Title:         An analysis of proofs and solutions of exercises
                  used in plane geometry tests,
Published:     New York city, Teachers college, Columbia
                  university, 1938.
Description:   p. cm.
LC Call No.:   QA461.P6 1938
Subjects:      Geometry, Plane -- Problems, exercises, etc.
                  [from old catalog]
               Geometry, Plane -- Study and teaching. [from old
                  catalog]
Control No.:   7841219

Author:        Shibli, Jabir, b. 1886.
Title:         Recent developments in the teaching of geometry,
                  by Jabir Shibli ...
Published:     State College, Pa., J. Shibli, 1932.
Description:   viii p., 1 l., 252 p., 1 l. diagrs. 21 cm.
LC Call No.:   QA461.S5 1932
Dewey No.:     513.07
Notes:         Thesis (Ph. D.)--Columbia university, 1932.
               Vita.
               Bibliography: p. 243-247.
Subjects:      Geometry -- Study and teaching.
               Geometry -- History.
Other titles:  Teaching of geometry, Recent developments in.
Control No.:   4526974

Author:        Smith, David Eugene, 1860-1944.
Title:         The teaching of geometry, by David Eugene Smith.
Published:     Boston, New York [etc.] Ginn and Company [c1911]
Description:   v, 339 p. illus., diagrs. 19 cm.
LC Call No.:   QA461.S64
Subjects:      Geometry -- Study and teaching.
Control No.:   7290919

Author:        Smith, Rolland R. (Rolland Ryther), 1894-
Title:         Three major difficulties in the learning of
                  demonstrative geometry, by Rolland R. Smith ...
Published:     [Menasha, Wis., George Banta publishing company,
                  c1940]
Description:   3 p.l., 65 p., 1 l. diagrs. 26 cm.
LC Call No.:   QA461.S66 1940
Dewey No.:     513.0712
Notes:         Thesis (PH. D.)--Columbia university, 1940.
               Vita.
               "The study involved all the pupils taking the
                  first course in demonstrative geometry during the fall of
                  1932 in Classical high school, Springfield,
                  Massachusetts."--p. 2.
               Published also without thesis note.
Subjects:      Geometry, Plane -- Study and teaching.
               Classical High School (Springfield, Mass.)
Other titles:  Demonstrative geometry.
Control No.:   2636148

Author:        Smith, Rolland R. (Rolland Ryther), 1894-
Title:         Three major difficulties in the learning of
                  demonstrative geometry, by Rolland R. Smith.
Published:     New York [Menasha, Wis., Printed by George Banta
                  publishing company] 1940.
Description:   3 p. l., 65 p. diagrs. 27 cm.
LC Call No.:   QA461.S66 1940a
Dewey No.:     513.0712
Notes:         "The study involved all the pupils taking the
                  first course in demonstrative geometry during the fall of
                  1932 in Classical high school, Springfield,
                  Massachusetts."--p. 2.
               Issued also as thesis (Ph. D.) Columbia
                  university.
Subjects:      Geometry, Plane -- Study and teaching.
               Classical High School (Springfield, Mass.)
Other titles:  Demonstrative geomeetry.
Control No.:   5973891

Author:        Stein, Harry L., 1902- [from old catalog]
Title:         Characteristic differences in mathematical traits
                  of good, average, and poor achievers in demonstrative
                  geometry ...
Published:     [n. p., 1943]
Description:   cover-title, [1], 164-168 p. incl. tab. 26 cm.
LC Call No.:   QA461.S8
Subjects:      Geometry -- Study and teaching.
               Mathematical ability -- Testing.
Control No.:   7395704

Author:        Stone, John C. (John Charles), 1867-1940.
Title:         Method in geometry, by John C. Stone ...
Published:     Boston, D.C. Heath & co., 1904.
Description:   40 p. diagrs. 20 cm.
Series:        Heath's mathematical monographs, no. 9
LC Call No.:   QA461.S87
Notes:         "The monograph is a revision of a paper read
                  before the Michigan Schoolmasters' club, in April, 1902."
Subjects:      Geometry -- Study and teaching.
Series Entry:  Heath's mathematical monographs ; no. 9.
Control No.:   2634016

Author:        Touton, Frank C. (Frank Charles), 1880-1936.
Title:         Solving geometric originals, by Frank Charles
                  Touton ...
Published:     New York city, Teachers college, Columbia
                  university, 1924.
Description:   viii, 115 p. incl. tables, diagrs. 25 cm.
LC Call No.:   QA461.T6 1919
Notes:         Thesis (Ph. D.)--Columbia university, 1919.
               Vita.
               Published also as Teachers college, Columbia
                  university, Contributions to education, no. 146.
Subjects:      Geometry. Plane -- Study and teaching.
Control No.:   3580694

Author:        Touton, Frank C. (Frank Charles), 1880-1936.
Title:         Solving geometric originals, by Frank Charles
                  Touton ...
Published:     New York city, Teachers college, Columbia
                  university, 1924.
Description:   viii, 114 p. incl. tables, diagrs. 24 cm.
Series:        Teachers College, Columbia university.
                  Contributions to education, no. 146
LC Call No.:   QA461.T6 1924
Notes:         Published also as thesis (Ph. D.) Columbia
                  University, 1919.
Subjects:      Geometry, Plane -- Study and teaching.
Series Entry:  Contributions to education ; no. 146.
Control No.:   2162415

Author:        Ulmer, Gilbert, 1903- [from old catalog]
Title:         Teaching geometry to cultivate reflective
                  thinking; an experimental study with 1239 high school
                  students,
Published:     [Lawrence, Kan., 1939]
Description:   4 p.l., 116 numb. l., 5 l. incl. tables, forms.
                  28 x 22 cm.
LC Call No.:   QA461.U4
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   9257639

Author:        University of the State of New York. Bureau of
                  Secondary Curriculum Development.
Title:         Mathematics 10; a handbook of resource material
                  to accompany the course of study in mathematics 10.
Published:     Albany, 1962.
Description:   v, 130 p. diagrs. 23 cm.
LC Call No.:   QA461.N37
Notes:         Bibliography: p. 130.
Subjects:      Geometry -- Study and teaching (Secondary)
Control No.:   6097489

Author:        Armas, Juan Ignacio de. [from old catalog]
Title:         Geometría de los niños.
Edition:       (2. ed.)
Published:     Nueva York, N. Ponce de Leon, 1880.
Description:   38, [1] p. diagr. 19 cm.
LC Call No.:   QA462.A72
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   9603155

Author:        Barber, A. W. [from old catalog]
Title:         A manual for the use of forms and solids,
Published:     Chicago, National school furnishing company
                  [1884]
Description:   1 p.l., 20 p. diagr. 19 cm.
LC Call No.:   QA462.B23
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   6793075

Author:        Bellows, Charles Fitzroy, 1832- [from old
                  catalog]
Title:         Geometrical figures,
Published:     Ypsilanti, Commercial steam printing house,
                  1875.
Description:   iv, [5]-71 p. 21 cm.
LC Call No.:   QA462.B44
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   6324939

Author:        Bellows, Charles Fitzroy, 1832- [from old
                  catalog]
Title:         Geometrical figures.
Published:     Ypsilanti, Pattison's steam printing house,
                  1872.
Description:   2 p. l., 40 p. 22 cm.
LC Call No.:   QA462.B43
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Other authors: YA Pamphlet Collection (Library of Congress) DLC
                  [from old catalog]
Control No.:   8666424

Author:        Berkhan, Gustav Waldemar, 1882-1914.
Title:         Aus dem geometrischen Anfangsunterricht / von
                  Gustav Waldemar Berkhan.
Published:     Hamburg : Lütcke & Wulff, 1911.
Description:   30 p., 1 leaf : ill. ; 24 cm.
LC Call No.:   QA462.B5
Notes:         Programm--Realschule in Eppendorf zu Hamburg.
Subjects:      Geometry -- Study and teaching.
Other authors: Hamburg. Realschule in Eppendorf.
Control No.:   10102064

Author:        Bevis, J. R. [from old catalog]
Title:         Concrete geometry by the inductive method ...
Published:     Boston, Philadelphia [etc.] J. E. Potter and
                  company, 1896.
Description:   viii, 158 p. diagr. 19 cm.
LC Call No.:   QA462.B57
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   8198276

Author:        [Boyden, Albert G.] [from old catalog]
Title:         Analysis of elementary geometry. Outline of
                  topics ...
Published:     [Boston, Wright & Potter, printers, c1875]
Description:   p. cm.
LC Call No.:   QA462.B78
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   5857056

Author:        Breslich, Ernst R. (Ernst Rudolph), 1874-
Title:         Excursion in mathematics, by Ernst R. Breslich
                  ...
Published:     Chicago, The Orthovis company, 1938.
Description:   4 p. l., 47, [1] p. incl. front., illus., diagrs.
                  23 x 21 cm.
LC Call No.:   QA462.B8
Dewey No.:     513
Notes:         Two ortho-scopes in pocket mounted on
                  lining-paper.
               "The book has developed from experiments devised
                  to train pupils in spatial imagination. It aims to supplement
                  and strengthen the teaching of geometry in the secondary
                  school from the seventh grade on."--Author's note.
Subjects:      Geometry, Solid.
Control No.:   8307437

Author:        Breslich, Ernst Rudolph, 1874- [from old
                  catalog]
Title:         Diagrams in three dimensions for solid geometry
Published:     Chicago, The Orthovis company [c1936]
Description:   1 p. l., 15 diagr. 24 x 22 cm.
LC Call No.:   QA462.B787
Subjects:      Geometry, Solid. [from old catalog]
Control No.:   6439431

Author:        Camargo, Ricardo. [from old catalog]
Title:         Geometria experimental práctico-razonada,
Published:     Montevideo, Dornaleche y Reyes, 1889.
Description:   1 p. l., 86, [1] p. illus. 18 cm.
LC Call No.:   QA462.C17
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   7732816

Author:        Campbell, William T. (William Taylor)
Title:         Observational geometry, by William T. Campbell
                  ... With an introduction by Andrew W. Phillips ... and over
                  300 illustrations and diagrams.
Published:     New York, London, Harper & brothers, 1899.
Description:   ix p., 2 l., 240 p. illus., diagrs. 21 cm.
Series:        Phillips-Loomis mathematical series
LC Call No.:   QA462.C19
Dewey No.:     513
Subjects:      Geometry -- Study and teaching.
Control No.:   275638

Author:        Cleveland Public Schools. Division of
                  Mathematics.
Title:         Teachers' guide, ninth grade plane and solid
                  geometry for the academically talented. Prepared by Cleveland
                  Public Schools, Division of Mathematics in cooperation with
                  the Ohio Dept. of Education under the direction of R.A. Horn,
                  director, Division of Special Education.
Published:     Columbus, 1963.
Description:   iv, 273 p. illus. 29 cm.
LC Call No.:   QA462.C55
Notes:         On cover: Issued by E.E. Holt, superintendent of
                  public instruction.  Columbus, Ohio.
               Bibliography: p. [269]-273.
Subjects:      Geometry -- Study and teaching (Secondary)
Other authors: Ohio. Dept. of Education.
Control No.:   10330762

Author:        Darley, George, 1795-1846. [from old catalog]
Title:         The geometrical companion,
Edition:       2d ed.
Published:     London, Printed for Taylor and Walton, 1841.
Description:   viii, 161, [1] p. diagr. 18 cm.
LC Call No.:   QA462.D22
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   5857280

Author:        Dodd, A[rthur] A., 1857- [from old catalog]
Title:         Plane geometry (first half); inductive method.
Published:     Kansas City, Mo., Press of Hudson-Kimberly
                  publishing co., 1898.
Description:   62 p. diagrs. 19 cm.
LC Call No.:   QA462.D63
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Other authors: Chace, B. Thomas, 1858- [from old catalog]
Control No.:   8657282

Author:        Failor, Isaac Newton, 1851-
Title:         Inventional geometry, by Isaac Newton Failor ...
Published:     New York, The Century co., 1904.
Description:   viii, 83 p. diagrs. 20 cm.
LC Call No.:   QA462.F16
Subjects:      Geometry -- Study and teaching.
Control No.:   2633976

Author:        Fowler, C[harles] W[esley], 1858- [from old
                  catalog]
Title:         Inductive geometry;
Edition:       3d ed.
Published:     Louisville, Ky., The author, 1905.
Description:   viii, 52 p. diagrs. 18 x 14 cm.
LC Call No.:   QA462.F79
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   9141694

Author:        Fowler, Charles Wesley, 1858- [from old catalog]
Title:         Inductive geometry.
Published:     Mt. Sterling, Ky., The author, 1894.
Description:   1 p.l., x, 128 p. diagrs. 13 cm.
LC Call No.:   QA462.F78
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   9134649

Author:        Giffin, William Milford, 1850- [from old
                  catalog]
Title:         Grammar school geometry and methods in
                  arithmetic,
Published:     Chicago, The author, c1897.
Description:   2 p.l., 3-26, 40, [2] p. diagrs. 22 cm.
LC Call No.:   QA462.G45
Subjects:      Geometry. [from old catalog]
               Arithmetic -- Study and teaching.
Control No.:   10071372

Author:        Hailmann, W. N. (William Nicholas), 1836-1920.
Title:         Constructive form work; an introduction to
                  geometry for grammar grades, by William N. Hailmann.
Published:     Boston, Mass., C. C. Birchard & co., 1901.
Description:   ix, 60 p. front., illus., col. pl. 20 cm.
LC Call No.:   QA462.H15
Notes:         Frontispiece duplicated in colors.
Subjects:      Geometry -- Study and teaching -- Methods.
Control No.:   7723907

Author:        Hanus, Paul H. (Paul Henry), b. 1855.
Title:         Geometry in the grammar school. An essay ... by
                  Paul H. Hanus.
Published:     Boston, D. C. Heath & company, 1893.
Description:   iv, 52 p. diagr. 19 cm.
LC Call No.:   QA462.H25
Subjects:      Geometry -- Study and teaching.
Control No.:   8198100

Author:        Hertel, Franz. [from old catalog]
Title:         Die arbeitsmethode im unterricht der
                  formenlehre.
Published:     Prag [etc.] A. Haase [c1913]
Description:   p. cm.
LC Call No.:   QA462.H4
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
               Geometrical drawing. [from old catalog]
Control No.:   8236871

Author:        Hill, Thomas, 1818-1891.
Title:         First lessons in geometry / by Thomas  Hill.
Published:     Boston : Hickling, Swan, and Brown, 1855.
Description:   144 p. : ill. ; 17 cm.
LC Call No.:   QA462.H64
Subjects:      Geometry -- Study and teaching.
Control No.:   8666562

Author:        Hill, Thomas, 1818-1891.
Title:         Puzzles to teach geometry : in seventeen cards,
                  numbered from the first to the seventeenth inclusive.
Published:     Boston : Wm. Crosby & H.P. Nichols, c1848.
Description:   [1], 17 cards : ill. ; 24 cm.
LC Call No.:   QA462.H655 1848
Notes:         18 cards (the first card is instructions for
                  using 1-17) in a slipcase, accompanied by 5 triangular blocks
                  in two sizes.
Subjects:      Geometry -- Juvenile literature.
Other authors: Marian S. Carson Collection (Library of Congress)
                  DLC
Control No.:   3081172

Author:        Hill, Thomas, 1818-1891.
Title:         A second book in geometry. By Thomas Hill ...
Published:     Boston, Brewer and Tileston, 1863.
Description:   136 p. pl. diagr. 20 cm.
LC Call No.:   QA462.H66
Subjects:      Geometry -- Study and teaching.
Control No.:   2633937

Author:        Hill, Thomas, 1818-1891. [from old catalog]
Title:         First lessons in geometry,
Edition:       Rev. ed.
Published:     Boston, W. Ware and company, 1878.
Description:   vi, [7]-160 p. diagr. 17 cm.
LC Call No.:   QA462.H65
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   7261582

Author:        Holbrook, Josiah, 1788-1854.
Title:         First lessons in geometry, for the use of
                  families, schools, and lyceums. By Josiah Holbrook.
Published:     Boston, Brown and Pierce ; New York, N. B. Holmes
                  ; [etc., etc.] 1833.
Description:   v, [6]-52 p. diagr. 16 cm.
LC Call No.:   QA462.H72
Subjects:      Geometry -- Study and teaching.
Control No.:   2633928

Author:        Holbrook, Josiah. [from old catalog]
Title:         First lessons in geometry, for the use of schools
                  and families.
Published:     New York, Calkins & Paine, 1850.
Description:   1p. l., iii, [6]-52 p. diagr. 15 cm.
LC Call No.:   QA462.H73
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   7261362

Author:        Hornbrook, Adelia Roberts.
Title:         Concrete geometry for beginners, by A. R.
                  Hornbrook.
Published:     New York, Cincinnati, American Book Company
                  [c1895]
Description:   201 p. pl., diagr. 20 cm.
LC Call No.:   QA462.H81
Subjects:      Geometry -- Study and teaching.
Control No.:   5857190

Author:        Hunt, Ephraim.
Title:         Geometry for grammar schools. By E. Hunt.
Published:     Boston, D. C. Heath & Co., 1894.
Description:   iv, 99 p. pl. 19 cm.
LC Call No.:   QA462.H93
Subjects:      Geometry -- Study and teaching (Elementary).
Control No.:   9134784

Author:        Lane, Ruth Onetta, 1892- [from old catalog]
Title:         The use of graded originals in plane geometry,
Published:     [New York, 1940]
Description:   p. 291-300. 26 cm.
LC Call No.:   QA462.L25 1940
Subjects:      Geometry, Plane -- Study and teaching. [from old
                  catalog]
               Ability -- Testing. [from old catalog]
Other titles:  Graded originals in plane geometry.
Control No.:   7849733

Author:        Lowell, Anna C. (Anna Cabot), 1811-1874.
Title:         Edward's first lessons in geometry / by the
                  Author of "Theory of Teaching" and "Edward's first lessons in
                  grammar."
Published:     Boston : William D. Ticknor, 1844 (Boston :
                  Freeman and Bolles)
Description:   viii, 150 p. : ill. ; 14 cm.
LC Call No.:   QA462.L88
Notes:         Tryon and Charvat, A56a
Subjects:      Geometry -- Study and teaching -- Methods.
Other authors: Niles, Emily, former owner.
               Chamberlain, Edward, former owner.
Control No.:   7729693

Author:        Lyman, Elmer A. (Elmer Adelbert), 1861-
Title:         Plane and solid geometry by correspondence, by
                  Prin. E.A. Lyman, A. B. and J.C. Stone ... based upon Well's
                  Essentials of geometry.
Published:     Chicago, Interstate school of correspondence
                  [1902]
Description:   1 p. l., 94 p. 20 cm.
LC Call No.:   QA462.L98
Subjects:      Geometry -- Study and teaching.
Other authors: Stone, John C. (John Charles), 1867-1940.
               Wells, Webster, 1851-1916. Essentials of
                  geometry.
Other authors: Interstate School of Correspondence (Chicago)
Control No.:   9599694

Author:        Macdonald, James Wallace, 1843- [from old
                  catalog]
Title:         Principles of plane geometry,
Published:     Boston, Allyn and Bacon, 1889.
Description:   vi, 63 p. 18 cm.
LC Call No.:   QA462.M13
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   6793210

Author:        Marks, Bernhard. [from old catalog]
Title:         Mark's First lessons in geometry.
Published:     New York, Ivison, Phinney, Blakeman, & co.;
                  Philadelphia, J. B. Lippincott & co.; [etc., etc.] 1869.
Description:   157, [1] p. diagrs. 20 cm.
LC Call No.:   QA462.M34 1869a
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   9603292

Author:        Marks, Bernhard. [from old catalog]
Title:         Marks' First lessons in geometry, objectively
                  presented ...
Published:     New York, Ivison, Phinney, Blakeman, & co.;
                  Philadelphia, J. B. Lippincott & co.; [etc., etc.] 1869.
Description:   157, [1] p. diagrs. 20 cm.
LC Call No.:   QA462.M34 1869
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   10071580

Author:        Menger, Karl, 1902-
Title:         You will like geometry : a guide book for the
                  Illinois Institute of Technology geometry exhibition at the
                  Museum of Science and Industry / by Karl Menger.
Published:     Chicago : Karl Menger, c1952.
Description:   36 p. : ill. ; 23 cm.
LC Call No.:   QA462.M57
Subjects:      Geometry -- Exhibitions.
Other authors: Illinois Institute of Technology.
Control No.:   8843734

Author:        Meyers, William J. (William John), 1869-
Title:         An inductive manual of the straight line and the
                  circle, with many exercises, by William J. Meyers ...
Published:     Fort Collins, Colo., W.J. Meyers, 1896.
Description:   xvii, 113 p. illus. 19 cm.
LC Call No.:   QA462.M61
Subjects:      Geometry -- Study and teaching.
               Geometry -- Problems, exercises, etc.
Control No.:   2633938

Author:        Morsell, W[illiam] F. C. [from old catalog]
Title:         Elementary form, or, Outlines of concrete
                  geometry, a key to the sequence of figure.
Published:     Springfield, Mass., M. Bradley co., 1897.
Description:   97 p. col. pl., diagr. 24 cm.
LC Call No.:   QA462.M88
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   6325068

Author:        Nichols, Edgar H. (Edgar Hamilton)
Title:         Elementary and constructional geometry, by Edgar
                  H. Nichols ...
Published:     New York, London [etc.] Longmans, Green and
                  company, 1896.
Description:   vii p., 1 l., 138, [2] p. diagr. 19 cm.
LC Call No.:   QA462.N61
Subjects:      Geometry -- Study and teaching.
Control No.:   3106786

Author:        Nichols, Edgar H[amilton] [from old catalog]
Title:         Elementary and constuctional geometry
Published:     New York, London [etc.] Longmans, Green and
                  company, 1896.
Description:   vii p., 1 l., 138, [2] p. diagr. 19 cm.
LC Call No.:   QA462.N61
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   8666985

Author:        Noetling, William.
Title:         Elements of constructive geometry, inductively
                  presented, by William Noetling ... From the German of K.H.
                  Stöcker.
Published:     New York, Boston [etc.] Silver, Burdett and
                  company, 1897.
Description:   62 p. 19 cm.
LC Call No.:   QA462.N77
Subjects:      Geometry -- Study and teaching.
Control No.:   1689173

Author:        Pereira, João Felix. [from old catalog]
Title:         Rudimentos de geometria; destinados,
                  principalmente, para os alumnos, que frequentão as aulas de
                  geographia, chronologia e historia.
Edition:       3. ed.
Published:     Lisboa, A. J. Germano, 1867.
Description:   1 p.l., 36 p. fold. pl. 16 cm.
LC Call No.:   QA462.P43
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   5857191

Author:        Philadelphia. Public Schools. Curriculum Office.
                  Senior High School Mathematics Committee. [from old catalog]
Title:         A guide to the study of plane geometry.
Published:     [Philadelphia] 1951 [i.e. 1952]
Description:   102 p. illus. 23 cm.
LC Call No.:   QA462.P5 1952
Subjects:      Geometry, Plane -- Outlines, syllabi, etc. [from
                  old catalog]
Other authors: Philadelphia School District. Board of Public
                  Education. [from old catalog]
Control No.:   6971954

Author:        Ritchie, William, 1790-1837. [from old catalog]
Title:         Principles of geometry;
Edition:       2d ed.
Published:     London, Printed for Taylor and Walton, 1837.
Description:   1 p.l., [v]-xi, 151 p. diagr. 18 cm.
LC Call No.:   QA462.R61
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   9134785

Author:        Ross, W. W.
Title:         Mensuration taught objectively, with lessons on
                  form. By W.W. Ross ... Manual for the use of the author's
                  Dissected surface forms and Geometrical solids.
Published:     Fremont, Ohio, [c1891]
Description:   1 p.l., [2]-28 p. 23 cm.
LC Call No.:   QA462.R82
Notes:         Also available in digital form on the Library of
                  Congress Web site.
Subjects:      Mensuration.
               Geometry -- Study and teaching.
Control No.:   10071581
Access:        PDF
    Location:  http://hdl.loc.gov/loc.gdc/scd0001.20050112001me.1
Access:        Page view
    Location:  http://hdl.loc.gov/loc.gdc/scd0001.20050112001me.2


Author:        Scharrelmann, Heinrich, 1871- [from old catalog]
Title:         Produktive geometrie,
Published:     Hamburg, A. Janssen, 1914.
Description:   108 p. illus., diagrs. 21 cm.
LC Call No.:   QA462.S33
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   5896449

Author:        Schmidt, Bruno. [from old catalog]
Title:         Formenkundliche übungen, material und
                  arbeitsweisen,
Published:     [n. p.] c1931
Description:   l. v. cm.
LC Call No.:   QA462.S35
Control No.:   8605736

Author:        Schoch, William.
Title:         Introduction to geometry; a manual of exercises
                  for beginners, by William Schoch.
Published:     Boston, Allyn and Bacon, 1904.
Description:   v, 137 p. illus., diagrs. 19 cm.
LC Call No.:   QA462.S36
Subjects:      Geometry -- Study and teaching.
Control No.:   6795513

Author:        Shaw, Edward R. (Edward Richard), 1855-1903.
Title:         Inventional geometry,
Published:     New York, D. Appleton and company, c1889.
Description:   11 p. diagr. 24 cm.
LC Call No.:   QA462.S53
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   9603293

Author:        Speer, William W.
Title:         Form lessons, to prepare for and to accompany the
                  study of number. By W.W.Speer.
Published:     [Chicago, Donohue & Henneberry, printers, c1888]
Description:   77 p. diagrs. 21 cm.
Series:        C.C.N.S.series
LC Call No.:   QA462.S72
Subjects:      Geometry -- Study and teaching -- Methods.
Control No.:   8205322

Author:        Spencer, William George
Title:         Inventional geometry; a series of problems,
                  intended to familiarize the pupil with geometrical
                  conceptions, and to exercise his inventive faculty. By
                  William George Spencer. With a prefatory note by Herbert
                  Spencer.
Published:     New York, D. Appleton and company, 1877.
Description:   97 p. 16 cm.
Series:        Science primers
LC Call No.:   QA462.S74
Subjects:      Geometry -- Study and teaching.
Other authors: Spencer, Herbert, 1820-1903.
Control No.:   2161089

Author:        Sundara Rao, T. (Tandalam), b. 1853.
Title:         T. Sundara Row's Geometric exercises in paper
                  folding; ed. and rev. by Wooster Woodruff Beman ... and David
                  Eugene Smith ... with 87 illustrations.
Published:     Chicago, The Open court pub. company; [etc.,
                  etc.] 1901.
Description:   xiv, 148 p. illus., diagrs. 20 cm.
LC Call No.:   QA462.S8 1901
Subjects:      Geometry -- Study and teaching.
               Paper work.
Control No.:   4052087

Author:        Sundara Rao, Tandalam, 1853- [from old catalog]
Title:         Geometrical exercises in paper folding.
Published:     Madras, Printed by Addison & co., 1893.
Description:   3 p. l., vi, 114 p. col. diagrs. 20 cm.
LC Call No.:   QA462.S8 1893
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
               Paper work. [from old catalog]
Control No.:   6788787

Author:        Treutlein, P. (Peter), 1845-1912.
Title:         Der geometrische anschauungsunterricht als
                  unterstufe eines zweistufigen geometrischen unterrichtes an
                  unseren höheren schulen, von P. Treutlein ... mit einem
                  einführungswort von F. Klein und mit 38 tafeln und 87
                  abbildungen im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1911.
Description:   x, 216 p. illus., diagrs. 23 cm.
LC Call No.:   QA462.T8
ISBN:          DM5.00
Notes:         "Figurenteil" (40 p.) in pocket on back cover.
               "Verzeichnis von schriften über den
                  geometrischen anschauungsunterricht": p [209]-216.
Subjects:      Geometry -- Study and teaching (Secondary) --
                  Germany.
Control No.:   1217747

Author:        Turney, Billy Lawrence, 1929- [from old catalog]
Title:         Geometry teaching aids you can make.
Published:     Portland, Me., J. W. Walch, c1958.
Description:   176 p. illus. 28 cm.
LC Call No.:   QA462.T85
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   7015228

Author:        Viña, N[icasio] L[ugo] [from old catalog]
Title:         Geometría explicativa;
Published:     St. Louis, Mo., Spanish-American educational co.,
                  1895.
Description:   41 p. 19 cm.
LC Call No.:   QA462.V77
Subjects:      Geometry -- Study and teaching -- Methods. [from
                  old catalog]
Control No.:   6793211

Author:        Viña, Nicasio Lugo. [from old catalog]
Title:         Geometría explicativa; clave de los cuadros
                  murales de geometría, por Nicasio Lugo Viña.
Published:     San Francisco, The History company, 1891.
Description:   41 p. 19 cm.
LC Call No.:   QA462.V76
Subjects:      Geometry -- Study and teaching.
Control No.:   12925711

Author:        Waite, Edward Broughton, 1873- [from old
                  catalog]
Title:         Plane geometry,
Published:     Chicago, American school [c1923]
Description:   3 p.l., 52 p. 21 cm.
LC Call No.:   QA462.W3
Subjects:      Geometry, Plane -- Study and teaching. [from old
                  catalog]
Control No.:   9664015

Author:        Wellington, Isaac M.
Title:         A geometry. By Isaac M. Wellington ...
Published:     Detroit, 1876.
Description:   1 p. l., vii, [1], 102 p. 20 cm.
LC Call No.:   QA462.W45
Subjects:      Geometry -- Study and teaching -- Methods.
Control No.:   8666563

Author:        Wentworth, G. A. (George Albert), 1835-1906.
Title:         First steps in geometry, by G.A. Wentworth and
                  G.A. Hill.
Published:     Boston, Ginn & company, 1901.
Description:   iv, 156 p. illus., diagrs. 20 cm.
LC Call No.:   QA462.W47
Subjects:      Geometry.
Other authors: Hill, G. A. (George Anthony), 1842-1916.
Control No.:   8660283

Author:        Wilkinson, Ely Wood, 1863- [from old catalog]
Title:         Game of constructive geometry.
Published:     Cincinnati, The Cincinnati game company, c1903.
Description:   1 p.l., 16 col. 28 col. pl. 9 x 15 cm.
LC Call No.:   QA462.W68
Subjects:      Constructive geometry (Game) [from old catalog]
Control No.:   7266096

Author:        Baker, Arthur Latham, 1853- [from old catalog]
Title:         The art of geometry;
Published:     Boston, Chicago, Sibley & company [c1905]
Description:   p. cm.
LC Call No.:   QA463.B18
Subjects:      Geometry -- Laboratory manuals. [from old
                  catalog]
Control No.:   9610161

Author:        Hjelmslev, Johannes, 1873-
Title:         Geometrische experimente, von dr. Johannes
                  Hjelmslev; aus dem dänischen übersetzt von Albert Rohrberg.
                  Mit 56 figuren im text.
Published:     Leipzig, Berlin; B. G. Teubner, 1915.
Description:   68, [2] p. diagrs. 26 cm.
Series:        Beihefte zur Zeitschrift für mathematischen und
                  naturwissenschaftlichen unterricht, hrsg. von W. Lietzmann
                  und E. Grimsehl. 5
LC Call No.:   QA463.H5
Notes:         "Literaturverzeichnis": 1 p. following p. 68.
Subjects:      Geometry -- Laboratory manuals.
Other authors: Rohrberg, Albert, 1887- tr.
Control No.:   9644546

Author:        Plant, L[ouis] C[lark] [from old catalog]
Title:         Laboratory experiments in plane geometry,
Published:     [Peoria? Ill.] 1903.
Description:   70 l. diagrs. 19 x 16 cm.
LC Call No.:   QA463.P71
Subjects:      Geometry -- Laboratory manuals. [from old
                  catalog]
Control No.:   7261278

Author:        Vuibert, Henry, 1857-
Title:         Les anaglyphes géométriques.
Edition:       3. éd.
Published:     Paris : Vuibert, [c1912]
Description:   32 p. : diagrs. (part col.) ; 26 cm.
LC Call No.:   QA463.V7
Subjects:      Geometry -- Laboratory manuals.
Control No.:   8699593

Title:         Pr¯otoleia t¯on t¯es kata physin metr¯es¯eos
                  hedrai¯on synteleest¯on kai vase¯on.
Published:     [1907?]
Description:   14 fold. mounted phot. 20 x 15 cm.
LC Call No.:   QA464.P8
Notes:         Romanized.
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   9630676

Author:        Angell, Oliver. [from old catalog]
Title:         Elements of mathematics.
Published:     Providence, A. S. Beckwith, 1829.
Description:   1 p. l., 5, [9]-94 p. diagr. 18 cm.
LC Call No.:   QA464.A58
Subjects:      Geometrical drawing. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   6324923

Author:        Cochrane, Richard. [from old catalog]
Title:         A comprehensive system of practical geometry.
Published:     Baltimore, R. Cochrane, 1857.
Description:   xi, [13]-265 p. front., diagr. 24 cm.
LC Call No.:   QA464.C66
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   5857036

Author:        Cochrane, Richard. [from old catalog]
Title:         A comprehensive system of practical geometry.
Edition:       2d ed.
Published:     Baltimore, R. Cochrane, 1857.
Description:   xi, [13]-227 p. front., diagrs. 21 cm.
LC Call No.:   QA464.C67
Subjects:      Geometrical drawing.
Other authors: Cochrane, John, [from old catalog] joint author.
Control No.:   6792146


Author:        Corson, Benjamin I. [from old catalog]
Title:         Layout geometry; a course in plane geometry for
                  draftsmen and layout mechanics,
Published:     [Merchantville, N.J., Camden county vocational
                  school] c1940.
Description:   1 p.l., 92 numb. l., 9 l. diagrs. 27 x 21 cm.
LC Call No.:   QA464.C75
Subjects:      Geometrical drawing. [from old catalog]
Other authors: Merchantville, N.J. Camden county vocational
                  school. [from old catalog]
Control No.:   6450479

Author:        Cyriaque de Mangin, Clément, d. 1642. [from old
                  catalog]
Title:         L'vsage dv compas de proportion,
Edition:       5. éd., reueuë, corr. & de beaucoup augm.
Published:     Roven, I. Bovlley, 1637.
Description:   148 p. illus. 17 cm.
LC Call No.:   QA464.C9 1637
Subjects:      Compass (Mathematical instruments) [from old
                  catalog]
               Geometry -- Early works to 1800. [from old
                  catalog]
Control No.:   8968444

Author:        Davies, Charles, 1798-1876. [from old catalog]
Title:         First lessons in geometry:
Published:     Hartford, A. S. Barnes & co.; 1839.
Description:   xiv, [15]-252 p. diagr. 20 cm.
LC Call No.:   QA464.D24
Subjects:      Geometrical drawing. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   7261424

Author:        Davies, Charles, 1798-1876. [from old catalog]
Title:         Practical geometry: with selected applications in
                  mensuration, in artificers' work and mechanics.
Published:     Philadelphia, A. S. Barnes and co., 1842.
Description:   xiv, [15]-252 p. diagr. 20 cm.
LC Call No.:   QA464.D25
Subjects:      Geometrical drawing. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   9134628

Author:        Fonseca Lessa, José Antonio da, 1830-1887. [from
                  old catalog]
Title:         Compendio de desenho geometrico,
Published:     Rio de Janeiro, Pinheiro & ca, 1871.
Description:   vi, [7]-230, iii p. fold. pl., tab., diagr. 19
                  cm.
LC Call No.:   QA464.F67
Subjects:      Geometrical drawing. [from old catalog]
               Architecture. [from old catalog]
Control No.:   7729529

Author:        Gama, Mucio. [from old catalog]
Title:         Principios de geometria elemental y método de
                  resolver con el auxilio de la regla y el compás las
                  operaciones mas necesarias para los artistas y artesanos.
Edition:       2. ed.
Published:     México, F. Diaz de Leon y S. White, 1870.
Description:   68 p. 6 fold. pl. 16 cm.
LC Call No.:   QA464.G18
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   10071428

Author:        Greenhalgh, Richard. [from old catalog]
Title:         Building geometry,
Published:     London, New York [etc.] Sir I. Pitman & sons,
                  ltd., 1931.
Description:   vii, 172 p. illus., fold. pl., diagrs. 19 cm.
LC Call No.:   QA464.G7
Subjects:      Geometrical drawing. [from old catalog]
               Architectural drawing. [from old catalog]
Control No.:   8753704

Author:        Harris, Robert.
Title:         Note-book on plane geometrical drawing : with a
                  chapter on scales, and an introduction to graphic statics /
                  by Robert Harris.
Edition:       New ed., rev. and enl.
Published:     London : George Bell & Sons, 1895.
Description:   230, 48 p. : ill. ; 19 cm.
LC Call No.:   QA464.H37x 1895
Notes:         Cover title: Plane geometrical drawing.
               Publisher's advertisements: 48 p. at end.
Subjects:      Geometrical drawing.
Other titles:  Plane geometrical drawing.
Control No.:   2873543

Author:        Harris, Robert. [from old catalog]
Title:         Note-book on plane geometrical drawing.
Published:     London, Hamilton, Adams & co., 1886.
Description:   187 p. diagrs. 19 cm.
LC Call No.:   QA464.H3
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   6008813

Author:        Hedley, W. H. (William Henry)
Title:         The basis of sheet metal drafting, by W.H. Hedley
                  ...
Published:     London, New York [etc.] Longmans, Green and co.
                  [1945]
Description:   viii, 118 p. illus., diagrs. 22 cm.
LC Call No.:   QA464.H38
Dewey No.:     744.4
Notes:         "First published 1945."
Subjects:      Geometrical drawing.
               Geometry, Descriptive.
               Sheet-metal work -- Patternmaking.
Other titles:  Sheet metal drafting.
Control No.:   4054935

Author:        Hedrick, Earle Raymond, 1876- [from old catalog]
Title:         Constructive geometry;
Published:     New York, The Macmillan company, 1916.
Description:   vi p., 1 l., 75 p. illus., diagrs. 27 cm.
LC Call No.:   QA464.H4
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   8709325

Author:        International Correspondence Schools
Title:         Geometrical drawing, by I.C.S. staff.
Published:     Scranton, Pa., International textbook company
                  [c1935]
Description:   v, 74, 50, 69 p. illus., diagrs. (part fold.) 20
                  cm.
Series:        [International textbook company. Bluebooks] 163C
LC Call No.:   QA464.I6 1935a
Dewey No.:     744
Notes:         Geometrical drawing.--Elements of projection
                  drawing.--Drawings for welded parts.
Subjects:      Geometrical drawing.
               Projection.
               Welding.
Control No.:   10174987

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Geometrial drawing,
Published:     [Scranton, c1942]
Description:   cover-title, 104 p. illus., diagrs. 19 cm.
LC Call No.:   QA464.I63 1942
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   6922201

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Geometrical drawing,
Published:     [Scranton, 1935]
Description:   cover-title, 74 p. diagrs. 19 cm.
LC Call No.:   QA464.I63
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   10202583

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Instruction paper.
Edition:       1st ed.
Published:     [n.p.] [c1899]
Description:   1 v. cm.
LC Call No.:   QA464.I61
Control No.:   10012743

Author:        Krogh, G[erhard] C[hristopher], 1839- [from old
                  catalog]
Title:         Praktisk geometri indeholdende plageometri og
                  stereometri.
Published:     Bergen, F. Beyers, 1869.
Description:   85, [1] p., 1 l. diagr. 21 cm.
LC Call No.:   QA464.K93
Subjects:      Geometrical drawing. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   9603137

Author:        Le Clerc, Sébastien, 1637-1714.
Title:         Traité de géométrie théorique et pratique à
                  l'usage des artistes.
Edition:       Nouv. ed.
Published:     Paris, Chez C.A. Jombert, 1774.
Description:   xvi, 231 62 fold. plates. 20 cm.
LC Call No.:   QA464.L46
Notes:         Title vignette; head and tail pieces; vignettes
                  by Cochin, Cochin fils, and Chedel.
               "Abrégé de la vie de Sebastien Le Clerc": p.
                  [ix]-xvi.
               "Cet ouvrage parut pour la première fois en 1669
                  sous le titre de Pratique de la géométrie sur le papier,
                  etc."--Quérard.
Subjects:      Le Clerc, Sébastien, 1637-1714.
               Geometrical drawing
Control No.:   9604623

Author:        Le Clerc, Sébastien, 1637-1714. [from old
                  catalog]
Uniform Title: Pratique de la géometrie sur le papier et sur le
                  terrain. German and French. [from old catalog]
Title:         Neue Ubung der Feldmess-Kunst; so wol auff dem
                  Papier als auff dem Feld.
Published:     Berne, Dans l'imprimerie de leurs Excellences,
                  par A. Huguenet, 1699.
Description:   187 p. illus. 17 cm.
LC Call No.:   QA464.L465 (Rare Bk. Coll.)
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   6062086

Author:        Le Clerc, Sébastien, 1637-1714. [from old
                  catalog]
Uniform Title: Pratique de la géométrie sur le papier et sur
                  le terrain. English. [from old catalog]
Title:         Practical geometry;
Edition:       4th ed.
Published:     London, T. Bowles and J. Bowles, 1742.
Description:   1 p.l., 185, [6] p. illus., diagrs. 16 cm.
LC Call No.:   QA464.L462 (Rare bk. Coll.)
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   8344883

Author:        Lilley, Henry Thomas, 1859- [from old catalog]
Title:         Geometrical drawing: for army candidates.
Published:     London, New York, Cassell [1886]
Description:   x, 54 p. diagrs. 19 cm.
LC Call No.:   QA464.L52
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   9760500

Author:        Morris, I. Hammond. [from old catalog]
Title:         Geometrical drawing for art students,
Published:     London, New York [etc.] Longmans, Green and co.
                  [1938]
Description:   4 p. l., 228 p. illus., diagrs. 19 cm.
LC Call No.:   QA464.M7 1938
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   5972194

Author:        Motta, Theodoro da, 1833-1894. [from old
                  catalog]
Title:         Compendio de desenho linear para uso dos alumnos
                  dos lyceus nacionaes,
Published:     Lisboa, Typographia da viuva Sousa Neves, 1884.
Description:   3 p. l., 105 p. and atlas of 2 p. l., 29 double
                  pl. 26 cm.
LC Call No.:   QA464.M8
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   8788916

Author:        Pasley, C[harles] W[illiam], Sir, 1780-1861.
                  [from old catalog]
Title:         A complete course of practical geometry,
Edition:       2d ed.
Published:     London, T. Egerton, 1822.
Description:   2 p. l., xlvii, 608 p. diagr. 22 cm.
LC Call No.:   QA464.P28
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   6793056

Author:        Paynter, J. E.
Title:         Practical geometry for builders and architects,
                  by J.E. Paynter ...
Published:     London, Chapman & Hall, ltd., 1921.
Description:   xii, 409, [1] p. diagrs. 23 cm.
Series:        The directly-useful (D.U.) technical series
LC Call No.:   QA464.P3
Subjects:      Geometrical drawing.
               Mechanical drawing.
Control No.:   1218240

Author:        Pease, W[illiam] [from old catalog]
Title:         A course of practical geometry.
Edition:       2d ed.
Published:     London, Simpkin & Marshall [etc., 1846]
Description:   76 p. diagr. 18 cm.
LC Call No.:   QA464.P36
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   6324924

Author:        Phillips, George, 1804-1872.
Title:         A brief treatise on the use and construction of a
                  case of instruments, for the use of schools.
Edition:       2d ed.
Published:     London, Printed for J. Souter, 1831.
Description:   58 p. diagrs. on 2 fold. pl. 18 cm.
LC Call No.:   QA464.P55
Subjects:      Geometrical drawing. [from old catalog]
               Drawing instruments. [from old catalog]
Control No.:   8674667

Author:        Pomodoro, Giovanni.
Title:         Geometria prattica : tratta dagl'Elementi
                  d'Euclide et altri auttori / da Giouanni Pomodoro ... ;
                  descritta et dichiarata da Giouanni Scala ... ; nella quale
                  si vede in 50 tauole di rame scolpito tutto quello che ad un
                  buon giometra s'appartiene di sapere et porre in uso ; opera
                  non meno vtile che necessaria, a'misuratori di terreni, di
                  fabriche, et altri simmili, ma'in'oltre ancora a, geografi,
                  cosmografi, architetti ciuile, et milittari, a'bombardieri,
                  soldati priuati, a'capitani, mastri di campo, et a'qual si
                  voglia altra persona virtuosa.
Published:     [Rome] : Apresso Stefano de Paulini in Roma,
                  1599.
Description:   [116] p. (first leaf blank) : ill. (engravings) ;
                  35 cm. (fol.)
LC Call No.:   QA464.P66 1599
Notes:         Signatures: pip4s(-pi4) A-Mp4s Np6s chi1.
               NUC pre-1956 NP 0471005
               Register at end of text.
               LC copy has bookseller's stamp for Oswald Weigel,
                  Leipzig and crossed out ownership stamp: Stello.
                  Generalkommando I. Armeekorps (Wehrkreiskdo. I inside front
                  cover. Also inside front cover are an illegible ownership
                  stamp and ink scription ending with "Vol. 1". Title page has
                  an ownership stamp: Kreigs-Karlen-Hauptamt d OKH/Gen St d H.
                  DLC
Subjects:      Geometrical drawing.
               Euclid's Elements.
               Geometry.
Other authors: Scala, Giovanni.
Control No.:   13507029

Author:        Quintiana, José M. [from old catalog]
Title:         Repertorio de geometria, con varios teoremas y
                  aplicaciones prácticas, escritos por José M. Quintiana.
Edition:       [2. ed.]
Published:     Montevideo, F. Jbarra, 1884.
Description:   128 p. incl. pl. 23 cm.
LC Call No.:   QA464.Q7
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   8669633

Author:        Silva Pereira, Manuel da, 1816-1868. [from old
                  catalog]
Title:         Noçoes de geometria para comprehensão do
                  desenho linear.
Edition:       2. ed. rev., accres. e mais cor.
Published:     Bahia, Catilina & c., 1867.
Description:   vi, [7]-45, [1] p. 8 pl. 16 cm.
LC Call No.:   QA464.S58
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   8666403

Author:        Smith, J[ohn] LL. D. [from old catalog]
Title:         A grammar of geometry; containing an essay
                  exhibition of the practice of that art;
Published:     London, Printed for R. Phillips, 1809.
Description:   viii, 80 p. diagr. 16 cm.
LC Call No.:   QA464.S65
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   8198256

Author:        Smith, Walter. [from old catalog]
Title:         The child's practical geometry;
Published:     Boston, J. R. Osgood and company, 1872.
Description:   1 p. l., 53 p. diagrs. 19 cm.
LC Call No.:   QA464.S66
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   5857037

Author:        Smith, Walter. [from old catalog]
Title:         School of art practical geometry; being the text
                  of a series of elementary problems in drawing plane
                  geometrical figures, as given in courses of lectures in
                  schools of art.
Edition:       6th ed.
Published:     Boston, Frost & Adams [1872]
Description:   31 p. 20 cm.
LC Call No.:   QA464.S67
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   7261425

Author:        Spanton, John Humphrey. [from old catalog]
Title:         Science and art drawing; complete geometrical
                  course consisting of plane and solid geometry, orthographic
                  and isometric projection, projection of shadows, the
                  principles of map projection, graphic arithmetic, and graphic
                  statics,
Published:     London and New York, Macmillan and co., 1895.
Description:   xiv, 582 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA464.S8
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   10109502

Author:        Stoddard, C. Whitney (Charlotte Whitney)
Title:         Geometric problems, their application to
                  constructive drawings; a hand-book for students, by C.
                  Whitney Stoddard ...
Published:     Boston, New York [etc.] The Prang educational
                  company, 1904.
Description:   79 p. illus., diagrs. 20 x 27 cm.
LC Call No.:   QA464.S86
Subjects:      Geometrical drawing.
Control No.:   2161250

Author:        Warren, S. Edward (Samuel Edward), 1831-1909.
Title:         A primary geometry; with simple and practical
                  examples in plane and projection drawing, and suited to all
                  beginners. By S. Edward Warren.
Published:     New York, J. Wiley & sons, 1887.
Description:   viii, 178 p. diagr. 22 cm.
LC Call No.:   QA464.W29
Subjects:      Geometrical drawing.
Control No.:   7729530

Author:        Warren, Samuel Edward, 1831-1909. [from old
                  catalog]
Title:         An elementary course of free-hand geometrical
                  drawing,
Published:     New York, J. Wiley & son, 1873.
Description:   vii. 116 p. illus., 2 fold. pl., diagrs. 20 cm.
LC Call No.:   QA464.W25
Subjects:      Geometrical drawing. [from old catalog]
Other titles:  Free-hand geometrical drawing.
Control No.:   8297858

Author:        Warren, Samuel Edward, 1831-1909. [from old
                  catalog]
Title:         A manual of drafting instruments and operations.
Published:     New York, J. Wiley & son, 1873.
Description:   x, 116 p. illus., v fold. pl., diagrs. 20 cm.
LC Call No.:   QA464.W25
Subjects:      Drawing instruments. [from old catalog]
               Mechanical drawing. [from old catalog]
Control No.:   8754324

Author:        Warren, S[amuel] Edward, 1831- [from old
                  catalog]
Title:         Plane problems in elementary geometry;
Published:     New York, J. Wiley & son, 1867.
Description:   xii, [9]-162 p. fold. pl., tab., diagr. 21 cm.
LC Call No.:   QA464.W28
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
               Geometrical drawing. [from old catalog]
Control No.:   9134629

Author:        Winter, Samuel H. [from old catalog]
Title:         Elementary geometrical drawing ...
Edition:       12th ed.
Published:     London, Longmans, Green, 1885-
Description:   1 v. illus. 19 cm.
LC Call No.:   QA464.W55
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   7428866

Title:         880-01 Kikujutsu sh¯o. Oku no sh¯o. Ge,
                  Ipponjutsu, ¯ohen, gokuhi sanka no daiji.
Published:     [Japan, not before 1716]
Description:   [68] p. : ill. ; 27 cm.
LC Call No.:   QA465.K514 1716
Notes:         Title from title piece.
               On double leaves, oriental style (fukurotoji).
Subjects:      Mensuration.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   12255724

Title:         880-01 Sanmy¯oden genkai.
Published:     [17--?]
Description:   [104] p. : ill. ; 14 x 21 cm.
LC Call No.:   QA465.S26 1700z
Notes:         Ms. (shahon), the copier and the date not known.
               Caption title.
               With no borders.
               On double leaves, oriental style (fukurotoji).
               Kokusho s¯omokuroku, v. 3, p. 861 (Sanmy¯oden
                  genkai, 1-satsu; variant: Sanmy¯oden).
               Not listed in Kotenseki s¯og¯o mokuroku.
               LC copy wormed, with loss of text. DLC
Subjects:      Mensuration.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13786598

Author:        American school of correspondence, Boston. [from
                  old catalog]
Title:         Mathematics. Algebraic formulas and mensuration.
                  Instruction paper. American school of correspondence ...
Published:     New York, c1897.
Description:   44 p. illus. 25 cm.
LC Call No.:   QA465.A6
Subjects:      Mensuration. [from old catalog]
Control No.:   8215467

Author:        Angles, John William. [from old catalog]
Title:         Mensuration for marine and mechanical engineers
Published:     London, New York [etc.] Longmans, Green and co.,
                  1919.
Description:   xxvii, 162 p., 1 l. incl. tables, diagrs. 19 cm.
LC Call No.:   QA465.A7
Subjects:      Mensuration. [from old catalog]
Control No.:   5910959

Author:        Babenko, Isaak Pimenovich. [from old catalog]
Title:         Metrolog¯iëiìa.
Published:     1905.
Description:   189 p. 24 cm.
LC Call No.:   QA465.B12
               Microfilm 15595 QA
Notes:         Romanized.
               Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Mensuration. [from old catalog]
Control No.:   10257596

Author:        Baillairgé, Charles P. Florent, 1827-1906. [from
                  old catalog]
Title:         The stereometricon. Originator: C. Baillairgé
                  ... Measurement of all solids by one and the same rule.
                  Universal application of the prismoidal formula ... Promoter:
                  Thomas Whitty ...
Published:     Quebec, Printed by C. Darveau, 1884.
Description:   2 p. l., [3]-69, 61, [1] p. incl. tables.,
                  diagrs. 22 cm.
LC Call No.:   QA465.B14
               Microfilm 15351 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Mensuration. [from old catalog]
Control No.:   9644731

Author:        Baker, T[homas] [from old catalog]
Title:         Rudimentary treatise on mensuration and
                  measuring, for students and practical use.
Edition:       8th ed.
Published:     London, Virtue brothers & co., 1865.
Description:   vi, 145 p. diagr. 19 cm.
LC Call No.:   QA465.B16
Subjects:      Mensuration. [from old catalog]
Control No.:   9603138

Author:        Bindernagel, Carl.
Title:         Sammlung geometrischer Formeln, nebst nöthiger
                  Erklärung, zur Vereinfachung der rechtwinklichen
                  Parallelvermessung, und der damit verbundenen Berechnungen.
Published:     Giessen, G.F. Heyer, 1822.
Description:   iv, 52 p. illus. 22 cm.
LC Call No.:   QA465.B56
Dewey No.:     516/.0212
Subjects:      Geometry -- Tables.
               Mensuration.
Control No.:   3746644

Author:        Bonnycastle, John, 1750?-1821.
Title:         An introduction to mensuration and practical
                  geometry / by John Bonnycastle ; to which are added a
                  treatise on guaging, and also the most important problems in
                  mechanics by James Ryan.
Published:     Philadelphia : Kimber & Sharpless, 1834, c1833.
Description:   xi, 288 p. : ill. ; 18 cm.
LC Call No.:   QA465.B73
Subjects:      Mensuration.
Other authors: Ryan, James.
Control No.:   8198257

Author:        Bonnycastle, John, 1750?-1821. [from old
                  catalog]
Title:         An introduction to mensuration and practical
                  geometry.
Published:     Philadelphia, Kimber & Sharpless, 1839.
Description:   xi, [1], 288 p. diagr. 19 cm.
LC Call No.:   QA465.B74
Subjects:      Mensuration. [from old catalog]
Control No.:   7261426

Author:        Bonnycastle, John, 1750?-1821. [from old
                  catalog]
Title:         An introduction to mensuration and practical
                  geometry ... / By John Bonnycastle ...
Edition:       11th ed., cor. and impr.
Published:     London, Printed for J. Johnson and co., 1812.
Description:   1 p.l., [v]-xii, 276 p. diagr. 17 cm.
LC Call No.:   QA465.B71
Notes:         Supplemented by: "Key ..." (2 p.l., 200 p. 18
                  cm.) published: London, Printed for F.C. and J. Rivington
                  [etc.] 1817. Call number: QA465.B711.
Subjects:      Mensuration. [from old catalog]
Control No.:   6793057

Author:        Bonnycastle, John, 1750?-1821. [from old
                  catalog]
Title:         An introduction to remsuration and practical
                  geometry.
Published:     The 2d American, from the 10th London ed., rev.
                  and corr. Philadelphia, Kimber and Sharpless, no. 93,
                  Market-street. 1818.
Description:   xii, [13]-262 p. diagrs. 18 cm.
LC Call No.:   QA465.B715
Subjects:      Mensuration. [from old catalog]
Control No.:   6460845

Author:        Bonnycastle, [John], 1750?-1821. [from old
                  catalog]
Title:         A key to the American edition of Bonnycastle's
                  Mensuration ...
Edition:       2d ed.
Published:     Philadelphia, Kimber and Sharpless, 1834.
Description:   88 p. 19 cm.
LC Call No.:   QA465.B732
Subjects:      Mensuration. [from old catalog]
Control No.:   5857038

Author:        Bonnycastle, [John], 1750?-1821. [from old
                  catalog]
Title:         A key to the third American edition of
                  Bonnycastle's Mensuration.
Published:     Philadelphia, Kimber and Sharpless, 1824.
Description:   90 p. diagr. 18 cm.
LC Call No.:   QA465.B721
Other authors: Mensuration. [from old catalog]
Control No.:   8666404

Author:        Brude, Adolf.
Title:         Das Zeichnen der Stereometrie als Vorschule zur
                  darstellenden Geometrie und zum Fachzeichnen für
                  Lehranstalten wie zum Selbstunterricht / von Adolf Brude.
Published:     Stuttgart : Julius Maier, 1872.
Description:   41 p., 28 leaves of plates : ill. ; 28 cm.
LC Call No.:   QA465.B78x 1872
Subjects:      Mensuration.
               Geometry, Descriptive.
Control No.:   983735

Author:        Callendar, B[enjamin] Franklin. [from old
                  catalog]
Title:         Geometry:
Published:     New-York, C. S. Francis, 1836.
Description:   xi, [12]-211 p. diagr. 19 cm.
LC Call No.:   QA465.C15
Subjects:      Mensuration. [from old catalog]
Control No.:   9134630

Author:        Cataneo, Girolamo.
Title:         Dell'arte del misvrare
Published:     In Brescia, Per Giacomo Tvrlino, 1682.
Description:   2 v. in 1. illus., fold. plates, tables, diagrs.
                  23 cm.
LC Call No.:   QA465.C2 1682
Subjects:      Mensuration. [from old catalog]
               Surveying -- Early works to 1800. [from old
                  catalog]
Control No.:   8747406

Author:        Colbert, George H. [from old catalog]
Title:         Outline of mensuration,
Edition:       [1st ed.]
Published:     Shenandoah, Iowa, Larimore & Stephens, 1888.
Description:   52 p. diagr. 19 cm.
LC Call No.:   QA465.C68
Subjects:      Mensuration. [from old catalog]
Control No.:   7729531

Author:        Day, Jeremiah, 1773-1867. [from old catalog]
Title:         A practical application of the principles of
                  geometry to the mensuration of superficies and solids: being
                  the third part of a course of mathematics, adapted to the
                  method of instruction in the American colleges.
Edition:       3d ed.
Published:     New Haven, H. Howe, 1831.
Description:   2 p.l., 96 p. pl. 23 cm.
LC Call No.:   QA465.D27
Subjects:      Mensuration. [from old catalog]
Control No.:   10071430

Author:        Digges, Leonard, d. 1571?
Uniform Title: Tectonicon
Title:         A booke named Tectonicon : briefly shewing the
                  exact measuring and spedie reckoning all maner of land,
                  squares, timber, stone, steeples, pillers, globes, &c. :
                  further, declaring the perfect making and large vse of the
                  carpenters ruler, conteining a quadrant geometricall,
                  comprehending also the rare vse of the squire : and in the
                  end a little treatise adioyning, opening the composition and
                  appliancie of an instrument called the profitable staffe :
                  with other things pleasant and necessarie, most conducible
                  for surueyors, landmeaters, ioyners, carpenters, and masons /
                  published by Leonard Digges gentleman in the yeare of our
                  Lord 1556.
Published:     Imprinted at London : By Thomas Orwin ..., 1592.
Description:   [2], 26 leaves, [2] folded leaves of plates :
                  ill. ; 20 cm. (4to)
LC Call No.:   QA465.D5
Notes:         Signatures: A-Gp4s.
               STC (2nd ed.) 6851
               With: Leigh, V. The moste profitable and
                  commendable science of surueying of landes, tenementes, and
                  hereditamentes.  Imprinted at London : For Miles Iennings,
                  1577. Bound together subsequent to publication. DLC
Subjects:      Mensuration -- Early works to 1800.
Other authors: Orwin, Thomas, d. 1593, printer.
Other authors: English Printing Collection (Library of Congress)
                  DLC
Control No.:   5899026

Author:        Dournel, A. [from old catalog]
Title:         Traité d'arpentage, comprenant plusieurs
                  méthodes nouvelles et simplifiées sur la mesure des
                  propriétés et sur leur division par les calculs; suivi de
                  la manière de mesurer les corps ou solides, à l'usage des
                  arpenteurs, géomètres, charpentiers, maçons, cultivateurs,
                  entrepreneurs, etc., etc.;
Published:     Paris, E. Tétu et cie.; [etc., etc.] 1844.
Description:   77, [5] p. pl. 22 cm.
LC Call No.:   QA465.D73
Subjects:      Mensuration. [from old catalog]
Control No.:   9603139

Author:        Fisher, Frank, 1892- [from old catalog]
Title:         Measuring with chords; the chordograph.
Published:     [New York?] c1952.
Description:   67 p. illus. 28 cm.
LC Call No.:   QA465.F5
Notes:         2 Triangulation.
Subjects:      Mensuration. [from old catalog]
Control No.:   8377167

Author:        Furst, Samuel Willis. [from old catalog]
Title:         Mensuration, with special application of the
                  prismoidal formula,
Published:     Philadelphia, C. Sower company, 1909.
Description:   x, 72 p. incl. fold. front., diagrs. 18 cm.
LC Call No.:   QA465.F82
Subjects:      Mensuration. [from old catalog]
Control No.:   7752567

Author:        Furst, S[amuel] W[illis] [from old catalog]
Title:         Mensuration, with special application of the
                  prismoidal formula;
Published:     Harrisburg, Pa., R. L. Myers & co., 1899.
Description:   ix, 72 p. fold. front., diagrs. 19 cm.
LC Call No.:   QA465.F8
Subjects:      Mensuration. [from old catalog]
Control No.:   9125751

Author:        Glaser, Robert, 1865-
Title:         Sammlung von aufgaben aus der stereometrie, von
                  professor dr. Robert Glaser ... Mit 54 figuren.
Published:     Berlin, Leipzig, G.J. Göschen, 1917.
Description:   168 p. diagrs. 16 cm.
Series:        Sammlung Göschen. [779]
LC Call No.:   QA465.G5
Subjects:      Mensuration.
Control No.:   9193014

Author:        Gregory, David, 1659-1708.
Title:         A treatise of practical geometry : in three
                  parts.
Edition:       9th ed.
Published:     Edinburgh : Printed for J. Balfour, 1780.
Description:   2 p.l., 139 p. 5 fold. pl. 21 cm.
LC Call No.:   QA465.G83
Subjects:      Mensuration -- Early works to 1800.
               Surveying -- Early works to 1800.
Other authors: MacLaurin, Colin, 1698-1746.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   9604652

Author:        Gregory, David, 1659-1708.
Title:         A treatise of practical geometry. In three parts.
                  By the late Dr. David Gregory. 
Edition:       4th ed.
Published:     Edinburgh, Printed by Hamilton, Balfour, and
                  Neil, 1761.
Description:   iv, 117 p. 5 fold. pl. 21 cm.
LC Call No.:   QA465.G82
Notes:         Preface signed: Col. M'Laurin.
Subjects:      Surveying -- Early works to 1800.
               Mensuration -- Early works to 1800.
Other authors: MacLaurin, Colin, 1698-1746. ed.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   6794590

Author:        Hagey, R. J. (Robert John), 1870-
Title:         The gauging of U.S. commercial measures of
                  volume, by R.J. Hagey, A.B.
Published:     Philadelphia, Pa., H. Troemner, c1913.
Description:   49, [12] p. diagrs. 17 cm.
LC Call No.:   QA465.H15
Notes:         [12] blank p. at end for Memorandum.
Subjects:      Volume (Cubic content)
               Weights and measures -- United States.
Control No.:   4053065

Author:        Hall, William S. (William Shaffer), 1861-
Title:         Mensuration. By Wm. S. Hall.
Published:     Boston, Ginn & Company, 1893.
Description:   vii, 62 p. diagr. 19 cm.
Series:        Mathematical series
LC Call No.:   QA465.H18
Subjects:      Mensuration.
Series Entry:  Mathematical series (Boston, Mass.)
Control No.:   6793058

Author:        Halsted, George Bruce, 1853-1922.
Title:         Metrical geometry. An elementary treatise on
                  mensuration, by George Bruce Halsted ...
Published:     Boston, Ginn, Heath & co., 1881.
Description:   xiii p., 1 l., 232 p. diagr. 19 cm.
LC Call No.:   QA465.H19
Subjects:      Mensuration.
Control No.:   744801

Author:        Haswell, Charles H[aynes], 1809- [from old
                  catalog]
Title:         Mensuration and practical geometry;
Edition:       6th ed.
Published:     New York, Harper & brothers, 1884.
Description:   x, [11], 323 p. diagr. 20 cm.
LC Call No.:   QA465.H36
Subjects:      Mensuration. [from old catalog]
Control No.:   8198258

Author:        Haswell, Chas. H. (Charles Haynes), 1809-1907.
Title:         Mensuration and practical geometry; containing
                  tables of weights and measures, vulgar and decimal fractions,
                  mensuration of areas, lines, surfaces, and solids ... To
                  which is appended a treatise on the carpenter's slide-rule
                  and gauging. By Chas H. Haswell ...
Published:     New York, Harper & brothers, 1858.
Description:   x, [11]-322 p. diagr. 20 cm.
LC Call No.:   QA465.H35
Subjects:      Mensuration.
Control No.:   3106783

Author:        Hawney, William. [from old catalog]
Title:         The complete measurer; or The whole art of
                  measuring.
Edition:       10th ed.
Published:     London, J. Knapton, 1759.
Description:   ix, 346 p. diagrs. 17 cm.
LC Call No.:   QA465.H4 1759
Subjects:      Mensuration. [from old catalog]
               Geometry. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   6018074

Author:        Hawney, William. [from old catalog]
Title:         The complete measurer; or The whole art of
                  measuring.
Edition:       3d ed.
Published:     London, J. and J. Knapton, 1729.
Description:   ix, 346 p. diagrs. 17 cm.
LC Call No.:   QA465.H4 1729
Subjects:      Mensuration. [from old catalog]
               Geometry. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   6949848

Author:        Hawney, William. [from old catalog]
Title:         The complete measurer; or The whole art of
                  measuring.
Edition:       4th ed.
Published:     London, J. J. and Knapton [17-]
Description:   ix, 346 p. diagrs. 18 cm.
LC Call No.:   QA465.H4 1700z
Subjects:      Mensuration. [from old catalog]
               Geometry. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   6956422

Author:        Hawney, William. [from old catalog]
Title:         [Hawney's] complete measurer;
Published:     Baltimore: Published by F. Lucas, jr. [182-]
Description:   xii, 312 p. diagrs. 18 cm.
LC Call No.:   QA465.H4
Subjects:      Mensuration. [from old catalog]
               Geometry. [from old catalog]
Other authors: Keith, Thomas, 1759-1824. [from old catalog]
               Craig, John D. [from old catalog]
Control No.:   8272171

Author:        Hawney, William. [from old catalog]
Title:         Hawney's complete measurer:
Published:     Philadelphia, Printed by Cochran & M'Laughlin,
                  for M. Carey [etc.] 1801.
Description:   5 p. l., 19-341, [1] p. diagrs. 17 cm.
LC Call No.:   QA465.H4
Subjects:      Mensuration. [from old catalog]
               Geometry. [from old catalog]
Other authors: Keith, Thomas, 1759-1824. [from old catalog]
Control No.:   5901635

Author:        Hickman, E. A. [from old catalog]
Title:         Arithmetical-geometry,
Published:     Kansas City, Mo., Ramsey, Millet & Hudson, 1876.
Description:   p. cm.
LC Call No.:   QA465.H61
Subjects:      Mensuration. [from old catalog]
Control No.:   5857039

Author:        Hickman, [E. A.] [from old catalog]
Title:         Manual of Hickman's trigonometrical chart.
Published:     Kansas City, Mo., Printed at the Journal of
                  commerce, 1872.
Description:   25 p. 22 cm.
LC Call No.:   QA465.H62
Subjects:      Mensuration. [from old catalog]
Control No.:   7261427

Author:        Hutton, Charles, 1737-1823.
Title:         The compendious measurer : being a brief, yet
                  comprehensive treatise on mensuration and practical geometry,
                  with an introduction to duodecimal arithmetick : adapted to
                  practice and the use of schools / by Charles Hutton.
Published:     Philadelphia : Hugh Maxwell, 1807.
Description:   190 p. : ill. ; 17 cm.
LC Call No.:   QA465.H98 1807
Notes:         Shaw & Shoemaker 12800
Subjects:      Mensuration.
               Mathematics.
Other authors: Marian S. Carson Collection (Library of Congress)
                  DLC
Control No.:   719379

Author:        Hutton, Charles, 1737-1823.
Title:         A treatise on mensuration, both in theory and
                  practice. by Charles Hutton.
Edition:       4th ed. with many additions.
Published:     London, F. C. & J. Rivington [etc.] 1812.
Description:   xvi, 530 p. pl., tab., diagr. 22 cm.
LC Call No.:   QA465.H971
Subjects:      Mensuration.
Control No.:   7729532

Author:        Hutton, Charles, 1737-1823. [from old catalog]
Title:         The compendious measurer;
Published:     London, Printed for F. C. and J. Rivington [etc.]
                  1812.
Description:   xvi, 322 p. illus., tables, diagrs. 18 cm.
LC Call No.:   QA465.H98.
Subjects:      Mensuration. [from old catalog]
Control No.:   6324776

Author:        Hutton, Charles, 1737-1823. [from old catalog]
Title:         A treatise on mensuration, both in theory and
                  practice.
Edition:       3d ed.
Published:     London, W. Glendinning, 1802.
Description:   xvi, 530, [1] p. fold. pl. tab., diagr. 22 cm.
LC Call No.:   QA465.H97.
Subjects:      Mensuration. [from old catalog]
Control No.:   9134631

Author:        Hutton, Henry H.
Title:         Manual of mensuration, for common and high
                  schools. By Henry H. Hutton ...
Published:     Syracuse, N.Y., C.W. Bardeen, 1882.
Description:   vi, [7]-168 p. diagrs. 17 cm.
Series:        School bulletin publications
LC Call No.:   QA465.H985
Subjects:      Mensuration.
Control No.:   8673485

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Geometry and mensruation,
Published:     Scranton, Pa., International textbook company
                  [1931]
Description:   2 p. l., 34, 36 p. diagrs. 20 cm.
LC Call No.:   QA465.I55 1931
Subjects:      Mensuration. [from old catalog]
               Geometry. [from old catalog]
Control No.:   10189517

Author:        Kern, Willis F. and James R. Bland. [from old
                  catalog]
Title:         Solid mensuration...
Published:     New York, London, 1934
Description:   73 p. 22 cm.,
LC Call No.:   QA465.K4
Control No.:   10486948

Author:        Kern, Willis F. (Willis Frederick), 1903-
Title:         Solid mensuration, by Willis F. Kern and James R.
                  Bland.
Published:     New York, J. Wiley & sons, inc.; London, Chapman
                  & Hall, limited, 1934.
Description:   viii, 73 p. front., illus., diagrs. 22 cm.
LC Call No.:   QA465.K4
Dewey No.:     513.3
Subjects:      Mensuration.
               Geometry, Solid.
Other authors: Bland, James R. joint author.
Control No.:   5951642

Author:        Kern, Willis F. (Willis Frederick), 1903-
Title:         Solid mensuration, with proofs, by Willis F. Kern
                  ... and James R. Bland ...
Edition:       2nd ed.
Published:     New York, J. Wiley & Sons, inc.; London, Chapman
                  & Hall, limited, 1938.
Description:   2 p. l., iii-vii, 172 p. illus., diagrs. 23 cm.
LC Call No.:   QA465.K42
Dewey No.:     513.3
Notes:         "The authors have entirely rewritten the original
                  text."--Pref.
               "Answers": p. 161-168.
Subjects:      Mensuration.
               Geometry, Solid.
Other authors: Bland, James R. joint author.
Control No.:   6434885

Author:        Knapen, D. M.
Title:         The mechanic's assistant : a thorough practical
                  treatise on mensuration and the sliding rule: teaching the
                  manner of drawing all regular superficies, and the contents
                  of all regular solids, both by numbers and by the sliding
                  rule. Treating also of the laws of motion, the descent of
                  falling bodies, the strength of materials, the mechanical
                  powers, the elasticity and force of steam, specific
                  gravities, levelling, the pendulum, etc., adapted for the use
                  of carpenters, shipwrights ... and artisans generally / by D.
                  M. Knapen, A.M.
Published:     New York [N.Y.] : D. Appleton & Co., 1849.
Description:   272, [4], 273-276, [8] p. : ill., diagrs. ; 20
                  cm.
LC Call No.:   QA465.K55
Dewey No.:     513.9
Notes:         Bound in: Publisher's catalog, [12] p.
Subjects:      Mensuration.
               Slide-rule.
Control No.:   9699138

Author:        Leigh, Valentine, fl. 1562.
Title:         The moste profitable and commendable science, of
                  surueying of landes, tenementes, and hereditamentes / drawen
                  and collected by the industrie of Valentine Leigh ; whereunto
                  is also annexed by the same authour a right necessarie
                  treatise of the measuryng of all kyndes of lande, be it
                  meadow, pasture, errable, wood, hill, or dale, and that
                  aswell by certaine easie and compendious rules, as also by an
                  exact and beneficiall table, purposely drawen and deuised for
                  that behalfe.
Published:     Imprinted at London : By Miles Iennings, anno
                  Domini 1577.
Description:   [120] p., [2] folded leaves of plates ; 20 cm.
                  (4to)
LC Call No.:   QA465.D5
Notes:         Signatures: A-Gp4s I-Qp4s. A4 blank.
               STC (2nd ed.) 15416a
               With: Digges, L. [Tectonicon]. A booke called
                  Tectonicon.  Imprinted at London : By Thomas Orwin ..., 1592.
                  Bound together subsequent to publication. DLC
Subjects:      Surveying -- Early works to 1800.
Other authors: Jennings, Miles, printer.
Other authors: English Printing Collection (Library of Congress)
                  DLC
Control No.:   7303492

Author:        McLachlan, Norman W.
Title:         Practical mathematics for students attending
                  evening and day technical classes, by Norman W. McLachlan.
Published:     London, New York, Longmans, Green, 1913.
Description:   vi, [2], 184 p. diagrs. 19 cm.
LC Call No.:   QA465.M3
Subjects:      Mensuration.
Control No.:   6363699

Author:        Milne, Robert Moir, 1873-
Title:         Mensuration and elementary solid geometry for
                  schools, by R. M. Milne.
Published:     Cambridge [Eng.] The University press, 1923.
Description:   x, 206 p. diagrs. 22 cm.
LC Call No.:   QA465.M5
Subjects:      Mensuration.
               Geometry, Solid.
Control No.:   8261837

Author:        Nicholson, Peter, 1765-1844.
Title:         The carpenter and builder's complete measurer.
                  Intended as a sequel to the "Carpenter's guide." A practical
                  treatise on mensuration, for the use of carpenters, builders,
                  and surveyors, and artificers in general; measurement of
                  curved surfaces in particular is clearly explained, by means
                  of their plans, sections, and elevations, accompanied with a
                  scale. By Peter Nicholson ...
Published:     [London, Jones & co., 1826]
Description:   240 p. 25 pl. 28 cm.
LC Call No.:   QA465.N62
Subjects:      Mensuration.
Control No.:   10071431

Author:        Ostrander, Tobias. [from old catalog]
Title:         A complete system of mensuration of superficies
                  and solids,
Published:     New York, M'Elrath, Bangs & co., 1833.
Description:   159 p. diagr. 22 cm.
LC Call No.:   QA465.O85
Subjects:      Mensuration. [from old catalog]
Control No.:   10071437

Author:        Puscariu, Ioan Joe, 1852- [from old catalog]
Title:         Das stereometer
                  priveligirtes-körper-messinstrument,
Published:     Budapest, Gedruckt bei Kocsi S., 1877.
Description:   iv p., 1 l., 33 p. illus., diagrs. 23 cm.
LC Call No.:   QA465.P9
Subjects:      Mensuration. [from old catalog]
Control No.:   6349187

Author:        Quimby, E[lihu] T[hayer], 1826-1890. [from old
                  catalog]
Title:         Formulæ in mensuration,
Published:     Hanover, N.H., Parker & White, 1869.
Description:   [4] p. 20 cm.
LC Call No.:   QA465.Q6
Subjects:      Mensuration. [from old catalog]
Control No.:   10074637

Author:        Rodgers, M. H. (Martha H.)
Title:         Rodgers' mensuration. Elements of mensuration. By
                  M.H. Rodgers.
Published:     Philadelphia, E.H. Butler & co., 1862.
Description:   vi, 7-144 p. diagr. 19 cm.
LC Call No.:   QA465.R68
Notes:         Key to Rodgers' mensuration containing solutions
                  and explanations of the more difficult examples in that work
                  by M.H. Rodgers.  Philadelphia, E.H. Butler, 1862.  72 p. 19
                  cm. QA465.R69 1862
Subjects:      Mensuration.
Control No.:   6793065

Author:        Rodgers, Martha H. [from old catalog]
Title:         A key to Rodgers' mensuration. Containing
                  solutions and explanations of the most difficult examples in
                  that work.
Published:     Philadelphia, New York [etc.] Butler, Sheldon &
                  company [c1862]
Description:   72 p. diagrs. 19 cm.
LC Call No.:   QA465.R69 1862a
Subjects:      Mensuration. [from old catalog]
Control No.:   8290810

Author:        Rodgers, Martha H. [from old catalog]
Title:         Rodgers' Mensuration. Elements of mensuration.
Published:     New York, Cincinnati [etc.] American book company
                  [1862]
Description:   vi, 7-144 p. diagrs. 19 cm.
LC Call No.:   QA465.R68 1862a
Subjects:      Mensuration. [from old catalog]
Control No.:   8793917

Author:        Schenker, Theodor, b. 1806. [from old catalog]
Title:         Beiträge zur visirkunst ...
Published:     Chemnitz, Gedruckt bei C.G. Kretschmar [1838]
Description:   11 p. pl. 21 cm.
LC Call No.:   T173.C513 1838
Subjects:      Mensuration. [from old catalog]
Other authors: Chemnitz. K. Gewerb-akademie. [from old catalog]
               Chemnitz. K. Baugewerkenschule. [from old
                  catalog]
Control No.:   6331832

Author:        Scribner, J. M. [from old catalog]
Title:         A practical system of mensuration of superfices
                  and solids ...
Published:     New York, A. V. Blake, 1844.
Description:   xv, [16]-123, [1] p. diagr. 19 cm.
LC Call No.:   QA465.S43
Subjects:      Mensuration. [from old catalog]
Control No.:   8666412

Author:        Sell, William F., 1860-
Title:         Development lessons in mensuration : with over a
                  thousand examples and problems illustrating the practical use
                  of mensuration / by Wm. F. Sell.
Edition:       2d ed.
Published:     Chicago : A. Flanagan, [1903]
Description:   74 p. : ill. ; 19 cm.
LC Call No.:   QA465.S47
Subjects:      Mensuration.
Control No.:   8667525

Author:        Sell, William Frederick, 1860- [from old
                  catalog]
Title:         Development lessons in mensuration.
Published:     Milwaukee, Wis., 1896.
Description:   50 p. diagrs. 23 cm.
LC Call No.:   QA465.S46
Subjects:      Mensuration. [from old catalog]
Control No.:   8198266

Author:        880-01 Shimizu, Sadanori, 1645-1717.
Title:         880-02 Kikuh¯o betsuden zukai mokuroku.
Published:     [Japan, not before 1716]
Description:   [60] p. : ill. (chiefly col.) ; 27 cm.
LC Call No.:   QA465.S525 1716
Notes:         Text in Kanbun, with reading marks.
               Title from title piece.
               On double leaves, oriental style (fukurotoji).
               Not listed in Kokusho s¯omokuroku and Kotenseki
                  s¯og¯o mokuroku; but Kokusho s¯omokuroku, v. 2, p. 398
                  (Kikuh¯o betsuden zukai, 1-satsu, by Shimizu Taemon).
Subjects:      Mensuration.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   12253976

Author:        Solski, Stanislaw, 1622-1701. [from old catalog]
Title:         Praxis nova & expeditissima mensurandi geometrice
                  quasuis distantias, altitudines, & profunditates, plerumq;
                  sine vsu ordinario regulae proportionum, quam auream seu
                  trium vocant ...
Published:     Cracoviae, Ex officina F. Cezary, 1688.
Description:   136 p. illus. 20 cm.
LC Call No.:   QA465.S64
Subjects:      Mensuration -- Early works to 1800. [from old
                  catalog]
               Geometry -- Early works to 1800. [from old
                  catalog]
Control No.:   7603208

Author:        Teller, Otto. [from old catalog]
Title:         Beispiele und Aufgaben: Geometrie.
Published:     München, J. Lindauer [19-
Description:   v. illus. 21 cm.
LC Call No.:   QA465.T4
Subjects:      Mensuration -- Problems, exercises, etc. [from
                  old catalog]
Other authors: Geometrie: Beispiele und Aufgaben. [from old
                  catalog]
Control No.:   8032618

Author:        Ticknor, Almon, b. 1796. [from old catalog]
Title:         A key to Ticknor's mensuration, containing
                  solutions to all the questions left unsolved in that work.
Published:     Pottsville, Pa., B. Bannan, 1850.
Description:   132 p. diagrs. 19 cm.
LC Call No.:   QA465.T55
Subjects:      Mensuration. [from old catalog]
Control No.:   7264524

Author:        Todhunter, I. (Isaac), 1820-1884.
Title:         Mensuration for beginners, with numerous
                  examples, by I. Todhunter ...
Published:     London, Cambridge, Macmillan and Co., 1869.
Description:   viii, 296 p. diagrs. 16 cm.
LC Call No.:   QA465.T6
Dewey No.:     511.8 [513.9]
Subjects:      Mensuration.
Control No.:   6887787

Author:        880-01 Tsuda, Zenjir¯o.
Title:         880-02 Sanp¯o jikata (ky¯useki) keikoy¯o j¯oh¯o /
                  [chosaku Tsuda Zenjir¯o].
Published:     880-04 ¯Osaka-shi : Tsuda Zenjir¯o, Taish¯o 1
                  [1912]
Description:   [98] p. : ill. ; 11 x 15 cm.
LC Call No.:   QA465.T 78 1912
Notes:         Caption title.
               On double leaves, oriental style.
Subjects:      Mensuration.
               Area measurement.
Control No.:   5275228

Author:        Tylkowski, Wojciech, 1629-1695.
Title:         Geometria practica, curiosa : in tres libros
                  divisa ... / auctore P. Adalberto Tylkowski ...
Published:     Posnaniae : Typis Collegij Societatis Ies.,
                  1692.
Description:   [2], 257, 358-368, 399-495, [1] p., [2] leaves of
                  plates : ill. ; 17 cm. (8vo)
LC Call No.:   QA465.T94 1692
Dewey No.:     530.8 20
Notes:         Signatures: pi1 A-Zp8s. The last leaf blank?;
                  wanting in LC copy.
               A "Quadratum lineare geometricum" is on the 2
                  leaves of plates.
               Backer-Sommervogel, v. 8, col. 294, no. 46.
               (from t.p.) De lineae -- De superficiei -- De
                  corporis dimensione.
Subjects:      Mensuration -- Early works to 1800.
               Geometry -- Early works to 1800.
Control No.:   3408241

Author:        United Corredpondence schools. [from old
                  catalog]
Title:         Instruction paper.
Published:     [n.p.] [1898]
Description:   1 v. cm.
LC Call No.:   QA465.U58
Control No.:   6734309

Author:        United correspondence schools. [from old
                  catalog]
Title:         Question paper.
Published:     [n.p.] [1898]
Description:   1 v. cm.
LC Call No.:   QA465.U59
Control No.:   10015841

Author:        Vogdes, William, 1802-1886.
Title:         An elementary treatise on mensuration and
                  practical geometry : together with numerous problems of
                  practical importance in mechanics / by William Vogdes.
Published:     Philadelphia : E.C. & J. Biddle, 1846.
Description:   299 p. : ill. ; 20 cm.
LC Call No.:   QA456.V87
Notes:         Spine title: Vogdes' mensuration.
Subjects:      Mensuration.
Other titles:  Vogdes' mensuration.
Control No.:   5857046

Author:        Vogdes, William, 1802-1886.
Title:         Key to An elementary treatise on mensuration. By
                  William Vogdes.
Published:     Philadelphia, E. C. & J. Biddle, 1847.
Description:   112 p. 20 cm.
LC Call No.:   QA465.V88
Subjects:      Mensuration.
Control No.:   9134639

Author:        Warner, C[larence] D. [from old catalog]
Title:         Elements of mensuration.
Published:     Northampton, Mass., Press of Gazette printing
                  co., 1886.
Description:   vi, [1], 92 p. 19 cm.
LC Call No.:   QA465.W28
Subjects:      Mensuration. [from old catalog]
Control No.:   7729539

Author:        Wright, W. V. [from old catalog]
Title:         Mechanics' arithmetic;
Published:     Boston, New England publishing co. [1889]
Description:   62 p. diagrs. 24 x 16 cm.
LC Call No.:   QA465.W95
Subjects:      Mensuration. [from old catalog]
Control No.:   7736109

Author:        880-01 Yoshida, Shigenori, fl. 1818.
Title:         880-02 Mizoguchi-ry¯u kikujutsu zukai / Yoshida
                  Shigenori cho ; Kawai Kagemitsu tei ; Matsuda Chigei k¯o.
Published:     880-06 Nihonbashi [Edo] : seihonjo Suharaya Moh¯e
                  : ¯Osakaya Mokichi, [1820?]
Description:   3 v. : ill. (woodcuts) ; 23 cm.
LC Call No.:   QA465.Y67 1820b
Notes:         Caption title.
               This work almost identical with LCCN 2000-696541,
                  different impression?
               Advertisement of this book on colophon page.
               Within single border (18.7 x 13.5 cm.), text in
                  11 vertical lines.
               On double leaves, oriental style (fukurotoji).
               Kokusho s¯omokuroku, v. 2, p. 394 (Kikujutsu
                  zukai, 3-satsu; by Yoshida Shigenori, Bunsei 3 [1820] kan).
               LC set wormed, with loss of text. DLC
Subjects:      Mensuration.
Other authors: 880-07 Kawai, Kagemitsu, fl. 1820.
               880-08 Matsuda, Chigei, fl. 1820.
               880-09 Murata, K¯ory¯u, 1747-1831?
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13800629

Author:        880-01 Yoshida, Shigenori, fl. 1818.
Title:         880-02 Mizoguchi-ry¯u Kikujutsu zukai / Yoshida
                  Shigenori cho ; Kawai Kagemitsu tei ; Matsuda Chigei k¯o.
Published:     880-05 Nihonbashi [Edo] : seihonjo Suharaya Moh¯e
                  : ¯Osakaya Mokichi, [1820?]
Description:   3 v. : ill. ; 23 cm.
LC Call No.:   QA465.Y67 1820
Notes:         Caption title.
               Advertisement of this book on colophon page.
               Within single border (18.7 x 13.5 cm.), text in
                  11 vertical lines.
               On double leaves, oriental style (fukurotoji).
               Kokusho s¯omokuroku, v. 2, p. 394 (Kikujutsu
                  zukai, 3-satsu; by Yoshida Shigenori, Bunsei 3 [1820] kan).
               LC set bound in 1 v., with new cover? DLC
               LC copy wormed, with loss of text. DLC
Subjects:      Mensuration.
Other authors: 880-06 Murata, K¯ory¯u, 1747-1831?
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13027168

Author:        Young, J. R. (John Radford), 1799-1885.
Title:         An introductory treatise on mensuration, in
                  theory and practice.
Published:     London, J. and C. Mozley, 1853.
Description:   vii, [8]-284 p. diagr., tab. 19 cm.
LC Call No.:   QA465.Y73
Subjects:      Mensuration.
Control No.:   10071438

Author:        Adler, Irving.
Uniform Title: Monkey business. 6. Doing the impossible
Title:         The impossible in mathematics / Irving Adler.
Published:     Reston, Va. : National Council of Teachers of
                  Mathematics, [1975], c1957.
Description:   25 p. : ill. ; 23 cm.
LC Call No.:   QA466.A34 1975
Dewey No.:     510
Notes:         "Reprinted, with minor editorial changes, from
                  the chapter 'Doing the impossible' in Monkey business, by
                  Irving Adler."
               Brief accounts of historical attempts to prove
                  impossible problems in mathematics, such as the trisection
                  problem, the "fifteen" and "64" puzzles, squaring the circle,
                  etc.
Subjects:      Geometry -- Problems, Famous -- Juvenile
                  literature.
               Mathematical recreations -- Juvenile literature.
               Geometry.
               Mathematical recreations.
Control No.:   2690327

Author:        Angherà, Domenico. [from old catalog]
Title:         Problemi del più alto interesse scientifico
                  geometricamente resoluti e dimostrati,
Published:     Napoli, Stamperia del Fibreno, 1861.
Description:   198 p. front. (port.) diagrs. on iv fold. pl. 24
                  cm.
LC Call No.:   QA466.A6
Subjects:      Geometry -- Problems, Famous. [from old catalog]
Control No.:   6812481

Author:        Klein, Felix, 1849-1925.
Uniform Title: Vorträge über ausgewählte fragen der
                  elementargeometrie. English
Title:         Famous problems of elementary geometry: the
                  duplication of the cube; the trisection of an angle; the
                  quadrature of the circle; an authorized translation of F.
                  Klein's Vorträge über ausgewählte fragen der
                  elementargeometrie, ausgearbeitet von F. Tägert, by Wooster
                  Woodruff Beman ... and David Eugene Smith ...
Published:     Boston, London, Ginn & company, 1897.
Description:   ix, 80 p. diagrs. 19 cm.
LC Call No.:   QA466.K64
Notes:         Lettered on cover: Problems in geometry. Beman
                  and Smith.
Subjects:      Geometry -- Problems, Famous.
Other authors: Beman, Wooster Woodruff, 1850-1922, tr.
               Smith, David Eugene, 1860-1944, joint tr.
Control No.:   744766

Author:        Klein, Felix, 1849-1925.
Title:         Famous problems of elementary geometry; the
                  duplication of the cube, the trisection of an angle, the
                  quadrature of the circle; an authorzed translation of F.
                  Klein's Vorträge über ausegewählte fragen der
                  elementargeometrie, ausgearbeitet von F. Tägert, by Wooster
                  Woodruff Beman and David Eugene Smith.
Edition:       2d ed. rev., and enl. with notes by Raymond Clare
                  Archibald.
Published:     New York, G. E. Stechert, 1930.
Description:   xi, 92 p. diagrs. 19 cm.
LC Call No.:   QA466.K64 1930
Notes:         Errata (1 leaf) laid in.
Subjects:      Geometry -- Problems, Famous.
Other authors: Archibald, Raymond Clare, 1875-1957, ed.
               Beman, Wooster Woodruff, 1850-1922, tr.
               Smith, David Eugene, 1860-1944, joint tr.
Control No.:   7815185

Author:        Rupert, William W. (William Whitehead)
Title:         Famous geometrical theorems and problems, with
                  their history, by William W. Rupert ...
Published:     Boston, D.C. Heath & Co., 1901.
Description:   iii, 107 p. 19 cm.
LC Call No.:   QA466.R95
Subjects:      Geometry -- History.
               Geometry -- Problems, Famous.
Control No.:   8661010

Author:        Rupert, William W. (William Whitehead)
Title:         Famous geometrical theorems and problems, with
                  their history, by William W. Rupert ...
Published:     Boston, D.C. Heath & co., 1900-
Description:   v. 20 cm.
Series:        Heath's mathematical monographs.
LC Call No.:   QA466.R94
Notes:         Issued in 4 parts, 1900-01.
Subjects:      Geometry -- History.
               Geometry -- Problems, Famous.
Control No.:   744650

Author:        Rupert, William Whitehead. [from old catalog]
Title:         Famous geometrical theorems and problems,
Published:     Boston, D. C. Heath & co., 1900-
Description:   p. 20 cm.
LC Call No.:   QA466.R94
Subjects:      Geometry -- History. [from old catalog]
               Geometry -- Problems, Famous. [from old catalog]
Control No.:   6318088

Author:        Stoëtìskiæi, M. K.  (Maksim Kirillovich),  b.
                  1891.
Title:         [Razreshil li ëiìa vekovuëiìu zadachu; kvadratury
                  kruga, trisekëtìsii ugla, kubatury shara.] Did I solve the
                  problem of the ages? The squaring of the circle,
                  tricésection [!] of an angle, cubing of a ball.
Published:     New York, 1944.
Description:   83 p. incl. port., diagrs. 21 cm.
LC Call No.:   QA466.S8
Notes:         At head of title: M.K. Stoëtìskiæi.
Subjects:      Geometry -- Problems, Famous.
Other titles:  Did I solve the problem of the ages?
Control No.:   5993038

Author:        Timerding, H. E. (Heinrich Emil), b. 1873.
Title:         Der goldene schnitt / von H.E. Timerding.
Published:     Leipzig ; Berlin : B.G. Teubner, 1919.
Description:   57 p. : ill. ; 19 cm.
Series:        Mathematisch-physikalische Bibliothek ; Bd. 32
LC Call No.:   QA466.T5
Subjects:      Golden section.
               Geometry -- Problems, Famous.
Control No.:   9199735

Author:        Woodlock, P. D. (Patrick Daniel), 1838?-
Title:         Important discoveries in plane and solid
                  geometry, consisting of the relation of polygons to circles
                  and the equalizing of perimeters to circumferences and
                  drawing curved lines equal to straight lines, the trisection
                  of an angle and the duplication of the cube, by P.D.
                  Woodlock.
Published:     Columbia, Mo., E.W. Stephens publishing company
                  [c1912]
Description:   39 p. diagrs. 22 cm.
LC Call No.:   QA466.W8
Subjects:      Geometry -- Problems, Famous.
Control No.:   2161846

Title:         Cyclometry and circle-squaring in a nutshell, by
                  a member of the British Association for the Advancement of
                  Science.
Published:     London, Simpkin, Marshall & co., 1871.
Description:   4 p.L., 44 p. diagrs. (1 fold.) 20 cm.
LC Call No.:   QA467.C9
Notes:         Signed: S. B. J.
Subjects:      Circle-squaring
Other authors: J., S. B.
               S. B. J.
Control No.:   5895252

Title:         Some omissions to the Pamphlet concerning the
                  circle.
Published:     [n.p.] 1861.
Description:   12 p. 21 cm.
LC Call No.:   QA467.S69
Subjects:      Circle-squaring.
Control No.:   9134646

Author:        Agnew, H. C. [from old catalog]
Title:         A letter from Alexandria, on the evidence of the
                  practical application of the quadrature of the circle, in the
                  configuration of the great pyramids of Gizeh.
Published:     London, Longman, Orme, Brown, Green, and
                  Longmans, 1838.
Description:   2 p.l., 57 p. plates (1 fold.) 28 cm.
LC Call No.:   QA467.A27
Subjects:      Pyramids.
               Circle-squaring.
Control No.:   9603146

Author:        Anderson, Alick Burnes.
Title:         The secret of the circle and the circle squared /
                  by Alick Burnes Anderson.
Published:     Oxford : F.H. Plummer, 1891.
Description:   26 p. : ill. ; 22 cm.
LC Call No.:   QA467.A52x 1891
Subjects:      Circle-squaring.
Control No.:   1456200

Author:        Andión F., Inocencio. [from old catalog]
Title:         La cuadratura del circulo y de la elíptica ...
Edition:       2. ed.
Published:     [n. p.] 1917.
Description:   1 v. cm.
LC Call No.:   QA467.A6 1917
Control No.:   10007616

Author:        Arnó, Pedro.
Title:         La cuadratura del círculo y sus frutos, ó sea
                  Antídoto contra la locura, por Pedro Arnó.
Published:     Buenos Aires [Sociedad Anónima] 1870.
Description:   25 p., 1 l. 21 cm.
LC Call No.:   QA467.A75
Subjects:      Circle-squaring.
Control No.:   1217048

Author:        Babini, José, 1897- [from old catalog]
Title:         La cuadratura del círculo.
Edition:       2. ed.
Published:     [Santa Fe, Rep. argentina [Imp. de la
                  Universidad] 1936.
Description:   29 p. 1 illus., diagrs. 23 cm.
LC Call No.:   QA467.B3
Subjects:      Circle-squaring. [from old catalog]
               Geometry -- Problems, Famous. [from old catalog]
Control No.:   8309661

Author:        Bean, David.
Title:         A collation of geometrical principle and
                  propositions and a combination of geometrical figures,
Published:     [n. p., 1881]
Description:   1 p.l., [9] p. 1 pl. 23 cm.
LC Call No.:   QA467.B36.
Subjects:      Circle-squaring.
Control No.:   6324930

Author:        Benson, Lawrence S. (Lawrence Sluter)
Title:         Some information concerning the circle, or The
                  fallacies of Archimedes, Newton and others exposed, by
                  Lawrence S. Benson.
Published:     [Mezula, S.C.] 1860.
Description:   12 p. diagr. 22 cm.
LC Call No.:   QA467.B47
Subjects:      Circle-squaring.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
Control No.:   8666413

Author:        Benson, Lawrence S[luter] [from old catalog]
Title:         A dissertation on the principles and science of
                  geometry ... By Prof. Lawrence S. Benson.
Published:     New York, C.H. Phelps, 1871.
Description:   16 p. 21 cm.
LC Call No.:   QA467.B452
Subjects:      Circle squaring. [from old catalog]
Control No.:   7266355

Author:        [Benson, Lawrence Sluter] [from old catalog]
Title:         Experimentum crucis.
Published:     [New York, 18--]
Description:   7 p. 21 cm.
LC Call No.:   QA467.B454
Subjects:      Circle squaring. [from old catalog]
Control No.:   7267479

Author:        [Benson, Lawrence Sluter] [from old catalog]
Title:         An exposé of Mr. Hunter's "Little book".
Published:     [New York, 1873?]
Description:   2 p. 28 x 21 cm. fold. to 18 cm.
LC Call No.:   QA467.B479
Notes:         [With his Notes on the first book of Benson's
                  Geometry. New York, 1873.]
Subjects:      Hunter, Thomas, 1831-1915. Elements of plane
                  geometry. [from old catalog]
Control No.:   8671255

Author:        Benson, Lawrence S[luter] [from old catalog]
Title:         Facts and figures for mathematicians; or, The
                  geometrical problem which Benson's geometry alone can solve
                  ...
Published:     [New York, 187-]
Description:   22 p. diagrs. 20 cm.
LC Call No.:   QA467.B456
Subjects:      Circle squaring. [from old catalog]
Control No.:   10076506

Author:        [Benson, Lawrence Sluter] [from old catalog]
Title:         Mensuration. New processes ensuring correct
                  results. Practically confirmed and geometrically sustained.
                  Adapted to surveying, navigation & astronomy.
Published:     [New York, c1889]
Description:   [3]-17 p. diagrs. 23 cm.
LC Call No.:   QA467.B46
Subjects:      Circle squaring. [from old catalog]
Control No.:   7732762

Author:        Benson, Lawrence Sluter. [from old catalog]
Title:         Notes on the first book of Benson's Geometry, and
                  Concerning the circle; showing the decided improvement
                  effected in the science of geometry. By Lawrence S. Benson
                  ...
Published:     New York, J.S. Burnton, 1873.
Description:   24 p. 20 cm.
LC Call No.:   QA467.B479
Subjects:      Circle squaring. [from old catalog]
Control No.:   6797958

Author:        Benson, Lawrence S[luter] [from old catalog]
Title:         Replies by Prof. Lawrence S. Benson to Prof. E.T.
                  Quimby ... Prof. Wm. Chauvenet ... Prof. Robert D. Allen ...
                  and Prof. A.T. Bledsoe ...
Published:     New York, J.S. Burnton, 1872.
Description:   16 p. 21 cm.
LC Call No.:   QA467.B465
Notes:         Supplemented by: "Reply to criticisms on Benson's
                  Geometry." [New York, J.S. Burnton? 1873] (6 p. diagr. 23
                  cm.) [With his Notes on the first book of Benson's Geometry,
                  New York, 1873] Call number: QA467.B48.
Subjects:      Circle squaring. [from old catalog]
Control No.:   8203102

Author:        Benson, Lawrence Sluter. [from old catalog]
Title:         Scientific disquisitions concerning the circle
                  and the ellipse. A discussion of the properties of the
                  straight line and the curve, with a critical examination of
                  the algebraic analysis ... By Lawrence S. Benson ...
Published:     Augusta, Ga., Singer's steam press, 1862.
Description:   iv, 94 p. diagrs. 19 cm.
LC Call No.:   QA467.B467
Subjects:      Circle-squaring.
               Ellipse.
Control No.:   7314152

Author:        Beutel, Eugen, 1880-
Title:         Die quadratur des kreises, von Eugen Beutel ...
                  Mit 15 figuren im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1913.
Description:   2 p.l., 75, [1] p. diagrs. 19 cm.
Series:        Mathematische bibliothek, hrsg. von W. Lietzmann
                  und A. Witting. 12
LC Call No.:   QA467.B5
ISBN:          DM1.00
Notes:         "Literatur-verzeichnis": p. [69]-70.
Subjects:      Circle-squaring.
Series Entry:  Mathematische Bibliothek ; 12.
Control No.:   2634725

Author:        Bradley, Isaac Sanford. [from old catalog]
Title:         Hypostasis: the story of a mite. Its dicovery and
                  utility.
Published:     Dayton Ohio, 1902.
Description:   20 p. 24 cm.
LC Call No.:   QA467.B81
Other titles:  Circle-squaring. [from old catalog]
Control No.:   8198267

Author:        Brower, William. [from old catalog]
Title:         The quadrature of the circle: being a full
                  exposition of the problem,
Published:     Philadelphia, Sower, Potts & co. [1874]
Description:   16 p. fold. diagrs. 23 cm.
LC Call No.:   QA467.B87
Subjects:      Circle-squaring. [from old catalog]
Control No.:   7254868

Author:        Cottrell, [Albert] [from old catalog]
Title:         Cottrell's system and process and squaring the
                  circle,
Published:     Providence, R.I., F. N. Shaw, 1888.
Description:   33 p. 16 cm.
LC Call No.:   QA467.C85.
Subjects:      Circle -- Squaring. [from old catalog]
Control No.:   7261434

Author:        Cottrell, Albert. [from old catalog]
Title:         Cottrell's system and process of squaring the
                  circle ...
Published:     Providence [R.I.] Printed by A. C. Greene, 1868.
Description:   37 p. 22 cm.
LC Call No.:   QA467.C84.
Subjects:      Circle-Squaring. [from old catalog]
Control No.:   5857047

Author:        Crabb, Norman. [from old catalog]
Title:         Geometrical square root;
Published:     Chicago, 1879.
Description:   28, [10] p. diagr. 17 cm.
LC Call No.:   QA467.C88
Subjects:      Circle-squaring. [from old catalog]
Control No.:   9134640

Author:        Davis, John. [from old catalog]
Title:         The measure of the circle, perfected in January,
                  1845, by John Davis.
Published:     Providence, For the author, 1854.
Description:   156 p. 22 cm.
LC Call No.:   QA467.D26
Subjects:      Circle-squaring.
Control No.:   12942845

Author:        De Medici, Charles. [from old catalog]
Title:         A prefatory essay to the new science:
                  mathematical commensuration. Preceded by a brief
                  retrospective view of research in the domain of geometry.
Published:     Chicago, A. M. Flanagan, 1883.
Description:   31 p. diagrs. 18 x 13 cm.
LC Call No.:   QA467.D37
Subjects:      Circle-squaring. [from old catalog]
Control No.:   8204776

Author:        Dingle, Edward, 1814-
Title:         The square of the circle considered under the
                  principle of action to reaction equal. By Edward Dingle ...
Published:     Tavistock, Devon, The author [1894]
Description:   vii, 9-35 p. front. (fold. diagr.) 22 cm.
LC Call No.:   QA467.D58
Notes:         The force of light. A lecture, reprinted from
                  Pitman's popular lecturer, no. 60, April, 1861: p. [30]-35.
Subjects:      Circle-squaring.
Control No.:   5870230

Author:        Dorst. [from old catalog]
Title:         Bing's kreiswinkel ...
Published:     [188?]
Description:   1 v. cm.
LC Call No.:   QA467.D8
Control No.:   6727003

Author:        Echegaray y Eizaguirre, José, 1832-1916. [from
                  old catalog]
Title:         Disertaciones matemáticas sobre la cuadratura
                  del círculo,
Published:     Madrid, Impr. de la Viuda á Hijo de D. E.
                  Aguado, 1887.
Description:   149 p. 24 cm.
LC Call No.:   QA467.E36
Subjects:      Circle-squaring. [from old catalog]
Control No.:   9296655

Author:        Fuller, Rufus.
Title:         Circle and square; the ancient problem arranged
                  in four parts; illustrated with original diagrams, by Rufus
                  Fuller.
Published:     Springfield, Mass., Press of Springfield printing
                  and binding co., 1908.
Description:   46 p. incl. front., diagrs. 21 cm.
LC Call No.:   QA467.F93
Subjects:      Circle-squaring.
Control No.:   745333

Author:        Fuller, Rufus.
Title:         A double discovery. The square of the circle, by
                  Rufus Fuller.
Published:     Boston, Mass., Printed for the author, 1893.
Description:   3 p. l., [1] p., 2 l. front. (port.) illus., 16
                  diagr. 20 cm.
LC Call No.:   QA467.F96
Subjects:      Circle-squaring.
Control No.:   10071439

Author:        Gaskill, George Washington. [from old catalog]
Title:         The absolutely equated circle,
Published:     [Elgin, Minn., Elgin monitor] c1914.
Description:   p. cm.
LC Call No.:   QA467.G25
Subjects:      Circle-squaring. [from old catalog]
Control No.:   8239434

Author:        Gee, William F. [from old catalog]
Title:         A new system of geometry successfully applied to
                  the solution of the sqare of the circle ...
Published:     Charleston, S.C., S. G. Courtenay & co., 1859.
Description:   68 p. 19 cm.
LC Call No.:   QA467.G29
Other titles:  Circle-squaring. [from old catalog]
Control No.:   9603147

Author:        Grosvenor, Cyrus Pitt, 1792-1879.
Title:         The quadrature of the circle perfected;
Published:     New York, Printed for the author, 1868.
Description:   8 p. diagrs. 30 cm.
LC Call No.:   QA467.G87
Notes:         A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Circle-squaring.
Control No.:   12942125

Author:        Guarrera, Vincenzo.
Title:         La quadratura del circolo : ovvero, un nuovo
                  rapporto tra circonferenza e diametro / Vincenzo Guarrera.
Published:     Catania : Niccolò Giannotta, 1908.
Description:   [13] p. : ill. ; 25 cm.
LC Call No.:   QA467.G82x 1908
Subjects:      Circle-squaring.
Control No.:   983731

Author:        Heisel, Carl Theodore, 1852-
Title:         Fundamental truth; startling, revolutionary
                  geometrical laws, ratios and relations between straight lines
                  and curved lines; the mathematical world defied and
                  challenged to upset these new facts, figures and truths; by
                  Carl Theodore Heisel.
Published:     [Cleveland, C. T. Heisel] 1936.
Description:   p. 348-394. diagrs. 25 cm.
LC Call No.:   QA467.H42
Dewey No.:     513.21
Notes:         Cover title.
               To accompany the 1934 second edition of
                  "Mathematical and geometrical demonstrations" or "The circle
                  squared".  cf. p. 394.
Subjects:      Circle-squaring.
Other authors: Heisel, Carl Theodore, 1852- Mathematical and
                  geometrical demonstrations.
Control No.:   8775524

Author:        Heisel, Carl Theodore, 1852-
Title:         Mathematical and geometrical demonstrations, by
                  Carl Theodore Heisel; disproving numerous theorems, problems
                  ... with ratios, laws and rules hitherto unknown in
                  mathematical and geometrical science, naturally growing out
                  of the extraordinary and significant discoveries of a lacking
                  link by Carl Theodore Faber ... in the demonstration of the
                  world renowned Pythagorean problem utterly disproving its
                  absolute truth, although demonstrated as such for twenty-four
                  centuries...
Edition:       2d ed.
Published:     [Cleveland, C. T. Heisel] 1934.
Description:   2 p. l., iii-xx, 278 p. illus., ports., tables (1
                  fold.) diagrs. (part fold.) 27 cm.
LC Call No.:   QA467.H4 1934
Notes:         Half-title: Behold! The grand problem no longer
                  unsolved: the circle squared beyond refutation.
Subjects:      Faber, Carl Theodore, 1811-1887.
               Circle-squaring.
Control No.:   9229011

Author:        Heisel, Carl Theodore, 1852-
Title:         Mathematical and geometrical demonstrations, by
                  Carl Theodore Heisel; disproving numerous theorems, problems
                  ... with ratios, laws and rules hitherto unknown in
                  mathematical and geometrical science, naturally growing out
                  of the extraordinary and significant discoveries of a lacking
                  link by Carl Theodore Faber ... in the demonstration of the
                  world renowned Pythagorean problem utterly disproving its
                  absolute truth, although demonstrated as such for twenty-four
                  centuries ...
Edition:       1st ed.
Published:     [Cleveland, Printed by S.J. Monck] 1931.
Description:   2 p. l., iii-xvi, 128 p. illus., ports., diagrs.
                  (part fold.) 27 cm.
LC Call No.:   QA467.H4
Dewey No.:     513.21
Notes:         Half-title: Behold! The grand problem no longer
                  unsolved: The circle squared beyond refutation.
Subjects:      Circle-squaring.
               Faber, Carl Theodore, 1811-1887.
Control No.:   6408221

Author:        Jackman, Alonzo. [from old catalog]
Title:         The circle squared,
Edition:       [Rev. ed.
Published:     Northfield, Vt., Norwich university press, 1876.
Description:   cover-title, 8 p. 3 diagr. 20 cm.
LC Call No.:   QA467.J14
Subjects:      Circle-squaring. [from old catalog]
Control No.:   8198268

Author:        Jackman, Alonzo. [from old catalog]
Title:         "The circle squared!"
Published:     Northfield, Vt., 1872.
Description:   broadside. diagr. 25 x 20 cm.
LC Call No.:   QA467.J13
Subjects:      Circle-squaring. [from old catalog]
Control No.:   8666414

Author:        Jacob, Bendicht. [from old catalog]
Title:         Square of the circle, measurement of the globe,
                  decimal degrees and world-time,
Published:     Stony Hill, Mo. [1889]
Description:   10 p. 23 cm.
LC Call No.:   QA467.J16
Subjects:      Circle-squaring. [from old catalog]
Control No.:   5857048

Author:        Kearney, H. [from old catalog]
Title:         The quadrature of the circle proved.
Published:     London, C. Ollier, 1847.
Description:   2 p.l., 44 p. 5 fold. pl. 20 m.
LC Call No.:   QA467.K24
Subjects:      Circle-squaring. [from old catalog]
Control No.:   7261435

Author:        Maines, Fabio José. [from old catalog]
Title:         Estudio sobre la cuadratura del círculo, por
                  Fabio José Maines.
Published:     Montevideo, Estab. tip. de "La Nación", 1878.
Description:   18 p., 1 l. diagr. 22 cm.
LC Call No.:   QA467.M22
Subjects:      Circle-squaring.
Control No.:   12894841

Author:        Mastellari, Filippo. [from old catalog]
Title:         Quadratura del circolo.
Published:     Puebla, Scuola tipografica salesiana, 1903.
Description:   21 p. diagrs. on fold. pl. 18 cm.
LC Call No.:   QA467.M42
Subjects:      Circle squaring. [from old catalog]
Control No.:   7268591

Author:        May, John.
Title:         The theory and construction of the quadrature of
                  the circle; also, the globe or ball reduced to the cube, and
                  two new measures--the octants, with the inclination of the
                  perpendicular line ...
Edition:       2d ed., with improved plates and demonstrations.
                  By John May.
Published:     Philadelphia, H. Orr, printer, 1866.
Description:   20 p. 3 fold. pl. 21 cm.
LC Call No.:   QA467.M46
Subjects:      Circle-squaring.
Control No.:   4525308

Author:        McInerney, T[imothy] [from old catalog]
Title:         Rectification of the circle,
Published:     [n.p., 1885]
Description:   8 p. 15 cm.
LC Call No.:   QA467.M15
Subjects:      Circle-squaring. [from old catalog]
Control No.:   9134641

Author:        Merceron, D[aniel] S. [from old catalog]
Title:         The square root of surds: solution fo the XLVII.
                  problem of Euclid, and square of the circle, with the true
                  method of finding the circumference.
Published:     Baltimore, Printed by S. Sands, 1848.
Description:   13 p. 23 cm.
LC Call No.:   QA467.M55
Subjects:      Circle-squaring. [from old catalog]
Control No.:   9603148

Author:        Monteil, Parfait Louis, 1855- [from old catalog]
Title:         Mesure de la longueur de la circonférence par la
                  valeur ...
Published:     Paris, H. Dunod et E. Pinat, 1917.
Description:   x, 56 p. diagrs. 27 x 22 cm.
LC Call No.:   QA467.M77
Subjects:      Circle-squaring. [from old catalog]
Control No.:   8245292

Author:        Montucla, Jean Etienne, 1725-1799.
Title:         Histoire des recherches sur la quadrature du
                  cercle, avec une addition concernant les problèmes de la
                  duplication du cube et de la trisection de l'angle. Par
                  Montucla.
Edition:       Nouv. éd., rev. et cor. [par S.F. Lacroix].
Published:     Paris, Bachelier père et fils, 1831.
Description:   xvi, 300 p. 4 fold. pl. 21 cm.
LC Call No.:   QA467.M81
Notes:         First edition appeared in 1754.
Subjects:      Circle-squaring.
               Geometry -- History.
Other authors: Lacroix, S. F. (Silvester François), 1765-1843,
                  ed.
Control No.:   4525259

Author:        Moore, Edward D. O. [from old catalog]
Title:         O. Moore's geometrical science.
Published:     New York, The Moss engraving company, 1890.
Description:   28 p. front. (port.) tables, diagr. 25 cm.
LC Call No.:   QA467.M82
Subjects:      Circle-squaring. [from old catalog]
Control No.:   7733325

Author:        Myers, William Alexander.
Title:         The quadrature of the circle, the square root of
                  two, and the right-angled triangle, by William Alexander
                  Myers.
Edition:       1st ed.
Published:     Cincinnati, Wilstach, Baldwin & Co., printers,
                  1873.
Description:   1 p. l., viii, [9]-150, 14 p., 1 l. incl. front.
                  diagrs. on xiii pl. 23 cm.
LC Call No.:   QA467.M99
Notes:         Appendix: A chapter on construction for the use
                  and benefit of draughtsmen, builders, and mechanics: 14 p. at
                  end.
               "History of the quadrature of the circle,
                  translated from the French of Montucla, by J. Babin": p.
                  [9]-33.
               Authors made use of in the present volume: p.
                  [iv]
Subjects:      Circle-squaring.
Other authors: Montucla, Jean Etienne, 1725-1799.
               Babin, J. tr.
Control No.:   10085256

Author:        O'Donnell, Elias. [from old catalog]
Title:         Resolución de la cuadratura del círculo, ó sea
                  de la relación exacta del diámetro à la circunferencia.
Published:     Buenos Aires, Impr. de P. E. Coni, 1870.
Description:   xxiv, 164, ii p. 4 fold. pl. 22 cm.
LC Call No.:   QA467.O26
               Microfilm 16305 QA
Control No.:   8666415

Author:        O'Donnelly, Terence Joseph. [from old catalog]
Title:         Solutio circuli quadraturæ problematis cum suis
                  sequelis de vera inclinatione ecliptici et magna astronomica
                  periodo.
Published:     Bruxellæ, Apud Perichon, 1853.
Description:   iv, 172 p. diagrs. 19 cm.
LC Call No.:   QA467.O29
Subjects:      Circle-squaring. [from old catalog]
Control No.:   7473364

Author:        Parker, John A.
Title:         The quadrature of the circle. Containing
                  demonstrations of the errors of geometry in finding the
                  approximation in use, the quadrature of the circle and
                  practical questions on the quadrature, applied to the
                  astronomical circles. With an appendix. By John A. Parker.
Published:     New York, S.W. Benedict, 1851.
Description:   2 p.l., [ix]-xi, [13]-212 p. diagrs. 23 cm.
LC Call No.:   QA467.P24 1851
Notes:         "A small edition only has been printed for free
                  distribution."-Pref.
Subjects:      Circle-squaring.
Control No.:   4053164

Author:        Parker, John A. [from old catalog]
Title:         Quadrature of the circle.
Published:     New York, J. Wiley & son, 1874.
Description:   1 p.l., [v]-vi, p. 1 l. 1 l., 24, 34, 33, 16 p.
                  diagr. 24 cm.
LC Call No.:   QA467.P24
Subjects:      Circle-squaring. [from old catalog]
Control No.:   8198269

Author:        Planas, Emilio. [from old catalog]
Title:         Cubismo, cuadratura del círculo (su
                  resolución)
Published:     Barcelona, A. Ortega, impresor, 1922.
Description:   4 p. l., vii-ix, 11-142 p., 1 l. diagrs. 19 cm.
LC Call No.:   QA467.P6
Subjects:      Circle-squaring. [from old catalog]
Control No.:   9662602

Author:        Raffalli, Antoine.
Title:         Découverte de la quadrature du cercle / par
                  Antoine Raffalli.
Published:     Bastia : C. Piaggi, 1905.
Description:   13 p. : ill. ; 24 cm.
LC Call No.:   QA467.R34x 1905
Notes:         Two diagrams on folded leaves inserted.
Subjects:      Circle-squaring.
Control No.:   4291663

Author:        Rudio, Ferdinand, 1856-1929.
Title:         Archimedes, Huygens, Lambert, Legendre. Vier
                  Abhandlungen über die Kreismessung. Deutsch Hrsg. und mit
                  einer Übersicht uber die Geschichte des Problemes von der
                  Quadratur des Zirkels, von den ältesten Zeiten bis auf
                  unsere Tage, versehen von Dr. F. Rudio ...
Published:     Leipzig, B. G. Teubner, 1892.
Description:   viii, 166 p. diagrs. 23 cm.
LC Call No.:   QA467.R83 1892
Notes:         I. Übersicht über die Geschichte des Prolemes
                  von der Quadratur des Zirkels, von den ältesten Zeiten bis
                  auf unsere Tage.--II. Archimedes. Kreismessung.--III.
                  Christian Huygens. Über die gefundene Grösse des
                  Kreises.--IV. Johann Heinrich Lambert. Vorläufige Kenntnisse
                  für die, so die Quadratur und Rectification des Circuls
                  suchen.--V. Adrien-Marie Legendre. Beweis, dass das
                  Verhältnis des Kreisumfanges zum Durchmesser und das Quadrat
                  desselben irrationale Zahlen sind.
Subjects:      Circle-squaring.
               Geometry -- History.
               Pi.
Other authors: Archimedes. Dimensio circuli, German.
               Huygens, Christiaan, 1629-1695.
               Lambert, Johann Heinrich, 1728-1777.
               Legendre, A. M. (Adrien Marie), 1752-1833.
Control No.:   9608609

Author:        Scribner, John C. [from old catalog]
Title:         Inventions, with investigations and demonstrative
                  diagrams, examples and explanations pertaining to geometry,
Published:     [Concord, N.H.] The author, 1875.
Description:   48 p. incl. 3 pl. 16 cm.
LC Call No.:   QA467.S43
Subjects:      Circle-squaring. [from old catalog]
Control No.:   7729541

Author:        Scribner, John C. [from old catalog]
Title:         Scribner's scientific planetary discoveries.
Published:     Concord, N.H., Printed by the Republican press
                  association, 1874.
Description:   3 p.l., 5-16 p. diagrs. 16 cm.
LC Call No.:   QA467.S43
Control No.:   10071440

Author:        Skinner, James Ralston. [from old catalog]
Title:         A criticism on the Legendre mode of the
                  rectification of the curve of the circle.
Published:     Cincinnati, R. Clarke & co., 1881.
Description:   22 p. diagrs. 23 cm.
LC Call No.:   QA467.S62
Subjects:      Circle-squaring. [from old catalog]
Control No.:   7261436

Author:        Smith, James, 1805-1872.
Title:         The geometry of the circle and mathematics as
                  applied to geometry by mathematicians, shewn to be a mockery,
                  delusion, and a snare. Letter to G.G. Stokes ... By James
                  Smith ...
Published:     Liverpool, E. Howell; London, Simpkin, Marshall &
                  co., 1869.
Description:   viii, 405 p., 1 l. 21 fold. diagr. 23 cm.
LC Call No.:   QA467.S65
Subjects:      Circle-squaring.
Control No.:   3579329

Author:        Smith, James, 1805-1872.
Title:         The problem of squaring the circle solved; or,
                  The true circumference and area of the circle discovered. By
                  James Smith.
Published:     London, Longman, Brown, Green, Longmans, &
                  Roberts; [etc.,etc.] 1859.
Description:   iv, [5]-37, [1] p. diagrs. 19 cm.
LC Call No.:   QA467.S68
Subjects:      Circle-squaring.
Control No.:   6849935

Author:        Vander Weyde, Peter Henri. [from old catalog]
Title:         The philosopher's stone,
Edition:       [2d ed.]
Published:     New York, D. Appleton & company, 1861.
Description:   v, 1 p., 1 l., [9]-40 p. 22 cm.
LC Call No.:   QA467.V24
Subjects:      Circle-squaring. [from old catalog]
Control No.:   6793067

Author:        Wallace, Ebenezer Erskine.
Title:         The circle squared; a solution of the problem of
                  squaring the circle, showing the exact ratio between radius
                  and quadrant, by Ebenezer Erskine Wallace.
Published:     Monmouth, Ill., E.E. Wallace, 1911.
Description:   20 p. diagrs. 26 x 15 cm.
LC Call No.:   QA467.W18 1911
ISBN:          $1.50
Subjects:      Circle-squaring.
Control No.:   2161902

Author:        Wallace, Ebenezer Erskine. [from old catalog]
Title:         The circle squared;
Edition:       [2d ed.]
Published:     Monmouth, Ill., E. E. Wallace, 1915.
Description:   20 p. diagrs. 24 cm.
LC Call No.:   QA467.W18 1915
Subjects:      Circle-squaring. [from old catalog]
Control No.:   5900059

Author:        Wallace, Ebenezer Erskine. [from old catalog]
Title:         The circle squared;
Published:     Monmouth, Ill., E. E. Wallace, 1903.
Description:   16 p. diagrs. 23 cm.
LC Call No.:   QA467.W18
Subjects:      Circle squaring. [from old catalog]
Control No.:   6324773

Author:        Ward, Russell. [from old catalog]
Title:         A general geometrical solution to the celebrated
                  question of squaring a circle.
Published:     Royalston, Mass., For the author, 1882.
Description:   1 p. l.,12 p. 20 cm.
LC Call No.:   QA467.W26
Subjects:      Circle-squaring. [from old catalog]
Control No.:   6324933

Author:        Willmon, J. C. (Jeremy Carlisle)
Title:         The secret of the circle and the square, by J.C.
                  Willmon.
Edition:       Author's ed.
Published:     Los Angeles, Cal., McBride press [1905]
Description:   1 p.l., 5-30 p. diagrs. 18 cm.
LC Call No.:   QA467.W712
Subjects:      Circle-squaring.
Control No.:   1689295

Author:        Willmon, J. C. (Jeremy Carlisle)
Title:         The secret of the circle and trisection of
                  angles, by Jeremy Carlisle Willmon.
Edition:       Author's ed.
Published:     Los Angeles, Cal., McBride press [1903]
Description:   1 p. l., 5-31 diagrs. 18 cm.
LC Call No.:   QA467.W71
Subjects:      Circle-squaring.
               Trisection of angle.
Control No.:   9605754

Author:        Wilson, Fred. [from old catalog]
Title:         A treatise on geometry, relating to the squaring
                  of the circle.
Published:     Portland, Or., D. Steel, 1890.
Description:   24 p. diagr. 24 cm.
LC Call No.:   QA467.W74.
Subjects:      Circle-squaring. [from old catalog]
Control No.:   8666416

Author:        Benson, Lawrence Sluter. [from old catalog]
Title:         Mathematics out of joint.
Published:     New York [n.d.]
Description:   Broadside. 28 x 21 cm.
LC Call No.:   QA468.B47
Subjects:      Trisection of angles. [from old catalog]
Control No.:   9606335

Author:        Benson, Lawrence Sluter. [from old catalog]
Title:         A vital question in mathematics.
Published:     New York [n.d.]
Description:   broadside. 28 x 22 cm.
LC Call No.:   QA468.B473
Subjects:      Trisection of angles. [from old catalog]
Control No.:   10074650

Author:        Blom, Hans Ørn, 1817-1885.
Title:         Solution du problême de diviser l'angle en trois
                  parties égales par des lignes droites et circulaires.
Published:     Christiania, Imp. Chez J. C. Abelsted, 1871.
Description:   [6] p., 1 l. diagrs. 23 cm.
LC Call No.:   QA468.B6
Subjects:      Trisection of angle. [from old catalog]
Control No.:   8235115

Author:        Brennan, Michael H. [from old catalog]
Title:         The trisection of the arc,
Published:     Devils Lake, Dakota, M. H. Brennan, 1888.
Description:   23, [1] p. diagr. 22 cm.
LC Call No.:   QA468.B8.
Subjects:      Trisection of angle. [from old catalog]
Control No.:   5857050

Author:        Callahan, Jeremiah Joseph, 1878- [from old
                  catalog]
Title:         The trisection of the angle; the trigonometric
                  function of one-third of an angle in terms of the functions
                  of tha angle.
Published:     Pittsburgh, Pa., Duquesne university, 1931.
Description:   29 p. diagrs. 23 cm.
LC Call No.:   QA468.C3
Subjects:      Trisection of angle. [from old catalog]
Control No.:   5943122

Author:        Davis, James P. [from old catalog]
Title:         The relations between the chord or sine of an
                  arc, and the chord or sine of three-times-five-times the arc,
                  etc., etc., also between the sine of an arc and the sine of
                  one-third of one-fifth, etc. ...
Published:     Newport, Eng., J. E. Southall, printer, 1886.
Description:   16 p. fold. diagr. 19 cm.
LC Call No.:   QA468.D2
Subjects:      Trisection of angle. [from old catalog]
Control No.:   7729544

Author:        Dexter, Orrando Perry, 1854-1903. [from old
                  catalog]
Title:         The division of angles.
Published:     New York, The American news company, 1881.
Description:   36 p. front., diagrs. (1 fold.) 27 cm.
LC Call No.:   QA468.D5
Subjects:      Trisection of angle. [from old catalog]
Control No.:   10069748

Author:        Douglas, William D. [from old catalog]
Title:         The geometrical problem solved.
Published:     Orange, N.J., Davis, Douglas & co., 1892.
Description:   22 p. illus., 20 diagr. (14 p.) 18 cm.
LC Call No.:   QA468.D73
Subjects:      Trisection of angle. [from old catalog]
Control No.:   9602050

Author:        Edwards, H[enry] A[lyn], 1864- [from old
                  catalog]
Title:         A new method of trisecting any angle and of
                  constructing a regular pentagon with ruler and compasses,
                  together with their uses in solving other geometric and
                  mathematical problems.
Published:     [Slater? Mo.] 1904.
Description:   [1], 6 p. diagrs. 16 x 9 cm.
LC Call No.:   QA468.E26
Subjects:      Trisection of angle. [from old catalog]
Control No.:   6328661

Author:        Galt, William R. [from old catalog]
Title:         Two geometrical problems. I. To trisect an angle.
                  II. To construct a regular nonagon.
Published:     Norfolk? Va., 1879.
Description:   1 l. 1 pl. 26 cm.
LC Call No.:   QA468.G1
Subjects:      Trisection of angle.
Control No.:   12909521

Author:        Gliebe, Julius Joseph, father, 1880- [from old
                  catalog]
Title:         The mathematical atom; its involution and
                  evolution exemplified in the trisection of the angle;
Published:     San Francisco, Calif., St. Boniface Franciscan
                  friary, 1933.
Description:   4 p.l., [5]-87 p. illus., diagrs. 18 cm.
LC Call No.:   QA468.G6 1933
Subjects:      Trisection of angle. [from old catalog]
Control No.:   8758531

Author:        Hanson, Eugene John, 1881- [from old catalog]
Title:         The theory of trisection and applied geometry.
Edition:       1st ed.
Published:     San Francisco, Printed by Isogonica, c1951.
Description:   22 l. diagrs. 26 cm.
LC Call No.:   QA468.H3
Subjects:      Trisection of angle. [from old catalog]
               Geometry. [from old catalog]
Control No.:   8370636

Author:        Hippauf, Hermann.
Title:         Lösung des Problems der Trisection mittelst der
                  Conchoide auf circularer Basis.
Published:     Leipzig, B. G. Teubner, 1872.
Description:   [3]-32 p. 2 fold. pl. 21 cm.
LC Call No.:   QA468.H6.
Notes:         Cover-title.
               Inaug.-diss.--Jena.
Subjects:      Trisection of angle
Control No.:   6793072

Author:        Hirst, Byron D. [from old catalog]
Title:         Solution of an insolvable problem,
Published:     [Youngstown, Ohio] c1932.
Description:   [4] p. diagrs. 23 cm.
LC Call No.:   QA468.H63
Subjects:      Trisection of angle. [from old catalog]
Control No.:   6410777

Author:        Jacobi, Andreas, 1801-1875.
Title:         De undecimo Euclidis axiomate iudicium cui
                  accedunt pauca De trisectione anguli / auctore Andrea
                  Iacobi.
Published:     Ienae : Libraria Croekeria, 1824.
Description:   54 p., [1] folded leaf of plates : ill. ; 24 cm.
LC Call No.:   QA468.J32x 1824
Notes:         "In certamine litterario civium Academiae
                  Ienensis die VI septembris MDCCCXXIII praemio principum
                  munificentia constituto ex sententia illustris philosophorum
                  ordinis ornatum."
               Includes bibliographical references.
Subjects:      Trisection of angle.
               Euclid. Elements.
Control No.:   2400412

Author:        Johnston, Noe. [from old catalog]
Title:         Johnston's geometrical division and measurement
                  of arcs and angles,
Published:     Bronson, Mich., Journal press, 1900.
Description:   10 p. diagrs. 22 cm.
LC Call No.:   QA468.J7
Subjects:      Trisection of angle. [from old catalog]
Control No.:   7253277

Author:        Katona, Diénes. [from old catalog]
Title:         Trisectio anguli acuti, a Dionysio Katona ...
Published:     Pestini, typis Trattner Karolyianis, 1852.
Description:   6 p. 1 pl. 25 cm.
LC Call No.:   QA468.K1
Subjects:      Trisection of angle. [from old catalog]
Control No.:   6324936

Author:        Lagarrigue, John Francis. [from old catalog]
Title:         Geometry of motion:
Published:     New-York, 1831.
Description:   4 p. l., 68 p. 3 fold. pl. 21 cm.
LC Call No.:   QA468.L17
Subjects:      Trisection of angle. [from old catalog]
Control No.:   8666421

Author:        Lanigan, John A. [from old catalog]
Title:         The trisection of the angle.
Published:     Hyde Park, Mass., Randall & Langley, printers,
                  1890.
Description:   15 p. diagr. 22 cm.
LC Call No.:   QA468.L2
Subjects:      Trisection of angle. [from old catalog]
Control No.:   8198273

Author:        McClay, Lucy A. [from old catalog]
Title:         Trisecting an angle of any general magnitude,
Published:     [West Plains, Mo., c1934]
Description:   6 p. diagr. 28 cm.
LC Call No.:   QA468.M3
Subjects:      Trisection of angle. [from old catalog]
Control No.:   10164458

Author:        McGrath, John J.
Title:         The secant trisector and methods of trisecting an
                  angle / by John J. McGrath.
Published:     Chicago : J.J. McGrath, c1940.
Description:   [3] p., [2] folded leaves of plates : ill. ; 21
                  cm.
LC Call No.:   QA468.M32x 1940
Notes:         Cover title.
Subjects:      Trisection of angle.
Control No.:   4764758

Author:        More, Egbert.
Title:         The trisection of a given angle geometrically
                  solved and illustrated / by Egbert More.
Published:     Denver : E. More, 1901.
Description:   7 p., [1] leaf of plates : ill. ; 24 cm.
LC Call No.:   QA468.M67x 1901
Notes:         Cover title.
Subjects:      Trisection of angle.
Control No.:   983717

Author:        Olán, Johan W. Th. [from old catalog]
Title:         Trisectio arcus et anguli,
Published:     Gothenburg, G. Wennerholm's printing office,
                  1906.
Description:   1 p.l., 8, [1] p. 24 x 32 cm.
LC Call No.:   QA468.O6
Subjects:      Trisection of angle. [from old catalog]
Control No.:   9666829

Author:        O'Sullivan, Martin J. [from old catalog]
Title:         Problem: to trisect an angle by (1) Carpenter's
                  square alone. (2) Auxiliary curve. (3) Straight edge and
                  compases. And why the radius spans the circle six times.
Published:     Monroe, Wash., 1928.
Description:   6 p. 23 cm.
LC Call No.:   QA468.O65
Subjects:      Trisection of angle. [from old catalog]
Control No.:   9209760

Author:        Pfeifer, W[illiam] H[ollis] [from old catalog]
Title:         Doubling the arc and trisection of the angle;
Published:     [Rosebud? S.D., c1904]
Description:   [5] p. 2 diagr. 27 x 21 cm.
LC Call No.:   QA468.P52
Subjects:      Trisection of angle. [from old catalog]
Control No.:   8205565

Author:        Samsonoff, Joseph. [from old catalog]
Title:         The trisection of an angle,
Published:     [New York, Publishers printing company, c1914]
Description:   12 p. diagrs. 23 cm.
LC Call No.:   QA468.S3
Subjects:      Trisection of angle. [from old catalog]
Control No.:   7300603

uthor:        Sherrod, Fletcher. [from old catalog]
Title:         Geometry:
Published:     New Orleans, La., c1932-1933.
Description:   [14] p. diagrs. 22 cm.
LC Call No.:   QA468.S45 1933
Subjects:      Trisection of angle. [from old catalog]
Control No.:   10160697

Author:        Sidler, Georg [Joseph], 1831- [from old catalog]
Title:         Zur dreitheilung eines kreisbogens,
Published:     Bern, Jent & Reinert, 1876.
Description:   1 p.l., 12 p. 3 fold. pl. 26 cm.
LC Call No.:   QA468.S5
Subjects:      Trisection of angle. [from old catalog]
Control No.:   5857053

Author:        Stoops, W. H. [from old catalog]
Title:         A general method for the geometric trisection of
                  angles and arcs.
Published:     [n. p.] [1902]
Description:   1 v. cm.
LC Call No.:   QA468.S895
Control No.:   7201552

Author:        Stoops, William H. [from old catalog]
Title:         A general method for the geometric trisection of
                  angles and arcs ...
Published:     [Riverside, N.J., 1902]
Description:   p. 21 cm.
LC Call No.:   QA468.S88
Control No.:   9087580

Author:        Stoops, William H. (William Henry), 1853-
Title:         A general method for the geometric trisection of
                  angles and arcs, with accompanying diagrams; supplemented
                  with a formal proof and a trigonometrical analysis. By
                  William H. Stoops ...
Published:     [Bethlehem, Pa., The Keystone printing co.,
                  1902]
Description:   vii, 34 p. diagr. 22 cm.
LC Call No.:   QA468.S89
Subjects:      Trisection of angle.
Control No.:   2633868

Author:        Turbyfill, D. T. (Daniel Theodore), 1880-
Title:         To trisect any angle; containing an algebraic
                  expression deduced from geometrical principles, which
                  trisects any angle. By D.T. Turbyfill ...
Published:     Sulphur Springs, Tex., J.W. Avera print, 1904.
Description:   5 p. 21 cm
LC Call No.:   QA468.T93
Notes:         Cover-title.
Subjects:      Trisection of angle.
Control No.:   272704

Author:        Turbyfill, D[aniel] T[heodore], 1880- [from old
                  catalog]
Title:         To trisect any angle; containing an algebraic
                  expression deduced from geometrical principles, which
                  trisects any angle.
Published:     [n.p.] c1904.
Description:   1 p.l., 8 p. illus. (port.) diagrs. 21 cm.
LC Call No.:   QA468.T94
Subjects:      Trisection of angle. [from old catalog]
Control No.:   8677310

Author:        Whited, Kirk. [from old catalog]
Title:         Trisection of an angle; the problem solved
                  geometrically, with other problems ...
Published:     Redmond, Or., The author, 1917.
Description:   13, [1] p., 1 l. diagrs. 26 cm.
LC Call No.:   QA468.W6
Subjects:      Trisection of angle. [from old catalog]
Control No.:   5904708

Author:        Willmon, Jeremy Carlisle. [from old catalog]
Title:         Trisection of angles,
Edition:       Author's ed.
Published:     [Los Angeles? Cal., 1902]
Description:   19 p. diagr. 18 cm.
LC Call No.:   QA468.W7
Subjects:      Trisection of angle. [from old catalog]
Control No.:   10068656

Author:        Yates, Robert C. (Robert Carl), 1904-1963.
Title:         The trisection problem [by] Robert C. Yates.
Published:     [Baton Rouge, The Franklin Press] 1942.
Description:   68 p. illus., diagrs. 24 cm.
LC Call No.:   QA468.Y3
Dewey No.:     513.9
Notes:         Facsimiles on lining-paper.
               Bibliography: p. [67]-68.
Subjects:      Trisection of angle.
Control No.:   9260457

Author:        Young, Edward H. [from old catalog]
Title:         Tri-secting an angle by compass and straight edge
                  ...
Published:     [n.p.] 1931.
Description:   1 leaf fol. cm.
LC Call No.:   QA468.Y6
Control No.:   10019515

Author:        Young, Edward H. [from old catalog]
Title:         The true value of Pi.
Published:     [n.p.] 1921.
Description:   1 leaf fol. cm.
LC Call No.:   QA468.Y62
Control No.:   7209538

Author:        Zielinski, Adalbert A. [from old catalog]
Title:         Euclidian trisection, quintisection and
                  hexasection;
Published:     Buffalo, N.Y., 1932.
Description:   iv, 20 p. diagrs. 21 cm.
LC Call No.:   QA468.Z5
Subjects:      Angles (Geometry)
Control No.:   9691876

Author:        Casanova, Giacomo, 1725-1798.
Title:         Les connaissances mathématiques de Jacques
                  Casanova de Seingalt;
Published:     Roma, 1882.
Description:   p. 637-669. 31 cm.
LC Call No.:   QA469.C3
Subjects:      Cube, Duplication of.
Control No.:   7726727

Author:        Fusco, Ricciotto E. E. L. [from old catalog]
Title:         The duplication of the cube or Delian problem.
Published:     Brooklyn [c1950]
Description:   16 p. illus. 23 cm.
LC Call No.:   QA469.F9
Subjects:      Cube, Duplication of.
Control No.:   8406962
