#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Lindgren, Birger.
Title:         Sur "Le cas d'exception de M. Picard" dans la
                  théorie des fonctions entières / par Birger Lindgren.
Published:     Uppsala : Impr. Almqvist & Wiksell, 1903.
Description:   38 p. : ill. ; 26 cm.
LC Call No.:   QA353.E5L56 1903
Notes:         Thesis (doctoral)--Uppsala universitet, 1903.
               Includes bibliographical references.
Subjects:      Functions, Entire.
Control No.:   4308522

Author:        Robinson, David Anton Frederick, 1886-
Title:         Fourier expansions of pseudo-doubly periodic
                  functions and applications.
Published:     1930.
Description:   viii, 58 l. 29 cm.
LC Call No.:   QA353.P4R62
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Periodic functions.
               Fourier series.
Control No.:   2208054

Author:        Dimsdale, Bernard, 1912-
Title:         Lacunary orthogonal polynomials, by Bernard
                  Dimsdale.
Published:     [n.p., 1942]
Description:   [1], [608]-617 p. 24 cm.
LC Call No.:   QA355.D5
Notes:         Thesis (PH. D.)--University of Minnesota, 1940.
               Thesis t.-p. and Vita on p. [2] of cover.
               A reprint from the Bulletin of the American
                  Mathematical Society, v. 48, no. 8, Aug. 1942, with title:
                  Approximation of continous functions by means of lacunary
                  polynomials.
Subjects:      Functions, Orthogonal.
               Numerical analysis.
Control No.:   7391158

Author:        Heyda, James Francis, 1913- [from old catalog]
Title:         Uniqueness properties over sets of positive
                  linear measure of functions of a complex variable,
Published:     Urbana, Ill., 1940.
Description:   1 p.l., 12 p. 23 cm.
LC Call No.:   QA355.H4 1940
Subjects:      Functions of complex variables.
Control No.:   9722831

Author:        Matison, Harry, 1910-
Title:         On certain classes of integral functions, by
                  Harry Matison
Published:     Durham, N.C., 1938
Description:   1p.l., p.9-29 26 cm.
LC Call No.:   QA355.M37 1938
Notes:         "Reprinted from the Duke mathematical journal,
                  vol. 4, no. 1, March, 1938."
               Thesis (Ph. D.)--Princeton university,1936.
Subjects:      Functions.

Author:        Risselman, William Charles, 1900-
Title:         Approximation to a given function by means of
                  polynomials in another given function, by William Charles
                  Risselman.
Published:     [New York, 1938]
LC Call No.:   QA355.R58 1928
Dewey No.:     517.5
Notes:         Thesis (Ph. D.)--University of Minnesota, 1928.
               Thesis t.-p. with "Vita" mounted on p. [2] of
                  cover.
               "Reprinted from bulletin of the American
                  Mathematical Society, April,1938."
Subjects:      Functions.
               Polynomials.
Control No.:   7375699

Author:        Bähr, Ernst Eduard, 1880- [from old catalog]
Title:         Abbildung einer unendlichen ebene,
Published:     Jena, Druck von B. Vopelius, 1905.
Description:   p. cm.
LC Call No.:   QA360.B3 1905
Subjects:      Surfaces, Representation of. [from old catalog]
               Functions. [from old catalog]
Control No.:   6340907

Author:        Bergman, Stefan, 1898-
Title:         The kernel function and conformal mapping.
Published:     New York, American Mathematical Society, 1950.
Description:   vii, 161 p. illus. 26 cm.
Series:        Mathematical surveys, no. 5
LC Call No.:   QA360.B36
Dewey No.:     517.5
Notes:         Bibliography: p. 151-158.
Subjects:      Surfaces, Representation of.
Series Entry:  Mathematical surveys ; no. 5.
Control No.:   7899727

Author:        Bergman, Stefan, 1898-
Title:         Partial differential equations, advanced topics,
                  by Stefan Bergman.
Published:     Providence, R.I. [1941]
Description:   1 v. diagrs. 28 cm.
LC Call No.:   QA360.B37
Notes:         At head of title: Brown university. Summer
                  session for advanced instruction and research in mechanics.
                  June 23-September 13, 1941.
               Leaves variously numbered; mimeographed.
               Includes bibliographical references.
Subjects:      Differential equations, Partial.
               Surfaces, Representation of.
Other authors: Brown University. Graduate School.
Control No.:   13164029

Author:        Bonsdorff, Ernst Jacob Waldemar, 1842- [from old
                  catalog]
Title:         Den geometriska theorin för complexa funktioner
                  tillämpad på elliptiska integralen af första ordningen
                  ...
Published:     Helsingfors, J. C. Frenckell & son, 1870.
Description:   1 p.l., 65 p. diagrs. on 1 pl. 26 x 21 cm.
LC Call No.:   QA360.B6 1870
Subjects:      Functions. [from old catalog]
Control No.:   10090635

Author:        Study, E. (Eduard), 1862-1930.
Title:         Vorlesungen über ausgewählte gegenstände der
                  geometrie, von E. Study ...
Published:     Leipzig, Berlin, B.G. Teubner, 1911-13.
Description:   2 v. diagrs. 24 cm.
LC Call No.:   QA360.S75
Dewey No.:     517.5
Notes:         Vol. 2: herausgegeben unter mitwirkung von W.
                  Blaschke.
               1. hft. Ebene analytische kurven und zu ihnen
                  gehörige abbildungen.--2. hft. Konforme abbildung
                  einfach-zusammenhängender bereiche.
Subjects:      Geometry.
               Functions.
Other authors: Blaschke, Wilhelm, 1885-
Control No.:   1689828

Title:         Topological methods in differential equations and
                  inclusions / edited by Andrzej Granas and Marlène Frigon,
                  and technical editor, Gert Sabidussi.
Published:     Dordrecht ; Boston : Kluwer Academic Publishers,
                  c1995.
Description:   xv, 522 p. : ill. ; 25 cm.
Series:        NATO ASI series. Series C, Mathematical and
                  physical sciences ; vol. 472
LC Call No.:   QA370.T66 1995
Dewey No.:     515/.355 20
ISBN:          079233678X (hb : alk. paper)
Notes:         "Published in cooperation with NATO Scientific
                  Affairs Division."
               "Proceedings of the NATO Advanced Study Institute
                  and Séminaire de mathématiques supérieures on Topological
                  Methods in Differential Equations and Inclusions, Montreal,
                  Canada, July 11-22, 1994"--T.p. verso.
               "Contributions to the 33rd session of the
                  Séminaire de mathématiques supérieures (SMS) on
                  'Topological Methods in Differential Equations and
                  Inclusions' ... [which] took place at the Université de
                  Montréal in July 1994"--Pref.
               Includes bibliographical references and index.
               English, with two contributions in French.
Subjects:      Differential equations -- Numerical solutions --
                  Congresses.
               Differential inclusions -- Congresses.
               Fixed point theory -- Congresses.
Other authors: Granas, Andrzej.
               Frigon, Marlène.
               Sabidussi, Gert.
Other authors: North Atlantic Treaty Organization. Scientific
                  Affairs Division.
Other authors: NATO Advanced Study Institute and Séminaire de
                  mathématiques supérieures on Topological Methods in
                  Differential Equations and Inclusions (1994 : Montréal,
                  Québec)
Series Entry:  NATO ASI series. Series C, Mathematical and
                  physical sciences ; no. 472.
Control No.:   3506661

Author:        Bellman, Richard Ernest, 1920-
Title:         Differential-difference equations [by] Richard
                  Bellman [and] Kenneth L. Cooke.
Published:     New York, Academic Press, 1963.
Description:   462 p. illus. 24 cm.
Series:        Mathematics in science and engineering, v. 6
LC Call No.:   QA373.B4
Dewey No.:     517.38
Notes:         Includes bibliography.
Subjects:      Differential-difference equations.
Other authors: Cooke, Kenneth L., joint author.
Series Entry:  Mathematics in science and engineering ; v. 6.
Control No.:   1222553

Author:        Philippov Mikhail, 1858- [from old catalog]
Title:         Sur les invariants des équations
                  différentielles linéaires ...
Published:     Heidelberg, C. Winter, 1892.
Description:   1 p.l., 64 p., 1 l. 23 cm.
LC Call No.:   QA375.P55
Subjects:      Differential invariants. [from old catalog]
Control No.:   5860321

Author:        Sulzberger, Siegmund, 1862-
Title:         Die reellen Transformationsgruppen der Geraden
                  und der Ebene ...
Published:     Leipzig-Reudnitz, Druck von M. Hoffmann, 1889.
Description:   49 p., 1 L. 23 cm.
LC Call No.:   QA375.S95
Notes:         Vita.
               Inaug.-diss.--Leipzig.
Subjects:      Continuous groups
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.18.
Control No.:   10074469

Author:        Umlauf, Karl Arthur, 1866-
Title:         Über die zusammensetzung der endlichen
                  continuierlichen transformationsgruppen, insbesondre der
                  gruppen vom range null ...
Published:     Leipzig, Druck von Breitkopf & Härtel, 1891.
Description:   79, [1] p. 24 cm.
LC Call No.:   QA375.U52
Notes:         Thesis--Leipzig.
               Lebenslauf.
Subjects:      Continuous groups.
Control No.:   7732589

Author:        Vukiâceviâc, Petar L., 1862- [from old catalog]
Title:         Die invarianten der linearen homogenen
                  differential-gleichungen nter ordnung ...
Published:     Berlin, Druck von Gebr. Unger (T. Grimm) 1894.
Description:   2 p.l., 42, [2] p. 28 cm.
LC Call No.:   QA375.V98
Subjects:      Differential invariants. [from old catalog]
Control No.:   5860320

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Sulla teorica generale dei parametri
                  differenziali. Memoria del Prof. E. Beltrami letta nella
                  sessione 25 febbraio 1869 dell' Accademia delle scienze dell'
                  Istituto di Bologna.
Published:     Bologna, Tipi Gamberini e Parmeggiani, 1869.
Description:   44 p. 30 cm.
LC Call No.:   QA381.B4
Subjects:      Differential invariants. [from old catalog]
Control No.:   7264558

Author:        Bouton, Charles Leonard, 1869-
Title:         Invariants of the general linear differential
                  equation and their relation to the theory of continuous
                  groups.
Published:     Baltimore, Friedenwald [1898]
Description:   62 p. 31 cm.
LC Call No.:   QA381.B78
Notes:         Inaug.-dis.--Leipzig.
               Vita.
Subjects:      Differential invariants.
Control No.:   8670509

Author:        Cohn, Richard M, 1919- [from old catalog]
Title:         Manifolds of difference polynomials.
Published:     [n.p., 1948]
Description:   133-172 p. 26 cm.
LC Call No.:   QA381.C73
Subjects:      Polynomials. [from old catalog]
Control No.:   8362575

Author:        Cotton, Émile [Clément], 1872- [from old
                  catalog]
Title:         Sur les variétés à trois dimensions ...
Published:     Paris, Gauthier-Villars, 1899.
Description:   3 p.l., 54 p., 1 l. 28 x 22 cm.
LC Call No.:   QA381.C8
Subjects:      Differential invariants. [from old catalog]
Control No.:   5871457

Author:        Dearborn, Donald Curtis, 1910- [from old
                  catalog]
Title:         Inequalities among the invariants of Pfaffian
                  systems,
Published:     [Durham, N.C., 1936]
Description:   p. 705-711. 26 cm.
LC Call No.:   QA381.D4 1936
Subjects:      Pfaffian systems.
Control No.:   5966482

Author:        Fischer, Albrecht, 1866-
Title:         Über die invarianten der linearen, homogenen
                  differentialgleichungen sechster ordnung ...
Published:     Halle a.S., 1891.
Description:   32 p. 23 cm.
LC Call No.:   QA381.F52
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Differential invariants.
Control No.:   6797205

Author:        Goursat, Edouard, 1858-1936.
Title:         Leçons sur le problème de Pfaff, par Édouard
                  Goursat.
Published:     Paris, J. Hermann, 1922.
Description:   2 p. l., [vii]-viii, 386 p., 1 l. 25 cm.
LC Call No.:   QA381.G6
Dewey No.:     517.38
Subjects:      Pfaffian problem.
Control No.:   8778966

Author:        Griffin, Mabel.
Title:         Invariants of Pfaffian systems, by Mabel Griffin
                  ...
Published:     [New York, n.p., 1933]
Description:   1 p. l., p. 929-939. 28 cm.
LC Call No.:   QA381.G67 1933
Notes:         Thesis (Ph. D.)--Duke university, 1933.
               From Transactions of the American mathematical
                  society, v. 35, October, 1933.
Subjects:      Pfaffian systems.
               Invariants.
Control No.:   5959840

Author:        Harnack, Axel, 1851-1888.
Title:         Über eine behandlungsweise algebraischer
                  differentiale in homogenen coordinaten ...
Published:     Leipzig, Druck von B.G. Teubner, 1876.
Description:   56 p. 24 cm.
LC Call No.:   QA381.H28
Notes:         Habilitationsschrift--Leipzig.
               "Besonderer abdruck aus dem IX. bande der
                  Mathematischen annalen."
Subjects:      Differential forms.
Control No.:   7268593

Author:        Haskins, Charles N. [from old catalog]
Title:         [Collected papers, reprints, etc., on
                  differential forms and in variants]
Published:     [n. p., n. d.]
Description:   v. cm.
LC Call No.:   QA381.H3
Control No.:   6728561

Author:        Heineck, Karl, 1877- [from old catalog]
Title:         Invariante kurvenintegrale bei infinitesimalen
                  transformationen in drei veränderlichen x, y, z und deren
                  verwertung ...
Published:     Leipzig, Druck von B. G. Teubner, 1899.
Description:   75, [1] p., 1 l. 22 cm.
LC Call No.:   QA381.H46
Subjects:      Differential invariants. [from old catalog]
Control No.:   10075576

Author:        Henrici, Olaus [Magnus Friedrich Erdmann], 1840-
                  [from old catalog]
Title:         Transformation von differentialausdrücken erster
                  ordnung zweiten grades mit hülfe der verallgemeinerten
                  elliptischen coordinaten ...
Published:     Berlin, Druck von G. Reimer, 1865.
Description:   1 p.l., 25 p. 27 cm.
LC Call No.:   QA381.H51
Subjects:      Differential forms.
               Coordinates, Elliptic.
Control No.:   7733675

Author:        Hessenberg, Gerhard Wilhelm, 1874-1925. [from old
                  catalog]
Title:         Über die invarianten linearer und quadratischer
                  binärer differentialformen und ihre anwendung auf die
                  deformation der flächen ...
Published:     [Stockholm, Gedruckt in der Central-druckerei,
                  1899]
Description:   4 p.l., 50 p. 29 cm.
LC Call No.:   QA381.H58
Subjects:      Differential forms.
               Surfaces, Deformation of.
Control No.:   9127369

Author:        Ingold, Louis, b. 1872.
Title:         Vector interpretation of symbolic differential
                  parameters ... by Louis Ingold ...
Published:     [Lancaster, Pa., 1910]
Description:   1 p.l., 26 p., 1 l. 28 cm.
LC Call No.:   QA381.I6
Notes:         Thesis (PH. D.)--University of Chicago, 1907.
               Biographical sketch.
               "Reprinted from the Transactions of the American
                  mathematical society, v. 11, 1910, p. 449-474."
               "Presented to the Society (Chicago) March 30,
                  1907, in somewhat different form under the title: Vector
                  theory, in terms of symbolic differential parameters."
Subjects:      Differential forms.
               Ausdehnungslehre.
Control No.:   1689768

Author:        Levi, Howard, 1916-
Title:         On the structure of differential polynomials and
                  on their theory of ideals, by Howard Levi ...
Published:     [n. p., 1942]
Description:   [1], 532-568 p. 28 cm.
LC Call No.:   QA381.L4
Notes:         Thesis (Ph. D.)--Columbia university, 1942.
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 51, no. 3 ... May, 1942."
               Vita: p. [3] of cover.
               Bibliographical foot-notes.
Subjects:      Polynomials.
               Differential forms.
Control No.:   7385698

Author:        Lindelöf, Ernst Leonard, 1870-
Title:         Sur les systèmes complets et le calcul des
                  invariants différentiels des groupes continus finis ...
Published:     Helsingfors, Impr. de la Société de
                  littérature finnoise, 1893.
Description:   1 p. l., 62 p. 30 cm.
LC Call No.:   QA381.L74
Notes:         Inaug.-dis.--Helsingfors.
Subjects:      Differential invariants.
Control No.:   12911688

Author:        Maschke, H. (Heinrich), 1853-1908.
Title:         Invariants of differential quantities, by H.
                  Maschke ...
Published:     Chicago, The University of Chicago press, 1903.
Description:   14 p. 28 cm.
LC Call No.:   QA381.M4
Notes:         Printed from First series, v. 9 (p. 127-138) of
                  the Decennial publications of the University of Chicago.
Subjects:      Differential invariants.
Control No.:   1689161

Author:        Mullins, George W. (George Walker), b. 1881.
Title:         Differential invariants under the inversion group
                  / by George Walker Mullins.
Published:     Lancaster, Pa. : Press of the New era printing
                  company, 1917.
Description:   22 p., ; 24 cm.
LC Call No.:   QA381.M8
Notes:         Thesis (PH. D.)--Columbia university, 1917.
               Vita.
Subjects:      Differential invariants.
Control No.:   5904376

Author:        Noth, Gottfried Hermann, 1879-
Title:         Differentialinvarianten und invariante
                  Differentialgleichungen zweier zehngliedriger Gruppen ...
Published:     Leipzig, Druck von B. G. Teubner, 1904.
Description:   32 p., 1 L. 23 cm.
LC Call No.:   QA381.N8
Notes:         Lebenslauf.
               Issued also in Berichte über die Verhandlungen
                  der K. Sächsischen gesellschaft der wissenschaften zu
                  Leipzig, vol. 56, 1904.
               Inaug.-diss.--Leipzig.
Subjects:      Transformations (Mathematics)
Other authors: Noth, Gottfried Hermann, 1879- Pamphlets.
Control No.:   6336936

Author:        Patterson, Boyd Crumrine, 1902-
Title:         The differential invariants of inversive geometry
                  ... by Boyd C. Patterson ...
Published:     [Baltimore, 1928]
Description:   1 p. l., p. 553-568, 1 l. 25 cm.
LC Call No.:   QA381.P3 1926
Notes:         Thesis (Ph. D.)--Johns Hopkins University, 1926.
               Vita.
               "Reprinted from the American journal of
                  mathematics, vol. L, number 4."
Subjects:      Differential invariants.
Control No.:   7806142

Author:        Pfaff, Johann Friedrich, 1765-1825.
Title:         Allgemeine methode partielle
                  differentialgleichungen zu integriren, von Johann Friedrich
                  Pfaff (1815) Aus dem lateinischen übers. und hrsg. von
                  Gerhard Kowalewski.
Published:     Leipzig, W. Engelmann, 1902.
Description:   84 p. 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 129
LC Call No.:   QA381.P5
Notes:         Presented before the K. Akad. der wissenschaften,
                  Berlin, under title: Methodus generalis, aequationes
                  differentiarum partialium, nec non aequationes differentiales
                  vulgares, utrasque primi ordinis, inter quotcunque
                  variabiles, complete integrandi.
               Published in Berlin, Akad. abhandl., 1814-15.
Subjects:      Differential equations, Partial.
Other authors: Kowalewski, Gerhard, 1876-1950, tr. and ed.
Series Entry:  Ostwalds Klassiker der exakten Wissenschaften ;
                  Bd. 129.
Control No.:   2161060

Author:        Rainville, Earl David, 1907-
Title:         Linear differential invariance under an operator
                  related to the Laplace transformation ... by Earl D.
                  Rainville.
Published:     [Baltimore, 1940.
Description:   1 p. L., p. 391-405. 25 cm.
LC Call No.:   QA381.R25 1940
Dewey No.:     517.38
Notes:         "Reprinted from the American journal of
                  mathematics, vol. LXII, number 2 [1940]"
               Thesis (Ph. D.)--University of Michigan, 1939.
Subjects:      Differential invariants
               Differential equations, Linear
Control No.:   6444521

Author:        Raudenbush, Henry William, 1902-
Title:         Differential fields and ideals of differential
                  forms, by Henry William Raudenbush ...
Published:     Princeton, N.J. [Printed by Lütcke & Wulff,
                  Hamburg, Ger.] 1933.
Description:   1 p. l., 509-517, [1] p. 26 cm.
LC Call No.:   QA381.R3 1933
Notes:         Thesis (Ph. D.)--Columbia university, 1933.
               Vita.
               "Reprinted from the Annals of mathematics, vol.
                  34 (1933)."
Subjects:      Differential forms.
Control No.:   7355723

Author:        Reingold, Haim.
Title:         Invariants of a system of linear homogeneous
                  differential equations of the second order ... by H. Reingold
                  ...
Published:     [Durham, N.C., 1940]
Description:   p. 141-147 26 cm.
LC Call No.:   QA381.R4 1940
Dewey No.:     517.38
Notes:         Cover-title.
               Thesis (Ph. D.)--University of Cincinnati, 1938.
               "By I.A. Barnett and H. Reingold."
               "Reprinted from Duke mathematical journal, vol.
                  6, no. 1, March, 1940."
Subjects:      Differential invariants.
               Differential equations, Linear.
Other authors: Barnett, Israel Albert, 1894- joint author.
Control No.:   6911888

Author:        Simonds, Eugene Francis, 1885- [from old
                  catalog]
Title:         Invariants of differential configurations in the
                  plane,
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1919.
Description:   1 p.l., p. 223-250, 1 l. 28 cm.
LC Call No.:   QA381.S5
Subjects:      Differential invariants. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Control No.:   7783014

Author:        Stöckert, Oskar Alexander, 1863-
Title:         Über die Beziehungen der Reciprokantentheorie
                  zur allgemeinen Theorie der Differentialinvarianten. ...
Published:     Chemnitz, Druck von J.C.F. Fickenhahn & Sohn,
                  1895.
Description:   43, [1] p. 27 cm.
LC Call No.:   QA381.S87
Notes:         Lebenslauf.
               Inaug.-diss.--Leipzig.
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.25.
Control No.:   8202374

Author:        Stone, William Beverley, 1878-1919.
Title:         The Gr(r<5) of n-dimensional space and their
                  differential invariants for n=r=3 / by William Beverley
                  Stone.
Published:     Lancaster, PA, Press of the New era printing
                  company, 1908.
Description:   60 p. ; 23 cm.
LC Call No.:   QA381.S88
Notes:         Thesis (Ph. D.)--University of Virginia, 1907.
Subjects:      Differential invariants.
               Transformations (Mathematics)
Control No.:   10220296

Author:        Stouffer, Ellis Bagley, 1884- [from old catalog]
Title:         Invariants of linear differential equations,
Published:     [London, 1912?]
Description:   1. p.l., 40 p., 1 l. 27 cm.
LC Call No.:   QA381.S89
Subjects:      Differential invariants.
Control No.:   7296750

Author:        Weber, Eduard von, b. 1870.
Title:         Vorlesungen über das Pfaff'sche problem und die
                  theorie der partiellen differentialgleichungen erster
                  ordnung, von Dr. Eduard von Weber ...
Published:     Leipzig, B.G. Teubner, 1900.
Description:   XI, 622 p. 25 cm.
Series:        Sammlung von lehrbüchern auf dem gebiete der
                  mathematischen wissenschaften mit einschluss ihrer
                  anwendungen, bd. 2
LC Call No.:   QA381.W37
Notes:         Litteraturverzeichnis: p. [610]-616.
Subjects:      Differential equations, Partial.
               Pfaffian problem.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit Einschluss
                  ihrer Anwendungen ; Bd. II.
Control No.:   4525282

Author:        Wright, Joseph Edmund. [from old catalog]
Title:         Invariants of quadratic differential forms,
Published:     Cambridge, University press, 1908.
Description:   4 p.l., 90 p. 22 cm.
LC Call No.:   QA381.W8
Subjects:      Differential forms.
Control No.:   7748812

Author:        Allen, Elbert Frank.
Title:         A reconstruction of certain parts of the Lie
                  theory, by Elbert Frank Allen.
Published:     [Columbia? Mo., 1924?]
Description:   6, [335]-338, 11-21 p. 23 cm.
LC Call No.:   QA385.A5 1923
Notes:         Cover-title.
               Resumé of thesis (Ph. D.)--University of
                  Missouri, 1923.
               The Lie theory of one-parameter groups.--The
                  jacobian of a contact transformation. (Reprinted from Bull.
                  Amer. math. society, v. 30, no. 7, July, 1924)--Contact
                  transformations.
Subjects:      Continuous groups.
               Transformations, Infinitesimal.
               Transformations, Tangential.
Other titles:  Lie theory.
Control No.:   9672346

Author:        Beaumont, Ross A. (Ross Allen), 1914-
Title:         Projections of non-Abelian groups upon Abelian
                  groups containing elements of infinite order / by Ross Allen
                  Beaumont.
Published:     Urbana, Ill., 1940.
Description:   1 p. leaf, 8 p., 1 leaf ; 23 cm.
LC Call No.:   QA385.B4 1940
Notes:         Abstract of thesis (Ph. D.)--University of
                  Illinois, 1940.
               Vita.
               Photoprinted.
Subjects:      Continuous groups.
Control No.:   6443683

Author:        Bianchi, Luigi, 1856-1928.
Title:         Lezioni sulla teoria dei gruppi continui finiti
                  di trasformazioni.
Published:     Pisa, E. Spoerri, 1918.
Description:   vi, 590 p. 25 cm.
LC Call No.:   QA385.B57 1918
Dewey No.:     512.86
Subjects:      Continuous groups.
               Transformations (Mathematics)
Control No.:   3107876

Author:        Bianchi, Luigi, 1856-1928.
Title:         Lezioni sulla teoria dei gruppi continui finiti
                  di trasformazioni. Anno 1902-1903.
Published:     Pisa, E. Spoerri, 1903.
Description:   ix, 708 p. 25 cm.
LC Call No.:   QA385.B57
Notes:         Autographed, with printed t.-p. and table of
                  contents.
Subjects:      Continuous groups.
               Transformations (Mathematics)
Control No.:   1689238

Author:        Blichfeldt, Hans Frederik, 1873-
Title:         On a certain class of groups of transformations
                  in space of three dimensions ...
Published:     [Berkeley, Cal., Press of Needham Brothers,
                  1900]
Description:   61 p. 22 cm.
LC Call No.:   QA385.B64
Notes:         Inaug.-dis.--Leipzig.
               Vita.
Subjects:      Continuous groups.
Control No.:   7265615

Author:        Bohlmann, Georg, 1869-
Title:         Über eine gewisse klasse continuierlicher
                  gruppen und ihren zusammenhang mit den additionstheoremen
                  ...
Published:     Halle a.S., Hofbuchdruckerei von C.A. Kaemmerer &
                  co., 1892.
Description:   1 p. l., [5]-31, [1] p., 1 l. 28 cm.
LC Call No.:   QA385.B67
Notes:         Inaug.-Dis.--Halle.
               Vita.
Subjects:      Continuous groups.
Control No.:   5863004

Author:        Brügmann, Walther Asmus Christian, 1876-
Title:         Über eine reell irreducible gruppe von
                  berührungs-transformationen ...
Published:     Hamburg, Gedruckt bei Lütcke & Wulff, 1906.
Description:   1 p. l., 35, [1] p., 1 l. diagrs. 28 x 22 cm.
LC Call No.:   QA385.B88
Notes:         Inaug.-diss.--Greifswald.
               Lebenslauf.
Subjects:      Continuous groups.
               Transformations, Tangential.
Control No.:   7747173

Author:        Bullard, James Atkins.
Title:         On the structure of finite continuous groups ...
                  by James Atkins Bullard ...
Published:     [Baltimore, 1917]
Description:   [1], [430]-450p. ; 30 cm.
LC Call No.:   QA385.B89
Notes:         Thesis (Ph. D.)--Clark University, 1917.
               "Reprinted from American journal of mathematics,
                  vol. XXXIX, no. 4, October, 1917."
Subjects:      Continuous groups.
Control No.:   9651986

Author:        Campbell, John Edward, 1862-1924.
Title:         Introductory treatise on Lie's theory of finite
                  continuous transformation groups, by John Edward Campbell
                  ...
Published:     Oxford, At the Clarendon press, 1903.
Description:   xx, 416 p. 23 cm.
LC Call No.:   QA385.C18
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Continuous goups.
Control No.:   4525364

Author:        Chevalley, C. (Claude), 1909-
Title:         Theory of Lie groups, I.
Published:     Princeton, Princeton University Press, 1946.
Description:   217 p. 24 cm.
Series:        Princeton mathematical series, 8
LC Call No.:   QA385.C5
Notes:         No more published in this ed.
Subjects:      Continuous groups.
Control No.:   10215492

Author:        Cohen, Abraham, b. 1870.
Title:         An introduction to the Lie theory of
                  one-parameter groups; with applications to the solution of
                  differential equations, by Abraham Cohen ...
Published:     Boston, New York [etc.] D.C. Health & co., 1911.
Description:   vii, 248 p. diagrs. 19 cm.
LC Call No.:   QA385.C7
ISBN:          $2.00
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Lie groups.
               Differential equations.
Control No.:   3107485

Author:        De Cicco, John. [from old catalog]
Title:         The geometry of whirl series
Published:     [N.Y., 1938]
Description:   344-358 p. 27 x 20 cm.
LC Call No.:   QA385.D43 1938
Control No.:   10011217

Author:        Dohmen, Franz Joseph, 1874-
Title:         Darstellung der Berührungstransformationen in
                  Konnexkoordinaten ... von Franz Joseph Dohmen ...
Published:     Leipzig, Druck von B.G. Teubner, 1905.
Description:   1 p. l., 41, [3] p. 24 cm.
LC Call No.:   QA385.D65
Notes:         Inaug.-Diss.--Greifswald.
               Lebenslauf.
Subjects:      Contact transformations.
Control No.:   5865573

Author:        Doyle, Thomas Carlson, 1908- [from old catalog]
Title:         Tensor decomposition with applications to the
                  contact and complex groups,
Published:     Princeton, 1939 [i.e. 1941]
Description:   698-722 p. 26 cm.
LC Call No.:   QA385.D68
Subjects:      Contact transformations.
               Calculus of tensors.
Control No.:   5976737

Author:        Eisenhart, Luther Pfahler, b. 1876.
Title:         Continuous groups of transformations, by Luther
                  Pfahler Eisenhart ...
Published:     Princeton, Princeton university press; London, H.
                  Milford, Oxford university press, 1933.
Description:   ix, 301 p. 24 cm.
LC Call No.:   QA385.E54
Dewey No.:     512.86
Notes:         Bibliography: p. 293-296.
Subjects:      Continuous groups.
               Contact transformations.
               Transformations, Infinitesimal.
               Geometry, Differential.
Control No.:   3108545

Author:        Engel, Friedrich, 1861-1941.
Title:         Über die definitionsgleichungen der
                  continuirlichen transformationsgruppen ...
Published:     Leipzig, Druck von B. G. Teubner, 1885.
Description:   1 p.l., 57 p. 23 cm.
LC Call No.:   QA385.E57
Subjects:      Continuous groups.
Control No.:   6329006

Author:        Engle, Friedrich, 1861- [from old catalog]
Title:         Zur theorie der berührungstransformationen ...
Published:     Leipzig, Druck von B. G. Teubner, 1883.
Description:   46 p., 1 l. 23 cm.
LC Call No.:   QA385.E59
Subjects:      Transformations, Tangential. [from old catalog]
Control No.:   8205163

Author:        Epsteen, Saul. [from old catalog]
Title:         Les groupes qui coincedent avec leurs groupes
                  adjoints.
Published:     [Leipzig, 1902]
Description:   4 p. 24 cm.
LC Call No.:   QA385.E64
Subjects:      Continuous groups.
Control No.:   6798973

Author:        Fitting, Friedrich, 1862-
Title:         Über eine klasse von berührungstransformationen
                  ...
Published:     Halle a.S. [Buchdruckerei von H.W. Schmidt]
                  1888.
Description:   1 p. l., 37, [3] p. 24 cm.
LC Call No.:   QA385.F56
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Transformations, Tangential.
Control No.:   9607266

Author:        Glicksberg, Irving Leonard, 1925- [from old
                  catalog]
Title:         Continuous games with given unique solutions
Published:     Santa Monica, Calif., Rand Corp., c1951.
Description:   8 l. 30 cm.
LC Call No.:   Q180.A1R36 no. 620
Subjects:      Continuous groups.
Other authors: Gross, Oliver Alfred, 1919- [from old catalog]
                  joint author.
Series Entry:  Rand Corporation. Project Rand research
                  memorandum, RM-620. [from old catalog]
Control No.:   8839640

Author:        Glicksberg, Irving Leonard, 1925- [from old
                  catalog]
Title:         A game with respective optimal spectra of
                  cardinality c and l
Published:     Santa Monica, Calif., Rand Corp., c1951.
Description:   3 l. 30 cm.
LC Call No.:   Q180.A1R36 no. 611
Subjects:      Continuous groups.
Other authors: Gross, Oliver Alfred, 1919- [from old catalog]
                  joint author.
Series Entry:  Rand Corporation. Project Rand research
                  memorandum, RM-611. [from old catalog]
Control No.:   6966649

Author:        Hartwell, George Wilbur. [from old catalog]
Title:         Plane fields of force whose trajectories are
                  invariant under a projective group ...
Published:     [New York] 1909.
Description:   22-246 p., 1 l. 28 cm.
LC Call No.:   QA385.H3
Notes:         Thesis (Ph. D.)--Columbia university.
               Biography: 1 l.
               From Transactions of the American mathematical
                  society, v. 10, no. 2, April, 1909.
Subjects:      Projectile. [from old catalog]
Control No.:   12894863

Author:        Koch, Richard, 1875- [from old catalog]
Title:         Bestimmung der viergliedrigen gruppen des raumes
                  (x y z) ...
Published:     Berlin, Buchdr. von G. Schade (O. Francke) 1898.
Description:   73, [1] p., 1 l. 22 cm.
LC Call No.:   QA385.K76
Subjects:      Continuous groups.
Control No.:   8191079

Author:        Kowalewski, Gerhard, 1876-1950.
Title:         Die primitiven transformationsgruppen in fünf
                  veränderlichen ...
Published:     Leipzig, B. G. Teubner, 1899.
Description:   1 p.l., [69]-144 p. 23 cm.
LC Call No.:   QA385.K88
Subjects:      Continuous groups.
Control No.:   9137719

Author:        Kowalewski, Gerhard, 1876-1950.
Title:         Über eine kategorie von transformationsgruppen
                  einer vierdimensionalen mannigfaltigkeit ...
Published:     Leipzig, Druck von B. G. Teubner, 1898.
Description:   1 p.l., 52 p., 1 l. 23 cm.
LC Call No.:   QA385.K89
Subjects:      Continuous groups.
Control No.:   8191118

Author:        Kratzi, Johannes, 1877- [from old catalog]
Title:         Gruppen mit einer dreigliedrigen untergruppe,
Published:     Leipzig, Druck von B. G. Teubner, 1904.
Description:   52, [2] p. 24 cm.
LC Call No.:   QA385.K92
Subjects:      Continuous groups.
Control No.:   8206803

Author:        Kummer, Adolf [Joseph] 1882-
Title:         Über eine gattung von projektiven
                  transformationsgruppen in sechs veränderlichen ...
Published:     Göttengen, Druck der Dieterichschen
                  universitäts-buchdr. (W.F. Kaestner), 1908.
Description:   65, [1] p. 24 cm.
LC Call No.:   QA385.K95
Notes:         Inaug.-diss.--Bonn.
               Lebenslauf.
Subjects:      Continuous groups.
Control No.:   8220540

Author:        Langman, Harry, 1889- [from old catalog]
Title:         Conformal transformations of period n and groups
                  generated by them,
Published:     [Baltimore, 1922]
Description:   1 p. l., [1], 54-86 p., 1 l. 35 cm.
LC Call No.:   QA385.L3
Subjects:      Transforamtions (Mathematics) [from old catalog]
               Continuous groups.
Control No.:   5917763

Author:        Lie, Sophus, 1842-1899.
Title:         Geometrie der berührungstransformationen.
                  Dargestellt von Sophus Lie und Georg Scheffers ... 1. band.
                  Mit figuren im text.
Published:     Leipzig, B. J. Teubner, 1896.
Description:   xi, [1], 693, [1] p. diagrs. 25 cm.
LC Call No.:   QA385.L66
Notes:         No more published.
               I. Berührungstransformationen der ebene.--II.
                  Geometrie der linienelemente des raumes.--III. Einführung in
                  die geometrie der flächenelemente. Partielle
                  differentialgleichungen erster
                  ordnung.--Sachregister.--Namenverzeichnis.
Subjects:      Contact transformations.
Other authors: Scheffers, George Wilhelm, 1866-
Control No.:   8204797

Author:        Lie, Sophus, 1842-1899.
Title:         Theorie der transformationsgruppen ... unter
                  mitwirkung von dr. Friedrich Engel bearb. von Sophus Lie ...
Published:     Leipzig, B.G. Teubner, 1888-93.
Description:   3 v. 25 cm.
LC Call No.:   QA385.L68
Notes:         1. abschnitt. Allgemeine eigenschaften der
                  endlichen continuirlichen transformationsgruppen. 1888.--2.
                  abschnitt. Theorie der berührungstransformationen und der
                  gruppen von berüchrungstransformationen. 1890.--3.
                  abschnitt. I. Die endlichen continuirlichen gruppen der
                  geraden linie und der ebene. II. Die endlichen
                  continuirlichen gruppen des gewöhnlichen raumes. III. Die
                  projectiven gruppen des gewöhnlichen raumes. IV.
                  Untersuchungen über verschiedene arten von gruppen des
                  n-fach ausgedehnten raumes. V. Untersuchungen über die
                  grundlagen der geometrie. VI. Allgemeine betrachtungen über
                  endliche continuirliche gruppen. 1893.
Subjects:      Transformation groups.
               Continuous groups.
               Contact transformations.
Other authors: Engel, Friedrich, 1861-1941.
Control No.:   1689123

Author:        Lie, Sophus, 1842-1899.
Title:         Vorlesungen über continuierliche Gruppen mit
                  geometrischen und anderen Anwendungen. Bearb. und hrsg. von
                  Georg Scheffers.
Published:     Leipzig, B.G. Teubner, 1893.
Description:   xii p., 2 p.l., 810 p. diagrs. 25 cm.
LC Call No.:   QA385.L7
Subjects:      Continuous groups.
Other authors: Scheffers, Georg, 1866-1945, ed.
Control No.:   5855241

Author:        Liebmann, Heinrich, 1874-
Title:         Die berührungstransformationen.
Published:     Leipzig, B. G. Teubner, 1914.
Description:   3 p. l., 79 p. 26 cm.
LC Call No.:   QA385.L75
Subjects:      Contact transformations.
               Invariants.
Other authors: Engel, Friedrich, 1861-1941.
Control No.:   9173484

Author:        Mariani, Jean.
Title:         Metrical geometry, contact transformations and
                  nuclear physics.
Published:     Brooklyn, Institute of Applied Biology, and
                  Cancer Research and Hospital Foundation, 1950.
Description:   28 p. 22 cm.
LC Call No.:   QA385.M3
Dewey No.:     512.86
Notes:         Cover title.
               Bibliography: p. 27-28.
Subjects:      Contact transformations.
               Quantum theory.
Control No.:   3110029

Author:        Murray, Francis J. (Francis Joseph), 1911-
Title:         Linear transformations between Hilbert spaces and
                  the application of this theory to linear partial differential
                  equations, by F.J. Murray ...
Published:     [New York, 1935]
Description:   1 p. l., p 301-338, 1 l. diagr. 28 cm.
LC Call No.:   QA385.M8 1935
Dewey No.:     512.86
Notes:         Thesis (Ph. D.)--Columbia University, 1935.
               Vita.
               "Reprinted from the Transactions of the American
                  Mathematical Society, vol. 37, no. 2 ... March, 1935.
Subjects:      Transformations, Infinitesimal.
               Hyperspace.
               Differential equations, Partial.
Control No.:   7831561

Author:        Oseen, Carl Wilhelm, 1879- [from old catalog]
Title:         Ueber die endlichen continuierlichen irreduciblen
                  berührungstranformationsgruppen im raume ...
Published:     Lund, H. Ohlssons buchdruckerei, 1901.
Description:   1 p.l., 36 p. 23 cm.
LC Call No.:   QA385.O8
Subjects:      Contact transformations.
Control No.:   7275944

Author:        Page, James M[orris], 1864- [from old catalog]
Title:         On the primitive groups of transformations in
                  space of four dimensions ...
Published:     Baltimore, Press of I. Friedenwald, 1888.
Description:   [293]-346 p. 31 x 25 cm.
LC Call No.:   QA385.P14
Subjects:      Continuous groups.
               Hyperspace. [from old catalog]
Control No.:   10076153

Author:        Pascal, Ernesto, b. 1865.
Title:         I gruppi continui di trasformazioni (parte
                  generale della teoria) per Ernesto Pascal.
Published:     Milano, U. Hoepli, 1903.
Description:   xi, 358 p. 15 cm.
Series:        Manuali Hoepli [Ser. scientifica, 327-328]
LC Call No.:   QA385.P3
Subjects:      Continuous groups.
Control No.:   8801654

Author:        Rettger, Ernest William, 1871-
Title:         On Lie's theory of continuous groups. By E. W.
                  Rettger ...
Published:     [Baltimore, 1900]
Description:   Cover-title, p. [60]-95 ; 27 x 23 cm.
LC Call No.:   QA385.R43
Notes:         "Reprinted from American journal of mathematics,
                  vol. XXII, no. 1."
               Thesis (Ph. D.)--Clark University, 1898.
               Typewritten manuscript.
               Includes bibliographical references.
Subjects:      Continuous groups.
Control No.:   7736107

Author:        Roberts, Hillery L., 1871-1915. [from old
                  catalog]
Title:         On the transformation group: p, q, r, xp, yq, zr,
                  xp2sp, yp2sq, zp2sr by Hillery L. Roberts, M.A.
Published:     Wash[ington] Gibson bros., prs. [1899?]
Description:   48 p. 28 cm.
LC Call No.:   QA385.R6
Notes:         Cover-title.
               Thesis (Ph. D.)--University of Virginia, 1899.
               Without thesis note.
               Dissertation as submitted has title: On the
                  geometry of a certain transformation group of eight
                  parameters.
Subjects:      Transformations, Infinitesimal.
Control No.:   12911742

Author:        Rothrock, David A. (David Andrew), 1864-1949.
Title:         Invariants of the finite continuous groups of the
                  plane ... by David Andrew Rothrock.
Published:     Indianapolis, Printed by W.B. Burford, 1899.
Description:   32 p. 23 cm.
LC Call No.:   QA385.R84
Notes:         Vita.
               Inaug.-diss.--Leipzig.
Subjects:      Differential invariants
               Continuous groups
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.15.
Control No.:   5861147

Author:        Scheffers, Georg, 1866-1945.
Title:         Bestimmung einer Classe von
                  Berührungstransformationsgruppen des dreifach ausgedehnten
                  Raumes ...
Published:     Stockholm, Gedruckt in der Centraldrukerei,
                  1890.
Description:   70, [2] p. 29 cm.
LC Call No.:   QA385.S31
Notes:         Lebenslauf.
               Inaug.-dis.--Leipzig.
Subjects:      Continuous groups
               Contact transformations
Other titles:  Pamphlets. 1890-1893.
Control No.:   9607828

Author:        Slocum, S. E. (Stephen Elmer), 1875-
Title:         On the continuity of groups generated by
                  infinitesimal transformations. By Stephen Elmer Slocum ...
Published:     1900.
Description:   1 p. l., [83]-109, [7] p. 24 cm.
LC Call No.:   QA385.S63
Notes:         Cover-title.
               Thesis (Ph. D.)--Clark University, 1900.
               From proceedings of the American academy of arts
                  and sciences, vol. xxxvi, no. 6, August 1900 and vol. xxxv,
                  no. 26, June 1900, p. 591-597.
Subjects:      Continuous groups.
Control No.:   8204775

Author:        Stephens, Rothwell Clifford, 1906- [from old
                  catalog]
Title:         Continuous transformations of abstract spaces,
Published:     [New York, 1932]
Description:   1 p. l., [1], 394-408 p. 27 cm.
LC Call No.:   QA385.S75 1931
Subjects:      Transformations (Mathematics) [from old catalog]
               Continuous groups.
               Hyperspace. [from old catalog]
Control No.:   6883991

Author:        Stone, Marshall H. (Marshall Harvey), 1903-
Title:         Linear transformations in Hilbert space and their
                  applications to analysis, by Marshall Harvey Stone ...
Published:     New York, The American Mathematical Society,
                  1932.
Description:   viii, 622 p. 24 cm.
Series:        American Mathematical Society. Colloquium
                  publications, vol. XV
LC Call No.:   QA385.S8
Dewey No.:     512.86
Subjects:      Transformations (Mathematics)
               Continuous groups.
               Hyperspace.
Series Entry:  Colloquium publications (American Mathematical
                  Society) ; v. 15.
Control No.:   8755801

Author:        Süss, Alfred, 1881-
Title:         Die Gruppen, die mit der allgemeinen projectiven
                  Gruppe der Ebene gleiche Zusammensetzung haben ...
Published:     Dresden, Druck von B.G. Teubner, 1905.
Description:   32, [2] p. 23 cm.
LC Call No.:   QA385.S93
Notes:         Lebenslauf.
               Inaug.-diss.--Greifswald.
Subjects:      Continuous groups
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.18.
Control No.:   8674946

Author:        Vivanti, G. (Giulio), 1859-
Title:         Leçons élémentaires sur la théorie des
                  groupes de transformations professées à l'Université de
                  Messine par G. Vivanti. Traduites par A. Boulanger ...
Published:     Paris, Gauthier-Villars, 1904.
Description:   vii, 296 p. 26 cm.
LC Call No.:   QA385.V85
Notes:         1. ptie. Théorie générale des groupes de
                  transformations.--2. ptie. Application de la théorie des
                  groupes de transformations aux équations
                  différentielles.--3. ptie. Transformations de contact.
Subjects:      Continuous groups.
               Differential equations.
               Contact transformations.
Other authors: Boulanger, A. (Auguste), 1866-1923, tr.
Control No.:   3106979

Author:        Volterra, Vito, 1860-1940.
Title:         ...Opérations infinitésimales linéaires;
                  applications aux équations différentielles et
                  fonctionnelles, par Vito Volterra ... et Bohuslav
                  Hotinský...
Published:     Paris, Gauthier-Villars, 1938.
Description:   vii, 238 p., 1 l. diagrs. 25 cm.
LC Call No.:   QA385.V88
Dewey No.:     512.86
Notes:         "Notes bibliographiques": p. [223]-231.
Subjects:      Transformations, Infinitesimal.
               Differential equations.
               Functional equations.
               Hostinský, Bohuslav, 1884- joint author.
Control No.:   8778844

Author:        Westfall, John Van Etten, 1872-
Title:         On a category of transformation groups in three
                  and four dimensions ...
Published:     Ithaca, N.Y., Andrus & Church, 1899.
Description:   32 p., 1 l. 22 cm.
LC Call No.:   QA385.W52
Notes:         Inaug. dis.--Leipzig.
               Vita.
Subjects:      Continuous groups.
Control No.:   7265594

Author:        Weyl, Hermann, 1885-1955.
Title:         The classical groups; their invariants and
                  representations, by Hermann Weyl ...
Published:     Princeton, N.J., Princeton University Press;
                  London, H. Milford, Oxford University Press, 1939.
Description:   xii, 302 p. 26 cm.
Series:        [Princeton mathematical series ... 1]
LC Call No.:   QA385.W54
Dewey No.:     512.86
Notes:         Bibliography: p. 291-297.
Subjects:      Continuous groups.
               Group theory.
Control No.:   6438056

Author:        Williams, John Edward, 1867-1943.
Title:         On the geometry of the transformation group p, q,
                  r, xq, yp, zr, xp-yq, zp2sr by J.E. Williams.
Published:     Washington, D.C., Gibson bros., printers, 1899.
Description:   38 p. 30 cm.
LC Call No.:   QA385.W6 1889
Notes:         On t.p. "p, q, r, xq, yp, zr, xp-yq, zp2sr" is
                  enclosed within a rectangular border.
               Thesis (Ph. D.)--University of Virginia, 1899.
               Life.
Subjects:      Transformations, Infinitesimal.
Control No.:   12911692

Author:        Winkler, Franz Richard, 1878-
Title:         Die infinitesimalen Transformationen, welche
                  einen Pfaffschen Ausdruck absolut oder Moduls eines
                  vollständigen Differentials invariant lassen ... von Franz
                  Winkler.
Published:     Leipzig, Druck von Metzger & Wittig, 1905.
Description:   38 p., 1 L. 23 cm.
LC Call No.:   QA385.W7
Notes:         Lebenslauf.
               Inaug.-diss.--Leipzig.
Subjects:      Transformations, Infinitesimal
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.20.
Control No.:   6335393

Author:        Zeldin, Samuel D.
Title:         On the structure of finite continuous groups with
                  a single exceptional infinitesimal transformation ... By
                  Samuel D. Zeldin ...
Published:     [Baltimore, 1922]
Description:   1 p. l., [1], 204-216 p. 26 cm.
LC Call No.:   QA385.Z5
Notes:         Thesis (Ph. D.)--Clark University, 1917.
               "Reprinted from American Journal of Mathematics,
                  vol. XLIV, no. e, July, 1922."
Subjects:      Continuous groups.
               Transformations, Infinitesimal.
Control No.:   7322622

Author:        Bottenbert, William R. [from old catalog]
Title:         Effect of Reynolds number on the flow about a
                  finite cone of 70 degrees.
Published:     Pasadena, 1949.
Description:   29 l. illus. 29 cm.
LC Call No.:   QA390.B67
Subjects:      Reynolds numbers. [from old catalog]
               Cone. [from old catalog]
Control No.:   10243912
