#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Cook, John Williston, 1844-1922. [from old
                  catalog]
Title:         Elementary arithmetic,
Published:     Boston, New York [etc.] Silver, Burdett &
                  company, 1895.
Description:   229 p. illus. 19 cm.
LC Call No.:   QA102.C755 1895
Subjects:      Arithmetic -- Early works to 1900.
Other authors: Cropsey, Nebraska C., d 1916, [from old catalog]
                  joint author.
Control No.:   9132397

Author:        Wells, Webster, 1851-1916.
Title:         New high school arithmetic, academic, industrial,
                  commercial, by Webster Wells .. and Walter W. Hart.
Published:     Boston, New York [etc.] D.C. Heath & co. [c1919]
Description:   viii, 358 p. illus., diagrs. 19 cm.
LC Call No.:   QA102.W438
Subjects:      Arithmetic.
Other authors: Hart, Walter W. (Walter Wilson), 1879- joint
                  author.
Control No.:   7313231

Author:        McLellan, James Alexander, 1832- [from old
                  catalog]
Title:         Primary arithmetic,
Published:     New York, The Macmillan company; London,
                  Macmillan & co., ltd., 1898.
Description:   x, 53 p. diagrs. 18 cm.
LC Call No.:   QA104.M154
Subjects:      Arithmetic -- Early works to 1900.
Other authors: Ames, Albert Flintoft, [from old catalog] joint
                  author.
Control No.:   6790961

Author:        Smith, David Eugene, 1860- [from old catalog]
Title:         Intermediate arithmetic,
Published:     Boston, New York [etc.] Ginn & company [c1905]
Description:   vi, 267, 30 p. illus. 19 cm.
LC Call No.:   QA104.S648
Subjects:      Arithmetic.
Control No.:   8671910

Title:         Whitcombe's new federal arithmetics] Grade
                  Specially written to meet the requirements of the revised
                  Victorian course of study in elementary schools.
Published:     Melbourne [etc.] Whitcombe & Tombs pty. ltd., 19
Description:   v. illus., diagrs. 19 cm.
LC Call No.:   QA105.W5
Subjects:      Arithmetic.
               Arithmetic -- Problems, exercises, etc.
Other titles:  Federal arithmetics.
               Whitcombe's new federal mathematics.
Control No.:   8341034

Author:        Perrot, Aristide M. [from old catalog]
Title:         Nouveau manuel complet pour la construction et le
                  dessin des cartes geographiques ...
Published:     [n.p.] 1903.
Description:   1 v. cm.
LC Call No.:   QA105.P45
Control No.:   6298453

Author:        Pinkerton, B. Frank. [from old catalog]
Title:         The practical mental and written arithmetic,
                  uniting oral and slate work, and containing over 4,500
                  practical problems.
Published:     [Philadelphia, Collins printing house] 1884.
Description:   viii, [9]-279 p. 19 cm.
LC Call No.:   QA105.P658
Subjects:      Arithmetic -- Early works to 1900.
Control No.:   6322858

Title:         Waltons' arithmetical works : Walton's normal
                  series of arithmetic.
Published:     [Boston? : Brewer and Tileston?, 1870]
Description:   18 p. : ill. ; 18 cm.
LC Call No.:   QA108.W358 1870
Notes:         Prospectus.
               Caption title.
Subjects:      Arithmetic -- Textbooks.
Other authors: Walton, George A. (George Augustus), 1822-1908.
Control No.:   13287426

Author:        Gómez, Carlina. [from old catalog]
Title:         Decimales;
Published:     Mendoza [Talleres gráficos de G. d'Accurzio]
                  1940.
Description:   22 p., 1 l. col. plates (part fold.) diagr. 20
                  cm.
LC Call No.:   QA117.G6
Subjects:      Decimal fractions.
               Arithmetic -- Study and teaching.
Control No.:   6939475

Author:        Holden, Warren, 1817-1903.
Title:         The oneness of arithmetic. By Warren Holden ...
Published:     Philadelphia, Press of J.B. Lippincott company,
                  1893.
Description:   16 [1] p. 21 cm.
LC Call No.:   QA117.H7
Subjects:      Ratio and proportion.
               Arithmetic.
Control No.:   6395873

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Decimals, prepared especially for home study ...
Published:     [Scranton, 1936]
Description:   cover-title, 34 p. 19 cm.
LC Call No.:   QA117.I58
Subjects:      Decimal fractions.
Control No.:   7860942

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Fractions, prepared especially for home study
                  ...
Published:     [Scranton, 1936]
Description:   cover-title, 34 p. diagrs. 19 cm.
LC Call No.:   QA117.I59
Subjects:      Fractions. [from old catalog]
Control No.:   7392691

Author:        Leonard, John H. [from old catalog]
Title:         Leonard's new and time saving method for
                  subtraction of fractions, with many corollaries on simple
                  numbers deduced from the fractional treatise.
Published:     Sacramento, H.S. Crocker & co., printers, 1883.
Description:   55 p. 15 cm.
LC Call No.:   QA117.L6
Subjects:      Fractions.
               Subtraction.
Control No.:   6267837

Author:        Metzger, William Thompson.
Title:         Table of 45,000 per cents; gives percentages up
                  to 100.00% on the basis of 1 to 300 lines (numerator) and 1
                  to 300 columns (denominator)
Published:     Indianapolis, .b Research Tabulating Bureau
                  [c1957]
Description:   54 p. 29 cm.
LC Call No.:   QA117.M4
Subjects:      Fractions -- Tables.
               Percentage -- Tables.
Control No.:   9816185

Author:        Norris, U. R. [from old catalog]
Title:         Lightning method.
Published:     [n.p.] 1880.
Description:   1 v. cm.
LC Call No.:   QA117.N8
Control No.:   10013366

Author:        Palmer, Val P. [from old catalog]
Title:         A new look at the fractions.
Edition:       [1st ed.
Published:     Rockford? Ill., 1956]
Description:   65 l. illus. 28 cm.
LC Call No.:   QA117.P2
Subjects:      Fractions. [from old catalog]
Control No.:   6982468

Author:        [Pestalozzi, Johann Heinrich] 1746-1827. [from
                  old catalog]
Title:         A B C der anschauung:
Published:     Z¯ur¯ich und Bern, H. Gessner; [etc., etc.]
                  1803.
Description:   p. cm.
LC Call No.:   QA117.P4
Other authors: Fractions. [from old catalog]
Control No.:   5857072

Author:        Peet, I. L. [from old catalog]
Title:         Monograph on decimal fractions.
Published:     [n.p.] 1866.
Description:   1 v. cm.
LC Call No.:   QA117.P3
Control No.:   7672362

Author:        Phipps, Charles.
Title:         The doctrine of vulgar and decimal fractions :
                  explain'd and made easy to the meanest capacity : to which is
                  added The art of decyphering, wherein that mysterious branch
                  of knowledge is made plain and easy ... / by Charles Phipps,
                  Senr., of the city of Dublin, writing-master.
Published:     Dublin : Printed for the author and sold by G.
                  and A. Ewing ..., 1745.
Description:   [32], 72 p. ; 20 cm. (8vo)
LC Call No.:   QA117.P45 1745
Notes:         Signatures: pip8s a-bp4s B-Ep8s Fp4s.
               LC copy is item no. 500 of the George Fabyan
                  Collection. DLC
Subjects:      Fractions -- Early works to 1800.
Other authors: George Fabyan Collection (Library of Congress)
                  DLC
Control No.:   4949524

Author:        Price, R. N. (Richard Nye), b. 1830.
Title:         Co-fractions, a new discovery and its
                  applications. By R. N. Price, A.M.
Published:     Nashville, Tenn., Publishing house of the M.E.
                  church, South, Barbee & Smith, agents, 1898.
Description:   46 p. 18 cm.
LC Call No.:   QA117.P9
Subjects:      Fractions.
Control No.:   275630

Author:        Railey, J. P. [from old catalog]
Title:         New rule for proportion.
Published:     [n.p.] [1896]
Description:   1 v. cm.
LC Call No.:   QA117.R2
Control No.:   7672418

Author:        Rowland, J. [from old catalog]
Title:         Geometrical method of stating questons.
Published:     [n. p.] 1873.
Description:   1 v. cm.
LC Call No.:   QA117.R8
Control No.:   8138080

Author:        Slaught, H. E. [from old catalog]
Title:         Principles of percentage.
Published:     [n.p.] 1887.
Description:   1 v. cm.
LC Call No.:   QA117.S6
Control No.:   8142462

Author:        Stone, Carol (Larson), 1922- [from old catalog]
Title:         Percentages for integers 1 to 399.
Published:     [Pullman] Washington Agricultural Experiment
                  Stations, Institute of Agricultural Sciences, State College
                  of Washington, 1959.
Description:   1 v. (loose-leaf) 28 cm.
LC Call No.:   QA117.S8
Subjects:      Percentage. [from old catalog]
Series Entry:  Washington (State) Agricultural Experiment
                  Station, Pullman. Station circular 341. [from old catalog]
Control No.:   10290044

Author:        United States. Agricultural Research Service.
Title:         Tables for computing percentages: for numbers 1
                  to 250.
Published:     [Washington] 1957.
Description:   75 p. 27 cm.
Series:        Its ARS 20-6
LC Call No.:   QA117.U5 1957
Dewey No.:     511
Notes:         "These tables were originally prepared by Charles
                  A. Clark and published in 1940 [under title: Percentage
                  tables for numbers from 1 to 250] as ET-172 of the Bureau of
                  Entomology and Plant Quarantine of the United States
                  Department of Agriculture.
Series Entry:  United States. Agricultural Research Service. ARS
                  20-6.
Control No.:   8878573

Author:        Whitbeck, J. [from old catalog]
Title:         Addition, subtraction, mult. & div. of vulgar
                  fractions.
Published:     1873.
Description:   p. cm.
LC Call No.:   QA117.W5
Control No.:   8126854

Author:        Barrett, Urbane L. [from old catalog]
Title:         An adventure in figuring;
Published:     Los Angeles [1943]
Description:   p. cm.
LC Call No.:   QA119.B3
Subjects:      Cube root.
Control No.:   6454009

Author:        Cataldi, Pietro Antonio, ca. 1548-1626.
Title:         Trattato del modo brevissimo di trouare la radice
                  quadra delli numeri, et regole da approssimarsi di coninuo al
                  vero nelle radici de' numeri non quadrati, con le cause, &
                  inuentioni loro, et anco il modo di pigliarne la radice cuba,
                  applicando il tutto alle operationi militari, & altre. Di
                  Pietro Antonio Cataldi.
Published:     Bologna, Appresso B. Cochi, 1613.
Description:   2 p. L., 140 p. diagrs. 30 cm.
LC Call No.:   QA119.C35
Notes:         Title in red and black; title vignette.
               Dedicated to Lodovico Mariscotti, with vignette
                  portrait of Mariscotti at head of dedication.
               At end: Finij questa copia, data alla stampa,
                  lunedi alli 11. agosto 1597 à hore 21 1/2 nella stanza in s.
                  Petronio vecchio, contrada di Bologna, essendodo fatta le
                  prima bozza alcuni anni auanti.
Subjects:      Square root.
               Cube root.
               Continued fractions.
Control No.:   10074889

Author:        Hill, H. H. [from old catalog]
Title:         New & simple method for square & cube root.
Published:     [1877]
Description:   1 v. cm.
LC Call No.:   QA119.H6
Control No.:   8141074

Author:        Hines, G. D. [from old catalog]
Title:         Mathematical roots uprooted.
Published:     [n.p.] 1886.
Description:   1 v. cm.
LC Call No.:   QA119.H7
Control No.:   6735522

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Powers and roots, prepared especially for home
                  study ...
Published:     [Scranton, 1936]
Description:   25 p. diagrs. 19 cm.
LC Call No.:   QA119.I55
Subjects:      Square root. [from old catalog]
Control No.:   5988289

Author:        McKirahan, William, 1845- [from old catalog]
Title:         Cube root,
Published:     [Norfolk, Va., Norfolk mission college electric
                  print.] c1915.
Description:   1 p. l., 10 p. diagrs. 21 cm.
LC Call No.:   QA119.M3
Subjects:      Cube root.
Control No.:   10112270

Author:        Pendelton, S. T. [from old catalog]
Title:         Extraction of roots.
Published:     [n.p.] 1879.
Description:   1 v. cm.
LC Call No.:   QA119.P4
Control No.:   7200808

Author:        Penn, B. F. [from old catalog]
Title:         Method of extracting the determinate square
                  root.
Published:     [n.p.] 1882.
Description:   1 v. cm.
LC Call No.:   QA119.P5
Control No.:   10482333

Author:        Ringberg, Abdiel Fredrik. [from old catalog]
Title:         On quadrattabellernas bruk till rotutdragning.
Published:     Lund, Tryckt uti Berlingska boktryckeriet, 1852.
Description:   1 p.l., 49-56 p. 23 cm.
LC Call No.:   QA119.R58
Subjects:      Square root. [from old catalog]
Control No.:   8201522

Author:        Tumminello, Charles E.
Title:         Tumminello theory of numerical roots, by Charles
                  E. Tumminello.
Published:     Boston, The Christopher publishing house [c1939]
Description:   2 p. l., vii-x, 11-178 p. 20 x 24 cm.
LC Call No.:   QA119.T85
Dewey No.:     511.9
Subjects:      Roots, Numerical.
Control No.:   6439920

Author:        Philippines. Bureau of Education.
Title:         Supplementary problems for trade schools and
                  trades classes in the Philippine public schools.
Published:     Manila, Bureau of printing, 1915.
LC Call No.:   QA129.P573 1915

Author:        Detroit Public Schools.
Title:         Course of study in arithmetic,
Published:     Detroit, 1924.
Description:   142 p. illus. (forms) diagr. 23 cm.
LC Call No.:   QA136.D45
Subjects:      Arithmetic -- Study and teaching
               Education -- Michigan -- Detroit.
               Education -- Michigan -- Curricula.
Control No.:   9669185

Author:        Alshouse, H. S. [from old catalog]
Title:         One hundred lessons in fractions,
Published:     Chicago, A. Flanagan company [c1907]
Description:   80 p. 18 cm.
LC Call No.:   QA137.A46
Subjects:      Fractions. [from old catalog]
Control No.:   9618309

Author:        Bynon, A. A. [from old catalog]
Title:         A manual of suggestive exercises of hints or the
                  method of using Bynon's factiona apples.
Published:     San Francisco, J. T. White, 1882.
Description:   15 p. 18 cm.
LC Call No.:   QA137.B95 (Rare Bk coll)
Subjects:      Fractions. [from old catalog]
Other titles:  Bynon's fractional apples.
Control No.:   8466343

Author:        Davis, Woodhull W. [from old catalog]
Title:         A manual of suggestions for teaching fractions,
Published:     Syracuse, N.Y., C. W. Bardeen, 1880.
Description:   43 p. 18 cm.
LC Call No.:   QA137.D3
Subjects:      Fractions -- Study and teaching.
Control No.:   5858014

Author:        Harrington, I. [from old catalog]
Title:         Illuminated fractions: a key to Fractional blocks
                  for the illustration of all the principles and rules of
                  common fractions.
Published:     New York and Chicago, A. S. Barnes & company,
                  1873.
Description:   20 p. 18 cm.
LC Call No.:   QA137.H31
Subjects:      Fractions.
Control No.:   7262426

Author:        Kellogg, Amos MArkham, 1832-1914. [from old
                  catalog]
Title:         How to teach fractions to young children.
Published:     New York and Chicago, E. L. Kellogg & co.
                  [c1900]
Description:   x, 11-63 p. 18 cm.
LC Call No.:   QA137.K3
Subjects:      Fractions. [from old catalog]
Control No.:   6784730

Author:        McGuire, Orville Wayne, 1895-
Title:         Objective lessons in common fractions for fifth
                  and sixth grades [by] O. W. McGuire ...
Published:     Caldwell, Id., The Caxton printers, ltd., 1929.
Description:   29 p. 23 cm.
LC Call No.:   QA137.M3
Notes:         Folded diagram laid in.
Subjects:      Fractions.
Control No.:   7807417

Author:        Page, Helen F. [from old catalog]
Title:         Fractions.
Edition:       [Pupils' ed.]
Published:     Boston, Ginn & company, 1889.
Description:   [52] p. diagr. (partly col.) 21 cm.
LC Call No.:   QA137.P13
Subjects:      Fractions.
Control No.:   9135625

Author:        Page, Helen F. [from old catalog]
Title:         Fractions. A teacher's manual of objective and
                  oral work. By Helen F. Page.
Edition:       [Teachers' ed.]
Published:     Boston, Ginn & company, 1889.
Description:   2 p. l., 47 p. diagr. (partly col.) 21 cm.
LC Call No.:   QA137.P14
Subjects:      Fractions.
Control No.:   13181397

Author:        Searle, Albert Henry, 1891-
Title:         Case studies of pupils' errors in common
                  fractions, by Albert H. Searle ...
Published:     Ann Arbor, Mich., Mimeographed by Edwards
                  Brothers [1928]
Description:   3 p. l., 2-29 numb. l. 27 x 21 cm.
LC Call No.:   QA137.S4 1928
Notes:         Thesis (Ph. D.)--University of Iowa, 1928.
               Thesis note on label mounted on t.-p.
               Bibliography: leaf 29.
Subjects:      Fractions.
               Mental tests.
Control No.:   10146482

Author:        Sebold, Mary Theodine, sister, 1901-
Title:         Learning the basic concepts in fractions and
                  their application in the addition and subtraction of simple
                  fractions, by Sister Mary Theodine Sebold.
Published:     Washington, D.C., The Catholic university of
                  America press, 1946.
Description:   88 p. incl. tables, diagrs. 23 cm.
LC Call No.:   QA137.S43
Dewey No.:     411.407
Notes:         At head of title: The Catholic university of
                  America.
               Thesis (Ph. D.)--Catholic university of America.
               Bibliography: p. 83-88.
Subjects:      Fractions -- Study and teaching.
Control No.:   6942088

Author:        Sloane, Florence N
Title:         Practical lessons in fractions by the inductive
                  method; accompanied by fraction cards, by Florence N.
                  Sloane.
Published:     Boston, D.C. Heath & Co., 1894.
Description:   xxvi, 92 p. diagr. 19 cm.
LC Call No.:   QA137.S6
Subjects:      Fractions.
Control No.:   10072412

Author:        Southworth E. [from old catalog]
Title:         Handbook for...means of teaching fractions
Published:     [n. p.] [1886]
Description:   1 v. cm.
LC Call No.:   QA137.S7
Control No.:   8606864

Author:        Stone, T. H. (Thomas Henry), 1861-
Title:         Suggestions and aids in teaching fractions and
                  percentage, by T.H. Stone ...
Published:     Chicago, W.M. Welch company, 1905.
Description:   2 p.l., 3-19, [1] p. 20 cm.
LC Call No.:   QA137.S87
Subjects:      Fractions.
               Percentage.
Control No.:   3579484

Author:        Wildeman, Edward.
Title:         The teaching of fractions / by Edward Wildeman.
Published:     Chicago : Plymouth Press, c1923.
Description:   145 p. ; 21 cm.
Series:        Modern education series
LC Call No.:   QA137.W5
Subjects:      Fractions.
Series Entry:  Modern education series (Chicago, Ill.)
Control No.:   7790665

Author:        Bowden, Aberdeen Orlando, 1881- [from old
                  catalog]
Title:         Consumers use of arithmetic;
Published:     New York city, Teachers college, Columbia
                  university, 1929.
Description:   vi, 69 p., 1 l. incl forms. 23 cm.
LC Call No.:   QA142.B6 1929
Subjects:      Arithmetic.
               Arithmetic -- Study and teaching.
Control No.:   10149407

Author:        Brooks, E. [from old catalog]
Title:         Philosophy of arithmetic...
Published:     Philadelphia [1876]
Description:   1 v. cm.
LC Call No.:   QA142.B8
Control No.:   9078294

Author:        Brooks, Edward, 1831-1912.
Title:         The philosophy of arithmetic as developed from
                  the three fundamental processes of synthesis, analysis and
                  comparison, containing also a history of arithmetic.
Edition:       Rev. ed. By Edward Brooks.
Published:     Philadelphia, Normal publishing company, 1901.
Description:   x p., 1 l., 9-570 p., 1 l. 22 cm.
LC Call No.:   QA142.B9
Subjects:      Numeration.
               Mathematics -- Philosophy.
Control No.:   7257850

Author:        [Choate, Rufus], 1847- [from old catalog]
Title:         Cho momo, the one arithmetic;
Published:     [City of Washington, The Beresford press, c1914]
Description:   170 p., 1 l. 20 cm.
LC Call No.:   QA142.C5
Subjects:      Arithmetic.
Control No.:   7768569

Author:        Edgerton, Edward Ira. [from old catalog]
Title:         Teacher's manual for elementary algebra.
Published:     Boston, N.Y., etc. [c1930]
Description:   1 v. cm.
LC Call No.:   QA142.E255 Manual
Control No.:   10487592

Author:        Halsted, George Bruce, 1853-1922.
Title:         On the foundation and technic of arithmetic, by
                  George Bruce Halsted ...
Published:     Chicago, The Open Court Publishing Company,
                  1912.
Description:   iv, 133 p. 21 cm.
LC Call No.:   QA142.H3
Subjects:      Arithmetic.
Control No.:   8700018

Author:        Jackson, Lambert L. (Lambert Lincoln),
                  1870-1952.
Title:         The educational significance of sixteenth century
                  arithmetic from the point of view of the present time, by
                  Lambert Lincoln Jackson ...
Published:     New York, Teachers college, Columbia university,
                  1906.
Description:   232 p. illus. 24 cm.
Series:        Teachers college, Columbia university.
                  Contributions to education, no. 8
LC Call No.:   QA142.J14
Notes:         Bibliography: p. 9-16.
               Published as thesis (Ph. D.)--Columbia
                  university, 1906.
Subjects:      Arithmetic -- History -- 16th century.
               Arithmetic -- Study and teaching.
Series Entry:  Contributions to education ; no. 8.
Control No.:   272942

Author:        Keyes, Lyman G. [from old catalog]
Title:         Ratio and proportion, square root and cube root
Published:     [Leavenworth, Kan., c1930]
Description:   32 p. 17 cm.
LC Call No.:   QA142.K4
Subjects:      Ratio and proportion.
               Square root.
               Cube root.
Control No.:   10153925

Author:        McKay, Herbert, 1881-
Title:         Odd numbers; or, Arithmetic revisited, by Herbert
                  McKay ...
Published:     New York, The Macmillan company; Cambridge, Eng.,
                  The University press, 1940.
Description:   3 p.l., 215 p. diagrs. 20 cm.
LC Call No.:   QA142.M3 1940a
Dewey No.:     510.4
Notes:         "Printed in Great Britain."
               "First impression, April 1940. Reprinted August
                  1940."
Subjects:      Arithmetic.
Other titles:  Arithmetic revisited.
Control No.:   4527604

Author:        Sherwood, Henry McDonaugh, 1847- [from old
                  catalog]
Title:         Properties and peculiarities of the number 9.
Published:     Morristown, Tenn. [Morristown sun publishing
                  company] c1915.
Description:   12 p. 23 cm.
LC Call No.:   QA142.S47
Subjects:      Nine (The number)
Control No.:   7771181

Author:        Swain, Robert L. (Robert Lomond)
Title:         Understanding arithmetic.
Published:     New York, Rinehart [1957]
Description:   xxi, 264 p. illus., diagrs. 24 cm.
LC Call No.:   QA142.S9
Dewey No.:     511
Subjects:      Number concept.
               Arithmetic -- Foundations.
               Arithmetic -- Study and teaching.
Control No.:   1221213

Author:        Wallace, William, Jr.
Title:         The rule of nine, simplified and expanded; an
                  easy, speedy way to check addition, subtraction,
                  multiplication, and division.
Published:     Annapolis, U.S. Naval Institute [1959]
Description:   27 p. 23 cm.
LC Call No.:   QA142.W3
Dewey No.:     511.2018
Subjects:      Nine (The number)
               Ratio and proportion.
               Arithmetic -- Problems, exercises, etc.
Control No.:   8419116

Author:        Wieleitner, Heinrich Karl, 1874-
Title:         Die sieben rechnungsarten mit allgemeinen zahlen
Published:     Leipzig Berlin, B. G. Teubner, 1912.
Description:   2 p.l., 70, [2] p. 19 cm.
LC Call No.:   QA142.W5
Subjects:      Arithmetic.
Control No.:   9169323

Author:        Wilson, Guy Mitchell, 1876-
Title:         A survey of the social and business usage of
                  arithmetic, by Guy Mitchell Wilson ...
Published:     New York city, Teachers college, Columbia
                  university, 1919.
Description:   v, 62 p. diagrs. 25 cm.
Series:        Teachers College, Columbia university.
                  Contributions to education, no. 100
LC Call No.:   QA142.W6
Notes:         Published also as thesis (Ph. D.) Columbia
                  university, 1918.
               Bibliography: p. 61.
Subjects:      Arithmetic.
Control No.:   7313781

Title:         Arithmetic and algebra, combining the most
                  important parts of those subjects, in a compendious form,
                  with a variety of examples, and all the senate-house
                  examiniation papers that have been proposed, within the last
                  six years, to candidates for the ordinary B. A. degree.
Published:     Cambridge, Printed by and for J. Hall; [etc.,
                  etc.] 1835.
Description:   p. cm.
LC Call No.:   QA145.A7
Subjects:      Arithmetic -- Early works to 1900.
               Algebra.
Control No.:   8667219

Author:        Adhémar, Joseph Alphonse, 1797-1862. [from old
                  catalog]
Title:         Traité complet d'arithmétique,
Published:     Paris, 1833.
Description:   2 pt. in 1 v. 14 cm.
LC Call No.:   QA145.C8
Subjects:      Arithmetic -- Early works to 1900.
Control No.:   9603071

Author:        Coleman, S. E. (Silas Ellsworth), 1865-
Title:         An algebraic arithmetic; being an exposition of
                  the theory and practice of advanced arithmetic, based on the
                  algebraic equation, by S.E. Coleman ...
Published:     New York, London, The Macmillan company, 1898.
Description:   xiii, 151 p. 19 cm.
LC Call No.:   QA145.C7
Subjects:      Arithmetic -- Early works to 1900.
Control No.:   744818

Author:        Condillac, [Étienne Bonnot de], 1714-1780. [from
                  old catalog]
Title:         Théorie des calculs, ouvrage extrait de celui de
                  Condillac, intitulée Langue des calculs,
Published:     Paris [Sèvres, Impr. de J. L. Joly] 1833.
Description:   3 pts. in 1 v. 14 cm.
LC Call No.:   QA145.C8
Subjects:      Arithmetic -- Study and teaching.
Control No.:   6325699

Author:        Cooley, James Avas, 1901-
Title:         Basic mathematics review : text and workbook /
Published:     New York : Macmillan, [1962]
Description:   279 p. : illus. ; 28 cm.
LC Call No.:   QA145.C82
Subjects:      Arithmetic.
               Algebra.
Control No.:   6097229

Author:        Davidson, John, mathematician.
Title:         Teach yourself mathematics; a book of
                  self-instruction in essential mathematics based on the work
                  by John Davidson.
Edition:       Completely rev. and enl. by E. T. Moore.
Published:     New York, Roy Publishers, [1959?]
Description:   239 p. illus. 18 cm.
Series:        The Teach yourself books
LC Call No.:   QA145.D3 1959
Dewey No.:     511
Subjects:      Arithmetic.
               Algebra.
Other authors: Moore, Ernest Trevor.
Control No.:   6077226

Author:        De Morgan, Augustus, 1806-1871. [from old
                  catalog]
Title:         Elements of arithmetic.
Published:     London, J. Walton, 1869.
Description:   vi, p., 1 l., 220 p. 21 cm.
LC Call No.:   QA145.D4
Subjects:      Arithmetic -- Early works to 1900.
               Algebra.
Control No.:   6467576

Author:        Dresner, Simon.
Title:         The Collier quick and easy guide to arithmetic /
                  Simon Dresner.
Edition:       1st ed.
Published:     New York, N.Y. : Collier Books, 1962.
Description:   123 p. : ill. ; 28 cm.
LC Call No.:   QA145.D7
Notes:         "A Collier Books original."
Subjects:      Arithmetic.
               Numerical calculations.
Other titles:  Arithmetic.
Control No.:   9375659

Author:        Glenn, William H.
Title:         Number patterns [by] William H. Glenn [and]
                  Donovan A. Johnson.
Published:     St. Louis, Webster Pub. Co., c1960.
Description:   47 p. illus. 23 cm.
Series:        Exploring mathematics on your own
LC Call No.:   QA145.G55
Dewey No.:     512.81
Notes:         Includes bibliography.
Subjects:      Number concept.
               Arithmetic.
               Algebra.
Other authors: Johnson, Donovan A. joint author.
Control No.:   10298166

Author:        Hartsell, Lester C. [from old catalog]
Title:         Essentials of mathematics,
Published:     Johnson City, Tenn., c1962.
Description:   229 p. illus. 28 cm.
LC Call No.:   QA145.H3
Subjects:      Arithmetic.
               Algebra.
Other authors: Wilson, Charles William, 1921- [from old catalog]
                  joint author.
Control No.:   9847894

Author:        Heis, Eduard, 1806-1877.
Title:         Sammlung von beispielen und aufgaben aus der
                  allgemeinen arithmetik und algebra.
Edition:       53. aufl.
Published:     Köln, M. DuMont-Schauberg; [etc., etc.] 1879.
Description:   2 p.l., 402, [2] p. 22 cm.
LC Call No.:   QA145.H4 1879
Subjects:      Arithmetic -- Problems, exercises, etc.
               Algebra -- Problems, exercises, etc.
Control No.:   7355532

Author:        Kinney, Lucien B. (Lucien Blair), b. 1895.
Title:         Holt general mathematics [by] Lucien B. Kinney,
                  Vincent Ruble [and] M. Russell Blythe.
Published:     New York, Holt [1960]
Description:    595 p. illus. 25 cm.
Series:        The Holt mathematics program
LC Call No.:   QA145.K5
Dewey No.:     511
Subjects:      Arithmetic.
               Algebra.
               Geometry.
Control No.:   7488798

Author:        Lay, L. Clark.
Title:         Arithmetic: an introduction to mathematics.
Published:     New York, Macmillan [1961]
Description:   xiii, 323 p. illus. 26 cm.
LC Call No.:   QA145.L27
Dewey No.:     510
Subjects:      Arithmetic.
               Algebra.
Control No.:   9368395

Author:        Layton, William Isaac, 1913-
Title:         College arithmetic.
Published:     New York, Wiley [1959]
Description:   ix, 200 p. illus. 22 cm.
LC Call No.:   QA145.L3
Dewey No.:     510
Subjects:      Arithmetic.
               Algebra.
               Geometry.
Control No.:   9824174

Author:        Lübsen, H. B. (Heinrich Borchert), 1801-1864.
Title:         Mathematics self-taught: the Lübsen method for
                  self-instruction, and use in the problems of practical life.
                  I. Arithmetic and algebra; adapted from the German of H.B.
                  Lübsen by Henry Harrison Suplee ...
Published:     Philadelphia, [Gillespie bros., printers,
                  Stamford, Conn.] 1897.
Description:   2 p.l., 333, iv p. 23 cm.
LC Call No.:   QA145.L9
Subjects:      Arithmetic -- Early works to 1900.
               Algebra.
Other authors: Suplee, Henry Harrison.
Control No.:   272583

Author:        Martin, Grace C.
Title:         Practical mathematics, by Grace C. Martin and Ann
                  Smalley.  Prepared under the direction of Educational Science
                  Division, a division of U.S. Industries, inc.
Edition:       [1st ed.]
Published:     Garden City, N.Y., Doubleday, 1962.
Description:   698 p. illus. 22 cm.
Series:        A Tutortext
LC Call No.:   QA145.M28
Dewey No.:     510.76
Subjects:      Arithmetic -- Problems, exercises, etc.
               Algebra -- Problems, exercises, etc.
               Programmed instruction.
Control No.:   6559065

Author:        Mueller, Francis J. [from old catalog]
Title:         Essential mathematics for college students.
Published:     Englewood Cliffs, N.J., Prentice-Hall, 1958.
Description:   238 p. illus. 28 cm.
LC Call No.:   QA145.M8
Subjects:      Arithmetic.
               Algebra.
Control No.:   7012914

Author:        Nielsen, Kaj Leo, 1914-
Title:         Mathematics for practical use.
Published:     [New York] Barnes & Noble [1962]
Description:   237 p. illus. 21 cm.
Series:        Everyday handbook, no. 212
LC Call No.:   QA145.N53
Dewey No.:     510
Subjects:      Arithmetic.
               Algebra
               Geometry
Control No.:   7501964

Author:        Ohm, M. [from old catalog]
Title:         Algebraische, geometrische & trigonometrische
Published:     1826.
Description:   p. cm.
LC Call No.:   QA145.O3
Control No.:   10468943

Author:        Olney, Edward, 1827-1887. [from old catalog]
Title:         The science of arithmetic, for high schools,
                  normal schools, preparatory departments to colleges, and
                  academies.
Published:     New York, Sheldon & company, 1876.
Description:   viii, 294 p. 19 cm.
LC Call No.:   QA145.O5
Subjects:      Arithmetic -- Early works to 1900.
Control No.:   7730339

Author:        Peck, Lyman C., 1920-
Title:         Secret codes, remainder arithmetic, and
                  matrices.
Published:     Washington, National Council of Teachers of
                  Mathematics [1961]
Description:   54 p.
LC Call No.:   QA145.P4
Notes:         Includes bibliography.
Subjects:      Arithmetic.
               Matrices.
               Ciphers.
Control No.:   8900547


Author:        Buckingham, Guy Emerson, 1899- [from old
                  catalog]
Title:         Diagnostic and remedial teaching in first year
                  algebra,
Published:     [Evanston, Ill., c1933]
Description:   1 p. l., xi, 136 p. diagrs. 24 cm.
Series:        Northwestern University contributions to
                  education. School of Education series, no. 11
LC Call No.:   QA159.B8 1933
Subjects:      Algebra -- Study and teaching.
               Algebra -- Examinations, questions, etc.
Other authors: Gilliland, Gladys Josephine, [from old catalog]
                  joint author.
               Hottenstein, Estella Lois, [from old catalog]
                  joint author.
               Tucker, Guy Emmett, [from old catalog] joint
                  author.
Control No.:   9696434

Author:        Calandra, Alexander.
Title:         A project in the teaching and development of an
                  integrated physics-algebra course at the ninth grade level.
Published:     [St. Louis? 1959]
Description:   138 l. illus. 29 cm.
LC Call No.:   QA159.C25
Dewey No.:     512.0712
Notes:         Cover title: U.S. education: algebra, physics.
               "Prepared at Washington University, St. Louis,
                  Mo., under Cooperative research project no. 403 (7672), of
                  the Office of Education, U.S. Department of Health,
                  Education, and Welfare."
               "First partially summarized in an article
                  published in the American mathematical monthly in May, 1959."
                  Reprint is inserted.
Subjects:      Algebra -- Study and teaching (Secondary)
               Physics -- Study and teaching (Secondary)
Other authors: Washington University (Saint Louis, Mo.)
Other titles:  Integrated physics-algebra course.
               U.S. education: algebra, physics.
Control No.:   277470

Author:        Calandra, Alexander. [from old catalog]
Title:         A project in the teaching and development of an
                  integrated physics-algebra course at the ninth grade level.
Published:     [St. Louis, Washington University, 1961?]
Description:   138 p. illus., diagrs., facsims. 29 cm.
LC Call No.:   QA159.C25 1961
Subjects:      Algebra -- Study and teaching (Secondary)
               Physics -- Study and teaching (Secondary)
Other authors: Washington University, St. Louis. [from old
                  catalog]
Other titles:  Integrated physics-algebra course.
Control No.:   7499326

Author:        Calhoun, John William, 1871- [from old catalog]
Title:         Make algebra talk.
Published:     Austin, The University, 1946.
Description:   20 p. 22 cm.
Series:        The University of Texas publication no. 4623
LC Call No.:   QA159.C3
Notes:         "The material in this bulletin consists mainly of
                  six articles written for the Interscholastic leaguer during
                  the school year 1945-46."
Subjects:      Algebra -- Study and teaching.
Control No.:   13181252

Author:        Châteauneuf, Amy Olive.
Title:         Changes in the content of elementary algebra
                  since the beginning of the high school movement, as revealed
                  by the textbooks of the period ... [by] Amy Olive
                  Châteauneuf.
Published:     Philadelphia, [c1930]
Description:   2 p.l., iii-x, 191 p. diagrs. 23 cm.
LC Call No.:   QA159.C45 1929
Dewey No.:     375.512
Notes:         Thesis (PH. D.)--University of Pennsylvania,
                  1929.
               On cover: University of Pennsylvania.
               Bibliography: p. 163-186.
Subjects:      Algebra -- Study and teaching.
Other titles:  Elementary algebra, Changes in the content of.
Control No.:   2635470

Author:        Clark, Mary L.
Title:         The adventures of X, dramatized by Mary L. Clark,
                  Wallace A. Newlin, Arthur E. Smothers.
Published:     Boston, New York [etc.] D. C. Heath & Co.
                  [c1920]
Description:   viii, 43 p. plates. 19 cm.
LC Call No.:   QA159.C5
Notes:         "Suggested by a story of the same name, written
                  by Ida M. Brown of London, Eng.  With the kind permission of
                  the author and the editor of the Open court, in which
                  magazine the article originally appeared."
Subjects:      Algebra -- Study and teaching.
Other authors: Newlin, Wallace Alfred, joint author.
               Smothers, Arthur Elton, joint author.
Control No.:   6848174

Author:        Cleveland. Public Schools. Division of
                  Mathematics. [from old catalog]
Title:         Teachers' guide: eighth grade algebra for the
                  academically talented.
Published:     Columbus, 1963.
Description:   iv, 107 p. illus. 28 cm.
LC Call No.:   QA159.C55
Subjects:      Algebra -- Study and teaching (Elementary)
Other authors: Horn, Raymond A. [from old catalog]
Other authors: Ohio. Division of Special Education. [from old
                  catalog]
Other titles:  Eighth grade algebra for the academically
                  talented.
               Algebra for the academically talented.
Control No.:   6123695

Author:        Correll, Floe E., 1879- [from old catalog]
Title:         Exercises in arithmetic,
Published:     Waverly, Iowa, Correll Francis [c1917]
Description:   71, [1] p. 1 illus. 20 cm.
LC Call No.:   QA159.C8
Subjects:      Arithmetic -- Problems, exercises, etc.
Other authors: Francis, May E., 1880- [from old catalog] joint
                  author.
Control No.:   7309769

Author:        Crosby, Gwladys.
Title:         Mathematics individual learning experiment [by]
                  Gwladys Crosby, Herbert Fremont [and] Harold E. Mitzel.
Published:     [n. p., 1961?]
Description:   107 p. illus. 28 cm.
LC Call No.:   QA159.C7
Notes:         Includes bibliography.
Subjects:      Algebra -- Study and teaching (Secondary)
Control No.:   6576559

Author:        Douglass, Harl Roy, 1892-
Title:         The derivation and standardization of a series of
                  diagnostic tests for the fundamentals of first year algebra,
                  by Harl Roy Douglass.
Published:     [Eugene, Or.] The University, 1921.
Description:   48 p. diagrs. 25 cm.
Series:        University of Oregon publication. v. 1, no. 8.
                  April, 1921
LC Call No.:   QA159.D7
Notes:         Bibliography: p. 47-48.
Subjects:      Algebra -- Study and teaching.
Control No.:   5913305

Author:        Douglass, Harl Roy. [from old catalog]
Title:         The Douglass standard diagnostic tests for
                  measuring achievement in first year algebra.
Published:     [Eugene. Or.] The University, 1924.
Description:   37, [4] p. diagrs. 26 cm.
LC Call No.:   QA159.D7 1923
Subjects:      Algebra -- Study and teaching.
Control No.:   5921760

Author:        Durell, Fletcher, 1859-1946.
Title:         Suggestions on the teaching of algebra, with
                  especial reference to the use of Durell and Arnold's
                  algebra,
Published:     New York, Chicago, Charles E. Merrill company
                  [c1924]
Description:   1 p.l., 22 p. 19 cm.
LC Call No.:   QA159.D8 1924
Subjects:      Algebra -- Study and teaching.
Control No.:   8728544

Author:        Durell, Fletcher, 1859-1946.
Title:         Suggestions on the teaching of algebra, with
                  special reference to the use of Durell and Arnold's algebra,
                  by Fletcher Durell ...
Published:     New York, Chicago, Charles E. Merrill Company
                  [c1921]
Description:   17 p. 19 cm.
LC Call No.:   QA159.D8
Notes:         Cover-title.
Subjects:      Algebra -- Study and teaching.
Control No.:   7318397

Author:        Everett, John Phelps, 1875-
Title:         The fundamental skills of algebra, by John Phelps
                  Everett.
Published:     New York city, Teacvhers college, Columbia
                  University, 1928.
Description:   vi p., 1 L., 109 p., 1 L. diagrs. 23 cm.
LC Call No.:   QA159.E8 1928
Notes:         Vita.
               Published also as Teachers college, Columbia
                  university, Contributions to education, no. 324.
               Thesis (Ph. D.)--Columbia university, 1928.
Subjects:      Algebra -- Study and teaching.
               Ability
Control No.:   7806403

Author:        Everett, John Phelps, 1875- [from old catalog]
Title:         The fundamental skills of algebra,
Published:     New York city, Teachers college, Columbia
                  university, 1928.
Description:   vi p., 1 l., 109 p. diagrs. 24 cm.
LC Call No.:   QA159.E8 1928a
Subjects:      Algebra -- Study and teaching.
               Ability. [from old catalog]
Control No.:   9211482

Author:        Hazard, William J [from old catalog]
Title:         Algebra notes,
Published:     New York, Vantage Press [c1952]
Description:   p. cm.
LC Call No.:   QA159.H35
Subjects:      Algebra.
Control No.:   10247500

Author:        Hotz, Henry Gustave, 1880-1972.
Title:         First year algebra scales [by] Henry Gustave Hotz
                  ...
Published:     New York city, Teachers college, Columbia
                  University, 1918.
Description:   3 p.l., 87, [1] p. diagrs. 25 cm.
LC Call No.:   QA159.H7
Notes:         Thesis (Ph. D.)--Columbia university, 1918.
               Vita.
               Published also as Contributions to education,
                  Teachers college, Columbia university no. 90.
Subjects:      Algebra -- Study and teaching.
               Mathematical ability -- Testing.
Control No.:   2162146

Author:        Hotz, Henry Gustave, 1880-1972.
Title:         Teacher's manual for First year algebra scales,
                  by Henry G. Hotz.
Published:     New York city, Teachers college, Columbia
                  university, 1922.
Description:   46 p. incl. tables, diagrs. 23 cm.
LC Call No.:   QA159.H75
Subjects:      Algebra -- Study and teaching.
               Mental tests.
               Ability.
Control No.:   6852162

Author:        Hotz, Henry Gustave, 1880- [from old catalog]
Title:         First year algebra scales
Published:     New York city, Teachers college, Columbia
                  university, 1918.
Description:   3 p. l., 87 p. incl. tables, diagrs. 24 cm.
LC Call No.:   QA159.H7 1918a
Subjects:      Algebra -- Study and teaching.
               Mathematical ability -- Testing. [from old
                  catalog]
Control No.:   5908705

Author:        Kellar, Wylma Rose.
Title:         The relative contribution of certain factors to
                  individual differences in algebraic problem solving ability /
                  by Wylma Rose Kellar, A. M.
Published:     Washington, D.C. : The Catholic University of
                  America press, 1939.
Description:   14 p. : ill. ; 26 cm.
LC Call No.:   QA159.K4 1939
Notes:         Thesis (PH. D.)--Catholic University of America,
                  1940.
               Reprinted from the Journal of experimental
                  education Sept. 1939.
               Bibliography : p. 10.
Subjects:      Algebra -- Study and teaching.
               Problem solving.
Other titles:  Individual differences in algebraic problem
                  solving ability.
Control No.:   7381371

Author:        Kunkel, Paul Vance, 1903-
Title:         The vocabulary of high school algebra; a study of
                  the technical and semitechnical words and phrases most
                  commonly used in certain recent elementary and intermediate
                  algebra textbooks, by Paul Vance Kunkel ...
Published:     Allentown, Pa., 1939.
Description:   3 p.l., 168 p. 23 cm.
LC Call No.:   QA159.K8 1939
Dewey No.:     512.014
Notes:         Thesis (PH. D.)--Columbia university, 1939.
               Vita.
               Published also without thesis note.
               Bibliography: p. 165-167.
Subjects:      Algebra -- Terminology.
Control No.:   1219203

Author:        Kunkel, Paul Vance, 1903- [from old catalog]
Title:         The vocabulary of high school algebra; a study of
                  the technical and semitechnical words and phrases most
                  commonly used in certain recent elementary and intermediate
                  algebra textbooks,
Published:     Allentown, Pa., 1939.
Description:   3 p.l., 168 p. 23 cm.
LC Call No.:   QA159.K8 1939a
Subjects:      Algebra -- Terminology.
Control No.:   6439303

Author:        Lawrence, Ann, 1946-
Title:         Lessons for algebraic thinking. Grades 6-8 / Ann
                  Lawrence, Charlie Hennessy.
Published:     Sausalito, CA : Math Solutions Publications,
                  c2002.
Description:   xvi, 258 p. : ill. ; 28 cm.
Series:        Lessons for algebraic thinking series
LC Call No.:   QA159.L38 2002
Dewey No.:     512/.0071/2 21
ISBN:          0941355497 (alk. paper)
Notes:         Includes bibliographical references (p. 255) and
                  index.
Subjects:      Algebra -- Study and teaching (Middle school)
Other authors: Hennessy, Charlie.
Control No.:   12820883

Author:        Ligda, Paul. [from old catalog]
Title:         The teaching of elementary algebra, by Paul Ligda
                  ... with an introduction by John Wesley Young ...
Published:     Boston, New York [etc.] Houghton Mifflin company,
                  [c1925]
Description:   xvii, 256 p. illus., diagrs. 20 cm.
LC Call No.:   QA159.L5
Subjects:      Algebra -- Study and teaching.
Control No.:   13158966

Author:        McKim, Margaret Grace, 1914-
Title:         The reading of verbal material in ninth grade
                  algebra, by Margaret Grace McKim ...
Published:     New York, Teachers college, Columbia university,
                  1941.
Description:   viii p., 1 l., 133, [1] p. incl. tables. 23 cm.
LC Call No.:   QA159.M2 1941
Notes:         Thesis (Ph. D.)--Columbia university, 1941.
               Published also as Teachers college, Columbia
                  university, Contributions to education, no. 850.
               Vita.
               Bibliography: p. 85-87.
Subjects:      Algebra -- Study and teaching.
               Reading.
Control No.:   5980469

Author:        McKim, Margaret Grace, 1914-
Title:         The reading of verbal material in ninth grade
                  algebra, by Margaret Grace McKim.
Published:     New York, Teachers College, Columbia University,
                  1941.
Description:   viii, 133 p. tables 24 cm.
Series:        Teachers College. Columbia University.
                  Contributions to education, no. 850
LC Call No.:   QA159.M2 1941a
Dewey No.:     512.0712
Notes:         Issued also as thesis (PH. D) Columbia
                  University.
               Bibliography: p. 85-87.
Subjects:      Algebra -- Study and teaching.
               Reading.
Control No.:   5981241

Author:        Meserve, Bruce Elwyn, 1917-
Title:         Foundations of algebra for high school
                  mathematics teachers; National Science Foundation summer
                  mathematics institute notes.
Published:     Stillwater, Dept. of Mathemaics, Oklahoma
                  Agricultural and Mechanical College, 1955.
Description:   151, 47 p. illus. 28 cm.
LC Call No.:   QA159.M4
Dewey No.:     512
Subjects:      Algebra -- Study and teaching.
               Algebra.
Other titles:  Algebra for high school mathematics teachers.
Control No.:   6524772

Author:        Michael, Ruby Eldon, 1907- [from old catalog]
Title:         The relative effectiveness of two methods of
                  teaching certain topics in ninth grade algebra.
Published:     [n.p., 1949]
Description:   83-87 p. tables. 26 cm.
LC Call No.:   QA159.M5
Subjects:      Algebra -- Study and teaching.
Control No.:   9317688

Author:        Novello, Russell R.
Title:         Differential factors in algebraic computation for
                  high-achieving boys and girls.
Published:     Washington, Catholic University of America Press,
                  1960.
Description:   viii, 69 p. diagrs., tables. 23 cm.
Series:        Catholic University of America. Educational
                  research monographs, v. 23, no. 2
LC Call No.:   QA159.N67
Dewey No.:     512.0712
Notes:         Issued also as thesis--Catholic University of
                  America.
               Bibilography: p. 67-69.
Subjects:      Algebra -- Study and teaching (Secondary)
               Sex (Psychology)
Control No.:   6111103

Author:        O'Brien, Katharine E. (Katharine Elizabeth)
                  editor.
Title:         Successful devices in teaching algebra.
Published:     Portland, Me., J. W. Walch, c1955.
Description:   150 p. illus. 28 cm.
LC Call No.:   QA159.O2
Dewey No.:     512.07
Subjects:      Algebra -- Study and teaching.
Control No.:   10271938

Author:        Overn, Orlando Evan Anthony, 1885-
Title:         Requirements and examinations in elementary
                  algebra of the College entrance examination board from 1900
                  to 1935, by Orlando Evan Anthony Overn ...
Published:     [Ann Arbor, 1937]
Description:   3 p. l., p. 373-468, 1 l. diagrs. 20 cm.
LC Call No.:   QA159.O9 1937
Notes:         Thesis (Ph. D.)--Columbia university, 1937.
               Vita.
               "Reprinted from the June, 1937, issue of the
                  Journal of experimental education."
               Bibliography: p. 462-465.
Subjects:      Algebra -- Examinations, questions, etc.
               College entrance examination board.
               Algebra -- Study and teaching.
Control No.:   9244258

Author:        Pease, Glenn Richard, 1889- [from old catalog]
Title:         An analysis of the learning-units in N processes
                  in algebra,
Published:     [New York, 1929]
Description:   p. cm.
LC Call No.:   QA159.P4 1928
Subjects:      Algebra -- Study and teaching.
Control No.:   10150135

Author:        Pickard, Willis Lloyd.
Title:         Evolution of algebra as a secondary school
                  subject.
Published:     Nashville, Tenn., George Peabody College for
                  Teachers [c1948]
Description:   xvi, 121 p. diagrs. 24 cm.
Series:        George Peabody College for Teachers. Contribution
                  to education no. 397.
LC Call No.:   QA159.P5
Dewey No.:     512.0712
Notes:         Bibliography: p. 120-121.
Subjects:      Algebra -- Study and teaching.
Series Entry:  George Peabody College for Teachers. Contribution
                  to education ; no.397.
Control No.:   7415178

Author:        Powell, Jesse Jerome, 1891-
Title:         A study of problem material in high school
                  algebra,
Published:     New York city, Teachers college, Columbia
                  university, 1929.
Description:   4 p.l., 100 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA159.P6 1930
Subjects:      Algebra -- Study and teaching.
               Algebra -- Problems, exercises, etc.
Other titles:  Problem material in high school algebra, A study
                  of.
Control No.:   10151722

Author:        Powell, Jesse Jerome, 1891-
Title:         A study of problem material in high school
                  algebra, by Jesse Jerome Powell.
Published:     New York city, Teachers college, Columbia
                  university, 1929.
Description:   4 p. l., 100 p. diagrs. 24 cm.
Series:        Teachers college, Columbia university.
                  Contributions to education, no. 405
LC Call No.:   QA159.P6 1929
Notes:         Published also as thesis (Ph. D.) Columbia
                  university.
Subjects:      Algebra -- Study and teaching.
               Algebra -- Problems, exercises, etc.
Other titles:  Problem material in high school algebra, A study
                  of.
Control No.:   9683461

Author:        Pyke, Alfred Joseph, 1880-
Title:         Functional thinking and the study of functional
                  relations in elementary algebra.
Published:     Chicago, 1935.
Description:   xii, 415 l. illus. 32 cm.
LC Call No.:   QA159.P84
Notes:         Thesis--University of Chicago.
               Bibliography: leaves 308-311.
Subjects:      Algebra -- Study and teaching.
               Functions.
Control No.:   1765919

Author:        Pyke, Alfred Joseph, 1880- [from old catalog]
Title:         Functional thinking and the study of functional
                  relations in elementary algebra ...
Published:     [Chicago] 1935.
Description:   [72] p. incl. tables, diagrs. 24 cm.
LC Call No.:   QA159.P85 1935
Subjects:      Algebra -- Study and teaching.
               Functions. [from old catalog]
Control No.:   7829740

Author:        Schmitz, Sylvester. [from old catalog]
Title:         Measurements in first year algebra; a study of
                  their present status.
Published:     Washington, D.C., The Catholic education press
                  [c1926]
Description:   1. Algebra--Study and teaching.
LC Call No.:   QA159.S3
Subjects:      Mental tests. [from old catalog]
Control No.:   7799326

Author:        School Mathematics Study Group.
Title:         Introduction to algebra. Prepared under the
                  supervision of a panel consisting of V. H. Haag [and others]
Edition:       Rev. ed.
Published:     [Ann Arbor? Mich., c1961-
Description:     v. illus. 28 cm.
LC Call No.:   QA159.S34
Notes:         Part 4 is Prelim. ed.
Subjects:      Algebra -- Study and teaching.
Control No.:   10311591

Author:        School Mathematics Study Group.
Title:         Study guide in modern algebra.
Published:     [New Haven? 1959]
Description:   12 p. 23 cm.
LC Call No.:   QA159.S35
Dewey No.:     512.0712
Notes:         Bibliography: p. 11-12.
Subjects:      Algebra -- Study and teaching.
               Algebra -- Bibliography.
Control No.:   277421

Author:        Simons, Lao Genevra, 1870-
Title:         Introduction of algebra into American schools in
                  the eighteenth century,
Published:     [Washington, 1924]
Description:   vi, 80 p., 1 l. illus. (facsims.) 23 cm.
LC Call No.:   QA159.S5 1925
Subjects:      Algebra -- Study and teaching.
               Algebra -- History.
Control No.:   6392298

Author:        Smith, David Eugene, 1860-1944.
Title:         The progress of algebra in the last quarter of a
                  century, by David Eugene Smith ...
Published:     Boston, New York [etc.] Ginn and company [c1925]
Description:   v, 86 p. illus., diagrs. 21 cm.
LC Call No.:   QA159.S6
Notes:         "Publisher's supplement; historical pages in
                  algebra": p. [69]-86.
Subjects:      Algebra -- Study and teaching.
Control No.:   13410709

Author:        Symonds, Percival Mallon, 1893-1960.
Title:         Special disability in algebra / by Percival
                  Mallon Symonds.
Published:     New York : Teachers College, Columbia University,
                  1923.
Description:   vii, 88 p. ; 24 cm.
Series:        Columbia University. Teachers College.
                  Contributions to education ; no. 132
LC Call No.:   QA159.S3 1923
Notes:         Originally presented as the author's thesis,
                  Columbia.
               Bibliography: p. 86-88.
Subjects:      Algebra -- Study and teaching.
               Mathematical ability -- Testing.
Series Entry:  Contributions to education ; no. 132.
Control No.:   5918224

Author:        Symonds, Percival Mallon, 1893-1960.
Title:         Special disability in algebra. New York, Teachers
                  College, Columbia University, 1923.
Published:     [New York, AMS Press, 1972]
Description:   vii, 88 p. 22 cm.
LC Call No.:   QA159.S8 1972
Dewey No.:     512.9/07
ISBN:          0404551327
Notes:         Reprint of the 1923 ed., issued in series:
                  Teachers College, Columbia University. Contributions to
                  education, no. 132.
               Originally presented as the author's thesis,
                  Columbia.
               Bibliography: p. 86-88.
Subjects:      Algebra -- Study and teaching.
               Mathematical ability -- Testing.
Series Entry:  Columbia University. Teachers College.
                  Contributions to education, no. 132.
Control No.:   312524

Author:        Symonds, Percival Mallon, 1893- [from old
                  catalog]
Title:         Special disability in algebra,
Published:     New York city, Teachers college, Columbia
                  university, 1923.
Description:   vii, 89 p. diagrs. 25 cm.
LC Call No.:   QA159.S8 1923a
Subjects:      Algebra -- Study and teaching.
               Mental tests. [from old catalog]
Control No.:   5918881

Author:        Thorndike, Edward L. (Edward Lee), 1874-1949.
Title:         The psychology of algebra, by Edward L.
                  Thorndike, Margaret V. Cobb, Jacob S. Orleans, Percival M.
                  Symonds, Elva Wald and Ella Woodyard ...
Published:     New York, The Macmillan company, 1923.
Description:   xi, 483 p. diagrs. 21 cm.
LC Call No.:   QA159.T5
Notes:         "Bibliography of references made in the text": p.
                  465-469.
Subjects:      Algebra -- Study and teaching.
Other authors: Cobb, Margaret V. (Margaret Vara), b. 1884.
               Orleans, Jacob S. (Jacob Samuel), 1899-
               Symonds, Percival Mallon, 1893-1960.
               Wald, Elva.
               Woodyard, Ella, b. 1878.
Control No.:   4526506

Author:        Weiden, Robertine, Sister, 1902-
Title:         The effect of checked directed study upon
                  achievement in ninth grade algebra / by Sister Robertine
                  Weiden.
Published:     Baltimore : Johns Hopkins Press, 1945.
Description:   xii, 87 p. : tables, diagrs. ; 25 cm.
LC Call No.:   QA159.W4
Notes:         "Reprinted from 'The Johns Hopkins university
                  studies in education,' number 34."
               Vita.
               Thesis (Ed. D.)--Johns Hopkins University, 1941.
               Bibliography: p. 74-82.
Subjects:      Algebra -- Study and teaching.
               Mental tests.
Control No.:   9742223

Author:        Weiden, Robertine, sister, 1902- [from old
                  catalog]
Title:         The effect of checked directed study upon
                  achievement in ninth grade algebra,
Published:     Baltimore, The Johns Hopkins press, 1945.
Description:   xii, 87 p. incl. tables, diagrs. 25 cm.
LC Call No.:   LB5.J6 no.34
Subjects:      Algebra -- Study and teaching.
               Mental tests. [from old catalog]
Control No.:   8337251

Author:        Wentworth, G. A. (George Albert), 1835-1906.
Title:         Elements of algebra.
Edition:       Complete ed.
Published:     Bostin, Ginn, Heath, & co., 1883.
Description:   xv, 510 p. 20 cm.
LC Call No.:   QA159.W49 1883
Subjects:      Algebra.
Control No.:   9172274

Author:        White, Annabel Lee, 1884- [from old catalog]
Title:         The retention of elementary algebra through
                  quadratics, after varying intervals of time,
Published:     Washington, Judd and Detweiler, inc., 1932.
Description:   v, 66 p., 1 l. diagrs. 24 cm.
LC Call No.:   QA159.W5 1930
Subjects:      Algebra -- Study and teaching.
               Mental tests. [from old catalog]
Control No.:   6883680

Title:         Ratio and proportion.
Published:     [n.p., n.d.]
Description:   68 p. 23 cm.
LC Call No.:   QA161.R2
Control No.:   6327951

Author:        Anderson, Archibald James Camillus, 1846-
Title:         Some re-discovered algebra, by Archibald J. C.
                  Anderson.
Published:     New York, The author [c1916]
Description:   7 p. 21 cm.
LC Call No.:   QA161.A55
Subjects:      Algebra.
Control No.:   5900769

Author:        Beckenbach, Edwin F.
Title:         An introduction to inequalities, by Edwin
                  Beckenbach [and] Richard Bellman.
Published:     [New York] Random House [1961]
Description:   133 p. illus. 23 cm.
Series:        New mathematical library, 3
LC Call No.:   QA161.B4
Dewey No.:     512
Subjects:      Inequalities (Mathematics)
Other authors: Bellman, Richard Ernest, 1920- joint author.
Control No.:   277858

Author:        Beman, Wooster Woodruff, 1850-1922. [from old
                  catalog]
Title:         Indeterminate coefficients and variables and
                  limits ...
Published:     Boston, London [etc.] 1904.
Description:   p.
LC Call No.:   QA161.B45
Notes:         For full entry see Main Card Catalog.
Control No.:   9544371

Author:        Bonnafous, Émile. [from old catalog]
Title:         Mathématiques simplifiées pour aborder l'étude
                  de l'électricité et de la radio.
Published:     Paris, Technique et vulgarisation, 1947.
Description:   110 p. illus. 21 cm.
LC Call No.:   QA161.B68
Subjects:      Algebra.
               Trigonometry. [from old catalog]
               Electric engineering -- Tables.
Control No.:   9814397

Author:        Brooks, E: [from old catalog]
Title:         Elaboration of sec. III. Brook's Normal
                  elementary algebra.
Published:     [n. p.] [c1904]
Description:   1 v. cm.
LC Call No.:   QA161.B87
Control No.:   9073218

Author:        Budanëtìsev, Petr Alekseevich. [from old
                  catalog]
Title:         Kvadratnye i irraëtìsional§ney uravneniëiìa.
Published:     1956.
Description:   117 p. 20 cm.
LC Call No.:   QA161.B9
Notes:         Romanized.
Subjects:      Equations. [from old catalog]
Other authors: Shchipakin, Grioriæi Mikhaæilovich, [from old
                  catalog] joint author.
Control No.:   7994361

Author:        Cabin, Sidney. [from old catalog]
Title:         Basic facts of 11th-year mathematics.
Edition:       [1st ed.]
Published:     New York, Collier Books [1963]
Description:   64 p. diagrs. 18 cm.
LC Call No.:   QA161.C13
Subjects:      Algebra.
               Geometry. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   7977908

Author:        Cameletti, Ignazio. [from old catalog]
Title:         Il binomio di Newton,
Published:     Genova, Tipografia del R. Istituto sordo-muti,
                  1880.
Description:   9 p. 28 cm.
LC Call No.:   QA161.C18
Subjects:      Binomial theorem.
Control No.:   6797335

Author:        [Chauvenet, William] 1820-1870. [from old
                  catalog]
Title:         Binomial theorem and logarithms.
Published:     Philadelphia-Perkins & Purves, 1843.
Description:   92 p. 24 cm.
LC Call No.:   QA161.C5
Subjects:      Binomial theorem.
               Logarithms.
Control No.:   7733151

Author:        Ch°en, Ming-che, fl. 1963- [from old catalog]
Title:         Fen chieh yin shih.
Published:     [1963]
Description:   101 p. 19 cm.
LC Call No.:   QA161.F3C46
Notes:         Romanized.
Subjects:      Factors (Algebra)
Control No.:   7639257

Author:        Chung-kuo shu hsüeh hui. Shang-hai fên hui.
                  Chung hsüeh shu hsüeh yen chiu wei yüan hui.
Title:         Lien ho, êrh hsiang shih ting li chi fu shu.
Published:     1957.
Description:   78 p. illus. 19 cm.
LC Call No.:   QA161.C54
Notes:         Romanized.
Subjects:      Binomial theorem.
Control No.:   7020084

Author:        Constant, Benjamin, 1836-1891.
Title:         Theoria das quantidades negativas: trabalho feito
                  por Benjamin Constant Botelho de Magalhães ... Apresentado
                  ao Instituto polytechnico nas ultimas sessões de dezembro de
                  1867.
Published:     Petropolis, Typographia do Mercantil de B.P.
                  Sudré, 1868.
Description:   82 p. diagrs. 22 cm.
LC Call No.:   QA161.B7
Control No.:   6796154

Author:        Evenson, A. B.
Title:         Modern mathematics;  introductory concepts and
                  their implications.
Published:     Chicago, Scott, Foresman [1962]
Description:   206 p. illus. 23 cm.
LC Call No.:   QA161.E8
Subjects:      Algebra.
               Mathematical analysis.
Control No.:   7970778

Author:        Heller, Hobart Franklin, 1901-
Title:         Concerning the evolution of the topic of
                  factoring in textbooks of elementary algebra published in
                  England and the United States from 1631 to 1890, by Hobart
                  Franklin Heller ...
Published:     Berwick, Pa. [Printed by Keystone publishing co.]
                  1940.
Description:   vi, 165, [1] p. 23 cm.
LC Call No.:   QA161.H45 1940
Dewey No.:     512.07
Notes:         Thesis (PH. D.)--Columbia university, 1940.
               Vita.
               Published also without thesis note.
               Errata slip laid in.
               Bibliography: p. 158-162.
Subjects:      Algebra.
               Factors (Algebra)
Other titles:  Factoring.
Control No.:   2636173

Author:        Heller, Hobart Franklin, 1901- [from old
                  catalog]
Title:         Concerning the evolution of the topic of
                  factoring in text-books of elementary algebra
Published:     Berwick, Pa. [Printed by Keystone publishing co.]
                  1940.
Description:   vi, 165, [1] p. 24 cm.
LC Call No.:   QA161.H45 1940a
Subjects:      Algebra.
               Factors (Algebra)
Other titles:  Factoring.
Control No.:   8782712

Author:        Hölting, C. E. [from old catalog]
Title:         Ueber einige eigenschaften der kettenbrüche ...
Published:     Rostock, C. Boldt's buchdruckerei, 1872.
Description:   29 p. 21 cm.
LC Call No.:   QA161.H6
Subjects:      Continued fractions.
Control No.:   10074501

Author:        Hunt, E.
Title:         Algebra. An essay to prove, among other matters,
                  that fractional and negative values of "n" in arithmetical
                  progression, are legitimate and admissible, contrary to the
                  erroneous views hitherto expressed by algebraists; a
                  contribution to the theory and art of computation. By E. Hunt
                  ...
Published:     Canaan, N.H., 1914.
Description:   3 p.l., 24 p. 21 cm.
LC Call No.:   QA161.H8
Notes:         Autographed.
Subjects:      Algebra.
Control No.:   2162083

Author:        Joseph, Margaret. [from old catalog]
Title:         Byroads of algebra:
Published:     Washington, National Council of Teachers of
                  Mathematics [1955]
Description:   11 p. 13 cm.
LC Call No.:   QA161.J6
Subjects:      Algebra.
               Ready-reckoners. [from old catalog]
Control No.:   9803408

Author:        Ladshaw, George E. [from old catalog]
Title:         Fifth fundamental process of mathematics...
Published:     [n. p.] 1910.
Description:   1 v. cm.
LC Call No.:   QA161.L15
Control No.:   9542600

Author:        Laisant, C[harles] A[nge], 1841- [from old
                  catalog]
Title:         Sur les tableaux de sommes.--Nouvelles
                  applications.
Published:     Paris, Au secrétariat de l'Association, 1893.
Description:   11 p. diagr. 24 cm.
LC Call No.:   QA161.L18
Subjects:      Series. [from old catalog]
Control No.:   6332290

Author:        Lefevre, Arthur, 1863-1929.
Title:         Number and its algebra. Syllabus of lectures on
                  the theory of number and its algebra introductory to a
                  collegiate course in algebra. By Arthur Lefevre ...
Published:     Boston, D.C. Heath & co., 1896.
Description:   219 p. 19 cm.
Series:        Heath's pedagogical library
LC Call No.:   QA161.L49
Subjects:      Algebra.
               Mathematics -- Philosophy.
Control No.:   4052275

Author:        McCoart, Richard F. [from old catalog]
Title:         Elementary analysis,
Published:     Washington, Georgetown University Press [1962]
Description:   54 p. illus. 23 cm.
LC Call No.:   QA161.M3
Subjects:      Algebra.
               Aggregates. [from old catalog]
Control No.:   8907554

Author:        Nicholson, J. W. (James William), 1844-
Title:         A new, simple, and complete demonstration of the
                  binomial theorem and logarithmic series.
Published:     [Baton Rouge, La., Louisiana Capitolian Print,
                  1879]
Description:   [9] p. 19 cm.
LC Call No.:   QA161.N5
Subjects:      Series.
Control No.:   6796155

Author:        Pownall, Malcolm W.
Title:         A prelude to the calculus [by] Malcolm W.
                  Pownall.
Published:     New York, McGraw-Hill [1967]
Description:   315 p. illus. 24 cm.
LC Call No.:   QA161.P6
Dewey No.:     517
Subjects:      Algebra.
               Geometry, Analytic.
               Calculus.
Control No.:   3117019

Author:        Schaewen, Paul von.
Title:         Die Binomialkoëfficienten in Verbindung mit
                  figurierten Zahlen und arithmetischen Reihen höherer Ordung
                  / von Paul von Schaewen.
Published:     Glogau : C. Flemming, 1901.
Description:   30 p. ; 23 cm.
LC Call No.:   QA161.B48S33x 1901
Notes:         Includes bibliographical references.
Subjects:      Binomial coefficients.
Control No.:   4291648

Author:        Stevenson, William Wesley, 1875- [from old
                  catalog]
Title:         Factoring tests,
Published:     Philadelphia, Walther printing house, c1913.
Description:   8 p., 1 l. 11 x 21 cm.
LC Call No.:   QA161.S7
Subjects:      Factors (Algebra)
Control No.:   9173506

Author:        Wells, Webster, 1851-1916.
Title:         Factoring, by Webster Wells.
Published:     Boston, D. C. Heath & co., 1902.
Description:   30 p. 20 cm.
Series:        Heath's mathematical monographs, no. 7
LC Call No.:   QA161.W4
Subjects:      Factors (Algebra)
Control No.:   9131374

Author:        Wheeler, A[lbert] Harry, 1873- [from old
                  catalog]
Title:         Quadratics; advance chapters from Principles and
                  methods of algebra,
Published:     Boston, New York [etc.] Houghton, Mifflin and
                  company, 1905.
Description:   [v]-xvi, 119 p. diagrs. 19 cm.
LC Call No.:   QA161.W56
Subjects:      Equations, Quadratic. [from old catalog]
Control No.:   5862663

Author:        Young, Frederick H.
Title:         Random numbers, mathematical induction, geometric
                  numbers.
Published:     Boston, Ginn [1962]
Description:   25 p. illus. 24 cm.
Series:        Topics in modern mathematics
LC Call No.:   QA161.Y6
Dewey No.:     519.1
Subjects:      Probabilities.
               Number theory.
               Induction (Mathematics)
Other titles:  Geometric numbers.
Control No.:   1695091

Author:        Zebold, Abraham M. [from old catalog]
Title:         Analysis of the law of algebraic multiplication.
Published:     1905.
Description:   p. cm.
LC Call No.:   QA161.Z41
Control No.:   7191206

Author:        Andrews, William Symes, b. 1847.
Title:         Magic squares and cubes, by W. S. Andrews, with
                  chapters by Paul Carus, L. S. Frierson, C. A. Browne, jr.,
                  and an introduction by Paul Carus.
Published:     Chicago, The Open court publish company; [etc.,
                  etc.] 1908.
Description:   vi, 199 p. diagrs. 25 cm.
LC Call No.:   QA165.A6
Subjects:      Magic squares.
Other authors: Carus, Paul, 1852-1919.
               Frierson, Lorraine Screven, 1861-
               Browne, Charles Albert, 1870-1947.
Control No.:   8684718

Author:        Arnoux, Gabriel, 1831-
Title:         Essais de psychologie et de métaphysique
                  positives. Arithmétique graphique. Les espaces
                  arithmétiques hypermagiques, par Gabriel Arnoux.
Published:     Paris, Gauthier-Villars et fils, 1894.
Description:   xxiii, 175 p. incl. tables, diagrs. fold. col.
                  pl. 25 cm.
LC Call No.:   QA165.A7
Subjects:      Magic squares.
Other titles:  Arithmétique graphique.
Control No.:   6384788

Author:        Candy, Albert L. (Albert Luther), 1857-
Title:         Construction, classification and census of magic
                  squares of an even order, by Albert L. Candy ...
Published:     Ann Arbor, Mich., Edwards brothers, 1937.
Description:   vi, 182 p. diagrs. 21 cm.
LC Call No.:   QA165.C24
Dewey No.:     511.61
Notes:         Imprint covered by label: Lincoln, Neb., A.L.
                  Candy, 1937.
               Lithoprinted.
Subjects:      Magic squares.
Control No.:   3108867

Author:        Candy, Albert L. (Albert Luther), 1857-
Title:         Construction, classification and census of magic
                  squares of order five. By Albert L. Candy ...
Edition:       2d ed., rev. and enl.
Published:     Lincoln, Neb., A. L. Candy, 1939.
Description:   ix, 221 (i.e. 227) p. 21cm.
LC Call No.:   QA165.C25 1939
Notes:         Extra numbered pages: 41a-c. 57a-b.
               "Lithoprinted."
Subjects:      Magic squares.
Control No.:   8312163

Author:        Candy, Albert L. (Albert Luther), 1857-
Title:         Construction, classification and census of magic
                  squares of order five, by Albert L. Candy.
Published:     Lincoln, Neb., A. L. Candy, 1938.
Description:   v, 141 p. 21 cm.
LC Call No.:   QA165.C25
Dewey No.:     511.61
Notes:         "Lithoprinted."
Subjects:      Magic squares.
Control No.:   5969276

Author:        Candy, Albert L. (Albert Luther), 1857-
Title:         Pandiagonal magic squares of composite order, by
                  Albert L. Candy ...
Published:     Lincoln, Neb., A.L. Candy, 1941.
Description:   x, 155 p. 1 illus. 21 cm.
LC Call No.:   QA165.C265
Dewey No.:     511.61
Notes:         Reproduced from type-written copy.
               A complement of the author's Pandiagonal magic
                  squares of prime order. cf. Pref.
Subjects:      Magic squares.
Control No.:   274826

Author:        Candy, Albert L. (Albert Luther), 1857-
Title:         Pandiagonal magic squares of prime order, by
                  Albert L. Candy.
Published:     Lincoln, Neb., A. L. Candy, 1940.
Description:   v, 93 p. diagrs. 21 cm.
LC Call No.:   QA165.C27
Dewey No.:     511.61
Notes:         "Lithoprinted."
Subjects:      Magic squares.
Control No.:   5973681

Author:        Chatland, Harold, 1911- [from old catalog]
Title:         The asymptotic Waring problem for homogeneous
                  polynomial summands.
Published:     1937.
Description:   p. cm.
LC Call No.:   QA165.C43 1937
Subjects:      partitions (Mathematics) [from old catalog]
Control No.:   6639565

Author:        Cunningham, Allan, 1842-
Title:         Quadratic partitions. By Lt.-Col. Allan
                  Cunningham ...
Published:     London, F. Hodgson, 1904.
Description:   2 p.l., xxiii, 266 p. tables. 23 cm.
LC Call No.:   QA165.C97
Subjects:      Partitions (Mathematics)
Control No.:   3107036

Author:        Fleisher, Edward, 1884-
Title:         On Euler squares ... by Edward Fleisher.
Published:     [New York?] 1934.
Description:   1 p.l., ii, 44 p. diagrs. 24 cm.
LC Call No.:   QA165.F55 1935
Dewey No.:     511.61
Notes:         Thesis (PH.D.)--New York university, 1935.
               Planographed.
               Bibliography: p. 38-41.
Subjects:      Magic squares.
               Permutations.
               Combinations.
Other titles:  Euler squares.
Control No.:   1690978

Author:        Fleisher, Edward. [from old catalog]
Title:         On Euler squares...
Published:     [New York?] 1934.
Description:   1 v. cm.
LC Call No.:   QA165.F55 1938a
Control No.:   10014887

Author:        Gepp, Heinrich, 1884-
Title:         Über inversionssummen ...
Published:     Giessen, v. Münchow'sche druckerei (O. Kindt)
                  1906.
Description:   40 p., 1 l. 23 cm.
LC Call No.:   QA165.G5
Notes:         Inaug.-diss.--Giessen.
               Lebenslauf.
Subjects:      Permutations.
Control No.:   9149156

Author:        Hugel, Theodor.
Title:         Die magischen Quadrate mathematisch behandelt und
                  bewiesen / von Theodor Hugel.
Published:     Ansbach : C. Brügel & Sohn, [18--]
Description:   33, 7, [9] p. : ill. ; 28 cm.
LC Call No.:   QA165.H83x 1800z
Notes:         Cover title.
               "Dissertation zur Erlangung der philosophischen
                  Doctorwürde."
Subjects:      Magic squares.
Control No.:   511475

Author:        Kammer, Otto, 1879-
Title:         Inversionen bei permutationen mit wiederholung
                  ...
Published:     Giessen, Von Münchow'sche druckerei (O. Kindt)
                  1905.
Description:   21, [1] p., 1 l. 29 x 23 cm.
LC Call No.:   QA165.K3
Notes:         Inaug.-diss.--Giessen.
               Lebenslauf.
Subjects:      Permutations.
Control No.:   7275963

Author:        MacMahon, Percy A. [from old catalog]
Title:         Memoir on the theory of the partitions of numbers
                  ...
Published:     [n.p.] 1911.
Description:   v. fol. cm.
LC Call No.:   QA165.M17
Control No.:   8608814

Author:        MacMahon, Percy Alexander, 1854-1929.
Title:         Combinatory analysis, by Major Percy A. MacMahon
                  ...
Published:     Cambridge [Eng.] The University press, 1915-16.
Description:   2 v. diagrs. 27 cm.
LC Call No.:   QA165.M16
Notes:         Bibliography: v.1, p. ix-x; v.2, p. viii-ix.
Subjects:      Combinatorial analysis.
Control No.:   745712

Author:        MacMahon, Percy Alexander, 1854-1929.
Title:         An introduction to Combinatory analysis, by P.A.
                  MacMahon ...
Published:     Cambridge [Eng.] The University press, 1920.
Description:   viii, 71 p. 23 cm.
LC Call No.:   QA165.M15
Notes:         "This little book is intended to be an
                  introduction to the two volumes of Combinatory analysis,
                  which were published ... in 1915-16".--Pref.
Subjects:      Combinatorial analysis.
Control No.:   3107926

Author:        Marder, Clarence C.
Title:         The magic squares of Benjamin Franklin; the first
                  of a series of four papers describing the technique of
                  Leonhard Euler applied to the Lahireian method of forming
                  magic squares of all sizes, under the general title The
                  intrinsic harmony of number, by Clarence C. Marder; also the
                  simple method of raising any 8 x 8 square to the 16 x 16 size
                  with the aid of an auxiliary square preserving all the
                  qualities of the original.  Three entirely new methods of
                  producing the bent diagonals of Benjamin Franklin.
Published:     New York, The Brick row book shop, inc., 1940.
Description:   1 p.l., 3-36 numb. l. 28 x 22 cm.
LC Call No.:   QA165.M22
Dewey No.:     511.61
Notes:         Reproduced from type-written copy.
Subjects:      Magic squares
               Franklin, Benjamin, 1706-1790.
               Euler, Leonhard, 1707-1783.
Other titles:  Intrinsic harmony of number.
Control No.:   2636359

Author:        Margossian, A.
Title:         Contribution à l'étude des carrés magiques :
                  de l'ordonnance des nombres dans les carrés magiques impairs
                  : (procédés généraux pour leur construction immédiate) /
                  par A. Margossian.
Published:     Paris : Librairie scientifique A. Hermann, 1908.
Description:   131 p. : ill. ; 19 cm.
LC Call No.:   QA165.M37x 1908
Notes:         Half title: De l'ordonnance des nombres dans les
                  carrés magiques impairs.
Subjects:      Magic squares.
Other titles:  De l'ordonnance des nombres dans les carré
                  magique impairs.
Control No.:   4764759

Author:        Marsano, Giovanni Battista. [from old catalog]
Title:         Nota sopra una questione di posizione di numeri.
Published:     Genova, Tipografia del R. I. de' sordo-muti,
                  1870.
Description:   33 p. 22 cm.
LC Call No.:   QA165.M23
Subjects:      Permutations. [from old catalog]
Control No.:   9137910

Author:        [Marsano, Giovanni Battista] [from old catalog]
Title:         Problema: Siano dati 90 numeri dall' I al 90, e
                  si suppongano combinati a tre a tre:
Published:     [Novara, Tip. Rivista di contabilità, 186-?]
Description:   7 p. 25 cm.
LC Call No.:   QA165.M25
Subjects:      Combinations. [from old catalog]
Control No.:   8201621

Author:        Marsano, G[iovanni] B[attista] [from old
                  catalog]
Title:         Sul problema risoluto a pag. 222 della Rivista di
                  matematica elementare vol. 1, risguardante il numero dei
                  terni possibili a farsi coi primi 90 numeri, di somma
                  inferiore o uguale a 100.
Published:     [Novara, Tipografia della Rivista di
                  contabilità, 1880]
Description:   46 p. 25 cm.
LC Call No.:   QA165.M27
Subjects:      Partitions (Math.) [from old catalog]
Control No.:   5860300

Author:        Marsano, Giovanni Battista. [from old catalog]
Title:         Sulla legge delle derivate generali delle
                  funzioni di funzioni di più variabili indipendenti e sulla
                  teoria delle forme di partizione dei numeri intieri.
Published:     Genova, Co' tipi del R. I. de' sordomuti, 1870.
Description:   2 p.l., 283 p., 2 l., [27] p. tables. 32 cm.
LC Call No.:   QA165.M3
Subjects:      Partitions (Mathematics) [from old catalog]
               Differential calculus.
Control No.:   7264771

Author:        Mauch, Margaret Evelyn, 1897-
Title:         Extensions of Waring's theorem on seventh powers
                  / by Margaret Evelyn Mauch.
Published:     [Chicago], 1941.
Description:   ii leaves, 21 p. ; 24 cm.
LC Call No.:   QA165.M38
Notes:         Lithoprinted.
               Vita.
               Thesis (Ph. D.)--University of Chicago, 1938.
Subjects:      Partitions (Mathematics)
Control No.:   6448731

Author:        Mikami, Yoshio. [from old catalog]
Title:         Wasan no h¯ojin mondai.
Published:     6 [1917]
Description:   2, 2, 174 p. 25 cm.
LC Call No.:   QA165.M47
Notes:         Romanized.
Subjects:      Magic squares. [from old catalog]
               Mathematics, Japanese. [from old catalog]
Control No.:   7131987

Author:        Rinecker, Franz. [from old catalog]
Title:         Über substitutionsfunktionen modulo 11 und die
                  analytische darstellung der permutationen von 5, 7, 11
                  elementen ...
Published:     Regensburg, Verlag von A. Coppenrath, 1886.
Description:   29 p. 23 cm.
LC Call No.:   QA165.R57
Subjects:      Permutations. [from old catalog]
Control No.:   6329565

Author:        Rocktäschel, Ernst Albert. [from old catalog]
Title:         Geheimnisse des steines der weisen,
Published:     Zittau, E. A. Rocktäschel, 1913.
Description:   5 p.l., 171, [1] p. pl., diagrs. (4 fold.) 22
                  cm.
LC Call No.:   QA165.R6
Control No.:   7766143

Author:        Schoenfeld, Lowell, 1920-
Title:         A transformation formula in the theory of
                  partitions [by] Lowell Schoenfeld.
Published:     Philadelphia, 1944.
Description:   1 p. l., 873-887 p. 26 cm.
LC Call No.:   QA165.S35
Dewey No.:     512.5
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1944.
               "Reprint from Duke mathematical journal, XI, 4."
               "References": p. 887.
Subjects:      Partitions (Mathematics)
               Series, Infinite.
Control No.:   9742143

Author:        Tarry, G[aston] [from old catalog]
Title:         Le problème des 36 officiers. Extrait des
                  Comptes rendus de l'Association française pour l'avancement
                  des sciences.
Published:     Paris, Secrétariat de l'Association] [1901?]
Description:   35, [1] p. diagr. 24 cm.
LC Call No.:   QA165.T2
Subjects:      Permutations. [from old catalog]
Control No.:   9606384

Author:        White, Henry S. [from old catalog]
Title:         Complete classification of the trial systems on
                  fifteen elements.
Published:     [n. p.] 1919.
Description:   1 v. cm.
LC Call No.:   QA165.W4
Control No.:   8602185

Author:        Wolfowitz, Jacob, 1910- [from old catalog]
Title:         Additive partition functions and a class of
                  statistical hypotheses,
Published:     [n. p., 1942]
Description:   p. cm.
LC Call No.:   QA165.W87
Subjects:      Partitions (Mathematics) [from old catalog]
               Mathematical statistics. [from old catalog]
Control No.:   9263122

Author:        Zulauf, Karl, 1870- [from old catalog]
Title:         Über tripelsysteme von 13 elementen ...
Published:     Darmstadt, C. F. Winter, 1897.
Description:   22 p., 1 l. 23 cm.
LC Call No.:   QA165.Z94
Subjects:      Combinations. [from old catalog]
Control No.:   7722516

uthor:        Eggenberger, Johann. [from old catalog]
Title:         Beiträge zur darstellung des Bernouilli'schen
                  theorems der gammafunktion und des Laplace'schen integrals
                  ...
Published:     Bern, Buchdruckerei K. J. Wyss, 1893.
Description:   75, [1] p. 23 cm.
LC Call No.:   QA173.E3
Subjects:      Probabilities. [from old catalog]
Control No.:   8669715

Author:        Herz, Norbert, 1858-1927.
Title:         Wahrscheinlichkeits- und Ausgleichungsrechnung,
                  von Norbert Herz.
Published:     Leipzig, G. J. Göschen, 1900.
Description:   iv, 381 p. 3. fold. tables. 20 cm.
Series:        Sammlung Schubert. 19
LC Call No.:   QA173.H6
Subjects:      Probabilities.
               Error analysis (Mathematics)
Control No.:   8197320

Author:        Peek, Johannes Hendrikus. [from old catalog]
Title:         Toepassing der waarschijnlijkheids-rekening op
                  levensverzekering en sterfte-statistiek ...
Published:     [s' Gravenhage] Gedrukt bij F. J. Belinfante,
                  voorh. : A. D. Schinkel, 1898.
Description:   xii, 145, [22] p., 1 l. incl. tables. 30 x 23
                  cm.
LC Call No.:   QA173.P37
Subjects:      Probabilities. [from old catalog]
               Insurance, Life. [from old catalog]
Control No.:   8669758

Author:        Simpson, Thomas, 1710-1761.
Title:         The nature and laws of chance. By Thomas Simpson,
                  F.R.S.
Edition:       New ed.
Published:     London, Printed for F. Wingrave, 1792.
Description:   1 p. l., iv, 95 p. diagr. 20 cm.
LC Call No.:   QA173.S61
Subjects:      Probabilities
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   9604828

Author:        Bond, George P[hillips], 1825-1865. [from old
                  catalog]
Title:         On the use of equivalent numbers in the method of
                  least squares.
Published:     Cambridge, Metcalf and company, 1856.
Description:   36 p. 30 cm.
LC Call No.:   QA175.B71
               Microfilm 65301 QA
Subjects:      Least squares. [from old catalog]
Control No.:   6791743

Author:        Bruns, Heinrich, 1848- [from old catalog]
Title:         Über die ableitung des mittleren fehlers ...
Published:     Lipsiae, typis A. Edelmanni [1893]
Description:   30 p. 27 x 22 cm.
LC Call No.:   QA175.B9
Subjects:      Error analysis (Mathematics)
Control No.:   8665901

Author:        Comstock, George C. (George Cary), 1855-1934.
Title:         An elementary treatise upon the method of least
                  squares, with numerical examples of its applications, by
                  George C. Comstock.
Published:     Boston, Ginn, 1890.
Description:   vi, 67 p. diagr. 21 cm.
LC Call No.:   QA175.C73
Subjects:      Least squares.
Control No.:   8197322

Author:        DeForrest, Erastus Lyman, 1834-
Title:         Interpolation and adjustment of series, by E.L.
                  DeForrest.
Published:     New Haven, Tuttle, Morehouse & Taylor, printers,
                  1876.
Description:   51, [1] p. tab., diagr. 24 cm.
LC Call No.:   QA175.D31
Notes:         "The present paper is a continuation of two
                  others on the same subject which have appeared in the Annual
                  reports of the Smithsonian Institution, for the years 1871
                  and 1873."--Pref.
Subjects:      Error analysis (Mathematics)
Control No.:   7261472

Author:        Merriman, Mansfield, 1848-1925.
Title:         A text book on the method of least squares. By
                  Mansfield Merriman.
Published:     New York, J. Wiley, 1884.
Description:   viii, 194 p. tables, diagrs. 22 cm.
LC Call No.:   QA275.M57
Subjects:      Least squares.
Control No.:   6323984

Author:        Merriman, Mansfield, 1848-1925. [from old
                  catalog]
Title:         A text book on the method of least squares.
Edition:       4th ed.
Published:     New York, J. Wiley & sons, 1888.
Description:   viii, 194 p. incl. tables. diagrs. 22 cm.
LC Call No.:   QA175.M57 1888
Subjects:      Least squares. [from old catalog]
Control No.:   9725197

Author:        Rüdiger, Wilhelm von. [from old catalog]
Title:         Die methode der kleinsten quadrate abgeleitet aus
                  der wahrscheinlichkeitslehre und ihre anwendung auf
                  naturwissenschaftliche messungen.
Published:     Frankfurt a. Oder, 1876.
Description:   48 p. 21 cm.
LC Call No.:   QA175.R91
Subjects:      Least squares. [from old catalog]
Control No.:   5856971

Author:        Rumpen, Hermann, 1849- [from old catalog]
Title:         Ueber den zusammenhang der von Gauss begründeten
                  methode der kleinsten quadrate mit der algebraischen theorie
                  der quadratischen formen ...
Published:     Bonn, J. Trapp, 1872.
Description:   1 p.l., 40 p. 21 cm.
LC Call No.:   QA175.R93
Subjects:      Least squares. [from old catalog]
               Forms, Quadratic. [from old catalog]
Control No.:   9602174

Author:        Thiele, T. N. (Thorvald Nicolai), 1838-1910.
Title:         Sur la compensation de quelques erreurs
                  quasi-systématiques par la méthode des moindres carrés,
                  par T. N. Thiele.
Published:     Copenhague, C. A. Reitzel, 1880.
Description:   29 p. incl. tab., diagr. 26 x 20 cm.
LC Call No.:   QA275.T41
Subjects:      Least squares
Control No.:   9602171

Author:        Werner, Friedrich [Johannes] 1875- [from old
                  catalog]
Title:         Beiträge zur collectivmasslehre ...
Published:     Leipzig, Verlag von W. Engelmann, 1899.
Description:   50, [2] p. tables, diagrs. 23 cm.
LC Call No.:   QA175.W5
Subjects:      Error analysis (Mathematics)
Control No.:   7264754

Author:        Dresher, Melvin.
Title:         Theory of multigroups,
Published:     [Baltimore, 1938]
Description:   1 p.l., 705-733 p. 25 cm.
LC Call No.:   QA177.D7
Subjects:      Group theory.
Other authors: Ore, Øystein, 1899-1968, joint author.
Other titles:  Multigroups.
Control No.:   9258085

Author:        Goodwin, Harry Manly, 1870- [from old catalog]
Title:         Notes on graphical methods,
Published:     Boston, W. B. Libby, printer, 1904.
Description:   iii, 5-22 p. diagrs. 23 cm.
LC Call No.:   QA277.G65
Subjects:      Graphic methods. [from old catalog]
Control No.:   8200354

Author:        Herschel, J[ohn] F[rederick] W[illiam], Sir,
                  bart., 1792-1871. [from old catalog]
Title:         On the formulæ investigated by Dr. Brinkley for
                  the general term in the development of Lagrange's expression
                  for the summation of series and for successive
                  intergrations.
Published:     [n.p., 1860]
Description:   319-323 p. 30 x 23 cm.
LC Call No.:   QA181.H5
Other titles:  Calculus of differences. [from old catalog]
Control No.:   8666453

Author:        Weeks, Raymond, 1863-1954.
Title:         Boys' own arithmetic, by Raymond Weeks;
                  illustrations by Usabal.
Published:     New York, E.P. Dutton & Company [c1924]
Description:   xv p., 1 l., 188 p. illus. 20 cm.
LC Call No.:   QA189.W4
Subjects:      Arithmetic -- Problems, exercises, etc.
Control No.:   9667978


Author:        Autonne, Léon, 1859-1916.
Title:         Sur la décomposition d'une substitution
                  linéaire réelle et orthogonale, en un produit d'inversions,
                  par Léon Autonne.
Published:     Lyon, A. Rey; Paris, Gauthier-Villars, 1903.
Description:   2 p. l., 124, [2] p. 25 cm.
Series:        Annales de l'Université de Lyon.  Nouv. sér. I.
                   Sciences, médecine. fasc. 12
LC Call No.:   QA190.A93
Notes:         "Exemplaire n. 114."
Subjects:      Substitutions, Linear.
Control No.:   13410749

Author:        Dziobek, Otto [Franz], 1856- [from old catalog]
Title:         Ueber die functionen von sechs variablen, welche
                  nur sechs verschiedene werte annehmen ...
Published:     Greifswald, Druck von F. W. Kunike, 1882.
Description:   2 p.l., 225-255 p. 23 cm.
LC Call No.:   QA190.D98
Subjects:      Substitutions, Linear. [from old catalog]
Control No.:   6331984

Author:        Herbst, Hermann i. e. Hugo Emil Hermann, 1856-
                  [from old catalog]
Title:         Beitrag zur theorie der orthogonalen
                  substitutionen ...
Published:     Halle a/S., Druck von O. Hendel [1879]
Description:   2 p. l., 24, [2] p. 23 cm.
LC Call No.:   QA190.H53
Subjects:      Substitutions, Linear. [from old catalog]
Control No.:   8672254

Author:        Maurer, Ludwig, 1859- [from old catalog]
Title:         Zur theorie der linearen substitutionen ...
Published:     Strassburg, Buchdruckerei von R. Schultz und
                  comp., 1887.
Description:   1 p.l., 26 p. 27 x 22 cm.
LC Call No.:   QA190.M45
Other authors: Substitutions, Linear. [from old catalog]
Control No.:   6792912

Author:        Rost, Georg, 1870-
Title:         Untersuchungen über die allgemeinste lineare
                  substitution deren potenzen eine endliche gruppe bilden ...
Published:     Leipzig, Druck von B.G. Teubner, 1892.
Description:   28 p., [1] l. 29 cm.
LC Call No.:   QA190.R83
Notes:         Inaug.-dis.--Würzburg.
               Vita.
Subjects:      Substitutions, Linear.
Control No.:   3106772

Author:        Babcock, Wealthy. [from old catalog]
Title:         On the geometry associated with certain
                  determinants with linear elements,
Published:     [Lawrence, Kan., 1929]
Description:   1 p.l., p. 27-42. 24 cm.
LC Call No.:   QA191.B3
Subjects:      Determinants. [from old catalog]
Control No.:   5940445

Author:        Baltzer, Richard, 1818-1887.
Title:         Theorie und Anwendung der Determinanten, von Dr.
                  Richard Baltzer.
Edition:       3. verb. Aufl.
Published:     Leipzig, S. Hirzel, 1870.
Description:   vi, p., 1 l., 241, [1] p. ; 23 cm.
LC Call No.:   QA191.B2 1870
Subjects:      Determinants.
Control No.:   9282324

Author:        Baltzer, Richard, 1818-1887. [from old catalog]
Title:         Théorie et applications des déterminants, avec
                  l'indication des sources originales;
Published:     Paris, Mallet-Bachelier, 1861.
Description:   xii, 235 p. 23 cm.
LC Call No.:   QA191.B213
Subjects:      Determinants. [from old catalog]
Other authors: Hoüel, Guillaume Jules, 1823-1886, [from old
                  catalog] tr.
Control No.:   7348067

Author:        Baltzer, Richard, 1818-1887. [from old catalog]
Title:         Theorie und anwendung der determinanten,
Edition:       4. verb. aufl.
Published:     Leipzig, S. Hirzel, 1875.
Description:   vi p., 1 l., 247 p. 23 cm.
LC Call No.:   QA191.B2 1875
Subjects:      Determinants. [from old catalog]
Control No.:   5895250

Author:        Baraniecki, Maryan Aleksander, 1848-1895. [from
                  old catalog]
Title:         Teorya wyznaczników (determinantów).
Published:     Paryçz. Nakladem wáâsciciela Bibliotheki
Description:   xxii p., [1] l., 600 p. diagrs. 24 cm.
LC Call No.:   QA191.B22
Subjects:      Determinants. [from old catalog]
Control No.:   10086853

Author:        Bowman, Frank, 1891-
Title:         An introduction to determinants and matrices [by]
                  F. Bowman.
Published:     Princeton, N.J., Van Nostrand [c1962]
Description:   163 p. illus. 22 cm.
Series:        Applied mathematics series
LC Call No.:   QA191
Notes:         Bibliography: p. [160]
Subjects:      Determinants.
               Matrices.
Other titles:  Determinants and matrices.
Control No.:   6111664

Author:        Brioschi, Francesco, 1824-1897.
Title:         Théorie des déterminants et leurs principales
                  applications; par le docteur F. Brioschi ... traduit de
                  l'italien par m. Édouard Combescure.
Published:     Paris, Mallet-Bachelier, 1856.
Description:   xii, 216 p. 22 cm.
LC Call No.:   QA191.B72
Dewey No.:     512.83
Subjects:      Determinants.
Other authors: Combescure, Édouard, 1824- tr.
Control No.:   6413179

Author:        Dostor, G. (Georges), b. 1820.
Title:         Éléments de la théorie des déterminants, avec
                  application à l'algèbre, la trigonométrie et la
                  géométrie analytique dans le plan et dans l'espace, à
                  l'usage des classes de mathématiques spéciales; par G.
                  Dostor ...
Published:     Paris, Gauthier-Villars, 1877.
Description:   xxxi, 352 p. diagrs. 22 cm.
LC Call No.:   QA191.D6
Dewey No.:     512.83
Subjects:      Determinants.
Control No.:   7355122

Author:        Dostor, Georges, b. 1820. [from old catalog]
Title:         Éléments de la théorie des déterminants,
Edition:       2. éd.
Published:     Paris, Gauthier-Villars, 1905.
Description:   xxxiii, 361 p. illus. 23 cm.
LC Call No.:   QA191.D6 1905
Subjects:      Determinants. [from old catalog]
Control No.:   7087605

Author:        Euclid.
Title:         Les trois livres de porismes d'Euclide, rétablis
                  pour la première fois, d'après la notice et les lemmes de
                  Pappus, et conformément au sentiment de R. Simon sur la
                  forme des énoncés de ces propositions; par M. Chasles ...
Published:     Paris, Mallet-Bachelier, 1860.
Description:   ix, 324 p. diagrs. 22 cm.
Series:        With Baltzer, Richard. Théorie et applications
                  des déterminants ... Paris, 1861
LC Call No.:   QA191.B213
Subjects:      Porisms.
               Euclid's Elements.
Other authors: Pappus, of Alexandria.
               Chasles, M. (Michel), 1793-1880, editor.
Control No.:   9223278

Author:        Everett, Harry Scheidy, 1891- [from old catalog]
Title:         Determination of all general homogeneous
                  polynomials expressible as determinants whose elements are
                  homogeneous polynomials ...
Published:     Lancaster, Pa., and New York, 1922]
Description:   1 p. l., p. 185-194. 1 l. 28 cm.
LC Call No.:   QA191.E8
Subjects:      Polynomials. [from old catalog]
               Determinants. [from old catalog]
Control No.:   9666315

Author:        Few, Herbert P. [from old catalog]
Title:         Elementary determinants for electrical engineers.
                  By Herbert P. Few.
Published:     London, S. Rentell & co., ltd.; New York, D. Van
                  Nostrand company [1922]
Description:   4 p. l., 98 p., 1 l. diagrs. 19 cm.
LC Call No.:   QA191.F4
Subjects:      Determinants.
               Electrical engineering -- Mathematics.
Control No.:   13410796

Author:        Fischer, Paul B. (Paul Bernhard), 1879-
Title:         Determinanten, von Paul B. Fischer ...
Published:     Leipzig, G.J. Göschen, 1908.
Description:   134 p. 16 cm.
Series:        Sammlung Göschen. [402]
LC Call No.:   QA191.F6
Notes:         "Literatur": p. [4]
Subjects:      Determinants.
Control No.:   3107313

Author:        Fischer, Paul Bernhard, 1879- [from old catalog]
Title:         Determinanten.
Edition:       2., verb. Aufl.
Published:     Berlin, W. de Gruyter, 1921.
Description:   136 p. 16 cm.
LC Call No.:   QA191.F6 1921
Subjects:      Determinants. [from old catalog]
Control No.:   8366112

Author:        Fischer, Paul Bernhard, 1879- [from old catalog]
Title:         Determinanten,
Published:     Leipzig, G. J. Göschen, 1908.
Description:   134 p. 16 cm.
LC Call No.:   QA191.F6
Subjects:      Determinants. [from old catalog]
Control No.:   8685971

Author:        Goodman, A. W. (Adolph Winkler), 1915-
Title:         On some determinants related to p-valent
                  functions.
Published:     New York, 1947 [i.e. 1948]
Description:   175-192 p. 28 cm.
LC Call No.:   QA191.G6
Notes:         Thesis--Columbia university.
               "Reprinted from the Transactions of the American
                  Mathematical Society, vol. 63, no. 1 ... January, 1948."
               Vita.
Subjects:      Determinants.
Control No.:   6947743

Author:        Günther, Siegmund, 1848- [from old catalog]
Title:         Lehrbuch der determinanten-theorie für
                  studirende,
Edition:       2. durchaus umgearb. verm. und durch eine
                  aufgaben-sammlung bereicherte aufl.
Published:     Erlangen, E. Besold, 1877.
Description:   xii, 209 p. 23 cm.
LC Call No.:   QA191.G7
               Microfilm 82/6524 (QA)
Subjects:      Determinants. [from old catalog]
Control No.:   8706217

Author:        Isander, Lars Frederik, 1828-1893. [from old
                  catalog]
Title:         Inledning till determinant-theorien...
Published:     Upsala, C. A. Leffler, Kongl. acad. boktryckare,
                  1860.
Description:   2 p.l., 23 p. 23 cm.
LC Call No.:   QA191.I8 1860
Subjects:      Determinants. [from old catalog]
Control No.:   9238971

Author:        Jacobi, C. G. J. (Carl Gustav Jakob), 1804-1851.
Title:         Ueber die bildung und die eigenschaften der
                  determinanten. (De formatione et proprietatibus
                  determinantium.) Von C.G.J. Jacobi. (1841) Hrsg. von P.
                  Stäckel.
Published:     Leipzig, W. Engelmann, 1896.
Description:   73, [1] p. 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 77
LC Call No.:   QA191.J16
Notes:         The first and third of three papers published in
                  Latin in Crelle's Journal, bd. 22, 1841.
               Title of third paper: De functionibus
                  alternantibus earumque divisione per productum e differentiis
                  elementorum conflatum.
               The second of the three papers, De
                  determinantibus functionalibus, is published as no. 78 of
                  this series.
Subjects:      Determinants.
Other authors: Stäckel, Paul, 1862-1919, ed.
Series Entry:  Ostwalds Klassiker der exakten Wissenschaften ;
                  Nr. 77.
Control No.:   4525300

Author:        Jacobi, C. G. J. (Carl Gustav Jakob), 1804-1851.
Title:         Ueber die functionaldeterminanten (De
                  determinantibus functionalibus) Von C.G.J. Jacobi (1841)
                  Hrsg. von P. Stäckel.
Published:     Leipzig, W. Engelmann, 1896.
Description:   <72 p.> 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 78
LC Call No.:   QA191.J18
Notes:         First pub. in Latin in Crelle's Journal für die
                  reine und angewandte mathematik, bd. 22, 1841.
               The second of three papers on determinants, the
                  first and third being Ostwald's Klassiker der exakten
                  wissenschaften, no. 77.
Subjects:      Determinants.
Other authors: Stäckel, Paul, 1862-1919, ed.
Series Entry:  Ostwalds Klassiker der exakten Wissenschaften ;
                  Bd. 78.
Control No.:   1217043

Author:        Kowalewski, Gerhard, 1876-1950.
Title:         Einführung in die determinantentheorie
                  einschliesslich der unendlichen und der Fredholmschen
                  determinanten, von dr. Gerhard Kowalewski
Published:     Leipzig, Veit & comp., 1909.
Description:   iv p., 1 l., 550 p. 24 cm.
LC Call No.:   QA191.K7
Notes:         "Literaturnachweise und anmerkungen" : p.
                  [541]-544.
Subjects:      Determinants.
Control No.:   8692832

Author:        Marsano, G[iovanni] B[attista] [from old
                  catalog]
Title:         Sopra una questione di algebra.
Published:     [Novara, Tip. della Rivista di contabilita,
                  1879]
Description:   79, [1] p. 24 cm.
LC Call No.:   QA191.M3
Other authors: Determinants. [from old catalog]
Control No.:   6323988

Author:        Mateos, Juan. [from old catalog]
Title:         Teoría elemental de los determinantes; lecciones
                  dadas en la Escuela n. de ingenieros,
Edition:       2. ed.
Published:     México, D.F. [192-?]
Description:   29 p. 23 cm.
LC Call No.:   QA191.M35 1925
Subjects:      Determinants. [from old catalog]
Control No.:   9215520

Author:        McDonough, Donald L., 1894-
Title:         On the expansion of a certain type of determinant
                  [by] Donald L. McDonough.
Published:     Menasha, Wis., 1931.
Description:   1 p. l., 10 p. 23 cm.
LC Call No.:   QA191.M25 1931
Dewey No.:     512.83
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1931.
               "Reprint from the American mathematical monthly,
                  vol. xxxviii, no. 10."
Subjects:      Determinants.
Control No.:   6412164

Author:        Mellberg, Edvard Julius.
Title:         Teorin för determinant-kalkylen ... af Edvard
                  Julius Mellberg ...
Published:     Helsingfors, J.C. Frenckell & Son, 1876.
Description:   1 p. l., 121 p. 24 cm.
LC Call No.:   QA191.M52
Notes:         Inaug.-dis.--Helsingfors.
Subjects:      Determinants.
Control No.:   9133692

Author:        Miller, G. A. (George Abram), 1863-1951.
Title:         Determinants. An introduction to the study of,
                  with examples and applications. By G.A. Miller ...
Published:     New York, D. Van Nostrand company, 1892.
Description:   2 p.l., 110 p. 15 cm.
Series:        [Van Nostrand science, series, no. 105]
LC Call No.:   QA191.M6
Subjects:      Determinants.
Series Entry:  Van Nostrand's science series ; no. 105.
Control No.:   2633898

Author:        Monteverde, Juan. [from old catalog]
Title:         Apuntes sobre la teoria de las determinantes,
                  redactados para los aspirantes al ingreso en la facultad de
                  matemáticas,
Published:     Montevideo, Dornaleche y Reyes, 1892.
Description:   p. cm.
LC Call No.:   QA191.M7
Subjects:      Determinants. [from old catalog]
Control No.:   6792122

Author:        Moritz, Robert Edouard, 1868-1940.
Title:         Ueber Continuanten und gewisse ihrer Anwendungen
                  im zahlentheoretischen Gebiete / von Robert Édouard Moritz.
Published:     Göttingen : W. F. Kästner, [1902]
Description:   36 p. ; 23 cm.
LC Call No.:   QA191.M86
Notes:         Lebenslauf.
               Inaug.-diss.--Kaiser Wilhelms-Universität zu
                  Strassburg.
Subjects:      Determinants.
               Continued fractions.
Control No.:   6800202

Author:        Muir, Thomas, Sir, 1844-1934.
Title:         The theory of determinants in the historical
                  order of development,
Published:     London, Macmillan and co., limited, 1906-
Description:   v. fold. tables. 23 cm.
LC Call No.:   QA191.M9
Notes:         Serial.
Subjects:      Determinants.
Control No.:   10086599

Author:        Bloch, Martin, 1864- [from old catalog]
Title:         Beiträge zur theorie der resultantensysteme
                  welche bei der bestimmung des grössten gemeinschaftlichen
                  teilers zweier ganzen funktionen einer variablen auftreten
                  ...
Published:     Berlin, Druck von P. Stankiezicz' buchdr., 1892.
Description:   2 p. l., 30, [1] p. 29 x 23 cm.
LC Call No.:   QA192.B65
Subjects:      Elimination.
Control No.:   7729385

Author:        Borchardt, C[arl] W[ilhelm], 1817-1880. [from old
                  catalog]
Title:         Zur theorie der elimination und
                  kettenbruch-entwicklung.
Published:     Berlin, Buchdruckerei der K. Akademie der
                  wissenschaften, 1878.
Description:   1 p.l., 17 p. 28 x 22 cm.
LC Call No.:   QA192.B7
Subjects:      Elimination.
               Continued fractions.
Control No.:   7728597

Author:        Dickmann, August, 1854- [from old catalog]
Title:         Ueber die fremdartigen lösungen der durch
                  division gebildeten resultante zweier gleichungen mit zwei
                  unbekannten ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1880.
Description:   2 p.l., 23, [1] p. 22 cm.
LC Call No.:   QA192.D54
Subjects:      Elimination.
Control No.:   6324775

Author:        Katter, Friedrich. [from old catalog]
Title:         Ueber die resultante zweier algebraischen
                  gleichungen..
Edition:       1. theil.
Published:     Putbus, Druck von A. Knaak [187-?]
Description:   22 p. 27 x 22 cm
LC Call No.:   QA192.K2
Subjects:      Elimination.
Control No.:   8665424

Author:        Laurent, H. (Hermann), 1841-1908.
Title:         L'élimination, par H. Laurent.
Published:     [Paris, G. Carré & C. Naud] 1900.
Description:   75 p. 20 cm.
Series:        Scientia. [Série] physico-mathématique, no. 7
LC Call No.:   QA192.L4
Notes:         At head of title: Scientia, mars 1900.
Subjects:      Elimination.
Series Entry:  Scientia. Série physico-mathématique ; no. 7.
Control No.:   1689132

Author:        Macaulay, F. S. (Francis Sowerby), 1862-1937
Title:         The algebraic theory of modular systems, by F.S.
                  Macaulay ...
Published:     Cambridge [Eng.] University press, 1916.
Description:   xiv, 112 p. diagrs. 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics ... no. 19
LC Call No.:   QA192.M2
Notes:         "List of references": p. [xiii]-xiv.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elimination.
               Forms (Mathematics)
Series Entry:  Cambridge tracts in mathematics and mathematical
                  physics ; no. 19.
Control No.:   273506

Author:        Marsano, Giovanni, Battista. [from old catalog]
Title:         Sull' eliminazione di un' incognita fra due
                  equazioni di grado qualunque.
Published:     Genova, Tip. del R. I. de' sordo-muti, 1880.
Description:   32 p. 31 x 24 cm.
LC Call No.:   QA192.M3
Subjects:      Elimination.
Control No.:   7260343

Author:        Tyler, H. W. (Harry Walter), 1863-1938.
Title:         Beziehungen zwischen der Sylvester'schen und der
                  Bézout'schen determinante ...
Published:     München, Akademische buchdruckerei von F.
                  Straub, 1891.
Description:   1 p. l., 96 p. 25 cm.
Series:        Universität Erlangen. Dissertationen. v. 4, no.
                  13
LC Call No.:   QA192.T98
Notes:         Inaug.-dis.--Erlangen.
Control No.:   6324984

Author:        Earnest, William Watson. [from old catalog]
Title:         Lessons in written arithmetic,
Published:     [Bushnell? Ill.] c1898.
Description:   2 p.l., [9]-160 p. 18 cm.
LC Call No.:   QA193.E11
Subjects:      Arithmetic -- Early works to 1900.
Control No.:   9600977

Author:        Cornely, Anton, 1853-
Title:         Untersuchungen über involutorische
                  gleichungensysteme ...
Published:     Göttingen, Druck der Dieterich'schen
                  Univ.-buchdruckerei, W.F. Kaestner, 1892.
Description:   28 p., 1 l. 22 cm.
LC Call No.:   QA195.C8
Notes:         Inaug.-diss.--Würzburg.
               Vita.
Subjects:      Equations, Simultaneous.
Control No.:   5867103

Author:        Dell, George Harper, 1894-
Title:         The effects of errors or variations in the
                  arbitrary constants of simultaneous equations / by George H.
                  Dell.
Published:     Urbana, Ill. : University of Illinois,
                  Engineering Experiment Station, 1938.
Description:   54 p. ; 23 cm.
Series:        University of Illinois (Urbana-Champaign campus).
                  Engineering Experiment Station. Bulletin ; no. 309
               University of Illinois bulletin ; v. 36, no. 29
LC Call No.:   QA195.D4
Subjects:      Equations, Simultaneous.
               Error analysis (Mathematics)
Series Entry:  Bulletin (University of Illinois
                  Urbana-Champaign. Engineering Experiment Station) ; no. 309.
Control No.:   10183570

Author:        Dwyer, Paul Sumner, 1901-
Title:         Linear computations.
Published:     New York, Wiley [1951]
Description:   xi, 344 p. 24 cm.
Series:        Wiley publications in statistics
LC Call No.:   QA195.D95
Dewey No.:     512.8
Notes:         Includes bibliographies.
Subjects:      Equations, Simultaneous.
               Calculators.
Control No.:   6964541

Author:        Friedman, Joan (Joan Corinne), 1930-
Title:         Computational methods for handling systems of
                  simultaneous equations : with applications to agriculture /
                  by Joan Friedman and Richard J. Foote.
Published:     Washington, D.C. : U.S. Dept. of Agriculture,
                  Agricultural Marketing Service, 1955.
Description:   ii, 109 p. : ill. ; 26 cm.
Series:        Agriculture handbook / United States Department
                  of Agriculture ; no. 94
LC Call No.:   QA195.F7
Dewey No.:     512.8
Notes:         Cover title.
               Bibliography: p. 87-88.
Subjects:      Equations, Simultaneous.
               Mathematics -- Tables.
Other authors: Foote, Richard Jay, 1914-
Series Entry:  Agriculture handbook (United States. Dept. of
                  Agriculture) ; no. 94.
Control No.:   8391921

Author:        Wright, Lawrence Thomas, 1917-
Title:         The solution of simultaneous linear equations by
                  an approximation method, by L.T. Wright, Jr. ...
Published:     Ithaca, N.Y. [1943]
Description:   6 p. incl. tables. 28 x 22 cm.
Series:        Bulletin no. 31. April, 1943. Cornell University
                  Engineering Experiment Station
LC Call No.:   QA195.W7
Subjects:      Equations, Simultaneous.
               Numerical analysis.
Control No.:   6928950

Author:        Strayer, George Drayton, 1876- [from old
                  catalog]
Title:         Social utility arithmetics ...
Published:     New York, Cincinnati [etc.] American book company
                  [c1937]
Description:   3 v. illus. (part col.) diagrs. 19 cm.
LC Call No.:   QA196.A733 1937
Subjects:      Arithmetic.
Other authors: Upton, Clifford Brewster, 1877- [from old
                  catalog] joint author.
Control No.:   6901241

880-01 Igarashi, Atsuyoshi, 1793-1861.
Title:         880-02 Shinki sokury¯oh¯o / Igarashi Atsuyoshi
                  cho ; dan Toyoo, Takashima Masaaki tei.
Published:     880-04 [Japan] : H¯ogind¯o z¯ohan ; Kanazawa :
                  toritsugi shorin Yaoya Kih¯e : Chikaokaya Tah¯e, Ansei 4
                  [1857] kankyo.
Description:   2 v. : ill. (woodcuts) ; 28 cm.
LC Call No.:   QA197.I53 1857
Notes:         Caption title.
               Prefaces dated Ansei 3 [1856].
               Within double single (19.5 x 14.2 cm.), text
                  chiefly in 11 vertical lines.
               On double leaves, oriental style (fukurotoji).
               Kokusho s¯omokuroku, v. 4, p. 642 (Shinki
                  sokury¯oh¯o, 2-kan 2-satsu; at head of title: Jikata; auth.
                  Igarashi Atsuyoshi, Ansei 3 jo, d¯o 4 kan).
Subjects:      Triangulation (Mathematics)
               Surveying.
Other authors: 880-05 Igarashi, Toyoo, fl. 1857.
               880-06 Takashima, Masaaki, fl. 1856.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13812447

Author:        880-01 Iwata, Seiy¯o, fl. 1836-1858.
Title:         880-02 Kib¯o shinkei jim¯o / Kansai Iwata
                  Shichihei Seiy¯o hen ; T¯ofu Ikeda Yasabur¯o Masayoshi k¯o.
Published:     880-06 [Osaka] : Kants¯usaijuku z¯o, Tenp¯o kib¯o
                  [1843]
LC Call No.:   QA197.I83 1843
