#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Day, Mahlon Marsh, 1913- [from old catalog]
Title:         [Part I. Regularity of function-to-function
                  transformations. Part II. Linear methods of summability]
Published:     [n.p., 1939-42]
Description:   2 pt. 24-28 cm.
LC Call No.:   QA253.D3
Subjects:      Calculus of operations.
               Substitutions, Linear.
Control No.:   6453483

Author:        Goodner, Dwight Benjamin, 1913- [from old
                  catalog]
Title:         Projections in normed linear spaces.
Published:     Urbana, 1949.
Description:   2 p. 23 cm.
LC Call No.:   QA253.G65
Subjects:      Calculus of operations.
               Functional analysis.
Control No.:   8848740

Author:        International Conference on Operator Theory and
                  Group Representations (1953 : Harriman, N.Y.)
Title:         Report.
Published:     Washington, 1955.
Description:   36 p. 25 cm.
Series:        National Research Council. Publication 387
LC Call No.:   QA253.I5 1953c
Dewey No.:     517.7
Notes:         Includes bibliographies.
Subjects:      Calculus of operations.
               Topology.
Control No.:   8872108

Author:        Paterson, John, 1801-1883.
Title:         The calculus of operations / by John Paterson.
Published:     Albany : Gray and Sprague, 1850.
Description:   viii, 184 p. : ill. ; 24 cm.
LC Call No.:   QA253.P2
Notes:         Includes supplement.
               A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Calculus of operations.
Control No.:   5860082

Author:        Paterson, John, 1801-1883. [from old catalog]
Title:         The calculus of operations--Supplement to the
                  Calculus of operations.
Published:     [Albany, 1874]
Description:   8 p. diagrs. 23 cm.
LC Call No.:   QA253.P2
Subjects:      Calculus of operations.
Control No.:   7264523

Author:        Silverman, Robert Jerome, 1922- [from old
                  catalog]
Title:         Invariant extensions of linear operators.
Published:     Urbana, 1952.
Description:   2 p. 23 cm.
LC Call No.:   QA253.S5
Subjects:      Calculus of operations.
Control No.:   6039516

Author:        Allen, Reginald Bryant, 1872- [from old catalog]
Title:         On hypercomplex number systems belonging to an
                  arbitrary domain of rationality,
Published:     [Lancaster, Pa., Press of the New era printing
                  company, 1908]
Description:   2 p.l., p. 203-218. 28 cm.
LC Call No.:   QA255.A55
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   9647214

Author:        Argand, Jean Robert, b. 1768.
Uniform Title: Essai sur une manière de représenter les
                  quantités imaginaires dans les constructions géométriques.
                  English
Title:         Imaginary quantities; their geometrical
                  interpretation, tr. from the French of M. Argand by Prof.
                  A.S. Hardy ...
Published:     New York, D. Van Nostrand, 1881.
Description:   xvi, [17]-135 p. diagr. 15 cm.
Series:        Van Nostrand's science series, no. 52
LC Call No.:   QA255.A713
Notes:         Translation of Essai sur une manière de
                  représenter les quantités imaginaires dans les
                  constructions géométriques.
               Reprinted from Van Nostrand's magazine.
Subjects:      Numbers, Complex.
Series Entry:  Van Nostrand's science series ; no. 52.
Control No.:   2161003

Author:        Bierens de Haan, David, 1822-1895. [from old
                  catalog]
Title:         Over de magt van het zoogenaamd onbestaanbare in
                  de wiskunde.
Published:     Deventer, J. de Lange, 1863.
Description:   2 p.l., 32 p. 24 cm.
LC Call No.:   QA255.B5
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   9685597

Author:        Gompertz, Benjamin, 1779-1865. [from old
                  catalog]
Title:         The principles and application of imaginary
                  quantities ...
Published:     London, Published for the author, by Davis and
                  Dickson, 1817-18.
Description:   in 1. diagrs. 26 x 21 cm.
LC Call No.:   QA255.G6
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   6901191

Author:        Kiseljak, M.
Title:         Grundlagen einer zahlentheorie eines speziellen
                  systems von komplexen grössen mit drei einheiten, von M.
                  Kiseljak.
Published:     Bonn, C. Georgi, 1905.
Description:   29 p. 22 cm.
LC Call No.:   QA255.K62
Subjects:      Numbers, Complex.
Control No.:   4052408

Author:        Krüger, Richard, b. 1856.
Title:         Lehrbuch des Rechnens mit imaginären und
                  komplexen Zahlen : mit 221 Erklärungen und 38 in den Text
                  gedruckten Figuren : mit einer Sammlung von 269 gelösten und
                  ungelösten analogen Aufgaben nebst den Resultaten der
                  ungelösten Aufgaben und einem Formelverzeichnis : für das
                  Selbstudium und zum Gebrauche an Lehranstalten / bearbeitet
                  von Richard Krüger.
Published:     Stuttgart : Julius Maier, 1891.
Description:   viii, 166 p. ; 24 cm.
Series:        Kleyers Encyklopädie der gesamten
                  mathematischen, technischen und exakten Natur-Wissenschaften
LC Call No.:   QA255.K78x 1891
Notes:         Bibliography: p. 166.
Subjects:      Numbers, Complex.
Control No.:   4764762

Author:        Le Vavasseur, Raymond, 1862-1930.
Title:         Quelques démonstrations relatives à la théorie
                  des nombres entiers complexes cubiques. Propriétés de
                  quelques groupes d'ordre fini. Par Raymond Vavasseur ...
Published:     Lyon, A. Rey; [etc., etc.] 1908.
Description:   2 p.l., 66, [2] p. 25 cm.
Series:        Annales de l'Université de Lyon. Nouv. sér. I.
                  Sciences, médecine. fasc. 21
LC Call No.:   QA255.L5
Notes:         Exemplaire no. 167.
Subjects:      Numbers, Complex.
               Group theory.
Series Entry:  Annales de l'Université de Lyon. Nouv. sér. 1,
                  Sciences, médecine ; fasc. 21.
Control No.:   2161679

Author:        Leonard, Heman Burr, 1872-
Title:         On the factoring of composite hypercomplex number
                  systems ... by Heman Burr Leonard.
Published:     Baltimore, Md., The Lord Baltimore Press, 1907.
Description:   1 p. l., p. [43]-64. 31 cm.
LC Call No.:   QA255.L4
Notes:         Thesis (PH. D.)--University of Colorado, 1906.
               Reprinted from the American journal of
                  mathematics, vol. xxx, 1908.
Subjects:      Numbers, Complex.
Control No.:   8712359

Author:        Marie, Maximilien, 1819-1891.
Title:         Discours sur la nature des grandeurs négatives
                  et imaginaires, par Maximilien Marie ...
Edition:       2. éd.
Published:     Paris, Carilian-Goeury et V. Dalmont, 1844.
Description:   xvi, vii, 286 p. 22 cm.
LC Call No.:   QA255.M3
Subjects:      Numbers, Complex.
Control No.:   4053082

Author:        Molien, Theodor. [from old catalog]
Title:         Ueber systeme höhere complexer zahlen ...
Published:     Dorpat, Druck von C. Mattiesen, 1892.
Description:   1 p.l., 74, [1] p. 25 cm.
LC Call No.:   QA255.M7
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   7260418

Author:        Mourey, C. V.
Title:         La vraie théorie des quantités négatives et
                  des quantités prétendues imaginaires. Dédié aux amis de
                  lèvidence. Par C.V. Mourey.
Edition:       2. éd.
Published:     Paris, Mallet-Bachelier, 1861.
Description:   xii, 106 p. diagrs. 19 cm.
LC Call No.:   QA255.M9
Subjects:      Numbers, Complex.
Control No.:   9137683

Author:        Olmsted, John Meigs Hubbell, 1911-
Title:         The real number system.
Published:     New York, Appleton-Century-Crofts [1962]
Description:   216 p. 24 cm.
Series:        Appleton-Century monographs in mathematics
LC Call No.:   QA255.O43
Dewey No.:     512.81
Subjects:      Numbers, Real.
Control No.:   2166945

Author:        Philip, Robert Ashby.
Title:         Multifoliate numbers, by Robert Ashby Philip.
Published:     Fairhaven, Mass., The Monographic Press, 1936.
Description:   [22]. p. 28 x 22
Series:        Multifoliate monographs. Monograph 5
LC Call No.:   QA255.P5
Dewey No.:     512.89
Subjects:      Numbers, Complex.
Control No.:   6902221

Author:        Philip, Robert Ashby.
Title:         Numbers to vectors / by Robert Ashby Philip.
Published:     White Plains, N.Y. : The Monographic press,
                  1946.
Description:   viii, 176 p. : ill., diagrs. ; 22 cm.
Series:        Monographic journal ; v.1
LC Call No.:   QA255.P513
Subjects:      Numbers, Complex.
               Vector analysis.
Control No.:   8346906

Author:        Philip, Robert Ashby. [from old catalog]
Title:         Bifoliate numbers,
Published:     Fairhaven, Mass., The Monographic press, 1935.
Description:   [58] p. diagrs. 28 cm.
LC Call No.:   QA255.P45
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   8311107

Author:        Philip, Robert Ashby. [from old catalog]
Title:         Calculus of multifoliate substitutions,
Published:     Fairhaven, Mass., The Monographic press, 1936.
Description:   [28] p. 2 diagr. 28 x 22 cm.
LC Call No.:   QA255.P48
Subjects:      Numbers, Complex. [from old catalog]
Other titles:  Multifoliate substitutions.
Control No.:   10180659

Author:        Philip, Robert Ashby. [from old catalog]
Title:         Second and thrid dimensions of algebra,
Published:     Fairhaven, Mass., The Monographic press, 1938.
Description:   [139] p. diagrs. 27 x 21 cm.
LC Call No.:   QA255.P52
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   8775750

Author:        Rey y Heredia, José María, 1818-1861. [from old
                  catalog]
Title:         Teoría transcendental de las cantidades
                  imaginarias,
Published:     Madrid, Imprenta nacional, 1865.
Description:   3 p.l., [ix]-xx, 343 p. front. (port.) diagrs. 27
                  cm.
LC Call No.:   QA255.R4
Subjects:      Numbers, Complex. [from old catalog]
Other authors: Monlau y Roca, Pedro Felipe, 1808-1871. [from old
                  catalog]
Control No.:   6878290

Author:        Roberts, Joe.
Title:         The real number system in an algebraic setting.
Published:     San Francisco, W. H. Freeman [1962]
Description:   145 p. illus. 21 cm.
Series:        A Series of undergraduate books in mathematics.
                  Golden Gate books
LC Call No.:   QA255.R64
Dewey No.:     512.81
Notes:         Includes bibliography.
Subjects:      Arithmetic -- Foundations.
               Number theory.
Control No.:   3112311

Author:        Rohr, H[ugo], 1865- [from old catalog]
Title:         Über die aus 5 haupteinheiten gebildeten
                  komplexen zahlensysteme ...
Published:     Marburg, 1890.
Description:   51, [1] p. 23 cm.
LC Call No.:   QA255.R7
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   5856886

Author:        Scheffers, Georg [Wilhelm], 1866- [from old
                  catalog]
Title:         Zurückführung complexer zahlensysteme auf
                  typische formen ...
Published:     Leipzig, Druck von B. G. Teubner, 1891.
Description:   1 p.l., 98 p. 24 cm.
LC Call No.:   QA255.S3
Subjects:      Numbers, Complex. [from old catalog]
Control No.:   9137878

Author:        Warren, John, 1796-1852.
Title:         A treatise on the geometrical representation of
                  the square roots of negative quantities. By the Rev. John
                  Warren ...
Published:     Cambridge [Eng.] Printed by J. Smith, 1828.
Description:   3 p.l., 154 p. diagrs. 23 cm.
LC Call No.:   QA255.W2
Subjects:      Numbers, Complex.
Control No.:   2161179

Author:        Baker, Arthur Latham, 1853-1934
Title:         Quaternions as the result of algebraic
                  operations, by Arthur Latham Baker ...
Published:     New York, D. Van Nostrand company, 1911.
Description:   ix, 92 p. diagrs. 21 cm.
LC Call No.:   QA257.B3
ISBN:          $1.25
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Quaternions.

Author:        Bermbach, Willibald, 1860-
Title:         Ueber n-mal nacheinander angewandte
                  substitutionen, durch welche drei quadrate in sich selbst
                  transformirt werden ...
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1887.
Description:   50, [2] p. 25 cm.
Series:        Universität Bonn. Dissertationen. v. 1, no. 10
LC Call No.:   QA257.B51
Notes:         Inaug.-dis.--Bonn.
               Vita.
Subjects:      Quaternions.
               Group theory.
Control No.:   8202920

Author:        Combebiac, Gaston Charles. [from old catalog]
Title:         Calcul des triquaternions ...
Published:     Paris, Gauthier-Villars, 1902.
Description:   2 p.l., 122 p., 1 l. 28 x 22 cm.
LC Call No.:   QA257.C73
Subjects:      Quaternions. [from old catalog]
Control No.:   6810855

Author:        Darkow, Marguerite D., 1893- [from old catalog]
Title:         Arithmetics of certain algebras of generalized
                  quaternions,
Published:     1924.
Description:   p. cm.
LC Call No.:   QA257.D37
Subjects:      Quaternions. [from old catalog]
Control No.:   6171434

Author:        Grinwis, Pieter Thomas.
Title:         De oplossing van quaternion-vergelijkingen ...
Published:     Utrecht, J. van Boekhoven, 1890.
Description:   6 p. l., 80 p. diagrs. 23 cm.
LC Call No.:   QA257.G8
Notes:         Proefschrift--Utrecht.
Subjects:      Quaternions.
Control No.:   5860272

Author:        Hamilton, William Rowan, Sir, 1805-1865.
Title:         Elements of quaternions. By the late Sir William
                  Rowan Hamilton.
Edition:       2d ed. Ed. by Charles Jasper Joly.
Published:     London, New York, Longmans, Green, and co.,
                  1899-1901.
Description:   2 v. diagr. 27 cm.
LC Call No.:   QA257.H23
Notes:         "The table of contents has been amplified by a
                  brief analysis of each article, designed ... to assist the
                  reader in following and in recapitulating the arguments in
                  the text."--Pref.
               Appendix of notes: v. 2, p. 359-475.
Subjects:      Quaternions.
Other authors: Joly, Charles Jasper, 1864-1906, ed.
Control No.:   7727312

Author:        Hamilton, William Rowan, Sir, 1805-1865.
Title:         Elements of quaternions. By the late Sir William
                  Rowan Hamilton ... Ed. by his son, William Edwin Hamilton
                  ...
Published:     London, Longmans, Green, & co., 1866.
Description:   vi p., 1 l., lix, 762 p. diagr. 23 cm.
LC Call No.:   QA257.H22
Subjects:      Quaternions.
Other authors: Hamilton, William Edwin, ed.
Control No.:   4052122

Author:        Hamilton, William Rowan, Sir, 1805-1865.
Title:         Elements of quaternions. Edited by Charles Jasper
                  Joly.
Edition:       [3d ed.]
Published:     New York, Chelsea Pub. Co. [1969]
Description:   2 v. 24 cm.
LC Call No.:   QA257.H232
Dewey No.:     512/.893
ISBN:          0828402191
Notes:         Bibliographical footnotes.
Subjects:      Quaternions.
               Vector analysis.
Other authors: Joly, Charles Jasper, 1864-1906, ed.
Control No.:   2176963

Author:        Hamilton, William Rowan, Sir, 1805-1865.
Title:         Lectures on quaternions; containing a systematic
                  statement of a new mathematical method; of which the
                  principles were communicated in 1843 to the Royal Irish
                  academy; and which has since formed the subject of successive
                  courses of lectures, delivered in 1848 and subsequent years,
                  in the halls of Trinity college, Dublin: with numerous
                  illustrative diagrams, and with some geometrical and physical
                  applications. By Sir William Rowan Hamilton ...
Published:     Dublin, Hodges and Smith; [etc., etc.] 1853.
Description:   3 p.l., lxxii, 736 p., 1 l. diagrs. 22 cm.
LC Call No.:   QA257.H2
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Quaternions.
Control No.:   2633995

Author:        Hardy, A[rthur] S[herburne] 1847-1930.
Title:         Elements of quaternions.
Published:     Boston, Ginn, Heath & co., 1881.
Description:   viii p., 1 l., 230 p. diagrs. 22 cm.
LC Call No.:   QA257.H26
Subjects:      Quaterions. [from old catalog]
Control No.:   9136890

Author:        Hathaway, Arthur S. (Arthur Stafford), 1855-
Title:         A primer of quaternions, by Arthur S. Hathaway
                  ...
Published:     New York, Macmillan and co.; London, Macmillan &
                  co., ltd., 1896.
Description:   x, 113 p. diagrs. 20 cm.
LC Call No.:   QA257.H36
Subjects:      Quaternions.
Control No.:   2634014

Author:        Hunt, Mildred.
Title:         The arithmetics of certain linear algebras.
Published:     1924.
Description:   49 l. 29 cm.
LC Call No.:   QA257.H85
Dewey No.:     512/.893
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
Subjects:      Quaternious.
               Diophantine analysis.
Control No.:   2192646

Author:        Joly, Charles Jasper, 1864-1906.
Title:         A manual of quaternions, by Charles Jasper Joly
                  ...
Published:     London, Macmillan and co., limited; New York, The
                  Macmillan company, 1905.
Description:   xxvii, 320 p. diagrs. 23 cm.
LC Call No.:   QA257.J75
Subjects:      Quaternions.
Control No.:   2634184

Author:        Kelland, Philip, 1808-1879.
Title:         Introduction to quaternions, by the late
                  professors Philip Kelland and Peter Guthrie Tait.
Edition:       3d ed. Prepared by C. G. Knott.
Published:     London, Macmillan; New York, Macmillan, 1904.
Description:   xvii, 208 p. diagrs. 19 cm.
LC Call No.:   QA257.K3
Subjects:      Quaternions.
Other authors: Tait, Peter Guthrie, 1831-1901, joint author.
               Knott, Cargill Gilston, 1856-1922, ed.
Control No.:   7734359

Author:        Kelland, Philip, 1808-1879.
Title:         Introduction to quaternions, with numerous
                  examples.
Published:     London, Macmillan and co., 1873.
Description:   xi, 227 p. 20 cm.
LC Call No.:   QA257.K3 1873
               Microfilm 82/5703 (QA)
Subjects:      Quaternions.
Other authors: Tait, Peter Guthrie, 1831-1901, joint author.
Control No.:   9242776

Author:        Latimer, Claiborne G. [from old catalog]
Title:         Arithmetics of generalized quaternion algebras,
Published:     [n. p.] 1924.
Description:   18 p. 29 cm.
LC Call No.:   QA257.L37
Subjects:      Algebra, Universal.
               Quaternions.
               Matrices.
Control No.:   8059503

Author:        Barton, Helen, 1891-
Title:         A modern presentation of Grassmann's tensor
                  analysis / by Helen Barton.
Published:     [Baltimore], 1926.
Description:   1 leaf, 17 p., 1 leaf ; 25 cm.
LC Call No.:   QA259.B3 1926
Notes:         Thesis (Ph. D.)--Johns Hopkins University, 1926.
               Biographical note.
Subjects:      Ausdehnungslehre.
Other titles:  Tensor analysis.
Control No.:   7803736

Author:        Burali-Forti, Cesare, b. 1861.
Title:         Lezioni di geometria metrico-proiettiva.
Published:     Torino, [etc.] Fratelli Bocca, 1904.
Description:   XII, 308 p. illus., diagrs. 25 cm.
Series:        Biblioteca matematica, vol. X
LC Call No.:   QA259.B94
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Ausdehnungslehre.
               Geometry, Analytic.
               Geometry, Projective.
Series Entry:  Biblioteca matematica ; v. 10.
Control No.:   4052642

Author:        Collins, Joseph V[ictor], 1858- [from old
                  catalog]
Title:         An elementary exposition of Grassmann's
                  ausdehnungslehre, or, Theory of extension,
Published:     Springfield, Mo., Dixon bros., printer, 1901.
Description:   1 p. l., 46 p. 25 cm.
LC Call No.:   QA259.C7
Subjects:      Ausdehnungslehre. [from old catalog]
Control No.:   8659665

Author:        Grassmann, Hermann, 1809-1877.
Title:         Die ausdehnugslehre.
Edition:       Vollständig und in strenger Form / bearbeitet
                  von Hermann Grassmann.
Published:     Berlin : T.C.F. Enslin, 1862.
Description:   388 p. ; 22 cm.
LC Call No.:   QA259.G76
Subjects:      Ausdehnungslehre.
Control No.:   8200490

Author:        Grassmann, Hermann, 1809-1877.
Title:         Die ausdehnungslehre von 1844, oder Die lineale
                  ausdehnungslehre, ein neuer zweig der mathematik, dargestellt
                  und durch anwendungen auf die übrigen zweige der mathematik,
                  wie auch auf die statik, mechanik, die lehre vom magnetismus
                  und die krystallonomie erläutert von Hermann Grassmann.
Edition:       2., im text unveränderte aufl. Mit 1 tafel.
Published:     Leipzig, O. Wigand, 1878.
Description:   xxxiv, 301, [1] p. fold., pl. (diagrs.) 23 cm.
LC Call No.:   QA259.G77 1878
Notes:         First ed. published in 1844 as v. 1 of the
                  author's Die Wissenschaft der extensiven Grösse; oder, Die
                  Ausdehnungslehre, eine neue mathematische Disciplin, under
                  title: Die lineale Ausdehnungslehre, ein neuer Zweig der
                  Mathematik.
Subjects:      Ausdehnungslehre.
Control No.:   3580548

Author:        Grassmann, Hermann Ernst, 1857-1922.
Title:         Anwendung der Ausdehnungslehre auf die allgemeine
                  Theorie der Raumkurven und krummen Flächen [3. T. Krumme
                  Flächen. 2. Hälfte]
Published:     Halle a. S., Buchdruckerei des Waisenhauses,
                  1893.
Description:   [59]-89 p. diagrs. 26 cm.
LC Call No.:   QA259.G73
Notes:         Inaug.-Diss.--Halle.
               Vita.
Subjects:      Ausdehnungslehre.
               Surfaces.
Control No.:   7732846

Author:        Grassmann, Hermann [Ernst], 1857- [from old
                  catalog]
Title:         Schraubenrechnung und nullsystem ...
Published:     Halle a. S., Buchdruckerei des Waisenhauses,
                  1899.
Description:   1 p.l., 20 p. diagrs. 28 x 22 cm.
LC Call No.:   QA259.G78
Subjects:      Ausdehnungslehre. [from old catalog]
               Screws, Theory of. [from old catalog]
Control No.:   9144757

Author:        Hyde, E. W. (Edward Wyllys), b. 1843.
Title:         The directional calculus, based upon the methods
                  of Hermann Grassmann. By E.W. Hyde ...
Published:     Boston, Ginn & company, 1890.
Description:   xii, 247 p. diagrs. 22 cm.
LC Call No.:   QA259.H99
Notes:         Blank leaves at end of chapters, included in
                  paging.
Subjects:      Ausdehnungslehre.
Control No.:   3579220

Author:        Mahler, Gottfried, 1851-1919. [from old catalog]
Title:         Einleitung in die Grassmannsche ausdehnungslehre
                  ...
Published:     Ulm. Wagnersche buchdruckerei, 1884.
Description:   1 p. l., 14 p. 26 x 21 cm.
LC Call No.:   QA259.M2
Subjects:      Ausdehnungslehre. [from old catalog]
Control No.:   7739607

Author:        Mehmke, Rudolf, 1857- [from old catalog]
Title:         Anwendung der Grassmann'schen ausdehnungslehre
                  auf die geometrie der kreise in der ebene ...
Published:     Stuttgart, Druck der E. Greiner'schen
                  hofbuchdruckerei Greiner & Pfeiffer, 1880.
Description:   p. cm.
LC Call No.:   QA259.M5
Subjects:      Ausdehnungslehre. [from old catalog]
               Circle. [from old catalog]
Control No.:   9137916

Author:        Mehmke, Rudolf, b. 1857.
Title:         Vorlesungen über punkt- und vektorenrechnung,
                  von dr. Rudolf Mehmke ...
Published:     Leipzig, Berlin, B.G. Teubner, 1913.
Description:   v. <1   > diagrs. 26 cm.
Series:        B.G. Teubners sammlung von lehrbüchern auf dem
                  gebiete der mathematischen wisenschaften, mit einschluss
                  ihrer anwendungen, bd. XXXVI [i.e. XXXVII] 1-
LC Call No.:   QA259.M55
Notes:         1. bd. Punktrechnung: 1. teilband. Das rechnen
                  mit punkten, geraden und ebenen (1. hälfte), grundzüge der
                  projektiven geometrie, anwendungen und übungen.
Subjects:      Ausdehnungslehre.
               Vector analysis.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit Einschluss
                  ihrer Anwendungen ; v. XXXVII, 1, etc.
Control No.:   1217896

Author:        Müller, Emil [Adalbert], 1861- [from old
                  catalog]
Title:         Die geometrie orientierter kugeln nach
                  Grassmann'schen methoden ...
Published:     Teschen, K. u. K. Hofbuchdr. K. Prochaska, 1898.
Description:   1 p.l., 209-315 p., 1 l. 23 cm.
LC Call No.:   QA259.M95
Subjects:      Ausdehnungslehre.
Control No.:   5876966

Author:        Peano, Giuseppe, 1858- [from old catalog]
Title:         Calcolo geometrico secondo l'Ausdchnungslehre di
                  H. Grassmann,
Published:     Torino [etc.] Fratelli Bocca, 1888.
Description:   x p. 1 l., 170 p. 24 cm.
LC Call No.:   QA259.P4
Subjects:      Ausdehnungslehre.
               Logic, Symbolic and mathematical.
               Grassmann, Hermann, 1809-1877. Ausdehnungslehre.
                  [from old catalog]
Control No.:   6387374

Author:        Rudert, Ernst, 1858-
Title:         Über kleine kugelkreise. Eine anwendung von
                  Grassmann's ausdehnungslehre ...
Published:     Leipzig, Druck von B.G. Teubner, 1900.
Description:   2 p. l., [45]-77, [1] p. 26 cm.
LC Call No.:   QA259.R92
Notes:         Inaug.-dis.--Leipzig.
               Lebenslauf.
               Continuation of the author's "Grundlagen zu einer
                  geometrie der kugel nach Grassmanns ausdehnungslehre." 1899.
Subjects:      Sphere.
               Ausdehnungslehre.
               Grassmann, Hermann, 1809-1877.
Control No.:   7264753

Author:        Rudert, Ernst, 1858- [from old catalog]
Title:         Grundlagen zu einer geometrie der kugel nach
                  Grassmanns ausdehnungslehre,
Published:     Leipzig, Druck von B. G. Teubner, 1899.
Description:   1 p. l., 44 p. 26 cm.
LC Call No.:   QA259.R9
Subjects:      Sphere.
               Ausdehnungslehre.
Control No.:   7722444

Author:        Schlegel, Victor, 1843-1908.
Title:         System der raumlehre. Nach den prinzipien der
                  Grassmann'schen ausdehnungslehre, und als einleitung in
                  dieselbe, dargestellt von Victor Schlegel ...
Published:     Leipzig, B.J. Teubner, 1872-75.
Description:   2 v. diagrs. 23 cm.
LC Call No.:   QA259.S3
Notes:         1. th. Geometrie. Die gebiete des punktes, der
                  geraden, der ebene.--2. th. Die elemente der modernen
                  geometrie und algebra.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Control No.:   1690358

Author:        Tarski, Alfred. [from old catalog]
Title:         Cardinal algebras.
Published:     New York, Oxford Univ. Press, 1949.
Description:   xii, 326 p. 23 cm.
LC Call No.:   QA266.T3
Subjects:      Algebra, Abstract.
Other authors: Jónsson, Bjarni. [from old catalog]
Control No.:   7888735

Author:        Searle, Arthur. [from old catalog]
Title:         Geometrical methods in the theory of combining
                  observations...
Published:     [n. p., n. d.]
Description:   1 v. cm.
LC Call No.:   QA277.S5
Control No.:   7201727

Author:        Dern, Herbert.
Title:         A study of the sampling and generation of random
                  time series / by Herbert Dern.
Published:     [New York : s.n.], 1963.
Description:   xv, 248 p. : ill. ; 28 cm.
LC Call No.:   QA280.D47
Dewey No.:     519.5
Notes:         Thesis--Columbia University.
               Bibliography: p. 167-168.
Subjects:      Time-series analysis.
               Discrete-time systems.
               Sampling (Statistics)
Control No.:   399642

Author:        Åstrand, J[ohan] J[ulius], 1819-1900. [from old
                  catalog]
Title:         Neue interpolationsmethode, von J.J. Astrand ...
Published:     [Leipzig, 1875]
Description:   7 p. 22 cm.
LC Call No.:   QA281.A82
Subjects:      Interpolation. [from old catalog]
Control No.:   7729578

Author:        Åstrand, J[ohan] J[ulius], 1819-1900. [from old
                  catalog]
Title:         Ny interpolationsmethode, af J.J. Åstrand.
Published:     [Christiania, 1871]
Description:   8 p. 23 cm.
LC Call No.:   QA281.A8
Subjects:      Interpolation. [from old catalog]
Control No.:   10071479

Author:        Bruns, Heinrich, 1848-1919.
Title:         Grundlinien des wissenschaftlichen rechnens von
                  dr. Heinrich Bruns ...
Published:     Leipzig, B.G. Teubner, 1903.
Description:   vi, 159 p. 24 cm.
LC Call No.:   QA281.B9
Subjects:      Interpolation.
Control No.:   3579414

Author:        Chesire, Leone, 1902-
Title:         Computing diagrams for the tetrachoric
                  correlation coefficient [by] Leone Chesire, Milton Saffir
                  [and] L.L. Thurstone ...
Published:     Chicago, Ill., Distributed by the University of
                  Chicago bookstore, c1933.
Description:   [59] p. diagrs. 30 x 30 cm.
LC Call No.:   QA281.C5
Dewey No.:     517.6
Notes:         Lithographed.
Subjects:      Correlation (Statistics)
               Graphic methods.
Other authors: Saffir, Milton A., 1910- joint author.
               Thurstone, L. L. (Louis Leon), 1887-1955, joint
                  author.
Control No.:   3108596

Author:        Clarke, Charles Lorenzo, 1853-
Title:         Diagonal functions and their operations, by
                  Charles Lorenzo Clarke...
Published:     Newton, Mass., C.L. Clarke, 1937.
Description:    xi,113 (i.e. 164) p. incl. tables, diagrs. 28 x
                  22 cm.
LC Call No.:   QA281.C6
Notes:         "Lithographed."
               Includes extra numbered pages.
               Includes examples with answers.
Subjects:      Trigonometrical functions.
               Interpolation.
Control No.:   8305673

Author:        Florijn, Jakob, 1751-1818.
Title:         Verhandeling over het sommeren en interpoleren
                  van arithmetische seriën, door Jacob Florijn lid van het
                  Koninklijk Nederlandsch instituut van wetenschappen,
                  letterkunde en schoone kunsten, enz. enz. Uitgegeven door
                  hetzelve Instituut.
Published:     Te Amsterdam, Bij P. den Hengst en zoon, 1816.
Description:   2 p. l., 68 p. diagrs. 27 cm.
LC Call No.:   QA281.F6
Subjects:      Interpolation.
Other authors: K. Nederlandsch instituut van wetenschappen,
                  letterkunde en schoone kunsten (Amsterdam : 1. klasse)
Control No.:   9150764

Author:        Gibb, David. [from old catalog]
Title:         A course in interpolation and numerical
                  integration for the mathimatical laboratory,
Published:     London, G. Bell & sons, ltd., 1915.
Description:   viii, 90 p. 22 cm.
LC Call No.:   QA281.G5
               Microfilm 68664 QA
Subjects:      Interpolation. [from old catalog]
               Calculus, Integral. [from old catalog]
Control No.:   9177943

Author:        Greenleaf, Herrick E. H. [from old catalog]
Title:         Curve approximation by means of functions
                  analogous to the Hermite polynomials,
Published:     Ann Arbor, Mich., Edwards brothers, inc. [1932]
Description:   cover-title, p. [203]-255. 23 cm.
LC Call No.:   QA281.G7
Subjects:      Interpolation. [from old catalog]
               Least squares. [from old catalog]
Control No.:   8755842

Author:        Hildebrandt, Emanuel Henry, 1902- [from old
                  catalog]
Title:         Systems of polynomials connected with the
                  Charlier expansions and the Pearson differential and
                  difference equations,
Published:     Ann Arbor, Mich., Edwards brothers, inc. [1931]
Description:   p. [379]-439. 23 cm.
LC Call No.:   QA281.H5 1932
Subjects:      Interpolation. [from old catalog]
               Statistics. [from old catalog]
Control No.:   7817592

Author:        Milne-Thomson, L. M. (Louis Melville), 1891-
Title:         The calculus of finite differences / by L.M.
                  Milne-Thomson.
Edition:       2nd (unaltered) ed.
Published:     New York : Chelsea Pub. Co., 1981, c1933.
Description:   xxii, 558 p. ; 21 cm.
LC Call No.:   QA281.M5 1981
Dewey No.:     515/.62 19
ISBN:          0828403082
Notes:         Title on spine: Finite differences.
               Includes bibliographical references and index.
Subjects:      Interpolation.
               Difference equations.
               Finite differences.
Other titles:  Finite differences.
Control No.:   3246148

Author:        Newton, Isaac, Sir, 1642-1727. [from old
                  catalog]
Title:         Newton's interpolation formulas,
Published:     London, C. & E. Layton [1927]
Description:   1 p.l., 95 p. illus., fold. facsims., diagrs. 23
                  cm.
LC Call No.:   QA281.N4
Subjects:      Interpolation. [from old catalog]
               Mathematics -- Early works to 1800. [from old
                  catalog]
Other authors: Fraser, Duncan Cumming. [from old catalog]
Control No.:   10148099

Author:        Reilly, John Franklin.
Title:         Certain generalizations of osculatory
                  interpolation, by John Franklin Reilly ...
Published:     [n.p., 1924]
Description:   4-22 p. 23 cm.
LC Call No.:   QA281.R4 1921
Notes:         Cover-title.
               Thesis (Ph. D.)--University of Iowa, 1921.
               "Reprint from vol. XIII, part I, no. 27, of the
                  Record of the American Institute of Actuaries, June, 1924."
Subjects:      Interpolation.
Other titles:  Osculatory interpolation.
Control No.:   9669624

Author:        Rice, Herbert L. (Herbert Louis), 1869-
Title:         The theory and practice of interpolation;
                  including mechanical quadrature and other important problems
                  concerned with the tabular values of functions. With the
                  requisite tables. By Herbert L. Rice ...
Published:     Lynn, Mass., T.P. Nichols, 1899.
Description:   ix, 234 p. incl. tables. 30 cm.
LC Call No.:   QA281.R49
Notes:         Bibliography: p. 233-234.
Subjects:      Interpolation.
Control No.:   4525180

Author:        Salzer, Herbert E.
Title:         A new formula for inverse interpolation.
Published:     [Washington] : U.S. Dept. of Commerce, National
                  Bureau of Standards, 1950.
Description:   4 p. ; 23 cm.
Series:        United States. National Bureau of Standards.
                  Mathematical table, MT30
LC Call No.:   QA281.S22
Other titles:  Inverse interpolation.
Control No.:   9321914

Author:        Salzer, Herbert E.
Title:         Table of coefficients for inverse interpolation
                  with central differences.
Published:     [Washington] U.S. Dept. of Commerce, National
                  Bureau of Standards, 1949.
Description:   ii, 15 p. illus. 24 cm.
Series:        United States. National Bureau of Standards.
                  Mathematical table, MT27
LC Call No.:   QA281.S24
Dewey No.:     517.6
Notes:         "Originally printed as part of the Mathematical
                  tables series of the National Bureau of Standards in the
                  Journal of Mathematics and physics, vol. XXII, no. 4,
                  December 1943."
Subjects:      Interpolation -- Tables.
Control No.:   6499790

Author:        Salzer, Herbert E.
Title:         Tables for bivariate osculatory interpolation
                  over a Cartesian grid, by Herbert E. Salzer and Genevieve M.
                  Kimbro.
Published:     San Diego, Calif., Convair-Astronautics, Convair
                  Division of General Dynamics Corp. [1958?]
Description:   40 p. 26 cm.
LC Call No.:   QA281.S26
Dewey No.:     517.6
Subjects:      Interpolation -- Tables.
Other authors: Kimbro, Genevieve M., joint author.
Control No.:   278126

Author:        Salzer, Herbert E.
Title:         Tables for complex hyperosculatory interpolation
                  over a Cartesian grid, by Herbert E. Salzer, Genevieve M.
                  Kimbro and Marjory M. Thorn.
Published:     San Diego, Calif., General Dynamics Astronautics,
                  1962.
Description:   71 p. 28 cm.
LC Call No.:   QA281.G4
Dewey No.:     517.6
Notes:         Bibliography: p. 12-13.
Subjects:      Interpolation -- Tables.
Other authors: Kimbro, Genevieve M. joint author.
               Thorn, Marjory M., joint author.
Other authors: General Dynamics Corporation. Astronautics
                  Division.
Control No.:   7970015

Author:        Salzer, Herbert E.
Title:         Tables for hyperosculatory interpolation.
Published:     San Diego, Calif., General Dynamics/Astronautics,
                  1962.
Description:   51 p. 28 cm.
LC Call No.:   QA281.S28
Dewey No.:     517.6
Subjects:      Interpolation -- Tables.
               Functions.
Other titles:  Hyperosculatory interpolation.
Control No.:   750782

Author:        Salzer, Herbert E.
Title:         Tables of osculatory integration coefficients, by
                  Herbert E. Salzer, Dexter C. Shoultz and Elizabeth P.
                  Thompson.
Published:     [San Diego, Calif., Convair (Astronautics)
                  Division of General Dynamics Corporation] 1960.
Description:   43 p. 28 cm.
LC Call No.:   QA281.S29
Subjects:      Interpolation -- Tables.
               Numerical integration -- Tables.
Control No.:   2168703

Author:        Sewell, W. E. (Walter Edwin)
Title:         Degree of approximation by polynomials in the
                  complex domain, by W.E. Sewell.
Published:     Princeton, Princeton university press; London, H.
                  Milford, Oxford university press, 1942.
Description:   2 p.l., iii-ix, 236 p. 23 cm.
Series:        [Annals of mathematics studies, no. 9]
LC Call No.:   QA281.S4
Dewey No.:     512.22
Notes:         "Lithoprinted."
               Bibliography: p. 226-236.
Subjects:      Approximation theory.
               Polynomials.
Series Entry:  Annals of mathematics studies ; no. 9.
Control No.:   1691483

Author:        Steffensen, J. F. (Johan Frederik), 1873-
Title:         Interpolation, by J.F. Steffensen ...
Published:     Baltimore, The Williams & Wilkins Company, 1927.
Description:   ix, 248 p. diagrs. 24 cm.
LC Call No.:   QA281.S7
Subjects:      Interpolation.
Control No.:   7332297

Author:        Thiele, T. N. (Thorvald Nicolai), 1838-1910.
Title:         Interpolationsrechnung, von dr. T.N. Thiele ...
Published:     Leipzig, B.G. Teubner, 1909.
Description:   xii, 175 p. 27 cm.
LC Call No.:   QA281.T4
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Interpolation.
Control No.:   1689752

Author:        United States. National Bureau of Standards.
                  Computation Laboratory.
Title:         Table of Lagrangean interpolation coefficients.
                  Prepared for the Ordnance department by the "Computation of
                  mathematical tables," a project of the Work projects
                  administration for the city of New York. Sponsored by the
                  National bureau of standards.
Published:     Washington, D.C., Engineer reproduction plant,
                  1941.
Description:   ix, 40 p. 27 cm.
LC Call No.:   QA281.U6 1941
Dewey No.:     517.6
Subjects:      Interpolation -- Tables.
Control No.:   4054563

Author:        Walsh, J. L. (Joseph Leonard), 1895-
Title:         Interpolation and approximation by rational
                  functions in the complex domain, by J. L. Walsh ...
Published:     New York city, American mathematical society,
                  1935.
Description:   ix, 382 p. diagrs. 26 cm.
Series:        American mathematical society. Colloquium
                  publications, vol. xx
LC Call No.:   QA281.W3
Dewey No.:     517.6
Notes:         Bibliography: p. 367-373.
Subjects:      Interpolation.
               Series, Infinite.
               Functions.
Control No.:   9704499

Author:        Airy, George Biddell, Sir, 1801-1892.
Title:         On the algebraical and numerical theory of errors
                  of observations and the combinations of observations.
Published:     Cambridge and London: Macmillan and Co., 1861.
Description:   xvi, 103 p. tables 18 cm.
LC Call No.:   QA275.A35
Subjects:      Error analysis (Mathematics)
               Probabilities.
Control No.:   6018093

Author:        Aragón, Agustín. [from old catalog]
Title:         Reflexiones acerca del criterio de Peirce,
Published:     Mexico, Oficina tip. de la Secretaría de
                  fomento, 1894.
Description:   10 p. 23 cm.
LC Call No.:   QA275.A65
Subjects:      Error analysis (Mathematics)
Control No.:   9609106

Author:        Bartlett, Dana Prescott. [from old catalog]
Title:         General principles of the method of least
                  squares,
Edition:       2d ed.
Published:     Boston, Massachusetts institute of technology,
                  1900.
Description:   3 p. l., 142, xi p. tables, diagrs. 22 cm.
LC Call No.:   QA275.B28
Subjects:      Least squares. [from old catalog]
Control No.:   8661845

Author:        Beers, Yardley, 1913-
Title:         Introduction to the theory of error.
Edition:       [2d ed.]
Published:     Reading, Mass., Addison-Wesley Pub. Co. [1957]
Description:   66 p. illus. 23 cm.
LC Call No.:   QA275.B4 1957
Dewey No.:     519.6
Subjects:      Error analysis (Mathematics)
Control No.:   276795

Author:        Beers, Yardley, 1913-
Title:         Introduction to the theory of error.
Published:     Cambridge, Mass., Addison-Wesley Pub. Co., 1953.
Description:   65 p. illus. 20 cm.
LC Call No.:   QA275.B4
Dewey No.:     519.6
Subjects:      Error analysis (Mathematics)
Control No.:   8849457

Author:        Bjerhammar, Arne, 1917- [from old catalog]
Title:         Application of calculus of matrices to method of
                  least squares,
Published:     Stockholm] 1951.
Description:   p. cm.
LC Call No.:   QA275.B5
Subjects:      Matrices. [from old catalog]
               Least squares. [from old catalog]
               Geodesy. [from old catalog]
Series Entry:  Transactions of the Royal Institute of
                  Technology, Stockholm, Sweden, no. 49 [from old catalog]
Control No.:   6972846

Author:        Brunt, David, b. 1886.
Title:         The combination of observations, by David Brunt
                  ...
Published:     Cambridge [Eng.] University press, 1917.
Description:   x, 219 p. diagrs. 23 cm.
LC Call No.:   QA275.B95
Notes:         "List of references":  p. [212]-23.
Subjects:      Least squares.
Control No.:   8715577

Author:        Chauvenet, William, 1820-1870.
Title:         A treatise on the method of least squares; or,
                  The application of the theory of probabilities in the
                  combination of observations. By William Chauvenet ... Being
                  the appendix to the author's Manual of spherical and
                  practical astronomy.
Published:     Philadelphia, Lippincott & co.; London, Trübner
                  & co., 1868.
Description:   2 p.l., 469-566 p., 4 l. tables. 24 cm.
LC Call No.:   QA275.C5
Notes:         "The tables are numbered IX., IX. A., X. and
                  X.A., as they stand in the original work."--Note.
               "Criterion for the rejection of doubtful
                  observations," by Benjamin Peirce (Gould's Astron. jour., v.
                  2, p. 161-163) "nearly in the words of its author, and with
                  only some slight changes of notation": p. 558-566 and tables
                  X, XA.
Subjects:      Least squares.
Other authors: Peirce, Benjamin, 1809-1880.
Control No.:   2161049

Author:        Condon, Edward. [from old catalog]
Title:         The rapid fitting of a certain class of empirical
                  formulae by the method of least squares.
Published:     [n.p.] 1927.
Description:   1 v. cm.
LC Call No.:   QA275.C75
Control No.:   10484459

Author:        Czuber, Emanuel, 1851-1925.
Title:         Theorie der Beobachtungsfehler. Von Emanuel
                  Czuber. Mit 7 in den Text gedruckten Figuren.
Published:     Leipzig, B. G. Teubner, 1891.
Description:   xii p., 1 l., 418 p. tables, diagrs. 23 cm.
LC Call No.:   QA275.C9
Dewey No.:     519.6
Subjects:      Error analysis (Mathematics)
               Least squares.
Control No.:   10165494

Author:        Deming, W. Edwards (William Edwards), 1900-
Title:         Some notes on least squares, by W. Edwards
                  Deming.
Published:     Washington, The Graduate school, the Dept. of
                  agriculture [c1938]
Description:   181p. diagrs. 26 x 20 cm.
LC Call No.:   QA275.D33
Notes:         Mimeographed.
Subjects:      Least squares.
Control No.:   7839951

Author:        Deming, W. Edwards (William Edwards), 1900-
Title:         Statistical adjustment of data / by W. Edwards
                  Deming.
Edition:       1st ed.
Published:     New York : John Wiley & Sons ; London : Chapman &
                  Hall, c1943.
Description:   x, 261 p. : ill. ; 21 cm.
LC Call No.:   QA275.D35
Dewey No.:     519.8
Notes:         Includes bibliographical references and index.
Subjects:      Error analysis (Mathematics)
Control No.:   7860073

Author:        Dodd, Edward Lewis, 1875-1943. [from old
                  catalog]
Title:         The error-risk of the median compared with that
                  of the arithmetic mean,
Published:     Austin, Tex., University of Texas [1914]
Description:   11 p. 23 cm.
LC Call No.:   QA275.D5
Subjects:      Error analysis (Mathematics)
Series Entry:  Bulletin of the University of Texas. no. 323 ...
                  Scientific ser. no. 27. [from old catalog]
Control No.:   8704977

Author:        Faà di Bruno, Francesco, 1825-1888. [from old
                  catalog]
Title:         Cenni elementari sopra il calcolo degli errori,
                  con tavole stereotipate utili ai cultori delle scienze
                  d'osservazione.
Published:     Torino, Tip. del Collegio degli artigianelli,
                  1867.
Description:   75, xxxiv p. illus. 21 cm.
LC Call No.:   QA275.F2
Subjects:      Error analysis (Mathematics)
               Least squares. [from old catalog]
               Mathematics -- Tables.
Control No.:   7105624

Author:        Faye, H. (Hervé), 1814-1902.
Uniform Title: Théorie des erreurs. Spanish
Title:         Teoría de los errores, por H. Faye ...
                  Traducción del francés con autorización del autor, por ...
                  Joaquin de Mendizábal Tamborrel ...
Edition:       Edición de la Sociedad "Alzate".
Published:     México, Imprenta del gobierno, 1888.
Description:   55 p. incl. diagr. 21 cm.
LC Call No.:   QA275.F28
               Microfilm 65424 QA
Notes:         LC copy replaced by microfilm.
               Microfilm. Washington, D.C., Library of
                  Congress.
Subjects:      Error analysis (Mathematics)
Control No.:   4525271

Author:        Ferrero, Annibale, 1839-1902.
Title:         Esposizione del metodo dei minimi quadrati / per
                  Annibale Ferrero.
Published:     Firenze : G. Barbèra, 1876.
Description:   x, 228 p., 1 leaf of plates : ill. ; 25 cm.
LC Call No.:   QA275.F47x 1876
Notes:         Includes bibliographical references.
Subjects:      Least squares.
Control No.:   1456211

Author:        Gauss, K[arl] Fr[iedrich], 1777-1855. [from old
                  catalog]
Title:         Méthode des moindres carrés.
Published:     Paris, Mallet-Bachelier, 1855.
Description:   4 p.l., 167 p. 23 cm.
LC Call No.:   QA275.G27
Subjects:      Least squares. [from old catalog]
Other authors: Bertrand, Joseph Louis François, 1822-1900,
                  [from old catalog] tr.
Control No.:   7267976

Author:        Helwig, Paul Iwan.
Title:         Over een algemeen gemiddelde en de integralen die
                  samenhangen met de foutenwet van het meetkundig gemiddelde
                  ...
Published:     Amsterdam, Delsman & Nolthenius, 1901.
Description:   6 p. l., 79 p. diagr. 30 cm.
LC Call No.:   QA275.H47
Notes:         Proefschrift--Utrecht.
Subjects:      Error analysis (Mathematics)
               Calculus of operations.
Control No.:   6800429

Author:        Henke, R. (Richard)
Title:         Über die Methode der kleinsten Quadrate / von
                  Richard Henke.
Edition:       2., unveränderte Aufl., nebst Zusätzen.
Published:     Leipzig : B.G. Teubner, 1894.
Description:   iv, 77 p. ; 24 cm.
LC Call No.:   QA275.H46x 1894
Notes:         Includes bibliographical references.
Subjects:      Least squares.
Control No.:   3346265

Author:        Henke, Richard. [from old catalog]
Title:         Ueber die methode der kleinsten quadrate ...
Published:     Dresden, Druck von B. G. Teubner, 1868.
Description:   57 p. 22 cm.
LC Call No.:   QA275.H51
Subjects:      Least squares. [from old catalog]
Control No.:   8198193

Author:        Hoel, Paul Gerhard, 1905-
Title:         Certain problems in the theory of closest
                  approximation, by Paul Gerhard Hoel.
Published:     [Baltimore, 1935]
Description:   p. 891-901. 25 cm.
LC Call No.:   QA275.H77 1933
Dewey No.:     519.8
Notes:         Thesis (PH. D.)--University of Minnesota, 1933.
               Thesis t.-p., with "Vita", mounted on p. [2] of
                  cover.
               "Reprinted from American Journal of Mathematics,
                  vol. LVII, no. 4. October, 1935"
Subjects:      Least squares.
Other titles:  Theory of closest approximation.
Control No.:   8300553

Author:        Howe, Malverd Abijah, 1863- [from old catalog]
Title:         Formulas and tables used in the application of
                  the method of least squares,
Published:     Terre haute, Ind., Moore & Langen, printers,
                  1890.
Description:   32 p. tab. 20 cm.
LC Call No.:   QA275.H85
Subjects:      Least squares. [from old catalog]
Control No.:   6792121

Author:        India. Survey of India dept. Trigonometrical
                  branch. [from old catalog]
Title:         Notes on the theory of errors of observation.
Published:     Dehra Dun. Printed at the office of the
                  Trigonometrical branch, Survey of India, 1903.
Description:   24 p. 28 cm.
LC Call No.:   QA275.I4 1903
Subjects:      Error analysis (Mathematics)
Other authors: Eccles, John. [from old catalog]
Other titles:  Theory of errors.
Control No.:   6886990

Author:        Johnson, William Woolsey, 1841-1927.
Title:         The theory of errors and method of least squares,
                  by William Woolsey Johnson ...
Published:     New York, J. Wiley & sons, 1892.
Description:   x, 152, [22] p. incl. tables, diagrs. 20 cm.
LC Call No.:   QA275.J7
Subjects:      Error analysis (Mathematics)
               Least squares.
Control No.:   1217019

Author:        Jørgensen, N. R. (Niels Rasmussen), 1879-
Title:         Undersøgelser over frequensflader og korrelation,
                  af N.R. Jørgensen.
Published:     København, A. Busck, 1916.
Description:   2 p.l., 208 p. incl. tables. 30 cm.
LC Call No.:   QA275.J6
Notes:         Thesis--Copenhagen.
Subjects:      Error analysis (Mathematics)
Control No.:   745928

Author:        Kerl, Otto, 1882- [from old catalog]
Title:         "Voranschläge" der genauigkeit beim
                  trigonometrischen punkteinschalten ...
Published:     [Berlin, Universitäts-buchdr. von G. Schade (O.
                  Francke)] 1907.
Description:   59, [1] p. 3 fold. pl. (incl. plans) tables,
                  diagrs. 23 cm.
LC Call No.:   QA275.K4
Subjects:      Error analysis (Mathematics)
               Triangulation. [from old catalog]
Control No.:   7751821

Author:        Koll, Otto, 1851-1911.
Title:         Die Theorie der Beobachtungsfehler und die
                  Methode der kleinsten Quadrate : mit ihrer Anwendung auf die
                  Geodäsie und die Wassermessungen / von Otto Koll.
Published:     Berlin : Julius Springer, 1893.
Description:   viii, 323, 31 p. : ill. ; 26 cm.
LC Call No.:   QA275.K64x 1893
Notes:         Includes bibliographical references.
Subjects:      Error analysis (Mathematics)
               Least squares.
Control No.:   983733

Author:        Krüger, Louis, 1857-
Title:         Über die Ausgleichung von bedingten
                  Beobachtungen in zwei Gruppen, von L. Krüger.
Published:     Potsdam, B.G. Teubner in Leipzig, 1905.
Description:   2 p. l., 24 p. diagr. 28 x 23 cm.
Series:        Veröffentlichung des Königl. preussischen
                  geodätischen Institutes. Neue Folge, no. 18
LC Call No.:   QA275.K9
Subjects:      Error analysis (Mathematics)
Control No.:   8683163

Author:        Leland, Ora Miner, b. 1876.
Title:         Practical least squares, by Ora Miner Leland.
Edition:       1st ed.
Published:     New York [etc.] McGraw-Hill book company, inc.,
                  1921.
Description:   xiv, 237 p. incl. tables, diagrs. 24 cm.
LC Call No.:   QA275.L4 1921
Notes:         "History and bibliography of least squares": p.
                  201-203.
Subjects:      Least squares.
Control No.:   13399953

Author:        Merriman, Mansfield, 1848-1925.
Title:         A text book on the method of least squares. By
                  Mansfield Merriman.
Published:     New York, J. Wiley, 1884.
Description:   viii, 194 p. tables, diagrs. 22 cm.
LC Call No.:   QA275.M57
Subjects:      Least squares.
Control No.:   6323984

Author:        Näbauer, Martin, 1879- [from old catalog]
Title:         Flächenfehler im einfachen,
Published:     Karlsruhe, G. Braun, 1918.
Description:   2 p. l., 92 p. diagrs. 27 cm.
LC Call No.:   QA275.N3
Subjects:      Error analysis (Mathematics)
               Polygons. [from old catalog]
Control No.:   7801646

Author:        Newcomb, Simon, 1835-1909. [from old catalog]
Title:         A generalized theory of the combination of
                  observations so as to obtain the best result.
Published:     [Baltimore, 1886]
Description:   p. [343]-366. 31 x 25 cm.
LC Call No.:   QA275.N5
Subjects:      Error analysis (Mathematics)
Control No.:   9626229

Author:        Nitz, Konrad, 1882-
Title:         Anwendungen der Theorie der Fehler in der Ebene
                  auf Konstruktionen mit Zirkel und Lineal ... von Konrad
                  Nitz.
Published:     Königsberg i. Pr., Druck von H. Jaeger, 1905.
Description:   3 p. L., 3-32 p., 2 L. diagrs. on pl. 22 cm.
LC Call No.:   QA275.N7
Notes:         Lebenslauf.
               Inaug.-diss.--Königsberg.
Subjects:      Error analysis (Mathematics)
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.14.
Control No.:   9145153

Author:        Pearson, Karl, 1857-1936.
Title:         On the criterion that a given system of
                  deviations from the probable in the case of a correlated
                  system of variables is such that it can be reasonably
                  supposed to have arisen from random sampling. By Karl
                  Pearson.
Published:     [London, 1900]
Description:   p. [157]-174. 22 cm.
LC Call No.:   QA275.P5
Notes:         Caption title.
               From the Philosophical magazine for July, 1900.
Subjects:      Error analysis (Mathematics)
Control No.:   6805749

Author:        Plummer, H. C. (Henry Crozier Keating), b. 1875.
Title:         Note on the principle of the arithmetic mean.
Published:     [London, 1902]
Description:   [545]-551 p. 22 cm.
LC Call No.:   QA275.P73
Subjects:      Error analysis (Mathematics)
Control No.:   9141580

Author:        Roeser, Harry Mance, 1892- [from old catalog]
Title:         Adjustment of parabolic and linear curves
Published:     Washington, Govt. print. off., 1920.
Description:   p. cm.
LC Call No.:   QA275.R6
Subjects:      Least squares. [from old catalog]
Other authors: United States. Bureau of standards. Scientific
                  papers, no. 3988. [from old catalog]
Control No.:   6406518

Author:        Salvosa, Luis Rada, 1891- [from old catalog]
Title:         Generalizations of the normal curve of error ...
Published:     Ann Arbor, Mich., Edward brothers, inc. [1930]
Description:   3 p. l., 53 p., 1 l., 187 p. 23 cm.
LC Call No.:   QA275.S3 1930
Subjects:      Error analysis (Mathematics)
               Functions. [from old catalog]
Other authors: Pearson, Karl, 1857- [from old catalog]
Control No.:   6407848

Author:        Schwering, Karl, b. 1846.
Title:         Lehrbuch der kleinsten Quadrate / von Karl
                  Schwering.
Published:     Freiburg im Breisgau : Herdersche
                  Verlagshandlung, 1909.
Description:   v, 105 p. : ill. ; 22 cm.
LC Call No.:   QA275.S38x 1909
Subjects:      Least squares.
Control No.:   1456210

Author:        Thiele, T. N. (Thorvald Nicolai), 1838-1910.
Title:         Sur la compensation de quelques erreurs
                  quasi-systématiques par la méthode des moindres carrés,
                  par T. N. Thiele.
Published:     Copenhague, C. A. Reitzel, 1880.
Description:   29 p. incl. tab., diagr. 26 x 20 cm.
LC Call No.:   QA275.T41
Subjects:      Least squares
Control No.:   9602171

Author:        Thiele, T. N. (Thorvald Nicolai), 1838-1910.
Title:         Theory of observations, by T.N. Thiele ...
Published:     London, C. & E. Layton, 1903.
Description:   4 p.l., 143 p. 4 diagrs. on 1 pl. 27 x 21 cm.
LC Call No.:   QA275.T42
Notes:         I. The law of causality.--II. Laws of
                  errors.--III. Tabular arrangements.--IV. Curves of
                  errors.--V. Functional laws of errors.--VI. Laws of errors
                  expressed by symmetrical functions.--VII. Relations between
                  functional laws of errors and half-invariants.--VIII. Laws of
                  errors of functions of observations.--IX. Free functions.--X.
                  Adjustment.--XI. Adjustment by correlates.--XII. Adjustment
                  by elements.--XIII. Special auxiliary methods.--XIV. The
                  theory of probability.--XV. The formal theory of
                  probability.--XVI. The determination of probabilities a
                  priori and a posteriori.--XVII. Mathematical expectation and
                  its mean error.
Subjects:      Error analysis (Mathematics)
               Probabilities.
               Correlation (Statistics)
Control No.:   1217074

Author:        U.S. Coast and Geodetic Survey.
Title:         Some elementary examples of least squares, by
                  Oscar S. Adams, mathematician.
Published:     Washington, Govt. Print. Off., 1924.
Description:   17 p. 25 cm.
LC Call No.:   QA275.U6 1924
Notes:         At head of title: Serial no. 250. Department of
                  Commerce. U.S. Coast and Geodetic Survey. E. Lester Jones,
                  director.
Subjects:      Least squares
Other authors: Adams, Oscar Sherman, 1874-
Series Entry:  U.S. Coast and Geodetic Survey. Serial ; no.
                  250.
Control No.:   8730845

Author:        United States. National bureau of standards.
                  Computation laboratory. [from old catalog]
Title:         Tables of probability functions ...
Published:     [New York] 1941-
Description:   2 v. 28 cm.
LC Call No.:   QA275.U63
Notes:         Serial.
Subjects:      Mathematics -- Tables.
               Error analysis (Mathematics)
               Probabilities. [from old catalog]
Control No.:   7853241

Author:        Veltmann, W[ilhelm] 1832- [from old catalog]
Title:         Die fehlerausgleichung nach mittelgrössen ...
Published:     Marburg, Universitäys-buchdruckerei (R.
                  Friedrich), 1885.
Description:   1 p. l., 43, [1] p. 23 cm.
LC Call No.:   QA275.V44
Notes:         Inaug.-dis.--Marburg.
               Lebenslauf.
Subjects:      Least squares.
Control No.:   13448046

Author:        Weitbrecht, Wilh. (Wilhelm)
Title:         Ausgleichungsrechnung nach der methode der
                  kleinsten quadrate von Wilh. Weitbrecht ... Mit 15 figuren
                  und 2 tafeln.
Published:     Leipzig, G.J. Göschen, 1906.
Description:   180 p. 2 fold. tab., diagrs. 16 cm.
Series:        Sammlung Göschen, [302]
LC Call No.:   QA275.W43
Subjects:      Error analysis (Mathematics)
               Least squares.
Control No.:   1689516

Author:        Weitbrecht, Wilhelm. [from old catalog]
Title:         Ausgleichungsrechnung nach der methode der
                  kelinsten quadrate,
Edition:       2., veräderte aufl.
Published:     Berlin und Leipzig, G. J. Göschen, 1912-
Description:   v. diagrs. 16 cm.
LC Call No.:   QA275.W432
Subjects:      Error analysis (Mathematics)
               Least squares. [from old catalog]
Control No.:   6925562

Author:        Weld, Le Roy D. (Le Roy Dougherty), 1880-
Title:         Theory of errors and least squares; a textbook
                  for college students and research workers, by Le Roy D. Weld
                  ...
Published:     New York, The Macmillan Company, 1916.
Description:   xii p., 1 l., 190 p. diagrs. 19 cm.
LC Call No.:   QA275.W45
Subjects:      Error analysis (Mathematics)
               Least squares.
Control No.:   9177929

Author:        Wilks, Samuel Stanley, 1906- [from old catalog]
Title:         On the distributions of statistics in samples
                  from a normal population of two variables with matched
                  sampling of one variable,
Published:     [Iowa City? 1932]
Description:   40 p. 24 cm.
LC Call No.:   QA275.W65 1931
Subjects:      Correlation (Statistics) [from old catalog]
Control No.:   9693042

Author:        Wright, T. W. (Thomas Wallace)
Title:         The adjustment of observations by the method of
                  least squares with applications to geodetic work, by Thomas
                  Wallace Wright ... with the coöperation of John Fillmore
                  Hayford ...
Edition:       2d ed.
Published:     New York, D. Van Nostrand company, 1906-
Description:   ix, 298 p. diagrs. 23 cm.
LC Call No.:   QA275.W96
Subjects:      Least squares.
               Geometry.
Other authors: Hayford, John Fillmore, 1868-1925.
Control No.:   2634218

Author:        Wright, T. W. (Thomas Wallace)
Title:         A treatise on the adjustment of observations,
                  with applications to geodetic work and other measures of
                  precision. By T.W. Wright ...
Published:     New York, D. Van Nostrand, 1884.
Description:   437 p. incl. tables, diagrs. 24 cm.
LC Call No.:   QA275.W95
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Least squares.
               Geodesy.
Other titles:  Adjustment of observations.
Control No.:   3106760

Author:        Zachariae, Georg Carl Christian, 1835-
Title:         De mindste kvadraters methode. Til brug ved
                  undervisningen i Officerskolens stabsafdeling. Af G.
                  Zachariae.
Published:     Nyborg, V. Schönemann, 1871.
Description:   viii, 233, [1] p. diagr. 25 cm.
LC Call No.:   QA275.Z12
Subjects:      Least squares.
Control No.:   6323983

Author:        Busson-Descars, P. (Pierre)
Title:         Essai sur la cubature des terrasses : avec son
                  application à la construction des grandes routes / par P.
                  Busson-Descars.
Published:     Paris : F. Didot, 1818.
Description:   xii, 140 p., XI folded leaves of plates : ill. ;
                  22 cm.
LC Call No.:   QA299.4.C83B87x 1818
Subjects:      Cubature formulas.
               Highway engineering.
Control No.:   1928045
