#+STARTUP: showeverything logdone
#+options: num:nil



Author:        Borel, Emile, 1871-1956.
Title:         Leçons sur les fonctions monogènes uniformes
                  d'une variable complexe, par Émile Borel, rédigées par
                  Gaston Julia.
Published:     Paris, Gauthier-Villars, 1917.
Description:   ix p., 1 l., 163, [2] p. diagrs. 26 cm.
Series:        Collection de monographies sur la théorie des
                  fonctions
LC Call No.:   QA332.B7
Subjects:      Functions.
Other authors: Julia, Gaston, 1893- ed.
Control No.:   6861451

Author:        Boutroux, Pierre Léon, 1880- [from old catalog]
Title:         Sur quelques propriétés des fonctions entières
                  ...
Published:     Stockholm, Centraltryckeriet, 1903.
Description:   2 p.l., 128 p., 1 l. diagr. 29 x 23 cm.
LC Call No.:   QA332.B8
Subjects:      Functions. [from old catalog]
Control No.:   9617577

Author:        Burdette, Albert Clark, 1905-
Title:         On simultaneous expansions of analytic functions
                  in composite power series / Albert Clark Burdette.
Published:     Urbana, Ill., 1936.
Description:   13 p. ; 21 cm.
LC Call No.:   QA332.B95 1936
Notes:         Vita.
               "Lithoprinted by Edwards brothers, inc. ... Ann
                  Arbor, Michigan."
               Abstract of thesis (Ph. D.)--University of
                  Illinois, 1936.
Subjects:      Functions.
               Series.
               Functional equations.
Other titles:  Composite power series.
Control No.:   7834519

Author:        Burdette, Albert Clark, 1905-
Title:         On simultaneous expansions of analytic functions
                  in composite power series / Albert Clark Burdette.
Published:     Urbana, Ill., 1936.
Description:   13 p. ; 21 cm.
LC Call No.:   QA332.B95 1936
Notes:         Vita.
               "Lithoprinted by Edwards brothers, inc. ... Ann
                  Arbor, Michigan."
               Abstract of thesis (Ph. D.)--University of
                  Illinois, 1936.
Subjects:      Functions.
               Series.
               Functional equations.
Other titles:  Composite power series.
Control No.:   7834519

Author:        Desaint, L. (Louis), 1874-
Title:         Sur quelques points de la théorie des fonctions
                  / par L. Desaint.
Published:     Paris : Gauthier-Villars et fils, 1897.
Description:   74 p. ; 28 cm.
LC Call No.:   QA332.D5
Notes:         Issued also in Annales de l'École normale
                  supérieure, 1897.
               Thèse--Université de Paris.
Subjects:      Functions.
Control No.:   6807565

Author:        Robertson, Malcom Irving Slingsby, 1906-
Title:         On the theory of univalent functions, by Malcom
                  I.S. Robertson.
Published:     Princeton, [1936]
Description:   p.374-408. 26 cm.
LC Call No.:   QA332.R6 1934
Notes:         cover-title.
               Thesis (Ph. D.)--Princeton university, 1934.
               "Reprinted from Annals of mathematics, vol. 37,
                  April, 1936."
Subjects:      Functions.
Other titles:  Univalent functions.
Control No.:   9239488

Author:        Zöllich, Hans, 1884-
Title:         Beiträge zur theorie der ganzen transzendenten
                  funktionen der ordnung null ...
Published:     Halle a. S., Buchdr. des Waisenhauses, 1908.
Description:   58 p., 1 L. 23 cm.
LC Call No.:   QA332.Z7
Notes:         Lebenslauf.
               Inaug.-diss.--Halle.
Subjects:      Transcendental functions.
Control No.:   7282628

Author:        Starke, Emory Potter, 1896-
Title:         Certain uniform functions of rational functions,
                  by Emory P. Starke ...
Published:     [Menasha, Wis., and New York, 1927]
Description:   276-286 p. 28 cm.
LC Call No.:   QA332.S7 1927
Notes:         Thesis (Ph. D.)--Columbia university, 1927.
               Vita.
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 29, no. 2 ... April, 1927."
Subjects:      Functions.
Control No.:   8272510

Author:        Zoretti, Ludovic, b. 1880.
Title:         Sur les fonctions analytiques uniformes qui
                  possèdent un ensemble parfait discontinu de points
                  singuliers / par M. Ludovic Zoretti.
Published:     Paris : Gauthier-Villars, 1905.
Description:   51 p. ; 28 cm.
LC Call No.:   QA332.Z8
Notes:         Thèse--Université de Paris.
               Issued also in Journal de mathématiques pures et
                  appliquées, 6. sér., t. 1, 1905.
Subjects:      Functions.
Control No.:   8680853

Author:        Ahlfors, Lars Valerian, 1907- ed.
Title:         Contributions to the theory of Riemann surfaces;
                  centennial celebration of Riemann's dissertation [by] L.V.
                  Ahlfors [and others]
Published:     Princeton, N.J., Princeton University Press,
                  1953.
Description:   v, 264 p. 26 cm.
Series:        Annals of mathematics studies, no. 30
LC Call No.:   QA333.A4
Dewey No.:     517.5
Notes:         Includes bibliographies.
Subjects:      Riemann surfaces.
Control No.:   6501596

Author:        Ahlfors, Lars Valerian, 1907-
Title:         Riemann surfaces, by Lars V. Ahlfors and Leo
                  Sario.
Published:     Princeton, N.J., Princeton University Press,
                  1960.
Description:   382 p. illus. 24 cm.
Series:        Princeton mathematical series, 26
LC Call No.:   QA333.A43
Dewey No.:     517.81
Notes:         Includes bibliography.
Subjects:      Riemann surfaces.
               Topology.
Other authors: Sario, Leo, joint author.
Series Entry:  Princeton mathematical series ; 26.
Control No.:   1221801

Author:        Graf, Joh[ann] Heinrich, 1852- [from old
                  catalog]
Title:         Beiträge zur theorie der Riemann'schen fläche
                  ...
Published:     Zürich, Druck von O. Füssli & co., 1878.
Description:   46 p. diagrs. 22 cm.
LC Call No.:   QA333.G7
Subjects:      Riemann surfaces. [from old catalog]
Control No.:   9606366

Author:        Johansson, Severin, 1879- [from old catalog]
Title:         Über die uniformisirung Riemannscher flächen
                  mit endlicher windungspunkte,
Published:     Helsingfors, Druckerei der Finnischen
                  litteratur-gesellschaft, 1905.
Description:   1 p.l., 29 p. 30 x 24 cm.
LC Call No.:   QA333.J8
Subjects:      Riemann surfaces. [from old catalog]
Control No.:   8212680

Author:        Kamer, Elizabeth van de.
Title:         Over rationeele functies behoorende bij een
                  Riemannsch oppervlak ...
Published:     Utrecht, J. von Boekhoven, 1901.
Description:   5 p.l., 122 p. 23 cm.
LC Call No.:   QA333.K15
Notes:         Inaug.-dis.--Utrecht.
Subjects:      Functions.
               Riemann surfaces.
Control No.:   1689177

Author:        Kasten, Hermann. [from old catalog]
Title:         Zur theorie der dreiblättrigen Riemann'schen
                  fläche ...
Published:     Bremen, Druckerei von H. Frese, 1876.
Description:   44 p. diagrs., on fold. pl. 23 cm.
LC Call No.:   QA333.K2
Subjects:      Riemann surfaces. [from old catalog]
Control No.:   6796337

Author:        Kommerell, K[arl] [from old catalog]
Title:         Riemannsche flächen im ebenen raum von vier
                  dimensionen ...
Published:     Leipzig [1905]
Description:   1 p.l., 49 p. diagrs. 24 cm.
LC Call No.:   QA333.K75
Subjects:      Riemann surfaces. [from old catalog]
               Hyperspace. [from old catalog]
Control No.:   6815480

Author:        MacLane, Gerald R.
Title:         Riemann surfaces and asymptotic values associated
                  with real entire functions.
Published:     [Houston, Tex., Rice Institute] 1952.
Description:   93 p. 24 cm.
Series:        Rice Institute pamphlet. Special issue. Monograph
                  in mathematics
LC Call No.:   QA333.M3
Dewey No.:     517.5
Notes:         Includes bibliography.
Subjects:      Riemann surfaces.
               Asymptotes.
               Functions.
Control No.:   7447247

Author:        Neumann, Karl Gottfried, 1832-1925. [from old
                  catalog]
Title:         Das Dirischlet'sche princip in seiner anwendung
                  auf die Reimann'schen flächen.
Published:     Leipzig, B. G. Teubner, 1865.
Description:   2 p. l., 80 p. 23 cm.
LC Call No.:   QA333.N4
Subjects:      Riemann surfaces. [from old catalog]
Control No.:   7369745

Author:        Prym, F. (Friedrich Emil), b. 1841.
Title:         Theorie der Prym'schen funktionen, erster
                  ordnung, im Anschluss an die schöpfungen Riemann's, von
                  Friedrich Prym und George Rost.  Mit 25 figuren im text.
Published:     Leipzig, B. G. Teubner, 1911.
Description:   xi, 250 p., vi, 300 p. front. (group ports.)
                  diagrs. 29 x 24 cm.
LC Call No.:   QA333.P7
Subjects:      Functions.
               Riemann surfaces.
Other authors: Rost, George, 1870-   , jt. author.
Control No.:   5992313

Author:        Schumacher, Hermann, 1882-
Title:         Über eine Riemann'sche funktionenklasse mit
                  zerfallender thetafunktion ...
Published:     Uppsala, Almqvist & Wiksells buchdr.-a.-g.,
                  1907.
Description:   1 p. l., 56 p. 2 pl., diagrs. 30 cm.
LC Call No.:   QA333.S4
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Riemann surfaces.
               Functions, Theta.
Control No.:   10092585

Author:        Thomae, Johannes, 1840- [from old catalog]
Title:         De propositione quadam Riemanniana ex analysis
                  situs ...
Published:     Numburgi a/S, typis expressit G. Paetz [1867]
Description:   10 p., 1 l. diagr. 24 cm.
LC Call No.:   QA333.T45
Subjects:      Riemann surfaces. [from old catalog]
Control No.:   10073102

Author:        Weyle, Hermann, 1885-
Title:         Die Idee der riemannschen Fläche, von Hermann
                  Weyl, mit 27 in den Text gedruckten Figuren.
Published:     Leipzig, Berlin, B. G. Teubner, 1913.
Description:   ix, 169 p. illus. 24 cm.
Series:        Mathematische Vorlesungen an der Universität
                  Göttingen, 5
LC Call No.:   QA333.W4
Subjects:      Riemann surfaces.
Control No.:   8702943

Author:        Vass, John Isaac, 1901- [from old catalog]
Title:         A class of boundary problems of highly irregular
                  type,
Published:     [Durham, N.C., 1936]
Description:   cover-title, p. 151-165. diagrs. 26 cm.
LC Call No.:   QA335.V3
Subjects:      Functions. [from old catalog]
Control No.:   9245054

Author:        Appell, Paul, 1855-1930.
Title:         Théorie des fonctions algébriques et de leurs
                  intégrales. Étude des fonctions analytiques sur une surface
                  de Riemann; par Paul Appell ... [et] Édouard Goursat ...
Published:     Paris, Gauthier-Villars et fils, 1895.
Description:   2 p.l., [a]-g, [1], x, 530 p. diagrs. 25 cm.
LC Call No.:   QA341.A6
Subjects:      Algebraic functions.
Other authors: Goursat, Edouard, 1858-1936, joint author.
Control No.:   4526121

Author:        Beatty, Samuel. [from old catalog]
Title:         Extensions of results concerning the derivatives
                  of an algebraic function of a complexvariable.
Published:     [n.p.] 1915.
Description:   1. cm.
LC Call No.:   QA341.B4
Control No.:   9542372

Author:        Bliss, Gilbert Ames, 1876-1951.
Title:         Algebraic functions, by Gilbert Ames Bliss ...
Published:     New York, American mathematical society, 1933.
Description:   ix, 218 p. diagrs. 23 cm.
Series:        American mathematical society. Colloquium
                  publications, vol. XVI
LC Call No.:   QA341.B45
Dewey No.:     512.8
Notes:         "Published with the cooperation of the National
                  research council."
               "List of references": p. 214-216.
Subjects:      Algebraic functions.
Other authors: National Research Council (U.S.)
Control No.:   7823538

Author:        Cohen, Eckford, 1920- [from old catalog]
Title:         Sums of an even number of squares in GF
Published:     [n.p., 1947]
Description:   251-267 p. 26 cm.
LC Call No.:   QA341.C65
Subjects:      Algebraic functions.
               Polynomials.
Control No.:   8836871

Author:        Dumas, Gustave.
Title:         Sur les fonctions à caractère algébrique dans
                  le voisinage d'un point donné ...
Published:     Paris, Librairie scientifique J. Rousset, 1904.
Description:   2 p.l., 72 p., 1 l., [2] p. diagrs. 28 x 23 cm.
LC Call No.:   QA341.D8
Notes:         Thèse--Univ. de Paris.
Subjects:      Algebraic functions.
Control No.:   272967

Author:        Fields, John Charles, 1863-1932.
Title:         Theory of the algebraic functions of a complex
                  variable by John Charles Fields.
Published:     Berlin, Mayer & Müller, 1906.
Description:   vii, 186 p. 29 cm.
LC Call No.:   QA341.F46
Subjects:      Algebraic functions.
Control No.:   8215897

Author:        Fischer, Karl, 1868-
Title:         Ueber kanonische Systeme algebraischer Functionen
                  einer veränderlichen, die einem Gattungsbereich dritter oder
                  vierter Ordnung angehören ...
Published:     Berlin, Druck von G. Reimer, 1896.
Description:   2 p. l., 23 p., 2 l. 28 x 22 cm.
Series:        [Berlin. Universität. Dissertationen, v. 26, no.
                  10]
LC Call No.:   QA341.F52
Notes:         Inaug.-diss.--Berlin.
               Vita.
               "Sonderabdruck aus hft. 1, bd. 117 des Journals
                  für die reine und angewandte mathematik."
Subjects:      Algebraic functions.
Control No.:   5863972

Author:        Gill, Bennington Pearson, 1898-
Title:         An analogue for algebraic functions of the
                  Thue-Siegel theorem, by Bennington Pearson Gill ...
Published:     Princeton, N.J., 1930.
Description:   1 p. l., p. 207-218, 1 l. 26 cm.
LC Call No.:   QA341.G5 1930
Notes:         Thesis (PH. D.)--Columbia university, 1930.
               Vita.
               "Reprinted from the Annals of mathematics, vol.
                  31 (1930)."
Subjects:      Algebraic functions.
Control No.:   8749082

Author:        Gourin, Eli, 1883- [from old catalog]
Title:         On irreducible polynomials in several variables
                  which become reducible when the variables are replaced by
                  powers of themselves,
Published:     [New York] 1930.
Description:   485-501, [1] p. 28 cm.
LC Call No.:   QA341.G6 1931
Subjects:      Algebraic functions.
               Polynomials.
Control No.:   10157776

Author:        Jung, Heinrich W. E. (Heinrich Wilhelm Ewald),
                  1876-
Title:         Die wurzelfunktionen in dem durch die gleichung G
                  (p, q) == O vom range 2 und durch die gleichung Zp2s == H
                  (p, q) definierten algebraischen körper K (p,q,z) ...
Published:     Marburg, Universitäts-buchdruckerei von J.A.
                  Koch, 1902.
Description:   31 p. 22 cm.
LC Call No.:   QA341.J95
Notes:         Zur erlangung der venia legendi--Marburg.
Subjects:      Algebraic functions.
Control No.:   10078392

Author:        Kneser, Adolf, 1862-1930.
Title:         Über einige fundamentalsätze aus der theorie
                  der algebraischen funktionen von mehreren variabeln ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1884.
Description:   25 p. 22 cm.
LC Call No.:   QA341.K68
Subjects:      Algebraic functions.
Control No.:   7736487

Author:        Mac Lane, Saunders, 1909-
Title:         Algebraic functions; lectures by Saunders MacLane
                  at Harvard university, spring 1939; notes compiled by Edwin
                  N. Nilson.
Published:     Ann Arbor, Mich., Planographed by Edwards
                  brothers, inc., 1940.
Description:   3 p.l., 62 p. illus. 28 x 22 cm.
LC Call No.:   QA341.M3
Dewey No.:     512.8
Notes:         "Selected bibliography": p. 61.
Subjects:      Algebraic functions.
Other authors: Nilson, Edwin N. (Edwin Norman)
Control No.:   4054538

Author:        Netto, Eugen, 1846-1919. [from old catalog]
Title:         De transformatione aequationis y>n = [Pi] (x),
                  designante [Pi] (x) functionem integram rationalem variabilis
                  x, in aequationem [eta]p2s = [Pi] [xi] ...
Published:     Berolini, typis expressit G. Schade [1870]
Description:   20 p. 25 x 21 cm.
LC Call No.:   QA341.N47
Subjects:      Algebraic functions.
Control No.:   10081620

Author:        Picard, Emile, 1856-1941.
Title:         Théorie des fonctions algébriques de deux
                  variables indépendantes, par Émile Picard et Georges
                  Simart.
Published:     Paris, Gauthier-Villars, 1897-1906.
Description:   2 v. diagrs. 26 cm.
LC Call No.:   QA341.P53
Subjects:      Algebraic functions.
Other authors: Simart, Georges.
Control No.:   6438043

Author:        Rehfeld, Camille, 1884-
Title:         Ueber Klassenbildung und Klassenzahl in
                  algebraischen Funktionenkörpern / von Camille Rehfeld.
Published:     Strassburg i E. : C. Müh, 1906.
Description:   52 p. ; 23 cm.
LC Call No.:   QA341.R34
Notes:         Vita.
               Inaug.-diss.--Strassburg.
Subjects:      Algebraic functions.
Control No.:   8216329

Author:        Sauer, Karl, 1882- [from old catalog]
Title:         Zur funktionentheorie auf dem algebraischem
                  gebilde S = 1p3s/ fb3sn (z) ...
Published:     Leipzig, Druck von B. G. Teubner, 1906.
Description:   37 p., 1 l. diagrs. 28 x 22 cm.
LC Call No.:   QA341.S3
Subjects:      Algebraic functions.
Control No.:   7750615

Author:        Schilling, Otto Franz Georg, 1911-
Title:         The theory of valuations.
Published:     New York, American Mathematical Society, 1950.
Description:   vii, 253 p. 26 cm.
Series:        Mathematical surveys, no. 4
LC Call No.:   QA341.S35
Dewey No.:     512.8
Notes:         Includes bibliographies.
Subjects:      Algebraic functions.
               Algebraic fields.
Series Entry:  Mathematical surveys ; no. 4.
Control No.:   6022147

Title:         Smithsonian mathematical tables. Hyperbolic
                  functions.
Published:     Washington, Smithsonian Institution. 1909-1961.
Description:   v. tables. 24 cm.
LC Call No.:   QA342.S6
Subjects:      Exponential functions.
Other authors: Becker, George F. (George Ferdinand), 1847-1919.
               Van Orstrand, C. E. (Charles Edwin), 1870-1959.
Other authors: Smithsonian Institution.
Control No.:   11044909

Author:        Cooley, Hollis Raymond, 1899- [from old catalog]
Title:         Trigonometric and logarithmic functons,
Published:     New York, N.Y., New York university press book
                  store, 1940.
Description:   vi, 142 p. diagrs. 23 cm.
LC Call No.:   QA342.C66
Subjects:      Trigonometrical functions. [from old catalog]
               Logarithms. [from old catalog]
Other authors: Graham, Palmer Hampton, 1887- [from old catalog]
                  joint author.
               John, Frederick Wallace, [from old catalog] joint
                  author.
               Tilley, Arthur, 1891- [from old catalog] joint
                  author.
Other titles:  Logarithmic functions.
Control No.:   8782333

Author:        De Morgan, Augustus, 1806-1871.
Title:         The connexion of number and magnitude: an attempt
                  to explain the fifth book of Euclid. By Augustus De Morgan
                  ...
Published:     London, Taylor and Walton, 1836.
Description:   iv, 87 p. diagrs. 21 cm.
LC Call No.:   QA342.D38
Subjects:      Ratio and proportion.
Control No.:   6324243

Author:        De Morgan, Augustus, 1806-1871. [from old
                  catalog]
Title:         Elements of trigonometry,
Published:     London, Taylor and Walton, 1837.
Description:   vii p., 2 l., 143, iv, 87 p. diagrs. 22 cm.
LC Call No.:   QA342.D3
Subjects:      Plane trigonometry.
               Exponential functions.
Control No.:   8197580

Author:        Dötsch, Georg. [from old catalog]
Title:         Ueber die hyperbolischen functionen und deren
                  beziehungen zu den kreisfunctionen ...
Published:     Nürnberg, druck der Bieling'schen offizin (G.
                  Dietz) 1870.
Description:   23 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA342.D6
Subjects:      Exponential functions.
Control No.:   10074680

Author:        Echols, William H. (William Holding), 1859-1934
Title:         The evolutionary construction of the imaginary
                  power of a number and its experssion as the exponential
                  function, by William H. Echols.
Published:     Charlottesville, Va., University of Virginia
                  [1913]
Description:   p. 319-330. 27 cm.
Series:        Bulletin of the Philosophical Society. 
                  Scientific ser., vol. 1, no. 13 ... Jan., 1913
               University of Virginia publications.
LC Call No.:   QA342.E2
Notes:         Cover title.
Subjects:      Exponential functions.
Control No.:   6830406

Author:        Friedländer, Julius.
Title:         General investigation of the convergence of
                  trigonometric series into which arbitrary functions are
                  expanded and some new applications of the same / by Julius
                  Friedländer.
Published:     Berlin : [s.n.], 1853.
Description:   28 p. ; 23 cm.
LC Call No.:   QA342.F74x 1853
Notes:         "Only 25 copies printed"--T.p. verso.
Subjects:      Trigonometrical functions.
Control No.:   983737

Author:        Gronau, J[ohann] F[riedrich] W[ilhelm],
                  1803-1887. [from old catalog]
Title:         Beilage zu den tafeln für sämmtliche
                  trigonometrische functionen der cyklischen und hyperbolischen
                  sektoren,
Published:     [Danzig, Druck von A. W. Kafemann, 1863]
Description:   4 p. 26 cm.
LC Call No.:   QA342.G8
Subjects:      Exponential functions.
Control No.:   7737839

Author:        Günther, Siegmund, 1848-1923.
Title:         Die lehre von den gewöhnlichen und
                  verallgemeinerten hyperbelfunktionen, theilweise auf grund
                  freier bearbeitung von Laisant's "Essai sur les fonctions
                  hyperboliques" und Forti's "Tavole logaritmiche" dargestellt
                  von dr. Siegm. Günther ...
Published:     Halle a/S., L. Nebert, 1881.
Description:   x, 440 p. diagrs. 23 cm.
LC Call No.:   QA342.G9
Notes:         "Historisch-bibliographische einleitung": p.
                  [1]-63.
               References at end of each chapter.
Subjects:      Exponential functions.
               Geometry, Non-Euclidean.
Other authors: Laisant, C.-A. (Charles-Ange), 1841-1920. Essai
                  sur les fonctions hyperboliques.
               Forti, Angelo, 1818-1900. Tavole dei logaritmi.
Control No.:   745092

Author:        Harvard University. Computation Laboratory.
Title:         Tables of the generalized exponential-integral
                  functions.
Published:     Cambridge, Harvard University Press, 1949.
Description:   xxv, 416 p. 28 cm.
Series:        Its Annals, v. 21
LC Call No.:   QA342.H39
Dewey No.:     517.36
Notes:         Includes "References."
Subjects:      Exponential functions
Series Entry:  Harvard University. Computation Laboratory.
                  Annals, v. 21.
Control No.:   6956916

Author:        Harvard University. Computation Laboratory. [from
                  old catalog]
Title:         Tables of inverse hyperbolic functions.
Published:     Cambridge, Harvard Univ. Press, 1949.
Description:   xx, 290 p. 28 cm.
Series:        Harvard University. Computation Laboratory.
                  Annals, v. 20
LC Call No.:   QA342.H38
Dewey No.:     517.36
Notes:         "Bibliography of tables of inverse hyperbolic
                  functions": p. xvi-xx.
Subjects:      Exponential functions.
Control No.:   12042013

Author:        Hayward, R. Baldwin (Robert Baldwin), 1829-1903.
Title:         The algebra of coplanar vectors and trigonometry.
                  By R. Baldwin Hayward ...
Published:     London, New York, Macmillan and co., 1892.
Description:   xxix p., 1 l., 343, [1] p. illus. 19 cm.
LC Call No.:   QA342.H4
Notes:         "Historical note": p. xvii-xxi.
Subjects:      Numbers, Complex.
               Exponential functions.
               Series, Infinite.
Control No.:   4525188

Author:        Hessenberg, Gerhard, 1874-1925.
Title:         Transzendenz von e und [pi]; ein beitrag zur
                  höheren mathematik vom elementaren standpunkte aus, von
                  Gerhard Hessenberg ...
Published:     Leipzig, Berlin, B.G. Teubner, 1912.
Description:   x, 106 p. diagrs. 24 cm.
LC Call No.:   QA342.H5
Dewey No.:     514.1
Notes:         Errata slip attached to p. [103]
Subjects:      Exponential functions.
               Trigonometrical functions.
Control No.:   1218863

Author:        Kennelly, Arthur E. (Arthur Edwin), 1861-1939.
Title:         Chart atlas of complex hyperbolic and circular
                  functions / by A. E. Kennelly.
Published:     Cambridge : Harvard University Press, 1914.
Description:   [23] p. : illus. ; 52 x 52 cm.
LC Call No.:   QA342.K46 1914
Notes:         "This chart supplements the °Tables of complex
                  hyperbolic and circular functions® by the same author."
Subjects:      Exponential functions.
Control No.:   7299572

Author:        Kennelly, Arthur Edwin, 1861-1939. [from old
                  catalog]
Title:         Chart atlas of complex hyperbolic and circular
                  functions.
Edition:       [3d ed., rev. and enl.]
Published:     Cambridge, Harvard University Press, 1924.
Description:   66 p. 52 cm.
LC Call No.:   QA342.K46 1924
Subjects:      Exponential functions.
Control No.:   8834569

Author:        Kennelly, Arthur Edwin, 1861- [from old catalog]
Title:         Chart atlas of complex hyperbolic and circular
                  functions,
Published:     Cambridge, Harvard university press; [etc., etc.]
                  1921.
Description:   4 p. l., 27 charts. 52 x 52 cm.
LC Call No.:   QA342.K46 1921
Subjects:      Exponential functions.
Control No.:   8722256

Author:        Le Cointe, Ignace Louis Alfred, 1823-1893. [from
                  old catalog]
Title:         Leçons sur la théorie des fonctions circulaires
                  et la trigonométrie,
Published:     Paris, Mallet-Bachelier, 1858.
Description:   xii, 387, [1] p. diagrs. 21 cm.
LC Call No.:   QA342.L4
Subjects:      Trigonometrical functions. [from old catalog]
               Trigonometry. [from old catalog]
               Trigonometry -- Problems, exercises, etc. [from
                  old catalog]
Control No.:   9699485

Author:        MacColl, LeRoy Archibald, 1896-
Title:         On the distributions of the zeros of sums of
                  exponentials of polynomials, by LeRoy Archibald MacColl.
Published:     [New York, 1934]
Description:   1 p. ?., p. 341-360. 28 cm.
LC Call No.:   QA342.M13 1934
Dewey No.:     517.5
Notes:         Thesis (Ph. D.)--Columbia University, 1934.
               Vita.
               "Reprinted from Transactions of the American
                  Mathematical Society, volume 36, number 2 ... 1934."
Subjects:      Polynomials.
               Exponential function

Author:        Macfarlane, Alexander, 1851-1913.
Title:         On the definitions of the trigonometric
                  functions. By Alexander Macfarlane ...
Published:     Boston, J.S. Cushing & co., printers [1894]
Description:   1 p.l., 49 p. diagrs. 25 cm.
LC Call No.:   QA342.M14
Notes:         Read before the mathematical congress at Chicago,
                  August 22, 1893.
Subjects:      Trigonometry.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
Control No.:   3107018

Author:        Philip, Robert Ashby. [from old catalog]
Title:         Bifoliate functions,
Published:     Fairhaven, Mass., The Monographic press, 1935.
Description:   [53] p. 27 x 22 cm.
LC Call No.:   QA342.P55
Subjects:      Exponential functions.
               Logarithms. [from old catalog]
Control No.:   8307530

Author:        Poinsot, Louis, 1777-1859. [from old catalog]
Title:         Recherches sur l'analyse des sections
                  angulaires,
Published:     Paris, Bachelier, 1825.
Description:   4 p.l., 80 p. 26 x 20 cm.
LC Call No.:   QA342.P75
Subjects:      Trigonometrical functions. [from old catalog]
Control No.:   6335054

Author:        Roggatz, Max. [from old catalog]
Title:         Einige anwendungen der theorie der hyperbolischen
                  funktionen ...
Published:     Göttingen, Druck von E. A. Huth, 1876.
Description:   44 p. diagrs. on fold. pl. 21 cm.
LC Call No.:   QA342.R7
Subjects:      Exponential functions.
Control No.:   8205178

Author:        Salazar, Arturo E., 1855- [from old catalog]
Title:         Las funziones iperbólikas i su aplikazion a los
                  problemas de injeniería eléktrika, por A.E. Salazar.
Published:     Killota, F. Enrríkez, 1913.
Description:   26 p. 25 cm.
LC Call No.:   QA342.S3
Subjects:      Exponential functions.
Control No.:   13194752

Author:        Sciobereti, Raymond Henri, 1886- [from old
                  catalog]
Title:         Complex numbers, hyperbolic functions, Fourier's
                  series,
Published:     Ann Arbor, Mich., Edwards brothers, inc., c1933.
Description:   1 p. l., 94, 38 numb. l. diagrs. 27 cm.
LC Call No.:   QA342.S75
Control No.:   7197339

Author:        Smoley, C. K. (Constantine Kenneth), 1869-1952.
Title:         Segmental functions; text and tables giving
                  simple methods of solving a circular segment, and of
                  compiling its area, when the segment is given with any 2 of
                  its 5 parts, viz.--the arc, the chord, the radius, the
                  central angle and the height, with numerous examples
                  illustrating the application of these methods.
Edition:       [2d ed.] Extended by E. R. Smoley and N. G.
                  Smoley.
Published:     Chautauqua, N.Y., C. K. Smoley & Sons, 1956.
Description:   255, 193 p. illus. 19 cm.
LC Call No.:   QA342.S65 1956
Dewey No.:     510.835
Subjects:      Circle.
               Logarithms.
Other authors: Smoley, E. R.
Control No.:   7931690

Author:        Smoley, C. K. (Constantine Kenneth), 1869-1952.
Title:         Segmental functions; text and tables offering
                  simple methods of solving a circular segment, and of
                  computing its area, when the segment is given with any 2 of
                  its 5 parts, viz., the arc, the chord, the radius, the
                  central angle and the height, with numerous examples
                  illustrating the application of these methods. By C.K. Smoley
                  ...
Published:     Scranton, Pa., C.K. Smoley and sons [c1937]
Description:   xliii, 255 p., 1 l., 184 p. diagrs. 18 cm.
LC Call No.:   QA342.S65
Dewey No.:     510.835
Notes:         On cover: First edition.
               "Part two containing reprints from Smoley's
                  Parallel tables of logarithms and squares; also extension of
                  logarithms of the English system of linear measure to 200
                  feet": 1 l., 184 p. at end.
Subjects:      Circle.
               Logarithms.
Control No.:   4054289

Author:        Smoley, Constantine Kenneth, 1869-1950. [from old
                  catalog]
Title:         Segmental functions; text and tables giving
                  simple methods of solving a circular segment ...
Published:     Chautauqua, N.Y., C. K. Smoley, 1962.
Description:   255, 179, 193 p. illus. 19 cm.
LC Call No.:   QA342.S65 1962
Subjects:      Circle. [from old catalog]
               Logarithms. [from old catalog]
Other authors: Smoley, E. R. [from old catalog]
               Smoley, N. G. [from old catalog]
Control No.:   8910148

Author:        Van Orstrand, Charles B. [from old catalog]
Title:         Tables of the exponential function and of the
                  circular sine and cosine to radian argument.
Published:     [n.p.] [1921]
Description:   1 v. fol. cm.
LC Call No.:   QA342.V3
Control No.:   8145965

Author:        Appell, Paul, 1855-1930.
Title:         Principes de la théorie des fonctions
                  elliptiques et applications, par P. Appell ... [et] E. Lacour
                  ...
Published:     Paris, Gauthier-Villars et fils, 1897.
Description:   ix, 421 p. illus., diagrs. 25 cm.
LC Call No.:   QA343.A6
               Microfilm 15383 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Elliptic functions.
Other authors: Lacour, E. (Emile), 1854- joint author.
Control No.:   2161943

Author:        Bacon, Clara Latimer, 1866- [from old catalog]
Title:         The Cartesian oval and the elliptic functions p
                  and ¼ ...
Published:     [Baltimore] 1913.
Description:   1 p. l., p. [261]-280, 1 l. diagrs. 31 cm.
LC Call No.:   QA343.B15
Subjects:      Elliptic functions.
               Curves, Quartic. [from old catalog]
Control No.:   9639582

Author:        Baker, Arthur L[atham] 1853- [from old catalog]
Title:         Elliptic functions.
Published:     New York, J. Wiley & sons, 1890.
Description:   iv p., 1 l., 118 p. diagrs. 24 cm.
LC Call No.:   QA343.B16
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Control No.:   10075215

Author:        Baker, Arthur L[atham] 1853- [from old catalog]
Title:         Elliptic functions.
Published:     New York, J. Wiley & sons, 1890.
Description:   iv p., 1 l., 118 p. diagrs. 24 cm.
LC Call No.:   QA343.B16
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Control No.:   10075215

Author:        Biedermann, Paul [Friedrich], 1862- [from old
                  catalog]
Title:         Ueber multiplicator-gleichungen höherer stufe im
                  gebiete der elliptischen functionen ...
Published:     Greifswald, Druck von F. W. Kunike, 1887.
Description:   2 p.l., 90 p., 1 l. 21 cm.
LC Call No.:   QA343.B58
Subjects:      Modular functions.
Control No.:   9137876

Author:        Biermann, Wilhelm Gustav Adolph, 1841-1888. [from
                  old catalog]
Title:         Problemata quaedam mechanica functionum
                  ellipticarum ope soluta ...
Published:     Berolini, typis Caroli Schultze [1865]
Description:   36, [2] p., 1 l. 21 cm.
LC Call No.:   QA343.B6
Subjects:      Elliptic functions.
Control No.:   6799659

Author:        Bobek, Karl Joseph, 1855-1899. [from old
                  catalog]
Title:         Einleitung in die theorie der elliptischen
                  funktionen,
Published:     Leipzig, B. G. Teubner, 1884.
Description:   xii, 274 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA343.B68
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Control No.:   8236461

Author:        Boehm, Karl, 1873- [from old catalog]
Title:         Elliptische funktionen
Published:     Leipzig, G. J. Göschen, 1908-10.
Description:   2 v. diagrs. 20 cm.
LC Call No.:   QA343.B7
               Microfilm 66520 QA
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Control No.:   8217708

Author:        Brandenberger, Conrad. [from old catalog]
Title:         Anwendung der elliptischen funktionen auf durch
                  algebraische funktionen vermittelte konforme abbildungen ...
Published:     Zurich, Druck von Zürcher & Furrer, 1899.
Description:   p. cm.
LC Call No.:   QA343.B81
Subjects:      Elliptic functions.
Control No.:   7732654

Author:        Briot, M. (Charles), 1817-1882.
Title:         Théorie des fonctions doublement périodiques
                  et, en particulier, des fonctions elliptiques / par M. Briot
                  et M. Bouquet.
Published:     Paris : Mallet-Bachelier, 1859.
Description:   xxiv, 342 p. ; 23 cm.
LC Call No.:   QA343.B83
Dewey No.:     517.36
Subjects:      Elliptic functions.
Other authors: Bouquet, M. (Jean Claude), 1819-1885.
Control No.:   7818477

Author:        Briot, M. (Charles), 1817-1882.
Title:         Théorie des fonctions elliptiques, par mm. Briot
                  et Bouquet ...
Edition:       2. éd.
Published:     Paris, Gauthier-Villars, 1875.
Description:   2 p. l., iv, 700 p. diagrs. 27 x 22 cm.
LC Call No.:   QA343.B84
Subjects:      Elliptic functions.
Other authors: Bouquet, M. (Jean Claude), 1819-1885, joint
                  author.
Control No.:   7268862

Author:        Broch, O[le] J[akob], 1818-1889. [from old
                  catalog]
Title:         Traité élémentaire des fonctions elliptiques,
Published:     Christiania, P. T. Malling, 1867.
Description:   vii, [1] p., 1 l., 281 p. 24 cm.
LC Call No.:   QA343.B86
Subjects:      Elliptic functions.
Control No.:   9137933

Author:        Cayley, Arthur, 1821-1895.
Title:         An elementary treatise on elliptic functions. By
                  Arthur Cayley ...
Published:     Cambridge [Eng.] Deighton, Bell and Co.; London,
                  Bell and Sons, 1876.
Description:   x, [1], 384 p. diagrs. 23 cm.
LC Call No.:   QA343.C3
Dewey No.:     517.36
Subjects:      Elliptic functions.
Control No.:   7369720

Author:        Byrd, Paul F. [from old catalog]
Title:         Handbook of elliptic integrals for engineers and
                  physicists,
Published:     Berlin, Springer; New York, Lange, Maxwell &
                  Springer, 1954.
Description:   xii, 355 p. 24 cm.
LC Call No.:   QA343.B95 1954
Subjects:      Elliptic functions.
Other authors: Friedman, Morris D., [from old catalog] joint
                  author.
Series Entry:  Die Grundlehren der mathematischen Wissenschaften
                  in Einzeldarstellungen, Bd. 67. [from old catalog]
Control No.:   6520274

Author:        Cayley, Arthur, 1821-1895.
Title:         An elementary treatise on elliptic functions, by
                  the late Arthur Cayley ...
Edition:       2d ed.
Published:     London, G. Bell and sons; [etc., etc.] 1895.
Description:   xii, p., 1 l., 386 p. diagrs. 22 cm.
LC Call No.:   QA343.C3 1895
Dewey No.:     517.36
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Control No.:   2636246

Author:        Curtiss-Wright Corporation. Research Division.
                  [from old catalog]
Title:         Tables of the incomplete elliptic integrals of
                  the first and third kind. [Prepared by F.A. Paxton and J.E.
                  Rollin].
Published:     Quehanna, Pa., 1959.
Description:   436 p. 29 cm.
LC Call No.:   QA343.C8
Subjects:      Elliptic functions.
Other authors: Paxton, F. A. [from old catalog]
               Rollin, J. E. [from old catalog]
Control No.:   13167721

Author:        Dini, Ulisse, 1845-1918.
Title:         Teoria delle funzioni ellittiche.
Published:     Livorno, Autografia A. Fattalini [1893]
Description:   528, [2] p. diagrs. 23 cm.
LC Call No.:   QA343.D5
Subjects:      Elliptic functions.
Other authors: Bianchi, Luigi, 1856- [from old catalog]
Control No.:   8691254

Author:        Donner, Anders [Severin] 1854- [from old
                  catalog]
Title:         Om uttrycken för entydiga elliptiska funktioner
                  ...
Published:     Helsingfors, J. C. Frenckell & son, 1879.
Description:   2 p.l., 83 p. fold. tab. 26 cm.
LC Call No.:   QA343.D68
Subjects:      Elliptic functions.
Control No.:   10074752

Author:        Dorn, Friedrich, Ernst, 1848- [from old catalog]
Title:         Ueber eine transformation zweiter ordnung, welche
                  das elliptische integral mit imaginärem modul auf ein
                  ultraelliptisches mit reellen moduln reducirt ...
Published:     Königsberg, Druck von E. J. Dalkowski [1871]
Description:   2 p.l., 33, [2] p. incl. tab. 29 cm.
LC Call No.:   QA343.D72
Subjects:      Elliptic functions.
Control No.:   8669684

Author:        Durège, Heinrich, 1821-1893.
Title:         Theorie der elliptischen funktionen. Mit 36
                  figuren im text.
Edition:       In 5. aufl. neu bearb. von Ludwig Maurer.
Published:     Leipzig, B. G. Teubner, 1908.
Description:   viii, 436 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA343.D8 1908
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Other authors: Maurer, Ludwig, 1859-1927.
Control No.:   8689686

Author:        Durège, Heinrich, 1821-1893. [from old catalog]
Title:         Theorie der elliptischen Functionen.
Edition:       4. Aufl.
Published:     Leipzig, B. G. Teubner, 1887.
Description:   393 p. illus. 23 cm.
LC Call No.:   QA343.D8 1887
Subjects:      Elliptic functions.
Control No.:   7922853

Author:        Enneper, Alfred, 1830-1885.
Title:         Elliptische functionen. Theorie und geschichte.
                  Akademische vorträge von Alfred Enneper.
Edition:       2. aufl., neu bearb. und hrsg. von Dr. Felix
                  Müller ...
Published:     Halle a. S., L. Nebert, 1890.
Description:   xix, [1], 598 p. 24 cm.
LC Call No.:   QA343.E6
Notes:         "Verzeichnis der erwähnten zeitschriften": p.
                  [596]-597.
Subjects:      Elliptic functions.
Other authors: Müller, Felix, 1843-1928.
Control No.:   744771

Author:        Fiedler, Ernst Wilhelm, 1861- [from old catalog]
Title:         Über eine besondere classe irrationaler
                  modulargleichungen der elliptschen functionen ...
Published:     Zürich, Druck von Zürcher & Furrer, 1885.
Description:   iv, 104 p. diagr. 20 cm.
LC Call No.:   QA343.F45
Subjects:      Modular functions.
Control No.:   7732811

Author:        Fricke, Robert, 1861-1930.
Title:         Die elliptischen funktionen und ihre anwendungen,
                  von dr. Robert Fricke ...
Published:     Leipzig, Berlin, B.G. Teubner, 1916-
Description:   v. <1   > illus., diagrs. 24 cm.
LC Call No.:   QA343.F85
Subjects:      Elliptic functions.
Control No.:   4053197

Author:        Fricke, Robert, 1861- [from old catalog]
Title:         Ueber systeme elliptischer modulfunctionen von
                  niederer stufenzahl ...
Published:     Braunschweig, Druck von F. Vieweg und sohn,
                  1886.
Description:   vi, 89, [1] p. 22 cm.
LC Call No.:   QA343.F89
Subjects:      Modular functions.
Control No.:   7263126

Author:        Friedrich, Georg, 1862- [from old catalog]
Title:         Die modulargleichungen der Galois'schen moduln
                  der 2. bis 5. stufe ...
Published:     Griefswald, Druck von F. W. Kunike, 1886.
Description:   4 p.l., 71, [1] p. fold. pl. 21 cm.
LC Call No.:   QA343.F92
Subjects:      Modular functions.
Control No.:   5858702

Author:        Greenhill, G. (George), Sir, 1847-1927.
Title:         The applications of elliptic functions, by Alfred
                  George Greenhill ...
Published:     London, New York, Macmillan and co., 1892.
Description:   xi, [1], 357 p. diagrs. 23 cm.
LC Call No.:   QA343.G7
               Microfilm 15982 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Elliptic functions.
Control No.:   3580206

Author:        Halphen, Georges Henri, 1844-1889. [from old
                  catalog]
Title:         Traité des fonctions elliptiques et de leurs
                  applications.
Published:     Paris, Gauthier-Villars, 1886-91.
Description:   3 v. diagrs. 25 cm.
LC Call No.:   QA343.H2
               Microfilm 73874 QA
Subjects:      Elliptic functions.
Control No.:   10111064

Author:        Hancock, Harris, 1867-1944.
Title:         Elliptic integrals.
Published:     New York, Dover Publications [1958, c1917]
Description:   104 p. illus. 21 cm.
LC Call No.:   QA343.H225 1958
Dewey No.:     517.36
Notes:         "Unabriged and unaltered republication of the
                  first edition."
Subjects:      Elliptic functions.
Control No.:   9349352

Author:        Hancock, Harris, 1867-1944.
Title:         Lectures on the theory of elliptic functions:
                  analysis.
Published:     New York, Dover Publications [1958]
Description:   498 p. 22 cm.
LC Call No.:   QA343.H23 1958
Dewey No.:     517.36
Notes:         "Originally appeared under the title, Lectures on
                  the theory of elliptic functions, volume I, Analysis. Volumes
                  II and III were never published."
Subjects:      Elliptic functions.
Control No.:   4529982

Author:        Hancock, Harris, 1867-1944.
Title:         Lectures on the theory of elliptic functions, by
                  Harris Hancock ... v. 1.
Edition:       1st ed., 1st thousand.
Published:     New York, J. Wiley & sons; [etc., etc.] 1910.
Description:   xxiii, 498 p. diagrs. 24 cm.
LC Call No.:   QA343.H23
ISBN:          $5.00
Notes:         No more published.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Control No.:   745391

Author:        Hancock, Harris, 1867- [from old catalog]
Title:         Elliptic integrals,
Edition:       1st ed.
Published:     New York, John Wiley & sons, inc.; [etc., etc.]
                  1917.
Description:   104 p. diagrs 24 cm.
LC Call No.:   QA343.H225
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Control No.:   8712528

Author:        Henderson, F. M. (Francis Martin), 1921-
Title:         Elliptic functions with complex arguments.
Published:     [Ann Arbor] University of Michigan Press for
                  University of Michigan Research Institute, 1960.
Description:   v, 38 p. diagrs., tables. 29 cm.
Series:        University of Michigan Research Institute.
                  Monographs
LC Call No.:   QA343.H5
Dewey No.:     517.36
Notes:         Bibliography: p. 38.
Subjects:      Elliptic functions.
Series Entry:  Monographs (University of Michigan. Research
                  Institute)
Control No.:   1694340

Author:        Herrmann, Oskar, 1858- [from old catalog]
Title:         Geometrische untersuchungen über den verlauf der
                  elliptischen transcendenten im complexen gebiete ...
Published:     Dresden, Druck von B. G. Teubner, 1883.
Description:   36 p., 1 l. fold. pl. 23 cm.
LC Call No.:   QA343.H55
Subjects:      Elliptic functions.
Control No.:   9136320

Author:        Hoebel, Ernst.
Title:         Ueber die darstellung doppelt-periodischer
                  funktionen durch unendliche producte ...
Published:     Göttingen, Druck von E.A. Huth, 1876.
Description:   50 p. diagrs. 22 cm.
LC Call No.:   QA343.H69
Notes:         Inaug.-dis.--Göttingen.
Subjects:      Elliptic functions.
Control No.:   1217133

Author:        Hurwitz, Adolf, 1859-1919.
Title:         Grundlagen einer independenten Theorie der
                  elliptischen Modulfunctionene und Theorie der
                  Multiplicatorgleichungen erster Stufe / von Adolf Hurwitz.
Published:     Leipzig : B. G. Teubner, 1881.
Description:   72 p. ; 23 cm.
LC Call No.:   QA343.H96
Notes:         Vita.
               Thesis--Universität Leipzig.
Subjects:      Modular functions.
Control No.:   8669685

Author:        Jacobi, C. G. J. (Carl Gustav Jakob), 1804-1851.
Title:         Fundamenta nova theoriae functionum ellipticarum,
                  auctore d. Carolo Gustavo Iacobo Iacobi ...
Published:     Regiomonti, sumtibus fratrum Borntræger; [etc.,
                  etc.] 1829.
Description:   vi, 191 p. fold. tab. 26 x 21 cm.
LC Call No.:   QA343.J27
Subjects:      Elliptic functions.
Control No.:   7408115

Author:        Kiepert, Ludwig, 1846-1934.
Title:         De curvis quarum arcus integralibus ellipticis
                  primi generis exprimuntur : dissertatio inauguralis quam ...
                  rite capessendis die XVI. m. Novembris a. MDCCCLXX ...
                  publice defendet / auctor Ludovicus Kiepert ...
Published:     Berolini : Typis A.W. Schade, [1871]
Description:   [1], 28, [1] p. : ill. ; 27 x 22 cm.
LC Call No.:   QA343.K47
Notes:         Printed 1871--NUC pre-1956.
               Thesis
                  (doctoral)--Friedrich-Wilhelms-Universität Berlin, 1870.
               Vita.
               Includes bibliographical references.
Subjects:      Elliptic functions.
               Curves -- Rectification and quadrature.
Control No.:   5864456

Author:        Knoche, Georg [Adolf Wilhelm], 1863- [from old
                  catalog]
Title:         Über die aus der komplexen multiplikation der
                  elliptischen funktionen entspringenden algebraischen
                  gleichungen ...
Published:     Marburg, 1892.
Description:   3 p.l., 38, [2] p. 24 cm.
LC Call No.:   QA343.K72
Subjects:      Modular functions.
Control No.:   10074697

Author:        Koenigsberger, Leo, 1837-1921.
Title:         Vorlesungen über die theorie der elliptischen
                  functionen, nebst einer einleitung in die allgemeine
                  functionenlehre,
Published:     Leipzig, B. G. Teubner, 1874.
Description:   2 v. in 1. diagrs. 24 cm.
LC Call No.:   QA343.K8
Subjects:      Elliptic functions.
Control No.:   7301401

Author:        König, Julius, 1849-1913.
Title:         Zur Theorie der Modulargleichungen der
                  elliptischen Functionen / Julius König.
Published:     Heidelberg, 1870.
Description:   24 p. ; 23 cm.
LC Call No.:   QA343.K78
Notes:         Thesis--Heidelberg.
Subjects:      Modular functions.
Control No.:   10074696

Author:        Krause, Martin, 1851-1920.
Title:         Theorie der doppeltperiodischen Functionen einer
                  veränderlichen Grösse. Von Martin Krause.
Published:     Leipzig, B. G. Teubner, 1895-97.
Description:   2 v. 25 cm.
LC Call No.:   QA343.K88
Subjects:      Elliptic functions.
Control No.:   6456680

Author:        Krause, Martin, 1851-1920.
Title:         Theorie der elliptischen Funktionen, von Martin
                  Krause. Unter Mitwirkung von Emil Naetsch.
Published:     Leipzig, Berlin, B. G. Teubner, 1912.
Description:   xi, 186 p. diagrs. 21 cm.
Series:        Mathematisch-physikalische Schriften für
                  Ingenieure und Studierende, 13
LC Call No.:   QA343.K883
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
Other authors: Naetsch, Emil, 1869-
Control No.:   9166320

Author:        Krause, Martin, 1851-1920.
Title:         Zur transformation der modulargleichungen der
                  elliptischen functionen, von Martin Krause ...
Published:     Heidelberg, 1873.
Description:   26 p. 24 cm.
LC Call No.:   QA343.K888
Notes:         Inaug.-diss.--Heidelberg.
Subjects:      Elliptic functions.
Control No.:   1689248

Author:        Krause, Martin, 1851-1920. [from old catalog]
Title:         Über die discriminante der modulargleichungen
                  der elliptischen functionen ...
Published:     Leipzig, Druck von B. G. Teubner, 1875.
Description:   [539]-554 p. 23 cm.
LC Call No.:   QA343.K886
Subjects:      Elliptic functions.
Control No.:   9137874

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Traité des fonctions elliptiques et des
                  intégrales eulériennes, avec des tables pour en faciliter
                  le calcul numérique; par A.M. Legendre ...
Published:     Paris, Imprimerie de Huzard-Courcier, 1825-28.
Description:   3 v. tables, diagrs. on 4 fold. pl. 27 cm.
LC Call No.:   QA343.L51
Notes:         t. 1. (1825) Théorie des fonctions elliptiques
                  et son application à différens problèmes de géométrie et
                  de mécanique.--t. 2. (1826) Méthodes pour construire les
                  tables elliptiques. Recueil des tables elliptiques. Traité
                  des intégrales eulériennes. Appendice.--t. 3. (1828)
                  Supplémens.
Subjects:      Elliptic functions.
               Gamma functions.
Control No.:   2633994

Author:        Lévy, Lucien, b. 1853.
Title:         Précis élémentaire de la théorie des
                  fonctions elliptique avec les tables numeriques et
                  applications, par Lucien Levy.
Published:     Paris, Gauthier-Villars et fils, 1898.
Description:   xi, 237 p. incl. tables, diagrs. 25 cm.
LC Call No.:   QA343.L6
Subjects:      Elliptic functions.
Control No.:   8704554

Author:        Lühn, Otto. [from old catalog]
Title:         Über funktionen zweier variabeln, welche durch
                  hilfe der elliptischen funktionen dargestellt werden können
                  ...
Published:     Heidelberg, C. Winter, 1881.
Description:   30 p. 24 cm.
LC Call No.:   QA343.L94
Subjects:      Elliptic functions.
Control No.:   9606383

Author:        Manning, H. P. [from old catalog]
Title:         Developments obtained by Cousby's theorem.
Published:     [n.p.] 1891.
Description:   1 v. cm.
LC Call No.:   QA343.M28
Control No.:   7665882

Author:        Miller, Bessie Irving, 1884- [from old catalog]
Title:         A new canonical form of the elliptic integral
                  ...
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1916.
Description:   1 p.l., 259-283, [1] p. 28 cm.
LC Call No.:   QA343.M6
Subjects:      Elliptic functions.
Control No.:   7774210

Author:        Miller, John Anthony, 1859-1946.
Title:         Concerning certain elliptic modular functions of
                  square rank ...
Published:     [Baltimore, The Johns Hopkins press, 1905]
Description:   2 p.l., [47]-68 p. 31 x 25 cm.
LC Call No.:   QA343.M64
Notes:         Thesis (PH. D.)--University of Chicago.
               Autobiography.
               "Reprinted from the American journal of
                  mathematics, vol. 27, no. 1."
Subjects:      Modular functions.
Control No.:   2161311

Author:        Mittag-Leffler, Magnus Gustaf, 1846-1927.
Title:         En metod att komma i analytisk besittning af de
                  elliptiska funktionerna.
Published:     Helsingfors, J. C. Frenckell & son, 1876.
Description:   2 p. l., 96 p. 21 cm.
LC Call No.:   QA343.M68
Subjects:      Elliptic functions.
Control No.:   7733243

Author:        Montessus de Ballore, Robert Fernand Bernard,
                  vicomte de, 1870-
Title:         Leçons sur les fonctions elliptiques en vue de
                  leurs applications, par R. de Montessus de Ballore.  Cours
                  libre professé à la Faculté des sciences de Paris.
Published:     Paris, Gauthier-Villars et cie, 1917.
Description:   x, 267, [1] p. diagrs. 26 cm.
LC Call No.:   QA343.M7
Subjects:      Elliptic functions.
Control No.:   9655742

Author:        Müller, Felix, 1843-
Title:         De transformatione functionum ellipticarum /
                  Felix Müller.
Published:     Berolini : typis A. W. Schade, [1867]
Description:   25, [1] p. ; 27 cm.
LC Call No.:   QA343.M94
Notes:         Vita.
               Inaug.-diss.--Berlin.
Subjects:      Elliptic functions.
Control No.:   7732794

Author:        Naval Ordnance Test Station (Inyokern, Calif.).
                  Research Dept.
Title:         A table of the incomplete elliptic integral of
                  the third kind, by R.G. Selfridge and J.E. Maxfield.
Published:     New York, Dover Publications, 1958.
Description:   805 p. 22 cm.
LC Call No.:   QA343.U6
Dewey No.:     517.36
Notes:         "Released within the Department of Defense as
                  NAVORD report 5643, NOTS 1870."
Subjects:      Elliptic functions.
Other authors: Selfridge, R. G. (Ralph Gordon), 1927-
               Maxfield, John E. (John Edward), 1927-
Control No.:   2638589

Author:        Nimsch, Paul 1860- [from old catalog]
Title:         Über die perioden der elliptischen integrale I.
                  und II. gattung als functionen der rationalen invarianten...
Published:     Leipzig, Druck von C. G. Naumann, 1886.
Description:   1 p.l., 47, [1] p. diagrs. 27 cm.
LC Call No.:   QA343.N71
Subjects:      Elliptic functions.
Control No.:   9604802

Author:        Riemann, Bernhard, 1826-1866.
Title:         Elliptische functionen. Vorlesungen von Bernhard
                  Riemann. Mit zusätzen herausgegeben von Hermann Stahl ...
Published:     Leipzig, B.G. Teubner, 1899.
Description:   viii, 144 p. diagrs. 25 cm.
LC Call No.:   QA343.R5
Subjects:      Elliptic functions.
Other authors: Stahl, Hermann, 1843-1908, ed.
Control No.:   3109251

Author:        Tannery, Jules, 1848-1910.
Title:         Élélments de la théorie des fonctions
                  elliptiques.
Published:     Paris, Gauthier-Villars et fils, 1893-1902.
Description:   4 v. in 2. diagrs. 24 cm.
LC Call No.:   QA343.T16
Subjects:      Elliptic functions.
Control No.:   10157455

Author:        Tannery, Jules, 1848-1910.
Title:         Éléments de la théorie des fonctions
                  elliptiques. Par Jules Tannery ... [et] Jules Molk ...
Published:     Paris, Gauthier-Villars et fils, 1893-1902.
Description:   4 v. in 2. diagrs. 26 cm.
LC Call No.:   QA343.T16
Notes:         "Lettre de Ch. Hermite à M. Jules Tannery": v.
                  4, p. 282-303.
               t. I. Introduction. Calcul différential (1.
                  ptie) 1893.---t. II. Calcul différentiel (2. ptie.)
                  1896.--t. III. Calcul intégral (1. ptie.) Théorèmes
                  généraux. Inversion. 1898.--t. IV. Calcul intégral (2.
                  ptie.) Applications. 1902.
Subjects:      Elliptic functions.
Other authors: Molk, Jules, 1857-1914, joint author.
               Hermite, Charles, 1822-1901.
Control No.:   4525310

Author:        Tikhomandriëtìskiæi, Matvei Aleksandrovich,
                  1844-1921. [from old catalog]
Title:         Teoriëiìa ellipticheskikh integralov i
                  elipticheskikh funkëtìsiæi.
Published:     [s.l. : s.n.], 1895.
Description:   xix, xi, 449 p. ; 26 cm.
LC Call No.:   QA343.T54
Notes:         Romanized.
Subjects:      Elliptic functions.
Control No.:   6715561

Author:        Tropfke, Johannes, b. 1866.
Title:         Zur darstellung des elliptischen integrales
                  erster gattung.
Published:     Halle a. S., Gebauer-Schwetschke'sche
                  buchdruckerei, 1889.
Description:   2 p. l., 49, [1] p., 1 l. diagr. 24 cm.
LC Call No.:   QA343.T85
Notes:         Inaug.-dis.--Halle.
               Vita.
Subjects:      Elliptic functions.
Control No.:   10075218

Author:        Vivanti, G. (Giulio), 1859-
Title:         Elementi della teoria delle funzioni poliedriche
                  e modulari / di Giulio Vivanti.
Published:     Milano : U. Hoepli, 1906.
Description:   viii p., 437 p. : ill. ; 16 cm.
Series:        Manuali Hoepli. Serie scientifica ; 366-367
LC Call No.:   QA343.V85
Subjects:      Modular functions.
               Polyhedral functions.
               Group theory.
Control No.:   10084090

Author:        Weber, Heinrich, 1842-1913.
Title:         Elliptische functionen und algebraische zahlen.
                  Academische vorlesungen von H. Weber ...
Published:     Braunschweig, F. Vieweg und sohn, 1891.
Description:   xiii, [1], 504 p. 23 cm.
LC Call No.:   QA343.W37
Notes:         2d ed. pub. as v. 3 of the author's Lehrbuch der
                  algebra. 2 aufl. 1908.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Elliptic functions.
               Number theory.
Control No.:   4052147

Author:        Weierstrass, Karl, 1815-1897.
Title:         Formeln und Lehrsätze zum Gebrauche der
                  elliptischen Functionen, nach Vorlesungen und Aufzeichnungen
                  des K. Weierstrass / bearb. und Hrsg. von H.A. Schwarz.
Edition:       2. Ausg.
Published:     Berlin : J. Springer, 1893-
Description:   v. <1-> ; 29 cm.
LC Call No.:   QA343.W4414
Notes:         Bound with the French translation: Formules et
                  propositions pour l'emploi des fonctions elliptiques. Paris,
                  1894.
Subjects:      Elliptic functions.
Other authors: Schwarz, Hermann Amandus, 1843-1921.
Other titles:  Formeln und Lehrsätze zum Gebrauche der
                  elliptischen Functionen ...
Control No.:   2229164

Author:        Weierstrass, Karl, 1815-1897.
Title:         Formules et propositions pour l'emploi des
                  fonctions elliptiques, d'après des leçons et des notes
                  manuscrites de K. Weierstrass / rédigées et publiées par
                  H. A. Schwarz ; traduit de l'allemand par Henri Padé.
Published:     Paris : Gauthier-Villars, 1894-
Description:   v.    ; 29 cm.
LC Call No.:   QA343.W4414
Dewey No.:     515/.983
Notes:         Bound with the German original: Formeln und
                  Lehrsätze zum Gebrauche der elliptischen Functionen. Berlin,
                  1893.
Subjects:      Elliptic functions.
Other authors: Schwarz, Hermann Amandus, 1843-1921.
Other titles:  Formules et propositions pour l'emploi des
                  fonctions elliptiques ...
Control No.:   2697538

Author:        Woods, Roscoe, 1889-
Title:         The elliptic modular functions associated with
                  the elliptic norm curve Ep7s, by Roscoe Woods ...
Published:     [Lancaster, Pa. ; New York, 1922]
Description:   2 p. l., 179-197, [1] p. 28 cm. in cover 30 cm.
LC Call No.:   QA343.W6
Notes:         Thesis (Ph. D.)--University of Illinois, 1920.
               Vita.
               "Reprinted from the Transactions of the American
                  Mathematica Society, vol. 23, no. 2, March, 1922."
Subjects:      Modular functions.
Control No.:   8260816

Author:        Bruns, Heinrich, 1848- [from old catalog]
Title:         Ueber die perioden der elliptischen interale
                  erster und zweiter gattung,
Published:     Dorpat, Druck von C. Mattiesen, 1875.
Description:   2 p.l., 18 p. 32 cm.
LC Call No.:   QA344.B89
Subjects:      Elliptic functions.
Control No.:   7732797

Author:        Assadourian, Fred. [from old catalog]
Title:         Intransitive Abelian almost-translation groups of
                  almost-periodic functions
Published:     [Durham, N.C., 1941]
Description:   518-524 p. 26 cm.
LC Call No.:   QA345.A8
Subjects:      Functions, Abelian. [from old catalog]
               Harmonic analysis. [from old catalog]
               Fourier's series. [from old catalog]
Other titles:  Almost-periodic functions.
Control No.:   8789804

Author:        Baker, H. F. (Henry Frederick), 1866-1956.
Title:         Abel's theorem and the allied theory, including
                  the theory of the theta functions, by H.F. Baker ...
Published:     Cambridge, University press, 1897.
Description:   xix, [1], 684 p. 28 cm.
LC Call No.:   QA345.B2
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Functions, Abelian.
               Functions, Theta.
Control No.:   744742

Author:        Baker, H. F. (Henry Frederick), 1866-1956.
Title:         An introduction to the theory of multiply
                  periodic functions, by H.F. Baker ...
Published:     Cambridge, University press, 1907.
Description:   xv, [1], 335 p. 27 cm.
LC Call No.:   QA345.B22
Subjects:      Functions.
Control No.:   4052693

Author:        Bellman, Richard Ernest, 1920-
Title:         A brief introduction to theta functions.
Published:     New York, Holt, Rinehart and Winston [1961]
Description:   78 p. 25 cm.
Series:        Athena series; selected topics in mathematics
LC Call No.:   QA345.B4
Dewey No.:     517.36
Notes:         Includes bibliography.
Subjects:      Functions, Theta.
Control No.:   3584723

Author:        Bolza, O. (Oskar), 1857-1942.
Title:         Über die Reduction hyperelliptischer Integrale
                  erster Ordnung und erster Gattung auf elliptische,
                  Insbesondere über die Reduction durch eine Transformation
                  vierten Grades ...
Published:     Berlin, Buchdruckerei von G. Schade (O. Francke)
                  [1886]
Description:   39, [1] p. 28 cm.
LC Call No.:   QA345.B69
Notes:         Inaug.-Dis.--Göttingen.
               Vita.
Subjects:      Functions, Abelian.
               Integrals, Hyperelliptic.
Control No.:   7732861

Author:        Briot, M. (Charles), 1817-1882.
Title:         Théorie des fonctions Abéliennes, par M. Ch.
                  Briot ...
Published:     Paris, Gauthier-Villars, 1879.
Description:   xix, 181, [1] p. diagrs. 28 x 22 cm.
LC Call No.:   QA345.B82
Subjects:      Functions, Abelian.
Control No.:   273092

Author:        Clebsch, Alfred, 1833-1872.
Title:         Theorie der Abelschen functionen, von A. Clebsch
                  und P. Gordan ...
Published:     Leipzig, B.G. Teubner, 1866.
Description:   xiii, 333 p. 24 cm.
LC Call No.:   QA345.C62
Subjects:      Functions, Abelian.
               Functions, Theta.
               Transcendental functions.
Other authors: Gordan, Paul, 1837-1912, joint author.
Control No.:   3106964

Author:        Cohen, Abraham, b. 1870.
Title:         On a certain class of functions analogous to the
                  theta functions...
Published:     Baltimore, Press of the Friedenwald company,
                  1894.
Description:   31, [1] p. 26 cm.
LC Call No.:   QA345.C67
Notes:         Biographical sketch.
               Thesis (Ph. D.)--Johns Hopkins university, 1894.
Subjects:      Functions
Control No.:   8201936

Author:        Cotty, Gaston, 1886-
Title:         Les fonctions abéliennes et la théorie des
                  nombres / par M. Gaston Cotty.
Published:     Toulouse : E. Privat, 1912.
Description:   [3]-170 p. ; 29 cm.
Series:        Bibliothèque de la Fondation Thiers ; v. 30
LC Call No.:   QA345.C7
Subjects:      Functions, Abelian.
               Number theory.
Control No.:   8234323

Author:        Dalwigk, Friedrich von, 1864- [from old catalog]
Title:         Beiträge zur theorie der thetafunctionen von
                  mehreren variablen ...
Published:     Marburg, 1891.
Description:   43 p., [1] p. 28 cm.
LC Call No.:   QA345.D15
Subjects:      Functions, Theta. [from old catalog]
Control No.:   9606822

Author:        Dolbnëiìa Ivan Petrovich, 1853-1912. [from old
                  catalog]
Title:         Izslëiìedovan¯ie po teorii Abelevykh integralov.
Published:     1896.
Description:   ii, 155 p. diagrs. 25 cm.
LC Call No.:   QA345.D6
Notes:         Romanized.
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   9783870

Author:        Epstein, P. (Paul), b. 1871.
Title:         Zur Lehre von den hyperelliptischen Integralen /
                  von Paul Epstein.
Published:     Stockholm : Gedruckt in der Central-druckerei,
                  1895.
Description:   58 p. ; 29 cm.
LC Call No.:   QA345.E64
Notes:         Lebenslauf.
               Thesis--Strassburg.
Subjects:      Functions, Abelian.
Control No.:   6328579

Author:        Fuchs, Richard, b. 1873.
Title:         Ueber die Periodicitätsmoduln der
                  hyperelliptischen Integrale als Functionen eines
                  Verzweigungspunktes ...
Published:     Berlin, Druck von G. Reimer, 1897.
Description:   2 p. l., 24 p., 2 l. 28 cm.
Series:        [Berlin. Universität. Dissertationen, v. 26, no.
                  12]
LC Call No.:   QA345.P95
Notes:         Inaug.-diss.--Berlin.
               Vita.
               "Sonderabdruck aus bd. 119 des Journals für die
                  reine und angewandte mathematik."
Subjects:      Functions, Abelian.
Control No.:   6794747

Author:        Gernet, Marie, 1865-
Title:         Über reduktion hyperelliptischer integrale ...
Published:     Karlsruhe, Druck von F. Gutsch, 1895.
Description:   40 p. 1 l. 22 cm.
LC Call No.:   QA345.G37
Notes:         Inaug.-dis.--Heidelberg.
               Lebenslauf.
Subjects:      Functions, Abelian.
Control No.:   7264717

Author:        Gillespie, William, b. 1870.
Title:         On the reduction of the hyperelliptic integrals
                  (p=3) to elliptic integrals by transformation of the second
                  and third degrees ...
Published:     Göttingen, Printed by L. Hofer, 1900.
Description:   40 p., 1 l. diagr. 24 cm.
LC Call No.:   QA345.G43
Notes:         Thesis (Ph. D.)--University of Chicago, 1900.
               Biography.
Subjects:      Integrals, Hyperelliptic.
Control No.:   2634045

Author:        Göpel, Adolf, 1812-1847.
Title:         Entwurf einer theorie der Abel'schen
                  transcendenten erster ordnung, von dr. A. Göpel (1847.) 
                  Hrsg. von H. Weber.  Aus dem lateinischen übersetzt von A.
                  Witting.
Published:     Leipzig, W. Engelmann, 1895.
Description:   60 p. 20 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften,
                  nr. 67
LC Call No.:   QA345.G46
Notes:         First published in Crelle's Journal, bd. 35,
                  1847, under title: Theoriae transcendentium Abelianarum primi
                  ordinis adumbratio levis.
               Notes on the life and work of the author by C. G.
                  J. Jacobi and A. L. Crelle: p. [52]-58.
Subjects:      Functions, Abelian.
Other authors: Witting, A. (Alexander), 1861- tr.
               Weber, Heinrich, 1842-1913, ed.
Control No.:   5856851

Author:        Gordan, Paul [Albert], 1837- [from old catalog]
Title:         Ueber die transformation der Theta funktionen
                  ...
Published:     Giessen, Druck von W. Keller, 1863.
Description:   18 p. 27 cm.
LC Call No.:   QA345.G6
Subjects:      Functions, Theta. [from old catalog]
Control No.:   9137931

Author:        Hager, Georg. [from old catalog]
Title:         Ueber die lineare transformation der
                  thetafunctionen ...
Published:     Göttingen, Druck der Dieterichschen
                  univ.-buchdruckerei W. F. Kaestner, 1877.
Description:   43 p. 21 cm.
LC Call No.:   QA345.H1
Subjects:      Functions, Theta. [from old catalog]
Control No.:   9137860

Author:        Hancock, Harris, 1867-1944.
Title:         Eine Form des Additionstheorems für
                  hyperelliptische Functionen erster Ordnung.
Published:     Berlin, Druck von G. Bernstein [1894]
Description:   41, [3] p. 28 cm.
LC Call No.:   QA345.H19
Notes:         Inaug.-diss.--Berlin.
               Vita.
Subjects:      Functions, Abelian.
Control No.:   8670071

Author:        Hancock, Harris, 1867- [from old catalog]
Title:         The historical development of Abelian functions
                  up to the time of Riemann.
Published:     [London, Printed by Spottiswoode and co., 1897]
Description:   p. [245]-286. 22 cm.
LC Call No.:   QA345.H2
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   8191663

Author:        Hauser, Wilhelm, 1883-
Title:         Über resultanten- und discriminantenbildung in
                  der theorie der elliptischen thetafunktionen ...
Published:     Borna-Leipzig, Buchdr. R. Noske, 1907.
Description:   40 p., 1 l. 27 cm.
LC Call No.:   QA345.H3
Notes:         Inaug.-diss.--Erlangen.
               Lebenslauf.
Subjects:      Functions, Theta.
Control No.:   9155764

Author:        Henoch, Max, b. 1841.
Title:         De Abelianarum functionum periodis : dissertatio
                  inauguralis ... / auctor Maximilianus Henoch ...
Published:     Berolini : Typis A.W. Schade, [1867]
Description:   [3], 20, [1] p. ; 27 x 21 cm.
LC Call No.:   QA345.H37
Notes:         Thesis
                  (doctoral)--Friedrich-Wilhelms-Universität Berlin, 1867.
               Vita.
Subjects:      Functions, Abelian.
Control No.:   10083096

Author:        Hensel, Kurt, 1861-1941.
Title:         Theorie der algebraischen funktionen einer
                  variabeln und ihre anwendung auf algebraische kurven und
                  Abelsche integrale, von dr. Kurt Hensel ... und dr. Georg
                  Landsberg ...
Published:     Leipzig, B.G. Teubner, 1902.
Description:   xvi, 707, [1] p. diagrs. 25 cm.
LC Call No.:   QA345.H4
Subjects:      Algebraic functions.
Other authors: Landsberg, Georg, b. 1865, joint author.
Control No.:   4525281

Author:        Hettner, Georg, 1854- [from old catalog]
Title:         Ueber die reduction der integrale einer
                  besonderen classe von algebraischen differentialen auf die
                  hyperelliptischen integrale ...
Published:     Berlin, Buchdruckerei von G. Schade (O. Francke)
                  [1877]
Description:   1 p.l., 36, [2] p. 27 x 21 cm.
LC Call No.:   QA345.H59
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   9142923

Author:        Hutchinson, John Irwin, 1867-1935.
Title:         On the reduction of hyperelliptic functions (p=2)
                  to elliptic functions, by a transformation of the second
                  degree ...
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buchdruckerei (W.F. Kaestner) 1897.
Description:   1 p.l., 40 p., 1 l. diagrs. 25 cm.
LC Call No.:   QA345.H96
Notes:         Vita.
               Thesis (PH. D.)--University of Chicago.
Subjects:      Integrals, Hyperelliptic.
Control No.:   3579430

Author:        Jacobi, C. G. J. (Carl Gustav Jakob), 1804-1851.
Title:         Ueber die vierfach periodischen functionen zweier
                  variabeln, auf die sich die theorie der Abel'schen
                  transcendenten stützt. Von C. G. J. Jacobi ... Hrsg. von H.
                  Weber.  Aus dem lateinischen übers. von A. Witting.
Published:     Leipzig, W. Engelmann, 1895.
Description:   40 p. 20 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften,
                  nr. 64
LC Call No.:   QA345.J16
Notes:         First published in Crelle's Journal, 13. bd.,
                  1834.
Subjects:      Functions, Abelian.
Other authors: Weber, Heinrich, 1842-1913, ed.
               Witting, A. (Alexander), 1861- tr.
Control No.:   6324740

Author:        Kadik, Peter. [from old catalog]
Title:         Theorie der sechsstelligen characteristiken.
Published:     Dorpat, Schnakenburg's buchdruckerei, 1885.
Description:   61 p., 1 l. 3 fold. tab. 22 cm.
LC Call No.:   QA345.K13
Subjects:      Functions, Theta. [from old catalog]
Control No.:   9137908

Author:        Koenigsberger, Leo, 1837-1921. [from old
                  catalog]
Title:         Beweis von der unmöglichkeit der existenz eines
                  anderen functionaltheorems als des Abel'schen.
Published:     Berlin, Druck von G. Reimer, 1886.
Description:   1 p. l., 88 p. 31 x 24 cm.
LC Call No.:   QA345.K6
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   6456722

Author:        Kossak, Ernst.
Title:         Das additionstheorem der ultra-elliptischen
                  functionen erster ordnung ... von Ernst Kossak.
Published:     Berlin, A.W. Schade's (L. Schade) buchdruckerei,
                  1871.
Description:   1 p.l., 20 p. 28 x 22 cm.
LC Call No.:   QA345.K86
Notes:         Inaug.-diss.--Göttingen.
Subjects:      Integrals, Hyperelliptic.
Control No.:   272657

Author:        Krause, Martin, 1851-1920. [from old catalog]
Title:         Die transformation der hyperelliptischen
                  funktionen, erster ordnung.
Published:     Leipzig, B. G. Teubner, 1886.
Description:   vii, 276 p. 25 cm.
LC Call No.:   QA345.K89
Subjects:      Integrals, Hyperelliptic.
Control No.:   10209394

Author:        Krazer, Adolf, 1858-1926.
Title:         Lehrbuch der thetafunktionen, von dr. Adolf
                  Krazer ... Mit 10 textfiguren.
Published:     Leipzig, B.G. Teubner, 1903.
Description:   xxiv, 509 p. 24 cm.
Series:        Sammlung von lehrbüchern auf dem gebiete der
                  mathematischen wissenschaften mit einschluss ihrer
                  anwendungen, bd. XII
LC Call No.:   QA345.K91 1903
Subjects:      Functions, Theta.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit Einschluss
                  ihrer Anwendungen ; Bd. XII.
Control No.:   3106794

Author:        Krazer, Adolf, 1858-1926.
Title:         Theorie der zweifach unendlichen thetareihen auf
                  grund der Riemann'schen thetaformel.
Published:     Leipzig, Druck von B. G. Teubner, 1881.
Description:   iv p., 1 l., 36 p., 1 l. incl. tables. 29 cm.
LC Call No.:   QA345.K93
Subjects:      Functions, Theta. [from old catalog]
Control No.:   6326561

Author:        Krazer, Adolf, 1858-1926.
Title:         Über thetafunctionen, deren charakteristiken aus
                  dritteln ganzer zahlen gebildet sind ...
Published:     Leipzig, Druck von B. G. Teubner, 1883.
Description:   36 p. 23 cm.
LC Call No.:   QA345.K95
Subjects:      Functions, Theta. [from old catalog]
Control No.:   9141569

Author:        Landfriedt, E.
Title:         Theorie der algebraischen funktionen und ihrer
                  integrale, von E. Landfriedt ... Mit 36 figuren.
Published:     Leipzig, G.J. Göschen, 1902.
Description:   IV, 294 p. diagr. 20 cm.
Series:        Sammlung Schubert, XXXI
LC Call No.:   QA345.L25
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Functions, Abelian.
Series Entry:  Sammlung Schubert ; 31.
Control No.:   3579288
Access:        

Author:        Landfriedt, E.
Title:         Thetafunktionen und hyperelliptische Funktionen /
                  von E. Landfriedt.
Published:     Leipzig : G. J. Göschen, 1902.
Description:   iv, 155, [1] p. : ill. ; 20 cm.
Series:        Sammlung Schubert ; 46
LC Call No.:   QA345.L27
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Functions, Theta.
               Functions, Abelian.
Control No.:   9133689

Author:        Landsberg, Georg, 1865- [from old catalog]
Title:         Zur theorie der Gauss'schen summen und der
                  linearen transformation der thetafunctionen ...
Published:     Berlin, Druck von G. Reimer, 1893.
Description:   22 p. 29 cm.
LC Call No.:   QA345.L29
Subjects:      Functions, Theta. [from old catalog]
Control No.:   8201935

Author:        Lange, Gerson, 1868-
Title:         Über die linearen homogenen
                  differentialgleichungen, denen die periodicitätsmoduln
                  Abelscher integrale genügen für den fall, dass die
                  irrationalität dritten grades ist ...
Published:     Halle a.S., Hofbuchdruckerei von C.A. Kaemmerer &
                  Co., 1891.
Description:   45, [1] p. 23 cm.
LC Call No.:   QA345.L32
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Functions, Abelian.
Control No.:   8669632

Author:        Lindemann, Ferdinand, 1852- [from old catalog]
Title:         Untersuchungen über den Riemann-Roch'schen satz
                  ...
Published:     Leipzig, Druck von B. G. Teubner, 1879.
Description:   1 p.l., 40 p. 23 cm.
LC Call No.:   QA345.L74
Subjects:      Functions. Abelian. [from old catalog]
Control No.:   7268441

Author:        Ludwig, Bernhard von, 1864-
Title:         Ueber die nothwendigkeit der beschränkung des
                  Jacobi'schen umkehrproblems auf Abel'sche integrale erster
                  gattung ...
Published:     Halle a. S., Hofbuchdruckerei von C.A. Kaemmerer
                  & Co., 1900.
Description:   [3]-94, [2] p. 22 cm.
LC Call No.:   QA345.L94
Notes:         Inaug.-dis.--Halle.
               Vita.
Subjects:      Functions, Abelian.
Control No.:   9137875

Author:        Meyer, Johann Theodor, 1845- [from old catalog]
Title:         De transformatione functionum ultraellipticarum
                  ...
Published:     Regimonti Pr., typis academicis Dalkowskianis
                  [1866?]
Description:   27, [1] p. 27 cm.
LC Call No.:   QA345.M57
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   6796781

Author:        Milewski, Ludwig, 1851- [from old catalog]
Title:         De Abelianarum functionum periodis per
                  aequationes differentiales definiendis ...
Published:     Berolini, typis expressit P. Stankiewicz [1876]
Description:   2 p. l., 93, [3] p. 26 cm.
LC Call No.:   QA345.M6
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   7264703

Author:        Möller, Ferdinand. [from old catalog]
Title:         Zur transformation der thetafunctionen ...
Published:     Griefswald, Druck von F. Kunike, 1884.
Description:   2 p.l., 59 p. 22 cm.
LC Call No.:   QA345.M69
Subjects:      Functions, Theta. [from old catalog]
Control No.:   9612288

Author:        Neumann, Carl, 1832-1925.
Title:         Vorlesungen über Riemann's theorie der
                  Abel'schen integrale, von Dr. C. Neumann ...
Edition:       2. vollständig umgearb. und wesentlich verm.
                  aufl. Mit einer lithographirten tafel und in den text
                  gedruckten figuren.
Published:     Leipzig, B.G. Teubner, 1884.
Description:   xiv, 472 p. 1 pl., diagr. 25 cm.
LC Call No.:   QA345.N49
Notes:         First edition, 1865.
Subjects:      Functions, Abelian.
               Riemann surfaces.
Control No.:   3106750

Author:        Nölke, Friedrich Gerhard Konrad, 1877-
Title:         Übersicht über die Theorie der Abelschen
                  Funktionen zweier Variabeln ...
Published:     Marburg, 1903.
Description:   30 p., 1 L. 25 cm.
LC Call No.:   QA345.N76
Notes:         Lebenslauf.
               Inaug.-diss.--Marburg.
Subjects:      Functions, Abelian
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.14.
Control No.:   9139318

Author:        Osgood, William F. (William Fogg), 1864-1943.
Title:         Zur theorie der zum algebraischen gebilde ym=R(X)
                  gehöngen Abelschen functionen ...
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buchdruckerei (W. Fr. Kästner) 1890.
Description:   61 p. 22 cm.
LC Call No.:   QA345.O82
Subjects:      Functions, Abelian.
Control No.:   10074695

Author:        Park, Russell Smith, 1898- [from old catalog]
Title:         On certain identities in theta functions ...
Published:     [Baltimore, 1931]
Description:   1 p.l., p. 855-863. 25 cm.
LC Call No.:   QA345.P3 1930
Subjects:      Functions, Theta. [from old catalog]
Other titles:  Identities in theta functions.
Control No.:   6429800

Author:        Pauls, Otto, 1857- [from old catalog]
Title:         Ueber die beziehung des Riemann'schen integrals
                  zweiter gattung zu den periodicitätsmoduln der function R.
                  ([Omikron]**[Epsilon]) ...
Published:     Strassburg, Buchdruckerei R. Schultz und comp.,
                  1882
Description:   30 p., 1 l. diagrs. 28 cm.
LC Call No.:   QA345.P33
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   7268924

Author:        Riemann, Bernhard, 1826-1866.
Title:         Beiträge zur Theorie der durch die Gauss'sche
                  Reihe F([alpha], [beta], [gamma], [chi]) darstellbaren
                  Functionen / von Bernhard Riemann.
Published:     Göttingen : Verlag der Dieterichschen
                  Buchhandlung, 1857.
Description:   22 p. ; 26 cm.
LC Call No.:   QA345.R54 1857
Dewey No.:     515/.55 19
Notes:         "Aus dem siebenten Bande der Abhandlungen der
                  Königlichen Gesellschaft der Wissenschaften zu Göttingen."
               With: Theorie der Abel'schen Functionen / von B.
                  Riemann. Berlin : Georg Reimer, 1857. Bound together
                  subsequent to publication.
Subjects:      Hypergeometric functions.
               Hypergeometric series.
Control No.:   3800914

Author:        Riemann, Bernhard, 1826-1866.
Title:         Theorie der Abel'schen Functionen / von B.
                  Riemann.
Published:     Berlin : Georg Reimer, 1857.
Description:   55 p. : ill. ; 26 cm.
LC Call No.:   QA345.R54 1857
Dewey No.:     515.9/83 19
Notes:         "Abdruck aus dem 'Journal für die reine und
                  angewandte Mathematik.'"
               With: Ueber das Verschwinden der Theta-Functionen
                  / von B. Riemann. Berlin : Georg Reimer, 1866 -- Beiträge
                  zur Theorie der durch die Gauss'sche Reihe F ([alpha],
                  [beta], [gamma], [chi]) darstellbaren Functionen / von
                  Bernhard Riemann. Göttingen : Verlag der Dieterichschen
                  Buchhandlung, 1857. Bound together subsequent to
                  publication.
Subjects:      Functions, Abelian.
Control No.:   1910300

Author:        Riemann, Bernhard, 1826-1866.
Title:         Ueber das Verschwinden der Theta-Functionen / von
                  B. Riemann.
Published:     Berlin : Georg Reimer, 1866.
Description:   12 p. ; 26 cm.
LC Call No.:   QA345.R54 1857
Dewey No.:     515.9/84 19
Notes:         "Abdruck aus dem 'Journal für die reine und
                  angewandte Mathematik.'"
               With: Theorie der Abel'schen Functionen / von B.
                  Riemann. Berlin : Georg Reimer, 1857. Bound together
                  subsequent to publication.
Subjects:      Functions, Theta.
Other titles:  Über das Verschwinden der Theta-Functionen.
Control No.:   4746648

Author:        Roch, Gustav, 1839-1866. [from old catalog]
Title:         De theoremate quodam circa functiones Abelianas
                  ...
Published:     Lipsiae, typis B. G. Teubneri [1862]
Description:   12 p., 1 l. 29 cm.
LC Call No.:   QA345.B6
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   6797330

Author:        Rohn, K[arl] [from old catalog]
Title:         Transformation der hyperelliptischen functionen
                  P=2, und ihre bedeutung für die Kummer'sche fläche ...
Published:     Leipzig, Druck von B. G. Teubner, 1879.
Description:   1 p.l., 40 p. diagrs. 23 cm.
LC Call No.:   QA345.R7
Subjects:      Functions, Theta. [from old catalog]
               Transformations (Mathematics) [from old catalog]
               Surfaces. [from old catalog]
Control No.:   6329597

Author:        Rosenhain, Georg, 1816-1887. [from old catalog]
Title:         Abhandlung über die functionen zweier variabler
                  mit vier perioden,
Published:     Leipzig. W. Engelmann, 1895.
Description:   p. cm.
LC Call No.:   QA345.R77
Subjects:      Functions, Abelian. [from old catalog]
Other authors: Weber, Heinrich Martin, 1842-1913, [from old
                  catalog] ed.
               *Witting, Alexander, 1861- [from old catalog]
                  tr.
Control No.:   7261244

Author:        Rost, Georg, 1870-
Title:         Theorie der Riemann'shen theta-function ...
Published:     Leipzig, Druck von B.G. Teubner, 1901.
Description:   iv, 66 p. 32 cm.
LC Call No.:   QA345.R8
Notes:         Habilitationsschrift--Würzburg.
Subjects:      Functions, Theta.
Control No.:   1216969

Author:        Schleicher, Karl, 1863- [from old catalog]
Title:         Darstellung und umkehrung von thetaquotienten,
Published:     Bayreuth, Druckerei von Th. Burger, 1890.
Description:   26 p. 1 l. 23 cm.
LC Call No.:   QA345.S34
Subjects:      Functions, Theta. [from old catalog]
Control No.:   8201934

Author:        Stahl, Hermann, 1843-1908.
Title:         Theorie der Abel'schen functionen,
Published:     Leipzig, B. G. Teubner, 1896.
Description:   x, 354 p. diagrs. 25 cm.
LC Call No.:   QA345.S7
               Microfilm 77223 QA
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   9174292

Author:        Ullrich, Edward.
Title:         Die Periodicitätsmoduln der hyperelliptischen
                  Normal-integrale dritter Gattung als Functionen eines
                  Parameters aufgefasst / von Edward Ullrich.
Published:     Leipzig : B. G. Teubner, 1884.
Description:   32 p. ; 23 cm.
LC Call No.:   QA345.U42
Notes:         Thesis--Heidelberg.
Subjects:      Functions, Abelian.
Control No.:   9138400

Author:        Wagner, Albert Ernst August, 1860-
Title:         Reihenentwickelung der hyperelliptischen
                  thetafunktionen, welche zu f(x)==xp6s + 2txp3s + I
                  gehören ...
Published:     Halle a.S., Druck der buchdruckerei des
                  Waisenhauses, 1892.
Description:   2 p. l., 44 p., 1 l. 23 cm.
LC Call No.:   QA345.W13
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Functions, Theta.
Control No.:   7265244

Author:        Weichold, Guido, 1857- [from old catalog]
Title:         Über symmetrische Riemann'sche flächen und die
                  periodicitätsmoduln der zugehörigen Abel'schen
                  normalintegrale erster gattung ...
Published:     Dresden, Druck von B. G. Teubner, 1883.
Description:   35, [1] p. 2 fold. pl. 23 cm.
LC Call No.:   QA345.W41
Subjects:      Riemann surfaces. [from old catalog]
               Functions, Abelian. [from old catalog]
Control No.:   5860798

Author:        Wiltheiss, Ernst Eduard, 1855- [from old
                  catalog]
Title:         Bestimmung Abelscher funktionen,
Published:     Halle, Druck von E. Karras, 1881.
Description:   38 p. 21 cm.
LC Call No.:   QA345.W75
Subjects:      Functions, Abelian. [from old catalog]
Control No.:   8202099
