#+STARTUP: showeverything logdone
#+options: num:nil


Author:        Ahrendt, Asmus. [from old catalog]
Title:         Untersuchungen über die parallelflächen der
                  flächen zweiten grades ...
Published:     Rostock, Universitäts-buchdruckerei von Adler's
                  erben, 1888.
Description:   75 p. 21 cm.
LC Call No.:   QA561.A28
Subjects:      Surfaces, Parallel. [from old catalog]
               Quadrics. [from old catalog]
Control No.:   8676504

Author:        Berger, Hugo, 1880-
Title:         Ueber rotationsflächen zweiten grades, die einem
                  gegebenen tetraeder eingeschrieben sind ...
Published:     Strassburg i. E., Buchdruckerei C. & J. Gœller,
                  1903.
Description:   43 p., 1 l. 23 cm.
LC Call No.:   QA561.B43
Notes:         Inaug.-dis.--Strassburg.
               Lebenslauf.
Subjects:      Quadrics.
Control No.:   8672251

Author:        Berthold, Ewald Richard.
Title:         Ueber den Umdrehungskegel, welcer ein System
                  dreier conjugirten Durchmesser eines dreiachsigen Ellipsoides
                  enthält, nebst Anwendungen ...
Published:     Zwickau, Druck von R. Zückler, 1885.
Description:   38 p. 28 x 22 cm.
LC Call No.:   QA561.B48
Notes:         Inaug.-ddiss.--Erlangen.
Subjects:      Quadrics
Other titles:  Über den Umdrehungskegel.
               [Pamphlets. Mathematics. 1841-1906.] v.21.
Control No.:   6327918

Author:        Boegehold, Hans, 1876- [from old catalog]
Title:         Historisch-kritische darstellung der
                  konstruktionen der fläche
Published:     Jena, Druck von B. Vopelius, 1898.
Description:   52, [4] p. 22 cm.
LC Call No.:   QA561.B56
Subjects:      Quadrics. [from old catalog]
Control No.:   9606479

Author:        Böhme, Emil Paul. [from old catalog]
Title:         Die Axen eines kegels zweiter ordnung ...
Published:     Berlin, Druck von, G. Schade, 1871.
Description:   24 p. diagr. on fold. pl. 21 cm.
LC Call No.:   QA561.B6
Other authors: Cone. [from old catalog]
Control No.:   5858900

Author:        Bollert, Karl.
Title:         Über konzentrische flächen zweiter ordnung ...
Published:     Berlin, Druck von G. Bernstein [1905?]
Description:   60 p., 1 l. diagrs. 22 cm.
LC Call No.:   QA561.B68
Notes:         Preisgekrönte lösung der von der hohen
                  Philosophischen fakultät der landesuniversität Rostock
                  gestellten preisaufgabe.
Subjects:      Quadrics.
Control No.:   4525616

Author:        Bullock, Roberts Cozart, 1906-
Title:         Non-conjugate osculating quadrics of a curve on a
                  surface ... by Roberts Cozart Bullock ...
Published:     [New York, 1933]
Description:   [1], 518-531 p., 1 l. 28 cm.
LC Call No.:   QA561.B8 1932
Dewey No.:     516.58
Notes:         Thesis (PH. D.)--University of Chicago, 1932.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from Transactions of the American
                  mathematical society, vol. 35, no. 2, 1933."
Subjects:      Quadrics.
               Curves on surfaces.
Control No.:   3581182

Author:        Caspary, Ferdinand, 1853-1901. [from old
                  catalog]
Title:         Die krümmungsmittelpunktsfläche des
                  elliptischen paraboloids.
Published:     Berlin, Druck von G. Reimer, 1875.
Description:   vi, 22, [2] p. 27 x 22 cm.
LC Call No.:   QA561.C34
Subjects:      Paraboloid. [from old catalog]
Control No.:   7739663

Author:        Chasles, M. (Michel), 1793-1880.
Title:         Two geometrical memoirs on the general properties
                  of cones of the second degree, and on the spherical conics /
                  by M. Chasles ; Tr. from the French, with notes and
                  additions, and an appendix on the application of analysis to
                  spherical geometry / by the Rev. Charles Graves.
Published:     Dublin : For Grant and Bolton, 1841.
Description:   vi p., 1 leaf, 112 p. ; 23 cm.
LC Call No.:   QA561.C4
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Cone.
               Conics, Spherical.
Other authors: Graves, Charles, 1812-1899.
Control No.:   7731803

Author:        Druxes, Joseph, 1874- [from old catalog]
Title:         Über eine specielle schaarschaar von flächen
                  zweiter classe ...
Published:     Strassburg i. E., Buchdruckerei des "Elsässer,"
                  1896.
Description:   30 p., 1 l. 22 cm.
LC Call No.:   QA561.D8
Subjects:      Quadrics. [from old catalog]
Control No.:   8208342

Author:        Eilker, Georg, 1842- [from old catalog]
Title:         Durch 9 puncte im raume und an 9 ebenen im raume
                  eine oberfläche 2. grades zu legen" ...
Published:     Jena, Druck von W. Ratz, 1872.
Description:   19 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA561.E34
Subjects:      Quadrics. [from old catalog]
Control No.:   8204094

Author:        Engel, J. H. [from old catalog]
Title:         Konstruktionen zur geometrie der flächen zweiter
                  ordnung und der ebenen kurven dritter ordnung...
Published:     Zürich, Druck von Zürcher und Furrer, 1889.
Description:   2 p.l., 39 p. 20 cm.
LC Call No.:   QA561.E57
Subjects:      Quadrics. [from old catalog]
               Curves, Plane. [from old catalog]
Control No.:   10074793

Author:        Fredholm, K[arl] A[ugust] [from old catalog]
Title:         Framställning af skärningarne mellan ett plan
                  samt en cylinder,
Published:     Nyköping, Tryckt, hos P. M. F. Lundberg, 1873.
Description:   22 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA561.F85
Subjects:      Hyperboloid.
Control No.:   9612035

Author:        Gradhandt, Ernst.
Title:         Beiträge zur theorie der focaleigenschaften der
                  krümmungscurven auf den flächen zweiter ordnung ... von
                  Ernst Gradhandt ...
Published:     Rostock, H. Winterberg's buchdruckerei, 1901.
Description:   58 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA561.G73
Notes:         Inaug.-diss.--Rostock.
Subjects:      Quadrics.
Control No.:   4525390

Author:        Graue, Louis C., 1923- [from old catalog]
Title:         A necessary and sufficient condition that a curve
                  lie on a hyperquadric.
Published:     [n.p., 1951]
Description:   607-612 p. 25 cm.
LC Call No.:   QA561.G74
Subjects:      Quadrics. [from old catalog]
Control No.:   7917819

Author:        Gutsche, Oskar, 1856-
Title:         Über eine neue erzeugungsart der regelflächen
                  zweiter ordnung ...
Published:     Halle a.S., 1890.
Description:   1 p. l., 32, [2] p. 22 cm.
LC Call No.:   QA561.G98
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Quadrics.
Control No.:   7732902

Author:        Heger, R. (Richard), 1846-1919.
Title:         Analytische Geometrie auf der Kugel, von Richard
                  Heger.
Published:     Leipzig, G. J. Göschen, 1908.
Description:   vii, 152 p. diagrs. 20 cm.
Series:        Sammlung Schubert, 54
LC Call No.:   QA561.H46
Notes:         "Veröffentlichungen über die Geometrie auf der
                  Kugel": p. [v]-vii.
Subjects:      Sphere.
Control No.:   7279467

Author:        Henderson, Archibald, 1877- [from old catalog]
Title:         The cone of the normals and an allied for central
                  surfaces of the second degree.
Published:     [Chapel Hill, N.C., 1901]
Description:   p. [32]-60. 23 cm.
LC Call No.:   QA561.H5
Subjects:      Quadrics. [from old catalog]
Control No.:   9670059

Author:        Hepke, Bernhard, 1877-
Title:         Über kürzeste Transversalen zwischen
                  Erzeugenden einer hyperboloidischen Regelschaar ...
Published:     Breslau, Buchdr. H. Fleischmann, 1905.
Description:   76, [2] p. 23 cm.
LC Call No.:   QA561.H52
Notes:         Lebenslauf.
               Inaug.-diss.--Breslau.
Subjects:      Hyperboloid
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.9.
Control No.:   10091476

Author:        Ide, Heinrich, 1851-1887. [from old catalog]
Title:         Zur analytischen behandlung der sphärischen
                  kegelschnitte ...
Published:     Marburg, 1876.
Description:   1 p.l., 28 p. diagrs. on 2 pl. 27 x 21 cm.
LC Call No.:   QA561.J19
Subjects:      Conics, Spherical.
Control No.:   7732586

Author:        Klöres, Carl.
Title:         Zur geschichte der Steiner'schen konstruktion
                  einer fläche 2. ordnung ...
Published:     Rostock, C. Boldt'sche hofbuchdruckerei, 1903.
Description:   40 p. diagrs. on II fold. pl. 23 cm.
LC Call No.:   QA561.K66
Notes:         Inaug.-diss.--Rostock.
Subjects:      Quadrics.
Control No.:   10080370

Author:        Kober, Georg Hubo, 1854-
Title:         Die harmonisch zugeordneten flächen zweiten
                  grades ...
Published:     Halle a.S., Plötz'sche buchdruckerei, R.
                  Nietschmann, 1888.
Description:   73, [1] p. 24 cm.
LC Call No.:   QA561.K75
Notes:         Inaug.-dis.--Halle.
               Vita.
Subjects:      Quadrics.
Control No.:   9137974

Author:        Kossow, Friedrich.
Title:         Zur Scheitelpunktsbestimmung des Paraboloids ...
Published:     Rostock, C. Boldt'sche Hofbuchdruckerei, 1903.
Description:   58 p., 1 L. 23 cm.
LC Call No.:   QA561.K86
Notes:         Inaug.-diss.--Rostock.
Subjects:      Paraboloid
Other titles:  [Pamphlets. Mathematics. 1841-1906] v. 11.
Control No.:   8202921

Author:        Kroeber, Karl. [from old catalog]
Title:         Über die fusspunctenflächen der flächen
                  zweiter ordnung ...
Published:     Strassburg, Buchdruckerei von R. Schultz & comp.,
                  1878.
Description:   1 p.l., 31 p. 24 cm.
LC Call No.:   QA561.K93
Subjects:      Quadrics. [from old catalog]
               Surfaces, Pedal. [from old catalog]
Control No.:   6334770

Author:        Krusche, Albert, 1879-
Title:         Ueber Kurven und Flächen, welche sich aus
                  geradlinigen Flächen 2. Grades durch gemeinsame Lote
                  zwischen den erzeugenden ableiten lassen ...
Published:     Breslau, Buchdruckerei H. Fleischmann, 1905.
Description:   58, [2] p. 23 cm.
LC Call No.:   QA561.K94
Notes:         Lebenslauf.
               Inaug.-diss.--Breslau.
Subjects:      Quadrics
Other titles:  Über Kurven und Flächen.
               [Pamphlets. Mathematics. 1841-1906] v. 11.
Control No.:   8680854

Author:        Ludwig, W. (Walther), 1876-
Title:         Über die ebenen, welche aus einer fläche II.
                  grades einem gegebenen kegelschnitt ähnliche kegelschnitte
                  ausschneiden ...
Published:     Breslau, R. Galle's buchdr., 1898.
Description:   74, [2] p. 23 cm.
LC Call No.:   QA561.L94
Notes:         Inaug.-diss.--Breslau.
               Lebenslauf.
Subjects:      Quadrics.
Control No.:   8659293

Author:        Ludwig, W. (Walther), 1876-
Title:         Uebertragung einer dreiecksaufgabe auf das
                  tetraeder ...
Published:     Marburg, Universitäts-buchdruckerei von J.A.
                  Koch, 1904.
Description:   65, [3] p. diagrs. 22 cm.
LC Call No.:   QA561.W53
Notes:         Inaug.-diss.--Marburg.
               Lebenslauf.
Subjects:      Hyperboloid.
               Tetrahedra.
Control No.:   6331831

Author:        Meyer, Theodor, 1859- [from old catalog]
Title:         Ueber die kegel des Pappus und des Hachette ...
Published:     Berlin, W. & S. Loewenthal, 1884.
Description:   27, [1] p. diagrs. 21 cm.
LC Call No.:   QA561.M61
Subjects:      Cone. [from old catalog]
Control No.:   5861710

Author:        Munk, Meier, 1869- [from old catalog]
Title:         Ueber die möglochen fälle mehrfach
                  hyperboloidischer lagen zweier tetraeder ...
Published:     Marburg, Buchdruckerei von J. Hamel, 1893.
Description:   2 p.l., 51 p., 2 l. 22 cm.
LC Call No.:   QA561.M96
Subjects:      Hyperboloid.
               Tetrahedra.
Control No.:   8673324

Author:        Müth, Gerhard, 1882-
Title:         Die projektive Erzeugung der Rotationsflächen
                  zweiten Grades ... von Gerhard Müth.
Published:     Breslau, Buchdruckerei H. Fleischmann, 1905.
Description:   62, [2] p. diagrs. 22 cm.
LC Call No.:   QA561.M9
Notes:         Lebenslauf.
               Inaug.-diss.--Breslau.
Subjects:      Quadrics
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.13.
Control No.:   7740001

Author:        Paepcke, Hermann.
Title:         Klassifikation der Oberflächen zweiten Grades
                  bei Cauchy, Plücker, Hesse ...
Published:     Rostock, C. Boldt'sche Hofbuchdruckerei, 1904.
Description:   70 p. 22 cm.
LC Call No.:   QA561.P13
Notes:         Inaug.-diss.--Rostock.
               "Benutzte Literatur": p. [3]-4.
Subjects:      Quadrics
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.14.
Control No.:   9611673

Author:        Pflaumbaum, Gustav Albert, 1860-
Title:         Bestimmung der scheinbaren grösse eines
                  elliptischen paraboloids für einen beliebigen punkt des
                  raumes unter berücksichtigung der wesentlichen specialfälle
                  ...
Published:     Halle a.S., Druck von Gundlach & Eggers, 1889.
Description:   33 p., 1 l. 22 cm.
LC Call No.:   QA561.P53
Notes:         Inaug.-diss.--Halle.
               Vita.
               Slip of "Druckfehler-berichtigungen" inserted.
Subjects:      Parabolid.
Control No.:   7264811

Author:        Phalen, Harold Romaine, 1889-
Title:         Metric properties of the quadric of Moutard.
Published:     1926.
Description:   iii, 34 l. 29 cm.
LC Call No.:   QA561.P48
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Quadrics.
Control No.:   784264

Author:        Schoenflies, A. (Arthur), 1853-1928.
Title:         Synthetisch-geometrische untersuchungen über
                  flächen zweiten grades und eine aus ihnen abgeleitete
                  regelfläche
Published:     Berlin, Buchdruckerei von G. Schade (O. Francke)
                  [1877]
Description:   38, [2] p. 23 cm.
LC Call No.:   QA561.S36
Subjects:      Quadrics. [from old catalog]
               Geometry, Projective. [from old catalog]
Control No.:   9610061

Author:        Schulte, Anton. [from old catalog]
Title:         Mathematische abhandlung über die
                  stereographische projection des ellipsoids ...
Published:     Bonn, Druck von C. Georgi, 1874.
Description:   32 p. diagr. 22 cm.
LC Call No.:   QA561.S39
Subjects:      Projection. [from old catalog]
               Ellipsoid. [from old catalog]
Control No.:   9141725

Author:        Schulze, Edmund, 1858- [from old catalog]
Title:         Über die parallelfläche des elliptischen
                  paraboloids ...
Published:     Halle, Druck von E. Karras, 1886.
Description:   36 p., 1 l. 22 cm.
LC Call No.:   QA561.S43
Subjects:      Surfaces, Parallel. [from old catalog]
               Paraboloid. [from old catalog]
Control No.:   5867104

Author:        Schwarzlose, R[ichard]
Title:         Ueber eine geometrische beziehung der
                  Fresnelschen wellenfläche zum dreiachsigen ellipsoid ...
Published:     Rostock, C. Hinstorffs buchdr., 1906.
Description:   56 p. 22 cm.
LC Call No.:   QA561.S46
Notes:         Inaug.-diss.--Rostock.
Subjects:      Ellipsoid.
               Refraction, Double.
Control No.:   8219336

Author:        Sourander, Emil, 1851-1901. [from old catalog]
Title:         Études nouvelles des lignes et surfaces du
                  second degré,
Published:     Helsingfors, J. C. Frenckell et fils, 1879.
Description:   1 p.l., 47 p. 2 fold. tab. 24 cm.
LC Call No.:   QA561.S71
Subjects:      Quadrics. [from old catalog]
               Conic sections. [from old catalog]
Control No.:   5860362

Author:        Spain, Barry.
Title:         Analytical quadrics.
Published:     Oxford, New York, Pergamon Press, 1960.
Description:   135 p. illus. 23 cm.
Series:        International series of monographs on pure and
                  applied mathematics, v. 14
LC Call No.:   QA561.S37 1960
Dewey No.:     516.4
Subjects:      Quadrics.
Series Entry:  International series of monographs in pure and
                  applied mathematics ; v. 14.
Control No.:   6085073

Author:        Spencker, Friedrich.
Title:         Ueber die ersten negativen Fusspunktflächen der
                  Flächen zweiter Ordnung / von Friedrich Spencker.
Published:     Rostock : C. Boldt'sche Hof-buchdruckerei, 1889.
Description:   56 p. ; 23 cm.
LC Call No.:   QA561.S74
Notes:         Thesis--Rostock.
Subjects:      Quadrics.
Control No.:   8201589

Author:        Stolte L. [from old catalog]
Title:         Das focalaxensystem einer fläche zweiter ordnung
                  ...
Published:     Strassburg, Buchdruckerei von R. Schulz & co.,
                  1877.
Description:   1 p. l., 22 p. 25 cm.
LC Call No.:   QA561.S8
Subjects:      Quadrics. [from old catalog]
Control No.:   9607854

Author:        Tan, Vidal Arceo, 1893- [from old catalog]
Title:         Projective properties of the Moutart quadric.
Published:     Chicago, 1925.
Description:   28, 8 l. tables. 29 cm.
LC Call No.:   QA561.T3
Subjects:      Quadrics. [from old catalog]
Control No.:   10337974

Author:        Theune, Hermann, 1840- [from old catalog]
Title:         Ueber den winkel, welchen zwei seitenkanten eines
                  kegels bilden, wenn derselbe in eine ebene abgewickelt wird
                  ...
Published:     Jena, Druck von W. Ratz, 1867.
Description:   34 p. diagrs. on pl. 21 cm.
LC Call No.:   QA561.T41
Subjects:      Cone. [from old catalog]
Control No.:   7266173

Author:        Valson, C.-Alph. (Claude-Alphonse), b. 1826.
Title:         Thèse d'analyse : application de la théorie des
                  coordonnées elliptiques à la géométrie de l'ellipsoïde :
                  thèse d'astronomie : questions proposées par la Faculté /
                  par C.-Alph. Valson.
Published:     Paris : Mallet-Bachelier, 1854.
Description:   28 p. ; 27 cm.
LC Call No.:   QA561.V3x 1854
Notes:         "Thèses présentées à la Faculté des sciences
                  de Paris pour obtenir le grade de docteur ès sciences ...
                  soutenues le lundi 7 août 1854 devant la commission
                  d'examen."
Subjects:      Ellipsoid.
Other titles:  Application de la théorie des coordonnées
                  elliptiques à la géométrie de l'ellipsoïde.
Control No.:   1456104

Author:        Vivian, R. H. [from old catalog]
Title:         Poles of a right line.
Published:     [n.p.] 1901.
Description:   1 v. cm.
LC Call No.:   QA561.V7
Control No.:   6738458

Author:        Vogt, Heinrich, 1850- [from old catalog]
Title:         Der sphärische kegelschnitt ...
Published:     Breslau, Druck von W. G. Korn, 1873.
Description:   2 p.l., 42, [2] p. 22 cm.
LC Call No.:   QA561.V9
Subjects:      Conics, Spherical.
Control No.:   9136506

Author:        Wageningen, F. van.
Title:         Théorie des pôles, des polaires et des plans
                  polaires par rapport aux surfaces du second degré,
Published:     La Haye, Belinfante frères; [etc., etc.] 1869.
Description:   47 p. diagrs. 29 cm.
LC Call No.:   QA561.W3
Subjects:      Quadrics. [from old catalog]
Control No.:   8262479

Author:        Zahn, Karl Albert Albin, 1883-
Title:         Constructive bestimmung der hauptaxen und der
                  umrisse einer fläche zweiten grades, die durch einen kreis
                  und vier punkte des raumes bestimmt ist ...
Published:     Strassburg, Buch- u. lichtdr. J. Manias & cie.,
                  1906.
Description:   43, [1] p. diagrs. on III fold. pl. 23 cm.
LC Call No.:   QA561.Z3
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Quadrics.
Control No.:   8687510

Author:        Berger, Richard, 1857- [from old catalog]
Title:         Über einige polyeder des regulären systems,
                  deren volumen bi gegebener oberfläche ein maximum ist ...
Published:     Marburg, Univeritäts-buchdruckerei (R.
                  Friedrich) 1881.
Description:   31, [1] p. diagrs. 21 cm.
LC Call No.:   QA563.B4
Subjects:      Maxima and minima. [from old catalog]
               Polyhedra. [from old catalog]
Control No.:   7731404

Author:        Bopp, Karl. [from old catalog]
Title:         Ueber des kürzeste verbindungssystem zwischen
                  vier punkten ...
Published:     Göttingen, Druck von Dieterichschen
                  univ.-buchdruckerei W. F. Kästner, 1879.
Description:   59 p. diagrs. on 2 fold. pl. 21 cm.
LC Call No.:   QA563.B73
Subjects:      Maxima and minima. [from old catalog]
Control No.:   8672252

Author:        Börsch, Anton, 1854- [from old catalog]
Title:         Über einige analytisch-geometrische maxima- und
                  minima-probleme ...
Published:     Marburg, 1876.
Description:   40 p. 26 cm.
LC Call No.:   QA563.B7
Subjects:      Maxima and minima.
               Ellipsoid.
Control No.:   10073297

Author:        Cresswell, D. (Daniel), 1776-1844.
Title:         An elementary treatise on the geometrical and
                  algebraical investigation of maxima and minima, being the
                  substance of a course of lectures delivered conformably to
                  the will of Lady Sadler: to which is added A selection of
                  propositions deducible from Euclid's Elements. By D.
                  Cresswell.
Published:     Cambridge [Eng.] Printed for J. Deighton, 1812.
Description:   271 p. illus. 22 cm.
LC Call No.:   QA563.C9
Subjects:      Maxima and minima.
Control No.:   7263563

Author:        Echols, William H. (William Holding), 1859-1934
Title:         On the maximum and minimum values of a linear
                  function of the radial co-ordinates of a point with respect
                  to simplicissimum in space of n dimensions. By William H.
                  Echols.
Published:     Charlottesville, Va., University of Virginia
                  [1910]
Description:   p. [45]-84. diagr. 27 cm.
Series:        Bulletin of the Philosophical Society. 
                  Scientific series, vol. 1, no. 3
               University of Virginia publications.
LC Call No.:   QA563.E4
Notes:         Cover title.
Subjects:      Maxima and minima.
Control No.:   8228006

Author:        Höhne, Richard i. e. Moritz Richard, 1861- [from
                  old catalog]
Title:         Analytische untersuchung Steinerscher maxima- und
                  minimaprobleme welche beziehungen zwischen umfang und inhalt
                  ebener figuren enthalten ...
Published:     Freiberg, Buchdruckerei E. Mauckisch, 1889.
Description:   p. cm.
LC Call No.:   QA563.H69
Subjects:      Max¯ima and m¯in¯ima [from old catalog]
Control No.:   6328232


Author:        Jahn, Ludwig, 1842- [from old catalog]
Title:         De theoria generali punctorum minimae distantiae
                  normalium superficierum curvarum cum exemplis ...
Published:     Gryphiswaldiae, typis F. G. Kunike [1864]
Description:   1 p.l., 52 p. 22 cm.
LC Call No.:   QA563.J25
Subjects:      Maxima and minima. [from old catalog]
               Quadrics. [from old catalog]
Control No.:   6800043

Author:        Odin, A[ugust] A., 1865-1890. [from old catalog]
Title:         Des maxima & minima de la distance de deux points
                  appartenant respectivement à deux courbes ou surfaces
                  données ...
Published:     Lausanne, Imprimerie Corbaz & comp., 1887.
Description:   23 p. diagrs. on pl. 22 cm.
LC Call No.:   QA563.O24
Subjects:      Maxima and minima. [from old catalog]
Control No.:   6796437

Author:        Papperitz, Erwin, 1857- [from old catalog]
Title:         Ueber das problem der kürzesten und weitesten
                  entfernung eines punctes von einer oberfläche II. ordnung
                  ...
Published:     Leipzig, Druck von Metzger & Wittig, 1883.
Description:   86 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA563.P21
Subjects:      Maxima and minima. [from old catalog]
               Quadrics. [from old catalog]
Control No.:   9610049

Author:        Ramchundra, 1821-1880.
Title:         A treatise on problems of maxima and minima,
                  solved by algebra. By Ramchundra ... Reprinted by order of
                  the Honourable court of directors of the East-India company
                  for circulation in Europe and in India, in acknowledgment of
                  the merit of the author, and in testimony of the sense
                  entertained of the importance of independent speculation as
                  an instrument of national progress in India. Under the
                  superintendence of Augustus De Morgan ...
Published:     London, W.H. Allen & co., 1859.
Description:   xxiii, v p., 1 l., 185 p., 1 l. diagrs. on 8 pl.
                  23 cm.
LC Call No.:   QA563.R17
Notes:         Has also special t.-p. with imprint: Calcutta,
                  Printed by P.S. d'Rozario and co., 1850.
Subjects:      Maxima and minima.
Other authors: De Morgan, Augustus, 1806-1871, ed.
Control No.:   272612

Author:        Simon, Konrad, 1860- [from old catalog]
Title:         Über den punkt kleinster entfernungssumme und
                  die flächen [Sigma] const. ...
Published:     Halle a/S., Druck von O. Hendel, 1887.
Description:   1 p.l., 45, [1] p., 1 l. diagrs. on pl. 23 cm.
LC Call No.:   QA563.S59
Subjects:      Maxima and minima. [from old catalog]
Control No.:   10078390

Author:        Sturm, Rudolf, 1841-1919.
Title:         Maxima und minima in der elementaren geometrie,
                  von Rudolf Sturm; mit 32 figuren im text.
Published:     Leipzig, Berlin, B. G. Teubner, 1910.
Description:   v, 138 p. 23 cm.
LC Call No.:   QA563.S8
Subjects:      Maxima and minima.
Control No.:   5884474

Author:        Worm, Hans [Otto], 1875- [from old catalog]
Title:         In der ebene einem gegebenen viereck ein viereck
                  von kleinstem umfange einzubeschreiben.
Published:     Zwickau, Druck von R. Zückler, 1900.
Description:   47, [1] p. diagrs. on 2 pl. 28 x 22 cm.
LC Call No.:   QA563.W92
Subjects:      Maxima and minima. [from old catalog]
               Triangle. [from old catalog]
Control No.:   9139319

Author:        Aeschlimann, Ulrich.
Title:         Zur Theorie der ebenen Curven vierter Ordnung /
                  von Ulrich Aeschlimann.
Published:     Zürich : Zürcher & Furrer, 1880.
Description:   39 p. ; 21 cm.
LC Call No.:   QA565.A2
Notes:         Thesis--Universität Zürich.
Subjects:      Curves, Plane.
Control No.:   9605002

Author:        Bacharach, J. [from old catalog]
Title:         Über schnittpunktsysteme algebraischer
                  curven...
Published:     Erlangen, Druck der universitäts-buchdruckerei
                  von Junge & sohn, 1881.
Description:   1 p.l., 34 p. 22 cm.
LC Call No.:   QA565.B12
Subjects:      Curves, Plane.
Control No.:   9606478

Author:        Basset, Alfred Barnard, 1854-1930.
Title:         An elementary treatise on cubic and quartic
                  curves, by A. B. Basset.
Published:     Cambridge, Deighton, Bell, 1901.
Description:   xvi, 255 p. 23 cm.
LC Call No.:   QA565.B32
Subjects:      Curves, Cubic.
               Curves, Quartic.
Control No.:   5853533

Author:        Beutel, Eugen, 1880-
Title:         Algebraische kurven, von Eugen Beutel ...
Published:     Leipzig, G.J. Göschen, 1909-11.
Description:   2 v. diagrs. 16 cm.
Series:        Sammlung Göschen. [435]-[436]
LC Call No.:   QA565.B5
Notes:         "Literaturverzeichnis": 1. t., p. [5]-6 (included
                  also in 2d vol.)
               1. t. Kurvendiskussion.--2. t. Theorie und kurven
                  dritter und vierter ordnung.
Subjects:      Curves, Plane.
Control No.:   273120

Author:        Blanchet, P[ierre] H[enry], 1795-1863. [from old
                  catalog]
Title:         Compléments de mathématiques spéciales.
Published:     Paris, Hachette, 1838.
Description:   2 p. l., 179, [1] p. diagrs. on iv fold. pl. 21
                  cm.
LC Call No.:   QA565.B6
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6794940

Author:        Borden, John, 1825-1919.
Title:         Some higher plane curves / by John Borden.
Published:     Chicago : E. J. Decker, 1888.
Description:   75 p. : ill. ; 24 cm.
LC Call No.:   QA565.B7
Subjects:      Curves, Plane.
Control No.:   8665427

Author:        Borelius, Johan.
Title:         Zur theorie der filarevoluten und parallelkurven
                  ebener und sphärischer kurven ...
Published:     Lund, Berlingsche buchdruckerei, 1906.
Description:   1 p. l., 63 p. 22 cm.
LC Call No.:   QA565.B74
Notes:         Akademisk-afhandling--Lund.
Subjects:      Curves.
Control No.:   5872969

Author:        Bretschneider, Wilhelm.
Title:         Ueber Curven vierter Ordnung mit drei
                  Doppelpunkten / von Wilhelm Bretschneider.
Published:     Stuttgart : C. Eberle, 1875.
Description:   viii, 65 p. : ill. ; 20 cm.
LC Call No.:   QA565.B8
Notes:         Thesis--Erlangen.
Subjects:      Curves, Plane.
Control No.:   6326757

Author:        Bullard, Warren Gardner, 1867-
Title:         On the general classification of plane quartic
                  curves.
Published:     Worcester, Mass., 1899.
Description:   193-208 p. diagrs. on III pl. 25 cm.
LC Call No.:   QA565.B93
Notes:         Cover title.
               Thesis (Ph. D.)--Clark University.
               "Reprinted from the Mathematical review," no. 3.
Subjects:      Curves, Quartic.
Control No.:   6331448

Author:        Coble, Arthur Byron, 1875- [from old catalog]
Title:         The relation of the quartic curve to conics,
Published:     [New York, 1903]
Description:   p. [65]-85. 27 cm.
LC Call No.:   QA565.C65
               Microfilm 65303 QA
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   7263535

Author:        Dowling, L. Wayland (Linnaeus Wayland), b. 1867.
Title:         On the forms of plane quintic curves, by L.
                  Wayland Dowling ...
Published:     Worcester, Mass., 1897.
Description:   p. [97]-119. : diagrs. on II pl. 25 cm.
LC Call No.:   QA565.D64
Notes:         Cover title.
               Thesis (Ph. D.)--Clark University, 1895.
               "Reprinted from the Mathematical review, vol.
                  I."
Subjects:      Curves, Quintic.
Control No.:   8672932

Author:        Drach, Carl Adelhard von, 1839-1915.
Title:         Ueber innere und äusere Polaren der Curven
                  dritter Ordnung / öffentlich vertheidigen wird Carl Adelhard
                  von Drach.
Published:     Marbung : J.A. Koch, [1864]
Description:   12 p. ; 25 cm.
LC Call No.:   QA565.D7
Notes:         Zur Erlangung der venia legendi--Universität
                  Marburg, 1864.
Subjects:      Curves, Plane.
Control No.:   8668260

Author:        Eberle, Johann Friedrich.
Title:         Über rationale curven fünfter ordnung
                  insbesondere diejenigen vierter und fünfter classe.
Published:     München, J. Lindauer'sche buchhandlung
                  (Schoepping) 1892.
Description:   34 p. diagrs. on pl. 22 cm.
LC Call No.:   QA565.E16
Notes:         Issued also as Inaug.-diss., Tübingen.
Subjects:      Curves, Quintic.
Control No.:   10074792

Author:        Field, Peter, b. 1876-
Title:         On the forms of unicursal quintic curves ...
Published:     Baltimore, The Lord Baltimore press, the
                  Friedenwald company, 1904.
Description:   1 p.l., 15 p. xiv pl. on 7 l., diagrs. 31 x 25
                  cm.
LC Call No.:   QA565.F45
Subjects:      Curves, Quintic.
Control No.:   6333565

Author:        Frahm, Wilhelm.
Title:         Ueber die erzeugung der curven dritter classe und
                  vierter ordnung ...
Published:     Tübingen, Druck von L.F. Fues, 1873.
Description:   vi, [7]-43 p. 22 cm.
LC Call No.:   QA565.F8
Subjects:      Curves, Plane. [from old catalog]
Control No.:   8200102

Author:        Fricke, Friedrich, 1863- [from old catalog]
Title:         Über ebene curven dritter ordnung welche durch
                  die imaginären kreispunkte gehen ...
Published:     Gotha, Druck von F. A. Perthes, 1898.
Description:   2 p.l., 33, [1] p. diagrs. on 2 fold. pl. 21 cm.
LC Call No.:   QA565.F88
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7732901

Author:        Friedrich, Philipp, 1863- [from old catalog]
Title:         Die rationale plancurve 4. ordnung im
                  zusammenhang mit der binären form 6. grades ...
Published:     Giessen, Druck von W. Keller, 1886.
Description:   30 p., 1 l. 26 x 22 cm.
LC Call No.:   QA565.F91
Subjects:      Curves, Plane. [from old catalog]
               Forms, Binary. [from old catalog]
Control No.:   9137655

Author:        Fuchs, August, 1864-
Title:         Untersuchung der brennpunktseigenschaften
                  höherer algebraischer kurven, insbesondere deren der dritten
                  und vierten ordnung ...
Published:     Marburg, Druck von J. Hamel, 1887.
Description:   55, [3] p. diagrs. on fold. pl. 24 cm.
LC Call No.:   QA565.F95
Notes:         Inaug.-diss.--Marburg.
               Lebenslauf.
Subjects:      Curves, Plane.
Control No.:   9137973

Author:        Greiner, Albert, 1879-
Title:         Ueber orthogonale Invarianten der Kurven dritter
                  Ordnung mit unendlich fernem Doppelpunkt und ihre
                  geometrische Bedeutung ... von Albert Greiner.
Published:     Jena, Universitätsbuchdruckerei G. Neuenhahn,
                  1902.
Description:   41, [1] p. diagrs. 23 cm.
LC Call No.:   QA565.G82
Notes:         Vita.
               Inaug.-diss.--Jena.
Subjects:      Curves, Plane
Other titles:  Über orthogonale Invarianten der Kurven dritter
                  Ordnung mit unendlich fernem Doppelpunkt und ihre
                  geometrische Bedeutung.
               [Pamphlets. Mathematics. 1841-1906] v.8.
Control No.:   7264486

Author:        Gross, Wilhelm, mathematician. [from old
                  catalog]
Title:         Ueber die Combinanten binärer Formensysteme,
                  welche ebenen rationalen Curven zugeordnet sind.
Published:     Stuttgart, 1887.
Description:   51 p. 20 cm.
LC Call No.:   QA565.G87
Subjects:      Curves, Plane. [from old catalog]
               Forms, Binary. [from old catalog]
Control No.:   7264810

Author:        Hanna, Ulysses S. (Ulysses Sherman), 1865-1940.
Title:         The equations of bitangential curves of the
                  general plane quintic and sextic curves / by Ulysses S.
                  Hanna.
Published:     [S.l. : Palermo, 1909].
Description:   25 p. ; 26 cm.
LC Call No.:   QA565.H25
Notes:         "Estratto dal tomo XXVII (2p0s sem. 1909) die
                  Rendiconti del Circolo Matematico di Palermo."
               Thesis (Ph. D.)--University of Pennsylvania,
                  1905.
Subjects:      Curves, Plane.
Control No.:   5883233

Author:        Haskell, Hellen K. [from old catalog]
Title:         On curvilinear asymptotes.
Published:     [n.p.] 1898.
Description:   1 v. cm.
LC Call No.:   QA565.H3
Control No.:   7672870

Author:        Hilton, Harold, b. 1876.
Title:         Plane algebraic curves, by Harold Hilton ...
Published:     Oxford, The Clarendon press, 1920.
Description:   xv, [1], 388 p. diagrs. 24 cm.
LC Call No.:   QA565.H5
Subjects:      Curves, Algebraic.
Control No.:   4053378

Author:        Hochheim, Franz. [from old catalog]
Title:         Über eine art der erzeugung der kurven 3. klasse
                  mit einer doppeltangente ...
Published:     Halle a/S., 1899.
Description:   2 p.l., 50, [2] p. 22 cm.
LC Call No.:   QA565.H6
Subjects:      Curves, Plane. [from old catalog]
Control No.:   9127386

Author:        Joerres, Peter, 1837- [from old catalog]
Title:         De diametris coniugatis curvarum algebraicarum,
Published:     Bonnae, typis expressit P. Neusser, 1862.
Description:   2 p. l., 26 p., 1 l. 21 cm.
LC Call No.:   QA565.J5
Subjects:      Curves, Plane. [from old catalog]
Control No.:   5858901

Author:        Johnson, William Woolsey, 1841-1927.
Title:         Curve tracing in Cartesian coordinates, by
                  William Woolsey Johnson ...
Published:     New York, J. Wiley & sons, 1884.
Description:   vi, 86 p. diagrs. 20 cm.
LC Call No.:   QA565.J6
Subjects:      Curves, Plane.
Control No.:   2634007

Author:        Kölmel, Friedrich, 1862- [from old catalog]
Title:         Die Grassmannsche erzeugungsweise von ebenen
                  kurven dritter ordnung ...
Published:     Lahr, Druck von M. Schauenburg, 1886.
Description:   38 p. diagrs. on 2 fold. pl. 22 cm.
LC Call No.:   QA565.K75
Subjects:      Curves, Cubic.
               Ausdehnungslehre.
Control No.:   5860361

Author:        Köstlin, Wilhelm.
Title:         Ueber singularitäten Ebener algebraischer Curven
                  / von Wilhelm Köstlin.
Published:     Dresden : B. G. Teubner, 1895.
Description:   36 p. : ill. ; 24 cm.
LC Call No.:   QA565.K78
Notes:         Thesis--Tübingen.
Subjects:      Curves, Plane.
Control No.:   8201588

Author:        Larrivee, Jules Alphonse, 1909- [from old
                  catalog]
Title:         Effects of singularities of rational curves upon
                  the symmetric correspondence between residuals on their
                  tangents,
Published:     Washington, D.C., The Catholic university of
                  America press, 1942.
Description:   2 p. l., 19 p. incl. tables, diagrs. 23 cm.
LC Call No.:   QA565.L3
Subjects:      Geometry, Projective. [from old catalog]
               Curves, Algebraic. [from old catalog]
Control No.:   10195553

Author:        Leuch, S. R. Albert. [from old catalog]
Title:         Erzeugung und untersuchung einiger ebenen curven
                  höherer ordnung ...
Published:     Bern, Buchdruckerei K. J. Wyss, 1888.
Description:   1 p. l., 58 p. diagrs. 23 cm.
LC Call No.:   QA565.L65
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6328231

Author:        Loewenherz, Leopold, 1847-1892.
Title:         De curvis tangentialibus curvarum algebraicarum
                  ordinis N. : dissertatio inauguralis mathematica ... / auctor
                  Leopoldus Loewenherz ...
Published:     Berolini : Typis expresserunt Rosenthal eiusque
                  soc., 1870.
Description:   [3], 22, [2] p. ; 21 cm.
LC Call No.:   QA565.L8
Notes:         Thesis
                  (doctoral)--Friedrich-Wilhelms-Universität Berlin, 1870.
               Vita.
Subjects:      Curves, Plane.
Control No.:   7263317

Author:        MacLaurin, Colin, 1698-1746.
Title:         Geometria organica; sive Descriptio linearum
                  curvarum universalis. Auctore Colino Mac Laurin ...
Published:     Londini, impensis G. & J. Innys, 1720.
Description:   6 p.l., 139, [1] p. 48 diagr. on xii pl. 23 x 19
                  cm.
LC Call No.:   QA565.M16
Subjects:      Curves, Plane.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   2633978

Author:        Manchester, James Eugene. [from old catalog]
Title:         Ueber singularitäten ebener kurven ...
Published:     Tübingen, Druck von H. Laupp, jr., 1899.
Description:   38 p. 23 cm.
LC Call No.:   QA565.M26
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6330766

Author:        Messick, John Frederick, 1875-
Title:         Cubic curves in reciprocal triangular situation
                  ... by John Frederick Messick.
Published:     Salem, Mass., The Salem press co., 1907.
Description:   29-47, [1] p. diagrs. 31 x 24 cm.
LC Call No.:   QA565.M57
Notes:         Cover title.
               Biography.
               "Reprint from the Annals of mathematics, second
                  series, vol. 9, no. 1, October, 1907."
               Thesis (Ph. D.)--Johns Hopkins university,1906.
Subjects:      Curves, Cubic
Control No.:   8685558

Author:        Meyer, Ernst, 1860-
Title:         Die rationalen ebenen Kurven 4ter Ordnung und die
                  binäre Form 6ter Ordnung ...
Published:     Königsberg, Hartungsche Buchdruckerei [1888]
Description:   2 p. l., 40, [2] p. 21 cm.
LC Call No.:   QA565.M61
Notes:         Inaug.-dis.-Königsberg.
               Vita.
Subjects:      Curves, Plane.
               Forms, Binary.
Control No.:   6796436

Author:        Molke, Roman, 1871- [from old catalog]
Title:         Über diejenigen sätze Jacob Steiner's, welche
                  sich auf die durch einen punkt gehenden transversalen einer
                  kurve nter ordnung beziehen ...
Published:     Breslau, Schlesische volkszeitungs-buchdruckerei
                  [1897]
Description:   2 p.l., 83 p. 23 cm.
LC Call No.:   QA565.M8
Subjects:      Curves, Plane. [from old catalog]
               Maxima and minima. [from old catalog]
Control No.:   8212681

Author:        Moore, Lucius Terrell, 1902-
Title:         Determination of the type of the tricrunodal
                  quartic by means of its invariants ... By L.T. Moore ...
Published:     [Baltimore, 1926]
Description:   1 p. l., p. 241-252, 1 l. diagrs. 26 cm.
LC Call No.:   QA565.M83 1925
Notes:         Thesis (PH. D.)--Johns Hopkins University, 1925.
               Vita.
               "Reprinted from the American journal of
                  mathematics, vol. XLVIII, number 4."
Subjects:      Curves, Quartic.
               Invariants.
Control No.:   5928240

Author:        Nichols, Thomas Flint.
Title:         On some special Jacobians, by Thomas F. Nichols
                  ...
Published:     Worcester, Mass., 1896.
Description:   p. [60]-80 p. 25 cm.
LC Call No.:   QA565.N59
Notes:         Cover title.
               Thesis (Ph. D.)--Clark University, 1895.
               "Reprinted from the Mathematical review."
Subjects:      Curves, Plane.
Control No.:   7736108

Author:        [Paczkowski, Ignacy], 1840- [from old catalog]
Title:         Tractantur curvae quarti gradus ex sententia
                  principiorum, quae sunt proposita in Cremonae libro:
                  Introduzione ad una teoria geometrica delle curve piane
                  praemisso additamento ad theoriam generalem ...
Published:     [Gryphiswaldiae, typis F. G. Kunike, 1867]
Description:   4 p.l., 48 p. 19 cm.
LC Call No.:   QA565.P12
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   7736485

Author:        Pengra, Charlotte Elvira, d. 1915. [from old
                  catalog]
Title:         On the conformal representation of plane curves,
                  particularly for the cases p=4, 5, and 6,
Published:     Madison, 1904.
Description:   1 p.l., [655]-669 p. 23 cm.
LC Call No.:   QA565.P4
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7393461

Author:        Piper, Karl.
Title:         Gestalten der kurven vom vierten grade, deren
                  gleichungen nur grade potenzen der coordinaten enthalten.
Published:     Rostock, Stiller'sche hofbuchhandlung (H.
                  Schmidt), 1871.
Description:   31, [1] p. diagrs. on 2 pl. 24 cm.
LC Call No.:   QA565.P5
Notes:         Preisschrift--Univ. Rostock.
               Plates printed on both sides.
Subjects:      Curves, Quartic.
Control No.:   9136507

Author:        Piper, Karl. [from old catalog]
Title:         Ueber die formen der curven vom vierten grade
                  welche keinen doppelpunkt haben ...
Published:     Rostock, C. Boldt'sche hof-buchdruckerei, 1876.
Description:   v, 110 p., 1 l. diagrs. on 8 pl. 22 cm.
LC Call No.:   QA565.P6
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7731405

Author:        Powell, Baden, 1796-1860.
Title:         The elements of curves; comprising, I. The
                  geometrical principles of the conic sections.  II. An
                  introduction to the algebraic theory of curves.  Designed for
                  the use of students in the university.
Published:     Oxford, Clarendon press, 1828.
Description:   xvi, 69, ix, 103 p. illus. 22 cm.
LC Call No.:   QA565.P8
Subjects:      Curves, Plane.
               Conic sections.
Control No.:   10073549

Author:        Primrose, E. J. F. (Eric John Fyfe)
Title:         Plane algebraic curves.
Published:     London, Macmillan; New York, St. Martin's Press,
                  1955.
Description:   111 p. illus. 23 cm.
LC Call No.:   QA565.P83
Dewey No.:     516.54
Subjects:      Curves, Algebraic.
Control No.:   6987513

Author:        Ragsdale, Virginia. [from old catalog]
Title:         On the arrangement of the real branches of plane
                  algebraic curves ...
Published:     Baltimore, Md., The Lord Baltimore press, the
                  Friedenwald company, 1906.
Description:   p. cm.
LC Call No.:   QA565.R14
Subjects:      Curves, Plane.
Control No.:   8681762

Author:        Rosenow, Hugo, 1851- [from old catalog]
Title:         Die curven dritter ordnung mit einem
                  doppelpunkt,
Published:     Leipzig, Druck von Metzger & Wittig, 1873.
Description:   2 p. l., 48, [2] p. diagrs. 22 cm.
LC Call No.:   QA565.R8
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7732795

Author:        Salmon, George, 1819-1904.
Title:         A treatise on the higher plane curves: intended
                  as a sequel to A treatise on conic sections. By George Salmon
                  ...
Edition:       3d ed.
Published:     Dublin, Hodges, Foster, and Figgis, 1879.
Description:   xix, 395 p. 23 cm.
LC Call No.:   QA565.S17 1879
Notes:         Assisted by Prof. A. Cayley.
Subjects:      Curves, Plane.
               Curves, Algebraic.
Other authors: Cayley, Arthur, 1821-1895.
Control No.:   745456

Author:        Salmon, George, 1819-1904.
Title:         A treatise on the higher plane curves: intended
                  as a sequel to A treatise on conic sections. By George Salmon
                  ...
Edition:       2d ed.
Published:     Dublin, Hodges, Foster, and co., 1873.
Description:   xix, [1], 379 p. diagrs. 23 cm.
LC Call No.:   QA565.S17 1873
Notes:         Assisted by Prof. A. Cayley. cf. Pref.
Subjects:      Curves, Plane.
               Curves, Algebraic.
Other authors: Cayley, Arthur, 1821-1895.
Control No.:   13190916

Author:        Sanchez, Alberto. [from old catalog]
Title:         La cornoide.
Published:     San Salvador, Imprenta nacional, 1895.
Description:   71 p. diagrs. on pl. 21 cm.
LC Call No.:   QA565.S2
Subjects:      Curves, Plane. [from old catalog]

Author:        Severi, Francesco, 1879-1961.
Title:         ...Vorlesungen über algebraische geometrie:
                  geometrie auf einer kurve, Riemannsche flächen, Abelsche
                  integrale, Berechtigte deutsche übersetzung, von dr. Eugen
                  Löffler... Mit einem einführungswort von A. Brill und 20
                  figuren.
Published:     Leipzig [etc.] B.G. Teubner, 1921
Description:   xv, [1] 408 p. diagrs. 25 cm.
LC Call No.:   QA565.S4
Notes:         "Die vorliegenden 'Vorlesungen'... erschienen
                  zuerst in italienischer sprache [Lezioni di geometria
                  algebraica, Padova, 1908] als autographierte wiedergabe einer
                  von mir im jahre 1907/08 an der Universität Padua gehaltenen
                  vorlesung. Bei der vorbereitung für den druck wurden
                  zahlreiche abänderungen und zusätze angebracht." - Vorwort,
                  p.[v]
Subjects:      Geometry, Algebraic.
               Curves, Algebraic.
               Riemann surfaces.
               Functions, Abelian.
Other authors: Löffler, Eugen, 1883- tr.
Control No.:   7360845

Author:        Tenz, Oskar, 1883-
Title:         Über singuläre Asymptotenkurven / von Oskar
                  Tenz.
Published:     Freiburg im Breisgau : C. A. Wagner, 1908.
Description:   35 p. ; 23 cm.
LC Call No.:   QA565.T5
Notes:         Lebenslauf.
               Thesis--Giessen.
Subjects:      Curves, Plane.
               Asymptotes.
Control No.:   6346753

Author:        Vargas y Aguirre, Joaquín de. [from old
                  catalog]
Title:         Catálogo general de curvas;
Published:     Madrid, Impr. de la "Gaceta de Madrid," 1908.
Description:   1030 p. illus. 30 cm.
LC Call No.:   QA565.V4
Subjects:      Curves. [from old catalog]
Control No.:   6950394

Author:        Vogel, Peter. [from old catalog]
Title:         Ueber die curven vierter ordnung vom geschlechte
                  eins ...
Published:     München, Akademische buckdruckerei von F.
                  Straub, 1880.
Description:   33 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA565.V88
Subjects:      Curves, Plane. [from old catalog]
Control No.:   8201428

Author:        Wieleitner, Heinrich Karl, 1874-1932. [from old
                  catalog]
Title:         Algebraische kurven;
Published:     Berlin und Leipzig, W. de Gruyter & co., 1919.
Description:   p. cm.
LC Call No.:   QA565.W62
Subjects:      Curves. [from old catalog]
Control No.:   6925680

Author:        Wieleitner, Heinrich Karl, 1874- [from old
                  catalog]
Title:         Algebraische kurven;
Published:     Berlin und Leipzig, G. J. Göschen, 1914.
Description:   p. cm.
LC Call No.:   QA565.W6
Subjects:      Curves. [from old catalog]
Control No.:   6363831

Author:        Winger, Roy Martin, 1885- [from old catalog]
Title:         Self-projective rational curves of the fourth and
                  fifth orders ...
Published:     [Baltimore] 1914.
Description:   1 p.l., p. 53-78, 1 l. diagrs. 31 cm.
LC Call No.:   QA565.W67
Subjects:      Curves, Plane.
               Curves, Quartic.
               Curves, Quintic.
Control No.:   8704478

Author:        Yates, Robert C. (Robert Carl), 1904-1963.
Title:         Curves, prepared for use in the Department of
                  mathematics,
Published:     [West Point, N.Y.] Lithographed by Reproduction
                  plant, U. S. M. A., c1946.
Description:   1 p. l., [1], 230, [4] p. illus., diagrs. 23 cm.
LC Call No.:   QA565.Y3
Subjects:      Curves, Plane.
Other authors: United States. Military academy, West Point.
                  Dept. of mathematics. [from old catalog]
Control No.:   8814153

Author:        Alvera, Johann. [from old catalog]
Title:         Die curve dritten grades xy (x + y) = a3 ...
Published:     Strassburg, Impr. C. Wurst, 1873.
Description:   32 p. diagr. on pl. 22 cm.
LC Call No.:   QA567.A4
Subjects:      Curves, Plane.
Control No.:   10073298

Author:        Arnold, Herbert Eli. [from old catalog]
Title:         Concerning the rational curves Rê5b3s (II) and
                  Rê4b2s ...
Published:     [Baltimore, 1930]
Description:   1 p. l., p. 601-606. 25 cm.
LC Call No.:   QA567.A6 1928
Subjects:      Curves, Algebraic.
Control No.:   7345277

Author:        Arnoldy, Mary Nicholas, Sister.
Title:         The reality of the double tangents of the
                  rational symmetric quartic curve, by Sister Mary Nicholas
                  Arnoldy.
Published:     Washington, D.C., Catholic University of America,
                  1932.
Description:   1 p. l., 31 p., 1 l. diagrs. (part fold.) 23 cm.
LC Call No.:   QA567.A64
Dewey No.:     516.54
Notes:         At head of title: The Catholic University of
                  America.
               Thesis (Ph. D.)--Catholic University of America.
Subjects:      Curves, Quartic.
               Coordinates, Tangential.
               Triangle.
Other titles:  The double tangents of the rational symmetric
                  quartic curve, The reality of.
Control No.:   7349520

Author:        Ashcraft, Thomas Bryce, 1882-
Title:         Quadratic involutions on the plane rational
                  quartic ... by Thomas Bryce Ashcraft. 1911.
Published:     Waterville, Me., Press of the Mail publishing
                  company [1912]
Description:   1 p.l., 29, [1] p. 31 cm.
LC Call No.:   QA567.A7
Notes:         Thesis (Ph.D.)--Johns Hopkins university, 1911.
               Vita.
Subjects:      Curves, Plane.
               Curves, Quartic.
Control No.:   2634662

Author:        Atchison, Clyde Shepherd, 1882-
Title:         Curves with a directrix ...
Published:     Baltimore, Md., The Lord Baltimore press, 1908.
Description:   2 p.l., 25 p., 1 l. diagrs. 30 x 24 cm.
LC Call No.:   QA567.A8
Notes:         Thesis (Ph. D.)--Johns Hopkins university.
Subjects:      Curves, Plane
Control No.:   9156894

Author:        Bateman, Harry, 1882-1946.
Title:         The quartic curve and its inscribed
                  configurations ...
Published:     [Baltimore, 1914]
Description:   1 p.l., [357]-386 p., 1 l. 31 cm.
LC Call No.:   QA567.B2
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   6365250

Author:        Bell, Clifford, 1898- [from old catalog]
Title:         The triangles in-and-circumscribed to the quartic
                  curves of deficiency zero, by Clifford Bell ...
Published:     [Berkeley, Calif., University of California
                  press, 1926]
Description:   3 p.l., p. [35]-53. 28 cm.
LC Call No.:   QA567.B5 1925
Subjects:      Curves, Quartic. [from old catalog]
               Triangle. [from old catalog]
Control No.:   7330644

Author:        Bell, Clifford. [from old catalog]
Title:         The triangles in-and-circumscribed to the quartic
                  curves of deficiency zero. Thesis, ...
Published:     [n.p.] 1926.
Description:   1 v. cm.
LC Call No.:   QA567.B5 1926
Control No.:   6741057

Author:        Beyer, Hermann. [from old catalog]
Title:         Zur punktuellen erzeugung der curven vierter
                  ordnung ...
Published:     Marburg, 1878.
Description:   30 p., 1 l. 19 cm.
LC Call No.:   QA567.B52
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   6798974

Author:        Boer, Marten Jan de, 1877- [from old catalog]
Title:         De rationale krommen van den vijfden graad in
                  Rb5s en Rb4s ... Door Marten Jan de Boer.
Published:     Schiedam, H.A.M. Roelants [1907]
Description:   7p. l., 128 p. 25 cm.
LC Call No.:   QA567.B64
Notes:         Proefschrift--Groningen.
Subjects:      Curves, Quintic.
Control No.:   13194541

Author:        Böhmer, Wilhelm. [from old catalog]
Title:         Untersuchungen über die cissoide des Diocles.
Published:     Brilon, Buchdruckerei von M. Friedländer, 1874.
Description:   25 p. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA567.B6
Subjects:      Curves, Plane. [from old catalog]
Control No.:   8669619

Author:        Boulliau, Ismael, 1605-1694.
Uniform Title: De lineis spiralibus demonstrationes novae
Title:         Ismaelis Bullialdi De lineis spiralibus
                  demonstrationes nouae.
Published:     Parisiis : Apud Sebastianum Cramoisy, regis &
                  reginae architypographum, et Gabrielem Cramoisy ..., 1657.
Description:   [8], 137, [3] p. (the last leaf blank) : ill. ;
                  23 cm. (4to)
LC Call No.:   QA567.B68 1657
Notes:         Signatures: ãp4s A-Rp4s Sp2s.
               BLC, v. 39, p. 173
               BN, v. 17, col. 588
               NUC pre-1956, NB 0692792
               With: Ismaelis Bullialdi Exercitationes
                  geometricae tres ... Parisiis : Apud Sebastianum Cramoisy,
                  regis ac reginae architypographum, et Gabrielem Cramoisy ...,
                  1657. Probably bound together subsequent to publication.
Subjects:      Spirals -- Early works to 1800.
Other titles:  De lineis spiralibus demonstrationes nouae.
Control No.:   2948438

Author:        Boulliau, Ismael, 1605-1694.
Uniform Title: Exercitationes geometricae tres.
Title:         Ismaelis Bullialdi Exercitationes geometricae
                  tres ... ; Astronomiae philolaicae fundamenta clariùs
                  explicata, & asserta aduersùs clariss. viri Sethi Wardi
                  Oxoniensis professoris impugnationem.
Published:     Parisiis : Apud Sebastianum Cramoisy, regis ac
                  reginae architypographum, et Gabrielem Cramoisy ..., 1657.
Description:   44, 56 p. : ill. ; 23 cm. (4to)
LC Call No.:   QA567.B68 1657; Alternative class.: QA444
Notes:         "Astronomiae philolaicae fundamenta" has special
                  t.p. with title: Ismaelis Bullialdi Astronomiae philolaicae
                  fundamenta ...
               Signatures: A-Ep4s Fp2s, p2sA-Gp4s.
               BLC, v. 39, p. 173
               BN, v. 17, col. 588
               NUC pre-1956, NB 0692797
               (of 1st work, from t.p.) I. Circa demonstrationes
                  per inscriptas & circimscriptas figuras -- II. Circa
                  conicarum sectionum quasdam propositiones -- III. De
                  porismatibus.
               With: Ismaelis Bullialdi De lineis spiralibus
                  demonstrationes nouae. Parisiis : Apud Sebastianum Cramoisy,
                  regis & reginae architypographum, et Gabrielem Cramoisy ...,
                  1657. Probably bound together subsequent to publication.
Subjects:      Geometry -- Early works to 1800.
Other authors: Boulliau, Ismael, 1605-1694. Astronomiae
                  philolaicae fundamenta. 1657.
Other titles:  Exercitationes geometricae tres.
               Astronomiae philolaicae fundamenta clariùs
                  explicata, & asserta aduersùs clariss. viri Sethi Wardi
                  Oxoniensis professoris impugnationem.
               Ismaelis Bullialdi Astronomiae philolaicae
                  fundamenta ...
               Astronomiae philolaicae fundamenta.
Control No.:   2475208

Author:        Brooks, Charles Edward, 1879- [from old catalog]
Title:         Orthic curves or algebraic curves which satisfy
                  La-place's equation in two dimensions ...
Published:     Baltimore, 1904.
Description:   [1], [294]-331, [1] p. 23 cm.
LC Call No.:   QA567.B87
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6800229

Author:        Burke, Leonarda, Sister, 1900-
Title:         On a case of the triangles in-and-circumscribed
                  to a rational quartic curve with a line of symmetry, by
                  Sister Leonarda Burke.
Published:     Washington, D.C., 1931.
Description:   2 p. l., 23 p., 1 l. illus. 23 cm.
LC Call No.:   QA567.B88 1931
Dewey No.:     516.54
Notes:         Thesis (Ph. D.)--Catholic University of America,
                  1931.
               Vita.
Subjects:      Curves, Quartic.
               Triangle.
Control No.:   7345444

Author:        Burke, Mary Francella, Sister, 1884- [from old
                  catalog]
Title:         The triangles in and circumscribed to the
                  tacnodal rational quartic with residual acnode, by Sister
                  Mary Francella Burke.
Published:     Washington, D.C., 1931.
Description:   1 p. l., 18 p., 1 l. illus. 23 cm.
LC Call No.:   QA567.B885 1931
Notes:         Thesis (Ph. D.)--Catholic university of America.
               Vita.
Subjects:      Curves, Quartic.
               Triangle.
Control No.:   13194642

Author:        Calloway, Rose Gertrude, Sister, 1909- [from old
                  catalog]
Title:         The reality of the triangles in-and-circumscribed
                  to the plane rational quartic with one cusp and two nodes.
Published:     Washington, Catholic University of America Press,
                  1948.
Description:   19 p. diagrs. 23 cm.
LC Call No.:   QA567.C3
Subjects:      Curves, Quartic.
Control No.:   7419695

Author:        Case, James Edward, 1896- [from old catalog]
Title:         The behavior of the Hessian at a multiple point
                  of a curve ...
Published:     [Chicago] 1938.
Description:   ii numb. l., 31 p. diagrs. 24 cm.
LC Call No.:   QA567.C38 1936
Subjects:      Curves, Algebraic.
               Curves, Plane.
Other titles:  Hessian at a multiple point of a curve.
Control No.:   6907347

Author:        Cohen, Teresa, 1892- [from old catalog]
Title:         Investigations on the plane quartic ...
Published:     [Baltimore, 1919]
Description:   1 p.l., p. [191]-211. 1 l. 31 cm.
LC Call No.:   QA567.C6
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   5910454

Author:        Connelly, Damian, Brother, 1918- [from old
                  catalog]
Title:         An investigation of the conditions for reality of
                  certain characterisitics of the bicircular cuspidal quartic
                  curve.
Published:     Washington, Catholic Univ. of America, 1948.
Description:   13 p. diagrs. 23 cm.
LC Call No.:   QA567.C64
Subjects:      Curves, Quartic. [from old catalog]
Other titles:  Bicircular cuspidal quartic curve.
Control No.:   7884166

Author:        Cooper, Elizabeth Morgan, 1891- [from old
                  catalog]
Title:         Perspective elliptic curves,
Published:     [Baltimore, 1931]
Description:   1 p.l., p. 555-572, 1 l. 25 cm.
LC Call No.:   QA567.C65 1930
Subjects:      Curves, Plane. [from old catalog]
Control No.:   8284577

Author:        Darboux, Gaston, 1842-1917. [from old catalog]
Title:         Sur une classe remarquable de courbes et de
                  surfaces algébriques et sur la théorie des imaginaires,
Edition:       2. tirage.
Published:     Paris, A. Hermann, 1896.
Description:   xiii, 340 p. 25 cm.
LC Call No.:   QA567.D3
Control No.:   9087218

Author:        Dean, Mildred Caroline (Waters), Mrs., 1904-
                  [from old catalog]
Title:         A system of six rectangular biquadratics ...
Published:     [New York, 1930]
Description:   1 p.l., p. 585-600, 1 l. diagr. 25 cm.
LC Call No.:   QA567.D4 1929
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   8747991

Author:        Dölle, Robert, 1880- [from old catalog]
Title:         Orthogonale invarianten der circularkurven 3.
                  ordnung ...
Published:     Jena, Druck von B. Vopelius, 1905.
Description:   38, [2] p. 23 cm.
LC Call No.:   QA567.D65
Subjects:      Curves, Cubic.
               Forms (Mathematics)
Control No.:   10083482

Author:        Fowler, Mary Charlotte, sister, 1899-
Title:         The discriminant of the sextic of double point
                  parameters of the plane rational quartic curve, by Sister
                  Mary Charlotte Fowler.
Published:     Washington, D.C., Catholic University of America,
                  1937.
Description:   2 p. l., 21 p. 23 cm.
LC Call No.:   QA567.F7 1938
Dewey No.:     516.54
Notes:         Thesis (Ph. D.)--Catholic Uiversity of America,
                  1938.
Subjects:      Curves, Quartic.
Control No.:   10181398

Author:        Gehman, Harry Merrill.
Title:         Concerning the subsets of a plane continuous
                  curve... / [by] Harry Merrill Gehman.
Published:     Philadelphia : [s.l.] 1925.
Description:   p. 29-46. : diagr. ; 26 cm.
LC Call No.:   QA567.G35 1925
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1925.
               "Reprint from Annals of mathematics, vol. 27, no.
                  1."
Subjects:      Curves, Plane.
Other titles:  Subsets of a plane continous curve.
Control No.:   5925776

Author:        Gentry, Ruth, b. 1862.
Title:         On the forms of plane quartic curves ... By Ruth
                  Gentry.
Published:     New York, Press of R. Drummond, 1896.
Description:   4 p.l., 73 p. diagrs. on 12 pl. 23 cm.
LC Call No.:   QA567.G4
Notes:         Plates printed on both sides.
               Biography.
               Thesis (PH. D.)--Bryn Mawr college, 1896.
Subjects:      Curves, Quartic.
Control No.:   272968

Author:        Glänzer, Carl. [from old catalog]
Title:         Die gegencurve der geraden linie ...
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buchdruckerei (W. F. Kästner) 1873.
Description:   46 p. diagrs. on 2 fold. pl. 21 cm.
LC Call No.:   QA567.G54
Subjects:      Curves, Plane. [from old catalog]
Control No.:   9608996

Author:        Gough, Mary de Lellis, Sister, 1892-
Title:         On the condition for the existence of triangles
                  in-and-circumscribed to certain types of the rational quartic
                  curve and having a common side, by Sister Mary de Lellis
                  Gough.
Published:     Washington, D.C., The Catholic University of
                  America, 1931.
Description:   1 p. l., 26 p., 1 l. illus., fold. pl. 23 cm.
LC Call No.:   QA567.G6 1931
Dewey No.:     516.54
Notes:         Thesis (Ph. D.)--Catholic University of America,
                  1931.
               Vita.
Subjects:      Curves, Quartic.
               Triangle.
Control No.:   8750170

Author:        Herwig, Hermann [Anton Bernhard], 1844-1881.
                  [from old catalog]
Title:         Über trajectorien zu den tangenten ebener curven
                  ...
Published:     Göttingen, Druck von  E. A. Huth, 1867.
Description:   40 p. diagrs. on double pl. 22 cm.
LC Call No.:   QA567.H58
Subjects:      Curves, Plane. [from old catalog]
Control No.:   10077340

Author:        Heymann, Carl Woldemar, 1855-1910. [from old
                  catalog]
Title:         Zwei abhandlungen aus dem nachlass des professors
                  dr W. Heymann: I. Ein rollenproblem.--Die kurven "T" und "N."
                  Mit 31 figuren. II. Auflösung der allgemeinen gleichung nten
                  grades durch konvergente reihen.
Published:     Chemnitz, Druck von J. C. F. Pickenhahn & sohn
                  [1915]
Description:   46 p. 2 fold. pl. 28 x 22 cm.
LC Call No.:   QA567.H6
Subjects:      Curves, Plane. [from old catalog]
               Equations -- Numerical solutions. [from old
                  catalog]
Other authors: Rockstuhl, Adolf, [from old catalog] ed.
Control No.:   8248065

Author:        Hill, Mary Laetitia, Sister.
Title:         The number and reality of quadrilaterals
                  in-and-circumscribed to a rational unicuspidal quartic with
                  real tangents from the cusp, by Sister Mary Laetitia Hill.
Published:     Washington, D.C., Catholic University of America,
                  1935.
Description:   2 p. l., 17 p. diagrs. 23 cm.
LC Call No.:   QA567.H65 1935
Dewey No.:     516.54
Notes:         At head of title: The Catholic University of
                  America.
               Thesis (Ph. D.)--Catholic University of America,
                  1935.
Subjects:      Curves, Quartic.
               Polygons.
Other titles:  Quadrilaterals in-and-circumscribed to a rational
                  unicuspidal quartic.
Control No.:   6892050

Author:        Hochheim, Adolf i. e. Karl Adolf, 1840-1898.
                  [from old catalog]
Title:         De genere quodam curvarum orthogonalium ...
Published:     Halis Saxonum, typis Schidtianis [1864]
Description:   18, [2] p. 28 x 22 cm.
LC Call No.:   QA567.H68
Subjects:      Curves, Plane. [from old catalog]
Control No.:   9141567

Author:        Hodgson, Joseph Ellis, 1872-
Title:         Orthocentric properties of the plane directed
                  n-line ... by Joseph E. Hodgson.
Published:     Lancaster, Pa., The New era printing company,
                  1912.
Description:   1 p. L., 199-231, [1] p. 28 cm.
LC Call No.:   QA567.H75
Notes:         Biography.
               Reprinted from the American mathematical society
                  Transactions, v. 13.
               Abstract of thesis (Ph. D.)--Johns Hopkins
                  university, 1910.
Subjects:      Curves, Plane
Control No.:   9636414

Author:        Hugi, Hans Rudolf. [from old catalog]
Title:         Begleitkurven eines punktes in bezug auf eine
                  kurve nter ordnung ...
Published:     Bern, Haller'sche buchdruckerei, 1900.
Description:   35 p. diagrs. on fold. pl. 24 x 19 cm.
LC Call No.:   QA567.H89
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7268439

Author:        Jentzsch, Hermann Theodor, 1838- [from old
                  catalog]
Title:         Theorie der astroiden einer neuen classe von
                  curven ...
Published:     Greifswald, Druck von F. W. Kunike [1860]
Description:   3 p.l., 34 p. 24 cm.
LC Call No.:   QA567.J54
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7734251

Author:        Kelley, Mary Gervase, Sister, 1888-
Title:         On the cardioids fulfilling certain assigned
                  conditions / by Sister Mary Gervase.
Published:     Washington, D.C. : [National capital Press],
                  1917.
Description:   45 p. : ill. ; 23 cm.
LC Call No.:   QA567.K4
Notes:         Thesis (Ph. D.)--Catholic University of America.
               Vita.
Subjects:      Cardioid.
Control No.:   7777101

Author:        Kortum, Hermann, 1836-1904. [from old catalog]
Title:         De proprietatibus curvarum tertii ordinis
                  synthetica methodo deductis,
Published:     Bonnae, formis Carthausianis [1861]
Description:   1. Curves, Cubic.
LC Call No.:   QA567.K67
Control No.:   9606167

Author:        Lefschetz, Solomon, 1884-1972
Title:         On the existence of loci with given
                  singularities.
Published:     Lancaster, Pa., 1913.
Description:   p.23-41.     28cm.
LC Call No.:   QA567.L4
Notes:         Thesis (Ph. D.) -Clark University, 1911.
               "Reprinted from tne Transactions of the American
                  Mathematical Society, January, 1913."
               Volume contains: Notes on the Riemann-Roch
                  theorem, a compilation of lectures and papers used in a
                  1972-73 tutorial ... Mathematics  Dept. of Holy Cross
                  College.
Subjects:      Curves, Plane
Control No.:   10107386

Author:        Lehmann, Fr. X. (Franz Xavier)
Title:         Die Archimedische Spirale mit Rücksicht auf ihre
                  Geschichte / von Fr. X. Lehmann.
Published:     [Freiburg : s.n.], 1862?
Description:   81 p., 3 folded leaves of plates : ill. ; 24 cm.
LC Call No.:   QA567.L43x 1862
Notes:         "Als Beilage zu dem Freiburger Lyceums-Programme
                  von 1862."
               Includes bibliographical references.
Subjects:      Spirals.
               Algebraic geometry.
               Calculus.
Control No.:   1456216

Author:        Lehr, Marguerite, 1898-
Title:         The plane quintic with five cusps ... by
                  Marguerite Lehr ...
Published:     [Baltimore, 1927]
Description:   1 p.l., p. 197-214, 1 l. diagrs. 25 cm.
LC Call No.:   QA567.L45 1925
Notes:         Thesis (Ph.D.)--Bryn Mawr college, 1925.
               Vita.
Subjects:      Curves, Quintic.
Other titles:  Cusps, The plane quintic with five.
Control No.:   2162552

Author:        Ljungh, Anders Theodor. [from old catalog]
Title:         Über isoptische und orthoptische kurven ...
Published:     Lund, H. Ohlsson's buchdruckerei, 1895.
Description:   2 p.l., 49 p., 1 l. diagrs. on fold. pl. 24 cm.
LC Call No.:   QA567.L78
Subjects:      Curves, Plane. [from old catalog]
Control No.:   5863959

Author:        Lorenz, [Franz Ferdinand] [from old catalog]
Title:         Analytische untersuchungen über äquidistante
                  curven ...
Published:     Chemnitz, Druck von J. C. F. Pickenhahn & sohn
                  [1876]
Description:   p. cm.
LC Call No.:   QA567.L86
Subjects:      Curves, Plane. [from old catalog]
Other authors: Chemnitz. K. Gewerb-akademie. [from old catalog]
Control No.:   8673323

Author:        Loria, Gino.
Title:         Spezielle algebraische und transzendente ebene
                  kurven; theorie und geschichte. Autorisierte nach dem
                  italienischen manuskript bearbeitete deutsche ausgabe, von
                  prof. Fritz Schütte ...
Edition:       2. aufl. ...
Published:     Leipzig, Berlin, B.G. Teubner, 1911.
Description:   1 v. vi fold pl. 23 cm.
Series:        B.G. Teubners sammlung von lehrbüchern auf dem
                  gebiete der mathematischen wissenschaften mit einschluss
                  ihrer anwendungen. bd. 5, 2
LC Call No.:   QA567.L88
ISBN:          14.00M
Subjects:      Curves, Plane.
               Curves, Transcendental.
Other authors: Schütte, Fritz, b. 1864.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit Einschluss
                  ihrer Anwendungen ; Bd. V, 2.
Control No.:   2634567

Author:        Loria, Gino, 1862- [from old catalog]
Title:         Spezielle algebraische und transscendente ebene
                  kurven.
Published:     Leipzig, B. G. Teubner, 1902.
Description:   xxi, 744 p. diagrs. on xvii fold. pl. 23 cm.
LC Call No.:   QA567.L87
Subjects:      Curves, Plane.
               Curves, Transcendental.
Other authors: Schütte, Fritz, 1864- [from old catalog]
Control No.:   6805541

Author:        Losehand, Otto, 1881-
Title:         Ueber Kurven 16. Ordnung und 12. Klasse, die bei
                  einem Problem der Enveloppentheorie auftreten ... von Otto
                  Losehand.
Published:     Göttingen, Druck der Dieterich'schen
                  Univ.-Buchdruckerei (W.F. Kaestner) 1904.
Description:   38, [2] p. diagrs. on III double pl. 24 cm.
LC Call No.:   QA567.L89
Notes:         Vita.
               Inaug.-diss.--Kiel.
Subjects:      Curves, Plane
Other titles:  Über Kurven 16. Ordnung und 12. Klasse.
               [Pamphlets. Mathematics. 1841-1906] v.12.
Control No.:   8205161

Author:        Mathews, Robert Maurice, 1884- [from old
                  catalog]
Title:         Cubic curves and desmic surfaces,
Published:     [Menasha, Wis., and New York, 1926]
Description:   [1], 502-522 p., 1 l. 28 cm.
LC Call No.:   QA567.M35 1925
Subjects:      Curves, Cubic. [from old catalog]
               Surfaces. [from old catalog]
Other titles:  Desmic sufaces.
Control No.:   8737368

Author:        McFarland, Elsie Jeanette, 1897- [from old
                  catalog]
Title:         A special quartic curve,
Published:     [Berkeley, Calif, 1923]
Description:   p. [389]-400. diagrs. 28 cm.
LC Call No.:   QA567.M3 1923
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   5920479

Author:        McNamara, Cyprian John, Brother, 1918- [from old
                  catalog]
Title:         The reality of the double tangents of the
                  rational bicircular symmetric quartic,
Published:     Washington, Catholic Univ. of America Press,
                  1948.
Description:   26 p. diagrs. 23 cm.
LC Call No.:   QA567.M33
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   8352143

Author:        Muehlenbruck, Martin Joseph, b. 1841. [from old
                  catalog]
Title:         Ueber die kardioidenförmigen Curven, welche
                  durch die Polargleichung ra+b sin t+c cos t gegeben sind.
Published:     Jena, Druck von W. Ratz, 1867.
Description:   30 p. diagrs. 26 cm.
LC Call No.:   QA567.M9
Subjects:      Cardioid.
Control No.:   9606322

Author:        Neelley, John Haven. [from old catalog]
Title:         Compound singularities of the rational plane
                  quartic curve,
Published:     [Baltimore, 1927]
Description:   1 p. l., p. 389-400. illus. 25 cm.
LC Call No.:   QA567.N4 1927
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   6398909

Author:        Obrist, Jeanette, sister. [from old catalog]
Title:         A problem arising from the special symmetric
                  correspondence, Cb2s, set up by the rational quartic curve
                  with two cusps ...
Published:     Washington, D.C., The Catholic university of
                  America press, 1941.
Description:   v. 15 p. diagrs. 23 cm.
LC Call No.:   QA567.O2
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   8787554

Author:        Otto, Karl Heinrich. [from old catalog]
Title:         Ueber einige eigenschaften der schwerpunktcurve
                  des kreises ...
Published:     Jena, Druck von W. Ratz, 1872.
Description:   22 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA567.O9
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7268592

Author:        Pence, Sallie Elizabeth, 1893- [from old
                  catalog]
Title:         The configuration of the double points of cubics
                  of a pencil,
Published:     Urbana, Ill., 1937.
Description:   1 p. l., 8 p., 1 l. 23 cm.
LC Call No.:   QA567.P47 1937
Subjects:      Curves, Cubic. [from old catalog]
Other titles:  Double points of cubics.
Control No.:   10181450

Author:        Phillips, Edward Charles, 1877-
Title:         On the pentacardioid ...
Published:     Baltimore, Md., The Lord Baltimore press, 1909.
Description:   1 p. L., 24 p., 1 L. diagrs. 29 x 23 cm.
LC Call No.:   QA567.P6
Notes:         Biographical note.
               Thesis (Ph. D.)--Johns Hopkins university.
Subjects:      Pentacardioid
Control No.:   7283756

Author:        Plateau, J[oseph Antoine Ferdinand], 1801-1883.
                  [from old catalog]
Title:         Quelques exemples curieux de discontinuité en
                  analyse;
Published:     [Bruxelles, Impr. de F. Hayez, 1877]
Description:   12 p. diagrs. 22 cm.
LC Call No.:   QA567.P71
Subjects:      Curves, Plane.
               Discontinuous functions.
Control No.:   8671432

Author:        Quinn, Miriam Francis, Sister, 1918- [from old
                  catalog]
Title:         On the number of quadrilaterals that can be
                  in-and-circumscribed to a plane quartic having one, two, or
                  three nodes.
Published:     Washington, Catholic Univ. of America Press,
                  1949.
Description:   3 p.l., 13 p. 23 cm.
LC Call No.:   QA567.Q5
Subjects:      Curves, Quartic. [from old catalog]
               Polygons. [from old catalog]
Control No.:   8849153

Author:        Rechenbach, Eduard. [from old catalog]
Title:         Discussion der durch die gleichung ayp3s +
                  bxp3s = abxy + cp3s(x + y) dargestellten krummen linie
                  ...
Published:     Münster, Gedrudckt bei E. C. Brunn, 1872.
Description:   1 p. l., 58 p. diagrs. on 6 pl. 22 cm.
LC Call No.:   QA567.R3
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6794941

Author:        Reilly, Mary Henrietta, Sister.
Title:         Self-symmetric quadrilaterals
                  in-and-circumscribed to the plane rational quartic curve with
                  a line of symmetry ... by Sister Mary Henrietta Reilly ...
Published:     Washington, D.C., The Catholic University of
                  America, 1936.
Description:   3 p. l., 16 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA567.R4 1936
Dewey No.:     516.54
Notes:         Thesis (Ph. D.)--Catholic University of America,
                  1936.
               Bibliographical foot-notes.
Subjects:      Curves, Quartic.
               Quadrilaterals.
               Polygons.
Control No.:   5962319

Author:        Rembieliânski, Ludwik. [from old catalog]
Title:         Teorya krzywych iloczynowych.
Published:     W Warszawie, 1826.
Description:   xiv, 195 p. diagrs. 21 cm.
LC Call No.:   QA567.R45
Subjects:      Curves, Algebraic. [from old catalog]
Control No.:   9314277

Author:        Rice, Joseph Nelson, 1890-
Title:         On the in-and-circumscribed triangles of the
                  plane rational quartic curve / by Joseph Nelson Rice.
Published:     Wahington, D.C. : [National Capital Press],
                  1917.
Description:   32 p. : ill. ; 23 cm.
LC Call No.:   QA567.R5
Notes:         Thesis (Ph. D.)--Catholic University of America.
               Biographical sketch.
Subjects:      Curves, Quartic.
               Triangle.
Control No.:   10119037

Author:        Roebbelen, O. [from old catalog]
Title:         Ueber einige formen der curve die von irgend
                  einem punkte einer geraden linie beschrieben wird, deren
                  einer endpunkt einen kreis, deren anderer endpunkt eine durch
                  den mittelpunkt dieses kreises gezogene gerade linie
                  durchläuft ...
Published:     Rostock, C. Boldt's buchdruckerei, 1874.
Description:   25 p. 21 cm.
LC Call No.:   QA567.R71
Subjects:      Curves, Plane. [from old catalog]
Control No.:   7735434

Author:        Schlink, Clemens, mathematician. [from old
                  catalog]
Title:         Discussion der curve ap2s
                  (x+y)+xy(xp2s+yp2s)=ap4s ...
Published:     Jena, Druck von W. Ratz, 1867.
Description:   28 p. 25 cm.
LC Call No.:   QA567.S3
Subjects:      Curves, Plane. [from old catalog]
Control No.:   9605003

Author:        Spiller, Philipp, 1800-1879. [from old catalog]
Title:         Disputatio de analysi curvae, aequatione hac
                  expressae:
Published:     Posnaniae, typis G. Deckeri et sociorum [1838]
Description:   36 p. 23 x 20 cm.
LC Call No.:   QA567.S7
Subjects:      Curves, Plane. [from old catalog]
               Posen, K. Marien-Gymnasium. [from old catalog]
Control No.:   9141581

Author:        Sporer, Benedikt. [from old catalog]
Title:         Über den schwerpunkt der gemeinschaftlichen
                  punkte zweier algebraischer kurven...
Published:     Tübingen, F. Fues, 1896.
Description:   1 p.l., 40 p. 22 cm.
LC Call No.:   QA567.S76
Subjects:      Curves, Plane. [from old catalog]
Control No.:   9606512

Author:        Steiner, Gustaf Fredrik. [from old catalog]
Title:         Über die katakaustiken algebraischer ebenen [!]
                  curven ...
Published:     Lund, E. Malmströms buchdruckerei, 1896.
Description:   1 p.l., 45, [1] p. diagrs. on 2 pl. 22 cm.
LC Call No.:   QA567.S82
Subjects:      Curves, Plane. [from old catalog]
Control No.:   10076154

Author:        Stephens, Roswell Powell, 1874-
Title:         On the pentadeltoid ...
Published:     [Lancaster, Pa., Press of the New era printing
                  company] 1906.
Description:   2 p. L., 207-227 p., 1 L. diagrs. 28 cm.
LC Call No.:   QA567.S83
Notes:         Vita.
               Reprinted from the Transactions of the American
                  mathematical society, v. 7, no. 2, April, 1906.
               Thesis (Ph. D.)--Johns Hopkins university.
Subjects:      Curves, Plane
Control No.:   10082845

Author:        Stiner, Gottlieb. [from old catalog]
Title:         Ueber curven vom geschlecht null ...
Published:     Uster-Zürich, Druck von A. Digglemann, 1890.
Description:   52 p. 23 cm.
LC Call No.:   QA567.S85
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6331830

Author:        Stosch, Friedrich. [from old catalog]
Title:         Über diejenigen unicursalcurven, deren bogen
                  eine algebraische funktion der rechtwinkligen koordinaten ist
                  ...
Published:     Guben, Druck von A. Koenig, 1891.
Description:   52 p. 22 cm.
LC Call No.:   QA567.S88
Subjects:      Curves, Plane. [from old catalog]
Control No.:   6800042

Author:        Sullivan, Helen, Sister, 1907-
Title:         The number and reality of the non-self-symmetric
                  quadrilaterals in-and-circumscribed to the rational
                  unicuspidal quartic with a line of symmetry, by Sister M.
                  Helen Sullivan.
Published:     Washington, D.C., Catholic University of America,
                  1934.
Description:   1 p. l., 17 p. diagrs. 23 cm.
LC Call No.:   QA567.S9 1934
Dewey No.:     516.54
Notes:         At head of title: The Catholic University of
                  America.
               Thesis (Ph. D.)--Catholic University of America,
                  1934.
               Vita.
Subjects:      Curves, Quartic.
               Polygons.
Other titles:  Non-self-symmetric quadrilaterals
                  in-and-circumscribed to the rational unicuspidal quartic.
Control No.:   8761320

Author:        Thuener, Domitilla, Sister, 1880-
Title:         On the number and reality of the self-symmetric
                  quadrilaterals in-and-circumscribed to the
                  triangular-symmetric rational quartic, by Sister M. Domitilla
                  Thuener.
Published:     Washington, D.C., The Catholic University of
                  America, 1932.
Description:   1 p. l., 19 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA567.T55 1932
Dewey No.:     516.54
Notes:         At head of title: The Catholic University of
                  America.
               Thesis (Ph. D.)--Catholic University of America,
                  l932.
Subjects:      Curves, Quartic.
               Polygons.
               Triangle.
Other titles:  The self-symmetric quadrilaterals
                  in-and-circumscribed to the triangular-symmetric rational
                  quartic.
Control No.:   6412750

Author:        Tracey, Joshua Irving, b. 1883.
Title:         Covariant curves of the plane rational quintic
                  ...
Published:     [Baltimore] 1914.
Description:   1 p. l., p. [31]-46, 1 l. 31 cm.
LC Call No.:   QA567.T7
Subjects:      Curves, Plane.
               Curves, Quintic.
Control No.:   6363080

Author:        Turner, Bird Margaret, 1877- [from old catalog]
Title:         Plane cubics with a given quadrangle of
                  inflexions ...
Published:     [Baltimore, 1922]
Description:   1 p.l., p. 261-278, 1 l. diagrs. 26 cm.
LC Call No.:   QA567.T8
Subjects:      Curves, Cubic. [from old catalog]
Control No.:   8259705

Author:        Turpin, Walter Stevens, 1910-
Title:         On the fundamental group of a certain class of
                  plane algebraic curves ...
Published:     [Baltimore, 1937]
Description:   2 p.l., p. 529-544, 1 l. diagrs. 25 cm.
LC Call No.:   QA567.T85 1936
Subjects:      Curves, Algebraic. [from old catalog]
               Curves, Plane. [from old catalog]
Control No.:   5966345

Author:        Vaudreuil, Mary Felice, Sister.
Title:         Two correspondences determined by the tangents to
                  a rational cuspidal quartic with a line of symmetry, by
                  Sister Mary Felice Vaudreuil.
Published:     Washington, D.C., Catholic University of America,
                  1931.
Description:   1 p. l., 17 p., 1 l. illus. 23 cm.
LC Call No.:   QA567.V3 1931
Dewey No.:     516.54
Notes:         Thesis (Ph. D.)--Catholic University of America,
                  1931.
Subjects:      Curves, Quartic.
               Polygons.
Control No.:   5940975

Author:        Veillon, Henri, 1865- [from old catalog]
Title:         Über ebene curven dritter ordnung, welche einen
                  mittelpunkt haben ...
Published:     Basel, L. Reinhardt, Universitäts-buchdruckerei,
                  1890.
Description:   38 p., 1 l. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA567.V42
Subjects:      Curves, Cubic. [from old catalog]
Control No.:   9607829

Author:        Vries, Johannes Friedrich de.
Title:         Analytische behandeling van de rationale kromme
                  van den vierden graad in vierdimensionale ruimte ...
Published:     's-Gravenhage, M. Nijhoff, 1922.
Description:   xv, 158 p. 23 cm.
LC Call No.:   QA567.V7
Notes:         Proefschrift--Leiden.
Subjects:      Curves, Quartic.
Control No.:   2162373

Author:        Wear, Luther Ewing, 1881- [from old catalog]
Title:         On self-dual plane curves of the fourth order
                  ...
Published:     [Baltimore, 1920]
Description:   1 p.l., p. 97-118, 1 l. diagrs. 25 cm.
LC Call No.:   QA567.W4
Subjects:      Curves, Quartic. [from old catalog]
Control No.:   8252951

Author:        White, Henry Seely, 1861-1943.
Title:         Plane curves of the third order, by Henry Seely
                  White ... published with the cooperation of the National
                  research council.
Published:     Cambridge, Mass., The Harvard university press,
                  1925.
Description:   xii, 168 p. diagrs. 24 cm.
LC Call No.:   QA567.W7
Subjects:      Curves, Plane.
Other authors: National Research Council (U.S.)
Control No.:   746149

Author:        Wieleitner, Heinrich, 1874-
Title:         Spezielle ebene kurven, von dr. Heinrich
                  Wieleitner.
Published:     Leipzig, G. J. Göschen, 1908.
Description:   xvi, 409 p. diagrs. 20 cm.
Series:        Sammlung Schubert. LVI
LC Call No.:   QA567.W72
Subjects:      Curves, Plane.
               Curves, Transcendental.
Control No.:   5877538

Author:        Willig, Hermann, 1860- [from old catalog]
Title:         Beiträge zur kenntnis der negativen
                  fusspunktscurven,
Published:     Giessen, Druck von W. Keller, 1886.
Description:   16 p., 1 l. 27 x 22 cm.
LC Call No.:   QA567.W73
Subjects:      Curves, Plane. [from old catalog]
Control No.:   9610048

Author:        Wünnenberg, Franz [Carl Anton], 1861- [from old
                  catalog]
Title:         Ueber einige bemerkenswerthe eigenschaften der
                  cissoide ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1884.
Description:   1 p.l., 33, [1] p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA567.W95
Subjects:      Curves, Cubic. [from old catalog]
Control No.:   7738419

Author:        Yerushalmy, Jacob, 1904- [from old catalog]
Title:         Construction of pencils of equianharmonic cubics
                  ...
Published:     [Baltimore, 1931]
Description:   1 p. l., p. 319-332, 1 l. 25 cm.
LC Call No.:   QA567.Y4 1930
Subjects:      Curves, Cubic. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Control No.:   8286345
