#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Askwith, E. H. (Edward Harrison), 1864-
Title:         The analytical geometry of the conic sections by
                  the Rev. E.H. Askwith ... Illustrated with seventy-six
                  diagrams.
Published:     London, A. and C. Black, 1908.
Description:   xiv, 443, [1] p. diagrs. 21 cm.
LC Call No.:   QA552.A8
Subjects:      Geometry, Analytic -- Plane.
Control No.:   2161664

Author:        Barnett, I. A. (Isaac Albert), 1894-
Title:         Plane analytic geometry, by I.A. Barnett ...
Published:     New York, J. Wiley & sons, inc.; London, Chapman
                  & Hall, limited, 1926.
Description:   ix, 269 p. diagrs. 21 cm.
LC Call No.:   QA552.B3
Subjects:      Geometry, Analytic -- Plane.
Control No.:   9204425

Author:        Besant, W. H. (William Henry), 1828-1917.
Title:         Conic sections, treated geometrically,
Edition:       5th ed.
Published:     Cambridge [Eng.] Deighton, Bell, and co.; 1884.
Description:   2 p. l., [vii]-xii, 264 p. diagrs. 17 cm.
LC Call No.:   QA552.B4 1884
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Conic sections.
Control No.:   9750657

Author:        Bôcher, Maxime, 1867-1918.
Title:         Plane analytic geometry, with introductory
                  chapters on the differential calculus, by Maxime Bôcher ...
Published:     New York, H. Holt and Company [c1915]
Description:   xiii, 235 p. diagrs. 20 cm.
LC Call No.:   QA552.B65
Subjects:      Geometry, Analytic.
Control No.:   9645141

Author:        Bohannan, R. D. (Rosser Daniel)
Title:         Plane analytical geometry, by R. D. Bohannan.
Published:     Columbus, O., R. G. Adams & co., 1913.
Description:   151 p. 20 cm.
LC Call No.:   QA552.B7
Subjects:      Geometry, Analytic -- Plane.
Control No.:   7764908

Author:        Briggs, George R[ussell] [from old catalog]
Title:         The elements of plane analytic geometry.
Published:     New York, J. Wiley and sons, 1881.
Description:   iv p., 1 l., 154 p. diagr. 20 cm.
LC Call No.:   QA552.B85
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   7729784

Author:        Briot, M. (Charles), 1817-1882.
Uniform Title: Leçons de géométrie analytique. English
Title:         Briot and Bouquet's elements of analytical
                  geometry of two dimensions.
Edition:       The 14th ed., tr. and ed. by James Harrington
                  Boyd ...
Published:     Chicago, New York, Werner school book company
                  [c1896]
Description:   2 p.l., 581 p. diagr. 23 cm.
LC Call No.:   QA552.B86
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Geometry, Analytic -- Plane.
Other authors: Bouquet, M. (Jean Claude), 1819-1885, joint
                  author.
               Boyd, James Harrington, 1862- ed.
Control No.:   2633874

Author:        Buchanan, Herbert Earle, b. 1881.
Title:         The elements of analytic geometry, / by H. E.
                  Buchanan ... and G. E. Wahlin ...
Published:     New York, Farrar & Rinehart, incorporated
                  [c1937]
Description:   ix, 3-256 p. : illus., diagrs. ; 20 1/2 cm.
LC Call No.:   QA552.B92
Dewey No.:     516.1
Notes:         "Answers": p. 230-254.
Subjects:      Geometry, Analytic -- Plane.
Other authors: Wahlin, Gustaf Eric, 1880- joint author.
Control No.:   7837910

Author:        [Byerly, William Elwood], 1849- [from old
                  catalog]
Title:         Syllabus of a course in plane analytic geometry.
Published:     Boston, Ginn, Heath & co., 1883.
Description:   8 p. 23 cm.
LC Call No.:   QA552.B98
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   10071678

Author:        Byerly, William Elwood, b. 1849.
Title:         Syllabus of a course on modern methods in
                  analytic geometry.
Published:     Boston, Ginn, Heath, & co., 1884.
Description:   8 p. 21 cm.
LC Call No.:   QA552.B99
Notes:         Cover title.
Subjects:      Geometry, Analytic -- Plane.
Control No.:   4052188

Author:        Campbell, Alan D. (Alan Ditchfield), 1891-
Title:         Advanced analytic geometry, by Alan D. Campbell
                  ...
Published:     New York, J. Wiley & sons, inc.; London, Chapman
                  & Hall, limited, 1938.
Description:   x, 310 p. diagrs. 22 cm.
LC Call No.:   QA552.C18
Dewey No.:     516
ISBN:          $4.00
Notes:         "The purpose of this book is to introduce the
                  student to the analytic side of projective geometry."--Pref.
Subjects:      Geometry, Analytic -- Plane.
               Geometry, Projective.
Control No.:   746925

Author:        Candy, Albert L. (Albert Luther), 1857-
Title:         The elements of analytic geometry, by Albert L.
                  Candy ...
Published:     Lincoln, Neb., A.L. Candy, 1900.
Description:   viii, 302 p., 1 l. diagrs. 22 cm.
LC Call No.:   QA552.C21
Subjects:      Geometry, Analytic -- Plane.
Control No.:   3106674

Author:        Casey, John, 1820-1891.
Title:         A treatise on the analytical geometry of the
                  point, line, circle, and conic sections, containing an
                  account of its most recent extensions, with numerous
                  examples. By John Casey ...
Edition:       2d ed., rev. and enl.
Published:     Dublin, Hodges, Figgis, & Co. ltd.; London,
                  Longmans, Green, & Co., 1893.
Description:   xxix, [3], 564 p. incl. diagrs. 20 cm.
Series:        Dublin University Press series
LC Call No.:   QA552.C33
Dewey No.:     513
Subjects:      Geometry, Analytic.
Other titles:  The analytical geometry of the point, line,
                  circle, and conic sections.
Control No.:   7263250

Author:        Chicago. University. University extension
                  division. Home-study dept. [from old catalog]
Title:         Mathematics 103 (plane analytic geometry)
Published:     [Chicago] The University of Chicago, c1941.
Description:   1 p.l., 41 numb. l. diagrs. 28 x 22 cm.
LC Call No.:   QA552.C48
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Other authors: Everett, Harry Scheidy, 1891- [from old catalog]
Control No.:   8318967

Author:        Cobb, Charles W. (Charles Wiggins), 1875-1949.
Title:         Plane analytic geometry, by Charles W. Cobb.
Published:     Norwood, Mass., The Norwood press, 1913.
Description:   1 p. 1, 82 p. diagrs. 19 cm.
LC Call No.:   QA552.C6
Subjects:      Geometry, Analytic -- Plane.
Control No.:   8233577

Author:        Crantz, Paul. [from old catalog]
Title:         Analytische geometrie der ebene, zum
                  selbstunterricht,
Published:     Leipzig und Berlin, B. G. Teubner, 1915.
Description:   p. cm.
LC Call No.:   QA552.C7
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   5901159

Author:        Dette, W.
Title:         Analytische geometrie der kegelschnitte, von W.
                  Dette ... Mit 45 textfiguren.
Published:     Leipzig, Berlin, B.G. Teubner, 1909.
Description:   vi, 232 p. diagrs. 23 cm.
LC Call No.:   QA552.D5
Subjects:      Geometry, Analytic -- Plane.
Control No.:   1689697

Author:        Eddy, Henry T. (Henry Turner), 1844-1921.
Title:         A treatise on the principles and applications of
                  analytic geometry. By Henry T. Eddy ...
Published:     Philadelphia, Cowperthwait & company, 1874.
Description:   200 p. diagr. 23 cm.
LC Call No.:   QA552.E21
Subjects:      Geometry, Analytic -- Plane.
               Curves, Plane.
Control No.:   1217057

Author:        Elliot, William Whitfield, 1898- [from old
                  catalog]
Title:         Introduction to analytic geometry and
                  differentiation,
Published:     Ann Arbor, Mich., Planographic reproduction of
                  author's manuscript by Edwards borthers, inc., 1939.
Description:   2 p.l., 91, [1] p. diagrs. 28 x 22 cm.
LC Call No.:   QA552.E4
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
               Differential calculus.
Other authors: Miles, Edward Roy Cecil, 1896- [from old catalog]
                  joint author.
Control No.:   6911702

Author:        Erler, W. (Wilhelm), 1820-1896.
Title:         Die elemente der kegelschnitte in synthetischer
                  behandlung. Zum gebrauche in der prima höherer lehranstalten
                  bearbeitet von dr. W. Erler ... Mit 30 figuren im text.
Edition:       5. aufl., besorgt von dr. L. Huebner ...
Published:     Leipzig, B.G. Teubner, 1898.
Description:   vi, 60 p. diagrs. 23 cm.
LC Call No.:   QA552.E72 1898
Dewey No.:     516.22
Subjects:      Conic sections.
Other authors: Hübner, L. (Louis), 1850- ed.
Control No.:   3581283

Author:        Erler, Wilhelm, 1820-1896. [from old catalog]
Title:         Einleitung in die analytische geometrie und in
                  die lehre von den kegelschnitten,
Published:     Berlin, F. Dümmler, 1862.
Description:   v, [1] p., 1 l., 69, [1] p. fold. pl. (diagrs.)
                  21 cm.
LC Call No.:   QA552.E7
Subjects:      Geometry, Analytic. [from old catalog]
               Conic sections. [from old catalog]
Control No.:   8762190

Author:        Ferrers, N. M. (Norman Macleod), 1829-1903.
Title:         An elementary treatise on trilinear co-ordinates,
                  the method of reciprocal polars, and the theory of
                  projections, by the Rev. N.M. Ferrers ...
Edition:       3d ed.
Published:     London, Macmillan and Co., 1876.
Description:   xiv, 184 p. diagrs. 20 cm.
LC Call No.:   QA552.F4 1876
Dewey No.:     516.22
Subjects:      Conic sections.
               Reciprocal polars.
Other titles:  Trilinear co-ordinates.
Control No.:   7821900

Author:        Frege, Gottlob, 1848- [from old catalog]
Title:         Ueber eine geometrische darstellung der
                  imaginären gebilde in der ebene ...
Published:     Jena, Druck von A. Neuenhahn, 1873.
Description:   75 p. diagrs. on fold. pl. 20 cm.
LC Call No.:   QA552.F85
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   10096288

Author:        Funkenbusch, William. [from old catalog]
Title:         An outline of army Math "62": Analytic geometry
                  and introduction to calculus,
Published:     [n.p.] c1945.
Description:   5 p.l., 69 numb. l. diagrs. 29 cm.
LC Call No.:   QA552.F9
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
               Differential calculus.
Other authors: United States. Army service forces. Army
                  specialized training division. [from old catalog]
Control No.:   5996577

Author:        Grandi, Guido, 1671-1742. [from old catalog]
Title:         Instituzioni delle sezioni coniche del padre d.
                  Guido Grandi ...
Published:     In Firenze, Nella stamperia di S. A. R. per Gio:
                  Gaetano Tartini, e Santi Franchi, 1744.
Description:   1 p.l., v-xii, 147, [1] p. 140 diagr. on xii
                  fold. pl. 23 cm.
LC Call No.:   QA552.G73 (Rare bk. coll.)
Subjects:      Conic sections. [from old catalog]
Other authors: Perelli, Tommaso, 1704-1783. [from old catalog]
Control No.:   9218451

Author:        Grelle, Friedrich, 1836-1878.
Title:         Analytische Geometrie der Ebene / von Friedrich
                  Grelle.
Edition:       2., gänzliche umgearbeitete Aufl.
Published:     Hannover : Carl Rümpler, 1875.
Description:   xi, 189 p. : ill. ; 24 cm.
LC Call No.:   QA552.G73x 1875
Subjects:      Geometry, Analytic -- Plane.
Control No.:   3818828

Author:        Hamilton, Henry Parr, 1794-1880. [from old
                  catalog]
Title:         An analytical system of conic sections:
Edition:       5th ed.
Published:     Cambridge, Printed at the University press,
                  1843.
Description:   p. cm.
LC Call No.:   QA552.H21
Subjects:      Geometry, Analytic. [from old catalog]
Control No.:   6325167

Author:        Harris, A. W. (Abram Winegardner), 1858-1935.
Title:         Lessons in mathematical drawing.
Published:     Orono, Me., The authors, 1900.
Description:   36 p. cm.
LC Call No.:   QA552.H31
Subjects:      Geometry, Analytic -- Plane.
Other authors: Hart, James Norris, 1861-1959.
Control No.:   5848593

Author:        Hesse, Ludwig Otto, 1811-1874.
Title:         Vorlesungen aus der analytischen geometrie der
                  geraden linie, des punktes und des kreises in der ebene. Von
                  dr. Otto Hesse ... Mit 13 in den text gedruckten
                  holzschnitten.
Published:     Leipzig, B.G. Teubner, 1865.
Description:   viii, 182 p. diagrs. 24 cm.
LC Call No.:   QA552.H58
Notes:         Appended is the author's Vier vorlesungen aus der
                  analytischen geometrie. Leipzig, 1866.
Subjects:      Geometry, Analytic -- Plane.
Control No.:   1689102

Author:        Jones, A. Clement (Alfred Clement), 1871-
Title:         Notes on analytical geometry; an appendix. By A.
                  Clement Jones ...
Published:     Oxford, Clarendon press, 1903.
Description:   2 p.l., 171, [1] p. diagrs. 20 cm.
LC Call No.:   QA552.J77
Notes:         "Examples for exercise": p. [143]-163.
               "The present work ... is written rather by way of
                  appendix to the ordinary text-book, than as an attempt to
                  impart the rudiments of the subject."--Pref.
Subjects:      Geometry, Analytic -- Plane.
Control No.:   4052260

Author:        La Hire, Philippe de, 1640-1718.
Title:         Sectiones conicæ in novem libros distribvtæ, in
                  quibus quidquid hactenus observatione dignum ... traditum est
                  ... explicatur ...
Published:     Parisiis, apud Stephanum Michallet, 1685.
Description:   4 p.l., 249, [1] p. diagrs. 38 cm.
LC Call No.:   QA552.L2
Subjects:      Conic sections. [from old catalog]
Other authors: Apollonius Pergaeus. [from old catalog]
Control No.:   7389357

Author:        Lacroix, S. F. (Silvestre François), 1765-1843.
Uniform Title: Traité élémentaire de trigonometrie rectiligne
                  et sphérique. English
Title:         An elementary treatise on plane and spherical
                  trigonometry, and on the application of algebra to geometry
                  from the mathematics of Lacroix and Bézout. Translated from
                  the French for the use of the students of the university at
                  Cambridge, New England.
Published:     Cambridge, N.E. Printed by Hilliard and Metcalf,
                  At the University Press. Sold by W. Hilliard, Cambridge, and
                  by Cummings & Hilliard, No. 1 Cornhill, Boston. 1820.
Description:   iv p., 1 l., 162 p. diagrs. on v fold. pl. 23
                  cm.
LC Call No.:   QA552.L148
Notes:         Translated by John Farrar.
               The treatise on plane and spherical trigonometry
                  is from Lacroix's Traité élémentaire de trigonométrie
                  rectiligne et sphérique; the chapter on the application of
                  algebra to geometry is from E. Bézout's Cours de
                  mathématiques, à l'usage des gardes du pavillon et de la
                  marine.
Subjects:      Trigonometry.
               Geometry, Analytic -- Plane.
Other authors: Farrar, John, 1779-1853, tr.
               Bézout, Etienne, 1730-1783.
Control No.:   1216964

Author:        Lacroix, Silvestre François, 1765-1843. [from
                  old catalog]
Title:         An elementary treatise on plane and spherical
                  trigonometry,
Edition:       3d ed.
Published:     Boston, Hilliard, Gray and co., 1833.
Description:   iv p., 1 l., 165 p. diagrs. on v. fold. pl. 25
                  cm.
LC Call No.:   QA552.L15
Subjects:      Trigonometry. [from old catalog]
               Geometry, Analytic -- Plane. [from old catalog]
Other authors: Farrar, John, 1779-1853, [from old catalog] tr.
               Bézout, Étienne, 1730-1783. [from old catalog]
Control No.:   8663545

Author:        Lennes, N. J. (Nels Johann), 1871-
Title:         Plane analytic geometry, by N. J. Lennes and A.
                  S. Merrill. With the editorial cooperation of H. E. Slaught.
Published:     New York and London, Harper, 1929.
Description:   xv p., 1 l., 305 p. diagrs. 21 cm.
LC Call No.:   QA552.L4
Subjects:      Geometry, Analytic -- Plane.
Other authors: Merrill, A. S. (Archibald Shepard), 1887- joint
                  author.
               Slaught, H. E. (Herbert Ellsworth), 1861-1937,
                  ed.
Control No.:   9682108

Author:        L'Hospital, Guillaume François Antoine de,
                  marquis de Sainte-Mesme, 1661-1704. [from old catalog]
Title:         An analytick treatise of conick sections, and
                  their use for resolving of equations in determinate and
                  indeterminate problems.
Published:     London, 1723.
Description:   p. cm.
LC Call No.:   QA552.L52 1723
Subjects:      Conic sections. [from old catalog]
Other authors: Stone, Edmund, d. 1768, tr.
Control No.:   5858728

Author:        L'Hospital, marquis de (Guillaume François
                  Antoine), 1661-1704.
Title:         Traité analytique des sections coniques et de
                  leur usage pour la resolution des equations dan les
                  problêmes tant déterminez qu'indéterminez. Ouvrage
                  posthume de m. le marquis de l'Hospital ...
Published:     Paris, Veuve de J. Boudot et J. Boudot fils,
                  1707.
Description:   1 p.l., 459, [2] p. diagrs. on 32 (i.e. 33) fold.
                  pl. 26 x 20 cm.
LC Call No.:   QA552.L5 1707
Dewey No.:     516.22
Notes:         Title vignette (publisher's device)
               Head-piece.
Subjects:      Conic sections -- Early works to 1800.
Control No.:   2163064

Author:        L'Hospital, marquis de (Guillaume François
                  Antoine), 1661-1704.
Title:         Traité analytique des sections coniques : et de
                  leur usage pour la resolution des equations dans les
                  problèmes tant déterminez qu'indéterminez / ouvrage
                  posthume de M. le marquis de l'Hospital ...
Published:     A Paris : Chez Montalant ..., 1720.
Description:   [8], 459 p., [34] leaves of plates (33 folded) :
                  charts ; 25 cm. (4to)
LC Call No.:   QA552.L5 1720
Notes:         33 of the leaves are numbered, one is not
                  numbered or folded.
Subjects:      Conic sections.
Control No.:   7263148

Author:        Mills, Clifford Newton, b. 1886.
Title:         Introduction to plane analytical geometry and
                  differential calculus, by Clifford Newton Mills ... with 95
                  illustrations.
Published:     Philadelphia, P. Blakiston's son & co. [c1922]
Description:   xi, 131 p. illus., diagrs. 20 cm.
LC Call No.:   QA552.M5
Subjects:      Geometry, Analytic -- Plane.
               Differential calculus.
Control No.:   4526487

Author:        Newton, Isaac, Sir, 1642-1727.
Uniform Title: Enumeratio linearum tertii ordinis
Title:         Isaaci Newtoni Enumeratio linearum tertii ordinis
                  : sequitur illustratio ejusdem tractatus / auctore Jacobo
                  Stirling.
Published:     Parisiis : Impensis J.B.M. Duprat ..., 1797.
Description:   viij, 198, [2] p., VI, [3] folded leaves of
                  plates : ill. ; 21 cm. (8vo)
LC Call No.:   QA552.N39 1797
Notes:         Half title: Lineae tertii ordinis Newtonianae.
               Signatures: pip4s A-Mp8s Np4s.
Subjects:      Geometry, Analytic -- Plane -- Early works to
                  1800.
Other authors: Stirling, James, 1692-1770.
Other titles:  Enumeratio linearum tertii ordinis.
               Lineae tertii ordinis Newtonianae.
Control No.:   2400339

Author:        O'Brien, M. (Matthew), 1814-1855.
Title:         A treatise on plane co-ordinate geometry; or, The
                  application of the method of co-ordinates to the solution of
                  problems in plane geometry. Pt. 1. By the Rev. M. O'Brien
                  ...
Published:     Cambridge, Deighton's [etc. etc.] 1844.
Description:   xii, 180 p. 5 fold pl. 22 cm.
LC Call No.:   QA552.O13
Subjects:      Geometry, Analytic -- Plane.
Control No.:   3106792

Author:        Olney, Edward, 1827-1887. [from old catalog]
Title:         A general geometry and calculus.
Published:     New York, Sheldon and company [c1870]
Description:   1 p. l., 92 p. diagr. 21 cm.
LC Call No.:   QA552.O51
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   8198490

Author:        Prado, Eduardo. [from old catalog]
Title:         Nociones de geometria analitica de dos
                  dimensiones
Published:     Mexico, Tip. economica, 1908.
Description:   342 p. diagrs. 23 cm.
LC Call No.:   QA552.P8
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   5883888

Author:        Puckle, George Hale. [from old catalog]
Title:         An elementary treatise on conic sections and
                  algebraic geometry,
Edition:       4th ed.
Published:     London, Macmillan and co., 1870.
Description:   vi p., 1 l., 362 p. diagrs. 20 cm.
LC Call No.:   QA552.P85 1870
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   6901193

Author:        Ransom, William Richard, 1876-
Title:         Graphical analysis; elements of analytic geometry
                  with applications preparatory to the study of the sciences
                  and the calculus, by William R. Ransom ...
Published:     [Medford, Mass.] Tufts College, 1946.
Description:   xi, 207 p. diagrs. 22 cm.
LC Call No.:   QA552.R3
Dewey No.:     516
Notes:         Reproduced from type-written copy.
Subjects:      Geometry, Analytic.
               Graphic methods.
Other authors: Tufts University.
Control No.:   6470398

Author:        Robinson, Robin, 1903- [from old catalog]
Title:         Notes on trigonometry,
Edition:       8th ed.
Published:     [Hanover, N.H.] c1944.
Description:   2 p.l., 2-124 numb. l. diagrs 28 x 23 cm .
LC Call No.:   QA552.R6 1944
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
               Plane trigonometry.
Control No.:   6930851

Author:        Rosanoff, M. A. (Martin André), b. 1874.
Title:         Select topics of plane analytic geometry for
                  scientific and technical workers [by] M. A. Rosanoff.
Published:     Brooklyn, N.Y., Long Island University Press
                  [1944]
Description:   viii, 76 p. diagrs. 23 cm.
LC Call No.:   QA552.R63
Dewey No.:     516.1
Notes:         Cover title: Analytic geometry.
Subjects:      Geometry, Analytic -- Plane.
Control No.:   8804425

Author:        Runge, Carl, 1856-1927.
Title:         Analytische geometrie der ebene, von C. Runge ...
                  mit 75 figuren im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1908.
Description:   2 p.l., 198 p. diagrs. 23 cm.
LC Call No.:   QA552.R85
Subjects:      Geometry, Analytic -- Plane.
Control No.:   1217646

Author:        Runkle, John D. (John Daniel), 1822-1902.
Title:         Elements of plane analytic geometry. By John D.
                  Runkle.
Published:     Boston, Ginn & company, 1888.
Description:   1 p. l., 344 p. diagr. 22 cm.
LC Call No.:   QA552.R94
Subjects:      Geometry, Analytic -- Plane.
Control No.:   7261674

Author:        Sñagajlo, Adolf, 1806-1877. [from old catalog]
Title:         Zasady geometryi analitycznej: geometrya plaska;
Published:     Paryçz, Nakladem Biblioteki kórnickiej, 1877-
Description:   1 v. diagrs. 31 x 24 cm.
LC Call No.:   QA552.S12
Subjects:      Geometry, Analytic. [from old catalog]
Other authors: Painvin, Louis Félix, 1826-1875? [from old
                  catalog]
Control No.:   6802122

Author:        Salmon, George, 1819-1904.
Title:         Analytische geometrie der kegelschnitte, mit
                  besonderer berücksichtigung der neueren methoden.
Edition:       7. aufl.
Published:     Leipzig, B.G. Teubner, 1907-18.
Description:   p. cm.
LC Call No.:   QA552.S23
Subjects:      Geometry, Analytic -- Plane.
Other authors: Fiedler, Wilhelm, 1832-1912, ed.
               Dingeldey, Friedrich, 1859- [from old catalog]
                  ed.
Control No.:   7369744

Author:        Salmon, George, 1819-1904.
Title:         A treatise on conic sections, containing an
                  account of some of the most important modern algebraic and
                  geometric methods.
Published:     Dublin, Hodges and Smith, 1848.
Description:   2 p.l., 300 p. diagrs. 22 cm.
LC Call No.:   QA552.S17
Subjects:      Geometry, Analytic -- Plane.
Control No.:   9129383

Author:        Salmon, George, 1819-1904.
Title:         A treatise on conic sections : containing an
                  account of some of the most important modern algebraic and
                  geometric methods / by George Salmon.
Edition:       6th ed.
Published:     London : New York : Bombay : Longmans, Green, and
                  Co., 1879.
Description:   xv, 399 p. : ill. ; 23 cm.
LC Call No.:   QA552.S17 1879
Dewey No.:     516.22
Notes:         Includes index.
Subjects:      Geometry, Analytic -- Plane.
               Conic sections.
               Geometry, Projective.
Control No.:   7840148

Author:        Salmon, George, 1819-1904.
Title:         A treatise on conic sections: containing an
                  account of some of the most important modern algebraic and
                  geometric methods. By George Salmon.
Edition:       5th ed.
Published:     London, Longmans, Green, Reader, and Dyer, 1869.
Description:   xv, 377 p. diagrs. 23 cm.
LC Call No.:   QA552.S17 1869
Subjects:      Geometry, Analytic -- Plane
Control No.:   10158004

Author:        Scott, Charlotte Angas, b. 1858.
Title:         An introductory account of certain modern ideas
                  and methods in plane analytical geometry, by Charlotte Angas
                  Scott ...
Published:     London, New York, Macmillan and co., 1894.
Description:   xii, 288 p. diagrs. 23 cm.
LC Call No.:   QA552.S42
Subjects:      Geometry, Analytic -- Plane.
Control No.:   2634260

Author:        Simon, Maximilain, 1844- [from old catalog]
Title:         Analytische geometrie der ebene,
Published:     Leipzig, G. J. Göschen, 1900.
Description:   p. cm.
LC Call No.:   QA552.S59 1900
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   7727549

Author:        Simon, Maximilian, 1844-
Title:         Analytische Geometrie der Ebene, von Max Simon
                  ... Mit 45 Abbildungen.
Published:     Leipzig, G.J. Göschen, 1897.
Description:   2 p. l., 7-203 p. diagrs. 16 cm.
Series:        Sammlung Göschen. [bd. 65]
LC Call No.:   QA552.S59 1897
Subjects:      Geometry, Analytic -- Plane.
Control No.:   7305799

Author:        Simon, Maximilian, 1844-1918.
Title:         Analytische Geometrie der Ebene / von Max Simon.
Edition:       3d ed. Mit 96 Figuren.
Published:     Leipzig : G.J. Göschen, 1900.
Description:   vii, 372 p. : illus. ; 20 cm.
Series:        Sammlung Göschen ; Bd. 8
LC Call No.:   QA552.S6
Notes:         The 2d edition was issued as no. 65 of Sammlung
                  Göschen.
Subjects:      Geometry, Analytic -- Plane.
Control No.:   5856069

Author:        Simon, Maximilian, 1844-1918. [from old catalog]
Title:         Analytische geometrie der ebene,
Edition:       3., verb. aufl.
Published:     Neudruck. Berlin und Leipzig, W. de Gruyter &
                  co., 1919.
Description:   p. cm.
LC Call No.:   QA552.S6 1919
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   9735458

Author:        Simon, Maximilian, 1844-1918. [from old catalog]
Title:         Analytische geometrie der ebene,
Edition:       2., verb. aufl.,
Published:     Leipzig, G. J. Göschen, 1903.
Description:   p. cm.
LC Call No.:   QA552.S6 1903
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
Control No.:   7821600

Author:        Smart, W. M. (William Marshall), 1889-
Title:         Foundations of analytical geometry.
Published:     London, New York, Longmans, Green [1956]
Description:   249 p. 23 cm.
LC Call No.:   QA552.S64
Dewey No.:     516
Subjects:      Geometry, Analytic -- Plane.
Control No.:   6543931

Author:        Smyth, William, 1797-1868.
Title:         Elements of analytic geometry,
Published:     Hallowell [Me.] Glazier Masters & co.; 1836.
Description:   iv, [5]-112 p. 3 fold. pl. 22 cm.
LC Call No.:   QA552.S66
Subjects:      Geometry, Analytic -- Plane.
Control No.:   5857279

Author:        Spain, Barry.
Title:         Analytical geometry.
Published:     Oxford, Pergamon Press; New York, Macmillan
                  [1963]
Description:   143 p. illus. 20 cm.
Series:        The Commonwealth and international library of
                  science, technology, engineering, and liberal studies.
                  Mathematics division, v. 9
LC Call No.:   QA552.S65 1963
Dewey No.:     516
Notes:         "161."
Subjects:      Geometry, Analytic -- Plane.
Control No.:   7977282

Author:        Staude, Otto, 1857-1928.
Title:         Analytische geometrie der kubischen
                  kegelschnitte, von dr. Otto Staude ... Mit 58 figuren im
                  text.
Published:     Leipzig, Berlin, B.G. Teubner, 1913.
Description:   viii, 242 p. diagrs. 23 cm.
Series:        B.G. Teubners sammlung von lehrbüchern auf dem
                  gebiete der mathematischen wissenschaften, mit einschluss
                  ihrer anwendungen. bd. XXXVIII
LC Call No.:   QA552.S77
ISBN:          DM10.00
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Conic sections.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit Einschluss
                  ihrer Anwendungen ; Bd. XXXVIII.
Control No.:   3107635

Author:        Staude, Otto, 1857-1928.
Title:         Analytische geometrie des punktes, der geraden
                  linie und der ebene. Ein handbuch zu den vorlesungen und
                  übungen über analytische geometrie, von Dr. Otto Staude ...
                  Mit 387 figuren im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1905.
Description:   viii, 447, [1] p. diagrs. 23 cm.
Series:        B.G. Teubner's Sammlung von lehrbüchern auf dem
                  gebiete der mathematischen wissenschaften mit einschluss
                  ihrer anwendungen. bd. xvi
LC Call No.:   QA552.S79
Subjects:      Geometry, Analytic -- Plane.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit einschluss
                  ihrer Anwendungen ; Bd. XVI.
Control No.:   2634203

Author:        Stirling, James, 1692-1770.
Title:         Lineae tertii ordinis Neutonianae, sive,
                  Illustratio tractatus D. Neutoni De enumeratione linearum
                  tertii ordinis : cui subjungitur, solutio trium problematum /
                  authore Jacobo Stirling ...
Published:     Oxoniae : ... Impensis Edvardi Whistler
                  Bibliopolae Oxoniensis, 1717.
Description:   [12], 128, 19, [1] p. : ill. (woodcuts) ; 20 cm.
                  (8vo)
LC Call No.:   QA552.S57x 1717
Notes:         "A catalogue of the subscribers names to this
                  work": p. [5]-[12]
               Signatures: ap2s bp4s A-Qp4s *A-*Bp4s
                  *Cp2s.
Subjects:      Geometry, Analytic -- Plane -- Early works to
                  1800.
Other authors: Newton, Isaac, Sir, 1692-1770. Enumeratio
                  linearum tertii ordinis.
Other titles:  Illustratio tractatus D. Neutoni De enumeratione
                  linearum tertii ordinis.
Control No.:   3818742

Author:        Taylor, Charles, 1840-1908.
Title:         An introduction to the ancient and modern
                  geometry of conics, being a geometrical treatise on the conic
                  sections with a collection of problems and historical notes
                  and prolegomena, by Charles Taylor ...
Published:     Cambridge [Eng.] Deighton, Bell and co.; London,
                  G. Bell and sons, 1881.
Description:   lxxxviii, 384 p. diagrs. (part fold.) 23 cm.
LC Call No.:   QA552.T3
Dewey No.:     516.22
Subjects:      Conic sections.
Control No.:   3108586

Author:        Studniˆcka, F. J. (Frantiˆsek Josef), 1836-1903.
Title:         Úvod do analytické geometrie v rovinˆe. Sepsal
                  ... Dr. F.J. Studniˆcka ... (S. ˆcetnymi illustracemi)
Published:     V Praze, Nákladem Jednoty ˆceských matematikêu,
                  1902.
Description:   242, [2] p. diagrs. 24 cm.
Series:        Sbornik Jednoty ˆceských matematikêu v Praze.
                  ˆcislo VII
LC Call No.:   QA552.S93
Notes:         "Literatura": p. [10]
Subjects:      Geometry, Analytic -- Plane.
Series Entry:  Jednota ˆceskoslovenských matematikêu a fyzikêu
                  v Praze. Sbornik ; cislo 7.
Control No.:   5856657

Author:        Taylor, Howard Edward, 1922-
Title:         Subsets of the plane: plane analytic geometry
                  [by] Howard E. Taylor [and] Thomas L. Wade.
Published:     New York, Wiley [1962]
Description:   97 p. illus. 26 cm.
LC Call No.:   QA552.T34
Dewey No.:     516.3
Subjects:      Geometry, Analytic -- Plane.
Other authors: Wade, Thomas Leonard, 1905- joint author.
Control No.:   4531215

Author:        Todhunter, I. (Isaac), 1820-1884.
Title:         A treatise on plane co-ordinate geometry as
                  applied to the straight line and the conic sections : with
                  numerous examples / by I. Todhunter.
Published:     London ; New York : Macmillan, 1888
Description:   vi, 358 p. : ill. ; 19 cm.
LC Call No.:   QA552.T62x 1888
Subjects:      Geometry, Analytic.
               Conic sections.
Control No.:   511477

Author:        Wentworth, G. A. (George Albert), 1835-1906.
Title:         Elements of analytic geometry.
Published:     Boston, Ginn & company, 1886.
Description:   vi, 221, 26 p. diagr. 19 cm.
LC Call No.:   QA552.W47
Subjects:      Geometry, Analytic -- Plane.
Control No.:   9134881

Author:        Albert, A. Adrian (Abraham Adrian), 1905-
Title:         Solid analytic geometry.
Edition:       1st ed.
Published:     New York, McGraw-Hill, 1949.
Description:   ix, 162 p. diagrs. 24 cm.
LC Call No.:   QA553.A58
Dewey No.:     516.3
Subjects:      Geometry, Analytic -- Solid.
Control No.:   7420579

Author:        Aldis, W. Steadman (William Steadman),
                  1839-1928.
Title:         An elementary treatise on solid geometry, by W.
                  Steadman Aldis ...
Edition:       4th ed., rev.
Published:     Cambridge [Eng.] Deighton, Bell, and co.; London,
                  G. Bell and sons, 1886.
Description:   viii, 276 p. diagrs, 19 cm.
LC Call No.:   QA553.A6 1886
Subjects:      Geometry, Analytic -- Solid.
               Geometry, Differential.
Control No.:   1691394

Author:        Aldis, William Steadman, 1839-1928. [from old
                  catalog]
Title:         An elementary treatise on solid geometry,
Published:     Cambridge [Eng.] Deighton, Bell, and co.; 1865.
Description:   viii, 188 p. diagrs. 23 cm.
LC Call No.:   QA553.A6
Subjects:      Geometry, Analytic -- Solid. [from old catalog]
               Geometry, Differential. [from old catalog]
Control No.:   8306395

Author:        Bourget, J. (Justin), 1822-1887.
Title:         Géométrie analytique à trois dimensions, par
                  J. Bourget et Ch. Housel.
Published:     Paris, Hachette et cie, 1872.
Description:   2 p. L., iv, 435 p. diagrs. 22 cm.
LC Call No.:   QA553.B6
Dewey No.:     516.3
Subjects:      Geometry, Analytic -- Solid
Other authors: Housel, Ch. (Charles), b. 1817.
Control No.:   8290430

Author:        Byerly, William Elwood, b. 1849.
Title:         Syllabus of a course in analytical geometry of
                  three dimensions.
Published:     Boston, Ginn, Heath & co., 1884.
Description:   10 p. 23 cm.
LC Call No.:   QA553.B9
Notes:         Cover title.
Subjects:      Geometry, Analytic -- Solid.
Control No.:   2161092

Author:        Carnoy, Joseph Antoine, 1841-1906. [from old
                  catalog]
Title:         Cours de géométrie analytique,
Edition:       2. éd.
Published:     Louvain, P. Desbarax, 1877.
Description:   v. diagrs. 25 cm.
LC Call No.:   QA553.C3 1877.
Subjects:      Geometry, Analytic -- Solid. [from old catalog]
Control No.:   10007639

Author:        Dresden, Arnold, b. 1882.
Title:         Solid analytical geometry and determinants, by
                  Arnold Dresden ...
Published:     New York, J. Wiley & Sons, inc.; London, Chapman
                  & Hall, limited, 1930.
Description:   1 p. l., x, 310 p. incl. illus., diagrs. 23 cm.
LC Call No.:   QA553.D7
Dewey No.:     516
Subjects:      Geometry, Analytic -- Solid.
               Determinants.
Control No.:   5937196

Author:        Gregory, D. F. (Duncan Farquharson), 1813-1844.
Title:         A treatise on the application of analysis to
                  solid geometry ... Commenced by D. F. Gregory ... Concluded
                  by W. Walton.
Edition:       2d ed.
Published:     Cambridge, J. Deighton; [etc.,etc.] 1852.
Description:   310 p. illus. 22 cm.
LC Call No.:   QA553.G9
Subjects:      Geometry, Analytic -- Solid.
Other authors: Walton, William, 1813-1901, joint author.
Control No.:   9603394

Author:        Haussner, Robert Karl Hermann, 1863-1948.
Title:         Analytische geometrie des raumes, von dr. Robert
                  Haussner ... Mit 36 figuren im text.
Published:     Berlin, Leipzig, W. de Gruyter & co., 1935.
Description:   132 p. diagrs. 16 cm.
Series:        Sammlung Göschen. [89]
LC Call No.:   QA553.H3
Subjects:      Geometry, Analytic -- Solid.
Control No.:   8307148

Author:        Hesse, Ludwig Otto, 1811-1874.
Title:         Vorlesungen über analytische geometrie des
                  raumes.
Edition:       2. aufl.
Published:     Leipzig, B. G. Teubner, 1869.
Description:   xvi, 456 p. 23 cm.
LC Call No.:   QA553.H58
Subjects:      Geometry, Analytic -- Solid. [from old catalog]
Control No.:   8199518

Author:        Hesse, Ludwig Otto, 1811-1874.
Title:         Vorlesungen über analytische geometrie des
                  raumes, insbesondere über oberflächen zweiter ordnung, von
                  Otto Hesse. Revidiert und mit zusätzen versehen von dr. S.
                  Gundelfinger ...
Edition:       3. aufl.
Published:     Leipzig, B.G. Teubner, 1876.
Description:   xvi, 546 p. 23 cm.
LC Call No.:   QA553.H58 1876
Dewey No.:     516.3
Notes:         Errata slip attached to p. [449]
               "Dieses lehrbuch verdankt seine entstehung den
                  universitäts-vorträgen, welche ich in Königsberg, Halle
                  und Heidelberg ... gehalten habe."--Vorrede zur 1. aufl.,
                  1861.
               "Anhang. Planeten-bewegung": p. [526]-546.
Subjects:      Geometry, Analytic -- Solid.
Other authors: Gundelfinger, S. (Sigmund), 1846-1910, ed.
Control No.:   2162909

Author:        Hymers, J. (John), 1803-1887.
Title:         A treatise on analytical geometry of three
                  dimensions : containing the theory of curve surfaces and of
                  curves of double curvature / by John Hymers.
Published:     Cambridge : J. & J. J. Deighton, 1830.
Description:   xv, 178 p. : illus. ; 22 cm.
LC Call No.:   QA553.H9
Subjects:      Geometry, Analytic -- Solid.
Control No.:   7261675

Author:        Ohm, Georg Simon, 1789-1854.
Title:         Elemente der analytischen geometrie im raume am
                  schiefwinkligen coordinatensysteme, von Dr. G.S. Ohm ...
Published:     Nürnberg, J.L. Schrag, 1849.
Description:   xii, 590, [2] p. 6 diagr. on 1 fold pl. 26 x 22
                  cm.
Series:        Beiträge zur molecular-physik, von Dr. G.S. Ohm,
                  1. bd.
LC Call No.:   QA553.O38
Subjects:      Geometry, Analytic -- Solid.
Series Entry:  Beiträge zur Molecular-Physik ; 1. Bd.
Control No.:   744785

Author:        Olmsted, John Meigs Hubbell, 1911-
Title:         Solid analytic geometry, by John M.H. Olmsted
                  ...
Published:     New York, London, D. Appleton-Century company,
                  inc. [1947]
Description:   xiii, 257 p. diagrs. 22 cm.
Series:        The Appleton-Century mathematics series
LC Call No.:   QA553.O45
Dewey No.:     516.3
Notes:         "Answers": p. 235-250.
Subjects:      Geometry, Analytic -- Solid.
Control No.:   1691863

Author:        Salmon, George, 1819-1904.
Title:         A treatise on the analytic geometry of three
                  dimensions, by George Salmon ... rev. by Reginald A.P. Rogers
                  ...
Edition:       5th ed. ...
Published:     London, New York, Longmans, Green and co.; [etc.,
                  etc.] 1912-15.
Description:   2 v. plates, diagrs. 23 cm.
LC Call No.:   QA553.S2 1912
Notes:         "Index of authors cited": vol. I p. 469-470; vol.
                  II p. 333-334.
Subjects:      Geometry, Analytic -- Solid.
               Surfaces.
Other authors: Rogers, Reginald A. P. (Reginald Arthur Percy),
                  b. 1874, ed.
Control No.:   3580159

Author:        Salmon, George, 1819-1904.
Title:         A treatise on the analytic geometry of three
                  dimision, by George Salmon...
Published:     Dublin, Hodges, Figgis, & co., 1882.
Description:   xix, [1], 612 p. 23 cm.
LC Call No.:   QA553.S2 1882
Subjects:      Geometry, Analytic -- Solid.
               Surfaces.
Control No.:   7729047

Author:        Simon, Maximilian, 1844-1918.
Title:         Analytische Geometrie des Raumes, von dr. Max
                  Simon.
Published:     Leipzig, G. J. Göschen, 1900-01.
Description:   2 v. diagr. 20 cm.
Series:        Sammlung Schubert, 9, 25
LC Call No.:   QA553.S6
Notes:         1. t. Gerade, Ebene, Kugel.--2. t. Die flächen
                  zweiten Grades.
Subjects:      Geometry, Analytic -- Solid.
Control No.:   8197286

Author:        Simon, Maximilian, 1844-1918.
Title:         Analytische Geometrie des Raumes, von Max Simon. 
                  Mit 28 Abbildungen.
Published:     Leipzig, G. J. Göschen, 1898.
Description:   200 p. diagr. 16 cm.
Series:        Sammlung Göschen, Bd. 89
LC Call No.:   QA553.S59
Subjects:      Geometry, Analytic -- Solid.
Control No.:   10069457

Author:        Simon, Maximilian, 1844-1918. [from old catalog]
Title:         Analytische geometrie des raumes,
Edition:       3., verb. aufl.
Published:     Neudruck, Berlin und Leipzig, G. J. Göschen,
                  1919.
Description:   p. cm.
LC Call No.:   QA553.S613
Subjects:      Geometry, Analytic -- Solid. [from old catalog]
Control No.:   692545

Author:        Smith, Charles, 1844-1916. [from old catalog]
Title:         An elementary treatise on solid geometry,
Published:     London, Macmillan and co., limited, 1920.
Description:   xv, 242 p. diagrs. 23 cm
LC Call No.:   QA553.S63
Subjects:      Geometry, Analytic -- Solid. [from old catalog]
Control No.:   9665448

Author:        Spencer, Walter A.
Title:         Basic principles of analytic geometry, by Walter
                  A. Spencer ...
Published:     Chicago, The Orthovis company, 1939.
Description:   iv, 27, [1] p. illus. (part col.) 28 cm.
LC Call No.:   QA553.S68
Dewey No.:     516
Notes:         "Ortho-scope" in pocket on lining paper.
               "Published February, 1939."
Subjects:      Geometry, Analytic -- Solid.
Control No.:   3581530

Author:        Venable, Charles S. (Charles Scott), 1827-1900.
Title:         Notes on elements of (analytical) solid geometry.
                  By Chas. S. Venable ...
Published:     New York, University Publishing Company [1879]
Description:   107 p., 2 l. 21.5 cm.
LC Call No.:   QA553.V4
Notes:         "Additional exercises":  2 leaves at end in
                  manuscript.
Subjects:      Geometry, Analytic -- Solid.
Control No.:   6434589

Author:        Vyvyan, T. G. (Thomas Grenfell)
Title:         Introduction to plane trigonometry / by T.G.
                  Vyvyan.
Edition:       3rd. ed., rev.
Published:     Cambridge : Deighton, Bell and Co., 1885.
Description:   viii, 127, 20 p. : ill. ; 19 cm.
Series:        Cambridge mathematical series
LC Call No.:   QA553.V98x 1885
Notes:         Publisher's advertisements: 20 p. at end.
Subjects:      Plane trigonometry.
Control No.:   3818822

Author:        Ball, Richard William, 1923- [from old catalog]
Title:         Dualities of finite projective planes.
Published:     Urbana, 1948.
Description:   3 p. 23 cm.
LC Call No.:   QA554.B3
Subjects:      Geometry, Projective. [from old catalog]
               Congruences and residues. [from old catalog]
Control No.:   9292612

Author:        Emch, Arnold, b. 1871.
Title:         An introduction to projective geometry and its
                  applications; an analytic and synthetic treatment, by Arnold
                  Emch ...
Edition:       1st ed. 1st thousand.
Published:     New York, J. Wiley & sons; London, Chapman &
                  Hall, limited, 1905.
Description:   vii, 267 p. diagrs. 24 cm.
LC Call No.:   QA554.E53
Subjects:      Geometry, Projective.
               Geometry, Analytic -- Plane.
Control No.:   1689293

Author:        Geiser, C[arl] F[riedrich], 1843- [from old
                  catalog]
Title:         Beiträge zur synthetischen geometrie
Published:     Zürich, Schabelitz'sche buchhandlung (C.
                  Schmidt) 1866.
Description:   36 p. 24 cm.
LC Call No.:   QA554.G31
Subjects:      Geometry, Projective. [from old catalog]
               Conic sections. [from old catalog]
               Curves, Plane. [from old catalog]
Control No.:   5862081

Author:        Grassmann, Hermann Ernst, 1857-1922.
Title:         Projektive Geometrie der Ebene unter Benutzung
                  der Punktrechnung dargestellt, von Herman Grassmann.
Published:     Leipzig und Berlin, B. G. Teubner, 1909-27.
Description:   3 v. illus. 26 cm.
LC Call No.:   QA554.G7
Notes:         "Nachwort" (v. 2, pt. 2) signed: G. Wolff.
               1. Bd. Binäres.--2. Bd. 1-2. T. Ternäres.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Geometry, Projective.
Other authors: Wolff, G. (Gunther), 1932- ed.
Control No.:   6866001

Author:        Halstenbach, Wilhelm, 1835- [from old catalog]
Title:         De relatione figurarum planarum quae cyclatio
                  (==kreisverwandtschaft) dicitur ...
Published:     Bonnae, formis Carthausianis [1864]
Description:   30, [2] p. 20 cm.
LC Call No.:   QA554.H19
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   6800204

Author:        Heger, Richard, 1846- [from old catalog]
Title:         Beiträge zur analytischen geometrie ...
Published:     Dresden, Druck von C. C. Meinhold & söhne,
                  1868.
Description:   37 p. 23 cm.
LC Call No.:   QA554.H46
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   9610206

Author:        Heyting, A. (Arend), 1898-
Title:         Axiomatic projective geometry.
Published:     New York, Interscience Publishers [1963]
Description:   148 p. diagrs. 25 cm.
Series:        Bibliotheca mathematica, a series of monographs
                  on pure and applied mathematics, v. 5
LC Call No.:   QA554.H48
Dewey No.:     516.57
Subjects:      Geometry, Projective -- Foundations.
Series Entry:  Bibliotheca mathematica ; v. 5.
Control No.:   1695545

Author:        Keller, Johannes, 1852- [from old catalog]
Title:         Die einander doppelt conjugirten elemente in
                  allgemeinen reciproken systemen ...
Published:     Zürich, Druck von Zürcher und Furrer, 1879.
Description:   48 p. diagrs. on 2 fold. pl. 22 cm.
LC Call No.:   QA554.K3
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   7736486

Author:        Kemmer, Gottfried, 1858- [from old catalog]
Title:         Über die verwandlung von projektivitäten in
                  involutionen und von reziprozitäten in polarsysteme durch
                  anwendung von projektivitäten ...
Published:     Darmstadt, C. F. Winter'sche buchdruckerei,
                  1898.
Description:   25 p. diagrs. on pl. 20 cm.
LC Call No.:   QA554.K33
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   10081332

Author:        Loos, Wilhelm, 1872- [from old catalog]
Title:         Analytische behandlung einiger grundprobleme der
                  projektiven geometrie ...
Published:     Giessen, Druck von E. Ottmann, 1896.
Description:   p. cm.
LC Call No.:   QA554.L86
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   9141568

Author:        Möbius, August Ferdinand, 1790-1868.
Title:         Der barycentrische calcul, ein neues hülfsmittel
                  zur analytischen behandlung der geometrie, dargestellt und
                  insbesondere auf die bildung neuer classen von aufgaben und
                  die entwickelung mehrerer eigenschaften der kegelschnitte
                  angewendet, von August Ferdinand Möbius ...Mit vier
                  kupfertafeln.
Published:     Leipzig, J.A. Barth, 1827.
Description:   1 p.l., xxiv, 454 p., 1 l. 78 diagr. on IV fold.
                  pl. 21 cm.
LC Call No.:   QA554.M7
Subjects:      Geometry, Projective.
               Geometry, Analytic.
Control No.:   2161320

Author:        Mouchot, A. (Augustin), 1825-
Title:         Les nouvelles bases de la géométrie supérieure
                  : (Géométrie de position) / par A. Mouchot.
Published:     Pairs : Gauthier-Villars et fils, 1892.
Description:   vii, 179 p. : ill. ; 23 cm.
LC Call No.:   QA554.M92
Notes:         I. Géométrie supérieure. Points de modes
                  quelconques.--II. Ligne droite. Coniques rectilignes.--III.
                  Courbes planes.--IV. Aires de mode quelconque. Fonctions
                  transcendantes.--V. Géométrie de l'espace.--VI.
                  Conclusion.
Subjects:      Geometry, Projective.
Control No.:   7739561

Author:        Pfaff, Hans [Heinrich Ulrich Vitalis], 1824-1872.
                  [from old catalog]
Title:         Analytisch-geometrische beitäge zur lehre von
                  der projektivischen beziehung ...
Published:     Erlangen, Druck von Junge & sohn, 1855.
Description:   p. cm.
LC Call No.:   QA554.P52
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   8203278

Author:        Pitz, Heinrich, 1861- [from old catalog]
Title:         Ueber projektive systeme, welche in der ebene
                  durch paare von projektiven systemen erzeugt werden ...
Published:     Giessen, Druck von C. v. Münchow, 1884.
Description:   34 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA554.P7
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   9613014

Author:        Schröter, Heinrich, 1829-1892.
Title:         Theorie der Oberflächen zweiter Ordnung und der
                  Raumkurven dritter Ordnung als Erzeugnisse projektivischer
                  Gebilde. Nach Jacob Steiner's Prinzipien auf synthetischem
                  Wege abgeleitet von Dr. Heinrich Schröter.
Published:     Leipzig, B. G. Teubner, 1880.
Description:   xv, 720 p. diagrs. 22 cm.
LC Call No.:   QA554.S3
Subjects:      Quadrics.
               Curves, Cubic.
               Curves of double curvature.
Control No.:   10094389

Author:        Vahlen, Theodor, 1869-
Title:         Konstruktionen und approximationen in
                  systematischer darstellung, eine ergänzung der niederen,
                  eine vorstufe zur höheren geometrie, von Theodor Vahlen; mit
                  127 figuren im text.
Published:     Leizig, Berlin, B.G. Teubner, 1911.
Description:   xii, 349, [1] p. diagrs. 23 cm.
Series:        B.G. Teubners sammlung von lehrbüchern auf dem
                  gebiete der mathematischen wissenschaften. bd. XXXIII
LC Call No.:   QA554.V3
ISBN:          DM11.00
Subjects:      Geometry.
               Algebra -- Graphic methods.
               Trigonometry.
Series Entry:  B.G. Teubners Sammlung von Lehrbüchern auf dem
                  Gebiete der mathematischen Wissenschaften mit Einschluss
                  ihrer Anwendungen ; Bd. XXXIII.
Control No.:   1217741

Title:         Exercises in analytic geometry.
Published:     [n. p., n. d.]
Description:   6 p. 24 cm.
LC Call No.:   QA555.E96
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   10073299

Author:        Booth, James, 1806-1878.
Title:         A treatise on some new geometrical methods ... By
                  James Booth ...
Published:     London, Longmans, Green, Reader, and Dyer,
                  1873-77.
Description:   2 v. diagrs. 24 cm.
LC Call No.:   QA555.B7
Notes:         v. 1. Tangential coordinates, pedal coordinates,
                  reciprocal polars, the trigonometry of the parabola, the
                  geometrical origin of logarithms, the geometrical properties
                  of elliptic integrals, and other kindred subjects.--v. 2. The
                  geometrical properties of elliptic integrals, rotatory
                  motion, the higher geometry, and conics derived from the
                  cone, with an appendix to the first volume.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Geometry, Analytic.
               Elliptic functions.
               Conic sections.
Control No.:   4525371

Author:        Brisse, Charles Michel, 1843-1898. [from old
                  catalog]
Title:         Recueil de problèmes de géométrie analytique,
                  à l'usage des classes de mathématiques spéciales,
Edition:       2. éd.
Published:     Paris, Gauthier-Villars et fils, 1892.
Description:   2 p.l., 226 p. diagrs. 23 cm.
LC Call No.:   QA555.B8
Subjects:      Geometry, Analytic -- Plane. [from old catalog]
               Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   7823322

Author:        Bürklen, Otto Th., 1856-1919. [from old
                  catalog]
Title:         Aufgabensammlung zur analytischen Geometrie der
                  Ebene.
Edition:       2., verb. Aufl.
Published:     Leipzig, G. J. Göschen, 1912.
Description:   175 p. diagrs. 16 cm.
LC Call No.:   QA555.B9 1912
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   9296470

Author:        Bürklen, Otto Th., 1856- [from old catalog]
Title:         Aufgaben zur analytischen geometrie des raumes,
Edition:       2., verb. und verm. aufl.
Published:     Berlin und Leipzig, G. J. Göschen, 1918.
Description:   109 p. diagrs. 16 cm.
LC Call No.:   QA555.B92 1920
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   6457433

Author:        Bürklen, O[tto] Th., 1856- [from old catalog]
Title:         Aufgabensammlung zur analytischen geometrie der
                  ebene,
Published:     Leipzig, G. J. Göschen, 1905.
Description:   196 p. diagrs. 16 cm.
LC Call No.:   QA555.B9
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   7269897

Author:        Bürklen, O[tto] Th., 1856- [from old catalog]
Title:         Aufgabensammlung zur analytischen geometrie des
                  raumes,
Published:     Leipzig, G. J. Göschen, 1906.
Description:   98 p. diagrs. 16 cm.
LC Call No.:   QA555.B92
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   7743075

Author:        Fergola, Nicolò, 1753-1824. [from old catalog]
Title:         Della invenzione geometrica:
Published:     Napoli, Stamperia privata dell' autore [Flauti]
                  1842.
Description:   lviii p., 1 l., 282, lxiv p. diagrs. on 11 fold.
                  pl. 26 cm.
LC Call No.:   QA555.F3
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Flauti, Vincenzo, 1782-1863, [from old catalog]
                  ed.
Control No.:   8675444

Author:        [Flauti, Vincenzo] 1782-1863. [from old catalog]
Title:         Produzioni relative al programma di tre quistioni
                  geometriche proposto da un nostro professore ...
Published:     Napoli, 1840-41.
Description:   [456] p. diagrs. on 29 fold. pl. 26 x 22 cm.
LC Call No.:   QA555.P9
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Other authors: Trudi, Nicola, 1811-1884. [from old catalog]
Control No.:   9627935

Author:        Gaskin, Thomas, 1811-1887. [from old catalog]
Title:         The solutions of geometrical problems, consisting
                  chiefly of examples in plane co-ordinate geometry, proposed
                  at St. John's college, Cambridge, from Dec 1830 to Dec 1846.
Published:     Cambridge, J. & J. J. Deighton; [etc., etc.]
                  1847.
Description:   viii, 263 p. diagrs. on 8 fold. pl. 22 cm.
LC Call No.:   QA555.G2
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   6326755

Author:        Hallowell, Benjamin, 1799-1877.
Title:         Geometrical analysis, or the construction and
                  solution of various geometrical problems from analysis, by
                  geometry, algebra, and the differential calculus; also, the
                  geometrical construction of algebraic equations, and a mode
                  of constructing curves of the higher order by means of
                  points. By Benjamin Hallowell.
Published:     Philadelphia, J.B. Lippincott & co., 1872.
Description:   279 p. front (port.) diagrs. 22 cm.
LC Call No.:   QA555.H19
Notes:         A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Geometry -- Problems, exercises, etc.
Control No.:   9135753

Author:        Hochheim, Adolf, 1840-1898.
Title:         Aufgaben aus der analytischen Geometrie der
                  Ebene, von dr. Adolf Hochheim.
Published:     Leipzig, B.G. Teubner, 1882-1883.
Description:   2 v. in 1. diagrs. 23 cm.
LC Call No.:   QA555.H6
Notes:         Heft 1. Die gerade Linie, der Punkt, der Kreis.
                  A. Aufgaben. B. Auflösungen.--Heft 2. Die Kegelschnitte, A.
                  Aufgaben. B. Auflösungen.
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
Control No.:   5959242

Author:        Lamé, G. (Gabriel), 1795-1870.
Title:         Examen des différentes méthodes employées pour
                  résoudre les problémes de géométrie / par G. Lamé.
Published:     Paris : Mme. Ve. Courcier, 1818.
Description:   xii, 124 p., 2 folded leaves of plates : ill. ;
                  22 cm.
LC Call No.:   QA555.L364 1818
Subjects:      Geometry, Analytic.
Control No.:   12441901

Author:        Löwe, Otto. [from old catalog]
Title:         Ueber die regulären und Poinsot'schen körper
                  und ihre inhaltsbestimmung vermittelst determinanten ...
Published:     Marburg, Druck von F. W. Kunike, 1875.
Description:   1 p.l., 28 p. diagrs. on pl. 22 cm.
LC Call No.:   QA555.L8
Subjects:      Polyhedra. [from old catalog]
               Determinants. [from old catalog]
Control No.:   6333173

Author:        Oakley, Cletus O. (Cletus Odia), 1899-
Title:         Analytic geometry problems.
Published:     New York, Barnes & Noble [1958]
Description:   253 p. illus. 21 cm.
Series:        College outline series, no. 108
LC Call No.:   QA555.O18
Dewey No.:     516.9
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
Control No.:   9817530

Author:        Rémond, A. [from old catalog]
Title:         Exercises élémentaires de géométrie
                  analytique à deux et à trois dimensions,
Published:     Paris, Gauthier-Villars et fils, 1898.
Description:   2 v. diagrs. 23 cm.
LC Call No.:   QA555.R4
Subjects:      Geometry, Analytic -- Problems, exercises, etc.
                  [from old catalog]
Control No.:   7354350

Author:        Booth, James, 1806-1878. [from old catalog]
Title:         On the application of a new analytic method to
                  the theory of curves surfaces.
Published:     Dublin, Hodges and Smith, 1840.
Description:   2 p.l., 32 p. 24 cm.
LC Call No.:   QA556.B7
Subjects:      Coordinates, Tangential.
Control No.:   7731664

Author:        Braude, L.
Title:         Les coordonnées intrinsèques; théorie et
                  applications, par L. Braude ...
Published:     [Paris, Gauthier-Villars et cie, 1914]
Description:   99, [1] p. incl. port., diagrs. 20 cm.
Series:        Scientia. Mars 1914. Phys.-mathématique. no. 34
LC Call No.:   QA556.B75
Notes:         "Notes bibliographiques": p. [6]
Subjects:      Coordinates.
Series Entry:  Scientia. Série physico-mathématique ; no. 34.
Control No.:   746012

Author:        Collins, Joseph Victor, 1858-1943.
Title:         The (r, x) system of coordinates and its place in
                  analytic geometry and calculus, by Joseph V. Collins.
Published:     Menasha, Wis. George Banta publishing company
                  [c1934]
Description:   v, 30 p. diagrs. 18 cm.
LC Call No.:   QA556.C65
Dewey No.:     516.51
Subjects:      Coordinates.
Control No.:   7356022

Author:        Conradt, Fr[iedrich Ludwig August] [from old
                  catalog]
Title:         Ueber die relation zwischen den entfernungen
                  einer beweglichen ebene von vier festen punkten ...
Published:     Colberg, C. F. Post'sche buchdruckerei, 1873.
Description:   1 p.l., 10 p. pl. 25 x 21 cm.
LC Call No.:   QA556.C7
Subjects:      Coordinates, Tetrahedral.
Control No.:   7744121

Author:        Daniels, Franz, 1860-
Title:         Essai de géométrie sphérique en coordonnées
                  projectives, par M.-Fr. Daniëls.
Published:     Fribourg (Suisse) Librairie de l'Université (O.
                  Gschwend) 1907.
Description:   xiii, 279, [1] p. diagrs. 26 cm.
Series:        Collectanea Friburgensia, nouv. sér., fasc. 8
                  (XVIIme de la collection)
LC Call No.:   QA556.D3
Subjects:      Coordinates.
               Geometry, Projective.
Control No.:   6385581

Author:        Fischer, Paul B. (Paul Bernhard), 1879-
Title:         Koordinatensysteme, von Paul B. Fischer ... mit 8
                  figuren.
Published:     Leipzig, G.J. Göschen, 1911.
Description:   125 p. diagrs. 16 cm.
Series:        Sammlung Göschen. [507]
LC Call No.:   QA556.F6
Notes:         "Literatur": p. [4]
               "Zusammenstellung der erwähnten literatur": p.
                  [124]-125.
Subjects:      Coordinates.
Control No.:   273222

Author:        Fischer Paul Bernhard, 1879- [from old catalog]
Title:         Koordinatensysteme.
Edition:       2., verb. Aufl.
Published:     Berlin, Vereiningung Wissenschaftlicher Verleger
                  W. de Gruyter, 1919.
Description:   128 p. diagrs. 16 cm.
LC Call No.:   QA556.F6 1919
Subjects:      Coordinates. [from old catalog]
Control No.:   7423653

Author:        Gerlach, Rudolf.
Title:         Die Metrik in projektivischen Koordinaten.
Published:     Zürich, 1899.
Description:   xii, 114 p. diagrs. 23 cm.
LC Call No.:   QA556.G3
Notes:         Inaug.-Diss.--Zürich.
Subjects:      Coordinates.
Control No.:   272384

Author:        Laisant, C.-A. (Charles-Ange), 1841-1920.
Title:         Théorie et applications des équipollences, par
                  C.-A. Laisant ...
Published:     Paris, Gauthier-Villars, 1887.
Description:   xvi, 299 p. diagrs. 23 cm.
LC Call No.:   QA556.5.L3
Subjects:      Equipollence, Mathematical.
Control No.:   1218337

Author:        Loney, S. L. (Sidney Luxton), 1860-1939.
Title:         The elements of coordinate geometry, by S. L.
                  Loney.
Published:     London, Macmillan and co., limited, 1923-27 [v.1,
                  '27]
Description:   2 v. diagrs. 19 cm.
LC Call No.:   QA556.L6
Notes:         First edition of part I published 1895; reprinted
                  with corrections 1896; reprinted 1927.
               pt. I. Cartesian coordinates.--pt. II. Trilinear
                  coordinates, etc.
Subjects:      Coordinates.
Control No.:   7337293

Author:        Maatz, Albert. [from old catalog]
Title:         Zur geschichte der polyedercoordinaten ...
Published:     Rostock, Druck der C. Boldt'schen
                  hof-buchdruckerei, 1903.
Description:   44 p. 26 x 21 cm.
LC Call No.:   QA556.M12
Subjects:      Coordinates. [from old catalog]
Control No.:   8675305

Author:        Moritz, Robert Édouard, 1868-1940.
Title:         Cycle-harmonic curves;
Published:     Seattle, Wash., The University, 1923.
Description:   1 p. l., 58 p. 21 pl., diagrs. 25 cm.
LC Call No.:   QA556.M6
Subjects:      Curves.
               Coordinates.
Control No.:   10136105

Author:        Ocagne, Philbert Maurice d', 1862- [from old
                  catalog]
Title:         Coordonnées parallèles et axiales.
Published:     Paris, Gauthier-Villars, 1885.
Description:   91 p. 1 l. diagrs. (1 fold.) 23 cm.
LC Call No.:   QA556.O3
Subjects:      Coordinates. [from old catalog]
               Graphic methods. [from old catalog]
Control No.:   8728727

Author:        Pfarrius, Fridericus, 1846- [from old catalog]
Title:         Novæ theses de tetrædero[!] et de pluribus in
                  unum conjunctis ...
Published:     Barmen, typis Ludovici Langewiesche [1874]
Description:   34 p. 20 cm.
LC Call No.:   QA556.P52
Subjects:      Coordinates, Tetrahedral.
Control No.:   10078550

Author:        Reina, Vincenzo, 1862-1919. [from old catalog]
Title:         Nuove ricerche sulle linee coniugate di una
                  superficie,
Published:     Roma, Tip. della R. Accademia dei Lincei, 1890.
Description:   p. [203]-209. diagrs. 27 cm.
LC Call No.:   QA556.R35
Subjects:      Coordinates. [from old catalog]
               Surfaces, Representation of. [from old catalog]
Control No.:   6403064

Author:        Severance, Lena Lilian (Hill), Mrs., 1855- [from
                  old catalog]
Title:         The theory of equipollences; method of analytical
                  geometry of Sig. Bellavitis,
Published:     Meadville, Pa., Tribune publishing co. [1930]
Description:   46 p. diagrs. 20 cm.
LC Call No.:   QA556.5.S4
Subjects:      Equipollence, Mathematical.
               Bellavitis, Giusto, conte, 1803-1880. [from old
                  catalog]
Control No.:   9219945

Author:        Silva, Daniel Augusto da, 1814-1878. [from old
                  catalog]
Title:         De varias formulas novas de geometria analytica
                  relativas aos eixos coordenados obliquos,
Published:     Lisboa, Typ. da Academia real das sciencias de
                  Lisboa, 1872.
Description:   2 p. l., 20 p. 29 cm.
LC Call No.:   QA556.S5
Subjects:      Geometry, Analytic -- Solid.
               Coordinates, Oblique.
Control No.:   8668258

Author:        Staude, Otto, 1857-1928.
Title:         Ueber Lineare Gleichungen zwischen elliptischen
                  Coordinaten ...
Published:     Leipzig, Druck von B.G. Teubner, 1881.
Description:   85, [1] p. diagrs. on 2 fold. pl. 23 cm.
LC Call No.:   QA556.S79
Notes:         Lebenslauf.
               Inaug.-diss.--Leipzig.
Subjects:      Coordinates, Elliptic
Other titles:  Über lineare Gleichungen zwischen elliptischen
                  Coordinaten.
               [Pamphlets. Mathematics. 1841-1906] v.18.
Control No.:   8668063

Author:        Weinmeister, Johann Philipp, 1848- [from old
                  catalog]
Title:         Das system der polaren linien-coordinaten in der
                  ebene ...
Published:     Marburg, 1876.
Description:   1 p.l., 26 p. diagrs. 23 cm.
LC Call No.:   QA556.W4
Subjects:      Coordinates. [from old catalog]
Control No.:   6801392

Author:        Whitworth, William Allen, 1840-1905. [from old
                  catalog]
Title:         Trilinear coordinates and other methods of modern
                  analytical geometry of two dimensions: an elementary
                  treatise,
Published:     Cambridge [Eng.] Deighton, Bell, and co.; London,
                  Bell and Daldy, 1866.
Description:   xxxvi p., 1 l., 506 p. diagrs. 23 cm.
LC Call No.:   QA556.W6
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Coordinates, Trilinear.
Control No.:   7330045

Author:        Wright, Williams James, 1831-
Title:         Trilinear coordinates / By Rev. W.J. Wright.
Published:     London : C.F. Hodgson & son, 1877.
Description:   77 p. ; 21 cm.
Series:        Tracts relating to the modern hgher mathematics.
                  no. 2
LC Call No.:   QA556.W9
Subjects:      Coordinates, Trilinear.
Control No.:   10076185

Author:        Browne, Edward Tankard, 1894-1959.
Title:         Involutions that belong to a linear class.
Published:     Chicago, 1926.
Description:   59 l. illus. 29 cm.
LC Call No.:   QA557.B76
Notes:         Thesis--University of Chicago.
               Includes bibliographical references.
Subjects:      Involutes (Mathematics)
               Matrices.
Control No.:   2307644

Author:        DoBell, Howard Adamas, 1896- [from old catalog]
Title:         On the geometry of the triangle ...
Published:     [Oberlin, Ohio, 1932]
Description:   p. [71]-85. 25 cm.
LC Call No.:   QA557.D6 1928
Subjects:      Triangle. [from old catalog]
Control No.:   6896090

Author:        Forbes, Charles Savage, 1879- [from old catalog]
Title:         The geometry of circles orthogonal to a given
                  sphere...
Published:     New York, 1904.
Description:   iv, 50 p. 27 cm.
LC Call No.:   QA557.F66
Control No.:   10011546

Author:        Habicht, Conrad.
Title:         Die Steinerschen Kreisreihen / von Conrad
                  Habicht.
Published:     Bern : K.J. Wyss, 1904.
Description:   35 p. : ill. ; 23 cm.
LC Call No.:   QA557.H2
Notes:         Plates printed on both sides.
               Thesis--Universität Bern.
Subjects:      Circle.
Control No.:   7751820

Author:        Juzi, Otto, 1876-
Title:         Ueber den Feuerbach'schen Kreis in variablen
                  Dreiecken ... von Otto Juzi.
Published:     [Langenthal, Buchdruckerei G. Dysli, 1903]
Description:   80 p. diagrs. on 10 fold. pl.  20 cm.
LC Call No.:   QA557.J98
Notes:         Inaug.-diss.--Bern.
Subjects:      Triangle
               Curves, Plane
Other titles:  Über den Feuerbach'schen Kreis in variablen
                  Dreiecken.
               [Pamphlets. Mathematics. 1841-1906] v. 10.
Control No.:   9606480

Author:        Krebs, A.
Title:         Konstruktionen gleischenkliger Dreiecke mit Hilfe
                  von Kurven höherer Ordnung / von A. Krebs.
Published:     Bern : K.J. Wyss, 1902.
Description:   95 p. : ill. ; 23 cm.
LC Call No.:   QA557.K92
Notes:         Thesis--Universität Bern.
               "Separatabdruck" from Mitteilungen der
                  Naturforschenden gesellschaft in Bern.
Subjects:      Triangle.
               Curves, Plane.
Control No.:   9137657

Author:        Mack, Ludwig.
Title:         Analytische Geometrie des Kreises / systematisch
                  ausgearbeitet als Einleitung in die höhere Geometrie von
                  Ludwig Mack.
Published:     Stuttgart : Verlag der J.B. Metzler'schen
                  Buchhandlung, 1855.
Description:   xvi, 316 p. ; 22 cm.
LC Call No.:   QA557.M32x 1855
Subjects:      Circle.
               Geometry, Analytic.
Control No.:   2873545

Author:        Marsano, Giovanni Battista.
Title:         Sul problema dei circoli tangenti a tre circoli
                  dati. Memoria di Gio. Batta Marsano.
Published:     Genova, Tip. del R. Istituto sordo-muti, 1872.
Description:   189, [1] p. diagrs. on fold. pl. 24 cm.
LC Call No.:   QA557.M36
Subjects:      Circle
Control No.:   9136750

Author:        Milne, John. [from old catalog]
Title:         The analytical geometry of the straight line and
                  the circle,
Published:     London, G. Bell and sons, ltd., 1919.
Description:   p. cm.
LC Call No.:   QA557.M5
Subjects:      Geometry, Analytic. [from old catalog]
Control No.:   6377932

Author:        Mudd, Rolla E.
Title:         The Muddonian theorem (analyzed) : complete
                  analysis of "The angle trisected" with demonstrations and
                  proofs / [by Rolla E. Mudd].
Published:     Stronghurst, Ill. : R.E. Mudd, c1946.
Description:   9 p. : ill. ; 21 cm.
LC Call No.:   QA557.M83x 1946
Notes:         Cover title.
Subjects:      Geometry, Analytic.
Control No.:   4291734

Author:        Reum, August. [from old catalog]
Title:         Die merkwürdigen punkte des dreiecks in
                  trimetrischen coordinaten...
Published:     Hagen, G. Butz, 1875-
Description:   1 p.l., 24 p. 27 cm.
LC Call No.:   QA557.R4
Subjects:      Triangle.
               Coordinates, Trilinear.
Control No.:   8200100

Author:        Sack, Pius. [from old catalog]
Title:         Über kreisbündel II. ordnung ...
Published:     Jena, Druck von G. Neuenhahn, 1890.
Description:   32 p. 21 cm.
LC Call No.:   QA557.S12
Other authors: Circle. [from old catalog]
Control No.:   6796439

Author:        Wagner, Paul Smith, 1896- [from old catalog]
Title:         An extension to Clifford's chain ... by Paul
                  Smith Wagner.
Published:     [Baltimore, 1929]
Description:   1 p. l., p. 473-481, i l. diagrs. 25 cm.
LC Call No.:   QA557.W3 1926
Notes:         Thesis (Ph. D.)--Johns Hopkins university, 1926.
               Vita.
               "Reprinted from hte American journal of
                  mathematics, vol. LI, number 3."
Subjects:      Geometry, Analytic.
               Cardioid.
Control No.:   13194781

Author:        Wittstein, Armin. [from old catalog]
Title:         Geschichte des Malfatti'schen problems ..
Published:     München, Druck von C. R. Schurich, 1871.
Description:   39 p. diagrs. on iv fold. pl. 21 cm.
LC Call No.:   QA557.W8
Subjects:      Malfatti's problem.
Control No.:   6800060

Author:        Angeli, Stefano degli, 1623-1697? [from old
                  catalog]
Title:         De infinitis parabolis,
Published:     Venetiis apud Ioannem La Noù., 1659.
Description:   10 p. l., 408 p. diagrs. 21 x 16 cm.
LC Call No.:   QA559.A5
Subjects:      Parabola. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   8350536

Author:        Angeli, Stefano degli, 1623-1697? [from old
                  catalog]
Title:         De infinitorvm spiralivm spatiorvm mensvra,
Published:     Venetiis, apud Ioannen La Noù, 1660.
Description:   8 p. l., 126 p. diagrs. 21 x 16 cm.
LC Call No.:   QA559.A5
Subjects:      Spirals. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9755516

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Intorno alle coniche di nove punti e ad alcune
                  quistioni che ne dipendono. Nota del Prof. Eugenio Beltrami.
Published:     Bologna, Tipi Gamberini e Parmeggiani, 1863.
Description:   37 p. 30 x 23 cm.
LC Call No.:   QA559.B45
Subjects:      Conic sections. [from old catalog]
Control No.:   7736641

Author:        Benter, Eduard. [from old catalog]
Title:         Untersuchungen über tangentialkegel und die
                  curven zweiten grades ...
Published:     Leipzig, B.G. Teubner's verlagsbuchhandlung,
                  1871.
Description:   4 p.l., 44 p. diagrs. on 2 fold. pl. 23 cm.
LC Call No.:   QA559.B47
Subjects:      Conic sections. [from old catalog]
               Surfaces -- Areas and volumes. [from old
                  catalog]
Control No.:   7264488

uthor:        Boegehold, Franz, 1881-
Title:         Ableitung einiger eigenschaften des
                  kegelschnittbüschels aus orthogonal invarianten und
                  kovarianten ...
Published:     Jena, Druck von B. Vopelius, 1904.
Description:   78 p., 1 l. 23 cm.
LC Call No.:   QA559.B66
Notes:         Inaug.-diss.--Jena.
               Lebenslauf.
Subjects:      Conic sections.
               Forms (Mathematics)
Control No.:   3107207

Author:        Cavalieri, Bonaventura, 1598-1647. [from old
                  catalog]
Title:         Lo specchio vstorio; overo,
Published:     In Bologna, Presso Clemente Ferroni, 1632.
Description:   8 p.l., 224, [1] p. xxxvi diagr. on 10 pl. 21
                  cm.
LC Call No.:   QA559.C3
               Microfilm 89/5098 (QA)
Subjects:      Conic sections.
               Burning-mirrors.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   6877214

Author:        Darreye, Adolf, 1875-
Title:         Polare felder und kegelschnitte mit gemeinsamem
                  poldreieck ...
Published:     Strassburg i. E., Buchdruckerei C. & J. Gœller,
                  1900.
Description:   41 p., 1 l. diagrs. on 2 fold. pl. 23 cm.
LC Call No.:   QA559.D22
Notes:         Inaug.-Diss.--Strassburg.
               Lebenslauf.
Subjects:      Conic sections.
Control No.:   7268440

Author:        Desargues, Gérard, 1593-1662? [from old
                  catalog]
Uniform Title: Brouillon projet d'une atteinte aux eâvènemens.
                  German. [from old catalog]
Title:         Erster entwurf eines versuchs über die
                  ergebnisse des zusammentreffens eines kegels mit einer
                  ebene,
Published:     Leipzig, Akademische verlagsgesellschaft m.b.h.,
                  1922.
Description:   86, [2] p. diagrs. 20 cm.
LC Call No.:   QA559.D4
Subjects:      Conic sections. [from old catalog]
Other authors: Zacharias, Max, [from old catalog] ed. and tr.
Control No.:   9673202

Author:        Dittmar, Peter, 1863- [from old catalog]
Title:         Das büschel von kegelschnitten,
Published:     Giessen, Druck von W. Keller, 1888.
Description:   19, [1] p. 27 x 22 cm.
LC Call No.:   QA559.D61
Subjects:      Conic sections. [from old catalog]
Control No.:   5860050

Author:        Egerer, Heinz, b. 1874.
Title:         Über die kurve der ecken der vierseite, die von
                  den gemeinsamen tangenten eines festen kegelschnitts und der
                  kegelschnitte eines büschels gebildet werden ...
Published:     Borna-Leipzig, Buchdr. R. Noske, 1906.
Description:   53 p., 1 l., diagrs. on 6 pl. 23 cm.
LC Call No.:   QA559.E3
Notes:         Inaug.-diss.--Erlangen.
               Lebenslauf.
Subjects:      Conic sections.
               Curves.
Control No.:   7282630

Author:        Fergola, Nicola, 1753-1824. [from old catalog]
Title:         Trattati analitici delle sezioni coniche e de'
                  loro luoghi geometrici di Nicola Fergola.
Edition:       3. ed.
Published:     Napoli, Nella stamperia per le opere del prof.
                  Flauti, 1840.
Description:   7 p.l., xxviii p., 421, [1], 60, [2] p. diagrs.
                  on 9 fold. pl. 26 cm.
LC Call No.:   QA559.F35
Subjects:      Conic sections. [from old catalog]
               Geometry, Analytic. [from old catalog]
Other authors: Flauti, Vincenzo, 1782-1863, [from old catalog]
                  ed.
Control No.:   6801543

Author:        Geis, Eduard. [from old catalog]
Title:         Untersuchung des systemes der kegelschnitte,
                  welche durch zwei feste punkte gehen und einen gegebenen
                  kegelschnitt doppelt berühren ...
Published:     Marburg, Universitätsbuchdruckerei (R.
                  Friedrich) 1882.
Description:   35 p. 21 cm.
LC Call No.:   QA559.G31
Subjects:      Conic sections. [from old catalog]
Control No.:   10074794

Author:        Geissler, Kurt, 1859-1941.
Title:         Die Kegelschnitte und ihr Zusammenhang durch die
                  Kontinuität der Weitenbehaftungen : mit einer Einführung in
                  die Lehre von den Weitenbehaftungen : für Selbstsudium und
                  Unterricht / von Kurt Geissler.
Published:     Jena : H.W. Schmidt's Verlagsbuchhandlung, 1905.
Description:   viii, 201 p., 19 folded leaves of plates : ill. ;
                  24 cm.
LC Call No.:   QA559.G44x 1905
Notes:         Includes bibliographical references.
Subjects:      Conic sections.
Control No.:   983734

Author:        Ghetaldi, Marino, 1566-1626.
Uniform Title: Nonnullae propositiones de parabola
Title:         Marini Ghetaldi, patricii Ragusini, Nonnullae
                  propositiones de parabola : nunc primum inuentae & in lucem
                  editae.
Published:     Romae : Apud Aloysium Zannettum, 1603.
Description:   20 p. : ill. ; 23 cm. (4to)
LC Call No.:   QC111.G54 1603; Alternative class.: QA559
Notes:         Signatures: Ap4s Bp6s.
               With: Promotus Archimedes / Marino Ghetaldi.
                  Romae : Apud Aloysium Zannettum, 1603. Probably bound
                  together subsequent to publication.
Subjects:      Parabola -- Early works to 1800.
Other titles:  Nonnullae propositiones de parabola.
Control No.:   4273213

Author:        Häfele, Engelhard.
Title:         Die Hyperbel : die wichtigsten Eigenschaften
                  derselben nach der analytischen Methode und nach der Methode
                  der Alten unter Vergleichung dieser Verfahrungsweisen /
                  dargestellt von Engelhard Häfele.
Published:     Bozen : Im Selbstverlage der Verfassers, 1901.
Description:   35 p. : ill. ; 22 cm.
LC Call No.:   QA559.H33x 1901
Subjects:      Hyperbola.
Control No.:   2873547

Author:        Hahn, August, 1860- [from old catalog]
Title:         Untersuchungen über kegelschnitte in solcher
                  lage, dass jedem von ihnen dreiecke umgeschrieben werden
                  können, die dem anderen eingeschrieben sind ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1882.
Description:   27, [1] p. 21 cm.
LC Call No.:   QA559.H14
Subjects:      Conic sections. [from old catalog]
Control No.:   9137975

Author:        Haller, Stanislaus.
Title:         Untersuchung der brennpunktskurve eines
                  kegelschnittbüschels, mit besonderer berücksichtigung der
                  gestaltlichen verhältnisse ...
Published:     Leipzig, Druck von B.G. Teubner, 1903.
Description:   42 p. diagrs. 24 cm.
LC Call No.:   QA559.H19
Notes:         Inaug.-diss.--Tech. hochschule, München.
Subjects:      Conic sections.
Control No.:   8217386

Author:        Handel, Otto, b. 1852.
Title:         Elementar-synthetische Kegelschnittslehre : mit
                  zahlreichen Übungsaufgaben zum Gebrauch an höheren
                  Lehranstalten / bearbeitet von Otto Handel.
Edition:       2. verb. Aufl.
Published:     Berlin : Weidmannsche Buchhandlung, 1901.
Description:   vi, 85 p. : ill. ; 22 cm.
LC Call No.:   QA559.H36 x 1901
Subjects:      Conic sections.
Control No.:   511480

Author:        Hartmann, Anton. [from old catalog]
Title:         Studium über kegelschnitte und flächen 2.
                  grades ...
Published:     Zürich, Druck von O. Füssli & co., 1889.
Description:   55 p. 22 cm.
LC Call No.:   QA559.H33
Subjects:      Conic sections. [from old catalog]
               Quadrics. [from old catalog]
Control No.:   7264812

Author:        Hearn, George Whitehead, 1812-1851.
Title:         Researches on curves of the second order, also on
                  cones and spherical conics treated analytically, in which the
                  tangencies of Apollonius are investigated, and general
                  geometrical constructions deduced from analysis; also several
                  of the geometrical conclusions of M. Chasles are analytically
                  resolved, together with many properties entirely original. By
                  George Whitehead Hearn ...
Published:     London, G. Bell, 1846.
Description:   vi, [7]-83 p. diagrs. 23 cm.
LC Call No.:   QA559.H4
Notes:         A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Conic sections.
Control No.:   2163611

Author:        Hedström, J. S.
Title:         Über die reciproke linien und ebenen der
                  brennpunkte der kegelschnitte und der flächen zweiter
                  ordnung ...
Published:     Lund, H. Ohlssons buchdruckerei, 1903.
Description:   1 p. l., 35 p. 22 cm.
LC Call No.:   QA559.H5
Notes:         Akademisk afhandling--Lund.
Subjects:      Conic sections.
               Quadrics.
Control No.:   6807566

Author:        Heinemann, Ernst, 1884- [from old catalog]
Title:         Die gemischte kegelschnittschar.
Published:     Darmstadt, Buchdr. von H. Uhde, 1908.
Description:   2 p. l., 84 p., 1 l. diagrs. on 2 l. (1 fold.) 23
                  cm.
LC Call No.:   QA559.H55
Subjects:      Conic sections. [from old catalog]
Control No.:   5878075

Author:        Hess, Robert, 1831-1855. [from old catalog]
Title:         Über die kegelschnitte, welche zwei gegebne
                  kreise, oder zwei gegebne kegelschnitte doppelt berühren
                  ...
Published:     Göttingen, Dieterichsche univ.-buchdruckerei,
                  1854.
Description:   iv, 64 p. 22 cm.
LC Call No.:   QA559.H57
Subjects:      Conic sections [from old catalog]
Control No.:   9740814

Author:        Hoffmann, Eduard. [from old catalog]
Title:         Über den ort der durchschnittspunkte der polaren
                  und über die enveloppe der verbindungslinien der pole von
                  punkten,
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1884.
Description:   27 p. diagrs. on pl. 22 cm.
LC Call No.:   QA559.H69
Subjects:      Conic sections. [from old catalog]
Control No.:   6329566

Author:        Hülsmann, Johann Heinrich Hermann, 1836- [from
                  old catalog]
Title:         Theoria normalium curvarum secundi ordinis,
                  praeipue determinatio numeri normalium, quae a dato puncto ad
                  sectionem conicam duci possunt, et earum constructio linea
                  recta et circulo perficienda...
Published:     Gryphiae, typis Frid. Guil. Kunike [1860]
Description:   2 p.l., 36 p. 21 cm.
LC Call No.:   QA559.H88
Subjects:      Conic sections. [from old catalog]
Control No.:   7278505

Author:        Israel, Karl. [from old catalog]
Title:         Untersuchung über die geometrischen
                  eigenschaften des schwerpunkts von parabel-dreiecken und
                  segmentem ...
Published:     Cassel, Druck von gebrüder Gotthelft, 1871.
Description:   44 p. diagrs., on 2 fold. pl. 21 cm.
LC Call No.:   QA559.I8
Subjects:      Parabola. [from old catalog]
Control No.:   5858899

Author:        Keil, Karl Ernst Jacob, 1861- [from old catalog]
Title:         Covarianten eines ebenen systems,
Published:     Giessen, Druck von W. Keller, 1888.
Description:   19, [1] p. 27 x 22 cm.
LC Call No.:   QA559.K27
Subjects:      Conic sections. [from old catalog]
Control No.:   8201271

Author:        Kemmer, Karl, 1855- [from old catalog]
Title:         Kriterien der realität für die schnittpunkte
                  von linien zweiter ordnung ...
Published:     Giessen, Druck von W. Keller, 1878.
Description:   19 p. diagr. 27 cm.
LC Call No.:   QA559.K3
Subjects:      Conic sections. [from old catalog]
Control No.:   7263316

Author:        Klippert, Arwed Wilhelm Conrad. [from old
                  catalog]
Title:         Ueber involutorische strahlenbüschel, deren
                  centrum auf einem kegelschnitte liegt ...
Published:     Marburg, 1872.
Description:   20 p. diagrs. on pl. 22 cm.
LC Call No.:   QA559.K65
Subjects:      Conic sections. [from old catalog]
Control No.:   8671073

Author:        Kroes, Ferdinand, 1855- [from old catalog]
Title:         Untersuchung des systems unter einander
                  ähnlicher kegelschnitte, welche einem dreiecke umschrieben
                  sind
Published:     Münster, Druck der Coppenrath'schen
                  buchdruckerei, 1881.
Description:   54 p. diagrs. on 3 pl. 22 cm.
LC Call No.:   QA559.K93
Subjects:      Conic sections. [from old catalog]
Control No.:   8673812

Author:        Kull, Herman.
Title:         Über systeme solcher kegelschnitte, diemittelst
                  linearer transformation involutorisch permutiert werden
                  können ... [von] Herman Kull ...
Published:     Lund, Berlingsche buchdruckerei, 1903.
Description:   1 p.l., 56 p. diagrs. 24 cm.
LC Call No.:   QA559.K95
Notes:         Akademisk afhandling--Lund.
Subjects:      Conic sections.
Control No.:   1689583

Author:        Linton, Anne.
Title:         Pascal's mystic hexagram; its history and
                  graphical representation, by Anne and Elizabeth Linton.
Published:     Philadelphia, Pa., 1921.
Description:   17 p., 14 l. XVIII pl. (part fold.; diagrs.) 28 x
                  31 cm.
LC Call No.:   QA559.L5
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1921.
Subjects:      Conic sections.
               Pascal, Blaise, 1623-1662.
Other authors: Linton, Elizabeth, joint author.
Other titles:  Mystic hexagram.
Control No.:   6850242

Author:        Mangold, Marie Cecilia, Sister, 1872-
Title:         The loci described by the vertices of singly
                  infinite systems of triangles circumscribed about a fixed
                  conic, by Sister Marie Cecilia Mangold ...
Published:     Washington, D.C., 1929.
Description:   49 p. diagrs. 23 cm.
LC Call No.:   QA559.M3 1929
Notes:         Thesis (PH. D.)--Catholic university of America,
                  1929.
               Vita.
Subjects:      Conic sections.
               Triangle.
               Curves.

Author:        Mitchell, Benjamin Ernest, b. 1879.
Title:         Complex conics and their real representation, by
                  Benjamin Ernest Mitchell ...
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1917.
Description:   iii, 44 p., 1 l. diagrs. 24 cm.
LC Call No.:   QA559.M6
Notes:         Thesis (Ph.D.)--Columbia university, 1917.
               Vita.
Subjects:      Conic sections.
               Geometry, Analytic.
Control No.:   3107790

Author:        Müller, Julius, of Grone. [from old catalog]
Title:         Ueber reciproke Polaren zweiten Grades.
Published:     Göttingen, 1875.
Description:   63 p. 22 cm.
LC Call No.:   QA559.M9
Subjects:      Conic sections. [from old catalog]
               Reciprocal polars. [from old catalog]
Control No.:   9605001

Author:        Olivier, Théodore, 1793-1853. [from old
                  catalog]
Title:         Additions au Cours de géométrie descriptive.
                  Démonstration nouvelle des propriétés principales des
                  sections coniques.
Published:     Paris, Carilian-Gœury et V. Dalmont, 1847.
Description:   xvi, 94 p. and atlas (15 plates) 28 cm.
LC Call No.:   QA559.O4
Notes:         LC copy imperfect: atlas wanting.
Subjects:      Conic sections. [from old catalog]
Control No.:   7004599

Author:        Pasch, Moritz, 1843-1930.
Title:         De duarum sectionum conicarum in circulos
                  projectione
Published:     Vratislaviae, typis Brehmeri et Minuthi [1865].
Description:   3 p.l., 18 p. 21 cm.
LC Call No.:   QA559.P2
Subjects:      Conic sections.
Control No.:   9136505

Author:        Peveling, Joseph, 1852- [from old catalog]
Title:         Das system konfokaler parabeln, die eine strecke
                  harmonisch teilen ...
Published:     Aachen, 1891.
Description:   xxii p. diagrs. 26 cm.
LC Call No.:   QA559.P5
Subjects:      Parabola. [from old catalog]
Control No.:   6802991

Author:        Piel, Carl, 1881-
Title:         Über die kegelschnitte welche durch drei punkte
                  und zwei tangenten oder durch zwei punkte und drei tangenten
                  bestimmt sind, und die kegelschnittsysteme (3 p, 1 l) und (1
                  p, 3 l) ...
Published:     Strassburg i. E., Buchdruckerei C. Müh & cie,
                  1905.
Description:   73 p., 1 l. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA559.P6
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Conic sections.
Control No.:   6339354

Author:        Pyrkosch, Reinhold, 1873- [from old catalog]
Title:         Über Poncelet'sche dreiecke, besonders solche,
                  welche confocalen kegelschnitten ein- und umgeschrieben sind
                  ...
Published:     Breslau, Schlesische volkszeitung-buchdruckerei,
                  1897.
Description:   2 p.l., 63 p. incl. diagrs. 23 cm.
LC Call No.:   QA559.P98
Subjects:      Conic sections. [from old catalog]
               Triangle. [from old catalog]
Control No.:   5863960

Author:        Riemann, Paul. [from old catalog]
Title:         Die krümmungs-halbmesser der kegelschnitte...
Published:     Marburg, Druck von C. L. Pfeil, 1881.
Description:   36 p. diagrs. on pl. 21 cm.
LC Call No.:   QA559.R55
Subjects:      Conic sections. [from old catalog]
               Curvature. [from old catalog]
Control No.:   5860363

Author:        Rosanes, Jacob, 1842- [from old catalog]
Title:         De polarium reciprocarum theoria observationes
                  ...
Published:     Vratislaviae, typis C. H. Strochii et socii
                  [1865]
Description:   23 p. 22 cm.
LC Call No.:   QA559.R76
Subjects:      Conic sections. [from old catalog]
               Reciprocal polars. [from old catalog]
Control No.:   10073296

Author:        Rosenstock, Eduard. [from old catalog]
Title:         Ueber gewisse syteme von kegelschnitten, welche
                  mit einer gegebenen ellipse eine berührung zweiter ordnung
                  haben ...
Published:     Marburg, Druck von C. L. Pfeil, 1878.
Description:   18 p. 22 cm.
LC Call No.:   QA559.R8
Subjects:      Conic sections. [from old catalog]
Control No.:   7731403

Author:        Rückoldt, Karl. [from old catalog]
Title:         Der gerade kreiskegel und die ebene ...
Published:     Eisenach, Hofbuchdruckerei, 1891.
Description:   1 p. l., 13 p. diagrs. 25 x 20 cm.
LC Call No.:   QA559.R91
Subjects:      Conic sections. [from old catalog]
               Eisenach. Grossherzogliches realgymnasium. [from
                  old catalog]
Control No.:   8201590

Author:        Rudolph, Paul. [from old catalog]
Title:         Die eigenschaften der einem kegelschnitt ein- und
                  umbschriebenen regulären dreiecke ...
Published:     Kahla, Druck von F. Beck, 1884.
Description:   48 p. diagrs. on pl. 22 cm.
LC Call No.:   QA559.R88
Subjects:      Conic sections. [from old catalog]
               Traingle. [from old catalog]
Control No.:   10080608

Author:        Rupp, Charles Andrew, 1898-
Title:         An extension of Pascal's theorem to space of r
                  dimensions.
Published:     1928.
Description:   ii, 33 l. 29 cm.
LC Call No.:   QA559.R96
Dewey No.:     516.3 19
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Includes bibliographical references.
Subjects:      Pascal's theorem.
               Generalized spaces.
Control No.:   4692726

Author:        Schindler, Theodor, 1858- [from old catalog]
Title:         Mehrpunktige berührung eines kreises mit
                  kegelschnitten ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1882.
Description:   33 p., 1 l. diagrs. on pl. 21 cm.
LC Call No.:   QA559.S33
Subjects:      Conic sections. [from old catalog]
Control No.:   8669730

Author:        Schlotke, J. (Julius), 1839-1907.
Title:         Die Kegelschnitte und ihre wichtigsten
                  Eigenschaften in elementar-geometrischer Behandlung / von J.
                  Schlotke.
Published:     Dresden : G. Kühtmann, 1903.
Description:   96 p. : ill. ; 25 cm.
LC Call No.:   QA559.S35x 1903
Subjects:      Conic sections.
Control No.:   3346198

Author:        Schulte, Emil. [from old catalog]
Title:         Ueber eine verallgemeinerung des satzes,
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1881.
Description:   14 p. 27 x 22 cm.
LC Call No.:   QA559.S38
Subjects:      Hyperbola.
Control No.:   6328233

Author:        Seipp, Heinrich. [from old catalog]
Title:         Ueber kegelschnitte, welche mit einer gegebenen
                  ellipse in doppelberèhruung sind und von denselben
                  hergeleitete verwandschaften geometrischer gebilde ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1883.
Description:   57 p. diagrs. on double pl. 21 cm.
LC Call No.:   QA559.S45
Subjects:      Conic sections. [from old catalog]
Control No.:   6796438

Author:        Spain, Barry.
Title:         Analytical conics.
Published:     New York, Pergamon Press, 1957.
Description:   145 p. illus. 22 cm.
Series:        International series of monographs on pure and
                  applied mathematics, v. 3
LC Call No.:   QA559.S67
Dewey No.:     516.22
Subjects:      Conic sections.
Series Entry:  International series of monographs in pure and
                  applied mathematics ; v. 3.
Control No.:   9346941

Author:        Stolzenburg, Richard.
Title:         Bestimmung einer ellipse durch die summe eines
                  ellipsenbogens und zweier tangenten ...
Published:     Jena, Druck von W. Ratz, 1872.
Description:   20 p. diagrs. 25 cm.
LC Call No.:   QA559.S8
Subjects:      Ellipse.
Control No.:   6326756

Author:        Study, Eduard, 1862- [from old catalog]
Title:         Über die geometrie der kegelschnitte
                  insbesondere deren charakteristikenproblem ...
Published:     Leipzig, Druck von B. G. Teubner, 1885.
Description:   2 p.l., 48 p. 23 cm.
LC Call No.:   QA559.S92
Notes:         Conic sections.
Control No.:   8669412

Author:        Tognoli, Oreste.
Title:         Teoremi di Chasles : sopra le proprietà dei
                  sistemi di coniche ([mu], [nu]), che servono di base alla
                  determinazione del numero di queste curve, che soddisfanno a
                  cinque condizioni qualunque :nota / d'Oreste Tognoli.
Published:     Pisa : Tip. Valenti, 1869.
Description:   65 p. ; 26 cm.
LC Call No.:   QA559.T63x 1869
Notes:         Includes bibliographical references.
Subjects:      Conic sections.
               Curves.
Other authors: Chasles, M. (Michel), 1793-1880.
Control No.:   3346196

Author:        Volpicelli, Paolo, 1804-1879. [from old catalog]
Title:         Ricerche analitiche relative al geometrico luogo,
                  tanto dei punti di tangenza fra uno e due sistemi di
                  parallele con una serie di coniche omofocali, quanto dei
                  punti d'intersecazione delle tangenti parallele di un sistema
                  colle respettive di un altro.
Published:     Roma, Tipografia delle belle arti, 1866.
Description:   128 p. diagrs. on 6 fold. pl. 30 cm.
LC Call No.:   QA559.V91
Subjects:      Conic sections. [from old catalog]
Control No.:   8668259

Author:        Weimar, Otto, 1861- [from old catalog]
Title:         Über verschiedene darstellungen des
                  korrespondierenden kegelschnitts einer geraden in bezug auf
                  ein kegelschnittbüschel ...
Published:     Giessen, Druck von W. Keller, 1890.
Description:   19, [1] p. 27 x 22 cm.
LC Call No.:   QA559.W42
Subjects:      Conic sections. [from old catalog]
Control No.:   8205162

Author:        Wiesing, Hermann. [from old catalog]
Title:         Studien über kegelschnittbüschel und eine
                  gewisse art
Published:     Nordhausen, Druck von C. Kirchner, 1873.
Description:   1 p.l., 62 p. 24 cm.
LC Call No.:   QA559.W6
Subjects:      Conic sections. [from old catalog]
Control No.:   8200101

Author:        Zeuthen, H. G. (Hieronymus Georg), 1839-1920.
Title:         Die Lehre von den Kegelschnitten im Altertum
                  [von] H.G. Zeuthen. Mit einem Vorwort und Register von J.E.
                  Hofmann. (Mit 80 Holzschnitten. Reprografischer Nachdruck der
                  deutschen Ausg. Kopenhagen 1886).
Published:     Hildesheim, Gg Olms, 1966.
Description:   xvi, 521 p. 23 cm.
LC Call No.:   QA559.Z45
Dewey No.:     516/.2
ISBN:          DM84.00
Notes:         "Namen- und Schriftenverzeichnis": p.
                  [513]-[522]
Subjects:      Conic sections.
               Geometry -- History.
Control No.:   4064275
