#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Berkhan, Gustav Waldemar, 1882-1914.
Title:         Zur projektivischen Behandlung der
                  Dreiecksgeometrie ...
Published:     Leipzig, Druck von B. G. Teubner, 1905.
Description:   1 p. l., 31, [3] p. 24 cm.
LC Call No.:   QA471.B5
Notes:         Inaug.-diss.--Königsberg.
Subjects:      Triangle.
Control No.:   7283832

Author:        Böger, Rudolf, 1854- [from old catalog]
Title:         Die geometrie der lage in der schule.
Published:     Hamburg, Gedruckt bei Lütcke & Wulff, 1897.
Description:   1 p. l., iii, 47 p. diagrs. 25 cm.
LC Call No.:   QA471.B67
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   6803219

Author:        Böger, Rudolf, 1854- [from old catalog]
Title:         Über buschel und netze von ebenen polarsystemen
                  zweiter ordnung ...
Published:     Hamburg, Gedruckt bei T. G. Meissner, 1886.
Description:   2 p.l., iv, 43 p. diagrs. 27 x 22 cm.
LC Call No.:   QA471.B68
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   8669731

Author:        Böger, Rudolf, b. 1854.
Title:         Ebene geometrie der lage, von dr. Rudolf Böger
                  ... Mit 142 figuren.
Published:     Leipzig, G.J. Göschen, 1900.
Description:   x, 289, [1] p. diagrs. 20 cm.
Series:        Sammlung Schubert, VII
LC Call No.:   QA471.B66
Subjects:      Geometry, Projective.
Series Entry:  Sammlung Schubert ; 7.
Control No.:   744779

Author:        Böklen, Otto, 1821-1900. [from old catalog]
Title:         Die methode des unterrichts in der projektiven
                  geometrie an der oberrealschule.
Published:     Reutlingen, C. Rupp'sche buchdr., 1894.
Description:   36 p. diagrs. 22 cm.
LC Call No.:   QA471.B7
Subjects:      Geometry -- Study and teaching. [from old
                  catalog]
               Geometry, Projective. [from old catalog]
Control No.:   7339620

Author:        Carnot, Lazare, 1753-1823.
Title:         Géométrie de position:
Published:     Paris, J. B. M. Duprat, an XI-1803.
Description:   2 p. l., xxxviii p., 1 l., 489 p. illus., diagrs.
                  on xv fold. pl. 27 cm.
LC Call No.:   QA471.C27
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   5942611

Author:        Carnot, Lazare, 1753-1823.
Title:         Geometrie der stellung,
Published:     Altona, J. F. Hammerich, 1808-10.
Description:   2 v. diagrs. on 10 fold. pl. 20 cm.
LC Call No.:   QA471.C29
Subjects:      Geometry, Projective. [from old catalog]
Other authors: Schumacher, Heinrich Christian, 1780-1850, [from
                  old catalog] tr.
Control No.:   9609588

Author:        Chasles, M. (Michel), 1793-1880.
Title:         Traité de géométrie supérieure, par M.
                  Chasles ...
Published:     Paris, Bachelier, 1852.
Description:   2 p. l., lxxxiii, 603 p. 198 diagr. on 12 fold.
                  pl. 22 cm.
LC Call No.:   QA471.C48
Notes:         Je fais suivre cette préface du Discours
                  d'inauguration du cours de géométrie supérieure de la
                  faculté des sciences, dans lequel, en jetant un coup d'œil
                  sur l'histoire de la géométrie, j'ai présenté quelques
                  considérations qui se rattachent au but de l'ouvrage
                  actuel."--Pref.
Subjects:      Geometry, Projective.
               Geometry -- History.
Control No.:   1216983

Author:        Coxeter, H. S. M. (Harold Scott Macdonald),
                  1907-
Title:         The real projective plane.
Edition:       1st ed.
Published:     New York, McGraw-Hill Book Co., 1949.
Description:   x, 196 p. diagrs. 24 cm.
LC Call No.:   QA471.C68
Dewey No.:     516.57
Notes:         Bibliography: p. 189-190.
Subjects:      Geometry, Projective.
Control No.:   8357223

Author:        Cremona, Luigi, 1830-1903.
Uniform Title: Elementi di geometria proiettiva. French
Title:         Éléments de géométrie projective, par Luigi
                  Cremona ... traduits, avec la collaboration de l'auteur, par
                  Éd. Dewulf ... 1 ptie.
Published:     Paris, Gauthier-Villars, 1875.
Description:   xvii, 272 p. diagrs. 23 cm.
LC Call No.:   QA471.C714
Notes:         No more published.
Subjects:      Geometry, Projective.
Control No.:   1217094

Author:        Cremona, Luigi, 1830-1903.
Uniform Title: Elementi di geometria proiettiva. English
Title:         Elements of projective geometry, by Luigi Cremona
                  ... tr. by Charles Leudesdorf ...
Published:     Oxford, Clarendon Press, 1885.
Description:   xxiii, 310 p. 23 cm.
LC Call No.:   QA471.C713 1885
Subjects:      Geometry, Projective.
Other authors: Leudesdorf, Charles, 1853-1924, tr.
Control No.:   8194722

Author:        Davidovic§, Stevan. [from old catalog]
Title:         Nacrtna geometrija za pitomce vojno akademije.
Published:     1896.
Description:   ix, 190 p. 24 cm.
LC Call No.:   QA471.D3
Control No.:   6767553

Author:        De Cleene, Louis Antoine Victor, 1893-
Title:         On triangles circumscribed about a conic and
                  inscribed in a cubic curve, by Louis Antoine Victor De Cleene
                  ...
Published:     Washington, D.C., 1927.
Description:   19 p. diagr. 25 cm.
LC Call No.:   QA471.D4 1927
Notes:         Thesis (PH. D.)--Catholic university of America,
                  1927.
               Biographical sketch.
Subjects:      Geometry, Projective.
               Conic sections.
               Triangle.
               Curves, Cubic.
Control No.:   2162588

Author:        Deaux, Roland, 1893-
Uniform Title: Introduction à la géométrie des nombres
                  complexes. English
Title:         Introduction to the geometry of complex numbers.
                  Translated from the rev. French ed. by  Howard Eves.
Published:     New York, F. Ungar Pub. Co. [1956]
Description:   208 p. illus. 25 cm.
LC Call No.:   QA471.D373
Dewey No.:     516.57
Notes:         Includes bibliography.
Subjects:      Numbers, Complex.
               Geometry, Projective.
Control No.:   276606

Author:        Doehlemann, Karl, 1864-1926. [from old catalog]
Title:         Projektive geometrie in synthetischer
                  behandlung,
Edition:       4., verb. aufl.
Published:     Berlin und Leipzig, G. J. Göschen, 1918.
Description:   181 p. diagrs. 16 cm.
LC Call No.:   QA471.D64 1918
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   7393817

Author:        Doehlemann, Karl, 1864- [from old catalog]
Title:         Projektive geometrie in synthetischer
                  behandlung,
Edition:       2. verm. und verb. aufl.
Published:     Leipzig, G. J. Göschen, 1901.
Description:   176 p. diagr. 16 cm.
LC Call No.:   QA471.D64
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   6322947

Author:        Dowling, L. Wayland (Linnaeus Wayland), b. 1867.
Title:         Projective geometry, by L. Wayland Dowling ...
Edition:       1st ed.
Published:     New York, McGraw-Hill book company, inc.; [etc.,
                  etc.] 1917.
Description:   xiii, 215 p. diagrs. 19 cm.
Series:        Modern mathematical texts, ed. by C.S. Slichter
LC Call No.:   QA471.D7
ISBN:          $2.00
Subjects:      Geometry, Projective.
Series Entry:  Modern mathematical texts.
Control No.:   4053250

Author:        Duporq, Ernest, 1873-1903.
Title:         Premiers principes de géométrie moderne à
                  l'usage des élèves de mathématiques spéciales et des
                  candidates à la licence et à l'agrégation, par Ernest
                  Duporcq.
Edition:       2. éd. rev. et augm. par Raoul Bricard.
Published:     Paris, Gauthier-Villars, 1912.
Description:   vii, 174 p. 23 cm.
LC Call No.:   QA471.D8 1912
Subjects:      Geometry, Projective.
Other authors: Bricard, Raoul, b. 1870.
Control No.:   5927976

Author:        Enriques, Federigo, 1871-1946.
Title:         Vorlesungen über projektive Geometrie von
                  Federigo Enriques ... Deutsche Ausg. von Dr. Hermann
                  Fleischer ... Mit einem Einführungswort von Felix Klein und
                  187 Figuren im Text.
Published:     Leipzig, B.G. Teubner, 1903.
Description:   xiv, 374 p. diagrs. 23 cm.
LC Call No.:   QA471.E59
Notes:         "Historische-kritische Notiz über die Entstehung
                  der Fundamentalbegriffe der projektiven Geometrie": p.
                  357-367.
Subjects:      Geometry, Projective.
Other authors: Fleischer, Hermann, tr. and ed.
Control No.:   7264343

Author:        Enriques, Federigo, 1871- [from old catalog]
Title:         Lessons in projective geometry,
Published:     Annandale-on-Hudson, N.Y., Printed by the
                  translator [c1933]
Description:   5 p.l., iii, 372 p. diagrs. 28 cm.
LC Call No.:   QA471.E6
Control No.:   6287523

Author:        Field, Peter, b. 1876.
Title:         Projective geometry, with applications to
                  engineering, by Peter Field ...
Published:     New York, W. Van Nostrand company, 1923.
Description:   viii, 98 p. diagrs. 22 cm.
LC Call No.:   QA471.F45
Subjects:      Geometry, Projective.
Control No.:   4526523

Author:        Filon, L. N. G. (Louis Napoleon George), 1875-
Title:         An introduction to projective geometry, by L.N.G.
                  Filon ...
Published:     London, E. Arnold [1908]
Description:   vi p., 1 l., 249, [1] p. diagrs. 19 cm.
LC Call No.:   QA471.F48
Subjects:      Geometry, Projective.
Control No.:   3579947

Author:        Gaba, Meyer Grupp, b. 1884.
Title:         A set of postulates for general projective
                  geometry ... by Meyer Grupp Gaba.
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1915.
Description:   1 p.l., 51-61, [1] p. 28 cm.
LC Call No.:   QA471.G2
Notes:         Thesis (Ph. D.)--University of Chicago, 1914.
               Vita.
               Reprinted from the Transactions of American
                  mathematical society, v. 16, no. 1, January, 1915.
Subjects:      Geometry, Projective -- Foundations.
Control No.:   4053134

Author:        Gibson, Robert Wilder, 1917- [from old catalog]
Title:         Projective geometry with coordinates from a
                  commutative primary ring,
Published:     Urbana, Ill., 1943.
Description:   [6] p. 23 cm.
LC Call No.:   QA471.G4
Subjects:      Geometry, Projective. [from old catalog]
               Group theory.
Control No.:   9267910

Author:        Gräfe, Friedrich, 1855-1918. [from old catalog]
Title:         Der Paskal'sche Satz.
Published:     Bern, Stämpfli'sche Buchdr., 1879.
Description:   30 p. 22 cm.
LC Call No.:   QA471.G73
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   5860114

Author:        Graham, Robert H. (Robert Hudson)
Title:         Geometry of position, by Robert H. Graham ...
Published:     London, New York, Macmillan and co., 1891.
Description:   xv, 192 p. diagrs. (part fold.) 19 cm.
LC Call No.:   QA471.G75
               Microfilm 15985 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Geometry, Projective.
Control No.:   1219179

Author:        Halsted, George Bruce, 1853-1922.
Title:         Elementary synthetic geometry. By George Bruce
                  Halsted ...
Published:     New York, J. Wiley & sons, 1892.
Description:   vi p., 1 l., 164 p. diagrs. 24 cm.
LC Call No.:   QA471.H19
Subjects:      Geometry, Projective.
Control No.:   4052229

Author:        Hart, T. E. [from old catalog]
Title:         Elemente der geometrie auf der geraden linie ...
Published:     Leipzig, Druck von B. G. Teubner [1867]
Description:   iv, [5]-49 p. 22 cm.
LC Call No.:   QA471.H32
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   8669664

Author:        Hatton, J. L. S. (John Leigh Smeathman),
                  1865-1933.
Title:         The theory of the imaginary in geometry, together
                  with the trigonometry of the imaginary, by J.L.S. Hatton ...
Published:     Cambridge, The University press, 1920.
Description:   vi, [2], 215, [1] p. diagrs. 24 cm.
LC Call No.:   QA471.H35
Subjects:      Geometry, Projective.
               Numbers, Complex.
Control No.:   273662

Author:        Henderson, Archibald, 1877- [from old catalog]
Title:         On the graphic representation of the projection
                  of two triads of planes into the mystic hexagram.
Published:     [Chapel Hill, N.C., 1904]
Description:   10 p. fold. diagr. 24 cm.
LC Call No.:   QA471.H48
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   8724974

Author:        Henderson, Archibald. [from old catalog]
Title:         The derivation of the Brianchon configuration
                  from two spatial pointtriads ...
Published:     [n. p., 19-?]
Description:   1 v. cm.
LC Call No.:   QA471.H4
Control No.:   6729342

Author:        Hertzer, Hugo [Ottomar], 1831- [from old
                  catalog]
Title:         Projectivische beziehungen einer besonderen art
                  ...
Published:     Berlin, Druck von C. Schultze, 1865.
Description:   31, [1] p. 20 cm.
LC Call No.:   QA471.H57
Subjects:      Geometry, Projective. [from old catalog]
Other authors: YA Pamphlet Collection (Library of Congress) DLC
                  [from old catalog]
Control No.:   7734609

Author:        Holgate, Thomas F. (Thomas Franklin), 1859-1945.
Title:         Projective pure geometry, by Thomas F. Holgate
                  ...
Published:     New York, The Macmillan company, 1930.
Description:   ix, 286 p. diagrs. 21 cm.
LC Call No.:   QA471.H6
Dewey No.:     515
Subjects:      Geometry, Projective.
Control No.:   3108326

Author:        Holst, Elling, 1849-1915.
Title:         Om Poncelet's betydning for geometrien. Et bidrag
                  til de moderngeometriske ideers udviklingshistorie af Elling
                  Holst ... Udgivet som universitets-program for 1ste halvaar
                  1879 ved Sophus Lie.
Published:     Christiania, Trykt hos A.W. Brøgger, 1878.
Description:   2 p.l., iii, [ix]-xvi, 146 p., 1 l. diagrs. 23
                  cm.
LC Call No.:   QA471.H75
Subjects:      Geometry, Projective.
               Poncelet, M. (Jean Victor), 1788-1867.
               Geometry -- History.
Other authors: Lie, Sophus, 1842-1899, ed.
Control No.:   3106942

Author:        Keller, Adam, 1864- [from old catalog]
Title:         Ueber gewisse vierecke, die von viereckspaaren
                  abhängen ...
Published:     Giessen, Druck von W. Keller, 1888.
Description:   29 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA471.K29
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   6800044

Author:        Lehmer, Derrick Norman, 1868-1938.
Title:         An elementary course in synthetic projective
                  geometry, by Derrick Norman Lehmer.
Published:     Boston, New York, Ginn and Company [c1917]
Description:   xiii, 123 p. diagrs. 20 cm.
LC Call No.:   QA471.L4
Subjects:      Geometry, Projective.
Control No.:   5903227

Author:        Ling, George Herbert, b. 1874.
Title:         Elements of projective geometry, by George
                  Herbert Ling, George Wentworth and David Eugene Smith.
Published:     Boston, New York [etc.] Ginn and company [1922]
Description:   vi, 186 p. diagrs. 22 cm.
Series:        Wentworth-Smith mathematical series
LC Call No.:   QA471.L5
Subjects:      Geometry, Projective.
Other authors: Wentworth, George, b. 1868, joint author.
               Smith, David Eugene, 1860-1944, joint author.
Control No.:   4526477

Author:        Mautz, Otto, 1878-
Title:         Ebene inversionsgeometrie, von dr. Otto Mautz.
Published:     Basel, Buchdr. Kreis & co., 1909.
Description:   62 p., 1 l. 29 cm.
Series:        Wissenschaftliche beilage zum Bericht über das
                  gymnasium schuljahr 1908-1909
LC Call No.:   QA471.M4
Subjects:      Geometry, Projective.
               Inversion.
Control No.:   8695280

Author:        Monteverde, G. F. (Giulio Filippo)
Title:         Elementi di geometria proiettiva / di G.F.
                  Monteverde.
Published:     Genova : Luigi Beuf, 1886.
Description:   2 v. : ill. ; 23 cm.
LC Call No.:   QA471.M66x 1886
Notes:         [1] Testo -- [2] Figure.
               Includes bibliographical references.
Subjects:      Geometry, Projective.
Control No.:   4291729

Author:        Patterson, Boyd Crumrine, 1902-
Title:         Projective geometry, by Boyd Crumrine Patterson
                  ...
Published:     New York, J. Wiley & sons, inc.; London, Chapman
                  & Hall, limited, 1937.
Description:   2 p.l., iii-xiii, 276 p. diagrs. 23 cm.
LC Call No.:   QA471.P37
Dewey No.:     516.57
ISBN:          $3.50
Notes:         "Projective geometry ... outline for a course of
                  ... lessons" (4 p.) laid in.
               "Supplementary reading": p. 263.
Subjects:      Geometry, Projective.
Control No.:   746840

Author:        Paulus, C. [from old catalog]
Title:         Grundlinien der neueren ebenen geometrie.
Published:     [n.p.] 1853.
Description:   1 v. cm.
LC Call No.:   QA471.P33
Control No.:   6733494

Author:        Peri, Giuseppe, 1822-1874. [from old catalog]
Title:         I principi della geometria moderna, esposti da G.
                  Peri e G. Bellacchi ... per dimostrare le proprietà delle
                  curve e superficie di 2.p0s grado in conformità dei nuovi
                  programmi ufficiali per gli istituti tecnici del regno.
Published:     Pistoia, Tipografia Niccolai, 1873.
Description:   viii, 414, [2] p. 24 pl. (diagrs.) 12 l. 23 cm.
LC Call No.:   QA471.P4
Subjects:      Geometry, Projective. [from old catalog]
Other authors: Bellacchi, Giacomo, 1839- [from old catalog]
                  joint author.
Control No.:   8753385

Author:        Poncelet, M. (Jean Victor), 1788-1867.
Title:         Applications d'analyse et de géométrie, qui ont
                  servi de principal fondement au Traité des propriétés
                  projectives des figures, par J.-V. Poncelet. Avec additions
                  par mm. Mannheim et Moutard ...
Published:     Paris, Mallet-Bachelier, 1862-64.
Description:   2 v. diagrs. 22 cm.
LC Call No.:   QA471.P75
Dewey No.:     513.5
Notes:         Vol. 2 has imprint: Paris, Gauthier-Villars,
                  successeur de Mallet-Bachelier.
Subjects:      Geometry, Projective.
Other authors: Mannheim, A. (Amédée), 1831-1906.
               Moutard, Théodore Florentin, 1827-1901.
Control No.:   9222956

Author:        Poncelet, M. (Jean Victor), 1788-1867.
Title:         Traité des propriétés projectives des figures,
                  ouvrage utile à qui s'occupent des applications de la
                  géométrie descriptive et d'opérations géométriques sur
                  le terrain Par J. V. Poncelet.
Edition:       2. éd.
Published:     Paris, Gauthier-Villars, 1865-66.
Description:   2v. diagrs. on 18 fold. pl. 28x22cm.
LC Call No.:   QA471.P8
Notes:         Vol. 1: 2. éd., rev., cor. et augm.
                  d'annotations nouvelles.
               Vol. 2: 2. éd., rev. par l'auteur et augm. de
                  sections et d'annotations nouvelles ou jusqu'ici inédites.
Subjects:      Geometry, Projective.
Control No.:   5864396

Author:        Rey Pastor, Julio, 1888- [from old catalog]
Title:         Fundamentos de la geometría proyectiva
                  superior,
Published:     Madrid [Estab. tip. de Fortanet] 1916.
Description:   xxii, 444 p., 1 l. 24 cm.
LC Call No.:   QA471.R47
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   6459947

Author:        Reye, Theodor, 1838-1919. [from old catalog]
Title:         Die geometrie der lage;
Published:     Stuttgart, A. Kröner, 1907-10.
Description:   3 v. diagrs. 25 cm.
LC Call No.:   QA471.R5
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   6819108

Author:        Reye, Theodor, 1838-1919. [from old catalog]
Title:         Die geometrie der lage.
Edition:       2. verm. aufl.
Published:     Hannover, C. Rümpler, 1877-80.
Description:   2 v. fold. diagrs. 24 cm.
LC Call No.:   QA471.R49
               Microfilm 15411 QA
Notes:         Replace; LC copy replaced by preservation
                  microfilm DLC
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   9741169

Author:        Robb, Dean Leroy, 1907- [from old catalog]
Title:         Special cases of the symmetric correspondence
                  C6,6 and their relation to the general C6,6 ...
Published:     Washington, D.C., The Catholic university of
                  America press, 1942.
Description:   v, 57 p. incl. tables, diagrs. 23 cm.
LC Call No.:   QA471.R6
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   7853819

Author:        Rosenbaum, R. A. (Robert A.)
Title:         Introduction to projective geometry and modern
                  algebra.
Published:     Reading, Mass., Addison-Wesley Pub. Co. [1963]
Description:   344 p. illus. 24 cm.
Series:        Addison-Wesley series in mathematics
LC Call No.:   QA471.R68
Dewey No.:     516.57
Notes:         Includes bibliography.
Subjects:      Geometry, Projective.
               Algebra.
Control No.:   1695252

Author:        Russell, John Wellesley, 1851-1922.
Title:         An elementary treatise on pure geometry with
                  numerous examples, by John Wellesley Russell ...
Edition:       New and rev. ed.
Published:     Oxford, Clarendon Press, 1905.
Description:   xii p., 1 l., 366, [2] p. fold. pl., diagrs. 20
                  cm.
LC Call No.:   QA471.R8
Subjects:      Geometry, Projective.
               Geometry.
Control No.:   6811586

Author:        Sanger, R. G. (Ralph Grafton), 1905-
Title:         Synthetic projective geometry, by R.G. Sanger
                  ...
Edition:       1st ed.
Published:     New York, London, McGraw-Hill book company, inc.,
                  1939.
Description:   ix, 175 p. diagrs. 21 cm.
LC Call No.:   QA471.S25
Dewey No.:     516.57
Subjects:      Geometry, Projective.
Control No.:   4054368

Author:        Sannia, Achille.
Title:         Lezioni di geometria proiettiva dettate nella R.
                  Università di Napoli / dal Achille Sannia.
Edition:       2. ed. ampliato/ con prefazione di E. d'Ovidio.
Published:     Napoli : B. Pellerano, 1895.
Description:   xvi, 763 p. : ill. ; 25 cm.
LC Call No.:   QA471.S26x 1895
Subjects:      Geometry, Projective.
Control No.:   3818831

Author:        Schwatt, Isaac J. (Isaac Joachim), 1867-
Title:         A geometrical treatment of curves which are
                  isogonal conjugate to a straight line with respect to a
                  triangle. In two parts. Part first. By I.J. Schwatt ...
Published:     Boston, New York [etc.] Leach, Shewell, and
                  Sanborn [c1895]
Description:   3 p. l., 45 p. 3 fold. pl. (diagrs.) 24 cm.
LC Call No.:   QA471.S41
Subjects:      Hyperbola.
               Ellipse.
Control No.:   12928731

Author:        Seidenberg, A. (Abraham), 1916-
Title:         Lectures in projective geometry.
Published:     Princeton, N.J., Van Nostrand [1962]
Description:   230 p. illus. 24 cm.
Series:        The University series in undergraduate
                  mathematics
LC Call No.:   QA471.S42
Dewey No.:     516.57
Notes:         Includes bibliography.
Subjects:      Geometry, Projective.
               Geometry, Analytic.
Other titles:  Projective geometry.
Control No.:   1694731

Author:        Sohon, F. W. (Frederick Wyatt), 1894-
Title:         The stereographic projection, by F. W. Sohon ...
Published:     Brooklyn, N.Y., Chemical publishing co., inc.,
                  1941.
Description:   ix, 210 p. incl. tables, diagrs.  pl. 23 cm.
LC Call No.:   QA471.S65
Dewey No.:     516.57
Subjects:      Geometry, Projective
Control No.:   9254402

Author:        Staudt, Karl Georg Christian von, 1798-1867.
Title:         Geometrie der lage, von dr. Georg Karl Christian
                  v. Staudt.
Published:     Nürnberg, F. Korn [1847]
Description:   vi, 216 p. 24 cm.
LC Call No.:   QA471.S8
Dewey No.:     516.57
Subjects:      Geometry, Projective
Control No.:   6424214

Author:        Steiner, Jakob, 1796-1863.
Uniform Title: Geometrischen Konstructionen. English
Title:         Geometrical constructions with a ruler, given a
                  fixed circle with its center. Translated from the first
                  German ed. (1833) by Marion Elizabeth Stark; edited with an
                  introd. and notes by Raymond Clare Archibald.
Published:     New York, Scripta Mathematica, Yeshiva
                  University, 1950.
Description:   88 p. ports. 26 cm.
Series:        Scripta mathematica studies ; no. 4
LC Call No.:   QA471.S823
Dewey No.:     516.57
Notes:         Bibliographical references included in "Editor's
                  introduction" (p. 1-9)
Subjects:      Geometry, Projective.
Other authors: Archibald, Raymond Clare, 1875-1957, ed.
Control No.:   4055359

Author:        Steiner, Jakob, 1796-1863.
Title:         Die geometrischen constructionen, ausgeführt
                  mittelst der geraden linie und eines festen kreises, als
                  lehrgegenstand auf höheren unterrichts-anstalten und zur
                  praktischen benutzung, von Jacob Steiner (1833) Hrsg. von A.
                  J. v. Oettingen. Mit 25 text figuren.
Published:     Leipzig, W. Engelmann, 1895.
Description:   84 p., 1 l. diagr. 20 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften,
                  nr. 60
LC Call No.:   QA471.S82
Notes:         First published Berlin, 1833.
Subjects:      Geometry, Projective.
Other authors: Oettingen, A. v. (Arthur), 1836-1920, ed.
Control No.:   8666218

Author:        Steiner, Jakob, 1796-1863.
Title:         Systematische entwicklung der Abhängigkeit
                  geometrischer gestalten von einander, mit berücksichtigung
                  der arbeiten alter und neuer geometer über porismen,
                  projections-methoden, geometrie der lage, transversalen,
                  dualität, und reciptrocität, etc., von Jacob Steiner ...
                  Hrsg. von A.J. von Oettingen.
Published:     Leipzig, W. Engelmann, 1896.
Description:   2 v. illus. 20 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften,
                  nr. 82-83
LC Call No.:   QA471.S84
Notes:         First edition, Berlin, 1832.
Subjects:      Geometry, Projective.
Other authors: Oettingen, A. v. (Arthur), 1836-1920, ed.
Control No.:   6324742

Author:        Todd, John, 1911-
Title:         Projective and analytical geometry.
Published:     New York, Pitman Pub. Corp. [1947]
Description:   x, 289 p. illus. 22 cm.
LC Call No.:   QA471.T6
Dewey No.:     516.57
Subjects:      Geometry, Projective.
               Geometry, Analytic.
Control No.:   7884080

Author:        Veblen, Oswald, 1880-1960.
Title:         Projective geometry, by Oswald Veblen ... and
                  John Wesley Young ...
Published:     Boston, New York [etc.] Ginn and Company
                  [1910-18]
Description:   2 v. diagrs. 24 cm.
LC Call No.:   QA471.V4
Subjects:      Geometry, Projective.
Other authors: Young, John Wesley, 1879-1932, joint author.
Control No.:   5883059

Author:        Venable, Charles S. (Charles Scott), 1827-1900.
Title:         Introduction to modern geometry. By Charles S.
                  Venable.
Published:     New York, University Publishing Company, 1887.
Description:   1 p. l., [367]-413 p. 21 cm.
LC Call No.:   QA471.N44
Notes:         At head of title: Appendix to Venable's Elements
                  of geometry.
Subjects:      Geometry, Projective.
Control No.:   9139586

Author:        Watson, Emery Ernest, 1876- [from old catalog]
Title:         Elements of projective geometry,
Published:     Boston, New York [etc.] D. C. Heath and company
                  [c1935]
Description:   v p., 1 l., 255 p. illus., diagrs. 21 cm.
LC Call No.:   QA471.W3
Subjects:      Geometry, Projective. [from old catalog]
Other authors: Watson, Margaret Marie, [from old catalog] joint
                  author.
Control No.:   8765251

Author:        Weyr, Eduard, 1852-1903.
Title:         Projektivná geometrie zakladných útvarêu
                  prvního ˆrádu. Napsal Eduard Weyr.
Published:     V Praze, Nákladem Jednoty ˆceských
                  mathematikêu, 1898.
Description:   viii, 189, [3] p. diagr. 24 cm.
Series:        Sborník Jednoty ˆceských mathematikêu v Praze.
                  ˆcislo I
LC Call No.:   QA471.W54
Subjects:      Geometry, Projective.
Series Entry:  Jednota ˆceskoslovenských matematikêu a fyskiêu
                  v Praze. Sbornik ; císlo 1.
Control No.:   6791094

Author:        Whitehead, Alfred North, 1861-1947.
Title:         The axioms of projective geometry, by A. N.
                  Whitehead.
Published:     Cambridge, University Press, 1906.
Description:   viii, 64 p. diagrs. 22 cm.
Series:        Cambridge tracts in mathematics and mathematical
                  physics, no. 4
LC Call No.:   QA471.W59
Subjects:      Geometry, Projective.
Control No.:   5872988

Author:        Whitehead, John Henry Constantine, 1904-1960.
Title:         The representation of projective spaces ... by
                  J.H.C. Whitehead.
Published:     Princeton, 1931.
Description:   1 p. l., p. 327-360. 26 cm.
LC Call No.:   QA471.W62 1930
Dewey No.:     513.5
Notes:         Thesis (PH. D.)--Princeton University, 1930.
               "Reprinted from the Annals of Mathematics, vol.
                  32, number 2."
Subjects:      Hyperspace.
               Geometry, Projective.
Control No.:   7349981

Author:        Winger, Roy Martin, 1885-
Title:         An introduction to projective geometry, by R.M.
                  Winger ...
Published:     Boston, New York [etc.] D.C. Heath & Co. [c1923]
Description:   xiii, 443 p. diagrs. 20 cm.
LC Call No.:   QA471.W63
Notes:         "References": p. 423.
Subjects:      Geometry, Projective.
Control No.:   5917696

Author:        Woods, Baldwin M. (Baldwin Munger), 1887-1956.
Title:         A discussion of synthetic methods of two
                  projective pencils of conics ...
Published:     Berneby, 1913.
Description:   1 v. fol. cm.
LC Call No.:   QA471.W65
Control No.:   7199776

Author:        Young, John Wesley, 1879-1932.
Title:         Projective geometry, by John Wesley Young ...
Published:     Chicago, Ill., Pub. for the Mathematical
                  association of America by the Open court publishing company
                  [c1930]
Description:   ix, 185 p. illus., diagrs. 20 cm.
Series:        The Carus mathematical monographs ; no. 4
LC Call No.:   QA471.Y6
Dewey No.:     515
Subjects:      Geometry, Projective.
Control No.:   1218623

Author:        Zacharias, Max, 1873-
Title:         Einführung in die projektive geometrie, von dr.
                  Max Zacharias...mit 18 figuren im text.
Published:     Leipzig und  Berlin, B.G. Teubner, 1912.
Description:   iv, 51, [1] p. diagrs. 18 1/2 cm.
Series:        Mathematische bibliothek, hrsg. von W. Lietzmann
                  und A. Witting. 6
LC Call No.:   QA471.Z3
Subjects:      Geometry, Projective.
Control No.:   7296303

Author:        Adler, Claire Fisher, 1895-
Title:         Modern geometry; an integrated first course.
Published:     New York, McGraw-Hill, 1958.
Description:   215 p. illus. 24 cm.
LC Call No.:   QA473.A15
Dewey No.:     513.01
Subjects:      Geometry -- Foundations.
               Geometry, Modern.
Control No.:   10279012

Author:        Benoit, Paul, b. 1823.
Title:         Essai d'une géométrie nouvelle / par Paul
                  Benoit.
Published:     Saint-Dié : Ad. Weick, 1900.
Description:   149, x p. : ill. ; 22 cm.
LC Call No.:   QA473.B46x 1900
Notes:         Lithograph of manuscript.
Subjects:      Geometry.
Control No.:   2400481

Author:        Hoch, Julius, 1855-1928.
Title:         Das Wichtigste aus der Geometrie / bearbeitet von
                  Julius Hoch.
Published:     Leipzig : Hilmar Klasing, 1902.
Description:   2 v. : ill. ; 22 cm.
Series:        Dr. iur. Ludwig Huberti's praktische gewerbliche
                  Bibliothek
LC Call No.:   QA473.H62x 1902
Notes:         1. Leitfaden der ebenen Geometrie für
                  Gewerbetreibende und gewerbliche Schulen -- 2. Leitfaden der
                  räumlichen Geometrie für Gewerbetreibende und gewerbliche
                  Schulen.
Subjects:      Geometry, Plane.
               Geometry, Solid.
Control No.:   4764774

Author:        Morley, Frank, 1860-1937.
Title:         Inversive geometry, by Frank Morley ... and F.V.
                  Morley ...
Published:     Boston, New York [etc.] Ginn and Company, 1933.
Description:   ix p., 1 l., 273 p. diagrs. 22 cm.
LC Call No.:   QA473.M7
Dewey No.:     515
Notes:         Printed in Great Britain.
Subjects:      Geometry, Modern.
Other authors: Morley, F. V. (Frank Vigor), 1899- joint author.
Control No.:   7355156

Author:        Morvan, Irene, Sister, 1912- [from old catalog]
Title:         A study of loci associated with systems of
                  isopolar lines of lines with respect to a quadrangle.
Published:     Washington, Catholic University of America Press,
                  1954.
Description:   iii, 28 p. 23 cm.
LC Call No.:   QA473.M74
Subjects:      Geometry, Modern -- Plane. [from old catalog]
Other titles:  Loci associated with systems of isopolar lines.
Control No.:   9323780

Author:        Shively, Levi S. (Levi Stephen), b. 1884.
Title:         An introduction to modern geometry, by Levi S.
                  Shively ...
Published:     New York, J. Wiley & sons, inc.; London, Chapman
                  & Hall, limited, 1939.
Description:   xi, 167 p. 23 cm.
LC Call No.:   QA473.S45
Dewey No.:     513.5
ISBN:          $2.00
Notes:         Bibliography: p. 161.
Subjects:      Geometry, Modern.
Control No.:   1691223

Author:        Smith, William Benjamin, 1850-1934.
Title:         Introductory modern geometry of point, ray, and
                  circle / by William Benjamin Smith.
Published:     New York; and London : Macmillan, 1893.
Description:   297 p. : illus. ; 19 cm.
LC Call No.:   QA473.S55 1893
Subjects:      Geometry, Projective.
Control No.:   10073132

Author:        Smith, William Benjamin, 1850- [from old
                  catalog]
Title:         Introductory modern geometry of point, ray, and
                  circle.
Published:     New York and London, Macmillan & co., 1892.
Description:   3 p.l., 143 p. diagrs. 19 cm.
LC Call No.:   QA473.S55 1892
Subjects:      Geometry, Projective. [from old catalog]
Control No.:   8669479

Author:        Altshiller-Court, Nathan, b. 1881.
Title:         College geometry; a second course in plane
                  geometry for colleges and normal schools, by Nathan
                  Altshiller-Court ...
Published:     Richmond, Va., Johnson publishing company
                  [c1925]
Description:   xiii p., 1 l., 254 p. front., diagrs. 24 cm.
LC Call No.:   QA474.C6
Dewey No.:     513.5
Subjects:      Geometry, Modern -- Plane.
Control No.:   2162423

Author:        Altshiller-Court, Nathan, b. 1881.
Title:         College geometry; an introduction to the modern
                  geometry of the triangle and the circle.
Edition:       2d ed., rev. and. enl.
Published:     New York, Barnes & Noble [1952]
Description:   313 p. illus. 22 cm.
LC Call No.:   QA474.C6 1952
Dewey No.:     513.5
Subjects:      Geometry, Modern -- Plane.
Control No.:   6970017

Author:        Daus, Paul H. (Paul Harold), 1894-
Title:         College geometry [by] Paul H. Daus ...
Published:     New York, Prentice-Hall, inc., 1941.
Description:   xv, 200 p. diagrs. 24 cm.
Series:        [Prentice-Hall mathematics series; A.A. Bennett,
                  editor]
LC Call No.:   QA474.D3
Dewey No.:     513.1
Notes:         Bibliography: p. 191-192.
Subjects:      Geometry, Modern -- Plane.
Series Entry:  Prentice-Hall mathematics series.
Control No.:   1219330

Author:        Durell, Clement V. (Clement Vavasor), b. 1882.
Title:         Modern geometry; the straight line and circle, by
                  Clement V. Durell ...
Published:     London, Macmillan and co., limited, 1920.
Description:   x, 145 p. diagrs. 19 cm.
LC Call No.:   QA474.D8
Dewey No.:     513.5
Notes:         Revision of the author' Course of plane geometry
                  for advanced students, pt. 1, 1909. cf. Pref.
Subjects:      Geometry, Modern -- Plane.
Control No.:   4526401

Author:        Godfrey, C. (Charles), 1873-1924.
Title:         Modern geometry, by C. Godfrey ... and A.W.
                  Siddons ...
Published:     Cambridge, University Press, 1908.
Description:   xvi, 162 p. diagrs. 20 cm.
LC Call No.:   QA474.G6
Subjects:      Geometry, Modern -- Plane.
Other authors: Siddons, A. W. (Arthur Warry) joint author.
Control No.:   6819936

Author:        Johnson, Roger A. (Roger Arthur)
Title:         Modern geometry; an elementary treatise on the
                  geometry of the triangle and the circle, by Roger A. Johnson
                  ... under the editorship of John Wesley Young ...
Published:     Boston, New York [etc.] Houghton, Mifflin company
                  [1929]
Description:   xiii, 319 p. diagrs. 20 cm.
LC Call No.:   QA474.J6
Dewey No.:     513.5
Notes:         Bibliography: p. vi-vii.
Subjects:      Geometry, Modern -- Plane.
Other authors: Young, John Wesley, 1879-1932, ed.
Control No.:   3108291

Author:        McBrien, Vincent Owen, 1916- [from old catalog]
Title:         On some systems of orthopolar and Kantor lines
                  referred to a quadrangle ...
Published:     Washington, D.C., The Catholic university of
                  America press, 1942.
Description:   2 p.l., 25 p. 23 cm.
LC Call No.:   QA474.M3
Subjects:      Geometry, Modern -- Plane. [from old catalog]
Other titles:  Orthopolar and Kantor lines of lines referred to
                  a quadrangle.
Control No.:   7385605

Author:        Steele, Mary Philip, sister, 1905- [from old
                  catalog]
Title:         A geometric interpretation and some applications
                  of the dihedral group Gb6s,
Published:     Washingon, D.C., the Catholic university of
                  America press, 1943.
Description:   4 p. l., 71 p. diagrs. 23 cm.
LC Call No.:   QA474.S8
Subjects:      Geometry, Modern -- Plane. [from old catalog]
               Group theory.
Control No.:   10204784

Author:        Taylor, E. H. (Edson Homer), 1874-
Title:         An introduction to college geometry, by E. H.
                  Taylor and G. C. Bartoo.
Edition:       [Rev. ed.]
Published:     New York, Macmillan Co., 1949.
Description:   vii, 143 p. 21 cm.
LC Call No.:   QA474.T3 1949
Dewey No.:     513
Subjects:      Geometry, Modern -- Plane.
Other authors: Bartoo, G. C. (Grover Cleveland), 1884- joint
                  author.
Control No.:   7420649

Author:        Taylor, E. H. (Edson Homer), 1874-
Title:         An introduction to college geometry, by E.H.
                  Taylor ... and G.C. Bartoo.
Published:     Hastings, Mich., Lithocraft, c1939.
Description:   1 p. l., 127, 27 p. diagrs. 23 cm.
LC Call No.:   QA474.T3 1939
Dewey No.:     513
Subjects:      Geometry.
Other authors: Bartoo, G. C. (Grover Cleveland), 1884- joint
                  author.
Control No.:   6907423

Author:        Winsor, Arthur Simeon.
Title:         Modern higher plane geometry, by Arthur S. Winson
                  ...
Published:     Boston, Mass., The Christopher publishing house
                  [c1941]
Description:   xvii, 19-214 p. diagrs. 21 cm.
LC Call No.:   QA474.W5 1941
Dewey No.:     513.5
Subjects:      Geometry, Modern -- Plane.
Control No.:   8318564

Author:        Winsor, Arthur Simeon.
Title:         Modern higher plane geometry, by Arthur S.
                  Winsor.
Published:     Ann Arbor, Mich., Edwards brothers, inc., 1940.
Description:   viii, 118 p. diagrs. 28 x 22 cm.
LC Call No.:   QA474.W5
Dewey No.:     513.5
Notes:         "Lithoprinted."
Subjects:      Geometry, Modern -- Plane.
Control No.:   7380735

Author:        Altshiller-Court, Nathan, b. 1881.
Title:         Modern pure solid geometry, by Nathan
                  Altshiller-Court ...
Published:     New York, The Macmillan company, 1935.
Description:   x p., 1 l., 311 p. diagrs. 22 cm.
LC Call No.:   QA475.C6
Dewey No.:     516.5
Notes:         "Bibliographical notes": p. 297-303.
Subjects:      Geometry, Modern -- Solid.
Control No.:   2635823

Author:        Bardot, Ad. [from old catalog]
Title:         Question de géométrie. Base d'une théorie
                  générale des parallèles sans postulatum.
Published:     Paris, Librairie C. Delagrave, 1873.
Description:   8 p. 22 cm.
LC Call No.:   QA481.B24
Subjects:      Parallels (Geometry) [from old catalog]
Control No.:   9613634

Author:        Barnett, Samuel, 1824- [from old catalog]
Title:         Elements of geometry, or, Introduction to the
                  science of space.
Published:     Washington, Ga., H. F. Andrews & co., printers,
                  1875.
Description:   cover-title, [3]-22 p. 21 cm.
LC Call No.:   QA481.B26
Subjects:      Geometry. [from old catalog]
Control No.:   10074535

Author:        Byrne, Oliver.
Title:         The doctrine of proportion clearly developed, on
                  a comprehensive, original, and very easy system; or, The
                  fifth book of Euclid simplified. By Oliver Byrne ...
Published:     London, J. Williams, 1841.
Description:   xix, 98, [2] p. 22 cm.
LC Call No.:   QA481.B9
Subjects:      Ratio and proportion.
Control No.:   2634040

Author:        Cataldi, Pietro Antonio, ca. 1548-1626.
Title:         Opvscvlvm de lineis rectis æqvidistantibvs, et
                  non æqvidistantibvs.
Published:     Bononiæ, apud hæredes I. Rossij, 1603.
Description:   2 p.l., 72 p. diagrs. 22 cm.
LC Call No.:   QA481.C3
Subjects:      Parallels (Geometry)
Control No.:   6348106

Author:        Crivetz, Théodore.
Title:         Essai sur le postulat d'Euclide, par Théodore
                  Crivetz ...
Published:     Bucarest, Établissement graphique I.V. Socecæu,
                  1895.
Description:   40 p. diagrs. 23 cm.
LC Call No.:   QA481.C8
Subjects:      Parallels (Geometry)
Control No.:   3579396

Author:        Crivetz, Théodore.
Title:         Essai sur l'équidistante, par Théodore Crivetz
                  ...
Published:     Bucarest, l'Institut d'arts graphiques, C. Göbl,
                  1900.
Description:   50 p. diagrs. 25 cm.
LC Call No.:   QA481.C9
Subjects:      Parallels (Geometry)
Control No.:   7722573

Author:        Davies, Charles, 1798-1876.
Title:         An examination of the demonstrations of Davies'
                  Legendre, showing how the polygon becomes the circle, by the
                  methods of Newton. By Charles Davies.
Published:     New York, A.S. Barnes, 1873.
Description:   36 p. : diagrs. ; 19 cm.
LC Call No.:   QA481.D2
Notes:         Cover title.
Subjects:      Newton, Isaac, Sir, 1642-1727. Principia.
               Circle.
Control No.:   8202953

Author:        Exley, Thomas, d. 1855? [from old catalog]
Title:         The theory of parallel lines perfected;
Published:     London, Printed for the author, 1818.
Description:   16 p. 22 cm.
LC Call No.:   QA481.E9
Subjects:      Parallels (Geometry) [from old catalog]
Control No.:   8674824

Author:        Kazarinoff, Nicholas D.
Title:         Geometric inequalities.
Published:     [New York] Random House [1961]
Description:   132 p. illus. 23 cm.
Series:        New mathematical library, 4
LC Call No.:   QA481.K35
Dewey No.:     513.1
Subjects:      Geometry, Plane.
               Inequalities (Mathematics)
Control No.:   1694420

Author:        [Kircher, Adolphe] [from old catalog]
Title:         Nouvelle théorie des parallèles,
Published:     Paris, Courcier, an XI--1803.
Description:   xiii, [13]-64 p. diagrs. on fold. pl. 20 cm.
LC Call No.:   QA481.K58
Subjects:      Parallels (Geometry)
Other authors: Legendre, A. M. (Adrien Marie), 1752-1833.
Control No.:   6333317

Author:        Liévano, Indalecio. [from old catalog]
Title:         Investigaciones científicas,
Published:     Bogotá, F. Mantilla, 1871.
Description:   85, [3] p. diagrs. on 2 fold. pl. 23 cm.
LC Call No.:   QA481.L6
Subjects:      Parallels (Geometry) [from old catalog]
               Arithmetic -- Problems, exercises, etc.
Control No.:   6347254

Author:        Ryan, Matthew. [from old catalog]
Title:         The celebrated theory of parallels.
Published:     Washington, Chronicle print, 1866.
Description:   10 p. diagrs. 22 cm.
LC Call No.:   QA481.R94
Subjects:      Geometry -- Miscellanea.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
                  [from old catalog]
Control No.:   7731423

Author:        Ryan, Matthew. [from old catalog]
Title:         Euclid's "world-renowned parallel postulate;"
Published:     Washington, D. C., The H. E. Wilkens printing
                  company [1905]
Description:   29 p. 23 cm.
LC Call No.:   QA481.R96
               Microfilm 65302 QA
Control No.:   6798377

Author:        Saladini, Girolamo, 1731-1813.
Title:         Nuovo metodo delle proporzioni geometrica,
                  aritmetica, ed armonica di d. Girolamo Saladini ...
Published:     Bologna : Stamperia di S. Tommaso d'Aquino,
                  1761.
Description:   xiv, 103, [1] p. diagrs. on III fold. pl. 19 cm.
LC Call No.:   QA481.S3
Subjects:      Ratio and proportion -- Early works to 1800.
Control No.:   7297348

Author:        Stringham, Irving, 1847- [from old catalog]
Title:         The geometrical theory of proportion.
Published:     San Francisco, The Berkeley press, 1893.
Description:   22 p. diagrs. 18 cm.
LC Call No.:   QA481.S9
Subjects:      Ratio and proportion. [from old catalog]
Control No.:   9606908

Title:         Concerning the degree of equivalence of
                  polygons;
Published:     [Chicago] The College, University of Chicago,
                  c1952.
Description:   21 l. diagrs. 28 cm.
LC Call No.:   QA482.C7
Subjects:      Polygons. [from old catalog]
Other authors: Tarski, Alfred. [from old catalog]
               Moese, Henryk. [from old catalog]
Control No.:   8856126

Author:        Aley, Robert J. (Robert Judson), 1863-1935.
Title:         Contributions to the geometry of the triangle, by
                  Robert Judson Aley.
LC Call No.:   QA482.Z38
Notes:         In Pennsylvania.  University.  Publications. 
                  Series in mathematics.  Philadelphia, 1897.  26 cm.  no. 1,
                  p. 3-32.  diagrs. on fold. pl.
               Accepted by the Department of mathematics of the
                  University of Pennsylvania, in partial fulfillment of the
                  requirements for the degree of doctor of philosophy.  cf. p.
                  3.
Subjects:      Triangle
Series Entry:  University of Pennsylvania. Publications.  Series
                  in mathematics ; no. 1, p. 3-32.
Control No.:   7272647

Author:        Baker, Marcus, 1849-1903.
Title:         Discussion of a geometrical problem: with
                  bibliographical notes. By Marcus Baker ... December 6, 1879.
Published:     Philadelphia, Collins, printer, 1880.
Description:   p. [55]-65. diagrs. 23 cm.
LC Call No.:   QA482.B1
Notes:         Cover-title.
               "Extracted from the Bulletin of the
                  [Philosophical] society [of Washington]"
               Problem: In a right-angled triangle, there are
                  given the bisectors of the acute angles: required to
                  determine the triangle.
Subjects:      Triangle.
Control No.:   7263363

Author:        Baker, Richard Philip, 1866-1937.
Title:         The problem of the angle-bisectors ...
Published:     Chicago, Ill., The University of Chicago press
                  [1911]
Description:   vi, 99 p. diagrs. 29 cm.
LC Call No.:   QA482.B16
ISBN:          $1.00
Notes:         Thesis (Ph.D.)--University of Chicago.
               Vita.
Subjects:      Triangle.
Other titles:  Angle-bisectors.
Control No.:   4052893

Author:        Blakslee, T[homas] M[arcus]. [from old catalog]
Title:         Direction as a quantity.
Published:     [Des Moines, Iowa, 1887]
Description:   19 p. diagrs. 23 cm.
LC Call No.:   QA482.B63
Subjects:      Geometry, Plane. [from old catalog]
Control No.:   9608007

Author:        Bruce, W. H. (William Herschel), 1856-1943.
Title:         Some noteworthy properties of the triangle and
                  its circles, by W.H. Bruce.
Published:     Boston, D.C. Heath & co., 1902.
Description:   28 p. 20 cm.
Series:        Heath's mathematical monographs, no. 8
LC Call No.:   QA482.B88
Subjects:      Triangle.
Series Entry:  Heath's mathematical monographs ; no. 8.
Control No.:   2633859

Author:        Bruce, William Herschel, 1856-
Title:         The nine circles of the triangle, by W. H.
                  Bruce.
Published:     [Denton, Tex., North Texas State Teachers
                  College, c1932]
Description:   2 p. l., [3]-48 p. illus. 19 cm.
LC Call No.:   QA482.B87
Subjects:      Triangle.
               Circle.
Control No.:   5943742

Author:        Cousinéry, B[arthélémy] É[douard], 1790-1851.
                  [from old catalog]
Title:         Le rapporteur de précision, contenant les cordes
                  successives de la demi-circonférence calculées dans les
                  trois systèmes de graduation, sexagésimal, centésimal et
                  mixte les sinus naturels du premier et du dernier système;
Published:     Paris, Carilian-Goeury et Vor. Dalmont, 1843.
Description:   xxxviii, [2], 87, [1] p. tables, diagrs. on fold.
                  pl. 24 cm.
LC Call No.:   QA482.C8
Subjects:      Trigonometry -- Tables.
               Angles (Geometry)
Control No.:   5858951

Author:        Cruewell, Ernst R. [from old catalog]
Title:         Regeln der mathematik.
Published:     [n.p.] 1903.
Description:   v. cm.
LC Call No.:   QA482.C95
Control No.:   7213590

Author:        Gallatly, William.
Title:         The modern geometry of the triangle. By William
                  Gallatly ...
Published:     London, F. Hodgson [1910]
Description:   1 p. l., 70 p., 1 l. diagrs. 21 cm.
LC Call No.:   QA482.G3
Subjects:      Triangle.
Other titles:  Geometry of the triangle.
Control No.:   5892133

Author:        Goldenring, Robert. [from old catalog]
Title:         Die elementargeometrischen konstruktionen des
                  regelmässigen siebzehnecks.
Published:     Leipzig und Berlin, B. G. Teubner, 1915.
Description:   4 p. l., 69 p. diagrs. 25 cm.
LC Call No.:   QA482.G6
Subjects:      Polygons. [from old catalog]
Control No.:   5901154

Author:        Haughery, Michael J.
Title:         Theorems on squares and rectangles inscribed in
                  right triangles, by Michael J. Haughery.
Published:     Pittsburgh, Pa., William G. Johnston Company
                  [c1934]
Description:   2 p. l., 15 p. diagrs. 19 cm.
LC Call No.:   QA482.H3 1934
Subjects:      Triangle.
               Geometry, Plane.
Control No.:   8292294

Author:        Haughery, Michael J. [from old catalog]
Title:         Theorems on squares and rectangles inscribed in
                  right triangles,
Published:     Pittsburgh, Pa., William G. Johnston company
                  [c1933]
Description:   2 p.l., 14 p. diagrs. 19 cm.
LC Call No.:   QA482.H3
Subjects:      Triangle. [from old catalog]
               Geometry, Plane. [from old catalog]
Control No.:   5949259

Author:        Heyl, Pual Renno, 1872- [from old catalog]
Title:         Properties of the locus r = constant, in space of
                  n dismensions,
Published:     Philadelphia, 1897.
Description:   p. 33-39. fold. pl. 26 cm.
LC Call No.:   QA482.A38
Subjects:      Hyperspace. [from old catalog]
Control No.:   5868166

Author:        [Holloway, Henry H.] [from old catalog]
Title:         Elements of geometry.
Published:     [n. p., 186-]
Description:   [9]-51 p. diagrs. 21 cm.
LC Call No.:   QA482.H7
Subjects:      Geometry, Plane. [from old catalog]
Control No.:   5861744

Author:        880-01 Hoshino, Sanenobu, 1638-1699.
Title:         880-02 Kok¯ogen sh¯o nank¯o ippyaku-gojikko
                  h¯ojutsu / Hoshino Sukeemon no J¯o Sanenobu hen.
Published:     [Japan : s.n., 1672?]
Description:   1, 58 leaves : ill. (woodcuts) ; 27 cm.
LC Call No.:   QA482.H76 1672
Notes:         In Kanbun, with reading marks.
               Caption title.
               Postscript also dated Kanbun 12.
               Within single border (21.6 x 16.5 cm.), text in
                  10 vertical lines.
               On double leaves, oriental style (fukurotoji).
Subjects:      Triangle (Geometry)
               Geometry
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13722296

Author:        Jacobi, Carl Friedr. Andr. (Carl Friedrich
                  Andreas), 1795-1855.
Title:         Die äussern Entfernungsörter geradliniger
                  Dreiecke : eine geometrische Abhandlung / von Carl Friedr.
                  Andr. Jacobi.
Published:     Naumburg : Heinrich Sieling, 1854.
Description:   73, viii p., 2 leaves of plates : ill. ; 25 cm.
LC Call No.:   QA482.J32x 1854
Notes:         "Nebst dem Jahresbericht des Rectors über die
                  Landesschule womit zur Jahresfeier der 311jährigen Stiftung
                  der Königl. Landesschule Pforta am 22. Mai 1854 und zu einem
                  Redeactus einzelner aus allen Classen erwählter Zöglinge,
                  Rector und Lehrercollegium ergebenst einladen."
Subjects:      Triangle.
Control No.:   1928119

Author:        Jacobi, Karl Friedrich Andreas, 1795-1855. [from
                  old catalog]
Title:         De triangulorum rectilineorum proprietatibus
                  quibusdam nondum satis cognitis ...
Published:     Lipsiae, prostat apud E. B. Schwickertum., 1825.
Description:   1 p. l., 62 p. 6 mounted pl. (diagrs.) 26 cm.
LC Call No.:   QA482.J3
Subjects:      Triangle. [from old catalog]
Control No.:   9213462

Author:        Kapteyn, Willem, 1849-1927.
Title:         Over de merkwaardige punten van den driehoek,
                  door W. Kapteyn.
Published:     Amsterdam, J. Müller, 1895.
Description:   33 p. 27 cm.
Series:        Verhandelingen der Koninklijke akademie van
                  wetenschappen te Amsterdam.  [Afdeeling voor de wis- en
                  natuurkundige wetenschappen] 1.sectie, deel III, no. 3
LC Call No.:   Q57.A532 deel 3, no. 3
Subjects:      Triangle.
Control No.:   9742056

Author:        Karl, Mary Cordia, sister, 1893- [from old
                  catalog]
Title:         The projective theory of orthopoles,
Published:     [Oberline, Ohio, 1932]
Description:   1 p.l., p. 327-228, 1 l. diagrs. 26 cm.
LC Call No.:   QA482.K35 1931
Subjects:      Geometry, Plane. [from old catalog]
Control No.:   9225477

Author:        Kirchner, Fr[iedrich] Wilhelm, 1858- [from old
                  catalog]
Title:         Über die perspectivische lage ebener dreiecke
                  ...
Published:     Halle a. S., C. Kirchner's buchdruckerei (Inh. F.
                  C. Schmülling) 1888.
Description:   30 p., 1 l. diagrs. on vi pl. 23 cm.
LC Call No.:   QA482.K58
Subjects:      Triangle. [from old catalog]
Control No.:   8669413

Author:        Kleyer, A. (Adolph)
Title:         Lehrbuch der Goniometrie (Winkelmessungslehre) :
                  mit 307 Erklärungen und 52 in den Text gedruckten Figuren
                  nebst einer Sammlung von 513 gelösten und ungelösten
                  analogen Aufgaben : zum Gebrauch an niederen und höheren
                  Schulen, sowie zum rationellen Selbststudium / bearbeitet
                  nach eigenem System von A. Kleyer.
Published:     Stuttgart : J. Maier, 1886.
Description:   ix, 364 p. : ill. ; 24 cm.
Series:        Dr. A. Kleyer's
                  mathematisch-technisch-naturwissenschaftliche Encyklopädie
LC Call No.:   QA482.K53x 1886
Subjects:      Angles (Geometry) -- Measurement.
Control No.:   1028263

Author:        Leybourn, Thomas, 1770-1840. [from old catalog]
Title:         A synopsis of data for the construction of
                  triangles,
Published:     London, Printed by W. Glendenning, 1802.
Description:   1 p.l., iii, [1], 14 p. 23 cm.
LC Call No.:   QA482.L6
Subjects:      Triangle. [from old catalog]
Control No.:   6796283

Author:        Ludlow, Henry H. (Henry Hunt), 1854-1926.
Title:         Geometric construction of the regular decagon and
                  pentagon inscribed in a circle, by Henry H. Ludlow ...
Published:     Chicago, The Open court publishing co., 1904.
Description:   12 p. 20 cm.
LC Call No.:   QA482.L94
Notes:         "Printed for the author."
Subjects:      Pentagon.
Control No.:   3579377

Author:        Marsano, Giovanni Battista.
Title:         Considerazioni sul triangolo rettilineo. Memoria
                  di Gio. Batta Marsano.
Published:     Genova, L. Beuf, 1863.
Description:   72 p. diagrs. on 2 fold. pl. 24 cm.
LC Call No.:   QA482.M35
Subjects:      Triangle
Control No.:   8668305

Author:        Marsano, G[iovanni] B[attista] [from old
                  catalog]
Title:         Memoria sopra tre teorie piu elementari della
                  geometria di G. B. Marsano ...
Published:     Genova, Tipografia del R. I. de' Sordo-muti,
                  1847.
Description:   68 p. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA482.M36
Subjects:      Geometry, Plane. [from old catalog]
Control No.:   6326802

Author:        Marsano, G[iovanni] B[attista] [from old
                  catalog]
Title:         Memoria sui rapporti delle figure di G. B.
                  Marsano ...
Published:     Genova, Tip. del R. I. Sordo-muti, 1846.
Description:   178 p. diagrs. on viii fold. pl. 23 cm.
LC Call No.:   QA482.M365
Subjects:      Geometry. [from old catalog]
Control No.:   9139682

Author:        Marsano, G[iovanni] B[attista] [from old
                  catalog]
Title:         Memoria sui triangoli simili
Published:     Genova, Tipografia del R. I. Sordo-muti, 1846.
Description:   63, [1] p. diagrs. on 2 fold. pl. 23 cm.
LC Call No.:   QA482.M37
Subjects:      Triangle. [from old catalog]
Control No.:   6794987

Author:        Marsano, G[iovanni] B[attista] [from old
                  catalog]
Title:         Sopra un problema di geometria elementare.
Published:     [Genova, 187-]
Description:   [3]-12 p. diagr. on pl. 22 cm.
LC Call No.:   QA482.M38
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   9605046

Author:        Martin, Artemas, 1835- [from old catalog]
Title:         Formulas for the sides of rational plane
                  triangles.
Published:     Washington, D.C., The author, 1896.
Description:   1 p. l., [221]-236 p. diagrs. 31 x 24 cm.
LC Call No.:   QA482.M4
Subjects:      Triangle. [from old catalog]
Control No.:   8673732

Author:        [Mary Hilaria], Sister. [from old catalog]
Title:         An explanation of the rule for finding the area
                  of a triangle when the three sides are given.
Published:     St. Louis, Mo., Ev. E. Carreras printing co.,
                  1914.
Description:   [7] p. diagrs. 28 cm.
LC Call No.:   QA482.M45
Subjects:      Triangle. [from old catalog]
Control No.:   9641718

Author:        Miller, Martin L. [from old catalog]
Title:         A geometrical proposition.
Published:     Vassar, Mich., Pioneer steam presses, 1886.
Description:   11 p. incl. diagr., fold. pl. 19 cm.
LC Call No.:   QA482.M64
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
               Trisection of angle. [from old catalog]
Control No.:   8200143


Author:        Milliken, Peter.
Title:         Introductory treatise on general method of
                  dividing all acute, right, obtuse and straight angles into
                  any number of equal parts and of describing all regular plane
                  figures of any number of sides, by Peter Milliken ...
Published:     [Perris, Cal., Progress print, c1917]
Description:   36 p. diagrs. 26 cm.
LC Call No.:   QA482.M67
Subjects:      Angles (Geometry)
Control No.:   2162104

Author:        Neely, Henry M. (Henry Milton), 1877-1963.
Title:         Triangles; getting ready for trigonometry.
Published:     New York, Crowell [1962]
Description:   114 p.
LC Call No.:   QA482.N4
Subjects:      Triangle.
               Trigonometry.
Control No.:   9837595

Author:        Onofrio, Georges, 1852- [from old catalog]
Title:         Les foyers du triangle; nombreuses applications,
                  par G. Onofrio ...
Published:     Lyon, Société anonyme de l'imprimerie A. Rey,
                  1924.
Description:   vii, [1], 47 p. fold. pl., diagrs. 25 cm.
LC Call No.:   QA482.O6
Subjects:      Triangle.
Control No.:   12942644

Author:        Overeem, M. van.
Title:         De merkwaardige punten van den ingeschreven
                  veelhoek, door M. van Overeem jr.
Published:     Amsterdam, J. Müller, 1896.
Description:   29 p. fold. diagr. 27 cm.
Series:        Verhandelingen der Koninklijke akademie van
                  wetenschappen te Amsterdam.  [Afdeeling voor de wis- en
                  natuurkundige wetenschappen] 1.sectie, dl. III, no. 7
LC Call No.:   Q57.A532 deel 3, no. 7
Subjects:      Polygons.
Control No.:   8337078

Author:        Rausenberger, Otto, 1852- [from old catalog]
Title:         Die elementargeometrie des punktes,
Published:     Leipzig, B. G. Teubner, 1887.
Description:   v. 236 p. diagrs. 23 cm.
LC Call No.:   QA482.R3
Subjects:      Geometry. [from old catalog]
Control No.:   6887056

Author:        Richeson, Allie W., 1897- [from old catalog]
Title:         An extension of Brahmagupta's theorem ...
Published:     [Baltimore, 1930]
Description:   1 p. l., p.. 425-438, 1 l. diagrs. 25 cm.
LC Call No.:   QA482.R5 1928
Subjects:      Polygons. [from old catalog]
               Pentagon. [from old catalog]
Other titles:  Brahmagupta's theorem.
Control No.:   9215640

Author:        Sutton, Flora Dobler, 1890- [from old catalog]
Title:         On certain chains of theorems in reflexive
                  geometry ...
Published:     [Baltimore, 1923]
Description:   1 p.l., [1], 122-144 p., 1 l. 26 cm.
LC Call No.:   QA482.S8
Subjects:      Geometry, Plane. [from old catalog]
Control No.:   10133900

Author:        Turner, Oscar A. [from old catalog]
Title:         The equibisectorial isosceles triangle
                  proposition proved by the direct method
Published:     [Washington, D.C. c1931]
Description:   1 L. diagr. 36 x 22 cm.
LC Call No.:   QA482.T8
Control No.:   7202636

Author:        880-01 Wakasugi, Taj¯ur¯o, fl. 1719.
Title:         880-02 K¯oko chikinsh¯u / Wakasugi Taj¯ur¯o sen.
Edition:       880-04 Saitei.
Published:     880-05 Heian [Kyoto] : Tenn¯ojiya Ichirob¯e,
                  Kansei 11 [1799]
Description:   2 v. : ill. (woodcuts) ; 23 cm.
LC Call No.:   QA482.W25 1799
Notes:         Caption title.
               Exact height of the book: 22.4 cm.; color of
                  cover dark brown.
               Within single border (18.9 x 13.7 cm.).
               On double leaves, oriental style (fukurotoji).
               Kokusho s¯omokuroku, v. 3, p. 225 (K¯oko
                  chikinsh¯u, 2-kan 2-satsu; variant: Sanp¯o k¯oko chikinsh¯u;
                  auth. Wakasugi Taj¯ur¯o, Ky¯oh¯o 4 [1719] kan, also Kansei 11
                  [1799] han).
               Book advertisement on colophon page.
               LC copy imperfect: title pieces wanting. DLC
Subjects:      Angles (Geometry)
               Geometry.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13716827

Author:        880-01 Wakasugi, Taj¯ur¯o, fl. 1719.
Title:         880-02 K¯oko chikinsh¯u / Wakasugi Taj¯ur¯o sen.
Published:     [Japan : s.n., not before 1719]
Description:   2 v. in 1 : ill. (woodcuts) ; 23 cm.
LC Call No.:   QA482.W25 1719
Notes:         Caption title.
               Exact height of the book: 22.8 cm.; color of
                  cover dark blue.
               Within single border (18.9 x 13.7 cm.).
               On double leaves, oriental style (fukurotoji).
               Kokusho s¯omokuroku, v. 3, p. 225 (K¯oko
                  chikinsh¯u, 2-kan 2-satsu; variant: Sanp¯o k¯oko chikinsh¯u;
                  auth. Wakasugi Taj¯ur¯o, Ky¯oh¯o 4 [1719] kan, also Kansei 11
                  [1799] han).
               LC copy has some additions in red. DLC
               LC copy wormed, with loss of text, and title
                  piece wanting. DLC
Subjects:      Angles (Geometry)
               Geometry.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13716826

Author:        Wang, Lai, 1768-1813. [from old catalog]
Title:         Hêng-chai suan hsüeh.
Published:     [n.p., 1810?]
Description:   2 v. (double leaves) in case. illus. 25 cm.
LC Call No.:   QA482.W3
Notes:         Romanized.
Subjects:      Triangle. [from old catalog]
               Mathematics, Chinese. [from old catalog]
Control No.:   9883561

Author:        Weber, Herrmann. [from old catalog]
Title:         Das dreieck.
Published:     Dresden, J. Breyer [c1914-
Description:   n.p. diagrs. 25 cm.
LC Call No.:   QA482.W5
Subjects:      Triangle. [from old catalog]
Control No.:   11092406

Author:        Weitzenböck, Roland, 1885-
Title:         Über eine ungleichung in der driecksgeometrie.
Published:     Berlin, J. Springer, 1919.
Description:   1 p. l., p. [137]-146. 23 cm.
LC Call No.:   QA482.W55
Notes:         "Mathematische zeitschrift ... Sonderabdruck aus
                  band 5, heft 1/2."
Control No.:   12929126

Author:        Académie royale des sciences, des lettres et des
                  beaux-arts de Belgique. Classe des sciences.
Title:         Mémoires de la Classe des sciences. Collection
                  in-8ê.
Published:     Bruxelles, Académie royale de Belgique [etc.]
Description:   v. ill. 22 cm.
LC Call No.:   QA483.C4
ISSN:          0365-0936
Notes:         At head of title: Académie royale de Belgique,
                  <1993>; Belgian Royal Academy Council of Applied Sciences,
                  1995-
               Chemical abstracts 0009-2258
               For index see Académie royale des sciences, des
                  lettres et des beaux-arts de Belgique. Tables générales des
                  mémoires.
               From 1816-1904 the Academy published three
                  collections of memoirs: 1. Mémoires de l'Académie, in -4ê;
                  2. Mémoires couronnés et mémoires des savants étrangers,
                  in -4ê; 3. mémoires couronnés et autres mémoires in -8ê.
                  In 1906 the memoirs were divided in two series: A. Mémoires
                  de la Classe des sciences: B. Mémoires de la Classe des
                  lettres et des sciences morales et politiques et de la Classe
                  des beaux-arts; each series includes two collections, one in
                  -4ê and one in -8ê.
Subjects:      Science -- Periodicals.
               Science -- Periodicals.
Location:      universal pattern
Control No.:   11494386

Author:        Eagles, T. H. (Thomas Henry)
Title:         Constructive geometry of plane curves, with
                  numerous examples, by T.H. Eagles ...
Published:     London, Macmillan and co., 1885.
Description:   xx, 374 p. diagrs. 19 cm.
LC Call No.:   QA483.E2
Subjects:      Curves, Plane.
               Conic sections.
Control No.:   3582097

Author:        Tango, Giuseppe.
Title:         Il disegno delle curve geometriche : cenni sulle
                  proiezioni geometriche e prospettiche / Giuseppe Tango.
Published:     Napoli : R. Pesole, 1903.
Description:   54 p. : ill. ; 23 cm.
LC Call No.:   QA483.T36x 1903
Subjects:      Curves.
               Projections.
Control No.:   4291732

Author:        [Whalen, John William] [from old catalog]
Title:         Analysis, record and assembly of ornamental
                  curves ...
Published:     [Pontiac, Ill., Pontiac publishing company]
                  c1914.
Description:   p. cm.
LC Call No.:   QA483.W4
Subjects:      Curves.
Control No.:   8237085

Author:        Yates, Robert C. (Robert Carl), 1904-1963.
Uniform Title: Handbook on curves and their properties
Title:         Curves and their properties.
Published:     [Washington] National Council of Teachers of
                  Mathematics [1974, c1952]
Description:   ix, 245 p. illus. 24 cm.
Series:        Classics in mathematics education, v. 4
LC Call No.:   QA483.Y37 1974
Dewey No.:     516/.15
Notes:         Reprint of the ed. published by J. W. Edwards,
                  Ann Arbor, under title: A handbook on curves and their
                  properties.
               Includes bibliographies.
Subjects:      Curves, Plane.
Control No.:   4569050

Title:         The question: Are there any commensurable
                  relations between a circle and other geometrical figures?
Published:     London, R. Griffin & co., 1860.
Description:   34 p., 1 l., diagrs. 22 cm.
LC Call No.:   QA484.Q5
Subjects:      Circle. [from old catalog]
Other titles:  A member of the "British association for the
                  advancement of science". [from old catalog]
Control No.:   9247233

Author:        Alvord, Benjamin. [from old catalog]
Title:         The tangencies of circles and of spheres.
Published:     Washington, 1856.
Description:   16 p. 9 pl. cm.
LC Call No.:   QA484.A47
Control No.:   7208849

Author:        Brennan, Michael H. [from old catalog]
Title:         Reciprocal arcs,
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1915.
Description:   7 p. diagrs. 26 cm.
LC Call No.:   QA484.B65
Subjects:      Circle. [from old catalog]
Control No.:   6365465

Author:        Brennecke, [Wilhelm] [from old catalog]
Title:         Einführung in die neuere geometrie.
Published:     Berlin, T. C. F. Enslin, 1860.
Description:   vii, [1], 112 p. incl. diagrs., 3 fold. pl. 23
                  cm.
LC Call No.:   QA484.B7
Subjects:      Circle. [from old catalog]
               Sphere. [from old catalog]
Control No.:   6328122

Author:        Cabreira, Antonio, 1868- [from old catalog]
Title:         Sur les propriétés de deux cercles égaux et
                  tangents.
Published:     Coimbra, Impr. da Universidade, 1906.
Description:   11 p. 25 cm.
LC Call No.:   QA484.C2
Subjects:      Circle. [from old catalog]
Control No.:   5893222

Author:        Davison, D. H. [from old catalog]
Title:         Circle-problem and its solution.
Published:     [Gettysburg, Ohio, J. S. Rider, 1885]
Description:   4 p. diagr. 23 cm.
LC Call No.:   QA484.D2
Subjects:      Circle. [from old catalog]
Control No.:   10073341

Author:        Guldberg, C[ato] M[aximilian], 1830-1902. [from
                  old catalog]
Title:         Om cirklers berøring.
Published:     Christiania, B. M. Bentzen bogtrykkeri, 1861.
Description:   2 p.l., 32 p. diagrs. on 14 pl. 25 cm.
LC Call No.:   QA484.G9
Subjects:      Circle. [from old catalog]
Other authors: Christiania. Universitet. [from old catalog]
Control No.:   6796187

Author:        Harris, Herman H.
Title:         The history and calculation of pi.
Published:     Emporia, Graduate Division of the Kansas State
                  Teachers College, 1959.
Description:   39 p. diagrs. 23 cm.
Series:        The Emporia State research studies, v. 8, no. 1
LC Call No.:   QA484.H3
Dewey No.:     513.92
Notes:         Bibliography: p. 37-38.
Subjects:      Pi.
Series Entry:  Emporia State research studies ; v. 8, no. 1.
Control No.:   3112046

Author:        Lamson, Franklin Silas. [from old catalog]
Title:         Exposition in fundamental space-measurement.
Published:     [Washington, D.C., The Press of Judd & Detweiler,
                  c1913]
Description:   [4] p. diagrs. 30 cm.
LC Call No.:   QA484.L3
Subjects:      [Pi] [from old catalog]
Control No.:   9171270

Author:        Marchetti Tomassi, Gaetano, 1778-1857.
Title:         Nuovo trattato sulla vera rettificazione del
                  circolo misurato esattamente con il diametro : utile alla
                  trigonometria, alla misura delle curve, e degli spazj
                  curvilinei / dedicato alla maesta' del czar Alessandro I,
                  imperatore di tutte le Russie da Gaetano Marchetti Tomassi,
                  conte e patrizio reatino : con una dissertazione sul modo di
                  navigare sott' acqua, inventato dallo stesso autore l'anno
                  1799.
Edition:       2a ed.
Published:     Fuligno : F. Campitelli, 1817.
Description:   75, 34 p., [6] folded leaves of plates : ill. ;
                  21 cm.
LC Call No.:   QA484.M29 1817
Dewey No.:     516.2/2 19
Notes:         On t.p.: Parte prima.
               Prefazione -- [pt. 1a] Delle curve circolari --
                  pt. 2a. Delle tre sezioni del cono -- pt. 3a. Di alcune altre
                  curve -- pt. 4a. Dissertazione sul modo di navigare
                  sott'acqua, recitata li 12 gennajo 1817.
Subjects:      Circle.
               Conic sections.
               Curves.
               Submarines (Ships)
Control No.:   928518

Author:        Marianini, Pietro Domenico, 1827-1884. [from old
                  catalog]
Title:         Settantacinque porismi tratti quasi tutti
                  dall'opera del Chasles intitolata, "Les trois livres des
                  porismes d'Euclide, etc." e dimostrati la maggior parte con
                  metodo che, dietro certe considerazioni, sembra probabile
                  essere stato usato da Euclide. Memoria del Prof. Pietro
                  Domenico Marianini ...
Published:     Modena, Tipografia degli eredi Soliani, 1863.
Description:   1 p.l., 131 p. diagrs. on 8 fold. pl. 31 cm.
LC Call No.:   QA484.M3
Subjects:      Porisms. [from old catalog]
Other authors: Chasles, M. (Michel), 1793-1880.
Control No.:   6796324

Author:        Matthews, William Oliver. [from old catalog]
Title:         Concerning a closed circular line
Published:     Toronto, 1922.
Description:   39 p. diagrs. 20 cm.
LC Call No.:   QA484.M35
Subjects:      Circle. [from old catalog]
Control No.:   6853106

Author:        M'Clelland, William J.
Title:         A treatise on the geometry of the circle and some
                  extensions to conic sections by the method of reciprocation,
                  with numerous examples.
Published:     London, New York, Macmillan, 1891.
Description:   xvi, 299 p. diagrs. 18 cm.
LC Call No.:   QA484.M2
Subjects:      Circle.
               Conic sections.
Control No.:   2164146

Author:        [Miller, Albert Arthur], 1883- [from old
                  catalog]
Title:         Circleometry.
Published:     [Des Moines, The Homestead company, printers,
                  c1916]
Description:   cover-title, 16 p. diagrs. 23 cm.
LC Call No.:   QA484.M45
Subjects:      Circle. [from old catalog]
Control No.:   10115034

Author:        Mitzscherling, Arthur, 1879-1912.
Title:         Das problem der kreisteilung, ein beitrag zur
                  geschichte seiner entwicklung von dr. Arthur Mitzscherling
                  ... mit einem vorwort von dr. Heinrich Liebmann ... Mit 210
                  figuren im text.
Published:     Leipzig, Berlin, B.G. Teubner, 1913.
Description:   vi, 214 p. illus., diagrs. 25 cm.
LC Call No.:   QA484.M5
ISBN:          DM8.49
Subjects:      Circle.
Other authors: Liebmann, Heinrich, 1874- ed.
Control No.:   1217917

Author:        880-01 Mizoguchi, Rinkei, fl. 1757-1788.
Title:         880-02 H¯oen jundo.
Published:     [1813?-1815?]
Description:   4 v. : ill. ; 33 cm.
LC Call No.:   QA484.M59 1813
Notes:         With no borders.
               On double leaves, oriental style (fukurotoji).
               LC copy wormed, with loss of text. DLC
               Kokusho s¯omokuroku, v. 7, p. 240 (H¯oen jundo,
                  2-kan 2-satsu; auth. Mizoguchi Rinkei, Tenmei 8 jo).
Subjects:      Circle.
               Geometry.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13673814

Author:        Pedoe, Daniel.
Title:         Circles.
Published:     London, New York, Pergamon Press, 1957.
Description:   x, 78 p. diagrs. 22 cm.
Series:        International series of monographs on pure and
                  applied mathematics, v. 2
LC Call No.:   QA484.P4
Dewey No.:     513.21 513.1*
Subjects:      Circle.
Series Entry:  International series of monographs in pure and
                  applied mathematics ; v. 2.
Control No.:   7937005

Author:        Reich, Jacob Jerome, 1901- [from old catalog]
Title:         Circumference tables,
Published:     [Huntington? W. Va.] c1952.
Description:   [15] l. 28-43 cm.
LC Call No.:   QA484.R4
Subjects:      Circle. [from old catalog]
Control No.:   6974480

Author:        Richter, A. W. [from old catalog]
Title:         Das Apollonische berührungs-problem,
Published:     Bielefeld, Druck von J. D. Kuster nachfolger,
                  1870.
Description:   p. cm.
LC Call No.:   QA484.R5
Other authors: Circle. [from old catalog]
Control No.:   7731451

Author:        Scaliger, Joseph Juste, 1540-1609.
Uniform Title: Cyclometrica elementa duo
Title:         Iosephi Scaligeri Iul. Caes. f. Cyclometrica
                  elementa duo.
Published:     Lugduni Batauorum : Ex officina Plantiniana, apud
                  Franciscum Raphelengium, 1594.
Description:   [12], 122 [i.e. 124] p. ; 32 cm. (fol.)
LC Call No.:   QA484.S33 1594
Notes:         Text chiefly in Latin; definitions, axioms, and
                  propositions also in Greek.
               Signatures: *p6s A-Op4s Pp6s.
               Adams 558
               With: Scaliger, Joseph Juste. Iosephi Scaligeri
                  Iul. Caes. f. Mesolabium. Lugduni Batauorum : Ex officina
                  Plantiniana, 1594. Issued together? DLC
Subjects:      Circle -- Early works to 1800.
Other authors: John Davis Batchelder Collection (Library of
                  Congress) DLC
Control No.:   2118148

Author:        Schubert, Hermann [Cäsar Hannibal], 1848- [from
                  old catalog]
Title:         I. Lösung des auf die trilineare verwandtschaft
                  ausgedehnten projectivitätsproblems. II. Elementarer beweis
                  des Feuerbach'schen satzes ...
Published:     Hamburg, Gedruckt bei T. G. Meissner, 1882.
Description:   1 p.l., 39 p. tables, diagrs. on pl. 27 x 22 cm.
LC Call No.:   QA484.S38
Subjects:      Transformations (Math.) [from old catalog]
               Circle. [from old catalog]
Control No.:   7264500

Author:        Steiner, Jakob, 1796-1863. [from old catalog]
Title:         Einige geometrische betrachtungen von Jacob
                  Steiner (1826.)
Published:     Leipzig, W. Engelmann, 1901.
Description:   125 p. diagr. 20 cm.
LC Call No.:   QA484.S82
Subjects:      Circle. [from old catalog]
Control No.:   8198065

Author:        Weaver, James Henry, 1883-1942.
Title:         Some extensions of the work of Pappus and Steiner
                  on tangent circles, by J.H. Weaver.
Published:     Lancaster, Pa., Press of the New Era Printing
                  Company, 1920.
Description:   1 p. L., 10 p., 1 L, diagrs. 26 cm.
LC Call No.:   QA484.W4
Notes:         Life.
               "Reprinted from the American mathematical
                  monthly, vol.XXVII., January 1920."
               Thesis (Ph. D.)--University of Pennsylvania,
                  1916.
Subjects:      Circle
Control No.:   6378508

Author:        Beyssell, Dr. (Adolf), b. 1821.
Title:         Die Kegelschnitte : ein Leitfaden für
                  Gewerbeschulen und das gewerbliche Leben / von Dr. Beyssell.
Published:     Braunschweig : F. Vieweg, 1862.
Description:   viii, 82 p. : ill. ; 23 cm.
LC Call No.:   QA485.B49x 1862
Subjects:      Conic sections.
Control No.:   4291659

Author:        Bopp, K. (Karl), 1877-1934.
Title:         Die Kegelschnitte des Gregorius a St. vincentio
                  in vergleichender Bearbeitung ...  von Karl Bopp.
Published:     Leipzig, Druck von B. G. Teubner, 1906.
Description:   42 p. diagrs. 23 cm.
LC Call No.:   QA485.B72
Notes:         The complete work, with sme title, is published
                  in Abhandlungen zur Geschichte der mathematischen
                  Wissenschaften mit Einschluss ihrer Anwendungen ...
               Habilitationsschrift--Heidelberg.
Subjects:      Gregorius a Sancto Vincentio, 1584-1667. Opus
                  geometricum quadraturae circuli et sectionum coni.
               Conic sections
Control No.:   5872398

Author:        Bridge, B. (Bewick), 1767-1833.
Title:         A treatise on the contruction, properties, and
                  analogies of the three conic sections. By the Rev. B. Bridge
                  ... From the 2d London ed., with additions and alterations by
                  the American editor.
Published:     New Haven, Durrie and Peck; New York, Collins,
                  Keese, and Co. [c1831]
Description:   136 p. diagrs. 22 cm.
LC Call No.:   QA485.B87
Notes:         "Advertisement" signed: F.A.P. Barnard.
Subjects:      Conic sections.
Other authors: Barnard, Frederick A. P. (Frederick Augustus
                  Porter), 1809-1889, ed.
Control No.:   9136549

Author:        Bridge, Bewick, 1767-1833. [from old catalog]
Title:         A treatise on the construction, properties, and
                  analogies of the three conic sections.
Edition:       2d London ed.
Published:     New Haven, H. Howe, 1831.
Description:   vii, [1]. 132 p. diagrs. 23 cm.
LC Call No.:   QA485.B86
Subjects:      Conic sections. [from old catalog]
Other authors: Barnard, Frederick Augustus Porter, 1809-1889,
                  [from old catalog] ed.
Control No.:   7263362

Author:        Bridge, B[ewick], 1767-1833. [from old catalog]
Title:         A treatise on the construction, properties and
                  anaologies of the three conic sections.
Edition:       3d ed.
Published:     London, Printed for T. Cadell; [etc., etc.]
                  1831.
Description:   3 p.l., 137 p. diagrs. 22 cm.
LC Call No.:   QA485.B85
Subjects:      Conic sections.
Control No.:   5858950

Author:        Cametti, Ottaviano, d. 1789. [from old catalog]
Title:         Sectionum conicarum compendium.
Published:     Venetiis, ex typographia Balleoniana, 1765.
Description:   viii, 108 p. diagrs. on xiv pl. 18 cm.
LC Call No.:   QA485.C18
Subjects:      Conic sections. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   9136609

Author:        Chasles, M. (Michel), 1793-1880.
Title:         Traìté des sections coniques.
Published:     [n.p.] 1865.
Description:   1 v. cm.
LC Call No.:   QA485.C48
Control No.:   9556611

Author:        De Baggis, Henry F., 1916- [from old catalog]
Title:         Hyperbolic geometry.
Published:     Notre Dame, Ind., University Press [1949]
Description:   24 p. 23 cm.
LC Call No.:   QA485.D4
Subjects:      Hyperbola.
Control No.:   8861006

Author:        Drew, William Henry. [from old catalog]
Title:         A geometrical treatise on conic sections.
Edition:       4th ed.
Published:     London and Cambridge, Macmillan and co., 1869.
Description:   2 p. l., 139 p. diagrs. 20 cm.
LC Call No.:   QA485.D7 1869
Subjects:      Conic sections. [from old catalog]
Control No.:   6903548

Author:        Grüninger, Wilhelm, 1880-
Title:         Das System der Kegelschnitte mit drei festen
                  Punkten und einer festen Tangente ... von Wilhelm Grüninger.
                  Mit 5 Tafeln.
Published:     Giessen, Münchow'sche Hof und
                  Universitäts-Druckerei, 1903.
Description:   52 p., 1 L. diagrs. on 5 pl. 23 cm.
LC Call No.:   QA485.G89
Notes:         Lebenslauf.
               Inaug.-diss.--Giessen.
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.8.
Control No.:   10074694

Author:        Hossfeld, Carl, 1857-
Title:         Construction des Kegelschnitts aus fünf zum teil
                  imaginären Curvenelementen / von Carl Hossfeld.
Published:     Jena : A. Neuenhahn, 1882.
Description:   27 p. : ill. ; 27 cm.
LC Call No.:   QA485.H82
Notes:         Thesis--Jena.
Subjects:      Conic sections.
Control No.:   6327919

Author:        Howland, Rufus B.
Title:         Elements of the conic sections.
Published:     Boston : Leach, Shewell & Sanborn, 1887.
Description:    60 p. : diagrs. ; 20 cm.
LC Call No.:   QA485.H86
Subjects:      Conic sections.
Control No.:   8668304

Author:        Jackson, I[saac] W[ilber] 1805-1877. [from old
                  catalog]
Title:         Elements of conic sections.
Published:     Albany, Gray and Sprague, 1850.
Description:   2 p. l., 96 p. diagrs. on 6 fold. pl. 23 cm.
LC Call No.:   QA485.J14
Notes:         A digital reproduction made from a copy held by
                  the University of Michigan is available from the University
                  of Michigan's Making of America Web site.
Subjects:      Conic sections. [from old catalog]
Control No.:   6794986
Access:        
    Location:  http://name.umdl.umich.edu/ACV4637

Author:        Jackson, I[saac] W[ilber] 1805-1877. [from old
                  catalog]
Title:         Elements of conic sections,
Edition:       3d ed.
Published:     Albany, O. Steele, 1838.
Description:   2 p. l., 87 p. diagrs. on 6 fold. pl. 19 cm.
LC Call No.:   QA485.J13
Subjects:      Conic sections. [from old catalog]
Control No.:   6326801

Author:        Messenger, Hiram John, 1855-1913. [from old
                  catalog]
Title:         Modern methods in geometric conics.
Published:     Boston, Printed by J. S. Cushing & co., 1886.
Description:   2 p.l., 21 p. diagrs. 21 cm.
LC Call No.:   QA485.M58
Subjects:      Conic sections. [from old catalog]
Control No.:   10065501

Author:        Milne, John J. (John James)
Title:         Geometrical conics, part I, the parabola, by the
                  Rev. John J. Milne ... and R. F. Davis.
Published:     London and  New York, Macmillan & co., 1890.
Description:   4 p. l., 72 p. diagr. 19 cm.
LC Call No.:   QA485.M6
Subjects:      Parabola.
               Conic sections.
Other authors: Davis, Robert Frederic, joint author.
Control No.:   7288178

Author:        Picquet, H. (Henry), b. 1845.
Title:         Étude géométrique des systèmes ponctuels et
                  tangentiels de sections coniques / par H. Picquet.
Published:     Paris : Gauthier-Villars, 1872.
Description:   viii, 133 p., 4 folded leaves of plates : ill. ;
                  22 cm.
LC Call No.:   QA485.P5
Dewey No.:     513.22
Notes:         Includes bibliographical references.
Subjects:      Conic Sections.
Control No.:   2635737

Author:        Prestel, Michael August Friedrich, 1809-1880.
                  [from old catalog]
Title:         Die kegelschnitte, in elementarer darstellung
                  für die schule.
Published:     [Emden, Gedruckt bei H. Woortman sen. wwe, 1868]
Description:   42 p. diagrs. on ii pl. 27 x 20 cm.
LC Call No.:   QA485.P9
Subjects:      Conic sections. [from old catalog]
Control No.:   7749501

Author:        Riecke, Friedrich Joseph Pythagoras, 1794-1876.
                  [from old catalog]
Title:         Die lehre von den kegelschnitten, dargestellt
                  für das bedürfniss des forstwirths ...
Published:     Stuttgart, F. H. Köhler, 1842.
Description:   iv, [5]-38, [1] p. diagrs. 23 cm.
LC Call No.:   QA485.R5
Subjects:      Conic sections. [from old catalog]
Control No.:   9212823

Author:        Robertson, A[braham] 1751-1826. [from old
                  catalog]
Title:         Elements of conic sections deduced from the
                  cone,
Published:     Oxford, At the Clarendon press, 1818.
Description:   xi, 125 p. diagrs. on xv fold. pl. 22 cm.
LC Call No.:   QA485.R63
Subjects:      Conic sections. [from old catalog]
Control No.:   10073340

Author:        Robertson, Abram, 1751-1826.
Title:         A geometrical treatise of conic sections. In four
                  books. To which is added a treatise on the primary properties
                  of conchoids, the cissoid, the quadratrix, cycloids, the
                  logarithmic curve, and the logarithmic, Archimedean, and
                  hyperbolic spirals. By the Rev. Abram Robertson ...
Published:     Oxford, At the Clarendon press, 1802.
Description:   xii, 268 p. diagrs. on 28 fold. pl. 22 cm.
LC Call No.:   QA485.R64
Subjects:      Conic sections.
               Curves, Plane.
Control No.:   4052232

Author:        Schilke, Emil. [from old catalog]
Title:         Die Newton'sche erzeugungsweise der
                  kegelschnitte
Published:     Göttingen, Druck von E. A. Huth, 1875.
Description:   25 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA485.S33
Subjects:      Conic sections. [from old catalog]
Control No.:   7731450

Author:        Simson, Robert, 1687-1768.
Title:         Elements of the conic sections, by Dr. Robert
                  Simson. Tr. from the Latin original.
Edition:       A new ed. rev. and cor.
Published:     Glasgow, Printed by R. Chapman, 1817.
Description:   253 p., 1 l. diagrs. on 14 fold. pl. 22 cm.
LC Call No.:   QA485.S59
Subjects:      Conic sections.
Control No.:   1217145

Author:        Simson, Robert, 1687-1768
Title:         Elements of the conic sections. By the late Dr.
                  Robert Simson ... Tr. from the Latin original, for the use of
                  students of mathematics.
Published:     New York, W. Falconer, 1804.
Description:   278, [2] p. 14 fold. pl. 21.5 cm.
LC Call No.:   QA485.S58 1804
Subjects:      Conic sections.
Control No.:   6323596

Author:        Simson, Robert, 1687-1768. [from old catalog]
Title:         Elements of the conic sections.
Published:     Edinburgh, C. Elliot, 1775.
Description:   3 p. l., 255 p. fold. diagrs. 22 cm.
LC Call No.:   QA485.S58 1775
Subjects:      Conic sections. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   6832224

Author:        Simson, Robert, 1687-1768. [from old catalog]
Title:         Sectionum conicarum libri v.
Published:     Edinburgi, apud T. & W. Ruddimannos, 1735.
Description:   viii, 204 p. xxxvi fold. diagr. 23 x 18 cm.
LC Call No.:   QA485.S6
Subjects:      Conic sections. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   5987420

Author:        Smith, Charles, 1844-1916.
Title:         An elementary treatise on conic sections, by
                  Charles Smith ...
Published:     London, Macmillan and co., limited; New York, The
                  Macmillan Company, 1904.
Description:   xi, 352 p. diagrs. 19 cm.
LC Call No.:   QA485.S62
Notes:         First edition, 1882. Second edition, 1833.
                  Reprinted with slight corrections 14 times between 1884 and
                  1904.
Subjects:      Conic sections.
Control No.:   10076260

Author:        Smith, Charles, 1844-1916.
Title:         Geometrical conics, by Charles Smith ...
Published:     London, New York, Macmillan and Co., 1894.
Description:   vi p., 1 l., 255, [1] p. diagrs. 19 cm.
LC Call No.:   QA485.S64
Subjects:      Conic sections.
Control No.:   6787718

Author:        Smith, Charles, 1844-1916. [from old catalog]
Title:         An elementary treatise on conic sections,
Edition:       4th ed.
Published:     London and New York, Macmillan and co., 1887.
Description:   xi, 352 p. illus. (diagrs.) 19 cm.
LC Call No.:   QA485.S62 1887
Subjects:      Conic sections. [from old catalog]
Control No.:   9676019

Author:        Somerset, [Edward Adolphus Seymour] 11th duke of,
                  1775-1855. [from old catalog]
Title:         Alternate circles and their connexion with
                  ellipse,
Published:     London, H. G. Bohn, 1851.
Description:   p. cm.
LC Call No.:   QA485.S52
Subjects:      Circle.
               Ellipse.
Control No.:   6797329

Author:        Somerset, Edward Adolphus Seymour, Duke of,
                  1775-1855.
Title:         A treatise in which the elementary properties of
                  the ellipse are deduced from the properties of the circle,
                  and geometrically demonstrated, by the Duke of Somerset.
Edition:       2d ed.
Published:     London, J. Murray, 1843.
Description:   1 p.l., 134 p. diagrs. 18 cm.
LC Call No.:   QA485.S53
Subjects:      Ellipse.
Control No.:   1689211

Author:        Stoltz, Karl. [from old catalog]
Title:         Das achteck im kegelschnitt.
Published:     Göttingen, Druck der Dieterisch'schen
                  Univ.-buchdruckerei (W. F. Kästner) 1873.
Description:   p. cm.
LC Call No.:   QA485.S87
Subjects:      Conic sections. [from old catalog]
Control No.:   5858949

Author:        Taylor, Charles, 1840-1908.
Title:         The elementary geometry of conics, with a chapter
                  on the line infinity; by C. Taylor ...
Edition:       7th ed. rev. with A new treatment of the
                  hyperbola.
Published:     Cambridge, D. Bell and co.; [etc., etc.] 1891.
Description:   v, [2], 144 p. diagr. 19 cm.
LC Call No.:   QA485.T24
Notes:         "The work as now revised includes ... A new
                  treatment of the hyperbola, which was read to the Association
                  for the improvement of geometrical teaching, January 1890,
                  and notes of A course for beginners."
Subjects:      Conic sections.
Control No.:   2633856

Author:        Trevigar, L. (Luke)
Title:         Sectionum conicarum elementa methodo facilllima
                  demonstrata. In usum juventutis academicæ. Authore L.
                  Trevigar ...
Published:     Cantabrigiæ, typis academicis, 1731.
Description:   8 p.l., 171, [1] p. 117 diagr. on 12 fold. pl. 25
                  x 20 cm.
LC Call No.:   QA485.T81
Subjects:      Conic sections -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   1217086

Author:        Vince, Samuel, 1749-1821.
Title:         The elements of the conic sections, as
                  preparatory to the reading of Sir I. Newton's Principia. By
                  the Rev. S. Vince, A.M.
Published:     Cambridge, Printed for J. Nicholson, 1781.
Description:   6 p.l., 55, [1] p. diagrs. on 3 fold. pl. 21 cm.
LC Call No.:   QA485.V76
Subjects:      Conic sections -- Early works to 1800.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   2634002

Author:        Wallace, William, 1768-1843.
Title:         A geometrical treatise on the conic sections.
                  With an appendix, containing formulae for their quadrature,
                  &c. By William Wallace.
Published:     Edinburgh, A. and C. Black, 1837.
Description:   xvi, 208 p. diagrs. 21 cm.
LC Call No.:   QA485.W19
Subjects:      Conic sections.
Control No.:   13158177

Author:        Walter, Michael, 1884-
Title:         Die gleichseitige hyperbel ...
Published:     Strassburg i.E., Buchdruckerei C. Müh & cie.,
                  1904.
Description:   32 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA485.W3
Notes:         Inaug.-diss.--Strassburg.
               Lebenslauf.
Subjects:      Hyperbola.
Control No.:   10085903

Author:        Weng, [August] [from old catalog]
Title:         Geometrie der kegelschnitte im
                  realschulunterricht ...
Published:     Heilbronn, Schell'sche buchdruckerei (Kraemer &
                  Schell) 1899.
Description:   47 p. diagrs. 26 x 21 cm.
LC Call No.:   QA485.W47
Subjects:      Conic sections. [from old catalog]
Control No.:   6328234

Author:        West, John, 1756-1817. [from old catalog]
Title:         Elements of conic sections;
Published:     New-York, Printed for F. Nicholas, 1820.
Description:   iv, [5]-64 p. diagrs. on x fold. pl. 24 cm.
LC Call No.:   QA485.W51
Subjects:      Conic sections. [from old catalog]
Control No.:   632680

Author:        Whewell, William, 1794-1866. [from old catalog]
Title:         Conic sections: their principal properties proved
                  geometrically.
Edition:       2d ed.
Published:     Cambridge, J. Deighton; [etc., etc.] 1849.
Description:   iv, [5]-47 p. diagrs. 22 cm.
LC Call No.:   QA485.W56
Subjects:      Conic sections. [from old catalog]
Control No.:   6328659

Author:        Kerst, B. [from old catalog]
Title:         Methoden zur lösung geometrischer aufgaben,
Published:     Leipzig und Berlin, B. G. Teubner, 1916.
Description:   2 p.l., 47, [1] p. diagrs. 19 cm.
LC Call No.:   QA489.K4
Subjects:      Geometry -- Problems, exercises, etc. [from old
                  catalog]
Control No.:   8263303

Author:        Baston, V. J. D.
Title:         Some properties of polyhedra in Euclidean space,
                  by V.J.D. Baston.
Edition:       [1st ed.]
Published:     Oxford, New York, Pergamon Press [1965]
Description:   xi, 212 p. illus. 23 cm.
Series:        International series of monographs in pure and
                  applied mathematics, v. 71
LC Call No.:   QA491.B3 1965
Dewey No.:     513.6
Notes:         "The main body of the book was approved by the
                  University of London for the award of their Ph. D. degree."
               "References": p. xi.
Subjects:      Polyhedra.
               Convex bodies.
Control No.:   7516425

Author:        Hessel, Dr. (Johann Friedrich Christian),
                  1796-1872.
Title:         Uebersicht der gleicheckigen Polyeder und
                  Hinweisung auf die Beziehungen dieser Körper zu den
                  gleichflächigen Polyedern / von Dr. Hessel.
Published:     Marburg : Oscar Ehrhardt's
                  Universitäts-Buchhandlung, 1871.
Description:   30 p. ; 24 cm.
LC Call No.:   QA491.H47x 1871
Subjects:      Polyhedra.
Control No.:   1928185

Author:        Koch, Karl [Ludwig Christian], 1854- [from old
                  catalog]
Title:         Zerlegbare modelle für kristallographie und
                  sphärik und andere gebiete ...
Published:     Cannstatt, Druck der G. F. Rapp'schen
                  buchdruckerei, 1899.
Description:   11 p. diagrs. 26 x 21 cm.
LC Call No.:   QA491.K76
Subjects:      Polyhedra. [from old catalog]
               Geometry -- Study and teaching. [from old
                  catalog]
Control No.:   7270053

Author:        Landweber, Louis, 1912- [from old catalog]
Title:         Mathematical formulation of bodies of
                  revolution,
Published:     Washington, 1950.
Description:   64 p. illus. 27 cm.
LC Call No.:   QA491.L3
Subjects:      Body of revolution. [from old catalog]
Other authors: Gertler, M., [from old catalog] joint author.
Series Entry:  [United States] David W. Taylor Model Basin
                  [Carderock, Md.] Report 719. [from old catalog]
Control No.:   8379196

Author:        Moraes de Almeida, Carlos Augusto, 1843- [from
                  old catalog]
Title:         Sobre a generalisação e discussão da formula
                  do volume do tronco de cone recto,
Published:     [Lisboa, 1876]
Description:   15 p. diagrs. 24 cm.
LC Call No.:   QA491.M82
Subjects:      Cone. [from old catalog]
               Mensuration. [from old catalog]
Control No.:   7266539

Author:        Schumacher, Ferdinand, 1865- [from old catalog]
Title:         Geometrie der kreise einer kugel...
Published:     Metz, Lothringer zeitung, 1889.
Description:   25 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA491.S39
Subjects:      Sphere. [from old catalog]
Control No.:   6796123

Author:        Thiel, Arnoud van.
Uniform Title: Analytische dialektiek. English
Title:         Analytical dialetic.
Published:     Helmond, Uitq. "Helmond" [c1960]
Description:   43 p. illus. 25 cm.
LC Call No.:   QA491.T4713
Subjects:      Polyhedra.
Control No.:   288097

Author:        Young, Frederick H.
Title:         The nature of the regular polyhedra. Infinity and
                  beyond. An introduction to groups.
Published:     Boston, Ginn [1961]
Description:   33 p. illus. 24 cm.
Series:        Topics in modern mathematics
LC Call No.:   QA491.Y6
Subjects:      Polyhedra.
               Algebra.
Other titles:  Infinity and beyond.
               Introduction to groups.
Control No.:   1224683

Author:        Adler, August, b. 1863.
Title:         Theorie der geometrischen konstruktionen, von
                  August Adler ... Mit 177 figuren.
Published:     Leipzig, G.J. Göschen, 1906.
Description:   viii, 301 p. diagrs. 20 cm
Series:        Sammlung Schubert LII
LC Call No.:   QA497.A23
Notes:         Series title also at head of t.p.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Geometrical drawing.
               Geometry, Plane.
Series Entry:  Sammlung Schubert ; 52.
Control No.:   1217436

Author:        Geuer, Ferdinand. [from old catalog]
Title:         Die genauigkeit geometrischer zeichnungen ...
Published:     Karlsruhe, Druck der G. Braun'schen
                  hofbuchdruckerei, 1902.
Description:   39 p. diagrs. on 4 pl. 25 cm.
LC Call No.:   QA497.G4
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   9606158

Author:        Lemoine, Émile Michel Hyacinthe, 1840-1912.
Title:         Géométrographie, ou Art des constructions
                  géometriques, par Émile Lemoine.
Published:     [Paris, C. Naud] 1902.
Description:   87, [1] p. diagr. 20 cm.
Series:        Scientia. [Série] physico-mathématique, no 18
LC Call No.:   QA497.L55 1902
Notes:         At head of title: Scientia, février 1902.
Subjects:      Geometrical drawing.
Control No.:   6325150

Author:        Lemoine, Émile Michel Hyacinthe, 1840-1921.
                  [from old catalog]
Title:         La géométrographie;
Published:     Paris, Gauthier-Villars et fils, 1893.
Description:   2 p.l., 66 p. diagrs. 23 cm.
LC Call No.:   QA497.L55 1893
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   9234057

Author:        Lony, Gustav. [from old catalog]
Title:         Über die beim nachzeichnen von streckenteilungen
                  auftretenden grössenfehler ...
Published:     Hamburg, 1907.
Description:   1 p.l., 33 p. 27 x 22 cm.
LC Call No.:   QA497.L8
Subjects:      Geometrical drawing. [from old catalog]
Control No.:   9156967

Author:        Minchin, George Minchin, 1845-1914.
Title:         Mathematical drawing, by G.M. Minchin ... and
                  J.B. Dale ...
Edition:       3d ed., 2d impression.
Published:     London, E. Arnold, 1920.
Description:   vi p., 1 l., 158 p. diagrs. 22 cm.
LC Call No.:   QA497.M5 1920
Subjects:      Geometrical drawing.
Other authors: Dale, John Borthwick, joint author.
Control No.:   9661024

Author:        Richter, Julius, 1881-
Title:         Experimentelle Untersuchung der beim nachzeichnen
                  von strecken und winkeln entstehenden Grössenfehler ... von
                  Julius Richter.
Published:     Naumberg a.S., Druck von Lippert & Co. (G.
                  Pätz'sche Buchdruckerei) 1904.
Description:   2 p. L., 26 p. tables, diagrs. 24 cm.
LC Call No.:   QA497.R53
Notes:         Lebenslauf.
               Inaug.ödiss.--Giessen.
Subjects:      Geometrical drawing
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.15.
Control No.:   6335000

Author:        Shupe, Hollie W.
Title:         A manual of engineering geometry and graphics for
                  students and draftsmen / Hollie W. Shupe, Paul E. Machovina.
Published:     New York : McGraw-Hill, 1956.
Description:   vii, 347 p. : ill. ; 25 cm.
Series:        The Engineering drawing series
LC Call No.:   QA497.S5
Subjects:      Geometrical drawing.
               Graphic methods.
Other authors: Machovina, Paul E.
Other titles:  Engineering geometry and graphics.
Control No.:   7456777

Author:        Shupe, Hollie W. [from old catalog]
Title:         Engineering geometry and graphics problems
Published:     New York, McGraw-Hill, 1957.
Description:   vii, 23 p., 105 l. illus. 28 cm.
LC Call No.:   QA497.S52
Subjects:      Geometrical drawing -- Problems, exercises, etc.
                  [from old catalog]
               Engineering -- Problems, exercises, etc. [from
                  old catalog]
Other authors: Shupe, Hollie W. A manual of engineering geometry
                  and graphics for students and draftsmen. [from old catalog]
Control No.:   7469383

Author:        Willson, Frederick Newton, 1855-1939.
Title:         Some mathematical curves and their graphical
                  construction ...
Published:     New York, Macmillan Co., 1898.
Description:   39-78 p. diagrs. 32 cm.
LC Call No.:   QA497.W74
Subjects:      Curves, Plane.
Control No.:   10062453

Author:        Zühlke, Paul, 1877-
Title:         Konstruktionen in begrenzter ebene, von dr. Paul
                  Zühlke ... Mit 65 figuren im text.
Published:     Leipzig und Berlin, B. G. Teubner, 1913.
Description:   2 p. iv, 39, [1] p. diagrs. 19 cm.
Series:        Mathematische bibliothek, hrsg. von W. Lietzmann
                  und A. Witting. 11
LC Call No.:   QA497.Z8
Notes:         "Einiges über die fachliteratur": p. [38]-39.
Subjects:      Geometrical drawing.
               Geometry, Plane.
Control No.:   8704225
