#+STARTUP: showeverything logdone
#+options: num:nil

Author:        National Council of Teachers of Mathematics.
Title:         Enrichment mathematics for high school.
Published:     Washington, 1963.
Description:   ix, 388 p. diagrs. 23 cm.
Series:        Yearbook 28th
LC Call No.:   QA1.N3 28th; Alternative class.: QA12
Dewey No.:     510/.71/2 s 510/.71/2 20
Notes:         Includes bibliographies.
Subjects:      Mathematics -- Study and teaching (Secondary)
Series Entry:  Yearbook (National Council of Teachers of
                  Mathematics) ; 28th.
Control No.:   3585707

Title:         Vestnik Novgorodskogo gosudarstvennogo
                  universiteta. Seriëiìa "Estestvennye i tekhnicheskie nauki."
Published:     Velikiæi Novgorod : Novgorodskiæi
                  gosudarstvennyæi universitet
Description:   v. : ill. ; 27 cm.
LC Call No.:   QA12.V47
Notes:         Description based on: '98, 10; title from cover.
               In Russian, with summaries in English.
Subjects:      Mathematics -- Research.
               Mathematical models.
               Mathematical physics.
Other authors: Novgorodskiæi gosudarstvennyæi universitet imeni
                  ëIìAroslava Mudrogo.
Control No.:   12332767

Author:        Le Vavasseur, Raymond, 1862-1930.
Title:         Quelques démonstrations relatives à la théorie
                  des nombres entiers complexes cubiques. Propriétés de
                  quelques groupes d'ordre fini. Par Raymond Vavasseur ...
Published:     Lyon, A. Rey; [etc., etc.] 1908.
Description:   2 p.l., 66, [2] p. 25 cm.
Series:        Annales de l'Université de Lyon. Nouv. sér. I.
                  Sciences, médecine. fasc. 21
LC Call No.:   QA255.L5
Notes:         Exemplaire no. 167.
Subjects:      Numbers, Complex.
               Group theory.
Series Entry:  Annales de l'Université de Lyon. Nouv. sér. 1,
                  Sciences, médecine ; fasc. 21.
Control No.:   2161679

Author:        Allman, George Johnston, 1824-1904.
Title:         Greek geometry from Thales to Euclid. By George
                  Johnston Allman ...
Published:     Dublin, Hodges, Figgis, & co.; London, Longmans,
                  Green, & co., 1889.
Description:   xii, 237 p. front. (port.) diagr. 23 cm.
Series:        Dublin university press series
LC Call No.:   QA22.A43
Notes:         "This book is the reproduction of a paper, the
                  several parts of which appeared in Hermathena during the last
                  eleven years".--Pref.
               Bibliographical foot-notes.
               "Bibliographical notices": p. [217]-223.
Subjects:      Geometry -- History.
               Mathematics, Greek.
Series Entry:  Dublin University Press series.
Control No.:   744750

Author:        Dantzig, Tobias, 1884-1956.
Title:         The bequest of the Greeks / Tobias Dantzig.
Published:     New York : Scribner, 1955.
Description:   191 p. : ill. ; 22 cm.
Series:        Mathematics in retrospect
LC Call No.:   QA22.D3 1955
Dewey No.:     510.9
Notes:         Includes index.
Subjects:      Mathematics, Greek.
               Mathematics -- History.
Series Entry:  Dantzig, Tobias, 1884-1956. Mathematics in
                  retrospect.
Control No.:   9798004

Author:        DeLacy, Estelle Allen, 1911-
Title:         Euclid and geometry.
Published:     New York, F. Watts [1963]
Description:   120 p. 22 cm.
Series:        Immortals of science
LC Call No.:   QA22.D4
Dewey No.:     513.09
Subjects:      Euclid.
               Mathematics, Greek.
               Geometry -- History.
Control No.:   6572521

Author:        Gerhardt, Karl Immanuel, 1816-1899. [from old
                  catalog]
Title:         Die sammlung des Pappus von Alexandrien.
Published:     Eisleben, H. Reichardt'sche buchdr., 1875.
Description:   15 p. diagrs. 27 x 22 cm.
LC Call No.:   QA22.G5
Subjects:      Pappus, of Alexandria. [from old catalog]
Control No.:   8691125

Author:        Gow, James, 1854-1923.
Title:         A short history of Greek mathematics, by James
                  Gow ... Edited for the Syndics of the University press.
Published:     Cambridge, University press, 1884.
Description:   xiv, [2], 323, [1] p. diagr. 23 cm.
LC Call No.:   QA22.G7
Notes:         An alphabetical list of the chief Greek
                  mathematicians with their approximate dates: 2 p. following
                  p. xiv.
Subjects:      Mathematics, Greek.
               Mathematics -- History.
Control No.:   2633861

Author:        Heath, Thomas Little, Sir, 1861-1940.
Title:         A history of Greek mathematics, by Sir Thomas
                  Heath ...
Published:     Oxford, The Clarendon Press, 1921.
Description:   2 v. diagrs. 23 cm.
LC Call No.:   QA22.H4
Notes:         I. From Thales to Euclid.--II. From Aristarchus
                  to Diophantus.
Subjects:      Mathematics, Greek.
               Mathematics -- History.
Control No.:   6383201

Author:        Horn, W[ilhelm] [from old catalog]
Title:         Die logistik und die trigonometrie der Griechen.
Published:     München, Buchdruckerei von F. Straub, 1877.
Description:   1 p.l., 46 p. 24 diagr. on 2 fold. pl. 23 cm
LC Call No.:   QA22.H81
Subjects:      Mathematics, Greek. [from old catalog]
Control No.:   6323958

Author:        Hunger, K. G. (Karl Gottlob)
Title:         Die arithmetische Terminologie der Griechen : als
                  Kriterium für das System der griechischen Arithmetik / von
                  K.G. Hunger.
Published:     Hildburghausen : F.W. Gadow, 1874.
Description:   27 p. ; 25 cm.
LC Call No.:   QA22.H86x 1874
Notes:         "Einladungsschrift des Herzogl. Gymnasiums in
                  Hildburghausen zur Anhörung der öffentlichen Prüfung der
                  Schüler am 26. März, Vormittags von 8-12 und Nachmittags
                  von 2-5 Uhr und des Redeactus am 28. März, Vormittags von 10
                  Uhr an."
               Includes bibliographical references.
Subjects:      Mathematics, Greek.
               Arithmetic -- Terminology.
Control No.:   1456205

Author:        Klein, Jacob, 1899-1978.
Uniform Title: Griechische Logistik und die Entstehung der
                  Algebra. English
Title:         Greek mathematical thought and the origin of
                  algebra / by Jacob Klein ; translated by Eva Brann.
Published:     New York : Dover Publications, 1992.
Description:   xv, 360 p. ; 22 cm.
LC Call No.:   QA22.K513 1992
Dewey No.:     512/.009 20
ISBN:          0486272893
Notes:         "Unabridged and unaltered republication of the
                  edition published by the M.I.T. Press, Cambridge,
                  Massachusetts, in 1968"--T.p. verso.
               Includes bibliographical references and indexes.
Subjects:      Mathematics, Greek.
               Algebra -- History.
Control No.:   4868995

Author:        Loria, Gino.
Title:         Le scienze esatte nell'antica Grecia.
Edition:       2. ed. totalmente riv.
Published:     Milano, Hoepli, 1914.
Description:   969 p. illus. 16 cm.
Series:        Manuali Hoepli
LC Call No.:   QA22.L62 1914
Subjects:      Mathematics, Greek.
Control No.:   6505500

Author:        Loria, Gino, 1862- [from old catalog]
Title:         Histoire des sciences mathématiques dans
                  l'antiquité hellénique,
Published:     Paris, Gauthier-Villars et cie, 1929.
Description:   2 p. l. iii, [1], 215 p. front., diagrs. 19 cm.
LC Call No.:   QA22.L6
Subjects:      Mathematics, Greek. [from old catalog]
               Mathematics -- History. [from old catalog]
Control No.:   9682286

Author:        Menelaus, of Alexandria. [from old catalog]
Title:         Kit¯ab M¯an¯al¯awus.
Published:     [1940] 1359
Description:   148 p. illus. 26 cm.
LC Call No.:   QA22.M4512 (Orien Arab)
Notes:         Romanized.
Subjects:      Spherical trigonometry.
               Mathematics, Greek. [from old catalog]
Other authors: Isòh¯aq ibn òHunayn, d 910 or 11, [from old
                  catalog] tr.
               al-òT¯us¯i, Naòs¯ir al-D¯in Muòhammad ibn
                  Muòhammad, 1201-1274, [from old catalog] ed.
Other titles:  F¯i al-ashk¯al al-kur¯iyah.
Control No.:   8958121

Author:        Neugebauer, O. (Otto), 1899-
Title:         The exact sciences in antiquity.
Edition:       2d ed.
Published:     Providence, Brown University Press, 1957.
Description:   xvi, 240 p. illus. 24 cm.
LC Call No.:   QA22.N36 1957
Dewey No.:     510.93
Subjects:      Mathematics, Ancient.
               Astronomy, Ancient.
Control No.:   4529617

Author:        Rothlauf, Benedikt. [from old catalog]
Title:         Die mathematik zu Platons zeiten und seine
                  beziehungen zur ihr, nach Platons eigenen werken und den
                  zeugnissen älterer schriftsteller ...
Published:     Jena, 1878.
Description:   74 p. 21 diagr. on 1  fold. pl. 23 cm.
LC Call No.:   QA22.R85
Subjects:      Mathematics, Greek. [from old catalog]
Control No.:   8665426

Author:        Smith, David Eugene, 1860-1944.
Title:         Mathematics,
Published:     Boston, Mass., Marshall Jones company [c1923]
Description:   x p., 1 l., 175 p. illus. 19 cm.
LC Call No.:   QA22.S65
Subjects:      Mathematics -- History.
Control No.:   5918310

Author:        Tannery, Paul, 1843-1904. [from old catalog]
Title:         La géométrie grecque,
Published:     Paris, Gauthier-Villars, 1887.
Description:   vi p., 1 l., 188 p. 2 diagr. 26 cm.
LC Call No.:   QA22.T16
Subjects:      Geometry -- History. [from old catalog]
               Mathematics, Greek. [from old catalog]
Control No.:   8666935

Author:        [Tannery, Paul], 1843-1904. [from old catalog]
Title:         Notes sur trois manuscits grecs mathématiques de
                  Turin.
Published:     [Paris, E. Leroux, 1905]
Description:   [207]-210 p. 24 cm.
LC Call No.:   QA22.T18
Subjects:      Mathematics, Greek. [from old catalog]
Control No.:   9738739

Author:        Tannery, Paul, 1843-1904. [from old catalog]
Title:         Les prétendues notations pythagoriennes. Sur
                  l'origine des chiffres.
Published:     Paris, E. Leroux, 1892.
Description:   12 p. 25 cm.
LC Call No.:   QA22.T2
Subjects:      Mathematics -- History. [from old catalog]
               Pythagoras and Pythagorean school. [from old
                  catalog]
Control No.:   5915270

Author:        Waerden, B. L. van der (Bartel Leendert), 1903-
Uniform Title: Ontwakende wetenschap. English
Title:         Science awakening. English translation by Arnold
                  Dresden, with additions of the author.
Published:     New York, Oxford University Press, 1961.
Description:   306 p. illus. 26 cm.
LC Call No.:   QA22.W314 1961
Dewey No.:     510.93
Notes:         Rev. translation of Ontwakende wetenschap.
Subjects:      Mathematics, Egyptian.
               Mathematics, Babylonian.
               Mathematics, Greek.
Control No.:   278046

Title:         Algorithmvs demonstratvs ...
Published:     [Norimbergæ, apud Io. Petreium] 1534.
Description:   [64] p. 20 cm.
LC Call No.:   QA23.A4
Notes:         Title within architectural border.
               Signatures: A-Hp4s.
               Authorship unknown; has been attributed to
                  Regiomontanus and to Jordanus Nemorarius.
               Edited by Johann Schöner.
               L. C. copy imperfect: t.-p. torn, sig. Diib-Diiia
                  badly boxed.
Subjects:      Mathematics -- Early works to 1800.
Other authors: Regiomontanus, Joannes, 1436-1476, supposed
                  author.
               Jordanus, Nemorarius, 13th cent, supposed
                  author.
               Schöner, Johann, 1477-1547, ed.
Control No.:   8809516

Author:        Benedict, Suzan Rose, b. 1873.
Title:         A comparative study of the early treatises
                  introducing into Europe the Hindu art of reckoning, by Suzan
                  Rose Benedict ...
Published:     [Concord, N.H., The Rumford press, 1916]
Description:   vi, 126 p. 25 cm.
LC Call No.:   QA23.B3
Notes:         Thesis (Ph. D.)--University of Michigan, 1914.
Subjects:      Mathematics -- History.
               Mathematics, Hindu.
               Algorithms.
Control No.:   2162069

Author:        Carlebach, Joseph, 1883-1942.
Title:         Lewi ben Gerson als mathematiker; ein beitrag zur
                  geschichte der mathematik bei den Juden. Von dr. phil. nat.
                  Joseph Carlebach ...
Published:     Berlin, L. Lamm, 1910.
Description:   238, [2] p. fold. diagrs. 24 cm.
LC Call No.:   QA23.C3
Notes:         "Literatur": p. 91-92.
Subjects:      Levi ben Gershom, 1288-1344.
               Mathematics, Medieval.
               Mathematics, Jewish.
Control No.:   3107531

Author:        Goldberg, Adeline, ed.
Title:         Die jüdischen mathematiker und die jüdischen
                  anonymen mathematischen schriften, alphabetisch geordnet mit
                  angabe ihrer zeit, zugleich ein index zu M. Steinschneider's
                  Mathematik bei den Juden, zusammengestellt von Adeline
                  Goldberg.
Published:     Frankfurt a.M., J. Kauffmann, 1901.
Description:   12 p. 22 cm.
LC Call No.:   QA23.G7
Subjects:      Mathematicians, Jewish.
               Steinschneider, Moritz, 1816-1907. Mathematik bei
                  den Juden
Control No.:   2634544

Author:        Levi ben Gershom, 1288-1344.
Title:         Ma®aâseh òhoshev.
Published:     [Frankfurt am Main] : Bi-defus Y. L. Golde
                  [1909]
Description:   100 p. ; xiv, 139 p. ; 23 cm.
LC Call No.:   QA23.L4 1909
Notes:         Added t.p.: Maassei choscheb.
Subjects:      Arithmetic -- Early works to 1900.
               Mathematics, Jewish.
Other authors: Lange, Gerson, 1868- ed. and tr.
Control No.:   6481810

Author:        Woepcke, Franz, 1826-1864. [from old catalog]
Title:         Sur l'introduction de l'arithmétique indienne en
                  occident et sur deux documents importants publiés par le
                  prince Don Balthasar Boncompagni et relatifs à ce point de
                  l'histoire des sciences.
Published:     Rome, Impr. des sciences mathématiques et
                  physiques, 1859.
Description:   72 p. 30 cm.
LC Call No.:   QA23.W62
Subjects:      Mathematics -- History. [from old catalog]
               Boncompagni-Ludovisi, Bladassare, principe,
                  1821-1894. [from old catalog]
               Fibonacci, Leonardo, fl. 1220. Abbaci di Leonardo
                  Pisano. [from old catalog]
               Khuw¯arizm¯i, Muòhammad ibn M¯us¯a, fl. 813-846.
                  Jam° wa-l-tafr¯iòk. [from old catalog]
Control No.:   8884191

Author:        Woepcke, Franz, 1826-1884.
Title:         Recherches, sur l'histoire des sciences
                  mathématiques chez les Orientaux, d'après des traités
                  inédits arabes et persans. Analyse et extrait d'un recueil
                  de constructions géométriques par Aboûl Wafâ. (Manuscrit
                  persan no. 169, ancien fonds de la Bibliothèque impériale),
                  par M. F. Woepcke.
Published:     Paris, Imprimerie impériale, 1855.
Description:   3 p. l., 89 p. diagrs. 23 cm.
LC Call No.:   QA23.W6
Notes:         "Extrait no. 2 de l'année 1855 du Journal
                  asiatique."
Subjects:      Mathematics -- History.
               Mathematics, Arab.
Other authors: Ab¯u al-Waf¯a al-Buzj¯an¯i, 940-997.
Control No.:   7324006

Author:        Hofmann, Joseph Ehrenfried, 1900-
Uniform Title: Geschichte der Mathematik. English
Title:         Classical mathematics; a concise history of the
                  classical era in mathematics. [Translated from the German
                  Geschichte der Mathematik by Henrietta O. Midonick].
Published:     New York, Philosophical Library [1960, c1959]
Description:   159 p. 22 cm.
LC Call No.:   QA24.H643
Dewey No.:     510.9
Subjects:      Mathematics -- History.
Control No.:   749801

Author:        Kloyda, Mary Thomas à Kempis, Sister, 1896-
Title:         Linear and quadratic equations, 1550-1660 [by]
                  Sister Mary Thomas à Kempis Kloyda ...
Published:     Ann arbor, Mich., Edwards brothers, inc., 1938.
Description:   xii, 141 p. illus., 1938.
LC Call No.:   QA24.K6
Dewey No.:     512.09
Notes:         Thesis (Ph. D.)--University of Michigan, 1936.
               "Lithoprinted."
               Bibliography: p. 119-135: "Sources of information
                  concerning works included in the bibliography": p. 2;
                  bibliographical foot-notes.
Subjects:      Equations.
               Equations, Quadratic.
               Algebra -- Early works to 1800.
               Algebra -- History.
               Algebra -- Bibliography.
Control No.:   9244366

Author:        880-01 Nishimura, T¯osato, 1718-1787.
Title:         880-02 S¯udo sh¯odan / T¯osato t¯o.
Published:     880-03 [Kyoto] : Minoya Jiemon : Nishimura
                  Heihachi : Hayashi Ih¯e, An®ei 7 [1778]
Description:   2 v. ; 23 cm.
LC Call No.:   QA24.N57 1778
Notes:         Caption title.
               Within single border, except inside double (18.8
                  x 13.5 cm.); text in 10 vertical lines.
               On double leaves, oriental style (fukurotoji).
               Kotenseki s¯og¯o mokuroku, v. 5, p. 26 (S¯udo
                  sh¯odan, 2-kan 2-satsu, auth. Nishimura T¯osato, An®ei 7
                  [1778] kan).
               LC copy (v. 1) imperfect: title piece wanting.
                  DLC
               LC set wormed, with loss of text. DLC
Subjects:      Mathematics.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13823876

Author:        Tramer, Moritz, 1882- [from old catalog]
Title:         Die Entdeckung und Begründung der Differential-
                  und Integralrechung durch Leibniz im Zusammenhange mit seinen
                  Anschauungen in Logik und Erkenntnistheorie.
Published:     Bern, buchdr. Scheitlin, Spring, 1906.
Description:   135 p. illus. 22 cm.
LC Call No.:   QA24.T7
Subjects:      Leibniz, Gottfried Wilhelm, Freiherr von,
                  1646-1716. [from old catalog]
               Mathematics -- History. [from old catalog]
Control No.:   7005122

Author:        Zeller, Mary Claudia, 1910-
Title:         The development of trigonometry from
                  Regiomontanus to Pitiscus [by] Sister Mary Claudia Zeller
                  ...
Published:     [Ann Arbor, Mich., Lithoprinted by Edwards
                  brothers, inc., 1946]
Description:   vi, 119 p. incl. fold. tab. front., facsisms.,
                  diagrs. 27 cm.
LC Call No.:   QA24.Z4
Dewey No.:     514.09
Notes:         Thesis (PH.D.)--University of Michigan, 1944.
               Bibliography: p. 115-119.
Subjects:      Trigonometry -- History.
Control No.:   1219713

Author:        Chasles, M. (Michel), 1793-1880.
Title:         Rapport sur les progrès de la géométrie, par
                  M. Chasles ... Publication faite sous les auspices du
                  Ministère de l'instruction publique.
Published:     Paris, Imprimerie nationale, 1870.
Description:   2 p. l., 388 p., 1 l. 26 cm.
Series:        Recueil de rapports sur l'état des lettres et
                  les progrès des sciences en France
LC Call No.:   QA26.C6
Notes:         Series title also at head of t.-p.
Subjects:      Geometry -- History.
Control No.:   2634426

Author:        Darboux, Gaston, 1842-1917. [from old catalog]
Title:         A survey of the development of geometric methods.
                  Address delivered before the section of geometry of the
                  International congress of arts and science,
Published:     New York, 1905.
Description:   [517]-543 p. 25 cm.
LC Call No.:   QA26.D3
Subjects:      Geometry -- History. [from old catalog]
Other authors: Thompson, Henry Dallas, 1864-1927, [from old
                  catalog] tr.
Control No.:   7743944

Author:        Hankel, Hermann, 1839-1873.
Title:         Die entwickelung der mathematik in den letzten
                  jahrhunderten. Ein vortrag beim eintritt in den akademischen
                  senat der universität Tübingen ein 29. April 1869, gehalten
                  von dr. Hermann Hankel.
Published:     Tübingen, L. F. Fues, 1869.
Description:   36 p. 23 cm.
LC Call No.:   QA26.H3
Subjects:      Mathematics -- History.
Control No.:   8803753

Author:        Isely, Louis, 1854-
Title:         Les progrès de la géométrie et l'enseignement
                  moderne, par Louis Isely ...
Published:     Neuchatel, Impr. Attinger frères, 1907.
Description:   54 p. 25 cm.
LC Call No.:   QA26.I78
Notes:         At head of title: Académie de Neuchatel.
Subjects:      Geometry -- History.
Other authors: Université de Neuchâtel.
Control No.:   2634364

Author:        Mangoldt, Hans von, 1854-1925.
Title:         Bilder aus der entwickelung der reinen und
                  angewandten mathematik während des neunzehnten jahrhunderts
                  mit besonderer berücksichtigung des einflusses von Carl
                  Friedrich Gauss ...
Published:     Aachen, La Ruell'sche accidenzdruckerei (J.
                  Deterre) [1900]
Description:   22 p. 24 cm.
LC Call No.:   QA26.M27
Notes:         Cover-title.
               Festrede--K. Tech. hochschule, Aachen, Jan. 11,
                  1900.
Subjects:      Mathematics -- History.
Other authors: Gauss, Carl Friedrich, 1777-1855.
Control No.:   272386

Author:        Simon, Maximilian, 1844-1918. [from old catalog]
Title:         Über die entwicklung der elementar-geometrie im
                  XIX. jahrhundert; bericht der Deutschen
                  mathematiker-vereinigung,
Published:     Leipzig, B. C. Teubner, 1906.
Description:   viii, 278 p. diagrs. 26 cm.
LC Call No.:   QA26.S5
Subjects:      Geometry -- History. [from old catalog]
               Geometry -- History -- Bibliography. [from old
                  catalog]
               Trigonometry -- History. [from old catalog]
               Trigonometry -- History -- Bibliography. [from
                  old catalog]
Control No.:   6864024

Author:        Smith, David Eugene, 1860-1944.
Title:         History of modern mathematics. By David Eugene
                  Smith ...
Edition:       4th ed., enl. 1st thousand.
Published:     New York, J. Wiley & Sons; London, Chapman &
                  Hall, limited, 1906.
Description:   81 p. 24 cm.
Series:        Mathematical monographs. no. 1
LC Call No.:   QA26.S64
Notes:         Reissue of chapter 11 of Higher mathematics, ed.
                  by M. Merriman and R.S. Woodward, 1896.
               Bibliography: p. 68-73.
Subjects:      Mathematics -- History.
Control No.:   8214417

Author:        Staude, Otto, 1857- [from old catalog]
Title:         Die hauptepochen der entwicklung der neueren
                  mathematik.
Published:     Leipzig, B. G. Teubner, 1902.
Description:   15 p. 24 cm.
LC Call No.:   QA26.S79
Subjects:      Mathematics -- History. [from old catalog]
Control No.:   6792858

Title:         880-01 Honch¯o s¯ugaku s¯ot¯o ryakki.
Published:     [not before 1887]
Description:   1 sheet : geneal. tables ; 40 x 53 cm. folded to
                  14 x 9 cm.
LC Call No.:   QA28.H66 1887
Notes:         Ms. (shahon), the copier and the date not known.
               Caption title.
               Not listed in Kokusho s¯omokuroku, and Kotenseki
                  s¯og¯o mokuroku.
Subjects:      Mathematicians -- Japan.
               Surveyers -- Japan.
Other authors: Japanese Rare Book Collection (Library of
                  Congress) DLC
Control No.:   13677611

Author:        Ahrens, W. (Wilhelm), 1872-1927.
Title:         Mathematiker-Anekdoten, von Dr. W. Ahrens ... mit
                  den Bildnissen von A. Riese, P. Fermat, L. Euler, C. F.
                  Gauss, J. L. Lagrange, A. L. Cauchy, B. Riemann, K. H.
                  Schellbach, H. Grassman.
Published:     Leipzig, B. G. Teubner, 1916.
Description:   56 p. ports. (incl. front.) 19 cm.
Series:        Mathematische Bibliothek, hrsg. von W. Lietzman
                  und A. Witting. 18
LC Call No.:   QA28.A45
Subjects:      Mathematicians.
Series Entry:  Mathematisch-physikalische Bibliothek.  Reihe I ;
                  18.
Control No.:   8710435

Author:        Archibald, Raymond Clare, 1875-1957.
Title:         Mathematical table makers; portraits, paintings,
                  busts, monuments, bio-bibliographical notes.
Published:     New York, Scripta mathematica, 1948.
Description:   82 p. ports. 25 cm.
Series:        The Scripta mathematica studies ; no. 3
LC Call No.:   QA28.A7
Dewey No.:     925.1
Notes:         "Revised, rearranged, and somewhat extended
                  reprint of two articles appearing in scripta mathematica in
                  1946, together with three additional sketches and
                  portraits."
Subjects:      Mathematicians.
Control No.:   2163972

Author:        Baldi, Bernardino, 1553-1617.
Title:         Cronica de matematici, overo Epitome dell'
                  istoria delle vite loro. Opera di Monsignor Bernardino Baldi
                  da Urbino, abate di Guastalla.
Published:     Urbino, Per A.A. Monticelli, 1707.
Description:   8 p.l., 156 p. 25 cm.
LC Call No.:   QA28.B17
Notes:         Title vignette: view of Urbino.
Subjects:      Mathematicians.
Control No.:   4525401

Author:        Baldi, Bernardino, 1553-1617.
Title:         Vite inedite di matematici italiani, scritte da
                  Bernardino Baldi e pubblicate da Enrico Narducci ...
Published:     Roma, Tip. delle scienze matematiche e fisiche,
                  1887.
Description:   xxii, 175, [1] p. 30 cm.
LC Call No.:   QA28.B19
Notes:         "Estratto dal Bullettino di bibliografia e di
                  storia delle scienze matematiche e fisiche, tomo xix.
                  luglio-novembre 1886."
Subjects:      Mathematicians.
Other authors: Narducci, Enrico, 1832-1893, ed.
Control No.:   1217192

Author:        Bell, Eric Temple, 1883-1960.
Title:         Men of mathematics, by E. T. Bell.
Published:     New York, Simon and Schuster, 1937.
Description:   xxi, 592 p., 1 l. front., ports., diagrs. 25 cm.
LC Call No.:   QA28.B4
Dewey No.:     925.1
Subjects:      Mathematicians.
               Mathematics -- History.
Control No.:   2635961

Author:        Bobynin, Viktor Viktorovich, 1849-1919, [from old
                  catalog] comp.
Title:         Biografii znamenitykh matematikov.
Published:     1886-
Description:   v. 24 cm.
LC Call No.:   QA28.B6
Subjects:      Mathematicians. [from old catalog]
Control No.:   7954909

Author:        [Ginn & co., publishers] [from old catalog]
Title:         Mathematical portraits and pages.
Published:     [Boston, Ginn and company, c1916]
Description:   [19] p. illus. (incl. ports., facsims.) 23 cm.
LC Call No.:   QA28.G5
Subjects:      Mathematicians. [from old catalog]
               Mathematics -- Early works to 1800 --
                  Bibliography. [from old catalog]
Other authors: Smith, David Eugene, 1860- [from old catalog]
                  comp.
Control No.:   7305630

Author:        Macfarlane, Alexander, 1851-1913.
Title:         Lectures on ten British mathematicians of the
                  nineteenth century, by Alexander Macfarlane ...
Edition:       1st ed., 1st thousand.
Published:     New York, John Wiley & sons, inc.; [etc., etc.,]
                  1916.
Description:   148 p. front. (10 port.) illus. (port.) diagrs.
                  24 cm.
Series:        Mathematical monographs, ed. by M. Merriman and
                  R.S. Woodward, no. 17
LC Call No.:   QA28.M2
ISBN:          $1.25
Notes:         Delivered at Lehigh university during the years
                  1901-1904. cf. Pref.
               George Peacock.--Augustus De Morgan.--Sir William
                  Rowan Hamilton.--George Boole.--Arthur Cayley.--William
                  Kingdon Clifford.--Henry John Stephen Smith.--James Joseph
                  Sylvester.--Thomas Penyngton Kirkman.--Isaac Todhunter.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Mathematicians -- Great Britain -- Biography.
               Mathematics -- Great Britain -- History -- 19th
                  century.
Series Entry:  Mathematical monographs (New York, N.Y.) ; no.
                  17.
Control No.:   273492

Author:        Smith, David Eugene, 1860-1944.
Title:         A portfolio of portraits of eminent
                  mathematicians. Edited by David Eugene Smith ...
Published:     Chicago, The Open court publishing company,
                  1905.
Description:   12 port. 35 x 28 cm.
LC Call No.:   QA28.S64
Notes:         In portfolio 37 x 29 cm.
               Each portrait has guard sheet with descriptive
                  letterpress.
              
                  Descartes.--Pythagoras.--Archimedes.--Fermat.--Leonardo of
                  Pisa.--Euclid.--Cardan.--Leibnitz.--Napier.--Vieta.--Newton.--Thales.
Subjects:      Mathematicians -- Biography.
Control No.:   1217249

Author:        Smith, David Eugene, 1860-1944.
Title:         Portraits of eminent mathematicians; with brief
                  biographical sketches, by David Eugene Smith ...
Published:     New York, Scripta mathematica, 1936-38.
Description:   2 v. illus. (incl. facsims.) ports. 36 x 27 cm.
Series:        Pictorial mathematics ; portfolio number 1-2
LC Call No.:   QA28.S645
Dewey No.:     925.1
Subjects:      Mathematicians -- Biography.
               Mathematics.
Other titles:  Pictorial mathematics.
Control No.:   746828


Title:         Directory of women mathematicians.
Published:     [New York] American Mathematical Society.
Description:   v. 23 cm.
LC Call No.:   QA30.D57
Dewey No.:     510/.92/2
ISSN:          0091-7583
Notes:         SERBIB/SERLOC merged record
Subjects:      Women mathematicians -- United States --
                  Directories.
Other authors: American Mathematical Society.
Control No.:   11172385

Title:         Bamberger Rechenbuch 1483. [Mit einem Nachwort
                  von J. J. Burckhardt. Photolithographischer Neudruck der
                  Ausg. Bamberg 1483.
Published:     München, Graphos, 1966]
Description:   1 v. (unpaged) 11 x 12 cm.
LC Call No.:   QA32.B3 1483a
Notes:         Title from "Nachwort" by J. J. Burckhardt.
               Authorship attributed to "Rechmeister Ulrich
                  Wagner."
               Bibliography at end of "Nachwort" by J. J.
                  Burckhardt.
Subjects:      Arithmetic -- Early works to 1900.
Other authors: Wagner, Ulrich, Rechenmeister.
               Burckhardt, Johann Jakob, 1903-
Control No.:   8953703

Author:        al-T¯us¯i, Naòs¯ir al-D¯in Muòhammad ibn
                  Muòhammad, 1201-1274. [from old catalog]
Title:         al-Ris¯alah al-sh¯afiyah °an al-shakk f¯i
                  al-khuòt¯uòt al-mutaw¯az¯iyah.
Published:     1359 [1940]
Description:   40 p. illus. 26 cm.
LC Call No.:   QA32.T87 1940 (Orien Arab)
Notes:         Romanized.
Subjects:      Mathematics, Arab.
               Geometry, Plane. [from old catalog]
Control No.:   7085346

Author:        ¯Aryabhaòta, b. 476.
Title:         Leçons de calcul d'Âryabhata, par m. Léon
                  Rodet ...
Published:     Paris, Imprimerie nationale, 1879.
Description:   48 p. diagrs. 23 cm.
LC Call No.:   QA32.A7
Notes:         Sanskrit title at head of t.-p.
               "Extrait du Journal asiatique."
               Avant-propos.--Traduction.--Notes.--Appendice:
                  Texte sancrit ([4] p. following p. 46 not included in
                  paging)
Subjects:      Mathematics, Hindu.
Other authors: Rodet, Léon, ca. 1850-1895.
Control No.:   10129881

Author:        B¯ir¯un¯i, Muòhammad ibn Aòhmad, 973?-1048.
Title:         Ras¯a®il.
Published:     [1948]
Description:   226, 126 (i.e. 226), 107, 30 p. diagrs. 25 cm.
LC Call No.:   QA32.B5 (Orien Arab)
Notes:         Romanized.
Subjects:      Mathematics -- Early works to 1800. [from old
                  catalog]
               Mathematics, Arab.
Control No.:   10294729

Author:        Bradwardine, Thomas, 1290?-1349.
Title:         Thomas of Bradwardine, his Tractatus de
                  proportionibus; its significance for the development of
                  mathematical physics. Edited and translated by H. Lamar
                  Crosby, Jr.
Published:     Madison, University of Wisconsin Press, 1955.
Description:   xi, 203 p. 24 cm.
LC Call No.:   QA32.B7 1955
Dewey No.:     510
Notes:         Latin and English.
               Bibliography: p. 195-197.
Subjects:      Mathematics -- Early works to 1800.
               Proportion.
Other authors: Crosby, Henry Lamar, 1916- ed.
Other titles:  Tractus de proportionibus.
Control No.:   9323395

Author:        Brahmagupta, 7th cent.
Title:         Algebra, with Arithmetic and mensuration, from
                  the Sanskrit of Brahmegupta and Bháscara.  Translated by
                  Henry Thomas Colebrooke.
Published:     London, J. Murray, 1817.
Description:   lxxxiv, 378 p. 27 cm.
LC Call No.:   QA32.B72
Notes:         The 12th and 18th chapters, Gaònit¯adhy¯aya and
                  Kuòtòtak¯adhy¯aya, of Brahmagupta's Brahmasiddh¯anta; and the
                  first two parts, L¯il¯avat¯i and B¯ijagaònita, of Bh¯askara's
                  Siddh¯antaâsir¯omaòni.
Subjects:      Mathematics, Arab.
               Algebra -- Early works to 1800.
Other authors: Bh¯askar¯ac¯arya, b. 1114.
               Colebrooke, H. T. (Henry Thomas), 1765-1837, tr.
Other titles:  Arithmetic and mensuration.
Control No.:   6549638

Author:        Chu, Shih-chieh, 14th century. [from old
                  catalog]
Title:         Ssu yüan yü chien.
Published:     [s.l. : s.n., i.e. 1838]
Description:   8 v. (on double leaves) in case : graphs ; 27
                  cm.
LC Call No.:   QA32.C48 1838
Notes:         Romanized.
Subjects:      Mathematics -- Early works to 1800. [from old
                  catalog]
               Mathematics, Chinese. [from old catalog]
Other authors: Lo, Shih-lin, 1774-1853. [from old catalog]
               I, Chih-han, 19th century. Ssu yüan shih li.
                  1838. [from old catalog]
Other titles:  Ssu yüan yü chien hsi ts°ao.
Control No.:   8584609

Author:        Fibonacci, Leonardo, ca. 1170-ca. 1240.
Title:         Scritti di Leonardo Pisano ... pubblicati da
                  Baldassarre Boncompagni ...
Published:     Roma, Tipografia delle scienze matematiche e
                  fisiche, 1857-62.
Description:   2 v. diagrs. 32 cm.
LC Call No.:   QA32.F5
Notes:         Vol. 1 has also special t.-p.
               In Latin.
               I. Il liber abbaci, secondo la lezione del Codice
                  magliabechiano, C. I, 2616, Badia fiorentina, n.p0s
                  73.--II. La practica geometriae, secondo la lezione del
                  Codice urbinate n.p0s 292 della Biblioteca vaticana.
                  Opuscoli, secondo la lezione di un codice della Biblioteca
                  ambrosiana di Milano contrassegnato E. 75, parte superiore.
Subjects:      Arithmetic -- Early works to 1900.
               Geometry -- Early works to 1800.
Other authors: Boncompagni, Baldassarre, 1821-1894, ed.
Other titles:  Liber abaci.
               Practica geometriae.
Control No.:   746976

Author:        Ibn Ezra, Abraham ben Meïr, 1092-1167.
Title:         Sefer ha-mispar / meturgam u-meforash bi-leshon
                  Ashkenaz me®et Mosheh Zilberberg.
Published:     Frankfurt de-Main : Y. Koffmann, 655 [1895]
Description:   80, ix, 118 p. ; 23 cm.
LC Call No.:   QA32.I2
Notes:         Added t.p.: Das Buch der Zahl.
Subjects:      Mathematics -- Early works to 1800.
Other authors: Silberberg, Moses, tr.
Control No.:   8845903

Author:        Khuw¯arizm¯i, Muòhammad ibn M¯usá, fl. 813-846.
Uniform Title: Jabr wa-al-muq¯abalah. Latin & English
Title:         Robert of Chester's Latin translation of the
                  Algebra of al-Khowarizmi / with an introduction, critical
                  notes and an English version by Louis Charles Karpinski.
Published:     New York : Macmillan ; London : Macmillan and
                  Company Limited, 1915.
Description:   vii, 164, [6] p. : ill. ; 27 cm.
Series:        University of Michigan studies. Humanistic series
                  ; . 11, pt. 1
               Contributions to the history of science ; pt. 1
LC Call No.:   QA32.K453
Notes:         Advertisements on [6] p. at end.
Subjects:      Mathematics -- Early works to 1800.
               Mathematics, Arab.
Other authors: Robert, of Chester, fl. 1143.
               Karpinski, Louis Charles, 1878-1956.
Control No.:   9645850

Author:        Khuw¯arizm¯i, Muòhammad ibn M¯us¯a, fl. 813-846.
                  [from old catalog]
Title:         Kit¯ab al-jabr wa-al-muq¯abalah.
Published:     1939.
Description:   106 p. facsims. 25 cm.
LC Call No.:   QA32.K45 1939
Notes:         Romanized.
Subjects:      Mathematics, Arab.
Other authors: Musharrafah, °Al¯i Muòsòtaf¯a, 1898-1950, [from
                  old catalog] ed.
               Aòhmad, Muòhammad Murs¯i, [from old catalog] ed.
Other titles:  Jabr wa-al-muq¯abalah.
Control No.:   8957772

Author:        Lefèvre d'Etaples, Jacques, d. 1536.
Title:         In hoc libro contenta;
Published:     [Parisiis, Ex officina H. Stephani, 1510]
Description:   xlviii l. illus. 29 cm.
LC Call No.:   QA32.L47 1510
Subjects:      Arithmetic -- Early works to 1900.
               Geometry -- Early works to 1800. [from old
                  catalog]
Other authors: Boethius, d. 524. Institutione arithmetica. [from
                  old catalog]
               Clichtove, Josse, d. 1543. [from old catalog]
Other titles:  Epitome c¯opendisoaque introductio in libros
                  arithmeticos.
Control No.:   7562680

Author:        Lefèvre d'Etaples, Jacques, d. 1536.
Title:         In hoc opere contenta Arithmetica decem libris
                  demonstrata.
Published:     [n.p.] [1514]
Description:   [144] p. incl. illus., tables. diagrs. 29 cm.
LC Call No.:   QA32.L5
Subjects:      Arithmetic -- Early works to 1900.
               Music theory -- Early works to 1800.
               Boethius, d. 524.
Other authors: Jordanus Nemorarius, fl 1230. [from old catalog]
               Estienne, Henri, 1460?-1520, ed.
Control No.:   6821316

Author:        Lefèvre d'Etaples, Jacques, d. 1536.
Title:         Introductio ** Jacobi fabri Stapul¯esis in
                  arithme ** cam Diui Seuerini Boetij pariter [et] Jordani
Published:     [n.p., 1507?]
Description:   [63] p. 21 x 15 cm.
LC Call No.:   QA32.L47 1507
Subjects:      Arithmetic -- Early works to 1900.
               Circle-squaring.
Other authors: Boethius, d. 524.
               Jordanus, Nemorarius, 13th cent.
               Clichtove, Josse, d. 1543.
               Augustine, Saint, Bishop of Hippo.
               Boueles, Charles de, ca. 1470-ca. 1553.
               Campano, da Novara, d. 1296.
Control No.:   6845699

Author:        Mah¯av¯¸r¯ac¯arya.
Title:         The Ganita-s¯ara-sangraha of Mah¯av¯¸r¯ac¯arya
                  with English translation and notes, by M. Rang¯ac¯rya, M.A.,
                  Rao Bahadur.
Published:     Madras, Government press, 1912.
Description:   4 p l., ii, [vii]-xxiv, v, 158, v, 325 p. diagrs.
                  25 cm.
LC Call No.:   QA32.M3
Notes:         Added t.-p. in Sanskrit.
               Introduction by David Eugene Smith.
               Appendices: I. Sanskrit words denoting numbers
                  with their ordinary and numerical signification.--II.
                  Sanskrit words used in the translation and their
                  explanation.--III. Answers to problems.--V. Tables of
                  measures.
Subjects:      Mathematics -- Early works to 1800.
               Mathematics, Hindu.
Other authors: Ranga Chariyar, M., 1861-
               Smith, David Eugene, 1860-1944.
Control No.:   10107108

Author:        Mishnat ha-Middot. [from old catalog]
Title:         Mishnat ha-midot.
Published:     Berlin, A. Asher, 1864.
Description:   vi, 10 p. 23 cm.
LC Call No.:   QA32.M5
Notes:         Romanized.
Subjects:      Geometry -- Early works to 1800. [from old
                  catalog]
Other authors: Abraham bar òHiyya, ha-Nasi, 12th century. òHibur
                  ha-meshiòhah veha-tishboret. [from old catalog]
               Steinschneider, Moritz, 1816-1907, [from old
                  catalog] ed.
Control No.:   6081738

Author:        Moody, Ernest A. (Ernest Addison), 1903-
Title:         The medieval science of weights, scientia de
                  ponderibus. Treatises ascribed to Euclid, Archimedes, Thabit
                  ibn Qurra, Jordanus de Nemore and Blasius of Parma, ed. with
                  introductions, English translations and notes by Ernest A.
                  Moody [and] Marshall Clagett.
Published:     Madison, Univ. of Wisconsin Press, 1952.
Description:   x, 438 p. ill.
LC Call No.:   QA32.M6
Subjects:      Mechanics -- Early works to 1800.
               Weights and measures -- Early works to 1800.
Other authors: Clagett, Marshall, 1916-
Control No.:   6501729

Author:        Omar Khayyam.
Title:         The algebra of Omar Khayyam, by Daoud S. Kasir
                  ...
Published:     New York city, Teachers college, Columbia
                  University, 1931.
Description:   iv p., 1 l., 126 p. diagrs. 24 cm.
Series:        Teachers college, Columbia university.
                  Contributions to education, no. 385
LC Call No.:   QA32.O55 1931
Dewey No.:     512
Notes:         Issued also as thesis (PH. D.) Columbia
                  university.
               "A ... manuscript ... in the library of Professor
                  David Eugene Smith ... has been used as the Arabic text in
                  the preparation of the present translation."--p. 9
               Bibliography: p. 125-126.
               Introduction.--Al-jabr w'al muqâbalah of Omar
                  Khayyam. Demonstration concerning the completion and
                  reduction of problems.
Subjects:      Algebra -- Early works to 1800.
               Mathematics, Arab.
               Algebra -- History.
Other authors: Kasir, Daoud S. (Daoud Suleiman), 1892-
Series Entry:  Contributions to education ; no. 385.
Control No.:   746478

Author:        Omar Khayyam.
Title:         The algebra of Omar Khayyam, by Daoud S. Kasir.
Published:     New York city, Teachers college, Columbia
                  university, 1931.
Description:   iv p., 1 l., 126 p., 1 l. diagrs. 23 cm.
LC Call No.:   QA32.O55 1929
Dewey No.:     512
Notes:         Vita.
               Published also as Teacher college, Columbia
                  university, Contributions to education, no. 385.
               "A ... manuscript ... in the library of Professor
                  David Eugene Smith ... has been used as the Arabic text in
                  the preparation of the present translation."--p. 9.
               Thesis (Ph. D.)--Columbia university, 1929.
               Bibliography: p. 125-126.
               Introduction.--Al-jabr w'al muqâbalah of Omar
                  Khayyam. Demonstration concerning the completion and
                  reduction of problems.
Subjects:      Mathematics -- Early works to 1800.
               Mathematics, Arab.
               Mathematics -- History.
               Algebra -- History.
Other authors: Kasir, Daoud S. (Daoud Suleiman), 1892- ed. and
                  tr.
Control No.:   6880208

Author:        Oresme, Nicole, ca. 1320-1382.
Title:         An abstract of Nicholas Orême's Treatise on the
                  breadths of forms. Copyright by Charles Glenn Wallis.
Published:     Annapolis, Md., The St. John's bookstore, c1941.
Description:   23 p. diagrs. 23 cm.
Series:        The great books of St. John's program
LC Call No.:   QA32.O665
Notes:         Reproduced from type-written copy.
Subjects:      Geometry -- Early works to 1800.
Other authors: Wallis, Charles Glenn, tr.
Control No.:   5982021

Author:        Oresme, Nicole, ca. 1320-1382.
Title:         Der Algorismus proportionum des Nicolaus Oresme.
                  Zum ersten male nach der lesart der handschrift R.4p0s.2.
                  der Königlichen gymnasial-bibliothek zu Thorn hrsg. von
                  E.L.W.M. Curtze. Mit einer lithographierten tafel.
Published:     [Berlin, Druck von J. Draeger's buchdruckerei (C.
                  Feicht) 1868]
Description:   30 p., 1 l. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA32.O66
Dewey No.:     511/.8 19
Notes:         List of published works of Oresme: p. 7-8.
Subjects:      Algorithms.
Other authors: Curtze, E. L. W. M. (Ernst Ludwig Wilhelm
                  Maximilian), 1837-1903, ed.
Control No.:   272754

Author:        Pacioli, Luca, ca. 1445-1517.
Uniform Title: Somma di aritmetica, geometria, proporzione e
                  proporzionalità [from old catalog]
Title:         Su[m]ma de arithmetica, geometria, proportioni
                  [e] proportionalita.
Published:     Venice, Paganinus de Paganinis, 10-20 Nov. 1494.
Description:   [8], 224, 76 leaves. woodcuts: diagrs., initials,
                  border. 31.5 cm. (fol.)
LC Call No.:   Incun. 1494P3; Alternative class.: QA32
Notes:         The original issue as described in BM 15th cent.
               Printed in black and red.
               Goff L-315
               Hain-Copinger 4105
               BM 15th cent., V, p. 457 (IB.23272)
               IGI 7132, 7133
               LC copy: numbered leaves 1-8 misbound after leaf
                  152. Provenance: Gilbert R. Redgrave (bookplate). DLC
Subjects:      Mathematics -- Early works to 1800.
               Incunabula -- Italy -- Venice -- 1494. lcsh
Control No.:   6954778

Author:        Petrus, de Dacia, ca. 1235-1289.
Uniform Title: In Algorismum vulgarem Johannis de Sacrobosco
                  commentarius
Title:         Petri Philomeni de Dacia In Algorismum vulgarem
                  Johannis de Sacrobosco commentarius. Una cum Algormismo ipso
                  edidit / et praefatus est Maximillianus Curtze.
Published:     Hauniae : A.F. Host, 1897.
Description:   xix, 92 p. ; 24 cm.
LC Call No.:   QA32.P48 1897
Notes:         Latin text; introd. in German.
               Includes bibliographical references.
Subjects:      Arithmetic -- Early works to 1900.
Other authors: Sacro Bosco, Joannes de, fl. 1230. Algorismus
                  vulgaris. 1897.
               Curtze, E. L. W. M. (Ernst Ludwig Wilhelm
                  Maximilian), 1837-1903.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
Other titles:  In Algorismum vulgarem Johannis de Sacrobosco.
Control No.:   3899884

Author:        Regiomontanus, Joannes, 1436-1476.
Uniform Title: De triangulis. [from old catalog]
Title:         De traingvlis planis et sphaericis libri quinque,
                  unà cum tabulis sinuum, in quibus tota ipsorum triangulorum
                  scientia ex primis fundamentis geometricarum
Published:     Basileae [H. Petri, 1561]
Description:   4 p.l., 146 p., 19 l. incl. tables, diagrs. 32
                  cm.
LC Call No.:   QA32.M77 (Rare bk. Coll.)
Subjects:      Trigonometry -- Early works to 1800.
Other authors: Peurbach, Georg von, 1423-1461. [from old
                  catalog]
               Santbech, Daniel, 16th century, [from old
                  catalog] ed.
Control No.:   7403050

Author:        Brooklyn, Earmus hall high school. [from old
                  catalog]
Title:         General mathematics...
Published:     [n. p.] 1922.
Description:   1 v. cm.
LC Call No.:   QA38.B75
Control No.:   8606111

Title:         Formulario di matematica e fisica.
Published:     Firenze, Successori Le Monnier, 1894.
Description:   128 p. 11 cm.
LC Call No.:   QA41.F6
Subjects:      Mathematics -- Formulae. [from old catalog]
               Physics -- Tables, etc. [from old catalog]
Control No.:   10193463

Author:        Brooke, Charles, 1804-1879.
Title:         A synopsis of the principal formulae and results
                  of pure mathematics. By Charles Brooke ...
Published:     Cambridge, J. & J.J. Deighton; London, C.J.G. &
                  F. Rivington, 1829.
Description:   x, [2], 358 p. 22 cm.
LC Call No.:   QA41.B8
Subjects:      Mathematics -- Formulae.
Control No.:   10071390

Author:        Bürklen, Otto Th., 1856- [from old catalog]
Title:         Formelsammlung und repetitorium der mathematik,
Edition:       3. aufl. Neudruck.
Published:     Berlin und Leipzig, W. de Gruyter & co., 1920.
Description:   227 p. diagrs. 16 cm.
LC Call No.:   QA41.B95 1920
Subjects:      Mathematics. [from old catalog]
Control No.:   5989224

Author:        Bürklen, Otto Th., 1856- [from old catalog]
Title:         Formelsammlung und repetitorium der mathematik,
Published:     Berlin und Leipzig, G. J. Göschen, 1917.
Description:   227 p. diagrs. 16 cm.
LC Call No.:   QA41.B95 1917
Subjects:      Mathematics -- Formulae. [from old catalog]
Control No.:   9731013

Author:        Bürklen, Otto Th., 1856- [from old catalog]
Title:         Formelsammlung und repetitorium der mathematik,
Edition:       2. aufl., 4. abdruck.
Published:     Leipzig, G. J. Göschen, 1903.
Description:   229 p. diagrs. 16 cm.
LC Call No.:   QA41.B95 1903
Subjects:      Mathematics -- Formulae. [from old catalog]
Control No.:   10163323

Author:        Bürklen, O[tto] Th., 1856- [from old catalog]
Title:         Formelsammlung und repetitorium der mathematik,
Edition:       2. aufl. 3. abdruck.
Published:     Leipzig, G. J. Göschen, 1901.
Description:   229 p. diagr. 16 cm.
LC Call No.:   QA41.B95
Subjects:      Mathematics -- Formulae. [from old catalog]
Control No.:   8664410

Author:        Cajori, Florian, 1859-1930.
Title:         A history of mathematical notations.
Published:     La Salle, Ill., Open Court Pub. Co. [1974-   ,
                  c1928-
Description:   v. illus. 21 cm.
Series:        Open Court paperback
LC Call No.:   QA41.C32
Dewey No.:     510/.1/48
ISBN:          087548154X
Notes:         Reprint of the 1928-29 ed. published by the Open
                  Court Pub. Co., Chicago.
               Includes bibliographical references.
               v. 1. Notations in elementary mathematics.
Subjects:      Mathematical notation -- History.
               Mathematics -- History.
               Numerals -- History.
Control No.:   4574451

Author:        Carr, G. S. (George Shoobridge), b. 1837.
Title:         A synopsis of elementary results in pure
                  mathematics: containing propositions, formulæ, and methods of
                  analysis, with abridged demonstrations.
Published:     London, F. Hodgson; Cambridge, Macmillan & Bowes,
                  1886.
Description:   xxxvi p., 1 l., 935 p. tab., 193 diagr. on 20
                  fold. pl. 25 cm.
LC Call No.:   QA41.C31
Subjects:      Mathematics -- Formulæ. [from old catalog]
               Mathematics -- Bibliography. [from old catalog]
Control No.:   6790882

Author:        Dodson, Norman E.
Title:         Formulas for this and that, by Norman E. Dodson
                  [and] Philip T. Kelly, jr.
Published:     [Columbia, S.C., Crowson printing company, 1943]
Description:   viii, 75 p. 22 cm.
LC Call No.:   QA41.D6
Dewey No.:     510.83
Notes:         Reproduced from type-written copy.
               First edition.  cf. Pref.
Subjects:      Mathematics -- Formulae.
               Mathematics -- Terminology.
Other authors: Kelly, Philip Thomas, joint author.
Control No.:   9269073

Author:        Hagen, Johann G., 1847-1930.
Title:         Synopsis der hoeheren mathematik, von Johann G.
                  Hagen ...
Published:     Berlin, F.L. Dames, 1891-1930.
Description:   4 v. 33 x 25 cm.
LC Call No.:   QA41.H14
Dewey No.:     510
Notes:         Each vol. has also special t.-p.
               Bibliography at end of each vol.
               1. bd. Arithmetische und algebraische analyse.
                  1891.--2. bd. Geometrie der algebraischen gebilde. 1894.--3.
                  bd. Differential- und integralrechnung. 1900-05.--4. bd.
                  Metrische differentialgeometrie der ebene und des raumes.
                  1930.
               A digital reproduction made from a copy held by
                  Cornel University is available from the Cornell University
                  Library's Historical Mathematics Monographs Web site.
Subjects:      Mathematics.
Control No.:   4525535

Author:        International Correspondence Schools
Title:         Formulas, cube root, logarithms, by I.C.S.
                  staff.
Published:     Scranton, Pa., International Textbook Company
                  [1938]
Description:   iv, 57, 24, 20, 47 p.  illus.  20 cm.
Series:        [International Textbook Company.  Bluebooks]
                  285B
LC Call No.:   QA41.I6
Dewey No.:     510.83
Subjects:      Mathematics -- Formulae
               Cube root
               Logarithms
Control No.:   8784016

Author:        Seaver, Edwin P. (Edwin Pliny), 1838-1917.
Title:         Mathematical handbook; containing the chief
                  formulas of algebra, trigonometry, circular and hyperbolic
                  functions, differential and integral calculus, and analytical
                  geometry, together with mathematical tables, selected and
                  arranged by Edwin P. Seaver ...
Published:     New York, McGraw publishing company, 1907.
Description:   ix, 279 p. incl. tables. 22 cm.
LC Call No.:   QA41.S44
Subjects:      Mathematics -- Formulae.
               Mathematics -- Tables.
Control No.:   4052650

Author:        Smithsonian Institution.
Title:         Smithsonian mathematical formulae and tables of
                  elliptic functions; mathematical formulae prepared by Edwin
                  P. Adams ... Tables of elliptic functions prepared under the
                  direction of Sir George Greenhill, bart., by Col. R.L.
                  Hippisley ...
Edition:       First reprint ...
Published:     City of Washington, The Smithsonian institution,
                  1939.
Description:   viii, 314 p. incl. tables, diagrs. 24 cm.
Series:        Smithsonian miscellaneous collections ; v. 74,
                  no. 1
LC Call No.:   QA41.S7 1939
Dewey No.:     517.36
Notes:         Publication 2672.
               "Collections of mathematical formulae, etc."
                  (bibliography): p. v.
Subjects:      Mathematics -- Formulae.
               Mathematics -- Tables.
               Elliptic functions.
Other authors: Adams, Edwin P. (Edwin Plimpton), b. 1878.
               Hippisley, R. L. (Richard Lionel), 1853-1936.
               Greenhill, G. (George), Sir, 1847-1927.
Series Entry:  Publication (Smithsonian Institution) ; 2672.
Control No.:   274690

Author:        Mehling, Alwin, 1873- [from old catalog]
Title:         Über diejenigen flächen, die äquidistante
                  infinitesimale biegungen gestatten ...
Published:     Würzburg, Kgl. universitäts-druckerei von H.
                  Stürtz, 1899.
Description:   62 p., 1 l. 23 cm.
LC Call No.:   QA48.M5
Subjects:      Surfaces, Deformation of. [from old catalog]
Control No.:   10064319

Title:         Calculs touts faits pour la multiplication des
                  nombres.
Published:     Rouen, 1827.
Description:   [4], 100 p. ; 22 cm.
LC Call No.:   QA49.C15 1827
Notes:         A manuscript.
Subjects:      Multiplication -- Tables.
Control No.:   12925118

Title:         The multiplication table in rhyme for young
                  arithmeticians.
Published:     New York : Kiggins & Kellogg, [between 1849 and
                  1856]
Description:   16 p. : ill. ; 12 cm.
Series:        Third series ; no. 2
LC Call No.:   QA49.M85 1849
Notes:         "88 John Street." Kiggins & Kellogg published at
                  this address between 1849 and 1856.
Subjects:      Multiplication -- Tables -- Juvenile literature.
               Chapbooks -- Specimens.
Other authors: Kiggins & Kellogg.
               Marian S. Carson Collection (Library of Congress)
                  DLC
Series Entry:  Redfield's toy books. Third series ; no. 2
Control No.:   3553578

Title:         [Multiplication tables]
Published:     [S.l. : s.n., ca. 1830]
Description:   3 leaves of plates (2 folded) ; 12 cm.
LC Call No.:   QA49.T115 1830
Notes:         No text. Publication date inferred from dated
                  inscription.
Subjects:      Multiplication -- Tables.
Other authors: Marian S. Carson Collection (Library of Congress)
                  DLC
Control No.:   3080767

Title:         The quadranorm ...
Published:     [n.p., 1869]
Description:   1 chart. 24 x 45 cm.
LC Call No.:   QA49.Q15
Control No.:   6795053

Title:         Tables of squares, cubes, and roots.
Published:     [n.p., 1868?]
Description:   1 p.l., 13 p. 26 cm.
LC Call No.:   QA49.T11
Subjects:      Squares, Tables of. [from old catalog]
Control No.:   5861712

Author:        Alvsaker, Torgier. [from old catalog]
Title:         A manual for multiplication and division of any
                  number of feet and inches with numbers from 1 to 60 advancing
                  by 1/16th of inches ...
Published:     [n.p.] [c1911]
Description:   1 v. fol. cm.
LC Call No.:   QA49.A4
Control No.:   7203874

Author:        Ayars, Robert S., [from old catalog] comp.
Title:         The lightning multiplier.
Published:     Louisville, Ky., J. P. Morton & company, printers
                  [c1888]
Description:   [5] p. 36 x 27 cm.
LC Call No.:   QA49.A97
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   6795052

Author:        Burroughs Corporation.
Title:         Table of reciprocals of numbers from 1 to 10000,
                  arranged especially for the convenience of operators of the
                  Burroughs calculator ...
Published:     [Detroit, Burroughs adding machine company,
                  c1918]
Description:   1 p. l., 5-31, [1] p. 29 cm.
LC Call No.:   QA49.B96
Subjects:      Reciprocals.
               Calculators.
Control No.:   9185704

Author:        Byrne, Oliver.
Title:         The calculator's constant companion, for
                  practical men, machinist, mechanics, and engineers. By Oliver
                  Byrne ...
Published:     Philadelphia, J.W. Moore, 1854.
LC Call No.:   QA49.B99

Author:        Camp, S. R. P. [from old catalog]
Title:         Computer.
Published:     [n. p., 1882]
Description:   1 v. cm.
LC Call No.:   QA49.C18
Control No.:   9070560

Author:        Christensen, George Andrew.
Title:         Products or dividends, by George Andrew
                  Christensen.
Published:     Oakland, Cal. [R.S. Kitchener] 1907.
Description:   [213] p. 14 cm.
LC Call No.:   QA49.C6
Subjects:      Multiplication -- Tables.
Control No.:   745201


Author:        Christensen, George Andrew. [from old catalog]
Title:         Products or dividends,
Published:     Oakland, Cal., 1907.
Description:   [182] p. 15 x 16 cm.
LC Call No.:   QA49.C6 1907a
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   6832248

Author:        Corbin, I[saiah] H. [from old catalog]
Title:         Complete excelsior chart of the law of numbers.
Published:     [Eaton Rapids, Mich.] c1893.
Description:   cover-title, [23] p. incl. tables. 24 cm.
LC Call No.:   QA49.C83
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   10073399

Author:        Crelle, A. L. (August Leopold), 1780-1855.
Uniform Title: Rechentafeln. English
Title:         Dr. A. L. Crelle's calculating tables giving the
                  products of every two numbers from one to one thousand and
                  their application to the multiplication and division of all
                  numbers above one thousand.
Edition:       New ed., by O. Seeliger. With tables of the
                  square-numbers and cube-numbers from 1-1000.
Published:     Berlin, G. Reimer, 1908.
Description:   vii, [501] p. 40 cm.
LC Call No.:   QA49.C94 1908
Subjects:      Multiplication -- Tables.
Other authors: Seeliger, O. (Oskar)
Control No.:   1217871

Author:        Crelle, A. L. (August Leopold), 1780-1855.
Title:         Dr. A. L. Crelle's rechentafeln, welche alles
                  multipliciren und dividiren mit zahlen unter tausend ganz
                  ersparen, bei grösseren zahlen aber die rechnung erleichtern
                  und sicherer machen. Mit einem vorworte von dr. C. Bremiker.
Edition:       6. stereotyp-ausg.
Published:     Berlin, G. Reimer, 1891.
Description:   2 p. l., [iii]-x, [452] p. 33 cm.
LC Call No.:   QA49.C92 1891
Notes:         Added t.-p. in French; pref. in German and
                  French.
Subjects:      Multiplication -- Tables.
Other authors: Bremiker, Karl, 1804-1879.
Control No.:   8235006

Author:        Crelle, A. L. (August Leopold), 1780-1855.
Title:         Rechentafeln, welche alles Multiplizieren und
                  Dividieren mit Zahlen unter Tausend ganz ersparen, bei
                  grösseren Zahlen aber die Rechnung erleichtern und sicherer
                  machen.
Edition:       Neue Ausg., besorgt von O. Seeliger. Neudruck,
                  mit Tafeln der Quadrant- und Kubikzahlen von 1-1000.
Published:     Berlin, W. de Gruyter, 1944.
Description:   vii p., tables. 38 cm.
LC Call No.:   QA49.C92 1944
Dewey No.:     511.9 [510.83]
Subjects:      Multiplication -- Tables.
Control No.:   10228779

Author:        Crelle, A. L. (August Leopold), 1780-1855.
Uniform Title: Rechentafeln. French
Title:         Tables de calcul ou se trouvent les
                  multiplications et divisions toutes faites de tous les
                  nombres au dessous de mille et qui facilitent et assurent le
                  calcul, par A.L. Crelle.
Edition:       Photolithographic reprint.
Published:     Washington, United States Geological survey,
                  1918.
Description:   [456] p. incl. tables. 31 cm.
LC Call No.:   QA49.C945
Notes:         At head of title: Department of the interior ...
                  United States geological survey ...
Subjects:      Multiplication -- Tables.
Other authors: Geological Survey (U.S.)
Control No.:   1218084

Author:        Crelle, August Leopold, 1780-1855. [from old
                  catalog]
Title:         Dr. A. L. Crelle's calculating tables,
Edition:       3d English ed.
Published:     New York, G. E. Stechert & co.; 1906.
Description:   vii p., 2 l., [iii]-x, [452] p. 34 cm.
LC Call No.:   QA49.C94 1906
Subjects:      Multiplication -- Tables. [from old catalog]
Other authors: Bremiker, Karl, 1804-1877, [from old catalog]
                  ed.
Control No.:   9692816

Author:        Crelle, A[ugust] L[eopold], 1780-1855. [from old
                  catalog]
Title:         Dr. A. L. Crelle's rechentafeln,
Published:     Berlin, G. Reimer, 1875.
Description:   1 p. l., x, [450] p. 33 cm.
LC Call No.:   QA49.C92
Subjects:      Multiplication -- Tables.
Other authors: Bremiker, Karl, 1804-1877, [from old catalog]
                  ed.
Control No.:   8199515

Author:        Crelle, August Leopold, 1780-1855. [from old
                  catalog]
Title:         Dr. A. L. Crelle's rechentafeln welche alles
                  multipliciren und dividiren mit zahlen unter tausend ganz
                  ersparen,
Published:     Berlin, G. Reimer, 1857.
Description:   1 p. l., x, [450] p. 37 cm.
LC Call No.:   QA49.C91
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   8196420

Author:        Crowgey, Robert. [from old catalog]
Title:         Crowgey's Universal calculator,
Published:     London, Printed for the author and pub. by J.
                  Richardson, 1827.
Description:   2 p. l., lviii, [2], 487, 3, [489]-491, [5] p. 25
                  cm.
LC Call No.:   QA49.C95
Subjects:      Mathematics -- Tables.
Control No.:   6834679

Author:        Deavenport fractional calculator co.,
                  incorporated, Okolona, Miss. [from old catalog]
Title:         Just what you want--Deavenport's fractional
                  calculator,
Published:     Okolona, Miss., The Deavenport fractional
                  calculator co. [c1901]
Description:   2 p.l., 196 p. of tables. 23 x 13 cm.
LC Call No.:   QA49.D28
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   6796864

Author:        Delbridge, Charles Lomax.
Title:         Delbridge's multiplication table, showing the
                  result of the multiplication of any number from 1 to 200,000
                  by any number from 1-8th of 1, to 100 ... By Charles Lomax
                  Delbridge ...
Published:     St. Louis, Mo., The Delbridge company, c1916.
Description:   [116] p. 34 cm.
LC Call No.:   QA49.D4
ISBN:          $5.00
Subjects:      Multiplication -- Tables.
               Ready-reckoners.
Control No.:   1690040

Author:        Delbridge, Charles Lomax. [from old catalog]
Title:         Delbridge pocket size calculator for
                  multiplication.
Published:     St. Louis, Mo., The Delbridge company, c1921.
Description:   [102] p. 18 cm.
LC Call No.:   QA49.D3
Subjects:      Multiplication -- Tables. [from old catalog]
               Ready-reckoners. [from old catalog]
Control No.:   9191886

Author:        Greene, Charles W.
Title:         The ready multiplier / by Charles W. Greene.
Published:     Boston : O.C. Greenleaf ... , 1833.
Description:   [iii]-x, [11]-29 p. ; 14 cm.
LC Call No.:   QA49.G79
Notes:         NUC pre-1956, 216:668
               Shoemaker 19103
Subjects:      Multiplication -- Tables.
Control No.:   9605112

Author:        Hall, John L. (John Lincoln).
Title:         Tables of squares : Containing the true square of
                  every foot and fraction thereof, from 0 to 100 feet,
                  advancing by one-sixteenth of an inch : also, the square of
                  each sixty-fourth of an inch up to one foot, and two
                  convenient tables of the decimal parts of a foot / by John L.
                  Hall.
Edition:       2d ed.
Published:     New York : Engineering News, 1901.
Description:   xi, [207] p. ; 9x15 cm.
LC Call No.:   QA49.H17
Subjects:      Squares, Tables of.
Control No.:   10065823

Author:        Hall, John L. (John Lincoln)
Title:         Tables of squares : containing the true square of
                  every foot and fraction thereof from 0 to 100 feet advancing
                  by one-sixteenth of an inch / by John L. Hall.
Published:     New York : Engineering News Pub. Co., 1899.
Description:   99 [i.e. 200] p. ; 15 cm.
LC Call No.:   QA49.H34x 1899
Subjects:      Squares, Tables of.
Control No.:   3346261

Author:        Hauff, W. A. [from old catalog]
Title:         Office arithmetic in tables.
Published:     [New York, W. A. Hauff, c1889]
Description:   1 p.l., 17 p. 17 cm.
LC Call No.:   QA49.H36
Subjects:      Mathematics -- Tables.
Control No.:   5859011

Author:        Hauff, W. A. [from old catalog]
Title:         Pocket-book of arithmetic tables.
Published:     [New York, W. A. Hauff, c1889]
Description:   33 p. 9 x 12 cm.
LC Call No.:   QA49.H362
Subjects:      Mathematics -- Tables.
Control No.:   7263422

Author:        Hedrick, Henry Benjamin, 1865-1936.
Title:         Interpolation tables; or, Multiplication tables
                  of decimal fractions, giving the products to the nearest unit
                  of all numbers from 1 to 100 by 0.01 to 0.99 and from 1 to
                  1000 by 0.001 to 0.999, by Henry B. Hedrick, PH. D.
Published:     Washington, Carnegie Institution of Washington
                  1918.
Description:   ix, 139 p. 35 cm.
Series:        Carnegie Institution of Washington. Publication,
                  no. 245
LC Call No.:   QA49.H4
Subjects:      Multiplication -- Tables.
               Decimal fractions.
Control No.:   7311685

Author:        Hinkley, Edward, 1791-1854.
Title:         New methods for multiplication and division with
                  ease, accuracy and despatch, by means of a table of nine
                  hundred and ninety-nine multiples of the nine digits, to
                  which are annexed other useful tables. By Edward Hinkley.
Published:     Baltimore, Printed for the author, 1853.
Description:   vi, 7-71 p. 27 cm.
LC Call No.:   QA49.H65
Subjects:      Mathematics -- Tables.
Control No.:   6795051

Author:        Hof, Hans, 1901-
Title:         Powers, roots, reciprocals from .0001-1.0000 / by
                  Hans Hof.
Edition:       1st ed.
Published:     [Jenkintown, Pa. : Professional Supply Company,
                  c1957]
Description:   ca. 250 p. 26 cm.
LC Call No.:   QA49.H69
Notes:         Tables.
Subjects:      Roots, Numerical.
               Reciprocals.
               Mathematics -- Tables.
Control No.:   9343820

Author:        Hof, Hans, 1901-
Title:         Powers, roots, reciprocals from 1-15000 / by Hans
                  Hof.
Published:     [Jenkintown, Pa. : Professional Supply Company,
                  c1956]
LC Call No.:   QA49.H68

Author:        Hof, Hans, 1901-
Title:         Powers, roots, reciprocals from 1-15000 / by Hans
                  Hof.
Edition:       1st ed.
Published:     [Jenkintown, Pa. : Professional Supply Company,
                  c1956]
Description:   ca. 300 p. 26 cm.
LC Call No.:   QA49.H68
Notes:         Tables.
Subjects:      Roots, Numerical.
               Reciprocals.
               Mathematics -- Tables.
Control No.:   7466140

Author:        Kent, WIlliam St. G. [from old catalog]
Title:         Some properties and tables of the one quarter
                  squares of numbers.
Published:     Phillipsburg, N.J., 1876.
Description:   [10] l. 31 cm.
LC Call No.:   QA49.K37
Subjects:      Squares, Tables of. [from old catalog]
Control No.:   8684097

Author:        Kühtmann, Gerhard. [from old catalog]
Title:         Kühtmanns rechentafeln, ein handliches
                  zahlenwerk mit zwei millionen lösungen die alles
                  multiplizieren und dividieren ersparen und selbst die
                  grössten rechnungen dieser art in wenige additions- oder
                  subtraktionzahlen auflösen,
Published:     Dresden, G. Kühtmann, 1910.
Description:   15, [460] p. 24 cm.
LC Call No.:   QA49.K8
Subjects:      Mathematics -- Tables.
Control No.:   6350751

Author:        Kummell, Charles H. [from old catalog]
Title:         Table of squares for all numbers up to 10,000,
                  for the use of astronomers, civil engineers, and
                  mathematicians in general,
Published:     Detroit, Mich., C. H. Kummell [c1873]
Description:   fold. tab. 20 cm.
LC Call No.:   QA49.K96
Subjects:      Squares, Tables of. [from old catalog]
Control No.:   8671075

Author:        Laffaille, J. (Jules), b. 1841.
Title:         Carrétique : branche nouvelle des mathématiques
                  : solutions difficultueuses effectuées au moyen des carrés
                  des nombres / par J. Laffaille.
Published:     Montrouge (Seine) : Laffaille, 1908.
Description:   iv, 43 p. ; 23 cm.
LC Call No.:   QA49.L33x 1908
Subjects:      Squares, Tables of.
Control No.:   3818757

Author:        McLane, George A. [from old catalog]
Title:         A new system of extended multiplication tables,
Published:     Chicago, J. G. Spalding & co., printers [c1875]
Description:   [7] p. 32 x 20 cm.
LC Call No.:   QA49.M16
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   9605113

Author:        Meech, Levi W. (Levi Witter)
Title:         Economy in mathematics. New calculation tables
                  for multiplication and division. Also a table of roots and
                  powers. By Levi W. Meech ...
Published:     Norwich, Conn., H. Bill publishing company,
                  1894.
Description:   xiv, [896] p. 23 x 27 cm.
LC Call No.:   QA49.M49
Subjects:      Multiplication -- Tables.
Control No.:   744860

Author:        Oakes, W. H. (William Henry)
Title:         Table of the reciprocals of numbers from 1 to
                  100,000, with their differences, by which the reciprocals of
                  numbers may be obtained up to 10,000,000. By Lieut.-Col. W.H.
                  Oakes, A.I.A.
Published:     London, C. & E. Layton [1865]
Description:   xii, 205 p. 26 cm.
LC Call No.:   QA49.O3
Subjects:      Reciprocals.
Control No.:   4525928

Author:        Pugsley, R. M. (Richard Marriotte), 1866-1918.
Title:         Pugsley's multiplication table for the student,
                  specially and conveniently arranged for practical use,
                  products to 14400, by R.M. Pugsley ...
Published:     New York, R.M. Pugsley, c1917.
Description:   [47] p. 19 cm.
LC Call No.:   QA49.P8
ISBN:          $1.00
Subjects:      Multiplication -- Tables.
               Ready-reckoners.
Control No.:   2162098

Author:        Robinson, J. Watts (James Watts), 1827-1918.
Title:         Robinsonian multiplication and division tables.
                  Giving, at sight, the products of all numbers from 1 to 100
                  and of all the halves, quarters, eighths, sixteenths, one
                  twelfth and one thirty-second, by all the numbers from 1 to
                  1000 ... by J. Watts Robinson ...
Edition:       [2d ed.].
Published:     [New Orleans] J.W. Robinson, 1912.
Description:   [108] p. 40 x 16 cm.
LC Call No.:   QA49.R66 1912
ISBN:          $3.00
Subjects:      Multiplication -- Tables.
Control No.:   3580096

Author:        Robinson, J[ames], Watts. [from old catalog]
Title:         Robinson multiplication and division tables.
Published:     [New Orleans, J. W. Robinson] 1891.
Description:   [106] p. 41 x 15 cm.
LC Call No.:   QA49.R66
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   10073400

Author:        Rochester bridge & iron works, Rochester, N.Y.
                  [from old catalog]
Title:         Table of squares from 1 to 10001.
Published:     [Rochester, N.Y., 1893]
Description:   2 p.l., 50 numb. l. 26 cm.
LC Call No.:   QA49.R69
               Microfilm 41411 QA
Subjects:      Squares, Tables of. [from old catalog]
Other authors: Alden, John F. [from old catalog]
Control No.:   8202923

Author:        Smith, J[ohn] C. [from old catalog]
Title:         Smith's ready reckoner:
Published:     Cincinnati, C. F. Bradley & co., 1853.
Description:   1 p.l., 33 p., 1 l. tab. 18 cm.
LC Call No.:   QA49.S75
Subjects:      Ready reckoners. [from old catalog]
Control No.:   8198192

Author:        United States. National Bureau of Standards.
                  Computation Laboratory.
Title:         Table of the first ten powers of the integers
                  from 1 to 1000 ... December 1, 1938.
Published:     [New York, 1939]
Description:   1 p.l., ii, ii, 80, [2] p. 35 cm.
LC Call No.:   QA49.U6 1939
Dewey No.:     511.9
Notes:         On cover: ... Project for the computation of
                  mathematical tables.
               Each section and introduction preceded by
                  half-title not included in the paging.
               Mimeographed.
               "Prepared by the 'Project for the computation of
                  mathematical tables' sponsored by Dr. Lyman J. Briggs,
                  director of the National bureau of standards, Washington,
                  D.C., and under the auspices of the U.S. Works progress
                  administration of New York city."--Pref.
Subjects:      Multiplication -- Tables.
Control No.:   1691249

Author:        Varian, E. B. (Everett Brown), 1865-
Title:         Varian's commercial multiplication tables, for
                  merchants, book-keepers, time-keepers, bill-clerks, cashiers
                  and sales-people, and for all calculations in multiplication
                  requiring speed and accuracy ...
Published:     Los Angeles, Cal., E.B. Varian [c1916]
Description:   2 p.l., [314] p. 28 cm.
LC Call No.:   QA49.V3
ISBN:          $5.00
Subjects:      Multiplication -- Tables.
               Ready-reckoners.
Control No.:   3580310

Author:        Williams, William Wendell. [from old catalog]
Title:         Multiplication tables of 11 to 30 through 1000,
                  including interpolation tables for division.
Published:     [Columbus, Ohio, c1951]
Description:   iii, 43 p. 23 cm.
LC Call No.:   QA49.W5
Subjects:      Multiplication -- Tables. [from old catalog]
Control No.:   6028815

Author:        Baker, C. L. [from old catalog]
Title:         The first six million prime numbers
Published:     Madison, Wis., Published by the Microcard
                  Foundation, [for] the RAND Corp., Santa Monica, Calif.,
                  1959.
Description:   8 p. 23 cm. and 62 cards (8 x 13 cm.)
LC Call No.:   QA51.B3
Subjects:      Numbers, Prime. [from old catalog]
Other authors: Gruenberger, Fred Joseph, 1918- [from old
                  catalog] joint author.
Control No.:   9353443

Author:        Baker, C. L. [from old catalog]
Title:         The first six million prime numbers [by] C. L.
                  Baker and F. J. Gruenberger.
Published:     Madison, Wis., Published by the Microcard
                  Foundation [for] the RAND Corp., Santa Monica, Calif., 1959.
Description:   8 p. 23 cm.
LC Call No.:   QA51.B3
Notes:         62 microprint cards (8 x 13) in pocket.
Subjects:      Numbers, Prime. [from old catalog]
Other authors: Gruenberger, Fred Joseph, 1918-     [from old
                  catalog] joint author.
Control No.:   9353444

Author:        Burckhardt, J. Ch., 1773-1825.
Title:         Table des diviseurs pour tous les nombres du
                  deuxième million, ou plus exactement, depuis 1020000 à
                  2028000, avec les nombres premiers qui s'y trouvent; par J.
                  Ch. Burckhardt.
Published:     Paris, Mme Ve Courcier, 1814.
Description:   viii, 112 p. 32 x 25 cm.
LC Call No.:   QA51.B94
Notes:         Bound with his Tables des diviseurs pour tous les
                  nombres du premier million. Paris, 1817.
Subjects:      Factor tables.
               Numbers, Prime.
Control No.:   9135053

Author:        Burckhardt, J. Ch., 1773-1825.
Title:         Table des diviseurs pour tous les nombres du
                  premier million, ou plus exactement, depuis 1 à 1020000,
                  avec les nombres premiers qui s'y trouvent; par J. Ch.
                  Burckhardt ...
Published:     Paris, Mme Ve Courcier, 1817.
Description:   4 p.l., 114 p. 32 x 25 cm.
LC Call No.:   QA51.B94
Subjects:      Factor tables.
               Numbers, Prime.
Control No.:   272572

Author:        Burckhardt, J[ohann] K[arl], 1773-1825. [from old
                  catalog]
Title:         Table des diviseurs pour tous los nombres du
                  troisième million,
Published:     Paris, Mme Ve Courcier, 1816.
Description:   2 p.l., 112 p. 32 x 25 cm.
LC Call No.:   QA51.B94
Subjects:      Factor tables. [from old catalog]
               Numbers, Prime. [from old catalog]
Control No.:   7261848

Author:        Dase, Zacharias, 1824-1861. [from old catalog]
Title:         Factoren-tafeln für alle zahlen der neunten
                  million,
Published:     Hamburg, Perthes-Besser & Mauke, 1865.
Description:   2 p. l., 225-334 p. 34 cm.
LC Call No.:   QA51.D22
Subjects:      Factor tables. [from old catalog]
               Numbers, Prime. [from old catalog]
Other authors: Rosenberg, H. [from old catalog]
Control No.:   7263571

Author:        Dase, Zacharias, 1824-1861. [from old catalog]
Title:         Factoren-tafeln für alle zahlen der siebenten
                  millon,
Published:     Hamburg, Perthes-Besser & Mauke, 1862.
Description:   3 p. l., 112 p. 34 cm.
LC Call No.:   QA51.D21
Subjects:      Factor tables. [from old catalog]
               Numbers, Prime. [from old catalog]
Control No.:   8673650

Author:        Douthat, Robert William, 1840-
Title:         A new method of obtaining all possible prime
                  numbers from one to infinity and of distinguishing absolute
                  from apparent primes, no matter how large; and as a corollary
                  to this method, the almost automatic production ad infinitum
                  of all quotients and divisors of apparent primes; and a
                  method of avoiding "long division" as well as of securing the
                  square and square roots of all odd numbers. By Robert Wm.
                  Douthat ...
Published:     [Morgantown? W. Va., c1904]
Description:   1 p.l., iii, [1], 56, 153 p. 20 cm.
LC Call No.:   QA51.D74
Notes:         "The tables for primes and apparent primes" (153
                  p.)
Subjects:      Numbers, Prime.
Control No.:   2634174

Author:        Glaisher, James, 1809-1903.
Title:         Factor table for the fifth million, containing
                  the least factor of every number not divisible by 2, 3, or 5
                  between 4,000,000 and 5,000,000. By James Glaisher, F.R.S.
Published:     London, Taylor and Francis, 1880.
Description:   1 p.l., 11, 112 p. tables. 32 x 26 cm.
LC Call No.:   QA51.G54
Subjects:      Factor tables.
               Numbers, Prime.
Control No.:   4052176

Author:        Glaisher, James, 1809-1903.
Title:         Factor table for the fourth million, containing
                  the least factor of every number not divisible by 2, 3, or 5
                  between 3,000,000 and 4,000,000. By James Glaisher, F.R.S.
Published:     London, Taylor and Francis, 1879.
Description:   52 p., 1 l., 112 p. tables, 2 diagr. (1 fold.) 32
                  x 26 cm.
LC Call No.:   QA51.G53
Notes:         The introduction contains a full description of
                  the mode of construction of the table and a historical
                  account relating to factor tables and to the distribution of
                  primes.
               "List of writings on the distribution of prime
                  numbers (including writings on factor tables, but not factor
                  tables themselves)": Introd., p. 36-38.
Subjects:      Factor tables.
               Numbers, Prime.
Control No.:   744798

Author:        Glaisher, James, 1809-1903.
Title:         Factor table for the sixth million,
Published:     London, Taylor and Francis, 1883.
Description:   103 p., 1 l., 112 p. tables, 1 diagr. 32 x 26
                  cm.
LC Call No.:   QA51.G55
Subjects:      Factor tables. [from old catalog]
               Numbers, Prime. [from old catalog]
Control No.:   6792976

Author:        Hinkley, Edward, 1791-1854.
Title:         Tables of the prime numbers, and prime factors of
                  composite numbers, from 1 to 100,000 : with the methods of
                  their construction, and examples of their use / by Edward
                  Hinkley.
Published:     Baltimore : Printed for the author, 1853.
Description:   216 p. : ill. ; 23 cm.
LC Call No.:   QA51.H66
Notes:         "An appendix to the English translation of
                  Rhonius's German treatise of algebra, made by Mr. Thomas
                  Brancker, M.A. and published by him, with the advice and
                  assistance of Dr. John Pell, at London, in the year 1668;
                  containing a table of odd numbers less than one hundred
                  thousand...;"p. [165]-205.
               "A brief notice of some authors and tables": p.
                  209-212.
Subjects:      Factor tables.
               Numbers, Prime.
Other authors: Brancker, Thomas, 1633-1676.
Control No.:   7264721

Author:        Jacobi, C. G. J. (Carl Gustav Jakob), 1804-1851.
Title:         Canon arithmeticus sive tabulae quibus exhibentur
                  pro singulis numeris primis vel primorum potestatibus infra
                  1000 numeri ad datos indices et indices ad datos numeros
                  pertinentes. Impensis Academiae litterarum regiae borussicae.
                  Edidit C.G.J. Jacobi ...
Published:     Berolini, typis academicis, 1839.
Description:   xl, 248 p. 28 x 21 cm.
LC Call No.:   QA51.J16
Subjects:      Congruences and residues.
Other authors: Deutsche Akademie der Wissenschaften zu Berlin.
Control No.:   2633977

Author:        Lehmer, Derrick Norman, 1868-1938.
Title:         Factor table for the first ten millions
                  containing the smallest factor of every number not divisible
                  by 2, 3, 5, or 7 between the limits 0 and 10,017,000
Published:     New York, Hafner Pub. Co., 1956.
Description:   xiv columns, 476 p. 32 x 43 cm.
Series:        Carnegie Institution of Washington. Publication,
                  no. 105
LC Call No.:   QA51.L5 1956
Dewey No.:     510.835
Subjects:      Factor tables.
               Numbers, Prime.
Control No.:   6995000

Author:        Lehmer, Derrick Norman, 1868-1938.
Title:         List of prime numbers from 1 to 10,006,721.
Published:     New York, Hafner Pub. Co., 1956.
Description:   xvi columns, 133 p. 32 x 43 cm.
Series:        Carnegie Institution of Washington. Publication
                  no. 165
LC Call No.:   QA51.L6 1956
Subjects:      Numbers, Prime.
Control No.:   6526651

Author:        Lehmer, Derrick Norman, 1868-1938.
Title:         List of prime numbers from 1 to 10,006,721, by
                  Derrick Norman Lehmer.
Published:     Washington, D.C., Carnegie institution of
                  Washington, 1914.
Description:   1 p.l., xvi col., 133 p. 32 x 44 cm.
Series:        Carnegie institution of Washington. Publication
                  no. 165
LC Call No.:   QA51.L6
Subjects:      Numbers, Prime.
Series Entry:  Carnegie Institution of Washington publication ;
                  165.
Control No.:   4526136

Author:        Lehmer, Derrick Norman, 1868- [from old catalog]
Title:         Factor table for the first ten millions
                  containing the smallest factor for every number not divisible
                  by 2, 3, 5, or 7 between the limits and 10017000,
Published:     Washington, D.C., Carnegie institution of
                  Washington, 1909.
Description:   1 p. l., xiv, [4] col., 0-476 p. 32 x 45 cm.
LC Call No.:   QA51.L5
Subjects:      Factor tables. [from old catalog]
               Numbers, Prime. [from old catalog]
Control No.:   8691419

Author:        Stager, Henry Walter, b. 1879.
Title:         A Sylow factor table of the first twelve thousand
                  numbers, giving the possible number of Sylow sub-groups of a
                  group of given order between the limits of 0 and 12000, by
                  Henry Walter Stager.
Published:     Washington, D.C., Carnegie institution of
                  Washington, 1916.
Description:   xii, 120 p. fold. diagr. 24 x 31 cm.
Series:        Carnegie institution of Washington. Publication
                  no. 151
LC Call No.:   QA51.S8
Subjects:      Factor tables.
Series Entry:  Carnegie Institution of Washington publication ;
                  151.
Control No.:   745733

Author:        University of Oklahoma. Dept. of Mathematics and
                  Astronomy.
Title:         A table of indices and power residues for all
                  primes and prime powers below 2000. Computed by the
                  University of Oklahoma mathematical tables project under the
                  direction of Richard V. Andree. Introd. by H.S. Vandiver.
Published:     New York, Norton [1962]
Description:   1 v. 23 cm.
LC Call No.:   QA51.O55
Notes:         Includes bibliography.
Subjects:      Factor tables.
Other authors: Andree, Richard Vernon, 1919-
Control No.:   7033528

Author:        Vollprecht, Hugo, 1855- [from old catalog]
Title:         Über die herstellung von faktorentafeln ...
Published:     Bautzen, Druck von E. M. Monse, 1891.
Description:   16, vii p. tables. 36 x 29 cm.
LC Call No.:   QA51.V9
Subjects:      Factor tables. [from old catalog]
Control No.:   9134484

Author:        Hull, George W[ashington] [from old catalog]
Title:         A complete algebra ...
Published:     Philadelphia, E. H. Butler & co. [c1895]
Description:   309 p. 20 cm.
LC Call No.:   QA52.H915
Subjects:      Algebra.
Control No.:   10069652

Author:        Hachette, Jean Nicolas Pierre, 1769-1834. [from
                  old catalog]
Title:         Éléments de géométrie à trois dimensions
                  ...
Published:     Paris, F. Didot, 1817.
Description:   2 v. in 1. diagr. on 5 pl. 21 cm.
LC Call No.:   QA53.H1
Subjects:      Surfaces. [from old catalog]
               Geometry, Analytic -- Solid. [from old catalog]
Control No.:   8196692

Author:        Schaaf, William Leonard, 1898-
Title:         Trigonometry for home study [by] William L.
                  Schaaf ...
Published:     Philadelphia, The Blakiston company [1945]
Description:   xii, 404 p. diagrs. 21 cm.
LC Call No.:   QA53.S37
Dewey No.:     514
Notes:         "Answers and solutions.": p. 371-402.
Subjects:      Trigonometry.
Control No.:   8337030

Author:        Atkinson, William, 1866- [from old catalog]
Title:         The mystery of logarithms,
Published:     Topsfield, Mass., The Perkins press, 1940.
Description:   31 p. incl. tables. 24 cm.
LC Call No.:   QA59.A8
Subjects:      Logarithms. [from old catalog]
Control No.:   7377983

Author:        Banhagel, Edward W.
Title:         Logarithms and slide rule for practical use, by
                  E.W. Banhagel...
Published:     New York, Ziff-Davis publishing company [1945]
Description:    vii, 141p. illus., diagrs. 24 cm.
LC Call No.:   QA59.B3
Dewey No.:     510.83
Notes:         "Answers to problems": p. 137-139.
Subjects:      Logarithms.
               Slide-rule.
Control No.:   5996776

Author:        Bradbury, William F. (William Frothingham),
                  1829-1914.
Title:         Logarithms of numbers, with tables to four
                  places, from Bradbury's Elementary algebra.
Published:     Boston, Thompson, Brown & company, c1875.
Description:   253-269 p. 19 cm.
LC Call No.:   QA59.B77
Subjects:      Logarithms.
Control No.:   9610827

Author:        Briggs, Henry, 1561-1630.
Title:         Arithmetica logarithmica,
Edition:       Ed. 2.,
Published:     Gordae, excudebat P. Rammasenius, 1628.
Description:   p. cm.
LC Call No.:   QA59.B78 1628 (Rare Bk Coll)
Subjects:      Logarithms -- Early works to 1800.
Other authors: Vlacq, Adriaan. [from old catalog]
Control No.:   9136172

Author:        Burritt, Elijah Hinsdale. [from old catalog]
Title:         Logarithmick arithmetick,
Published:     Williamsburgh [Mass.] Printed by E. Whitman,
                  1818.
Description:   1 p.l., 251, [1] p. incl. tables. diagrs. on 1
                  fold. pl. 21 cm.
LC Call No.:   QA59.B8 (Office)
Subjects:      Logarithms. [from old catalog]
               Arithmetic -- Early works to 1900.
               Eclipses. [from old catalog]
Control No.:   7264522

Author:        Byrne, Oliver. [from old catalog]
Title:         Practical, short and direct method of calculating
                  the logarithm of any given number, and the number
                  corresponding to any given logarithm.
Published:     London, Simpkin, Marshall & co.; New York, D.
                  Appleton & co., 1849.
Description:   xxiii, [13]-82 p. incl. tables. 20 cm.
LC Call No.:   QA59.B9
Subjects:      Logarithms. [from old catalog]
Control No.:   9137682

Author:        Card, Ernest.
Title:         Logarithms simplified for the use of students in
                  all branches of elementary mathematics and in connection with
                  commercial and technical examinations, by Ernest Card and A.
                  C. Parkinson.
Edition:       2d ed.
Published:     London, New York [etc.] Sir I. Pitman & sons,
                  ltd., 1931.
Description:   vii, 77 p. 19 cm.
LC Call No.:   QA59.C3 1931
Dewey No.:     510.835
Subjects:      Logarithms.
Other authors: Parkinson, Albert Charles, joint author.
Control No.:   7353315

Author:        Carson, Albert B. (Albert Bertie), 1908-
Title:         Logarithms simplified.
Published:     Chicago, American Technical Society, 1949.
Description:   165 p. illus. 22 cm.
LC Call No.:   QA59.C33
Dewey No.:     510.83
Subjects:      Logarithms.
Control No.:   6955858

Author:        Chanin, W. [from old catalog]
Title:         Logarithms in commerce with section on annuities
                  and hire-purchase interest,
Published:     London, New York [etc.] Sir I. Pitman & sons,
                  ltd., 1931.
Description:   ix, 70 p. 19 cm.
LC Call No.:   QA59.C5
Subjects:      Logarithms. [from old catalog]
               Annuities. [from old catalog]
               Interest.
Control No.:   9223564

Author:        Compton, Alfred G. (Alfred George), 1835-1913.
Title:         A manual of logarithmic computation, with
                  numerous examples.
Published:     New York, J. Wiley & sons, 1881.
Description:   ix, 142 p. diagr. 20 cm.
LC Call No.:   QA59.C7
Subjects:      Logarithms. [from old catalog]
Control No.:   6327007

Author:        Hill, Nathaniel. [from old catalog]
Title:         Having the logarithms of two numbers, to find the
                  logarithm of their sum or difference.
Published:     [Philadelphia, 1895]
Description:   5 p. 23 cm.
LC Call No.:   QA59.H6
Subjects:      Logarithms. [from old catalog]
Control No.:   5860080

Author:        Hite, Melville P. [from old catalog]
Title:         Logarithms & exponents, reduced to arithmetic,
Published:     Jacksonville, Fla., Technical press [1942]
Description:   48 p. diagrs. 22 cm.
LC Call No.:   QA59.H65 1942
Subjects:      Logarithms. [from old catalog]
Control No.:   6922016

Author:        Hite, Melville P. [from old catalog]
Title:         Logarithms and exponents, reduced to arithmetic,
Published:     Jacksonville, Fla., Technical press, c1940.
Description:   1, 14 p., 4 numb. l. 28 x 22 cm.
LC Call No.:   QA59.H65 1940
Control No.:   7671615

Author:        Hite, Melville P. [from old catalog]
Title:         Logarithms and exponents reduced to arithmetic, a
                  manual for practical use,
Published:     [Jacksonville, Fla.] c1939.
Description:   12, L1-L 4 numb. l. 29 x 22 cm.
LC Call No.:   QA59.H65 1939
Subjects:      Logarithms. [from old catalog]
Control No.:   9734347

Author:        Huntington, E. V. (Edward Vermilye), 1874-1952.
Title:         How to use a table of logarithms, by E.V.
                  Huntington.
Edition:       2d ed., enl. ...
Published:     Cambridge, Mass., The Harvard coöperative
                  society, c1912.
Description:   3 p.l., 12 p. tables. 23 cm.
LC Call No.:   QA59.H8
ISBN:          $0.20
Notes:         Cover title
Subjects:      Logarithms.
Control No.:   3580111

Author:        International correspondence schools. [from old
                  catalog]
Title:         Instruction paper- Logarithms.
Edition:       4th ed.
Published:     [n. p.] [1898]
Description:   1 v. cm.
LC Call No.:   QA59.I6
Control No.:   8607369

Author:        International correspondence schools. [from old
                  catalog]
Title:         Instruction paper- Logarithms.
Edition:       3d ed.
Published:     [n. p.] [1898]
Description:   1 v. cm.
LC Call No.:   QA59.I6
Control No.:   9075730

Author:        International correspondence schools, Scranton,
                  Pa. [from old catalog]
Title:         Logarithms, prepared especially for home study
Published:     [Scranton, 1938]
Description:   cover-title, 47 p. 19 cm.
LC Call No.:   QA59.I63
Control No.:   7203561

Author:        Isham, Ira.
Title:         Isham's method of computing logarithms; a
                  treatise developing a general method of computing an infinite
                  number of logarithms from the terms of a single series.
Published:     [Spokane, I. Isham, 1915]
Description:   11 p. 24 cm.
LC Call No.:   QA59.I8
ISBN:          $1.00
Subjects:      Logarithms.
Control No.:   2634764

Author:        Jones, John Lucien.
Title:         Logarithms are easy, by J. Lucien Jones and James
                  Bernard Jones.
Published:     [Blacksburg, 1948]
Description:   26 p. fold. tables. 24 cm.
Series:        Virginia Polytechnic Institute, Blacksburg.
                  Engineering Extension Division. Engineering extension series.
                   Bulletin no. 47
               Bulletin of the Virginia Polytechnic Institute,
                  v. 41, no. 4
LC Call No.:   QA59.J6
Dewey No.:     510.83
Subjects:      Logarithms
Other authors: Jones, James Bernard, joint author
Control No.:   9757173

Author:        Lawrence, Peter C. [from old catalog]
Title:         A tract on the higher grade of mathematics,
                  disclosing the theory, principal construction, philosophy and
                  practice of logarithms, thoroughly demonstrated and
                  illustrated by theoretical and practical examples, for the
                  use of common schools.
Published:     Charleston, S.C., Republican book and job office,
                  1870.
Description:   14 p. 23 cm.
LC Call No.:   QA59.L4
Subjects:      Logarithms. [from old catalog]
Control No.:   8201300

Author:        Little, James. [from old catalog]
Title:         An explanation of the nature and properties of
                  logarithms,
Published:     Dublin, R. Graisberry, 1830.
Description:   254 p. 22 cm.
LC Call No.:   QA59.L7
Subjects:      Logarithms. [from old catalog]
               Maguire, James. Of the measure of ratios. [from
                  old catalog]
Control No.:   7732619

Author:        Martin, Artemas, 1835- [from old catalog]
Title:         A method of finding, without tables, the number
                  corresponding to a given logarithm.
Published:     Washington, D.C., The author, 1897.
Description:   1 p.l., 237-240 p. 31 x 25 cm.
LC Call No.:   QA59.M38
Subjects:      Logarithms. [from old catalog]
Control No.:   8673782

Author:        Maseres, Francis, 1731-1824.
Title:         Scriptores logarithmici : or, A collection of
                  several curious tracts on the nature and construction of
                  logarithms, mentioned in Dr. Hutton's historical introduction
                  to his new edition of Sherwin's Mathematical tables :
                  together with some tracts on the binomial theorem and other
                  subjects connected with the doctrine of logarithms / [Francis
                  Maseres pref.]
Published:     London : Printed by J. Davis, and sold by B.
                  White and son, 1791-1807.
Description:   6 v. : ill., port. ; 27x22 cm.
LC Call No.:   QA59.M4
Notes:         Vol. 4 has imprint : London, Printed by Davis,
                  Wilks, and Taylor, and sold by J. White ; v. 5-6 : London,
                  Printed by R. Wilks, and sold by J. White.
Subjects:      Logarithms.
               Mathematics -- Early works to 1800.
Other authors: Hutton, Charles, 1737-1823.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   10203655

Author:        Adams, George, 1750-1795.
Title:         Geometrical and graphical essays,
Edition:       4th ed.
Published:     London, Printed by C. Baldwin, 1813.
Description:   xii, 534 p. front., diagrs. and atlas of 34 fold.
                  pl. 22 cm.
LC Call No.:   QA71.A22
Subjects:      Mathematical instruments.
Other authors: Jones, William, 1763-1831.
Control No.:   8670072

Author:        Adams, George, 1750-1795.
Title:         Geometrical and graphical essays,
Edition:       3d ed.
Published:     London, Printed by W. Glendinning, 1803.
Description:   10, [6], 518 p. front., diagrs., xxxiv pl. 21
                  cm.
LC Call No.:   QA71.A21
Subjects:      Mathematical instruments.
Other authors: Jones, William, 1763-1831.
Control No.:   6328580

Author:        Brown, John, philomath. [from old catalog]
Title:         The description and vse of the carpenters-rule:
Published:     London, Prited for W. Fisher and R. Mount, 1688.
Description:   [204] p. front. 13 cm.
LC Call No.:   QA71.B7
Subjects:      Mathematical instruments. [from old catalog]
               Carpentry -- Tables, calculations, etc. [from old
                  catalog]
               Slide-rule. [from old catalog]
Other titles:  Gunters-line.
Control No.:   8255827

Author:        Davis, Edgar A. [from old catalog]
Title:         Easy math solutions charts.
Published:     [Pittsburgh] c1958.
Description:   5 pieces (in portfolio) 23 x 36 cm.
LC Call No.:   QA71.D3 (Spec. Format)
Subjects:      Mathematical instruments. [from old catalog]
Control No.:   10290228

Author:        Deutsche mathematiker-vereinigung. [from old
                  catalog]
Title:         Katalog mathematischer und
                  mathematisch-physikalischer modelle, apparate und
                  instrumente.
Published:     München, C. Wolf & sohn, 1892.
Description:   xv, [1], 430 p. illus., diagrs. 25 cm.
LC Call No.:   QA71.D48
Subjects:      Mathematical instruments.
               Surfaces, Models of.
               Machinery -- Models.
               Curves.
Control No.:   6791943

Author:        Dyck, Walther von, 1856-1934. [from old catalog]
Title:         Deutsche unterrichts-ausstellung in Chicago
                  1893.
Published:     Berlin, 1893.
Description:   x p., 2 l., [3]-115, [1] p. illus., diagrs. 25
                  cm.
LC Call No.:   QA71.D9
Subjects:      Mathematical instruments. [from old catalog]
               Surfaces, Models of. [from old catalog]
               Mathematics -- Bibliography. [from old catalog]
               Chicago. World's Columbian exposition, 1893 --
                  Germany. [from old catalog]
Other titles:  Special-katalog der mathematischen ausstellung.
Control No.:   9256701

Author:        Gale, John, 18th/19th cent.
Title:         Appendix to Mr. Adams's geometrical and graphical
                  essays : containing a table of the quantity of northing,
                  southing, easting, and westing, made on any course, to every
                  degree and fifteenth minute of the quadrant, at any distance
                  from 1 to 100 / by John Gale.
Published:     London : Printed by R. Hindmarsh ..., 1791.
Description:   91, [1] p. ; 22 cm. (8vo)
LC Call No.:   QA71.G35x 1791
Notes:         Signatures: A-Lp4s Mp2s.
Subjects:      Mathematical instruments -- Tables -- Early works
                  to 1800.
Other authors: Adams, George, 1720-1772. Geometrical and
                  graphical essays.
Control No.:   2400278

Author:        Galle, Andreas Wilhelm Gottfried, 1858-
Title:         Mathematische Instrumente, von Prof. Dr. A. Galle
                  ... Mit 86 Abbildungen und Figuren.
Published:     Leipzig, Berlin, B.G. Teubner, 1912.
LC Call No.:   QA71.G3

Author:        Grillet, René. [from old catalog]
Title:         Curiositez mathematiques de l'invention du Sr
                  Grillet ...
Published:     n.p., 1673.
Description:   1 v.
LC Call No.:   QA71.G7
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC [from old catalog]
Control No.:   8643399

Author:        Hacre, Muséum d'histoire naturelle. [from old
                  catalog]
Title:         Notice ...
Published:     Le Havre. [n.d.]
Description:   v. cm.
LC Call No.:   QA71.H4A3
Control No.:   6275651

Author:        Horsburgh, Ellice Martin, ed.
Title:         Modern instruments and methods of calculation; a
                  handbook of the Napier Tercentenary Exhibition, ed. by E.M.
                  Horsburgh ... with the co-operation of the following
                  committee: Herbert Bell ... G.A. Carse ... David Gibb ...
                  J.R. Milne ... E.T. Whittaker ... Gargill G. Knott ...
Published:     London, G. Bell and Sons, ltd., [Edinburgh] The
                  Royal Society of Edinburgh [1914]
LC Call No.:   QA71.H7

Author:        Leybourn, William, 1626-1700? [from old catalog]
Title:         The line of proportion or numbers, commonly
                  called Gunter's line, made easie.
Published:     London, Printed by J. M. for G. Sawbridge, 1678.
Description:   3 p.l., 16, [2], 153 p. 14 cm.
LC Call No.:   QA71.L42 (Rare Bk. Coll.)
Subjects:      Mathematical instruments. [from old catalog]
               Slide-rule. [from old catalog]
Control No.:   9266569

Author:        Mayer, Joh. Eugen. [from old catalog]
Title:         Das mechanische Rechnen des Ingenieurs;
                  Rechenschieber, Rechenmaschinen, Planimeter, Integrator,
                  Integraph.
Published:     Hannover, M. Jänecke, 1908.
Description:   117 p. illus. 18 cm.
LC Call No.:   QA71.M28
Subjects:      Slide rule. [from old catalog]
               Calculators.
Series Entry:  Bibliotehk der gesamten Technik, 91. Bd. [from
                  old catalog]
Control No.:   9772157

Author:        Mayer, Joh. Eugene.
Title:         Das rechnen in der technik und seine hilfsmittel,
                  rechenschieber, rechentafeln, rechenmaschinen usw. Von Joh.
                  Eugen Mayer ... mit 30 abbildungen.
Published:     Leipzig, G.J. Göschen, 1908.
Description:   128 p. incl. illus., tables, diagrs. 16 cm.
Series:        Sammlung Göschen [405]
LC Call No.:   QA71.M3
Notes:         "Literaturverzeichnis": p. [4]
Subjects:      Slide rule.
               Calculators.
               Graphic methods.
               Mathematics -- Tables.
Control No.:   4052734

Author:        Merrifield, Charles Watkins, 1827-1884. [from old
                  catalog]
Title:         A catalogue of a collection of ruled surfaces.
Published:     London, Printed by G. E. Eyre and W.
                  Spottiswoode, for H. M. Stationery off., 1872.
Description:   41, [1] p. diagrs. 21 cm.
LC Call No.:   QA71.M4
Subjects:      Surfaces, Models of. [from old catalog]
               Fabre de Lagrange, --. [from old catalog]
Other authors: South Kensington museum, London. [from old
                  catalog]
Control No.:   9666941

Author:        Murray, Francis J. (Francis Joseph), 1911-
Title:         The theory of mathematical machines.
Edition:       Rev. [i.e. 2d] ed.
Published:     New York, King's Crown Press [1948]
Description:   ix, 139 p. illus. 28 cm.
LC Call No.:   QA71.M8 1948
Dewey No.:     510.78
Notes:         Bibliography: p. 135-136.
Subjects:      Mathematical instruments.
               Calculators.
Other titles:  Mathematical machines.
Control No.:   10225758

Author:        Murray, Francis J. (Francis Joseph), 1911-
Title:         The theory of mathematical machines [by] Francis
                  J. Murray ...
Published:     New York, King's crown press, 1947.
Description:   1 p.l., v-vii, 116 p. illus., diagrs. 28 x 22
                  cm.
LC Call No.:   QA71.M8
Dewey No.:     510.78
Notes:         Bibliography: p. 115-116.
Subjects:      Mathematical instruments.
               Calculators.
Other titles:  Mathematical machines.
Control No.:   1219777

Author:        Neuendorff, Richard, 1877-1935. [from old
                  catalog]
Title:         Praktische mathematik.
Published:     Leipzig, B. G. Teubner, 1911.
Description:   vi, 104, [2] p. illus., diagrs. (part fold.) 19
                  cm.
LC Call No.:   QA71.N3
Subjects:      Mathematical instruments. [from old catalog]
               Graphic methods. [from old catalog]
Control No.:   6353632

Author:        Neuendorff, Richard, 1877- [from old catalog]
Title:         Praktische mathematik ...
Published:     Leipzig und Berlin, B. G. Teubner, 1917-18.
Description:   2 v. illus., diagrs. (1 fold.) 19 cm.
LC Call No.:   QA71.N32
Subjects:      Mathematical instruments. [from old catalog]
               Graphic methods. [from old catalog]
Control No.:   5993266

Author:        Oliver, Henry K. (Henry Kemble), 1800-1885.
Title:         An elementary treatise on the construction and
                  use of the mathematical instruments usually put into portable
                  cases.
Published:     Boston, Perkins & Marvin, 1830.
Description:   68 p. 23 diagr. on 6 fold. pl. 19 cm.
LC Call No.:   QA71.O1
Notes:         Preface signed: H. K. O.
Subjects:      Mathematical instruments.
Control No.:   8666337

Author:        Data Processing Seminar on Status of Digital
                  Computer and Data Processing Developments in the Soviet Union
                  (1958 : Washington, D.C.)
Title:         Proceedings.
Published:     [Washington] Office of Naval Research, Dept. of
                  the Navy, [1959]
Description:   179 p. illus. 26 cm.
Series:        ONR symposium report, ACR-37
LC Call No.:   QA74.D3 1958
Dewey No.:     510.7834
Notes:         Cover title.
               Bibliography: p. 46-52.
Subjects:      Computation laboratories -- Soviet Union --
                  Congresses.
               Electronic digital computers -- Congresses.
               Electronic data processing -- Congresses.
Series Entry:  ONR symposium report ; ACR-37.
Control No.:   6550388

Author:        University of Wisconsin--Madison. Graduate
                  School. Research Committee.
Title:         The computing laboratory in the university,
                  edited by Preston C. Hammer.
Published:     Madison, University of Wisconsin Press, 1957.
Description:   236 p. illus. 25 cm.
LC Call No.:   QA74.W5 1955
Dewey No.:     510.78
Notes:         "A conference ... held at the University of
                  Wisconsin in August, 1955 ... Sponsored by the University of
                  Wisconsin Graduate Research Committee."
Subjects:      Computation laboratories.
               Universities and colleges.
Other authors: Hammer, Preston C., ed.
Control No.:   1693401

Author:        Abbott, A[mos], 1812- [from old catalog]
Title:         Plane and spherical trigonometry, simplified,
                  illustrated and problems solved by the spherometer, an
                  instrument accompanying this treatise, and designed to be
                  used in high schools, academies and colleges, also, for
                  surveyors and others. By A. Abbott, M.D.
Published:     Nashua, N.H., R.T. Smith, 1873.
Description:   1 p.l., iv, [5]-64 p. 3 diagrs. in pocket. 20
                  cm.
LC Call No.:   QA77.A12
Subjects:      Mathematical instruments. [from old catalog]
               Trigonometry. [from old catalog]
Control No.:   7263421

Author:        Adams, George, 1720-1772.
Uniform Title: Geometrical and graphical essays
Title:         Plates to the geometrical and graphical essays /
                  by the late George Adams ...
Edition:       The second edition / corrected and enlarged by
                  William Jones ...
Published:     London : Printed by J. Dillon ... and sold by W.
                  and S. Jones, opticians ..., 1797.
Description:   xxxiv folded leaves of plates : ill.
                  (engravings), diagrs., plans ; 22 cm. (8vo)
LC Call No.:   QA77.A33x 1797
Subjects:      Mathematical instruments -- Early works to 1800.
Other authors: Jones, William, 1763-1831.
Control No.:   3818627

Author:        Bolles, [William] [from old catalog]
Title:         A description and practical application of
                  Bolles's trigonometer.
Published:     [Griswold, Conn.?] 1824.
Description:   1 p. l., 32 p., 1 l. front. (diagr.) 18 cm.
LC Call No.:   QA77.B69
Subjects:      Mathematical instruments. [from old catalog]
Control No.:   9136608

Author:        Bundy, William. [from old catalog]
Title:         Bundy's scientific principles on the square,
Published:     Valparaiso, Ind., c1899.
Description:   sheet (fold.) 55 x 75 cm.
LC Call No.:   QA77.B96
Subjects:      Mathematical instruments. [from old catalog]
Control No.:   8190206

Author:        Cox, William, 1847- [from old catalog]
Title:         The logarithmic spiral curve.
Published:     New York, Keuffel & Esser co. [1891]
Description:   8 p. diagrs. 24 cm.
LC Call No.:   QA77.C87
Subjects:      Mathematical instruments. [from old catalog]
Control No.:   9610468

Author:        Foster, Samuel, d. 1652.
Title:         Posthuma Fosteri: the description of a ruler,
                  upon which is inscribed divers scales: and the uses thereof:
Published:     London, Printed by R. and W. Leybourn, for N.
                  Bourn, 1652.
Description:   4 p.l., 80 p., 1 l. illus., diagrs. 19 x 15 cm.
LC Call No.:   QA77.F6
Subjects:      Mathematical instruments.
               Mathematics -- Early works to 1800.
Other authors: Wingate, Edmund, 1596-1656, ed.
Control No.:   7860443

Author:        Henry, Charles, 1859- [from old catalog]
Title:         Rapporteur esthétique de M. Charles Henry.
                  Notice sur les applications à l'art industriel, à
                  l'histoire de l'art, à l'interprétation de la méthode
                  graphique, en général à l'étude et à la rectification
                  esthétiques de toutes formes.
Published:     Paris, G. Séguin, 1888.
Description:   27, [13] p. incl. tables. diagrs. 43 cm.
LC Call No.:   QA77.H4
Subjects:      Protractors. [from old catalog]
Control No.:   7789120

Author:        Leybourn, William, 1626-1716.
Title:         Panorganon: or, A universal instrument,
                  performing all such conclusions geometrical and astronomical
                  as are usually wrought by the globes, spheres, sectors,
                  quadrants, planispheres, or other the like instruments, yet
                  in being; with ease and exactness. Some uses whereof are
                  exemplified in the solution of such problems as are of
                  frequent use in the practise of geometry, astronomy,
                  dialling, geography, trigonometry, projection, &c. By William
                  Leybourn, PHILOM.
Published:     London, Printed for W. Birch, 1672.
Description:   2 pts. in 1 v. front. (port.) 2 pl. (1 fold.)
                  tables, diagrs. 19 cm.
LC Call No.:   QA77.L68
Notes:         Collation: pt. 1: 4 p. l., 140 p.; pt. 2: 4 p.
                  l., 119 p.
Subjects:      Mathematical instruments.
               Sundials.
Control No.:   272591

Author:        Marchelli, Giovanni, 1713-1764. [from old
                  catalog]
Title:         Trattato del compasso di proporzione ad
                  istriuzione de'signori convittori del Collegio de'nobili di
                  Milano ...
Published:     Milano, G. Galleazzi, 1759.
Description:   xxii, 352 p. diagrs., tables. 21 cm.
LC Call No.:   QA77.M3 1759 (Rare Bk Coll)
Subjects:      Compasses (Mathematical instruments)
Control No.:   9854425

Author:        Nicholson, J. W. (James William), 1844-
Title:         The multisector and polyode / by J. W.
                  Nicholson.
Published:     New Orleans : The Times-Democrat, 1882.
Description:   14 p. : ill. ; 24 cm.
LC Call No.:   QA77.N62
Subjects:      Mathematical instruments.
               Angles (Geometry)
Control No.:   7731513

Author:        Ozanam, Jacques, 1640-1717.
Title:         Usage de l'instrument universel.
Published:     Paris, Chez J. B. Delespine, 1700.
Description:   116 p. diagrs. on 2 fold. pl. 15 cm.
LC Call No.:   QA77.O99
Subjects:      Mathematical instruments. [from old catalog]
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   7731515

Author:        Pepper, Paul Milton.
Title:         The general theory of verniers; verniers for
                  nonuniform scales.
Published:     Columbus, Engineering Experiment Station, College
                  of Engineering, Ohio State University, 1961.
Description:   54 p. illus.
Series:        Ohio State University. Engineering Experiment
                  Station. Bulletin no. 186
               Ohio State University studies. Engineering
                  series, v. 30, no. 2
LC Call No.:   QA77.P4
Subjects:      Measuring instruments.
Series Entry:  Ohio State University. Engineering series ; v.
                  30, no. 2.
Series Entry:  Bulletin (Ohio State University. Engineering
                  Experiment Station : 1963) ; no. 186.
Control No.:   9837239

Author:        Prony, [Gaspard Claire François Marie Riche],
                  baron de, 1755-1839. [from old catalog]
Title:         Note sur les moyens de perfectionner le compas de
                  réduction,
Published:     Paris, Carilian-Gœury, 1835.
Description:   16 p. incl. tab. 21 cm.
LC Call No.:   QA77.P96
Subjects:      Mathematical instruments. [from old catalog]
Control No.:   7266175

Author:        Romano, Bartolomeo. [from old catalog]
Title:         Proteo militare.
Published:     Napoli, G. I. Carlino & A. Pace, 1595.
Description:   192 p. illus. 20 cm.
LC Call No.:   QA77.R6 (Rare bk. coll.)
Subjects:      Mathematical instruments. [from old catalog]
               Military engineering. [from old catalog]
               Nautical instruments. [from old catalog]
Control No.:   6009342

Author:        [Wadsworth, Henry] [from old catalog]
Title:         Gemoetry and trigonometry: a new demonstration of
                  the usual rules.
Published:     [Duxbury? Mass., c1877]
Description:   12 p. illus. 13 cm.
LC Call No.:   QA77.W12
Subjects:      Mathematical instruments. [from old catalog]
Control No.:   9606321

Author:        Zahm, Albert Francis, 1862- [from old catalog]
Title:         The vector-ruling protractor.
Published:     [Philadelphia] Press of J. B. Lippincott Co.,
                  1924.
Description:   209-215 p. illus. 25 cm.
LC Call No.:   QA77.Z3
Subjects:      Protractors. [from old catalog]
Control No.:   9772080

Author:        Abakanowicz, Br[uno], 1852- [from old catalog]
Title:         Les intégraphes, la courbe intégrale et ses
                  applications; étude sur un nouveau système d'intégrateurs
                  mécaniques, par Br. Abdank-Abakanowicz.
Published:     Paris, Gauthier-Villars, 1886.
Description:   x, 156 p. illus., diagrs. 26 cm.
LC Call No.:   QA81.A13
Subjects:      Planimeter. [from old catalog]
Control No.:   6796527

Author:        Bremiker, K[arl], 1804-1877. [from old catalog]
Title:         Theorie des Amsler'schen polarplanimeters,
Published:     Berlin, K. Geheime oberhofbuchdruckerei (R.
                  Decker) 1863.
Description:   32 p. diagrs. 25 cm.
LC Call No.:   QA81.B83
Subjects:      Planimeter. [from old catalog]
Control No.:   6326866

Author:        Colberg, Juliusz. [from old catalog]
Title:         Sposob dochodzenia powierzchni plaskich bez
                  uçzycia rachunku za pomocña nowo-wynalezionego instrumentu
                  planimetr zwanego, albo za pomocña w tym celu urzñadzonych
                  tabell; dla uçzytku jeometrów praktycznych.
Published:     Warszawa, W Druk, Jego Ces. Król. Moâsci
                  Rzñadowey, 1824.
Description:   58 p. illus. 21 cm.
LC Call No.:   QA81.C64
Subjects:      Planimeter. [from old catalog]
Control No.:   8511963

Author:        Cox, William, 1847-
Title:         The polar planimeter. A manual, by Wm. Cox.
Published:     New York, Hoboken, N.J. [etc.] Keuffel & Esser
                  co. [c1915]
Description:    20 p. illus. 22 cm.
LC Call No.:   QA81.C86 1915
Subjects:      Planimeter.
Control No.:   8239205

Author:        Cox, William, b. 1847.
Title:         The polar planimeter. A manual, by Wm. Cox.
Published:     New York, Keuffel & Esser co. [1891]
Description:   20 p. illus. 23 cm.
LC Call No.:   QA81.C87
Subjects:      Planimeter.
Control No.:   9141188

Author:        Favaro, Antonio, 1847- [from old catalog]
Title:         Beiträge zur geschichte der planimeter,
Published:     Wien, R. v. Waldheim, 1873.
Description:   40 p. 14 diagrs. on fold. pl. 29 cm.
LC Call No.:   QA81.F27
Subjects:      Planimeter. [from old catalog]
Control No.:   8668367

Author:        General education committee. [from old catalog]
Title:         Some mathematics pratice in California secondary
                  schools.
Published:     Sacramento [1941]
Description:   39 p. 23 cm.
LC Call No.:   QA81.G44
Control No.:   8152148

Author:        [Hamburg, Bau deputation] [from old catalog]
Title:         Instruction für den gebrauch des Amsler'schen
                  polarplanimeters zur ermittelung des flächeninhalts.
Published:     [Hamburg, Druck von G. F. Thiele, 1865]
Description:   23 p. incl. tables, diagrs. 28 cm.
LC Call No.:   QA81.H19
Subjects:      Planimeter. [from old catalog]
Control No.:   7731514

Author:        Herschel, Clemens, 1842- [from old catalog]
Title:         Directions for using the planimetre as made by
                  Buff & Berger ...
Published:     [Boston, Press of Rockwell & Churchill, c1877]
Description:   4 p. 25 cm.
LC Call No.:   QA81.H57
Subjects:      Planimeter. [from old catalog]
Control No.:   6329934

Author:        Satterly, John, 1879- [from old catalog]
Title:         The hatchet planimeter, by John Satterly.
Published:     [Toronto] The University library: pub. by the
                  librarian, 1921.
Description:   24 p. pl., diagrs. 26 cm.
Series:        University of Toronto series. Mathematical
                  series. no. 2
LC Call No.:   QA1.T8 no. 2
Subjects:      Planimeter. [from old catalog]
Control No.:   7319442

Author:        Hartree, Douglas R. (Douglas Rayner), 1897-1958.
Title:         Calculating instruments and machines.
Published:     Urbana, Univ. of Illinois Press, 1949.
Description:   ix, 138 p. illus. 26 cm.
LC Call No.:   QA85.H29
Dewey No.:     510.78
Notes:         "References": p. 131-134.
Subjects:      Calculators.
               Mathematical instruments.
Control No.:   275523

Author:        Lean, John Udy, d. 1913
Title:         Freaks of figures,
Edition:       2d ed.
Published:     Detroit, Mich., Udy publishing company [1907]
Description:   3 p.l., [11]-68 p. diagrs. 17 cm.
LC Call No.:   QA94.L4 1907A
Subjects:      Mathematical recreations. [from old catalog]
Control No.:   8247702

Author:        Lean, John Udy, d. 1913.
Title:         Freaks of figures,
Published:     Detroit, Mich., Modern methods publishing company
                  [c1907]
Description:   3 p. l., [11]-64 p. illus. 18 cm.
LC Call No.:   QA95.L4
Subjects:      Mathematical recreations. [from old catalog]
Control No.:   8214552

Title:         Memorabilia mathematica : the philomath's
                  quotation book : 1140 anecdotes, aphorisms, and passages by
                  famous mathematicians, scientists & writers / [compiled by]
                  Robert Edouard Moritz.
Published:     [Washington, D.C.] : Mathematical Association of
                  America, [1993?], c1942.
Description:   vii, 410 p. : ill. ; 22 cm.
Series:        MAA spectrum
LC Call No.:   QA99.M45 1993
Dewey No.:     510 20
ISBN:          0883853213 (pbk.)
Notes:         "This is an unaltered and unabridged
                  republication of the first edition published in 1914."--T.p.
                  verso.
               Includes index.
Subjects:      Mathematics -- Quotations, maxims, etc.
Other authors: Moritz, Robert Édouard, 1868-1940.
Other titles:  Philomath's quotation-book.
Control No.:   1609874

Author:        Adorno, Juan Nepomuceno, b. 1814
Title:         Introduction to the harmony of the universe; or,
                  Principles of physico-harmonic geometry. By Juan Nepomuceno
                  Adorno.
Published:     London, J. Weale [etc.] 1851.
Description:   1 p. l., viii p., [2], 160 p. fold. plates, fold.
                  map, fold. tab. 25 cm.
LC Call No.:   QA99.A24
Subjects:      Geometry -- Curiosa and miscellany
Control No.:   7263336

Author:        Appoullot, L. [from old catalog]
Title:         Voilà l'algèbre.
Published:     [n.p., c1942]
Description:   29 p. table. 28 cm.
LC Call No.:   QA99.A6
Subjects:      Algebra.
Control No.:   9309237

Author:        Bennett, John, engineer. [from old catalog]
Title:         The Arcanum. Comprising a concise theory, of
                  practicable elementary and definitive geometry; exhibiting
                  the various transmutations of superfices and solids;
                  obtaining also their actual capacity by the mathematical
                  scale: including solutions to the yet unanswered problems of
                  the ancients ... By John Bennett ...
Published:     London, J. Bennett, 1838.
Description:   iv, 48 p. front., plates. 22 cm.
LC Call No.:   QA99.B2
Subjects:      Geometry -- Miscellanea.
Control No.:   10073317

Author:        Bennett, John, engineer. [from old catalog]
Title:         Original geometrical illustrations; or, The book
                  of lines, squares, circles, triangles, polygons, &c. Showing
                  an easy and scientific analysis for increasing, decreasing,
                  and altering any given circle, square, triangle, ellipsis,
                  &c. to any other figure containing the same area, by plain
                  and simple methods, laid down agreeably to mathematical
                  demonstration ... Containing also a variety of useful
                  information, intended as a complete instructor to the most
                  useful science of geometry and mensuration. By John Bennett
                  ...
Published:     London, J. Bennett [etc.] 1837.
Description:   iv, 48, 22 p. front., 55 pl., diagrs. 28 cm.
LC Call No.:   QA99.B3
Subjects:      Geometry -- Miscellanea.
Control No.:   6794959

Author:        Benson, Lawrence S. (Lawrence Sluter)
Title:         Mathematics in a dilemma.
Edition:       Complimentary ed.
Published:     New York : W. L. Hyde, 1879.
Description:   17 p. : ill. ; 24 cm.
LC Call No.:   QA99.B4
Notes:         Cover-title.
               Preface signed:  Lawrence Sluter Benson.
Subjects:      Geometry.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
Control No.:   8197297

Author:        [Benson, Lawrence Sluter] [from old catalog]
Title:         Progress in mathematics during 3000 years.
Published:     [New York, 1901]
Description:   [4] p. diagr. 36 cm.
LC Call No.:   QA99.B43
Subjects:      Geometry -- Miscellanea.
Control No.:   7731424

Author:        Berlitzheimer, I[saac] [from old catalog]
Title:         A few brief extracts from the Dynamic algebra,
Published:     New York, J. Briem, 1878.
Description:   14, [2] p. 23 cm.
LC Call No.:   QA99.B5
Subjects:      Mathematics -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   9605021

Author:        De Medici, Charles. [from old catalog]
Title:         Principles, theory and practice of mathematical
                  commensuration, comprising five analytical primers, a
                  prefatory essay and a retrospective view of research in the
                  domain of geometry.
Published:     Chicago, A. M. Flanagan, 1883.
Description:   5 pts. in 1 v. diagrs. 18 cm.
LC Call No.:   QA99.D3
Subjects:      Mathematics -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   9136525

Author:        Dodgson, Charles Lutwidge, 1832-1898.
Title:         Euclid and his modern rivals, by Charles L.
                  Dodgson ...
Published:     London, Macmillan and co., 1879.
Description:   xxxi, 299 p. incl. front. (diagr.) 19 cm.
LC Call No.:   QA99.D6
Subjects:      Euclid.
               Geometry -- Miscellanea.
Control No.:   1691720

Author:        Faber, Theodore. [from old catalog]
Title:         Mathematical and philosophical manifesto,
                  declaring numerous theorems, problems, postulates,
                  corollaries, axioms, propositions, rules, and facts, hitherto
                  unknown in science, and naturally growing out of the
                  extraordinary and most significant discovery of a lacking
                  link in the demonstration of the world-renowned Pythagorean
                  problem, utterly disproving its absolute truth, although
                  demonstrated as such for twenty-three centuries; and by this
                  discovery establishing the fact of the existence of perfect
                  harmony between arithmetic and geometry as a law of nature;
                  and calculated to settle forever the famous dispute between
                  the two great philosophical schools.
Published:     New York, E. S. Dodge & co., 1872.
Description:   34 p. front. 24 cm.
LC Call No.:   QA99.F11
Subjects:      Geometry -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   5858921

Author:        Fleming, J. W. [from old catalog]
Title:         An essay on arithmetic.
Published:     Maquoketa, Ia., W. S. Belden, printer, 1876.
Description:   cover-title, 48 p. 23 cm.
LC Call No.:   QA99.F58
Subjects:      Mathematics -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   7735436

Author:        Fleming J. W. [from old catalog]
Title:         The unit and the number.
Published:     Maquoketa. Iowa, Record print, 1881.
Description:   1 p.l., 70 p. 16 cm.
LC Call No.:   QA99.F6
Subjects:      Mathematics -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   10077342

Author:        Frankenstein, Gustavus. [from old catalog]
Title:         Magic reciprocals: involving a new, wonderful and
                  beautiful theorem.
Published:     Cincinnati, Wrightson & co., 1875.
Description:   8 p. diagrs. 24 cm.
LC Call No.:   QA99.F8
Subjects:      Mathematics -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   8668279

Author:        Houlston, William. [from old catalog]
Title:         Inklings of areal autometry.
Published:     London, Simpkin, Marshall, and co. [1874]
Description:   36 p. diagr. 15 cm.
LC Call No.:   QA99.H83
Subjects:      Geometry -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   6794958

Author:        Hugo, Léopold, comte, 1828-1895.
Title:         Les cristalloïdes à directrice circulaire.
                  Études géométriques par le Cte Léopold Hugo.
Published:     Paris, Gauthier-Villars, 1867.
Description:   vi, [7]-40 p. diagrs. on fold. pl. 25 cm.
LC Call No.:   QA99.H85
Subjects:      Geometry -- Miscellanea.
Control No.:   4052318

Author:        Hugo, Léopold, comte, 1828-1895
Title:         Les cristalloïdes complexes a sommet étoilé /
                  par le Cte Léopold Hugo.
Published:     Paris : Gauthier-Villars, 1872.
Description:   24 p., 3 fold. plates : ill. ; 25 cm.
LC Call No.:   QA99.H852
Subjects:      Geometry -- Curiosa and miscellany.
Control No.:   10076156

Author:        Hugo, Léopold, comte, 1828-1895.
Title:         Essai de géométrie polyédrique. Théorie des
                  cristalloïdes élémentaires, par le Cte. Léopold Hugo.
Published:     Paris, Gauthier-Villars, 1867.
Description:   59 p. 4 fold. pl. 25 cm.
LC Call No.:   QA99.H853
Notes:         Half-title: Théorie des cristalloïdes
                  élémentaires.
Subjects:      Geometry -- Miscellanea.
Control No.:   3579473

Author:        Hugo, Léopold, comte, 1828-1895.
Title:         Essai sur la géométrie des cristalloïdes, par
                  le Cte Léopold Hugo ...
Published:     Paris, Gauthier-Villars, 1873.
Description:   20 p. fold. pl. 25 cm.
LC Call No.:   QA99.H855
Subjects:      Geometry -- Miscellanea.
Other titles:  Cristalloïdes, Essai.
Control No.:   2161234

Author:        Hugo, Léopold, comte, 1828-1895.
Title:         Extraite de deux lettres adressées à D. B.
                  Boncompagni ...
Published:     [Rome, 1876]
Description:   3 p. diagrs. 32 x 23 cm.
LC Call No.:   QA99.H86
Control No.:   7679720

Author:        Hugo, Léopold, comte, 1828-1895.
Title:         Géométrie Hugodomoïdale, anhellénique, mais
                  philosophique et architectonique. La question de
                  l'équidomoïde et des cristalloïdes géometriques, par le
                  cte Léopold Hugo ...
Published:     Paris [Typ de Rouge, Dunon et Fresné] 1875.
Description:   viii, [9]-31, [1] p. incl. front., diagrs. on pl.
                  25 cm.
LC Call No.:   QA99.H88
Notes:         A satirical treatise.
Subjects:      Geometry -- Miscellanea.
Control No.:   12911729

Author:        Hugo, Léopold, comte, 1828-1895.
Title:         La théorie Hugodécimale; ou, La base
                  scientifique et definitive de l'arithmo-logistique
                  universelle, par le cte. Léopold Hugo ...
Published:     Paris [Imprimerie Laloux fils et Guillot] 1877.
Description:   31, [1] p. illus. 26 cm.
LC Call No.:   QA99.H9
Control No.:   12911726

Author:        Lamson, Alexander O. [from old catalog]
Title:         Special higher mathematics,
Published:     Jersey City, N.J., Palisades publishers [c1927]
Description:   3 p.l., 70 p. illus., fold. pl., diagrs. 24 x 21
                  cm.
LC Call No.:   QA99.L3
Subjects:      Mathematics. [from old catalog]
Control No.:   5928842

Author:        [Leonard, George F.] [from old catalog]
Title:         The mechanical calculator explained.
Published:     [Boston, 1889]
Description:   7 p. 18 cm.
LC Call No.:   QA99.L58
Control No.:   9142961

Author:        Medici, C. de (Charles)
Title:         Medici's rational mathematics ...
Published:     New York city, C. de Medici, 1895-96.
Description:   3 v. diagrs. 20 cm. (v. 1: 20 cm.)
LC Call No.:   QA99.D4
Notes:         Section A. pt. 1. Geometry: first principles and
                  primary elements...--pt. 2. Geometry: first principles of
                  commensuration ... pt. 3. Classification of geometric figures
                  and forms...--Section B. Geometry, study and practice.
Subjects:      Geometry -- Miscellanea.
Control No.:   2633999

Author:        Miller, Aaron.
Title:         A treatise on algebraic dexsins, by Aaron Miller
                  ...
Published:     [Flat Rock, Ind?] c1920.
Description:   2 v. 27 cm.
LC Call No.:   QA99.M5
Notes:         Type-written.
Subjects:      Mathematics -- Miscellanea.
Control No.:   3580471

Author:        Ryan, Matthew. [from old catalog]
Title:         The celebrated theory of parallels.
Published:     Washington, Chronicle print, 1866.
Description:   10 p. diagrs. 22 cm.
LC Call No.:   QA481.R94
Subjects:      Geometry -- Miscellanea.
Other authors: YA Pamphlet Collection (Library of Congress) DLC
                  [from old catalog]
Control No.:   7731423

Author:        Smith, James, 1805-1872.
Title:         Curiosities of mathematics for the instruction of
                  mathematicians and the benefit of the British association for
                  the advancement of science,
Published:     Liverpool, E. Howell; [etc., etc.] 1870.
Description:   50, [2] p. diagrs. 22 cm.
LC Call No.:   QA99.S5
Subjects:      Mathematics -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   8725292

Author:        Smith, John Cauchois.
Title:         Questions in mathematics. By John C. Smith.
Published:     Brooklyn, N.Y., H.C. Smith [c1889]
Description:   vi p., 1 l., [7]-157 p. fold. pl., diagrs. 21
                  cm.
LC Call No.:   QA99.S6
Subjects:      Geometry -- Curiosa and miscellany.
Control No.:   9136524

Author:        Smith, Seba, 1792-1868. [from old catalog]
Title:         New elements of geometry.
Published:     London, R. Bentley, 1850.
Description:   viii, [9]-200 p. diagrs. 22 cm.
LC Call No.:   QA99.S7
Subjects:      Geometry -- Curiosa and miscellany. [from old
                  catalog]
Control No.:   10073129

Author:        Thomas, W. N. [from old catalog]
Title:         A mathematical curiosity. Square of 50 figures
                  from 1 to 2500...
Published:     [n.p.] 1917.
Description:   1 leaf cm.
LC Call No.:   QA99.T5
Control No.:   7672035
