#+STARTUP: showeverything logdone
#+options: num:nil

Author:        Demartres, Gustave, 1848-1919. [from old
                  catalog]
Title:         Cours de géométrie infinitésimale,
Published:     Paris, Gauthier-Villars, 1913.
Description:   x, 455, [1] p. diagrs. 25 cm.
LC Call No.:   QA615.D4
Subjects:      Geometry, Infinitesimal. [from old catalog]
Control No.:   9271711

Author:        Aoust, M. l'abbé (Louis Stanislas Xavier
                  Barthélemy), 1814-1885.
Title:         Analyse infinitésimale des courbes planes,
Published:     Paris, Gauthier-Villars, 1873.
Description:   p. cm.
LC Call No.:   QA621.A6
Subjects:      Curves, Plane.
Control No.:   6327150

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Intorno ad alcuni sistemi di curve piane. Nota di
                  Eugenio Beltrami ...
Published:     Roma, Tipografia editrice degli Annali di
                  matematica, 1862.
Description:   9 p. 30 x 22 cm.
LC Call No.:   QA621.B44
Subjects:      Curves, Plane.
Control No.:   6331985

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Sulla teoria delle sviluppoidi e delle
                  sviluppanti. Di Eugenio Beltrami ...
Published:     Roma, 1862.
Description:   1 p.l., 30 p. diagr. 29 x 22 cm.
LC Call No.:   QA621.B46
Subjects:      Curves. [from old catalog]
Control No.:   6800203

Author:        Boeddicker, Otto, 1853- [from old catalog]
Title:         Beitrag zur theorie des winkels ...
Published:     [Stuttgart, Druck von Gebrüder Mäntler, 1876]
Description:   [3]-48 p. diagrs. 25 cm.
LC Call No.:   QA621.B6
Subjects:      Angles (Geometry)
Control No.:   7732814

Author:        Dodd, Edward L. (Edward Lewis), 1875-1943.
Title:         On ordinary plane and skew curves, by Edward L.
                  Dodd.
Published:     Austin, Tex., University of Texas [1912]
Description:   36 p. diagrs. 23 cm.
Series:        Bulletin of the University of Texas. no. 222.
                  Scientific ser. 21. March 8, 1912
LC Call No.:   QA621.D6
Subjects:      Curves.
Control No.:   7771953

Author:        Fontenelle, M. de (Bernard Le Bovier),
                  1657-1757.
Title:         Élémens de la géométrie de l'infini. Suite
                  des Mémoires de l'Académie royale des sciences.
Published:     Paris, De l'Imprimerie royale, 1727.
Description:   13 p. l., 548 p. diagr. 26 cm.
LC Call No.:   QA621.F68
Notes:         Title vignette.
Subjects:      Infinite.
               Curves, Plane.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   744805

Author:        Grane, Nils. [from old catalog]
Title:         Über kurven mit gleichartigen successiven
                  developpoiden ...
Published:     Lund, E. Malmströms buchdruckerei, 1894.
Description:   1 p.l., 71 p. 22 cm.
LC Call No.:   QA621.G75
Subjects:      Curves, Plane. [from old catalog]
Control No.:   10078795

Author:        Henkel, Ludwig, 1859- [from old catalog]
Title:         Ueber die aus einer curve y=f(x) abgeleiteten
                  curven yb1s=x dy/dx =xfp1s(x) (tangentencurve) und
                  yb2s=x dx/dy=x/fp1s(x) (normalcurve) mit specieller
                  anwendung auf die parabel ...
Published:     Marburg, Druck von J.A. Koch, 1882.
Description:   30 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA621.H5
Notes:         Inaug.-diss.--Marburg.
Subjects:      Curves, Plane.
               Parabola.
Control No.:   13194655

Author:        Klaas, Adolph, 1836- [from old catalog]
Title:         Die normal-fusspunktslinien ..
Published:     Wiesbaden, L. Schellenberg'sche
                  hof-buchdruckerei, 1871.
Description:   18 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA621.K57
Subjects:      Curves, Pedal.
Control No.:   8208104

Author:        Klein, Felix, 1849-1925.
Title:         Anwendung der differential- und intergralrechnung
                  auf geometrie:
Published:     Leipzig, In commission bei B. G. Teubner, 1902.
Description:   p. cm.
LC Call No.:   QA621.K6
Subjects:      Calculus.
               Harmonic analysis.
               Interpolation.
               Curves.
Other authors: Müller, C. H. (Conrad Heinrich), b. 1878, ed.
Control No.:   8665739

Author:        Legendre, A. M. (Adrien Marie), 1752-1833.
Title:         Elements of geometry and trigonometry from the
                  works of A. M. Legendre.
Published:     New York and Chicago, A. S. Barnes & company,
                  c1885.
Description:   viii, [9]-291, 150, 62 p. diagr. 21 cm.
LC Call No.:   QA621.L43 1885
Subjects:      Geometry.
               Trigonometry.
Control No.:   8664373

Author:        Parkinson, George Ambrose, 1899- [from old
                  catalog]
Title:         Pairs of curves in an Su.
Published:     Princeton, N.J. [1932]
Description:   p. 649-657. 26 cm.
LC Call No.:   QA621.P3 1929
Subjects:      Curves. [from old catalog]
               Hyperspace. [from old catalog]
Control No.:   6884199

Author:        Powell, Baden, 1796-1860. [from old catalog]
Title:         An elementary treatise on the geometry of curves
                  and curved surfaces,
Published:     Oxford, University press, 1830.
Description:   xiv, 1 l., 300 p. front. (diagrs. on fold. pl.)
                  22 cm.
LC Call No.:   QA621.P8
Subjects:      Curves. [from old catalog]
               Surfaces. [from old catalog]
Control No.:   9605389

Author:        Reina, Vincenzo, 1862-1919. [from old catalog]
Title:         Di alcune proprietà della linee
                  caratteristiche,
Published:     Roma, Tip. della R. Accademia dei Lincei, 1889.
Description:   cover-title, p. [881]-885. 27 cm.
LC Call No.:   QA621.R4
Subjects:      Curves. [from old catalog]
Control No.:   6871142

Author:        Ruchonnet, Charles, 1832-1914. [from old
                  catalog]
Title:         Exposition géométrique des propriétés
                  générales des courbes.
Published:     Paris, Gauthier-Villars; [etc., etc.] 1864.
Description:   3 p. l., [3]-116 p., 1 l. ii fold. pl. (diagrs.)
                  20 cm.
LC Call No.:   QA621.R8
Subjects:      Curves. [from old catalog]
Control No.:   7823969

Author:        Schlabach, Gustav.
Title:         Über die Enveloppen, welche bei der Bewegung
                  einer Geraden längs einer gegebenen Curve enstehen ...
Published:     Marburg, Universitäts-Buchdruckerei (R.
                  Friedrich) 1887.
Description:   39 p. diagrs. on pl. 21 cm.
LC Call No.:   QA621.S3
Notes:         Inaug.-diss.--Marburg.
Subjects:      Envelopes (Geometry)
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.16.
Control No.:   9149154

Author:        Völker, Karl, 1857- [from old catalog]
Title:         Ueber die relationen zwischen einer gegebenen
                  curve y = f(x) und einer daraus abgeleiteten curve y
                  k·dx/dy = k/fp1s(x) mit specieller anwendung auf die
                  ellipse ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1880.
Description:   1 p. l., 32 p., 1 l. diagrs. on 2 pl. 21 cm.
LC Call No.:   QA621.V87
Notes:         Inaug.-diss.--Marburg.
               Vita.
Subjects:      Curves, Plane.
Control No.:   13194146

Author:        Weissenborn, Hermann, 1830-1896.
Title:         Die cyclischen curven, methodisch und mit
                  besonderer rücksicht auf constructionen zum gebrauche für
                  techniker, sowie als uebingsbeispiel für angehende
                  mathematiker behandelt, von dr. Hermann Weissenborn. Mit
                  sieben figurentafeln.
Published:     Eisenach, J. F. Bärecke, 1856.
Description:   viii, [2], 316 p. VII fold. pl. (diagrs.) 22 cm.
LC Call No.:   QA621.W4
Subjects:      Curves, Plane.
               Cycloids.
Control No.:   9215938

Author:        Wolkenhauer, Wilhelm, 1845- [from old catalog]
Title:         Zur theorie der parallel curven ...
Published:     Jena, Druck von W. Ratz, 1874.
Description:   35 p. 22 cm.
LC Call No.:   QA621.W86
Subjects:      Curves, Parallel.
Control No.:   9144811

Author:        Archibald, Raymond Clare, 1875-1957.
Title:         The cardioide and some of its related curves ...
Published:     Strassburg i.E., J. Singer, buchhandlung, 1900.
Description:   4 p. l.,  32 p., 1 l. 3 pl. (1 fold.) diagrs. 28
                  x 22 cm.
LC Call No.:   QA623.A7
Notes:         Inaug.-diss.--Strassburg.
               Vita.
Subjects:      Roulettes (Geometry)
Control No.:   5874676

Author:        Bellermann, Gustav i. e. Christian Friedrich
                  Gustav, 1838- [from old catalog]
Title:         Epicycloiden und hypocycloiden ...
Published:     Jena, Druck von W. Ratz, 1867.
Description:   64 p. 21 cm.
LC Call No.:   QA623.B44
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   8669697

Author:        Biel, Bernhard. [from old catalog]
Title:         Ueber rollbewegungen unter der voraussetzung,
Published:     Marburg, 1886.
Description:   28 p. diagrs. on fold. pl. 26 cm.
LC Call No.:   QA623.B58
Subjects:      Kinematic geometry. [from old catalog]
Control No.:   7732933

Author:        Converse, Henry Augustus, 1875- [from old
                  catalog]
Title:         On a system of hypocycloids of class three
                  inscribed to a given 3-line and some curves connected with it
                  ...
Published:     Salem, Mass., The Salem press co., 1904.
Description:   1 p.l., 105-139, [1] p. 30 cm.
LC Call No.:   QA623.C76
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   9138314

Author:        Dahl, Wilhelm. [from old catalog]
Title:         Beitrag zur theorie der epicyklen ...
Published:     Jena, Druck von W. Ratz, 1868.
Description:   67 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA623.D1
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   6326978

Author:        Dingeldey, Friedrich, 1859-1939.
Title:         Über die Erzeugung von Curven vieter Ordnung
                  durch Bewegungsmechanismen / von Friedrich Dingeldey.
Published:     Leipzig : B.G. Teubner, 1885.
Description:   viii, 61 p. : ill. ; 23 cm.
LC Call No.:   QA623.D5
Notes:         Thesis--Leipzig.
               Lebenslauf.
Subjects:      Kinematic geometry.
Control No.:   6328202

Author:        Ganter, Heinrich. [from old catalog]
Title:         Ueber die rouletten der kegelschnitte ...
Published:     Frauenfeld, J. Huber's buchdruckerei [1881]
Description:   1 p.l., 29 diagrs. 27 cm.
LC Call No.:   QA623.G2
Subjects:      Roulettes (Geometry) [from old catalog]
               Conic sections. [from old catalog]
Control No.:   6795167

Author:        Ellensson, Leo. [from old catalog]
Title:         Die reciproken polarcurven der epi- und
                  hypocykloiden ...
Published:     München, K. Hofbuchdruckerei Kastner & Lossen,
                  1899.
Description:   3 p.l., 93 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA623.E45
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   6796403


Author:        Gildemeister, Stephan Heinrich. [from old
                  catalog]
Title:         De lineis curvis epicycloidibus et
                  hypocycloidibus ...
Published:     Marburgi-Cattorum, 1866.
Description:   1 p.l., 50 p. diagr. 24 cm.
LC Call No.:   QA623.G4
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   10074700

Author:        Grosse, Heinrich.
Title:         Beiträge zur kinematischen Geometrie ...
Published:     Berlin, Druck von E. Krause, 1872.
Description:   35 p. 21 cm.
LC Call No.:   QA623.G8
Notes:         Inaug.-diss.--Jena.
Subjects:      Kinematic geometry
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.8.
Control No.:   6797802

Author:        Hartmann, Eduard. [from old catalog]
Title:         Untersuchung einiger curven, welche durch rollen
                  von kegelschnitten erzeugt werden ...
Published:     Marburg, 1876.
Description:   2 p.l., 36 p. diagrs. on 2 fold. pl. 25 cm.
LC Call No.:   QA623.H3
Subjects:      Roulettes (Geometry) [from old catalog]
               Conic sections. [from old catalog]
Control No.:   5860253

Author:        Hartmann, Eduard. [from old catalog]
Title:         Untersuchung einiger curven, welche durch rollen
                  von kegelschnitten erzeugt werden ...
Published:     Cassel, Druck von F. Scheel, 1876.
Description:   1 p.l., 36 p. diagrs. on 2 pl. 26 cm.
LC Call No.:   QA623.H31
Subjects:      Roulettes (Geometry) [from old catalog]
               Conic sections. [from old catalog]
Control No.:   6801599

Author:        Kessler, Oscar, 1845- [from old catalog]
Title:         Darstellung der kegelschnitte als rouletten,
Published:     Jena, 1869.
Description:   40 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA623.K4
Subjects:      Roulettes (Geometry) [from old catalog]
               Conic sections. [from old catalog]
Control No.:   8201493

Author:        Leutenegger, Jakob.
Title:         Eine mehrfach symmetrische Kurve / von Jakob
                  Leutenegger.
Published:     Basel : E. Birkhäuser, 1904.
Description:   40 p. : ill. ; 23 cm.
LC Call No.:   QA623.L6
Notes:         Thesis--Universität Basel.
Subjects:      Roulettes (Geometry)
Control No.:   10081811

Author:        Ludwig, Hermann Friedrich Theodor. [from old
                  catalog]
Title:         Elementare ableitung derjenigen
                  haupteigenschaften der cycloiden.
Published:     Leipzig, Gedruckt bei F. A. Brockhaus [1845]
Description:   13 p. diagrs. on double pl. 23 cm.
LC Call No.:   QA623.L94
Subjects:      Cycloids. [from old catalog]
               Epicycloids and hypocycloids. [from old catalog]
Other authors: Chemnitz K. Gewerb- und Baugewerkenschule. [from
                  old catalog]
Control No.:   8204093

Author:        Mangelsdorff, Friedrich.
Title:         Ueber Ovalwerke ...
Published:     Berlin, Druck von L. Simion, 1902.
Description:   2 p. l., 23 p. illus., diagrs. 29 x 22 cm.
LC Call No.:   QA623.M27
Notes:         Inaug.-diss.--Rostock.
               Author's name on verso of t.-p.
Subjects:      Kinematic geometry.
               Links and link motion.
Control No.:   8206438

Author:        Merkelbach, Wilhelm. [from old catalog]
Title:         Ueber rollcurven, die von einer geraden
                  eingehüllt werden ...
Published:     Marburg, 1881.
Description:   38 p. diagrs. on pl. 21 cm.
LC Call No.:   QA623.M56
Subjects:      Roulettes (Geometry) [from old catalog]
Control No.:   10074761

Author:        Morrill, William Kelso, 1903- [from old catalog]
Title:         A problem of ambience ...
Published:     [Baltimore, 1930]
Description:   1 p.l., p. 889-898, 1 l. 25 cm.
LC Call No.:   QA623.M6 1929
Subjects:      Kinematic geometry. [from old catalog]
Other titles:  Ambience, A problem of.
Control No.:   10154541

Author:        Opitz, Paul.
Title:         Anwendung der elliptischen Funktionen auf ein
                  problem aus der Theorie der Rollkurven ...
Published:     Dresden, Druck von C. Heinrich, 1904.
Description:   51 p., 1 l. III fold. pl., diagrs. 24 cm.
LC Call No.:   QA623.O6
Notes:         Inaug.-diss.--Rostock.
Subjects:      Roulettes (Geometry)
               Elliptic functions.
Control No.:   7272938

Author:        Pietsch, Georg. [from old catalog]
Title:         Das sphärische viereck mit gleichen
                  gegenseiten.
Published:     Gleiwitz, Druck von R. David, 1882.
Description:   24 p., 1 l. diagrs. on fold. pl. 29 x 22 cm.
LC Call No.:   QA623.P62
Subjects:      Roulettes (Geometry) [from old catalog]
               Sphere. [from old catalog]
Control No.:   7266174

Author:        Ramler, Otto Joseph, 1887-
Title:         On the three-cusped hypocycloids fulfilling
                  certain assigned conditions, by Otto Joseph Ramler.
Published:     Washington, D.C., 1918.
Description:   iv, 22 p. diagrs. 23 cm.
LC Call No.:   QA623.R3
Notes:         Thesis (Ph. D.)--Catholic University of America.
               Biography.
Subjects:      Epicycloids and hypocycloids.
Control No.:   6845478

Author:        Rehfeld, Emil, 1859-
Title:         Die derivationscurve der cycloide ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich), 1884.
Description:   1 p. l., 41, [1] p. diagrs. on pl. 22 cm.
LC Call No.:   QA623.R33
Subjects:      Cycloids. [from old catalog]
Control No.:   5865921

Author:        Reinhardt, W. 1859-
Title:         Untersuchung einiger durch das rollen von
                  kegelschnitten auf einer geraden entstehenden curven ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1885
Description:   30 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA623.R36
Notes:         Inaug.-dis.--Marburg.
               Lebenslauf.
Subjects:      Roulettes (Geometry)
Control No.:   7732870

Author:        Sang, Edward. [from old catalog]
Title:         On the contact of the loops of epicycloidal
                  curves.
Published:     Edinburgh, Printed for the Society, 1865.
Description:   1 p.l., 53-57 p. diagrs. on 7 pl. 28 cm.
LC Call No.:   QA623.S2
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   10073520


Author:        Saussure, René de, 1868-
Title:         Sur la génération des courbes par roulement,
                  par Réné de Saussure ...
Published:     Genève, Impr. Aubert-Schuchardt, 1895.
Description:   94, [2] p., diagrs. on 2 fold. pl. 28 cm.
LC Call No.:   QA623.S25
Notes:         Thesis (Ph. D.)--Johns Hopkins university, 1895.
               Notice biographique on last page.
Subjects:      Roulettes (Geometry)
Control No.:   3106891

Author:        Schotten, Heinrich, 1856- [from old catalog]
Title:         Ueber einige bemerkenswerte gattungen der
                  hypocykloiden ...
Published:     Marburg, 1883.
Description:   2 p.l., 18 p. diagrs. on 6 pl. 27 x 22 cm.
LC Call No.:   QA623.S37
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   9137942

Author:        Sellentin, Richard. [from old catalog]
Title:         Ueber die rouletten des sphärischen
                  antiparallelogramms ...
Published:     Iserlohn, Druck von J. Baedeker, 1881.
Description:   35 p. diagr. on fold. pl. 22 cm.
LC Call No.:   QA623.S46
Subjects:      Roulettes (Geometry) [from old catalog]
Control No.:   7264779

Author:        Sylvester, James Joseph, 1814-1897. [from old
                  catalog]
Title:         Outline trace of the theory of reducible
                  cyclodes,
Published:     [London, 1869]
Description:   24 p. 22 cm.
LC Call No.:   QA623.S9
Subjects:      Cyclodes.
               Diophantine analysis.
Control No.:   10086099

Author:        Tschumi, Johann.
Title:         Ein Beitrag zur Geschichte und Discussion der
                  Cycloiden / von Johann Tschumi.
Published:     Bern : K. J. Wyss, 1892.
Description:   48 p. : ill. ; 22 cm.
LC Call No.:   QA623.T88
Notes:         Thesis--Universität Bern.
Subjects:      Cycloids.
Control No.:   8207160

Author:        Wetzell, Otto. [from old catalog]
Title:         Die cyclischen curven als einhüllungscurven
                  eines beweglichen kreises ...
Published:     Cassel, Druck von L. Döll, 1880.
Description:   22 p. diagrs. on pl. 22 cm.
LC Call No.:   QA623.W54
Subjects:      Roulettes (Geometry) [from old catalog]
Control No.:   5860330

Author:        Willson, Frederick Newton, 1855-1939.
Title:         A completed nomenclature for the principal
                  roulettes.
Published:     [New York, 1887]
Description:   15 p. incl. diagrs. 27 cm.
LC Call No.:   QA623.W7
Subjects:      Roulettes (Geometry)
Control No.:   8668634

Author:        Wilson, Frederick.
Title:         A treatise on geometry, by Capt. Fred Wilson.
Published:     Portland, Lewis & Dryden printing co., 1896.
Description:   33 p. port. 22 cm.
LC Call No.:   QA623.W74
Subjects:      Kinematic geometry.
Control No.:   6323956

Author:        Wirtz, Carl [Friedrich], 1878- [from old
                  catalog]
Title:         Die Steiner'sche hypocycloide ...
Published:     Strassburg i. E., Buchdruckerei C. & J. Gœller,
                  1900.
Description:   44 p., 1 l. diagrs. on 2 pl. (1 fold.) 24 cm.
LC Call No.:   QA623.W79
Notes:         Vita.
               Inaug.-diss.--Strassburg.
Subjects:      Epicycloids and hypocycloids. [from old catalog]
Control No.:   8201554

Author:        Arndt, Bruno, 1884-
Title:         Über dis Verallgemeinerung des
                  Krümmungsbegriffes für Raumkurven ...
Published:     Leipzig, Druck von A. Hoffmann, 1908.
Description:   117 p., 1 L. 23 cm.
LC Call No.:   QA624.A8
Notes:         Lebenslauf.
               Inaug.-diss.--Königsberg.
Subjects:      Curvature
               Curves of double curvature
Control No.:   9624217

Author:        Greenwood, Joseph Albert. [from old catalog]
Title:         On the curvatures of certain curves in function
                  space,
Published:     [Princeton, N.J., 1935]
Description:   p. 157-166. 26 cm.
LC Call No.:   QA624.G7 1931
Subjects:      Curvature. [from old catalog]
               Hyperspace. [from old catalog]
Control No.:   7832705

Author:        Raussenberger, Otto, 1852- [from old catalog]
Title:         Grundlagen zu einem system vom
                  krümmungscoordinaten ...
Published:     Berlin, A. W. Schade's buchdruckerei (L. Schade)
                  1875.
Description:   2 p.l., 34 p. 21 cm.
LC Call No.:   QA624.R2
Subjects:      Curvature. [from old catalog]
               Coordinates. [from old catalog]
Control No.:   9611400

Author:        Velde, August, 1862-
Title:         Über die curven, deren bogen der tangente des
                  leitstrahlwinkels proportional ist, und die damit verwandten
                  curvenscharen ...
Published:     Halle a./S., Druck von F.W. Kunike, 1895.
Description:   1 p. l., [200]-239, [2] p. diagrs. on 2 fold. pl.
                  23 cm.
Series:        Universität Heidelberg. Dissertationen. v. 47,
                  no. 6
LC Call No.:   QA624.V43
Notes:         Inaug.-diss.--Halle.
               Vita.
               "Separatabdruck aus dem Àrchiv für mathematik
                  und physik.'"
Control No.:   8669696

Author:        Wellmann, H. [from old catalog]
Title:         Bei welcher auf ein rechtwinkeliges
                  coordinatensystem bezogenen linie ist die abscisse jedes
                  punktes die mittlere proportionale zwischen dem
                  krümmungshalbmesser und einer gegebenen constanten länge?
                  ...
Published:     Rostock, C. Baldt's buchdruckerei, 1875.
Description:   26 p. diagrs. on pl. 21 cm.
LC Call No.:   QA624.W4
Subjects:      Curves, Plane. [from old catalog]
Control No.:   10078404

Author:        Bergengren, Johan Oskar Georg. [from old
                  catalog]
Title:         Rektificirbare symmetrische kurven ...
Published:     Lund, H. Ohlssons boktryckeri, 1900.
Description:   1 p.l., 37 p. fold. tab. 23 cm.
LC Call No.:   QA626.B49
Subjects:      Curves -- Rectification and quadrature. [from old
                  catalog]
Control No.:   5862890

Author:        Budérus, Karl Heinrich. [from old catalog]
Title:         Die gleichungen zwischen bogenlänge und
                  neigungswinkel der tangente für die kegelschnittslinien und
                  einige andere curven ...
Published:     Marburg, Druck von J. A. Koch, 1863.
Description:   2 p. l., 36 p. 24 x 20 cm.
LC Call No.:   QA626.B92
Subjects:      Curves -- Rectification and quadrature. [from old
                  catalog]
Control No.:   6328201

Author:        Franck, Paul, 1874-
Title:         Uber die flächeninhalte und bogenlängen von
                  fusspunktkurven und rollkurven ...
Published:     Meissen, Druck von C.E. Klinkicht & sohn, 1899.
Description:   57 p. incl. diagrs. 22 cm.
LC Call No.:   QA626.F82
Notes:         Inaug.-dis.--Leipzig.
               Lebenslauf.
Subjects:      Curves -- Rectification and quadrature.
Control No.:   6796402

Author:        Gregory, David, 1659-1708.
Title:         Exercitatio geomatrica de dimensione figvrarvm
                  sive specimen methodi generalis.
Published:     Edinbvrgi : Ex officinâ typographicâ Jacobi
                  Kniblo, J. Solingensis, & J. Colmarii, 1684.
Description:   2 p. l., 50 p., 1 l. 24 diagrs. on fold. pl. 19 x
                  14 cm.
LC Call No.:   QA626.G82
Subjects:      Curves -- Rectification and quadrature.
Other authors: Pre-1801 Imprint Collection (Library of Congress)
                  DLC
Control No.:   10072943

Author:        Hickethier, Gustav. [from old catalog]
Title:         Bogen, fläche und rotationskörper der cissoide
                  ...
Published:     Jena, Druck von W. Ratz, 1869.
Description:   17 p. diagrs. on pl. 24 cm.
LC Call No.:   QA626.H62
Subjects:      Curves -- Rectification and quadrature. [from old
                  catalog]
               Surfaces -- Areas and volumes. [from old
                  catalog]
Control No.:   8669620

Author:        Janzen, Oscar Alfred Bernhard, 1885-
Title:         Über einige stetige Kurven, über bogenlänge,
                  Linearen inhalt und Flächeninhalt ...
Published:     Konigsberg i. Pr., Buch- und steindr. von O.
                  Kümmel, 1907.
Description:   70, [4] p., 1 l., diagrs. 22 cm.
LC Call No.:   QA626.J4
Notes:         Inaug.-diss.--Königsberg.
               Lebenslauf.
Subjects:      Curves -- Rectification and quadrature.
               Set theory.
Control No.:   8688726

Author:        Janzen, Oscar Alfred Bernhard, 1885-
Title:         Über einige stetige Kurven, über bogenlänge,
                  Linearen inhalt und Flächeninhalt ...
Published:     Konigsberg i. Pr., Buch- und steindr. von O.
                  Kümmel, 1907.
Description:   70, [4] p., 1 l., diagrs. 22 cm.
LC Call No.:   QA626.J4
Notes:         Inaug.-diss.--Königsberg.
               Lebenslauf.
Subjects:      Curves -- Rectification and quadrature.
               Set theory.
Control No.:   8688726

Author:        Krohs, Georg Ferdinand Gotthilf, 1861-
Title:         Die Serretschen kurven sind die einzigen
                  algebraischen von geschlecht null, deren koordinaten
                  eindeutige doppelt-periodische funktionen des bogens der
                  kurve sind ...
Published:     Halle a.S., Hofbuchdruckerei von C.A. Kaemmerer &
                  Co., 1891.
Description:   74 p., 1 l. 23 cm.
LC Call No.:   QA626.K8
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Curves -- Rectification and quadrature.
Control No.:   7743942

Author:        Linthicum, Cadwallader Edwards.
Title:         On the rectification of certain curves, and on
                  certain series involved.
Published:     Baltimore [Md.] J. Murphy & co., 1888.
Description:   28 p. 25 cm.
LC Call No.:   QA626.L76
Notes:         Thesis (PH. D.)--Cornell university.
Subjects:      Curves -- Rectification and quadrature.
Control No.:   6811104

Author:        Smith, Herman Lyle.
Title:         The Minkowski linear measure for a simple
                  rectifiable curve.
Published:     1926.
Description:   27 l. 29 cm.
LC Call No.:   QA626.S56
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
Subjects:      Curves -- Rectification and quadrature.
               Measure theory.
Control No.:   3626213

Author:        Weerth, O. [from old catalog]
Title:         Ueber eine classe von curven,
Published:     Celle, Druck von W. Grossgebauer, 1874.
Description:   24 p. 26 cm.
LC Call No.:   QA626.W3
Subjects:      Curves, Plane. [from old catalog]
Control No.:   10079750

Author:        Dobrachowski, Martin.
Title:         Monographie der Kettenlinie ...
Published:     Bern, Buchdr. K.J. Wyss, 1907.
Description:   54 p. diagrs. 23 cm.
LC Call No.:   QA628.D6
Notes:         Inaug.-diss.--Bern.
Subjects:      Catenary.
Control No.:   8220541

Author:        Newton, H[ubert] A[nson] 1830- [from old
                  catalog]
Title:         On the transcendental curves whose equation is
                  sin y sin my = a sin x sin nx + b;
Published:     [New Haven, Tuttle, Morehouse & Taylor, printers,
                  1875]
Description:   [97]-107 p. diagrs. on 24 pl. 24 cm.
LC Call No.:   QA628.N5
Subjects:      Curves, Transcendental.
Other authors: Phillips, Andrew Wheeler, 1844- [from old
                  catalog] joint author.
Control No.:   8201430

Author:        Palmer, Walter K[eifer] [from old catalog]
Title:         A graphical method for constructing the catenary,
                  with exact drawing-board constructions for all cases of the
                  problem of plotting the curve of a flexible cord of uniform
                  weight.
Published:     Lawrence, Kan., 1898.
Description:   2 p.l., 21 p. diagrs. 24 cm.
LC Call No.:   QA628.P2
Other authors: Catenary. [from old catalog]
Control No.:   10530849

Author:        Rehdans, Wilhelm Joseph. [from old catalog]
Title:         Discussion der transcendenten curven:
Published:     Jena, Druck von W. Ratz, 1877.
Description:   62 p. diagrs. on 2 fold. pl. 21 cm.
LC Call No.:   QA628.R3
Subjects:      Curves, Transcendental.
Control No.:   6328193

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Intorno ad alcune proprieta delle superficie di
                  rivoluzione. Nota del professor Eugenio Beltrami ...
Published:     Roma, Stamperia della S.C. de Prop. fide, 1865.
Description:   11 p. diagr. 30 x 23 cm.
LC Call No.:   QA631.B45
Subjects:      Surfaces. [from old catalog]
Control No.:   9610205

Author:        Kadesch, Adolf Friedrich, 1862-
Title:         Über die einhüllungsflächen von
                  potenzebenenscharen ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1887.
Description:   1 p. l., 33, [1] p. 28 x 22 cm.
LC Call No.:   QA631.K2
Notes:         Inaug.-diss.--Marburg.
               Lebenslauf.
Subjects:      Envelopes (Geometry)
Control No.:   10085923

Author:        Zeigel, Marguerite Lenore, 1907-
Title:         Some invariant properties of a two-dimensional
                  surface in hyperspace / by Marguerite Lenore Zeigel.
Published:     Ann Arbor, Mich. : Edwards Brothers, 1933.
Description:   42 p., 1 leaf ; 21 cm.
LC Call No.:   QA631.Z4 1932
Notes:         Vita.
               "Photo-lithoprint reproduction of author's
                  manuscript."
               Thesis (Ph. D.)--University of Missouri, 1932.
               Bibliography: p. 41-42.
Subjects:      Surfaces.
               Hyperspace.
Control No.:   5949878

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Zur theorie des krümmungsmaasses. Von E.
                  Beltrami ...
Published:     [Leipzig, 1865]
Description:   8 p. 23 cm.
LC Call No.:   QA634.B4
Subjects:      Curvature. [from old catalog]
Control No.:   7736498

Author:        Haas, August, 1853-
Title:         Versuch einer darstellung der geschichte des
                  krümmungsmasses.
Published:     Tübingen, Druck von L. F. Fues, 1881.
Description:   80 p. 25 x 21 cm.
LC Call No.:   QA634.H12
Notes:         Inaug.-dis.--Tübingen.
               "Literatur-nachweisungen" : p. [3]-6.
Subjects:      Curvature.
Control No.:   9606446

Author:        Heckhoff, Max. [from old catalog]
Title:         Die schraubenflächen. Eine monographische studie
                  ...
Published:     Bonn, Universitäts-buchdruckerei von C. Georgi,
                  1894.
Description:   43 p. 22 cm.
LC Call No.:   QA634.H44
Subjects:      Curvature. [from old catalog]
               Surfaces. [from old catalog]
Control No.:   7268843

Author:        Ruoss, Hermann, 1864-
Title:         Die metrischen beziehungen der krümmung
                  reciproker flächen und kurven sowie der flächeninhalte der
                  letzteren ...
Published:     Stuttgart, Druck der J.B. Metzlerschen
                  buchdruckerei, 1891.
Description:   42 p. diagrs. on pl. 22 cm.
Series:        Universität Erlangen. Dissertationen. v. 6, no.
                  13
LC Call No.:   QA634.R94
Notes:         Inaug.-diss.--Erlangen.
Control No.:   6796379

Author:        Willert, Axel Theodor, 1837- [from old catalog]
Title:         Disquisitiones de curvaturis nonnullarum secundi
                  ordinis superficierum ...
Published:     Gryphiswaldiae, typis Frid. Guil. Kunike [1862]
Description:   2 p.l., 110 p. 22 cm.
LC Call No.:   QA634.W71
Subjects:      Curvature. [from old catalog]
               Quadrics. [from old catalog]
Control No.:   9606422

Author:        Ackermann, Karl Christian, 1841- [from old
                  catalog]
Title:         Ueber inhalt und oberfläche von
                  rotationskörpern ...
Published:     Marburg, 1864.
Description:   15 p. diagrs. on pl. 24 cm.
LC Call No.:   QA636.A18
Subjects:      Surfaces -- Areas and volumes. [from old
                  catalog]
Control No.:   7731632

Author:        Kepler, Johannes, 1571-1630.
Uniform Title: Nova stereometria. German
Title:         Neue stereometrie der fässer, besonders der in
                  der form am meisten geeigneten österreichischen, und
                  gebrauch der kubischen visierrute. Mit einer ergänzung zur
                  stereometrie des Archimedes. Von Johannes Kepler ... Linz
                  1615. Druck von Johannes Plank. Aus dem lateinisehen übers.
                  und hrsg. von R. Klug. Mit 29 figuren im text.
Published:     Leipzig, W. Engelmann, 1908.
Description:   130 p. diagrs. 19 cm.
Series:        Ostwald's Klassiker der exakten wissenschaften.
                  nr. 165
LC Call No.:   QA636.K5
Notes:         "Ergänzung zu Archimedes. Stereometrie der den
                  konoiden und sphäroiden am nächsten stehen den körper": p.
                  5-44.
Subjects:      Mensuration.
               Surfaces -- Areas and volumes.
               Gaging.
Other authors: Klug, R. (Rudolf), 1873-1952.
               Archimedes.
Series Entry:  Ostwald's Klassiker der exakten Wissenschafter ;
                  Bd. 165.
Control No.:   1689643

Author:        Pietsch, Karl. [from old catalog]
Title:         Die rotationsfläche von grösstem oder kleinstem
                  volumen.
Published:     Oppeln, Druck von E. Raabe, 1881.
Description:   56 p. diagrs. 22 cm.
LC Call No.:   QA636.P62
Subjects:      Surfaces. [from old catalog]
               Maxima and minima. [from old catalog]
Control No.:   7734252

Author:        Szymaânski, Peter, 1851- [from old catalog]
Title:         Determinatio areae et voluminis duperficiei
                  definitae per aequationem: (x>2 + y>2 +
                  z>2)>2-a>2x>2-b>2y>2-c>2z>2=o ...
Published:     Berolini, typis expressit G. Schade (O. Francke)
                  [1876]
Description:   2 p.l., 24, [2] p. 22 cm.
LC Call No.:   QA636.S9
Subjects:      Surfaces -- Areas and volumes. [from old
                  catalog]
Control No.:   6796393

Author:        Foster, Malcolm Cecil. [from old catalog]
Title:         Rectilinear congruences referred to special
                  surfaces,
Published:     Princeton, N.J. [1923]
Description:   p. [159]-180. 26 cm.
LC Call No.:   QA639.F6 1921
Subjects:      Congruences (Geometry) [from old catalog]
Control No.:   6858090

Author:        Kendall, Claribel.
Title:         Congruences determined by a given surface ... by
                  Claribel Kendall ...
Published:     [Baltimore, 1923]
Description:   1 p.l., 25-41, [1] p. 26 cm.
LC Call No.:   QA639.K4
Notes:         Thesis (PH. D.)--University of Chicago, 1921.
               Vita.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from American journal of mathematics,
                  vol. XLV, no. 1, January, 1923."
Subjects:      Congruences (Geometry)
Control No.:   3108017

Author:        Ahl, Fritz, 1878- [from old catalog]
Title:         Untersuchungen über geodätische linien ...
Published:     Kiel, Druck von P. Peters, 1901.
Description:   50, [2] p. 23 cm.
LC Call No.:   QA643.A28
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   9137656

Author:        Aoust, M. l'abbé (Louis Stanislas Xavier
                  Barthélemy), 1814-1885.
Title:         Analyse infinitésimale des courbes tracées sur
                  une surface quelconque; par M. l'abbé Aoust.
Published:     Paris, Gauthier-Villars, 1869.
Description:   xl, 314 p. diagrs. 23 cm.
LC Call No.:   QA643.A6
Subjects:      Curves on surfaces.
Control No.:   6795348

Author:        Beal, Frederick Wahn, 1879- [from old catalog]
Title:         Normal congruences determined by centers of
                  geodesic curvature ...
Published:     [Baltimore] 1913.
Description:   p. [10]-36. 29 cm.
LC Call No.:   QA643.B4
Subjects:      Curves on surfaces. [from old catalog]
               Curvature. [from old catalog]
Control No.:   10109390

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Sulla teoria delle linee geodetiche. Nota del
                  Prof. Eugenio Beltrami.
Published:     1868.
Description:   p. 708-718.
LC Call No.:   AS222.L616
Notes:         In: R. Istituto lombardo di scienre e lettere,
                  Milan. Rendiconti. Milano, 1868. 24 cm., ser. 2., v. 1, p.
                  708-718.
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   9137918

Author:        Bliss, Gilbert Ames, 1876-1951.
Title:         The geodesic lines on the ancho ring / by Gilbert
                  Ames Bliss.
Published:     [Cambridge? Mass.], 1902.
Description:   23, [1] p. : ill. ; 30 cm.
LC Call No.:   QA643.B64
Notes:         Autobiography.
               Read before the Chicago section of the American
                  Mathematical Society, Dec. 27, 1900.
               From the Annals of mathematics, second series,
                  vol. 4, no. 1.
               Thesis (Ph. D.)--University of Chicago.
Subjects:      Curves on surfaces.
Control No.:   6325225

Author:        Cronin, Sarah Elizabeth.
Title:         Geometric properties completely characterizing
                  all the curves in a plane along which the constrained motion
                  is such that the pressure is proportional to the normal
                  component of the acting force / by Sarah Elizabeth Cronin.
Published:     Lancester, Pa. : Press of the new era printing
                  company, 1917.
Description:   viii, 34 p. ; 25 cm.
LC Call No.:   QA643.C8
Notes:         Includes vita on p. 34.
               Thesis (Ph. D.)--Columbia University, 1917.
Subjects:      Geometry, Differential.
               Dynamics.
Control No.:   10118834

Author:        Davisson, Schuyler Colfax. [from old catalog]
Title:         Ueber die geodätische linie der mannigfaltigkeit
                  dsp2s=dxp2s+5inp2sxdyp2s+dzp2s...
Published:     Tübingen, Druck von H. Laupp, jr., 1900.
Description:   22 p. diagrs. 24 cm.
LC Call No.:   QA643.D26
Subjects:      Curves on surfaces.
Control No.:   7264756

Author:        Douglas, Jesse, 1897-1965.
Title:         On certain two-point properties of general
                  families of curves,
Published:     [Lancaster, Pa. and New York, 1921]
Description:   1 p.l., p. 289-310, 1. l. 28 cm.
LC Call No.:   QA643.D6
Subjects:      Curves. [from old catalog]
               Geometry, Differential. [from old catalog]
Control No.:   6385722

Author:        Grant, Anna, 1903- [from old catalog]
Title:         Surfaces of negative curvature and permanent
                  regional transitivity
Published:     [Durham, N.C., 1939]
Description:   1 p.l., p. 207-229, 1 l. 26 cm.
LC Call No.:   QA643.G84 1937
Subjects:      Geometry, Differential. [from old catalog]
               Surfaces. [from old catalog]
Control No.:   7378126

Author:        Groscurth, Ferdinand, 1859-
Title:         Über parabolische coordinaten und die
                  geodätischen linien auf dem elliptischen paraboloid ...
Published:     1887.
Description:   1 p. l., 21 p., 1 l. 26 x 22 cm.
LC Call No.:   QA643.G87
Notes:         Inaug.-dis.--Marburg.
               Vita.
Subjects:      Curves on surfaces.
               Co-ordinates.
Control No.:   7264487

Author:        Grove, Vernon Guy, 1890-
Title:         A theory of a general net on a surface.
Published:     1925.
Description:   38 l. illus. 29 cm.
LC Call No.:   QA643.G88
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
Subjects:      Curves on surfaces.
               Nets (Mathematics)
Control No.:   766075

Author:        Hammond, Edward Sanford, 1893-
Title:         Periodic conjugate nets ... by Edward S. Hammond
                  ...
Published:     [Princeton, N.J., 1921]
Description:   1 p. l., p.238-261. 24 cm.
LC Call No.:   QA643.H3
Notes:         Thesis (Ph. D.)--Princeton University, 1920.
               "Reprinted from the Annals of mathematics, second
                  series, vol. 22, no. 4, June, 1921."
Subjects:      Curves on surfaces.
Control No.:   8254797

Author:        Hasse, Helmut, 1898- [from old catalog]
Title:         Eine Verallgemeinerung des
                  Dreipunktdeckungsverfahrens; bearb. in der Forschungsabt. der
                  Amtsgruppe Mar-Rüst/FEP im Auftrage der Arbeitsgemeinschaft
                  IX.
Published:     [n.p., 1944]
Description:   73 p. diagrs. 30 cm.
LC Call No.:   QA643.H33
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   6025827

Author:        Hoffmann, Otto, of Beeskow. [from old catalog]
Title:         Ueber sphärische curven ...
Published:     Göttingen, Druck der Dieterichschen
                  univ.-buchdruckerei, W. F. Kaestner, 1876.
Description:   44 p. 21 cm.
LC Call No.:   QA643.H7
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   6332245

Author:        Issaly, abbé, (Pierre-Adolphe), b. 1833.
Title:         Principes fondamentaux de la théorie des
                  pseudo-surfaces / par M. l'abbé Issaly.
Published:     Paris : A. Hermann, 1902.
Description:   vi, 107 p. : ill. ; 26 cm.
LC Call No.:   QA643.I873 1902
Notes:         "Une complète refonte des deux mémoires ...
                  publiés ... en 1888 et 1889, dans le Bulletin de la
                  Société mathématique de France, sous ces titres: 1ê
                  Nouveaux principes de la théorie des congruences de droites;
                  2ê Etude géométrique de la courbure des pseudo-surfaces"--
                  P. [v].
               BN LXXVI, column 57
               Livre 1. Etude des diverses lignes qu'on peut
                  tracer sur une pseudo-surface -- Livre 2. Propriétés
                  géométriques des pseudo-surfaces.
Subjects:      Curves on surfaces.
               Geometry, Infinitesimal.
Other titles:  Bulletin de la Société mathématique de
                  France.
Control No.:   12561593

Author:        Issaly, abbé, (Pierre-Adolphe), b. 1833.
Title:         Les pseudo-surfaces appliquées à la
                  généralisation ou à l'amendement de diverses théories
                  classiques, issues de calcul infinitésimal / par M. l'abbé
                  Issaly.
Published:     Paris : Librairie scientifique A. Hermann, 1906.
Description:   viii, 85 p. ; 26 cm.
LC Call No.:   QA643.I873 1906
Notes:         "Complément aux trois précédents ouvrages de
                  l'auteur sur les pseudo-surfaces."
               NUC pre-1956 NI 0173789
               1re ptie. Théories de géométrie
                  infinitésimale à généraliser au moyen des pseudo-surfaces
                  -- 2e ptie. Théories d'analyse et de mécanique à amender
                  au moyen des pseudo-surfaces -- 3e ptie. Extension aux
                  systèmes triples de pseudo-surfaces coordonnées des
                  résultats précédemment obtenus.
Subjects:      Curves on surfaces.
               Geometry, Infinitesimal.
Control No.:   12624055

Author:        Kempe, Hermann, 1861-
Title:         Kugel- und kegelfläche in ihren beziehungen zu
                  den schwingungskurven ...
Published:     Marburg, C.L. Pfeil'sche
                  universitäts-buchdruckerei, 1887.
Description:   56 p., 1 l. diagrs. on fold. pl. 24 cm.
LC Call No.:   QA643.K32
Notes:         Inaug.-diss.--Marburg.
               Lebenslauf.
Subjects:      Curves on surfaces.
Control No.:   9139320

Author:        Kimball, Bradford Fisher, 1896- [from old
                  catalog]
Title:         Geodesics on a toroid ... by Bradford F.
                  Kimball.
Published:     Ithaca, N.Y. [1926?]
Description:   [6] p. 23 cm.
LC Call No.:   QA643.K5 1926
Notes:         Abstract of thesis (Ph. D.)--Cornell university,
                  1926.
Subjects:      Curves on surfaces.
Control No.:   13194663

Author:        Kraemer, Karl i. e. Friedrich Karl, 1880- [from
                  old catalog]
Title:         Beitrag zur analytischen untersuchung sphärisher
                  kunven...
Published:     Marburg, Universität-buchdruckerei von J. A.
                  Koch, 1902.
Description:   35, [1] p. diagrs. 22 cm.
LC Call No.:   QA643.K88
Subjects:      Curves on surfaces. [from old catalog]
               Sphere. [from old catalog]
Control No.:   6332224

Author:        Kreuschmer, Robert. [from old catalog]
Title:         Ueber einige eigenschaften der kürzesten linie
                  und der logarithmischen spirale auf dem mantel eines normalen
                  krieskegels ...
Published:     Jena, Druck von W. Ratz, 1874.
Description:   23 p. 26 x 21 cm.
LC Call No.:   QA643.K92
Subjects:      Curves on surfaces. [from old catalog]
               Cone. [from old catalog]
Control No.:   5860308

Author:        Krüger, Louis i.e. Johann Heinrich Louis, 1857-
                  [from old catalog]
Title:         Die geodätische linie des sphäroids und
                  untersuchung darüber,
Published:     Berlin, A. W. Schade's buchdruckerei (L. Schade),
                  1883.
Description:   28 p. diagrs. 25 cm.
LC Call No.:   QA643.K94
Subjects:      Curves on surfaces. [from old catalog]
               Ellipsoid. [from old catalog]
Control No.:   8201531

Author:        Langenbeck, Rudolf August Justus, 1854-
Title:         Ueber diejenigen geodätischen linien auf dem
                  dreiaxigen ellipsoid, welche durch einen der nabelpunkte
                  desselben gehen.
Published:     Göttingen, Druck der Dieterischen univ.
                  buchdruckerei, W. F. Kaestner, 1877.
Description:   39 p. 21 cm.
LC Call No.:   QA643.L27
Notes:         Inaug.-dis.--Göttingen.
Subjects:      Curves on surfaces.
               Ellipsoid.
Control No.:   3106881

Author:        Lassalle, Edmund. [from old catalog]
Title:         Ueber einen satz von den krümmunsglinien der
                  flächen zweiten grades ...
Published:     Tübingen, Druck von H. Laupp, 1885.
Description:   31 p. 21 cm.
LC Call No.:   QA643.L34
Subjects:      Curves on surfaces. [from old catalog]
               Quadrics. [from old catalog]
Control No.:   8669671

Author:        Ling, Donald Percy, 1912- [from old catalog]
Title:         Geodesics on surfaces of revolution, by Donald
                  Percy Ling.
Published:     [n.p., 1946]
Description:   1 p. l., 415-429, [1] p. 28 cm.
LC Call No.:   QA643.L47
Notes:         Thesis (Ph. D.)--Columbia university, 1944.
               "Reprinted from the Transactions of the American
                  mathematical society, vol. 59, no. 3 ... May, 1946."
Subjects:      Geometry, Differential.
               Curves on surfaces.
Control No.:   13194166

Author:        Mangoldt, Hans [Carl Friedrich] von, 1854- [from
                  old catalog]
Title:         Über diejenigen punkte auf positiv gekrümmten
                  flächen, welche die eigenschaft haben, dass die von ihnen
                  ausgehenden geodätischen linien nie aufhören, kürzeste
                  linien zu sein ...
Published:     Berlin, Druck von G. Reimer, 1881.
Description:   33, [1] p. diagrs. on fold. pl. 28 x 23 cm.
LC Call No.:   QA643.M27
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   9138004

Author:        Meacham, Edgar D., b. 1888.
Title:         Properties of surfaces whose osculating ruled
                  surfaces belong to linear complexes ... by Edgar D. Meacham
                  ...
Published:     Chicago, Ill., 1924.
Description:   19 p. 24 cm.
LC Call No.:   QA643.M4 1922
Notes:         Thesis (PH. D.)--University of Chicago, 1922.
               "Private edition, distributed by the University
                  of Chicago libraries."
Subjects:      Curves on surfaces.
               Complexes.
Control No.:   3108062

Author:        Morrison, Frank Marion, b. 1871.
Title:         On the relation between some important notions of
                  projective and metrical differential geometry ... by Frank
                  Marion Morrison ...
Published:     [Baltimore, 1917]
Description:   1 p.l., p. [199]-220, 1 l. 31 cm.
LC Call No.:   QA643.M85
Notes:         Thesis (Ph. D.)--University of Chicago, 1913.
               Vita.
               "A private edition distributed by the University
                  of Chicago libraries."
               "Reprinted from American journal of mathematics,
                  vol. XXXIX, no. 2, April, 1917."
Subjects:      Geometry, Differential.
               Projective differential geometry.
Control No.:   4053247

Author:        Moser, Christian, 1861-
Title:         Über Gebilde, welche durch Fixation einer
                  sphärischen Curve und Fortbewegung des Projectionscentrums
                  entstehen ... von Ch. Moser.
Published:     Bern, Buchdruckerei K.J. Wyss, 1887.
Description:   31 p. 23 cm.
LC Call No.:   QA643.M89
Notes:         Inaug.-diss.-Bern.
Subjects:      Curves on surfaces
               Map projection.
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.13.
Control No.:   5864377

Author:        Pfister, Arthurs, 1881- [from old catalog]
Title:         Die geodätischen linien einer klass von
                  flächen,
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buch-druckerei (W. F. Kaestner) 1904.
Description:   44, [4] p. diagr. 24 cm.
LC Call No.:   QA643.P52
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   8205160

Author:        Pizzetti, Paolo, 1860- [from old catalog]
Title:         Sulla curva d'allineamento.
Published:     [Napoli, B. Pellerano, 1883]
Description:   15 p. diagr. on pl. 29 cm.
LC Call No.:   QA643.P7
Subjects:      Curves on surfaces.
               Earth -- Figure.
Control No.:   10081569

Author:        Quidde, Walter, 1880- [from old catalog]
Title:         Über Gauss'sche kreise auf rotationsfläschen
                  ...
Published:     Kiel, Druck von Schmidt & Klaunig, 1905.
Description:   85, [1] p., 1 l. diagrs. 24 cm.
LC Call No.:   QA643.Q6
Notes:         Inaug.-diss.--Kiel.
               Lebenslauf.
Subjects:      Curves on surfaces.
Control No.:   12928196

Author:        Reaves, Samuel Watson.
Title:         Metric properties of flecnodes on ruled surfaces
                  ... by Samuel Watson Reaves ...
Published:     [Napoli, 1917]
Description:   2 p.l., [3]-28 p. 24 cm.
LC Call No.:   QA643.R4
Notes:         Thesis (PH.D.)--University of Chicago, 1915.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from the Giornale di matematiche di
                  Battaglini, vol. LV (1917), 8p0s della 3a serie."
Subjects:      Curves on surfaces.
Control No.:   4526344

Author:        Renard, M. (Nicolas), 1823-1880.
Title:         Thèse d'analyse : courbure des surfaces : thèse
                  d'astronomie : sur le mouvement des planètes dans le cas des
                  perturbations / par M. Renard.
Published:     Paris : Mallet-Bachelier, 1856.
Description:   44 p. ; 27 cm.
LC Call No.:   QA643.R4x 1856
Notes:         "Thèses présentées à la Faculté des sciences
                  de Paris pour obtenir le grade de docteur ès sciences ...
                  soutenues le août 1856 devant la commission d'examen."
Subjects:      Curves on surfaces.
               Perturbations (Astronomy)
Other titles:  Courbure des surfaces.
               Sur le mouvement des planètes dans le cas des
                  perturbations.
Control No.:   511376

Author:        Richmond, Donald Everett, 1898-
Title:         Geodesics on surfaces of genus zero with knobs
                  ... by Donald Everett Richmond.
Published:     Ithaca, N.Y. [1926?]
Description:   [5] p. 23 cm.
LC Call No.:   QA643.R5 1926
Notes:         Abstract of thesis (Ph.D.)--Cornell university,
                  1926.
Subjects:      Curves on surfaces.
Control No.:   13194680

Author:        Sager, Paul.
Title:         Übersicht Über die Entwickelung der Theorie der
                  geodätischen Linien seit Gauss ...
Published:     Rostock, C. Hinstorffs Buchdruckerei, 1903.
Description:   89 p. diagrs. 22 cm.
LC Call No.:   QA643.S13
Notes:         Inaug.-diss.--Rostock.
               "Literatur": p. [68]-89.
Subjects:      Curves on surfaces
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.16.
Control No.:   10080018

Author:        Schulz, Karl. [from old catalog]
Title:         Traité mathématique d'un théorème de la
                  théorie des lignes de courbure sur les surfaces du second
                  degré ...
Published:     Putbus, A. Knaak, imprimeur, 1873.
Description:   2 p.l., 34 p. diagrs. 27 cm.
LC Call No.:   QA643.S3
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   7264705

Author:        Schwering, Karl [Maria Johann Gerhard], 1846-
                  [from old catalog]
Title:         De linea brevissima in elliptica paraboloide sita
                  ...
Published:     Berolini, typis expressit G. Schade [1869]
Description:   2 p. l., 32 p. 25 x 20 cm.
LC Call No.:   QA643.S41
Subjects:      Curves on surfaces. [from old catalog]
               Paraboloid. [from old catalog]
Control No.:   9606447

Author:        Simpson, Thomas McNider, b. 1882.
Title:         Relations between the metric and projective
                  theories of space curves ... by Thomas McNider Simpson, jr.
Published:     Chicago, Illinois, 1920.
Description:   1 p.l., 26 p. 29 cm.
LC Call No.:   QA643.S5
Notes:         Thesis (Ph. D.)--University of Chicago, 1917.
               "Private edition, distributed by the University
                  of Chicago libraries."
Subjects:      Curves on surfaces.
               Projective differential geometry.
Control No.:   1690202

Author:        Sperry, Pauline, b. 1885.
Title:         Properties of a certain projectively defined
                  two-parameter family of curves on a general surface ... by
                  Pauline Sperry ...
Published:     [Baltimore, 1918]
Description:   1 p.l., p. [213]-224. 31 cm.
LC Call No.:   QA643.S7
Notes:         Thesis (Ph. D.)--University of Chicago, 1916.
               "Private edition distributed by the University of
                  Chicago libraries, Chicago, Illinois, 1918."
               "Reprinted from American journal of mathematics,
                  vol. XL, no. 2, April, 1918."
Subjects:      Curves on surfaces.
Control No.:   4053286

Author:        Stehle, Ad. [from old catalog]
Title:         Ueber fusspunkten-curven auf der oberfläche
                  eines geraden krieskegels ...
Published:     Göttingen, Druck der Gebruüder Hofer, 1873.
Description:   39 p. diagrs. on fold. pl. 21 cm.
LC Call No.:   QA643.S81
Subjects:      Curves on surfaces. [from old catalog]
               Cone. [from old catalog]
Control No.:   7267365

Author:        Stetson, John Minor, 1887- [from old catalog]
Title:         Conjugate systems of curves on a surface both of
                  whose Laplace transforms are lines of curvature,
Published:     Princeton, 1917.
Description:   1 p. l., [1], 106-126 p. 26 cm.
LC Call No.:   QA643.S8
Subjects:      Curves on surfaces. [from old catalog]
Control No.:   10120291

Author:        Sullivan, Charles Thompson, b. 1884.
Title:         Properties of surfaces whose asymptotic curves
                  belong to linear complexes ... by Charles Thompson Sullivan.
Published:     Lancaster, Pa., Press of the New era printing
                  company, 1912.
Description:   1 p.l., p. 167-196, 1 l. 28 cm.
LC Call No.:   QA643.S85
Notes:         Thesis (Ph. D.)--University of Chicago, 1912.
               Vita.
Subjects:      Curves on surfaces.
               Complexes.
Control No.:   2161960

Author:        Tuller, Annita, 1910-
Title:         The measure of transitive geodesics on certain
                  three-dimensional manifolds, by Annita Tuller.
Published:     [Durham, N.C., 1938]
Description:   1 p. l., p. 78-94, 1 l., 26 cm.
LC Call No.:   QA643.T8 1937
Notes:         Vita.
               "Reprinted from Duke mathematical journal, vol.
                  4, no. 1, March, 1938."
               Thesis (Ph. D.)--Bryn Mawr college, 1937.
               Bibliography: p. 94.
Subjects:      Curves on surfaces.
               Geometry, Non-Euclidean.
Control No.:   10183951

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Sulle proprietà generali delle superficie d'area
                  minima. Memoria del Prof. E. Beltrami.
Published:     Bologna, Tipi Gamberini e Parmeggiani, 1868.
Description:   73 p. 32 cm.
LC Call No.:   QA644.B4
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   5859288

Author:        Bohnert, Felix i. e. Eduard Felix Philipp, 1862-
                  [from old catalog]
Title:         Bestimmung einer speciellen periodischen
                  minimalfläche,
Published:     Göttingen, Druck von W. F. Kästner, 1888.
Description:   2 p. l., 43, [1] p. diagrs. on pl. 24 cm.
LC Call No.:   QA644.B67
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   6333380

Author:        Davids, Norman. [from old catalog]
Title:         Minimal surfaces spanning closed manifolds and
                  having prescribed topological position ...
Published:     [Baltimore, 1942]
Description:   1 p.l., 348-362 p. incl. diagrs. 25 cm.
LC Call No.:   QA644.D3
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   6448837

Author:        Glaser, Robert. [from old catalog]
Title:         Ueber die minimalflächen ...
Published:     Tübingen, Druck von H. Laupp jr., 1891.
Description:   42 p. 23 cm.
LC Call No.:   QA644.G54
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   6328177

Author:        Götting, Edurad, 1860- [from old catalog]
Title:         Bestimmung einer speciellen gruppe nich
                  algebrascher minimalflächen,
Published:     Göttingen, Druck der Dieterichschen
                  univ.-buchdruckerei W. F. Kästner, 1887.
Description:   42 p., 1 l. 24 cm.
LC Call No.:   QA644.G59
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   6327928

Author:        Hancock, Harris, 1867- [from old catalog]
Title:         On minimal surfaces,
Published:     Worcester, Mass., 1896-97.
Description:   2 v. 25 cm.
LC Call No.:   QA644.H2
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   9127502

Author:        Henneberg, Lebrecht, 1850- [from old catalog]
Title:         Ueber solche minimalflächen, welche eine
                  vorgeschriebene ebene curve zur geodätischen linie haben
                  ...
Published:     Zürich, Druck von Zürcher und Furrer, 1875.
Description:   68 p. 21 cm.
LC Call No.:   QA644.H5
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   7732796

Author:        Herzog, Albin. [from old catalog]
Title:         Bestimmung einiger speciellen minimalflächen
                  ...
Published:     Zürich, Druck von Zürcher und Furrer, 1875.
Description:   2 p. l., 38 p. 23 cm.
LC Call No.:   QA644.H6
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   10074682

Author:        Iuga, Georg Eugen, 1871-
Title:         Die cyklischen Minimalflächen ...
Published:     Strassburg, Buchdruckerei C. & J. Gœller, 1898.
Description:   39, [1] p. diagrs. 23 cm.
LC Call No.:   QA644.I9
Notes:         Lebenslauf.
               Inaug.-diss.--Strassburg.
Subjects:      Minimal surfaces.
Other titles:  [Pamphlets. Mathematics. 1841-1906] v. 10.
Control No.:   7254357

Author:        Nelson, Alfred Lewis, 1891-
Title:         Plane nets with equal invariants ... by Alfred
                  Lewis Nelson ...
Published:     [Palermo, 1916]
Description:   1 p.l., 25 p., 1 l. 24 cm.
LC Call No.:   QA644.N37
Notes:         Thesis (Ph. D.)-- University of Chicago, 1915.
               Vita.
               "A private edition distributed by the University
                  of Chicago libraries."
               "Reprinted from Rendiconti del Circolo matematico
                  di Palermo, vol. XLI, 1916."
Subjects:      Geometry, Differential.
Control No.:   2634863

Author:        Neovius, E. R. (Edvard Rudolf), 1851-
Title:         Bestimmung zweier speciellen periodischen
                  Minimalflächen : auf welchen unendlich viele gerade linien
                  und unendlich viele ebene geodätische Linien liegen / von
                  E.R. Neovius ; Nebst vier Figurentafeln und zwei
                  Photographien.
Published:     Helsingfors : J.C. Frenckell & sohn, 1883.
Description:   viii, 117 p. : ill. ; 24 cm.
LC Call No.:   QA644.N4
Notes:         Zur Erlangung der venia legendi--Universität
                  Helsingfors.
Subjects:      Minimal surfaces.
Control No.:   8200491

Author:        Peche, Martin i. e. Wilhelm August Martin, 1866-
                  [from old catalog]
Title:         Analytische bestimmung aller minimalflächen,
                  welche eine schaar reeler parabein enthalten ...
Published:     Göttingen, Druck der Dieterich'schen
                  univ.-buchdruckerei (W. F. Kaestner), 1891.
Description:   p. cm.
LC Call No.:   QA644.P36
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   6796378

Author:        Rebstein, Jacob, 1868-
Title:         Bestimmung aller reellen Minimalflächen : die
                  eine Schaar ebener Curven enthalten, denen auf der
                  Gauss'schen Kugel die Meridiane entsprechen / von Jacob
                  Rebstein.
Published:     Berlin, 1895.
Description:   29, [3] p. ; 24 cm.
LC Call No.:   QA644.B20
Notes:         Vita.
               Thesis--Berlin.
Subjects:      Minimal surfaces.
Control No.:   9606421

Author:        Riemann, Bernhard, 1826-1866.
Title:         Ueber die Fläche vom kleinsten Inhalt bei
                  gegebener Begrenzung : eine Abhandlung / von Bernhard Riemann
                  ; bearbeitet von K. Hattendorff.
Published:     Göttingen : In der Dieterichschen Buchhandlung,
                  1867.
Description:   52 p. ; 28 cm.
LC Call No.:   QA644.R47 1867
Notes:         "Aus dem dreizehnten Bande der Abhandlungen der
                  Königlichen Gesellschaft der Wissrnschaften zu Göttingen."
Subjects:      Minimal surfaces.
               Mappings (Mathematics)
Other authors: Hattendorff, Karl, 1834-1882.
Control No.:   3813707

Author:        Ritter, Irving F., 1902- [from old catalog]
Title:         Solution of Schwarz' problem concerning minimal
                  surfaces
Published:     [n.p., 1940]
Description:   [49]-62 p. 28 cm.
LC Call No.:   QA644.R5
Subjects:      Surfaces, Minimal. [from old catalog]
Other titles:  Schwarz' problem.
Control No.:   8326784

Author:        Schilling, Carl [David], 1857-
Title:         Die minimalflächen fünfter klasse mit dem
                  stereoscopbild eines modells derselben ...
Published:     Göttingen, Druck von E.A. Huth, 1880.
Description:   53, [1] p., 1 l. l pl. 21 cm.
LC Call No.:   QA644.S33
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   10074736

Author:        Schondorff, Arthur.
Title:         Über die minimalfläche, die von einem
                  doppelt-gleichschenkligen räumlichen viereck begrenzt wird
                  ...
Published:     Göttingen, Druck (der univ.-buchdruckerei) von
                  W.F. Kaestner, 1868.
Description:   52 p. 27 x 22 cm.
LC Call No.:   QA644.S37
Notes:         Preisschrift--Göttingen.
Subjects:      Minimal surfaces.
Control No.:   2161188

Author:        Sinclair, Mary Emily.
Title:         Concerning a compound discontinuous solution in
                  the problem of the surface of revolution of minimum area ...
Published:     Salem, Mass., The Salem press co., 1909.
Description:   1 p.l., p. 55-80 diagrs. 24 cm.
LC Call No.:   QA644.S6
Notes:         Thesis (Ph. D.)--University of Chicago.
               Reprinted from the Annals of mathematics, second
                  sries, v. 10, no. 2, p. 55-80, January, 1909.
Subjects:      Minimal surfaces.
Control No.:   273114

Author:        Tegengren, Gustaf. [from old catalog]
Title:         Bestämning af ett enkelt sammanhängande
                  minimalytstycke,
Published:     Helsingfors, J. Simelii arfvingars boktryckeri
                  aktiebolag, 1904.
Description:   x p., 1 l., 82 p., 1 l. diagrs. on IV pl., III
                  fold. tab. 29 x 23 cm.
LC Call No.:   QA644.T25
Subjects:      Surfaces, Minimal. [from old catalog]
Control No.:   8215939

Author:        Tenius, Gustav Carl Heinrich, 1863-
Title:         Bestimmung einer speziellen minimalfläche ...
Published:     1888.
Description:   38, [2] p. 22 cm.
LC Call No.:   QA644.T29
Notes:         Inaug.-diss.--Marburg.
               Lebenslauf.
Subjects:      Surfaces, Minimal.
Control No.:   7264755

Author:        Tallqvist, Hjalmar, 1870-
Title:         Bestimmung einiger minimalflächen, deren
                  begrenzung gegeben ist ...
Published:     Helsingfors, Gedruckt bei J.C. Frenckel & sohn,
                  1890.
Description:   3 p.l., 79 p. 2 pl. 30 x 23 cm.
LC Call No.:   QA644.T14
Notes:         Inaug.-dis.--Helsingfors.
Subjects:      Minimal surfaces.
Control No.:   3579427

Author:        Thienemann, Wilhelm, 1857- [from old catalog]
Title:         Ueber eine transcendente minimalfläche, welche
                  eine schar algebraischer raumcurven vierten grades enthält
                  ...
Published:     Leipzig, Druck von B. G. Teubner, 1890.
Description:   22 p., 1 l. 24 cm.
LC Call No.:   QA644.T43
Subjects:      Surfaces, Minimal. [from old catalog]
               Curves of double curvature. [from old catalog]
Control No.:   5860307

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Risoluzione di un problema relativo alla teoria
                  delle superficie gobbe. Del Prof. E. Beltrami.
Published:     [Roma, 1865]
Description:   12 p. 30 cm.
LC Call No.:   QA645.B45
Subjects:      Surfaces. [from old catalog]
Control No.:   9141724

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Teoria fondamentale degli spazii di curvatura
                  costante. Memoria del Prof. Eugenio Beltrami ...
Published:     Milano, Tip. di F. Zanetti, 1868.
Description:   1 p.l., 24 p. 29 cm.
LC Call No.:   QA645.B47
Subjects:      Surfaces of constant curvature. [from old
                  catalog]
Control No.:   9613050

Author:        Betz, Ebon Elbert, 1914-
Title:         Accessibility and separation by simple closed
                  curves, [by] Ebon Elbert Betz.
Published:     Philadelphia, 1940.
Description:   1 p. l., [8] p. 25 cm.
LC Call No.:   QA645.B49 1940
Dewey No.:     513.7
Notes:         Thesis (Ph. D.)--University of Pennsylvania,
                  1939.
               "Reprinted from the American journal of
                  mathematics, vol. LXIII, number 1, p. 127-135."
Subjects:      Curves.
               Hyperspace.
Control No.:   6913202

Author:        Bockwoldt, Georg.
Title:         Ueber die Enneper'schen Flächen mit constantem,
                  positivem Krümmungsmaas, bei denen die eine Schaar der
                  Krümmungslinien von ebenen Curven gebildet wird ...
Published:     Göttingen, Druck der Dieterichschen
                  Univ.-Buchdruckerei, W.F. Kaestner, 1878.
Description:   32 p. 21 cm.
LC Call No.:   QA645.B66
Notes:         Inaug.-diss.--Göttingen.
Subjects:      Surfaces
Other titles:  Über die Enneper'schen Flächen mit constantem,
                  positivem Krümmungsmaas.
               [Pamphlets. Mathematics. 1841-1906] v.4.
Control No.:   6800452

Author:        Coddington, Emily.
Title:         A brief account of the historical development of
                  pseudospherical surfaces from 1827 to 1887...
Published:     Lancaster, Pa. : Press of the New era printing
                  company, 1905.
Description:   1 p. l. 74 p. ; 28 cm.
LC Call No.:   QA645.C66
Notes:         Thesis (PH. D.)--Columbia university.
               "Books of reference": p. 1-8.
Subjects:      Surfaces of constant curvature.
Control No.:   6802278

Author:        Dobriner, Hermann, 1857-
Title:         Die Flächen constanter Krümmung mit einem
                  System sphärischer Krümmungslinien dargestellt mit Hilfe
                  von Thetafunctionen zweier Variabeln ...
Published:     Marburg, 1886.
Description:   2 p. l., 32 p., 1 l. 28 x 22 cm.
LC Call No.:   QA645.D63
Notes:         Inaug.-Dis.--Marburg.
               Lebenslauf.
Subjects:      Surfaces.
               Functions, Theta.
Control No.:   8201283

Author:        Hedley, James Walter. [from old catalog]
Title:         Ruled surfaces whose flecnode curves belong to
                  linear complexes.
Published:     1924.
Description:   49 l. 29 cm.
LC Call No.:   QA645.H4
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Includes bibliographical references.
Subjects:      Surfaces, Ruled.
               Differential equations, Linear.
Control No.:   13198766

Author:        Lasley, John Wayne, 1891-
Title:         Some special cases of the flecnode transformation
                  of ruled surfaces, by John Wayne Lasley, jr.
Published:     Chicago, Illinois, 1922.
Description:   1 p. l., 19 p., 24 cm.
LC Call No.:   QA645.L3
Notes:         Vita.
               "Private edition, distributed by the University
                  of Chicago libraries."
               Thesis (PH. D.)--University of Chicago, 1920.
Subjects:      Surfaces.
               Transformations (Mathematics).
Control No.:   10131412

Author:        Lenz, Ernst.
Title:         Ueber die Enneper'schen Flächen constanten
                  negativen Krümmungsmaasses mit einem Systeme ebener
                  Krümmungslinien ...
Published:     Göttingen, Druck der Dieterichschen
                  Univ.-Buchdruckerei, W.F. Kästner, 1879.
Description:   28 p. fold. tab., diagrs. on fold. pl. 21 cm.
LC Call No.:   QA645.L57
Notes:         Inaug.-diss.--Göttingen.
Subjects:      Surfaces
Other titles:  Über die Enneper'schen Flächen constanten
                  negativen Krümmungsmaasses mit einem Systeme ebener
                  Krümmungslinien.
               [Pamphlets. Mathematics. 1841-1906] v.12.
Control No.:   9610469

Author:        Lietke, Arthur, 1865-
Title:         Über die flächen, für welche eine
                  krümmungscentralfläche ein kegel zweiten grades ist ...
Published:     Königsberg, Hartungsche buchdruckerei [1890]
Description:   2 p. l., 36, [2] p. diagrs. on 2 fold. pl. 23
                  cm.
LC Call No.:   QA645.L71
Notes:         Inaug.-diss.--Königsberg.
               Vita.
Subjects:      Surfaces.
Control No.:   8669422

Author:        MacLean, Neil Bruce, 1883-
Title:         On certain sufaces related covariantly to a given
                  ruled surface ... by Neil Bruce MacLean.
Published:     [Toronto, 1924]
Description:   1 p. l., 18 p. 26 cm.
LC Call No.:   QA645.M3 1923
Notes:         Thesis (Ph. D.)--University of Chicago, 1923.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
               "Reprinted from the Proceedings of the
                  International mathematicial [!] congress, Toronto, August,
                  1924, vol. I."
Subjects:      Surfaces.
Control No.:   8267050

Author:        Probst, Friedrich, 1867- [from old catalog]
Title:         Über flächen mit isogonalen systemen von
                  geodätischen kreisen ..
Published:     Berlin, P. Stankiewicz' buchdruckerei, 1893.
Description:   2 p.l., 46 p., 1 l. 22 cm.
LC Call No.:   QA645.P96
Subjects:      Surfaces. [from old catalog]
Control No.:   10076155

Author:        Rasmusen, Ruth Beatrice, 1899-
Title:         Conjugate osculating quadrics associated with the
                  lines of curvature ... by Ruth Beatrice Rasmusen ...
Published:     [Chicago] 1937.
Description:   ii numb. l., 31 p. 24 cm.
LC Call No.:   QA645.R3 1936
Dewey No.:     516.58
Notes:         Thesis (PH. D.)--University of Chicago, 1936.
               Vita.
               Lithoprinted.
               "Private edition, distributed by the University
                  of Chicago libraries, Chicago, Illinois."
Subjects:      Quadrics.
Control No.:   4527367

Author:        Robinson, Pierre Gain, 1889-
Title:         Surfaces with constant absolute invariants.
Published:     Chicago, 1925.
Description:   37 l. 29 cm.
LC Call No.:   QA645.R6
Dewey No.:     541.3/453
Notes:         Typescript (carbon copy)
               Thesis--University of Chicago.
               Vita.
               Bibliographical footnotes.
Subjects:      Surfaces.
               Invariants.
Control No.:   3273604

Author:        Sievert, Heinrich. [from old catalog]
Title:         Ueber die zentralflächen der Enneper'schen
                  flächen konstanten krümmungsmasses ...
Published:     Tübingen, Druck von H. Laupp, jr., 1886.
Description:   36 p. diagrs. on fold. pl. 21 cm.
LC Call No.:   QA645.S47
Subjects:      Surfaces of constant curvature. [from old
                  catalog]
Control No.:   6327931

Author:        Simon, Paul [Richard], 1846- [from old catalog]
Title:         Ueber flächen mit constantem krümmungsmaass
                  ...
Published:     Halle, Druck von O. Hendel [1876]
Description:   2 p.l., 30, [2] p. 30 cm.
LC Call No.:   QA645.S5
Subjects:      Surfaces of constant curvature. [from old
                  catalog]
Control No.:   6798140

Author:        Smith, Arthur Whipple, 1876-
Title:         The symbolic treatment of differential geometry /
                  by Arthur Whipple Smith.
Published:     Lancaster, Pa. : Press of the New Era Printing
                  Company, 1905.
Description:   33-61 p. ; 28 cm.
LC Call No.:   QA645.S64
Notes:         Vita.
               From the Transactions of the American
                  Mathematical Society.
               Thesis (Ph. D.)--University of Chicago.
Subjects:      Curvature.
               Curves on surfaces.
Control No.:   8678426

Author:        Tachauer, Abraham, 1875-
Title:         Über diejenigen flächen, auf denen zwei scharen
                  geodätischer linien ein conjugiertes system bilden ...
Published:     [Würzburg, C.J. Becker's univ.-buchdruckerei,
                  1902]
Description:   2 p.l., 67, [1] p., 1 l. diagrs. on fold. pl. 22
                  cm.
LC Call No.:   QA645.T12
Notes:         Inaug.-dis.--Würzburg.
               Lebenslauf.
Subjects:      Surfaces.
Control No.:   1689315

Author:        Amstein, Hermann, 1840- [from old catalog]
Title:         Ueber die conforme abbildung der oberfläche
                  eines regulären octaeders auf die oberfläche einer kugel
                  ...
Published:     Zürich, Druck von Zürcher und Furrer, 1872.
Description:   2 p.l., 46 p. diagrs. on 2 fold. pl. 21 cm.
LC Call No.:   QA646.A52
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   8668471

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Risoluzione del problema: riportare i punti di
                  una superficie sopra un piano in modo che le linee geodetiche
                  vengano rappresentate da linee rette. Del professor Eugenio
                  Beltrami ...
Published:     Roma, Stamperia della S.C. de Prop. fide, 1866.
Description:   1 p.l., 20 p. 30 cm.
LC Call No.:   QA646.B45
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   10078797

Author:        Bieberbach, Ludwig, 1886-
Title:         Einführung in die konforme abbildung, von dr.
                  Ludwig Bieberbach ... Mit 44 figuren.
Published:     Berlin und Leipzig, G. J. Göschen, 1915.
Description:   141 p. diagrs. 16 cm.
Series:        Sammlung Göschen. [768]
LC Call No.:   QA646.B5
Subjects:      Surfaces, Representation of.
Control No.:   7317809

Author:        Binder, Johannes Karl, 1876-
Title:         Über eine gewisse abbildung zweier
                  rotationshyperboloide aufeneinander ...
Published:     [Dresden, Albanus] 1900
Description:   81 p. incl. diagrs. 23 cm.
LC Call No.:   QA646.B61
Notes:         Inaug.-dis.--Leipzig.
               Vita.
Subjects:      Surfaces, Representation of.
               Hyperboloid.
Control No.:   6796134

Author:        Brückner, Joh[annes] Max, 1860- [from old
                  catalog]
Title:         Über eine besondere art der konformen abbildung
                  einer ebene auf eine andere ...
Published:     Dresden, Druck von B. G. Teubner, 1886.
Description:   47, [1] p. diagrs. on fold. pl. 23 cm.
LC Call No.:   QA646.B88
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   9606170

Author:        Busolt, Max, 1863-
Title:         Behandlung der conformen Abbildung der
                  Oberflächen zweiter Ordnung ...
Published:     Königsberg, Hartungsche Buchdruckerei, 1890.
Description:   1 p. L., 95, [2] p. 21 cm.
LC Call No.:   QA646.B95
Notes:         Lebenslauf.
               Inaug.-diss.--Königsberg.
Subjects:      Conformal mapping
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.5.
Control No.:   10074480

Author:        Busse, Friedrich, 1872- [from old catalog]
Title:         Ueber eine specielle conforme abbildung der
                  flächen constanten krümmungsmasses auf die ebene mit einem
                  anhange,
Published:     Göttingen, Druck der Dieterich'schen.
                  Univ.-buchdruckerei (W. F. Kaestner) 1896.
Description:   31, [1] p., 1 l. 24 cm.
LC Call No.:   QA646.B97
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   7732599

Author:        Courant, Richard, 1888-1972.
Title:         Dirichlet's principle, conformal mapping, and
                  minimal surfaces. With an appendix by M. Schiffer.
Published:     New York, Interscience Publishers, 1950.
Description:   xiii, 330 p. diagrs. 24 cm.
Series:        Pure and applied mathematics (Interscience
                  Publishers) ; v. 3
LC Call No.:   QA646.C6
Dewey No.:     517.5
Notes:         Bibliography: p. 245-248, 319-323.
Subjects:      Surfaces, Representation of.
Control No.:   9768144

Author:        Cremona, Luigi, 1830-1903. [from old catalog]
Title:         Rappresentazione piana di alcune superficie
                  algebriche dotate di curve cuspidali.
Published:     Bologna, Tipi Gamerini e Parmeggiani, 1872.
Description:   1 p.l., [117]-127 p. 30 x 22 cm.
LC Call No.:   QA646.C9
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   7736883

Author:        Dalwigk, F. von (Friedrich), 1864-
Title:         Ueber die integration von [Delta]u=o und die
                  konforme abbildung ...
Published:     1897.
Description:   1 p. l., 53 p. diagr. 22 cm.
LC Call No.:   QA646.D15
Notes:         Habilitationsschrift--Marburg.
Subjects:      Surfaces, Representation of.
Control No.:   9137664

Author:        Danich, Dimitrie [from old catalog]
Title:         Conorme abbildung des elliptischen paraboloïds
                  auf die ebene ...
Published:     Belgrad, Druck der K. Serbischen staatsdruckerei,
                  1885.
Description:   2 p. l., 41, [1] p. 24 cm.
LC Call No.:   QA646.D18
Subjects:      Surfaces, Representation of. [from old catalog]
               Paraboloid. [from old catalog]
Control No.:   7264499

Author:        Dresher, Melvin. [from old catalog]
Title:         Moment space boundaries and some applications.
Published:     Santa Monica, Calif., Rand Corp. c1951.
Description:   13 l. 30 cm.
LC Call No.:   QA646.D7
Subjects:      Surfaces, Representation of. [from old catalog]
Series Entry:  Rand Corporation. Project Rand research
                  memorandum, RM-534. [from old catalog]
Control No.:   6965883

Author:        Dudensing, Wilhelm, 1864- [from old catalog]
Title:         Über einige probleme der conformen abbildung
                  ...
Published:     Leipzig, Druck von Breitkopf & Härtel, 1889.
Description:   31, [1] p. diagr. 27 x 21 cm.
LC Call No.:   QA646.D84
Subjects:      Conformal mapping. [from old catalog]
Control No.:   5860061

Author:        Fischer, Otto, 1861- [from old catalog]
Title:         Konforme abbildung sphärischer dreicke auf
                  einander mittelst algebraischer funktionen ...
Published:     Leipzig., Druck von Metzger & Wittig, 1885.
Description:   78 p. diagrs., on 2 double pl. 23 cm.
LC Call No.:   QA646.F52
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   8201282

Author:        Gerst, Francis Joseph, 1882-
Title:         Image points and Riemann's theorem / by Francis
                  Joseph Gerst.
Published:     Chicago, Ill. : Loyola University Press, 1925.
Description:   43 p. : ill. ; 23 cm.
LC Call No.:   QA646.G4 1925
Notes:         Vita.
               Thesis (Ph. D.)--Johns Hopkins University, 1925.
Subjects:      Surfaces, Representation of.
               Riemann surfaces.
Other titles:  Riemann's theorem.
Control No.:   7329000

Author:        Haenig, Conrad, 1859- [from old catalog]
Title:         Ueber Hansens methode, ein geodätisches dreieck
                  auf die kugel oder in die ebene zu übertragen ...
Published:     Dessau, Druck von Weniger & co., 1888.
Description:   2 p.l., 36 p., 1 l. 22 cm.
LC Call No.:   QA646.H13
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   9144993

Author:        Henstchel, Oscar. [from old catalog]
Title:         Ueber einige conforme abbildungen ...
Published:     Jena, Druck von W. Ratz, 1871.
Description:   42 p. diagrs. on fold. pl. 22 cm.
LC Call No.:   QA646.H5
Subjects:      Conformal mapping. [from old catalog]
Control No.:   8200320

Author:        Hollaender, Eugen, 1862-
Title:         Über aequivalente abbildung ...
Published:     Halle/S., 1891.
Description:   1 p. l., 35, [3] p. 25 x 21 cm.
LC Call No.:   QA646.H73
Notes:         Inaug.-dis.--Halle.
               Vita.
Subjects:      Surfaces, Representation of.
Control No.:   8669421

Author:        Holzmüller, Gustav, 1844-1914. [from old
                  catalog]
Title:         Einführung in die theorie der isogonalen
                  verwandtschaften und der conformen abbildungen,
Published:     Leipzig, B. G. Teubner, 1882.
Description:   vii p., 1 l., 284 p. fold. diagrs. 23 cm.
LC Call No.:   QA646.H74
Subjects:      Surfaces, Representation of. [from old catalog]
               Map-projection. [from old catalog]
Control No.:   6935747

Author:        Hoyle, Vinton Asbury, 1904- [from old catalog]
Title:         Some problems in conformal geometry ...
Published:     Easton, Pa., Mack printing co., 1931.
Description:   30 p. 23 cm.
LC Call No.:   QA646.H75 1930
Subjects:      Geometry, Differential. [from old catalog]
               Transformations (Mathematics) [from old catalog]
Control No.:   9222280

Author:        Huber, Gottlieb, 1857-1923. [from old catalog]
Title:         Anwendung der conformen abbildung ...
Published:     Zürich, Druck von Zürcher & Furrer, 1883.
Description:   p. cm.
LC Call No.:   QA646.H87
Subjects:      Conformal mapping. [from old catalog]
Control No.:   6327930

Author:        Kober, H.
Title:         Dictionary of conformal representations.
Published:     [New York] Dover Publications [1952]
Description:   xvi, 208 p. diagrs. 25 cm.
LC Call No.:   QA646.L73
Dewey No.:     517.5
Notes:         "Written for the British Admiralty during
                  1944-1948 ... Reproduced and circulated in the Department of
                  Scientific Research and Experiment, and in the Department of
                  Physical Research."
               Bibliography: p. 202-204.
Subjects:      Conformal mapping.
Control No.:   1220469

Author:        Koch, Walter [Immanuel] 1864- [from old catalog]
Title:         Die conforme abbildung des hyperbolischen
                  paraboloids auf einer ebene ...
Published:     Greifswald, Druck von F. W. Kunike, 1887.
Description:   45 p. 22 cm.
LC Call No.:   QA646.K76
Subjects:      Surfaces, Representation of. [from old catalog]
               Paraboloid. [from old catalog]
Control No.:   6796133

Author:        Ladue, Mary Elizabeth, 1914-
Title:         Conformal geometry of horn angles of higher
                  order, by Mary Elizabeth Ladue ...
Published:     [N.p., 1943]
Description:   2 p. l., 455-476 p., 1 l. 25 cm.
LC Call No.:   QA646.L3
Dewey No.:     513.7
Notes:         Thesis (Ph. D.)--Columbia University, 1942.
               "Reprinted from the American journal of
                  mathematics, vol. LXV, number 3."
               Vita.
               "References": p. 476.
Subjects:      Surfaces, Representation of.
               Transformations (Mathematics)
Control No.:   10200377

Author:        Lambert, Johann Heinrich, 1728-1777.
Title:         Anmerkungen und zusätze zur entwerfung der land-
                  und himmelscharten. Von J. H. Lambert (1772.) Hrsg. von A.
                  Wangerin. Mit 21 textfiguren.
Published:     Leipzig, W. Engelmann, 1894.
Description:   95, [1] p. diagr. 20 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften,
                  nr. 54
LC Call No.:   QA646.I22
Notes:         Reprint of the sixth of 9 treaties published by
                  the author as pt. 3 of his "Beyträge zum gebrauche der
                  mathematik und deren anwendung", Berlin, 1772.
Subjects:      Map projection.
Control No.:   6792882

Author:        Lewent, Leo, d. 1910.
Title:         Konforme abbildung, hrsg. von prof. dr. Eugen
                  Jahnke, mit einem beitrag von dr. Wilhelm Blaschke ... Mit 40
                  abbildungen.
Published:     Leipzig, Berlin, B.G. Teubner, 1912.
Description:   vi, 118 p. diagrs. 21 cm.
Series:        Mathematische-physikalische schriften für
                  ingenieure und studierende, hrsg. von E. Jahnke. 14
LC Call No.:   QA646.L5
ISBN:          DM3.20
Subjects:      Conformal mapping.
Series Entry:  Mathematisch-physikalische Schriften für
                  Ingenieure und Studierende ; 14.
Control No.:   3580117

Author:        Litvinova, Elizaveta Fedorovna, 1845?-1919. [from
                  old catalog]
Title:         Lösung einer abbildungsaufgabe ...
Published:     St. Petersburg, Buchdruckerei der K. Akademie der
                  wissenschaften, 1879.
Description:   28 p. 27 cm.
LC Call No.:   QA646.L78
Subjects:      Conformal mapping. [from old catalog]
Control No.:   8668474

Author:        Modesitt, Virginia, 1910- [from old catalog]
Title:         Some singular properties of conformal
                  transformations between Riemannian spaces,
Published:     Urbana, Ill., 1937.
Description:   1 p.l., 8 p., 1 l. 21 cm.
LC Call No.:   QA646.M6 1937
Subjects:      Transformations (Mathematics) [from old catalog]
               Generalized spaces.
Control No.:   9713338

Author:        Mühll, Karl von der, 1841- [from old catalog]
Title:         Über ein problem der kartenprojektion ...
Published:     Leipzig, Druck von B. G. Teubner, 1868.
Description:   18 p. 26 cm.
LC Call No.:   QA646.M94
Subjects:      Map projection. [from old catalog]
Control No.:   8205581

Author:        Nauenberg, Julius, 1857-
Title:         Die konforme Abbildung eines Flächenstückes,
                  das von einer algebraischen Kurve 2nõtõeõr Ordnung begrenzt
                  wird ...
Published:     Berlin, Universitäts-Buchdruckerei von G. Schade
                  (O. Francke) 1904.
Description:   51 p., 1 L. diagrs. on pl. 22 cm.
LC Call No.:   QA646.N29
Notes:         In title "õtõeõr" is superscript.
               Inaug.-diss.--Erlangen.
               "Literatur": p. [5]-6.
Subjects:      Conformal mapping
Other titles:  [Pamphlets. Mathematics. 1841-1906] v.14.
Control No.:   7271825

Author:        Nehari, Zeev, 1915-
Title:         Conformal mapping.
Edition:       1st ed.
Published:     New York, McGraw-Hill, 1952.
Description:   396 p. 24 cm.
Series:        International series in pure and applied
                  mathematics
LC Call No.:   QA646.N35
Dewey No.:     517.5 518
Subjects:      Conformal mapping.
Control No.:   4055539

Author:        Reina, Vinzenzo, 1862-1919. [from old catalog]
Title:         Di alcune formole relative alla teoria delle
                  superficie;
Published:     Roma, Tip. della R. Accademia dei Lincei, 1890.
Description:   p. [103]-110. 27 cm.
LC Call No.:   QA646.R34
Subjects:      Surfaces, Representation of. [from old catalog]
               Coordinates. [from old catalog]
Control No.:   9213077

Author:        Reinbeck, Karl, 1859- [from old catalog]
Title:         Ueber diejenigen flächen, auf welche die
                  flächen zweiten grades durch parallele normalen conform
                  abgebildet werden ...
Published:     Göttingen, Druck der Dieterichschen
                  univ.-buchdruckerei, W. F. Kaestner, 1886.
Description:   48 p. diagrs. on pl. 21 cm.
LC Call No.:   QA646.R36
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   9606169

Author:        Sanio, Theodor, 1847- [from old catalog]
Title:         Die abbildung des aeusseren eines
                  kreisbogenpolygons auf eine kreisfläche ...
Published:     Greifswald, Druk von F. W. Kunike [1885]
Description:   p. cm.
LC Call No.:   QA646.S22
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   10074479

Author:        Schaffrath, Friedrich Wilhelm, 1852- [from old
                  catalog]
Title:         Ueber die Konforme abbildung Z=zp3s und z=[Cube
                  root symbol]Z ...
Published:     Marburg, Universitäts-buchdruckerei (R.
                  Friedrich) 1884.
Description:   32 p., 1 l. diagrs. on 2 pl. 21 cm.
LC Call No.:   QA646.S27
Subjects:      Conformal mapping. [from old catalog]
Control No.:   7732598

Author:        Schottky, Friedrich Hermann, 1851-1935. [from old
                  catalog]
Title:         Ueber die conforme abbildung mehrfach
                  zusammenhängender ebner flächen ...
Published:     Berlin, Buchdruckerei von G. Schade (O. Francke)
                  [1875]
Description:   2 p.l., 36, [2] p. 23 cm.
LC Call No.:   QA646.S3
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   5859115

Author:        Seyler, Gotthold, 1876-
Title:         Ueber die erhaltung der krümmungslinien bei
                  orthogonal-projektion ...
Published:     Passau, Buchdruckerei aktiengesellschaft
                  Passavia, 1903.
Description:   24, [2] p., 1 l. 24 cm.
LC Call No.:   QA646.S51
Notes:         Inaug.-dis.--Erlangen.
               Lebenslauf.
Subjects:      Surfaces, Representation of.
Control No.:   4052317

Author:        Tauberth, Johannes. [from old catalog]
Title:         Die abbildung des ebenen kreissystemes auf den
                  raum ...
Published:     Dresden, Druck von A. Schönfeld, 1884.
Description:   p. cm.
LC Call No.:   QA646.T3
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   6360393

Author:        Thybaut, A. (Alexander), 1870-
Title:         Sur la déformation du paraboloïde et sur
                  quelques problèmes qui s'y rattachent / par M. A. Thybaut.
Published:     Paris : Gauthier-Villars et fils, 1897.
Description:   58 p., 1 leaf ; 28 cm.
LC Call No.:   QA646.T6
Notes:         Issued also in Annales de l'École normale
                  supérieure, 1897.
               Thèse--Université de Paris.
Subjects:      Surfaces, Representation of.
Control No.:   6807586

Author:        Trognitz, Bernhard. [from old catalog]
Title:         Ueber einige curven auf dem rotationsellipsoid,
                  der kugel und der Mercator'schen projectionsebene bei
                  conformem zusammen enhange dieser flächen unter einander
                  ...
Published:     Jena, Druck J. Hossfeld, 1883.
Description:   56 p. 21 cm.
LC Call No.:   QA646.T84
Subjects:      Surfaces, Representation of. [from old catalog]
Control No.:   9137663

Author:        Wangerin, A. (Albert), 1844-1933, ed.
Title:         Ueber kartenprojection Abhandlungen von Lagrange
                  (1779) und Gauss (1822) Hrsg. von A. Wangerin. Mit 2
                  textfiguren.
Published:     Leipzig, W. Engelmann, 1894.
Description:   101, [1] p. diagr. 20 cm.
Series:        Ostwalds Klassiker der exakten Wissenschaften.
                  nr. 55
LC Call No.:   QA646.W24
Notes:         List of works of Lagrange: p. 83-84.
               List of works of Gauss: p. 84-85.
               Lagrange, J. L. de. Ueber die construction
                  geographischer karten. (Sur la construction des cartes
                  géographiques) [Berlin, Mém. acad., année 1779,
                  1781]--Gauss, K. F. Allgemeine auflösung der aufgabe: Die
                  theile einer gegebnen fläche auf einer andern gegebnen
                  fläche so abzubilden, dass die abbildung dem abgebildeten in
                  den kleinsten theilen ähnlich wird. [Astronom. abhandlungen,
                  hrsg. von H. C. Schumacher, 3. hft. Altona, 1825]
Subjects:      Map projection.
               Surfaces, Representation of.
Other authors: Lagrange, J. L. (Joseph Louis), 1736-1813.
               Gauss, Carl Friedrich, 1777-1855.
Control No.:   7260707

Author:        Yeaton, Chester Henry, b. 1886.
Title:         Surfaces characterized by certain special
                  properties of their directrix congruences ... by Chester
                  Henry Yeaton ...
Published:     [Milano, Tip.-lit. Rebeschini di Turati e c.,
                  1916]
Description:   2 p.l., 33 p. 29 cm.
LC Call No.:   QA646.Y4
Notes:         Thesis (Ph. D.)--University of Chicago, 1915.
               Vita.
               "Reprinted from Annali di matematica, serie III,
                  tomo XXVI, 1916."
Subjects:      Surfaces, Representation of.
Control No.:   4053253

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Intorno alla flessione delle superficie rigate.
                  Memoria del Dr Eugenio Beltrami ...
Published:     Venezia, Tipografia del Commercio edit., 1865.
Description:   20 p. 24 cm.
LC Call No.:   QA648.B45
Subjects:      Surfaces, Deformation of. [from old catalog]
Control No.:   9141985

Author:        Beltrami, Eugenio, 1835-1900.
Title:         Sulla flessione delle superficie rigate. Memoria
                  del Prof. E. Beltrami ...
Published:     Roma, Stamperia della S.C. de Prop. fide, 1865.
Description:   1 p.l., 34 p. 30 cm.
LC Call No.:   QA648.B47
Subjects:      Surfaces, Deformation of. [from old catalog]
Control No.:   7268845

Author:        Cosserat, Eugène Maurice Pierre, 1866-1931.
                  [from old catalog]
Title:         Théorie des corps déformables,
Published:     Paris, A. Hermann et fils, 1909.
Description:   vi, 226 p., 1 l. 25 cm.
LC Call No.:   QA648.C6
Subjects:      Surfaces, Deformation of.
               Elasticity.
               Equilibrium of flexible surfaces.
               Hydrodynamics.
Other authors: Cosserat, François, 1852- [from old catalog]
                  joint author.
Control No.:   6908666

Author:        Eisenhart, Luther Pfahler, b. 1876.
Title:         Infinitesimal deformation of surfaces.
Published:     Baltimore, Md., Friedenwald company [1900?]
Description:   34 p., 1 L. 31 x 35 cm.
LC Call No.:   QA648.E36
Notes:         Biographical sketch.
               Thesis (Ph. D.)--Johns Hopkins university, 1900.
Subjects:      Surfaces, Deformation of.
Other titles:  Pamphlets. Mathematics. Quartos. v. 2, no. 8.
Control No.:   8215258

Author:        Kohl, Johannes. [from old catalog]
Title:         Beitrag zur theorie der biegung krummer
                  oberflächen ...
Published:     Strassburg, Buchdruckerei von R. Schultz & comp.,
                  1880.
Description:   46 p. diagrs. on pl. 24 cm.
LC Call No.:   QA648.K79
Subjects:      Surfaces, Deformation of. [from old catalog]
Control No.:   7264498

Author:        Liebmann, Heinrich, 1874-
Title:         Über die Verbiegung der geschlossenen Flächen
                  positiver Krümmung / von Heinrich Liebmann.
Published:     Leipzig : B.G. Teubner, 1899.
Description:   32 p. : ill. ; 25 cm.
LC Call No.:   QA648.L71
Notes:         Habilitationsschrift--Leipzig.
               From den Mathematischen Annalen, Bd. 53.
Subjects:      Surfaces, Deformation of.
Control No.:   5860060

Author:        Offenhauer, Adolf, 1862-
Title:         Über eine bestimmte art von flächenverbiegung
                  ...
Published:     Halle a.S., 1887.
Description:   1 p. l., 46 p., 1 l. 24 cm.
LC Call No.:   QA648.O32
Notes:         Inaug.-diss.--Halle.
               Vita.
Subjects:      Surfaces, Deformation of.
Control No.:   8201281

Author:        çZorawski, Kazimierz, 1866- [from old catalog]
Title:         Über biegungsinvarianten. Eine anwendung der
                  Lie'schen gruppentheorie ...
Published:     Stockholm, Gedruckt in der Centraldruckerei,
                  1891.
Description:   2 p.l., 64 p. 29 x 23 cm.
LC Call No.:   QA648.Z89
Subjects:      Surfaces, Deformation of. [from old catalog]
               Continuous groups.
Control No.:   8201270
