#+STARTUP: showeverything logdone
#+options: num:nil

Describe the new page here.

I really like wordreference. Here is for instance the page where they discuss the
French translations of the English "resent". 

http://www.wordreference.com/enfr/resent

and

http://forum.wordreference.com/showthread.php?t=437305

It is often more interesting than
a dictionary because there are more explanations about tiny facts (levels of
language, constructions, small differences between available translations). I
wonder if the same thing could exist for math. One theorem (one definition)
and a stack of comments in the spirit of wordreference. -- [[file:fl.org][fl]] 29-Aug-2009

*  references (cont.)

Decidedly wordreferences is great. Here is the page concerning "handout".

http://www.wordreference.com/enfr/handout

And here is a page where the word is discussed (at least its meaning in a school context)

http://forum.wordreference.com/showthread.php?t=428222


It's clear that sort of discussion proves valuable. First it shows how current a word is.
Then it helps to clarify the obscurity. In the definition a translation (polycopié) 
for "handout"  is given with the mention "universite" and the discussion helps to 
clarify that this mention is wrong (the word may be used in a more general school context
not only at the university);
Other translations are given (for instance "support de cours"). Old words no longer in use
("stencil") are also given.

And there is a mistake "support de presentation" is definitely not current (the correct words
are "polycopie" and "support de cours").

I think one can get a lot out of that sort of discussions. And that metamath would benefit 
a lot of that sort of (genuine) discussion also. -- [[file:fl.org][fl]] 30-Aug-2009

*  A last one

There a French person will learn (with interest) that un "agent de securite" may 
be a "security guard" or a "store walker" depending on the presence or the absence 
of a uniform (you can't invent that).

http://forum.wordreference.com/showthread.php?t=704491

-- [[file:fl.org][fl]] 30-Aug-2009
