#+STARTUP: showeverything logdone
#+options: num:nil

Since it seems likely that a Chief Knowledge Officer role will be 
created for me to fill, I thought I'd say a few words about why
that's a good idea, and post a few links that talk about related
ideas.

The role of the CKO is sketched in generic terms
[http://en.wikipedia.org/wiki/Chief_Knowledge_Officer on Wikipedia].
This overview speaks to what I already do fairly well.  I am very concerned with
[http://www.systems-thinking.org/kmgmt/kmgmt.htm systems thinking],
and with using system thinking to advance the
[http://www.oreillynet.com/pub/wlg/3139 platforms] used by the organization,
with the ultimate goal of creating an increasingly useful 
[http://www.experiencedesignernetwork.com/archives/000663.html learning environment].

Furthermore, I've been working to exploit existing PM knowledge (e.g. in the [[file:FEM.org][FEM]]
project, for improved content-delivery purposes; also in [[file:HDM.org][HDM]], for research purposes), and also working on outreach (to get PM better integrated into
the existing mathematics-content landscape and get more people involved),
and of course looking at fundraising opportunities.

I expect that these sorts of tasks will continue to be relevant!  PM
is a knowledge-based and knowledge-oriented resource; the role of
knowledge management in such an organization seems especially key.

--[[file:jcorneli.org][jcorneli]]

: For the record, so I am not accused in the future of not participating in the Wiki in order to make decisions, here it is recorded my oposition to the creation of this position as a paid permanent position. Other members have expressed similar concerns (drini and matte, at least). The correspoding arguments may be found here (along the thread) http://planetmath.org/?op=getmsg&id=9980 --[[file:alozano.org][alozano]]

That reference doesn't contain arguments against the creation of this
position, it contains a critique of my writing in the above paragraph
that it seemed likely that such a position would be created with me
filling it.  I continue to feel that's likely.  If you want to talk
about why this position shouldn't be created or why I shouldn't fill
it, please make your case using specific and direct arguments.
--[[file:jcorneli.org][jcorneli]]

: The reference does contain an argument. Please read the full thread again if you forgot. Here is one of my messages. 

Joe,

I understand that my views may seem antagonistic to you, because they
oppose something that you are so aggresively pursuing, but
unfortunately I need to express my views as much as you feel the need
of express yours. Let me say that I don't bring this up because of
personal issues with you or Ray or Aaron. The issue here is
priorities. The budget is very limited right now. There seems to be
some hope that it will increase but we cannot cut and administer the
cake before we've got it. Since the budget is extremely limited I
don't think it is a good idea to hold paid positions of any
sort. However, the code bounties seem to me like the way to go. They
are priority items at low cost. I encourage you to take on some of
them. By the way, you personal economic situation, whatever it is,
should not be a factor on the decision making at PM.

I understand too that in order to increase the budget we need some
organized procedure, but this should be done in a volunteer basis, the
same way that the rest of the community is being built up. I don't
think we should pay the members who invest a lot of their time
writing/correcting entries (like matte or pahio) and I don't we should
pay the members who invest a lot of their time doing organization and
"meta" stuff (like you or ray). It is an online community and as such
should be built on volunteer effort. Aaron would say, "but we don't
have enough volunteers on one side!". Oh well, as we increase in size
it seems like the volunteers on the other side are also slowly
increasing. Give it time. In the meantime, yes, we can pay some
bounties for first-need items, like a server migration. But should we
pay right now for a "Chief Knowledge Officer"? I don't think so. Not
because it is you, but because there is no need for it. Not an
immediate need at least.

Now, you say "I think PM (whose views are generated by the complicated
process I described above) is of the view that some paid positions
should be created to further the interests of the organization." This
statement is simply not true. You, Aaron and Ray share that opinion,
but the three of you are definitely not ALL of the PM community. I
understand Aaron can play his trump card (i.e. founder privilege), in
which case we all have to suck it up, but I really hope things don't
turn that way. In some sense I believe you are drugged by your own
words. Let me explain this: you are extremely prolific, the wiki is
immense and mostly due to you. Thousands of pages it seems to me, but
with essentially one author. The Wiki is NOT the official PM
vision. This you must understand. It is essentially run by three
people and expresses the views of three people. Hence, I think the
Wiki should have some sort of disclaimer in the first page, letting
people know that. On the other hand, the Wiki seems to mix some
official stuff (like the entries on PM board meetings) with extremely
non-official PM stuff, some of your stuff for example.

If you are to count the voice of the community, just take votes, take
a poll right here. For starters, seems that out of regular members
Drini and I oppose the creation of paid positions while you and Ray
(the people who would get paid by the way) agree on it.

Also, one should be aware that how the money is spent and how we
decide who is to get this money, is *essential* to promote
fund-raising. I disagree with some of your views of PlanetMath, and
thus I don't think I could agree on you being the Chief Knowledge
Officer for PlanetMath. Note that I am all for some of the projects,
like the FEM. But even there I don't think you have the right
vision. For example, I believe you are overly optimistic about the
sales of FEM. I think it will be a tough thing to sale to respectable
institutions and, for one, I would not recommend any institution to
acquire a copy (mainly because the degree of accuracy, overall, may
not be enough for a published reference work, and in some cases, the
content may be catastrophically bad). We can talk some more about this
later on.

Finally, it is only disappointing that the board is not more involved
in all this. But the board is still the board. And the board should
take decisions.--[[file:alozano.org][alozano]]

/The budget is very limited right now./ We aren't talking about
using the current budget to pay salaries.

/It is an online community and as such should be built on volunteer
effort./  Support for this claim?

/On the other hand, the Wiki seems to mix some official stuff (like
the entries on PM board meetings) with extremely non-official PM
stuff, some of your stuff for example./  There is very little
official stuff; most of the goings on at the wiki and elsewhere happen
through an informal process.  That's just the way it is.  There are
also board meetings etc.; so I'm not sure what the complaint is here.
If creating a CKO position is basically a consensus among wiki users,
then we'll do that (i.e., we will at least propose it to the board).  If you actually oppose it strongly enough to want
to revise it out of any joint proposal going to the board or whatever,
you can undertake to do that.  But basically the wiki belongs to those
who take the initiative.  

: Indeed, you agree most of the wiki is unofficial, so imagine I
start discussing the issue unoficially on my school homepage, and
consensus among the people reading my school webpage is that a
position should be created for me to fill, then ok we'll do that! if
you actually oppose it strongly enough to want to revise it you should
revise it as well. But hey, 2 points, my school homepage is as
unoifficial as this wiki is, right? So consensus there would mean the
same as here. And you changed your stance in the middle: first you
said it will happen, the position will be created, I will fill it in,
then you switched to consensus is to make a proposal to the board,
nothing else. --[[file:drini.org][drini]]

:: Drini, I too am mortal.  My wording reflects my thinking, which
is complicated.  All we're talking about is making a proposal to
the board.  However, since Aaron and Ray and I all agree about
this proposal, it seems likely that the board will also agree. --[[file:jcorneli.org][jcorneli]]

/I am all for some of the projects, like the FEM. But even there I
don't think you have the right vision./ Honestly I don't know how you
can assume you know my view on FEM; and if you disagree with some of
the things I've said about it, you're free to argue some opposing
point of view.  The fact that I might disagree with you or any number
of other people about various things doesn't somehow disqualify me
from being a good CKO.

/If you are to count the voice of the community, just take votes,
take a poll right here./ As I said, right now is the time for
discussion, not voting.  We've got some discussion going now, and I'm
sure we'll have more when the various documents we've been drafting
get posted to the mailing lists and the forums.

/But the board is still the board. And the board should take
decisions./  And they will.  That doesn't stop other people from
acting in the mean time, nor from discussing things independently of
the board, nor from preparing documents for the board to look at.

: Has the board (as such) stated the positions WILL be created? Has it
stated you will fill it in? You seem pretty sure about it (all from
informal consensus on an unofficial wiki) --[[file:drini.org][drini]]

:: No, the board has not stated any of these things as of yet.  I am
not certain that the position will be created.  The wiki may be
"unofficial" but it carries a certain amount of weight, since
the people who are working on the wiki are the ones running the PM
organization on a day-to-day basis.  --[[file:jcorneli.org][jcorneli]]

To sum up, I see very little here that opposes the creation of a CKO
position. 

: I gave up regularly tracking the wiki because it has a lot of fluf
and unrelated content to planetmath. For every planetmath related
content there would be 10 pages of hdm, fem metastuff, philosophical
essays, personal writings, etc. And the only way of trackign the wiki
is with recent changes which put everything mixed, it's certainly not
easy and discouraging. And I think several other people feel the
same. --[[file:drini.org][drini]]

:: I agree that the wiki isn't a perfect medium, however, it works
reasonably well.  You don't need to watch it every day or read
everything poste to be aware of the main things that have been done
and to participate in discussing the things that matter to
you. --[[file:jcorneli.org][jcorneli]]

: This is the core of the issue. Most of your claims are supported by
"noone said otherwise on the wiki so consensus exists". It was
yourphilosophical essays that let YOU came up with the idea that HDM
is a research subproject of PM, but again, most (and I mean truly
most) pm users don't track the wiki and I don't think they will due to
its excessive noise/signal ratio. /The wiki is there for those who
take the initiative/. For instance, the page "Wikipedia the non free
encyclopedia" was your personal place to criticize wikipedia, and you
refused to change the name of it even though *being non-gfdl
complaint is not the same as not being free* (but hey, the title was
certainly catchy even if misleading) and by the record, then we should
write as well "planetmath, the other non-free encyclopedia" then. This
was just an example of how you use this wiki to propell your biases,
and coupled with the fact that a lot of non-PM content is added, makes
hard for someone with a PM interest only to use the wiki
regularly. And when faced with opposition you say "but it was written
on the wiki and noone objected! go to the wiki and object!" Why should
I? PLanetmath important issues should be discussed on a place with
planetmath focus so people don't have to sort out the relevant content
from the nonrrelevant one --[[file:drini.org][drini]]

:: I don't know what to say; everyone is biased in some ways, and any
time they write they "propel" their own biases in some way.  Still, I
tend to think of myself as fairly open minded.  And the wiki is a
free-for-all, it isn't owned by anyone.  If you think something needs
to be changed, then you can go ahead and change it yourself.  If you
don't feel that strongly about the issue, then I don't see why you
complain about it.  Your other option is to ignore what's written; and
again, I don't see why you'd go to the length of criticizing me about
writing things that you intend to ignore.  --[[file:jcorneli.org][jcorneli]]

#+BEGIN_VERSE Joe, drini is explaining why he doesn't like the wiki, or how it works and he would not like to use it as a medium of debate, at least as it is now. However, he cannot stop using it because otherwise you will use this against him, saying that he was not involved with the decision making so he cannot have a say in the decision. --[[file:alozano.org][alozano]]

#+BEGIN_VERSE: Drini might think that he can't be involved in decision making
except through the wiki, but if he does, then he's mistaken.  There
are plenty of other ways to be involved in decision making.  When we
who use the wiki have concrete plans that we actively want feedback on
from persons who don't use the wiki, you can be sure we'll get in
touch by other media.  --[[file:jcorneli.org][jcorneli]]

#+BEGIN_VERSE:: But not only we want to be participants of the decision making, we would like to be part of the creation of the plans themselves! In any case, I like the idea of sending a package of information to the members about the things which are going to be discussed in board meetings (sent ahead of time) so we can prepare arguments and have a lively discussion during the meeting.--[[file:alozano.org][alozano]]

#+BEGIN_VERSE#+BEGIN_VERSE Yes, everyone should also be involved in making plans.  I was
responding (in disagreement) to your remark /However, he cannot stop
using it because otherwise you will use this against him, saying that
he was not involved with the decision making so he cannot have a say
in the decision./  Absolutely we will be sending out packages and
postings of all kinds, and hopefully there will be lively discussion
using all existing media prior to the board meeting as well as
during it.  --[[file:jcorneli.org][jcorneli]]

I see slightly more that opposes my filling such a
position, but I don't think that the argument holds much water.  You'd
have to show, in the first case, why we don't need such a position,
and in the second case, why I shouldn't be that person.  Since the
overview of the position "speaks to what I already do fairly well" (as
I said above), you'll have to either prove me wrong in this claim, or
show that this work I've been doing is not needed and/or that it won't
need to be continued for a year or more.  I have no idea how you'd go
about doing that, but if you want to give it a shot, I'll be happy
to look at the results; presumably your arguments can only make
it easier for me, since you'll remove various things from my task-list
by application of pure reason.  That's something I can enjoy.

If, however, you're merely opposed to the creation of paid positions
of any sort, then you'll have to take up that argument; and perhaps
that would be better done on some other page, since the CKO position
is just one example of a broader set of proposed positions.

--[[file:jcorneli.org][jcorneli]]
