#+STARTUP: showeverything logdone
#+options: num:nil

Raymond S. Puzio

I am interested in both Planet Math and the Hyperreal Dictionary project.

I contribute regularly to Planet Math and will, from time to time, use the Planet Math section to  discuss ideas and suggestions regarding Planet Math.  For example, Joe has invited me to write up some thoughts I have had about the possible pitfalls of a (poorly designed) rating system.  I intend to do so, but it may be a while before it happens because I have a rather large backog of research projects and writing among which are the h-code business.

I am also interested in the [[file:Hyperreal Dictionary of Mathematics.org][Hyperreal Dictionary of Mathematics]] project.  Certainly, this is a very ambitious project, it will certainly involve much time and effort and entail developing new techniques and theory, but it is by no means unreasonable.  At present, I am most interested in developing "[[file:h-code.org][h-code]]", a notation for mathematics at a level in-between that of text such as one might find in a math book and symbolic logic.  Working on this project has suggested to me some novel ideas regarding the foundations of mathematics which, combined with other ideas I have thought of over the years, lead me to envision some sort of system of "relativistic hyperlogic".  Right now, this is all very speculative, but when some of these speculations and conjectures will have been studied further, I may add some material on them as well.
----

[[file:Greetings from Roanoke.org][Greetings from Roanoke]]

*** Mathematical Speculations

These are notes and expositions on some mathematical ideas which I have been thinking of.

 * [[file:Connections as Functors.org][Connections as Functors]]
 * [[file:Monadology of systems.org][Monadology of systems]]
 * [[file:Locally Cyclic Rings.org][Locally Cyclic Rings]]

----
Welcome aboard Ray, thanks for your contributions. --[[file:jcorneli.org][jcorneli]] Tue Feb  8 23:09:38 2005

Hey - plans for the night?  Maybe we can coordinate edits so we don't get in
eachother's way / do complementary things.  I was thinking of working on the
JACKYL page and adding some stuff there that I'd like you to look at.  I suppose
I really should be working on my list of tasks, but creating new pages is just
so fun.  --[[file:jcorneli.org][jcorneli]] Wed Feb 9 19:12:52 2005

Thanks for this morning's comment in the [[file:PlanetMath Budget and Resources.org][PlanetMath Budget and Resources]]
page; it seems very well-grounded, and I find it reassuring.  I might continue
to debate you about site membership a little bit... but all-in-all I'm feeling
less desparate about that issue & more motivated to work on the book!  --[[file:jcorneli.org][jcorneli]] Tue Feb 22 14:24:24 2005 UTC
----
Thank you for the information about deletion. -- [[file:fl.org][fl]] 13-Jan-2007
----
I tried to send you an e-Mail but it came back, so I'm just posting it here.--[[file:GrafZahl.org][GrafZahl]]

Hi Ray,


Joseph A. Corneli left a cryptic remark on my AsteroidMeta page 
http://planetx.cc.vt.edu/AsteroidMeta/GrafZahl about some world domination 
plans of yours regarding the mass digitalisation of mathematics works and my 
involvement with Wikisource (http://en.wikisource.org/wiki/Main_Page).

I don't know what exactly your intentions are, but I invite you to have a look 
at Wikisource. I've already put some texts on Wikisource (for a near-finished 
example, see http://en.wikisource.org/wiki/On_the_expression_of_a_number_in_the_form_𝑎𝑥²+𝑏𝑦²+𝑐𝑧²+𝑑𝑢²
and http://en.wikisource.org/wiki/Page:On_the_expression_of_a_number.djvu/1).
There is also a page describing how I've digitalised works: 
http://en.wikisource.org/wiki/User:GrafZahl/How_to_digitalise_works_for_Wikisource.

Let me know if this stuff is useful for you. If you have questions, you can 
reach me on the AsteroidMeta wiki or on my Wikisource talk page.


Best regards,
Alexander
