#+STARTUP: showeverything logdone
#+options: num:nil

The page [[file:HDM-related things to check out.org][HDM-related things to check out]] has a number of leads,
but they are quite disorganized.  And there is more info out there.
Some of these leads are going to be very important to follow up on!
Others are poetic and interesting, but perhaps not too relevant.
Someone should sort the wheat from the chaff, and write short descriptions
of the relevant projects and project areas.  Furthermore, we should
try to network with other researchers who are working on HDM-like things.

The first pass should be a fairly small project... --[[file:jcorneli.org][jcorneli]]

Some other things that seem particularly worth checking out at this
point are [[file:metamath.org][metamath]] and probably (for a point of comparison) ACL2.
See [[file:Small Projects - Condense MMAF literature.org][Small Projects - Condense MMAF literature]] for some more words
on the first of these items.

----
[[file:Focused HDM subprojects.org][Focused HDM subprojects]]
