#+STARTUP: showeverything logdone
#+options: num:nil

We're currently in a phase of negotiating values, and defining our goals. This
will help people make informed decisions about whether, and how, to contribute.
This document and other contemporaneous efforts seek to get a good discussion
fired up (developing new bylaws, together with an /admin's guide/ are
important complementary efforts).

In the process of identifying goals, many questions come up. A nonexhaustive
but representative list is as follows:

 * How should we make decisions?
 * How should we allocate resources?
 * What resources do we have?
 * How can we accrue additional resources?
 * With whom should we seek partnerships?
 * What powers should we give to members, the board, and unaffiliated users?
 * What are the difference between the current user community and the user
      communities of the future, and who speaks for future users?
 * What license or licenses should we use?
 * What role should original research have on the site?
 * How should we balance amathematical efforts with mathematical efforts?
 * What reward schedules can we offer?
 * Who is going to be involved in answering these questions?
 * How important is it to that they be answered soon?
 * Who is going to actually do the work?

Certain high-level goals have been suggested by various parties:

 * !PlanetMath as creating not just a new kind of community, but a
      revolutionizing the way people approach mathematical content.
 * !PlanetMath as an e-institute for the study of math on the one hand and of
      the related /meta/ stuff on the other, including various aspects of
      mathematical knowledge management.
 * And relatedly: !PlanetMath as a key leader in commons-based knowledege
      production, operating both (a) by doing it; (b) dy doing research on it.

 * !PlanetMath as a center for international mathematical collaborations,
      which integrates many languages and approaches to mathematics, and
      fosters fruitful relationships between sub-communities.

 * !PlanetMath as a center for independent learners and/or developing
      scholars, which complements or replaces traditional education and
      research channels.

In addition, certain lower-level goals have been advanced as being somehow
helpful. For example:

 * Integrating free software into the site.
 * Better supporting grade-school level mathematics.
 * Doing computer work that is of general interest (and salable!).
 * Find ways to support people want to who use the content to make some
      money of their own (and who will pay us to do this).
 * Find a way to coordinate or cluster individual goals, in order to figure
      out what our organizational priorities should be.
 * Replace specific existing non-free options (e.g. books or tutoring
      services).

Clearly nearly all of the items in the lists above are subject to discussion
and debate. Which are really relevant? For the tasks, which tasks should get
/organizational support/ and which ones can we count on volunteers to take
care of? And so on and so forth.

The fact that these questions have not been completely resolved shouldn't stop
us from going forward with some strategic plan, since it will be easier to
revise even an off-the-mark strategy than to start from scratch when the goals
finally coalesce. As we go forward, we should also keep in mind goals that we
don't yet fully understand or know how to achieve are OK; no doubt they are
where the greater share of our inspiration comes from.

In subsequent sections, we sketch a strategic plan for a fairly moderate and
bland set of goals. As the questions and issues mentioned in the current
section get hashed out and better understood, the plan can be revised
accordingly.
