#+STARTUP: showeverything logdone
#+options: num:nil

Regardless of how it works in the rest of the world, it seems that
question-asking is a vital part of online "education" (or learning
more generally).  A student who doesn't ask questions online seems
more likely to have a low "interactivity index".  The only other way
would be if they were talking a lot - which is probably a decent
way to learn, since it often leads to discussions, from which everyone
learns.  Still, asking questions is a good thing.  In the words
of a famous video game console: "question everything".

My question is: are students being taught not to ask questions?  It
almost seemed that way in some of my classes, particularly the lecture
classes.  Questions tend to derail lectures; and although they can be
answered "offline", such a dynamic makes it so that other class
participants often don't hear the answer.  Since they didn't ask,
that could be OK.  (I remember one lecture class I took, one of the
students would ask very basic questions and it began to get on
the professor's nerves, and maybe everyone else's too.)  On the other
hand, in a sufficiently sophisticated online environment, students
come and go as they please, and can listen or not listen at will.

All in all, I think anyone who is new to /this wiki/ should probably
start by asking a half-dozen questions (or more)....

--[[file:jcorneli.org][jcorneli]]

I think students not asking questions is almost entirely a by-product
of the "mass production" of the formal education setting.  Questions
are a natural part of the learner "synching" their own understanding 
up with that of the teacher's.   When you have thirty students who
all need to do this, but only one teacher, there is massive contention.
To keep things moving, the questions are kept as "representative" as
possible, when they are not outright eliminated.  But this is so
"successful" that pretty much everyone hates lectures, if they dont hate
formal education entirely. --[[file:akrowne.org][akrowne]] Thu Jul 14 05:43:11 UTC 2005

There are social factors like students being embarassed to ask questions because they do not want to take the chance of looking stupid in front of the class.  Conversely, there are also students who ask certain kinds of questions to show off how smart they are.  As I know from experience teaching, it is a delicate business to set up a classroom environment in which the questions are appropriate (as opposed to no questions or lots of very basic questions or show-off questions).

One thing that seems to help (at least it worked for me) is to explicitly encourage students to ask questions and to ask the students questions.

While not having students ask questions certainly fits well with a mass production approach to education, I would think that the practise predates the current era of mass production.  What I have in mind is the traditional society where teachers are seen in an exalted role as wise elders and students are supposed to sit quietly at their masters' feet soaking in and memorizing what they are told.  In such a setting, interupting a lecture to ask questions would be seen as insulting.  To be sure, in such a traditional setting, there would likely be occasions for students to ask their teachers questions, but it would likely not be during the lecture.  While the old ways have have passed away, the institution of the question-free lecture hall was retained as useful to the new ways of mass-produced education.  More generally, I would say that the whole attitude of students as passive made a smooth tradition form the old state of affairs to the new.  Of course, this doesn't really contradict what you have to say about the reason why things are as they are nowadays; rather I am trying to point out that it may not so much have been a matter of silencing questions as propagating a state of affairs which suited the new conditions. --[[file:rspuzio.org][rspuzio]] 14 July 2005

Ray, all true, for sure =) --[[file:akrowne.org][akrowne]] Thu Jul 14 06:51:25 UTC 2005
