#+STARTUP: showeverything logdone
#+options: num:nil

(((Ok, Christoph is not /yet/ Herr Doktor Lange...but
that day will come, and then this posting will be 100%
accurate!)))

---

To:	project-omdoc@jacobs-university.de, project-mathweb@jacobs-university.de, "OpenMath" <om@openmath.org>
From:	"Christoph LANGE" <ch.lange@jacobs-university.de>  Add to Address BookAdd to Address Book  Add Mobile Alert
Date:	Sat, 31 May 2008 00:47:33 +0100
Subject:	[MathWeb] Survey on issues in a math knowledge base: please participate!

Dear "mathematical knowledge managers",

  I'd like to invite you to participate in my little survey on
 mathematical
knowledge items, possible issues with them, and how to solve issues:

http://tinyurl.com/5qdetd

It will take around 10 minutes to answer the questions.

The results will be used in order to improve the mathematical
 argumentation
ontology that is used in my semantic wiki SWiM
(http://kwarc.info/projects/swim/) and thus the assistance in tracking
 and
solving issues there.

Please see
https://svn.kwarc.info/repos/swim/doc/scoop08/semwiki-discussions.pdf
(submitted to the JEM seminar on scientific communities of
 practice/SCooP) for
background information.

Thanks in advance,

Christoph

-- 
Christoph Lange, Jacobs Univ. Bremen, http://kwarc.info/clange, Skype
 duke4701
