#+STARTUP: showeverything logdone
#+options: num:nil

** Summarry

Copyright law has a provision which allows authors to abritrarily declare any copyright license on their works null and void.  To be sure, there are restrictions on when this can be done and a procedure to be followed --- one can't simply release a work under some license one day and then change one's mind the next day and undo the license.  Rather, the author has to wait 30 years and has only can exercise this prerogative before the 35th year.  (In the case of works before 1978, the dated are somewhat different) Also, the author has to file a notice of intent to do so with the copyright office at least two years in advance.

In the case that the author dies before having a chance to terminate a transfer, a by survivng spouse, children, or grandchildren can terminate copyright transfers instead.  There is no way an author can give up this right to reneg on copyright licenses.  The only case where it the law does not allow a trasfer to be terminated was when that transfer was made in a will or if the work in question is a work for hire.

** Bibliography

U.S. Code, Title 17, Chapter 2, section 203 
http://www.copyright.gov/title17/92chap2.html#203

P.S. Menell and D.Nimmer. Defusing the Termination of Transfers Time Bomb http://www.idc.ac.il/ipatwork/PUBLICATION/Defusing.pdf

Lloyd J. Jassin.  COPYRIGHT TERMINATION:
HOW AUTHORS (AND THEIR HEIRS) CAN
RECAPTURE THEIR PRE-1978 COPYRIGHTS
http://copylaw.com/new_articles/copyterm.html

IVAN HOFFMAN. TERMINATIONS OF TRANSFERS 
http://www.ivanhoffman.com/termination.html

William Patry.   Winnie the Pooh and Copyright Too.
The Patry Copyright Blog 
http://williampatry.blogspot.com/2005/07/winnie-pooh-and-copyright-too.html
