#+STARTUP: showeverything logdone
#+options: num:nil

 *Examples of Hyperlinks to Businesses by Tax-Exempt Organizations*

Below are 10 examples of tax-exempt non-profit organizations whose websites
include hyperlinks to sites of for-profit businesses.  In many cases their
websites also not only reproduce trademarks of the companies to which they link, but even appear to promote for-profit businesses alongside their non-profit conterparts.

Given these examples, it would seem that the practice of linking to the websites of corporate benefactors is common among the some of the most reputable non-profit organizations.  Therefore, it is difficult to believe the statement "As an exempt organization you may not have an Internet link for the
organizations making a corporate sponsorship contribution on the organizations
website." (6.c.2 in the enclosure to the letter of 25 February 2005) If there is such an absolute prohibition in force, then it would seem that such pillars of the non-profit community as the Red Cross and Little League stand /in flagrante delicto/ and risk having their non-profit status revoked.

In order to demonstrate that the organizations behind the websites are
legitimate, I have provided their adresses.  In order to verify tax-exempt
status, I have included their EIN numbers and information on their tax-exempt
status as given in the [http://www.guidestar.org/ Guide Star] database of Philanthropic Research, Inc.

[[file:rspuzio | Raymond S. Puzio.org][rspuzio | Raymond S. Puzio]] 7 March 2005

1. <u>American Red Cross</u>

While most of the links on this page are to informational pages about companies and their fundraising activities, some are purely commerical.  When I clikced on the "Best Buy" and "Target", and Wal-mart trademarks, I saw pages of adveertised specials.  When I clicked on the Kodak trademark I saw an advertisement for their newest camera.  When I clicked on the Federal express trademark, I landed on a page for sending packages and when I clicked on the Visa link I was greeted with an offer to buy a credit card.

http://www.redcross.org/sponsors/irf/tre2005-recognition.html

Note that not only do they provide a link to their sponsor's website here, they also reproduce a Maglite advertisement:

http://www.redcross.org/sponsors/howtohelp/partnering.html

American National Red Cross

2025 E St NW

Washington, DC 20006 

EIN: 53-0196605

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity.

2. <u>Habitat for Humanity</u>

http://www.habitat.org/CP/cp_part.html
        ww.habitat.org/CP/cp_part.html

Habitat for Humanity International, Inc.

121 Habitat St

Americus, GA 31709 

EIN: 91-1914868

This organization is not required to file an annual return with the IRS because its income is less than $25,000. It is a 501(c)(03) public charity.

3. <u>First Book</u>

Notice that the link to Google is in fact a link to the Google search engine and the text next to that link is essentially advertising text for Google --- mention of Google as a corporate partner and donor does not occur until the second paragraph.  This completely violates what was said in the letter of 25 February regarding corporate sponsorship, advertising, private benefits, and linking.

http://www.firstbook.org/partners/

http://www.firstbook.org/cause/

First Book

1319 F St NW

Ste 1000

Washington, DC 20004

EIN: 52-1779606

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity.

4. <u>Community Health Charities</u>

http://www.healthcharities.org/homepage2731/

Community Health Charities

200 N Glebe Rd 801

Arlington, VA 22203 

EIN: 52-1476848

This organization files a group return with the IRS. It is a 501(c)(03) public charity

5. <u>Special Olympics</u>

http://www.specialolympics.org/Special+Olympics+Public+Website/English/Support/Meet_our_Corporate_Sponsors/default.htm

Special Olympics, Inc.

1133 19th St, N.W.

Washington, DC 20036 

EIN: 52-0889518

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity.

6. <u>United Cerebral Palsy</u>

http://www.ucp.org/ucp_general.cfm/1/6

Note that if you click on the corporate logo on the following page, you arrive at a commercial website for readers 21 years of age and older.

http://www.ucp.org/ucp_generaldoc.cfm/1/6/6/6-6/208

United Cerebral Palsy (UCP National)

1660 L Street, NW, Suite 700,

Washington, DC 20036

EIN: 13-1641079

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity.

7. <u>Little League</u>

Under "Capri Sun" and "Choice Hotels" entries there are advertisements of special offers exclusively for people associated with Little League.  The "Choice Hotels" entry includes such details as special codes and phone numbers which viewers of this web page can use to get discounts on hotel rooms!  I would be very interested to know exactly how such a special offer for viewers of a website does not constitute a preferential referral service.  Under the Sunkist and Upper deck entries, there are descriptions of sweepstakes and links to websites where one can enter these sweepstakes.

http://www.littleleague.org/sponsors/index.asp

Little League International Baseball and Softball

539 US Route 15 Hwy

P.O. Box 3485

EIN: 23-6296634

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity.

Williamsport, PA 17701-0485

8. <u>Arbor Day Foundation</u>

http://www.arborday.org/join/partnerships.cfm

The National Arbor Day Foundation

100 Arbor Avenue 

Nebraska City, NE  68410 

EIN: 23-7169265

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity. 

9. <u>Human Rights Campaign</u>

Note that the IBM link goes to a special advertising page "Featured offers for GLBT business community" targeted to a group of people who are likely to support and benefit from the Human Rights Campaign.  

Next to the text "Volvo for life" there is a special coupon and the link points to an advertisement for a car on the Volvo website.

Next to the "Washington Mutual Home Loans" link, there is a special offer by the bank of a special discount rate on home loans for members of HRC.  Also, this advertisement comes with a special telephone number which one can call to apply for a loan at this rate.  The link points to a page on the bank's website which says "customized interest rates  and discounts just for you" which is only accessible through the non-profit website and even displays the non-profit organization's trademark prominently.

How come does this not constitute a case of preferential treatment and a private benefit for these companies insofar as it targets a particular class of potential customers?  Remember, these links occur on the corporate sponsors page, not as advertisements put up for the purpose of supplemental income.

http://www.hrc.org/Content/NavigationMenu/HRC/Get_Involved/HRC_Sponsors/Corporate_Sponsors/National_Corporate_Sponsors.htm

Human Rights Campaign Foundation

1640 Rhode Island Ave NW

WASHINGTON , DC 20036 

EIN: 52-1481896

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity.

10. <u>Mothers Aggainst Drunk Driving</u>

http://www.madd.org/aboutus/0,1056,1986,00.html

Even though this page only links to their pages on the website, if you follow the links, you get to pages about individual companies which link to those companies websistes (and even explicitly say that the links will leave the MADD site).  For instance, look at the following page:

http://www.madd.org/aboutus/1,1056,9396,00.html

Even more interesting is the following page which links to a law firm which represents victims of drunk drivers.  The page to which it links prominently displays a toll-free number to talk to an attorney on the top of the page.  Given that people who visit the MADD website are more likely than average members of the population to be interested in the services of an attorney with experience representing accident victims, how does this link not violate the principles stated in section 6.c.2, 6.d.1, and 6.d.2 of the letter of 25 February?

http://www.madd.org/aboutus/1,1056,8021,00.html

Mothers Against Drunk Driving

511 E John Carpenter Fwy

Ste 700

Irving, TX 75062 

EIN: 94-2707273

This organization files an IRS Form 990 or 990-EZ. It is a 501(c)(03) public charity.

<u>Conclusions</u>

After considering these facts, it apperars to me that one can draw one of two conclusions with respect to the interpretation of the internal revenue code presented in the letter.  Both are equally disturbing because they imply either wrongdoing or unfair play.

 1.  Open disregard of the law with respect to hyperlinks is widespread in the non-profit sector.  Even the insinuation of such misconduct would seem to me rather shocking, if not unthinkable, in light of the fact that the organizations accused of these improprities are not fly-by-night operations of questionable character, but well-known charities of the highest reputation and character with long histories of devotion to the betterment of the community whose names are virtually synonymous with service over self.

 1.  If the practices documented above are in accordance with the law, then the interpretation presented in the letter cannot stand.  If so, then the understanding of the law on this point with respect to how these organization can recognize and work with their sponsors has been rather different than the stance on hyperlinking taken in the letter.  This too is troubling, because it suggests incompetence or selective enforcement of the law.

Back to [[file:501(c)3 Saga.org][501(c)3 Saga]]

[[file:Comments on Thanks to our corporate sponsors.org][Comments on Thanks to our corporate sponsors]]
