#+STARTUP: showeverything logdone
#+options: num:nil

It sounds loopy and sort of generic, but the idea is: that "reality"
often itself plays the role of fiction.  A key class of examples is:
what goes on when people say something is "more real" than something
else -- or when they say something is "unrealistic".

Disneyland is not any more or less real than a small town.  But you
could easily find people who would say it is "more real" (in the sense
of being hyperreal) or that it is "less real" (in the sense of being
superficial).

Similarly, the ghetto doesn't contain anything "more real" than the
condominium complex -- but it is common enough for people to imagine
that poor people, and especially poor black people, have some special
handle on "reality" and "authenticity" that is lacking in their richer
and paler contemporaries.

(By the way, "black" and "white" are both obvious fictions, but other
than acknowledging that fact, I am going to use these words the way
they are usually used in polite conversation.)

The fiction of a hightened "reality" of black experience (and other
similar essentializing fictions) will almost without a doubt be used
to oppress the groups and individuals who may at first appear to be
receiving praise.

And to me, the idea that this or that way of being is "more real"
sounds so suspicious, that I can imagine it forming an important part
of the basis of oppressive systems in many cases.  Perhaps percieved
"authenticity" is taken as a green light for exploitation or control?

Here is an example from my own experience.

I think fell prey to the "reality fiction" when I was at the
University of Texas.  At the time I was an experiencing an inner
conflict over what seemed to be a fundamental disagreement between me
and the authorities as to the nature of my "real goal" in grad school.

I thought the "real goal" was to further mathematics, and it seemed to
me that they thought that the "real goal" was for me to complete the
program.  It reduced to a matter of approach, and the approaches
conflicted with each other over how "deep", how "pressing", and
especially how "measurable" they were.

In hindsight, it is fairly clear that on these terms, the system would
inevitably "win" -- since there were no adequate pathways for
measuring the "reality" of my goal-set, or my progress towards it,
within the system's rubric.

If I had known then what I've spelled out in this essay, then I would
have been sure to distrust *anything* described as a "real goal".
What matters more is the complex of perceived or imagined
relationships -- which is to say: what matters more than "reality" is
the slew of honest fictions describing hopes, dreams, elusive goals,
and the other questionable data of mental experience.  I would have
known that instead of trying to obtain the semantic high-ground by
touting the "reality" of my experience, instead I could have humbly
sought a receptive audience for my fictions.  No one wanted to hear me
going on about how my experience was "more real" -- because that is
certainly very dull -- but I could have shared other more entertaining
stories and ideas, had I only thought to go out onto the limb of
fantasy, instead of hugging the trunk of my so-called real (or even,
as I put it tentatively then, "hyperreal") experience.

Indeed, I think that by claiming that what I was doing was "more real"
than what the other students in the program were doing, I ended up
"ghettoizing myself".  And this was probably not a strong choice.

--[[file:jcorneli.org][jcorneli]], May 14, 2007
