#+STARTUP: showeverything logdone
#+options: num:nil

: "We live in a universe of new media with phenomenal opportunities
for worldwide communications and research, but populated by volunteer
vandals with poison-pen intellects." -- John Seigenthaler Sr., NYT
Dec. 4, '05

Such a fine choice of words!  Oh, how nice it would be to be able
to say such deliciously defaming things -- about myself, or
about my whole class of internet-using peers!

And what makes it even better is that maybe he's right.
He was after all the editor of a newspaper.  

Poison is an interesting thing (as Paul and Dargelos from "Les Enfants
Terrible" could remind you).  But my personal experience with poison
is fairly limited, specifically, there is Ratpoison, that most
excellent window manager.  Down with the rodent!

Down with the rodent and down with the Yellow Plague!  Down with
pencils and down with books!  Down with The Tennessean and down with
the New York Times!

Up with vandals and hacks!  Up with knowledge and truth!  Up with new
media and intellects of all sorts, poisonous and otherwise!

--[[file:jcorneli.org][jcorneli]]

Once again a crusty Old Media figure hopes that no one will notice that
all knowledge is provisional and that even Old Media makes mistakes.  Of course,
for Siegenthaler, its more personal than for someone like McHenry.  

The specifics are worth mentioning.  What is 
glossed over in Seigenthaler's complaints of the article sitting for "132 days" with
the false information is that it /wasn't linked to any other articles/.  Thus, it
probably wasn't being viewed much, and certainly doesn't represent a failure of
CBPP vetting effects.

I do, however, think Wikipedia's shrinking "anonymous" capabilities are a good thing.
Since they are only requiring accounts, anonymity in the classical sense is still
available, but edits without some form of persistant identity (and therefore responsibility
are not).

--[[file:akrowne.org][akrowne]] Tue Dec 6 05:16:13 UTC 2005

Note that the NYT really might be considered to be "new media" in some ways.
It has become fairly high-tech (the website version at least); and you
get some collaborative effects like
"The 25 most frequently emailed articles in the last 24 hours".
(or so I've heard).  Many people find the NYT very useful and interesting.
So I feel sort of bad knocking it, even in play.  --[[file:jcorneli.org][jcorneli]]

----
Note: see [[file:tragical comedy intermission.org][tragical comedy intermission]] for some further discussion and relationships
to other CBPP issues.

----

Regarding the current retraction of fraudulent stem cell cloning results, the following 
quote struck me:

: When a paper is retracted, a notice appears in Science's letters
section, but an online link to the original article is kept, she
said. In the past eight years, 30 to 40 papers have been retracted after
being published in the journal.  

Egads!  30-40 articles?! In /Science/?!  I don't know anything about the relative badness
of this quantity, but this sounds much worse to me than tiny insignificant parts
of Wikipedia being wrong.   If I were to look at this controversy with the same
alarmist mindset as Wikipedia's critics, I might think "this whole a priori 
peer-review publication thing is crap!  We need to throw it out and find 
something *guaranteed* trustworthy!"

But of course, that'd be dumb.  Pre-hoc peer review as in traditional publication is clearly 
not perfect, but it does have its utility.  Similarly, Wikipedia (and PlanetMath) have 
different, but just as important, utility, with their post hoc form of review.

(The cloning article is here: http://www.post-gazette.com/pg/05350/623383.stm, not that
this is necessarily the best article on this controversy...)

--[[file:akrowne.org][akrowne]] Fri Dec 16 06:29:05 UTC 2005

The recent Wikipedia "controversy" is bogus.  The Wikipedia naysayers
are attempting to apply a standard that is not met by conventional
scientific and scholarly publications.  Are conventional publications
free of errors?  No!  That is why we have errata and revised editions.
Are conventional publications "authoritative".  Only up to a point.  A
measure of debate and controversy is a good thing.  Scientific
revolutions are all about overturning established concensus.  The
standard for journalistic and non-academic publication is even lower.
People print intentional distortions and diatribes, and its all
business as usual.  Wikipedia is "vulnerable" because it replaces the
conventional authority-based quality mechanism with a mechanism that
is based on the participation of a large numbers of peers.

Really, there is a continuum of possibilities.  Ideally, a knowledge
project benefits from a large number of participants whose
qualifications are as high as possible.  Practical considerations
place these two measures in an inversely proportional relationship.
Wikipedia is operating in a different area of parameter space from
Britannica.  It would be interesting to compare the two modalities and
study their differences.  That's not the journalists' goal.  They just
want a juicy story.

--[[file:rmilson.org][rmilson]] Sat Dec 17 


/The Wikipedia naysayers are attempting to apply a standard that is
not met by conventional scientific and scholarly publications./

Similarly, I'd also hope that the Wikipedia yea-sayers are trying to
/set/ such a standard! ;)  

I think that a discussion of what is "good" and "bad" in Wikipedia and
in other media is something that should happen.  But I also think that
it risks missing a very important point.  This point is that we should
be somewhat detached.  I think Robert's comment on the topic of
comparing Britannica and Wikipedia in an objective fashion is an
example of thinking in this detached way and I commend that.

One thing to remember is that media are consumed as well as produced.
This fact can be forgotten by professional journalists, who'll curse
Wikipedia to high heaven without changing the fact that lots of people
find it useful!

Wikipedia certainly has weaknesses, and I could point out some
half-dozen of them on demand.  (I doubt whether the journalists will
have comments that are half as useful as the comments of users and
contributors!)  Our mission (should we choose to accept it) is to
either build something better than what we have currently or to make
the best of what we've got, or maybe even better, try for a blend of both.

The "perceived quality" of resources like Wikipedia certainly matters,
but I wouldn't turn to the journalists here either.  Rather, perceived
quality should be measured by user studies.

The nay-saying may give Wikipedia some bad publicity (and maybe even a
bad name in some circles), but on the other hand, a high-quality
resource will without doubt speak for itself to some extent.  Let's
keep that in mind as a potential goal! --[[file:jcorneli.org][jcorneli]]
