#+STARTUP: showeverything logdone
#+options: num:nil

What, if anything, is special about mathematics?  Perhaps mathematics
lays exclusive claim to a certain class of questions and answers?

Are Vincent van Gogh's paintings of sunflowers beautiful?  As much as
we may want to say "yes", in all fairness, we must admit that this
is, in some sense, a subjective view.

Was Vincent van Gogh born in 1853?  The answer here is "yes"
(although it could be "no" or "I don't know"), but there is no
 *reason* for this other than the vicissitudes of fate.

Is $2008 - 1853 = 155$?  The *correct* answer is "yes".  Like
the previous question, the correct answer depends on knowledge, but
this time, there is not just a reason for the answer to be correct (or
not) -- this time, we feel there is a reason for the answer  itself*.

The first question is a matter of opinion.  It might be made the
subject of a scientific investigation, but as such, it has no correct
answer.  The second question is a matter of factual knowledge -- data
about the real world.  You may have to check a few sources to be sure
of the fact, but you can't figure it abstractly.  The third question
is one of procedural knowledge.  Anyone who has learned how to
subtract integers can figure out the answer.

If, as we've heard, "knowledge is power", then surely procedural
knowledge carries more power than factual knowledge: facts alone don't
do anything.  Procedural knowledge alone may not convey the ability to
do: the circumstances must be right.  But it is a good start.
