#+STARTUP: showeverything logdone
#+options: num:nil

Well, there are a lot of things, right?  But two that I've
been emphasizing when I talk to people are: facilities for
doing collaborative open research; and facilities for
doing collaborative open curriculum development.
Right now some of the best support for these ends are in
the "collaborations" facility for PM, of course.

However, there is much more that PM can offer or contribute to,
e.g, HDM.  The question for me right now is how to pitch
the project/organization/site/etc., which will presumably
be differ as we move around in potential-sponsor space.

--[[file:jcorneli.org][jcorneli]]

Based on various discussions in and around PM, I am beginnning to
think of these issues under several broader headings, which may be
labelled with variations on the title of this page.

[[file:What PlanetMath can offer to Students and Teachers.org][What PlanetMath can offer to Students and Teachers]]

[[file:What PlanetMath can offer to Shoppers.org][What PlanetMath can offer to Shoppers]]

[[file:What PlanetMath can offer to Researchers.org][What PlanetMath can offer to Researchers]]

--[[file:rspuzio.org][rspuzio]]
