#+STARTUP: showeverything logdone
#+options: num:nil

If I was to feel hopeful about the revolutionary potential of HDM,
which sometimes I do, then I think it would through a confident feeling
about HDM's role in bringing about a new era of Simulationism (which
is like Situationism, but interestingly enough done with computers).

It got the name "Hyperreal Dictionary of Mathematics" because of its
association with some of the core philosophy of this movement.
(Baudrillard perhaps playing a role for this theory something like
that played by Rousseau or Smith for things like socialism and
capitialism.)

Lately I have been interested by (and sort of alarmed by) Kurzweil's
new book, its ideas, and its popularity.  (I haven't actually read the
book yet, although I took a quick look at it; and my mom is reading
it, so I know something about what it is about; besides, I've read the
[http://en.wikipedia.org/wiki/The_Singularity_is_Near summary on Wikipedia].)

What alarms me about this book is the idea that "acceleration" may
lead many people to want to free-ride.  (Of course, the Situationists
might have been partially OK with that; since, they envision a future
in which everyone can freeride to some extent.  Still, I think through
their "totalizing" vision, they would tend to recognize that it might
be a lot of work to bring that happy state about, and they would want
to see people working, or at least playing, towards this goal.  It is
unclear to me.)

What also alarms me is the fact that these AI visionaries don't seem
to be thinking about Mathematics at all.  They do seem to be thinking
about things like AI for Science, which is close, but also quite
different.

If like Kurzweil says, AI is a virtual inevitability (and relatively
soon, too), then one might hope that one would be able to assume that
Mathematics would be captured in the "totalizing drift".  But when,
and by whom?  (And can we really make this assumption?)

For me, HDM seems like the A#1 next step in a Simulationist programme
(or movement or whatever), falling nicely into place right in line
after GNU and Wikipedia.  I have a hard time conceptualizing anything
I'd call AI outside of the context of a scholium system like
[[file:Arxana.org][Arxana]].  I also might question the usefulness/validity/worth of an
AI system that didn't take the "right" role on user freedom and social
contracts.

After all, if the "society of the (future) mind" is the contemporary
human society... well, it would seem we have a lot to learn.

Kurzweil may do just fine at predicting revolutions & their frequency,
but I think we want to do better.  (Ted Nelson did a great job
sketching Xanadu, but hasn't yet made it into the popular system he
was hoping it would become.  Incidentally, that would, I suppose, be
another approach besides writing a manifesto - write a semi-popular
/book/.  Cf. [[file:Why I am frustrated by the idea of writing an HDM Manifesto.org][Why I am frustrated by the idea of writing an HDM Manifesto]].)

We want to actually make this particular revolution happen.

But I don't think it is "just" a revolution in Mathematics or "math
culture" we're talking about.  We might focus on that part of it.  But
the various writing on the scholium system seem to indicate that the
revolution is much broader -- "total", maybe.

My hunch is that Kurzweil's revolutions won't be feasible without
something like the revolution in mathematics we've been talking about
happening first.  Maybe I'm wrong about that.  The logic isn't
completely tight, admittedly.  One could build any number of other
sorts of AI systems.  

But as I indicated above, I think these other systems could have some
serious flaws, both social and logical.  Would you trust a computer
that hadn't been proved accurate /with your mind/?  Trust can only
go so far... so if the computer says that it is trustworthy, should
you believe it?  Our mill-race metaphor describes how one might be
able to "ramp up" to understanding even a very large and complex
proof.

I don't think we should get so caught up with these future revolutions
that we lose sight of contemporary reality.  We can preach and
prosthelytize all we want, but someone is eventually going to have to
do the work, or it won't happen.

I do think that pitching the HDM as a /key step/ in an overall
Simulationist program may be a good idea, and a way to get popular
support (if we /want/ popular support), or at least, maybe, the
support of AI fans.

* Discussion

George Orwell neglected to this one in "1984": /[http://terranova.blogs.com/terra_nova/2004/01/the_value_of_re.html fake is real]/. --[[file:jcorneli.org][jcorneli]]

----
[[file:The HDM Manifesto.org][The HDM Manifesto]]
